### ISSUE TITLE
bug in signed_distance.cpp:117-119

### ISSUE THREAD

**Issue by kalov** [libigl/libigl#100]
The line libigl/include/igl/signed_distance.cpp:118 triggers an Eigen exception:

../libigl/external/nanogui/ext/eigen/Eigen/src/Core/PlainObjectBase.h:241: void Eigen::PlainObjectBase<Derived>::resize(Eigen::PlainObjectBase<Derived>::Index, Eigen::PlainObjectBase<Derived>::Index) [with Derived = Eigen::Matrix<double, 1, 2>; Eigen::PlainObjectBase<Derived>::Index = long int]: Assertion `(!(RowsAtCompileTime!=Dynamic) || (nbRows==RowsAtCompileTime)) && (!(ColsAtCompileTime!=Dynamic) || (nbCols==ColsAtCompileTime)) && (!(RowsAtCompileTime==Dynamic && MaxRowsAtCompileTime!=Dynamic) || (nbRows<=MaxRowsAtCompileTime)) && (!(ColsAtCompileTime==Dynamic && MaxColsAtCompileTime!=Dynamic) || (nbCols<=MaxColsAtCompileTime)) && nbRows>=0 && nbCols>=0 && "Invalid sizes when resizing a matrix or array."' failed.

The reason is that q is either 2D or 3D vector.
    const RowVectorXd q = P.row(p);
    RowVector3d q3 = q;
    RowVector2d q2 = q; // in case of a 3D vector, Eigen throws an exception here. you need a condition that checks dim.

**Comment by alecjacobson** [comment]
fixed in 81a3adb56106a7d20bd9a32ddb43edaec03bd0c8
