### ISSUE TITLE
Anisotropic Remeshing

### ISSUE THREAD

**Issue by alessandrofasse** [libigl/libigl#1000]
Dear libigl community,

i am currently working with your excellent libary and are now stucked with the problem of remeshing a mesh in order to produce a "nice" mesh. I found in the tutorial about anisotropic remeshing how I don't get what is happening in the example file 

https://github.com/libigl/libigl/blob/master/tutorial/506_FrameField/main.cpp

Furthermore, you explain in the tutorial that one can also apply some field constraints and so forth. This is some that (I think) I dont need. I want to simply remesh a given mesh with respect to its curvature (as in the last picture of the tutorial). 

Which rountines do I need in order to achieve this? I.e. how can I write a function link

`quad_remesh(MatrixXd const & vertices, MatrixXi const & faces`, MatrixXd & new_vertices, MatrixXi & new_faces, ... ) `

wher with the ... I mean that there also have to be added some further parameter that define the accuracy of the quad-remeshing.

Many thanks in advance!

**Comment by fwilliams** [comment]
[Instant Meshes](https://github.com/wjakob/instant-meshes) is also a great options for quad remeshing. There's a GUI and you can call it from the command line in batch mode. You may have to do a bit of work to call it directly from a function but I think it should be pretty easy to set up.

**Comment by AlessandroFasse** [comment]
@fwilliams many thanks for your recommendation! The tool is awesome! I tried it with some meshes and it is exactlly what I am looking for! I also had a quick look at the code and that also looks very good. However, do you know of some documentation if how I have to perform the certains tasks and in which order? Or, do I have to try to extract it from the GUI files?
