### ISSUE TITLE
Floating point error signals

### ISSUE THREAD

**Issue by copyme** [libigl/libigl#1002]
Discovered with #1001

```
bbw: decimated_knight
-------------------------------------------------------------------------------
/home/kacper/Projects/libigl/tests/include/igl/bbw.cpp:8
...............................................................................

/home/kacper/Projects/libigl/tests/include/igl/bbw.cpp:8: FAILED:
due to a fatal error condition:
  SIGFPE - Floating point error signal

===============================================================================
test cases:  5 |  4 passed | 1 failed
assertions: 28 | 27 passed | 1 failed


Process finished with exit code 136 (interrupted by signal 8: SIGFPE)
```

```
qslim: cylinder
-------------------------------------------------------------------------------
/home/kacper/Projects/libigl/tests/include/igl/qslim.cpp:9
...............................................................................

/home/kacper/Projects/libigl/tests/include/igl/qslim.cpp:9: FAILED:
due to a fatal error condition:
  SIGFPE - Floating point error signal

===============================================================================
test cases:      52 |      51 passed | 1 failed
assertions: 3017577 | 3017576 passed | 1 failed


Process finished with exit code 136 (interrupted by signal 8: SIGFPE)
```

**Comment by copyme** [comment]
Another one

```
-------------------------------------------------------------------------------
EmbreeIntersector: cube
-------------------------------------------------------------------------------
/home/kacper/Projects/libigl/tests/include/igl/embree/EmbreeIntersector.cpp:4
...............................................................................

/home/kacper/Projects/libigl/tests/include/igl/embree/EmbreeIntersector.cpp:4: FAILED:
due to a fatal error condition:
  SIGFPE - Floating point error signal

===============================================================================
test cases:  4 |  3 passed | 1 failed
assertions: 22 | 21 passed | 1 failed


Process finished with exit code 136 (interrupted by signal 8: SIGFPE)
```

**Comment by copyme** [comment]
Ok the last one was reported to embree (see [#220](https://github.com/embree/embree/issues/220))

**Comment by copyme** [comment]
So, I propose that tfar will not be set to inf be `intersectRay` (`EmbreeIntersector.h`).

**Comment by jdumas** [comment]
I'm sorry I'm not sure this one is really a problem. Sure 0*inf produces a nan, but that's normal no? Are the results used in any way in libigl when this is the case? You could argue that for speed, it's better to avoid `nan` and `inf` for example. But if one sets the value of `tfar` to `std::numeric_limits<double>::max()` (for example), then it gets multiplied by something and the result will overflow (or will it be set to `inf`?).

**Comment by copyme** [comment]
@jdumas You are right that this is expected but IMHO comparisons against nan values should be always avoided. Well, this `nan` will occur internally in embree: `valid &= (T^sgnDen) <= absDen*vfloat<M>` where the right side may contain `nan`s.

**Comment by copyme** [comment]
@jdumas Yes, setting the variable to std::numeric_limits<double>::max() will not solve anything. We will then have type-overflow in absDen*vfloat<M>.

**Comment by jdumas** [comment]
Well I'd have to look at the code to see if there's an obvious way to deal with this on the libigl side, but it's rather low priority for me at the moment. Embree could add an `if` to have a special treatment for `inf` values of `tfar`, but there's a small overhead to this.
