### ISSUE TITLE
Cannot compile with CGAL and CGAL_WITH_GMPXX

### ISSUE THREAD

**Issue by copyme** [libigl/libigl#1004]
So the compilation crashes with these two options set.
```
/home/kacper/Projects/libigl/include/igl/copyleft/cgal/assign.cpp:21:20: error: no matching function for call to ‘assign_scalar(const CGAL::Lazy_exact_nt<CGAL::Gmpq>&, Eigen::DenseCoeffsBase<Eigen::Matrix<double, -1, 3>, 1>::Scalar&)’
       assign_scalar(C(i,j),D(i,j));
       ~~~~~~~~~~~~~^~~~~~~~~~~~~~~
```

**Comment by jdumas** [comment]
Is `CGAL_WITH_GMPXX` ON by default?

**Comment by copyme** [comment]
@jdumas I do not think so.

**Comment by jdumas** [comment]
Then it's to be expected that there are missing template instantiations since we do not capture them on the CI. Feel free to add those!

**Comment by alecjacobson** [comment]
Happy to merge these missing templates as a PR. Closing for now.
