### ISSUE TITLE
A question in 709_SLIM

### ISSUE THREAD

**Issue by seamanj** [libigl/libigl#1005]
[Hi, There.
I am a little confused with the mesh area calculation when it applies to DEFORM_3D.
igl::doublearea(V, F, data.M);
The above code computes the doubled area. However, when it comes to tetrahedra, I think it should be its volume, not just sum up the two triangle areas as it did in the code.
  template <typename Derivedl, typename DeriveddblA>
  IGL_INLINE void doublearea(
    const Eigen::MatrixBase<Derivedl> & l,
    Eigen::PlainObjectBase<DeriveddblA> & dblA);
  // DOUBLEAREA_QUAD computes twice the area for each input quadrilateral

Thanks in advance.
]

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [ x] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by jdumas** [comment]
Well if `F` represents a quad-mesh, this is the correct thing to do. There is `igl::volume` for calculating the volume of tetrahedra.

**Comment by seamanj** [comment]
> Well if `F` represents a quad-mesh, this is the correct thing to do. There is `igl::volume` for calculating the volume of tetrahedra.

thanks for your reply.
So, in the tutorial,  it uses "cube_40k.obj", whose 'F' has 4 indices. So I wonder each 'F' is a tetrahedra or a quad-mesh.

From the area computation's view, it seems to be a quad-mesh.
However, when I look into the 'grad' function, it is more likely to be a tetrahedra.


`
template <typename DerivedV, typename DerivedF>
IGL_INLINE void igl::grad(const Eigen::PlainObjectBase<DerivedV>&V,
                     const Eigen::PlainObjectBase<DerivedF>&F,
                    Eigen::SparseMatrix<typename DerivedV::Scalar> &G,
                    bool uniform)
{
  assert(F.cols() == 3 || F.cols() == 4);
  if (F.cols() == 3)
    return grad_tri(V,F,G,uniform);
  if (F.cols() == 4)
    return grad_tet(V,F,G,uniform);
}`

**Comment by jdumas** [comment]
Well `cube_40k.obj` is a obj file so it's either a triangle mesh or a quad mesh (obj is only for surface meshes). I agree that there's a bit of an ambiguity here, so you have to read the documentation of the functions to find out if they expect a surface/volume mesh, or can do both.

**Comment by seamanj** [comment]
thanks for your explain.

But I am still a little confused when I look into 'grad_tet', in which 'igl::volume(V,T,vol);' is used,

If we use a surface like 'cube_40k.obj', is it contradict to regard it as tetrahedra to compute gradient?

**Comment by jdumas** [comment]
Well I guess you can view a quad mesh as a tet-mesh too, but your tets will be mostly very flat...

**Comment by seamanj** [comment]
thank u very much.
