### ISSUE TITLE
Bug in geodesics code

### ISSUE THREAD

**Issue by ghost** [libigl/libigl#1013]
There appears to be a bug with the propagate step with the geodesics code used by libigl. Under certain circumstances, attemping to calculate exact geodesics will yield the message "Assertion failed: p->start() < p->stop()", and terminate the program. 

To reproduce: 
Load the attached mesh in libigl.
 Declare the parameters for the exact_geodesic function.
Set VS to a vector of size 1 with value 105.
Then call igl::exact_geodesic
    

>  igl::readOBJ("box1Holeremesh.obj", V, F);
>      Eigen::VectorXi VS, FS, VT, FT;
>      VS.resize(1); 
>      VS << 105;
>      VT.setLinSpaced(V.rows(), 0, V.rows() - 1);
>      Eigen::VectorXd d;
>      igl::exact_geodesic(V, F, VS, FS, VT, FT, d);
> 

I am certain that there are no problems with the geometry of the mesh. In addition, exact_geodesic works on vertices 0-104 without any issues. This error occurs in both the libigl version as well as the original version found here:
https://code.google.com/archive/p/geodesic/downloads

[box1Holeremesh.zip](https://github.com/libigl/libigl/files/2578235/box1Holeremesh.zip)

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [x] Linux

**Comment by jiangzhongshi** [comment]
Hi, 

I have been trying the same libigl code (debug build) on my Linux machine, but cannot seem to reproduce it. Can you verify it again, and what is the version you are using?

```
#include <igl/opengl/glfw/Viewer.h>
#include <igl/readOBJ.h>
#include <igl/exact_geodesic.h>

int main(int argc, char *argv[])
{
  Eigen::MatrixXd V;
  Eigen::MatrixXi F;
  igl::readOBJ("box1Holeremesh.obj", V, F);
  Eigen::VectorXi VS, FS, VT, FT;
  VS.resize(1);
  VS << 105;
  VT.setLinSpaced(V.rows(), 0, V.rows() - 1);
  Eigen::VectorXd d;
  igl::exact_geodesic(V, F, VS, FS, VT, FT, d);

  // Plot the mesh
  igl::opengl::glfw::Viewer viewer;
  viewer.data().set_mesh(V, F);
  viewer.data().set_colors(d);
  viewer.launch();
}
```

**Comment by RobertBelfer** [comment]
Hi,

I can confirm that I'm still getting the error on Windows with the release build. I can't seem to be able to run in in debug mode (getting the error "number of sections exceeded object file format limit : compile with /bigobj"). I'll try to see what happens with debug mode on Wednesday, and will get back to you.

I'm using the libigl master branch (downloaded on October 30th). I don't think any changes done to libigl since then would affect the exact geodesics code.

**Comment by alecjacobson** [comment]
I also can't reproduce this. Please reopen with more information if still an issue.
