### ISSUE TITLE
Simple mesh that crashes scaf example

### ISSUE THREAD

**Issue by FrankEscobar** [libigl/libigl#1015]
2D scaf works nice but crashes on some simple meshes like this.
Attached obj file.
[temp.zip](https://github.com/libigl/libigl/files/2579854/temp.zip)

Any idea on this?

**Comment by FrankEscobar** [comment]
As reference it crashes on 
`    uv_init = uv_init.topRows(V.rows());`

**Comment by jiangzhongshi** [comment]
Thanks for the report, I will probably check it over the weekend

**Comment by jiangzhongshi** [comment]
Hi Frank,

After looking at the model, I observed that this mesh contains many non-manifold vertices, so the initialization with Tutte's embedding will fail, so won't be taken as input for our method. 

If you have an example of a clean mesh that also fails, please let me know.

Best,
Zhongshi

**Comment by jiangzhongshi** [comment]
Hi Frank,

It's not vertex manifold. Yes, I agree that we should have a more thorough sanity check. Thanks!

**Comment by alecjacobson** [comment]
The general policy for libigl is to have preconditions on input well documented in the header and leave it to the caller to check on their end.

**Comment by jdumas** [comment]
Seems related to #987. That being said, if a condition is not met the function should gracefully return, not crash the program.

**Comment by FrankEscobar** [comment]
@jiangzhongshi vertex manifold? I've heard about edge not manifold, face not manifold but what vertex not manifold means? Not connected vertex?

**Comment by jdumas** [comment]
It means you have a vertex of the mesh where the local topology is not a disk (e.g. an extra triangle connected to the surface, or two components touching each other by a vertex).

**Comment by FrankEscobar** [comment]
btw probably it is my bad but I used "extract_manifold_patches" to break the mesh in patches but still my result meshes are non-vertex manifold, has this any sense for you?

**Comment by FrankEscobar** [comment]
> 
> 
> I think `extract_manifold_patch` only deals with edge manifoldness, and doesn't change `F` itself.
> 
> While vertex manifold may require duplicating vertices of interest and split them. I wonder if we have such functionality in libigl? @jdumas

it could be really nice to split meshes with that kind of problem.

**Comment by alecjacobson** [comment]
This would indeed be a cool feature to have. It's a bit tricky to do in a
way that doesn't introduce self-intersections, but that's not always
important. Sometimes just a combinatorial split is enough.

You might actually be able to use `unzip_corners` to do this.

**Comment by jdumas** [comment]
I have an implementation of Tarjan’s algorithm for detecting vertex bridges
in graphs, would that help? Would still need to do the coloring afterwards
though.
