### ISSUE TITLE
Question: Correct way to get Laplace Beltrami operator

### ISSUE THREAD

**Issue by chongkong** [libigl/libigl#1017]
I'm trying to get Laplace Beltrami operator L using `cotmatrix()`, but I'm not sure whether its return type is divided by vertex area or not.

In the implementation of `cotmatrix_entries`, cotangent is divided by `4*doublearea()`, which seems to be sort of a vertex area.

``` c++
{
  ...
  // cotangents and diagonal entries for element matrices
  // correctly divided by 4 (alec 2010)
  C.resize(m,3);
  for(int i = 0; i < m; i++) {
    C(i,0) = (l2(i,1) + l2(i,2) - l2(i,0))/dblA(i)/4.0;
    C(i,1) = (l2(i,2) + l2(i,0) - l2(i,1))/dblA(i)/4.0;
    C(i,2) = (l2(i,0) + l2(i,1) - l2(i,2))/dblA(i)/4.0;
  }
  break;
}
```

But in the docs, it describes the way to get Laplace Beltrami operator as:

``` c++
##include <igl/cotmatrix.h>
##include <igl/massmatrix.h>
##include <igl/invert_diag.h>
...
MatrixXd HN;
SparseMatrix<double> L,M,Minv;
igl::cotmatrix(V,F,L);
igl::massmatrix(V,F,igl::MASSMATRIX_TYPE_VORONOI,M);
igl::invert_diag(M,Minv);
HN = -Minv*(L*V);
H = HN.rowwise().norm(); //up to sign
```

I'd like to have my laplacian operator matrix to be divided by Voronoi vertex area. Do I need to follow the second case? or is `doublearea()` calculating vertex area on its own scheme and should not be 
divided by massmatrix further?

**Comment by jiangzhongshi** [comment]
In the first code snippet, `l2` is the length squared, so the expression divided by area will give cotangent angles, then in the second code snippet, it's divided by Voronoi area.

So please follow the implementation in the tutorial.

**Comment by chongkong** [comment]
Thank you!
