### ISSUE TITLE
Cmake error.

### ISSUE THREAD

**Issue by 40oz** [libigl/libigl#1018]
[Describe your issue]Hi, I am trying to cmake the whole files, but when I use cmakegui to configure, the errors come like this:

Looking for pthread.h
Looking for pthread.h - not found
Found Threads: TRUE  
Creating target: igl::core (igl)
CMake Error at C:/Users/Administrator/Desktop/cmake-3.13.0-rc1-win64-x64/share/cmake-3.13/Modules/ExternalProject.cmake:2329 (message):

  error: could not find git for clone of pybind11-download
Call Stack (most recent call first):
  C:/Users/Administrator/Desktop/cmake-3.13.0-rc1-win64-x64/share/cmake-3.13/Modules/ExternalProject.cmake:3105 (_ep_add_download_command)
  CMakeLists.txt:9 (ExternalProject_Add)

CMake Error at cmake/DownloadProject.cmake:171 (message):
  CMake step for pybind11 failed: 1
Call Stack (most recent call first):
  cmake/LibiglDownloadExternal.cmake:14 (download_project)
  cmake/LibiglDownloadExternal.cmake:98 (igl_download_project)
  cmake/libigl.cmake:182 (igl_download_pybind11)
  CMakeLists.txt:43 (include)

Configuring incomplete, errors occurred!
See also "D:/A_work_files/libiglnew/libigl/build/CMakeFiles/CMakeOutput.log".
See also "D:/A_work_files/libiglnew/libigl/build/CMakeFiles/CMakeError.log".

How can I fix this problem? Should I use gitbash rather than github desktop to clone? Thanks a lot!

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [ ] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by jdumas** [comment]
It looks like your cmake installation doesn't find an installation of `git`. Make sure git is installed and is in your PATH. The CMake documentation states that you need to have git version 1.6.5 or above installed for this.
