### ISSUE TITLE
CMake error on Ubuntu 18.04

### ISSUE THREAD

**Issue by gulib** [libigl/libigl#1019]
Hello,

I was trying to install newer version of libigl while faced the following error

```
CMake Error at .cache/eigen/eigen-download-prefix/src/eigen-download-stamp/download-eigen-download.cmake:159 (message):
  Each download failed!

    error: downloading 'http://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
           Trying 18.205.93.0...

  TCP_NODELAY set

  Connected to bitbucket.org (18.205.93.0) port 80 (#0)

  GET /eigen/eigen/get/3.2.10.tar.gz HTTP/1.1

  Host: bitbucket.org

  User-Agent: curl/7.58.0

  Accept: */*

  

  HTTP/1.1 301 Moved Permanently

  Content-Type: text/html

  Date: Mon, 19 Nov 2018 05:50:28 GMT

  Location: https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz

  Connection: Keep-Alive

  Content-Length: 0

  

  Connection #0 to host bitbucket.org left intact

  Issue another request to this URL:
  'https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz'

  Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         error: downloading 'http://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
           Trying 18.205.93.0...

  TCP_NODELAY set

  Connected to bitbucket.org (18.205.93.0) port 80 (#0)

  GET /eigen/eigen/get/3.2.10.tar.gz HTTP/1.1

  Host: bitbucket.org

  User-Agent: curl/7.58.0

  Accept: */*

  

  HTTP/1.1 301 Moved Permanently

  Content-Type: text/html

  Date: Mon, 19 Nov 2018 05:50:28 GMT

  Location: https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz

  Connection: Keep-Alive

  Content-Length: 0

  

  Connection #0 to host bitbucket.org left intact

  Issue another request to this URL:
  'https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz'

  Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         error: downloading 'http://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
           Trying 18.205.93.1...

  TCP_NODELAY set

  Connected to bitbucket.org (18.205.93.1) port 80 (#0)

  GET /eigen/eigen/get/3.2.10.tar.gz HTTP/1.1

  Host: bitbucket.org

  User-Agent: curl/7.58.0

  Accept: */*

  

  HTTP/1.1 301 Moved Permanently

  Content-Type: text/html

  Date: Mon, 19 Nov 2018 05:50:33 GMT

  Location: https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz

  Connection: Keep-Alive

  Content-Length: 0

  

  Connection #0 to host bitbucket.org left intact

  Issue another request to this URL:
  'https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz'

  Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         error: downloading 'http://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
           Trying 18.205.93.0...

  TCP_NODELAY set

  Connected to bitbucket.org (18.205.93.0) port 80 (#0)

  GET /eigen/eigen/get/3.2.10.tar.gz HTTP/1.1

  Host: bitbucket.org

  User-Agent: curl/7.58.0

  Accept: */*

  

  HTTP/1.1 301 Moved Permanently

  Content-Type: text/html

  Date: Mon, 19 Nov 2018 05:50:38 GMT

  Location: https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz

  Connection: Keep-Alive

  Content-Length: 0

  

  Connection #0 to host bitbucket.org left intact

  Issue another request to this URL:
  'https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz'

  Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         error: downloading 'http://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
           Trying 18.205.93.0...

  TCP_NODELAY set

  Connected to bitbucket.org (18.205.93.0) port 80 (#0)

  GET /eigen/eigen/get/3.2.10.tar.gz HTTP/1.1

  Host: bitbucket.org

  User-Agent: curl/7.58.0

  Accept: */*

  

  HTTP/1.1 301 Moved Permanently

  Content-Type: text/html

  Date: Mon, 19 Nov 2018 05:50:53 GMT

  Location: https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz

  Connection: Keep-Alive

  Content-Length: 0

  

  Connection #0 to host bitbucket.org left intact

  Issue another request to this URL:
  'https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz'

  Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         error: downloading 'http://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
           Trying 18.205.93.1...

  TCP_NODELAY set

  Connected to bitbucket.org (18.205.93.1) port 80 (#0)

  GET /eigen/eigen/get/3.2.10.tar.gz HTTP/1.1

  Host: bitbucket.org

  User-Agent: curl/7.58.0

  Accept: */*

  

  HTTP/1.1 301 Moved Permanently

  Content-Type: text/html

  Date: Mon, 19 Nov 2018 05:51:54 GMT

  Location: https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz

  Connection: Keep-Alive

  Content-Length: 0

  

  Connection #0 to host bitbucket.org left intact

  Issue another request to this URL:
  'https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz'

  Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         
    


make[2]: *** [eigen-download-prefix/src/eigen-download-stamp/eigen-download-download] Error 1
make[1]: *** [CMakeFiles/eigen-download.dir/all] Error 2
make: *** [all] Error 2
CMake Error at cmake/DownloadProject.cmake:179 (message):
  Build step for eigen failed: 2
Call Stack (most recent call first):
  cmake/LibiglDownloadExternal.cmake:14 (download_project)
  cmake/LibiglDownloadExternal.cmake:52 (igl_download_project)
  cmake/libigl.cmake:100 (igl_download_eigen)
  CMakeLists.txt:43 (include)


-- Configuring incomplete, errors occurred!
See also "/home/galib/libigl_latest_2/libigl/build/CMakeFiles/CMakeOutput.log".

```

I am not sure why this is happening. Any help/suggestion is appreciated.

Regards,
Asad

**Comment by jdumas** [comment]
Interesting. Try to `sudo apt-get install curl` and see if it helps. Seems that CMake's built in version of curl doesn't support https.

**Comment by jdumas** [comment]
Can you try `sudo apt-get install openssl libssl-dev` and to call `cmake -DCMAKE_USE_OPENSSL=ON ..` on your project (be sure to delete your `CMakeCache.txt` beforehand).

**Comment by jdumas** [comment]
Then you're on your own, as I cannot reproduce the problem on my machine...

**Comment by gulib** [comment]
Hi Jeremie,

I have tried with `TLS_VERIFY OFF` option .... but still having the same error.

**Comment by ikoruk** [comment]
This may be related to [the bitbucket migration](https://bitbucket.org/blog/deprecating-tlsv1-tlsv1-1-2018-12-01), although it shouldn't take effect until Dec 1.

**Comment by jdumas** [comment]
But you didn't udpate anything in libigl in the meantime? So it's really a change on the bitbucket side that caused this failure to download now?

Can you try to replace the `http` in the url of eigen by `htttps` ? Otherwise, another solution may be to use the `git` version instead of the zip. A third solution would be to use a different mirror, but it's more annoying. Otherwise, if it's really a bitbucket specific issue, you may try to contact their support team with information about your specific system and see if they can help finding a solution.

**Comment by gulib** [comment]
using `https` for eigen doesn't work on my computer.

using the `git` version of eigen instead of the `zip` worked for me. but embree is also using bitbucket. So, you have to use `git` version for embree also.

**Comment by jdumas** [comment]
Is this issue still relevant, or does it work now?

**Comment by gulib** [comment]
Yes it works when I used the git repository to download eigen and embree instead of bitbucket. Here are the lines I have changed, for eigen

`		GIT_REPOSITORY	https://github.com/eigenteam/eigen-git-mirror`
`		GIT_TAG			c50d586b9a43395a83e51821ebd1759d1c4668e4`

for embree
`		GIT_REPOSITORY https://github.com/embree/embree.git`
`		GIT_TAG        cb61322db3bb7082caed21913ad14869b436fe78`

**Comment by jdumas** [comment]
I guess my question is rather, if you try to build the `dev` branch of libigl, wihtout any modification, do you still get the same http error 301?

**Comment by gulib** [comment]
yes, still getting the same error when trying to build the `dev` branch of libigl.

**Comment by Utsav-Patel** [comment]
> Yes it works when I used the git repository to download eigen and embree instead of bitbucket. Here are the lines I have changed, for eigen
> 
> `	GIT_REPOSITORY	https://github.com/eigenteam/eigen-git-mirror`
> `	GIT_TAG	c50d586b9a43395a83e51821ebd1759d1c4668e4`
> 
> for embree
> `	GIT_REPOSITORY https://github.com/embree/embree.git`
> `	GIT_TAG cb61322db3bb7082caed21913ad14869b436fe78`

In which file should I change these variables?
Can you please share the path of these files?

**Comment by gulib** [comment]
> > Yes it works when I used the git repository to download eigen and embree instead of bitbucket. Here are the lines I have changed, for eigen 
> > `	GIT_REPOSITORY	https://github.com/eigenteam/eigen-git-mirror`
> > `	GIT_TAG	c50d586b9a43395a83e51821ebd1759d1c4668e4`
> > for embree
> > `	GIT_REPOSITORY https://github.com/embree/embree.git`
> > `	GIT_TAG cb61322db3bb7082caed21913ad14869b436fe78`
> 
> In which file should I change these variables?
> Can you please share the path of these files?

For Eigen 
[change here](https://github.com/libigl/libigl/blob/e699d257fe860d4fd82709835e72438bd0cd1533/cmake/LibiglDownloadExternal.cmake#L53) and the next line

For Embree
comment line 61 & 62 and uncomment  63 & 64

**Comment by robertguetzkow** [comment]
This is a problem with cURL. The easiest way to fix this under Ubuntu is to build cmake with your system cURL that supports TLS. What you need to do is:

1. `sudo apt install libcurl4-openssl-dev` (or another dev package for cURL with TLS support)
2. Download cmake source and change to unpacked directory
3. `./bootstrap --system-curl -- -DCMAKE_BUILD_TYPE:STRING=Release`
4. `make`
5. `make install`

**Comment by jdumas** [comment]
Is there any solution that doesn't involve a user recompiling their own version of curl?

**Comment by robertguetzkow** [comment]
Technically it's compiling your own version of cmake and doesn't touch your cURL installation. I guess the easiest way is using precompiled versions which probably have TLS enabled (but I haven't checked whether the packages in apt or from cmake actually do).

**Comment by jdumas** [comment]
I'd like to find a solution for non tech-savvy users that doesn't require any action from the user. E.g. can we download over non-encrypted http? We're checking md5sum anyway so I don't see why we need TLS.

**Comment by robertguetzkow** [comment]
Then the easiest way is to replace the URLs with the git variables. That works out of the box.

**Comment by jdumas** [comment]
Ok I see. The downside is that it pulls the whole git history for each repository, which can be quite heavy (compared to the zip). But maybe we can add an option to do a shallow clone or smth.

**Comment by LesiukAndrii** [comment]
just update cmake to the latest version
