### ISSUE TITLE
Heat Geodesic precompute compiling error

### ISSUE THREAD

**Issue by RobertBelfer** [libigl/libigl#1020]
When trying to compile example 716, as well as my own code, I get the error "You mixed matrices of different sizes".  This error seems to arise when _igl::heat_geodesics_precompute_ is called (commenting it out makes the code compile correctly, but caused errors when executing).

**Comment by jdumas** [comment]
Possibly fixed in #996 (see specific [comment](https://github.com/libigl/libigl/blob/a5da5ca3dcd6bc008584cec33cb10ebec846d5b9/include/igl/grad_intrinsic.cpp#L22) about the issue).

**Comment by sandervdbroekisd** [comment]
Same issue here, it can be fixed by compiling with a static library?

**Comment by jdumas** [comment]
I'll close this issue when it gets merged then!

**Comment by RobertBelfer** [comment]
I'm a complete novice when it comes to c++. What am I  supposed to do to fix the issue?

**Comment by sandervdbroekisd** [comment]
> I'm a complete novice when it comes to c++. What am I supposed to do to fix the issue?

You download the pull request version of the code instead of the dev branch.
