### ISSUE TITLE
Possible segmentation fault in principal_curvature

### ISSUE THREAD

**Issue by copyme** [libigl/libigl#1024]
So in the  function `CurvatureCalculator::computeCurvature` there is a condition for skipping the calculations for some special cases, i.e.,

```
if (vv.size()<6)
{
  continue;
 }
```

but then the memory allocation in `finalEigenStuff`is not done for curvDir, which will result in segmentation fault in `principal_curvature` thus the bounds are not checked

```
PD1.row(i) << cc.curvDir[i][0][0], cc.curvDir[i][0][1], cc.curvDir[i][0][2];
PD2.row(i) << cc.curvDir[i][1][0], cc.curvDir[i][1][1], cc.curvDir[i][1][2];
```

Indeed, a you can see I got a SIGSEGV for a vertex (i = 8) that caused the condition for skipping the loop in `CurvatureCalculator::computeCurvature`.

![image](https://user-images.githubusercontent.com/456607/48792251-76921900-ecfc-11e8-9cf5-6017957a5c03.png)

#### Check all that apply (change to `[x]`)
- [X] Windows
- [X] Mac OS X
- [X] Linux

**Comment by copyme** [comment]
And, yes the problem happened here because I used some nasty data with non-referenced vertices, etc. ;-)

**Comment by copyme** [comment]
Maybe it would be sufficient to throw an exception once the if condition is met?

**Comment by copyme** [comment]
If something, here, you have a mesh which seems to always crash the calculations. 
[tetrahedron.off.zip](https://github.com/libigl/libigl/files/3023422/tetrahedron.off.zip)

**Comment by CongliWANG** [comment]
I am suffering exactly the same issue here. Any updates?

**Comment by CongliWANG** [comment]
OK here is one workaround to avoid this issue.

Around line 688 in `principal_curvature.cpp` https://github.com/libigl/libigl/blob/87b54fc4dcc5aea182dd842a55ac75536fb69e1a/include/igl/principal_curvature.cpp#L688

change from
```cpp
if (vv.size() < 6)
{
  continue;
}
```
to
```cpp
if (vv.size() < 6)
{
  std::vector<Eigen::Vector3d> ref(3);
  computeReferenceFrame(i, normal, ref);
  Quadric q;
  fitQuadric(me, ref, vv, &q);
  finalEigenStuff(i, ref, q);
  continue;
}
```
Then it should work (at least for an "ill-posed" two-triangle mesh generated from a simple quad mesh).

**Comment by silence401** [comment]
I finally find the solution of this problem, `template <
  typename DerivedV,
  typename DerivedF,
  typename DerivedPD1,
  typename DerivedPD2,
  typename DerivedPV1,
  typename DerivedPV2>
IGL_INLINE void principal_curvature(
  const Eigen::MatrixBase<DerivedV>& V,
  const Eigen::MatrixBase<DerivedF>& F,
  Eigen::PlainObjectBase<DerivedPD1>& PD1,
  Eigen::PlainObjectBase<DerivedPD2>& PD2,
  Eigen::PlainObjectBase<DerivedPV1>& PV1,
  Eigen::PlainObjectBase<DerivedPV2>& PV2,
  unsigned radius = 5,
  bool useKring = true);

template <
  typename DerivedV,
  typename DerivedF,
  typename DerivedPD1,
  typename DerivedPD2,
  typename DerivedPV1,
  typename DerivedPV2,
  typename Index>
IGL_INLINE void principal_curvature(
  const Eigen::MatrixBase<DerivedV>& V,
  const Eigen::MatrixBase<DerivedF>& F,
  Eigen::PlainObjectBase<DerivedPD1>& PD1,
  Eigen::PlainObjectBase<DerivedPD2>& PD2,
  Eigen::PlainObjectBase<DerivedPV1>& PV1,
  Eigen::PlainObjectBase<DerivedPV2>& PV2,
  std::vector<Index>& bad_vertices,
  unsigned radius = 5,
  bool useKring = true);

}`
The second function in principal_curvature.h can solve this problem.

**Comment by alecjacobson** [comment]
libigl functions don't generally throw exceptions or validate inputs that don't meet the documentations stated precomputations at runtime. It'd be great to have better assertions in this function to catch bad inputs in debug mode. Happy to merge PRs.
