### ISSUE TITLE
'isovalue' implementation in marching_cubes.cpp is incomplete

### ISSUE THREAD

**Issue by vinbhaskara** [libigl/libigl#1032]
Calling marching_cubes.cpp with isovalue argument rightly identifies the nontrivial cubes by checking if the implicit function values take values above and below the isovalue (line number 130 and 226).

But then, once the nontrivial cubes have been identified, the isovalue does not seem to be used later on in the code, especially in the add_vertex function where it is necessary. 

Because the linear interpolation must be now done to find the points on the nontrivial edges where the interpolated value = isovalue rather than where the interpolated value = zero.

So, when the isovalue option is used in the current igl implementation, the nontrivial cubes are shortlisted right but the interpolation done to add a vertex finally seems to be wrong.

A fix would be to subtract MatrixXd::Ones() * isovalue from the "values" matrix before calling add_vertex function from line number 240.

A workaround currently to get the right mesh is to manually subtract isovalue from the field values and run marching_cubes() with its isovalue argument = 0.

There is currently a huge error in the final mesh when calling marching_cubes using isovalue argument VS the above alternative way. 

#### Check all that apply (change to `[x]`)
- [x] Windows
- [x] Mac OS X
- [x] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by alecjacobson** [comment]
I think this is not an issue with the non copyleft version.
