### ISSUE TITLE
Tutorial build error

### ISSUE THREAD

**Issue by KareemErgawy** [libigl/libigl#104]
Hello,
I am trying to build the tutorial on Ubuntu. When I run "cmake -DCMAKE_BUILD_TYPE=Release ../" everything runs smoothly regarding building and linking external libraries. Specifically, I get the following output:
```
-- Linking with: 
-- Found TINYXML2: /home/kareem/libigl2/libigl/external/tinyxml2
-- Found TRIANGLE: /home/kareem/libigl2/libigl/external/triangle
-- Found TETGEN: /home/kareem/libigl2/libigl/external/tetgen
-- Found EMBREE: /home/kareem/libigl2/libigl/external/embree/include
-- Found EMBREE: /home/kareem/libigl2/libigl/external/embree/include
-- Configuring done
```

Then the following error message is printed out:
```
CMake Error at 101_FileIO/CMakeLists.txt:10 (add_executable):
  Cannot find source file:

    /usr/include/../src/glew.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


-- Build files have been written to: /home/kareem/libigl2/libigl/tutorial/build
```

No make files are generated so I can't run "make" to produce the executables.

**Comment by danielepanozzo** [comment]
It could be two things:

1) The submodules have not been cloned. glew should be in libigl/external/nanogui/ext

You can clone them with:
git submodule init --recursive
git submodule update --recursive

2)
If this is not the problem, then probably cmake is getting confused and it is finding a local installation of glew on your system and using it instead of the embedded one. Could you try to uninstall glew and then launch cmake again?

**Comment by KareemErgawy** [comment]
Thanks a lot. It seems like I had both problem.
1) The submodule dirs were empty so I cloned them. However, the commands you provided should be slightly changed to:
git submodule init
git submodule update --init --recursive
That's what worked for me.

2) I am still having the 2nd problem since I see this in cmake logs:
```
-- Found GLFW: /usr/local/include -- HEADERS ONLY
-- Found GLEW: /usr/include
```
So it looks like the local copy is found. I am still struggling to uninstall them as I don't remember how they got there in the first place. I am trying to figure it out myself now, however, if you have some pointers on how can I do this please tell.

Thanks again.

**Comment by KareemErgawy** [comment]
It works find now. Turned out your cmake scripts took care of priority for searching directories. All I had to do was to remove the build directory I had before cloning the submodules to get rid of cmake cache in there and run a clean cmake.
