### ISSUE TITLE
Boundary_conditions cannot calculate parameters b and bc

### ISSUE THREAD

**Issue by BigXinSmallJin** [libigl/libigl#1045]
Hello,
I want to use BBW to calculate the weight of the arm model in shared file, but the parameters B and BC cannot be calculated in function boundary_conditions. 
![image](https://user-images.githubusercontent.com/37997949/49695803-290e1b00-fbdb-11e8-9541-9c34b627ed86.png)
Is there a problem with the parameters of model segmentation?
Here's the code for BBW testing and model segmentation.
//bbw
int arm_bbw_demo(std::string fileName)
{
	using namespace Eigen;
	using namespace std;
	igl::readMESH(TUTORIAL_SHARED_PATH + fileName + ".mesh", V, T, F);
	U = V;
	igl::readTGF(TUTORIAL_SHARED_PATH + fileName + ".tgf", C, BE);
	// retrieve parents for forward kinematics
	igl::directed_edge_parents(BE, P);

	VectorXi b;
	MatrixXd bc;
	igl::boundary_conditions(V, T, C, VectorXi(), BE, MatrixXi(), b, bc);

	// compute BBW weights matrix
	igl::BBWData bbw_data;
	// only a few iterations for sake of demo
	bbw_data.active_set_params.max_iter = 4;
	bbw_data.verbosity = 1;
	if (!igl::bbw(V, T, b, bc, bbw_data, W))
	{
		return EXIT_FAILURE;
	}
	// Normalize weights to sum to one
	igl::normalize_row_sums(W, W);
	// precompute linear blend skinning matrix
	igl::lbs_matrix(V, W, M);

	// Plot the mesh with pseudocolors
	igl::opengl::glfw::Viewer viewer;
	viewer.data().set_mesh(U, F);
	set_color(viewer);
	viewer.data().set_edges(C, BE, sea_green);
	viewer.data().show_lines = false;
	viewer.data().show_overlay_depth = false;
	viewer.data().line_width = 1;
	viewer.core.trackball_angle.normalize();
	viewer.callback_pre_draw = &pre_draw;
	viewer.callback_key_down = &bbw_key_down;
	viewer.core.is_animating = false;
	viewer.core.camera_zoom = 2.5;
	viewer.core.animation_max_fps = 30.;
	cout <<
		"Press '.' to show next weight function." << endl <<
		"Press ',' to show previous weight function." << endl <<
		"Press [space] to toggle animation." << endl;
	viewer.launch();
	return EXIT_SUCCESS;
}
//model segmentation
int tetgen_demo()
{
	using namespace Eigen;
	using namespace std;

	// Load a surface mesh
	igl::readOBJ(TUTORIAL_SHARED_PATH "/arm.obj", V_TET, F_TET);

	igl::copyleft::tetgen::tetrahedralize(V_TET, F_TET, "pq1.414", TV, TT, TF);
	igl::writeMESH(TUTORIAL_SHARED_PATH "/arm1.mesh", TV, TT, TF);
	// Compute barycenters
	igl::barycenter(TV, TT, B_TET);

	// Plot the generated mesh
	igl::opengl::glfw::Viewer viewer;
	viewer.callback_key_down = &key_down_TET;
	key_down_TET(viewer, '5', 0);
	viewer.launch();

	return 1;
}

#### Check all that apply (change to `[x]`)
- [x ] Windows
- [ ] Mac OS X
- [ ] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by alecjacobson** [comment]
Perhaps make sure that the bones and points appear as vertices in the corresponding tet mesh. Reopen with more info.
