### ISSUE TITLE
followed tutorial's directions, but make is failing

### ISSUE THREAD

**Issue by roiebs** [libigl/libigl#1047]
Hi everyone.

I am trying to build libigl. I followed the directions given on the tutorial. cmake finished successfully, but when building using make I keep getting the following error:

.
.
.
.
[ 13%] Building CXX object CMakeFiles/igl.dir/include/igl/edge_lengths.cpp.o
[ 13%] Building CXX object CMakeFiles/igl.dir/include/igl/edge_topology.cpp.o
[ 13%] Building CXX object CMakeFiles/igl.dir/include/igl/edges.cpp.o
[ 13%] Building CXX object CMakeFiles/igl.dir/include/igl/edges_to_path.cpp.o
[ 13%] Building CXX object CMakeFiles/igl.dir/include/igl/eigs.cpp.o
[ 13%] Building CXX object CMakeFiles/igl.dir/include/igl/euler_characteristic.cpp.o
[ 13%] Building CXX object CMakeFiles/igl.dir/include/igl/exact_geodesic.cpp.o
[ 14%] Building CXX object CMakeFiles/igl.dir/include/igl/example_fun.cpp.o
[ 14%] Building CXX object CMakeFiles/igl.dir/include/igl/exterior_edges.cpp.o
[ 14%] Building CXX object CMakeFiles/igl.dir/include/igl/extract_manifold_patches.cpp.o
/home/roie/graphics/libigl/include/igl/extract_manifold_patches.cpp:96:28: error: template-id ‘extract_manifold_patches<Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<int, -1, 1, 0, -1, 1> >’ for ‘long unsigned int igl::extract_manifold_patches(const Eigen::PlainObjectBase<Eigen::Matrix<int, -1, -1> >&, Eigen::PlainObjectBase<Eigen::Matrix<int, -1, 1> >&)’ does not match any template declaration
 template long unsigned int igl::extract_manifold_patches<Eigen::Matrix<int, -1, -1, 0, -1, -1>,   Eigen::Matrix<int, -1, 1, 0, -1, 1> >(Eigen::PlainObjectBase<Eigen::Matrix<int, -1, -1, 0, -1, -1> > const&, Eigen::PlainObjectBase<Eigen::Matrix<int, -1, 1, 0, -1, 1> >&);
                            ^~~
/home/roie/graphics/libigl/include/igl/extract_manifold_patches.cpp:82:19: note: candidates are: template<class DerivedF, class DerivedP> std::size_t igl::extract_manifold_patches(const Eigen::PlainObjectBase<DerivedF>&, Eigen::PlainObjectBase<DerivedEMAP>&)
 IGL_INLINE size_t igl::extract_manifold_patches(
                   ^~~
/home/roie/graphics/libigl/include/igl/extract_manifold_patches.cpp:19:19: note:                 template<class DerivedF, class DerivedEMAP, class uE2EType, class DerivedP> std::size_t igl::extract_manifold_patches(const Eigen::PlainObjectBase<DerivedF>&, const Eigen::PlainObjectBase<DerivedEMAP>&, const std::vector<std::vector<uE2EType> >&, Eigen::PlainObjectBase<DerivedP>&)
 IGL_INLINE size_t igl::extract_manifold_patches(
                   ^~~
/home/roie/graphics/libigl/include/igl/extract_manifold_patches.cpp:98:28: error: template-id ‘extract_manifold_patches<Eigen::Matrix<int, -1, 3, 1, -1, 3>, Eigen::Matrix<int, -1, 1, 0, -1, 1>, long unsigned int, Eigen::Matrix<int, -1, 1, 0, -1, 1> >’ for ‘long unsigned int igl::extract_manifold_patches(const Eigen::PlainObjectBase<Eigen::Matrix<int, -1, 3, 1, -1, 3> >&, const Eigen::PlainObjectBase<Eigen::Matrix<int, -1, 1> >&, const std::vector<std::vector<long unsigned int, std::allocator<long unsigned int> >, std::allocator<std::vector<long unsigned int, std::allocator<long unsigned int> > > >&, Eigen::PlainObjectBase<Eigen::Matrix<int, -1, 1> >&)’ does not match any template declaration
 template long unsigned int igl::extract_manifold_patches<Eigen::Matrix<int, -1, 3, 1, -1, 3>, Eigen::Matrix<int, -1, 1, 0, -1, 1>, unsigned long, Eigen::Matrix<int, -1, 1, 0, -1, 1> >(Eigen::PlainObjectBase<Eigen::Matrix<int, -1, 3, 1, -1, 3> > const&, Eigen::PlainObjectBase<Eigen::Matrix<int, -1, 1, 0, -1, 1> > const&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > > const&, Eigen::PlainObjectBase<Eigen::Matrix<int, -1, 1, 0, -1, 1> >&);
                            ^~~
/home/roie/graphics/libigl/include/igl/extract_manifold_patches.cpp:82:19: note: candidates are: template<class DerivedF, class DerivedP> std::size_t igl::extract_manifold_patches(const Eigen::PlainObjectBase<DerivedF>&, Eigen::PlainObjectBase<DerivedEMAP>&)
 IGL_INLINE size_t igl::extract_manifold_patches(
                   ^~~
/home/roie/graphics/libigl/include/igl/extract_manifold_patches.cpp:19:19: note:                 template<class DerivedF, class DerivedEMAP, class uE2EType, class DerivedP> std::size_t igl::extract_manifold_patches(const Eigen::PlainObjectBase<DerivedF>&, const Eigen::PlainObjectBase<DerivedEMAP>&, const std::vector<std::vector<uE2EType> >&, Eigen::PlainObjectBase<DerivedP>&)
 IGL_INLINE size_t igl::extract_manifold_patches(
                   ^~~
CMakeFiles/igl.dir/build.make:2342: recipe for target 'CMakeFiles/igl.dir/include/igl/extract_manifold_patches.cpp.o' failed
make[2]: *** [CMakeFiles/igl.dir/include/igl/extract_manifold_patches.cpp.o] Error 1
CMakeFiles/Makefile2:226: recipe for target 'CMakeFiles/igl.dir/all' failed
make[1]: *** [CMakeFiles/igl.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

could anyone please let me know how to get passed that? 
thanks!

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [x] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by tly000** [comment]
i just changed the `unsigned long` to `size_t` in the template specializations.

**Comment by jdumas** [comment]
Fixed by  #1471
