### ISSUE TITLE
Geodesic heat gives non-normalized results

### ISSUE THREAD

**Issue by sandervdbroek** [libigl/libigl#1048]
I am having an issue that the geodesic distances calculated seem to be scaled/anisotropic. I have attached two different obj files with which I have had this issue. When I calculate a length array (distances between all vertices) for the simple 3x3 grid mesh I get:
      0 1.96216 3.76497 1.96216 3.12582 4.40176 3.76497 4.40176 5.31797
0.98983       0 1.78279 2.69215  1.9042 2.65338 4.48467 3.86245 4.17995
2.82843 1.41421       0 4.24264 2.82843 1.41421 5.65685 4.24264 2.82843
0.98983 2.69215 4.48467       0  1.9042 3.86245 1.78279 2.65338 4.17995
1.95268 1.69903 3.11325 1.69903       0 1.69903 3.11325 1.69903 1.95268
4.17995 2.65338 1.78279 3.86245  1.9042       0 4.48467 2.69215 0.98983
2.82843 4.24264 5.65685 1.41421 2.82843 4.24264       0 1.41421 2.82843
4.17995 3.86245 4.48467 2.65338  1.9042 2.69215 1.78279       0 0.98983
5.31797 4.40176 3.76497 4.40176 3.12582 1.96216 3.76497 1.96216       0
This array should be symmetric, and as the grid has unit spacing have unit increments over the first two rows/columns, e.g.
0 1 2 ...
1 0 1 ...
2 1 0 ...
The maximum distance of the mesh is calculated as 5.31, while it should be 2*sqrt(2)=2.82, there seems to be close to a 100% error in many of these entries?

The second file I have attached (flatpanel.obj) is of a larger mesh, which has a spacing of 2 in both directions. This mesh also gives results which are almost doubled, with the first vertex having distances:
row: 0 3.92271  7.6437 11.4905 15.3928 19.3001 23.2002 27.0942 30.9848 (calculated from vertex)
col:  0 1.50652  4.4048 8.26968 12.3192 16.3684 20.3913 24.3957 28.3929 (calculated from other vertices)

I am not quite sure where the issue lies, there is a general increase in value when the distance increases, but the values do not represent the distance on the surface. Has anyone else encountered this issue?

(I used pull request 996 to generate these results)

[meshfiles.zip](https://github.com/libigl/libigl/files/2699018/meshfiles.zip)

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [x] Mac OS X
- [x ] Linux

**Comment by sandervdbroekisd** [comment]
The results seem to be much closer to the true value when:
 igl::min_quad_with_fixed_solve(data.Poisson,(-2.0*div_X).eval(),DerivedD(),Beq,D);
is replaced with:
  igl::min_quad_with_fixed_solve(data.Poisson,(-1.0*div_X).eval(),0.5*DerivedD(),Beq,D);

**Comment by alecjacobson** [comment]
Either this was fixed or I don't get the same factor of two issue when I test just now. Feel free to reopen if it's still an issue to investigate.
