### ISSUE TITLE
doublearea() produced NaN

### ISSUE THREAD

**Issue by xianyongzhang** [libigl/libigl#105]
hi，I have test the input mesh’s area which meet >0 ,but why it corrupt in doublearea.cpp and prompt
‘dblA(i) == dblA(i) && "DOUBLEAREA() PRODUCED NaN"’  when run igl::arap_precomputation(V, F, V.cols(), eigen_handlevec, *p_arap_data);
：
   //// Heron's formula for area
    //const typename Derivedl::Scalar arg =
    //  s(i)*(s(i)-l(i,0))*(s(i)-l(i,1))*(s(i)-l(i,2));
    //assert(arg>=0);
    //dblA(i) = 2.0*sqrt(arg);
    // Kahan's Heron's formula
    const typename Derivedl::Scalar arg =
      (l(i,0)+(l(i,1)+l(i,2)))*
      (l(i,2)-(l(i,0)-l(i,1)))*
      (l(i,2)+(l(i,0)-l(i,1)))*
      (l(i,0)+(l(i,1)-l(i,2)));
    dblA(i) = 2.0*0.25*sqrt(arg);
    assert( l(i,2) - (l(i,0)-l(i,1)) && "FAILED KAHAN'S ASSERTION");
    assert(dblA(i) == dblA(i) && "DOUBLEAREA() PRODUCED NaN");

**Comment by danielepanozzo** [comment]
Does the tutorial (http://libigl.github.io/libigl/tutorial/tutorial.html#as-rigid-as-possible) work for you?

If the tutorial works it is likely a problem with your mesh. There are probably degenerate faces.

**Comment by alecjacobson** [comment]
If you can post the mesh, we can try to debug this. This assertion shouldn't be firing even for degenerate faces. Only if the edge-lengths don't satisfy the triangle inequality (which perhaps is being violated via some floating point non-sense).

**Comment by alecjacobson** [comment]
Is it possible you're having the same problem as the top of this thread. https://github.com/libigl/libigl/issues/45

**Comment by alecjacobson** [comment]
We can reopen this when the input data is available.
