### ISSUE TITLE
Crashes in Viewer::draw() due to zero-width window

### ISSUE THREAD

**Issue by evouga** [libigl/libigl#1054]
Sometimes glfwGetWindowSize() in Viewer.cpp line 816 will return zero width, causing libigl to crash due to division by zero. I haven't tracked down exactly what causes this issue but I suspect it has to do with the glfw window losing focus/becoming minimized at just the wrong time.

In my local copy I've fixed the issue by simply checking:
````
if (width_window <= 0 || height_window <= 0)
        return;
````

#### Check all that apply (change to `[x]`)
- [X] Windows (MSVC 2017 x64)
- [ ] Mac OS X
- [ ] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by jdumas** [comment]
This should be fixed in the `dev` branch. Are you using the master branch?

**Comment by evouga** [comment]
Yes I am on master.
