### ISSUE TITLE
igl/copyleft/cgal/mesh_boolean.h

### ISSUE THREAD

**Issue by 96sgong** [libigl/libigl#1058]
I need to do Boolean operations with libigl(#include <igl/copyleft/cgal/mesh_boolean.h>).
Now,i only add this header file,this error occurred during compilation. how to solve?@alecjacobson

  @@![01](https://user-images.githubusercontent.com/44165351/50423132-5241d300-088c-11e9-9bde-47803c58a5e1.PNG)

**Comment by 96sgong** [comment]
![02](https://user-images.githubusercontent.com/44165351/50423166-f297f780-088c-11e9-911d-dd1d569a57cd.PNG)

**Comment by alecjacobson** [comment]
Best way is to use the new cmake setup. reopen if you have problems with that.
