### ISSUE TITLE
Unit test documentation on webpage is out of date

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#1059]
https://libigl.github.io/unit-tests/ still references gtest setup. 

We should have a description of the new setup and instructions on how to isolate tests etc.

For example, the current dev branch is failing for one of the "test on a bunch of meshes" tests ( https://travis-ci.org/libigl/libigl/jobs/472451023 ). Is it possible to isolate the failure or figure out which exact test is failing?

#### Check all that apply (change to `[x]`)
- [X] Windows
- [X] Mac OS X
- [X] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by jdumas** [comment]
Lots of pages may be outdated on the website, I've listed pages to check in [libigl.github.io/#7](https://github.com/libigl/libigl.github.io/issues/7).
