### ISSUE TITLE
Feature request: Hausdorff distance

### ISSUE THREAD

**Issue by visorz** [libigl/libigl#106]
Hello and thank you for your great work on libigl. I would like to see a Hausdorff distance function in libigl to compare two meshes. Unfortunately I am not able (yet) to do my own implementation. Because I am missing a MatLab license I can not use the MatLab engine link.

**Comment by alecjacobson** [comment]
I pushed a translation of the [gptoolbox hausdorff distance](https://github.com/alecjacobson/gptoolbox/blob/master/mesh/hausdorff.m) to libigl, commit 9db14076510b85de4f605a40bc0d5196f3801905
