### ISSUE TITLE
The recent commit merging"jdumas-fix-cgal" seems to break something about boost lib ...

### ISSUE THREAD

**Issue by metorm** [libigl/libigl#1061]
Minutes ago I pulled the latest dev branch to my local repository and my current project fails to build.
The problem is on `boost`. My project uses the `MT` version of `boost` and compiles well with the older versions.
However, with the latest version, a fatal error "Mixing a dll boost library with a static runtime is a really bad idea" is triggered. I checked the history and it turned out [the commit "Merge branch 'jdumas-fix-cgal' into dev"](https://github.com/libigl/libigl/commit/48c7fa98c1e01472141a2640bd237ce18c7d85b6) triggered the error.

![image](https://user-images.githubusercontent.com/12082680/50481185-286ae680-0a1b-11e9-880e-d2ca37d8a7be.png)

Anyone please help with this?

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [ ] Linux

**Comment by jdumas** [comment]
This is a known issue, see #1057, we're not sure what's the best way to fix it for now.

**Comment by alecjacobson** [comment]
Hopefully this is fixed now.
