### ISSUE TITLE
Do these 10^10 assertions actually do what they're intended to?

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#1065]
https://github.com/libigl/libigl/blob/e699d257fe860d4fd82709835e72438bd0cd1533/include/igl/copyleft/comiso/nrosy.cpp#L669

Reading the code I'm guessing this is meant to be 10^10 = 10,000,000,000, but I believe this is 10 BITWISE XOR 10...

**Comment by jdumas** [comment]
Lol, this must have been ported from python or something :p (`1e10` would be more reasonable too).

**Comment by alecjacobson** [comment]
huh. @hankstag changed these to 1e-10 instead. I don't know this code to know which is correct (and I guess probably not many are using it in debug mode?) 
<img width="1100" alt="image" src="https://github.com/libigl/libigl/assets/2241689/96259429-4725-489b-a470-0c9f675b5388">
