### ISSUE TITLE
Do not require write permission to the libigl folder

### ISSUE THREAD

**Issue by evouga** [libigl/libigl#1068]
The new ligibl configuration automatically downloads missing dependencies from the Internet when you compile using CMake, rather than when you check out the repository. This approach has some advantages but also causes some problems: for instance, in my class, I used to install libigl as a world-readable, write-protected system library, so that each individual student did not need their own personal copy of all of the headers (students are constantly running out of disk quota).

This approach no longer works because CMake fails to build any libigl applications when the libigl folder is write-protected (even if the dependencies are already present in `libigl/external`!). I urge you to change this so that libigl emits a warning (but does not abort with a fatal error) when it fails to download dependencies---especially when those dependencies are already installed in `external`.

#### Check all that apply (change to `[x]`)
- [X] Windows
- [X] Mac OS X
- [X] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by jdumas** [comment]
Hi. This new behavior is a consequence of the [big rewrite](https://libigl.github.io/rewritten-history/) that happened last October. Contributions are welcomed to improve the current behavior! My immediate suggestion would be to look at the file [LibiglDownloadExternal.cmake](https://github.com/libigl/libigl/blob/dev/cmake/LibiglDownloadExternal.cmake) and add a CMake option `LIBIGL_NO_DOWNLOAD` (defaulting to `OFF`) which would change the `igl_download_project()` function to a no-op. You'll also need to adjust the `igl_download_test_data()` and `igl_download_tutorial_data()` function as needed at the bottom of this file.

Once this modification is done you could do the following:
1. Run cmake _once_ to download external dependencies as needed in the `external/` folder.
2. Have your student compile libigl with the `LIBIGL_NO_DOWNLOAD` flag set to `OFF`, so CMake wouldn't try to update external dependencies.

This is also a problem when working offline (e.g. in the train/plane), and adding this option would be a cheap way to switch between both behaviors.

If you're feeling adventurous you might also want to look into the more advanced [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html) mechanics that came with CMake 3.11, which may be able to skip the update step if no internet connection is available, or the destination folder is not writable.

**Comment by jdumas** [comment]
Should be fixed with #1073.
