### ISSUE TITLE
a questuion about compile tutorial 609_Boolean

### ISSUE THREAD

**Issue by 96sgong** [libigl/libigl#1069]
hi everyone!
    I want to compile  tutorial 609_Boolean, when i compile this, i have some problems,the first picture is  the error of compile this example 609_Boolean separately, the second picture is the error of compile the whole tutorial,how to resolve this error? thank you!
![single](https://user-images.githubusercontent.com/44165351/50585595-bbd76800-0eb0-11e9-8878-53bb3cc8c902.PNG)
![duo](https://user-images.githubusercontent.com/44165351/50585596-bc6ffe80-0eb0-11e9-9040-263785702cd8.PNG)

**Comment by ferguras** [comment]
I got it working last week and didn't encounter your problem, but did encounter some others. The makefiles don't seem to be very robust and there are more dependancies then documented.

How I got it working:
1) I installed the CGAL library, including boost.
sudo apt-get install libcgal-dev and sudo apt-get install libboost-all-dev should do the trick.
2) I compiled libigl with CGAL extension
make with -DLIBIGL_WITH_CGAL defined
make still gave a couple of errors with libraries that it needed but google solved all those problems.
3)
At the end of the make process, all tutorials gets build, including the 609 example.

**Comment by 96sgong** [comment]
> I got it working last week and didn't encounter your problem, but did encounter some others. The makefiles don't seem to be very robust and there are more dependancies then documented.
> 
> How I got it working:
> 
> 1. I installed the CGAL library, including boost.
>    sudo apt-get install libcgal-dev and sudo apt-get install libboost-all-dev should do the trick.
> 2. I compiled libigl with CGAL extension
>    make with -DLIBIGL_WITH_CGAL defined
>    make still gave a couple of errors with libraries that it needed but google solved all those problems.
> 
> At the end of the make process, all tutorials gets build, including the 609 example.

thanks for your reply, i have installed CGAL and boost before,
i also select the LIBIGL_WITH_CGAL,
My version: windows x64, CGAL4.13
the error remains as follows:

CMake Error at D:/libigl/shared/cmake/libigl.cmake:174 (get_target_property):
  INTERFACE_LIBRARY targets may only have whitelisted properties.  The
  property "IMPORTED_LOCATION_configurations-NOTFOUND" is not allowed.
Call Stack (most recent call first):
  D:/libigl/shared/cmake/libigl.cmake:191 (igl_copy_imported_dll)
  609_Boolean/CMakeLists.txt:6 (igl_copy_cgal_dll)


cmake error: unknown cmake command "igl_copy_cgal_dll" ,but  i don't know what is igl_copy_cgal_dll.

**Comment by ferguras** [comment]
I am using ubuntu, sorry.

The igil_cgal library in my situation gets compiled when I build libigl with the CGAL option enabled. To me, your error implies that you didn't build libigl with the CGAL extension succesfully. The 609 example requires that extension to be in place. My guess is that the 609 example links with the static version of libigl.

**Comment by jdumas** [comment]
Hi.

Just to make sure: are you using the `master` branch or the `dev` branch version of libigl? If the former, could you please try to build the version on the `dev` branch to see if it solves your issue.

On ubuntu, you do not need to have CGAL installed with libigl (libigl will download its own version of CGAL). You need however, to have the following packages installed to build the CGAL dependency:
- boost
- gmp
- mpfr

If you have doubts, take a look at the `.travis.yml` file on the `dev` branch, so see the list of Ubuntu packages that gets installed in order to build libigl with CGAL, as well as the commands to call CMake (and start with a clean `build/` folder again).

**Comment by alecjacobson** [comment]
hoepfully easier with the new cmake setup. Please reopen if still an issue with the current main branch.
