### ISSUE TITLE
NRosyField without CoMisO?

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#107]
From private email:

> I am a grad student and have been trying NRosyField available in LibIGL. I am having very tough time compiling CoMISO. Is there any way, I could bypass CoMISO altogether and use your Software.

**Comment by alecjacobson** [comment]
Daniele will know better, but I believe CoMiso is currently used only for the final quad meshing and currently there is no alternative.

**Comment by danielepanozzo** [comment]
CoMiso is used for:
1) the parametrization needed for quad meshing
2) for the n-rosy field interpolation.
For 1) there is currently no replacement for CoMiso, but if you only need 2) you could use the alternative method http://libigl.github.io/libigl/tutorial/tutorial.html#npolyvectorfields
that only requires Eigen.

**Comment by csverma** [comment]
Which libraries are preferred ( and necessary ) in building CoMISO ? There is an 
option between SuiteSparse and Eigen3 libraries.

Also are IpOpt and Gurobi required for libIGL ?

Thanks.
csv

**Comment by csverma** [comment]
Has anyone tried compiling CoMISO on Ubuntu 15.04 with g++4.9 ? I 
am having very tough time making CoMISO work for the NRoSy fields
and quad meshing in libIGL. Can someone help me urgently ?

**Comment by danielepanozzo** [comment]
I suggest you ask the authors of CoMiso, noone of the developers of libigl is a developer of CoMiso, we are simply using it. I can build comiso on MacOSX with only eigen and gmm++, and I expect that you could do the same on linux. IpOpt and Gurobi are not used in libigl.

**Comment by csverma** [comment]
Hello Daniele,
Thank you very much for your guide. I realized that CoMSIO is not portable on Ubuntu as of now. There are features that areno longer available in g++4.9 because of which g++ does not include many modules.
Template version of libIGL fails on Ubuntu, therefore, I had to resort to static library path.
Thanks.csv
