### ISSUE TITLE
Non vertex manifold after splitting meshes in manifold patches

### ISSUE THREAD

**Issue by FrankEscobar** [libigl/libigl#1070]
I used _igl::extract_manifold_patches(F, P)_ and also I tried with my own implementation that fills a 

Eigen::MatrixXi F; with the edge index instead the vertex one and use _igl::vertex_components(F,C)_

Both modes work ok on super-simple cases but both fail on some regular meshes, I mean the function _igl::is_vertex_manifold(F,V);_ return false on the new component.

Any thought on this?
Thank you in advance.

**Comment by alecjacobson** [comment]
The more precise documentation of extract_manifold_patches is correct: patches are connected via manifold _edges_. They may contain non-manifold _vertices_.
