### ISSUE TITLE
A shallow gray boundary in captured screenshot

### ISSUE THREAD

**Issue by rozentill** [libigl/libigl#1075]
[Describe your issue]

Hi there,

I have been used libigl for a while, and thanks for your effort to make it such amazing. I met a problem about the screenshot recently(seems no problem one year ago). I am using the latest version and try to capture a screenshot for image processing usage. But there is always a shallow gray boundary, even if I turn off the light (light_factor = 0.0), and it also exist in the shading results.  Here is an example from tutorial of the screen capture. The black pixels are caused by the shading, the gray ones between black and background are the weird boundaries. I wonder how they are generated or how to remove them. Thanks a lot!

![capture](https://user-images.githubusercontent.com/11246898/51061090-d7282e80-15a6-11e9-94ed-936cc8fa525d.PNG)

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [ ] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by jdumas** [comment]
You can try to disable multisample anti-aliasing, commenting [this line](https://github.com/libigl/libigl/blob/7895811be45816ba399365a13487305660f152a7/include/igl/opengl/glfw/Viewer.cpp#L142) I think should do the trick.

**Comment by rozentill** [comment]
Thanks for your reply, but the boundary seems still exist.

**Comment by rozentill** [comment]
modified draw_buffer and solved.

**Comment by jdumas** [comment]
Cool. Yeah `draw_buffer` is not used in the main rendering loop, so if you take a screenshot of the app manually you shouldn't need to modify it. But if you are taking the screenshot programmatically (as in tutorial 607), then makes sense that you need to tweak `draw_buffer` as well.
