### ISSUE TITLE
Camera variables explanations

### ISSUE THREAD

**Issue by ygrimault** [libigl/libigl#1076]
Hello,

This is not really an issue, it's more a problem of understanding how things work.

I want to implement a double camera system, one that allows the user to manipulate the scene, and one that allows the user to move around the scene. In the second case, I have some UI elements linked to the first camera system.

For these reasons, I need to manipulate the camera myself in a ViewerPlugin, and tweak with the ViewerCore's camera's parameters. My question is: are these parameters explained exactly somewhere? 

Because I would have thought that the `camera_eye` parameter would return the camera position in world coordinate, yet it doesn't change.
I guess it's in fact the local coordinates of the eye, and I need to look at `camera_base_translation` and/or `camera_translation`, but I don't understand how they work. Similarly, how does the zoom work? Can it be "replaced" by a translation of the camera? If so, how?

Thanks in advance for reading me and trying to enlighten me.

**Comment by jdumas** [comment]
Not directly related to your question, but you might want to check out the "multiple viewports" PR #978, which implement support for multiple views inside the same application. The transformations to compute the camera matrix are performed [here](https://github.com/libigl/libigl/blob/0294540603ce29def75caa2bf5474f4070f46229/include/igl/opengl/ViewerCore.cpp#L134), so you can check how the different parameter are used. The base translation + rotation correspond to a fixed rigid transformation applied to the scene (as computed by `align_camera_center()`), to recenter it and rescale it. `camera_eye` is indeed the position of the camera, but after this rigid transformation + trackball rotation + translation has been applied.
