### ISSUE TITLE
use libigl as external project (modern cmake build with targets)

### ISSUE THREAD

**Issue by schmidje** [libigl/libigl#1077]
Hi,

I am using a very recent build of libigl (>=ver. 2) (compiled as a static lib, but this should not be the issue) in visual studio 2017 and I use it as an external dependency:

```cmake
find_package(libigl CONFIG REQUIRED core common)
if(NOT TARGET igl::core OR NOT TARGET igl::common)
  message (FATAL_ERROR "libigl not found!")
endif()

(...)

add_library(MyFooLib ${some_sources})
target_link_libraries(MyFooLib PUBLIC igl::core igl::common)
```

At the configure stage, CMake complains that despite it found libigl config, libigl package is considered as not found:

```
CMake Error at CMakeLists.txt:76 (find_package):
  Found package configuration file:

    C:/Programming/Libs/Git/Build/x64/vs2017/libigl/libigl-config.cmake

  but it set libigl_FOUND to FALSE so package "libigl" is considered to be
  NOT FOUND.
```
By inspecting generated libigl-config.cmake, the issue is that some code like:

```cmake
if(TARGET igl::common)
  set(libigl_common_FOUND TRUE)
endif()
```

is missing after group `if (TARGET igl::core) (...) endif()` to indicate that target igl::common has been properly found (as it is done for target core).

Am I missing something about the use of new cmake targets? The libgl-example-project does something similar (except that I am specifically calling the find_package in CONFIG mode).

Thanks!

**Comment by jdumas** [comment]
@ithron was the one that developed this `libigl-config.cmake` in #839. I personally don't use it yet and it's really just there for convenience, but it may still be a bit rough around the edges. The "official" supported way of using libigl is to build it with your project, as is done in the [libigl-example-project](https://github.com/libigl/libigl-example-project/). I.e., you need to `include()` the file `cmake/libigl.cmake` somehow in your project.

**Comment by schmidje** [comment]
Thanks for the reply, maybe @ithron can have a look to it. Most probably the config approach must be checked, it should not break the current official approach.

What I found problematic with the current official approach is that set options specified when building libigl (typically building it as a static library) are **not** preserved from my personal experience when reincluding the `cmake/libigl.cmake` file. Hence users using an installed libigl version must somehow know how it was built, to reset the same options.

Conversely, the exported config is purposely designed to save all this information. That is why I used in config mode.

**Comment by jdumas** [comment]
If you are building libigl in your project, then _you_ are the one to choose which option you want to enable and build libigl with. Default options can be set in the toplevel CMake file of your project, so that whomever include `cmake/libigl.cmake` first will use this set of defaults. That way, you need only build what is required for your current project.

**Comment by schmidje** [comment]
Oh I see, this makes sense if I build libigl with my project as explained in the previous post, my bad. 

I guess this is okay as long as libigl is mainly header only (INTERFACE lib in cmake sense). I personally prefer to re-use an existing build although is an INTERFACE library via a config. This is mainly because I don't like my IDE being cluttered with external projects.

Thanks.

**Comment by jdumas** [comment]
Yes I understand. libigl can be used both in header-only or in static lib mode. The latter will require rebuilding the whole thing, which can be time-consuming if you use only a small part of it. There are advantages in terms of maintenance and reproducibility, as you know exactly which version of libigl you are using in your project though. Once we get a more streamlined build and version system we'll be looking into packaging it better, but this is low priority for us so it may not happen anytime soon.

**Comment by schmidje** [comment]
Thank you for your comments! I will close since it is not really an "issue" per se although this building scheme could be improved.

Thanks.

**Comment by ithron** [comment]
There's indeed an error in the libigl-config.cmake.in. I fixed it in #1097.

**Comment by schmidje** [comment]
I tried the committed fixes in #1097 eigen-dev and it works for my build, but I am not ready to switch to the dev branch yet : ) Thanks.

**Comment by jdumas** [comment]
I can assure you the `dev` branch is in fact quite stable. This is where new features and bug fixes are committed. The reason we have a separate default `master` branch is to be able to clearly identify a release and make a list of changes/new features so that people can update their libigl dependency. In the `dev` branch we may update stuff that affects you, but you can also choose the latest commit and stick to it.

**Comment by ShuangLiu1992** [comment]
this is great, but what about optional modules like embree?

**Comment by jdumas** [comment]
You mean, to use as installed packages on your system? At the moment this is not supported, and you will need to build libigl with your project directly.
