### ISSUE TITLE
Various Constraints on Vector Fields

### ISSUE THREAD

**Issue by csverma** [libigl/libigl#108]
Hello All,

(1) Are there any guidelines on setting constraints with various vector field generators in libIGL ?
(2) In some of the tutorial examples, constraints are placed randomly and the vectors
     are generated randomly, therefore, I am curious of know, if the LibIGL will automatically
     project these vectors on the faces ?
(3) In the conjugate vector field example, 6 vectors are chosen on 84 faces. What are these
     six vectors ?
(4) Is there any plan to provide "lapped texture" to visualize vector fields in libIGL ? Are there
     any free "lapped texture" software available that we can use ?

Thanks.
csv

**Comment by alecjacobson** [comment]
For 1-3, @danielepanozzo would have to help you. For 4, the answer is no, but I think Daniele has a new visualization in the works.

**Comment by copyme** [comment]
@csverma Are you still expecting an answer? Can this issue be closed?
