### ISSUE TITLE
problem with mesh boolean intersection

### ISSUE THREAD

**Issue by gulib** [libigl/libigl#1080]
Hello,

I was trying to use `igl::copyleft::cgal::mesh_boolean` to perform `intersection` operation with the meshes I got from Voronoi operation of some objects. The files are attached here [gvd.zip](https://github.com/libigl/libigl/files/2806217/gvd.zip). I am trying to do `intersection` operation of `Frihole_n.obj` with other `gvd.obj` files. the output shows that the meshes are not PWN and I only get a result for the `gvd-4.obj`. 

Do you have any suggestion how can I do the boolean operation? Is that because the meshes are not PWN? If so, How can I make the meshes PWN?

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [x ] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by alecjacobson** [comment]
How are the gvd-1.obj , etc. meshes generated? Are you in control of that process? Those meshes are pretty messy in terms of duplicated stuff and non-manifold stuff. You might be able to repair them, but it'd be better to see why they're like that.

**Comment by gulib** [comment]
I have used [this](https://github.com/geometryprocessing/SVAM). @jdumas wrote the code that perform Voronoi tessellation on 3D objects.

**Comment by alecjacobson** [comment]
I guess https://github.com/geometryprocessing/SVAM is a private repo because that link didn't work for me.
