### ISSUE TITLE
RuntimeError: Incompatible buffer format, windows

### ISSUE THREAD

**Issue by dragonbook** [libigl/libigl#1081]
Hi,

I just compiled libigl under windows 10(x64), and when I run following code, it throws a run time error: "Incompatible buffer format!".
```
import numpy as np
import pyigl as igl

a = np.ones((3, 4), dtype=np.int32)
b = igl.eigen.MatrixXi(a)
```

The libigl code(latest master branch) is compiled by vs2017 with python3.5.6(installed by conda). I also tried vs2015+python3.6.8 etc, but still got the same run time error. When I  print *info.format* and *py::format_descriptor<Scalar>::format()* in code [py_vector.cpp](https://github.com/libigl/libigl/blob/master/python/modules/py_vector.cpp#L35), it shows 'l' and 'i'. 

Note, the same libigl code(with externals) can work well under ubuntu16.04, and I am using it.

#### Check all that apply (change to `[x]`)
- [x ] Windows
- [ ] Mac OS X
- [ ] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by teseoch** [comment]
this issue involves the old bindings which have been discontinued, plz refer to https://libigl.github.io/libigl-python-bindings/ for the new version.

There is no need of using Eigen, igl is not compatible with numpy matrices
