### ISSUE TITLE
Does not show viewer tool bar

### ISSUE THREAD

**Issue by thelagrangian** [libigl/libigl#1084]
I was running the tutorial of 102_DrawMesh_bin on Mac, but the viewer's tool bar (the side bar) did not show up when the viewer popped up.

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [x] Mac OS X
- [ ] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by jdumas** [comment]
Yes that's because the screenshot are outdated. Only tutorial 106 will show the menu (sidebar) now.

**Comment by thelagrangian** [comment]
Thank you so much again, jdumas.
