### ISSUE TITLE
add_label function not rendering text in tutorial 105_Overlays

### ISSUE THREAD

**Issue by chrisleong-nvg** [libigl/libigl#1089]
I am using 105_Overlays from the tutorials to add_labels but no text is being rendered.

Building in Visual Studio 2017 in x64 Debug mode and x64 Release.

I also tried to use add_label in my own sandbox project but it won't render as well.

#### Check all that apply (change to `[x]`)
- [X] Windows
- [ ] Mac OS X
- [ ] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by jdumas** [comment]
Hi. To get the labels to show you need to enable the ImGui pluging (e.g., tutorial 106).

**Comment by chrisleong-nvg** [comment]
Thank you. Works perfectly now.
