### ISSUE TITLE
Static library 

### ISSUE THREAD

**Issue by csverma** [libigl/libigl#109]
Hello,

Initially, I tried template version of libigl on my Ubuntu machine running g++4.9, but I get core
dump right after executing the code besides that the templated code take long time to compile.

I have been trying to have libigl as a shared library. I have installed CoMISo with IpOpt and Gmm++
libraries. While linking the libigl library to the applications, I get the following messages for which 
I have no clue. Can someone help ?

Thanks.
csv

nrosy.cpp:(.text+0x2e05): undefined reference to `void COMISO::ConstrainedSolver::solve<gmm::row_matrix<gmm::wsvector<double> >, gmm::col_matrix<gmm::wsvector<double> >, std::vector<double, std::allocator<double> >, std::vector<int, std::allocator<int> > >(gmm::row_matrix<gmm::wsvector<double> >&, gmm::col_matrix<gmm::wsvector<double> >&, std::vector<double, std::allocator<double> >&, std::vector<double, std::allocator<double> >&, std::vector<int, std::allocator<int> >&, double, bool, bool)'
/home/csverma/Software/LibIGL/lib/libigl.so(nrosy.o): In function `COMISO::MISolver::~MISolver()':
nrosy.cpp:(.text._ZN6COMISO8MISolverD2Ev[_ZN6COMISO8MISolverD5Ev]+0x2a): undefined reference to `COMISO::EigenLDLTSolver::~EigenLDLTSolver()'
/home/csverma/Software/LibIGL/lib/libigl.so(nrosy.o): In function `COMISO::ConstrainedSolver::ConstrainedSolver(bool)':
nrosy.cpp:(.text._ZN6COMISO17ConstrainedSolverC2Eb[_ZN6COMISO17ConstrainedSolverC5Eb]+0x19): undefined reference to `COMISO::MISolver::MISolver()'

**Comment by danielepanozzo** [comment]
It seems that you are not linking against COMISO. Is this compiled using the cmake project in the tutorials or with you own makefile? To debug this, try to use the library as header only, in that way you are 100% sure that the linking problem is not due to libigl.

**Comment by danielepanozzo** [comment]
This should now be working out of the box with the newest version of libigl. Please reopen if it is not the case.
