### ISSUE TITLE
Compilation error on Linux 32bit

### ISSUE THREAD

**Issue by dvd0101** [libigl/libigl#1095]
Hi everyone!

While preparing a conan package for libigl, I found a compilation error during the build of the static version targeting a 32bit platform (on a 64bit host using the -m32 bit switch of gcc/clang).

The bug is caused by a mismatch between some functions declaration and their explicit instantiations.

When the target is 64bit the error goes away because sizeof(size_t) == sizeof(unsigned long).

The attached patch resolves the problem; I've not opened a PR because the template instantiations are "guarded" by a comment citing a tool (autoexplicit.sh), so I don't know if such code is auto-generated or, instead, it is manually updated.

[fix_static_build.txt](https://github.com/libigl/libigl/files/2905079/fix_static_build.txt)

This is the same error reported by #1047 

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [X] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by jdumas** [comment]
Hi. Feel free to create a PR to update said template instantiations. I don't think anyone is using `autoexplicit.sh` anyway (personally I had explicit template instantiations manually as needed). Note that we do not plan to support officially 32bit compilation, but as long as your changes do not conflict with existing build on Travis, should be fine to merge them.
