### ISSUE TITLE
CMake Error on Ubuntu 14.04

### ISSUE THREAD

**Issue by aklonc** [libigl/libigl#1098]
Hi everyone,

I previously write and modify my code inside libigl and build everything and It works well. But right now I want to try another way, creating a new project using the [example project](https://github.com/libigl/libigl-example-project). And I have encountered a CMake Error on Ubuntu 14.04 when I was building it. 

The strange thing is that everything works well on Ubuntu 18.04 with the same installation(every step is the same).

Here is the CMake Error information on Ubuntu 14.04:
```
CMake Error at cmake/FindLIBIGL.cmake:36 (include):
  include could not find load file:

    libigl
Call Stack (most recent call first):
  CMakeLists.txt:10 (find_package)


-- Configuring incomplete, errors occurred!
```

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [x] Linux

**Comment by jdumas** [comment]
Make sure your `FindLIBIGL.cmake` is looking for `libigl.cmake` in the `${LIBIGL_INCLUDE_DIR}/../cmake` folder, and not `${LIBIGL_INCLUDE_DIR}/../shared/cmake` (this has been updated in libigl 2.0).

That being said, Ubuntu 14.04 is starting to get really old. I'm not even sure it has a version of CMake recent enough for libigl.

**Comment by aklonc** [comment]
@jdumas Thank you for your reply! My libigl is up-to-date(2.0). And `FindLIBIGL.cmake` does look for `libigl.cmake` in the `${LIBIGL_INCLUDE_DIR}/../cmake` folder. I have also updated my CMake to the latest version 3.13.4. May I ask what might be the problem here?

**Comment by jdumas** [comment]
Hell if I know :D
You can try to `message()` the value of `${LIBIGL_INCLUDE_DIR}`, to get a sense of which folder CMake found libigl in. Most likely it ended up looking in the wrong place.

**Comment by aklonc** [comment]
Let me try it for one more hour. : )

**Comment by aklonc** [comment]
It looks like the function find_path doesn't work. I just manually set the `LIBIGL_INCLUDE_DIR` to `/home/(username)/project/libigl/include/` and it works now. : )

**Comment by jdumas** [comment]
Well [find_path()](https://cmake.org/cmake/help/latest/command/find_path.html) does what's in the CMake documentation. Since `FindLIBIGL.cmake` is a file you should have in your project, you can tweak it to your needs. I guess I'll just close this then.

**Comment by aklonc** [comment]
Sure! Thanks a lot!
