### ISSUE TITLE
principal curvature crash

### ISSUE THREAD

**Issue by cristiulian** [libigl/libigl#11]
principal_curvature crashes when the radius is set to 1. I'm using Visual Studio 2008.
Also, it would be very nice to have the crease lines computed by the principal_curvature method, as described in the "Efficient Multi-scale Curvature and Crease Estimation" paper.

**Comment by danielyan86129** [comment]
> I think the problem happens when a vertex has less than 6 neighbors, then the optimization to fit the quadric fails since there is no unique solution. I pushed a fix that does not allow to pick one as radius, the minimum value is now 2. This fitting method is not designed to work on the 1-ring anyway, even if it will work, it will produce noisy results if the neighborhood used do not intersect considerably.

Such important detail deserves to be added to the "tutorial" and "API" sections. For me the function failed because my mesh contains small components, which is not obvious until I read this comment.
