### ISSUE TITLE
Wrong Eigen3 dependency when using find_package(libigl)

### ISSUE THREAD

**Issue by ithron** [libigl/libigl#1100]
Following scenario:
- Eigen3 is installed and can be found with `find_package(Eigen3)`
- Eigen3 cannot be found with PkgConfig, i.e. `pkg_check_modules(Eigen3)`
- libigl is included in the base project by using `find_package(libigl CONFIG REQUIRED)`

When the base project links against `libigl::core` or `libigl::common` (e.g. in the test target) cmake outputs then following error:

> Target "test" links to target "PkgConfig::Eigen3" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

This is a result of a wrong ordering of  the  if-else cases in `libigl-config.cmake.in`. The PkgConfig case is chosen even if `find_package()` succeeded and `pkg_check_modules()` did not. 

#### Check all that apply (change to `[x]`)
- [x] Windows
- [x] Mac OS X
- [x] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by jdumas** [comment]
This is starting to look a tad complicated. Since this only affects the `libigl-config.cmake` it's not too bad, but I think I would rather avoid relying on PkgConfig at all. The logic should be:
- If a target `Eigen3::Eigen` exists and has been defined by the user, use it.
- Otherwise, download Eigen via CMake, and use the bundled version.

Multiplying the logic of how Eigen can be found (e.g. via PkgConfig) is just gonna increase maintenance cost. I would be more inclined to provide a mechanism for the users to load their own options, e.g., by calling `include(LibiglOptions)` if the file `LibiglOptions.cmake` exists, so that users can inject their own code without modifying the upstream repo.

**Comment by ithron** [comment]
Yes,  PkgConfig support can/should be dropped. I think it was in because on older Ubuntu systems Eigen was installed without a CMake configuration file. At least for 18.04 I know it's no longer the case.

IMO if Eigen is not present is should **not** be downloaded automatically via CMake.
When one uses libigl through `find_package()`, libigl is usually installed somewhere on the system (e.g. in /usr/local or some project specific install path). As a user I usually don't want `find_package()` to download or install any additional software for me. I'd suggest to
1. check if the target Eigen3::Eigen is available, and if not:
2. use `find_package(Eigen3 CONFIG REQUIRED)` to locate it.
3. if Eigen3::Eigen is still not present, present an error and let the user install/downlad/etc Eigen

A optional `include(LibiglOptions)` is a great idea, but I don't know how well it fits in the `find_package()` ecosystem. Maybe something like `find_package(libigl CONFIG REQUIRED Options)` could load the 'Options' component and allows the user to customize the configuration that is then used in a subsequent `find_package(libigl CONFIG REQUIRED)` call.

But in the most common use cases, a user should be able to use libigl after a single `find_package()` call without any tweaking.

**Comment by jdumas** [comment]
Yeah that makes sense. If libigl is installed on the system it should not try to download anything on its own. If we can support the latest Ubuntu LTS and Debian stable without PkgConfig, then I vote for dropping it indeed (and produce an error message as you suggest). The `LibiglOptions` thing would be nice too, but it's a different topic for later I'd say.

**Comment by ithron** [comment]
I updated the PR #1101  and dropped PkgConfig support. Now the code is much simpler.
