### ISSUE TITLE
/Projects/libigl/include/igl/opengl/glfw/Viewer.cpp:148:22: Use of undeclared identifier 'GLFW_TRANSPARENT_FRAMEBUFFER'

### ISSUE THREAD

**Issue by hanamizukigakki** [libigl/libigl#1111]
I have created a new project with code in example 102 in Xcode. 
Add include path:
`/libigl/include`
`/opt/local/include/GLFW`
`/opt/local/include/eigen3`
`/opt/local/include`
`/libigl/external/glad/include`
Link with
`libglfw.3.2.dylib`
`OpenGL.framework`

Then an error occurred with 
`/Projects/libigl/include/igl/opengl/glfw/Viewer.cpp:148:22: Use of undeclared identifier 'GLFW_TRANSPARENT_FRAMEBUFFER'`

The source code seems to customize for MacOs:
`#ifdef __APPLE__`
`      glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);`
`      glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);`
  `    glfwWindowHint(GLFW_TRANSPARENT_FRAMEBUFFER, GLFW_TRUE);`
`    #endif`

- [ ] Windows
- [x] Mac OS X
- [ ] Linux

Any ideas to solve this problem ?

THANKS.

**Comment by jdumas** [comment]
You need to use the version of GLFW that comes with libigl.

**Comment by hanamizukigakki** [comment]
I have installed `eigen`, `glfw` and `glew` with `brew install eigen`, `brew install glew` and `brew install glfw3`. The version is `eigen-3.3.7`, `glfw-3.2.1` and `glew-2.1.0`. All these include pathes have beed included. Still the same problem.. Then what is the right version of these packages?

**Comment by jdumas** [comment]
You don't need to install anything, you should let libigl's cmake download the correct version of the dependencies and use those.

**Comment by alecjacobson** [comment]
This thread hints that our documentation could be more clear.

@hanamizukigakki  could you give us a little feedback? Why did you start installing things with brew? Is it just natural habit or did something on the libigl documentation lead you to doing this?

**Comment by jdumas** [comment]
Agreed, we could be a bit more aggressive in the documentation. Maybe we could have a "quickstart" page or something and make use of [fancy blocks](https://squidfunk.github.io/mkdocs-material/extensions/admonition/#tip) on the website to catch the user's attention.

**Comment by hanamizukigakki** [comment]
I uninstall glfw3 and glew, exclude the related path, now the project include path is : 
`/usr/local/include/eigen3`
`/Projects/GP/libigl/include`
Then another error occurred:
`/libigl/include/igl/opengl/gl.h:23:10: 'glad/glad.h' file not found`
Any advice?


For installing, I googled eigen3 installation and installed as https://qiita.com/itoru257/items/7ffccf9f1556f3787a9b suggested

**Comment by hanamizukigakki** [comment]
OK, I found an answer from  #820,  `'glad/glad.h' file not found` may caused by my uncompleted configuration. I'll try it later with a better network.

**Comment by hanamizukigakki** [comment]
Still error with `'glad/glad.h' file not found`. My operations lists as below:
`brew install eigen`
`git clone https://github.com/libigl/libigl.git`
`cd libigl`
`mkdir build`
configure && generate with CMake-GUI
`cd build`
`make`
Then open a new Xcode project and copy code in Example102, add HeaderSearchPath:
`/opt/local/include/eigen3`
`/libigl/include`
`/usr/local/include`
add LibrarySearchPath:
`/usr/local/lib`
Then build failed ...

Any Advices ?

THANKS.

**Comment by hanamizukigakki** [comment]
Still error with `'glad/glad.h' file not found`. My operations lists as below:
`brew install eigen`
`git clone https://github.com/libigl/libigl.git`
`cd libigl`
`mkdir build`
configure && generate with CMake-GUI
`cd build`
`make`
Then open a new Xcode project and copy code in Example102, add HeaderSearchPath:
`/opt/local/include/eigen3`
`/libigl/include`
`/usr/local/include`
add LibrarySearchPath:
`/usr/local/lib`
Then build failed ...

Any Advices ?

THANKS.

**Comment by jdumas** [comment]
Can you tell us exactly what kind of instructions from the website you are trying to follow?

**Comment by hanamizukigakki** [comment]
I have build success on Windows10 & Visual Studio 15 2017 Win64 according to https://github.com/libigl/libigl-example-project and I am trying to make it work on MacOS now.

**Comment by jdumas** [comment]
And what led you to believe that you have to install anything on macOS to make it work?

**Comment by hanamizukigakki** [comment]
OK, I have build success on macOS and all tutorials have worked with`./*_bin`, but I still cannot make it work with Xcode, any suggestions about projection configuration with libigl on Xcode ?

**Comment by jdumas** [comment]
Can you be more specific of what went wrong, and how are you generating the Xcode project exactly?

**Comment by hanamizukigakki** [comment]
Operations to generate the Xcode project:
1. Start a new command project with Xcode, add `libigl/include` and `/usr/local/inlcude/eigen3` to HeaderSearchPath
2. copy code from tutorial-101_FIileIO to main.cpp. Then build success and get a right answer.
3. replace the code with tutorial-102_DrawMesh. Then build failed, the error is `glad/glad.h file not found`

No more other operations.

**Comment by Aniwax** [comment]
> Operations to generate the Xcode project:
> 
> 1. Start a new command project with Xcode, add `libigl/include` and `/usr/local/inlcude/eigen3` to HeaderSearchPath
> 2. copy code from tutorial-101_FIileIO to main.cpp. Then build success and get a right answer.
> 3. replace the code with tutorial-102_DrawMesh. Then build failed, the error is `glad/glad.h file not found`
> 
> No more other operations.

I have exactly the same problem when I try to run the code "tutorial-102_DrawMesh."

**Comment by jdumas** [comment]
Answered in #820. Closing.
