### ISSUE TITLE
Triangulate fails on VS17 64bit. Any hints?

### ISSUE THREAD

**Issue by klocska** [libigl/libigl#1114]
[Describe your issue]

#### Check all that apply (change to `[x]`)
- [ x] Windows
- [ ] Mac OS X
- [ ] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

After migration from VS2013 to VS2017 (ISO C++17 v141 toolset SDK 8.1 ) I have unexpected fails inside Triangulate library. If compiler optimization is switched off code works. Could you give me any hints how to improve this issue? I visited main Triangulate source but there is nothing fresh there.
Regards, Maxim Prut

**Comment by jdumas** [comment]
Can you provide a minimal working example as well as the input data that is causing the code to fail?

**Comment by klocska** [comment]
I'm working on it. I believe that's Triangulate issue, not LIBIGL one that's why I treat the ticket more like a question

**Comment by jdumas** [comment]
Well, Triangle has a known bug where it can segfault if your input has duplicated vertices. We tried contacting prof. Shewchuk about it, but he never got back to us so I suspect either the email got lost or he's not fixing bugs anymore. But maybe you're having a different issue altogether, it's hard to know without an example.

**Comment by klocska** [comment]
I made some investigation. The cause that lead to behavior change is occasionally switched on /fp:fast setting during VS compiler change. It leads to unpredictable behavior in floating points operations and fails inside insertsegment function. I believe the cause of fail is the same with "duplicated vertices" case but it's provoked by rough fp operations. The same input data are processed stable on standalone version of Triangulate and seems pretty valid.
