### ISSUE TITLE
Applying texture to a grid

### ISSUE THREAD

**Issue by MarcinKolber** [libigl/libigl#1115]
Hi,
I have been struggling with applying and stretching textures on a grid without repeating the image. I have been using the grid.off file from the tutorials. 
I do not know whether there are functions that allow me to apply an image over the grid, or I need to use OpenGL for this? 

Thanks,
Marcin

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [X] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by alecjacobson** [comment]
Not sure exactly what the original question is. perhaps using set_uv and set_texture in the viewer. Please reopen with more information if still an issue
