### ISSUE TITLE
mesh_boolean results in selfintersections

### ISSUE THREAD

**Issue by ferguras** [libigl/libigl#1116]
I have written some example code that creates a roof through an union of a single rooftile. The union code works great for a lot of objects, but the rooftile union results in self intersections and degenerates further with each union. The original object is manifold and does not have self intersections, according to the tools I used to verify. 

[roof.zip](https://github.com/libigl/libigl/files/2990313/roof.zip)

My code:

```
bool unionroof_test(void)
{
	Eigen::MatrixXd m_Points;
	Eigen::MatrixXi m_Triangles;	
	Eigen::MatrixXd Normals;
        bool Result=readSTL("rooftile.stl",m_Points,m_Triangles,Normals);
	if (!Result) return Result;
	Eigen::MatrixXd m_PointsCopy=m_Points;
	Eigen::MatrixXi m_TrianglesCopy=m_Triangles;
	int counter=4;
	while (counter>0)
        {
	  --counter;
          m_PointsCopy.array().col(1)+=10.0;
	  Eigen::MatrixXd VC;
	  Eigen::VectorXi J;
	  Eigen::MatrixXi FC;     
igl::copyleft::cgal::mesh_boolean(m_Points,m_Triangles,m_PointsCopy,m_TrianglesCopy,MESH_BOOLEAN_TYPE_UNION,VC,FC,J);
	  m_Points=VC;
	  m_Triangles=FC;
	}	
	m_PointsCopy=m_Points;
	m_TrianglesCopy=m_Triangles;
	counter=4;
	while (counter>0)
    {
	  --counter;
          m_PointsCopy.array().col(0)+=10.0;
	  Eigen::MatrixXd VC;
	  Eigen::VectorXi J;
	  Eigen::MatrixXi FC; igl::copyleft::cgal::mesh_boolean(m_Points,m_Triangles,m_PointsCopy,m_TrianglesCopy,MESH_BOOLEAN_TYPE_UNION,VC,FC,J);
	  m_Points=VC;
	  m_Triangles=FC;
	}	
	return writeSTL("rooftest.stl", m_Points, m_Triangles, false);
}

```

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [x] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by alecjacobson** [comment]
There are a few things that can be improved in this snippet.

 - avoid using `.stl` for the input because it loses mesh connectivity
 - avoid using `.stl` for the output because it rounds to single precision
 - avoid rounding to float after _every_ call to `mesh_boolean`, instead use an "exact" number type for all the boolean operations and round at the very end

Here's my re-write of your code.

```
#include <igl/readSTL.h>
#include <igl/writeSTL.h>
#include <igl/copyleft/cgal/mesh_boolean.h>
#include <igl/copyleft/cgal/assign.h>
#include <igl/copyleft/cgal/remesh_self_intersections.h>
#include <igl/copyleft/cgal/RemeshSelfIntersectionsParam.h>

using namespace igl;
bool unionroof_test(void)
{
Eigen::MatrixXd m_Points;
Eigen::MatrixXi m_Triangles;
Eigen::MatrixXd Normals;
// If possible, avoid using .stl files. This file type forgets mesh
// connectivity and will make processing slower.
bool Result=readSTL("rooftile.stl",m_Points,m_Triangles,Normals);
if (!Result) return Result;
// for repeated Boolean operations avoid rounding to float after each
// operation by using an exact type and then rounding at the very end.
typedef Eigen::Matrix<CGAL::Epeck::FT,Eigen::Dynamic,3> MatrixX3E;
// Convert input to exact number type
MatrixX3E m_PointsExact = igl::copyleft::cgal::assign<CGAL::Epeck::FT>(m_Points);
MatrixX3E m_PointsCopy = m_PointsExact;
Eigen::MatrixXi m_TrianglesCopy=m_Triangles;
int counter=4;
while (counter>0)
{
--counter;
m_PointsCopy.array().col(1)+=10.0;
Eigen::VectorXi J;
// Each call to mesh_boolean inputs the exact mesh and outputs an exact mesh
igl::copyleft::cgal::mesh_boolean(MatrixX3E(m_PointsExact),Eigen::MatrixXi(m_Triangles),m_PointsCopy,m_TrianglesCopy,MESH_BOOLEAN_TYPE_UNION,m_PointsExact,m_Triangles,J);
}
m_PointsCopy=m_PointsExact;
m_TrianglesCopy=m_Triangles;
counter=4;
while (counter>0)
{
--counter;
m_PointsCopy.array().col(0)+=10.0;
Eigen::VectorXi J;
// Each call to mesh_boolean inputs the exact mesh and outputs an exact mesh
igl::copyleft::cgal::mesh_boolean(MatrixX3E(m_PointsExact),Eigen::MatrixXi(m_Triangles),m_PointsCopy,m_TrianglesCopy,MESH_BOOLEAN_TYPE_UNION,m_PointsExact,m_Triangles,J);
}
{
    MatrixX3E _V;
    Eigen::MatrixXi _F;
    Eigen::MatrixXi IF;
    Eigen::VectorXi _2,_3;
    copyleft::cgal::remesh_self_intersections(
      m_PointsExact,m_Triangles,
      copyleft::cgal::RemeshSelfIntersectionsParam(true,false,false),
      _V,_F,
      IF,_2,_3);
    std::cout<<"#self-intersections in exact mesh: "<<IF.rows()<<std::endl;
}

m_Points = igl::copyleft::cgal::assign<double>(m_PointsExact);
{
  Eigen::MatrixXd _V;
    Eigen::MatrixXi _F;
    Eigen::MatrixXi IF;
    Eigen::VectorXi _2,_3;
    copyleft::cgal::remesh_self_intersections(
      m_Points,m_Triangles,
      copyleft::cgal::RemeshSelfIntersectionsParam(true,false,false),
      _V,_F,
      IF,_2,_3);
    std::cout<<"#self-intersections in double mesh: "<<IF.rows()<<std::endl;
}
// Another problem with STL is that it's binary format is single precision. So
// writing to .stl and reading back could create self-intersections.
writeSTL("rooftest.stl", m_Points, m_Triangles, false);
readSTL("rooftest.stl",m_Points,m_Triangles,Normals);
{
  Eigen::MatrixXd _V;
    Eigen::MatrixXi _F;
    Eigen::MatrixXi IF;
    Eigen::VectorXi _2,_3;
    copyleft::cgal::remesh_self_intersections(
      m_Points,m_Triangles,
      copyleft::cgal::RemeshSelfIntersectionsParam(true,false,false),
      _V,_F,
      IF,_2,_3);
    std::cout<<"#self-intersections in stl mesh: "<<IF.rows()<<std::endl;
}
}
```

Running this will output:

```
#self-intersections in exact mesh: 0
#self-intersections in double mesh: 0
#self-intersections in stl mesh: 7242
```

Our methods guarantees `0` self-intersections if all operations are done in the exact mesh type.
In this case, rounding (after all booleans are finished) also results in `0` self-intersections (this is not guaranteed but often observed). Writing to `.stl` and reading back in, we see that many new self-intersections have appeared.

**Comment by ferguras** [comment]
Thank you very much for the great library, helping me out and even helping to write better code. I still feel like a rookie but I do love libigl. I did not have any problems with booleans operations on any object, until this one.
Thanks for the info on the exact calculations and the example code, I was unaware that writing to stl would lead to intersection problems. This problem does not occur when I write back to obj, but my slicer only accepts stl files. 

I am unable to get your example code to compile. The assign statement gives an error that I do not know how to fix:
'''
/libigl/external/eigen/Eigen/src/Core/DenseBase.h: In instantiation of 'class Eigen::DenseBase<CGAL::Lazy_exact_nt<CGAL::Gmpq> >':
3dmesh_2.cpp:225:79:   recursively required by substitution of 'template<class DerivedC, class DerivedD> void igl::copyleft::cgal::assign(const Eigen::MatrixBase<Derived>&, Eigen::PlainObjectBase<DerivedD>&) [with DerivedC = CGAL::Lazy_exact_nt<CGAL::Gmpq>; DerivedD = <missing>]'
3dmesh_2.cpp:225:79:   required from here
/libigl/external/eigen/Eigen/src/Core/DenseBase.h:41:34: error: invalid use of incomplete type 'struct Eigen::internal::traits<CGAL::Lazy_exact_nt<CGAL::Gmpq> >'
 template<typename Derived> class DenseBase
'''

I was however able to write code that does the same thing, using the CSGTree code. It compiles like a charm and seems to do its thing. But it still doesn't generate the output I would expect.

'''
ool unionroof_test_csg(void)
{
  Eigen::MatrixXd m_Points,m_PointsCopy;
  Eigen::MatrixXi m_Triangles,m_TrianglesCopy;
  Eigen::MatrixXd Normals;
  // If possible, avoid using .stl files. This file type forgets mesh
  // connectivity and will make processing slower.
  bool Result=readSTL("rooftile_gj.stl",m_Points,m_Triangles,Normals);
  if (!Result) return Result;
  // for repeated Boolean operations avoid rounding to float after each
  // operation by using an exact type and then rounding at the very end.
  igl::copyleft::cgal::CSGTree::MatrixX3E m_V=m_Points.template cast<igl::copyleft::cgal::CSGTree::ExactScalar>();
  igl::copyleft::cgal::CSGTree::POBF m_F=m_Triangles;
  igl::copyleft::cgal::CSGTree::VectorJ m_J;
  igl::copyleft::cgal::CSGTree::MatrixX3E m_V_Copy=m_V;
  igl::copyleft::cgal::CSGTree::POBF m_F_Copy=m_F;
  int counter=16;
  while (counter>0)
  {
	cout << "Rooftile " << counter << endl;
    --counter;
    m_V_Copy.array().col(1)+=10.0;
	igl::copyleft::cgal::mesh_boolean(m_V,m_F,m_V_Copy,m_F_Copy,MESH_BOOLEAN_TYPE_UNION,m_V,m_F,m_J);
  }
  m_V_Copy=m_V;
  m_F_Copy=m_F;
  counter=16;
  while (counter>0)
  {
  	cout << "Roofrow " << counter << endl;
    --counter;
    m_V_Copy.array().col(0)+=10.0;
	igl::copyleft::cgal::mesh_boolean(m_V,m_F,m_V_Copy,m_F_Copy,MESH_BOOLEAN_TYPE_UNION,m_V,m_F,m_J);
  }
  
  {
    igl::copyleft::cgal::CSGTree::MatrixX3E m_SIV;
    Eigen::MatrixXi _F;
    Eigen::MatrixXi IF;
    Eigen::VectorXi _2,_3;
    copyleft::cgal::remesh_self_intersections(
      m_V,m_F,
      copyleft::cgal::RemeshSelfIntersectionsParam(true,false,false),
      m_SIV,_F,
      IF,_2,_3);
    std::cout<<"#self-intersections in exact mesh: "<<IF.rows()<<std::endl;
    std::cout<<"#triangles in exact mesh: "<<m_F.rows()<<std::endl;
  }
  
  {
            m_PointsCopy.resize(m_V.rows(),m_V.cols());
            for(int i = 0;i<m_V.rows();i++)
            {
              for(int j = 0;j<m_V.cols();j++)
              {
                m_PointsCopy(i,j) = CGAL::to_double(m_V(i,j));
              }
            }
  }
  m_Points=m_PointsCopy;
  m_Triangles=m_F;
  {
    Eigen::MatrixXd m_SIV;
    Eigen::MatrixXi _F;
    Eigen::MatrixXi IF;
    Eigen::VectorXi _2,_3;
    copyleft::cgal::remesh_self_intersections(
      m_Points,m_Triangles,
      copyleft::cgal::RemeshSelfIntersectionsParam(true,false,false),
      m_SIV,_F,
      IF,_2,_3);
    std::cout<<"#self-intersections in double mesh: "<<IF.rows()<<std::endl;
    std::cout<<"#triangles in exact mesh: "<<m_Triangles.rows()<<std::endl;
  }
  {
    write_triangle_mesh("rooftest.mesh",m_Points, m_Triangles,false);
	Eigen::MatrixXd m_SIV;
    Eigen::MatrixXi _F;
    Eigen::MatrixXi IF;
    Eigen::VectorXi _2,_3;
    bool Result=readMESH("rooftest.mesh",m_PointsCopy,_F,m_TrianglesCopy);
    copyleft::cgal::remesh_self_intersections(
      m_PointsCopy,m_TrianglesCopy,
      copyleft::cgal::RemeshSelfIntersectionsParam(true,false,false),
      m_SIV,_F,
      IF,_2,_3);
    std::cout<<"#self-intersections in mesh file: "<<IF.rows()<<std::endl;
    std::cout<<"#triangles in mesh file: "<<m_TrianglesCopy.rows()<<std::endl;
  }
}
'''
To avoid the small gap between two tiles, I have changed the input stl slightly. This in the hope it would ease the calculation and generate a good object. 
[rooftile_gj.zip](https://github.com/libigl/libigl/files/3000417/rooftile_gj.zip)

Unfortuantly, the more rows are added to the object (second loop), the more likely the program stops with a coredump. Sometimes it finishes with a message that there are intersections in the exact mesh and not in the double. Sometimes, with low counters, it finishes succesfully.

Any advice on how to proceed futher?
