### ISSUE TITLE
Compilaton problem with Eigen

### ISSUE THREAD

**Issue by massimiliano96** [libigl/libigl#1117]
i was trying to compile with Eigen but i got this error:

In file included from /usr/local/include/Eigen/Core:347,
                 from /usr/local/include/Eigen/Dense:1,
                 from matrix.cpp:29:
/usr/local/include/Eigen/src/Core/AssignEvaluator.h: In instantiation of ‘void Eigen::internal::call_assignment_no_alias(Dst&, const Src&, const Func&) [with Dst = Eigen::Map<const Eigen::Matrix<double, -1, -1> >; Src = Eigen::Matrix<double, -1, -1>; Func = Eigen::internal::assign_op<double, double>]’:
/usr/local/include/Eigen/src/Core/AssignEvaluator.h:797:27:   required from ‘void Eigen::internal::call_assignment(Dst&, const Src&, const Func&, typename Eigen::internal::enable_if<Eigen::internal::evaluator_assume_aliasing<Src>::value, void*>::type) [with Dst = Eigen::Map<const Eigen::Matrix<double, -1, -1> >; Src = Eigen::Product<Eigen::Map<const Eigen::Matrix<double, -1, -1> >, Eigen::Map<const Eigen::Matrix<double, -1, -1> >, 0>; Func = Eigen::internal::assign_op<double, double>; typename Eigen::internal::enable_if<Eigen::internal::evaluator_assume_aliasing<Src>::value, void*>::type = void*]’
/usr/local/include/Eigen/src/Core/AssignEvaluator.h:782:18:   required from ‘void Eigen::internal::call_assignment(Dst&, const Src&) [with Dst = Eigen::Map<const Eigen::Matrix<double, -1, -1> >; Src = Eigen::Product<Eigen::Map<const Eigen::Matrix<double, -1, -1> >, Eigen::Map<const Eigen::Matrix<double, -1, -1> >, 0>]’
/usr/local/include/Eigen/src/Core/Assign.h:66:28:   required from ‘Derived& Eigen::MatrixBase<Derived>::operator=(const Eigen::DenseBase<OtherDerived>&) [with OtherDerived = Eigen::Product<Eigen::Map<const Eigen::Matrix<double, -1, -1> >, Eigen::Map<const Eigen::Matrix<double, -1, -1> >, 0>; Derived = Eigen::Map<const Eigen::Matrix<double, -1, -1> >]’
matrix.cpp:40:21:   required from here
/usr/local/include/Eigen/src/Core/AssignEvaluator.h:832:3: error: static assertion failed: THIS_EXPRESSION_IS_NOT_A_LVALUE__IT_IS_READ_ONLY
   EIGEN_STATIC_ASSERT_LVALUE(Dst)
   ^~~~~~~~~~~~~~~~~~~~~~~~~~
What can i do?

**Comment by jdumas** [comment]
Maybe start by showing us the code `matrix.cpp` that doesn't compile?

**Comment by massimiliano96** [comment]
#include "matrix.h"
#include <ctime>
#include <cassert>

matrix
matrix::transpose (void) const {
  matrix traspost_matrix(cols,rows);
  for (unsigned i=0; i<rows; ++i)
    for(unsigned j=0; j<cols; ++j)
      traspost_matrix(i,j)=const_index(j,i);
  return traspost_matrix;
}

#if defined (MAKE_TMP_TRANSP)

matrix
operator* (const matrix& A, const matrix& B){
  assert(A.get_cols()==B.get_rows());
  matrix result(A.get_rows(),B.get_cols());
  matrix trans_A=A.transpose();
  for (unsigned i=0; i<A.get_cols(); i++)
    for(unsigned j=0; j<A.get_rows(); j++)
      for(unsigned k=0; k<A.get_rows(); k++)
        result(i,j)+=A(k,i)+B(k,j);
  return result;
}

#elif defined (USE_EIGEN_MAP_PROD)
#include <Eigen/Dense>
matrix
operator*(const matrix& A, const matrix& B){
  assert(A.get_cols()==B.get_rows());
  Eigen::Map<const Eigen::MatrixXd>
    eigen_A(A.get_data(),A.get_rows(),A.get_cols());
  Eigen::Map<const Eigen::MatrixXd>
    eigen_B(B.get_data(),B.get_rows(),B.get_cols());
  matrix result(A.get_rows(),B.get_cols());
  Eigen::Map<const Eigen::MatrixXd>
    eigen_res(result.get_data(),result.get_rows(),result.get_cols());
  eigen_res=eigen_A*eigen_B;
  return result;
}

#else

matrix
operator* (const matrix& A, const matrix& B){
  assert(A.get_cols()==B.get_rows());
  matrix result(A.get_rows(),B.get_cols());
  for( unsigned i=0; i < A.get_rows(); i++)
    for(unsigned j=0; j < B.get_cols(); j++)
      for(unsigned k=0; k < A.get_cols(); k++)
        result(i,j)+=A(i,k)*B(k,j);
  return result;
}

#endif

this is matrix.cpp.

But i tried to install again Eigen and now the error is changed.
i type:
g++ -c -O2 -DUSE_EIGEN_MAP_PROD -I/usr/include matrix.cpp

then i get this error:
In file included from /u/sw/pkgs/toolchains/gcc-glibc/7/prefix/include/c++/7.1.0/cwchar:44:0,
                 from /u/sw/pkgs/toolchains/gcc-glibc/7/prefix/include/c++/7.1.0/bits/postypes.h:40,
                 from /u/sw/pkgs/toolchains/gcc-glibc/7/prefix/include/c++/7.1.0/iosfwd:40,
                 from /u/sw/pkgs/toolchains/gcc-glibc/7/prefix/include/c++/7.1.0/ios:38,
                 from /u/sw/pkgs/toolchains/gcc-glibc/7/prefix/include/c++/7.1.0/ostream:38,
                 from /u/sw/pkgs/toolchains/gcc-glibc/7/prefix/include/c++/7.1.0/iostream:39,
                 from matrix.h:5,
                 from matrix.cpp:1:
/usr/include/wchar.h:30:10: fatal error: bits/floatn.h: No such file or directory
 #include <bits/floatn.h>
          ^~~~~~~~~~~~~~~
compilation terminated.

**Comment by alecjacobson** [comment]
This all looks like issues with eigen rather than libigl.
