### ISSUE TITLE
"Weight space" in uniformly_sample_two_manifold

### ISSUE THREAD

**Issue by vahisht** [libigl/libigl#1118]
I'm trying to use the function [uniformly_sample_two_manifold](https://github.com/libigl/libigl/blob/master/include/igl/uniformly_sample_two_manifold.h), but I'm not sure what is meant by "#W by dim positions of mesh in weight space" in the first argument. I tried passing all my mesh vertices as this argument but the output I get is very messy and does not uniformly sample the mesh at all.

What is meant by "weight space" in this context? Or would anyone happen to know what do I need to pass to the function to obtain the uniform samples on the given mesh?

Thanks!

#### Check all that apply (change to `[x]`)
- [x] Windows
- [x] Mac OS X
- [x] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by alecjacobson** [comment]
This is a poorly named function to implement the furthest-point sampling style approach for sampling a mesh embedded in a high-dimensional space (e.g., per-vertex skinning weights) introduced in the Fast Automatic Skinning Transformations paper. 

`igl::blue_noise` is probably a better function to use in most cases.
