### ISSUE TITLE
Triangle and quad faces in OBJs

### ISSUE THREAD

**Issue by robertguetzkow** [libigl/libigl#1119]
Currently libigl doesn't support loading valid OBJs that contain both triangle and quad faces. The check in `igl::list_to_matrix` expects `igl::min_size` to have the same value as `igl::max_size`. 

#### Check all that apply (change to `[x]`)
- [x] Windows
- [x] Mac OS X
- [x] Linux

**Comment by jdumas** [comment]
We have a pending PR #1108 that is adding support for writing OBJ files with varying face size. That being said, libigl's matrix representation for meshes doesn't play well with hybrid meshes that have varying face sizes. For that you might want to consider an alternative (geogram, libhedra, cinolib, OpenMesh, etc.).

**Comment by robertguetzkow** [comment]
Alright, no problem. I'll triangulate meshes before loading.
