### ISSUE TITLE
Crash on biharmonic_coordinates

### ISSUE THREAD

**Issue by zapan669** [libigl/libigl#112]
Hey Alec,
I get a crash using  igl::biharmonic_coordinates( V, T, S, power, W) ;  // with power = 2

S  is  an  std::vector<std::vector>    filled by singletons such as :    {  {0},{1},{2},{3},{4},{5},{6},{7}   }     (cube vertices)

It’s crashing  in    normal_derivative.cpp   line 76     DD.setFromTriplets(IJV.begin(),IJV.end());

Can it be related to the 3D case instead of 2D  ?

**Comment by zapan669** [comment]
Sorry I did not find how to attach a txt file, here my matrices T and V

T :
4 414
0
0
0
1
1
2
2
3
3
3
4
4
4
5
5
6
6
7
7
7
8
8
8
8
8
8
8
8
8
8
8
8
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
10
10
10
10
10
10
10
10
10
10
10
10
10
10
11
11
11
11
11
11
11
11
11
11
11
11
12
12
13
13
14
14
15
15
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
17
17
18
18
19
19
20
20
20
20
20
21
21
22
22
23
23
24
24
24
24
24
24
24
24
24
24
24
24
25
25
26
26
26
26
26
26
26
26
26
26
26
26
26
26
27
27
28
28
28
28
28
28
29
29
29
29
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
31
31
31
31
31
32
32
32
32
32
32
32
32
32
32
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
34
34
34
35
36
36
36
37
37
37
38
39
39
39
40
40
40
40
41
41
41
41
43
43
43
45
46
46
46
46
46
46
46
46
46
46
46
46
46
46
46
46
46
46
47
47
47
47
48
48
48
49
49
49
49
50
50
50
50
50
50
50
50
50
50
50
50
51
51
51
51
51
51
51
51
52
52
52
53
53
53
53
53
53
53
53
53
54
54
56
57
57
58
58
61
61
62
66
68
69
70
70
70
73
74
74
74
78
80
81
81
81
82
82
82
82
82
82
82
82
84
86
86
86
86
86
86
86
86
87
87
88
89
89
89
89
89
94
94
95
96
96
97
97
102
102
102
103
103
104
104
105
105
105
105
105
105
106
106
106
106
106
106
106
107
107
107
107
107
115
115
115
122
125
126
127
127
129
129
129
129
129
139
141
142
144
146
146
146
147
147
147
148
148
148
151
152
153
156
159
163
169
172
173
174
174
174
174
174
175
66
57
66
68
68
59
60
69
58
132
62
71
62
90
61
65
67
20
20
20
54
159
54
151
88
175
150
138
158
145
158
177
44
20
20
145
63
63
63
82
85
82
134
125
126
172
159
170
31
31
53
42
53
70
76
114
53
168
138
150
138
150
39
163
39
154
84
84
140
155
162
143
174
176
55
155
154
118
163
117
162
115
75
35
148
39
155
39
73
117
75
141
92
117
163
148
141
157
96
165
169
113
98
150
44
64
85
120
145
151
109
159
108
101
153
152
102
102
122
156
177
139
153
141
157
174
174
152
124
48
38
72
142
118
84
162
147
118
154
142
164
147
154
156
125
105
173
171
127
176
173
167
106
128
169
52
45
79
52
109
88
158
139
153
109
151
144
139
160
151
153
62
71
53
71
71
160
107
107
129
164
179
142
165
144
161
150
54
175
90
78
80
108
90
108
159
146
111
149
146
146
170
168
159
55
46
66
75
57
89
137
69
50
58
48
173
163
163
48
60
48
142
61
90
146
97
71
53
99
52
140
155
83
137
83
89
124
89
129
89
89
129
102
102
157
152
140
155
67
52
139
103
60
119
72
68
75
141
104
69
69
87
77
87
87
136
143
105
113
128
105
166
70
70
146
106
175
168
147
67
110
79
107
70
165
100
100
138
107
151
114
177
175
75
91
66
136
116
112
90
71
83
75
132
165
166
165
130
115
87
136
90
133
121
82
134
145
121
153
122
156
134
145
158
162
170
126
126
148
127
172
149
177
115
143
175
93
93
140
129
154
143
163
162
147
147
146
169
161
152
152
139
152
141
156
128
169
128
163
173
169
146
167
176
175
169
176
175
151
160
160
175
175
167
143
162
177
156
170
148
171
154
164
154
174
179
144
148
165
161
149
171
169
167
176
165
172
172
174
175
161
177
174
177
173
171
177
174
175
176
175
179
178
177
57
66
123
56
75
48
48
58
116
69
31
31
71
61
90
52
52
64
120
134
150
54
175
88
158
88
138
151
145
159
177
175
20
85
134
20
44
145
159
85
82
125
82
172
170
126
145
159
42
53
31
98
70
53
53
53
138
70
98
98
150
168
155
39
174
84
162
176
154
140
143
163
154
174
155
92
93
154
94
163
95
162
35
92
39
148
39
163
75
73
141
92
155
148
117
141
157
155
165
114
97
169
150
111
64
120
134
134
134
100
151
63
159
153
121
102
157
174
153
122
122
152
139
156
141
156
177
103
152
38
95
48
48
72
154
84
95
142
118
147
142
162
164
104
156
171
105
127
173
171
176
106
169
167
128
45
101
52
139
79
151
88
101
101
144
109
139
153
144
160
158
42
53
71
62
76
107
165
179
161
129
129
164
142
160
144
54
159
54
78
111
90
80
146
149
108
111
150
146
168
175
149
150
170
46
66
91
56
137
93
89
50
94
69
59
148
173
174
60
48
142
96
90
61
90
146
53
100
71
65
55
55
66
66
89
83
89
129
89
137
140
102
129
152
102
124
155
157
52
67
52
139
59
60
119
75
68
75
141
77
136
77
87
113
128
87
87
94
105
105
143
70
168
175
106
147
106
146
166
65
67
110
70
107
70
138
151
107
138
107
165
159
177
68
66
137
69
136
90
133
99
123
130
77
107
165
175
75
87
136
116
112
90
82
134
120
121
153
122
156
125
145
158
153
176
126
172
177
127
149
148
170
172
128
115
151
140
154
129
140
129
105
105
147
142
165
149
146
129
161
174
144
144
148
148
113
113
169
143
163
171
169
147
147
169
176
175
176
138
151
175
165
179
128
162
167
153
172
177
173
149
140
154
174
161
174
152
156
147
152
171
169
175
162
162
166
156
174
173
160
174
158
172
170
174
176
174
176
176
175
178
175
177
178
91
137
137
75
130
60
119
136
136
136
71
131
99
112
133
67
110
120
134
135
175
177
177
175
180
180
175
175
177
177
180
180
145
134
177
177
145
159
170
125
134
177
177
177
177
177
177
177
138
76
138
138
166
175
114
166
175
175
150
168
175
175
174
176
176
179
176
179
174
174
176
176
179
179
157
157
164
164
173
173
167
167
141
141
173
174
174
173
148
148
148
157
157
173
173
174
174
174
166
166
171
171
168
168
145
145
135
145
177
160
160
170
170
158
158
180
174
180
180
177
180
180
180
174
174
177
180
161
161
147
147
142
147
142
179
179
162
164
164
179
179
179
179
172
172
176
176
178
178
178
178
176
176
176
176
139
139
144
144
144
180
180
153
158
160
160
180
180
180
180
180
138
76
138
138
131
180
179
180
180
179
180
179
179
180
180
175
178
178
146
146
149
149
149
170
170
168
168
178
175
178
178
175
178
140
140
140
141
140
140
140
143
143
143
147
174
174
176
142
147
147
147
146
149
149
149
138
138
138
139
155
157
137
140
124
137
161
161
174
140
174
161
174
161
174
161
174
174
139
144
144
144
147
142
142
141
148
148
148
136
143
113
136
128
176
143
176
143
128
176
176
179
175
179
175
179
179
175
179
139
144
144
165
175
166
151
160
151
175
160
166
178
178
141
140
140
143
143
146
149
138
137
148
136
175
179
179
148
143
143
143
146
149
145
145
145
158
158
177
177
177
177
177
177
179
178
177
178
178
178
178
178
178
176
176
180
154
164
154
174
164
163
173
167
165
166
171
171
174
174
180
152
161
156
172
169
171
176
176
176
176
175
176
179
178
178
178
179
175
175
180
179
180
176
176
176
180
177
178
178
178
174
179
179
180
180
180
174
179
180
178
178
178
176
179
179
174
178
178
180
180
180
177
178
176
178
178
178
178
179
180
180
180
180

V : 
3 181
-0.5
0.5
-0.5
0.5
-0.5
0.5
-0.5
0.5
1.1102230246251565e-016
0.5
-0.25
1.1102230246251565e-016
0
-0.5
0.5
0
0.25
-0.5
0.5
0
0.5
-0.5
0.5
0
0
-0.5
-0.25
0.5
0.5
0.125
-0.25
-0.375
-0.5
0.25
-0.25
0.25
-0.5
0.5
-0.25
0.125
-0.5
0.5
-0.25
-0.5
0.5
-0.25
-0.25
-0.5
-0.375
0.5
0.5
-0.0625
-0.375
-0.5
0.125
-0.125
0.375
-0.5
0.5
-0.375
-0.5
0.5
-0.375
0.5
0.5
-0.375
-0.375
-0.5
0.5
0.5
-0.15625
-0.5
-0.5
0.5
0.25
0.375
-0.5
0.5
0.25
-0.5
0.5
0.25
0.25
-0.5
-0.125
0.5
0.5
0.3125
-0.125
-0.5
0.375
-0.375
0.125
-0.5
0.5
-0.125
-0.5
0.5
-0.125
-0.5
-0.5
-0.125
-0.125
-0.5
0.5
0.5
0.03125
-0.5
0.5
-0.5
-0.5
0.125
0.375
0.5
-0.5
0.125
0.375
0.5
-0.5
-0.5
0.375
0.125
0.125
-0.5
-0.5
0.5
0.5
0.5
0.21875
-0.5
0.5
-0.5
0.5
0.5
0.375
0.5
0.40625
-0.5
-0.2083333283662796
-0.2083333283662796
-0.2083333283662796
0.2083333283662796
-0.5
0.2083333283662796
-0.5
0.2083333283662796
0.20703125
-0.20703125
0.5
0.5
-0.011363636702299118
-0.28787878155708313
-0.28787878155708313
-0.011363636702299118
-0.28787878155708313
-0.011363636702299118
0.28787878155708313
0.011363636702299118
0.011363636702299118
0.28787878155708313
-0.5
-0.5
0.011363636702299118
0.28787878155708313
-0.5
-0.5
-0.28781884908676147
-0.010867387987673283
0.010548505932092667
0.28804421424865723
0.5
0.5
0.5
0.5
2.2204460492503131e-016
-0.018435942009091377
0.10661841183900833
0.2068452388048172
0.23928116261959076
-0.18790046870708466
-0.121045783162117
-0.5
-0.5
0.5
0.5
0.5
0.5
-0.5
-0.5
1.1102230246251565e-016
-0.25
0.5
-1.1102230246251565e-016
-0.5
0
0
0.5
-0.25
0.5
0.5
0.5
-0.375
0
0
-0.5
-0.5
-0.5
0.25
-0.5
0.125
0.5
-0.25
0.5
0
0.25
-0.5
-0.5
-0.25
0.25
0.5
-0.125
0.5
0.5
0.5
0.25
-0.25
-0.5
-0.5
-0.5
0.375
-0.5
0.3125
0.5
-0.375
0.25
0.125
-0.5
-0.5
-0.375
0.375
0.5
0.5
0.5
0.5
-0.125
-0.375
-0.5
-0.5
-0.5
-0.5
0.40625
0.5
0.375
0.25
-0.25
0.5
-0.375
0.5
0.5
0.5
-0.25
0.25
-0.5
-0.5
-0.5
0.125
-0.5
-0.0625
0.5
-0.125
-0.25
0.375
-0.5
-0.5
-0.125
0.125
0.5
0.5
0.5
0.5
0.375
0.125
-0.5
-0.5
-0.5
-0.5
0.21875
0.5
0.125
0.125
-0.125
-0.375
0.5
0.5
0.5
0.5
0.5
0.5
-0.125
0.125
0.375
-0.5
-0.5
-0.5
-0.5
-0.5
-0.5
-0.15625
0.03125
0.5
-0.125
-0.375
0.5
0.5
0.375
-0.5
-0.5
0.5
-0.375
0.2083333283662796
-0.5
-0.2083333283662796
-0.5
0.2083333283662796
0.2083333283662796
-0.2083333283662796
-0.2083333283662796
0.5
0.5
-0.20703125
0.20703125
0.28787878155708313
0.011363636702299118
-0.5
-0.5
-0.011363636702299118
-0.28787878155708313
-0.5
-0.5
-0.28787878155708313
-0.011363636702299118
-0.011363636702299118
-0.28787878155708313
0.28787878155708313
0.011363636702299118
0.011363636702299118
0.28787878155708313
0.5
0.5
0.5
0.5
0.010548505932092667
0.28804421424865723
-0.28781884908676147
-0.010867387987673283
-0.125
0.14343594014644623
0.24010777473449707
-0.2068452388048172
0.050000756978988647
0.14532913267612457
-0.18390122056007385
0.5
0.5
0.5
0.5
-0.5
-0.5
-0.5
-0.5
-0.5
-0.25
-0.25
0.5
0.5
0.5
0.5
0.5
0.5
0
0
-0.5
-0.375
-0.5
-0.5
-0.5
0
0
0.5
0
0.125
0.125
-0.5
-0.375
0
-0.5
0.5
0.5
0.5
0.5
0.5
0.5
0.25
-0.25
-0.5
-0.5
-0.5
-0.5
0.25
-0.25
0.5
0.25
0.3125
-0.0625
-0.5
-0.25
-0.5
0.5
0.5
0.5
0.5
0.5
0.375
-0.375
-0.5
-0.5
-0.5
-0.5
0.375
-0.375
0.375
0.40625
-0.15625
-0.375
0.5
0.5
0.5
0.5
-0.25
0.25
-0.5
-0.5
-0.5
-0.5
-0.25
0.25
0.5
-0.25
-0.0625
0.3125
-0.5
0.25
-0.5
0.5
0.5
0.5
0.5
0.5
0.125
-0.125
-0.5
-0.5
-0.5
-0.5
0.125
-0.125
0.125
0.21875
0.03125
-0.125
-0.5
-0.5
-0.5
-0.5
-0.5
0.125
-0.125
0.5
0.5
0.5
0.5
0.5
-0.5
-0.5
-0.125
0.375
0.125
-0.125
-0.15625
0.03125
0.21875
0.125
0.5
-0.375
0.375
-0.5
-0.375
-0.375
0.40625
0.375
-0.5
-0.2083333283662796
0.5
0.2083333283662796
0.2083333283662796
0.5
-0.2083333283662796
-0.5
-0.20703125
0.20703125
0.20703125
-0.20703125
-0.5
-0.5
-0.011363636702299118
-0.28787878155708313
0.5
0.5
0.011363636702299118
0.28787878155708313
-0.5
-0.5
-0.28787878155708313
-0.011363636702299118
0.5
0.5
0.28787878155708313
0.011363636702299118
0.010548505932092667
0.28804421424865723
-0.28781884908676147
-0.010867387987673283
-0.28781884908676147
-0.010867387987673283
0.010548505932092667
0.28804421424865723
0.125
-0.15763191878795624
0.23713159561157227
-0.1994047611951828
-0.081250756978988647
0.12461400032043457
-0.17579084634780884

**Comment by alecjacobson** [comment]
I can't reproduce this. Could you try compiling and running this small program (change paths accordingly):

```cpp
#include <igl/biharmonic_coordinates.h>
#include <igl/readDMAT.h>
int main(int argc, char * argv[])
{
  using namespace Eigen;
  MatrixXd V;
  MatrixXi T;
  igl::readDMAT("/Users/ajx/Downloads/V.txt",V);
  igl::readDMAT("/Users/ajx/Downloads/T.txt",T);
  MatrixXd W;
  igl::biharmonic_coordinates( 
    V,T,std::vector<std::vector<int> >({{0},{1},{2},{3},{4},{5},{6},{7}}),2,W);
}
```

_BTW, for posting text files you can use https://gist.github.com_

**Comment by zapan669** [comment]
Thank you Alec,
I try it and come back to you asap.

__________________________________________________________________________________________Hans GodardCharacter TD,  Naughty Dog





hans_godard@naughtydog.com

Date: Wed, 9 Sep 2015 07:07:04 -0700

**Comment by zapan669** [comment]
It seems Eigen::DynamicSparseMatrix is deprecated, I'm using Eigen 3.2.
Probably igl::readDMAT is calling it somehow because I dont get this compilation issue in my original code :/

**Comment by alecjacobson** [comment]
Hmmm. `igl::readDMAT` is only for dense matrices and isn't calling `Eigen::DynamicSparseMatrix`. In any case, using `Eigen::DynamicSparseMatrix` should only result in a deprecation **warning**, not an **error**.  Are you unable to compile the small example above? If you are able, does it run correctly?

**Comment by zapan669** [comment]
I can't compile it exactly because this is not allowed : 
std::vector<std::vector<int> >({{0},{1},{2},{3},{4},{5},{6},{7}})

I use this instead :
std::vector<std::vector<int> S( 8) ;
for (int ii=0; ii<8; ii++) {   S[ii]	= std::vector<int>( 1, ii ) ;   }

Then it's compiling and crashing to the same line in normal_derivative.cpp :
DD.setFromTriplets(IJV.begin(),IJV.end());

The vector of Triplet IJV is explosed in my debug I guess, values are .0 or -1.456e+144
![tetraharmonic](https://cloud.githubusercontent.com/assets/14187208/9802685/15fe0a5e-57d1-11e5-9d9b-74faa226ea12.jpg)

Its size is 25392, is it possible in your mind Alec ?

**Comment by alecjacobson** [comment]
The first issue is [again coming from the old vs version with poor c++11 support](https://github.com/libigl/libigl/issues/111). 

Just to be absolutely sure, the new program to try is:

```cpp

#include <igl/biharmonic_coordinates.h>
#include <igl/readDMAT.h>
int main(int argc, char * argv[])
{
  using namespace Eigen;
  MatrixXd V;
  MatrixXi T;
  igl::readDMAT("/Users/ajx/Downloads/V.txt",V);
  igl::readDMAT("/Users/ajx/Downloads/T.txt",T);
  MatrixXd W;
  std::vector<std::vector<int> >S(8);
  for(int ii=0; ii<8; ii++)
  { 
    S[ii] = std::vector<int>(1,ii);
  }
  igl::biharmonic_coordinates(V,T,S,2,W);
}
```

This works on my machine. With no compilation or runtime errors, with clang or gcc in debug and release mode.

If it doesn't work for you, can you please list your machine, compiler version, full compilation error or runtime stack trace.

**Comment by zapan669** [comment]
Yes it is exactly what I do,  to be more specific I get this issue if I perform : 

Eigen::SparseMatrix<double> N ;
igl::normal_derivative(V,T,N);

Here is my call stack 
![aaa](https://cloud.githubusercontent.com/assets/14187208/9804028/e63f539c-57dd-11e5-9327-a975a50b3c31.jpg)

I'm on windows7, VisualStudio2013

**Comment by alecjacobson** [comment]
which (exact) version of Eigen do you have?

It's hard, if I can't also reproduce the issue. If you compile in Debug, then when it's crashing is an assert firing? Or how is it crashing, bad memory access? 

Or can you try changing in `normal_derivative.cpp`:

```cpp
      IJV.resize(DDV.size());
      for(size_t f = 0;f<12;f++)
      {
        for(size_t e = 0;e<m;e++)
        {
          IJV.push_back(Triplet<Scalar>(DDI(e,f),DDJ(e,f),DDV(e,f)));
        }
      }
```

to


```cpp
      std::cout<<DDV.size()<<std::endl;
      IJV.resize(DDV.size());
      for(size_t f = 0;f<12;f++)
      {
        for(size_t e = 0;e<m;e++)
        {
          IJV.push_back(Triplet<Scalar>(DDI(e,f),DDJ(e,f),DDV(e,f)));
          std::cout<<DDI(e,f)<<","<<DDJ(e,f)<<","<<DDV(e,f)<<" ";
        }
      }
```

and then uploading the output.

**Comment by zapan669** [comment]
I did not try yet but first question, is that normal you .resize() then push_back() in the loop ?

**Comment by alecjacobson** [comment]
Huh. Indeed that's suspicious, but should have only resulted in a "performance" bug (fixed in de264268db620813a3af09dbf563892c2cf772c4). That shouldn't have affected `DDV` above that though... You could try now after  `git pull`ing.

**Comment by zapan669** [comment]
I tried to fix it in my side in the same way.
But unfortunately my issue is something else ... still investigating

**Comment by alecjacobson** [comment]
I'm closing this since we strayed from the title problem a bit. If there's still another issue please start a new "github issue", or if `biharmonic_coordinates` is still crashing then reopen this one.
