### ISSUE TITLE
Memory leaks in TGA code

### ISSUE THREAD

**Issue by robertguetzkow** [libigl/libigl#1122]
In [tga.cpp](https://github.com/libigl/libigl/blob/e699d257fe860d4fd82709835e72438bd0cd1533/include/igl/copyleft/opengl2/tga.cpp#L366-L376) the `cmap` is not deallocated when `fread()` fails. Adding a `free(cmap);` should fix this. In [render_to_tga.cpp](https://github.com/libigl/libigl/blob/e699d257fe860d4fd82709835e72438bd0cd1533/include/igl/copyleft/opengl2/render_to_tga.cpp#L75) memory is allocated to hold an image, but if the TGA-file can't be opened the memory isn't deallocated. Adding `free(genericImage);` should fix this.

#### Check all that apply (change to `[x]`)
- [x] Windows
- [x] Mac OS X
- [x] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by jdumas** [comment]
Can you create a single PR to fix all those issues, instead of creating 1 thread per memory leak that you find?

**Comment by robertguetzkow** [comment]
Sure. Do you want me to put these in the same PR as the fix for `ply.h`? Hope you don't mind the extra issue tickets, otherwise I can merge them too.

**Comment by jdumas** [comment]
No I think the ply should be a separate PR (probably needs to be discarded altogether).

**Comment by robertguetzkow** [comment]
OK, I will create the PR tomorrow.

**Comment by jdumas** [comment]
Thanks!

**Comment by robertguetzkow** [comment]
Fixed in c9d0b35b6a11fb1da9b005f6e658d8a5acb876ec
