### ISSUE TITLE
Segfault during cotmatrix: tetrahedron test with CLANG

### ISSUE THREAD

**Issue by robertguetzkow** [libigl/libigl#1126]
There appears to be a bug in one of the functions called in [cotmatrix.cpp](https://github.com/libigl/libigl/blob/e699d257fe860d4fd82709835e72438bd0cd1533/tests/include/igl/cotmatrix.cpp#L97) that occasionally causes a segfault during testing with CLANG (apparently only with CLANG). Here are two build jobs that failed: 

- [Job #1737.4](https://travis-ci.org/libigl/libigl/jobs/509626667)
- [Job #1746.4](https://travis-ci.org/libigl/libigl/jobs/510265400)

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [x] Mac OS X
- [ ] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by jdumas** [comment]
The fact that it fails randomly on your PR (which is not touching cotmatrix at all), and seems fixed with Clang + Eigen 3.3 indicates a possible memory/segfault issue within an Eigen operation (like working with empty matrices). Would be nice to catch it still.

**Comment by robertguetzkow** [comment]
I see @alecjacobson already tried to fix it in PR #1066 which didn't seem to work.
