### ISSUE TITLE
Conversion  of .OBJ to Signed Distance Field uisng libigl

### ISSUE THREAD

**Issue by Yemibank** [libigl/libigl#1127]
[Describe your issue]
I am trying to convert ShapeNet dataset with .OBJ to Signed Distance Field using libigl but I could not do it. It always give error message as:

ajayi@apollo:~/SDF/build$ make
[  9%] Built target glad
[ 90%] Built target glfw
Scanning dependencies of target example_bin
[ 95%] Building CXX object CMakeFiles/example_bin.dir/main.cpp.o
/home/ajayi/SDF/main.cpp: In function ‘int main(int, char**)’:
/home/ajayi/SDF/main.cpp:144:42: error: no matching function for call to ‘readOBJ(const char [14], Eigen::MatrixXd&, Eigen::MatrixXi&, Eigen::MatrixXi&)’
   igl::readOBJ(DATA_PATH  "/1.obj", V,T,F);
                                          ^
In file included from /home/ajayi/libigl/include/igl/readOBJ.h:98:0,
                 from /home/ajayi/SDF/main.cpp:10:
/home/ajayi/libigl/include/igl/readOBJ.cpp:21:17: note: candidate: template<class Scalar, class Index> bool igl::readOBJ(std::__cxx11::string, std::vector<std::vector<_RealType> >&, std::vector<std::vector<_RealType> >&, std::vector<std::vector<_RealType> >&, std::vector<std::vector<Index> >&, std::vector<std::vector<Index> >&, std::vector<std::vector<Index> >&)
 IGL_INLINE bool igl::readOBJ(
                 ^
/home/ajayi/libigl/include/igl/readOBJ.cpp:21:17: note:   template argument deduction/substitution failed:
/home/ajayi/SDF/main.cpp:144:42: note:   ‘Eigen::MatrixXd {aka Eigen::Matrix<double, -1, -1>}’ is not derived from ‘std::vector<std::vector<_RealType> >’
   igl::readOBJ(DATA_PATH  "/1.obj", V,T,F);
                                          ^
In file included from /home/ajayi/libigl/include/igl/readOBJ.h:98:0,
                 from /home/ajayi/SDF/main.cpp:10:
/home/ajayi/libigl/include/igl/readOBJ.cpp:42:17: note: candidate: template<class Scalar, class Index> bool igl::readOBJ(FILE*, std::vector<std::vector<_RealType> >&, std::vector<std::vector<_RealType> >&, std::vector<std::vector<_RealType> >&, std::vector<std::vector<Index> >&, std::vector<std::vector<Index> >&, std::vector<std::vector<Index> >&)
 IGL_INLINE bool igl::readOBJ(
                 ^
/home/ajayi/libigl/include/igl/readOBJ.cpp:42:17: note:   template argument deduction/substitution failed:
/home/ajayi/SDF/main.cpp:144:42: note:   cannot convert ‘"../data/1.obj"’ (type ‘const char [14]’) to type ‘FILE* {aka _IO_FILE*}’
   igl::readOBJ(DATA_PATH  "/1.obj", V,T,F);
                                          ^
In file included from /home/ajayi/libigl/include/igl/readOBJ.h:98:0,
                 from /home/ajayi/SDF/main.cpp:10:
/home/ajayi/libigl/include/igl/readOBJ.cpp:233:17: note: candidate: template<class Scalar, class Index> bool igl::readOBJ(std::__cxx11::string, std::vector<std::vector<_RealType> >&, std::vector<std::vector<Index> >&)
 IGL_INLINE bool igl::readOBJ(
                 ^
/home/ajayi/libigl/include/igl/readOBJ.cpp:233:17: note:   template argument deduction/substitution failed:
/home/ajayi/SDF/main.cpp:144:42: note:   ‘Eigen::MatrixXd {aka Eigen::Matrix<double, -1, -1>}’ is not derived from ‘std::vector<std::vector<_RealType> >’
   igl::readOBJ(DATA_PATH  "/1.obj", V,T,F);
                                          ^
In file included from /home/ajayi/libigl/include/igl/readOBJ.h:98:0,
                 from /home/ajayi/SDF/main.cpp:10:
/home/ajayi/libigl/include/igl/readOBJ.cpp:250:17: note: candidate: template<class DerivedV, class DerivedTC, class DerivedCN, class DerivedF, class DerivedFTC, class DerivedFN> bool igl::readOBJ(std::__cxx11::string, Eigen::PlainObjectBase<OtherDerived>&, Eigen::PlainObjectBase<DerivedC>&, Eigen::PlainObjectBase<DerivedL>&, Eigen::PlainObjectBase<DerivedN>&, Eigen::PlainObjectBase<DerivedE>&, Eigen::PlainObjectBase<DerivedEMAP>&)
 IGL_INLINE bool igl::readOBJ(
                 ^
/home/ajayi/libigl/include/igl/readOBJ.cpp:250:17: note:   template argument deduction/substitution failed:
/home/ajayi/SDF/main.cpp:144:42: note:   candidate expects 7 arguments, 4 provided
   igl::readOBJ(DATA_PATH  "/1.obj", V,T,F);
                                          ^
In file included from /home/ajayi/libigl/include/igl/readOBJ.h:98:0,
                 from /home/ajayi/SDF/main.cpp:10:
/home/ajayi/libigl/include/igl/readOBJ.cpp:325:17: note: candidate: template<class DerivedV, class DerivedF> bool igl::readOBJ(std::__cxx11::string, Eigen::PlainObjectBase<OtherDerived>&, Eigen::PlainObjectBase<DerivedC>&)
 IGL_INLINE bool igl::readOBJ(
                 ^
/home/ajayi/libigl/include/igl/readOBJ.cpp:325:17: note:   template argument deduction/substitution failed:
/home/ajayi/SDF/main.cpp:144:42: note:   candidate expects 3 arguments, 4 provided
   igl::readOBJ(DATA_PATH  "/1.obj", V,T,F);
                                          ^
CMakeFiles/example_bin.dir/build.make:62: recipe for target 'CMakeFiles/example_bin.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/example_bin.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/example_bin.dir/all' failed
make[1]: *** [CMakeFiles/example_bin.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Kindly help.

Thank you.

Ajayi Ebenezer A
#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [x ] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by alecjacobson** [comment]
I'm guessing that you should replace:

    igl::readOBJ(DATA_PATH "/1.obj", V,T,F);

with

    igl::readOBJ(DATA_PATH "/1.obj", V,F);

If that doesn't work or you still have errors. Please post you full source code (or even better a minimal example).

**Comment by Yemibank** [comment]
Okay.

Thank you.

**Comment by jdumas** [comment]
Did this fix your problem?

**Comment by Yemibank** [comment]
No.

I will post the code now.

Thank you.

Ajayi Ebenezer Akinyemi

**Comment by Yemibank** [comment]
This is the code.

#include <igl/cat.h>
#include <igl/edge_lengths.h>
#include <igl/parula.h>
#include <igl/per_edge_normals.h>
#include <igl/per_face_normals.h>
#include <igl/per_vertex_normals.h>
#include <igl/point_mesh_squared_distance.h>
#include <igl/readMESH.h>
#include <igl/readOFF.h>
#include <igl/readOBJ.h>
#include <igl/signed_distance.h>
#include <igl/slice_mask.h>
#include <igl/marching_tets.h>
#include <igl/upsample.h>
#include <igl/opengl/glfw/Viewer.h>
#include <igl/writeOBJ.h>
#include <Eigen/Sparse>
#include <iostream>

#include "data_path.h"

Eigen::MatrixXd V;
Eigen::MatrixXi T,F;
igl::AABB<Eigen::MatrixXd,3> tree;
Eigen::MatrixXd FN,VN,EN;
Eigen::MatrixXi E;
Eigen::VectorXi EMAP;
double max_distance = 1;

double slice_z = 0.5;
bool overlay = false;

void update_visualization(igl::opengl::glfw::Viewer & viewer)
{
  using namespace Eigen;
  using namespace std;
  Eigen::Vector4d plane(
    0,0,1,-((1-slice_z)*V.col(2).minCoeff()+slice_z*V.col(2).maxCoeff()));
  MatrixXd V_vis;
  MatrixXi F_vis;
  // Extract triangle mesh slice through volume mesh and subdivide nasty
  // triangles
  {
    VectorXi J;
    SparseMatrix<double> bary;
    {
      // Value of plane's implicit function at all vertices
      const VectorXd IV = 
        (V.col(0)*plane(0) + 
         V.col(1)*plane(1) + 
         V.col(2)*plane(2)).array()
        + plane(3);
      igl::marching_tets(V,T,IV,V_vis,F_vis,J,bary);
      igl::writeOBJ("vis.obj",V_vis,F_vis);
    }
    while(true)
    {
      MatrixXd l;
      igl::edge_lengths(V_vis,F_vis,l);
      l /= (V_vis.colwise().maxCoeff() - V_vis.colwise().minCoeff()).norm();
      const double max_l = 0.03;
      if(l.maxCoeff()<max_l)
      {
        break;
      }
      Array<bool,Dynamic,1> bad = l.array().rowwise().maxCoeff() > max_l;
      MatrixXi F_vis_bad, F_vis_good;
      igl::slice_mask(F_vis,bad,1,F_vis_bad);
      igl::slice_mask(F_vis,(bad!=true).eval(),1,F_vis_good);
      igl::upsample(V_vis,F_vis_bad);
      F_vis = igl::cat(1,F_vis_bad,F_vis_good);
    }
  }

  // Compute signed distance
  VectorXd S_vis;
  {
    VectorXi I;
    MatrixXd N,C;
    // Bunny is a watertight mesh so use pseudonormal for signing
    signed_distance_pseudonormal(V_vis,V,F,tree,FN,VN,EN,EMAP,S_vis,I,C,N);
  }
  // push to [0,1] range
  S_vis.array() = 0.5*(S_vis.array()/max_distance)+0.5;
  MatrixXd C_vis;
  // color without normalizing
  igl::parula(S_vis,false,C_vis);


  const auto & append_mesh = [&C_vis,&F_vis,&V_vis](
    const Eigen::MatrixXd & V,
    const Eigen::MatrixXi & F,
    const RowVector3d & color)
  {
    F_vis.conservativeResize(F_vis.rows()+F.rows(),3);
    F_vis.bottomRows(F.rows()) = F.array()+V_vis.rows();
    V_vis.conservativeResize(V_vis.rows()+V.rows(),3);
    V_vis.bottomRows(V.rows()) = V;
    C_vis.conservativeResize(C_vis.rows()+V.rows(),3);
    C_vis.bottomRows(V.rows()).rowwise() = color;
  };
  if(overlay)
  {
    append_mesh(V,F,RowVector3d(0.8,0.8,0.8));
  }
  viewer.data().clear();
  viewer.data().set_mesh(V_vis,F_vis);
  viewer.data().set_colors(C_vis);
  viewer.core.lighting_factor = overlay;
}

bool key_down(igl::opengl::glfw::Viewer& viewer, unsigned char key, int mod)
{
  switch(key)
  {
    default:
      return false;
    case ' ':
      overlay ^= true;
      break;
    case '.':
      slice_z = std::min(slice_z+0.01,0.99);
      break;
    case ',':
      slice_z = std::max(slice_z-0.01,0.01);
      break;
  }
  update_visualization(viewer);
  return true;
}

int main(int argc, char *argv[])
{
  using namespace Eigen;
  using namespace std;

  cout<<"Usage:"<<endl;
  cout<<"[space]  toggle showing surface."<<endl;
  cout<<"'.'/','  push back/pull forward slicing plane."<<endl;
  cout<<endl;

  // Load mesh: (V,T) tet-mesh of convex hull, F contains original surface
  // triangles
  igl::readOBJ(DATA_PATH  "/1.obj", V,F);

  //igl::readMESH(TUTORIAL_SHARED_PATH "/bunny.mesh",V,T,F);


  // Encapsulated call to point_mesh_squared_distance to determine bounds
  {
    VectorXd sqrD;
    VectorXi I;
    MatrixXd C;
    igl::point_mesh_squared_distance(V,V,F,sqrD,I,C);
    max_distance = sqrt(sqrD.maxCoeff());
  }

  // Precompute signed distance AABB tree
  tree.init(V,F);
  // Precompute vertex,edge and face normals
  igl::per_face_normals(V,F,FN);
  igl::per_vertex_normals(
    V,F,igl::PER_VERTEX_NORMALS_WEIGHTING_TYPE_ANGLE,FN,VN);
  igl::per_edge_normals(
    V,F,igl::PER_EDGE_NORMALS_WEIGHTING_TYPE_UNIFORM,FN,EN,E,EMAP);

  // Plot the generated mesh
  igl::opengl::glfw::Viewer viewer;
  update_visualization(viewer);
  viewer.callback_key_down = &key_down;
  viewer.data().show_lines = false;
  viewer.launch();
}

Thank you
