### ISSUE TITLE
Random crash in Release, 100% reproducible in Debug with tutorial 710_SCAF_bin

### ISSUE THREAD

**Issue by FrankEscobar** [libigl/libigl#1129]
In Release sometimes it crash (also other times it just hangs) but it is fully reproducible in Debug mode.

The crash is thrown in Triangle.c

Called from scaf.cpp
igl::triangle::triangulate(V, E, H, std::basic_string<char>("qYYQ"), uv2, s.s_T); -> divconqdelaunay

It doesn't happen with any mesh of course but with some really basic ones like the attached one.

Regards F.
[temp.zip](https://github.com/libigl/libigl/files/3012275/temp.zip)

**Comment by jiangzhongshi** [comment]
Hi,

This is expected behavior. Since the simple code in tutorial only deals with meshes with disk topology. I will add clarification.

**Comment by jiangzhongshi** [comment]
The code in the original complete repo will show how to do multiple boundary.

**Comment by jdumas** [comment]
Is it possible to prevent the crash and spit an error message instead?

**Comment by jiangzhongshi** [comment]
I can do that, yes
