### ISSUE TITLE
MIQ Performance

### ISSUE THREAD

**Issue by csverma** [libigl/libigl#113]
Hello,

I am running "MIQ" software for 250,000 triangles which takes almost 30-40 minutes on 16GB RAM
running Ubuntu 15.04 with optimization level set to O3 to all the components.

Is this an expected performance of MIQ implementation or I should tune certain parameters ?

Thanks.
csv

**Comment by danielepanozzo** [comment]
MIQ is just a solver, it depends on what problem you solve with it.
As a reference, tutorial 505_MIQ takes ~4seconds on my laptop (MacOSX 10.10.4, i7 3Ghz, 16Gb ram)
