### ISSUE TITLE
Using LIBIGL_DIR for CMake import 

### ISSUE THREAD

**Issue by martinruenz** [libigl/libigl#1136]
Typically, a cmake library can be imported by setting the variable `<libname>_DIR`, which corresponds to setting `-DLIBIGL_DIR="..."` here.

However, I run into a cmake error when I try using this idiom. Here is a minimal example showing what I am trying to do:

```bash
# Create cmake
echo "cmake_minimum_required(VERSION 3.1)
project(example)
find_package(LIBIGL REQUIRED QUIET)
add_executable(example main.cpp)
target_link_libraries(example igl::core)" > CMakeLists.txt

# empty dummy cpp file
touch main.cpp

# prepare libigl (download, build, install locally)
git clone --depth=1 https://github.com/libigl/libigl
cd libigl
mkdir build
cd build
cmake \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX=../install \
  ..
make -j8 && make install
cd ../..

# Try building project
mkdir build
cd build
cmake \
  -DCMAKE_BUILD_TYPE=Release \
  -DLIBIGL_DIR=libigl/install/share/libigl/cmake \
  ..
``` 

The error message reads:

> CMake Error at libigl/install/share/libigl/cmake/libigl-config.cmake:42 (target_link_libraries):
>   Cannot specify link libraries for target "igl::core" which is not built by
>   this project.
> Call Stack (most recent call first):
>   CMakeLists.txt:3 (find_package)

I think the reason this happens is because the [command](https://github.com/libigl/libigl/blob/e699d257fe860d4fd82709835e72438bd0cd1533/cmake/libigl-config.cmake.in#L18) (generated at: install_dir/share/libgl/cmake/libigl-config.cmake):
`target_link_libraries(igl::core INTERFACE PkgConfig::Eigen3)`

Does not fit the **imported** library (generated at: install_dir/share/libgl/cmake/libigl-export.cmake):
`add_library(igl::core STATIC IMPORTED)`

Is this a bug or do I misunderstand something and this is the intended behaviour?

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [x] Linux

**Comment by jdumas** [comment]
Hi. Are you trying to use an _installed_ version of libigl, or are you trying to import libigl in config mode? Also, are you using the version on the `master` branch, or the current `dev` branch?

**Comment by martinruenz** [comment]
Hey,
as in the script above, I would like to locally build libigl and import it in config mode. I was using the master branch.

**Comment by jdumas** [comment]
Do you still have the issue in the `dev` branch?

**Comment by martinruenz** [comment]
The error seems to be gone on `dev`. Thanks for the quick reply!
