### ISSUE TITLE
Embree.dll not found VS2017

### ISSUE THREAD

**Issue by ryanlukejohns** [libigl/libigl#1137]
I am having trouble running example 606_AmbientOcclusion, with a system error popup stating that "The code execution cannot proceed because embree.dll was not found.  Reinstalling the program may fix this problem."  

Running Windows 10 x64 and installed using the default settings with cmake (Embree is checked to be included).  Have you encountered this before?  Any ideas to what I'm doing wrong, or is this a bug?

#### Check all that apply (change to `[x]`)
- [x ] Windows
- [ ] Mac OS X
- [ ] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by jdumas** [comment]
If you're on the master branch, please try again with the `dev` branch (don't forget to delete your build folder in the meantime).

**Comment by ryanlukejohns** [comment]
Oops, that did the trick...thanks!
