### ISSUE TITLE
MIQ: Degenerate FUV matrix

### ISSUE THREAD

**Issue by csverma** [libigl/libigl#114]
Hello,

In the "miq" algorithm, I was expecting the FUV will have three distinct nodes for
every triangle corresponding to F matrix. 

But in some cases ( especially for not so smooth triangle meshes) I get few triangles
in FUV, which are degenerate i.e. two of the vertices are same. Therefore, i am wondering
if the MIQ requires some specific clean triangulation as an input.

Thanks.
csv

**Comment by danielepanozzo** [comment]
MIQ needs a manifold triangle mesh as input. It is NOT guaranteed to give you back a bijective UV map, i.e. you can have triangles that are degenerate or even worse they are flipped in UV space.

Increasing the stiffening iterations helps with this, but it is not guaranteed to work. The reference for this is the original paper: https://www.graphics.rwth-aachen.de/publication/44/bommes_zimmer_2009_siggraph_011.pdf
