### ISSUE TITLE
I try to run cmake but I have the following error

### ISSUE THREAD

**Issue by Yemibank** [libigl/libigl#1143]
[Describe your issue]
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
 
 libigl not found

I have clone libigl into root directory of my system

Kindly help.

Ajayi Ebenezer Akinyemi

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [ x] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by jdumas** [comment]
You need to put libigl in a folder where the `FindLIBIGL.cmake` will find it. See the list of folders being searched [here](https://github.com/libigl/libigl-example-project/blob/6860585e3744825fdb130b0c90408cb6e5621cca/cmake/FindLIBIGL.cmake#L10).
