### ISSUE TITLE
I am trying to compile my program using cmake .. 

### ISSUE THREAD

**Issue by Yemibank** [libigl/libigl#1144]
[Describe your issue]

I am trying to compile my program using cmake ..  and I got the following error: 
CMake Error at CMakeLists.txt:35 (add_executable):
  Target "tyf_bin" links to target "igl::opengl_viewer" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

Kindly help

Ajayi Ebenezer Akinyemi

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [x ] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by jdumas** [comment]
You need to enable the cmake option you need, e.g. `LIBIGL_WITH_OPENGL_GLFW`.

**Comment by Yemibank** [comment]
This is my code for the cmake  that bring about the error.

cmake_minimum_required(VERSION 3.1)
project(tyf)

set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${CMAKE_CURRENT_SOURCE_DIR}/cmake)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")

# libigl
option(LIBIGL_USE_STATIC_LIBRARY "Use libigl as static library" OFF)
option(LIBIGL_WITH_ANTTWEAKBAR      "Use AntTweakBar"    OFF)
option(LIBIGL_WITH_CGAL             "Use CGAL"           OFF)
option(LIBIGL_WITH_COMISO           "Use CoMiso"         OFF)
option(LIBIGL_WITH_CORK             "Use Cork"           OFF)
option(LIBIGL_WITH_EMBREE           "Use Embree"         OFF)
option(LIBIGL_WITH_LIM              "Use LIM"            OFF)
option(LIBIGL_WITH_MATLAB           "Use Matlab"         OFF)
option(LIBIGL_WITH_MOSEK            "Use MOSEK"          OFF)
option(LIBIGL_WITH_NANOGUI          "Use Nanogui menu"   OFF)
option(LIBIGL_WITH_OPENGL           "Use OpenGL"         ON)
option(LIBIGL_WITH_OPENGL_GLFW      "Use GLFW"           ON)
option(LIBIGL_WITH_PNG              "Use PNG"            OFF)
option(LIBIGL_WITH_PYTHON           "Use Python"         OFF)
option(LIBIGL_WITH_TETGEN           "Use Tetgen"         OFF)
option(LIBIGL_WITH_TRIANGLE         "Use Triangle"       OFF)
option(LIBIGL_WITH_VIEWER           "Use OpenGL viewer"  ON)
option(LIBIGL_WITH_XML              "Use XML"            OFF)

find_package(LIBIGL REQUIRED QUIET)
# find_package(Boost 1.65 REQUIRED COMPONENTS filesystem system)
find_package(Boost 1.58 REQUIRED COMPONENTS filesystem system)

include_directories(${Boost_INCLUDE_DIRS})

# Add your project files
file(GLOB SRCFILES *.cpp)
add_executable(${PROJECT_NAME}_bin main.cpp)
target_link_libraries(${PROJECT_NAME}_bin igl::core igl::viewer ${Boost_LIBRARIES})

**Comment by jdumas** [comment]
As I said before, you need to change `igl::opengl_viewer` into `igl::opengl_glfw` ...
