### ISSUE TITLE
Errror in my program using make command

### ISSUE THREAD

**Issue by Yemibank** [libigl/libigl#1145]
[Describe your issue]
I am trying to compile my program with make command and this error message appear. All the include files are available in the source code:
 
[  9%] Built target glad
[ 90%] Built target glfw
Scanning dependencies of target syf_bin
[ 95%] Building CXX object CMakeFiles/syf_bin.dir/main.cpp.o
/home/ajayi/MyProject/main.cpp:1:25: fatal error: igl/readOFF.h: No such file or directory
 #include <igl/readOFF.h>
                         ^
compilation terminated.
CMakeFiles/syf_bin.dir/build.make:62: recipe for target 'CMakeFiles/syf_bin.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/syf_bin.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:708: recipe for target 'CMakeFiles/syf_bin.dir/all' failed
make[1]: *** [CMakeFiles/syf_bin.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

All the include files are available in the source code.
 
#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [x] Linux

Kindly help!

Thank you.

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by jdumas** [comment]
Please post your cmake file when reporting an error, we do not have crystal ball ...

**Comment by Yemibank** [comment]
Thank you for the information. Find below my cmake file. 

# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ajayi/MyProject

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ajayi/MyProject/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/ajayi/MyProject/build && $(CMAKE_COMMAND) -E cmake_progress_start /home/ajayi/MyProject/build/CMakeFiles /home/ajayi/MyProject/build/glfw/CMakeFiles/progress.marks
	cd /home/ajayi/MyProject/build && $(MAKE) -f CMakeFiles/Makefile2 glfw/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ajayi/MyProject/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/ajayi/MyProject/build && $(MAKE) -f CMakeFiles/Makefile2 glfw/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/ajayi/MyProject/build && $(MAKE) -f CMakeFiles/Makefile2 glfw/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/ajayi/MyProject/build && $(MAKE) -f CMakeFiles/Makefile2 glfw/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/ajayi/MyProject/build && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... rebuild_cache"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... test"
	@echo "... edit_cache"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/ajayi/MyProject/build && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system


The error generated is as follows:

ajayi@apollo:~MyProject/build$ make
[  9%] Built target glad
[ 90%] Built target glfw
[ 95%] Building CXX object CMakeFiles/sdf_bin.dir/main.cpp.o
/home/ajayi/MyProject/main.cpp:1:25: fatal error: igl/readOFF.h: No such file or directory
 #include <igl/readOFF.h>
                         ^
compilation terminated.
CMakeFiles/syf_bin.dir/build.make:62: recipe for target 'CMakeFiles/syf_bin.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/sdf_bin.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:708: recipe for target 'CMakeFiles/syf_bin.dir/all' failed
make[1]: *** [CMakeFiles/syf_bin.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2




Kindly help
Thank you

**Comment by jdumas** [comment]
Please post the *cmake* file you are using, not the makefile generated by cmake itself...

**Comment by alecjacobson** [comment]
hopefully this is resolved by the changes to cmake setup
