### ISSUE TITLE
tutorial/shared folder removed - how do I run the Python tutorial examples?

### ISSUE THREAD

**Issue by mikeroberts3000** [libigl/libigl#1146]
Hello there,

The `tutorial/shared` folder was removed (a1e026fbe65b544ee9b49d93374c643ab158ed01), but the Python tutorial examples still refer to this folder. Is there a separate download link for the `tutorial/shared` folder now? What is the recommended way to obtain the simple models (e.g., cube, beetle, etc) that used to be in this folder, so the Python examples can be executed?

Cheers,
Mike

#### Check all that apply (change to `[x]`)
- [x] Windows
- [X] Mac OS X
- [x] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by jdumas** [comment]
If you compile the tutorials (`LIBIGL_BUILD_TUTORIALS=ON`), then the function [igl_download_tutorial_data()](https://github.com/libigl/libigl/blob/c9d0b35b6a11fb1da9b005f6e658d8a5acb876ec/tutorial/CMakeLists.txt#L18) will be called, which should download the tutorial shared data in the expected destination.

**Comment by mikeroberts3000** [comment]
Ah. thanks for the pro tip. That sounds about right. I didn't see the `LIBIGL_BUILD_TUTORIALS` option in the CMake GUI when I was building libigl. I see {`LIBIGL_USE_STATIC_LIBRARY`, `LIBIGL_WITHOUT_COPYLEFT`, `LIBIGL_WITH_CGAL`, ..., `LIBIGL_WITH_XML`} but I don't see `LIBIGL_BUILD_TUTORIALS`. Is this intended?

**Comment by mikeroberts3000** [comment]
Ah, I see what's happening. This is my mistake. I wasn't pointing CMake to the top-level libigl folder. Instead, I was pointing it to the python folder. So I was building the python bindings, but I wasn't building (i.e., downloading) the tutorials. Taking this shortcut had worked for me in the past, when the shared folder was checked into the repository, but is no longer valid. That's why the `LIBIGL_BUILD_TUTORIALS` option wasn't showing up for me in the CMake GUI. The solution was to point CMake to the top-level libigl folder. Thank you so much for your help @jdumas :smile:

**Comment by mikeroberts3000** [comment]
Actually, there is still a minor issue here. The tutorial data gets downloaded to `libigl/tutorial/data`, but `libigl/python/tutorial/shared.py` assumes that the data is located at `libigl/tutorial/shared`. So the python tutorial examples still don't work out-of-the-box. The solution was to modify `libigl/python/tutorial/shared.py` to point to the new data location. I'll reopen this issue as a reminder.

**Comment by jdumas** [comment]
I think this is fixed in the `dev` branch, so I suggest you to use it.

**Comment by mikeroberts3000** [comment]
Sounds good, thanks again @jdumas :smile:

**Comment by jdumas** [comment]
Also, note that it's not "expected" for libigl to download the tutorial data if you are using libigl as a library (i.e. including the CMake via a `add_subdirectory()`). However, it will be downloaded when you compile the top-level project, or the tutorials directly.
