### ISSUE TITLE
heatgeosics compilation

### ISSUE THREAD

**Issue by Aeoll** [libigl/libigl#1149]
#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [ ] Linux

Hi, C++ novice attempting to run the Heat Geodesics sample using the CMakeLists.txt in the root folder & VS2017.
The generation solution fails to run with the error: `Expression: vector subscript out of range`

I've also tried including heat_geodesic into a Houdini plugin (I've successfully compiled a plugin based on EigenDecomposition sample). In this case the build fails with 'grad_tri: identifier not found' and 'grad_tet: identifier not found'

`note: 'grad_tri': function was not declared in the template definition context and can be found only via argument-dependent lookup in the instantiation context`

Many Thanks

**Comment by jdumas** [comment]
1. Can you compile the tutorial code on its own?
2. Can you share the exact code you are trying to compile using libigl.
3. Are you trying to compile in header-only mode, or in static mode? If one doesn't work, can you try the other?

**Comment by Aeoll** [comment]
1. If this means creating a build folder in tutorial/716_HeatGeodesics and running cmake ../ from there - I'm not able to get this to work as it can't find the necessary paths? If it means something else let me know
2. Sure, I've added you to my github repo
3. header-only I assume? For static I would follow this guide? https://libigl.github.io/static-library/

**Comment by jdumas** [comment]
In 1. I mean compiling the libigl folder from the root or from the `tutorial` folder. And for 2. would be best if you could share a MWE for everyone so we can reproduce the situation. I can't promise to have the time to check you situation soon.

**Comment by Aeoll** [comment]
I compiled libigl from root which output solutions to libigl\build\tutorial. All of these solutions run fine in VS - apart from HeatGeodesics.

**Comment by jdumas** [comment]
Ok, so compiling is fine, but tutorial runs with an error under VS. We can look into and hopefully add a unit test as needed.

**Comment by BruegelN** [comment]
Hi there,

currently I only have VS2019 nearby. But using the dev branch I've been able to reporduce your error!
However changing Eigen to 3.3.7 (LIBIGL_EIGEN_VERSION in cmake) solved the issue for me. See screenshot below:
![libigl_geodesic-heat](https://user-images.githubusercontent.com/9728182/58278558-9b934180-7d9c-11e9-83b7-82074c95bcf0.PNG)

@Aeoll could you try again with Eigen 3.3.7?

**Comment by jdumas** [comment]
Should be fixed by #1288

**Comment by dmitterberger** [comment]
Hello, 

I am using libIGL in openframeworks & VS2017 and everything runs fine. When I tried using Heat Geodesics the build fails with 'grad_tri: identifier not found' and 'grad_tet: identifier not found'. Any idea what it could be?

Many Thanks
