### ISSUE TITLE
How to get projection/other matrices in libigl?

### ISSUE THREAD

**Issue by whatyougonnado** [libigl/libigl#1151]
[Describe your issue]
Hi! I want to know the vertex position of my obj at 2D image viewer from ```viewer.launch();```.

Is there any function **donwload 2D image** at image on viewer and **final result projection or other matrices** that I can get?
*Thank you in advance*

**Comment by BruegelN** [comment]
Hi @whatyougonnado,

Yes you can take a screenshot of your scene. This is described in tutorial 607_ScreenCapture (https://libigl.github.io/tutorial/#screen-capture) or have a look at the corresponding source code (https://github.com/libigl/libigl/blob/master/tutorial/607_ScreenCapture/main.cpp#L12)

But I don't know what you mean by **final result projection or other matrices**? Maybe ViewerCores' draw() method might help you: https://github.com/libigl/libigl/blob/master/include/igl/opengl/ViewerCore.cpp#L97 . The `view` , `porj` & `norm` matricies are public members of ViewerCore: https://github.com/libigl/libigl/blob/master/include/igl/opengl/ViewerCore.h#L131.

**Comment by whatyougonnado** [comment]
Thank you! That's what I want =)
I am going to use parameters at ViewerCore for reproducing output image of viewer
