### ISSUE TITLE
I am trying to complie a cmake file and run into this error "No such file or directory"

### ISSUE THREAD

**Issue by Yemibank** [libigl/libigl#1154]
[Describe your issue]
I am trying to run make on the below cmake file and run into this error "No such file or directory"

This is my cmake file
#include <igl/readOFF.h>
#include <igl/readPLY.h>
#include <igl/readOBJ.h>
#include <igl/cat.h>
#include <igl/edge_lengths.h>
#include <igl/parula.h>
#include <igl/per_edge_normals.h>
#include <igl/per_face_normals.h>
#include <igl/per_vertex_normals.h>
#include <igl/point_mesh_squared_distance.h>
#include <igl/signed_distance.h>
#include <igl/WindingNumberAABB.h>
#include <igl/parallel_for.h>
#include <igl/upsample.h>
#include <igl/viewer/Viewer.h>
#include <Eigen/Sparse>

#include <iostream>
#include <string>
#include <fstream>
#include <chrono>

//#include <igl/opengl/glfw/Viewer.h>

#include "tutorial_shared_path.h"

using namespace std;

Eigen::MatrixXd V;
Eigen::MatrixXd normalizedV;
Eigen::MatrixXi F;
Eigen::MatrixXd GV;
Eigen::VectorXd S_signed;
igl::AABB<Eigen::MatrixXd,3> tree;

static igl::WindingNumberAABB<Eigen::RowVector3d,
                              Eigen::MatrixXd,
                              Eigen::MatrixXi> hier;

void add_wireframe(igl::viewer::Viewer & viewer, Eigen::MatrixXd m, Eigen::MatrixXd M, Eigen::RowVector3d color)

Error generated as follows:
apollo@apollo:~/signed/build$ cmake ..
-- Creating target: igl::core (igl)
-- Creating target: igl::opengl (igl_opengl)
-- Creating target: igl::opengl_glfw (igl_opengl_glfw)
-- Using X11 for window creation
-- Configuring done
-- Generating done
-- Build files have been written to: /home/apollo/signed/build
apollo@apollo:~/signed/build$ make 
[ 80%] Built target glfw
[ 90%] Built target glad
Scanning dependencies of target example_bin
[ 95%] Building CXX object CMakeFiles/example_bin.dir/main.cpp.o
/home/apollo/signed/main.cpp:15:31: fatal error: igl/viewer/Viewer.h: No such file or directory
 #include <igl/viewer/Viewer.h>
                               ^
compilation terminated.
CMakeFiles/example_bin.dir/build.make:62: recipe for target 'CMakeFiles/example_bin.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/example_bin.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/example_bin.dir/all' failed
make[1]: *** [CMakeFiles/example_bin.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Pls kindly help.

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [x ] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by jdumas** [comment]
`#include <igl/viewer/Viewer.h>` is deprecated, you need to update your code following existing examples (cf. tutorials or example project).

**Comment by YemmyMMU** [comment]
I am trying to run make on the below cmake file and run into this error "No such file or directory"

This is my cmake file:

#include <igl/readOFF.h>
#include <igl/opengl/glfw/Viewer.h>
#include <igl/cat.h>
#include <igl/edge_lengths.h>
#include <igl/readPLY.h>
#include <igl/readOBJ.h>

#include <igl/edge_lengths.h>
#include <igl/parula.h>
#include <igl/per_edge_normals.h>
#include <igl/per_face_normals.h>
#include <igl/per_vertex_normals.h>
#include <igl/point_mesh_squared_distance.h>
#include <igl/signed_distance.h>
#include <igl/WindingNumberAABB.h>
#include <igl/parallel_for.h>
#include <igl/upsample.h>
#include <igl/parser.h>
#include <Eigen/Sparse>

#include
#include
#include
#include

// #include
// #include <boost/filesystem.hpp>

#include "tutorial_shared_path.h"

using namespace std;

Eigen::MatrixXd V;
Eigen::MatrixXd normalizedV;
Eigen::MatrixXi F;
Eigen::MatrixXd GV;
Eigen::VectorXd S_signed;
igl::AABBEigen::MatrixXd,3 tree;

The error is as follows:
ajayi@apollo:/singed/build$ cmake ..
-- Creating target: igl::core (igl)
-- Using header-only CGAL
-- Targetting Unix Makefiles
-- Using /usr/bin/c++ compiler.
-- __cplusplus is 201103
-- --> Do not link with Boost.Thread
-- Boost version: 1.58.0
-- Boost include dirs: /usr/include
-- Boost libraries:
-- Boost version: 1.58.0
-- Found the following Boost libraries:
-- thread
-- system
-- chrono
-- date_time
-- atomic
-- Using gcc version 4 or later. Adding -frounding-math
-- Creating target: igl::cgal (igl_cgal)
-- Creating target: igl::opengl (igl_opengl)
-- Creating target: igl::opengl_glfw (igl_opengl_glfw)
-- Using X11 for window creation
-- Boost version: 1.58.0
-- Found the following Boost libraries:
-- filesystem
-- system
-- Configuring done
-- Generating done
-- Build files have been written to: /singed/build
ajayi@apollo:/build$ make
[ 9%] Built target glad
[ 90%] Built target glfw
Scanning dependencies of target sdf_bin
[ 95%] Building CXX object CMakeFiles/sdf_bin.dir/main.cpp.o
/singed/main.cpp:1:25: fatal error: igl/readOFF.h: No such file or directory
#include <igl/readOFF.h>
^
compilation terminated.
CMakeFiles/sdf_bin.dir/build.make:62: recipe for target 'CMakeFiles/sdf_bin.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/sdf_bin.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:708: recipe for target 'CMakeFiles/sdf_bin.dir/all' failed
make[1]: *** [CMakeFiles/sdf_bin.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

Pls kindly help!

**Comment by jdumas** [comment]
1. Can you compile the tutorials, and the [libigl-example-project](https://github.com/libigl/libigl-example-project)?
2. If no, please tell us what went wrong. If yes, please check your project cmake to make sure you follow the same pattern.
3. If this still doesn't work, please post both your project's `CMakeLists.txt` and your `main.cpp`

**Comment by Yemibank** [comment]
Yes, I can compile the tutorials, and the libgl-example-project.

CMakeLists.txt
cmake_minimum_required(VERSION 3.1)
project(tyf)

set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH}
${CMAKE_CURRENT_SOURCE_DIR}/cmake)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")

# libigl
option(LIBIGL_USE_STATIC_LIBRARY "Use libigl as static library" OFF)
option(LIBIGL_WITH_ANTTWEAKBAR      "Use AntTweakBar"    OFF)
option(LIBIGL_WITH_CGAL             "Use CGAL"           OFF)
option(LIBIGL_WITH_COMISO           "Use CoMiso"         OFF)
option(LIBIGL_WITH_CORK             "Use Cork"           OFF)
option(LIBIGL_WITH_EMBREE           "Use Embree"         OFF)
option(LIBIGL_WITH_LIM              "Use LIM"            OFF)
option(LIBIGL_WITH_MATLAB           "Use Matlab"         OFF)
option(LIBIGL_WITH_MOSEK            "Use MOSEK"          OFF)
option(LIBIGL_WITH_NANOGUI          "Use Nanogui menu"   OFF)
option(LIBIGL_WITH_OPENGL           "Use OpenGL"         ON)
option(LIBIGL_WITH_OPENGL_GLFW      "Use GLFW"           ON)
option(LIBIGL_WITH_PNG              "Use PNG"            OFF)
option(LIBIGL_WITH_PYTHON           "Use Python"         OFF)
option(LIBIGL_WITH_TETGEN           "Use Tetgen"         OFF)
option(LIBIGL_WITH_TRIANGLE         "Use Triangle"       OFF)
option(LIBIGL_WITH_VIEWER           "Use OpenGL viewer"  ON)
option(LIBIGL_WITH_XML              "Use XML"            OFF)

find_package(LIBIGL REQUIRED QUIET)
# find_package(Boost 1.65 REQUIRED COMPONENTS filesystem system)
find_package(Boost 1.58 REQUIRED COMPONENTS filesystem system)

include_directories(${Boost_INCLUDE_DIRS})

# Add your project files
file(GLOB SRCFILES *.cpp)
add_executable(${PROJECT_NAME}_bin main.cpp)
target_link_libraries(${PROJECT_NAME}_bin igl::core igl::opengl_glfw
${Boost_LIBRARIES})


main.cpp
#include <igl/readOFF.h>
#include <igl/opengl/glfw/Viewer.h>
#include <igl/cat.h>
#include <igl/edge_lengths.h>
#include <igl/readOFF.h>
#include <igl/readPLY.h>
#include <igl/readOBJ.h>

#include <igl/edge_lengths.h>
#include <igl/parula.h>
#include <igl/per_edge_normals.h>
#include <igl/per_face_normals.h>
#include <igl/per_vertex_normals.h>
#include <igl/point_mesh_squared_distance.h>
#include <igl/signed_distance.h>
#include <igl/WindingNumberAABB.h>
#include <igl/parallel_for.h>
#include <igl/upsample.h>
//#include <igl/viewer/Viewer.h>
#include <igl/parser.h>
#include <Eigen/Sparse>

#include <iostream>
#include <string>
#include <fstream>
#include <chrono>

// #include <thread>
// #include <boost/filesystem.hpp>

#include "tutorial_shared_path.h"

using namespace std;

Eigen::MatrixXd V;
Eigen::MatrixXd normalizedV;
Eigen::MatrixXi F;
Eigen::MatrixXd GV;
Eigen::VectorXd S_signed;
igl::AABB<Eigen::MatrixXd,3> tree;

static igl::WindingNumberAABB<Eigen::RowVector3d,
                              Eigen::MatrixXd,
                              Eigen::MatrixXi> hier;

// double max_distance = 1;

void add_wireframe(igl::viewer::Viewer & viewer, Eigen::MatrixXd m,
Eigen::MatrixXd M, Eigen::RowVector3d color)
{
  // Corners of the bounding box
  Eigen::MatrixXd V_box(8,3);
  V_box <<
  m(0), m(1), m(2),
  M(0), m(1), m(2),
  M(0), M(1), m(2),
  m(0), M(1), m(2),
  m(0), m(1), M(2),
  M(0), m(1), M(2),
  M(0), M(1), M(2),
  m(0), M(1), M(2);

  // Edges of the bounding box
  Eigen::MatrixXi E_box(12,2);
  E_box <<
  0, 1,
  1, 2,
  2, 3,
  3, 0,
  4, 5,
  5, 6,
  6, 7,
  7, 4,
  0, 4,
  1, 5,
  2, 6,
  7 ,3;

  // Plot the corners of the bounding box as points
  viewer.data.add_points(V_box,color);

  // Plot the edges of the bounding box
  for (unsigned i=0;i<E_box.rows(); ++i)
    viewer.data.add_edges
    (
      V_box.row(E_box(i,0)),
      V_box.row(E_box(i,1)),
      color
    );

}

/*****
* Create a grid
* Input:
    num_grids- number of grids in x, y, z
    Vmin - minimum vertex location
    Vmax - maximum vertex location

  Output:
    GV - grid
*/
void create_grid(int num_grids, const Eigen::RowVector3d Vmin, const
Eigen::RowVector3d Vmax, Eigen::MatrixXd &GV)
{
  // std::chrono::steady_clock::time_point begin =
std::chrono::steady_clock::now();
  cout<<"------> Creating grid..."<<endl;
  const double step = (Vmax - Vmin).maxCoeff()/(double)num_grids;
  const Eigen::RowVector3i dim = (num_grids * ((Vmax - Vmin)/(Vmax -
Vmin).maxCoeff())).cast<int>();

  // cout<<"normalizedVmin "<<normalizedVmin<<endl;
  // cout<<"normalizedVmax "<<normalizedVmax<<endl;
  cout<<"------> step "<<step<<endl;
  cout<<"------> dim "<<dim<<endl;

  Eigen::MatrixXd gridV(dim(0) * dim(1) * dim(2), 3);
  // GV.resize(dim(0) * dim(1) * dim(2), 3);
  for(int zi = 0;zi < dim(2); zi++)
  {
    // lambda expression
    const auto lerp = [&](const int di, const int d)->double
      {return Vmin(d) + (double)di / (double)(dim(d) - 1) * (Vmax(d) -
Vmin(d)); };

    const double z = lerp(zi, 2);
    for(int yi = 0;yi < dim(1); yi++)
    {
      const double y = lerp(yi, 1);
      for(int xi = 0;xi < dim(0); xi++)
      {
        const double x = lerp(xi, 0);
        gridV.row(xi + dim(0) * (yi + dim(1) * zi)) = Eigen::RowVector3d(x,
y, z);
        // cout<<"row "<<xi+dim(0)*(yi + dim(1)*zi)<<"[x, y, z] = "<<x<<"
"<<y<<" "<<z<<endl;
      }
    }
  }

  GV = gridV;
  // std::chrono::steady_clock::time_point end=
std::chrono::steady_clock::now();
  // cout<<"Grid creating time
"<<(std::chrono::duration_cast<std::chrono::microseconds>(end -
begin).count()) /1000000.0 <<endl;
}

int main(int argc, char *argv[])
{

  bool visualize = false;
  int num_grids;

  if(argc < 2)
  {
    cout<<"No input file"<<endl;
    return -1;
  }

  string input = argv[1];
  string output = argv[2];

  if(argv[3] != NULL)
    num_grids = stoi(argv[3]);
  else{
    cout<<"No num_grids is specified, default value is used [50]"<<endl;
    num_grids = 50;
  }

  if(string(argv[4]) == "1")
  {
    visualize = true;
    cout<<"Visualize SET"<<endl;
  }

  cout<<"Loading "<<input<<endl;
  // Load a mesh model
  // igl::readOFF(TUTORIAL_SHARED_PATH"/bunny.off", V, F);
  // igl::readOFF(input, V, F);
  // igl::readPLY(input, V, F);
  // igl::readOBJ(input, V, F);
  // igl::readOFF(input, V, F);
  igl::readOFF(input, V, F);

  // Scale down the mesh to fit unit cube [0-1] . Center around (0.5, 0.5,
0.5).
  /************
    To normalize the value into a new range [new_min, new_max]

    normalizeValue = scale*((val - min)/(max - min)) + new_min

    where, scale = (new_max - new_min)
  *************/
  // Find the bounding box
  const Eigen::RowVector3d Vmin = V.colwise().minCoeff();
  const Eigen::RowVector3d Vmax = V.colwise().maxCoeff();

  cout<<"------> Model's minCoeff: "<<Vmin<<endl;
  cout<<"------> Model's maxCoeff: "<<Vmax<<endl;

  const Eigen::RowVector3d center(0.5, 0.5, 0.5);
  const Eigen::RowVector3d origin = (Vmax + Vmin) * 0.5;
  const Eigen::RowVector3d extents = Vmax - Vmin;
  const float scale = (1.0 / extents.array()).minCoeff();

  cout<<"------> New center "<<center<<endl;
  cout<<"------> Model's origin "<<origin<<endl;
  cout<<"------> extents "<<extents<<endl;
  cout<<"------> scale "<<scale<<endl;

  // normalizedV = (V.rowwise() - Vmin).array().rowwise() / (Vmax -
Vmin).array();
  normalizedV = ((V.rowwise() - origin) * scale).array().rowwise() +
center.array();

  // const Eigen::RowVector3d normalizedVmin =
normalizedV.colwise().maxCoeff();
  // const Eigen::RowVector3d normalizedVmax =
normalizedV.colwise().minCoeff();
  const Eigen::RowVector3d normalizedVmin(0,0,0);
  const Eigen::RowVector3d normalizedVmax(1,1,1);

  cout<<"------> normModel's maxCoeff:
"<<normalizedV.colwise().maxCoeff()<<endl;
  cout<<"------> normModel's minCoeff:
"<<normalizedV.colwise().minCoeff()<<endl;
  cout<<"------> New maxCoeff: "<<normalizedVmax<<endl;
  cout<<"------> New minCoeff: "<<normalizedVmin<<endl;


  std::chrono::steady_clock::time_point begin =
std::chrono::steady_clock::now();
  // GV.resize(num_grids * num_grids * num_grids, 3);
  create_grid(num_grids, normalizedVmin, normalizedVmax, GV);

  cout<<"------> GV "<< GV.rows() <<" x "<< GV.cols() <<endl;
  std::chrono::steady_clock::time_point end=
std::chrono::steady_clock::now();
  cout<<"------> Grid creating time
"<<(std::chrono::duration_cast<std::chrono::microseconds>(end -
begin).count()) /1000000.0 <<" secs"<<endl;

  /*------------------ This part is not required for signed distance
computation -------------------------*/
  // Encapsulated call to point_mesh_squared_distance to determine bounds
  // begin = std::chrono::steady_clock::now();
  // {
  //   Eigen::VectorXd sqrD;
  //   Eigen::VectorXi I;
  //   Eigen::MatrixXd C;
  //   igl::point_mesh_squared_distance(GV,normalizedV,F,sqrD,I,C);
  //   max_distance = sqrt(sqrD.maxCoeff());

  //   cout<<"------> Squared minDist "<<sqrD.minCoeff()<<endl;
  //   cout<<"------> Squared maxDist "<<sqrD.maxCoeff()<<endl;
  //   cout<<"------> Unsquared minDist "<<sqrt(sqrD.minCoeff())<<endl;
  //   cout<<"------> Unsquared maxDist "<<sqrt(sqrD.maxCoeff())<<endl;
  // }
  // end= std::chrono::steady_clock::now();
  // cout<<"------> point_mesh_squared_distance time
"<<(std::chrono::duration_cast<std::chrono::microseconds>(end -
begin).count()) /1000000.0 <<" secs"<<endl;

  /*------------------ END OF This part is not required for signed distance
computation -------------------------*/

  // Use AABB
  // Clear tree
  tree.deinit();
  // Prepare AABB tree for distance computation
  tree.init(normalizedV,F);
  // Winding number evaluation hierarchy
  hier.set_mesh(normalizedV,F);
  hier.grow();

  // Compute signed distance
  begin = std::chrono::steady_clock::now();

  {
    double s, sqrD;
    Eigen::VectorXi I;
    Eigen::MatrixXd C, N;

    S_signed.resize(GV.rows(),1);
    I.resize(GV.rows(),1);
    C.resize(GV.rows(),3);
    N.resize(GV.rows(),3);

    // Note: Both signed_distnace() and signed_distance_winding_number()
WORK perfectly.
    // Either one can be used, but signed_distance_winding_number() can
control the parallel process.

    //
igl::signed_distance(GV,normalizedV,F,igl::SIGNED_DISTANCE_TYPE_WINDING_NUMBER,S_signed,I,C,N);

    // Using SIGNED_DISTANCE_TYPE_WINDING_NUMBER
    // Outputs:
      //   s  sign
      //   sqrd  squared distance
      //   i  closest primitive
      //   c  closest point
    const size_t min_parallel = 1;
    //   min_parallel  min size of loop_size such that parallel
(non-serial) thread pooling should be attempted {0}
    igl::parallel_for(GV.rows(),[&](const int p)
        {
          const Eigen::RowVector3d q(GV(p,0),GV(p,1),GV(p,2));
          double s,sqrD;
          Eigen::RowVector3d c;
          int i;

igl::signed_distance_winding_number(tree,normalizedV,F,hier,q,s,sqrD,i,c);
          S_signed(p) = s * sqrt(sqrD);
          I(p) = i;
          C.row(p) = c;
        },min_parallel);

    // S_signed is a signed "unsquared" distance.
    cout<<"------> signedDist "<<S_signed.rows()<<" x
"<<S_signed.cols()<<endl;
    cout<<"------> min signedDist "<<S_signed.minCoeff()<<endl;
    cout<<"------> max signedDist "<<S_signed.maxCoeff()<<endl;
  }
  end= std::chrono::steady_clock::now();
  cout<<"------> signed distance computation time
"<<(std::chrono::duration_cast<std::chrono::microseconds>(end -
begin).count()) /1000000.0 <<" secs"<<endl;

  if((S_signed.minCoeff() < 0 && S_signed.minCoeff() >= -1) &&
(S_signed.maxCoeff() <= 1 && S_signed.maxCoeff() >= 0))
  {
    ofstream write2file(output);
    if(write2file.is_open())
    {
      write2file << S_signed;
      write2file.close();
      // std::this_thread::sleep_for(std::chrono::milliseconds(2000));
      cout<<"Output is SAVE at "<<output<<endl;
    }
  }else
    cout << "File is NOT saved!!!" <<endl;


/*---------------------------Visualization---------------------------*/
  if(visualize)
  {
    // // Plot the mesh
    igl::viewer::Viewer viewer;
    viewer.data.set_mesh(normalizedV, F);

    viewer.callback_key_down =
      [&](igl::viewer::Viewer & viewer, unsigned char key, int mod)->bool
      {
        switch(key)
        {
          default:
            return false;
          case '1': // Show an original mesh
            // viewer.data.clear();
            viewer.data.set_mesh(V,F);
            break;
          case '2': // Show a normalized mesh
            // viewer.data.clear();
            viewer.data.set_mesh(normalizedV,F);
            break;
          case '3': // draw points on a grid with colormap
            {
              Eigen::MatrixXd Colors;
              viewer.data.clear();
              Colors.resize(S_signed.rows(),3);
              const auto & append_color = [&Colors](
                                  const Eigen::VectorXd Ssigned)
                      {
                          Eigen::VectorXd normV; // push to [0, 1]
                          normV = ((Ssigned.array() -
Ssigned.array().minCoeff()) / (Ssigned.maxCoeff() - Ssigned.minCoeff()));
                          // Colormap
                          igl::parula(normV,true,Colors);
                          // Gray-scale
                          // Colors.col(0) =  normV;
                          // Colors.col(1) =  normV;
                          // Colors.col(2) =  normV;
                      };
              append_color(S_signed);
              viewer.data.add_points(GV,Colors);
              break;
            }
          case '4':
            {
              // viewer.data.clear();
              Eigen::RowVector3d color(1,0,0);
              add_wireframe(viewer, Vmin, Vmax, color);
              color << 0,1,0;
              add_wireframe(viewer, normalizedVmin, normalizedVmax, color);
              break;
            }
          case '5':
            viewer.data.clear();
            break;
        }
        viewer.data.set_face_based(true);
        return true;
      };

    // viewer.data.add_points(center,Eigen::RowVector3d(1,0,0));
    // viewer.data.add_points(origin,Eigen::RowVector3d(0,1,0));
    viewer.launch();
  }
  /*-------------------- END OF Visualization ------------------------*/

  return 0;
}

**Comment by jdumas** [comment]
That looks correct to me. What does `make VERBOSE=1` outputs when you run it?

**Comment by Yemibank** [comment]
It only give this error : fatal error: igl/readOFF.h: No such file or
directory
#include <igl/readOFF.h>

**Comment by jdumas** [comment]
Can you paste the output of `make VERBOSE=1`?

**Comment by Yemibank** [comment]
My make VERBOSE=1

ajayi@apollo:~/signed/build$ make VERBOSE=1
/usr/bin/cmake -H/home/signed -B/home/signed/build --check-build-system
CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/signed/build/CMakeFiles
/home/signed/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/signed/build'
make -f glad/CMakeFiles/glad.dir/build.make glad/CMakeFiles/glad.dir/depend
make[2]: Entering directory '/home/signed/build'
cd /home/signed/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles"
/home/signed /home/signed/external/glad /home/signed/build
/home/signed/build/glad
/home/signed/build/glad/CMakeFiles/glad.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/signed/build'
make -f glad/CMakeFiles/glad.dir/build.make glad/CMakeFiles/glad.dir/build
make[2]: Entering directory '/home/signed/build'
make[2]: Nothing to be done for 'glad/CMakeFiles/glad.dir/build'.
make[2]: Leaving directory '/home/signed/build'
[  9%] Built target glad
make -f glfw/src/CMakeFiles/glfw.dir/build.make
glfw/src/CMakeFiles/glfw.dir/depend
make[2]: Entering directory '/home/signed/build'
cd /home/ajayi/signed/build && /usr/bin/cmake -E cmake_depends "Unix
Makefiles" /home/ajayi/signed /home/signed/external/glfw/src
/home/signed/build /home/signed/build/glfw/src
/home/signed/build/glfw/src/CMakeFiles/glfw.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/signed/build'
make -f glfw/src/CMakeFiles/glfw.dir/build.make
glfw/src/CMakeFiles/glfw.dir/build
make[2]: Entering directory '/home/signed/build'
make[2]: Nothing to be done for 'glfw/src/CMakeFiles/glfw.dir/build'.
make[2]: Leaving directory '/home/signed/build'
[ 90%] Built target glfw
make -f CMakeFiles/tyf_bin.dir/build.make CMakeFiles/sdf_bin.dir/depend
make[2]: Entering directory '/home/signed/build'
cd /home/signed/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles"
/home/signed /home/signed /home/signed/build /home/signed/build
/home/signed/build/CMakeFiles/sdf_bin.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/signed/build'
make -f CMakeFiles/tyf_bin.dir/build.make CMakeFiles/sdf_bin.dir/build
make[2]: Entering directory '/home/signed/build'
[ 95%] Building CXX object CMakeFiles/sdf_bin.dir/main.cpp.o
/usr/bin/c++    -isystem /home/signed/cmake/../include -isystem
/home/signed/cmake/../external/eigen
-I/home//home/signed/external/glad/include
-I/home/signed/external/glfw/include  -std=c++11 -fPIC -O3 -DNDEBUG
-std=gnu++11 -o CMakeFiles/sdf_bin.dir/main.cpp.o -c /home/signed/main.cpp
/home/signed/main.cpp:1:25: fatal error: igl/readOFF.h: No such file or
directory
 #include <igl/readOFF.h>
                         ^
compilation terminated.
CMakeFiles/sdf_bin.dir/build.make:62: recipe for target
'CMakeFiles/tyf_bin.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/sdf_bin.dir/main.cpp.o] Error 1
make[2]: Leaving directory ''/home/signed/build'
CMakeFiles/Makefile2:708: recipe for target 'CMakeFiles/tyf_bin.dir/all'
failed
make[1]: *** [CMakeFiles/sdf_bin.dir/all] Error 2
make[1]: Leaving directory '/home/signed/build'
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jdumas** [comment]
It looks like you modified your copy of the libigl repository to put your `main.cpp` and compile from there... You really should try to stick to the format used in the [libigl-example-project](https://github.com/libigl/libigl-example-project).

In particular, it looks like the compiler is adding `/home/signed/include` as the include directory for libigl. Does this folder contains the libigl header files? If not, in which folder is the file `readOFF.h` located for example?

**Comment by wooriel** [comment]
Hi, I think I am facing similar problem. I cloned the libigl repo inside libigl-example-project and followed the instruction. However, I could not find readOFF.h file in the include folder.
