### ISSUE TITLE
libigl does not seem to install exported targets for igl::opengl and others

### ISSUE THREAD

**Issue by aschier** [libigl/libigl#1156]
When I build libigl, it only installs ``igl.lib`` and the target ``igl::core``, and the other targets are missing, even when they are configured in cmake and built as project inside the MSVC solution.

From the cmake log

```
Creating target: igl::core (igl)
Creating target: igl::embree (igl_embree)
Creating target: igl::opengl (igl_opengl)
Creating target: igl::opengl_glfw (igl_opengl_glfw)
(...)
Creating target: igl::opengl_glfw_imgui (igl_opengl_glfw_imgui)
Creating target: igl::png (igl_png)
Creating target: igl::triangle (igl_triangle)
Creating target: igl::xml (igl_xml)
```

And ``libigl-export-release.cmake``:

```
#----------------------------------------------------------------
# Generated CMake target import file for configuration "Release".
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Import target "igl::core" for configuration "Release"
set_property(TARGET igl::core APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(igl::core PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/igl.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS igl::core )
list(APPEND _IMPORT_CHECK_FILES_FOR_igl::core "${_IMPORT_PREFIX}/lib/igl.lib" )

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
```

I think the targets should be listed there, but they do not seem to get installed using the generated MSVC ``INSTALL`` target.

I can build the tutorial projects with ``BUILD_TUTORIALS`` (and the binaries are inside the build folder), but I cannot build them on their own with the installed cmake, as there are missing targets, e.g.,``igl::opengl``.

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [ ] Linux

**Comment by jdumas** [comment]
Yes it's a known issue. Well, more like a missing feature.The recommended way of using libigl is to build it along your project with [add_subdirectory()](https://github.com/libigl/libigl-example-project). Installing system-wide is more complicated and we haven't really looked into it. We can review and accept PRs to improve the installed behaviour as long as they do not overcomplicate the build process, and work on all OS.

**Comment by aschier** [comment]
Thank you for the fast feedback.
If I adapt the cmake file for global installation I will send a PR. For now I will start with the ``add_subdirectory`` method.

**Comment by aschier** [comment]
I tried to export the igl::opengl and igl::opengl_glfw targets needed for the DrawMesh tutorial and it seems to work.
I get a warning because I need to export the target glad, that does not have a install target, so the include path is prefixed by the source directory, so I would need to add an install target for glad next.

So I just want to ask, if you tried to create more targets and had trouble or too complicated cmake files or if you just did not have the time to look into it, yet?
I am not sure how much time I should invest and if you're interested in the result or if you already know that it will be too complex for your builds.

**Comment by jdumas** [comment]
I haven't had time to look into it yet. Proper packaging is a complicated matter, and since I don't have a use-case for it yet it's low on my priority list. My only requirement is that the cmake files do not turn into a monster that would be unmaintainable over time. So probably separating into different files, or using cmake functions, would be a way to grow while still making it easy to maintain. If you have a way to do that, we'd be happy to review a PR and discuss how to integrate that into the codebase.
