### ISSUE TITLE
cannot load obj uv

### ISSUE THREAD

**Issue by xarthurx** [libigl/libigl#1157]
When loading an obj mesh with the function `Viewer::load_mesh_from_file`, I always get an error which point to: `data().set_uv(UV_V,UV_F);`  in the same function, where the `UV_V` and `UV_F` are empty.

This only happens in Debug mode but not Release mode.
And also don't happen to `*.off` files.

I guess this is because the obj file doesn't have `uv` info?

How can I suppress it?

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [ ] Linux

**Comment by alecjacobson** [comment]
I think this is fixed with the if statement guarding it. Reopen if not.
