### ISSUE TITLE
[dev-branch] `Viewer::lanuch()` function fail to get window size set by `resize()`

### ISSUE THREAD

**Issue by xarthurx** [libigl/libigl#1167]
In the develop branch, the `launch_init()` function (called by `lanuch()`) is changed from:

https://github.com/libigl/libigl/blob/e699d257fe860d4fd82709835e72438bd0cd1533/include/igl/opengl/glfw/Viewer.cpp#L135

to:

https://github.com/libigl/libigl/blob/05666a7e727a47ee00763f907b465bdc0ab2329c/include/igl/opengl/glfw/Viewer.cpp#L136-L137

This result in the window size set by `resize(w, h)` function cannot be catched, because:
https://github.com/libigl/libigl/blob/05666a7e727a47ee00763f907b465bdc0ab2329c/include/igl/opengl/glfw/Viewer.cpp#L159

 which is not the case in the master branch:

https://github.com/libigl/libigl/blob/e699d257fe860d4fd82709835e72438bd0cd1533/include/igl/opengl/glfw/Viewer.cpp#L159

the `viewport` variable is set by the `resize()` function of the `Viewer` class.

Not sure how to properly fix it by the libigl guideline, report here.

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [ ] Linux

**Comment by jdumas** [comment]
> This result in the window size set by resize(w, h) function cannot be catched, because:

I'm not sure exactly what you mean by this? What is the issue you're having exactly?

**Comment by xarthurx** [comment]
In the master branch, the viewer is launched by reading the window size set by `viewer.resize(w, h)` (which set the variable `viewerport` and be read when launch the viewer)

In the dev branch, the `resize()` function doesn't work anymore, because the `launch()` function is changed and only accept window size given in the function directly, like:

```
  viewer.launch(true, false, "libigl Viewer", 2560, 1440);
```

This make the function `viewer.resize()` useless...

I'm not sure what is the purpose that you change the `lanuch` function, but either `resize()` should be removed, or the `lanuch()` function should take consideration of the window size, as the version in master branch did.

Hope this is understandable.

**Comment by jdumas** [comment]
`resize()` should still work if you call it *after* launching the viewer. I guess we could make it so that when the `launch` function is called with default width/height (set to 0) it tries to use the `core().viewport` info instead (but this should only work when there is only one viewport).

**Comment by xarthurx** [comment]
Nope,
```
  viewer.launch();
  viewer.resize(2560, 1440);
```
doesn't work either.

But I got what I need with the one-line command above. This is just for reference.
Thanks for the help.

**Comment by jdumas** [comment]
Well, when you call `launch()` it goes into a loop, so `resize()` won't be reached until you close the viewer. Try calling it from the `viewer.callback_init` for example.

**Comment by jdumas** [comment]
Alternatively, you can call as follows:
```
viewer.launch_init();
viewer.resize(...);
viewer.launch_rendering(true);
viewer.launch_shut();
```
