### ISSUE TITLE
Viewer UI text rendering issue

### ISSUE THREAD

**Issue by mlamarre** [libigl/libigl#117]
![nanogui_viewer_issue](https://cloud.githubusercontent.com/assets/7805609/9891011/4b19d070-5bd1-11e5-9329-8d30c81b7313.png)

This is how tutorial 503 renders on my system : Windows 10. Built with Visual Studio 2012 x64. Nvidia graphics card driver 355.60.

I see this for all tutorials must be something in nanogui.

Not a big deal but does someone has ideas on how to debug this?

Thanks

**Comment by danielepanozzo** [comment]
Could you please try to clone the official nanogui repo: https://github.com/wjakob/nanogui
and see if the examples there also have the same issue?

Since nanogui shares the same opengl context as our viewer, it might also be a bug on our side.

**Comment by mlamarre** [comment]
The error was on my side. I made a mistake while replacing the delegating constructors in the Color class.
