### ISSUE TITLE
where to set `mesh_id`?

### ISSUE THREAD

**Issue by xarthurx** [libigl/libigl#1174]
I'm trying to add two meshes to the viewer, one original, one processed.
I understand the viewer handles different mesh using a `data_list`, where each mesh takes one.
The question I have is that the `data()` function takes the argument of `mesh_id`:

![image](https://user-images.githubusercontent.com/1921878/56568287-f4619580-65b6-11e9-9a8e-adaf46858ff3.png)

instead of the index of the `data_list`.

It seems that the viewer tries to provide the functionality of locating the mesh by its unique `id` instead of just the index of the `data_list`, which is good. But I cannot find anywhere in the source code where I can set this `mesh_id`.

The `append_mesh()` function takes in a **bool** as "visible", and the `load_mesh()` takes in the file name.

It turns out that the `mesh_id` in the current settings are just another index which I cannot set, and make confusion about accessing the data, for example:

 `data(1)` will point to the `data_list[0]`, if I just `viewer.data_list.resize(2)` and assign the two meshes to `data(0)` and `data(1)`.

I'm not sure if I misunderstand the use of the `data()` function, or should I just use `data_list[0]` and `data_list[1]` instead. But quite confused here about the setup...

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [ ] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by xarthurx** [comment]
Initializing the `data_list` with the following works:

```
  viewer.data_list.resize(2);

  // init data_list for taking two meshes
  for (size_t i = 0; i < viewer.data_list.size(); i++) {
    viewer.data_list[i].clear();
    viewer.data_list[i].id = i;
  }
```

so that I can access different mesh with `data(0)` and `data(1)`. It seems `mesh_id` is just the same as `id` in the `viewer` class... 

Some info/functions about these settings will be super appreciated.

**Comment by jdumas** [comment]
Think of the `mesh_id` as a persistent index that stays valid after you erase a mesh from the viewer. This allows you to identify a particular mesh in `data_list`. When you append a new mesh, the counter `next_data_id` is incremented, making sure each new id is unique. You can also set it yourself if you want, although there is little point in that. Note that the function `append_mesh()` also returns the id of the newly inserted mesh for convenience. Finally, the function `mesh_index()` will simply iterate over all elements of `data_list`, and return the current index of a mesh based on its unique id.

**Comment by xarthurx** [comment]
Thanks for the response.
I didn't notice the `append_mesh()` will return the `id`.

For the `mesh_id` question, the `erase_mesh(const size_t index)` function remove the entry in the `data_list`, then may I ask what do you mean by *identify a particular mesh*? Hasn't the mesh been totally removed?

**Comment by jdumas** [comment]
If you have three meshes [0, 1, 2], and you remove the mesh with index 1, then the two remaining meshes will have indices [0, 1], but their `mesh_id` will still be `[0, 2]`. So even after you do `viewer.erase_mesh(1)`, you can still call `viewer.data(2)` and it will return the last mesh. Of course the mesh with id 1 has been removed, so it is not available anymore. If you want to access a mesh by its current index, you can call `viewer.data_list[index]` directly.

**Comment by xarthurx** [comment]
Crystal clear!
Thanks!
