### ISSUE TITLE
error: 'igl' has not been declared!

### ISSUE THREAD

**Issue by trandatjp** [libigl/libigl#1177]
[Describe your issue]
Hello,
I tried to use libigl library in my project in C++ (Ubuntu).
I followed the tutorial but I got error as above
I added libigl/include to my include path and include relevant headers:
#include <igl/cotmatrix.h>
#include <Eigen/Dense>
#include <Eigen/Sparse>
#include <igl/principal_curvature.h>

and in main() I call function
Eigen::MatrixXd V;
Eigen::MatrixXd F;
MatrixXd PD1,PD2;
MatrixXd PV1,PV2;
igl::principal_curvature(V,F,PD1,PD2,PV1,PV2);

I got the error: 'igl' has not been declared!

Do you have any suggestion how can I solve this problem?
Thank you very much.
Tran. 
#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [x] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by jdumas** [comment]
Can you detail:
1. How you are compiling your code exactly.
2. What error message you get exactly.
3. Whether you are using the `dev` or `master` branch.
4. If you are able to compile the tutorials using CMake.

**Comment by trandatjp** [comment]
Thank you for your prompt reply.
1. I used makefile to compile my code. The makefile as follows:
all:
#	g++ -std=c++14 -g -O3 main.cpp \#
	g++ -std=c++14 -g -O3 main.cpp \
	-I ./../FEA/include/ \
	-I ./../LSM/include/ \
	-l blas \
	-l lapack \
	-l metis \
	-L /usr/local/gfortran/lib \
	-l gfortran \
	-l ma57 \
	-l arpack \
	-l nlopt -llapack -llapacke -ltmglib -lcblas -lblas -lcblas -lgfortran -lma57 -lfakemetis -lmetis -lma57 -lblas -lcblas -lnlopt -lm -lglpk
       -L ../../vendor/libigl/include/igl #-l igl
clean:
	rm a.out

2. The following error I got:
main.cpp: In function ‘int main()’:
main.cpp:405:4: error: ‘igl’ has not been declared
    igl::principal_curvature(V,F,PD1,PD2,PV1,PV2);
    ^
makefile:76: recipe for target 'main' failed
make: *** [main] Error 1
3. I am using master branch.
4. I can compile the tutorials using CMake.

**Comment by jdumas** [comment]
You need to specify include directories with the `-I` option (`-L` is for link directories). But really I encourage you to compile your project using CMake, otherwise anything outside the core igl library will be a pain to use.

**Comment by trandatjp** [comment]
I changed -L to -I but the error still appeared.
Actually, I am familiar with makefile than CMake. I don't know how to write CMake file.
I just want to use function principal_curvature.h/cpp to calculate principal curvature in my case. Do you have any suggestion to overcome this issue.
Thank you.

**Comment by jdumas** [comment]
You should also remove the space, as in the example on the website homepage:
```
g++ -std=c++11 -I/usr/local/include/eigen3 -I./libigl/include/ hello.cpp -o hello
```

Alternatively, if you want to learn how to use CMake, you can check out the resources listed [here](https://gist.github.com/mbinna/c61dbb39bca0e4fb7d1f73b0d66a4fd1), it's a good place to start.
