### ISSUE TITLE
how to draw more labels easily

### ISSUE THREAD

**Issue by xarthurx** [libigl/libigl#1178]
**Goal: "" draw different labels (vertices weights, or other info) on the vertices, faces, etc.

The current viewer draws labels on vertices by checking the flag `show_vertid` inside the class `ViewerData`. 

Unlike other plugins such as the `ImGuiMenu` (for which I can create derived class of plugins and modify the function), if I want to add flags and corresponding conditions inside the `draw_label` function, it seems I have to make derived classes of both the `Viewer` and the `ViewerData` for the modification...

Is there an easier way of adding label information?

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [ ] Linux

**Comment by jdumas** [comment]
Label support is still a bit rough around the edge. You can use `ViewerData::add_label()` to add customized labels at the desired positions (e.g. vertices). You can also look into the code of the plugin itself and copy the drawing code if you want to customize other things like colors, etc.

**Comment by xarthurx** [comment]
Thanks for the instant response!

Two following questions since the `add_label()` can only draw on one vertex.

1. There's a `draw_labels_window()` function:
![image](https://user-images.githubusercontent.com/1921878/56694572-50c3d280-66e7-11e9-8ee9-e712aa7433dd.png)

Not very familiar with the OpenGL. Is it drawing a transparent layer on top of the viewer so that we can draw labels on it?


2. Shouldn't the `draw_labels` function also be a virtual one so that I can override it in my derived class?
![image](https://user-images.githubusercontent.com/1921878/56694517-2b36c900-66e7-11e9-9774-2ef2ef9f735f.png)

**Comment by jdumas** [comment]
You're not really supposed to override this method with your own. This is a part of the API and the viewer that we need still to flesh out, so right now, if you want to customize the `draw_labels()` method, I would suggest to simply copy the code of `draw_labels_window()` into your own derived menu and go from there.
