### ISSUE TITLE
EIGEN_MAKE_ALIGNED PROBLEM

### ISSUE THREAD

**Issue by wkindling** [libigl/libigl#1179]
[Describe your issue]

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [ ] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.
Hello!
I use ligigl to calculate bounded biharmonic weights, and visualize it throw Viewer. But I frequently come across the problem of EIGEN_MAKE_ALIGNED. It just report error and stop execution. I have looked up the documentation of Eigen library, and although EIGEN_MAKE_ALIGNED_OPERATOR_NEW has been declared in the class. The problem still occurs. Can you check what is wrong?
Thx a lot:)

**Comment by jdumas** [comment]
Do you have an example/MWE where this happens? Are you using the `dev` branch? MSVC 2017, 2019?

**Comment by wkindling** [comment]
> Do you have an example/MWE where this happens? Are you using the `dev` branch? MSVC 2017, 2019?
Thx for attention!
In fact, it just occurs in the tutorial program 403 Bounded Biharmonic Weights. I run the example code and frequently come across the problem. And I am using MSVC 2017.

**Comment by jdumas** [comment]
Thanks. We'll try to investigate. (You didn't say if you were on the `dev` branch?)

**Comment by wkindling** [comment]
sry, I missed it . I were on the master branch.

**Comment by jdumas** [comment]
Can you try the dev branch and see if it fixes the problem?

**Comment by wkindling** [comment]
It seems that using dev branch can solve this problem. But I am curious about the reason. Can you just explain it simply? thx :)

**Comment by jdumas** [comment]
I think it was #1029. Closing the issue then =)

**Comment by wkindling** [comment]
thx very much！ Have a nice day.
