### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by rubilin** [libigl/libigl#1180]
[Describe your issue]

#### Check all that apply (change to `[x]`)
- [ ] Windows
See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.
when I cmake libigl,it will have a error:error: could not find git for clone of tutorial_data-download

**Comment by jdumas** [comment]
You need an installation of git > 1.6.5 on your computer for cmake to download the necessary dependencies when compiling libigl.
