### ISSUE TITLE
Method to rotate the object?

### ISSUE THREAD

**Issue by aklonc** [libigl/libigl#1182]
Hi all,

I am working on a small project. I want to implement a feature to rotate the object (not the viewport) by dragging. I haven't found related information yet. Is there an existing solution inside?

Thank you!

#### Check all that apply (change to `[x]`)
- [x] Windows
- [x] Mac OS X
- [x] Linux

**Comment by LihengGong** [comment]
Hi,
If I understand your question correctly, probably you're looking this code:

`igl/viewer.cpp:   bool Viewer::mouse_down(MouseButton button,int modifier)`

**Comment by aklonc** [comment]
@LihengGong Hi! I'm sure mouse_down is needed but it's not enough. For example, we can rotate our viewport by dragging. I want to know the rest part of that.

**Comment by alecjacobson** [comment]
the viewer supports rotating by dragging.
