### ISSUE TITLE
Label support `ViewerData::add_label()` 

### ISSUE THREAD

**Issue by thesvend** [libigl/libigl#1183]
I am having troubles using the viewer.data().add_labels() method in my code. It compiles and runs without errors. However, non of the labels are shown in my window. I don't know what I am doing wrong?
When running the sample-project 105 where the bounding box is drawn I get the same issues. When looking into the code, the labels should be drawn automatically - or do I have to activate any flags?

Or is this related to the fact, that this code is under construction and not ready to be used?

"Label support is still a bit rough around the edge. You can use `ViewerData::add_label()` to add customized labels at the desired positions (e.g. vertices). You can also look into the code of the plugin itself and copy the drawing code if you want to customize other things like colors, etc.

_Originally posted by @jdumas in https://github.com/libigl/libigl/issues/1178#issuecomment-486421626_"

**Comment by thesvend** [comment]
My output of sample 105 looks like this. All nice, but the labels are missing
![Unbenannt](https://user-images.githubusercontent.com/45479696/57176131-60b08480-6e54-11e9-8a20-fb2abb997b20.JPG)

**Comment by jdumas** [comment]
You need to enable the imgui plugin in order to have labels drawn in the viewer.

**Comment by thesvend** [comment]
thx for the fast reply! In Tutorial 106 I found that this can be done by linking it by adding "igl::opengl_glfw_imgui" to the linking command. 

In the .cpp file I added:
  igl::opengl::glfw::imgui::ImGuiMenu menu;
  viewer.plugins.push_back(&menu);

However, now I always have the menu inside my viewer. Is there a way to enable the imgui plugin without having to add the menu object?

**Comment by jdumas** [comment]
You can easily disable the menu by overriding the `callback_draw_viewer_window` member variable, e.g.
```
igl::opengl::glfw::imgui::ImGuiMenu menu;
menu.callback_draw_viewer_window = [](){};
viewer.plugins.push_back(&menu);
```

**Comment by thesvend** [comment]
that's exactly what I was looking for! Thank you :)
