### ISSUE TITLE
Cannot make tutorials

### ISSUE THREAD

**Issue by yonigo** [libigl/libigl#1184]
Hey,

I am trying to tun the tutorial (regular & python binding), but I keep getting:

0 [main] make 3720 find_fast_cwd: WARNING: Couldn't compute FAST_CWD pointer.  Please report this problem to
the public mailing list cygwin@cygwin.com
make: *** No targets specified and no makefile found.  Stop.

I'm on windows 10, I've installed everything using anaconda (make, cmake, python), and I'm using the anaconda prompt to run the command.

What am I missing?

#### Check all that apply (change to `[x]`)
- [ x] Windows
- [ ] Mac OS X
- [ ] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by jdumas** [comment]
If you're on Windows you should compile libigl using MSVC, not cygwin.

**Comment by jbs0645** [comment]
how to compile **libigl** using MSVC  on Windows 10 system? I have installed  the **mingw** , but I faced the following error when using the  'mingw32-make ' command： 
_`mingw32-make: *** No targets specified and no makefile found.  Stop.`_

**Comment by jdumas** [comment]
Well don't use mingw. On Windows you should compile with Visual Studio.

**Comment by jbs0645** [comment]
OK,  Thank you very much!
