### ISSUE TITLE
Cannot init ImGuiMenu (ViewerPlugin) with Viewer

### ISSUE THREAD

**Issue by xarthurx** [libigl/libigl#1186]
Try to explore the possibilities of the ViewerPlugin setup.

At the beginning of the main function, I try to init the ImGuiMenu with the viewer:

`  menu.init(&viewer);`

where `menu` is a class of the default `ImGuiMenu`, and `viewer` similarly.

The compilation shows an error:

![image](https://user-images.githubusercontent.com/1921878/57252369-36291c00-704c-11e9-89bf-dfdf0067bfeb.png)

cmd error:
`Assertion failed: window != NULL, file C:\Libraries\libigl\external\glfw\src\window.c, line 685`

it seems that to get the `hidpi_scaling` a window needs to be created, but at the beginning of the main function, the window has not been since we haven't launched the viewer.

Reasons that I want to init the viewer of the ViewerPlugin is to take advantage of the `load_mesh_from_file()` function of the viewer, in which it will use the `load` function of the plugin to load things -- I can redefine the loading process in my customized plugins.

It seems to me that some fix can be done for the ImGuiViewer, though not sure how. 
Creating some default window, or default scaling?

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [ ] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by jdumas** [comment]
You're not really supposed to call the `init()` function yourself. If you register the plugin before calling `viewer.launch()`, the `init()` function will be called by the viewer when it creates the window itself.

**Comment by xarthurx** [comment]
but then if I load a mesh from cmd with sth like:
```
  if (argc == 2) {
    //menu.load(argv[1]);
    viewer.load_mesh_from_file(argv[1]);
  }
```

it will give me error since the plugin is not initialized with the viewer...

**Comment by jdumas** [comment]
It this case you can decompose the `viewer.launch()` call into the following calls:
```
viewer.launch_init(...);
if (argc == 2) {
  viewer.load_mesh_from_file(...);
}
viewer.launch_rendering(...);
viewer.launch_shut();
```

**Comment by xarthurx** [comment]
Thanks for the quick response. 
That works~

Another question also related to this issue:

If I use a derived class `xViewer` of the default OpenGL Viewer, with some additional variables, is there a way to set this new viewer as the viewer of the plugin?

adding a customised `init()` function inside my plugin doesn't seem to work, and the `viewer` pointer inside the plugin is always empty...

**Comment by jdumas** [comment]
Why do you need a derived viewer class? We have plugins exactly for this reason, so that you can override some default behavior without having to write a derived viewer class.

**Comment by xarthurx** [comment]
Hmm... perhaps I didn't get the philosophy of the design.
That's basically for variables that each plugin can access....

If I use a plugin to take care of all these kind of variables, then for the access issue, I guess `friend class` should be used so that plugin classes can access data from each other?

**Comment by jdumas** [comment]
Each plugin can have its own variables. If a variable needs to be shared between different plugins, it can be a public member of shared plugin for example? I don't see why you would need *several* plugins to begin with, but from a plugin you can access the viewer, and from the viewer you can access the list of plugins if you need to.

I usually have a single plugin derived from the `ImGuiMenu`, where I can add my own menus and variables.

**Comment by xarthurx** [comment]
The whole story is I'd like to extend the abilities to add customized flags for labels, similar to the existing label `show_vertid`, etc., as asked in this issue: https://github.com/libigl/libigl/issues/1178.

Then I found little by little that I need my own class for `ViewerData`, `Viewer`, `Menu` etc... getting into an endless loop...

Now I kind of understand a bit, and maybe I'll just use different flags to do this...

**Comment by jdumas** [comment]
You can also simply get the functionalities that you need by simply reimplementing it on top of the existing imgui plugin. Or copy the code for drawing labels in your own plugin entirely. If you need to "extend" the info stored in a vertex data, you can also use a map from mesh id to whatever data you need, similar to how the `colors` attribute is handled in tutorial 107. Then your plugin can have its own `add_mesh_labels(int mesh_id, ...)` function or something.

**Comment by xarthurx** [comment]
Great, thx for the detailed explanation.
I'll do sth like this.
