### ISSUE TITLE
[request] upgrade Eigen version (or related Functors) for support of C++17

### ISSUE THREAD

**Issue by xarthurx** [libigl/libigl#1188]
If compiled with c++17 feature, libigl will report missing members of `binder2nd` and `binder1st` in `Functors.h:

![image](https://user-images.githubusercontent.com/1921878/57288027-fea48900-70b8-11e9-8401-2fef270f8893.png)

The Eigen community has already solved this in:
http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1309

Could we also modify the libigl so that these functions can be replaced?

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [ ] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by jdumas** [comment]
You can already use Eigen 3.3 with libigl, either by defining the `Eigen3::Eigen` target before including libigl, or by passing the CMake options `-DLIBIGL_EIGEN_VERSION=3.3.7` (you need to be on the `dev` branch).

We'll change the default Eigen version soon as well, but cannot say when for sure.

**Comment by xarthurx** [comment]
Don't I also need to set the MD5 using the second method?

cmake got errors and after checking the download function in the `LibiglDownloadExternal.cmake` file.

**Comment by jdumas** [comment]
I just merged a PR where we switch from the `http` url to the `git` one for downloading the Eigen dependency, and this one uses git tags and does not need MD5 anymore. Try to update your version of libigl, and delete the `external/` folder, and then try again.

**Comment by xarthurx** [comment]
@jdumas  Works now! 
Thanks.
