### ISSUE TITLE
Cannot find igl::opengl_glfw_imgui

### ISSUE THREAD

**Issue by robertguetzkow** [libigl/libigl#1189]
I wanted to add `igl::opengl_glfw_imgui` to the target linked libraries in order to add labels to the viewer, but cmake doesn't find this target. Building a viewer with `igl::opengl_glfw` works. For some reason building the tutorials works as well,  including 106 which uses `igl::opengl_glfw_imgui`. Am I missing something obvious?
```
cmake_minimum_required(VERSION 3.13)
project(meshtransplant)

set(CMAKE_CXX_STANDARD 14)
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${CMAKE_CURRENT_SOURCE_DIR}/cmake)
set(OpenGL_GL_PREFERENCE "GLVND")

option(LIBIGL_WITH_OPENGL "Use OpenGL" ON)
option(LIBIGL_WITH_OPENGL_GLFW "Use GLFW" ON)
option(LIBIGL_WITH_OPENGL_GLFW_IMGUI "Use ImGui" ON)

find_package(LIBIGL REQUIRED)
find_package(Boost COMPONENTS program_options REQUIRED)

add_executable(${PROJECT_NAME} main.cpp MeshViewer.cpp MeshViewer.h Metric.cpp Metric.h MeshTransplant.cpp MeshTransplant.h Mesh.cpp Mesh.h)
target_link_libraries(${PROJECT_NAME} ${Boost_LIBRARIES} igl::core igl::opengl_glfw igl::opengl_glfw_imgui)
```

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [x] Linux

**Comment by jdumas** [comment]
Did you try to build in a clean build folder? (Or after removing the `CMakeCache.txt`)

**Comment by robertguetzkow** [comment]
Okay this is strange, it works perfectly when manually run on the terminal with the usual `cmake ..`, however CLion manages to break this in some way. I didn't expect this to behave differently since everything else worked both in the IDE and terminal.

Closing this issue, since it is caused by the IDE.

**Comment by jdumas** [comment]
If you clear CLion's build folder it should behave normally again. The problem is that `option(...)` in CMake only sets the *default* value of the variable, which is stored in the `CMakeCache.txt` file. CLion has its own build folder (I don't remember if it uses a separate cache folder to put cmake files), which may cause it to use the previous default value of the variable.

**Comment by robertguetzkow** [comment]
Thanks for the help. Seems like Clion's own clean didn't do the job, but I will try to do it manually.

**Comment by jdumas** [comment]
Note that you can also manually force the value of the cmake variable to be set directly from the cmake script itself:
```
set(LIBIGL_USE_STATIC_LIBRARY ON CACHE BOOL "" FORCE)
```

**Comment by ivanpuhachov** [comment]
in CLion `Tools -> CMake -> Reset Cache and Reload Project` solved this issue
