### ISSUE TITLE
nanogui

### ISSUE THREAD

**Issue by chenhonghua** [libigl/libigl#119]
Hello, 
I have been using the old version of libigl, which uses AntTweakBar.  It runs well.
Now, I'am using the new version. Some errors occurred when I compile nanogui using VS2013.
Firstly, I download the package of nanogui from github and the related dependencies(glfw、eigen and nanovg), Then, I cmake it to generate the projects. Until now, it  seems ok. 
But when I build the project using VS2013, it reports error: 
      error c2719: "color": formal parameter with __declspec(align('16')) won't be aligned
This error may be caused by Eigen.
I am curious about how to solve it?
Look forward to your response!

**Comment by danielepanozzo** [comment]
You could try adding
add_definitions(-DEIGEN_DONT_ALIGN)
to the cmake.

**Comment by chenhonghua** [comment]
@danielepanozzo 
I'v solved the problem above by adding add_definitions(-DEIGEN_DONT_ALIGN) to the cmake.
But I met the same problem as shown in #98 .
I compile in the debug mode. 
![error](https://cloud.githubusercontent.com/assets/11238777/9932602/dd8018dc-5d77-11e5-8fd3-fd792246ef82.png)

**Comment by chenhonghua** [comment]
Hi, @danielepanozzo  @alecjacobson 
In the webpage (http://eigen.tuxfamily.org/doxdevel/group__TopicUnalignedArrayAssert.html)  show some causes for this issue. 
When I cmake nanogui without adding add_definitions(-DEIGEN_DONT_ALIGN), It truly shows the problem of alignment because libigl uses the Eigen library heavily.

**Comment by alecjacobson** [comment]
I can't tell from your screenshot where the assertion is firing. In a
libigl function or in nanogui?

**Comment by alecjacobson** [comment]
Meanwhile, there was a missing:

  public:
      EIGEN_MAKE_ALIGNED_OPERATOR_NEW

in ViewerCore.h

It's added in 990515a you could try pulling to see if that fixes it.

**Comment by chenhonghua** [comment]
hi, @alecjacobson 
Let's go back to the beginning. When I cmake nanogui without adding add_definitions(DEIGEN_DONT_ALIGN), it always fail to compile because the error occured in (nanogui-master\include/label.h(31)). It shows that 
error C2719: "color" formal parameter with __declspec(align('16')) won't be aligned.

And then followed danielepanozzo's advice , I try to add add_definitions(DEIGEN_DONT_ALIGN) to cmake, there was no problem in the process of compilation. But when I run the demo 501, the same error shown in #98 occurred.

**Comment by chenhonghua** [comment]
Adding the missing  above didn't solve this problem.

**Comment by alecjacobson** [comment]
Where is the assert firing? Please send a stack trace (as text rather than
a screenshot image).

**Comment by chenhonghua** [comment]
the assert occurred in the DenseStorage.h（line 86）

**Comment by alecjacobson** [comment]
Can please you paste the **full** stack trace?

**Comment by chenhonghua** [comment]
EG1.exe!nanogui::Color::Color (int r,int g,int b,int a) line 76
EG1.exe!nanogui::Color::Color () line 43
EG1.exe!nanogui::Theme::Theme(NVGcontext * ctx ) line 7
EG1.exe!nanogui::Screen ::initScreen(GLFWwindow * window )line 161
EG1.exe!nanogui::FormScreen::init (GLFWwindow * window) line 46

**Comment by alecjacobson** [comment]
K, thanks. This looks like a nanogui issue, so please report it [there](https://github.com/wjakob/nanogui)

**Comment by chenhonghua** [comment]
Using 64 bit compile will solve the problem. :)
