### ISSUE TITLE
is_edge_manifold uninitilized values in BE parameter passed in

### ISSUE THREAD

**Issue by chrisleong-nvg** [libigl/libigl#1190]
I am trying to list all non-manifold edges in a mesh using `is_edge_manifold` but I am unable to make sense of `EMAP` and `BE` variables passed in and what they represent.

printing out the values is showing that `BE` has uninitialized values as well.

Can anyone clarify what those 2 parameters are?

**Comment by chrisleong-nvg** [comment]
BE printed values is `-842150451`.
Looked at the src I am assuming the init is setting to 0x00?

Would this mess with the compare logic: `const bool manifold = count[EMAP[e]] <= 2;`?

**Comment by chrisleong-nvg** [comment]
I have another issue, 
`is_edge_manifold` with only `F` is getting different results with the overloaded version.

**Comment by alecjacobson** [comment]
Definitely shouldn't get different results. But would need an example to debug. See the documentation of unique_edge_map to understand those outputs https://libigl.github.io/dox/namespaceigl.html#a5ec9f63d03451613c1a56df8308fe4b2

feel free to reopen if the problem is still happening.
