### ISSUE TITLE
how to get the coordinates of the picking point?

### ISSUE THREAD

**Issue by peiyueY** [libigl/libigl#1191]
#### Describe your issue
Hi,

As described in the title, I'm trying to get the coordinates of the picking point, not the vertex or face. Can unproject_onto_mesh() function do it? Or do I need to use other function?

One more question: When I try to get model matrix using "**viewer.core.model**", the compiler complains "_class 'viewerCore' doesn't have a field 'model'_"...

Thanks

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [x ] Mac OS X
- [ ] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by jdumas** [comment]
The `model` matrix has been removed now on the `dev` branch. There is only the `view` and `proj` matrices now. I suggest you take a look at the tutorial codes to adapt  your code accordingly.

As for getting the coordinates of the picked point, you can use the barycentric coordinates returned by the function to compute the position of the picked point (by averaging the face corners with the barycentric coefficients).
