### ISSUE TITLE
Async PNG writer

### ISSUE THREAD

**Issue by csverma610** [libigl/libigl#1192]
Hello,

I am wondering if there could be memory leak in async png writer in the
render_to_png_async.cpp. Who is responsible for freeing the memory 
of data? 

I am capturing many rendered images in an application, so, how can we
ensure that all the png files have been written if using detach thread?

Thanks

- [ ] Windows
- [ ] Mac OS X
- [* ] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by alecjacobson** [comment]
Not sure I understand the concern. The delete[] is called by the thread. https://github.com/libigl/libigl/blob/main/include/igl/opengl/stb/render_to_file_async.cpp#L29
