### ISSUE TITLE
Error can't find igl_stb_image.h

### ISSUE THREAD

**Issue by jlyw1017** [libigl/libigl#1199]
#### Describe your issue

I followed the instruction here
https://libigl.github.io/tutorial/
but I got 

[ 50%] Building CXX object CMakeFiles/velofu_texture_tool.dir/main.cpp.o
In file included from /home/jlyw/libigl/include/igl/png/readPNG.h:36:0,
                 from /home/jlyw/Masterarbeit/velofu_texture_tool/Function_and_Class.hpp:17,
                 from /home/jlyw/Masterarbeit/velofu_texture_tool/main.cpp:2:
/home/jlyw/libigl/include/igl/png/readPNG.cpp:9:10: **fatal error**: igl_stb_image.h: **No such file or directory**
 #include <igl_stb_image.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/velofu_texture_tool.dir/build.make:62: recipe for target 'CMakeFiles/velofu_texture_tool.dir/main.cpp.o' failed
make[3]: *** [CMakeFiles/velofu_texture_tool.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/velofu_texture_tool.dir/all' failed
make[2]: *** [CMakeFiles/velofu_texture_tool.dir/all] Error 2
CMakeFiles/Makefile2:84: recipe for target 'CMakeFiles/velofu_texture_tool.dir/rule' failed
make[1]: *** [CMakeFiles/velofu_texture_tool.dir/rule] Error 2
Makefile:118: recipe for target 'velofu_texture_tool' failed
make: *** [velofu_texture_tool] Error 2

if I clone and include this repo

https://github.com/libigl/libigl-stb

I still have

In file included from /home/jlyw/libigl/include/igl/png/readPNG.cpp:9:0,
                 from /home/jlyw/libigl/include/igl/png/readPNG.h:36,
                 from /home/jlyw/Masterarbeit/velofu_texture_tool/Function_and_Class.hpp:17,
                 from /home/jlyw/Masterarbeit/velofu_texture_tool/main.cpp:2:
/home/jlyw/libigl/include/libigl-stb/igl_stb_image.h:4:10: fatal error: igl_stb_image_export.h:**No such file or directory**
 #include <igl_stb_image_export.h>

#### Check all that apply (change to `[x]`)

Ubuntu 18.04

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by BruegelN** [comment]
I assume your project is based on the libigl-example-project.
Please ensure that the CMake flag `LIBIGL_WITH_PNG` is set to ON and that you link your taget against igl::png ( in CMakeLists.txt `target_link_libraries( [...] igl::png)` )
When running the cmake generate step the needed libs should be automatic downloaded.

If this does not work please check that you can compile the libigl tutorials first e.g. like :
```
cd libigl
mkdir build
cd build
cmake ../
make -j4
```

p.s. viel Erfolg bei der Masterarbeit! :)

**Comment by iAnyKey** [comment]
@jdumas, @jlyw1017  : Should we close it? It is not reproducible at v2.4.0( https://github.com/libigl/libigl/commit/66b3ef2253e765d0ce0db74cec91bd706e5ba176 ) for me anymore.
s. attached logs for more details:
[configuration.log](https://github.com/libigl/libigl/files/10082943/configuration.log)
[build.log](https://github.com/libigl/libigl/files/10083238/build.log)
