### ISSUE TITLE
Per-Face Curvature Calculations

### ISSUE THREAD

**Issue by csverma** [libigl/libigl#120]
I would like to calculate curvatures at each face of the triangle mesh similar
to what was described in the paper by "Szymon Rusinkiewicz" ( or better
technique) . Is there a way to do in the libigl or I will have to implement is 
using other pieces of the code in the libigl ?

Thanks.
csv

**Comment by alecjacobson** [comment]
This is not currently implemented, but yes we do have the bits and pieces that could be useful to implement yourself. See also: https://github.com/libigl/libigl/issues/95
