### ISSUE TITLE
camera eye position in the viewer class

### ISSUE THREAD

**Issue by jhwang7628** [libigl/libigl#1201]
I found that the ViewerCore class is a bit under-documented and so want to make sure what I am doing is correct. I want to know the world-space coordinate of my camera eye position and I use:
```
auto &core = viewer.core;
Eigen::Matrix<float,4,1> eye;
eye << core.camera_eye, 1.0f;
const Eigen::Matrix<double,3,1> camera_pos = (core.view.inverse() * eye).cast<double>().head(3);
```
Also, I would like to know if there is a modeling matrix that takes object-space coordinates to world-space coordinates? Thanks.

**Comment by jdumas** [comment]
The model matrix is gone in the `dev` branch, there is no such concept in the viewer (the meshes you provide are already in the world space). See related issue #1076 for more info on some other variables (but yes, documentation could be improved).

And I don't see anything wrong with your code to get the world-space camera position.

**Comment by jhwang7628** [comment]
Ok. That sounds good. I will have to write my own transformation then.
