### ISSUE TITLE
Polytope visulization, wrong direction within some normals

### ISSUE THREAD

**Issue by JianqiangDing** [libigl/libigl#1203]
#### Description

Hi, I'm trying to do some experiments with polytope mesh, the original vertices and faces indices are returned by qhull (http://www.qhull.org/html/qh-code.htm#cpp), I've checked the document of qhull, and confirmed each returned facet is  a region of the Delaunay triangulation, so I use this these vertices and indices as V and F to construct a mesh for visualization. but it turns out that some normals were in the wrong directions, so when I set the faced_base=true, some faces are black, is there something wrong when I was using these functions within libigl?? the screenshots following are captured with normals inverted and keep them original as libigl computed after calling of function viewer.data().set_mesh(V,F)
do I need to do some check about the F?? or V???
I was trying to invert these wrong normals manually, but I can only get all the normals, is there a way to check which is the wrong normals? 
any suggestion would be helpful 
![2019-05-30 14-53-34](https://user-images.githubusercontent.com/7833870/58614423-e0fac600-82ea-11e9-9c4f-d353ae0e152e.png)
![2019-05-30 14-54-16](https://user-images.githubusercontent.com/7833870/58614424-e1935c80-82ea-11e9-995d-d83cb6ab390b.png)

#### Check all that apply 
- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by jdumas** [comment]
You can try to call `igl::bfs_orient` to orient the normals consistently. Then you may need to flip them all to ensure positive volume.

**Comment by JianqiangDing** [comment]
thank you, only use bfs_orient can orient the normals consistently. but hard to detect whether or not need to flip them, so I checked the tutorial again and follow the example706, call igl::embree::reorient_facets_raycast, and address the problem, maybe this is not the best way, but it does work
thanks again, you can close the issue now

**Comment by jdumas** [comment]
There is code in libigl to orient a surface to have positive volume, but it's a bit hidden. See #880 for a discussion on the topic. In the meantime I had my own reimplementation of it:

```cpp
namespace {

inline double tetra_signed_volume(
	const Eigen::RowVector3d & p1, const Eigen::RowVector3d & p2,
	const Eigen::RowVector3d & p3, const Eigen::RowVector3d & p4
) {
	return (p2 - p1).dot((p3 - p1).cross(p4 - p1)) / 6.0;
}

// -----------------------------------------------------------------------------

double signed_volume(const Eigen::MatrixXd &V, const Eigen::MatrixXi &F) {
	assert(F.cols() == 3);
	assert(V.cols() == 3);
	std::array<Eigen::RowVector3d, 4> t;
	t[3] = Eigen::RowVector3d::Zero(V.cols());
	double volume_total = 0;
	for (int f = 0; f < F.rows(); ++f) {
		for (int lv = 0; lv < F.cols(); ++lv) {
			t[lv] = V.row(F(f, lv));
		}
		double vol = tetra_signed_volume(t[0], t[1], t[2], t[3]);
		volume_total += vol;
	}
	return -volume_total;
}

// -----------------------------------------------------------------------------

void orient_closed_surface(const Eigen::MatrixXd &V, Eigen::MatrixXi &F, bool positive) {
	if ((positive ? 1 : -1) * signed_volume(V, F) < 0) {
		for (int f = 0; f < F.rows(); ++f) {
			F.row(f) = F.row(f).reverse().eval();
		}
	}
}

} // anonymous namespace

////////////////////////////////////////////////////////////////////////////////

void orient_volume(const Eigen::MatrixXd &V, const Eigen::MatrixXi &F, Eigen::MatrixXi &FO) {
	Eigen::VectorXi C;
	igl::bfs_orient(F, FO, C);
	orient_closed_surface(V, FO, true);
}
```

**Comment by JianqiangDing** [comment]
thank you so much for the snippet, runs faster than the "raycast" method,  the problem solved
thanks again

Best
(now you can close the issue :) )
