### ISSUE TITLE
igl::signed_distance returns NaN for point 𝑜𝑛 the mesh

### ISSUE THREAD

**Issue by rodyo** [libigl/libigl#1204]
This is due to the check on line 158-ish: 

set the distance to `NaN` if `(sqrd >= up_sqr_d || sqrd <= low_sqr_d)` 

There is no way for points _on_ the mesh to satisfy this condition, even if `low_sqr_d = 0`. 

This is unexpected behavior: when computing the distance from a vertex or face centroid to the mesh, the distance should just be `0`, not `NaN`...

Making the following change would fix that: 
`sqrd <= low_sqr_d` → `sqrd < low_sqr_d`  

Or get rid of the lower bound altogether (though there is probably a good reason for it...)

**Comment by evouga** [comment]
I can confirm this bug. Here is a minimal example. First two assertions pass, but the last one fails.

````
#include <Eigen/Core>
#include <igl/signed_distance.h>

int main(int argc, char *argv[])
{
  // Inline mesh of a cube
  const Eigen::MatrixXd V= (Eigen::MatrixXd(8,3)<<
    0.0,0.0,0.0,
    0.0,0.0,1.0,
    0.0,1.0,0.0,
    0.0,1.0,1.0,
    1.0,0.0,0.0,
    1.0,0.0,1.0,
    1.0,1.0,0.0,
    1.0,1.0,1.0).finished();
  const Eigen::MatrixXi F = (Eigen::MatrixXi(12,3)<<
    1,7,5,
    1,3,7,
    1,4,3,
    1,2,4,
    3,8,7,
    3,4,8,
    5,7,8,
    5,8,6,
    1,5,6,
    1,6,2,
    2,6,8,
    2,8,4).finished().array()-1;

  Eigen::MatrixXd testpt(3,3);
  testpt << 1e-6, 0.5, 0.5,
  -1e-6, 0.5, 0.5,
  0, 0.5, 0.5;
  
  Eigen::VectorXd S;
  Eigen::VectorXi I;
  Eigen::MatrixXd C;
  Eigen::MatrixXd N;
  igl::signed_distance(testpt, V, F, igl::SIGNED_DISTANCE_TYPE_PSEUDONORMAL, -1.0, 1.0, S, I, C, N);
  
  assert(!std::isnan(S[0]));
  assert(!std::isnan(S[1]));
  assert(!std::isnan(S[2]));
}
````

**Comment by alecjacobson** [comment]
confirmed and fixed in https://github.com/libigl/libigl/commit/79e7a05b16fd6affb21e47975cead63c8fb75983.

Thank you for reporting and suggesting the fix.
