### ISSUE TITLE
Python Binding - AttributeError: module 'pyigl' has no attribute 'eigen'

### ISSUE THREAD

**Issue by oracle3001** [libigl/libigl#1207]
I have successfully build the python binding from the dev branch on a Windows machine using VS2017. Then, I have placed the .pyd in a sub-directory of my project called pyigl, which I have also added an empty __init__.py to.

I then call the standard 

`import pyigl as igl`

at the start of my script.

However, when I try and do a simple mesh import via

```
V = igl.eigen.MatrixXd()
F = igl.eigen.MatrixXi()
igl.readOFF("test.obj", V, F)
```

I get the error message stating module pyigl has no attribute eigen.

Edit - If I drop the .pyd directly into the folder of a script I am using, I can call the igl functions. However, I want to have it either in a subdirectory or more preferably in the site-packages so all scripts in a particular environment can use it.

I presume I must be doing something wrong in terms of the __init__.py ?
...

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [x] I have tried the `dev` branch and the problem persists

**Comment by teseoch** [comment]
the new version of the bindings uses numpy for the matrices.

for you example:
`v, f = igl.read_triangle_mesh("test.obj")`
and v and f will be numpy matrices
