### ISSUE TITLE
Per Face Curvature and Vector Fields

### ISSUE THREAD

**Issue by csverma** [libigl/libigl#121]
Hello,

Almost all the vector fields generation methods in libigl require face constraints and a 
natural constraint is derived from principal curvature line. Is there a way to specify 
such constraints ( for example in NRosy field or Integrable field ) or users are expected
to provide such constraints interactively by mouse click ? 

Thanks.
csv

**Comment by danielepanozzo** [comment]
Hi,

we currently do not have a way of computing curvature on faces, as already answered in the other issue that you opened a few hours ago. If the surface is sufficiently smooth, you can compute the principal directions on the vertices, and then simply average it on faces.
