### ISSUE TITLE
Python Binding Tutorial 102_DrawMesh - Incompatible function arguments

### ISSUE THREAD

**Issue by oracle3001** [libigl/libigl#1211]
When I attempt to run the simple DrawMesh tutorial, the call to the viewer crashes with the following error.

traceback (most recent call last):
  File "102_DrawMesh.py", line 28, in <module>
    viewer.data().set_mesh(V, F)
TypeError: data(): incompatible function arguments. The following argument types are supported:
    1. (self: pyigl.glfw.Viewer, arg0: int) -> pyigl.glfw.ViewerData

Invoked with: <pyigl.glfw.Viewer object at 0x0000015A04018E68>

...

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [x] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by lawsonfulton** [comment]
I ran into this too. Try replacing `data()` with `data(0)`.

**Comment by oracle3001** [comment]
Thanks, that worked.

**Comment by teseoch** [comment]
this issue involves the old bindings which have been discontinued, plz refer to https://libigl.github.io/libigl-python-bindings/ for the new version.

Note:
The viewer has been removed and replaced with
https://skoch9.github.io/meshplot/ or any other python viewer
