### ISSUE TITLE
cutting a mesh into separate patches

### ISSUE THREAD

**Issue by kabukunz** [libigl/libigl#1212]
Hello, this is my first post here. First of all, kudos and thank you for this little big library.
I'd like to ask a question about cutting a mesh into separate patches:

I use igl::cut_mesh(V, T, EFV, VCut, FCut) by passing a list of EFV edges, and I obtain a VCut,FCut mesh which contains a list of patches with shared vertices; this is the result of an UV Cutting, as is used in MIQ code.

Then I use igl::extract_manifold_patches(FCut, PCut), so I get PCut patches indices into different faces; in short, a face-patch relationship.

Now I want to take all patches, and effectively divide them all into different meshes, so that they are separated and can be fetched to a writeOBJ(outputFile, V, F, CN, FN, TC, FTC) for saving the patches as UV maps, after having fed them thru slim.

How can I do that? Is there a libigl function I can call to separate one mesh of patches into different meshes by patch? I've browsed around but I wasn't able to find one...

Forgot to say everything is manifold.

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by kabukunz** [comment]
Actually looks more complicated than I envisioned in the beginning...
Let's close it for now, I'll check on that back later.

**Comment by xarthurx** [comment]
Similar question in:
https://github.com/libigl/libigl/issues/1329
