### ISSUE TITLE
Python Callbacks Hang

### ISSUE THREAD

**Issue by lawsonfulton** [libigl/libigl#1214]
#### Describe your issue

When running one of the python tutorials with callbacks such as 103_Events.py, the program will freeze when a key is pressed.

I believe it could be related to this [this](https://github.com/pybind/pybind11/issues/813) issue but I don't have time to dig into it at the moment.
I've verified that the code reaches the line right before the python callback is called (Viewer.cpp:511).

I'm running the latest dev branch (with my recent PR  #1213 and the fix mentioned in issue #1211).
...

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [x] Mac OS X
- [ ] Linux
- [x] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by mikeroberts3000** [comment]
I've noticed this issue as well on the latest master commit as of October 26th, 2019. I haven't attempted to reproduce the problem on the latest dev branch. This issue occurs for me on macOS 10.14.5, complied against Anaconda Python 3.7. After building libigl, the Python tutorial examples work mostly correctly, but the Python callbacks hang.

**Comment by teseoch** [comment]
this issue involves the old bindings which have been discontinued, plz refer to https://libigl.github.io/libigl-python-bindings/ for the new version.

Note:
The viewer has been removed and replaced with
https://skoch9.github.io/meshplot/ or any other python viewer
