### ISSUE TITLE
Python Binding - Incompatible Buffer Format when using p2e help function

### ISSUE THREAD

**Issue by oracle3001** [libigl/libigl#1215]
When trying to convert a numpy array to an eigen matrix, I receive a runtime error. For example with the following simple code.

```
V = igl.eigen.MatrixXd()
F = igl.eigen.MatrixXi()
igl.readOBJ('test.obj', V, F)
F_np = e2p(F)
F_eigen = p2e(F_np)

....
    F_eigen = p2e(F_np)
    iglhelpers.py", line 17, in p2e
    return igl.eigen.MatrixXi(m.astype(np.int32))
RuntimeError: Incompatible buffer format!
```
...

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [x] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by teseoch** [comment]
this issue involves the old bindings which have been discontinued, plz refer to https://libigl.github.io/libigl-python-bindings/ for the new version.

Note:
The viewer has been removed and replaced with
https://skoch9.github.io/meshplot/ or any other python viewer
