### ISSUE TITLE
problem compiling examples

### ISSUE THREAD

**Issue by taramtaram** [libigl/libigl#122]
Hi, 

I am a new one in using libigl. I just started working with this library but I faced a problem. When I am running the Example 102 the following errors appear. Could you please help me with this?

ndefined symbols for architecture x86_64:
  "nanogui::FormScreen::addNewGroup(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, nanogui::FormScreen::Layout)", referenced from:
      igl::viewer::Viewer::init() in main.o
  "nanogui::FormScreen::addVariable(std::__1::function<void (bool)>, std::__1::function<bool ()>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, bool)", referenced from:
      igl::viewer::Viewer::init() in main.o
  "nanogui::FormScreen::addVariable(bool&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool)", referenced from:
      igl::viewer::Viewer::init() in main.o
  "nanogui::FormScreen::addVariable(float&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool)", referenced from:
      igl::viewer::Viewer::init() in main.o
  "nanogui::FormScreen::addNewWindow(Eigen::Matrix<int, 2, 1, 0, 2, 1> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      igl::viewer::Viewer::init() in main.o
  "nanogui::FormScreen::addColorPicker(Eigen::Matrix<float, 3, 1, 0, 3, 1>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool)", referenced from:
      igl::viewer::Viewer::init() in main.o
  "nanogui::FormScreen::draw()", referenced from:
      igl::viewer::Viewer::draw() in main.o
  "nanogui::FormScreen::addButton(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void ()>)", referenced from:
      igl::viewer::Viewer::init() in main.o
  "nanogui::FormScreen::FormScreen(float)", referenced from:
      igl::viewer::Viewer::launch_init(bool, bool) in main.o
  "nanogui::Screen::initScreen(GLFWwindow*)", referenced from:
      nanogui::FormScreen::init(GLFWwindow*) in main.o
  "nanogui::Screen::keyCallbackEvent(GLFWwindow*, int, int, int, int)", referenced from:
      nanogui::FormScreen::keyEvent(GLFWwindow*, int, int, int, int) in main.o
  "nanogui::Screen::charCallbackEvent(GLFWwindow*, unsigned int)", referenced from:
      nanogui::FormScreen::charEvent(GLFWwindow*, unsigned int) in main.o
  "nanogui::Screen::dropCallbackEvent(GLFWwindow*, int, char const**)", referenced from:
      nanogui::FormScreen::dropEvent(GLFWwindow*, int, char const**) in main.o
  "nanogui::Screen::scrollCallbackEvent(GLFWwindow*, double, double)", referenced from:
      nanogui::FormScreen::scrollEvent(GLFWwindow*, double, double) in main.o
  "nanogui::Screen::cursorPosCallbackEvent(GLFWwindow*, double, double)", referenced from:
      nanogui::FormScreen::cursorPosEvent(GLFWwindow*, double, double) in main.o
  "nanogui::Screen::mouseButtonCallbackEvent(GLFWwindow*, int, int, int)", referenced from:
      nanogui::FormScreen::mouseButtonEvent(GLFWwindow*, int, int, int) in main.o
  "_glfwCreateWindow", referenced from:
      igl::viewer::Viewer::launch_init(bool, bool) in main.o
  "_glfwDestroyWindow", referenced from:
      igl::viewer::Viewer::launch_shut() in main.o
  "_glfwGetCurrentContext", referenced from:
      igl::viewer::TextRenderer::BeginDraw(Eigen::Matrix<float, 4, 4, 0, 4, 4> const&, Eigen::Matrix<float, 4, 4, 0, 4, 4> const&, Eigen::Matrix<float, 4, 1, 0, 4, 1> const&, float) in main.o
  "_glfwGetFramebufferSize", referenced from:
      igl::viewer::Viewer::launch_init(bool, bool) in main.o
      igl::viewer::TextRenderer::BeginDraw(Eigen::Matrix<float, 4, 4, 0, 4, 4> const&, Eigen::Matrix<float, 4, 4, 0, 4, 4> const&, Eigen::Matrix<float, 4, 1, 0, 4, 1> const&, float) in main.o
  "_glfwGetPrimaryMonitor", referenced from:
      igl::viewer::Viewer::launch_init(bool, bool) in main.o
  "_glfwGetVideoMode", referenced from:
      igl::viewer::Viewer::launch_init(bool, bool) in main.o
  "_glfwGetWindowAttrib", referenced from:
      igl::viewer::Viewer::launch_init(bool, bool) in main.o
  "_glfwGetWindowSize", referenced from:
      igl::viewer::Viewer::launch_init(bool, bool) in main.o
      igl::viewer::TextRenderer::BeginDraw(Eigen::Matrix<float, 4, 4, 0, 4, 4> const&, Eigen::Matrix<float, 4, 4, 0, 4, 4> const&, Eigen::Matrix<float, 4, 1, 0, 4, 1> const&, float) in main.o
  "_glfwInit", referenced from:
      igl::viewer::Viewer::launch_init(bool, bool) in main.o
  "_glfwMakeContextCurrent", referenced from:
      igl::viewer::Viewer::launch_init(bool, bool) in main.o
  "_glfwPollEvents", referenced from:
      igl::viewer::Viewer::launch_rendering(bool) in main.o
  "_glfwSetCharModsCallback", referenced from:
      igl::viewer::Viewer::launch_init(bool, bool) in main.o
  "_glfwSetCursorPosCallback", referenced from:
      igl::viewer::Viewer::launch_init(bool, bool) in main.o
  "_glfwSetDropCallback", referenced from:
      igl::viewer::Viewer::launch_init(bool, bool) in main.o
  "_glfwSetErrorCallback", referenced from:
      igl::viewer::Viewer::launch_init(bool, bool) in main.o
  "_glfwSetInputMode", referenced from:
      igl::viewer::Viewer::launch_init(bool, bool) in main.o
  "_glfwSetKeyCallback", referenced from:
      igl::viewer::Viewer::launch_init(bool, bool) in main.o
  "_glfwSetMouseButtonCallback", referenced from:
      igl::viewer::Viewer::launch_init(bool, bool) in main.o
  "_glfwSetScrollCallback", referenced from:
      igl::viewer::Viewer::launch_init(bool, bool) in main.o
  "_glfwSetWindowShouldClose", referenced from:
      glfw_key_callback(GLFWwindow*, int, int, int, int) in main.o
  "_glfwSetWindowSizeCallback", referenced from:
      igl::viewer::Viewer::launch_init(bool, bool) in main.o
  "_glfwSwapBuffers", referenced from:
      igl::viewer::Viewer::launch_rendering(bool) in main.o
  "_glfwTerminate", referenced from:
      igl::viewer::Viewer::launch_init(bool, bool) in main.o
      igl::viewer::Viewer::launch_shut() in main.o
  "_glfwWaitEvents", referenced from:
      igl::viewer::Viewer::launch_rendering(bool) in main.o
  "_glfwWindowHint", referenced from:
      igl::viewer::Viewer::launch_init(bool, bool) in main.o
  "_glfwWindowShouldClose", referenced from:
      igl::viewer::Viewer::launch_rendering(bool) in main.o
  "_nvgBeginFrame", referenced from:
      igl::viewer::TextRenderer::BeginDraw(Eigen::Matrix<float, 4, 4, 0, 4, 4> const&, Eigen::Matrix<float, 4, 4, 0, 4, 4> const&, Eigen::Matrix<float, 4, 1, 0, 4, 1> const&, float) in main.o
  "_nvgCreateFontMem", referenced from:
      igl::viewer::TextRenderer::Init() in main.o
  "_nvgCreateGL3", referenced from:
      igl::viewer::TextRenderer::Init() in main.o
  "_nvgDeleteGL3", referenced from:
      igl::viewer::TextRenderer::Shut() in main.o
  "_nvgEndFrame", referenced from:
      igl::viewer::TextRenderer::EndDraw() in main.o
  "_nvgFillColor", referenced from:
      igl::viewer::TextRenderer::DrawText(Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in main.o
  "_nvgFontFace", referenced from:
      igl::viewer::TextRenderer::DrawText(Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in main.o
  "_nvgFontSize", referenced from:
      igl::viewer::TextRenderer::DrawText(Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in main.o
  "_nvgRGBA", referenced from:
      igl::viewer::TextRenderer::DrawText(Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in main.o
  "_nvgText", referenced from:
      igl::viewer::TextRenderer::DrawText(Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in main.o
  "_nvgTextAlign", referenced from:
      igl::viewer::TextRenderer::DrawText(Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by alecjacobson** [comment]
What system are you on? Is this after running cmake for the tutorial?

**Comment by taramtaram** [comment]
I am on a OSX machine, using XCode. I run the CMake, and then I tried to compile the example but it does not work. 

p.s. example 101 works...

**Comment by danielepanozzo** [comment]
We need more informations to debug the problem, please try to be very precise in your report.
Could you please write down ALL the commands that you used to download the library and create the xcode project with cmake?

From the error it seems that nanogui is missing, maybe you cloned the library without the recursive option? You could try to clone it again with this command:
git clone --recursive https://github.com/libigl/libigl.git

**Comment by danielepanozzo** [comment]
We now have continuous builds for macosx and all examples compiles. Please take a look at:
https://travis-ci.org/libigl/libigl

and check if you are doing something different.
