### ISSUE TITLE
Heat geodesics example crashes

### ISSUE THREAD

**Issue by windblast942** [libigl/libigl#1230]
#### Describe your issue
Running the tutorial `716_HeatGeodesics_bin` on the default file `beetle.off` crashes with a `vector subscript out of range` error. 

It seems to be triggered by `slice()` in `min_quad_with_fixed.cpp` while running the function `heat_geodesics_precompute()`.

#### Check all that apply (change to `[x]`)
- [X] Windows
- [ ] Mac OS X
- [ ] Linux
- [X] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by BruegelN** [comment]
A similar issue is described in #1149
Which version of Visual Studio are you using?
I've verified it myself that this error still persists in VS2019.

**Comment by windblast942** [comment]
> A similar issue is described in #1149
> Which version of Visual Studio are you using?
> I've verified it myself that this error still persists in VS2019.

I am using VS2017.

**Comment by oracle3001** [comment]
It definitely appears to be a Visual Studio / Windows issue. I have built off the dev branch with Windows and on Ubuntu, the windows version crashes on the precompute method, where as the Ubuntu version works fine.

**Comment by xinyazhang** [comment]
I put the following assertions at slice.cpp:64 and they failed
```
	  assert(it.row() >= 0);
	  assert(it.row() < xm);
	  assert(it.col() >= 0);
	  assert(it.col() < xn);
```
It seems the [standard iteration code of Eigen::SparseMatrix](https://eigen.tuxfamily.org/dox/group__TutorialSparse.html) cannot guarantee the iterator is always valid on Windows.

We could add the following code at Line 64 to fix this issue
```
	    if (it.row() >= xm || it.col() >= xn)
		    break;
```
However this is not the solution. After applying the patch above, another index out of range error would be raised during the execution of `SparseMatrix<T> AeqT = Aeq.transpose();` (min_quad_with_fixed.cpp:177).

Now I'm guessing this is a bug, or a series of bugs from Eigen on Windows.

Tested on:
Windows 10.0.17134 Build 17134
Visual Studio 15.8.2
Microsoft (R) C/C++ Optimizing Compiler Version 19.15.26726 for x86
libigl v2.1.0
eigen3 3.3.7-2 (from [vcpkg](https://github.com/Microsoft/vcpkg))

by the way my Linux build works pretty well (gcc 8.3.1, Eigen 3.3.7)

**Comment by xinyazhang** [comment]
Confirmed, this is an Eigen bug -- at least partially from Eigen.

Code snippet to reproduce
```
#include "assert.h"
#include <vector>

#include <Eigen/Core>
#include <Eigen/SparseCore>

constexpr int K = 4;
typedef Eigen::Triplet<double> Tri;

void iter(const Eigen::SparseMatrix<double>& X)
{
	int xm = X.rows();
	int xn = X.cols();
	for(int k=0; k<X.outerSize(); ++k) {
		for(typename Eigen::SparseMatrix<double>::InnerIterator it (X,k); it; ++it) {
			assert(it.row() >= 0);
			assert(it.row() < xm);
			assert(it.col() >= 0);
			assert(it.col() < xn);
		}
	}
}

int main()
{
	Eigen::SparseMatrix<double> M(K, K);
	std::vector<Tri> tris;
	tris.reserve(K);
	for (int i = 0; i < K; i++)
		tris.emplace_back(i, i, 1.0);
	M.setFromTriplets(tris.begin(), tris.end());
	const Eigen::SparseMatrix<double> Aeq = M.diagonal().transpose().sparseView();
	iter(Aeq);

	return 0;
}
```

**Comment by jdumas** [comment]
@xinyazhang has this bug been reported upstream?

**Comment by xinyazhang** [comment]
> @xinyazhang has this bug been reported upstream?

No I haven't. I'm writing an email to eigen so I can report this to upstream.
(Sorry for the late reply.)

**Comment by xinyazhang** [comment]
filed to Eigen as https://eigen.tuxfamily.org/bz/show_bug.cgi?id=1754

**Comment by jdumas** [comment]
Fixed by #1288

**Comment by ioanna21** [comment]
Hello,
I see that this issue is closed, but I am running into the same problem. The tutorial 716_HeatGeodesics_bin crashes in the function `heat_geodesics_precompute()` with the `vector subscript out of range error`. 
Any suggestions on how to overcome this? 
Thanks!

**Comment by ioanna21** [comment]
I switched to dev and it works. Thanks!
