### ISSUE TITLE
Documentation issue for Fast Winding Number for Soups

### ISSUE THREAD

**Issue by dcoeurjo** [libigl/libigl#1232]
#### Describe your issue

In the documentation, there is a note saying that the brand new fast winding number for soups functions are in the `dev` branch but they are in the `origin/fast-winding-number-soups` one.

#### Check all that apply (change to `[x]`)
- [x] Windows
- [x] Mac OS X
- [x] Linux
- [x] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by jdumas** [comment]
That's because we haven't merged #1218 yet :D

**Comment by dcoeurjo** [comment]
yeah I saw that.. but will it be merged to the dev or master branch?

**Comment by dcoeurjo** [comment]
`dev` apparently

**Comment by dcoeurjo** [comment]
but still, at this point the documentation should probably refer to the `fast-winding-number-soups` branch, not the `dev` one

**Comment by jdumas** [comment]
Yes, `master` get updated every 6 months or so, with proper tags and changelog. `dev` is the stable development branch where the new stuff gets merged.

**Comment by jdumas** [comment]
I've updated the info box in the website to reflect that #1218 isn't merged yet (needs unit tests).

**Comment by dcoeurjo** [comment]
thx;)
