### ISSUE TITLE
Mesh Boolean Performance issues

### ISSUE THREAD

**Issue by wofsauge** [libigl/libigl#1238]
Im currently trying to get into the Libigl framework and therefore tried out most of the example projects. When i run the 609_boolean_bin Project, the command prompt opens, displays the usual Viewer Hotkeys and then it tried to compute the mesh boolean from the "decimated-knight" and "cheburashka" model. But even after several minutes of waiting it never finishes this task while also only using ~20mb of ram constantly.
I then tried to replace the meshes with the cube and xcylinder objects. The project now uses ~3mb of RAM and finishes after ~12 seconds. But this is still a very bad performance for such low quality meshes.

**Is there any way to make this task faster or use more RAM?** 

PS: I also tried a to test, if there is something wrong with the memory allocator or my PC itself by using the following code which uses 4gb of RAM:
`for (int i = 0; i < 4000000; ++i) {
    char* ch = new char[1024];
}`
Result was a fast increase of the uses memory by 4GB (which is expected).

**Specs of my PC:**
32GB RAM
Intel I7-4800MQ (2,7GHz)
Nvidia Quadro K1100M (18GB)

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] I have tried the `dev` branch and the problem persists

**Comment by jdumas** [comment]
Are you compiling in Debug or Release?

**Comment by wofsauge** [comment]
Debug and 64-bit (Visual Studio 14 2015)

**Comment by jdumas** [comment]
Try in Release, it should be much faster.

**Comment by wofsauge** [comment]
in release mode it still takes 2:53 minutes for the  "decimated-knight" and "cheburashka" models. it doesnt really feel that much faster to be honest.

**Comment by jdumas** [comment]
I just tried on my Windows laptop (i7-8850H, 32GB of RAM), with MSVC 2017 in Release mode, and each operation in the tutorial 609 only takes a couple of seconds at most on the default meshes.

**Comment by evouga** [comment]
@wofsauge Have you tried a complete clean and rebuild of the application? I usually see a huge performance difference (~10x) between Debug and Release configurations (even the responsiveness of the GUI is noticeably different). It's a bit strange if you're not noticing a change at all.

**Comment by wofsauge** [comment]
Ived now reinstalled everything and directly tried to build the Dev-branch. Building it in Debug mode did the same results. The Release mode on the other hand did increase the speed by alot. The example 609 now starts in ~4-5 seconds, which is significantly faster than the 2,5 minutes :D 
I dont really understand why this issue occured, but for now, it should work fine enough for my tasks.
Thanks you two for helping me :)

**Comment by jdumas** [comment]
Eigen has huge performance differences between Debug and Release. I have no idea why you'd have to rebuild from a clean folder though, that shouldn't be needed.

**Comment by alecjacobson** [comment]
Re: EDIT: How do i fix that issue, where the function says "Input mesh is not PWN"? what does that mean?

See https://www.cs.columbia.edu/cg/mesh-arrangements/#definitions Meshes need to meet certain preconditions to use booleans. You may need to repair your meshes (I like the meshfix tool).
