### ISSUE TITLE
Tutorial fails to execute

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#124]
From personal email:

> I am trying to use the libigl for our project but I faced a problem. Following your tutorial, I compile the examples with the terminal by using the suggested commands:

>```
cd tutorial
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ../
make
```
>
> After the compile process is finished, when I run any of the examples, errors like the following appear:

>    XXX-mbp:~ XX$ /Users/XXX/libigl/tutorial/build/102_DrawMesh_bin ; exit;
    IOError: ../shared/bunny.off could not be opened...
    edge_lengths.h: Error: Simplex size (0) not supported

> Is something wrong with the compile process or is it required any additional action by me?

> Just in case, I am running your library in Mac OSX 10.10.

> Could you please help me with this?

**Comment by alecjacobson** [comment]
The problem seems to be that you're running the example from the home directory `~` instead of running the example from within the `libigl/tutorial/build` directory where the [relative path](https://en.wikipedia.org/wiki/Path_(computing)#Unix_style) `../shared/bunny.off` will point to the correct file.

**Comment by ChrisMousas** [comment]
I am attaching an image that shows the directory that the compiled tutorials are located. As you can see the outputs are located into the libigl/tutorial/build directory and the root for the missing file (../shared/bunny.off) is correct. Am I wrong?

![img](https://cloud.githubusercontent.com/assets/11978959/10120020/df5eba5e-6476-11e5-9cea-f6fa7ba410dd.png)

**Comment by alecjacobson** [comment]
I'm guessing that you're double-clicking on `102_DrawMesh_bin` from Finder. Is that right? The executables that cmake creates are not really generic user-friendly apps, but rather binaries that are expected to be run directly from a terminal. In Terminal.app try:

    cd ~/libigl/tutorial/build
    ./102_DrawMesh_bin

you may need to replace `~/libigl/tutorial/build` with the exact path of your libigl folder.
