### ISSUE TITLE
need help to delay a function without time.sleep()? thanks in advance

### ISSUE THREAD

**Issue by jab05** [libigl/libigl#1241]
need to add a time delay before jumping again
 
import turtle as t
import time
wn = t.Screen()
t.left(90)
x=-335
y=-275
t.up()
t.goto(x, y)
def playerj():
    global y
    y = y+35
wn.onkey(playerj, "w")
wn.listen()

while True:
    t.goto(x, y)
    y = y-1
    time.sleep(0.03)

**Comment by jdumas** [comment]
Not sure I understand your question.

**Comment by jab05** [comment]
> Not sure I understand your question.

if you use time.sleep() it will pause the entire code whereas i would need it to only stop a function from repeating until a certain amount of time has passed

**Comment by jdumas** [comment]
What are you talking about? `python/tcpviewer.py`?

**Comment by jab05** [comment]
for the game i need to stop the function that makes you jump stop if a certain amount of time has passed since it last was ran

**Comment by jdumas** [comment]
I'm sorry but you need to be able to explain more clearly what is the problem you are doing and what you want from us. We can't program your game for you, so until you formulate your issue in a way I can understand I'm closing this.

**Comment by jab05** [comment]
for the game you shouldn't be able to jump infinitely as that would just allow you to skip it all but i don't know how you could require x amount of time until the function can run again. i've tried

def jump():
  start = time.time()
  if time.time()-start< x:
    return
