### ISSUE TITLE
Duplicate duplicate vertex functions

### ISSUE THREAD

**Issue by ikoruk** [libigl/libigl#1243]
There are two files for removing duplicate vertices: `remove_duplicates` and `remove_duplicate_vertices` with the latter being much much faster than the first one since the first is a double for loop.

Maybe `remove_duplicates` should be removed?

**Comment by jdumas** [comment]
I think you mean `remove_duplicate_vertices` for the second. But yes I agree this is confusing. I never know which one to use, so I look at the last time both files were edited and take the most recent one :p 

We should either remove the old one or mark it as deprecated. Although we currently don't have a way to mark a function as `[[decrecated]]` (the tag is C++14). @alecjacobson any thoughts?

**Comment by ikoruk** [comment]
Yes, corrected.

Actually looking into it further, they don't do the same thing, with `remove_duplicates` using actual L2 distance, while `remove_duplicate_vertices` uses truncation which is not very reliable. It's just with a double for loop, `remove_duplicates` is all but useless on large meshes. Maybe a better strategy would be building a Delaunay triangulation and merging vertices tied to small edges or looking up in a kd tree.

I think the face versions should also clean up degenerate edges themselves, see https://github.com/libigl/libigl/issues/1078#issuecomment-505840659

**Comment by jdumas** [comment]
Well `remove_duplicate_vertices` is a L1 distance for the tolerance, which is probably fine for most usage. If one wants to use L2 the way to go would be to use a Kd-Tree such as Nanoflann to detect and merge points within a given tolerance radius.

**Comment by ikoruk** [comment]
Yea, I was just speculating to what the reason was for both to be kept.

**Comment by alecjacobson** [comment]
yes. let's just delete remove_duplicates in dev and mark it as deprecated
in the comments in master. Been meaning to do this for a while.

**Comment by jdumas** [comment]
Should we have a system with a macro IGL_DEPRECATED that gives off a compiler warning when someone uses a deprecated function (more visible than a comment that might go unnoticed), and keep the function for one version before removing it in the following release?

**Comment by alecjacobson** [comment]
We could. I wonder if anyone is using it who shouldn't be using
remove_duplicate_vertices

**Comment by BruegelN** [comment]
@jdumas I think https://github.com/libigl/libigl/blob/master/include/igl/deprecated.h already does this :)
However one might change 
```C++
#ifdef __GNUC__
```
to 
```C++
#if defined(__GNUC__) || defined(__clang__)
```
similar to the updated version in the stackoverflow link in `deprecated.h`.

**Comment by jdumas** [comment]
Perfect, let's do this then =)
