### ISSUE TITLE
std::runtime_error with no error message when computing normals

### ISSUE THREAD

**Issue by pzpzpzp1** [libigl/libigl#1246]
#### Describe your issue
I've already debugged and found the reason. Consider the following two lines of code. If your .obj file has 6 numbers per vertex, e.g. xyz and then color, then VMesh will be Nx6 instead of Nx3. Then trying to compute face normals will result in a runtime_error with no understandable error message because it will try to assign a temporary 1x3 variable to a row of VMeshT under the assumption that VMesh has only 3 columns.

igl::readOBJ(meshname, VMesh, FMesh);
igl::per_face_normals(VMesh, FMesh, normals);

I think a reasonable fix would be to simply assert within per_face_normals that VMesh have 3 columns. This makes it very easy for a user to realize what went wrong. Maybe even display a warning in readOBJ saying the VMesh has 6 values per vertex instead of 3.

...

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [x ] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by alecjacobson** [comment]
debug `assert` pull requests are very welcome! Almost every libigl function could probably have better debug assertions on input sizes. In general, the only advice I can give currently is to read the documentation for any misbehaving function and hopefully it will be clear if there's an input error.
