### ISSUE TITLE
Point handles in BBW

### ISSUE THREAD

**Issue by Mydrako** [libigl/libigl#1249]
#### Describe your issue
Hi,
I am trying to implement bbw calculation in maya to get better automatic skin weights calculation but I realize in the bbw implementation, the point handles needs to lie on the vertex position of the input mesh, else the calculated skin weights will be weird. In alot of cases in rigs, the skin joints does not rest specifically on the vertices so this greatly decrease the usefulness of this algo. Is it a requirement of the BBW algorithm that the point handles must lie on the input mesh vertices? 

Thanks!

**Comment by alecjacobson** [comment]
Ideally, you'd refine your mesh to include the point handle in the mesh.

Otherwise, for point handles lying in the middle of a tet/triangle you can
simply treat the tet it falls in as a small region handle (fix the weights
of that handle to =1 for all vertices of that tet. If the mesh is
reasonably high resolution near the point this will work fine.

**Comment by Mydrako** [comment]
I see. Unfortunately, we usually cannot make any changes to the mesh. And in most cases, we won't want the handles to be on the vertices. For example, for a handle that deform a lip, u would want it to be in the middle of the lip volume so that rotating it will produce pleasing lip curl. One way is to offset the handles from the actual control but I think that would make the rig abit messy.

And also in some cases, we have joints that are floating in the middle of the geom ( example in the middle of an arm) but it is not a bone edge. Is it still possible to use bbw to calculate weights for such a setup?

And a question about ur second point of making the triangle's weight to be =1 for that handle, how do we do that? FYI, I am using it on a triangular mesh.

**Comment by alecjacobson** [comment]
So we're on the same page, you can compute BBW on 1) the surface of a
triangle mesh or 2) on a volumetric tet mesh filling the solid region on
_inside_ your surface.

For handles floating in the interior, the best thing to do is to
volumetrically mesh the inside, compute BBW and then keep just the weights
on the surface.

For handles in the middle of an element, if you want to avoid remeshing
then you can identity all vertices of the triangle containing the handle
and force their weight values to be 1 for this handle and zero for all
other handles via the b,bc parameters.

-Alec

>

**Comment by Mydrako** [comment]
That is a good idea with using a tet mesh to solve for floating handles. 

I will look into how to set the weights to 1 for the handles. Thanks for your help!
