### ISSUE TITLE
Dirty flags in igl::opengl::ViewerData::set_colors()

### ISSUE THREAD

**Issue by BruegelN** [libigl/libigl#1250]
#### Describe your issue
When setting a color through `igl::opengl::ViewerData::set_colors()` only `dirty |= MeshGL::DIRTY_DIFFUSE;` is set. (see https://github.com/libigl/libigl/blob/master/include/igl/opengl/ViewerData.cpp#L211)
So when changing the color a second time it'll leaf some artifacts that shine through from the first call of `set_colors()` because the ambient and specular terms aren't overwritten properly inside `updateGL()`.

Here are some screenshot from a [slightly modified version](https://github.com/BruegelN/libigl/blob/rework-colormaps/tutorial/104_Colors/main.cpp) of tutorial 104.
Generate a colormap with `igl::jet(Z,true,C)` and then `set_colors(C)`
![Bildschirmfoto vom 2019-07-09 11-49-01](https://user-images.githubusercontent.com/9728182/60879987-03b1c000-a243-11e9-98db-5fe2ef18e324.png)

The artifacts becomes clearly visible when changing the color to white with `C.setOnes()` then a second call to `set_colors(C)` (e.g. with black/`C.setZero()` it also shines through.)
![Bildschirmfoto vom 2019-07-09 11-49-13](https://user-images.githubusercontent.com/9728182/60879998-07454700-a243-11e9-9853-38db844849fd.png)

And this is the way I'd expected it to look like:
![Bildschirmfoto vom 2019-07-09 11-49-25](https://user-images.githubusercontent.com/9728182/60880005-09a7a100-a243-11e9-8f55-9cb18bfc3969.png)

To fix this you need to set all 3 flags( `dirty |= MeshGL::DIRTY_SPECULAR | MeshGL::DIRTY_DIFFUSE | MeshGL::DIRTY_AMBIENT;`) inside `set_color()`. Like already done in [igl::opengl::ViewerData::uniform_colors()](https://github.com/libigl/libigl/blob/master/include/igl/opengl/ViewerData.cpp#L415-L442).

Is there any reason (I've might missed) that this isn't done yet?
If not, just let me know. I'm happy to submit a PR for this.

#### Check all that apply (change to `[x]`)
- [x] Windows
- [x] Mac OS X
- [x] Linux
- [x] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by jdumas** [comment]
Hmm seems like an omission. Feel free to submit a PR =)
