### ISSUE TITLE
ARAP Mesh Deformation failed

### ISSUE THREAD

**Issue by JianqiangDing** [libigl/libigl#1252]
https://github.com/libigl/libigl/blob/f6b406427400ed7ddb56cfc2577b6af571827c8c/include/igl/min_quad_with_fixed.cpp#L222
Hi, I am trying to use arap mesh deformation method to do some test, the mesh I am using is like this:
![2019-07-10 22-29-46](https://user-images.githubusercontent.com/7833870/60978108-39e66100-a363-11e9-994a-f9c21de755c7.png)
but the programe always broken with Numerical Issue in min_quad_with_fixed.cpp(Line 222),
i don't get  the reason of the issue, could you please provide some clues?
the way I am calling ARAP method is:

        igl::ARAPData arap_data;
	arap_data.max_iter		 = 100;
	arap_data.energy		 = igl::ARAPEnergyType::ARAP_ENERGY_TYPE_DEFAULT;
	int				debugCnt = 3;
	Eigen::VectorXi b;
	b.resize(debugCnt);
	Eigen::MatrixXd					 bc(b.rows(), triVF.first.cols());
	std::random_device				 rd;
	std::mt19937					 gen(rd());
	std::uniform_int_distribution<>  dist(0, triVF.first.rows() - 1);
	std::uniform_real_distribution<> realDist(-0.5, 0.5);
	for (std::size_t index = 0; index < debugCnt; ++index)
	{
		Eigen::RowVector3d offset;
		offset(0) = realDist(gen);
		offset(1) = realDist(gen);
		offset(2) = 0.0;
		// int curIndex  = dist(gen);
		int curIndex  = index;
		b(index)	  = curIndex;
		bc.row(index) = triVF.first.row(curIndex) /*+ offset*/;
	}
	std::cout << b << std::endl;
	std::cout << bc << std::endl;
	igl::arap_precomputation(triVF.first, triVF.second, triVF.first.cols(), b, arap_data);
	Eigen::MatrixXd U = triVF.first;
	igl::arap_solve(bc, arap_data, U);

I don't know if is the mesh within some extreme small triangles inside, is there some other methods can I use to do the deformation robustly?

**Comment by JianqiangDing** [comment]
the program is the debug version, even without any kind of vertices moved, the program still crashed, triVF is the triangulation result, which is a pair including V(vertices) as the first item and F(facets) as the second item

**Comment by JianqiangDing** [comment]
Hi, did you reproduce the failure case? I can provide a demo program with mesh data if necessary.

**Comment by lilingtongji** [comment]
> Hi, did you reproduce the failure case? I can provide a demo program with mesh data if necessary.

I also faced this problem and solved it by adding more boundary points, following Alec's suggestion in https://github.com/libigl/libigl/issues/343
Moreover, it is actually not a bug of ligigl, it is an error msg from Eigen, which tells you that the constrain matrix could not do qr factoring.

**Comment by JianqiangDing** [comment]
@lilingtongji , big thanks for the comment, you are right, adding more boundary constraints is the easiest and effective way to address the problem, thank you for the help.
@jdumas thanks anyway.
