### ISSUE TITLE
pyigl wants to link release python lib when being built under debug mode

### ISSUE THREAD

**Issue by ghost** [libigl/libigl#1253]
#### Describe your issue
When building under Debug mode in Visual Studio 2015, pyigl wants to link python37.lib which is the Release version of python lib, rather than python37_d.lib which is what should be linked under Debug mode. As a consequence, the linker seems to search somewhere for python37.lib where it does not exists and reports an error "cannot open file python37.lib" accordingly. If I specify the lib path of python37.lib (C:\Program Files\Python37\libs) in VS, the Debug mode building completes with no error. This problem does not appear under Release mode. Due to the large scale of libigl, I don't have time to find out what specific cmake setting leads to this issue, so I just report this problem and my workaround here.
...

#### Check all that apply (change to `[x]`)
- [x] Windows 10, 64bit, version 1803
- [ ] Mac OS X
- [ ] Linux
- [ ] I have tried the `dev` branch and the problem persists
- [x] Visual Studio 2015 Update 3
- [x] Today's master branch of libigl. Not clear what version number it is.
- [x] CMake 3.14.5
- [x] Python 3.7.4

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by fwilliams** [comment]
Hi, you may want to try the new libigl python bindings available on conda (just `conda install -c conda-forge igl`). They're still in beta and missing some functions, but they're much easier to use and directly compatible with numpy/scipy. 

Tutorial is [here](https://geometryprocessing.github.io/libigl-python-bindings/tutorials/)
Function reference is [here](https://geometryprocessing.github.io/libigl-python-bindings/igl_docs/)

**Comment by teseoch** [comment]
now that the official bindings are out, this seems outdated.
If the problem persists open an issue on https://github.com/libigl/libigl-python-bindings/
