### ISSUE TITLE
Where is the documentation?

### ISSUE THREAD

**Issue by zhfsu** [libigl/libigl#1254]
#### Describe your issue
Sorry if my question sounds stupid, but where is the documentation of libigl? As a user, I think there should be a link somewhere on the left side of https://libigl.github.io/ which contains all the online documentation, but there isn't. Or, there should be a sub dir named `docs` in the root dir of libigl which contains all the offline documentation, but there isn't. If the doc can be generated during the building, I'm glad to do that, but I did not see any instruction in the homepage of libigl. I searched in cmake-gui in the hope of finding some var like `BUILD_DOC` or `LIBIGL_WITH_DOC`, but of no avail. I searched google using key words, e.g., libigl Viewer::append_mesh documentation, but I was returned nothing useful for this method. For now, being at my wit's end, I can only use libigl functions by guesswork based on its source code. So, where is the documentation of libigl, if there is any at all? Note that tutorial is NOT doc. Thank you.
...

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by jdumas** [comment]
For now the only documentation we have is the tutorial on the website. For example, you'll notice in the tutorial `107_MultipleMeshes`, the function `load_mesh_from_file()` calls `append_mesh()`, so you can see how it is used there. The documentation of the functions are in the header files (the viewer is a bit special and we need to improve its documentation). Usually when I look a functionality I just do a <kbd>Ctrl+F</kbd> on [this page](https://github.com/libigl/libigl/tree/dev/include/igl), or use the github search function in libigl repository (since it also returns bug reports and discussion, e.g. about how to use the viewer).

**Comment by zhfsu** [comment]
Thank you for the reply. Tutorial is a good material to learn libigl, but it has two shortcomings. First, it does not contain details of how to use a method. Taking `viewport` property used in 108_MultiViewers as an example, I had thought at first that the four components of Vector4f passed to it are two coordinates representing the top-left and bottom-right corner, respectively, and this guessed usage confused me quite a while. After that I finally realized that the latter two components are width and height of the viewport. If there is a documentation for the `viewport` property, such a confusion could have been avoided. Second, tutorial is incomplete. If a function happens to appear in the tutorial, I know it, but what about those functions that do not show up in tutorial? A full documentation gives users an opportunity to explore new functions so that they can decide which function is the best for their application. As you mentioned, I learned from the tutorial that function `viewer::load_mesh_from_file()` can be used to load mesh. But users lose a chance to know that `igl::read_triangle_mesh()` can also do the same job. As a side note, I know the latter from the libigl's ppt in [libigl-course](https://github.com/libigl/libigl-course), but I have no idea what is the difference between the two functions. So I hope developers of libigl do not get contented by the tutorial and stop. A full documentation (like Eigen's doc) is helpful to ease of use and in turn a wide adoption. Thank you again for the reply.

**Comment by jdumas** [comment]
You're describing two separate issues. 1) lack of documentations for certain functions, and 2) discoverability for new users. Regarding 1), apart from the Viewer, every libigl function has a documentation in its header file describing what the function does. And for 2), improving how to navigate the existing documentation is on the roadmap. We need some kind of doxygen-style reference that is easily accessible. But note that the search in github can already take you a long way.

Finally, please note that libigl is an free and open-source project, developed in their free time by researchers. We do not have an army of engineers at our disposal. Contributions and feedbacks are welcome. Now, if you have a specific question, we can try to help. But a general statement like "there is no documentation" brings little to the table that we don't already know.

**Comment by zhfsu** [comment]
Thanks. I'm aware of the situation. The ticket can be closed now.

**Comment by alecjacobson** [comment]
It's here now: https://libigl.github.io/dox/
