### ISSUE TITLE
A few questions about the input data type of igl::floor

### ISSUE THREAD

**Issue by ghost** [libigl/libigl#1257]
#### Describe your issue
It all begins with the `igl::floor` call in "301_slice" in the tutorial. Due to the lack of documentation, I made some experiments to test this function. Now that the function is working for me, this thread is mainly for knowledge acquisition purpose based on some problems I encountered during experiments. 

I first tried to pass a single value using `MatrixXd` type:
```
MatrixXd VV = MatrixXd::Constant(1, 1, 1.9);
VectorXi II;
igl::floor(VV, II);

```
The code snippet causes an error that the overloading version of the function that has the input data type matching my code does not exist, hence a linking error. The same error occurs if I declare `VV` to be a `VectorXd`. If I change the declaration of `VV` to
```
ArrayXd VV = MatrixXd::Constant(1,1, 1.9);
```
inspired by the working code in the tutorial, the code compiles and links. So my first question is:

- Question (1)

Does `igl::floor` support only Array type? If so, is this because floor is a coefficient-wise operation and only Array supports coefficient-wise operation? But applying such a coefficient-wise operation to a matrix does not introduce any confusion like multiplication.

Since Constant function is available to ArrayXd as well, so next I tried the following code (the other statements are the same)
```
auto VV = ArrayXd::Constant(1, 1.9);
```
I got a compiling error of "no matching overloaded function found". So

- Question (2) 

Why the above code is wrong? The right side is `ArrayXd` so `igl::floor` should accept it. My understanding is that `Constant()` returns a so-called "expression object" but not an `ArrayXd` object, so `igl::floor` complains. But I am not sure. Please correct me if I am wrong.

Again by observing the working code in the tutorial, I modified the above declaration as follows:
```
auto VV = ArrayXd::Constant(1, 1.9).eval();
```
Now it works due to the addition of `eval()`. But my superficial understanding of Eigen is that the purpose of `eval()` is to avoid aliasing issue by creating a temporary copy, but here the nonworking code `auto VV = ArrayXd::Constant(1, 1.9);` seems to have nothing to do with aliasing, so

- Question (3)

Why does adding `.eval()` make `auto` deduce correct data type with which `igl::floor` works? Is it because `eval()` returns true `ArrayXd` type?

It is fine if the data type I want to floor is of Array type in the first place. But what if the variable I want to floor is unfortunately a Matrix and I hope `auto` can work as expected? So I tried the following code:
```
auto VV = MatrixXd::Constant(1, 1, 1.9).array().eval();
```
This declaration does not agree with `igl::floor` no matter what. As you can see, I have changed the matrix to an array using `array()`, and I have changed whatever object returned by `array()` to `ArrayXd` type using `eval()`, but why `auto` still fails to deduce the input type of `igl::floor`? Thus my last question:

- Question (4)

If I insist on using `auto` to deduce the input type `igl::floor` is happy to accept from a `MatrixXd` variable, how should I write the declaration of `VV`?
```
auto VV = MatrixXd::Constant(1, 1, 1.9)......? 
//auto VV = VectorXd::Constant(1,1, 1.9).array().eval();   //but this line works
VectorXi II;
igl::floor(VV, II);
```
Thank you for your enlightening answer.

I am using Visual Studio 2015 on Windows.
...

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by alecjacobson** [comment]
The code would work fine in header only mode. It is/was just missing the template in the static library. Feel free to reopen if this is still an issue.
