### ISSUE TITLE
What opetion of libigl viewer can disable rendering of triangle edges?

### ISSUE THREAD

**Issue by zhfsu** [libigl/libigl#1260]
#### Describe your issue
It is a question, not an issue. The question is: what option of libigl in `igl::opengl::glfw::Viewer` can disable rendering of edges of a triangle programmably (i.e. by code), so that only the internal area is rendered but the wireframe is not? Thank you.
...

#### Check all that apply (change to `[x]`)
- [x] Windows
- [x] Mac OS X
- [x] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by chopwohaa** [comment]
`viewer.data().show_lines = false`，是这个不，xiong dei。

**Comment by zhfsu** [comment]
Yes, it is. Thank you very much! 你怎么找到啊，太厉害了，xiong dei。
