### ISSUE TITLE
Ray Mesh Intersection 

### ISSUE THREAD

**Issue by chopwohaa** [libigl/libigl#1261]
##### It's a question, not an issue.
I'm trying to use the` ray_mesh_intersect()` to check ray/mesh intersections. I've two points coordinates (the local space coor). The connection line between two points as shown in the pic, it intersected. But `ray_mesh_intersect() `return a false, why？

Thank you！

![2019-07-28 11-43-35 的屏幕截图](https://user-images.githubusercontent.com/20747089/62002092-1b88af80-b130-11e9-9d13-4d2e4f0ac9e4.png)

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by BruegelN** [comment]
Which values do you use for `source` and `dir`? Did you maybe mixed the order for `dir = endpoint-startpoint;` because otherwise the `dir` vector points in the opposite direction (and then it's true that there are no intersections).
