### ISSUE TITLE
Can igl::qslim() handle multiple UVs per vertex in .obj?

### ISSUE THREAD

**Issue by unclearness** [libigl/libigl#1262]
#### Describe your issue
I'm trying to apply igl::qslim() to .obj like in the following URL.
http://kunzhou.net/tex-models.htm

I want to simplify mesh with texture UV regularization like Meshlab's Filters->Remeshing, Simplification and Reconstruction->Simplification: Quadric Edge Collapse Decimation (with texture).

But multiple "islands" in Atlas (acceptable in .obj) assign mutiple UV coordinates to a single vertex at boundaries of islands.
Input argument V of igl::qslim() is supposed to be like (x,y,z,s,t) that a vertex has the exact single correspondence to one UV.

Is there any right way to pass such multiple UVs per vertex to igl::qslim()?
Other solutions not using igl::qslim() are also welcome.

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by jiangzhongshi** [comment]
I think you are probably looking for https://github.com/songrun/SeamAwareDecimater

**Comment by unclearness** [comment]
Thanks, jiangzhongshi.
That is exactly what I want!
After reading https://github.com/songrun/SeamAwareDecimater and the correspoding publication (Seamless: Seam erasure and seam-aware decoupling of shape from mesh resolution), I realized that original QSlim can't handle mutiple UV coordinates on  a single vertex issue and more sphisticated method like SeamAwareDecimater is needed.
