### ISSUE TITLE
topological_hole_fill.h F_filled matrix bug ?

### ISSUE THREAD

**Issue by Faysmaxime** [libigl/libigl#1264]
#### Describe your issue
Hello, i'm currently trying to fill the holes of a given mesh (with topological_hole_fill) (to call later nrosy on it)
Here is my code: 

```
Eigen::MatrixXd V;
Eigen::MatrixXi F;
Eigen::MatrixXd No;
Eigen::MatrixXi F_filled;

int main(int argc, char *argv[])
{
	using namespace std;
	using namespace Eigen;

	// Load a mesh in STL format
	igl::readSTL("face.stl", V, F, No);
	
	cout << '\n' << "Initial nb vertex : " << V.rows()  << '\n';

	// REPAIR THE MESH.
	double epsilon = 0.000001;
	MatrixXd SV;
	MatrixXi SVI;
	MatrixXi SVJ;
	MatrixXi SF;

	cout << '\n' << "Correcting format, due to STL format connectivity information loss, please wait ... " << '\n';

 	igl::remove_duplicate_vertices(V,F, epsilon, SV, SVI, SVJ,SF);
	
	cout << '\n' << "Done" << '\n';
	cout << '\n' << "nb corrected vertex : " << SV.rows() << '\n';

	// NEW MESH IS SV, SF
	// Look for the boundaries to close
	vector<vector<int>> all_bnds;
	igl::boundary_loop(SF, all_bnds);

	int compteur = 0;
	vector<int> bnd_vect;
	for (int i = 0; i < all_bnds.size(); i++) {
		cout << '\n' <<  "Boundary loop number : " << i+1 << " " << '\n';
		for (int j = 0; j < all_bnds[i].size(); j++) {
			cout << all_bnds[i][j] << " ";
			bnd_vect.push_back(all_bnds[i][j]);
			compteur++;
		}
	}
	
	vector<int> problems_indice;
	vector<int> problems_values;
	VectorXi bnd(compteur);
	compteur=0;
	// setting every point on the boundary as boundary indices to preserve
	for (int i = 0; i < bnd.size(); i++) {
		bnd(i) = bnd_vect[i];
		// Check for issue on bnd (just in case)
		if (bnd(i) < 0 && bnd(i) > SV.rows()) {
			compteur++;
			problems_indice.push_back(i);
			problems_values.push_back(bnd(i));
		}
	}
	
	cout << '\n' << "nb points with problem : " << compteur << '\n'; 
	
	
	igl::topological_hole_fill(SF, bnd, all_bnds, F_filled);
	
	cout << '\n' << "F_filled rows: " << F_filled.rows() <<  '\n'; // looks ok
	cout << '\n' << "F_filled cols: " << F_filled.cols() << '\n'; // ok

        igl::opengl::glfw::Viewer viewer;	
        viewer.data().set_mesh(SV, F_filled); // <- CRASH
```

So far, i have a mesh (SV,SF) that is equivalent to (V,F) except that now i have the connectivity information. I can call viewer.data().set_mesh(SV, SF) and everything works fine.
But whenever i try to call viewer.data().set_mesh(SV, F_filled); I have an error coming from Eigen's Block.h (line 118) assertion compiletime check). I've tried computing  every's SV(F_filled,i),j) and everything works fine. It feels like i can call F_filled.rows() & F_filled.cols() but extern functions cant... . I also tried to make copy of F_filled & still got the same results.  
I also cant write the mesh with V and F_filled.
I don't really understand why i'm able to compute every vertex pointed by F_filled with no errors and have writeSTL and the set_mesh crashing...

Here is the stl that i used: 

[face.zip](https://github.com/libigl/libigl/files/3461551/face.zip)

Using VS2017 on Windows x64

#### Check all that apply (change to `[x]`)
- [X] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by jiangzhongshi** [comment]
In `topological_hole_fill`, one vertex is added for each hole, (for simplicity of coding and potentially ease of use in the context of harmonic parameterization).

Suppose you have vertices indexed `0,1,2,...,n` with 2 holes, there will be rows in `F_filled` referring to `n+1, n+2`, which will result in an array out of bounds.

**Comment by Faysmaxime** [comment]
Thanks, didnt understood it that way
