### ISSUE TITLE
How to build static library?

### ISSUE THREAD

**Issue by ghost** [libigl/libigl#1266]
#### Describe your issue
Since the cluster node I am now using to work with libigl is slow, I decided to build a static library of libigl to shorten the compiling time. I checked this page for instructions: https://libigl.github.io/static-library/. The key step is `cmake -DCMAKE_BUILD_TYPE=Release ../optional`. It means calling the CMakeLists.txt file in `../optional` which is all about generating the static library. But I could not find the `../optional` folder in the downloaded libigl source package. Did I miss somewhere while searching for it? Thanks.

PS: I am using ubuntu 16.04, cmake 3.5.1 and g++ version 5.4.0.
...

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by BruegelN** [comment]
Sadly that bit of the documentation is not up to date as you already noticed.
There is a cmake switch to control this behaviour: `LIBIGL_USE_STATIC_LIBRARY`
You could either use `cmake .. -DLIBIGL_USE_STATIC_LIBRARY=ON` or add the following line to your CMakeLists.txt e.g. if you base your project on [libigl-example-project](https://github.com/libigl/libigl-example-project) so you don't need to manually specify it every time you call `cmake`
```CMake
option(LIBIGL_USE_STATIC_LIBRARY "Use LibIGL as static library" ON)
```
