### ISSUE TITLE
Is the information https://libigl.github.io/python-bindings/ still correct?

### ISSUE THREAD

**Issue by r03ert0** [libigl/libigl#1268]
#### Describe your issue
I am unsure whether the information on the main website about building python bindings is still correct. I've seen bits and pieces of information referring building from the root, or even pointing to some alternative git repositories. Would it be possible to provide a stable way of building the python bindings in the main website?

...

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ x ] Mac OS X
- [ ] Linux
- [ x ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by jdumas** [comment]
Hi,

If you want to play with the new shinny python bindings, please [look here](https://geometryprocessing.github.io/geometric-computing-python/), you can install those via conda. Python bindings are currently being switched over to this new version. Until we finish the transition the documentation on the libigl website will remain a bit obsolete.

**Comment by r03ert0** [comment]
ok. Thank you :)
