### ISSUE TITLE
Is there any way to control the thickness of the overlayed edge?

### ISSUE THREAD

**Issue by ghost** [libigl/libigl#1270]
#### Describe your issue
Is there any way to control the thickness of the overlayed edge? Furthermore, the thicknesses of the overlayed edges are not the same, for example, some of the overlayed edges have thickness of 1 while others have thickness of 5. How to set it up in code? Thank you.
...

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by BruegelN** [comment]
ViewerData contains fields for point_size and line_width: https://github.com/libigl/libigl/blob/master/include/igl/opengl/ViewerData.h#L216-L217
You can set/read it like: `viewer.data().line_width`

But please note that `igl::opengl::glfw::Viewer::data()` take the mesh_id as an optional argument (see https://github.com/libigl/libigl/blob/master/include/igl/opengl/glfw/Viewer.h#L91-L92). This is relevant if you have more than one mesh e.g. if you call `viewer.append_mesh();`

**Comment by zhfsu** [comment]
Thank you very much, BruegelN. I got it.
This ticket can be closed.

**Comment by FantasyVR** [comment]
@jdumas `line_width` still doesn't work on macOS.

**Comment by Linsanity81** [comment]
It still doesn't work on MacOS until Jan, 2023 >-<

**Comment by alecjacobson** [comment]
glLineWidth just isn't supported for meaningful widths. Fixing this would require something like #875 which I'm personally not going to work on.
