### ISSUE TITLE
igl::upsample fails in some rare case

### ISSUE THREAD

**Issue by ldXiao** [libigl/libigl#1272]
#### Describe your issue
Dear developers

I was working on some other project based on libigl and used igl::upsample(V, F, NV, NF, num_subdiv) to upsample the mesh. In most of the cases, the function works well but failed in some rare case. 
[https://github.com/ldXiao/issue_attachments/blob/master/10.0__sf.obj](https://github.com/ldXiao/issue_attachments/blob/master/10.0__sf.obj)

this file is generated by the python binding of tetwild and is a legal mesh to be shown in viewer and I also calculated pervertex normal on it without any error message.

the minimal reproducer is below
```C++
int main() {
    Eigen::MatrixXd Vt, Vtt;
    Eigen::MatrixXi Ft, Ftt;
    igl::read_triangle_mesh("10.0__sf.obj", Vt, Ft);
    igl::upsample(Vt, Ft, Vtt, Ftt, 1);
}
```
the error message reads
```shell
Assertion failed: (row >= 0 && row < rows() && col >= 0 && col < cols()), function operator()
```

According to debugger, the error is generated from line 49 of upsample.cpp at some stage.

Looking forward to your reply.
Best.
...

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [x] Mac OS X
- [ ] Linux
- [x] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by BruegelN** [comment]
Your mesh seems to be somehow broken :/
<img width="889" alt="Bildschirmfoto 2019-08-14 um 23 33 56" src="https://user-images.githubusercontent.com/9728182/63058189-5fc7ce00-beec-11e9-8e04-0988a00b027e.png">
And that's a problemt because `igl::upsample()` needs a manifold mesh as input, see: https://github.com/libigl/libigl/blob/master/include/igl/upsample.h#L54-L55

**Comment by ldXiao** [comment]
Uh, Yes, you are right. Thanks! Though, I do think upsample should work for even broken mesh...
