### ISSUE TITLE
Counter-intuitive overwritten behavior when edges/faces coincide

### ISSUE THREAD

**Issue by ghost** [libigl/libigl#1273]
#### Describe your issue
If we draw some element like a face or edge first with one color, say yellow, and then draw the same element at exactly the same position with another different color, say red, the expected result that conforms to intuition is that what we draw later should overwrite what we draw earlier. That is, the red face or edge should overwrite the yellow one, leading to a red element shown to us. But what libigl does is the contrary: What is shown is the yellow element drawn earlier. I made many experiments in drawing coincident faces in multiple meshes and drawing coincident overlay edges in a single mesh. The results were consistent: what we draw earlier is shown while what we draw later does not overwrite. So, does this counter-intuitive overwritten behavior come by design, or is there any option that I can set to make the element drawn later overwrite the coincident element drawn earlier? Thank you.

...

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by xarthurx** [comment]
Following with this question, for color additional edges added with `add_edges()` function, no matter I put the function call in `callback_pre_draw()` or `callback_post_draw`, the new color is not shown unless disable the `wireframe` checkbox from the default menu.

Is there a way to overlay colored edges over the default drawing process?

Thanks.

**Comment by alecjacobson** [comment]
This sounds like classic z-fighting. I wish the viewers "edge" drawing could support thicker lines and we could use z-nudging. I'm not going to personally fix that though.
