### ISSUE TITLE
Compiling errors with per_face_normals/internal_angels and other files with similar problems mainly with the typedefs.

### ISSUE THREAD

**Issue by aoabuhatab** [libigl/libigl#1275]
#### Describe your issue

The example project compiles and works just fine. I have added and used, in its main.cpp, the readSTL and embree/line_mesh_intersection functions and it works just fine as well. When I try to use the same headers (even only including them with out any implementation) in my project, readSTL alone works fine, but embree/line_mesh_intersection.h which includes per_face_normals gives errors as follows:
error: reference to ‘Matrix’ is ambiguous
   Matrix<typename DerivedN::Scalar,3,1> Z(0,0,0);
error: expected ‘(’ before ‘,’ token
   Matrix<typename DerivedN::Scalar,3,1> Z(0,0,0);
error: there are no arguments to ‘Z’ that depend on a template parameter, so a declaration of ‘Z’ must be available [-fpermissive]
   Matrix<typename DerivedN::Scalar,3,1> Z(0,0,0);
error: ‘Z’ was not declared in this scope
   return per_face_normals(V,F,Z,N);
error: reference to ‘Matrix’ is ambiguous
   typedef Matrix<typename DerivedV::Scalar,1,3> RowVectorV3;
error: ‘RowVectorV3’ does not name a type
     const RowVectorV3 p0 = V.row(F(f,0));
error: ‘RowVectorV3’ does not name a type
     const RowVectorV3 n0 = (p1 - p0).cross(p2 - p0);
error: there are no arguments to ‘n0’ that depend on a template parameter, so a declaration of ‘n0’ must be available [-fpermissive]
       N(f,d) = sum3(n0(d),n1(d),n2(d));

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [x ] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by jiangzhongshi** [comment]
Looks like you don't have eigen included in your search path, could you share the cmake configuration for your project?
