### ISSUE TITLE
conda-forge igl

### ISSUE THREAD

**Issue by uhussai7** [libigl/libigl#1279]
#### Describe your issue
Installed igl from conda-forge, but it seems like the library is incomplete? Is this still being worked on?
...

#### Check all that apply (change to `[x]`)
- [x ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by jdumas** [comment]
Which feature are you missing?

**Comment by uhussai7** [comment]
Sorry, this was a problem with pycharm not the library! I will close this unnecessary issue I created. Apologies again.
