### ISSUE TITLE
How to install and use LIbigl on Window Operating System

### ISSUE THREAD

**Issue by YemmyMMU** [libigl/libigl#1281]
#### Describe your issue
I want to install and use Libigl on Windows Operating System. How can I go about it?

Thank you.
Ajayi
...

#### Check all that apply (change to `[x]`)
- [ X] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by jiangzhongshi** [comment]
libigl is a header-only project. You don't need to install things. Just include the corresponding headers in your project and you will be ready to go.
