### ISSUE TITLE
Compilation Errors

### ISSUE THREAD

**Issue by aoabuhatab** [libigl/libigl#1282]
#### Describe your issue

I am getting compilation errors because of namespace clashes. Problem is solved when namespace is removed and direct scope is used. E.g. instead of (using namespace Eigen) use (Eigen::) where ever needed.

Because other namespaces that we have, has a matrix class, for example, defined as well.

e.g. per_vertex_normals.h

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by jdumas** [comment]
Afaik all occurrences of `using namespace Eigen` are scoped within libigl functions. So if their is a compilation clash, it's probably your fault for polluting the global namespace. If you can provide a MWE where such a clash happens without yourself polluting the global namespace, we'd be happy to look into it.

**Comment by adityaghantasala** [comment]
Completely agree, stray classes are very bad and pollute the global namespace. Saying that assuming everyone is ware of that and does program accordingly is a bit dangerous. Here is a small example code 

```cpp
#include <iostream>

namespace nsp2
{
	class Matrix{
		public:
			Matrix(int ii = 0){i = ii;}
		private:
			int i;
	};
}

class Matrix{
	public:
		Matrix(double ii = 0.0){i = ii;}
	private:
		double i;
};

namespace nsp3
{
	void UseMatrix(){
		using namespace nsp2;
		Matrix A(1);
	}
}


int main() {
	std::cout << "!!!Hello World!!!" << std::endl; // prints !!!Hello World!!!
	return 0;
}
```

In namespace nsp3  `using namespace nsp2` is scoped in the function `UseMatrix`. But the presence of class `Matrix` which does not belong to any namespace will compilation failure with the error saying `error: reference to ‘Matrix’ is ambiguous`.  What works without any ambiguity and even if someone pollutes the global namespace is 

```cpp
namespace nsp3
{
	void UseMatrix(){
		nsp2::Matrix A(1);
	}
}
```
A stray class `Matrix` can occur when combining multiple projects, sometimes they can be multiple open-source projects (which happened in our case). So to avoid clashes like this, its safe to use `nsp2:: Matrix`.

**Comment by jdumas** [comment]
I agree it would be preferable to not use `using namepace` at all, even scoped. If someone creates a PR in that direction we will review it and merge it. However, if someone pollutes your global namespace, you should complain to that person first and have it fixed there. It is not libigl's job to make compilation robust against that type of mistake. So in short: it's not something that I will fix myself, but if someone does it and creates a PR we will merge it.

**Comment by adityaghantasala** [comment]
as @jdumas says @aoabuhatab may be you can me the PR with the changes you made so we can also benefit from them.
