### ISSUE TITLE
Issue while running 502_LSCMParam.py 

### ISSUE THREAD

**Issue by rupeshchandgude** [libigl/libigl#1284]
#### Describe your issue
I want to test LSCM implementation in python. lib is compiled successfully without any errors. While I ran the 502_LSCMParam.py file using:
`python3.5 502_LSCMParam.py`

Following error occurs :

> igl::opengl::glfw::Viewer usage:
  [drag]  Rotate scene
  A,a     Toggle animation (tight draw loop)
  F,f     Toggle face based
  I,i     Toggle invert normals
  L,l     Toggle wireframe
  O,o     Toggle orthographic/perspective projection
  T,t     Toggle filled faces
  Z       Snap to canonical view
  [,]     Toggle between rotation control types (trackball, two-axis
          valuator with fixed up, 2D mode with no rotation))
  <,>     Toggle between models
  ;       Toggle vertex labels
  :       Toggle face labels
Traceback (most recent call last):
  File "502_LSCMParam.py", line 60, in <module>
    viewer.data().set_mesh(V, F)
TypeError: data(): incompatible function arguments. The following argument types are supported:
    1. (self: pyigl.glfw.Viewer, arg0: int) -> pyigl.glfw.ViewerData
Invoked with: <pyigl.glfw.Viewer object at 0x7fc9182de688>

Is anything wrong while testing the code? Thanks in advance.

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [ x] Linux
- [ ] I have tried the `dev` branch and the problem persists

**Comment by BruegelN** [comment]
Replacing `viewer.data()` with `viewer.data(0)` should fix this, see https://github.com/libigl/libigl/issues/1211

**Comment by rupeshchandgude** [comment]
@BruegelN  Thanks. Working well now. Is there any way to save output as an .off file or any other format(.ply or .obj)? Also can I get only UV points from the code?

**Comment by BruegelN** [comment]
`V_uv` contains the XY coordinates.
So before you can safe it as an .obj you need to add a column of `0`
`igl.writeOBJ("my-uv.obj",V_uv,F)`
