### ISSUE TITLE
Viewer image smearing Issues with High DPI display (Windows scaling)

### ISSUE THREAD

**Issue by deGravity** [libigl/libigl#1285]
#### Describe your issue
Whenever the background color in the viewer has been changed from the default, the background becomes black, and the framebuffer does not appear to clear, causing image smearing. This only occurs when Windows high-DPI scaling is turned on

Minimal code to reproduce:

#include <igl/opengl/glfw/Viewer.h>

int main(void) {
	igl::opengl::glfw::Viewer viewer;
	//viewer.core().background_color << 0.79f, 0.79f, 0.87f, 1.0f;
        viewer.load_mesh_from_file("bunny.obj");
	viewer.launch();
	return 0;
}

With the background_color change commented out the viewer behaves normally, without it, the framebuffer never seems to clear. Also occurs with Example 106 (Viewer Menu) if you use the widget to change the frame buffer color. 

![image_smearing](https://user-images.githubusercontent.com/2359109/64839171-585b1980-d5ab-11e9-8763-137a22a6eab4.png)
...

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by alecjacobson** [comment]
This is wild. I wonder if it's still happening. If it is please reopen.
