### ISSUE TITLE
Initialize LSCM with previous parametrization

### ISSUE THREAD

**Issue by AlbertoFrancoDD** [libigl/libigl#1286]
I would like to use LSCM for generating a new parametrization based on how the user has pinned the vertices in our editor. I am able to achieve this result using ARAP with the following code: 
```C++
igl::ARAPData data;
igl::arap_precomputation(vertices, faces, 2, b, data);

for (int i = 0; i < itearation_count; ++i) {
   igl::arap_solve(bc, data, uv_init);
}
```
I would like to do something similar with LSCM but I have seen that the parameter `V_uv` are only for output. Is there a way to do this? 

Thanks 
Alberto

**Comment by BruegelN** [comment]
I'm not sure what you mean by "how the user has pinned the vertices".
Did you take a look at tutorial 502? Specific at this section: https://github.com/libigl/libigl/blob/dev/tutorial/502_LSCMParam/main.cpp#L42-L48
To minimize the LSCM energy one need to provide at least two vertices on the boundary+their boundary values. This is done through `b` and `bc`.
I don't know if this answers your question.... sorry

**Comment by AlbertoFrancoDD** [comment]
No, unfortunately you do not reply my question. I want to initialize the LSCM parametrization with my previous unwrapping coming from some other place. What I am doing is editing the UVs with an editor we created. I already have my boundary condition vectors initialized with the pinned vertices. 

In the other scenario I am using ARAP (as you can see above) and the `uv_init` variable is initialized with the previous parametrization so that I can do one step based on the pinning situation the user has defined.

**Comment by alecjacobson** [comment]
ARAP is minimized by an iterative algorithm, hence multiple steps.

LSCM is a quadratic energy so we (can and do) minimize it directly with one
big step.

It would be possible to add the LSCM energy with a "data fidelity" energy
that pulls the solution toward your initial guess. In that way, you could
have a slider where the value corresponds to how much you prefer the LSCM
result vs. keeping the input.

**Comment by AlbertoFrancoDD** [comment]
That makes sense. I wanted to reproduce a simiar result as blender does when editing the UVs (while live unwrapping is active) and checking from their code they do re-parametrize (with their LSCM implementation) the current situtation adding the pinned vertices as constraint. We are using ARAP at the moment to do that but it seems like that when live editing the UVs LSCM is more natural for the users. 

Thanks for the help!
