### ISSUE TITLE
Is there any way to find out the triangle under the mouse click?

### ISSUE THREAD

**Issue by zhfsu** [libigl/libigl#1287]
#### Describe your issue

After I rendered a triangle mesh and click on it, how do I get the face index of the triangle being clicked so that, for example, I can highlight the clicked triangle? I guess it may relate to `ray_mesh_intersect()`, but I am not sure and there is no example of this function in the tutorial. So, is there any specific function in libigl that can retrieve the clicked triangle, or `ray_mesh_intersect` is the only way out? If `ray_mesh_intersect` is the right solution, does anyone have an example code of it and is willing to share? Thanks a lot.
...

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by jdumas** [comment]
Hi,

Please check out tutorial `708 - Picking` and let us know if that answers your question.

**Comment by zhfsu** [comment]
Yes, tutorial 708 is exactly what I am looking for. Thank you for your prompt answer.
This ticket can be closed.
