### ISSUE TITLE
Error: Numerical issue in 502_LSCMParam.py on test mesh

### ISSUE THREAD

**Issue by rupeshchandgude** [libigl/libigl#1289]
#### Describe your issue
I am using my simple test mesh to get UV coordinates. I use following code to get UV coordinates (subset of 502_LSCMParam.py).

> import sys, os
sys.path.insert(0, os.getcwd() + "/../")
import pyigl as igl
from shared import TUTORIAL_SHARED_PATH, check_dependencies
dependencies = ["glfw"]
check_dependencies(dependencies)
V = igl.eigen.MatrixXd()
F = igl.eigen.MatrixXi()
V_uv = igl.eigen.MatrixXd()
def key_down(viewer, key, modifier):
    if key == ord('1'):
        # Plot the 3D mesh
        viewer.data(0).set_mesh(V, F)
        viewer.core.align_camera_center(V, F)
    elif key == ord('2'):
        # Plot the mesh in 2D using the UV coordinates as vertex coordinates
        viewer.data(0).set_mesh(V_uv, F)
        viewer.core.align_camera_center(V_uv, F)
    viewer.data(0).compute_normals()
    return False
igl.readOFF('test_simple_sample.off', V, F)
bnd = igl.eigen.MatrixXi()
b = igl.eigen.MatrixXi(2, 1)
igl.boundary_loop(F, bnd)
b[0] = bnd[0]
b[1] = bnd[int(bnd.size() / 2)]
bc = igl.eigen.MatrixXd([[0, 0], [1, 0]])
igl.lscm(V, F, b, bc, V_uv)

Following issue has been occurred while testing on my mesh :

> Error: Numerical issue.
Out[4]: False

Mesh File : 
[test_simple_sample.off.zip](https://github.com/libigl/libigl/files/3615918/test_simple_sample.off.zip)

Is something is going wrong in my code?
 

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] I have tried the `dev` branch and the problem persists

**Comment by BruegelN** [comment]
You have two unreferenced vertices in your mesh.
Either call `igl::remove_unreferenced` or manually clean your mesh using meshlab > Filters > Cleaning and Repairing > Remove Unreferenced Vertices.
`Input should be a manifold mesh (also no unreferenced vertices) [...]` https://github.com/libigl/libigl/blob/master/include/igl/lscm.h#L24-L25

**Comment by rupeshchandgude** [comment]
@BruegelN  I am using python code to for LSCM. I searched for igl.remove_referenced method , but there is no such method available. Where should I get that in python binding?

**Comment by BruegelN** [comment]
@rupeshchandgude sorry for the delayed response.
You're right, the currently included python bindings do not contain `igl.remove_unreferenced`.
However I want to point you to this answer: https://github.com/libigl/libigl/issues/1268#issuecomment-520808404
`igl.remove_unreferenced` is part of the [new python bindings](https://github.com/geometryprocessing/libigl-python-bindings) which can be install via conda.
