### ISSUE TITLE
How to get one of the all isolines?

### ISSUE THREAD

**Issue by Ivylee6108** [libigl/libigl#1290]
hello I get a problem with igl::isolines(V, F, *z, 5, isoV, isoE), if I want to select the one of the isolines of all the 5 isolines, how can I deal with this problem, can you give me some ideas?

Another question is that how can I use the heat_geo() function do the same thing as the VS and VT is the igl::exact_geodesic(SmoothV, SmoothF, VS, FS, VT, FT, geodis), to calculate the geo dis of the selected vertice to the target VT vertices.

Thanks for your answer to my question, and thanks for your contributions.

Best regards.

**Comment by jiangzhongshi** [comment]
The output of isolines is a matrix (V by 3) of vertex positions and a matrix (E by 2) edge list.
You can think of it as a graph, with nodes and edges, (you only need isoE). Each isoline is a connected component in the graph.

**Comment by jiangzhongshi** [comment]
Regarding geodesic, heat method has separated precompute and solve interface
```
igl::HeatGeodesicsData<double> data;
igl::heat_geodesics_precompute(V,F,t,data);
```
Then
```
igl::heat_geodesics_solve(data,(Eigen::VectorXi(1,1)<<vid).finished(),D);
```
gives distances (in D) to all vertices in the mesh from vid.(VS)
If you want to find VT, just find the corresponding entry in D

**Comment by daphna-kaplan** [comment]
@jiangzhongshi I was trying to find a single isoline line by:
```
ilx_v, ilx_e = igl.isolines(v, f, z_exact, n)
ad = igl.adjacency_matrix(ilx_e)
num_components, component_map, component_lengths = igl.connected_components(ad)
```

However when trying to plot a single connected component the results didn't make sense. 
Maybe you can shed some light?
