### ISSUE TITLE
Miq border edges

### ISSUE THREAD

**Issue by cristiulian** [libigl/libigl#1291]
#### Describe your issue

How does the miq implementation handle border edges?
By default, the border edges/vertices are not mapped along integer positions.
I tried to add the border edges as hard features, but it gets extremely slow.
I also tried to add the border vertices to the round_vertices, but the result is not as expected, as vertices are clustered into integer positions.

#### Check all that apply (change to `[x]`)
- [ X] Windows
- [ X] Mac OS X
- [ X] Linux
- [ X] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by arch-tu** [comment]
I have the same question. How to control the feature lines, ie. free surface boundary?

**Comment by arch-tu** [comment]
Hi,

I have the same question. When I added the hardfeatures, it computed extremely slow.
So, how can we use the border edges/vertices?  Add them both or just need one of them?

thx
