### ISSUE TITLE
can't find igl::png

### ISSUE THREAD

**Issue by jlyw1017** [libigl/libigl#1292]
#### Describe your issue
Hey 
I have successfully tried tutorials and the libigl-example-project. So I have put example-project next to libigl as it said here  https://github.com/libigl/libigl-example-project/tree/6860585e3744825fdb130b0c90408cb6e5621cca 

I want to using readPNG in libigl-example-project.
So I added this line
option(LIBIGL_WITH_PNG "Use PNG" ON)
and igl::png to
target_link_libraries(${PROJECT_NAME}_bin igl::core igl::png igl::opengl_glfw igl::png)

I got error like:
CMake Error at CMakeLists.txt:33 (add_executable):
  Target "example_bin" links to target **"igl::png" but the target was not
  found**.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
It seems igl::png can't be found. 
How should I solve this? 

and **if I don't add igl::png,**
I got 

In file included from /home/jlyw/Masterarbeit/libigl/include/igl/png/readPNG.h:36:0,
                 from /home/pgr/Masterarbeit/libigl-example-project/main.cpp:2:
/home/pgr/Masterarbeit/libigl/include/igl/png/readPNG.cpp:9:10: fatal error: igl_stb_image.h: **no such file or directory**
 #include <igl_stb_image.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/example_bin.dir/build.make:62: recipe for target 'CMakeFiles/example_bin.dir/main.cpp.o' failed
make[3]: *** [CMakeFiles/example_bin.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:73: recipe for target 'CMakeFiles/example_bin.dir/all' failed
make[2]: *** [CMakeFiles/example_bin.dir/all] Error 2
CMakeFiles/Makefile2:85: recipe for target 'CMakeFiles/example_bin.dir/rule' failed
make[1]: *** [CMakeFiles/example_bin.dir/rule] Error 2
Makefile:118: recipe for target 'example_bin' failed
make: *** [example_bin] Error 2

It seems that the stb under external wasn't found or linked.
Thanks in advanced!

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [X ] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by jlyw1017** [comment]
eh.....
It could be the problem of IDE but I didn't find why yet.
It worked in Terminal....

**Comment by jdumas** [comment]
You need to link against the cmake target `igl::png` in your project indeed, but also when changing the cmake option `LIBIGL_WITH_PNG` from `OFF` to `ON`, you need to be careful to either 1) change its value in the file `CMakeCache.txt` created in your build folder, or 2) delete this file altogether, or 3) use the `set()` cmake command with the `FORCE` option to override the value that was previously stored in the file `CMakeCache.txt` (changing the line `option(... ON)` will only change the *default* value of the variable, not the one currently stored in the `CMakeCache.txt`).
