### ISSUE TITLE
How to change background color of the viwer?

### ISSUE THREAD

**Issue by spk921** [libigl/libigl#1294]
#### Describe your issue
I would like to change the background color of the viewer and where should I change?
...

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [X ] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by jdumas** [comment]
Take a look at `viewer.core().background_color`.

**Comment by spk921** [comment]
@jdumas  Thank you for the reply. However, could you be more specific? 

I would like to change the background color as white.

Should I do following? 
viewer.core().background_color(255,255,255);

**Comment by jdumas** [comment]
Try `viewer.core().background_color.setOnes()`

**Comment by spk921** [comment]
@jdumas  Thank you for the help. It works!
