### ISSUE TITLE
& vs && in Viewer.cpp

### ISSUE THREAD

**Issue by zhfsu** [libigl/libigl#1295]
#### Describe your issue

The line below comment "// Set default windows width" in Viewer.cpp is like [this](https://github.com/libigl/libigl/blob/b0d7740e0b7e887a7e93601c4c557ecf762b389b/include/igl/opengl/glfw/Viewer.cpp#L162):

>       if (windowWidth <= 0 & core_list.size() == 1 && core().viewport[2] > 0)

, which causes a warning in Visual Studio 2015. Is there any special reason why & is used here instead of &&? If not, I think it might be better to change the line to:

>       if (windowWidth <= 0 && core_list.size() == 1 && core().viewport[2] > 0)

Thanks. 

...

#### Check all that apply (change to `[x]`)
- [x] Windows
- [x] Mac OS X
- [x] Linux
- [x] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by jdumas** [comment]
Probably a mistake. Do you mind submitting a PR?

**Comment by jiangzhongshi** [comment]
#1305
