### ISSUE TITLE
How to change the caption of the Window?

### ISSUE THREAD

**Issue by ghost** [libigl/libigl#1296]
#### Describe your issue

The caption of the libigl rendering window is always "libigl viewer". I would like to have the window caption change at run-time to show the selected face index when I move the mouse inside window. Does libigl provide any function to change the caption of the rendering window? Thank you.

...

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by jdumas** [comment]
In the `dev` branch, one of the argument of the `.launch()` method takes a string that you can use to overwrite the window title.
