### ISSUE TITLE
tcpviewer.py needs to updated with some of the fixes mentioned in other issues.

### ISSUE THREAD

**Issue by SelvamArul** [libigl/libigl#1297]
#### Describe your issue
In the following issues, there are some fixes suggested related to `igl.glfw.Viewer`
https://github.com/libigl/libigl/issues/1225#issuecomment-502031522
https://github.com/libigl/libigl/issues/1211#issuecomment-499978150
The suggested fixes are: 
`viewer.data()` to `viewer.data(0)` 
`viewer.core` to `viewer.core()`

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] I have tried the `dev` branch and the problem persists

I applied the suggested fixes in my machine and it works for me. I would be nice to update the `tcpviewer.py` file with the fixes. 
I couldn't try it on the dev branch since python directory is not present in the dev branch and neither does the dev-python branch.
I am sorry If I missed something related to dev and dev-python branch.

**Comment by jdumas** [comment]
Hi,

New python bindings are currently in development in [this repository](https://github.com/geometryprocessing/libigl-python-bindings), and are installable via conda. You can find more information on this [website](https://geometryprocessing.github.io/geometric-computing-python/). They come with a new web-based mesh viewer compatible with Jupyter notebook. They will be merged back into the `dev` branch once coverage is complete (I think).

Anyway, I'm not sure the old `tcpviewer.py` is still relevant in this context, but let us know if you have any thoughts/suggestions.

**Comment by SelvamArul** [comment]
Thanks a lot your quick response. I installed the new python bindings and it works like a charm. I like the new web-based mesh viewer. Also, I particularly like the use of `numpy` as the primary tensor library. You guys are doing a great job. I don't think the old `tcpviewer.py` is relevant anymore. Is the decision already made to abandon the old python interface?

**Comment by jdumas** [comment]
Yes the old python interface will be removed in the next version of libigl (and replaced by these new bindings).

**Comment by jdumas** [comment]
I'll close this issue then, let us know if you have more comments!

**Comment by fwilliams** [comment]
@SelvamArul The new libigl bindings don't ship with a viewer!

We wrote a [very simple 3D viewer](https://skoch9.github.io/meshplot/tutorial/) that works in a browser (and in a terminal where it will output an html file). You can also install this viewer with conda. 

I highly recommend using the new bindings in conjunction with this viewer instead of relying on the old bindings. If you run into any problems, please file issues GitHub.
