### ISSUE TITLE
igl::dijkstra, the backtracked path is in wrong direction(reversed)

### ISSUE THREAD

**Issue by dragonbook** [libigl/libigl#1298]
#### Describe your issue

The [interface comment](https://github.com/libigl/libigl/blob/master/include/igl/dijkstra.h#L70) says that the path direction is from source to target, but [the implementation](https://github.com/libigl/libigl/blob/master/include/igl/dijkstra.cpp#L71) reversed it.

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [x ] Linux
- [x ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by jiangzhongshi** [comment]
Thanks for the catch! The proposed fix is in #1304
