### ISSUE TITLE
Any functions can compute geodesic distance

### ISSUE THREAD

**Issue by KevinChenGit** [libigl/libigl#130]
Hi Daniele,

I started using Libigl two days ago. This library is just fantastic with amazingly rich features and tutorials! The viewer interface is just perfect. However, I didn't find an explicit function that computes geodesic distance. I think it should be somewhere inside the lib as it is a very fundamental function. Could you give me some instructions? Thank you very much!

Best regards,
Kevin

**Comment by alecjacobson** [comment]
While we don't have explicit functions for geodesic distance it should be very easy to compute approximate distances via:

"Biharmonic Distance" [Lipman et al.] using the `ig::cotmatrix`, `igl::massmatrix` and `igl::eigs`

or 

"Geodesics in Heat" [Crane et al.] using `igl::cotmatrix`, `igl::massmatrix` and `igl::min_quad_with_fixed`.

If you're familiar with Matlab you could use the implementations of either of these in https://github.com/alecjacobson/gptoolbox

`mesh/biharmonic_distance.m` or `mesh/heat_geodesic.m`

For now, we'll consider this a feature request.

**Comment by KevinChenGit** [comment]
Thank you very much, Alec!
