### ISSUE TITLE
How to put label text to the left of an ImGui input widget?

### ISSUE THREAD

**Issue by ghost** [libigl/libigl#1300]
#### Describe your issue

Taking tutorial 106 as an example, all the label texts of the ImGui input widgets are put to the right, but I want the label text to be shown to the left. I had thought there is some option of `ImGui::InputDouble` function that users can set to easily change the position of label, but I did not find it. So, how to put label text to the left of an ImGui input widget? Thank you.
![image](https://user-images.githubusercontent.com/52508314/65826181-58674480-e24e-11e9-92d5-3544ef0af122.png)

...

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by jdumas** [comment]
How about using `ImGui::Text(); ImGui::SameLine(); ImGui::InputDouble()` to mimic this?

**Comment by cloutn** [comment]
static std::string _labelPrefix(const char* const label)
{
	float width = ImGui::CalcItemWidth();

	float x = ImGui::GetCursorPosX();
	ImGui::Text(label); 
	ImGui::SameLine(); 
	ImGui::SetCursorPosX(x + width * 0.5f + ImGui::GetStyle().ItemInnerSpacing.x);
	ImGui::SetNextItemWidth(-1);

	std::string labelID = "##";
	labelID += label;

	return labelID;
}


double v1 = 0;
ImGui::InputDouble(_labelPrefix(label).c_str(), &v1);

int v2[2] = {0};
ImGui::InputInt2(_labelPrefix(label).c_str(), v2);

float v3[4] = {0};
ImGui::ColorEdit3(_labelPrefix(label).c_str(), v3);

**Comment by alecjacobson** [comment]
Is this related to libigl? It seems like an imgui issue/question. Please reopen if I'm mistaken.
