### ISSUE TITLE
Cotangent Laplacian calculated incorrectly for Tetrahedral meshes?

### ISSUE THREAD

**Issue by deGravity** [libigl/libigl#1307]
#### Describe your issue

In cotmatrix.cpp, the edges of the tetrahedra are enumerated in the following order:

[1,2], [2,0], [0,1], [3,0], [3,1], [3,2];

see: https://github.com/libigl/libigl/blob/master/include/igl/cotmatrix.cpp#L47

These are used to index into the array of entries generated by cotmatrix_entries.cpp, which appears to use the following order (the same as used in edge_lengths.cpp):

[3 0],[3 1],[3 2],[1 2],[2 0],[0 1]

see: https://github.com/libigl/libigl/blob/master/include/igl/edge_lengths.h#L35

Should the indexing order in cotmatrix.cpp be changed that used in edge_lengths, or am I missing something?
...

#### Check all that apply (change to `[x]`)
- [x] Windows
- [x] Mac OS X
- [x] Linux
- [x] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by deGravity** [comment]
Making this change breaks the bounded bi-harmonic weights example (pre-conditions of min_quad_with_fixed are no longer met), so I'm guessing that the original formulation is the correct one.  This leaves me to ask a slightly different question: why does this edge ordering change?

**Comment by alecjacobson** [comment]
The documentation is correct. Laplacian entries for tets involve opposite edge-lengths. It's unfortunate that cotmatrix_entries and edge_lengths are using different conventions for the orders but that'd be too subtle of a break to try to change.
