### ISSUE TITLE
Why is my mesh not a PWN mesh?

### ISSUE THREAD

**Issue by xylosper** [libigl/libigl#1308]
I have a mesh whose PWN test(piecewise_constant_winding_number) fails.

Here's my mesh in .obj format:

```
v 768.3499999999999 238.12499999999994 463.55
v 819.1499999999999 238.12500000000006 463.5499999999999
v 819.1499999999999 279.4 463.54999999999995
v 768.3499999999999 279.39999999999986 463.55000000000007
v 768.3499999999999 238.125 504.82499999999993
v 819.1499999999999 238.1250000000001 504.82499999999993
v 819.1499999999999 258.7625 484.18749999999994
v 768.3499999999999 258.7625 484.18749999999994
f 4 3 2
f 4 2 1
f 5 6 7
f 5 7 8
f 5 4 1
f 3 6 2
f 2 6 5
f 2 5 1
f 8 7 3
f 8 3 4
```

I have read your paper but I don't fully understand the condition for PWN.
It contains some colinear edges and coplanar faces, but I could not find any description about colinear edges/coplanar faces in mesh from your paper.

Could you tell me why my mesh is not a PWN mesh?

**Comment by xylosper** [comment]
Further question: this mesh is relatively simple. When a mesh is complicated, it is almost impossible to find defect by seeing mesh. Is there any tool to detect mesh defect or heal it?

**Comment by alecjacobson** [comment]
PWN is defined as being _exactly_ PWN. The problem with the provided mesh
is that there is a crack that is due to floating point. The vertex that
seems to lie on the diagonal is not exactly on that diagonal because of
floating point numbers. We do not use epsilons or fudge factors, so this
mesh is strictly not PWN.
[image: image.png]
For mesh clean up tools, personally I prefer meshfix. Another option would
be to run tetwild (this will more aggressively change the input mesh).

**Comment by jdumas** [comment]
I feel that this question comes up pretty often. Should we add an entry to the FAQ on the website?

**Comment by alecjacobson** [comment]
Good idea. There's one on the mesh arrangements project page but it might
not be enough/visible enough.

**Comment by qnzhou** [comment]
Yup, I have checked for collinearity using exact predicates.  There is a tiny gap due to floating point error.

```python
>>> import pymesh
>>> mesh = pymesh.load_mesh("test.obj")
>>> mesh.vertices
array([[768.35 , 238.125, 463.55 ],
       [819.15 , 238.125, 463.55 ],
       [819.15 , 279.4  , 463.55 ],
       [768.35 , 279.4  , 463.55 ],
       [768.35 , 238.125, 504.825],
       [819.15 , 238.125, 504.825],
       [819.15 , 258.762, 484.187],
       [768.35 , 258.762, 484.187]])
>>> pymesh.is_colinear(mesh.vertices[2], mesh.vertices[6], mesh.vertices[5])
False

```

**Comment by xylosper** [comment]
Thank you!
