### ISSUE TITLE
crash at ImGuiMenu::pre_draw()

### ISSUE THREAD

**Issue by amir90** [libigl/libigl#1311]
#### Describe your issue

Trying to get tutorial 105 working. The viewer itself works with the .off file and the bounding box.

when trying to enable imgui for the labels, the viewer crashes at initialization.

It seems that the crash happens at ImGuiMenu.cpp, at ImGuiMenu::pre_draw(), when executing ImGui_ImplOpenGL3_NewFrame();

The msvc debugger's error message is:
![image](https://user-images.githubusercontent.com/8117439/66518850-d0efc000-eaee-11e9-8d4c-e25ee903067b.png)

From online searching, I think the problem is related to an opengl context not being initialized, but I am not sure why, as it happens even on this minimal example:

#include <igl/readOFF.h>
#include <igl/opengl/glfw/Viewer.h>
#include <igl/opengl/glfw/imgui/ImGuiMenu.h>
#include <sstream>

int main(int argc, char *argv[])
{
	igl::opengl::glfw::Viewer viewer;
	igl::opengl::glfw::imgui::ImGuiMenu menu;
	menu.callback_draw_viewer_window = []() {};
	viewer.plugins.push_back(&menu); //if commented out - the viewer launches normally
	viewer.launch();
}

I am using MSVC 2017, the 'dev' branch, GLFW 3.3, and Imgui 1.68. 
The imgui example_glfw_opengl3 builds and works fine.

Any ideas on what to try?

#### Check all that apply (change to `[x]`)
- [X] Windows
- [ ] Mac OS X
- [ ] Linux
- [X] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by jdumas** [comment]
Are you able to run the tutorial 105 without any issue? Your callback for the viewer menu should be either or `menu.callback_draw_viewer_window = [](){};`. Apart from that I don't see what's wrong with the example code you pasted.

**Comment by amir90** [comment]
I am able to run tutorial 105 without a problem, except for the labels part, as it requires enabling imgui.
and yes, it was a typo, the callback is 
menu.callback_draw_viewer_window = [](){} .

**Comment by jdumas** [comment]
The tutorial 105 has ImGui enabled. I don't understand what you mean by "except for the label part": does it crash when you enable the labels in tutorial 105 (without modifying the code in any way)?

**Comment by amir90** [comment]
yes, it crashes the viewer crashes at start due to:
viewer.plugins.push_back(&menu)

**Comment by amir90** [comment]
I managed to get it to work by using [libigl-legacy's opengl include and externel imgui code](https://github.com/libigl/libigl-legacy/tree/master/include/igl/opengl). Have no real idea why it does not work normally, but at least it works.

![image](https://user-images.githubusercontent.com/8117439/66551628-83a43a80-eb50-11e9-9cab-79eb1c8778a1.png)

**Comment by jdumas** [comment]
Please do not close the issue it may still affect other people. I just tested the label on Linux and they are working fine. I'll try on my Windows machine to see if I can reproduce.
