### ISSUE TITLE
 how can i  convert a point  from UV coordinate to 3D mesh with LSCM inverse.  

### ISSUE THREAD

**Issue by yanjiapi** [libigl/libigl#1316]
HI,This is Yang!
I map a  3D mesh  in UV with LSCM parameterize for path programming !
And I produce a path trajectory in UV plane. Now ,I want map this trajectory in 3D mesh.
How to realize it with libigl ?

**Comment by jiangzhongshi** [comment]
Hi,

The mesh-triangle and UV-triangle have a one-to-one correspondence.
In the case of LSCM (of a disk-like mesh), each planar UV vertex corresponds to one vertex in 3D.
It depends on how do you represent the path in the plane: if you just had a list of vertices indexed into `UV`, the same indices apply to 3D `V`. And if the path points are barycentric coordinates, they correspond to the same in 3D.

**Comment by alecjacobson** [comment]
See https://github.com/libigl/libigl/issues/1501#issuecomment-1694935568
