### ISSUE TITLE
`igl::hit` doc explanation

### ISSUE THREAD

**Issue by xarthurx** [libigl/libigl#1322]
A question instead of an issue.

I'm using `igl::ray_mesh_intersect` to draw some curves on a given mesh.
The results is stored in an `igl::Hit` type variable.

while the header file have these info:
```
  // TODO: template on floating point type
  struct Hit
  {
    int id; // primitive id
    int gid; // geometry id
    float u,v; // barycentric coordinates
    float t; // distance = direction*t to intersection
  };
```

I have the following questions:
1.  the `id` is for the facet the ray is intersecting, what is the `gid`? In my case, this is always `-1`.
2. what does the `u,v` means? The barycentric coords of a parameterized version of the original mesh? How to use them (What are they used for)?
3. To retrieve the intersection point on the mesh, should I just use the `t` with the original ray to get the distance from the `source` point?

And one more related question, I read in a previous issue https://github.com/libigl/libigl/issues/544 that using embree will make the process faster, if I have a lot of points to check.
Are we using embree v2 or v3 in libigl?

Thanks.

**Comment by xarthurx** [comment]
OK. If I'm understanding correctly, the `u, v` is the barycentric coordinates.
And I also found `igl::unproject_onto_mesh` is a wrapper of the `ray_mesh_intersect` function.

So two question remaining:
1. `gid` related, as stated above.
2. embree related, as stated above.

One new question:
the `bc` given by `unproject_onto_mesh` is a `barycentric` coords of `[1-u-v, u, v]`. Does it follow the order of `F[0], F[1], F[2]` of any facet?

**Comment by alecjacobson** [comment]
`gid` is something from embree that we're not using.Currently using embree v3.13.3

**Comment by amadou1998** [comment]
Just coming across this. The whole AABB tree documentation is lacking while the library is incredibly useful. Would be greatly appreciated if all of that could be improved a little bit for outsiders to use as well.
