### ISSUE TITLE
is the folder `libigl\external\embree\include` added in the include path

### ISSUE THREAD

**Issue by xarthurx** [libigl/libigl#1324]
#### Describe your issue
1. I enabled the "LIBIGL_WITH_EMBREE" option in cmake.
2. `#include <igl/embree/EmbreeIntersector.h>` has no problem in my project.
3. The compiler report `cannot open source file "embree3/rtcore.h"` and some other file missing error. This line was from the file in point `2`.

Is the folder included by the settings or am I missing something?

P.S. 
changing the missing #include to:
```
#include <embree/include/embree3/rtcore.h>
#include <embree/include/embree3/rtcore_ray.h>
```
and the last line of the `EmbreeIntersector.h` file to:

```
#endif //IGL_EMBREE_EMBREE_INTERSECTOR_H
```

will make the project work.

I guess the file is quite old and needs an update?
I've submit a PR.

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [x] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by xarthurx** [comment]
![image](https://user-images.githubusercontent.com/1921878/67277897-1eddce00-f4c8-11e9-9268-efea75ead2ba.png)

Update:
There's still a lot of linking errors.

**Comment by jdumas** [comment]
You need to link against `igl::embree` in your CMake file.

**Comment by xarthurx** [comment]
Ah, I see... silly mistake...
Thanks!
