### ISSUE TITLE
[Question] Split a topology-disk mesh into two parts.

### ISSUE THREAD

**Issue by xarthurx** [libigl/libigl#1329]
Following the question in: https://github.com/libigl/libigl/issues/1328

I realize perhaps I'm doing sth wrong or libigl is missing the functionality. So asking here in a separate issue:

For a simple example like this:
![image](https://user-images.githubusercontent.com/1921878/67571438-38834d80-f734-11e9-9351-a89302e49fe2.png)

Given the cut edge-path in read, I can extract all the boundary vertices of the left part, but how can I get the sub-mesh in `V, F` format? `cut_mesh` doesn't work in this case.

Or even better, get the two separate piece all together.

**Comment by hankstag** [comment]
Hi,
I believe for this case you can prepare a cut-mask with the same size as the F matrix and mark the red halfedges as cuts and pass into cut_mesh, the output should contain two components. Could you please give the input/output of cutting this mesh?

**Comment by xarthurx** [comment]
@hankstag 
Hi, thank you for the quick reply.

I use a different mesh for the test:
![image](https://user-images.githubusercontent.com/1921878/67642435-16442800-f90c-11e9-8e43-49b216e0bdf4.png)

file here:
https://idethz-my.sharepoint.com/:u:/g/personal/2rltf9u0gv_ethz_ch/EXExIOqWULVEn9i9zsPbyvgB3p0RGK5gx5FNmR913mbEpA?e=bAtRtz

the output:
```
 ----------------
 The cut matrix:
1 0 0
0 0 0
0 0 0
0 1 0
0 0 0
0 0 0
1 0 0
0 0 0
0 0 0
0 1 0
0 0 0
0 0 0
1 0 0
0 0 0
0 0 0
0 1 0
0 0 0
0 0 0
 ----------------
 Original F size: 18
 5  1  0
 5  0  4
 6  2  1
 6  1  5
 7  3  2
 7  2  6
 9  5  4
 9  4  8
10  6  5
10  5  9
11  7  6
11  6 10
13  9  8
13  8 12
14 10  9
14  9 13
15 11 10
15 10 14
 New F size: 18
 7  2  0
 7  0  5
 8  3  1
 8  1  6
 9  4  3
 9  3  8
12  7  5
12  5 10
13  8  6
13  6 11
14  9  8
14  8 13
16 12 10
16 10 15
18 13 11
18 11 17
19 14 13
19 13 18
 ----------------
 Original V size: 16
        0   3.21246         0
 0.260939   3.21246  -1.41186
  1.12762   3.21246  -2.54482
  2.40934   3.21246  -3.21246
-0.450782   2.16436 -0.279919
-0.189843   2.16436  -1.69178
 0.676835   2.16436  -2.82474
  1.95856   2.16436  -3.49238
-0.448342   1.03721 -0.278404
-0.187403   1.03721  -1.69026
 0.679275   1.03721  -2.82322
    1.961   1.03721  -3.49086
        0         0         0
 0.260939         0  -1.41186
  1.12762         0  -2.54482
  2.40934         0  -3.21246
 New V size: 20
        0   3.21246         0
 0.260939   3.21246  -1.41186
 0.260939   3.21246  -1.41186
  1.12762   3.21246  -2.54482
  2.40934   3.21246  -3.21246
-0.450782   2.16436 -0.279919
-0.189843   2.16436  -1.69178
-0.189843   2.16436  -1.69178
 0.676835   2.16436  -2.82474
  1.95856   2.16436  -3.49238
-0.448342   1.03721 -0.278404
-0.187403   1.03721  -1.69026
-0.187403   1.03721  -1.69026
 0.679275   1.03721  -2.82322
    1.961   1.03721  -3.49086
        0         0         0
 0.260939         0  -1.41186
 0.260939         0  -1.41186
  1.12762         0  -2.54482
  2.40934         0  -3.21246
```

It seems I can get the `cuts` correct by assgning the edge index as that of its starting vertex. e(0, 1) - 0; e(1,2) - 1; e(2, 0) - 2;  (IMHO, the doc of this part should be improved...)

But how can I separate the output into two parts as `V1, F1, V2, F2`?
From the output, it seems the function duplicates the vert on the cuts and re-assigning new vertices to the faces...

**Comment by xarthurx** [comment]
The code of the above tests:

```
          std::set<int> cuts{ 1, 5, 9, 13 };

          // cuts -> fCuts: translate the vertex-style cuts into the F oriented cuts representation
          MatrixXi fCuts;
          fCuts.setZero(viewer.data().F.rows(), 3);

          std::vector<std::vector<int>> VF, VFi;
          igl::vertex_triangle_adjacency(viewer.data().V, viewer.data().F, VF, VFi);
          for (auto i : cuts) {
            for (size_t fi = 0; fi < VF[i].size(); fi++) {
              std::set<int> vSet{ 0, 1, 2 };
              vSet.erase(VFi[i][fi]); // erase the vert, then check if the other two verts are in the cut

              for (auto x : vSet) {
                // if the face have two verts on the cuts
                if (cuts.find(viewer.data().F(VF[i][fi], x)) != cuts.end()) {

                  auto [min, max] = std::minmax(VFi[i][fi], x);
                  int id = (max == 2 && min == 0 ? max : min);

                  fCuts(VF[i][fi], id) = 1;
                  break;
                }
              }
            }
          }

          igl::cut_mesh(viewer.data().V, viewer.data().F, fCuts, tmpV, tmpF);
```

**Comment by xarthurx** [comment]
I think we need a function that can extract the face indices of a given boundary (either vert bound or edge bound), which I cannot find from libigl.

Then, without touching the output of `cut_mesh`, we can do more operations on with the results.

**Comment by alecjacobson** [comment]
I'm not sure I totally understand the goal, but if it's to separate a mesh into components that don't cross the red edges, I would:

- collect face-edge adjacency information using `unique_edge_map` or `triangle_triangle_adjacency` 
- build a modified adjacency matrix where A(i,j) =1 iff face i shares an non-red edge with face j.
- call `connected_components`

This issue is old and inactive so I'll close. Feel free to reopen/follow up.
