### ISSUE TITLE
igl::arap_solve, minor bug in the local step (closest rotations)

### ISSUE THREAD

**Issue by MichaelRabinovich** [libigl/libigl#133]
In the main loop, it seems you enforce boundary constraints by the following lines, before calling fit_rotations_planar:

   // enforce boundary conditions exactly
    for(int bi = 0;bi<bc.rows();bi++)
    {
      U.row(data.b(bi)) = bc.row(bi);
    }

This cause the fit_rotations to be called not on the previous uv, but on a slightly changed versions (assuming it doesn't have the same boundary constraints).
I found it while playing around with arap and doing a sanity check to flatten a developable mesh from a isometric initialisation. I expected it to be "solved" after 1 local/global step but it didn't.

Placing the previous lines below the fit_rotations part fix the issue.

**Comment by alecjacobson** [comment]
Huh. That's funny. Maybe I don't completely understand the change. Could
you post as a pull request?
https://help.github.com/articles/using-pull-requests/

On Tue, Oct 13, 2015 at 6:41 AM, MichaelRabinovich <notifications@github.com

**Comment by alecjacobson** [comment]
Was this ever resolved?
