### ISSUE TITLE
Unable to determine connected components on mesh imported with readSTL

### ISSUE THREAD

**Issue by gaze** [libigl/libigl#1331]
#### Describe your issue

I'm writing a program that checks the health of an STL file. When run on a healthy STL file, in particular [this](https://github.com/VoronDesign/Voron-2/blob/master/STLs/VORON2.2/Bottom_Skirts_%2B_Decorative_Parts/Skirts/front_rear_skirt_a_250spec_x2_Rev1.stl), though other display similar issues, the following code

```
    Eigen::MatrixXf V;
    Eigen::MatrixXi F;
    Eigen::MatrixXf N;

    igl::readSTL("./front_rear_skirt_a_250spec_x2_Rev1.stl",
                V, F, N);

    Eigen::SparseMatrix<double> A;
    igl::adjacency_matrix(F,A);

    Eigen::MatrixXi C, Ci;
    igl::vertex_components(A, C, Ci);

    int connected_components = Ci.rows();

    std::cout << "ccs: " << connected_components << std::endl;
```
Produces 
```
ccs: 31512
```

Is this some simple user error or have I uncovered something?

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [X] Mac OS X
- [ ] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by jdumas** [comment]
A STL file is a list of disconnected triangles, so each vertex is duplicated for each incident face. You need to merge vertices together prior to doing any further processing, e.g. using `igl::remove_duplicate_vertices()`.

**Comment by gaze** [comment]
Thank you so much, especially for the fast response! In the future, is filing a report like this okay for ask such questions, or is there a preferred alternative? I haven't found a slack or discord or IRC channel.

**Comment by jdumas** [comment]
No github issues are fine for questions. Do not open a 100 threads if you have a millions different questions, try to keep it organized so it can be useful to everyone, and close the thread/reopen if your question has been solved or need more answers.

**Comment by gaze** [comment]
Okay, then in that spirit I have one more question. I've added in ``igl::remove_duplicate_vertices()``,  and that's indeed resulted in 1 connected component. Great! I append to my previous program
I then check ``igl::euler_characteristic()``, but this gives the seemingly absurd result of -24. Meshmixer and rhino and similar programs say this STL is watertight, but this suggests otherwise. Is there another processing step I should add?

**Comment by jdumas** [comment]
The Euler characteristic of an orientable surface is connected to its topological genus, so if your mesh has a number of "handles", it's possible it could have a Euler characteristic of -24.
