### ISSUE TITLE
[Question] edge order / index of `unique_edge_map`?

### ISSUE THREAD

**Issue by xarthurx** [libigl/libigl#1333]
In the doc, there is a `F(f, c)` seems to indicating the c-th edge of the face.
May I ask how the first edge of a face is decided in `F(f, c)`? 

I originally thought  `F(f, c)` will be the edge `F(f, i) - F(f, i+1)` (i is the vert index), but after some experiment, this is not true... the i-th edge does not start from the i-th vertex.

**Comment by jiangzhongshi** [comment]
It is described here as the edge opposite to the vertex. ` F(f, i+1) -> F(f, i+2)`.
https://github.com/libigl/libigl/blob/master/include/igl/unique_edge_map.h#L22

There's some confusion since two conventions coexist in libigl

**Comment by xarthurx** [comment]
Thanks.
I learned it the hard way...
