### ISSUE TITLE
Different line_width for different lines

### ISSUE THREAD

**Issue by xarthurx** [libigl/libigl#1334]
I'd like to draw the border of a mesh with thicker lines and the rest of the wireframe of the mesh thinner.

It seems the `viewer.data().line_width` is controlling the global `line_width` for all edges in the same data element of the `data_list`.

Under the current framework, it seems that it is only possible to add separate data to the `data_list` for controlling different `line_width`.... Is this correct?

Or using a different `viewer.core`?

A side question is, when are we suppose to use different `core` and when different `core.data` in the data_list? I'm not very clear how to make the choice when there's multiple piece of mesh I need to draw.

**Comment by jdumas** [comment]
1. Line width is constant for all edges/overlay lines in a `ViewerData`. Use different `ViewerData` if you want different line width. This may change in the future but for now this is how it it.
2. Use different `ViewerCore` if you want to have different viewports/camera in your viewer. Check out the respective tutorials implementation for each feature.

**Comment by alecjacobson** [comment]
btw, what's the max `line_width` if I put `line_width=100` it looks only marginally thicker than the default.

**Comment by jdumas** [comment]
On macOS I don't think line_width has any effect.

**Comment by alecjacobson** [comment]
it does seem to have a really minor effect. maybe it's the difference
between 1 highdpi pixel and 1 real pixel....

In any case, it'd be great to have a way to draw truly thick lines.
-Alec

**Comment by jdumas** [comment]
Agreed. We need to revive #875 ...

**Comment by paul0noah** [comment]
Is there still a plan to improve `line_width` on MacOs or does anyone have a workaround for this?

**Comment by jdumas** [comment]
Not planning to work on this anytime soon, sorry.

**Comment by paul0noah** [comment]
If someone else has the problem and still wants to see something like a thicker edge, here is a hacky workaround: 
```
            #ifdef __APPLE__
                Eigen::MatrixXf P1_P2_vec = P1 - P2;
                const int numPoints = P1_P2_vec.norm() / POINT_DISTANCE + 1;
                const float distBetweenPoints = 1 / (float) numPoints;
                for (int i = 0; i < numPoints; i++) {
                    viewer.data(numFacesPlotted).add_points((P2 + i * distBetweenPoints * P1_P2_vec).cast<double>(), color);
                    viewer.data(numFacesPlotted).point_size = EDGE_THICKNESS;
                }
            #else
                viewer.data(numFacesPlotted).add_edges(P1.cast<double>(), P2.cast<double>(), color);
                viewer.data(numFacesPlotted).line_width = EDGE_THICKNESS;
            #endif
```
