### ISSUE TITLE
Isoline at any location

### ISSUE THREAD

**Issue by xarthurx** [libigl/libigl#1336]
#### Describe your issue
Beside the bug report here:https://github.com/libigl/libigl/issues/1245
and discussions at here: https://github.com/libigl/libigl/issues/1290 for extracting one of the isolines,

I'm wondering if it possible to evaluate the isoline at any given location on the mesh? This will apply to circumstances like "extract the isoline at mouse click" for instance.

One workaround I can think of is to generate a large number of isolines and find the one that closest to the target point, but this seems very inefficient.

**Comment by jdumas** [comment]
For that you'd better write a marching triangle (similar to marching tet, but to extract an isoline on a surface).

**Comment by evouga** [comment]
It would be useful to extend `igl::isolines` to accept an isovalue and/or a set of isovalues (in addition to just a desired number of evenly-spaced isovalues) since the same code is involved for all of these operations.
