### ISSUE TITLE
Viewer callbacks should get a chance to handle the escape key before closing the window

### ISSUE THREAD

**Issue by mikeroberts3000** [libigl/libigl#1338]
#### Describe your issue

Hello there, I would like to suggest a lightweight modification to the keyboard handling logic in Viewer.cpp. Namely, the Viewer's keyboard callbacks should get a chance to handle the escape key before the window gets closed. Currently, when the escape key is pressed, the Viewer closes the window immediately and unconditionally, and there is no way to override this behavior without modifying the libigl source code.

This behavior is problematic for me because I'm using the libigl Viewer as a starting point to build a lightweight mesh editing app, where a user might lose valuable edits if their window is suddenly closed without warning.

A clean way to give client code a way to override the behavior in question, would be to shut down the app after the keyboard handling callback has been executed, and only if it returns false. This would be a minimally invasive change to the overall logic in the Viewer, and would preserve the default behavior unless client code specifically overrides it.

#### Check all that apply (change to `[x]`)
- [x] Windows
- [x] Mac OS X
- [x] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by jdumas** [comment]
Hi. It should be possible to achieve what you want without modifying the libigl source code.

1. If you want to execute a routine before closing the viewer, you can register a `ViewerPlugin` and override the `shutdown()` function to inject your own code.
2. If you want to cancel the shutdown command set by libigl when pressing "Escape", you can call `glfwSetWindowShouldClose()` yourself and reset the flag, in the `key_down()` viewer callback.

**Comment by mikeroberts3000** [comment]
Ah, that's great. Thank you. Option 2 sounds like a good fit for my use case. Cheers 😄

**Comment by jdumas** [comment]
No worries. If you want to make a PR that doesn't set the flag when `key_down()` returns true we could also merge that easily.
