### ISSUE TITLE
Concurrently readable lazy-evaluated number type

### ISSUE THREAD

**Issue by tfmk** [libigl/libigl#1339]
Hello, does libigl (or CGAL) provide a lazy-evaluated number type that allows concurrent read operations?

The program I'm working on could benefit from parallelization (potentially a 2x speedup), but when using Kernel<CGAL::Lazy_exact_nt<ExactNumberType>> or CGAL::Epeck, I've noticed that concurrent read operations cause data races and crash the program.

I've tried using the number type mpq_class (as mentioned in https://github.com/CGAL/cgal/issues/2685), which does not use lazy evaluation nor reference counting. As a result, the program runs without data races, but ~3 times slower (I would expect a concurrent-read-safe lazy-evaluated NT to be slower as well, but not this much).

**Comment by jdumas** [comment]
Libigl only provides wrapper around CGAL functionalities. You should ask your question directly to the CGAL folks.

**Comment by alecjacobson** [comment]
AFAIK, CGAL does not have this. There's a github issues thread about one
that was in the works. Not sure what happened to it. I think GMPs core type
allows concurrent reads, but it's slower without the lazy evals.

This would be an awesome thing to find. So if you find a good solution out
there. Please let us (me) know.
