### ISSUE TITLE
kronecker_product mentioned in tutorial, but missing in library

### ISSUE THREAD

**Issue by tbleher** [libigl/libigl#134]
tutorial.md (https://github.com/libigl/libigl/blob/master/tutorial/tutorial.md) mentions the function igl::kronecker_product, but I can't find it anywhere in the igl library. How do I access this function?

**Comment by alecjacobson** [comment]
`igl::kronecker_product` was removed from libigl in commit 90d90af3756908d5b2b279a9b8501e5a882f2d0a because kronecker product's already exist in Eigen:

```cpp
#include <unsupported/Eigen/src/KroneckerProduct>
...
Eigen::kroneckerProduct(A,B,C);
```

I've removed this line from the tutorial.
