### ISSUE TITLE
Issue running the .exe for the Tutorial of the Fast Winding Number

### ISSUE THREAD

**Issue by hwahanik** [libigl/libigl#1341]
Hi libigl team:

I have been running into some issues with Libigl running in Windows 10 x64.  As the main priority I want to run the Fast Winding Number tutorial which is contained in the FWN-branch.

1.   The first step is to solve the CGAL and Boost dependency.  For doing download Anaconda 64bit, and from the Anaconda command prompt I run the command:  

**conda install -c anaconda boost.**  

Also add Anaconda to the windows PATH.  Following this proceed to download CMAKE for Windows 64 bit from here:

**https://cmake.org/download/**

2.  The second step is to Run CMAKE and configure Boost and CGAL.  Open CMAKE and input the following:

Input the source as:    [YOUR LOCAL PATH]/libigl-fast-winding-number-soups 
and the build as          [YOUR LOCAL PATH]/libigl-fast-winding-number-soups/build

Important: select the compiler as Visual Studio.

Press configure.  This will create a list of the flags contained in the cmake files of the project.  Proceed now to check the box for LIBIGL_FOR_CGAL, and press configure again.  This will download the CGAL package, and it will link LIBIGL to the Boost package created inside of Anaconda.

3.  Proceed now to press "Generate".  Press Generate at least a couple of times.  This should generate a the file "libigl.sln" file inside of [YOUR LOCAL PATH]\libigl-fast-winding-number-soups\build.

4.  Open libigl.sln in Visual Studio and Build all.  This should generate all the executables for the tutorials which will be located in the build directory.

5.  The executables for the tutorials work fine except for the .exe corresponding to the Fast Winding Number.

#### Check all that apply (change to `[x]`)
- [X] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by jdumas** [comment]
Have you tried the latest `dev` branch? There were some bugs that were fixed recently.

**Comment by hwahanik** [comment]
I unzipped the Dev branch, and I tried copying the folder of the FWN tutorial over here, and included the additional commands in the CMakeList file in order to compile it.

After running CMAKE and opening the project in Visual Studio I get a build error with the FWN tutorial, shown bellow.  I believe the Dev branch and the FWN branch and not synced.  


76>D:\libigl-dev\tutorial\717_FastWindingNumber\main.cpp(71,15): warning C4244: 'initializing': conversion from 'Eigen::EigenBase<Derived>::Index' to 'int', possible loss of data
76>D:\libigl-dev\tutorial\717_FastWindingNumber\main.cpp(71,15): warning C4244:         with
76>D:\libigl-dev\tutorial\717_FastWindingNumber\main.cpp(71,15): warning C4244:         [
76>D:\libigl-dev\tutorial\717_FastWindingNumber\main.cpp(71,15): warning C4244:             Derived=Eigen::Matrix<int,-1,-1,0,-1,-1>
76>D:\libigl-dev\tutorial\717_FastWindingNumber\main.cpp(71,15): warning C4244:         ]
76>D:\libigl-dev\tutorial\717_FastWindingNumber\main.cpp(98,12): warning C4477: 'printf' : format string '% 8ld' requires an argument of type 'long', but variadic argument 1 has type 'Eigen::EigenBase<Derived>::Index'
76>D:\libigl-dev\tutorial\717_FastWindingNumber\main.cpp(98,12): warning C4477:         with
76>D:\libigl-dev\tutorial\717_FastWindingNumber\main.cpp(98,12): warning C4477:         [
76>D:\libigl-dev\tutorial\717_FastWindingNumber\main.cpp(98,12): warning C4477:             Derived=Eigen::Matrix<double,-1,-1,0,-1,-1>
76>D:\libigl-dev\tutorial\717_FastWindingNumber\main.cpp(98,12): warning C4477:         ]
76>D:\libigl-dev\tutorial\717_FastWindingNumber\main.cpp(98,12): message : consider using '%td' in the format string
76>D:\libigl-dev\tutorial\717_FastWindingNumber\main.cpp(102,12): warning C4477: 'printf' : format string '% 8ld' requires an argument of type 'long', but variadic argument 1 has type 'Eigen::EigenBase<Derived>::Index'
76>D:\libigl-dev\tutorial\717_FastWindingNumber\main.cpp(102,12): warning C4477:         with
76>D:\libigl-dev\tutorial\717_FastWindingNumber\main.cpp(102,12): warning C4477:         [
76>D:\libigl-dev\tutorial\717_FastWindingNumber\main.cpp(102,12): warning C4477:             Derived=Eigen::Matrix<double,-1,-1,0,-1,-1>
76>D:\libigl-dev\tutorial\717_FastWindingNumber\main.cpp(102,12): warning C4477:         ]
76>D:\libigl-dev\tutorial\717_FastWindingNumber\main.cpp(102,12): message : consider using '%td' in the format string
73>D:\libigl-dev\tutorial\106_ViewerMenu\main.cpp(91,1): warning C4305: 'argument': truncation from 'double' to 'float'
76>D:\libigl-dev\tutorial\717_FastWindingNumber\main.cpp(111,10): error C2039: 'FastWindingNumberBVH': is not a member of 'igl'
76>D:\libigl-dev\include\igl/get_seconds.h(12): message : see declaration of 'igl'
76>D:\libigl-dev\tutorial\717_FastWindingNumber\main.cpp(111,31): error C2065: 'FastWindingNumberBVH': undeclared identifier
76>D:\libigl-dev\tutorial\717_FastWindingNumber\main.cpp(111,31): error C2146: syntax error: missing ';' before identifier 'fwn_bvh'
76>D:\libigl-dev\tutorial\717_FastWindingNumber\main.cpp(111,31): error C2065: 'fwn_bvh': undeclared identifier
76>D:\libigl-dev\tutorial\717_FastWindingNumber\main.cpp(114,70): error C2065: 'fwn_bvh': undeclared identifier
76>D:\libigl-dev\tutorial\717_FastWindingNumber\main.cpp(112,12): warning C4477: 'printf' : format string '% 8ld' requires an argument of type 'long', but variadic argument 1 has type 'Eigen::EigenBase<Derived>::Index'
76>D:\libigl-dev\tutorial\717_FastWindingNumber\main.cpp(112,12): warning C4477:         with
76>D:\libigl-dev\tutorial\717_FastWindingNumber\main.cpp(112,12): warning C4477:         [
76>D:\libigl-dev\tutorial\717_FastWindingNumber\main.cpp(112,12): warning C4477:             Derived=Eigen::Matrix<int,-1,-1,0,-1,-1>
76>D:\libigl-dev\tutorial\717_FastWindingNumber\main.cpp(112,12): warning C4477:         ]
76>D:\libigl-dev\tutorial\717_FastWindingNumber\main.cpp(112,12): message : consider using '%td' in the format string
76>D:\libigl-dev\tutorial\717_FastWindingNumber\main.cpp(118,43): error C2065: 'fwn_bvh': undeclared identifier
76>D:\libigl-dev\tutorial\717_FastWindingNumber\main.cpp(116,12): warning C4477: 'printf' : format string '% 8ld' requires an argument of type 'long', but variadic argument 1 has type 'Eigen::EigenBase<Derived>::Index'
76>D:\libigl-dev\tutorial\717_FastWindingNumber\main.cpp(116,12): warning C4477:         with
76>D:\libigl-dev\tutorial\717_FastWindingNumber\main.cpp(116,12): warning C4477:         [
76>D:\libigl-dev\tutorial\717_FastWindingNumber\main.cpp(116,12): warning C4477:             Derived=Eigen::Matrix<double,-1,-1,0,-1,-1>
76>D:\libigl-dev\tutorial\717_FastWindingNumber\main.cpp(116,12): warning C4477:         ]

**Comment by jdumas** [comment]
Can you try to build the whole thing and not copy stuff partially?

**Comment by hwahanik** [comment]
The dev branch does not have the code for the FWN tutorials.  So the only way to build the whole thing would be to sync both, or simply copy the latest .cpp and .h files for the Fast Winding Number in the FWN branch over to the dev branch, and also the folder of the FWN tutorial.

**Comment by jdumas** [comment]
#1218 has been merged into `dev` 1h ago. Can you try again?

**Comment by hwahanik** [comment]
Ok I will try with the latest merge.

**Comment by hwahanik** [comment]
Hi jdumas, 

This worked fine, but some observations are important here:

-The .exe of the tutorial for the Fast Winding Number only worked once the solution is built in Release mode.  

-If Building in Debug mode, the .exe run stops due to a few Asserts in the Eigen library that fail to be true.  The same problem occurs with the Winding Number .exe file, which only works when building in Release mode.

Thank you

**Comment by xarthurx** [comment]
Question to the `717` example here:

In the tutorial webpage, the link to the "Example 717" is 404.
https://libigl.github.io/tutorial/

Additionally, after running CMake for libigl with the tutorial option `ON`, only the `717` example is missing:
![image](https://user-images.githubusercontent.com/1921878/126657427-d4963018-f670-4f2d-84b0-0590f85e2f3f.png)

Any idea what happened?

**Comment by xarthurx** [comment]
Sorry for the spam.
![image](https://user-images.githubusercontent.com/1921878/126657848-d92a0ef3-ddf7-44e4-a2ed-515799d5579f.png)

Realize that I need to turn on `CGAL`.
