### ISSUE TITLE
How to compute cotmatrix robustly?

### ISSUE THREAD

**Issue by jaredsagendorf** [libigl/libigl#1342]
#### Describe your issue
Hello, I'm trying to compute the conformal factors of a mesh as described in the following paper: https://pdfs.semanticscholar.org/d197/d297d12fe648db2c8f99547ab1162283385c.pdf

which amount to solving the following Poisson equation:

![image](https://user-images.githubusercontent.com/16827826/68175729-0d201000-ff37-11e9-863f-1941394f71f7.png)

where _L_ is the cotmatrix (Laplace-Beltrami operator) and 
![image](https://user-images.githubusercontent.com/16827826/68175801-3f317200-ff37-11e9-86c2-01b99f5a3ecb.png) are values defined on the mesh. My implementation is working great for some meshes, but for others I'm getting diverging values which I believe is because these meshes are not great quality - they may contain irregular vertices or sharp points, which leads to bad values in the cotmatrix.

Does anyone know of a way I can use libigl to compute the cotmatrix in a way which would be robust to bad vertices? I've tried both  igl::cotmatrix and igl::intrinsic_delaunay_cotmatrix, both both are diverging. Alternatively, is there some way I can identify and impute bad vertices?
 
...

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [x ] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by jiangzhongshi** [comment]
I assume your diverging means values with `inf` or `nan`. In that case,

If you look at cotangent function, it diverges when the angle is close to `0` or `pi`. So according to the definition of cotmatrix, it is not going to be robust to bad angles. 
I believe intrinsic Delaunay should partially remedy the problem unless you have sharp extrusions on the mesh. 

The way to identify problematic regions is to simply check the angles of the triangles in the mesh. But you do need some remeshing to eliminate them.
