### ISSUE TITLE
Creating point cloud from mesh sampling

### ISSUE THREAD

**Issue by ChimMeya** [libigl/libigl#1343]
Hi,
I'm trying to create point clouds from mesh using `random_points_on_mesh(n, V, F, B, FI)` function (see code below). After some iterations, I get this error and sometimes I get it from the first iteration when n is big (about 100000 samples). 
![error_libigl](https://user-images.githubusercontent.com/26687429/68224427-e0c7ca80-ffee-11e9-9021-37d588f6c273.PNG)
Debbuging:
![error2](https://user-images.githubusercontent.com/26687429/68224548-1e2c5800-ffef-11e9-8db0-493c10a9b78c.PNG)

My code:
```
int main() {
	for (int i = 0; i < 100; i++) {
		get_sampled_pointCloud_from_OFF("bathtub_0001.off");
	}
	return 0;
}
Eigen::MatrixXd get_sampled_pointCloud_from_OFF(const std::string fileName) {
	Eigen::MatrixXd V;
	Eigen::MatrixXi F;
	igl::readOFF(fileName, V, F);
        Eigen::VectorXi FI;
	Eigen::MatrixXd B;
	
	igl::random_points_on_mesh(100000, V, F, B, FI);
	Eigen::MatrixXd samples(B.rows(), 3);
	for (int i = 0; i < samples.rows(); i++){
		samples.row(i) =
			B(i, 0)*V.row(F(FI(i), 0)) +
			B(i, 1)*V.row(F(FI(i), 1)) +
			B(i, 2)*V.row(F(FI(i), 2));
	}
	return samples;}
```
This code is inspired from [This comment](https://github.com/libigl/libigl/issues/808#issuecomment-397099198). I changed the number of rows since I want to create point cloud from the n sampled points.
I couldn't figure the problem! I'm new in Libigl.
Thanks.
...
- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] I have tried the `dev` branch and the problem persists

**Comment by ChimMeya** [comment]
I printed some values of `FI(i)` and I found that some of them are equal to `-1`.
I think that this shouldn't happen, is it? is the problem in `random_points_on_mesh(n, V, F, B, FI)`? why it returns `-1`?

**Comment by jiangzhongshi** [comment]
It seems to be a bug. Could you share the mesh that is creating the problem?

**Comment by ChimMeya** [comment]
It's from ModelNet10, the first bathtub test image.

**Comment by ChimMeya** [comment]
@jiangzhongshi yes! I did some debugging and yes! it's a bug! the random_points_on_mesh() function returns sometimes -1 value as indice. To overcome this problem for the moment, I considered only positive indices and in the end I resized the sampled point cloud.

**Comment by jdumas** [comment]
Have you tried the dev branch as well? I believe a similar bug has been fixed recently.

**Comment by ChimMeya** [comment]
@jdumas  no, I didn't! I'm using the master branch.

**Comment by jdumas** [comment]
Well, can you try the dev branch then?

**Comment by jiangzhongshi** [comment]
It looks like the same as https://github.com/libigl/libigl/issues/842

**Comment by ChimMeya** [comment]
Thank you, I will retry this evening!
