### ISSUE TITLE
How to break from viewer.launch() and refresh the scene

### ISSUE THREAD

**Issue by KevinChenGit** [libigl/libigl#135]
The scene that I want to display needs to be updated during each iteration. The problem is that I want to draw the scene using viewer.launch() during each iteration, but I don't know how to save the iteration results (for animation purpose) and break from viewer.launch() safely. If I use viewer.launch_rendering(false), the viewer just shuts down and I have no chance to check the intermediate results. 

Is there any method to achieve similar functions like cv::waitkey() in opencv (so that the viewer can keep displaying the result until reaching a specified time limit or encountering a button event)? Many thanks!

**Comment by alecjacobson** [comment]
What is that you want to save between iterations? Why not just use
viewer.clear() followed by viewer.set_mesh()?

**Comment by KevinChenGit** [comment]
The thing is when viewer.launch() is executed, how to break this function and run the code of next iteration?

**Comment by danielepanozzo** [comment]
The viewer supports callbacks to execute actions after pressing keys or after a certain time.
Take a look at: http://libigl.github.io/libigl/tutorial/tutorial.html#interactionwithkeyboardandmouse

If you need full control of the rendering loop, you can simply reimplement the method launch in the viewer. The only thing it does is open a window and then register the callbacks in glfw.

**Comment by KevinChenGit** [comment]
I see=D Thank you, Daniele!

**Comment by wguo68** [comment]
How to wait for in each iteration just like cv::waitkey()?

**Comment by AravindhPadmanabhan** [comment]
@danielepanozzo , The tutorial you had mentioned does not show how to iteratively change a mesh in libigl viewer. I am writing a genetic algorithm to fit a parametric mesh to a point cloud and would like to display how the mesh evolves with each generation. Or, even if I have an array of meshes, how do I display each of those one after the other with a specific wait time or a key callback?
