### ISSUE TITLE
bugs on recent update on `heat_geodesics` in develop branch

### ISSUE THREAD

**Issue by xarthurx** [libigl/libigl#1351]
#### Describe your issue

I see a recent update on the `heat_geodesic` func in the development branch.
This updates caused a bug when using this function when loading `.obj` meshes:

I'm not sure what the problem is. Here is the call stack:
![image](https://user-images.githubusercontent.com/1921878/68756847-30b81a00-060b-11ea-8cf9-dbffa46dbdc8.png)

The problem arise when calling the `min_quad_with_fixed_precompute` function on `Aeq`, which is among the recent change of the function. (line `87`)

![image](https://user-images.githubusercontent.com/1921878/68756868-40376300-060b-11ea-9583-17a211604251.png)

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by xarthurx** [comment]
**https://github.com/libigl/libigl/blob/9145faf782b8fc52bb43c2aa6b9afe4dd82f53f9/include/igl/heat_geodesics.cpp#L87**

@alecjacobson

**Comment by xarthurx** [comment]
OK, I think the error is caused due to the "lazy evaluation mechanism" of Eigen.
changing the line to:

`    const Eigen::SparseMatrix<double> Aeq = M.diagonal().eval().transpose().sparseView();
`

will solve the bug.

Besides, shouldn't the `double` be `Scalar` to be consistent with the libigl syntax?

**Comment by BruegelN** [comment]
This issue existed before and should have been fixed by https://github.com/libigl/libigl/pull/1288
However it looks like the changes have been reverted by https://github.com/libigl/libigl/pull/1344

**Comment by jdumas** [comment]
@alecjacobson

**Comment by alecjacobson** [comment]
gnarly eigen gotcha, but looks like this was fixed.
