### ISSUE TITLE
MIQ program didn't work tutorial/505_MIQ/main.cpp

### ISSUE THREAD

**Issue by yu-yuxuan** [libigl/libigl#1355]
#### Describe your issue

MIQ is not working. For example, if you add the following code after line 300
`std::cout << "=====" << V.rows() << std::endl;`
It will not output anything in command windows.
#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by jdumas** [comment]
I don't see what you're talking about. The tutorial is working fine on my Windows machine. Did you copy the openblas dll to the build directory?

**Comment by yu-yuxuan** [comment]
> I don't see what you're talking about. The tutorial is working fine on my Windows machine. Did you copy the openblas dll to the build directory?

Yes, finally, I use the OpenBLAS 0.3.6 version to solve this problem.
I use visual studio 2017

**Comment by jdumas** [comment]
Ok so this seems related to #9 and #1050
I need to take another look to ensure this gets caught by our unit test continuous integration on Windows.
