### ISSUE TITLE
switch between different shader

### ISSUE THREAD

**Issue by xarthurx** [libigl/libigl#1358]
I can see there's an example about using a customized shader in tutorial 716: https://github.com/libigl/libigl/blob/master/tutorial/716_HeatGeodesics/main.cpp

Since this is using the mechanism of destroy/recreate the `meshgl`, doesn't it mean that `meshgl` can only use one shader for each `viewer` instance?

Is it possible to, say make sth like click a button and switch to another shader without re-compile and run the code again? (Sorry I'm not very familar with the opengl low level process)

**Comment by alecjacobson** [comment]
You should be able to toggle shaders. You'll need to manually destroy the shader programs in `meshgl` and create your new ones. See `destroy_shader_program` and `create_shader_program`
