### ISSUE TITLE
Compiling CSG operations

### ISSUE THREAD

**Issue by csverma** [libigl/libigl#136]
Hello, 

I am building boolean operations on Linux machine and I used C++14 as a compiler option. I am
getting the following message and google search did not help.

cgal/remesh_intersections.cpp:314:460: error: ‘std::__1’ has not been declared

How should I compile the code ?

csv

**Comment by alecjacobson** [comment]
I'm pushing a fix. It seems clang snuck in some `::__1` namespace garbage into our templates. You can `git pull` the latest version that replaces `std::__1` with `std::`

I've also added a check for this in the nightly build to catch these if they show up again by mistake.
