### ISSUE TITLE
bug in readobj?

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#1367]
https://github.com/libigl/libigl/blob/abe94567a81a094115e34d796c5dc15877c64b32/include/igl/readOBJ.cpp#L243

    /usr/local/libigl/include/igl/readOBJ.cpp:243:27: warning: format specifies type 'char *' but the argument has type 'char (*)[2048]' [-Wformat]

Should this line be 

            sscanf(l, "%s\n", currentmaterialref);

?

**Comment by jdumas** [comment]
Looks like a bug to me.
