### ISSUE TITLE
tutorials can run in Debug mode, but crash when running in Release mode

### ISSUE THREAD

**Issue by KevinChenGit** [libigl/libigl#137]
All tutorials can run successfully in debug mode. Compilation in release mode is also okay! But when it runs to viewer.init() in release mode, the program crashes with error message:

Access violation reading location 0X00000000.

The call stack is as follows:
 	105_Overlays_bin.exe!nanogui::Label::Label(class nanogui::Widget *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)	C++
 	105_Overlays_bin.exe!nanogui::FormScreen::addVariablePreWork(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)	C++
 	105_Overlays_bin.exe!nanogui::FormScreen::initFloatVariableWidget(float,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,bool)	C++
 	105_Overlays_bin.exe!nanogui::FormScreen::addVariable(float &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,bool)	C++
>	105_Overlays_bin.exe!igl::viewer::Viewer::init() Line 203	C++
 	105_Overlays_bin.exe!igl::viewer::Viewer::launch_init(bool resizable, bool fullscreen) Line 824	C++
 	105_Overlays_bin.exe!igl::viewer::Viewer::launch(bool resizable, bool fullscreen) Line 876	C++
 	105_Overlays_bin.exe!main(int argc, char * * argv) Line 71	C++

PS: it happens in all tutorial examples: program crashes in viewer.init() in release mode. I use VS2013 + window 7. 

Any idea how it happens? Thanks a lot!

**Comment by danielepanozzo** [comment]
Very strange, could you try to build it with VS2015 community edition and see if the problem is still there? I cannot reproduce this with Win 10 + VS 2015.

**Comment by KevinChenGit** [comment]
Hi Daniele,

I finally solved it using VS2013. The error is very weird. I need to run CTRL + F5 in debug mode first in order to get release mode functioning well. Thanks for your suggestion anyway!
