### ISSUE TITLE
trim_with_solid reporting insideness wrong?

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#1374]
<img width="965" alt="image" src="https://user-images.githubusercontent.com/2241689/70002411-f7017180-152d-11ea-9480-effc5f21e29e.png">

Trimming the blue mesh with the orange mesh appears to succeed but then the "is inside solid" flag `D` classifies the right hand incorrectly:

<img width="852" alt="image" src="https://user-images.githubusercontent.com/2241689/70002450-126c7c80-152e-11ea-87e3-21877fc36c94.png">

Dropping the data here so I don't forget to debug this more when I have time

[trim-with-solid-fail.mat.zip](https://github.com/libigl/libigl/files/3913680/trim-with-solid-fail.mat.zip)

...

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [x] Mac OS X
- [ ] Linux
- [x] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by qnzhou** [comment]
Can you share the meshes as well?

**Comment by alecjacobson** [comment]
Do you have Matlab? Theyre in the zip

If not I can send objs later

**Comment by jdumas** [comment]
Eigen also has some functions to read `.mat` in its unsupported modules `SparseExtra`.

**Comment by qnzhou** [comment]
Hmmm, I got the error "Input mesh is not PWN!".

**Comment by alecjacobson** [comment]
One mesh should be solid and the other not
