### ISSUE TITLE
Question: How to do instancing in igl's viewer

### ISSUE THREAD

**Issue by IasonManolas** [libigl/libigl#1381]
I want to render the same object multiple times at different locations using libigl's viewer.

I did not find something in the tutorial but I found [that tutorial](https://learnopengl.com/Advanced-OpenGL/Instancing) and [how to set the viewer's shaders](https://github.com/libigl/libigl/issues/657). 
Is there a way to call functions such as glDrawArraysInstanced through libigl?

**Comment by jdumas** [comment]
We specifically have a [tutorial entry](https://libigl.github.io/tutorial/#multiple-meshes) on how to draw multiple meshes and how to render in multiple viewports using libigl. Does that not answer your question?

**Comment by IasonManolas** [comment]
I already saw those but I can't see how they could solve my problem.
Isn't the multiple meshes entry aimed for multiple meshes? I don't want to have multiple copies of the same mesh. I just want to send to the viewer the mesh data only once + multiple tranformation matrices (for every instance of the mesh that I want to be rendered). 
Regarding the multiple viewports entry, isn't this supposed to "split" the screen in multiple views?
Am I misunderstanding something in the tutorial entries?

**Comment by jdumas** [comment]
How many instances do you need to render? If it's < 10, honestly you're better off just creating multiple copies (unless the mesh is huge). Otherwise you'd have to cook up the solution yourself indeed (using custom shaders and whatnot), but I can't help with that.

**Comment by IasonManolas** [comment]
Its in the order of 1k. So back to my initial question, probably I will need to do that outside of igl since I need calls to opengl functions that are not supported by libigl's interface(e.g. glDrawArraysInstanced). Is that correct?

**Comment by jdumas** [comment]
You can perfectly call any OpenGL function within the libigl viewer, nothing's preventing you to do that. Specifically, you can hook up your own calls in the `pre_draw` or `post_daw` callbacks (using either a `ViewerPlugin` or setting the `callback_pre_draw` lambdas). `pre_draw` means the callback will be called before the libigl viewer calls its main `draw` function, and `post_draw` well ... is called after.

**Comment by IasonManolas** [comment]
I see, great! Thanks for that

**Comment by jdumas** [comment]
I'll close this then, feel free to re-open if you have specific questions about the libigl viewer.
