### ISSUE TITLE
Can MIQ keep feature?

### ISSUE THREAD

**Issue by ytyyyx** [libigl/libigl#1382]
#### Describe your issue
For example,  fix one line in a 3D surface into integer isolines. I didn't see any options based on 505 MIQ. Tell me wrong if I miss something.
...

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by alecjacobson** [comment]
Seems like no.
