### ISSUE TITLE
Bug of igl::copyleft::cgal::half_space_box()

### ISSUE THREAD

**Issue by bylee20** [libigl/libigl#1384]
#### Describe your issue

For a plane x + y + z = 0 and cube bounding box whose x, y, z in [0, 1], igl::copyleft::cgal::half_space_box() crashes for

```
Assertion failed: x.squared_length() > 0, file c:\users\bylee\documents\boolt\boolt-igl\3rdparty\libigl\include\igl\copyleft\cgal\half_space_box.cpp, line 48
```

because projected point of average of bounding box, `o2` is zero vector and the bounding box also contains zero vector, the shortest projected vector `u` will be always zero vector.

...

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by xylosper** [comment]
Is there any workaround?
