### ISSUE TITLE
compile error[windows10;vs studio 2017 win64]

### ISSUE THREAD

**Issue by giserHacter** [libigl/libigl#1385]
Hello,buddy
I miss a compile error:
![image](https://user-images.githubusercontent.com/37400203/70787994-dd341a00-1dca-11ea-9dff-e4b95835bf6b.png)

i hope you can give me a hand.

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by jdumas** [comment]
Have you tried the `dev` branch of libigl?

**Comment by giserHacter** [comment]
Hello,jdumas
I have tried the dev and master,then they did't miss cmake error,but i miss the error:LNK1181 can't open glad.lib when i compile imgui project in vs2017 win64:
![image](https://user-images.githubusercontent.com/37400203/70859001-56587c00-1f47-11ea-956d-f99dec501d4d.png)

**Comment by alecjacobson** [comment]
Hopefully this is fixed with the changes to cmake. If not please reopen.
