### ISSUE TITLE
something wrong with Ex305

### ISSUE THREAD

**Issue by seamanj** [libigl/libigl#139]
![image](https://cloud.githubusercontent.com/assets/10722187/10711294/5fb376a6-7a6e-11e5-9612-1c10886af813.png)
![image](https://cloud.githubusercontent.com/assets/10722187/10711296/6c80a02a-7a6e-11e5-9e77-c44f21bd20cd.png)
help!

**Comment by alecjacobson** [comment]
Are the other examples working? Could it be an issue that it's not finding
the path to the mesh?

I can't reproduce this on my end. Could you send the sizes of the input
matrices to `active_set` to see if they're sensical?

**Comment by seamanj** [comment]
thx,  alecjacobson 
First, I assure that the path is definitely correct. 
The picture below shows the sizes of the input matrices to 'active_set':
![image](https://cloud.githubusercontent.com/assets/10722187/10711409/17772294-7a72-11e5-8abf-59a78232498a.png)

**Comment by alecjacobson** [comment]
I've also tried running this example in debug mode and can't manage to
trigger this exception. Is it happening immediately or after you change the
scale and resolve?

I assume you're using the most up-to-date version of libigl, too.

**Comment by seamanj** [comment]
it's happening immediately. and I am also using the most up-to-date version, is there something wrong with this version?

**Comment by alecjacobson** [comment]
No this version seems correct. I'll need more information from you to
debug. Can you also post the version of Eigen you're using?

**Comment by seamanj** [comment]
Hi,  alecjacobson 
![image](https://cloud.githubusercontent.com/assets/10722187/10712101/a872985e-7a87-11e5-98b0-58e553cb6c61.png)
AS the image shown ,  my EIGEN verison is 3.2.4

**Comment by alecjacobson** [comment]
Oh wait. Are you running this on a different mesh? Not the default one from
the example?

**Comment by seamanj** [comment]
no, I am using the default one,   
igl::readOFF("../../shared/cheburashka.off",V,F);
![image](https://cloud.githubusercontent.com/assets/10722187/10712152/4df49f56-7a89-11e5-86ec-9549e75be2c4.png)

**Comment by alecjacobson** [comment]
I don't understand the print of the vertices and faces then...

I don't have a Windows machine to check this issue. Are you compiling with
any special flags or in full debug mode? Can you post the inputs to the
slice function that's throwing the error?

**Comment by seamanj** [comment]
the print of vertices and faces is from ex101, I make use of that example to print the version number of EIGEN, excuse me for the inconvenience i brought, 

the whole code of ex305 is below:

#include <igl/active_set.h>
#include <igl/boundary_facets.h>
#include <igl/cotmatrix.h>
#include <igl/invert_diag.h>
#include <igl/jet.h>
#include <igl/massmatrix.h>
#include <igl/readOFF.h>
#include <igl/viewer/Viewer.h>
#include <Eigen/Sparse>
#include <iostream>

  
Eigen::VectorXi b;
Eigen::VectorXd B,bc,lx,ux,Beq,Bieq,Z;
Eigen::SparseMatrix<double> Q,Aeq,Aieq;

void solve(igl::viewer::Viewer &viewer)
{
  using namespace std;
  igl::active_set_params as;
  as.max_iter = 8;
  cout << "the size of Q:" << Q.rows() << "*" << Q.cols() << endl;
  cout << "the size of B:" << B.size() << endl;
  cout << "the size of b:" << b.size() << endl;
  cout << "the size of bc:" << bc.size() << endl;
  cout << "the size of Aeq:" << Aeq.rows() << "*" << Aeq.cols() << endl;
  cout << "the size of Beq:" << Beq.size() << endl;
  cout << "the size of Aieq:" << Aieq.rows() << "*" << Aieq.cols() << endl;
  cout << "the size of Bieq:" << Bieq.size() << endl;
  cout << "the size of lx:" << lx.size() << endl;
  cout << "the size of ux:" << ux.size() << endl;
  cout << "the size of Z:" << Z.size() << endl;

  igl::active_set(Q,B,b,bc,Aeq,Beq,Aieq,Bieq,lx,ux,as,Z);
  // Pseudo-color based on solution
  Eigen::MatrixXd C;
  igl::jet(Z,0,1,C);
  viewer.data.set_colors(C);
}

bool key_down(igl::viewer::Viewer &viewer, unsigned char key, int mod)
{
  switch(key)
  {
    case '.':
      Beq(0) *= 2.0;
      solve(viewer);
      return true;
    case ',':
      Beq(0) /= 2.0;
      solve(viewer);
      return true;
    case ' ':
      solve(viewer);
      return true;
    default:
      return false;
  }
}


int main(int argc, char *argv[])
{
  using namespace Eigen;
  using namespace std;
  MatrixXd V;
  MatrixXi F;
  igl::readOFF("../../shared/cheburashka.off",V,F);

  // Plot the mesh
  igl::viewer::Viewer viewer;
  viewer.data.set_mesh(V, F);
  viewer.core.show_lines = false;
  viewer.callback_key_down = &key_down;

  // One fixed point
  b.resize(1,1);
  // point on belly.
  b<<2556;
  bc.resize(1,1);
  bc<<1;

  // Construct Laplacian and mass matrix
  SparseMatrix<double> L,M,Minv;
  igl::cotmatrix(V,F,L);
  igl::massmatrix(V,F,igl::MASSMATRIX_TYPE_VORONOI,M);
  //M = (M/M.diagonal().maxCoeff()).eval();
  igl::invert_diag(M,Minv);
  // Bi-Laplacian
  Q = L.transpose() * (Minv * L);
  // Zero linear term
  B = VectorXd::Zero(V.rows(),1);

  // Lower and upper bound
  lx = VectorXd::Zero(V.rows(),1);
  ux = VectorXd::Ones(V.rows(),1);

  // Equality constraint constrain solution to sum to 1
  Beq.resize(1,1);
  Beq(0) = 0.08;
  Aeq = M.diagonal().transpose().sparseView();
  // (Empty inequality constraints)
  solve(viewer);
  cout<<
    "Press '.' to increase scale and resolve."<<endl<<
    "Press ',' to decrease scale and resolve."<<endl;

  viewer.launch();
}

**Comment by ArtisticCoding** [comment]
Same Problen occured to me... i suppose that igl::cat() make some bug in Eigen on VS2013

igl::active_set(...) 
{
   ...
   std::cout << Aeq_i << std::endl; // ok
   igl::cat(1, Aeq, Aieq_i, Aeq_i);  // after evaluation of igl::cat(), Aeq_i may be corrupted
   std::cout << Aeq_i << std::endl; // error
    ...
}

**Comment by ArtisticCoding** [comment]
Same Problen occured to me...

i supposed to DiagonalMatrix.tranposed() have some bug in Visual Studio 2013...

int main(int argc, char *argv[])
{
  ...
  Aeq = M.diagonal().transpose().sparseView();				// Aeq is corrupted...

  SparseMatrix<double> test1 = M.diagonal().sparseView();
  std::cout << test1 << std::endl;					// no error

  SparseMatrix<double> test2 = M.diagonal().transpose().sparseView();
  std::cout << test2 << std::endl;					// memory error
  ...
}

**Comment by ArtisticCoding** [comment]
finally, i fixed the bug

change following source code:
Aeq = M.diagonal().transpose();sparseView().
->
Aeq = M.diagonal().sparseView().transpose();

**Comment by alecjacobson** [comment]
This sounds like an Eigen bug. Not sure why one should be invalid. Perhaps
post this to https://forum.kde.org/viewforum.php?f=74

**Comment by alecjacobson** [comment]
Even though this seems like an Eigen bug, I've fixed our code to avoid this bug for now.
