### ISSUE TITLE
cmake file is deprecated. use libigl.cmake instead

### ISSUE THREAD

**Issue by Monica-Xiao** [libigl/libigl#1391]
#### Describe your issue

...
hey, guys. I am a newbie for libigl, and I am trying to operate the coding of Developable surface for triangle mesh which requires the libigl package. When I use CMake to configure the CMake.list, it shows the same problem. However, I have tried to download the files of the shared file manually, but still have the problem. The libigl.cmake file is at the same location as the CMakeLists.txt file.
 My computer is Win system. May I have and suggestions? thank you
 
>CMake Deprecation Warning at CMakeLists.txt:4 (message):
>shared/cmake/CMakeLists.txt is deprecated.  Use libigl.cmake instead.

Using Win32 for window creation
Configuring done

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by jdumas** [comment]
Hi. You're trying to use a code based off a version of libigl from >1 year ago. You should update you code to use the latest commit from the 'dev' branch of libigl. As always, please read the instructions on the website (e.g. the section about the libigl example project) and update your code accordingly.
