### ISSUE TITLE
cmake fails for cgal 4.11 on linux ubuntu

### ISSUE THREAD

**Issue by emilebobleponge** [libigl/libigl#1394]
#### Describe your issue

Today, I installed CGAL version 4.11 on my linux Ubuntu PC. When I try to use cmake to open a file that requires CGAL, I get the following error message:

"CGAL not found.  Set the CGAL_DIR cmake variable or environment variable to
  the directory containing CGALConfig.cmake.  This is either the binary
  directory where CGAL was configured or PREFIX/lib/CGAL for an installation."

Thanks in advance!

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by jdumas** [comment]
Hi,

Libigl is built and tested using CGAL 4.12. Earlier versions will not work, and we can't guarantee that later version will remain compatible.

To use CGAL with libigl you need to:
1. Install CGAL's dependencies. On Ubuntu that means installing boost + gmp/mpfr
    ```
    sudo apt-get install libboost-filesystem-dev libboost-system-dev libboost-thread-dev libmpfr-dev
    ```
    On macOS using brew
    ```
    brew install boost gmp mpfr
    ```
    On Windows you only need to install boost.
2. You do not need to install CGAL itself. Call CMake with `-DLIBIGL_WITH_CGAL=ON`, and link your target with `igl::cgal` (e.g. see tutorial 609_Boolean). Then CMake will download the correct version of CGAL to use with libigl.
3. If something does not work, make sure you are using the `dev` branch of the libigl repository.

**Comment by alecjacobson** [comment]
Hopefully improved with gmp and mpfr as part of the build. Only the cgal version sucked in from cmake is supported (and we intend to keep it up to date).
