### ISSUE TITLE
CMake Error Can not libigl

### ISSUE THREAD

**Issue by YemmyMMU** [libigl/libigl#1398]
#### Describe your issue
Hi everyone,

Pls kindly help I am trying to run Cmake and gave me undelisted error.

Thank you.

Ajayi 

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [X] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

CMake Error at cmake/FindLIBIGL.cmake:36 (include):
  include could not find load file:

    libigl
Call Stack (most recent call first):
  CMakeLists.txt:27 (find_package)

CMake Error at /usr/share/cmake-3.10/Modules/FindBoost.cmake:1286 (file):
  file STRINGS file "/home/cherdsak/boost_1_58_0/boost/version.hpp" cannot be
  read.
Call Stack (most recent call first):
  CMakeLists.txt:29 (find_package)

CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  0 (all versions older than 1.33)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:29 (find_package)

CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  0 (all versions older than 1.33)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:29 (find_package)

CMake Error at /usr/share/cmake-3.10/Modules/FindBoost.cmake:1947 (message):
  Unable to find the requested Boost libraries.

  Boost version: 0.0.0

  Boost include path: /home/cherdsak/boost_1_58_0

  Detected version of Boost is too old.  Requested version was 1.58 (or
  newer).
Call Stack (most recent call first):
  CMakeLists.txt:29 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/cherdsak/Documents/My_Projects/Fall_2017/SDFGenerator/build/CMakeFiles/CMakeOutput.log".
See also "/home/cherdsak/Documents/My_Projects/Fall_2017/SDFGenerator/build/CMakeFiles/CMakeError.log".

**Comment by jdumas** [comment]
Well the error message says you have a problem with your boost installation. Why don't you simply install boost via the package manager on linux?

**Comment by YemmyMMU** [comment]
Hi everyone, pls I need help 

pgstudent@pgstudent-HP-EliteDesk-800-G4-Twr-IDS-APJ:~/Documents/MeshGAN/SDFGenerator/build$ cmake ..
CMake Error at cmake/FindLIBIGL.cmake:36 (include):
  include could not find load file:

    libigl
Call Stack (most recent call first):
  CMakeLists.txt:27 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/pgstudent/Documents/MeshGAN/SDFGenerator/build/CMakeFiles/CMakeOutput.log".
See also "/home/pgstudent/Documents/MeshGAN/SDFGenerator/build/CMakeFiles/CMakeError.log".
pgstudent@pgstudent-HP-EliteDesk-800-G4-Twr-IDS-APJ:~/Documents/MeshGAN/SDFGenerator/build$

**Comment by jdumas** [comment]
You need to have a folder with the libigl source next to your project folder. Please take a look at the content of the [FindLIBIGL.cmake](https://github.com/libigl/libigl-example-project/blob/master/cmake/FindLIBIGL.cmake) to figure out the search paths that are used by CMake to find the libigl folder.

**Comment by XuRongYan** [comment]
I came across the same question as YemmyMMU. I followed the tutorial and compiled the libigl and then I installed the header files into /usr/local/include.
The igl/readOFF.h can be found at /usr/local/include/igl/readOFF.h.
Then, my CMakeLists.txt is just like:
```
option(LIBIGL_WITH_TETGEN     "Use Tetgen" ON)
option(LIBIGL_WITH_CGAL     "Use CGAL" ON)
find_package(LIBIGL REQUIRED QUIET)
```
Then the error is:
```
CMake Error at cmake/FindLIBIGL.cmake:37 (include):
  include could not find requested file:

    libigl
Call Stack (most recent call first):
```
Please give me some help.

**Comment by jdumas** [comment]
Please take a look at the [example project](https://github.com/libigl/libigl-example-project). In particular, you just need to put [this file](https://github.com/libigl/libigl-example-project/blob/8bffa8b1722f937734d06f8762f813cc4022abcd/cmake/libigl.cmake#L1) in your own CMake project to start using libigl. Do not install anything on your system.
