### ISSUE TITLE
boundry_loop return empty object 

### ISSUE THREAD

**Issue by wissalsayhi** [libigl/libigl#1401]
#### Describe your issue
I'm trying to parametrize a human body 3D mesh, I tried to use the code in the lscm tutorial on an a mesh with 24461 vertices and 48918 of a human body. the boundry_loop function always return an empty object. 
I used the same code on a different object and it worked.

##############
v, f = igl.read_triangle_mesh(os.path.join(root_folder, "data", "camel_b.obj"))
b = np.array([2, 1])

bnd = igl.boundary_loop(f)
b[0] = bnd[0]
b[1] = bnd[int(bnd.size / 2)]

bc = np.array([[0.0, 0.0], [1.0, 0.0]])
_, uv = igl.lscm(v, f, b, bc)

p = plot(v, f, uv=uv, shading={"wireframe": False, "flat": False}, return_plot=True)
############

I can't seem to figure out why it doesn't work on my object 
...

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by BruegelN** [comment]
Does your 3D Model have a boundary? It's quite likely that it's genus 0 (=> 2 == igl::euler_characteristic(V,F)).
If your 3D model is _not_ disk-like you can achieve this e.g. by `igl::cut_to_disk()` + `igl::cut_mesh()`

**Comment by wissalsayhi** [comment]
Thank you very much for your reply it was really helpful. I think it doesn't have a boundary. The igl::euler_characteristic(V,F) is 2 as you said. Still I'm not sure how to define the cuts parameter for the cut_mesh .

**Comment by BruegelN** [comment]
Maybe this helps: https://github.com/libigl/libigl/issues/1328

**Comment by wissalsayhi** [comment]
Hi, 
It seems like the cut_to_disk function is not available in the python Binding. is it gonna be implemented? or is it there but i failed to find it ? Thanks for your help

**Comment by jiangzhongshi** [comment]
`cut_to_disk` is not yet in the bindings but it is going to be implemented.
