### ISSUE TITLE
Faster 708_Picking

### ISSUE THREAD

**Issue by VasilisTz1** [libigl/libigl#1406]
I am dealing with the task of Picking Faces with "libigl". I have found 708_Picking tutorial very useful, but I realised as well that for big meshes it takes too much time. I stumbled upon this link: https://github.com/libigl/libigl/issues/544?fbclid=IwAR0PaqkQhUvvSf4bx9LxM3y8xrEIFDMRXLoh48FtPpo-gDrAwN4Vak7WmtI . Even though I tried so hard to implement the solution you had suggested (to replace `igl::ray_mesh_intersect`  with `igl::embree::EmbreeIntersector` (using interectRay) for my project), I am unable to make it work. 

Specifically, I installed embree, I created an Embree intersection structure ( igl::embree::EmbreeIntersector ei; ) and I initialized  ( ei.init(V.cast<float>(), F.cast<int>()); ). Then, I tried to replace "igl::unproject_onto_mesh", which is inside the callback function (look at 708_Picking Tutorial code) with the following code (which i found on libigl-examples repository)

////////////////

> win_s = Eigen::Vector3f(x, y, 0);
> Eigen::Vector3f win_d(x, y, 1);
> igl::opengl2::unproject(win_s, s);
> igl::opengl2::unproject(win_d, d);
> 			
> dir = d - s;
> int num_rays_shot;
> ei.intersectRay(s, dir, hits, num_rays_shot);
> 	for (std::vector<igl::Hit >::iterator hit = hits.begin();
> 				hit != hits.end();
> 				hit++)
> 			{
> 				// Change color of hit faces
> 				C(hit->id, 0) = 1;
> 				C(hit->id, 1) = 0.4;
> 				C(hit->id, 2) = 0.4;
> 			}

////////////////
I realised that i should include unproject.h (#include <igl/opengl2/unproject.h>), as i did. I found the library in this link: https://gitlab.ouahpiti.info/faquin/IMAGE/blob/5ace3aa171361046134b991c658656db113c7e66/libigl/include/igl/opengl2/unproject.h . I got the following LNK errors
<img width="787" alt="my_errors" src="https://user-images.githubusercontent.com/59918539/72525500-f9fdba80-386c-11ea-802f-39cfeaa57365.png"> .

Unfortunately, my programming skills in C++ are not so advanced.

If you'd be so kind, I would really appreciate it, if you could give me some help or guidance.

**Comment by alecjacobson** [comment]
This is a minimal change on that tutorial to use the Embree version:

```

#include <igl/read_triangle_mesh.h>
#include <igl/embree/unproject_onto_mesh.h>
#include <igl/opengl/glfw/Viewer.h>
#include <iostream>

int main(int argc, char *argv[])
{
  // Mesh with per-face color
  Eigen::MatrixXd V, C;
  Eigen::MatrixXi F;

  // Load a mesh in OFF format
  igl::read_triangle_mesh(argv[1], V, F);
  igl::embree::EmbreeIntersector ei;
  ei.init(V.cast<float>(),F);

  // Initialize white
  C = Eigen::MatrixXd::Constant(F.rows(),3,1);
  igl::opengl::glfw::Viewer viewer;
  viewer.callback_mouse_down =
    [&V,&F,&C,&ei](igl::opengl::glfw::Viewer& viewer, int, int)->bool
  {
    int fid;
    Eigen::Vector3f bc;
    // Cast a ray in the view direction starting from the mouse position
    double x = viewer.current_mouse_x;
    double y = viewer.core().viewport(3) - viewer.current_mouse_y;
    if(igl::embree::unproject_onto_mesh(Eigen::Vector2f(x,y), F, viewer.core().view,
      viewer.core().proj, viewer.core().viewport, ei, fid, bc))
    {
      // paint hit red
      C.row(fid)<<1,0,0;
      viewer.data().set_colors(C);
      return true;
    }
    return false;
  };
  std::cout<<R"(Usage:
  [click]  Pick face on shape

)";
  // Show mesh
  viewer.data().set_mesh(V, F);
  viewer.data().set_colors(C);
  viewer.data().show_lines = false;
  viewer.launch();
}

```

**Comment by VasilisTz1** [comment]
Thank you for your immediate help, but i still can't run this...
First of all, i added (#include <igl/embree/EmbreeIntersector.h>).
Now I am getting a similar LNK error as the above.
<img width="1602" alt="error_1" src="https://user-images.githubusercontent.com/59918539/72733244-246ab300-3ba0-11ea-81d2-b2f7ae66ec82.png">
I guess that I should do something in Linker-->Input Additional Dependencies. I have already added:
..\..\Debug\embree3.lib
..\..\Debug\tbb.lib
..\..\Debug\tbbmalloc.lib

**Comment by jdumas** [comment]
You need to set the CMake option `LIBIGL_WITH_EMBREE` to `ON`, and add `igl::embree` to the list of libraries linked in the `target_link_libraries(...)` for your executable.

**Comment by VasilisTz1** [comment]
Thank you for your guidance, now embree is working! :)

Nevertheless, the marking process has a slow response rate -- far from "real-time" in big meshes. Is there any way that it can work in real-time? 

Picking could be in something like "brush" mode (thick ray that intersects multiple polygons), which is the ultimate goal for my implementation. Any info would be much appreciated!

**Comment by jdumas** [comment]
If you are coloring a single triangle at a time, you might want to modify the shader and pass that information as a uniform -- that way you don't have to reupload the entire color attribute vector for the whole mesh. Otherwise, there are ways to update only parts of a buffer data, using `glBufferSubData`, so you could update color information for triangles as they are selected/deselected. Nothing easy to do out of the box with the current viewer I'm afraid.

**Comment by BruegelN** [comment]
Maybe too trivial to ask, but just to check, did you built in `Release` or `Debug` mode?
If `Debug` could you please try again in `Release` mode.
Eigen gets quite slow in `Debug` mode due to assertions.
