### ISSUE TITLE
Help needed - Extra weights and rotations

### ISSUE THREAD

**Issue by BingEdison** [libigl/libigl#1408]
#### Describe your issue
Howdy do! After computing custom biharmonic weights around limbs using point_mesh_squared_distance of human body(using tetrahedral mesh) output results in mesh deformations like cloth with much sagging and loss of rigidity. Desired result is seen in 2:25 and 2:50 mark of video.How do you use extra weights to obtain rigid behavior? Is it possible with libigl to rotate verts with single handle as seen in video?

https://m.youtube.com/watch?v=H8wX5jO5lMo

...

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by alecjacobson** [comment]
I'm not quite sure what it means to compute biharmonic weights with point_mesh_squared_distance, but I guess if you have weights then have a look at arap_dof.h you can mark the transformations associated with the "extra" handles as free and then the optimization will fully control them.
