### ISSUE TITLE
Possible error in gaussian_curvature.cpp

### ISSUE THREAD

**Issue by jmespadero** [libigl/libigl#141]
Hi,

First of all, congratulations for your work and thank you very much for releasing your code.

Then... I would like to discuss the formula you are using for computing gaussian_curvature in  libigl/include/igl/gaussian_curvature.cpp

Basically you are computing K_G(x_i) = (2π - ∑θj) , but seems that you forgot to normalize the value dividing by the (voronoi or mixed) area of the vertex.

Without this normalization, you will have plausible results for curvature in semi-regular meshes, where all vertex areas are similar. This is the case of your bumpy.off case test.

See page 12 of Mark Meyer, Mathieu Desbrun, Peter Schröder and Alan H. Barr, [Discrete Differential-Geometry Operators for Triangulated 2-Manifolds](https://www.google.com/search?q=Discrete+Differential-Geometry+Operators+for+Triangulated+2-Manifolds)
or see page 47 of Botsch, Kolbert, Pauly, et al, "Polygon Mesh Processing" book
or see page 20 of [PMP-book slides ](http://www.pmp-book.org/download/slides/Differential_Geometry.pdf)

**Comment by alecjacobson** [comment]
You can consider `gaussian_curvature.cpp` as computing the _local integral_ of Gaussian curvature, see the equation under section 4.1 in Mark Meyer, Mathieu Desbrun, Peter Schröder and Alan H. Barr, Discrete Differential-Geometry Operators for Triangulated 2-Manifolds.

If you divide by the local area, then you'll get a local integral average (i.e. a pointwise quantity). 

We will **not** change the `gaussian_curvature.cpp` function to include this averaging, but it might make sense to change the visualization and relevant to tutorial entry: http://libigl.github.io/libigl/tutorial/tutorial.html#gaussiancurvature

I have updated the doc of `gaussian_curvature.cpp` to make this (extra) clear.
