### ISSUE TITLE
Problems with quadrilateral mesh

### ISSUE THREAD

**Issue by pauljurczak** [libigl/libigl#1410]
There is an example of a quadrilateral mesh in `libgl\tests\data\cube.off`:
```
OFF
8 6 12
 1.0   0.0   1.0
 0.0   1.0   1.0
-1.0   0.0   1.0
 0.0  -1.0   1.0
 1.0   0.0  -1.0
 0.0   1.0  -1.0
-1.0   0.0  -1.0
 0.0  -1.0  -1.0
 4  0 1 2 3
 4  7 4 0 3
 4  4 5 1 0
 4  5 6 2 1
 4  3 2 6 7
 4  6 5 4 7
```
which doesn't work as intended with master branch of `libigl`. Is it work in progress?

![Screenshot from 2020-01-23 02-14-28](https://user-images.githubusercontent.com/4933032/72971317-b3d1bb00-3d86-11ea-8dfd-1d3edca9b739.png)

**Comment by jdumas** [comment]
The viewer only supports triangle meshes. Here is a function to turn a quad mesh into a triangle mesh:
```cpp
void quad_to_tri(const Eigen::MatrixXi &Q, Eigen::MatrixXi &F, Eigen::MatrixXi &E, Eigen::VectorXi &J) {
	assert(Q.cols() == 4);
	F.resize(Q.rows() * 2, 3);
	E.resize(Q.rows() * 4, 2);
	J.resize(F.rows());
	for (int q = 0; q < Q.rows(); ++q) {
		F.row(2*q+0) << Q(q, 0), Q(q, 1), Q(q, 2);
		F.row(2*q+1) << Q(q, 0), Q(q, 2), Q(q, 3);
		E.row(4*q+0) << Q(q, 0), Q(q, 1);
		E.row(4*q+1) << Q(q, 1), Q(q, 2);
		E.row(4*q+2) << Q(q, 2), Q(q, 3);
		E.row(4*q+3) << Q(q, 3), Q(q, 0);
		J->segment(2*q, 2).setConstant(q);
	}
}
```

You can then display the edges `E` using `ViewerData::set_edges()` to give the impression of a quad mesh in the viewer.

**Comment by pauljurczak** [comment]
Thank you. Small typo in your code:
`J->segment(2*q, 2).setConstant(q);`  -->  `J.segment(2*q, 2).setConstant(q);`

Out of curiosity, what is the purpose of a quadrilateral mesh file: `libgl\tests\data\cube.off`?

**Comment by jdumas** [comment]
A few libigl functions support quad meshes as well as triangle meshes, though support is not very widely spread.
