### ISSUE TITLE
numeric_limits<double>::min() is the minimal positive number

### ISSUE THREAD

**Issue by nepluno** [libigl/libigl#1411]
https://github.com/libigl/libigl/blob/56f129e4403d3b7b04ddd786745fd3d574e95e04/include/igl/copyleft/cgal/extract_cells.cpp#L203

From the context it seems this line should be numeric_limits<double>::lowest() since numeric_limits<double>::min() refers to the minimal positive number (2.22507e-308) in the double range, instead of the lowest number (-1.79769e+308) in the double range. This bug would cause incorrect computation of the bounding box.

**Comment by jdumas** [comment]
Agreed. Can you create a PR for it?
