### ISSUE TITLE
glad.h issue after attempting to compile program including igl

### ISSUE THREAD

**Issue by ifigs** [libigl/libigl#1412]
I tried just moving the folder igl that I downloaded into the /usr/local/include directory. I had to install Eigen, which I didn't have yet. I compiled (using the g++ command by itself) to test my version of Eigen and igl, and I got an error. What do I do about the glad.h issue?

code:
#include <Eigen/Core>
#include <iostream>
#include <igl/readOFF.h>`
#include <igl/opengl/glfw/Viewer.h>

using namespace std;
using namespace Eigen; 

int main(int argc, char *argv[])
{
 cout << "Eigen version: " << EIGEN_MAJOR_VERSION << "." << EIGEN_MINOR_VERSION << endl;

        // Load a mesh in OFF format
        igl::readOFF(TUTORIAL_SHARED_PATH "/bunny.off", V, F);

        // Plot the mesh
        igl::opengl::glfw::Viewer viewer;
        viewer.data().set_mesh(V, F);
        viewer.launch();

        //return 0; 
} 

error:
` /usr/local/include/igl/opengl/glfw/../gl.h:23:10: fatal error: 'glad/glad.h'
      file not found
#include <glad/glad.h>`

- [ ] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by jdumas** [comment]
The only module we support installing for now is the core libigl library, i.e. the part that depends on Eigen and nothing else. If you want to use libigl with other dependencies (like glad) you need to compile from source, as done in the [libigl-example-project](https://libigl.github.io/example-project/).

**Comment by ifigs** [comment]
Ok, so what is the core library in the GitHub? Is it in include/igl? That's the folder I moved into usr/local/include and then I got that error when I tried to compile the simple program. I don't even know what glad is.

I tried compiling from source like in the example project, but it's not working for me either. I'm not sure where it's installing. I thought it would show up in usr/local/include since the tutorial said it would be copied. I'm not sure what the library actually is in the file hierarchy anymore.

**Comment by jdumas** [comment]
Everything that is directly under `include/igl` is part of the core library. Everything that is in a subfolder (like the opengl viewer) has extra dependency and needs additional setup. If you have trouble compiling the example project, please open a different issue and explain what is going on. If you follow the instruction on the website you should be able to compile it though.

**Comment by gitouni** [comment]
> I tried just moving the folder igl that I downloaded into the /usr/local/include directory. I had to install Eigen, which I didn't have yet. I compiled (using the g++ command by itself) to test my version of Eigen and igl, and I got an error. What do I do about the glad.h issue?
> 
> code: #include <Eigen/Core> #include #include <igl/readOFF.h>` #include <igl/opengl/glfw/Viewer.h>
> 
> using namespace std; using namespace Eigen;
> 
> int main(int argc, char *argv[]) { cout << "Eigen version: " << EIGEN_MAJOR_VERSION << "." << EIGEN_MINOR_VERSION << endl;
> 
> ```
>     // Load a mesh in OFF format
>     igl::readOFF(TUTORIAL_SHARED_PATH "/bunny.off", V, F);
> 
>     // Plot the mesh
>     igl::opengl::glfw::Viewer viewer;
>     viewer.data().set_mesh(V, F);
>     viewer.launch();
> 
>     //return 0; 
> ```
> 
> }
> 
> error: ` /usr/local/include/igl/opengl/glfw/../gl.h:23:10: fatal error: 'glad/glad.h' file not found #include <glad/glad.h>`
> 
> * [ ]  Windows
> * [x]  Mac OS X
> * [ ]  Linux
> * [ ]  I have tried the `dev` branch and the problem persists
> 
> See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

I think the missing file is `glad/gl.h` rather than `glad.h`. It can be found at `build/_deps/glfw-src/deps` if the libigl package has been compiled. If you want to include `libigl/Viewer.h` in other projects, you must add the absolute path of  `build/_deps/glfw-src/deps`  in that project.
