### ISSUE TITLE
questions also about example 505_MIQ

### ISSUE THREAD

**Issue by ChildAdrian** [libigl/libigl#1414]
Hi, I ve read example 505_MIQ and https://github.com/libigl/libigl/issues/393,
I still have question about how to map UV to every vertices on orig mesh or a cut mesh(if igl can generate the cut mesh from Seams)?
it seems that the V.rows() isn`t increased after igl::cut_mesh_from_singularities(V, F, MMatch, Seams);

**Comment by BruegelN** [comment]
Hi @ChildAdrian,
`igl::cut_mesh_from_singularities(V, F, MMatch, Seams);` only generates flag which edges of the mesh tu cut, that's what is stored in `Seams` ( https://github.com/libigl/libigl/blob/master/include/igl/cut_mesh_from_singularities.h#L23-L25 ).
To actually cut the mesh you have to call [igl::cut_mesh()](https://github.com/libigl/libigl/blob/master/include/igl/cut_mesh.h), which is done inside [igl::copyleft::comiso::miq()](https://github.com/libigl/libigl/blob/master/include/igl/copyleft/comiso/miq.cpp#L1202), too.


_______
To save the mesh with the cuts you could do sth. like the following (without UV/texture coordinates):
```C++
// Cut the mesh, duplicating all vertices on the seams
igl::cut_mesh_from_singularities(V, F, MMatch, Seams);
Eigen::MatrixXd Vnew;
Eigen::MatrixXi Fnew;
igl::cut_mesh(V,F,Seams, Vnew, Fnew);
igl::writeOBJ("test.obj", Vnew, Fnew);
```
Seams are colored green for visualization:
![Bildschirmfoto vom 2020-02-03 22-47-07](https://user-images.githubusercontent.com/9728182/73694009-87e3fd00-46d7-11ea-919d-9fb3e460db2f.png)

**Comment by ChildAdrian** [comment]
@BruegelN Thank you very much! Your explanation is exactly what i need to solve the question!
