### ISSUE TITLE
doublearea returns null matrix (0 rows ,1 col), leading to segfault in orient_outward

### ISSUE THREAD

**Issue by prashantraina** [libigl/libigl#1416]
#### Describe your issue

When  `doublearea` is called in `orient_outward` for a 3D triangular mesh, it returns a null matrix with 0 rows and 1 column.
This causes a segfault in `orient_outward` when it tries to loop over the entries of the `A` matrix.

#### Workaround

I changed line 57 of `doublearea.cpp` as follows:
`dblA = dblA.array().sqrt().eval();`  
to:  
`dblA = dblA.array().sqrt();`  
And now everything appears to work fine.
Should I make a pull request?

For some reason I don't understand, calling `.eval()` results in a null matrix.
It also doesn't seem to be necessary to call `eval()`, since this is a coefficient-wise operation, so it should not matter that `dblA` is on both sides of the assignment operation. [see Eigen docs](https://eigen.tuxfamily.org/dox/group__TopicAliasing.html)
I am using Eigen 3.3.4, which is both bundled with PyMesh and installed on my system (not sure which is being included, but both are the same version).

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [ x] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by alecjacobson** [comment]
I can't reproduce this. Maybe a skipped entry in the `C` input?

In any case, I'd recommend using `reorient_facets_raycast`/
