### ISSUE TITLE
SLIM with python bindings - minimal working example?

### ISSUE THREAD

**Issue by zlato-kral-dans** [libigl/libigl#1421]
#### Describe your issue

Installed libigl python bindings with conda. I have ARAP working, however, it produces a 2D mesh that has overlapping triangles (with code below). Therefore, I would like a 2D parameterized mesh (non-overlapping tri's) with SLIM. Trying to get SLIM working with python bindings...Can someone post a minimal working example to use SLIM with python please (maybe for the camel head)? Looks like the doc page for SLIM is still under construction. I am aware that SLIM needs a initialization and is iterative.

```
v, f = igl.read_triangle_mesh(os.path.join(root_folder, "camelhead.off"))
bnd = igl.boundary_loop(f)
bnd_uv = igl.map_vertices_to_circle(v, bnd)
uv = igl.harmonic_weights(v, f, bnd, bnd_uv, 1)
arap = igl.ARAP(v, f, 2, np.zeros((0)))
uva = arap.solve(np.zeros((0, 0)), uv)
uvmod = np.hstack([uva, np.zeros((uva.shape[0],1))])
p = plot(v, f, uv=uva, shading={"wireframe": False, "flat": False}, return_plot=True)
```

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [x ] Mac OS X
- [ ] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by teseoch** [comment]
I think we miss the tutorial bu we do have it.

Here is an example:
```
v, f, _ = igl.read_off(os.path.join(self.test_path, "camelhead.off"))
        b = igl.boundary_loop(f)
        thetas = np.linspace(0, 2 * np.pi, len(b))[:, np.newaxis]
        bc = np.concatenate([np.cos(thetas), np.sin(thetas), np.zeros_like(thetas)], axis=1)
        uv_initial_guess = igl.harmonic_weights(v, f, b, bc, 1)

        slim = igl.SLIM(v, f, uv_initial_guess[:, :2], b, bc[:, :2], igl.SLIM_ENERGY_TYPE_ARAP, 0.0)
        slim.solve(1)
        v2 = slim.vertices()
        self.assertEqual(v2.shape[0], v.shape[0])
        self.assertTrue(v2.flags.c_contiguous)
```

the `test_basic.py` file
https://github.com/libigl/libigl-python-bindings/blob/master/tests/test_basic.py
contains am almost exhaustive (but less fancy) list of examples
