### ISSUE TITLE
csvread reads only first column (or first element of the file). 

### ISSUE THREAD

**Issue by AdithyaPediredla** [libigl/libigl#1423]
#### Describe your issue

csvread command reads only the first column (or first element of each line) of the CSV file. 

I have fixed the problem in my local copy by changing lines 33-34 of readCSV.cpp from 
```
while (iss >> a)
     temp.push_back(a);
```
to 
```
char ch;
while (iss >> a >> ch)
     temp.push_back(a);
temp.push_back(a);
```
I can create a pull request with a unit test if you prefer to. 

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by jdumas** [comment]
That's surprising. Yes please create a PR against the `dev` branch. A unit test would be nice but probably not needed, this looks like a simple enough bug.

**Comment by alecjacobson** [comment]
Seems like this got fixed
