### ISSUE TITLE
How to interpolate colors with Laplace-Beltrami.

### ISSUE THREAD

**Issue by makayla-moster** [libigl/libigl#1424]
#### Describe your issue

I'm trying to interpolate colors using the Laplace-Beltrami operator, but I'm unsure how to do so using libigl. I tried using 205_laplacian from the tutorial as my base code, but that gave me errors/no mesh in the viewer.

Can someone point me in the right direction? Thank you!

#### Check all that apply (change to `[x]`)
- [X] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by alecjacobson** [comment]
Did the tutorial give errors without any changes? If not, what were your changes?
