### ISSUE TITLE
Set camera parameters and switching camera by using the keyboard

### ISSUE THREAD

**Issue by lukkio88** [libigl/libigl#1426]
#### Describe your issue
Hi, I have a file with different camera poses and a mesh to render.

I was wondering if I can setup a simple viewer which main functionality is render the mesh from different point of view. By pressing the `left` and `right` keys on the keyboard I'd like to be able to change such view.

I was looking at the interface of `Viewer`, `ViewerCore` and `ViewerData`. `ViewerCore` has the member fields

```
// Camera parameters
  float camera_base_zoom;
  float camera_zoom;
  bool orthographic;
  Eigen::Vector3f camera_base_translation;
  Eigen::Vector3f camera_translation;
  Eigen::Vector3f camera_eye;
  Eigen::Vector3f camera_up;
  Eigen::Vector3f camera_center;
  float camera_view_angle;
  float camera_dnear;
  float camera_dfar;

```

I assume I have to use these somehow, am I right? can you provide some advice on how I can achieve this correctly?

Thank you
...

#### Check all that apply (change to `[x]`)
- [x] Linux

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by lukkio88** [comment]
Also, I'd like to be able to retrieve the camera parameters when for example I move the camera around using my mouse. At the moment reading through the data members I mentioned doesn't give me an updated camera position.

**Comment by pauljurczak** [comment]
I have a similar request. I'm using `libigl` for real time visualization and I don't see a way to set the camera view other than orthographic top view. In the real time loop I'm calling:
```
viewer.data().add_edges(cube.end0, cube.end1, Red);
viewer.core().align_camera_center(cube.end0);
viewer.core().set_rotation_type(igl::opengl::ViewerCore::ROTATION_TYPE_NO_ROTATION);
viewer.draw();
viewer.data().clear();
glfwSwapBuffers(viewer.window);
```
and the view is the same regardless of `set_rotation_type` argument. I would like to be able to set camera parameters directly.

**Comment by alecjacobson** [comment]
The viewer camera controls are a mess. The  `camera_up`, `camera_eye` and `camera_center` params define a "Look at" view matrix, but then this gets multiplied by the `trackball_angle` (rotation controlled by the mouse dragging).

see https://github.com/libigl/libigl/blob/9bfacf8fb6cb38f63c06bc5a7ba81105c9310cef/include/igl/opengl/ViewerCore.cpp#L142
