### ISSUE TITLE
Camera parameters not normalized when rietrieved from the viewer.

### ISSUE THREAD

**Issue by lukkio88** [libigl/libigl#1427]
#### Describe your issue

Hi, I'm trying to retrieve the camera parameters from the a `Viewer` object as I move the camera around the scene.

The syntax I'm using to achieve this is of the form: `viewer.core().view`  or `viewer.core().proj` or `viewer.core().norm`. According to the comment in the relevant file `ViewerCore.h`
```
// Save the OpenGL transformation matrices used for the previous rendering pass
  Eigen::Matrix4f view;
  Eigen::Matrix4f proj;
  Eigen::Matrix4f norm;
```

So in particular the `view` matrix should encode something of the form `[R T;0 1]` where `R` is in particular an orthonormal matrix.

However few attempts to print the content show content like the following:

```
view: 
 0.0517871          0          0 -0.0575183
         0  0.0517871          0   0.157005
         0          0  0.0517871   -4.93254
         0          0          0          1
```

Where from the topleft subblock of dimension 3x3 you can see it's not orthonormal.
I would highly appreciate a reply... please.

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [x ] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by lukkio88** [comment]
Just to clarify, what I need to know is how to get the camera position in world space. The reason for that is because I need to place object in the scene where the camera is currently located, however for some reason everything I place gets rescaled.

**Comment by alecjacobson** [comment]
The view matrix contains scaling (zoom).

The viewer camera setup is a bit of a mess. I personally won't fix it any time soon. I wish it were better documented but even that is a headache to unravel.
