### ISSUE TITLE
Duplicate Symbol Compile Error Involving Serialize.h

### ISSUE THREAD

**Issue by graphitical** [libigl/libigl#1432]
#### Describe your issue

I get a `duplicate symbol 'igl::serialization::_serialization(my_args)'` compile error in my code when using libigl library. This can be fixed by `inline`-ing `igl::serialization::_serialization` on line 48 in `libigl/include/igl/serialize.h`

I'm pretty new to C++ and libigl so apologies in advance if the explanation is poor or the hack is shoddy.

I'm working with @merlinyx and they also have seen the same problem.

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [x] Mac OS X (10.15.3)
- [x] Linux
- [x] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by alecjacobson** [comment]
I'm not going to personally fix anything involving the serialization so marking this as such. Would be happy to merge a PR if someone else does.
