### ISSUE TITLE
A required library with BLAS API not found

### ISSUE THREAD

**Issue by Haitham96** [libigl/libigl#1435]
Hi,
i'm trying to compile the library through cmake on linux.
I do:
1) mkdir build
2) cd build
3) cmake ..
then i got this error:
-- Creating target: igl::core (igl)
-- Creating target: igl::comiso (igl_comiso)
CMake Error at /usr/share/cmake-3.10/Modules/FindBLAS.cmake:699 (message):
  A required library with BLAS API not found.  Please specify library
  location.
Call Stack (most recent call first):
  external/CoMISo/CMakeLists.txt:40 (find_package)

what i can do?

**Comment by jdumas** [comment]
You need to install a BLAS library (e.g. OpenBLAS) via your package manager (`apt`).

**Comment by Haitham96** [comment]
@jdumas Hi i installed eigen library

**Comment by jdumas** [comment]
You need to install a BLAS library (e.g. OpenBLAS) via your package manager (`apt`).

**Comment by GopherJ** [comment]
> You need to install a BLAS library (e.g. OpenBLAS) via your package manager (`apt`).

You need to install a BLAS library (e.g. OpenBLAS) via your package manager (apt).

**Comment by waveviewer** [comment]
On Ubuntu20.04, I install blas by `sudo apt-get install -y libblas-dev` and it seems to work.

**Comment by alecjacobson** [comment]
Hopefully these are resolved now with all the cmake changes. If not feel free to reopen.
