### ISSUE TITLE
Cmake Download of Eigen references deprecated mirror

### ISSUE THREAD

**Issue by graphitical** [libigl/libigl#1437]
#### Describe your issue

`LibiglDownloadExternal.cmake` attempts to download Eigen from the [deprecated github mirror](https://github.com/eigenteam/eigen-git-mirror.git) instead of [new gitlab repo](https://gitlab.com/libeigen/eigen) referenced on mirror site.

...

#### Check all that apply (change to `[x]`)
- [x] Windows
- [x] Mac OS X
- [x] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by lxwlzr** [comment]
is there a new cmake file out there or should I try to copy-paste it?

**Comment by jdumas** [comment]
Fixed by #1631
