### ISSUE TITLE
segmentation fault shapeup tutorial

### ISSUE THREAD

**Issue by AlbertoMQ** [libigl/libigl#1445]
[groove.zip](https://github.com/libigl/libigl/files/4321109/groove.zip)

I tried modifying the shapeup tutorial to use my own obj file, but am getting a non-informative segfault.
Strangely, shapeup_precomputation does not give a segfault on obj version but does on ply.

`
igl::readOBJ(".../5mmgroove.obj", VQC, FQC);
igl::readPLY(".../5mmgroove.ply", VQC, FQC);
`

**Comment by vfonov** [comment]
in the example 713_ShapeUp the code is expecting a quad mesh, and the 5mm-groove-0.5mm-scan-mm-cropped-2.ply is a triangular mesh.

**Comment by AlbertoMQ** [comment]
Ah sorry, just changed to quad mesh. Still the same issue. Cannot perform operation on either mesh, but with the obj file it at least tries unsuccessfully to do the precomputation (with numerical error)

**Comment by vfonov** [comment]
if you compile in Debug mode, it might print something more useful

**Comment by AlbertoMQ** [comment]
I am unable to compute avg_edge_length on any of the meshes I am passing in. Does this assume the input meshes do not have disconnected elements?
