### ISSUE TITLE
 error: 'Vector' is not a member of 'Eigen'

### ISSUE THREAD

**Issue by Haitham96** [libigl/libigl#1446]
I'm trying to compile my code, it's depend on igl and eigen.
i tried to compile through cmake like the [example project](https://github.com/libigl/libigl-example-project) (igl depend on eigen).  
I got this error:
![image](https://user-images.githubusercontent.com/45899818/76688166-20549200-6633-11ea-906c-b490d1cac551.png)
how i can fix it?

- [x ] Windows

**Comment by jdumas** [comment]
Is this an error in libigl's code or yours? Eigen::Vector isn't something that Eigen provide.

**Comment by Haitham96** [comment]
in my code also Eigen provide's Eigen::vector template on master branch [see this link](https://gitlab.com/libeigen/eigen/-/issues/1835).

**Comment by jdumas** [comment]
Well then you have your answer, you need to use the latest version of Eigen from their master branch if your want to use this alias...

**Comment by Haitham96** [comment]
how i can edit the makefile in the example-project to work these alias and libigl?

**Comment by jdumas** [comment]
I would suggest that you stick with the version of Eigen provided inside libigl for now.

**Comment by Haitham96** [comment]
i downloaded the code from github, and i wanted to run it (i didn't run it).
what do you suggest to do?
