### ISSUE TITLE
Targets not yet defined: igl::common

### ISSUE THREAD

**Issue by philRudd69** [libigl/libigl#1447]
Hi, 

I would like to use libigl with tetgen and cgal from within my ROS node. I am on Ubuntu 18.04 using ROS melodic and catkin_make.
When I try compliling it, I get the following cmake (well technically catkin_make) output: 

```
CMake Error at ros_package_name/libigl/build/libigl-export.cmake:46 (message):
  Some (but not all) targets in this export set were already defined.

  Targets Defined: igl::core

  Targets not yet defined: igl::common

Call Stack (most recent call first):
  ros_package_name/libigl/build/libigl-config.cmake:27 (include)
  /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:76 (find_package)
  ros_package_name/CMakeLists.txt:38 (find_package)
```

What did I do: 

1. I coded my stuff into the **lib-example-project** and it **works**.
Have a look at my CMakeLists.txt:

```cmake
cmake_minimum_required(VERSION 3.1)
project(example)

set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${CMAKE_CURRENT_SOURCE_DIR}/cmake)

message (WARNING "CMAKE_MODULE_PATH is ${CMAKE_MODULE_PATH}")
message (WARNING "CMAKE_CURRENT_SOURCE_DIR is ${CMAKE_CURRENT_SOURCE_DIR}")

# libigl
option(LIBIGL_WITH_OPENGL            "Use OpenGL"         ON)
option(LIBIGL_WITH_OPENGL_GLFW       "Use GLFW"           ON)
option(LIBIGL_WITH_TETGEN       "Use Tetgen"           ON)
option(LIBIGL_WITH_CGAL 	"Use CGAL"	ON)

find_package(LIBIGL REQUIRED QUIET)

include_directories(
	libigl/external/tetgen	
	libigl/external/cgal
)

# Add your project files
file(GLOB SRCFILES *.cpp)
add_executable(${PROJECT_NAME}_bin ${SRCFILES})
target_link_libraries(${PROJECT_NAME}_bin 
	igl::core 
	igl::opengl_glfw 
	igl::tetgen 
	igl::cgal
)
```

2. Then I tried to migrate the stuff into my ROS-node. This means:
3. put the git-repo into a _libigl_ folder in my ROS-package.
4. I made the _build_ directory inside _libigl_ and called `cmake-gui` and set the options `USE_CGAL` and `USE_TETGEN`
5. then I called `make` and `sudo make install`. (**This installation I did also when configuring the lib-example-project**)
6. copied the _cmake_ folder from the libigl-example-project with the _FindLIBIGL.cmake_ file into the ros package folder _ros_package_name_
7. moved the `option` lines from the _libigl-example-project CMakeLists.txt_ into the _FindLIBIGL.cmake_ file to make sure that these options are really used.

My CMakeLists.txt for catkin_make to use looks now like this:
```cmake
cmake_minimum_required(VERSION 3.1)#2.8.3)
project(ros_package_name)

set(LIBIGL_DIR "${CMAKE_CURRENT_SOURCE_DIR}/libigl/build/")
set(LIBIGL_INCLUDE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/libigl/include/")

include(${CMAKE_CURRENT_SOURCE_DIR}/cmake/FindLIBIGL.cmake)

# added some debugging output
message(WARNING ${LIBIGL_INCLUDE_DIR})
# the above shows 
/home/markus/Development/ros/bench-ros/catkin_ws/src/ros_package_name/libigl/include/
message(WARNING "the LIBIGL_DIR is now set to " ${LIBIGL_DIR} " --> about to find packages")
# the above shows 
the LIBIGL_DIR is now set to
  /home/markus/Development/ros/bench-ros/catkin_ws/src/ros_package_name/libigl/build/
  --> about to find packages


find_package(
	catkin REQUIRED COMPONENTS 
	dynamic_reconfigure 
	roscpp 
	rosgraph_msgs 
	std_msgs 
	geometry_msgs
	pcl_ros
	message_generation
	sensor_msgs
	geometry_msgs
	PCL REQUIRED
	LIBIGL REQUIRED core common
)


add_message_files(
  FILES
  ....
)

generate_messages(
  DEPENDENCIES
  ....
)

generate_dynamic_reconfigure_options(
  cfg/ros_package_name.cfg
)

catkin_package(
  INCLUDE_DIRS include
  CATKIN_DEPENDS 
  	dynamic_reconfigure 
	roscpp 
	rosgraph_msgs 
	std_msgs 
	sensor_msgs 
	pcl_ros 
	message_runtime 
)

include_directories(include 
	${catkin_INCLUDE_DIRS} 
	${PCL_INCLUDE_DIRS} 
	${CMAKE_CURRENT_SOURCE_DIR}/libigl/external/tetgen	
	${CMAKE_CURRENT_SOURCE_DIR}/libigl/external/cgal
	)

add_executable(ros_node src/nodes/ros_node.cpp)
target_link_libraries(ros_node 
	${catkin_LIBRARIES} 
	igl::core igl::common
	igl::cgal
	igl::tetgen
	)

add_dependencies(ros_node 
	ros_package_name_gencfg 
	ros_package_name_generate_messages_cpp)

install(DIRECTORY include/${PROJECT_NAME}/
  DESTINATION ${CATKIN_PACKAGE_INCLUDE_DESTINATION}
  FILES_MATCHING PATTERN "*.h" 
)

install(TARGETS ros_node
  RUNTIME DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION}
  LIBRARY DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION}
  ARCHIVE DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION}
)

install(DIRECTORY launch
  DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}
)
```

As far as I understand (cmake rookie), the cmake procedure that now takes place goes as follows:

1. catkin is run (basically creates some directories and calls cmake and make for the user)
2. my _CMakeLists.txt_ is run
2.1. the `include` command is run and calls _FindLIBIGL.cmake_
2.2. this should set the `LIBIGL_INCLUDE_DIR` automatically, but as I set this variable already manually in _CMakeLists.txt_ it is not altered. but my `option` flags are recognized.
3. _FindLIBIGL.cmake_ calls _/libigl/cmake/libigl.cmake_
3.1 **I guess this is where the targets `igl::core` and `igl::tetgen` etc. are created, because I get this output:**
```
-- Creating target: igl::core (igl)
-- Using header-only CGAL
-- Targetting Unix Makefiles
-- Using /usr/bin/c++ compiler.
-- __cplusplus is 201402
--   --> Do not link with Boost.Thread
-- Boost version: 1.65.1
-- Boost include dirs: /usr/include
-- Boost libraries:    
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   thread
--   system
--   chrono
--   date_time
--   atomic
-- Using gcc version 4 or later. Adding -frounding-math
-- Creating target: igl::cgal (igl_cgal)
-- Creating target: igl::comiso (igl_comiso)
-- Creating target: igl::embree (igl_embree)
-- Creating target: igl::opengl (igl_opengl)
-- Creating target: igl::opengl_glfw (igl_opengl_glfw)
-- Using X11 for window creation
-- Creating target: igl::opengl_glfw_imgui (igl_opengl_glfw_imgui)
-- Creating target: igl::png (igl_png)
-- Creating target: igl::tetgen (igl_tetgen)
-- Creating target: igl::triangle (igl_triangle)
-- Creating target: igl::predicates (igl_predicates)
-- Creating target: igl::xml (igl_xml)
```
4. Then the `LIBIGL` package is found by `find_package()`
5. Then _libigl/build/libigl-export.cmake_ is called, I print out the `EXPECTED TARGES` (I added a message command to this libigl-export.cmake file) and then the previously mentioned error occurs:
```
CMake Warning at ros_package_name/libigl/build/libigl-export.cmake:35 (message):
  THE EXPECTED TARGES ARE igl::core;igl::common
Call Stack (most recent call first):
  ros_package_name/libigl/build/libigl-config.cmake:27 (include)
  /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:76 (find_package)
  ros_package_name/CMakeLists.txt:38 (find_package)


CMake Error at ros_package_name/libigl/build/libigl-export.cmake:46 (message):
  Some (but not all) targets in this export set were already defined.

  Targets Defined: igl::core

  Targets not yet defined: igl::common

Call Stack (most recent call first):
  ros_package_name/libigl/build/libigl-config.cmake:27 (include)
  /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:76 (find_package)
  ros_package_name/CMakeLists.txt:38 (find_package)
```
**QUESTION**
Why is the `igl::common` target not defined? What do I have to do to get this running?

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] I have tried the `dev` branch and the problem persists

**Comment by philRudd69** [comment]
> tree -I 'build|build.new|tutorial|external|*.h|*.cpp|*.launch|docs' 
.
├── cfg
│   └── ros_package_name.cfg
├── cmake
│   └── FindLIBIGL.cmake
├── CMakeLists.txt
├── include
│   └── ros_package_name
│       └── impl
├── launch
├── libigl
│   ├── cmake
│   │   ├── CXXFeatures.cmake
│   │   ├── DownloadProject.cmake
│   │   ├── DownloadProject.CMakeLists.cmake.in
│   │   ├── FindCORK.cmake
│   │   ├── FindMATLAB.cmake
│   │   ├── FindMOSEK.cmake
│   │   ├── libigl.cmake
│   │   ├── libigl-config.cmake (copy).in
│   │   ├── libigl-config.cmake.in
│   │   ├── libigl (copy).cmake
│   │   ├── LibiglDownloadExternal.cmake
│   │   └── LibiglWindows.cmake
│   ├── CMakeLists.txt
│   ├── include
│   │   └── igl
│   │       ├── copyleft
│   │       │   ├── cgal
│   │       │   │   └── CGAL_includes.hpp
│   │       │   ├── comiso
│   │       │   ├── cork
│   │       │   ├── opengl2
│   │       │   ├── README.md
│   │       │   └── tetgen
│   │       │       └── README
│   │       ├── embree
│   │       ├── IO
│   │       ├── matlab
│   │       ├── mosek
│   │       ├── opengl
│   │       │   └── glfw
│   │       │       └── imgui
│   │       ├── png
│   │       ├── predicates
│   │       ├── raytri.c
│   │       ├── Singular_Value_Decomposition_Givens_QR_Factorization_Kernel.hpp
│   │       ├── Singular_Value_Decomposition_Jacobi_Conjugation_Kernel.hpp
│   │       ├── Singular_Value_Decomposition_Kernel_Declarations.hpp
│   │       ├── Singular_Value_Decomposition_Main_Kernel_Body.hpp
│   │       ├── Singular_Value_Decomposition_Preamble.hpp
│   │       ├── triangle
│   │       └── xml
│   │           └── serialization_test.skip
│   ├── LICENSE.GPL
│   ├── LICENSE.MPL2
│   ├── python
│   │   ├── CMakeLists.txt
│   │   ├── iglhelpers.py
│   │   ├── matlab
│   │   │   ├── example1.m
│   │   │   ├── example2.m
│   │   │   ├── launch_viewer.m
│   │   │   ├── m2p.m
│   │   │   └── p2m.m
│   │   ├── modules
│   │   │   └── copyleft
│   │   ├── py_igl
│   │   │   ├── copyleft
│   │   │   │   ├── cgal
│   │   │   │   ├── comiso
│   │   │   │   └── tetgen
│   │   │   ├── embree
│   │   │   ├── png
│   │   │   └── triangle
│   │   ├── pyigl.so
│   │   ├── scripts
│   │   │   ├── basic_function.mako
│   │   │   ├── generate_bindings.py
│   │   │   ├── generate_docstrings.py
│   │   │   ├── parser.py
│   │   │   ├── py_igl.mako
│   │   │   └── python_shared.mako
│   │   ├── setup.py
│   │   └── tcpviewer.py
│   ├── README.md
│   └── tests
│       ├── CMakeLists.txt
│       ├── data
│       │   ├── 3holes-miq-FUV.dmat
│       │   ├── 3holes-miq-UV.dmat
│       │   ├── 3holes.off
│       │   ├── annulus.obj
│       │   ├── boolean_minus_test_cube.obj
│       │   ├── boolean_minus_test_green.obj
│       │   ├── bunny.off
│       │   ├── cheburashka.off
│       │   ├── cube.obj
│       │   ├── cube.off
│       │   ├── cube_with_fold.ply
│       │   ├── decimated-knight-matlab-active-set.dmat
│       │   ├── decimated-knight.mesh
│       │   ├── decimated-knight.obj
│       │   ├── decimated-knight.tgf
│       │   ├── degenerated.obj
│       │   ├── duplicated_faces_F.dmat
│       │   ├── duplicated_faces_N1.dmat
│       │   ├── duplicated_faces_N2.dmat
│       │   ├── duplicated_faces_V.dmat
│       │   ├── elephant.off
│       │   ├── extrusion.obj
│       │   ├── hemisphere.obj
│       │   ├── marching_tets_input.mesh
│       │   ├── marching_tets_output.obj
│       │   ├── marching_tets_scalars.dmat
│       │   ├── README.md
│       │   ├── sliver_tet.ply
│       │   ├── tet.obj
│       │   ├── TinyTorus.obj
│       │   ├── truck.obj
│       │   └── two-boxes-bad-self-union.ply
│       └── include
│           └── igl
│               ├── copyleft
│               │   ├── boolean
│               │   ├── cgal
│               │   ├── comiso
│               │   └── tetgen
│               ├── embree
│               ├── mosek
│               └── predicates
├── LICENSE
├── mkdocs.yml
├── msg
│   └── foo.msg
├── package.xml
├── src
│   └── nodes
└── statick_config
    └── rsc
        ├── cccc.opt
        ├── config.yaml
        ├── exceptions.yaml
        └── profile.yaml

**Comment by alecjacobson** [comment]
I'm hoping this is fixed or irrelevant with the cmake changes. Please reopen if it's still an issue.
