### ISSUE TITLE
Crash when using `unproject_onto_mesh`

### ISSUE THREAD

**Issue by lukkio88** [libigl/libigl#1448]
Hi,

I have this simple app
```
#include <igl/readOBJ.h>
#include <igl/unproject_onto_mesh.h>
#include <Eigen/Dense>

using std::string;
using Eigen::MatrixXi;
using Eigen::MatrixXd;
using std::ofstream;
using std::cout;
using std::endl;

int main(int argc, char *argv[])
{

    string meshFilename(argv[1]);

    MatrixXi faceList;
    MatrixXd vertexList;
    igl::readOBJ(meshFilename, vertexList, faceList);

    Eigen::Matrix4f model;
    Eigen::Matrix4f projection;
    Eigen::Vector4f viewport;
    Eigen::Vector2f screenCoordinates;
    int faceId;
    Eigen::Vector2f baricentricCoordinate;

    model <<
    -0.197834, -0.783464, -0.589105, -27.707,
    -0.239861, 0.621405, -0.74587, -33.58,
    0.950436, -0.00625538, -0.310858, -48.7152,
    0, 0, 0, 1;

    projection <<
    0.07189, 0, -0.000333553, 0,
    0, 0.0479267, 2.74298e-05, 0,
    0, 0, -1, -248.452,
    0, 0, -1, 0;

    viewport << -1728.58, -2591.93, 1727.42, 2592.07;

    screenCoordinates << 1885.0, 1284.0;

    igl::unproject_onto_mesh(screenCoordinates, model, projection, viewport, vertexList, faceList,
                        faceId, baricentricCoordinate);

    return 0;
}
```

But I get an error that I can quite understand:

```
libigl/external/eigen/Eigen/src/Core/PlainObjectBase.h:241: void Eigen::PlainObjectBase<Derived>::resize(Eigen::PlainObjectBase<Derived>::Index, Eigen::PlainObjectBase<Derived>::Index) [with Derived = Eigen::Matrix<double, 1, 3>; Eigen::PlainObjectBase<Derived>::Index = long int]: Assertion `(!(RowsAtCompileTime!=Dynamic) || (nbRows==RowsAtCompileTime)) && (!(ColsAtCompileTime!=Dynamic) || (nbCols==ColsAtCompileTime)) && (!(RowsAtCompileTime==Dynamic && MaxRowsAtCompileTime!=Dynamic) || (nbRows<=MaxRowsAtCompileTime)) && (!(ColsAtCompileTime==Dynamic && MaxColsAtCompileTime!=Dynamic) || (nbCols<=MaxColsAtCompileTime)) && nbRows>=0 && nbCols>=0 && "Invalid sizes when resizing a matrix or array."' failed.

```

I cannot understand what the issue is, because all the matrices I've loaded seem fine and correct.
Can you help?

...

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by lukkio88** [comment]
From the debugging mode in my IDE I can see in the call stack that the issue is with my `baricentricCoordinate` variable. There's a resize done at some point that doesn't work. I've tried to change the type to `Eigen::Vector3f` (by doing copy paste from one of your examples) but It doesn't work either.

**Comment by lukkio88** [comment]
I think I tracked at least the variable causing the issue (by looking at the call stack)... it's the `screenCoordinates` variable. Not sure what the issue is, but it seems like there's a resize at some point that causes the issue.

**Comment by jdumas** [comment]
Can you please
1. Try with the header-only version of libigl as well as with the static version.
2. Post the result of the call stack.
3. Try with the latest `dev` branch.

**Comment by lukkio88** [comment]
How do I get the header only version?

**Comment by jdumas** [comment]
Toggle the CMake option `LIBIGL_USE_STATIC_LIBRARY`

**Comment by lukkio88** [comment]
You mean in _my CMake project?_ or in when I build libigl?

**Comment by jdumas** [comment]
Change the option in your CMakeCache.txt, using `ccmake` or `cmake-gui`.

**Comment by lukkio88** [comment]
Can you please be more elaborate? There's no `LIBIGL_USE_STATIC_LIBRARY" in my `CMakeCache.txt` (i.e. the one generated using the `CMakeLists.txt` I'm using to compile the source code I posted)

**Comment by jdumas** [comment]
Are you sure? Can you paste the output of the command:
```
> cd build/
> grep LIBIGL_USE_STATIC_LIBRARY CMakeCache.txt 
LIBIGL_USE_STATIC_LIBRARY:BOOL=ON
```

**Comment by lukkio88** [comment]
I literally get nothing if I run the command you just said.

```
>
>cd cmake-debug-build/
>grep LIBIGL_USE_STATIC_LIBRARY CMakeCache.txt
>
```

**Comment by lukkio88** [comment]
The error I get instead when I try to use the `dev` branch:

```
CMake Error at CMakeLists.txt:48 (message):
  Python binding are in the process of being redone.  Please use the master
  branch or refer to
  https://github.com/geometryprocessing/libigl-python-bindings for the
  developement version or https://anaconda.org/conda-forge/igl for the stable
  version.


-- Configuring incomplete, errors occurred!
See also "/home/libigl/build/CMakeFiles/CMakeOutput.log".
See also "/home/libigl/build/CMakeFiles/CMakeError.log".
```

**Comment by jdumas** [comment]
Please try to delete your build folder and recompile by calling `cmake -DLIBIGL_USE_STATIC_LIBRARY=OFF ..`.

**Comment by lukkio88** [comment]
Which branch? `master` or `dev`?

**Comment by jdumas** [comment]
`dev`

**Comment by lukkio88** [comment]
Ok, I built from dev, with the option of static libraries disabled. I still get the same error at the beginning of my question.

**Comment by lukkio88** [comment]
Just an update on this, I've also tried to use the combination of

```
igl::unproject_ray(screenCoordinates, model, projection, viewport, s, direction);
igl::ray_mesh_intersect(s,direction,vertexList,faceList,hits);
```

Since I believe they should give me the same result as `unproject_onto_mesh`, I still get the same error as above. It crashes in `ray_mesh_intersect.cpp`, more specifically line 39

```
RowVector3d v0 = V.row(F(f,0)).template cast<double>();
```

I don't understand why these casts are problematic, can you please advice me in what to do? I would really avoid writing these functions from scratch since they're already there in the library.

**Comment by jdumas** [comment]
Just to be sure: are you compiling this code in Debug mode? Looking at the source code it looks like a discrepancy between row/column vector, i.e. a Vector3f that would be a RowVector3f and vice-versa.

**Comment by lukkio88** [comment]
Yes, it is in Debug mode. All the inputs of `unproject_onto_mesh` seem to be `Vector2f` or `Vector3f`. My face and vertex lists are initialized by `igl::readOBJ`, so whatever those calls give me is what I'm passing.

**Comment by lukkio88** [comment]
Hi again,

I realize I'm probably being annoying but I really like to get some form of help/update on this topic, especially because I'm using your library quite extensively lately.

As mentioned earlier in my messages there seem to be an issue with the lines `38-41` in `ray_mesh_intersect.cpp`

Namely the following assignment:

// Should be but can't be const
```
RowVector3d v0 = V.row(F(f,0)).template cast<double>();
RowVector3d v1 = V.row(F(f,1)).template cast<double>();
RowVector3d v2 = V.row(F(f,2)).template cast<double>();
```

The function is relatively short so I created my own version

```
inline bool my_ray_mesh_intersect(
        const Eigen::Vector3d & s,
        const Eigen::Vector3d & dir,
        const Eigen::MatrixXd & V,
        const Eigen::MatrixXi & F,
        std::vector<igl::Hit> & hits)
{
    using namespace Eigen;
    using namespace std;
    // Should be but can't be const
    Vector3d s_d = s.template cast<double>();
    Vector3d dir_d = dir.template cast<double>();
    hits.clear();
    hits.reserve(F.rows());

    // loop over all triangles
    for(int f = 0;f<F.rows();f++)
    {
        // Should be but can't be const
        Eigen::RowVector3d v0(V(F(f,0),0),V(F(f,0),1),V(F(f,0),2));
        Eigen::RowVector3d v1(V(F(f,1),0),V(F(f,1),1),V(F(f,1),2));
        Eigen::RowVector3d v2(V(F(f,2),0),V(F(f,2),1),V(F(f,2),2));
        // shoot ray, record hit
        double t,u,v;
        if(intersect_triangle1(
                s_d.data(), dir_d.data(), v0.data(), v1.data(), v2.data(), &t, &u, &v) &&
           t>0)
        {
            hits.push_back({(int)f,(int)-1,(float)u,(float)v,(float)t});
        }
    }
    // Sort hits based on distance
    std::sort(
            hits.begin(),
            hits.end(),
            [](const igl::Hit & a, const igl::Hit & b)->bool{ return a.t < b.t;});
    return hits.size() > 0;
}
```

The main change are the three lines

```
Eigen::RowVector3d v0(V(F(f,0),0),V(F(f,0),1),V(F(f,0),2));
Eigen::RowVector3d v1(V(F(f,1),0),V(F(f,1),1),V(F(f,1),2));
Eigen::RowVector3d v2(V(F(f,2),0),V(F(f,2),1),V(F(f,2),2));
```

And this version doesn't crash.

I've also changed the input types a bit mostly to avoid the casting, I'm still not 100% sure if the issue is the casting or the constructor of "RowVector3d" somehow.

Another attempt I've also tried is to remove your eigen directory and replace it with the latest version. I was still getting the same issue though, so that didn't work.

Given that both my example is very simple and I can't really figure there's an issue with my input, I think is safe to assume there's a bug in the library.

Can you please:
1. Confirm if I'm talking no sense?
2. If the answer to 1. is yes what am I doing wrong?
3. If the answer to 1. is no can you please fix this?

Thank you.

**Comment by jdumas** [comment]
I think the issue is indeed in the libigl source code. It should be using a RowVector3f where it's using a Vector3f, or vice-versa. I don't really have a lot of time to investigate more deeply these days, so I suggest you stick with your own implementation in the meantime. The ideal solution would be to fix libigl's implementation and add a unit test of course.

**Comment by lukkio88** [comment]
Ok, for now I'll stick with my implementation then.
Let me know if and when you fix it.

**Comment by alecjacobson** [comment]
Seems maybe this got fixed. I can't reproduce the issue in the original post (I also don't have whatever mesh it was crashing on). Feel free to reopen if it's still an issue (please include the mesh).
