### ISSUE TITLE
Implementations query.

### ISSUE THREAD

**Issue by csverma** [libigl/libigl#145]
Hello ,
There are few papers from prof. Olga i.e

Least Square Meshes
Differential Coordinates ...
Linear Rotation Invariant Coordinates for Meshes

Are there any implementation of these papers in libigl ?

csv

**Comment by alecjacobson** [comment]
"Least Squares Meshes" and "Differential Coordinates" are essentially just applying the cotangent Laplacian `igl::cotmatrix` to different (or not even that different) quantities. This Laplacian will get you 90% of the way there. I think there are details in each paper like sampling for LSM and handle descriptions in DC that maybe need to be added on top.

**Comment by wguo68** [comment]
How to implement rotation invariant Laplacian differential coordinates in paper "Subspace Gradient Domain Mesh Deformation". The gradient of this kind of laplacian term is hard to compute mannually.
