### ISSUE TITLE
Closest point to a line in a mesh

### ISSUE THREAD

**Issue by lukkio88** [libigl/libigl#1454]
Hi,

I've actually implemented this functionality already since I couldn't find an equivalent in the library, but I want to double check with you.
Do you have a function/api that given some description of a line, say `source` and `direction` and a triangle whose vertices are `vertex0, vertex1, vertex2,` returns the baricentric coordinate corresponding to the closest point of the triangle to the line (assuming they don't intersect).

If not is there a function that computes the distance of a given line to a given *segment* whose endpoints are given.

If yes do you have a more general function that given a mesh and line computes point/points on the mesh which are closest to the mesh?

Thank you.

...

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by alecjacobson** [comment]
igl::copyleft::cgal::segment_segment_squared_distance is the closest

>

**Comment by lukkio88** [comment]
So it's not native on libigl, it relies on cgal.
