### ISSUE TITLE
Non rigid alignment?

### ISSUE THREAD

**Issue by MotivaCG** [libigl/libigl#1456]
Question:

In the demo 718_IterativeClosestPoint_bin found in the dev branch, you can test a rigid alignment of two meshes.

Is there any chance to make something similar using the same iterative approach to get a non rigid alignment? Obviously the intention is to match two slightly different meshes with different topology.

Thank you in advance.

**Comment by alecjacobson** [comment]
There are no plans. Would be happy to merge a pr if someone else did it.
