### ISSUE TITLE
About cmake failed to download the necessary dependency source code ExternalProject_Add

### ISSUE THREAD

**Issue by hrq0106** [libigl/libigl#1457]
#### Describe your issue

After I use git to get the source code of libigl, it takes a long time to cmake, and I always get an error here. I want to ask why? Or can libigl developers think about downloading these dependencies into libigl's source code in advance?
![QQ图片20200325222731](https://user-images.githubusercontent.com/48640195/77547280-f418fb00-6ee7-11ea-9435-3ef10df526dc.png)

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [x] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by jdumas** [comment]
Hmm did you try the `dev` branch as well? Can you also paste the content of the `CMakeOutput.log` and `CMakeError.log`?

**Comment by hrq0106** [comment]
Sorry, I haven't tried the dev branch yet, but is the dev branch useful? But I only have one log file, which is the CMakeOutput.log file. I'll send you this file for a look. This problem has troubled me for many days. thank.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jérémie Dumas"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月25日(星期三) 晚上11:00
收件人:&nbsp;"libigl/libigl"<libigl@noreply.github.com&gt;;
抄送:&nbsp;"阿白"<1256812704@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [libigl/libigl] About cmake failed to download the necessary dependency source code ExternalProject_Add (#1457)





 
Hmm did you try the dev branch as well? Can you also paste the content of the CMakeOutput.log and CMakeError.log?

**Comment by jdumas** [comment]
Yes please try the dev branch. If that doesn't work, paste your `CMakeOutput.log` file here.

**Comment by hrq0106** [comment]
Sorry, I can't seem to download the source code of the dev branch through git bash. As far as I know, many people around me cannot use libigl, an excellent computational geometry library, for the same reasons as me. I would like to ask if you can put the libigl dependencies in the source code in advance, instead of downloading these dependencies through cmake. Thank you for your help.

‍






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jérémie Dumas"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月26日(星期四) 中午1:29
收件人:&nbsp;"libigl/libigl"<libigl@noreply.github.com&gt;;
抄送:&nbsp;"阿白"<1256812704@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [libigl/libigl] About cmake failed to download the necessary dependency source code ExternalProject_Add (#1457)





 
Yes please try the dev branch. If that doesn't work, paste your CMakeOutput.log file here.

**Comment by hrq0106** [comment]
Hello, I re-downloaded the source code from the dev branch with git and tried to compile with cmake, but this still happened. This frustrates me, libigl is a great computational geometry library, but why not try to put all the dependencies in the libigl source code? It is really difficult to download these dependencies when cmake.







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jérémie Dumas"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月26日(星期四) 中午1:29
收件人:&nbsp;"libigl/libigl"<libigl@noreply.github.com&gt;;
抄送:&nbsp;"阿白"<1256812704@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [libigl/libigl] About cmake failed to download the necessary dependency source code ExternalProject_Add (#1457)





 
Yes please try the dev branch. If that doesn't work, paste your CMakeOutput.log file here.

**Comment by jdumas** [comment]
Please post the content of your `CMakeOutput.log` and we'll see what we can do.

**Comment by hrq0106** [comment]
[CMakeOutput.log](https://github.com/libigl/libigl/files/4391363/CMakeOutput.log)

**Comment by jdumas** [comment]
Hmm that doesn't tell us anything. Do you have any log/error files under `external/.cache/eigen/CMakeFiles` by any chance?

**Comment by hrq0106** [comment]
OK, I guess this is what you want. Does have CMakeLists.txt
[CMakeLists.txt](https://github.com/libigl/libigl/files/4393202/CMakeLists.txt)

**Comment by jdumas** [comment]
Hm no that's not really what I asked for.

**Comment by xenomarz** [comment]
This is also happening to me.

**Comment by hrq0106** [comment]
Sorry, I found the log file again. There is a CMakeOutput.log file under the folder path you said. I think what you need is this?
[CMakeOutput.log](https://github.com/libigl/libigl/files/4396589/CMakeOutput.log)

**Comment by lxwlzr** [comment]
same issue on Windows 10, Cmake 3.17 and VS 15 2017 - any hints?

**Comment by lxwlzr** [comment]
I get the same error code - trying to build in Cmake:

CMake Error at C:/Windows/System32/libigl/cmake/DownloadProject.cmake:171 (message):
  CMake step for eigen failed: 1
Call Stack (most recent call first):
  C:/Windows/System32/libigl/cmake/LibiglDownloadExternal.cmake:25 (download_project)
  C:/Windows/System32/libigl/cmake/LibiglDownloadExternal.cmake:37 (igl_download_project_aux)
  C:/Windows/System32/libigl/cmake/LibiglDownloadExternal.cmake:69 (igl_download_project)
  C:/Windows/System32/libigl/cmake/libigl.cmake:111 (igl_download_eigen)
  cmake/FindLIBIGL.cmake:33 (include)
  CMakeLists.txt:17 (find_package)

**Comment by mezzomax** [comment]
I get the same error too. How can I solve it?


Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
MSVC -> forcing use of dynamically-linked runtime.
CMake Error at C:/Program Files/CMake/share/cmake-3.17/Modules/ExternalProject.cmake:2454 (message):

  error: could not find git for clone of eigen-download
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.17/Modules/ExternalProject.cmake:3267 (_ep_add_download_command)
  CMakeLists.txt:9 (ExternalProject_Add)



CMake Error at C:/local/libigl/cmake/DownloadProject.cmake:171 (message):
  CMake step for eigen failed: 1
Call Stack (most recent call first):
  C:/local/libigl/cmake/LibiglDownloadExternal.cmake:25 (download_project)
  C:/local/libigl/cmake/LibiglDownloadExternal.cmake:37 (igl_download_project_aux)
  C:/local/libigl/cmake/LibiglDownloadExternal.cmake:69 (igl_download_project)
  C:/local/libigl/cmake/libigl.cmake:111 (igl_download_eigen)
  CMakeLists.txt:12 (include)


Configuring incomplete, errors occurred!
See also "C:/local/libigl/tutorial/build/CMakeFiles/CMakeOutput.log".

**Comment by jdumas** [comment]
Can you give a bit more details? What's the content of `C:/local/libigl/tutorial/build/CMakeFiles/CMakeOutput.log` ?

**Comment by jdumas** [comment]
From the error message it looks like you don't have git installed on your computer, or that CMake cannot find git. Please make sure that the `git` executable is in your `PATH`.

**Comment by mezzomax** [comment]
It works! Many thanks!

**Comment by hrq0106** [comment]
How did it succeed? Is it convenient for you to write a tutorial? thank------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;mian&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月14日(星期二) 上午8:19
收件人:&nbsp;&quot;libigl/libigl&quot;<libigl@noreply.github.com&gt;;
抄送:&nbsp;&quot;Porsche0106&quot;<1256812704@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [libigl/libigl] About cmake failed to download the necessary dependency source code ExternalProject_Add (#1457)

**Comment by mezzomax** [comment]
I just download the git from the website and install it. Then use cmake to configure and generate as usual

**Comment by hrq0106** [comment]
How many mb did you download from git?------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;mian&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月14日(星期二) 中午11:01
收件人:&nbsp;&quot;libigl/libigl&quot;<libigl@noreply.github.com&gt;;
抄送:&nbsp;&quot;Porsche0106&quot;<1256812704@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [libigl/libigl] About cmake failed to download the necessary dependency source code ExternalProject_Add (#1457)

**Comment by mezzomax** [comment]
I download git 2.27.0 (45.8MB) from this website https://git-scm.com/downloads. It is a .exe file. Just download and install it. Then run you cmake.

**Comment by trick-bat** [comment]
I get the two errors too, and I solved the second one through adding the git executable into my PATH.

However, I don't know how to solve the first one raised in this issue.


CMake Error at cmake/DownloadProject.cmake:179 (message):
  **Build step for eigen failed: 1**
Call Stack (most recent call first):
  cmake/LibiglDownloadExternal.cmake:25 (download_project)
  cmake/LibiglDownloadExternal.cmake:37 (igl_download_project_aux)
  cmake/LibiglDownloadExternal.cmake:69 (igl_download_project)
  cmake/libigl.cmake:111 (igl_download_eigen)
  CMakeLists.txt:59 (include)

**Comment by SchweitzerGAO** [comment]
Have anyone solved the problem that @trick-bat mentioned? I have the same problem on my Win10 PC and I have made sure that git works well on it

**Comment by alecjacobson** [comment]
Hoping this is all fixed with the changes to cmake. Please reopen if still needed.

**Comment by 3417725275** [comment]
I get the same error too, and I had make sure that the git executable is in my PATH.

Creating target: igl::core (igl_core)
Third-party: creating target 'Eigen3::Eigen'
Microsoft(R) 生成引擎版本 4.8.9037.0
[Microsoft .NET Framework 版本 4.0.30319.42000]
版权所有 (C) Microsoft Corporation。保留所有权利。

  Checking Build System
  Creating directories for 'eigen-populate'
  Building Custom Rule D:/git/converters/libigl/build/_deps/eigen-subbuild/CMakeLists.txt
  Performing download step (git clone) for 'eigen-populate'
  Cloning into 'eigen-src'...
CUSTOMBUILD : error : RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly before end of the underlying stream [D:\git\converters\libigl\build\_deps\eigen-subbuild\eigen-populate.vcxproj]
CUSTOMBUILD : error : 16684 bytes of body are still expected [D:\git\converters\libigl\build\_deps\eigen-subbuild\eigen-populate.vcxproj]
  fetch-pack: unexpected disconnect while reading sideband packet
  fatal: early EOF
  fatal: fetch-pack: invalid index-pack output
  Cloning into 'eigen-src'...
CUSTOMBUILD : error : RPC failed; curl 56 OpenSSL SSL_read: Connection was reset, errno 10054 [D:\git\converters\libigl\build\_deps\eigen-subbuild\eigen-populate.vcxproj]
CUSTOMBUILD : error : 10720 bytes of body are still expected [D:\git\converters\libigl\build\_deps\eigen-subbuild\eigen-populate.vcxproj]
  fetch-pack: unexpected disconnect while reading sideband packet
  fatal: early EOF
  fatal: fetch-pack: invalid index-pack output
  Cloning into 'eigen-src'...
CUSTOMBUILD : error : RPC failed; curl 56 OpenSSL SSL_read: Connection was reset, errno 10054 [D:\git\converters\libigl\build\_deps\eigen-subbuild\eigen-populate.vcxproj]
CUSTOMBUILD : error : 28248 bytes of body are still expected [D:\git\converters\libigl\build\_deps\eigen-subbuild\eigen-populate.vcxproj]
  fetch-pack: unexpected disconnect while reading sideband packet
  fatal: early EOF
  fatal: fetch-pack: invalid index-pack output
  -- Had to git clone more than once: 3 times.
  CMake Error at eigen-subbuild/eigen-populate-prefix/tmp/eigen-populate-gitclone.cmake:39 (message):
    Failed to clone repository: 'https://gitlab.com/libeigen/eigen.git'
  
  

CMake Error at E:/Program Files/CMake/share/cmake-3.24/Modules/FetchContent.cmake:1604 (message):
  Build step for eigen failed: 1
Call Stack (most recent call first):
  E:/Program Files/CMake/share/cmake-3.24/Modules/FetchContent.cmake:1744:EVAL:2 (__FetchContent_directPopulate)
  E:/Program Files/CMake/share/cmake-3.24/Modules/FetchContent.cmake:1744 (cmake_language)
  cmake/recipes/external/eigen.cmake:16 (FetchContent_Populate)
  cmake/igl/modules/core.cmake:23 (include)
  cmake/igl/igl_include.cmake:32 (include)
  cmake/igl/igl_include.cmake:54 (_igl_include_full)
  cmake/libigl.cmake:15 (igl_include)
  CMakeLists.txt:142 (include)
