### ISSUE TITLE
Rendering without a main window

### ISSUE THREAD

**Issue by aschier** [libigl/libigl#1458]
#### Describe your issue

Can libigl be used to render a scene without opening a window to render into a PNG file?

I created a simple program to render mesh previews, but currently it still opens a window for a second during rendering.
It would be useful when I could use the Viewer without opening a window at all.

**Minimal example code:**

```cpp
Eigen::MatrixXd V;
Eigen::MatrixXi F;

igl::readOBJ("test.obj", V, F);

igl::opengl::glfw::Viewer viewer;
viewer.core().is_animating = true;
viewer.data().set_mesh(V, F);

Eigen::Matrix<unsigned char,Eigen::Dynamic,Eigen::Dynamic> R(1024, 1024);
Eigen::Matrix<unsigned char,Eigen::Dynamic,Eigen::Dynamic> G(1024, 1024);
Eigen::Matrix<unsigned char,Eigen::Dynamic,Eigen::Dynamic> B(1024, 1024);
Eigen::Matrix<unsigned char,Eigen::Dynamic,Eigen::Dynamic> A(1024, 1024);

viewer.callback_post_draw = [&](igl::opengl::glfw::Viewer &viewer) {
	viewer.core().draw_buffer(viewer.data(), false, R, G, B, A);
	igl::png::writePNG(R, G, B, A, output_filename);
	return true;
};

viewer.core().camera_zoom *= 1.4;

viewer.launch_init();
viewer.launch_rendering(false);
```

Is there a better way to render a scene in the background?

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [x] I have tried the `dev` branch and the problem persists

**Comment by alecjacobson** [comment]
Take a look at igl::opengl::glfw::background_window

>

**Comment by aschier** [comment]
I tried

```cpp
igl::opengl::glfw::background_window(viewer.window);
glfwMakeContextCurrent(viewer.window);
for(int i=0;i<viewer.core_list.size(); i++)
{
  viewer.core_list[i].align_camera_center(viewer.data().V,viewer.data().F);
}
viewer.init();
viewer.launch_rendering(false);
```

trying to mimic `launch_init`, but it only renders a transparent image.
Do you have any hint what I may be missing?

**Comment by alecjacobson** [comment]
I can't take a look immediately, but maybe you need to trigger a draw call
or something to do with reshaping...

>

**Comment by jdumas** [comment]
Hmm I remember I made some changes in a fork of mine in order to achieve this functionality. See [this branch](https://github.com/jdumas/libigl/blob/jdumas/serialization/include/igl/opengl/glfw/Viewer.h) (`jdumas/serialization`), and in particular the new `hidden` option. To take a screenshot I would then do the following:

```cpp
	// Offscreen rendering context
	viewer.launch_init(false, false, true, "", args.width, args.height);

	// Allocate temporary buffers
	Eigen::Matrix<unsigned char,Eigen::Dynamic,Eigen::Dynamic> R(args.width, args.height);
	Eigen::Matrix<unsigned char,Eigen::Dynamic,Eigen::Dynamic> G(args.width, args.height);
	Eigen::Matrix<unsigned char,Eigen::Dynamic,Eigen::Dynamic> B(args.width, args.height);
	Eigen::Matrix<unsigned char,Eigen::Dynamic,Eigen::Dynamic> A(args.width, args.height);

	// Draw the scene in the buffers
	viewer.core().align_camera_center(VB);
	viewer.core().draw_buffer(viewer.data(),true,R,G,B,A);

	// Save it to a PNG
	igl::png::writePNG(R,G,B,A,args.output);
```

We should probably have a tutorial or smth for offline rendering, since it's such a useful feature (it's not truly headless since you still need to have a running X server though).

**Comment by alecjacobson** [comment]
We figured out a way to do it without the x server. But it's also a but
complicated to set up (on server side).

**Comment by aschier** [comment]
Requiring a X server would not be a problem for me at the moment.

I tried to extract the modified launch_init function into a HiddenViewer class to stick with the official libigl branches, but this seems to require a few more changes so I will have a closer look tomorrow.

**Comment by jdumas** [comment]
I remember back in 2017 I tried to make the libigl viewer work with OSMesa for headless rendering, but I had some trouble with the GLFW setup. Maybe it's possible to do so now, that'd be cool.

@aschier you can try to use my fork directly see if if works. Porting the changes would be nice but might require some extra work.

**Comment by aschier** [comment]
@jdumas 

I created a HiddenViewer class with `launch_init` from current libigl plus this commit https://github.com/jdumas/libigl/commit/03008a0e319cea6ed3d25d40d39b8222341ce055 and it works fine.

What do you think about merging this commit into the official dev branch?

**Comment by aschier** [comment]
It works without any new class using

```cpp
glfwInit();
glfwWindowHint(GLFW_VISIBLE, GLFW_FALSE);
viewer.launch_init(false, false, "", 1024, 1024);
viewer.launch_rendering(false)
```

**Comment by jdumas** [comment]
I would rather not create a new class, but modify the existing one + add a tutorial showcasing this.

**Comment by aschier** [comment]
@jdumas I think your commit could just be merged.

For my projects I am probably fine with the four lines above, but having the `hidden` option included in the viewer class would probably not hurt and be useful for others as well.

**Comment by jdumas** [comment]
I'll make a note to take a look once we fix our CI issues.

**Comment by vnghia** [comment]
@jdumas can we merge this commit ? Because `embree` does not support adding texture but only vertex color so it is a little bit weird for me.

**Comment by jdumas** [comment]
Which commit are you referring to? The PR linked in this issue has been merged some time ago already.

**Comment by vnghia** [comment]
I mean this commit https://github.com/jdumas/libigl/commit/03008a0e319cea6ed3d25d40d39b8222341ce055. I am not sure if it is merged yet ?

**Comment by jdumas** [comment]
Ah right, it's not been merged yet. Sorry I don't have any plan to merge it myself at the moment.

**Comment by alecjacobson** [comment]
https://github.com/libigl/libigl/issues/1458#issuecomment-604460945 seems like the way to go.
