### ISSUE TITLE
Mesh orientation

### ISSUE THREAD

**Issue by lukkio88** [libigl/libigl#1460]
Though I suppose it's not difficult to implement this using Eigen do you have a function that given a triangular mesh (V,F) can compute the principal axis (in order to determine the orientation)?

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by jdumas** [comment]
It's easy enough to do directly with Eigen, see e.g. [this code snippet](https://gist.github.com/ialhashim/0a2554076a6cf32831ca).

**Comment by lukkio88** [comment]
That's exactly what I was going to do, but I was wondering if you had a function for this (so wouldn't be re-inventing the wheel =D).

**Comment by jdumas** [comment]
Well no you have it.
