### ISSUE TITLE
Mesh keypoints and local feature extraction

### ISSUE THREAD

**Issue by lukkio88** [libigl/libigl#1461]
Hi,

I think the library doesn't provide API for key points and local feature extraction but I want to double check anyway. I know you have the Laplace Beltrami operator and it's the basis of many algorithms, such as diffusion wavelet, HKS etc...

Anything available that would avoid me looking for different libraries or implement these from scratch?

...

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by alecjacobson** [comment]
There's nothing like that currently implemented. Would be happy to merge a pr for such a technique.
