### ISSUE TITLE
How to use "point_mesh_squared_distance"

### ISSUE THREAD

**Issue by lukkio88** [libigl/libigl#1462]
I cannot undestand how to use the [https://github.com/libigl/libigl/blob/master/include/igl/point_mesh_squared_distance.h](url) (the templates confuse me).

Can you show me a very simple example or maybe point to a specific tutorial of yours that uses it?

...

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by Rocketmagnet** [comment]
I would also love to see a working example of this function. I am really confused about the exact parameters it expects. The same goes for AABB. I simply can't get this to compile and run.

    #include <igl/readSTL.h>
    #include <igl/opengl/glfw/Viewer.h>
    #include<igl/point_mesh_squared_distance.h>
    #include <igl/AABB.h>

    #include <math.h>
    #include <iostream>

    using namespace std;

    Eigen::MatrixXd V;  // Vertices
    Eigen::MatrixXi F;  // Faces

    Eigen::MatrixXd N;  // Normals

    Eigen::VectorXd P;      // query point
    Eigen::VectorXd Pn;     // nearest point on mesh
    Eigen::MatrixXd sqrD;   // squares of the distances
    Eigen::MatrixXd C;
    Eigen::MatrixXi I;

    igl::AABB<Eigen::MatrixXd, 1> tree;



    double t = 0.0;

    bool PreDraw(igl::opengl::glfw::Viewer& viewer)
    {
        t += 0.01;

        P(0) = sin(t) * 10.0;
        P(1) = 0;
        P(2) = 0;

        //igl::point_mesh_squared_distance(P, V, F, sqrD, I, C);
        tree.squared_distance(V, F, P, sqrD, I, C);

        return false;
    }

    int main(int argc, char* argv[])
    {
        P = Eigen::Vector3d(0, 0, 0);

        igl::readSTL("Glitter_Surface.STL", V, F, N);

        tree.init(V, F);

        igl::opengl::glfw::Viewer viewer;
        viewer.data().set_mesh(V, F);
        viewer.data().point_size = 5;

        viewer.callback_pre_draw = PreDraw;
        viewer.launch();
    }

**Comment by lukkio88** [comment]
I actually managed to get my code compiled right now... As soon as I check I will not get rubbish I'll post a code snippet.

I'm actually glad I see people with similar issues to mine xD, it just means I'm not nuts!

**Comment by lukkio88** [comment]
@Rocketmagnet do you have the CMakeLists.txt of your program? I think I managed to make it work. In your case I believe all you need to do is to size your matrices before you launch your code.

If it doesn't work I'm more than happy to help out, but I need to be able to build your program.

**Comment by Rocketmagnet** [comment]
I don't have a CMakeLists.txt. I'm using Visual Studio, and have set up all the paths etc in the IDE. There shouldn't be anything unusual in this simple program.  I would love to see your code.

**Comment by lukkio88** [comment]
I can't share my specific code, so when I have an issue I work out an example from scratch. I'll post in the afternoon a simple example like yours.

**Comment by Rocketmagnet** [comment]
OK, I've got it working at last, and I'll post my code in the next comment. But what's surprising (to me, a newcomer to Eigen) is that while a Vector has 3 rows and 1 column, squared_distance expects the P matrix to have N rows and 3 columns.

**Comment by Rocketmagnet** [comment]
#include <igl/readSTL.h>
    #include <igl/opengl/glfw/Viewer.h>
    #include <igl/point_mesh_squared_distance.h>
    #include <igl/AABB.h>

    #include <math.h>
    #include <iostream>

    using namespace std;

    Eigen::MatrixXd V;  // Vertices
    Eigen::MatrixXi F;  // Faces
    Eigen::MatrixXd N;  // Normals

    #define NUM_POINTS  2

    Eigen::MatrixXd P(NUM_POINTS,3);      	// query point
    Eigen::MatrixXd Pn(NUM_POINTS*2, 3);    // nearest point on mesh
    Eigen::MatrixXd sqrD;   				// squares of the distances
    Eigen::MatrixXd C;
    Eigen::MatrixXi I;

    igl::AABB<Eigen::MatrixXd, 3> tree;


    bool PreDraw(igl::opengl::glfw::Viewer& viewer)
    {
        static double t += 0.01;

        for (int i = 0; i < NUM_POINTS; i++)				// Move 2 points about in space
        {
            P(i, 0) = sin(t+i) * 10.0;
            P(i, 1) = i*2;
            P(i, 2) = -30;
        }

        tree.squared_distance(V, F, P, sqrD, I, C);			// Find the nearest points on
                                                            // the mesh to those 2 points.

        for (int i = 0; i < NUM_POINTS; i++)                // Copy the original points, and
        {                                                   // the closest points into another
            Pn(i*2 + 0, 0) = P(i, 0);                       // matrix, so we can display all
            Pn(i*2 + 0, 1) = P(i, 1);                       // four points.
            Pn(i*2 + 0, 2) = P(i, 2);
            Pn(i*2 + 1, 0) = C(i, 0);
            Pn(i*2 + 1, 1) = C(i, 1);
            Pn(i*2 + 1, 2) = C(i, 2);
        }

        viewer.data().set_points(Pn, Eigen::RowVector3d(1, 1, 1));  // View all of those points

        return false;
    }


    int main(int argc, char* argv[])
    {
        igl::readSTL("filename.STP", V, F, N);

        tree.init(V, F);

        igl::opengl::glfw::Viewer viewer;
        viewer.data().set_mesh(V, F);
        viewer.data().point_size = 5;

        viewer.callback_pre_draw = PreDraw;
        viewer.launch();
    }

**Comment by Rocketmagnet** [comment]
Being stored in this order, doesn't it also mean that the X,Y,Z coordinates of each point in P aren't stored contiguously?

Does anyone know why it was decided to require P in this format?

**Comment by alecjacobson** [comment]
Not sure what is meant by P is transposed. Individual query points are 3-long rowvectors just like how vertices in (V,F) are 3-long rows in V.

I pushed an example into the doc. It contains:

```cpp      
Eigen::MatrixXd V;      
Eigen::MatrixXi F;      
igl::read_triangle_mesh("bunny.obj",V,F);      
// 100 points in [-1,1]³ cube      
Eigen::MatrixXd P = Eigen::MatrixXd::Random(100,3);      
Eigen::VectorXd sqrD;      
Eigen::VectorXi I;      
Eigen::MatrixXd C;      
igl::point_mesh_squared_distance(P,V,F,sqrD,I,C);      
// Now sqrD(i) = squared distance from P.row(i) to mesh      
// I(i) = closest primitive index      
// C.row(i) = closest point on mesh to P.row(i)      
```
