### ISSUE TITLE
Android/Ios support?

### ISSUE THREAD

**Issue by ChristofferGreen** [libigl/libigl#1466]
Hello,

Has anyone had any luck in compiling/using igl for android or ios?

When compiling on raspbian (raspberry pi/arm) I have an issue with FastWindingNumberForSoups.h including emmintrin.h so I would guess this is not supported, but figured it's best to check. If not, would it be a lot of changes needed to support such platforms?

**Comment by jdumas** [comment]
raspbian is neither android nos ios afaik. We are not trying to support either of those platforms at the moment, but we can accepts bugfix PRs in order to support those.
