### ISSUE TITLE
Submesh smoothing

### ISSUE THREAD

**Issue by candycat1992** [libigl/libigl#147]
Hi, 
I'm wondering if libigl has any feature for smoothing submeshes? In Example 205, the Laplacian  introduces a lot shrinkage. But i want to smooth only a part of the meshes without much shrinkage. Is it possible with libigl?

**Comment by alecjacobson** [comment]
We don't have a direct function for this. There's sort of two parts here:
1. Smoothing only part of a mesh, and 
2. Smoothing without shrinkage

For 1. I would set up an optimization problem to do implicit fairing. For example, minimize the squared Laplacian of the vertex positions + squared displacement of the vertex positions. Then I'd fix all vertices that I don't want to move. This is easy to do with `igl::min_quad_with_fixed` and `igl::cotmatrix`/`igl::massmatrix`. 

For 2., I'd have to read up on the state of the art of volume preserving smoothing. Something like taking small steps and projecting toward the tangent plane. Or perhaps really writing the total volume as a constraint. You could start with "Laplacian Mesh Optimization" [Nealen et al.] and working forward in time.

**Comment by candycat1992** [comment]
@alecjacobson Thanks very much! And great job!
