### ISSUE TITLE
Point triangle distance

### ISSUE THREAD

**Issue by lukkio88** [libigl/libigl#1472]
I can see you have a function that computes a distance point mesh. I can also see I'd be able to reuse such function to compute q distance point triangle.

I cannot find however the primitive for computing the distance point triangle, which I assume you have somewhere.

Can you please tell me where such function is? I've already my function, but if libigl already has it I would just get rid of mine.

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by jdumas** [comment]
There is a file literally called `point_triangle_squared_distance.h`, idk what more you need.

**Comment by lukkio88** [comment]
That's CGAL, isn't there a license to be aware of?

**Comment by jdumas** [comment]
Well yes, the files that depend on CGAL are licensed under GPL. That wasn't your question.
