### ISSUE TITLE
How to use ARPACK?

### ISSUE THREAD

**Issue by lukkio88** [libigl/libigl#1486]
Hi, I've the following program:

```
#include <igl/cotmatrix.h>
#include <igl/readOBJ.h>
#include <igl/opengl/glfw/Viewer.h>
#include <Eigen/Eigenvalues>
#include <Eigen/Dense>
#include <Eigen/Sparse>
#include <Eigen/SparseCore>
#include <unsupported/Eigen/ArpackSupport>

#include <iostream>

Eigen::MatrixXd V;
Eigen::MatrixXi F;
Eigen::SparseMatrix<double> L;
igl::opengl::glfw::Viewer viewer;

int main(int argc, char *argv[])
{
    using namespace Eigen;
    using namespace std;

    int k = std::atoi(argv[2]);

    std::cout << "Loading obj" << std::endl;

    igl::readOBJ(argv[1], V, F);
    int nrows = V.rows();

    std::cout << "Computing laplacian matrix" << std::endl;

    igl::cotmatrix(V,F,L);

    std::cout << "Computing eigen vectors of laplacian matrix" << std::endl;

    //Finding eigen values and eigen vectors
    //Eigen::EigenSolver<Eigen::SparseMatrix<double>> eigenSolver(L);
    Eigen::ArpackGeneralizedSelfAdjointEigenSolver<Eigen::SparseMatrix<double>> eigenSolver(L,5);

    auto eigenVector = eigenSolver.eigenvectors();

    std::cout << "Showing result" << std::endl;

    // Use original normals as pseudo-colors
    MatrixXd color = eigenVector.block(0,k,eigenVector.rows(),1).normalized().array()*0.5+0.5;

    viewer.data().set_mesh(V, F);
    viewer.data().set_colors(color);
    return viewer.launch();
}
```

Which is my own version of computing the eigen vectors of the laplacian operator.
However I do get the following error:

```
[ 50%] Building CXX object CMakeFiles/laplacian.dir/main.cpp.o
[100%] Linking CXX executable laplacian
CMakeFiles/laplacian.dir/main.cpp.o: In function `Eigen::ArpackGeneralizedSelfAdjointEigenSolver<Eigen::SparseMatrix<double, 0, int>, Eigen::SimplicialLLT<Eigen::SparseMatrix<double, 0, int>, 1, Eigen::AMDOrdering<int> >, false>::compute(Eigen::SparseMatrix<double, 0, int> const&, Eigen::SparseMatrix<double, 0, int> const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, double)':
main.cpp:(.text._ZN5Eigen39ArpackGeneralizedSelfAdjointEigenSolverINS_12SparseMatrixIdLi0EiEENS_13SimplicialLLTIS2_Li1ENS_11AMDOrderingIiEEEELb0EE7computeERKS2_S9_iNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEid[_ZN5Eigen39ArpackGeneralizedSelfAdjointEigenSolverINS_12SparseMatrixIdLi0EiEENS_13SimplicialLLTIS2_Li1ENS_11AMDOrderingIiEEEELb0EE7computeERKS2_S9_iNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEid]+0x824): undefined reference to `dsaupd_'
main.cpp:(.text._ZN5Eigen39ArpackGeneralizedSelfAdjointEigenSolverINS_12SparseMatrixIdLi0EiEENS_13SimplicialLLTIS2_Li1ENS_11AMDOrderingIiEEEELb0EE7computeERKS2_S9_iNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEid[_ZN5Eigen39ArpackGeneralizedSelfAdjointEigenSolverINS_12SparseMatrixIdLi0EiEENS_13SimplicialLLTIS2_Li1ENS_11AMDOrderingIiEEEELb0EE7computeERKS2_S9_iNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEid]+0xbc8): undefined reference to `dseupd_'
collect2: error: ld returned 1 exit status
CMakeFiles/laplacian.dir/build.make:86: recipe for target 'laplacian' failed
make[3]: *** [laplacian] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/laplacian.dir/all' failed
make[2]: *** [CMakeFiles/laplacian.dir/all] Error 2
CMakeFiles/Makefile2:84: recipe for target 'CMakeFiles/laplacian.dir/rule' failed
make[1]: *** [CMakeFiles/laplacian.dir/rule] Error 2
Makefile:118: recipe for target 'laplacian' failed
make: *** [laplacian] Error 2
```

The question is: In order to use ARPACK do I need to link against something specific? If not can you help me with this error?

In you example `306_EigenDecomposition` you use `eigs` but from a quick look at the source it seems that you suggest the proper way would be to use ARPACK.

Can you help?

...

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] macOS
- [x] Linux

**Comment by jdumas** [comment]
Hi. This is a Eigen question, not a libigl question. The Arpack module in Eigen is in the unsupported modules, so you're a bit on your own if you want to use it. Yes you probably need to link again Arpack, which is what's missing here. Alternatively, you can take a look at other projects such as [Arpack-Eigen](https://github.com/yixuan/arpack-eigen) or [Spectra](https://spectralib.org/) for computing eigenvalues, both of which should be easier to use than the standard Arpack lib.

**Comment by lukkio88** [comment]
By "link again Arpack" what do you mean exactly? Do I need to download it as a separate library? It seems to be a fortran library, I cannot manage to find the C++ version.

Is spectra better then `igl::eigs` in terms of accuracy and computational speed?

**Comment by jdumas** [comment]
Arpack is neither a dependency of Eigen nor libigl. Eigen has an optional wrapper for Arpack, but it's unsupported. If you want Arpack you have to integrate it in your project yourself.

> Is spectra better then igl::eigs in terms of accuracy and computational speed?

Probably. The implementation in libigl is very straightforward.

**Comment by lukkio88** [comment]
I've just tried to use spectra, but I think it needs eigen 3.3 in order to work. The version with your repo is 3.2. Can I just replace it with the most recent version?

**Comment by jdumas** [comment]
The version in our repo is using Eigen 3.3, you probably need to update.

**Comment by lukkio88** [comment]
`master` or `dev`?

**Comment by jdumas** [comment]
Dev doesn't exist anymore.

**Comment by lukkio88** [comment]
Ok, Spectra works. The only thing is that is quite slow in computing eigenvectors, I guess this is a common thing.
