### ISSUE TITLE
How to set a linear gradient background color

### ISSUE THREAD

**Issue by yvanblanchard** [libigl/libigl#1490]
Hello,

I would like to know if it’s possible to set a linear gradient (horizontal) background color, or how (and where) to code it if not possible.

Thank you

- [ x] Windows
- [ ] macOS
- [ ] Linux

**Comment by jdumas** [comment]
It's currently not possible, but maybe you can draw a textured quad in the background, disabling the camera transform in the vertex shader. See #657 on how to use custom shaders with the libigl viewer.
