### ISSUE TITLE
How to animate mesh in viewer 

### ISSUE THREAD

**Issue by yvanblanchard** [libigl/libigl#1491]
Hello,

I would like to know if it’s possible to animate the 3d. For example doing a progressive display of a mesh back and forth, with interpolations..

Thank you,

- [ x] Windows
- [ ] macOS
- [ ] Linux

**Comment by jdumas** [comment]
Yes, you just need to update the mesh at every frame (so it might be slow).

**Comment by alecjacobson** [comment]
See https://github.com/libigl/libigl/blob/main/tutorial/401_BiharmonicDeformation/main.cpp for example. 

https://libigl.github.io/dox/classigl_1_1opengl_1_1ViewerCore.html#a0effd92cbb0d11dcf1a5939fc5fc098d
https://libigl.github.io/dox/classigl_1_1opengl_1_1ViewerData.html#a8693588093bd351fd98b252bb1bd340f
