### ISSUE TITLE
_bin suffix really needed?

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#1492]
Do we really need the _bin suffix on all of the tutorial executables? similarly in https://github.com/libigl/libigl-example-project

I vaguely remember this was a hack because of name collisions on Windows with cmake. Is it still an issue? Is there a way to fix the name collision in the other way (rename what ever the binary would have collided with)?

This is a minor thing obviously, but if it's also easy to fix it'd make the mac/linux executables more normal looking.

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by jdumas** [comment]
I think there is some kind of conflict when an executable target has the same name as a folder or CMake project. I can try it out again on a Windows machine this week-end, but I'm all for killing the `_bin` suffix.
