### ISSUE TITLE
Mesh boolean multiple times minus

### ISSUE THREAD

**Issue by Da-Rudi** [libigl/libigl#1496]
Hello,

so I have a Cube around some complex geometry (as a scene box) and several complex geometry in space. Now I want to substract all of the complex geometry from that cube and end up with a geometry which describes the free space in the scene. What would be the best approach to do this with libigl? When I try to call mesh_boolean several times, I always end up with the PWN error when calling the boolean operation the second time on the cube. Is it better to use the Variadic boolean operations with a vector from start on?

**Comment by alecjacobson** [comment]
Best to keep the representation exact until the end.
