### ISSUE TITLE
Set points color incorrect if column vector color provided

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#1498]
```
  viewer.data().set_points(P,Eigen::RowVector3d(1,1,1));
```
Produces the correct result 
![image](https://user-images.githubusercontent.com/2241689/80548453-f956e300-8988-11ea-9505-00e8335e6617.png)

But if I use
```
  viewer.data().set_points(P,Eigen::Vector3d(1,1,1));
```
it compiles fine but I see:
![image](https://user-images.githubusercontent.com/2241689/80548509-1b506580-8989-11ea-9a12-afff8de4bb26.png)

Hopefully we can fix this to just work. Or at least we should catch it at compile time.

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [x] macOS
- [ ] Linux

**Comment by jdumas** [comment]
I don't think you can detect it as *compile time*, but we should certainly throw an error at *runtime* if you're trying to set colors using `Vector3d`. But I don't think we should try to do anything clever and correct the user intent (what if I only have 3 points for example?). Also, in Eigen when you do `M.row(i) << Vector3d(1, 1, 1)` it's not gonna end well, and Eigen doesn't even tell you in Release mode...

**Comment by alecjacobson** [comment]
Not sure I understand the issue if there are 3 points. Then the input for colors would be 3x3.

**Comment by jdumas** [comment]
But a 3x1 vector can also be interpreted as giving a scalar attribute to 3 points. Right now if `C.cols() == 1` we defer to `set_data(C)`. So if we allow a `Vector3d()` to be interpreted as a uniform color, this creates an ambiguity. We already have similar problems when |V| = |F| and we don't know if we set the colors per face or per vertex (happens easily for planar meshes). I'm not sure I want to introduce more "ambiguity magic". Throwing an exception for invalid use case shows problems early on and makes it easy to fix for the user.

**Comment by alecjacobson** [comment]
we should deprecate using set_color for set_data. This is legacy that we
can get rid of. Also, setting data on three points seems far less likely
than setting a color for three points, so it's ok to support this behavior
now.

>

**Comment by jdumas** [comment]
Sure. I'm just saying that explicit is better than implicit, and I prefer an error message over an "assumed" behavior (like recast a 3x1 vector into a uniform color).

**Comment by alecjacobson** [comment]
we can be explicit in the documentation that it's treated this way. With
all the templating and dynamic sizing, that's often all we can really do.

>
