### ISSUE TITLE
Changing name of parent directory affects viewer behavior

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#1499]
Changing the parent directory of an executable with our viewer to have the suffix `.app` will cause the resolution to drop.

This is incredibly weird behavior that is almost certainly unique to mac and probably a bug/issue we're inheriting from glfw (see, e.g., https://github.com/Gargaj/Bonzomatic/issues/53).

```
git clone https://github.com/libigl/libigl-example-project
cd libigl-example-project
mkdir build
cd build
cmake ../
make
../example_bin
```
<img width="1392" alt="Screen Shot 2020-04-29 at 12 25 45 PM" src="https://user-images.githubusercontent.com/2241689/80620984-ac205300-8a14-11ea-8e75-979ef17ffd31.png">

If you change the name of the parent directory to `build.app` then you get different rendering:

```
mv ../build/ ../build.app
cd ../build.app/
./example_bin 
```

![Screen Shot 2020-04-29 at 12 26 27 PM](https://user-images.githubusercontent.com/2241689/80621083-ca864e80-8a14-11ea-8849-c47f2a820601.png)

Notice how the lines are thicker. 

The blurriness of the menu bar looks like a good clue that somehow glfw is getting tricked into using a lower resolution. It's seems unlikely that glfw is looking at the executable path for `.app`. So maybe the `Terminal.app` is feeding in different environment variables depending on whether it's in this `.app` folder?

![image](https://user-images.githubusercontent.com/2241689/80621328-1f29c980-8a15-11ea-9475-c3cb00812c33.png)

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [x] macOS
- [ ] Linux

**Comment by jdumas** [comment]
Why do you want to rename the parent folder to end with .app in the first place?

**Comment by alecjacobson** [comment]
This is is a [minimal example](https://en.wikipedia.org/wiki/Minimal_working_example). The problem originates from attempt to bundle a libigl-viewer based app.

**Comment by jdumas** [comment]
I think we've successfully bundled a macOS app for [Cellogram](https://github.com/cellogram/cellogram/blob/master/app/viewer/CMakeLists.txt) with @teseoch. Does it also exhibit the resolution problem you're experiencing?

**Comment by alecjacobson** [comment]
Yes, seems like cellgram is blurry too.

>

**Comment by BruegelN** [comment]
Well I don't have a solution however:
```bash
mkdir -p good.app/Contents
cd good.app/Contents/
cmake ../../ && make -j4
./example_bin 
```
renders libigl-viewer as expected.
Apparently this `Contents/` folder is where macOS expects the content for app bundles.
(Just so you know it's neither an issue with `Terminal.app` nor bash on macOS as it's the same with [alacritty](https://github.com/alacritty/alacritty) and/or zsh.)

**Comment by alecjacobson** [comment]
Thanks. This is all so weird. The Celloramo app seems to have the
executable in the Contents/MacOS and has the problem. Not sure where this
problem is coming from.

>

**Comment by teseoch** [comment]
the app in macOS are strange.
The cellogram app cannot be opened with double-click.
I tried changing permission/changing plist and couldn't find a solution.
The weird stuff is that same cmake for instant meshes works.

**Comment by alecjacobson** [comment]
I forgot about this incredibly weird unresolved issue. I'm not noticing it on my new mac so I'm hoping the spirits have moved on to haunt another piece of software. Closing but happy to hear if someone resolved this.
