### ISSUE TITLE
Install libigl tutorials on windows using vcpkg

### ISSUE THREAD

**Issue by lukkio88** [libigl/libigl#1500]
Hi,

I'm trying to install libigl using vcpkg on windows 10.
Just running
```
vcpkg install libigl
```

Seems to install only the core part of libigl, but the builiding of the tutorial is missing.
Is there a specific way to install the tutorials in this case? (I'm quite new to `vcpkg`).

Thank you

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by jdumas** [comment]
We do not support vcpkg. Some people created a package to install the core components of libigl via vcpkg (see #1356), but that's pretty much it. I don't see why you'd want the tutorials as an installed package though, it's better to `git clone` and build them yourself.

**Comment by lukkio88** [comment]
Ah ok, so they're not actually built.

**Comment by jdumas** [comment]
No.
