### ISSUE TITLE
Mapping UV bidir Conversion with XYZ coords 

### ISSUE THREAD

**Issue by yvanblanchard** [libigl/libigl#1501]
Hello

I want to flatten a 3d triangle mesh having a point on it (not a triangle vertice, knowing it’s xyz Cartesian coords), then get the corresponding UV coords of this point.
Finally , I would also like to do the inverse : select a point on the 2D flatten mesh (uv), then get the corresponding point on the 3d mesh (xyz).
To sum up: is there is way with the library to make such a bidirectional conversion of coordinates , directly and easily (without extra computations needed for each conversion) ?

Thank you,
Yvan.

#### Check all that apply (change to `[x]`)
- [ c] Windows
- [ ] macOS
- [ ] Linux

**Comment by 1YILIU6** [comment]
Hey, libigl can flatten 3D meshes to UV coordinates. For the inverse, I'm also looking for an answer. Have you found an ideal approach to do that now?

**Comment by alecjacobson** [comment]
A pretty standard way to do this is to use barycentric coordinates.

Suppose you have a triangle whose 2D coordinates are
a,b,c ∈ℝ²

and whose corresponding 3D coordinates are 

A,B,C ∈ℝ³

Then a 2D point p in that 2D triangle can be written as:

p = α a + β b + γ c

see [barycenter_coordinates](https://libigl.github.io/dox/namespaceigl.html#a8a603159f2a82b981f00ca10be97d62e) and [in_element](https://libigl.github.io/dox/namespaceigl.html#ae6a48ea815ed7c6fce66c5fb16643592)

then you can reconstruct the corresponding 3D point with 

P = α A + β B + γ C 

see [barycentric_interpolate](https://libigl.github.io/dox/namespaceigl.html#ac2d34543d4673ecc638e11d0340f7c38)

closing this old issue but feel free to reopen if there're still problems.
