### ISSUE TITLE
not connecting -IGL :: opengl_glfw_imgui

### ISSUE THREAD

**Issue by Vladislav1507** [libigl/libigl#1502]
#### Describe your question

I can not connect -IGL :: opengl_glfw_imgui
I found this link:
https://github.com/libigl/libigl-example-project/issues/12
that in the case when imgui.n does not connect you need to target
append IGL :: opengl_glfw_imgui

but nothing has changed
maybe I'm recording it wrong?

- (target_link_libraries ($ {PROJECT_NAME} _bin igl :: core igl :: opengl_glfw igl :: opengl IGL :: opengl_glfw_imgui))

when creating it writes:
1> [CMake] CMake Error at C: \ Users \ Admin \ libigl-example-project \ CMakeLists.txt: 14 (add_executable):
1> [CMake] Target "example_bin" links to target "::" but the target was not found.
1> [CMake] Perhaps a find_package () call is missing for an IMPORTED target, or an
1> [CMake] ALIAS target is missing?

Error:
1) Error CMake Error at C: \ Users \ Admin \ libigl-example-project \ CMakeLists.txt: 14 (add_executable):
  Target "example_bin" links to target "::" but the target was not found.
  Perhaps a find_package () call is missing for an IMPORTED target, or an
  ALIAS target is missing? example C: \ Users \ Admin \ libigl-example-project \ CMakeLists.txt 14

2) Error C1083 Cannot open the inclusion file: igl / opengl / glfw / imgui / imgui_fonts_droid_sans.h: No such file or directory, C: \ Users \ Admin \ libigl-example-project \ out \ build \ x64-Debug \ libigl -example-project C: \ Users \ Admin \ libigl-example-project \ libigl \ include \ igl \ opengl \ glfw \ imgui \ ImGuiMenu.cpp 15

can you help me?

#### Check all that apply (change to `[x]`)
- [X ] Windows
- [ ] macOS
- [ ] Linux

**Comment by Vladislav1507** [comment]
I went around the problem in every way
downloaded the missing libraries
did not find only one

#include <imgui_fonts_droid_sans.h>

I could not find it either in the repositories or on the Internet

**Comment by jdumas** [comment]
Hi,

You need to enable the CMake option `LIBIGL_WITH_OPENGL_GLFW_IMGUI`, and link your executable target with `igl::opengl_glfw_imgui`.

**Comment by Vladislav1507** [comment]
Hi
//////////////////////////////////////////////////// //////////////////////////////////
my code is:
//////////////////////////////////////////////////// //////////////////////////////////
cmake_minimum_required (VERSION 3.1)
project (example)

set (CMAKE_MODULE_PATH $ {CMAKE_MODULE_PATH} $ {CMAKE_CURRENT_SOURCE_DIR} / cmake)

# libigl
option (LIBIGL_WITH_OPENGL "Use OpenGL" ON)
option (LIBIGL_WITH_OPENGL_GLFW "Use GLFW" ON)
option (LIBIGL_WITH_OPENGL_GLFW_IMGUI "Use ImGui" ON)


find_package (LIBIGL REQUIRED QUIET)

# Add your project files
file (GLOB SRCFILES * .cpp)
add_executable ($ {PROJECT_NAME} _bin $ {SRCFILES})
target_link_libraries ($ {PROJECT_NAME} _bin igl :: core igl :: opengl_glfw igl :: opengl_glfw_imgui)

//////////////////////////////////////////////////// ////////////////////////////////////
my mistake:
//////////////////////////////////////////////////// //////////////////////////////////
Error CMake Error at C: \ Users \ Admin \ libigl-example-project \ CMakeLists.txt: 16 (add_executable):
  Target "example_bin" links to target "igl :: opengl_glfw_imgui" but the
  target was not found. Perhaps a find_package () call is missing for an
  IMPORTED target, or an ALIAS target is missing? example C: \ Users \ Admin \ libigl-example-project \ CMakeLists.txt 16

**Comment by jdumas** [comment]
You need to remove the spaces around the colons: `igl::opengl_glfw_imgui`

**Comment by Vladislav1507** [comment]
Thank
but removing spaces does not help solve the problem

**Comment by jdumas** [comment]
Clean out your build folder/remove your `CMakeCache.txt`

**Comment by Vladislav1507** [comment]
I tried a lot of everything, but now CMake does not create a cache due to another error:

Error CMake Error at libigl / cmake / LibiglWindows.cmake: 18 (string):
   string sub-command REPLACE requires at least four arguments. C: \ Users \ Admin \ libigl-example-project \ libigl / cmake / LibiglWindows.cmake 18

**Comment by jdumas** [comment]
What version of CMake/Visual Studio are you using? Have you tried updating those?

**Comment by Vladislav1507** [comment]
Visual Studio 2019 - 16.5.4
Cmake - 3.17.1

Today I launched once again, just like yesterday I deleted everything, I downloaded the project again and it worked
Although I did the same yesterday
I don’t know what is the reason ...

thank you very much

**Comment by jdumas** [comment]
Sounds good. I'll close this then. You probably had a stale build folder that got cleared up.

**Comment by ppolack** [comment]
I got exactly the same problem today when starting from a blank new project and wanting to add LIBIGL_WITH_OPENGL_GLFW_IMGUI

when I removed the cache, I got when running `cmake ..` : 
-- Creating target: igl::opengl_glfw_imgui (igl_opengl_glfw_imgui)
CMake Error at libigl/cmake/libigl.cmake:405 (target_compile_features):
  target_compile_features specified unknown feature "cxx_std_11" for target
  "imguizmo".

I fixed it by changing l405 of  libigl/cmake/libigl.cmake : 
I removed: `target_compile_features(imguizmo PUBLIC cxx_std_11)`
and replace it by : `set (CMAKE_CXX_STANDARD 11)`
And it worked ! Hope it will help the next one

**Comment by jdumas** [comment]
You need to update your CMake version.

**Comment by chatyan** [comment]
Hi, I want to use libigl + imgui. But something went wrong. 
Could you give me some advice?

CMake:

cmake_minimum_required(VERSION 3.1)
project(example)

set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${CMAKE_CURRENT_SOURCE_DIR}/cmake)

# libigl
option(LIBIGL_WITH_OPENGL            "Use OpenGL"         ON)
option(LIBIGL_WITH_OPENGL_GLFW       "Use GLFW"           ON)
option(LIBIGL_WITH_OPENGL_GLFW_IMGUI "Use ImGui"         ON)

find_package(LIBIGL REQUIRED QUIET)

# Add your project files
file(GLOB SRCFILES *.cpp)
add_executable(${PROJECT_NAME} ${SRCFILES})
target_link_libraries(${PROJECT_NAME} _bin igl::core igl::opengl_glfw igl::opengl_glfw_imgui)

OUTPUT:
Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
MSVC -> forcing use of dynamically-linked runtime.
Creating target: igl::core (igl)
Creating target: igl::opengl (igl_opengl)
Creating target: igl::opengl_glfw (igl_opengl_glfw)
Using Win32 for window creation
Creating target: igl::opengl_glfw_imgui (igl_opengl_glfw_imgui)
CMake Error at D:/IGL_Base/libigl/cmake/DownloadProject.cmake:179 (message):
  Build step for imgui failed: 1
Call Stack (most recent call first):
  D:/IGL_Base/libigl/cmake/LibiglDownloadExternal.cmake:25 (download_project)
  D:/IGL_Base/libigl/cmake/LibiglDownloadExternal.cmake:37 (igl_download_project_aux)
  D:/IGL_Base/libigl/cmake/LibiglDownloadExternal.cmake:104 (igl_download_project)
  D:/IGL_Base/libigl/cmake/libigl.cmake:399 (igl_download_imgui)
  cmake/FindLIBIGL.cmake:34 (include)
  CMakeLists.txt:11 (find_package)


Configuring incomplete, errors occurred!
See also "D:/IGL_Base/libigl-example-project/build/CMakeFiles/CMakeOutput.log".
See also "D:/IGL_Base/libigl-example-project/build/CMakeFiles/CMakeError.log".

**Comment by yang-zhifei** [comment]
> option(LIBIGL_WITH_OPENGL_GLFW_IMGUI "Use ImGui" ON)
> 
> find_package(LIBIGL REQUIRED QUIET)
> 
> # Add your project files
> file(GLOB SRCFILES *.cpp)
> add_executable(${PROJECT_NAME} ${SRCFILES})
> target_link_libraries(${PROJECT_NAME} _bin igl::core igl::opengl_glfw igl::opengl_glfw_imgui)
> 
> OUTPUT:
> Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
> MSVC -> forcing use of dynamically-linked runtime.
> Creating target: igl::core (igl)
> Creating target: igl::opengl (igl_opengl)
> Creating target: igl::opengl_glfw (igl_opengl_glfw)
> Using Win32 for window creation
> Creating target: igl::opengl_glfw_imgui (igl_opengl_glfw_imgui)
> CMake Error at D:/IGL_Base/libigl/cmake/DownloadProject.cmake:179 (message):
> Build step for imgui failed: 1
> Call Stack (most recent call first):
> D:/IGL_Base/libigl/cmake/LibiglDownloadExternal.cmake:25 (download_project)
> D:/IGL_Base/libigl/cmake/LibiglDownloadExternal.cmake:37 (igl_download_project_aux)
> D:/IGL_Base/libigl/cmake/LibiglDownloadExternal.cmake:104 (igl_download_project)
> D:/IGL_Base/libigl/cmake/libigl.cmake:399 (igl_download_imgui)
> cmake/FindLIBIGL.cmake:34 (include)
> CMakeLists.txt:11 (find_package)
> 
> Configuring incomplete, errors occurred!
> See also "D:/IGL_Base/libigl-example-project/build/CMakeFiles/CMakeOutput.log".
> See also "D:/IGL_Base/libigl-example-project/build/CMakeFiles/CMakeError.log".

same as you 
my device is window10+vs2019
Could you give me some advice?
mistakes as following:

Creating target: igl::opengl_glfw_imgui (igl_opengl_glfw_imgui)
CMake Error at cmake/DownloadProject.cmake:179 (message):
  Build step for imgui failed: 1
Call Stack (most recent call first):
  cmake/LibiglDownloadExternal.cmake:25 (download_project)
  cmake/LibiglDownloadExternal.cmake:37 (igl_download_project_aux)
  cmake/LibiglDownloadExternal.cmake:104 (igl_download_project)
  cmake/libigl.cmake:398 (igl_download_imgui)
  CMakeLists.txt:59 (include)


Configuring incomplete, errors occurred!
See also "E:/libigl/build/CMakeFiles/CMakeOutput.log".
