### ISSUE TITLE
Decimation: UVs of Diffuse channel or LightMap channel?

### ISSUE THREAD

**Issue by oschakravarthi** [libigl/libigl#1506]
Hi

The birth vertex stuff is working great.
I have a question. For the decimate operation do I need to use UVs of Diffuse channel or LightMap channel?

BTW,

I am trying to use SeamAware decimator but it is buggy. It is throwing exceptions like array out of bounds etc.. I even implemented birth vertex stuff in it. I am not receiving any replies from the author of SeamAware.

Will you be able to help me in fixing this?

Thanks in advance

**Comment by alecjacobson** [comment]
Check out this thread https://github.com/libigl/libigl/issues/1540

Closing because this is old and answered in the other thread but feel free to reopen if there's still an issue.
