### ISSUE TITLE
find the volume of figures

### ISSUE THREAD

**Issue by Vladislav1507** [libigl/libigl#1507]
#### Describe your question

Hello,
Perhaps it’s silly to write support with such simple tasks, but I can’t find the volume of figures

I thought it’s very easy to solve
Eigen :: VectorXd vol = igl :: volume (V, F);
vol.array (). abs (). sum ();
but complains about igl :: volume

#### Check all that apply (change to `[x]`)
- [x ] Windows
- [ ] macOS
- [ ] Linux

**Comment by alecjacobson** [comment]
Does F contain triangles or tetrahedra? `igl::volume` computes volume per tetrahedron. If you have a surface triangle mesh bounding a solid region, and would like the contained volume, then you can use `igl::centroid` whose second output is the volume.

**Comment by Vladislav1507** [comment]
At execution
igl :: centroid (V, F, vol);
the program crashes

**Comment by alecjacobson** [comment]
vol should be the second output argument. Something like:

Eigen::Vector3d C;
double vol;
igl::centroid(V,F,C,vol);

If it still crashes, you might have to run in debug mode to collect a
backtrace and send the mesh to help you debug.

>

**Comment by Vladislav1507** [comment]
And how to calculate the volume if I need to do this through the selected shape?
I choose a figure through
viewer.selected_data_index
or how to assign the current value viewer.selected_data_index V and F?
