### ISSUE TITLE
file_dialog_open causes heap corruption on Windows

### ISSUE THREAD

**Issue by evouga** [libigl/libigl#1513]
#### Describe the bug

On line 63, libigl creates a buffer of size 100 to store the filename:
````ofn.lpstrFile = new char[100];````
but then tells Windows that the maximum file length is 260. This corrupts the heap when loading a file with between 100 and 260 characters. Incidentally, this line also leaks memory.

There is a static buffer of the right size that is for some reason not used; I think the fix is as simple as:
````ofn.lpstrFile = szFile;````

#### Check all that apply (change to `[x]`)
- [X] Windows
- [ ] macOS
- [ ] Linux

**Comment by evouga** [comment]
Oh and file_dialog_save.cpp needs the same fix.

**Comment by jdumas** [comment]
Good catch! Would you be able to make a PR for that?
