### ISSUE TITLE
Faster mesh importer than readOBJ?

### ISSUE THREAD

**Issue by lukkio88** [libigl/libigl#1515]
Hi,

Quick question. Do you have a fast mesh reader? I'm currently reading from an obj file, but I could store this in different ways. Maybe you have a mesh reader from binary?

I can see you have different readers, but I'm not familiar with all the formats (apart from `.ply` and `.obj` I don't know much about it).

**Comment by alecjacobson** [comment]
Ply is binary and faster. I remember using binary .dmat (a matrix format
rather than a mesh format) and that was also fast.

**Comment by jdumas** [comment]
If you want speed you might want to try another ply reader library:
https://github.com/mhalber/ply_io_benchmark

For obj https://github.com/tinyobjloader/tinyobjloader may be faster than libigl's reader I think.
