### ISSUE TITLE
How to get the triangles indices intersected with a given line in a mesh

### ISSUE THREAD

**Issue by SeanTse** [libigl/libigl#1517]
#### Describe your question
Hi,
I am new to graphics. Is there any possible way to get the triangles in a triangle mesh intersected with a line, which is represented as a vector?
...

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by jdumas** [comment]
Hi,

Please take a loot at the [picking](https://libigl.github.io/tutorial/#picking) tutorial.

**Comment by SeanTse** [comment]
I see!! Thanks a lot!
