### ISSUE TITLE
Modify the default menu or remove it?

### ISSUE THREAD

**Issue by JianqiangDing** [libigl/libigl#1519]
https://github.com/libigl/libigl/blob/1df0987271ddc89bc2a3055482a478ac981f1884/include/igl/opengl/glfw/imgui/ImGuiMenu.cpp#L174-L178

Hi, can I remove the default viewer menu? or is there a way that I can modify the properties of the default "View" menu? i.e. make it's background transparent.
I would like to define our menu but the default "Viewer"(not another separate menu), but I don't get the way that I can remove the default one, I think it is better to begin the “Viewer” out of the ImGuiMenu.cpp, could this be possible? does this change affects some other functions?

**Comment by jdumas** [comment]
Hi,

You can write your own menu by overriding the virtual method `draw_viewer_window()`, or providing your own alternative in the form of a lambda callback by setting the member variable `callback_draw_viewer_window`.

**Comment by JianqiangDing** [comment]
I know what you are talking about, Yes, that's what the tutorial said, I mean, it seems that I can still not remove the bar of "Viewer" even though by providing my callback function, Cause the "Viewer" was defined inside the libigl. Here is the screenshot, So, what's your point?
![image](https://user-images.githubusercontent.com/7833870/82106325-c10a1f80-9752-11ea-80c8-1c43a4b28c0e.png)

**Comment by jdumas** [comment]
There's a difference between `draw_viewer_menu()` and `draw_viewer_window()`. The tutorial mentions the former, which only draws the _content_ of the menu window. The second method is the one that defines the actual window, and calls `draw_viewer_menu()` internally. Both can be overidden via inheritance or lambda.

**Comment by JianqiangDing** [comment]
Oh, sorry for the misunderstanding, you are right, big thanks!!!, you may close the issue now.
