### ISSUE TITLE
Rotate a 2d mesh by a pivot point off the center

### ISSUE THREAD

**Issue by kabukunz** [libigl/libigl#1522]
#### Describe your question

Hello there, I'm trying to rotate the longest side of a polygon to align to Y axis.
For "longest side" I mean the longest edge with colinear edges combined as one single edge.
I start from this simple rectangular mesh:

<img width="290" alt="start" src="https://user-images.githubusercontent.com/33091053/82321007-7dbee380-99d4-11ea-80cf-8a87eba71de8.png">
 
the code I'm using:

```
#include <iostream>

#include <igl/rotation_matrix_from_directions.h>
#include <igl/writeOBJ.h>

#include <Eigen/Core>

using namespace Eigen;

//
//
//

int main(int argc, char *argv[])
{

    MatrixXd V (25,3);

    V << 
    -1.833111,  -1.28051,        -0,
     2.124274, -0.698183,        -0,
    -2.124274,  0.698183,         0,
     1.833111,   1.28051,         0,
    -1.978693, -0.291164,        -0,
     0.145582, -0.989346,        -0,
     1.978693,  0.291164,         0,
    -0.145582,  0.989346,         0,
            0,         0,         0,
    -1.905902, -0.785837,        -0,
     1.134928, -0.843764,        -0,
     1.905902,  0.785837,         0,
    -1.134928,  0.843764,         0,
     1.062137, -0.349091,        -0,
    -2.051483,   0.20351,         0,
    -0.843764, -1.134928,        -0,
     2.051483,  -0.20351,        -0,
     0.843764,  1.134928,         0,
    -1.062137,  0.349091,         0,
    -0.072791,  0.494673,         0,
     0.989346,  0.145582,         0,
     0.916555,  0.640255,         0,
    -0.916555, -0.640255,        -0,
     0.072791, -0.494673,        -0,
    -0.989346, -0.145582,        -0;

    MatrixXi F (32,3);

    F <<
     1, 13, 10,
     1, 16, 13,
     8, 19, 18,
     8, 20, 19,
     6, 11, 21,
     5, 22, 15,
     5, 23, 22,
     8, 18, 24,
    24, 14,  4,
    24, 18, 14,
    18,  2, 14,
    22, 24,  4,
    22, 23, 24,
    23,  8, 24,
    15,  9,  0,
    15, 22,  9,
    22,  4,  9,
    21, 17,  7,
    21, 11, 17,
    11,  3, 17,
    19, 21,  7,
    19, 20, 21,
    20,  6, 21,
    18, 12,  2,
    18, 19, 12,
    19,  7, 12,
    13, 20,  8,
    13, 16, 20,
    16,  6, 20,
    10, 23,  5,
    10, 13, 23,
    13,  8, 23;


    //right rectangle side vector (precalculated)
    Vector3d LSV;
    LSV << 0.989346220797831, 0.145581782490286, 0;    

    // get the Y axis
    Vector3d axis;
    axis = Vector3d::UnitY();

    Matrix3d RM;
    RM = igl::rotation_matrix_from_directions(LSV, axis);

    // rotate polygon
    MatrixXd RV;
    RV = V * RM;

    V = RV;

    // write output
    if (!igl::writeOBJ("model_roax.obj", V, F))
        return 1;

    return 0;
}
```
and I get:

<img width="294" alt="end" src="https://user-images.githubusercontent.com/33091053/82321407-135a7300-99d5-11ea-89fc-8febca2a6fff.png">

while I would of course expect:

<img width="295" alt="desired" src="https://user-images.githubusercontent.com/33091053/82321432-1d7c7180-99d5-11ea-9bc1-c7134fb67b47.png">

My tests shows it always rotate 90° to the right, while I should be getting alignment.
Maybe the problem is that rotation_matrix_from_directions makes it rotate around the mesh center, while the side vector is off from it? I'd like to rotate by the down right mesh point, i.e. I need to change the rotation pivot. How can I do that?

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [x] macOS
- [ ] Linux

**Comment by jdumas** [comment]
If you're multiplying to the right you need to transpose your transformation matrix:
```cpp
    RV = V * RM.transpose();
```

**Comment by kabukunz** [comment]
Thank you, it worked. I guess I need some more math homework...
