### ISSUE TITLE
issue with compile the tutorial

### ISSUE THREAD

**Issue by aiyouweiyxx** [libigl/libigl#1526]
#### Describe your question
I use
`sh compile_dependencies_macosx.sh`
under `nPV-3/libigl/tutorial` and got the error
`In file included from /usr/local/Cellar/gcc/9.2.0_3/include/c++/9.2.0/cstdio:42,
                 from /Users/yxx/Downloads/nPV-3/libigl/external/embree/embree/sys/platform.h:23,
                 from /Users/yxx/Downloads/nPV-3/libigl/external/embree/embree/sys/platform.cpp:17:
/usr/local/Cellar/gcc/9.2.0_3/lib/gcc/9/gcc/x86_64-apple-darwin19/9.2.0/include-fixed/stdio.h:219:10: fatal error: _ctermid.h: No such file or directory
  219 | #include <_ctermid.h>
      |          ^~~~~~~~~~~~
compilation terminated.
`
How can I fix this?

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [x] macOS
- [ ] Linux

**Comment by jdumas** [comment]
What is `compile_dependencies_macosx.sh`?

**Comment by aiyouweiyxx** [comment]
`cd ../external/AntTweakBar/src/
rm ../lib/*.a
make -f makefile.osx.igl

cd ../../glfw/
cmake -DCMAKE_BUILD_TYPE=Release .
rm src/*.a
make

cd ../embree/
rm -fr build
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ../
make

cd ../../../tutorial`

**Comment by jdumas** [comment]
> AntTweakBar
Ok I think you're using a version of libigl from 10 years ago. Maybe you should update it.

**Comment by aiyouweiyxx** [comment]
ok, thank you
