### ISSUE TITLE
k-ring neighbour faces

### ISSUE THREAD

**Issue by lslog3** [libigl/libigl#1528]
igl does not have half-edge structure. Is there any quick way to get k-ring neighbour faces or iterate the adjacent faces for a given vertex?

**Comment by jdumas** [comment]
Sure, look at any function marked with "adjacency" in their name.

**Comment by lslog3** [comment]
> Sure, look at any function marked with "adjacency" in their name.

Thanks. I found vertex_face_adjacency(V, F, VF, VFi) is useful. But I don't understand what the output VFi mean. The note reads confusing to me.
  //   VI  #V list of lists of index of incidence within incident faces listed
  //     in VF

**Comment by MartensCedric** [comment]
I'm also confused by `vertex_triangle_adjacency`.

I expected this function to take as an input a list of faces and a single vertex and return a list of face indices of the vertex's neighboring faces.

However, the documentation is quite confusing 

![image](https://github.com/libigl/libigl/assets/18620025/bcb9e784-082b-49c1-bc60-d3525e4dae13)

**Comment by alecjacobson** [comment]
The documentation looks correct to me, but let's see if we can make it clearer.

The second input `n` is the total number of vertices in the mesh.

This function builds adjacency information for the entire mesh, not just a single vertex. The output variable `VF` contains a serialized array of that information.
