### ISSUE TITLE
cannot find targets `igl::opengl` and `igl::opengl_glfw`

### ISSUE THREAD

**Issue by lukkio88** [libigl/libigl#1529]
Hi, I'm trying to isolate your example 102_DrawMesh, because I need to modify it.

I've written the following CMakeLists.txt

```
cmake_minimum_required(VERSION 3.12 FATAL_ERROR)
project(mesh-manipulation)
set(CMAKE_CXX_STANDARD 14)

set(SRC_DIR ${CMAKE_CURRENT_SOURCE_DIR})
set(HEADER_DIR ${CMAKE_CURRENT_SOURCE_DIR})
#include_directories(${CMAKE_CURRENT_SOURCE_DIR}/../../external/eigen)

# libigl
option(LIBIGL_WITH_OPENGL "Use OpenGL" ON)
option(LIBIGL_WITH_OPENGL_GLFW "Use GLFW" ON)

find_package(LIBIGL REQUIRED QUIET)

# Add your project files
add_executable(mesh-manipulation ${SRC_DIR}/main.cpp)
target_link_libraries(mesh-manipulation igl::core igl::common igl::opengl igl::opengl_glfw)
```

When I run `cmake` to build it I also set `-DLIBIGL_WITH_OPENGL=ON -DLIBIGL_WITH_OPENGL_GLFW=ON`

However I get the error:
```
CMake Error at CMakeLists.txt:16 (add_executable):
  Target "mesh-manipulation" links to target "igl::opengl" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at CMakeLists.txt:16 (add_executable):
  Target "mesh-manipulation" links to target "igl::opengl_glfw" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
```

I'm not really sure what I'm doing wrong, I've also tried to use `CMAKE_MODULE_PATH` and `CMAKE_PREFIX_PATH` but it doesn't make a difference.

Can you help?
...

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] macOS
- [x] Linux

**Comment by jdumas** [comment]
When changing CMake options you need to either remove your `CMakeCache.txt` or use a program like cmake-gui or ccmake to update the CMakeCache.txt and reconfigure your project.

**Comment by lukkio88** [comment]
Which options are you talking about? Do you mean when building libigl? The way I built it was the usual
```
mkdir build && cd build && cmake ../ && make -j8
```

**Comment by jdumas** [comment]
I am talking about [CMake Cache Variables](https://cliutils.gitlab.io/modern-cmake/chapters/basics/variables.html).

**Comment by lukkio88** [comment]
Do you mean I should do a clean build of my project when I set `-DLIBIGL_WITH_OPENGL=ON -DLIBIGL_WITH_OPENGL_GLFW=ON`? Those are the only options I'm changing.

**Comment by jdumas** [comment]
Yes delete your build folder and try again.

**Comment by lukkio88** [comment]
I get this If I delete and try again:

My line from my build

```
cmake ../ -DCMAKE_PREFIX_PATH=/home/MeshProcessing/l
ibigl/build -DLIBIGL_WITH_OPENGL=ON -DLIBIGL_WITH_OPENGL_GLFW=ON
```

Output

```
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- [libigl] Looking for Eigen3
-- Configuring done
CMake Error at CMakeLists.txt:16 (add_executable):
  Target "mesh-manipulation" links to target "igl::opengl" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at CMakeLists.txt:16 (add_executable):
  Target "mesh-manipulation" links to target "igl::opengl_glfw" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


-- Generating done
-- Build files have been written to: /MeshManipulation/build
```

**Comment by BruegelN** [comment]
Please try to base your project on the [libigl-example-project](https://github.com/libigl/libigl-example-project).
Or you need to add this line: https://github.com/libigl/libigl-example-project/blob/master/cmake/FindLIBIGL.cmake#L33 to your CMakeLists.txt and replase `${LIBIGL_INCLUDE_DIR}` with `/home/MeshProcessing/libigl/`
Said [cmake folder](https://github.com/libigl/libigl/tree/master/cmake) contains all the *magic*( download dependencies, export targets...).

**Comment by lukkio88** [comment]
It still doesn't work. The error is the same. I've also tried to use the example you suggested. In such case I get the error:

```
 ../
CMake Error at cmake/FindLIBIGL.cmake:34 (include):
  include could not find load file:

    libigl
Call Stack (most recent call first):
  CMakeLists.txt:10 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/MeshProcessing/libigl-example-project/build/CMakeFiles/CMakeOutput.log".
```

**Comment by BruegelN** [comment]
Sorry, my fault, I overlooked sth. I've updated the comment above.

>  I've also tried to use the example you suggested. In such case I get the error: [...]

I assume you did something like:
```bash
git clone https://github.com/libigl/libigl-example-project.git
git clone https://github.com/libigl/libigl.git
cd libigl-example-project
mkdir build
cd build
cmake ..
```
So the libigl-example-project is not working? :/

**Comment by lukkio88** [comment]
Yes, the only difference is that I've also built in a build folder. So more like:

```
git clone https://github.com/libigl/libigl-example-project.git
git clone https://github.com/libigl/libigl.git
cd libigl
mkdir build && cd build
cmake ..
cd ../../libigl-example-project
mkdir build && cd build
cmake ..
```

**Comment by lukkio88** [comment]
I've also tried this variant:
```
cmake ../ -DCMAKE_MODULE_PATH=../../libigl/cmake
```

And I get

```
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at cmake/FindLIBIGL.cmake:34 (include):
  include could not find load file:

    ../../libigl/cmake/libigl.cmake
Call Stack (most recent call first):
  CMakeLists.txt:10 (find_package)
```

However if I

ls ../../libigl/cmake/

The content is:

```
CXXFeatures.cmake                    FindCORK.cmake    HunterGate.cmake  libigl-config.cmake.in        LibiglWindows.cmake
DownloadProject.cmake                FindMATLAB.cmake  libigl-cgal.yml   LibiglDownloadExternal.cmake
DownloadProject.CMakeLists.cmake.in  FindMOSEK.cmake   libigl.cmake      LibiglFolders.cmake
```

So the file is there, I'm not sure what's going on.

**Comment by lukkio88** [comment]
It seems this line worked (for the example, not my code).

```
cmake ../ -DCMAKE_MODULE_PATH=/home/MeshProcessing/libigl/cmake -DLIBIGL_DIR=/home/MeshProcessing/libigl
```

And the example is running, let me see if I can fix my actual code to work with this.

**Comment by lukkio88** [comment]
Ok, so I managed.

I changed my `CMakeLists.txt` as follows:

```
cmake_minimum_required(VERSION 3.1 FATAL_ERROR)
project(mesh-manipulation)
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${CMAKE_CURRENT_SOURCE_DIR}/cmake)

set(SRC_DIR ${CMAKE_CURRENT_SOURCE_DIR})
set(HEADER_DIR ${CMAKE_CURRENT_SOURCE_DIR})
#include_directories(${CMAKE_CURRENT_SOURCE_DIR}/../../external/eigen)

# libigl
option(LIBIGL_WITH_OPENGL "Use OpenGL" ON)
option(LIBIGL_WITH_OPENGL_GLFW "Use GLFW" ON)

find_package(LIBIGL REQUIRED QUIET)

# Add your project files
add_executable(mesh-manipulation ${SRC_DIR}/main.cpp)
target_link_libraries(mesh-manipulation igl::core igl::opengl igl::opengl_glfw)
```

I've also copied the content of the whole `cmake` folder in the `libigl-example-project`, this together with the same line I used earlier worked.

There's one small side question though (I'm not an expert on CMake, I learn everytime I come across a problem). If In my current CMakeLists.txt I replace

```
target_link_libraries(mesh-manipulation igl::core igl::opengl igl::opengl_glfw)
```

with

```
target_link_libraries(mesh-manipulation igl::core igl::common igl::opengl igl::opengl_glfw)
```

I get the error:

```
CMake Error at CMakeLists.txt:17 (add_executable):
  Target "mesh-manipulation" links to target "igl::common" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```

Would I need to modify the `FindLIBIGL.cmake` to make it work? or do I need to add maybe one more option in my `CMakeLists.txt`?

Thank you

**Comment by jdumas** [comment]
A couple of things:
1. You do not need to first build libigl prior to compiling your own project (since the model we use is that third-party projects build libigl from source).
2. You shouldn't need to provide your own `CMAKE_MODULE_PATH` or `LIBIGL_DIR` from the command-line.
3. You do not need to link against `igl::common`. Only `igl::core`, `igl::opengl`, and `igl::opengl_glfw` are necessary (actually they each depend on the previous one so you could only write `igl::opengl_glfw` and it should work).
4. Actually it should be enough to replace your `find_package(LIBIGL REQUIRED QUIET)` with a `add_subdirectory(<path-to-libigl> libigl)` in your own project. No need to copy any `cmake/` folder or anything.

In any case, you seem to be pretty "green" when it comes to CMake. I would strongly suggest that you do your homework and learn how to work with CMake projects before trying to blindly solve every problem you might encounter. Here are some good resources to learn about CMake projects:
- [Effective Modern CMake](https://gist.github.com/mbinna/c61dbb39bca0e4fb7d1f73b0d66a4fd1#file-effective_modern_cmake-md).
- [An Introduction to Modern CMake](https://cliutils.gitlab.io/modern-cmake/).

**Comment by lukkio88** [comment]
I'll try to modify my CMakeLists based on your suggestions.

**Comment by lukkio88** [comment]
Ok, this is my final `CMakeLists.txt`

```
cmake_minimum_required(VERSION 3.1 FATAL_ERROR)
project(mesh-manipulation)
set(CMAKE_CXX_STANDARD 14)

set(SRC_DIR ${CMAKE_CURRENT_SOURCE_DIR})
set(HEADER_DIR ${CMAKE_CURRENT_SOURCE_DIR})

add_subdirectory(${LIBIGL_DIR} libigl)

add_executable(mesh-manipulation ${SRC_DIR}/main.cpp)
target_link_libraries(mesh-manipulation igl::opengl_glfw)
```

Where `LIBIGL_DIR` is passed through the command line when running `cmake` (so something like `cmake .. -DLIBIGL_DIR=<path-to-libigl>`

**Comment by alecjacobson** [comment]
cmake has changed a lot since this issue so hopefully all this is easier. Feel free to reopen if there's still an issue.
