### ISSUE TITLE
How to render standard .obj file with texture using libigl

### ISSUE THREAD

**Issue by KevinChenGit** [libigl/libigl#153]
Hi Alec, Daniele, 

I want to render a mesh (i.e. a standard .obj file with .mtl and texture image) with texture using libigl? However, I found that the function of loading mtl and texture image is not implemented under igl::readOBJ(). Is there any way to render standard mesh file with texture in libigl? How to load the texture image?

Thank you very much!

**Comment by alecjacobson** [comment]
The libigl support for .obj files is very "academic". Basically it will
read simple streams of vertices, faces, texture coordinates and normals and
ignore everything else. The .mtl file will be ignored entirely, so will
groups and strange relative orderings and whatever other nonsense full
.obj's can support.

The libigl viewer is really just a toy to show examples. I'd suggest
Blender, Maya or maybe MeshLab for a full-featured .obj/.mtl viewer.

**Comment by KevinChenGit** [comment]
okay:-) Actually I just render texture for debugging purpose, not for final paper results. But thanks for your reply anyway!
