### ISSUE TITLE
Removing faces from a mesh

### ISSUE THREAD

**Issue by lukkio88** [libigl/libigl#1530]
#### Describe your question

Hi,

I currently have this code:

```
#include <igl/readOBJ.h>
#include <igl/opengl/glfw/Viewer.h>
#include <igl/adjacency_list.h>

Eigen::MatrixXd V;
Eigen::MatrixXi F;

int main(int argc, char *argv[])
{

  std::vector<std::vector<int>> neighboor;

  // Load a mesh in OFF format
  igl::readOBJ(argv[1], V, F);

  std::cout << "Loaded (V, F).size() = " << "(" << V.rows() << ", " << F.rows() << ")" << std::endl;

  igl::adjacency_list(F,neighboor,true);

  int i = 0;
  for(const auto & list : neighboor)
  {
    std::cout << "neigh(" << (i++) << ") = {";
    for(const auto & neigh : list)
    {
      std::cout << neigh << " ";
    }
    std::cout << "};" << std::endl;
  }

  // Plot the mesh
  igl::opengl::glfw::Viewer viewer;
  viewer.data().set_mesh(V, F);
  viewer.launch();
}
```

Which I need to update to remove faces around a certain vertex. The idea would be:

```
1. Fix v vertex in V
2. `Nk = k-neighbours of v //these the the neigbours in ring 0,..,k
3. `remove vertices in Nk`
```

I can't figure what function I'm supposed to use for this job, the closest thing I believe I should look at is:

`https://github.com/libigl/libigl/blob/master/include/igl/remove_unreferenced.h`

Am I right? or is there a different function for the purpose? If this is the function I'm not really sure of the input I need to provide.

Can you please clarify?

Thank you
...

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] macOS
- [x] Linux

**Comment by jdumas** [comment]
For removing faces I'd suggest first tagging all the faces you want to remove in a big buffer, then doing another pass on the face array to actually remove/resize the array. Libigl's data structures are not well suited for representing dynamic meshes. I would suggest you investigate alternative data structures such as OpenMesh if that is your goal.

**Comment by lukkio88** [comment]
Wouldn't this be a matter of labelling the faces and just remove the related rows in `MatrixXi` representing the faces then? I know the question seems trivial, but I'm just checking there isn't an ad hoc function for the purpose.

**Comment by jdumas** [comment]
Yes.
