### ISSUE TITLE
Correct use of Gaussian curvature?

### ISSUE THREAD

**Issue by lukkio88** [libigl/libigl#1532]
Hi,

I'm running the example 202_GaussianCurvature on a small mesh I have. The mesh isn't watertight so it's open.

The behaviour I'm getting is that the boundary seems to have the highest curvature, which doesn't seem quite likely to me.

Is it possible I need to preprocess the mesh in order to apply the method?

I was hoping I could use this to detect some bumps in my mesh, but what I get is like uniform with a sudden change on the boundary of the mesh.

(I'll try with other meshes, in case I'll post results which might be useful to explain the problem).

...

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] macOS
- [x] Linux

**Comment by lukkio88** [comment]
Correction... I'm probably not using it correctly. Like the mesh below (same example) I get a curvature that seems constant.

![curvature](https://user-images.githubusercontent.com/7476182/83193272-a0689f00-a12e-11ea-8efc-cb377e6f72d1.PNG)

**Comment by alecjacobson** [comment]
Might be the normalization for the set_data. Did you check the values?

**Comment by lukkio88** [comment]
For this specific mesh, the one in the picture. I get these two values for the vector `K`

```
Min : -77.0688
Max : 229.905
```

Does this have anyhing to do with the colouring then? is there a way for me to visualize the curvature? I'd really need to see this.

**Comment by alecjacobson** [comment]
Yeah, so probably there's just a few vertices with the extreme values and
then everything else is in a small range being mapped to the same color.

You can normalize the data yourself or provide the ranges you'd like to
look at.
-Alec

>

**Comment by lukkio88** [comment]
For this specific mesh `229.905` and `-77.0688` are max and min. They don't look like extreme values to me. Also I've tried a completely flat mesh and I'm getting as min and max the following:

```
min := -1.84911e-09
max := 2.55641e+06
```

I can't really justify that huge max value, but they're calculated at the boundary of the mesh.

**Comment by BruegelN** [comment]
Related: https://github.com/libigl/libigl/issues/516.
Maybe try via principal curvatures instead (K=k1k2).

**Comment by alecjacobson** [comment]
by "extreme values" I meant maximum and minimum values (as in extrema).
Suppose most of the values are in the range [-2,+2], then if the color
range goes from -77 to 229, you won't be able to see them.

**Comment by brupelo** [comment]
Hi guys, I'm curious, I've been reading some papers talking about gaussian&mean curvature computation (ie: http://www.multires.caltech.edu/pubs/diffGeoOps.pdf) but none of them expose the method you implemented in libigl using this concept of internal angles.

- https://github.com/libigl/libigl/blob/master/include/igl/gaussian_curvature.cpp
- https://github.com/libigl/libigl/blob/master/include/igl/internal_angles.cpp#L33

Could anyone please clarify and post the paper referencing such formulas and derivations? I'd like to understand how correct is such method in comparison to others.

Thanks.

**Comment by alecjacobson** [comment]
see section 4.1 of the paper you linked to.

**Comment by brupelo** [comment]
@alecjacobson Cool, thanks to clarify! Btw, any particular reason why using that expressions instead (9) from section 4.2? 

If you take a look at section 3.4 Fig.4, `A_mixed` is intended to handle both obtuse & acute triangles, on the other hand section 4.1 says:

> Therefore, the integral of the Gaussian curvature (also called total curvature) for non-obtuse triangulations is: 2π −j θj . This result is still valid for the mixed region and is proven using a similar geometric argument.

**Comment by alecjacobson** [comment]
I think just convenience.

>
