### ISSUE TITLE
Unresolved externals link error while using readPLY()

### ISSUE THREAD

**Issue by lslog3** [libigl/libigl#1533]
#### Describe your question

Using readPLY() with the inputs more than F and V results "Unresolved externals" link error. Anyone saw this issue?

See codes:
int main(int argc, char *argv[])
{
  Eigen::MatrixXd V;
  Eigen::MatrixXi F;
  Eigen::MatrixXd temp_V;
  Eigen::MatrixXi temp_F;
  Eigen::MatrixXd N, E;
  Eigen::MatrixXd UV;
  Eigen::MatrixXd VD;
  std::vector<std::string> Vheader;

  // Load a mesh
  // igl::readPLY("D:/laurana500_trim_clean.stl", temp_V, temp_F, N, UV, VD, Vheader);
  igl::readPLY("D:/laurana500_trim_clean.stl", temp_V, temp_F, E);
.....

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by jdumas** [comment]
Are you having an issue with the *compilation*, or an issue at runtime when trying to load the mesh? It looks like you are trying to read a .stl file, which is a different file format than .ply. Alternatively you can try to use `igl::read_triangle_mesh` which will choose the correct loader based on the file extension.

**Comment by lslog3** [comment]
> Are you having an issue with the _compilation_, or an issue at runtime when trying to load the mesh? It looks like you are trying to read a .stl file, which is a different file format than .ply. Alternatively you can try to use `igl::read_triangle_mesh` which will choose the correct loader based on the file extension.

It is an issue with the compilation. Never get through the VS building.
Sorry to make it mixed. The file I am trying to load is PLY. I have corrected it, but again it doesn't get through compiling. 

1>main.obj : error LNK2019: unresolved external symbol "bool __cdecl igl::readPLY<class Eigen::Matrix<double,-1,-1,0,-1,-1>,class Eigen::Matrix<int,-1,-1,0,-1,-1>,class Eigen::Matrix<double,-1,-1,0,-1,-1>,class Eigen::Matrix<double,-1,-1,0,-1,-1>,class Eigen::Matrix<double,-1,-1,0,-1,-1> >(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class Eigen::PlainObjectBase<class Eigen::Matrix<double,-1,-1,0,-1,-1> > &,class Eigen::PlainObjectBase<class Eigen::Matrix<int,-1,-1,0,-1,-1> > &,class Eigen::PlainObjectBase<class Eigen::Matrix<double,-1,-1,0,-1,-1> > &,class Eigen::PlainObjectBase<class Eigen::Matrix<double,-1,-1,0,-1,-1> > &,class Eigen::PlainObjectBase<class Eigen::Matrix<double,-1,-1,0,-1,-1> > &,class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > &)" (??$readPLY@V?$Matrix@N$0?0$0?0$0A@$0?0$0?0@Eigen@@V?$Matrix@H$0?0$0?0$0A@$0?0$0?0@2@V12@V12@V12@@igl@@YA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAV?$PlainObjectBase@V?$Matrix@N$0?0$0?0$0A@$0?0$0?0@Eigen@@@Eigen@@AEAV?$PlainObjectBase@V?$Matrix@H$0?0$0?0$0A@$0?0$0?0@Eigen@@@4@111AEAV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@2@@Z) referenced in function main

**Comment by jdumas** [comment]
Ok can you try with `LIBIGL_USE_STATIC_LIBRARY=OFF`?

**Comment by lslog3** [comment]
> Ok can you try with `LIBIGL_USE_STATIC_LIBRARY=OFF`?

I have turned off LIBIGL_USE_STATIC_LIBRARY in CMake. Still saw this unresolved external error.

**Comment by jdumas** [comment]
Please delete your build folder and try again.
