### ISSUE TITLE
How to upgrade from legacy libigl to current version

### ISSUE THREAD

**Issue by AndreeaRadoescu** [libigl/libigl#1536]
#### Describe your question
Hi, I am in the process of setting up some code on my workstation and I was trying to figure out for quite a while how to compile the old python bindings in order to get the `pyigl.so`. 

I have it set up on another computer but I don't remember from where did I manage to put together the folder that somehow looks like the legacy repo but not quite. The libigl-legacy repo has the python folder but the cmake file is missing. The current libigl repo has a cmake file but the python bindings are separated into another repo. And for some reason the folder that I have on the other computer has the python folder and the cmake file but I don't remember how did I put that together (I thought I downloaded the repo but I'm not sure anymore).

Now, I could just copy over the `pyigl.so` and be done with it, but I would like to be able to do it in a nicer way than just depending on an old compiled library. 

Furthermore, I have somewhere a file that I assume was part of libigl at some point (it's called `iglhelpers.py`) that contains 2 functions which are used quite a lot in my code : `p2e` and `e2p`. These are conversion functions between numpy arrays and eigen matrices. 

I would like to upgrade my code to use the new libigl, new python bindings and all, but I am at a loss to where should I start. I only found documentation for the new libigl library and I don't know what the functions from the old libigl were doing. 
How should I go about this? 
...

#### Check all that apply (change to `[x]`)
- [ x ] Windows
- [ x ] macOS
- [ x ] Linux

**Comment by jdumas** [comment]
Are you asking about the python bindings specifically, or about the C++ library as well? The new python bindings are distributed through conda, and this is the recommended way to install them. The API is also different (now it uses numpy arrays), and the viewer is also different (it is based on pythreejs). Despite all this changes, the function names should mostly be the same. The only functions that were removed are features that are provided by numpy directly (e.g. slicing) or are no longer needed (e.g. conversion to/from eigen matrices).

**Comment by AndreeaRadoescu** [comment]
I was referring to the python bindings yes. 
So basically all the conversion functions are removed and I can work straight with the numpy arrays in that case? 
Is there some documentation for the old library in the way that there is now on the website for the new one?

**Comment by jdumas** [comment]
Yes you can now work directly with numpy arrays now. Regarding the old documentation we never had a lot to begin with. You can checkout d6558dbce790cdb0f92fadefce20796615aa49c3 on https://libigl.github.io/ and build the website locally with `mkdocs serve` if you want to check it out. But really the name of the functions haven't changed, so I'd advise to just go over your code and update manually. If you had any viewer code you might as well rewrite it from scratch.

**Comment by AndreeaRadoescu** [comment]
Ok! That sounds nice then. 
I'll try to update manually and if I get stuck, I'll check out the documentation, Thanks for telling me where to look.
When you mean the viewer code, do you refer to the `glfw`  viewer that was there or?

**Comment by jdumas** [comment]
Yes, I am referring to the glfw viewer.

**Comment by AndreeaRadoescu** [comment]
Ok, I understand. Thanks a lot for the help :)
