### ISSUE TITLE
Cut mesh along isolines

### ISSUE THREAD

**Issue by ioannaMitropoulou** [libigl/libigl#1537]
#### Describe your question
I am using `igl::isolines` on a mesh with to create the isolines of a scalar function on the vertices. The resulting edges and vertices lie on the mesh, but they are not part of the mesh (i.e. the newly created points are in different locations than the mesh vertices). As a result, I cannot use the `igl::cut_mesh`. I was wondering if there is an alternative method in igl for cutting a mesh along an isoline. If not, could you recommend me some approach?

Also, regarding the `igl::isolines` the result is a list of vertices and edges. I was wondering how I can find what level of my scalar field each one of the created curves belongs to. 

I attach a screenshot of the cuts that I am trying to create.

Thanks,
Ioanna
 
![Capture](https://user-images.githubusercontent.com/17250275/83304264-d7a68100-a1fe-11ea-8835-77c9225237a8.PNG)

...

#### Check all that apply (change to `[x]`)
- [ X ] Windows
- [ ] macOS
- [ ] Linux

**Comment by jdumas** [comment]
I don't think we have that feature yet in libigl. But the code from `igl::isolines` should be simple to modify and adapt to your needs. Basically you're running marching triangles to find out how each triangle is "cut" by the isolines of your function. It should be a simple modification to generate a new subdivided mesh with a list of vertices/edges tags indicating the location of the isoline. Then you'd be able to feed this subdivided mesh directly to `igl::cut_mesh()`

**Comment by alecjacobson** [comment]
I think you're looking for `igl::remesh_along_isoline`

**Comment by jdumas** [comment]
Oh nice, somehow I missed that one :D

**Comment by ioanna21** [comment]
Great, thanks a lot for your answer, I didn't know about this function. I have one follow up question. when I generate isolines for a mesh like the one I have posted, on some levels I have 1 closed curve, in some 2, 3, and so on. How can I identify which curve is coming from which level? 

Thanks,
Ioanna

**Comment by kappa95** [comment]
About this question, I don't understand how edges when isolines are extracted.

**Comment by alecjacobson** [comment]
@ioannaMitropoulou , the new isolines includes a `I` output for this https://github.com/libigl/libigl/blob/deae7a2767252f40490f92a499e32c396b8ce681/include/igl/isolines.h#L19

I'm not sure I understand @kappa95 's question. The edges are extracted by remeshing along the iso-level.

I'm closing this old issue, but feel free to reopen if there's more issues on this.
