### ISSUE TITLE
Unexplainable deformation after using ARAP (tutorial 405)

### ISSUE THREAD

**Issue by mzanin** [libigl/libigl#1539]
#### Describe your question

The issue I'm having is that the resulting geometry after ARAP does not produce a shape that makes sense to me. I'm at a loss as to what the the reason for this could be and would really appreciate any input on what I could be doing wrong. Note I used tutorial 405 as a starting point on understanding how to make use of ARAP. 

Below is an image of the state of the source geometry before deformation with the selection indices on the geometry shown in purple (the strip on the rim of the geometry) and the boundary conditions shown as green points (if there is a better way to visualize this in igl please let me know).

![image](https://user-images.githubusercontent.com/1013551/83790116-f93cb800-a697-11ea-8580-73b4c660f876.png)

and below are some images of the state after deformation. Note the unwanted bulge which is not present in the original source geometry. 

![image](https://user-images.githubusercontent.com/1013551/83790207-1b363a80-a698-11ea-9cea-55d973739ee4.png)

![image](https://user-images.githubusercontent.com/1013551/83790285-402aad80-a698-11ea-84ee-f2fbcf070071.png)

Below is the simplified source code used to obtain these results. Some additional details -
* None of the energy types improve the final shape. 
* Lowering the maximum iterations to below 10 results in a better shape. The bulge is gradually introduced the more iterations there are.
* Enabling with_dynamics also improves the shape but I don't really understand what this does. All I know is that the boundary conditions are no longer used.

```
int main(int argc, char *argv[])
{
    Eigen::MatrixXd vertices, initial_guess_vertices;
    Eigen::MatrixXi faces;
    Eigen::VectorXi selected_indices;
    igl::ARAPData arap_data;

    // the mesh which has already been transformed by a procrustes
    igl::readOFF(TUTORIAL_SHARED_PATH "/template.off", vertices, faces);
    
    // the mesh used for the initial guess which has undergone a procrustes transform
    // and a laplacian

    igl::readOFF(TUTORIAL_SHARED_PATH "/deformed.off", initial_guess_vertices, faces);
    igl::readDMAT(TUTORIAL_SHARED_PATH "/selection.dmat", selected_indices);
   
    // the boundary conditions are already defined in the deformed.off geometry so just 
    // use the selected indices to populate the boundary_conditions
    Eigen::MatrixXd boundary_conditions(selected_indices.size(), initial_guess_vertices.cols());
    for (int i = 0; i < selected_indices.size(); i++)
    {
        boundary_conditions.row(i) = initial_guess_vertices.row(selected_indices(i));
    }

    arap_data.max_iter = 100;
    arap_data.energy = igl::ARAPEnergyType::ARAP_ENERGY_TYPE_SPOKES;
    if (!igl::arap_precomputation(vertices, faces, vertices.cols(), selected_indices, arap_data))
    {
        return -1;
    }

    igl::arap_solve(boundary_conditions, arap_data, initial_guess_vertices);

    igl::opengl::glfw::Viewer viewer;
    viewer.data().set_mesh(initial_guess_vertices, faces);
    Eigen::MatrixXd colors = GetColors(faces, selected_indices);
    viewer.data().set_colors(colors);
    viewer.core().is_animating = false;
    viewer.core().animation_max_fps = 30.;
    viewer.launch();
}
```

...

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by danielepanozzo** [comment]
Could you please share the off and dmat files? I think the issues is that your constraints are imposing a non-isometric distortion on the boundary, and this is causing the "bending" that you are likely trying to avoid.

**Comment by alecjacobson** [comment]
It's hard to say that this is showing anything wrong with ARAP. Unfortunately it might just not be producing the result expected by the user in this case.

btw, you can use `writeOFF` and `writeDMAT` to write those file types (and you could use `readOBJ`/`readSTL` to read in meshes to write to .off; though I bet Daniele would have been happy with .obj). 

Closing this old issue, but feel free to reopen if there still might be something wrong with libigl here.
