### ISSUE TITLE
Does libigl decimator somehow preserve texture coordinates?

### ISSUE THREAD

**Issue by lukkio88** [libigl/libigl#1540]
Hi,

I was wondering if libigl decimator can preserve uv/texture coordinates of a given mesh.
I'm loading a mesh with texture coordinates using your `igl::readOBJ`. Ideally I would like the mesh to be remeshed (I've tried `instant-meshes` and `quadri-flow`) but none of them does seem to preserve UVs, so I'm considering some decimation scheme where I think it's more likely to find one where UVs are preserved. (I don't mean literally since the vertex count would be reduced, but I think you got my point).

The meshes I'm processing come from structure from motion like pipeline so they're quite big and relatively messy, they do come with UVs however.

To clarify my input mesh is an obj of the form

```
 v x0 y0 z0
 ..
 v xn yn zn
 vt u0 v0
 ..
 vt um vm
 f iv00/it00 iv01/it01 iv02/it02
 ...
 f ivl0/itl0 ivl1/itl1 ivl2/itl2
```

Namely I don't have a "color" per vertex, but texture coordinates per face.

It seems the `igl::decimate` call and `igl::qslim` can have vertex list of dimension `#V by N`, so eventually I could pass `x y z u v` and something would happen, but my input is unfortunately not formatted in the same way.

Any chance I can use this in a smart way to preserve somewhat UV's as well?

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] macOS
- [x] Linux

**Comment by jdumas** [comment]
Well it's not really well-defined what should happen when you want to contract two vertices where the incident corners have different uv values. You could build your own decimator to prevent collapsing vertices on a seam, but it's not gonna be supported out of the box...

**Comment by alecjacobson** [comment]
If the input is disk topology (and UV map is also disk topology with the same boundary), then libigl's decimator can handle UVs by appending the uvs as coordinates. Each vertex is in 5d [x y z u v]. Following "Simplifying surfaces with color and texture using quadric error metrics" [Garland & Heckbert 1998].

As Jeremie writes, things get more confusing if the input is a generic mesh with arbitrary topology with UV seams/cuts in arbitrary places. None of the exposes implementations in libigl using `decimate` will handle this **_but_** Songrun Liu's https://github.com/songrun/SeamAwareDecimater is built off of libigl's decimate (I believe it diverged a bit) and will handle all of the nasty cases. That method implements the paper "Seamless: Seam erasure and seam-aware decoupling of shape from mesh resolution" [Liu et al. 2017].
