### ISSUE TITLE
internal_angles to vertices?

### ISSUE THREAD

**Issue by wcheung-code** [libigl/libigl#1542]
#### Describe your question
I am curious if there is any functions that exists within the igl library where one can restore the parameters of `internal_angles`. Namely, I would like to reconstruct the vertices of the mesh provided the faces matrix.

Some sample code:

    vertices, faces = igl.read_triangle_mesh("data/bunny.obj")
    angles = igl.internal_angles(vertices, faces)

Is there any way to convert `angles` back to `vertices` given `faces`?

The goal is to use the angle based flattening (ABF) algorithm to create a map parameterization of a given .obj file. I know that LSCM is created, but will there be a function devoted to using ABF?

Thanks,
Wilson

...

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by alecjacobson** [comment]
In general, there might be no set of vertices that explains a set of
angles. There might also be an infinite number of surfaces (even beyond
translations and rotations of the surface. Imagine crumpled newspaper).

So, there's no canonical solution to this problem. Depending on your
setting, you might be able to set up an optimization problem that solves
for vertex positions in the least squares sense. You could use libigl to
set up and solve that but we don't have something readymade.
-Alec

**Comment by jdumas** [comment]
Note that if you have a tet mesh, it is possible to recover vertex position from dihedral angles. See this paper:
https://members.loria.fr/Bruno.Levy/papers/anglemaps_SIGGRAPH_2015.pdf

@alecjacobson is there an easy counter-example with a closed surface where the ambiguity is more than a rigid transform? For a newspaper it's easy to see, but for a closed surface it's less obvious to me.

**Comment by alecjacobson** [comment]
Imagine a concave bump getting popped into a convex one.
