### ISSUE TITLE
cork version of mesh_boolean does not work

### ISSUE THREAD

**Issue by fornit1917** [libigl/libigl#1548]
#### Describe the bug

I built libigl with cork on Windows, and when I called igl::copyleft::cork::mesh_boolean, I got "access violation" error inside cork code.
Exception was thrown in file libigl\external\cork\src\isct\triangle.c (see screenshot below)

![image](https://user-images.githubusercontent.com/1011149/84866056-dd66e800-b081-11ea-9788-01536eabc8bf.png)

My code:

```
	Eigen::MatrixXd VA, VB, VC;
	Eigen::MatrixXi FA, FB, FC;
	igl::MeshBooleanType boolean_type(igl::MESH_BOOLEAN_TYPE_UNION);

	igl::readOBJ("D:\\tmp\\meshes\\teapot.obj", VA, FA);
	igl::readOBJ("D:\\tmp\\meshes\\cow.obj", VB, FB);

	std::cout << "Start\r\n";
	igl::copyleft::cork::mesh_boolean(VA, FA, VB, FB, boolean_type, VC, FC);
	igl::writeOBJ("D:\\tmp\\meshes\\result.obj", VC, FC);
	std::cout << "Finish\r\n";
```

I get this error on any meshes. You can download meshes from my example (teapot.obj and cow.obj) here: https://groups.csail.mit.edu/graphics/classes/6.837/F03/models/

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] macOS
- [ ] Linux

On linux it works fine, but on Windows I get an error.

**Comment by amakhno** [comment]
The same problem with Win, but works perfectly on Ubuntu 20

**Comment by merlinyx** [comment]
I had the same problem on windows as well; thank you for the fix!

**Comment by Kanteloper** [comment]
I'm sorry but I am still having this problem though using your modified code. 
My environment is,
Windows / VS2019 / x64

**Comment by Kanteloper** [comment]
I'm sorry but I'm still having this problem though using your solution. Of course, I've tested using your sample code and OBJ files. (in DEBUG mode)
My environment is Windows / VS2019 / x64

**Comment by Kanteloper** [comment]
Thank you for your fix! It works well in Windows / VS2019 / x64 environment.

**Comment by alecjacobson** [comment]
No longer supported and part of libigl but you could try https://github.com/libigl/libigl-cork
