### ISSUE TITLE
PNG Module

### ISSUE THREAD

**Issue by teseoch** [libigl/libigl#1550]
#### Describe your feature request

The current PNG module is mixed with texture loads.

The png reader/writer should be separated from the texture parts

#### Check all that apply (change to `[x]`)
- [x] Windows
- [x] macOS
- [x] Linux

**Comment by jdumas** [comment]
Related discussion in #1417. I agree that that the PNG module should be reworked. But putting `readPNG` directly into `igl::core` is problematic due to the header-only requirement of libigl (which is a mistake imho).

**Comment by teseoch** [comment]
We could leave the png read/write in its module, and move the textures in the OpenGL target.

**Comment by jdumas** [comment]
It will be a sorry module with only 2 functions, but yeah that would be a first step...

**Comment by teseoch** [comment]
true
