### ISSUE TITLE
singed distance doesn't compile

### ISSUE THREAD

**Issue by Da-Rudi** [libigl/libigl#1552]
Hello! 
I'm feeling a bit stupid right now but asking myself what exactly am I doing wrong with this little peace of code:

```
    #include <igl/signed_distance.h>  
    struct Mesh {
        Eigen::MatrixXd vertices;
        Eigen::MatrixXi faces;
    };

    void MeshCalculator::CalculateMinSignedDistance(Mesh part_a, Mesh part_b) {
    Eigen::MatrixXd S,C,N; 
    Eigen::MatrixXi I;
    igl::signed_distance(part_b.vertices,
                         part_a.vertices,
                         part_a.faces,
                         igl::SIGNED_DISTANCE_TYPE_WINDING_NUMBER,
                         0.0,
                         2048.0, S, I, C, N);
    }

```

And it complains while linking with:

Undefined symbols for architecture x86_64:
  "void igl::signed_distance<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1> >(Eigen::MatrixBase<Eigen::Matrix<double, -1, -1, 0, -1, -1> > const&, Eigen::MatrixBase<Eigen::Matrix<double, -1, -1, 0, -1, -1> > const&, Eigen::MatrixBase<Eigen::Matrix<int, -1, -1, 0, -1, -1> > const&, igl::SignedDistanceType, Eigen::Matrix<double, -1, -1, 0, -1, -1>::Scalar, Eigen::Matrix<double, -1, -1, 0, -1, -1>::Scalar, Eigen::PlainObjectBase<Eigen::Matrix<double, -1, -1, 0, -1, -1> >&, Eigen::PlainObjectBase<Eigen::Matrix<int, -1, -1, 0, -1, -1> >&, Eigen::PlainObjectBase<Eigen::Matrix<double, -1, -1, 0, -1, -1> >&, Eigen::PlainObjectBase<Eigen::Matrix<double, -1, -1, 0, -1, -1> >&)", referenced from:
      MeshCalculator::CalculateMinSignedDistance(MeshCalculator::Mesh, MeshCalculator::Mesh) in MeshCalculator.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ x] macOS
- [ ] Linux

**Comment by jdumas** [comment]
Can you try to compile libigl with `LIBIGL_USE_STATIC_LIBRARY=OFF` ?

**Comment by Da-Rudi** [comment]
This seems to work now, thanks :)
