### ISSUE TITLE
How to set the background image of the viewport

### ISSUE THREAD

**Issue by youngallien** [libigl/libigl#1555]
#### Describe your question
I would like to set the background  image for each viewport and how can i do it?
...

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by alecjacobson** [comment]
There's no easy way to set a background image. You could draw a single full screen quad in the predraw callback and make sure the depth buffer is clear.

If somebody wanted to submit a PR with this I'd probably merge it but I'm not going to implement this myself.
