### ISSUE TITLE
Compiling tutorial examples on Windows

### ISSUE THREAD

**Issue by xieanne** [libigl/libigl#1557]
Hi, I am trying to compile libigl on Windows. I have followed the tutorial and downloaded libigl, and I built it using visual studios. But when I trying to run the code, it gives me this error. 
![image](https://user-images.githubusercontent.com/44624612/86025975-e0a49100-b9fc-11ea-827a-a5c5750ee72d.png)
I am wondering what might be the issue that causes this problem. Thank you!

**Comment by jdumas** [comment]
You need to set your startup project to be the tutorial that you want to run.

**Comment by xieanne** [comment]
I am sorry that I didn't quite understand what you mean by set your startup project. So I open libigl from the build folder and open the libigl.sln, and I build the entire solution. But how can I set the project to be the tutorial I want (e.g. the Laplacian tutorial)?

**Comment by xieanne** [comment]
I got the startup project part, thank you!
