### ISSUE TITLE
Gptoolbox vs libigl

### ISSUE THREAD

**Issue by csverma610** [libigl/libigl#156]
Hello,

Are there some special modules which are part of gptoolbox and not
Libigl ? Does libigl contain all the modules of gptoolbox ?

Thanks

**Comment by alecjacobson** [comment]
Some functions in libigl & gptoolbox are identical. Some functions implement similar things in different ways. Some functions only exist in gptoolbox, and some only exist in libigl. Meanwhile, certain things are much faster implemented in C++ or depend on C++ libraries so gptoolbox has "mex" functions calling libigl functions.
There's no real attempt, or will there be, for gptoolbox or libigl to be organized together.
