### ISSUE TITLE
Build started: Project: igl, Configuration: Debug x64

### ISSUE THREAD

**Issue by Lennon-di** [libigl/libigl#1566]
I'm a newbie, using visual studio 2019 on windows 10. When I debug the tutorial 101_FileIO_bin , I get this: 
1>------ Build started: Project: igl, Configuration: Debug x64 ------
1>planarize_quad_mesh.cpp
1>polar_svd.cpp
1>principal_curvature.cpp
1>project.cpp
1>project_to_line.cpp
1>pseudonormal_test.cpp
1>qslim_optimal_collapse_edge_callbacks.cpp
1>ramer_douglas_peucker.cpp
1>random_points_on_mesh.cpp
1>random_quaternion.cpp
1>random_search.cpp
1>randperm.cpp

...
It keeps on going, but i canceled it, since it doesn't seem to be right and takes much time. What am I doing wrong here?
Thanks!

**Comment by jdumas** [comment]
Well yes compiling libigl takes time...
