### ISSUE TITLE
Different behaviour of igl::point_mesh_squared_distance

### ISSUE THREAD

**Issue by lukkio88** [libigl/libigl#1567]
Hi, I'm running literally the same code on windows and link, and it gives correct results on linux but not on windows..
I've noticed in the [implementation](https://github.com/libigl/libigl/blob/master/include/igl/point_mesh_squared_distance.cpp) there's a special `#ifdef WIN32` which I'm not sure messes things up.

Is this a bug? Or maybe I need to use the function differently on windows.

The call is literally this simple:

```
igl::point_mesh_squared_distance(
            minimizer, //Eigen::MatrixXd
            mVertex, //Eigen::MatrixXd
            mFace, //Eigen::MatrixXi
            squaredDistances, //Eigen::MatrixXd
            triangleIndices, //Eigen::MatrixXi
            closestPoints); //Eigen::MatrixXd
```

**Update**: I actually was running v2.1.0, I spot a difference in this very specific function. I've tried to build with the latest tag and it seems better (still wrong) but this might be due to me.

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] macOS
- [x] Linux

**Comment by alecjacobson** [comment]
the `ifdef WIN32` is just for the templates not the code. It shouldn't affect it but feel free to post a minimal complete example that triggers the issue if this is still a problem.
