### ISSUE TITLE
Laplacian function parameters

### ISSUE THREAD

**Issue by xieanne** [libigl/libigl#1569]
#### Describe your question
Hi, sorry to bother you guys again with this question. But I want to know for the Laplacian method, is there any parameters that I can alter so it can produce a different result? Such us, every single time we press 'space', how many iterations of smoothing is being done, and where did you decide what is the factor that is being reduced. Because currently, when I import the original geometry as you can see in the first graph, when I press 'space' once, the geometry does not change. Only when I press the 'space' the second time, the geometry will become like the second graph. But I feel like it is being reduced too much, so I am wondering if there is any parameters in the code that controls how much the geometry is being smoothed? Thank you! 
(The first graph is the original geometry, second graph is when I press "space" once which there is no change, and the third graph is when I press "space" again)
![image](https://user-images.githubusercontent.com/44624612/87705455-e542a680-c76b-11ea-82ab-91f974c8270d.png)
![image](https://user-images.githubusercontent.com/44624612/87705548-0c00dd00-c76c-11ea-8325-36133f638bf6.png)
![image](https://user-images.githubusercontent.com/44624612/87705482-f1c6ff00-c76b-11ea-9f97-a3905328c7fa.png)

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by HollowSun0** [comment]
Random comment but if you wish to apply a Laplacian smoothing while preserving the volume, you can implement the HC Laplacian Smoothing algorithm like shown here: https://pdfs.semanticscholar.org/5ca9/11cd0c1c2feba9e863f56def364ab5abe51d.pdf

**Comment by jiangzhongshi** [comment]
Assuming you mean the Laplacian example from the tutorial,

The behavior of the space key is defined here, and each time one implicit step is performed. 
https://github.com/libigl/libigl/blob/master/tutorial/205_Laplacian/main.cpp#L54

You can try to insert a few debug lines to trace its execution and see whether the geometry is really changing or not, and occasionally, it might be possible that the first keystroke is not captured for some reason.

**Comment by xieanne** [comment]
Yes, it is the laplacian example from the tutorial. I am just wondering if there is any parameter that can be altered to reduce the smoothing?

**Comment by jiangzhongshi** [comment]
You can change the parameter in line 60 before L to alter the speed of smoothness

**Comment by xieanne** [comment]
Thank you so much! And just another followup question, can this application apply to open surfaces?

**Comment by jiangzhongshi** [comment]
I think you need some special treatment on the boundary for it to work (for example, fixing the coordinates in the linear system, or use a fake vertex, but you can try it out for fewer iterations.

**Comment by alecjacobson** [comment]
Feel free to continue this as a [discussion](https://github.com/libigl/libigl/discussions) rather than an issue.
