### ISSUE TITLE
Passing varargin in matlab

### ISSUE THREAD

**Issue by csverma610** [libigl/libigl#157]
Hello

How can we pass varargin or optional arguments in libigl matlab interface ?

Thanks
Csv

**Comment by alecjacobson** [comment]
I'm not sure what exactly you mean. Do you have a particular function in mind? Or are you referring to the `igl::matlab::MatlabInterface`?

**Comment by csverma** [comment]
Hello,

It seems that there are few very important modules in gptoolbox which I wish were part of libigl C++.
One of them is "MeshUntangle" which has varargin (similarly many others).  I googled for interfacing
varargin with C++, but found no clear directions. Is there any short cut of passing additional arguments
with igl matlab interface ?

Thanks.
csv

**Comment by alecjacobson** [comment]
I'm not exactly sure what you'd like to do.

1. Would you like to call the `untangle` matlab function from a C++
application? or

2. Are you trying to reimplement a similar function in C++? or

3. Something else?
