### ISSUE TITLE
Compilation error in a very simple code using assign_scalar (Gmpq and Eigen)

### ISSUE THREAD

**Issue by glirunjohn** [libigl/libigl#1570]
Copied a project onto a new machine a few days ago and I just can't get it to compile. I extracted a tiny piece of code which causes errors. I hope that solving this problem will fix everything else.

The error:
```
.../libigl/include/igl/copyleft/cgal/assign.cpp:21:20: error: no matching function for call to ‘assign_scalar(const CGAL::Lazy_exact_nt<boost::multiprecision::number<boost::multiprecision::backends::gmp_rational> >&, Eigen::DenseCoeffsBase<Eigen::Matrix<CGAL::Lazy_exact_nt<CGAL::Gmpq>, -1, 3>, 1>::Scalar&)’
       assign_scalar(C(i,j),D(i,j));
       ~~~~~~~~~~~~~^~~~~~~~~~~~~~~
```

The code:
```
#include <igl/copyleft/cgal/trim_with_solid.h>
#include <Eigen/Dense>
#include <CGAL/Lazy_exact_nt.h>
#include <CGAL/Gmpq.h>
typedef CGAL::Lazy_exact_nt<CGAL::Gmpq> FT;
typedef Eigen::Matrix<FT, Eigen::Dynamic, 3> VertexMat;
typedef Eigen::Matrix<int, Eigen::Dynamic, 3> FaceMat;

void libiglTrim(const VertexMat &vertexMat1, const FaceMat &objFaceMat1,
	const VertexMat &vertexMat2, const FaceMat &objFaceMat2,
	VertexMat &outVertexMat, FaceMat &outFaceMat,
	Eigen::Matrix<bool, Eigen::Dynamic, 1> &objIMat, Eigen::Matrix<int, Eigen::Dynamic, 1> &objJMat)
{ igl::copyleft::cgal::trim_with_solid(vertexMat1, objFaceMat1, vertexMat2, objFaceMat2, outVertexMat, outFaceMat, objIMat, objJMat); }
```

I tried to look for a similar issue but there's not many and there were no solutions that worked for me. I tried changing the CMakeLists file in a few ways but it was of no use. I have no idea where to look for a solution to this error anymore, does anybody have any clues? I suspect that it might be something very simple, yet I just can't solve it whatever I try.
Thanks very much in advance.

This applies to:
- [ ] Windows
- [ ] macOS
- [x] Linux

**Comment by jiangzhongshi** [comment]
It seems that `assign_scalar` is implemented for types in `copyleft/cgal/assign_scalar.h`, it may worth trying to overload it for your type specifically in a similar manner.

**Comment by alecjacobson** [comment]
This is more of a feature request and its not clear that it's one that makes sense in libigl or just as a snippet for this use case. Feel free to propose a PR if it does make sense though.
