### ISSUE TITLE
Q: How to install libigl without GPL dependencies?

### ISSUE THREAD

**Issue by Chandler** [libigl/libigl#1571]
I would like to install libigl + python bindings in a commercial setting that is not GPL compatible.

I've seen this folder https://github.com/libigl/libigl/tree/master/include/igl/copyleft
Is this an exhaustive list of the GPL deps or is this organization still in progress?

I am also not sure how to generate the python bindings in a way that does not include the igl::copyleft namespace.

Thanks!

**Comment by danielepanozzo** [comment]
The new python bindings published on conda are by default not including any function in the copyleft folder: https://libigl.github.io/libigl-python-bindings/

**Comment by jdumas** [comment]
Please note that some modules, such as `triangle/`, `matlab/` or `mosek/`, while not under GPL, depends on non-free licenses that are not compatible with commercial code. You best bet is to grab anything that is directly under the `include/igl` folder, that only depends on Eigen, and compile Eigen with the `EIGEN_MPL2_ONLY` flag.

**Comment by Chandler** [comment]
@jdumas If I come up with an explicit list of libigl cpp files that I want to include in my custom build could you give me a hint about where in this file I would swap in that list.
https://github.com/libigl/libigl-python-bindings/blob/master/CMakeLists.txt

I'm not very familiar with cmake and I'm a little confused about if this can be done entirely from the `libigl-python-bindings` or if it requires modifying the libigl cpp cmake file too.

Thanks!

**Comment by teseoch** [comment]
if you need the bindings, install them with conda, https://anaconda.org/conda-forge/igl

**Comment by alecjacobson** [comment]
With the new pip build, you'd just have to disable the copyleft in the cmake build. Feel free to reopen if needed.
