### ISSUE TITLE
imgui.h not found

### ISSUE THREAD

**Issue by M45t3rL4** [libigl/libigl#1572]
#### Describe your question
Hey,
I am trying to implement my own viewer menu as in example 106. My CMakeList.txt includes:

option(LIBIGL_WITH_OPENGL_GLFW_IMGUI "Use IMGUI"           ON)
target_link_libraries(${PROJECT_NAME}_bin igl::core igl::opengl igl::opengl_glfw igl::opengl_glfw_imgui)

And is compiling correctly, however if I add:

#include <igl/opengl/glfw/imgui/ImGuiMenu.h>
#include <imgui/imgui.h>

in my main.cpp it tells me that it cannot open the sourcefile imgui/imgui.h in both cases, in the first due to the dependencies of ImGuiMenu and in the second directly so. I tried clearing my cache multiple times as well as reinstalling a "clean version". 
The example compiles and works fine, only once i start trying to extend the blank example project to include its own viewer menu it fails to find the header.
I am using VS Community 2019 amd 64 as compiler kit and visual code as ide.

Thanks for your help
...

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by jdumas** [comment]
You need to set the CMake option before you do `find_package(libigl)`, and then clear your CMake cache again before you generate the project. If you open CMake GUI or look into the CMakeCache.txt file, you should be able to see the actual value of `LIBIGL_WITH_OPENGL_GLFW_IMGUI`.

**Comment by M45t3rL4** [comment]
Thank you for the fast reply and sorry if i was unclear, my CMake file looks like this:
cmake_minimum_required(VERSION 3.1)
project(example)

set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${CMAKE_CURRENT_SOURCE_DIR}/cmake)

# libigl
option(LIBIGL_WITH_OPENGL            "Use OpenGL"         ON)
option(LIBIGL_WITH_OPENGL_GLFW       "Use GLFW"           ON)
option(LIBIGL_WITH_OPENGL_GLFW_IMGUI "Use IMGUI"           ON)

find_package(LIBIGL REQUIRED QUIET)

# Add your project files
file(GLOB SRCFILES src/*.cpp)
add_executable(${PROJECT_NAME}_bin ${SRCFILES})
target_link_libraries(${PROJECT_NAME}_bin igl::core igl::opengl igl::opengl_glfw igl::opengl_glfw_imgui)

The value in the Cache File is ON

**Comment by jdumas** [comment]
Can you post a minimal example? Linking against `igl::opengl_glfw_imgui` should be enough to use ImGui. Let me know if you can compile and run tutorial 106_ViewerMenu with the latest libigl from `master`, as it uses ImGui as well.

**Comment by M45t3rL4** [comment]
I have been able to make it work on a different machine. I will try to fix it on the original one and if I can track down the error i made i will add that information here. Thank you for your support
