### ISSUE TITLE
Compile the laplacian function into a dll

### ISSUE THREAD

**Issue by xieanne** [libigl/libigl#1576]
#### Describe your question
Hi, I am wondering if it is possible for me to compile the Laplacian function into a dynamic link library? I am not that familiar with dll so I am wondering if it is possible? Thanks!

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by jdumas** [comment]
You don't need a dll, as the code is header-only. Just include what you need and you should be good to go.

**Comment by xieanne** [comment]
Because I only want to use the Laplacian method, so I want to make a dll that only defines the Laplacian method so that it can be used in another application.

**Comment by jdumas** [comment]
Even with a DLL you're gonna need a header to define the function API. Since libigl code is header-only, there is nothing to "compile" into a DLL, you don't have to do anything special.
