### ISSUE TITLE
laplacian tutorial code question

### ISSUE THREAD

**Issue by xieanne** [libigl/libigl#1577]
#### Describe your question
Hi, sorry to bother you guys again. But I am wondering what are the V and F in this Laplacian tutorial? Are they triangles and vertices of the geometry? Because I want to write a function that gets the input of the geometry instead of using the readOff function, I want the inputs to be std::vector<int> triangles and std::vector<double> vertices. Thanks! 
![image](https://user-images.githubusercontent.com/44624612/88578151-19dd1a80-d016-11ea-89df-a34b560d53c8.png)

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by jdumas** [comment]
This is explained in the [tutorial](https://libigl.github.io/tutorial/#mesh-representation).

**Comment by xieanne** [comment]
Thanks!
