### ISSUE TITLE
Crash in miq.cpp/getVerticesPerSeam

### ISSUE THREAD

**Issue by huxingyi** [libigl/libigl#1579]
#### Describe the bug

The app will crash on the following line because of visit front of an empty list:
https://github.com/libigl/libigl/blob/48ac6aa0b5ef9286c95874042cfe68965bc94f29/include/igl/copyleft/comiso/miq.cpp#L503

If I change following line to `for (size_t j = 0; j < neighborSize && !startVertexNeighbors->empty(); j++)`, it works properly on my test model(1). I am not sure if it's a correct fix, or just suppressed the symptoms.
https://github.com/libigl/libigl/blob/48ac6aa0b5ef9286c95874042cfe68965bc94f29/include/igl/copyleft/comiso/miq.cpp#L491

BTW, the frame field deforming method for miq is really a fantastic thought. Thanks for the state of the art work!

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] macOS
- [ ] Linux

(1): Reproducing obj file and frame field mat for 506_FrameField: [libigl-miq-crash-test.zip](https://github.com/libigl/libigl/files/5010072/libigl-miq-crash-test.zip)

**Comment by alecjacobson** [comment]
I'm not personally fixing anything in the comiso module. Happy to merge a pr if others do.
