### ISSUE TITLE
surface mesh registration

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#158]
From personal email:

> How can one use libigl for surface mesh registration ?
> I think as of now no such implementation is present in libigl.
Please excuse, I am very new to libigl, I was searching for some geometry library for surface mesh registration and got to know about libigl

**Comment by alecjacobson** [comment]
There isn't a full implementation of surface mesh registration, but many of the pieces you might need exist: `igl::point_mesh_squared_distance` for finding closest points, `igl::cotmatrix` and `igl::massmastrix` or `igl::arap` for constructing a smoothness/regularization term if conducting deformable registration, and `igl::fit_rotations` for finding best fit rotations if conducting rigid registration. 

I've implemented the iterative closest point registration method (ICP) in the matlab library [gptoolbox](https://github.com/alecjacobson/gptoolbox/blob/master/mesh/icp.m), which you _could_ use that as a guide. But I'd actually recommend looking at Sofien Bouaziz and Andrea Tagliasacchi's recent SGP 2015 course notes. I think they also had some code...

**Comment by Namdhari** [comment]
The link of the above mentioned course notes
http://lgg.epfl.ch/publications/2014/2d3dRegistration/

**Comment by rahulTrial** [comment]
Sorry, I know this is not related to libigl, but I have a question regarding the implementation from the paper, <a href="https://www.codecogs.com/eqnedit.php?latex=\mathbf{z}_i^{t&plus;1}&space;-&space;(\mathbf{\tilde{R}}&space;(\mathbf{R}^{t}\mathbf{x}_i&space;&plus;&space;\mathbf{t}^t)&space;&plus;&space;\mathbf{\tilde{t}})" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\mathbf{z}_i^{t&plus;1}&space;-&space;(\mathbf{\tilde{R}}&space;(\mathbf{R}^{t}\mathbf{x}_i&space;&plus;&space;\mathbf{t}^t)&space;&plus;&space;\mathbf{\tilde{t}})" title="\mathbf{z}_i^{t+1} - (\mathbf{\tilde{R}} (\mathbf{R}^{t}\mathbf{x}_i + \mathbf{t}^t) + \mathbf{\tilde{t}})" /></a>, is used for rigid minimization, with a linearized rotation matrix. So wouldn't  <a href="https://www.codecogs.com/eqnedit.php?latex=\mathbf{R}^{t}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\mathbf{R}^{t}" title="\mathbf{R}^{t}" /></a> for a 2D registration be as <a href="https://www.codecogs.com/eqnedit.php?latex=\begin{pmatrix}&space;1&space;&&space;-\alpha\\&space;\alpha&space;&&space;1&space;\end{pmatrix}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\begin{pmatrix}&space;1&space;&&space;-\alpha\\&space;\alpha&space;&&space;1&space;\end{pmatrix}" title="\begin{pmatrix} 1 & -\alpha\\ \alpha & 1 \end{pmatrix}" /></a>, but in the sample code only the part with respect to <a href="https://www.codecogs.com/eqnedit.php?latex=\alpha" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\alpha" title="\alpha" /></a> is taken in the A matrix, why is that?
