### ISSUE TITLE
file_dialog_open.cpp errors

### ISSUE THREAD

**Issue by xieanne** [libigl/libigl#1580]
#### Describe your question
Hi, I am currently writing a cpp file that defines the Laplacian function. But there is always errors as shown in the following diagram, it happens as long as I include the viewer.h, so I am wondering what might be the issue? 
![image](https://user-images.githubusercontent.com/44624612/89304557-91750000-d63b-11ea-953f-4963a90a9786.png)

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by xieanne** [comment]
Resolved, thanks

**Comment by jdumas** [comment]
Care to share what was wrong in case someone else comes across the same issue in the future?
