### ISSUE TITLE
render_to_png, image empty most times when using imgui menus

### ISSUE THREAD

**Issue by Mc-Zen** [libigl/libigl#1583]
When storing captures of the screen buffer with the `render_to_png` function, approximately nine out of ten saved images are just filled with the background color (purple). The issue occurs only, however, when using an imgui menu as viewer plugin. 

Also, by the way, `render_to_png` does not flip the image back to how it is seen on the screen but this is not a real problem, as it is quite easy to flip the image...

- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by alecjacobson** [comment]
This is odd. I haven't experienced this but I often don't use imgui. If this is still an issue after all the changes since 2020. Please reopen this with a minimal code example.
