### ISSUE TITLE
Boundary-preserving meshes with MIQ

### ISSUE THREAD

**Issue by arpastrana** [libigl/libigl#1584]
#### Describe your question

Hello! I want to extract a mesh from a 2d triangular mesh with a boundary and a custom vector field using libigl's MIQ implementation. For this, I am working on top of tutorial 505 and then I plug the output to libQEx. What I ultimately would like to achieve are mesh tessellations on 2d and 2.5 d meshes like those @danielepanozzo  obtained for the unreinforced masonry models in [this paper](https://cims.nyu.edu/gcl/papers/designing-unreinforced-masonry-models-siggraph-2013-panozzo-et-al.pdf)

However, as you can see below, the resulting mesh is _trimmed_ before it hits its original boundary (rectangle, in white). Searching around in libgl's docs and issues section, it seems that dealing with boundaries is a known issue that requires special care, and that to extract a boundary-preserving mesh with libQEx, MIQ's parametrization has _to be_ aligned to the boundaries. 

![image](https://user-images.githubusercontent.com/13332619/89714667-e8dddd80-d965-11ea-8661-ee788fd9a22d.png)

Not sure how to go forth. The input vector field is extracted from a finite element simulation and is not aligned to the boundaries per se. I have tried both passing in lists with `roundVertices` and `hardFeatures` containing the indices of the naked vertices and edges respectively to MIQ without success (maybe I am not using this correctly?). 

I don't need to have quads at the boundary to meet the boundary condition. What I can think of as a quick fix is to artificially enlarge the original 2d triangular mesh, repeat the same process I describe above, and then simply trim out the bits of the resulting libQEx mesh that are outside the original boundary. However, this workaround will not work on 2.5d meshes.  

Is there an alternative way I could produce this boundary-preserving meshes using MIQ and a custom vector field like in the paper referenced above? Thank you.

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ x ] macOS
- [ ] Linux

**Comment by danielepanozzo** [comment]
I, unfortunately, don't see a way to fix this without changing how libQEX deals with boundaries. @avaxman might be able to help, Directional (https://avaxman.github.io/Directional/) will soon have support for quad mesh extraction and maybe in their setup, it is easier to support the direct cutting of the faces on the boundary.

**Comment by avaxman** [comment]
Yes, Directional is coming up with a full meshing package (subject to CGAL dependncy) and it will have the option to leave the boundaries intact (producing non-quad faces) or trim to the nearest pure-quad mesh (like what you show). No MIQ or libqex dependency, but requiring a field that integrates into a locally-injective parameterization. It is coming up soon. I will write here when it does.

**Comment by arpastrana** [comment]
That's great news - looking forward to Directional's meshing package release! Sorry if I'm not familiar with this @avaxman, but what would be some of the things a field shouldn't be doing in order to integrate into a localliy-injective parametrization?

**Comment by avaxman** [comment]
I am considering making the locally-injective property also be optimized for the initial solution (translation: getting a seamless not-yet-integer parameterization), instead of having it as a requirement. The requirements---in that case---would be an order preserving field, where all vectors appear counter-clock-wise around the normal in order.

**Comment by arpastrana** [comment]
Thanks, @avaxman! In this case, would a "combed" field (i.e.via libigl) satisfy these requirements?

**Comment by avaxman** [comment]
Yes, though Directional also takes care of combing. It will also tell you if the field is not order preserving (cross fields are).

Amir.

**Comment by arpastrana** [comment]
Hi @avaxman! Just touching base again on the boundary-preserving quad meshing issue. Are there any updates on the release of Directional's meshing package? Thanks a lot!

**Comment by arpastrana** [comment]
> Yes, Directional is coming up with a full meshing package (subject to CGAL dependency) and it will have the option to leave the boundaries intact (producing non-quad faces) or trim to the nearest pure-quad mesh (like what you show). No MIQ or libqex dependency, but requiring a field that integrates into a locally-injective parameterization. It is coming up soon. I will write here when it does.

Hello again, @avaxman! Following up on our previous convo: does Directional now include a boundary-preserving meshing algorithm that takes in a cross-field and outputs a quad-dominant mesh? See our convo thread above 👆🏽 Thanks!

**Comment by avaxman** [comment]
Yes, Directional has a field->parameterization package now. It’s not guaranteed to be robust if the field is non-integrable though, but it preserves the original mesh and produces any polygonal mesh you’d like. Check the tutorial!

**Comment by arpastrana** [comment]
Awesome, thank you!

**Comment by arpastrana** [comment]
Closing this as Directional helped me generate a boundary-preserving quad mesh from a cross field.

**Comment by avaxman** [comment]
That's great! it would be awesome to learn about your experience with Directional.

**Comment by bootsmakes** [comment]
@arpastrana Hi, could you share the steps to generate a boundary preserving quad mesh from an arbitrary mesh? Thanks.

**Comment by arpastrana** [comment]
Check out tutorial 505 of Directional: https://avaxman.github.io/Directional/tutorial/#505-meshing

**Comment by bootsmakes** [comment]
@arpastrana Yes, I've checked that tutorial, I'm not sure how to generate those .rawfields to load as input for the 505-meshing tutorial, also those .rawfields look wrong to me, the cuts are incorrect as well. It doesn't look like a MIQ  implementation at all.
