### ISSUE TITLE
Eigen decomposition error

### ISSUE THREAD

**Issue by hadhoryth** [libigl/libigl#1585]
#### Describe your question
Hello!

I have a problem with eigendecomposition. I use code from the tutorial:
```
SparseMatrix<double> L, M;
igl::cotmatrix(V, F, L);
igl::massmatrix(V, F,igl::MASSMATRIX_TYPE_DEFAULT,M);
L = (-L).eval();
VectorXd D;
MatrixXd U;
igl::eigs(L, M, nb_eigen + 1, igl::EIGS_TYPE_SM, U, D);
```  

But for my custom mesh, I have an error 
```
Vertices: (578, 3)
Faces: (683, 3)
Irregular vertices: 
172/578 (29.76%)
Areas (Min/Max)/Avg_Area Sigma: 
0.00/3.32 (0.43)
Angles in degrees (Min/Max) Sigma: 
0.00/157.17 (nan)

Failed to converge. 
Error: eigendecomposition.
```

It might be a problem that mesh is non-manifold. Is any function in LibIgl to check it or maybe stabilize `eigs` computation?

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [x] macOS
- [ ] Linux

**Comment by alecjacobson** [comment]
Hmm. Could there be nans/infs in L or zeros on the diagonal of M?
