### ISSUE TITLE
Unable to load libigl

### ISSUE THREAD

**Issue by YemmyMMU** [libigl/libigl#1586]
#### Describe your question
Unable to load libigl. Kindly help
...
pgstudent@pgstudent-HP-EliteDesk-800-G4-Twr-IDS-APJ:~/Documents/MeshGAN/SDFGenerator/build$ cmake ..
CMake Error at cmake/FindLIBIGL.cmake:36 (include):
  include could not find load file:

    libigl
Call Stack (most recent call first):
  CMakeLists.txt:27 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/pgstudent/Documents/MeshGAN/SDFGenerator/build/CMakeFiles/CMakeOutput.log".
See also "/home/pgstudent/Documents/MeshGAN/SDFGenerator/build/CMakeFiles/CMakeError.log".
pgstudent@pgstudent-HP-EliteDesk-800-G4-Twr-IDS-APJ:~/Documents/MeshGAN/SDFGenerator/build$ 

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] macOS
- [ X ] Linux

**Comment by jdumas** [comment]
Duplicate of #1398
