### ISSUE TITLE
heat method; extract iso-curves

### ISSUE THREAD

**Issue by CatrielCarbonera** [libigl/libigl#1600]
#### Describe your question
I am looking into using the **Heat Method** to extract **iso-curves** - geodesic offsets of curves, but am not familiar with this technique nor other similar ones in the field. Hence, I would like **libigl** to provide me with the data that I need.

Is there a utility in **libigl** that will extract the **iso-curves** from the distance field generated by the **Heat Method** on the mesh being provided? Using linear interpolation of the distance field values at the end of the vertices does not give the desired results; shock-fronts are not capture, broken curves, etc. I've tried to track the fronts by trying to split the triangles into piece-wise linear elements but don't know enough about these techniques to do this properly. Any suggestions will be greatly appreciated.

#### Check all that apply (change to `[x]`)
- [x ] Windows
- [ ] macOS
- [ ] Linux

**Comment by jiangzhongshi** [comment]
There are two ways to generate iso-curves.

https://github.com/libigl/libigl/blob/master/include/igl/isolines.h will give you vertex and edges which you can directly draw.
and https://github.com/libigl/libigl/blob/master/include/igl/isolines_map.h gives a colormap instead (see Tutorial 206, 712 for its application)
