### ISSUE TITLE
CUDA defines break compilation due to Eigen errors

### ISSUE THREAD

**Issue by j8asic** [libigl/libigl#1602]
#### Describe your question

I'm using `clang` compiler for compiling `CUDA` code, where in the same compilation unit there is some `libigl` code. The defines enabled for `CUDA` break the compilation. I need to undef `CUDA` stuff in this file since `Eigen` breaks with it.

```
#undef __CUDACC__
#undef __CUDA_ARCH__
```

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] macOS
- [x] Linux

**Comment by BruegelN** [comment]
Hi @j8asic,

not sure how up to date this site is https://eigen.tuxfamily.org/dox/TopicCUDA.html but it mentiones issues with nvcc + clang.
I don't know this can be fixed in libigl it should rather be fixed in Eigen I guess.
