### ISSUE TITLE
Access violation crash in igl::project 

### ISSUE THREAD

**Issue by asaf92** [libigl/libigl#1607]
#### Describe the bug

When loading large (40k vertices) meshes, clicking on the mouse on the screen can cause a crash:
![image](https://user-images.githubusercontent.com/35231408/92302580-05c1fc80-ef76-11ea-90e6-0f1e41b9ac4e.png)
![image](https://user-images.githubusercontent.com/35231408/92302585-0e1a3780-ef76-11ea-8a47-cfa21266fe75.png)

It happens randomly in Release build when you first click the mouse. 

#### Check all that apply (change to `[x]`)
- [X ] Windows
- [ ] macOS
- [ ] Linux

**Comment by jdumas** [comment]
Can you share the model where this is happening? Which tutorial are you running, 708?

**Comment by asaf92** [comment]
It's not a tutorial, it's a school assignment.

I uploaded the code of the assignment + the model where this bug happens most often (bumpy_plane.off)

[bug.zip](https://github.com/libigl/libigl/files/5238156/bug.zip)

**Comment by asaf92** [comment]
Could it be related to the fact I uncommented `#define ImDrawIdx unsigned int` in `imconfig.h`?

**Comment by alecjacobson** [comment]
Maybe! I have no idea what commenting out that line will do. 

40K is not particularly large so the viewer should work fine for such a mesh. If this is still an issue feel free to reopen with more details.
