### ISSUE TITLE
Large Quadrilaterization of Meshes

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#161]
From personal email:

>   I have used libigl, and I am very impressed with the capabilities.   I was wondering if there exists a way to accomplish something.  I am looking for a way to make large scale quadrilaterization of a mesh.

> Similar to this paper:
http://research.microsoft.com/en-us/um/people/hoppe/bspline.pdf

> but not for bsplines.  I just need the mesh broken up into large quads.

> I have looked at the global parameterization example 505, but it does not produce the results I am looking for.  Step #3 on page 9 in the paper at the bottom of the paper.

> Can libigl do this?  If not, can it be added?

> This paper also describes what I am looking for.  Just identifying vertices that make quad the patches is what I'm after.

> https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=0ahUKEwjT27yLyq7JAhVMGj4KHZHfCl4QFggoMAE&url=https%3A%2F%2Fwww.ideals.illinois.edu%2Fbitstream%2Fhandle%2F2142%2F11036%2FQuadrangulating%2520a%2520Mesh%2520using%2520Laplacian%2520Eigenvectors.pdf%3Fsequence%3D2&usg=AFQjCNFNXqvf_uJYxKycJpOcQRRTm124Gw&sig2=TkTcl8g4i433ESZb-pUNJg&bvm=bv.108194040,d.eWE

**Comment by alecjacobson** [comment]
As far as I know we don't have anything in libigl that's well suited for very coarse quadrangulations. We have some of the low level routines you might use to implement the [Dong et al.] paper: `igl::cotmatrix` and `igl::eigs`.

Daniele might know better...

**Comment by danielepanozzo** [comment]
We do not have anything that can create coarse quadrangulations currently and the state of the art methods (such as http://www-sop.inria.fr/members/David.Bommes/publications/IGM_preprint.pdf) are really complex to code. 

As Alec wrote, we have some of the pieces that are needed in libigl to implement the spectral quadrangulation paper, but we do not have the extraction of the morse graph that is again not easy to implement.

**Comment by RogersDoug** [comment]
I understand that they are complex to code.  That is precisely why I am asking this to be part of this project.

**Comment by RogersDoug** [comment]
This can also be accomplished with Laplacian eigenvectors which you already support.  The only missing piece is the Morse-Smale complex as per the paper refefenced in the OP.

**Comment by danielepanozzo** [comment]
We will be happy to receive a pull request with this feature added, it will indeed be nice to have. The development of the library follows the research projects we are working on, and it is currently not in our plans to code the morse-smale complex extraction. We will add it to the long-term todo list.

**Comment by bootsmakes** [comment]
> We do not have anything that can create coarse quadrangulations currently and the state of the art methods (such as http://www-sop.inria.fr/members/David.Bommes/publications/IGM_preprint.pdf) are really complex to code.

@danielepanozzo Just curious, what are the state of the art methods in 2023?
