### ISSUE TITLE
Dimensions of hessians in documentation

### ISSUE THREAD

**Issue by medakk** [libigl/libigl#1611]
#### Describe your question

In the [hessian for a mesh](https://github.com/libigl/libigl/blob/21acee15fe4451e828b52bedcdba53b79d846376/include/igl/hessian.h), the return value is specified as:

```
    // Outputs:
    //   H  #V by #V Hessian energy matrix, each column i
    //     corresponding to V(i,:)
```

Why is the return value #V x #V? I'd expect it to be 9 x #V. Also it seems to be talking about "hessian energy" and not the hessian.

When I run the function, I get a result of (9*#V) x #V

**Comment by alecjacobson** [comment]
I've tried to improve the documentation for the Hessian function https://libigl.github.io/dox/namespaceigl.html#a8e6dbdaae94657379ac8491942082d20

The matrix is dim²⋅|V| by |V| and it is the sparse matrix which computes the Hessian of a scalar field defined at vertices of the mesh. So let's say you have a scalar field X ∈ ℝ^|V| on a mesh in 2D then the multiplication Y = H X  will be 4|V| vector containing the entries of the Hessian (2x2 matrix of second derivatives) of X at each vertex of the mesh.

Please reopen if this is still not clear.
