### ISSUE TITLE
Picking a vertex but obtain it's x,y,z coordinates

### ISSUE THREAD

**Issue by MarcoGZ98** [libigl/libigl#1616]
Hi I already followed the picking tutorial in wich the variable bc is the barycentric coordinate of the picked position and that the value with the highest value is tha one that it is more close to the vertex

However how can I obtain the index of a picked vertex (index accordingly to the obj file of that mesh), along with its x, y and z coordinates? Let's say that I pick a vertex and store in a list the following: 32, -192, 245, 83 --- in wich the first value is the index, and the next ones are x,y,z

Is there a way to achieve this?
Thank you

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] macOS
- [x] Linux

**Comment by jdumas** [comment]
Yes you can use [igl::barycentric_interpolation](https://github.com/libigl/libigl/blob/master/include/igl/barycentric_interpolation.h), or compute the coordinates yourself...
