### ISSUE TITLE
Mesh editing and queries

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#162]
From personal email:

> I am trying to implement some basic triangle mesh remeshing and am
> looking at the support in ligigl.
>
> I noticed that you implemented some edge collapse code. Will this work
> on manifolds with boundary?
>
> Is there edge split code?
>
> Is there already an implementation of triangle mesh remeshing? (I
> noticed that Daniele's quad remeshing is implemented.)
>
> Also while I have you, is there support for finding the nearest face given a query point in space (using e.g. a kd tree)?
> 
> I do see support for fast ray-mesh intersection, which is very cool.
>

**Comment by alecjacobson** [comment]
The edge collapsing is currently only implemented correctly for closed manifold meshes. It shouldn't be too much work to have it work for meshes+boundary. (but it would be a lot of work to have it work for non-manifolds)

There's no edge-split code per-se, but there's `igl::upsample` if you want to 1-4 subdivide everything. I imagine a decently amortized edge-split implementation would not be too hard to add either.

There's no triangle remeshing implemented. I think Daniele has plans to add the "Instant Meshes" paper which can do triangle meshes as a special case. (Otherwise I've previously used OpenFlipper or CGAL for remeshing with decent success).

We have an AABB tree. See `igl::AABB`, or you might just call `igl::point_mesh_squared_distance` if you have lot of points to query and don't want to know/bother about the acceleration that's being used behind the scenes.

**Comment by danielepanozzo** [comment]
I would like to add wrappers in libigl for instant meshes but I am not sure of when I will do it. For now you can find it here: https://github.com/wjakob/instant-meshes
