### ISSUE TITLE
Using heat_geodesics_solve for multiple vertices

### ISSUE THREAD

**Issue by medakk** [libigl/libigl#1623]
#### Describe your question

How do I make a single query to get the geodesic distance from multiple source vertices? I tried:

```cpp
    // ... compute heatData using heat_geodesics_precompute

    Eigen::VectorXd D;
    Eigen::VectorXi gamma(3);
    gamma << 3, 2, 8;
    igl::heat_geodesics_solve(heatData,gamma,D);
```

but the dimension of D doesn't change at all whether gamma has 1,2 ,3  or more vertices. The doc talks about "set of selected source vertices": how do I use that?

This is the current definition of the function:

```cpp
  // Compute fast approximate geodesic distances using precomputed data from a
  // set of selected source vertices (gamma)
  //
  // Inputs: 
  //   data  precomputation data (see heat_geodesics_precompute)
  //   gamma  #gamma list of indices into V of source vertices
  // Outputs:
  //   D  #V list of distances to gamma 
  template < typename Scalar, typename Derivedgamma, typename DerivedD>
  IGL_INLINE void heat_geodesics_solve(
    const HeatGeodesicsData<Scalar> & data,
    const Eigen::MatrixBase<Derivedgamma> & gamma,
    Eigen::PlainObjectBase<DerivedD> & D);
```

**Comment by alecjacobson** [comment]
If gamma contains 3 vertices then the result will be the heat method's
approximate _minimum_ distance to _any_ of the three vertices. That is,
they are simultaneously sources together. For example if gamma contains all
vertices on the boundary, then this will return the distance to the
boundary (not a matrix of distances to each point).

If you want distances to each point independently, you can call it in a for
loop.

**Comment by medakk** [comment]
Got it, thanks!
