### ISSUE TITLE
Can't perform correct Laplacian recostruction

### ISSUE THREAD

**Issue by PurpleSensation** [libigl/libigl#1626]
#### Describe your question
I am trying to reconstruct a mesh using the Laplacian eigenvalues, wanting to keep the low harmonics. When I try to reconstruct following basic algebra, I get clearly wrong mesh. I don't get to see the problem.

Thank you

`
import igl as igl
import scipy as sp
import numpy as np
from meshplot import plot, subplot, interact
import meshplot

import os
root_folder = os.getcwd()

v, f = igl.read_triangle_mesh("cow.off")

#v,SVI,SVJ =igl.remove_duplicates(v,f,1e-3)
#f=np.reshape(SVJ,f.shape)

l = igl.cotmatrix(v, f)
m = igl.massmatrix(v, f, igl.MASSMATRIX_TYPE_BARYCENTRIC)

def reconstruction(u_x,u_y,u_z,v,ev):
    v_r=np.zeros(v.shape)
    v_r[:,0]=np.matmul(u[:,0:ev],v_hat_x[0:ev])
    v_r[:,1]=np.matmul(u[:,0:ev],v_hat_y[0:ev])
    v_r[:,2]=np.matmul(u[:,0:ev],v_hat_z[0:ev])
    return v_r

k = 20

d, u = sp.sparse.linalg.eigsh(l, k, m,sigma=0, which="LM")

#u = (u - np.min(u)) / (np.max(u) - np.min(u))

v_hat_x=np.matmul(np.transpose(u),v[:,0])
v_hat_y=np.matmul(np.transpose(u),v[:,1])
v_hat_z=np.matmul(np.transpose(u),v[:,2])

p = plot(reconstruction(v_hat_x,v_hat_y,v_hat_z,v,20), f, return_plot=True)

`
...

#### Check all that apply (change to `[x]`)
- [x ] Windows
- [ ] macOS
- [ ] Linux

**Comment by jiangzhongshi** [comment]
I believe this is the implementation you are looking for: https://geometryprocessing.github.io/blackbox-computing-python/geo_viz/#shape-filtering-spectral-smoothing

I think there are two things that might be confusing. `cotmatrix` gives a semi-*negative*-definite matrix, and the usual laplacian should be `-l`. Then the eigen values should be taken such that they are of the smallest magnitude. (`which='SM'`)

**Comment by alecjacobson** [comment]
I agree with @jiangzhongshi . In addition, I've personally found the `sp.sparse.linalg.eigsh` to be unreliable. I don't believe this is an issue with libigl.
