### ISSUE TITLE
can not compile example 102 code

### ISSUE THREAD

**Issue by BEMfreshman** [libigl/libigl#163]
Hi,
   I am a new user to libigl and used Eigen before.
   Some compile errors occur when I compile the Example 102 following the instruments from tutorial use Clion IDE on mint linux 17.2. This is the information about error :  

     /home/yangwenlu/libigl/include/igl/viewer/TextRenderer.cpp:12:28: fatal error: nanogui/opengl.h: no such file or directory 

    Can someone help me with this problem?
    Thanks.

**Comment by danielepanozzo** [comment]
You probably cloned the repository without the -recursive option. Can you check if the libigl/external/nanogui/ is empty? If that is the case, then cloning the repository again with -recurvise should fix it.

**Comment by BEMfreshman** [comment]
Thank for you response.
Perhaps I don't express myself clearly.I do use --recurisve and libigl/external/nanogui/ is not empty.
I mean when I want to use example102 code to build my own program in other folder(not in libigl/tutorial/), the system show me the error information and build failed.

PS: I have checked tutorial folder, and find a file whose name is CMakeLists.shared. I notice the brief introduction about this file is "Fix link order on linux". Shall I replace my CMakeLists with this file when I use libigl to build my program ?

**Comment by danielepanozzo** [comment]
If you want to build your own examples, you need to copy all the cmake files in another folder and correspondingly update all paths in them. We will have a simplified way to do this in the near future, probably around February/March.

**Comment by BEMfreshman** [comment]
Oh,it maybe late for me.
Anyway,thanks for your advice and I will try it.
