### ISSUE TITLE
libigl build fails (embree)

### ISSUE THREAD

**Issue by avaxman** [libigl/libigl#1632]
#### Describe your question

I'm getting embree errors (from a fresh copy):

/Users/amirvaxman/libigl/external/embree/kernels/common/rtcore.cpp:1071:7: error: 
      no member named 'createGridMesh' in namespace 'embree::sse41'; did you
      mean simply 'createGridMesh'?
  ...SELECT_SYMBOL_DEFAULT_AVX_AVX2_AVX512KNL_AVX512SKX(device->enabled_cpu_features,createGridMesh);

and

/Users/amirvaxman/libigl/external/embree/kernels/common/rtcore.cpp:1059:7: error: 
      no member named 'createInstance' in namespace 'embree::sse41'; did you
      mean simply 'createInstance'?
  ...SELECT_SYMBOL_DEFAULT_AVX_AVX2_AVX512KNL_AVX512SKX(device->enabled_cpu_features,createInstance);

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [X] macOS
- [ ] Linux

**Comment by BruegelN** [comment]
I'm not able to reproduce this on my 2014 MBP, running macOS Catalina 10.15.7 and Xcode 12.0.1.
However I've had issues with embree on macOS in the past and it was no fun...
Which version of macOS+XCode are you running?
What's the output of:
`sysctl machdep.cpu.features`
and
`clang -dM -E - < /dev/null | egrep -i '(sse|aes|rdrnd|rdseed|avx|bmi)' | sort` ?

Maybe a newer version of embree fixes this?!
You can change it here: https://github.com/libigl/libigl/blob/master/cmake/LibiglDownloadExternal.cmake#L80

**Comment by avaxman** [comment]
Here is what I get:
(base) Amirs-MacBook-Pro:~ amirvaxman$ sysctl machdep.cpu.features
machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTES64 MON DSCPL VMX SMX EST TM2 SSSE3 FMA CX16 TPR PDCM SSE4.1 SSE4.2 x2APIC MOVBE POPCNT AES PCID XSAVE OSXSAVE SEGLIM64 TSCTMR AVX1.0 RDRAND F16C
(base) Amirs-MacBook-Pro:~ amirvaxman$ clang -dM -E - < /dev/null | egrep -i '(sse|aes|rdrnd|rdseed|avx|bmi)' | sort
#define __SSE2_MATH__ 1
#define __SSE2__ 1
#define __SSE3__ 1
#define __SSE4_1__ 1
#define __SSE_MATH__ 1
#define __SSE__ 1
#define __SSSE3__ 1
(base) Amirs-MacBook-Pro:~ amirvaxman$

**Comment by jdumas** [comment]
Hmm that looks similar to [this issue](https://github.com/embree/embree/issues/262)? Maybe we need to update our embree dependency?
