### ISSUE TITLE
Import Error with pyigl as igl

### ISSUE THREAD

**Issue by trick-bat** [libigl/libigl#1633]
#### Describe your question
1、
**import pyigl as igl
ModuleNotFoundError: No module named 'pyigl'**

2、
I change the code from _import pyigl as igl_  to  _from igl import pyigl_ and I got another error.

 **v = pyigl.eigen.MatrixXd()
AttributeError: module 'igl.pyigl' has no attribute 'eigen'**

How can I solve these two problems？

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by BruegelN** [comment]
Are you using the *new* python binding? https://github.com/libigl/libigl-python-bindings
With those you can work directly with numpy nd-arrays, no need to take care of converting between eigen <-> numpy.
For installation instructions and a tutorial see https://libigl.github.io/libigl-python-bindings/

**Comment by trick-bat** [comment]
Yes, I installed the new python binding by running the _conda_ command.

In fact, I cloned some codes which import the _pyigl_ and I met those two errors.

Did you remove `igl.eigen.MatrixXd()`? I find that it can't be called while the function like `igl.read_triangle_mesh()` can.

**Comment by jiangzhongshi** [comment]
The new binding has a complete refactoring. Therefore, simply change the import would not be sufficient. For the usage, please refer to https://geometryprocessing.github.io/blackbox-computing-python/geo_viz/

**Comment by mm23mm** [comment]
I have the same problem as you. Did you finally solve the problem?   :(

**Comment by jiangzhongshi** [comment]
@mm23mm if you are using the new binding,
 simply `import igl` works.

**Comment by mm23mm** [comment]
> @mm23mm if you are using the new binding, simply `import igl` works.

I still got the same error.  
**module 'igl' has no attribute 'eigen'**

**Comment by jiangzhongshi** [comment]
It seems that you have installed `igl` and the binding does not rely on submodule `eigen` anymore. So the command like 
```
v = pyigl.eigen.MatrixXd()
```
is not needed anymore.

Please refer to the new tutorial here.  https://geometryprocessing.github.io/blackbox-computing-python/geo_viz/

**Comment by qiu-guo** [comment]
Did you solve the problem? I have the same problem.

**Comment by jiangzhongshi** [comment]
@qiu-guo the api described in the post is deprecated now. Please refer to the new tutorials.

**Comment by alecjacobson** [comment]
This is likely out of data. Try the new bindings on pypi and reopen if this is still an issue.
