### ISSUE TITLE
Add conan support

### ISSUE THREAD

**Issue by AndreyMlashkin** [libigl/libigl#1634]
#### Describe your feature request
Conan is a C/C++ package manager, but it is able to manage builds from source, dependencies, and precompiled binaries for any language.
It can also ease a CI pipeline creation in the future.

check out the existing conan recipes:
https://github.com/conan-io/conan-center-index/tree/master/recipes

**Comment by jdumas** [comment]
Hi,

We already have community support for vcpkg and hunter. If you want to add support for conan, we'd be happy to review your contribution.

**Comment by AndreyMlashkin** [comment]
It seems, I came to a dead-end, implementing conan recipe
https://github.com/conan-io/conan-center-index/pull/5542

If you have a possibility, please help

**Comment by jdumas** [comment]
Hi,

I am currently in the process of rewriting our CMake support entirely (cf. #1805). Once this is merged, I will have more time to look into conan support, but no timeline on this yet.

**Comment by AndreyMlashkin** [comment]
just for your info: I have added conan support. You can install it with command
conan install libigl/2.3.0@ --build missing

**Comment by melMass** [comment]
> just for your info: I have added conan support. You can install it with command conan install libigl/2.3.0@ --build missing

Can you link to the recipe?

**Comment by melMass** [comment]
Oh it's on conan-center: 
https://github.com/conan-io/conan-center-index/tree/master/recipes/libigl
https://conan.io/center/libigl

Thank you so much @AndreyMlashkin !!
