### ISSUE TITLE
A bug in the `repdiag` function

### ISSUE THREAD

**Issue by HTDerekLiu** [libigl/libigl#1639]
#### Describe the bug

When I call `igl::repdiag(A,2,B);` where `A` is a dense matrix. I got some `nan` values in the off-diagonal blocks.
<img width="1322" alt="Screen Shot 2020-11-02 at 2 08 10 PM" src="https://user-images.githubusercontent.com/32198009/97908905-54410c80-1d15-11eb-899c-ad423fd1a357.png">

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [x] macOS
- [ ] Linux

**Comment by alecjacobson** [comment]
Any chance you can post the input matrices or get this to happen for a
small problem consistently?

**Comment by alecjacobson** [comment]
Nevermind! I think I found the issue. This is wild. We were setting the matrix to 0 by multiplying the random values in memory by 0. Will fix imminently.

**Comment by jdumas** [comment]
Can we add a unit test for it?

**Comment by alecjacobson** [comment]
Great idea. I fixed it immediately in https://github.com/libigl/libigl/commit/870eb14ec297c878439cd25226c9d657c9ad56b5 .
