### ISSUE TITLE
Don't set_face_based in set_uv (or by extension set_data)?

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#1647]
Currently, calling set_uv with per-vertex uvs will change the viewing setting to "not face based". Why?

https://github.com/libigl/libigl/blob/0bb27beb88ae1aebe9653754c64d3f281f7e4a33/include/igl/opengl/ViewerData.cpp#L233

`set_uv` is called by `set_data` and this works well/fine when in `face_based = true`: face-based lighting, but continuously interpolated data.

I expect the same to be true for typical UVs and texturing. Any reason _not_ to delete this line?

**Comment by jdumas** [comment]
Seems to me that both L233 and L243 can go away.
