### ISSUE TITLE
OpenMP support on Mac OS X

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#165]
This is a bit outside the scope of libigl's issues, but I'd like to find a clean way of taking advantage of OpenMP within libigl on my usual build platform, mac os x.

Previously, I've experimented with gcc but this leads to a nightmare of incompatible libraries between things compiled with gcc and things compiled with the "built-in" clang compiler.

Now, I've successfully built the libigl tutorial using the latest clang compiler (v3.8, not the apple/xcode v3.7 one) and libiomp. I installed these with homebrew in a way that _does not_ clobber the default clang compiler. It appears that these clang 3.8 binaries play nicely with binaries compiled with the apple one (but who really knows?).

It was a bit of a mess to _hack_ cmake into finding my openmp installation. Basically I just short circuit the system level `FindOpenMP.cmake` and define the appropriate flags.

To reproduce, try:

``` bash
brew install libiomp
# this will take a while:
brew install llvm --with-clang --HEAD
cd $LIBIGL/tutorial/
mkdir build-omp
cd build-omp
CC=/usr/local/opt/llvm/bin/clang CXX=/usr/local/opt/llvm/bin/clang++ cmake -DOpenMP_C_FLAGS="-fopenmp=libiomp5 -I /usr/local/include/libiomp/ -liomp5" "-DOpenMP_CXX_FLAGS=-fopenmp=libiomp5 -I /usr/local/include/libiomp/ -liomp5" ..
```

One slight annoyance is that this adds the `-liomp5` flag to compilation commands, too. So I get a bunch of warnings:

```
clang-3.8: warning: -liomp5: 'linker' input unused
```

**1. Is there a cleaner way to tell cmake to use the libiomp I installed via homebrew?**

I'd like to avoid editing system files and ideally minimal changes to the current cmake configuration (and obviously something that will still find the usual openmp on linux/windows etc.).

**2. Is there a _better_ or _easier to install_ constellation of compiler/openmp on Mac OS X?**

For example, the clang v3.8 compiler (as installed above) is _very_ slow compared to the built-in v3.7 one.

**Comment by alecjacobson** [comment]
I still don't know the answers to my OpenMP questions above, and as far as I can tell there's no sign that MacOS X's builtin clang will support OpenMP any time soon.

So in the meantime, I'm [experimenting](http://www.alecjacobson.com/weblog/?p=4544) with using C++ `std::thread` for _primitive_ `parallel for` behavior.

For example, I've pushed a recent change to `igl/ambient_occlusion.cpp` which replaces the previous openMP `parallel for` this mechanism. Alas, OpenMP only needs to add one line above the for loop. This method adds 7 (generic) lines above the for loop, slightly changes the loop to run over a chunk of its range, and adds 3 lines after the for loop. ~10 lines is not _sooo_ bad for something that will really work everywhere out of the box.

**Comment by danielepanozzo** [comment]
I think we should stop waiting for apple to support and switch to TBB. It is lightweight, it can be compiled statically and works on all platforms. I can add it to the external and do a pass to convert everything. since we mostly use the "omp parallel" it is a really trivial conversion.

https://www.threadingbuildingblocks.org

I would rather avoid trying to use the standard c++ threading as a long term solution, it is not easy to make it work well on an arbitrary machines, while tbb does the work distribution on its own.

**Comment by alecjacobson** [comment]
What's up with C++ threads on arbitrary machines? It seems C++11
std::thread is standard.
TBB offers more features, but it's adding a dependency, whereas C++11 is
already assumed.

**Comment by danielepanozzo** [comment]
You need to do task balancing, i.e. decide how many "work packages" every thread gets, how many threads you keep in the thread pool and eventually increase or decrease the pool depending on the system load. It is hard to do right: tbb, openmp, apple GCD do it for you and they are good at it :) . For what I know, the c++11 thread library is very basic and only allows to start and stop threads, but everything else has to be done manually. I am also scared of the c++11 implementation of it inside visual studio and we definitely want to get it to work also there. TBB is a lightweight dependency (it depends on c++11 only), tested on all platforms and it is very convenient to have, since it has a full set of parallel data structure that are useful for anything more than a "omp parallel".

**Comment by alecjacobson** [comment]
According to 
https://msdn.microsoft.com/en-us/library/hh920601(v=vs.110).aspx
https://msdn.microsoft.com/en-us/library/hh567368.aspx 
visual studio should support C++11 concurrency and std::thread since 2012.

The other issue you brought up is dead on though: std::thread is low level. AFAIK there's no standard library thread pooling or high-level features like OpenMP or TBB provides.

So if I had tasks more complicated than `parallel for` loops or I was trying to really squeeze multi-core performance out of my implementation, then I'd definitely go for OpenMP, TBB or some other dependency.

However, my point is that our core `igl/` library currently only depends on C++11, stl and Eigen. We're currently only using (optionally) openmp for `parallel for` and a few `critical` scopes. In the [little example](http://www.alecjacobson.com/weblog/?p=4544), I showed that _basic_ `parallel for` with a critical section is not _so_ bad to do in a generic way with `std::thread` in C++11.

So unless there's a dying need to use fancier threading features or to get significantly higher performance, I see no need to add another dependency to the core library.

Despite that, I agree that TBB is very cool, lightweight, and continuously maintained. If there's a really cool feature that we want to use for some task we can easily create a `igl/tbb/` dependency folder. If that folder starts to out weigh the main folder, we could merge them and declare tbb a bonafide top-level dependency.

**Comment by danielepanozzo** [comment]
I was more thinking of keeping tbb as an optional dependency for the main library. We can have a define that activates/disactivates it and ifdef the pieces of code in the core libigl that requires to run stuff in parallel. If you do not have tbb, it will just gracefully run it serially. Similarly to how we use openmp now.

I am still worried that your simple solution will create disaster on VS, but if you tested it and you are sure that it is not the case (and you are willing to maintain it also on windows) I am also ok doing it this way.

**Comment by alecjacobson** [comment]
What specifically are you worried will go wrong on windows? It's a
supported feature in the standard library for many years now, correct?

**Comment by danielepanozzo** [comment]
I am worried that thing will not be as transparent as you hope. The threading system (at a low-level) is very different on unix and windows system and I think it is unlikely that everything will work out of the box. It should in theory, I agree, but I somehow doubt that it will be so easy.

Even if we use [this](http://www.alecjacobson.com/weblog/?p=4544), we will still have to ifdef it to provide a "clean" serial version. libigl functions could be used inside other application that use openmp/GDC/tbb and in that case you do not want to spawn additional threads inside the function themselves.

I also think it might be extremely problematic if a function parallelized with [this](http://www.alecjacobson.com/weblog/?p=4544) calls another function that is also parallelized with [this](http://www.alecjacobson.com/weblog/?p=4544). Too many threads will be spawned and it will be very slow.

Overall, I don't feel confident in coding from scratch a parallelization framework (even if it is a simple one): it is hard and there might be a lot of cases that we are missing and that will be annoying to debug and fix.
