### ISSUE TITLE
macOS + CMake 3.19.0: can't compile GLFW

### ISSUE THREAD

**Issue by BruegelN** [libigl/libigl#1655]
#### Describe the bug
There's a bug in with macOS + CMake 3.19.0 when trying to compile GLFW: https://github.com/glfw/glfw/issues/1787

I'll have an eye on GLFWs next release and submit a PR to bump GLFW used by libigl to version 3.3.3

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [x] macOS
- [ ] Linux

**Comment by jdumas** [comment]
We can update to a non-release commit of GLFW too, no need to wait for the next version bump?
