### ISSUE TITLE
how to use functions that was not used in tutorial?

### ISSUE THREAD

**Issue by uingue** [libigl/libigl#1659]
#### Describe your question
Funtions that has been used in tutorial folds work well,  but when I use functions not used in tutorial folds (e.g. igl::remove_duplicate_vertices()), I got an error LNK2019.
What should I do? 
Thanks for your help. 
`error LNK2019: unresolved external symbol "void __cdecl igl::remove_duplicate_vertices<class Eigen::Matrix<double,-1,-1,0,-1,-1>,class Eigen::Matrix<double,-1,-1,0,-1,-1>,class Eigen::Matrix<double,-1,-1,0,-1,-1>,class Eigen::Matrix<double,-1,-1,0,-1,-1> >(class Eigen::MatrixBase<class Eigen::Matrix<double,-1,-1,0,-1,-1> > const &,double,class Eigen::PlainObjectBase<class Eigen::Matrix<double,-1,-1,0,-1,-1> > &,class Eigen::PlainObjectBase<class Eigen::Matrix<double,-1,-1,0,-1,-1> > &,class Eigen::PlainObjectBase<class Eigen::Matrix<double,-1,-1,0,-1,-1> > &)" (??$remove_duplicate_vertices@V?$Matrix@N$0?0$0?0$0A@$0?0$0?0@Eigen@@V12@V12@V12@@igl@@YAXAEBV?$MatrixBase@V?$Matrix@N$0?0$0?0$0A@$0?0$0?0@Eigen@@@Eigen@@NAEAV?$PlainObjectBase@V?$Matrix@N$0?0$0?0$0A@$0?0$0?0@Eigen@@@2@11@Z)`

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by jdumas** [comment]
Try to use libigl in header-only mode.

**Comment by alecjacobson** [comment]
I've added some info about this on the main page of the doc https://libigl.github.io/dox/index.html
