### ISSUE TITLE
Mean curvature flow

### ISSUE THREAD

**Issue by csverma610** [libigl/libigl#166]
Hello,

I have noticed that for an arbitrary triangle mesh, the mean curvature flow produces
Neck pinchers which were also reported by mirela ben chen and kazdan etc.
Should we use some specific triangle mesh ( for example, all acute triangles, geodesics trinangle
) so that we converge to canonical shapes faster without intermediate niddle shape objects ?

**Comment by alecjacobson** [comment]
Take a look at "can mean-curvature flow be made non-singular?" That paper
will describe a solution to your problem and is implemented in tutorial
#205.
