### ISSUE TITLE
How to process output: trim_with_solid

### ISSUE THREAD

**Issue by Megidd** [libigl/libigl#1660]
#### Question

[`trim_with_solid`](https://github.com/libigl/libigl/blob/efee81b7dbc81ec87adaca1197b47f4faab961d3/include/igl/copyleft/cgal/trim_with_solid.h#L18) is called:

```c++
// Trim mesh A (m_VA and m_FA) with solid B (m_VB and m_FB)
igl::copyleft::cgal::trim_with_solid(
    m_VA, m_FA               // input: mesh A
    , m_VB, m_FB             // input: solid B
    , m_V, m_F, m_D, m_J // output
);
```

The output is processed:

```c++
    // Loop over output vertex data
    for (int i = 0; i < m_V.rows(); ++i) {
        // Access all the vertex data
    }

   // Loop over output triangle (face) data
    for (int i = 0; i < m_F.rows(); ++i) {
        // Condition to decide if facet is inside or outside the solid B
        if (m_D.coeff(i)) {
            // The output face is outside the solid B
        } else {
            // The output face is inside the solid B
        }
    }
```

### Fine result

Sometimes the trim result is fine. Like this one which is trimming a teapot model with a solid cylinder:

![image](https://user-images.githubusercontent.com/17475482/100319435-d5b65280-2fd4-11eb-8d8c-2b121e3e4a30.png)

![image](https://user-images.githubusercontent.com/17475482/100319323-a69fe100-2fd4-11eb-97aa-3552a39efd37.png)

### Bad result

But sometimes the trim result is NOT as expected:

![image](https://user-images.githubusercontent.com/17475482/100319125-62acdc00-2fd4-11eb-88be-7112b10bc39d.png)

![image](https://user-images.githubusercontent.com/17475482/100319192-77896f80-2fd4-11eb-8351-2820438f5254.png)

![image](https://user-images.githubusercontent.com/17475482/100319222-853ef500-2fd4-11eb-95cb-1aa2f2b3acc3.png)

As shown by the wire-frame view above, the intersection of teapot and cylinder is identified correctly. But for some reason, this loop is NOT able to detect triangles which are outside the cylinder:

```c++
   // Loop over output triangle (face) data
    for (int i = 0; i < m_F.rows(); ++i) {
        // Condition to decide if facet is inside or outside the solid B
        if (m_D.coeff(i)) {
            // Face is outside the solid B
        } else {
            // Face is inside the solid B
        }
    }
```

Does anybody know what I'm possibly missing?

#### OS

- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by alecjacobson** [comment]
could you post the inputs to trim_with_solve (ideally as .dmat or .ply in
*binary* form)?

**Comment by Megidd** [comment]
@alecjacobson Sure, I shared 4 STL files here:

https://drive.google.com/drive/folders/1MNAgSOfy9PEgIWZWM2VhtCQrd-TrlX-l?usp=sharing

The 4 STL files are shown with MeshLab and described:

![2020-11-29 10_37_43-Window](https://user-images.githubusercontent.com/17475482/100535607-abac9c80-322f-11eb-8f04-f7c092f32bf7.png)

![2020-11-29 10_38_43-Window](https://user-images.githubusercontent.com/17475482/100535606-aa7b6f80-322f-11eb-8d2e-e7340379b851.png)

![2020-11-29 10_39_29-Window](https://user-images.githubusercontent.com/17475482/100535604-a8b1ac00-322f-11eb-933d-de1edb2f788f.png)

![2020-11-29 10_40_18-Window](https://user-images.githubusercontent.com/17475482/100535679-4dcc8480-3230-11eb-9763-93c2b99228a0.png)

**Comment by alecjacobson** [comment]
I think the trouble is that your cylinder is not exactly solid. If I snap together vertices that are _exactly_ the same. There is an open boundary (red edges):
![image](https://user-images.githubusercontent.com/2241689/100684093-a8a4cf80-3347-11eb-9257-77720c24f0d7.png)

If I snap using 9e-7 then this model is solid and the result looks good:

![image](https://user-images.githubusercontent.com/2241689/100684330-1c46dc80-3348-11eb-8863-7171084848f6.png)

So, I'm guessing that your cylinder is getting created/written in a way that vertices which are supposed to be coincident are becoming slightly different.

**Comment by Megidd** [comment]
@alecjacobson 

That was it! Previously, I was using [Qt3DExtras::QCylinderMesh](https://doc.qt.io/qt-5/qt3dextras-qcylindermesh.html). But it was NOT watertight as you noticed. I replaced it with the following code which creates watertight cylinders.

#### Header:

```c++
    // Create a cylinder mesh which is exactly solid
    // without any open boundary
    // Down facing cylinder in Z direction with arguments:
    // r: radius
    // h: Height
    // ssteps: how many edges will create the base circle
    // sp: starting point
    static void cylinder(
            std::vector<QVector3D>& points
            , std::vector<std::array<int, 3>>& indices
            , const float r
            , const float h
            , const size_t ssteps = 45
            , const QVector3D &sp = QVector3D()
            );
```

#### Source:

```c++
void EditorUtils::cylinder(
        std::vector<QVector3D> &points
        , std::vector<std::array<int, 3>> &indices
        , const float r
        , const float h
        , const size_t ssteps
        , const QVector3D &sp
        )
{
    assert(ssteps > 0);

    auto PI = M_PI;

    auto steps = int(ssteps);
    points.reserve(2*ssteps);
    double a = 2*PI/steps;

    QVector3D jp = sp;
    QVector3D endp = {sp.x(), sp.y(), sp.z() + h};

    // Upper circle points
    for(int i = 0; i < steps; ++i) {
        double phi = i*a;
        double ex = endp.x() + r*std::cos(phi);
        double ey = endp.y() + r*std::sin(phi);
        points.emplace_back(ex, ey, endp.z());
    }

    // Lower circle points
    for(int i = 0; i < steps; ++i) {
        double phi = i*a;
        double x = jp.x() + r*std::cos(phi);
        double y = jp.y() + r*std::sin(phi);
        points.emplace_back(x, y, jp.z());
    }

    // Now create long triangles connecting upper and lower circles
    indices.reserve(2*ssteps);
    auto offs = steps;
    for(int i = 0; i < steps - 1; ++i) {
        indices.emplace_back(std::array<int, 3>{i, i + offs, offs + i + 1});
        indices.emplace_back(std::array<int, 3>{i, offs + i + 1, i + 1});
    }

    // Last triangle connecting the first and last vertices
    auto last = steps - 1;
    indices.emplace_back(std::array<int, 3>{0, last, offs});
    indices.emplace_back(std::array<int, 3>{last, offs + last, offs});

    // Try generating a watertight body.
    // So we create a triangle fan for the upper and lower
    // ending of the cylinder to close the geometry.
    points.emplace_back(jp); int ci = int(points.size() - 1);
    for(int i = 0; i < steps - 1; ++i)
        indices.emplace_back(std::array<int, 3>{i + offs + 1, i + offs, ci});

    indices.emplace_back(std::array<int, 3>{offs, steps + offs - 1, ci});

    points.emplace_back(endp); ci = int(points.size() - 1);
    for(int i = 0; i < steps - 1; ++i)
        indices.emplace_back(std::array<int, 3>{ci, i, i + 1});

    indices.emplace_back(std::array<int, 3>{steps - 1, 0, ci});

    return;
}
```

Now the holes are created properly, as far as tested:

![image](https://user-images.githubusercontent.com/17475482/101474129-f761f300-395f-11eb-89a5-43e5391a695b.png)


![image](https://user-images.githubusercontent.com/17475482/101474210-119bd100-3960-11eb-8992-e20bbfbc050f.png)
