### ISSUE TITLE
Weird skeletal deformation

### ISSUE THREAD

**Issue by MotivaCG** [libigl/libigl#1662]
Probably it is my bad but when rotation BoneEdges (BE) my mesh is not getting deformed as expected, it seems that somehow it still uses the parent bone orientation

Initial pose
![image](https://user-images.githubusercontent.com/7759954/100879254-83c96d00-34ab-11eb-9cb4-6734e0fa4bf3.png)

Rotated bone
![image](https://user-images.githubusercontent.com/7759954/100879317-9643a680-34ab-11eb-930f-a97ed4b2e461.png)

- [X] Windows
- [ ] macOS
- [ ] Linux

Thank you in advance for any tip!

**Comment by alecjacobson** [comment]
Could you post a minimal example of your code and the input? This could be a problem with how the weights are computed. And if you're using `bbw` then it could be a problem with the tet-mesh used for computation.
