### ISSUE TITLE
libigl always header-only install even with static lib

### ISSUE THREAD

**Issue by FabienPean** [libigl/libigl#1668]
#### Describe your question
Trying to package and use libigl as a static library with vcpkg https://github.com/microsoft/vcpkg/pull/14888 leads to the problem where libigl does not leave the opportunity to call methods not explicitly instantiated in the cpp file. Vcpkg maintainer requested opening a PR here.

A solution could be to install libigl in all cases as header-only while providing the static lib when the option is set.

#### Check all that apply (change to `[x]`)
- [x] Windows
- [?] macOS
- [x] Linux

**Comment by jdumas** [comment]
If you want to install libigl as a header-only library, then please compile with `LIBIGL_USE_STATIC_LIBRARY=OFF`. You can't do both at the same time though, so you need to chose. Not sure there's any change we need to do on our side.

**Comment by FabienPean** [comment]
As I understood it, that is the issue: both should be possible, one can have both template definition headers and a static lib containing explicit template instantiations. The source of the problem seems to be igl conflating both the template definition and explicit template instantiation within the cpp file instead of splitting them. Perhaps @JackBoosY can hop in and provides details on the concern.

**Comment by jdumas** [comment]
This is not an error. When compiling libigl in static mode, we only use explicit template instantiation and hide the function definitions from the headers to speed up compile times. This is probably not the best way to do it (e.g. using `extern template` may be a better approach). But refactoring this would require significant work, and I don't have a good sense of what's the best way to architecture that (speeding up compilation times is really important).

**Comment by JackBoosY** [comment]
I need official staff to confirm the correctness of the changes.

**Comment by jdumas** [comment]
I'm sorry I'm not official staff enough for you?

**Comment by JackBoosY** [comment]
@jdumas  I'm not clear enough. I mean I hope to open the issue here to let you confirm the correctness of the modification.

**Comment by jdumas** [comment]
What modification are you proposing? We can't expose all the implementations in the header files without a solid plan to ensure compilation speeds are not negatively affected when compiling with `LIBIGL_USE_STATIC_LIBRARY=ON`.

**Comment by JackBoosY** [comment]
@jdumas In PR https://github.com/microsoft/vcpkg/pull/14888.

**Comment by jdumas** [comment]
Ok sounds good. As I said my suggestion is to use the option `LIBIGL_USE_STATIC_LIBRARY=OFF`. This will make libigl into a pure header-only library. Maybe in the future we will have options to mix both explicit instantiations and expose function definitions in headers, but that's a major rework and we need to be careful about that, so I can't provide a timeline for it.

**Comment by JackBoosY** [comment]
@jdumas Thanks!
