### ISSUE TITLE
Viewer Render Issue in "Release" Mode.

### ISSUE THREAD

**Issue by xarthurx** [libigl/libigl#1669]
#### Describe the bug

I updated to the newest master branch `libigl` and compiled projects both in `Debug` and `Release` mode.

Using the `106_ViewerMenu` example, screenshot are shown below:

##### Debug
![image](https://user-images.githubusercontent.com/1921878/101804123-86623d00-3b11-11eb-83b3-549184b36a91.png)

##### Release
![image](https://user-images.githubusercontent.com/1921878/101804010-6d598c00-3b11-11eb-88ff-17e929b82429.png)

* Notice the small triangle on top of the menu bar.
* Compiled in the newest VS2019.
* When switching to `v.2.2.0` release, the problem still exist. So I guess there's sth incompatible with the MSVC?

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by xarthurx** [comment]
Any update on this?
I tried to debug but cannot figure out what is happening...
And it affects the development speed a lot, as the program I'm creating is relatively big and debug mode will no suffice.

Any backup plan?

**Comment by alecjacobson** [comment]
I can't reproduce this on mac. Unless someone on windows gets inspired to track this down, I'm guessing that this won't get fixed until after we overhaul the imgui plugin situation (which might accidentally fix whatever is going wrong here).

**Comment by jdumas** [comment]
I'll try it out on my Windows machine when I can, sorry this slipped my mind...

**Comment by xarthurx** [comment]
OK, I think I found the issue.

```
  m_menu.callback_draw_viewer_window = [&]() {
    float menu_width = 240.f * m_menu.menu_scaling();
    ImGui::SetNextWindowPos(ImVec2(0.0f, 0.0f), ImGuiCond_FirstUseEver);
    ImGui::SetNextWindowSize(ImVec2(0.0f, 0.0f), ImGuiCond_FirstUseEver);
    //ImGui::SetNextWindowSizeConstraints(ImVec2(menu_width, -1.0f), ImVec2(menu_width, -1.0f));
    bool _viewer_menu_visible = true;
    ImGui::Begin("Main Panel", &_viewer_menu_visible,
      //ImGuiWindowFlags_NoSavedSettings | ImGuiWindowFlags_AlwaysAutoResize  <---- This guy.
      ImGuiWindowFlags_NoSavedSettings 
    );
    ImGui::PushItemWidth(ImGui::GetWindowWidth() * 0.4f);
    m_menu.callback_draw_viewer_menu();
    m_menu.callback_draw_mouse_state();
    ImGui::PopItemWidth();
    ImGui::End();
  };
```

The problem is caused by `ImGuiWindowFlags_AlwaysAutoResize`.
If this flag is on, then the issue will emerge.
If we turn off the flag, we should also comment out or define carefully the function `SetNextWindowSizeConstraints` so that menu size can be resized.

`OpenGL` rendering is beyond my knowledge. If there's a fix in the future, perhaps this post will provide useful info.

**Comment by jdumas** [comment]
FYI I have tried on my Windows machine and I cannot reproduce the bug. The ImGui window works fine with both Debug and Release builds, and I am using VS 2019 (MSVC 19.27.29112).

**Comment by xarthurx** [comment]
@jdumas 
Thank you for the test.
Would you please update to the latest VS2019? 
I experienced this issue with the latest version VS2019 16.8.3 (MSVC 19.28.29335).

**Comment by jdumas** [comment]
Ah, interesting, I've just updated to VS 16.8.3 and indeed I see the bug now. This looks like a compiler-related bug, but I'm not familiar enough with ImGui to determine what could be causing this. Maybe @ocornut could help us out on this one?

**Comment by ocornut** [comment]
Try to use the Debugger/Metrics window first to look into the data for this window. Then you can either try to create a standalone repro or step into Begin() and try to understand how ContentSize and Size are setup.

**Comment by xarthurx** [comment]
@ocornut  
The problem is in `Debug` mode, the issue doesn't appear.
And in `Release` mode, breakpoint does not work in VS2019 (Or is there a way to use breakpoint?)

**Comment by mmalex** [comment]
hello! I looked into this a little. as @xarthurx suggests, this problem is caused by the flag ImGuiWindowFlags_AlwaysAutoResize somehow, and can be worked around by removing that flag.
I tried adding the debugger metrics window as @ocornut suggested and it shows that the viewer has a vertical size of 0.0! I can't see why this would happen, especially as it only happens in release builds on windows (not mac). see screenshot below:
![image](https://user-images.githubusercontent.com/715855/107752738-104ba380-6d17-11eb-8525-6e64d295e7ac.png)

**Comment by mmalex** [comment]
a little more poking. the relevant area of code in igl is shown below. the problem is caused by the SetNextWindowSizeConstraints call with a negative height. if you comment out that line, the app behaves as I would expect; if you set largish positive values for the min and max height (100 and 200, say) then the window is too small but is no longer 'buggy'. So I think a reasonable workaround that doesn't change behaviour of igl as far as I can see, is to remove that call. As to why it behaves differently across platforms/build types, I haven't investigated but it will be something inside imgui with this sequence of calls with these parameters. 
![image](https://user-images.githubusercontent.com/715855/107754213-12aefd00-6d19-11eb-9d6f-218dce4a0f14.png)

**Comment by ocornut** [comment]
Hello Alex :)

I'm going to investigate but failing to get a repro at the moment (tho already I can tell the constraint doesn't behave as expected, without _AlwaysAutoResize, using <0.0f should still allow to manually resize on that axis but right now it doesn't).

What is probably not helping is the `SetNextWindowSize(ImVec2(menu_width, 1.f))` call setting an initial height of -1.0f.

About the build type difference: we run static-analysis on dear imgui so although I don't doubt there are bugs in there (and the sequencing of code in caller and inside CalcWindowSizeAfterConstraint() leading to use that SizeConstraints value and combined with _AlwaysAutoResize is a little fishy to me right now), I'd be surprised if there are any use of uninitialized variables in there.

I'll investigate further.

**Comment by mmalex** [comment]
thanks omar! yes sorry I had forgotten that I had made that change locally. I was trying all sorts of combinations to try to narrow down what was causing it. Regardless, the outcome in the inspector is always a 0 height. I will have a look later too, but am teaching home school at the moment so I just managed the minimal repro for now :) perhaps menu_width is garbage on the first frame or something? <random theory>

**Comment by mmalex** [comment]
if it's useful, this line is responsible for choosing the incorrect 0 size,  `new_size.y = (cr.Min.y >= 0 && cr.Max.y >= 0) ? ImClamp(new_size.y, cr.Min.y, cr.Max.y) : window->SizeFull.y;` and it is using window->SizeFull.y which is 0 in Release builds and 767 (on my machine) on Debug builds. Im not sure where window->SizeFull is set yet.

**Comment by ocornut** [comment]
I build igl's example here and can repro

**Comment by mmalex** [comment]
I'm pretty sure this is some weird compiler optimization issue for MSVC in release builds in function CalcWindowAutoFitSize. check this out:  around the call site (line 5623) I do this:
```printf("before\n");
        const ImVec2 size_auto_fit = CalcWindowAutoFitSize(window, window->ContentSize);
        printf("autofit y %f\n", size_auto_fit.y);```
on the last line of the CalcWindowAutoFitSize, I print out the y coordinate of the return value:
`printf("autofit %f\n", size_auto_fit.y);`
clearly they should be the same. they are not. tty output:
```
before
autofit 794.000000
autofit y 0.000000
```
looking at the disassembly, the correct value is in xmm6 at the time of the printf, but is replaced with a value read from the stack (!) just before actually returning:
![image](https://user-images.githubusercontent.com/715855/107774158-8c091880-6d36-11eb-8d2a-611bd36b42fc.png)
the movaps xmm6 is the one that puts junk into xmm6 which is picked up on return.
placing a `#pragma optimize( "", off )` and on pair around CalcWindowAutoFitSize also fixes the issue. the extra bizarre thing to sprinkle on top is that the same function is called 3 times per frame, and only 'fails' one time out of 3. I feel like I'm not at the bottom of this yet but... ugh

**Comment by ocornut** [comment]
> I'm pretty sure this is some weird compiler optimization issue for MSVC 

Nice find. You probably better equipped than me to make such a statement :)
Everytime I suspected something like that it was my fault, maybe there's some unobvious reliance on UB somewhere.

I briefly scanned the code and intuitively felt that the fact that `CalcWindowSizeAfterConstraint()` modifies its `ImVec2 new_size` parameter was a little unusual in the codebase. Not incorrect but unusual and a mess up of the optimizer could read back a value that was modified on the stack/registers of that function... 

Indeed, changing
```cpp
static ImVec2 CalcWindowSizeAfterConstraint(ImGuiWindow* window, ImVec2 new_size)
{
    ImGuiContext& g = *GImGui;
```
into
```cpp
static ImVec2 CalcWindowSizeAfterConstraint(ImGuiWindow* window, const ImVec2& new_size_request)
{
    ImGuiContext& g = *GImGui;
    ImVec2 new_size = new_size_request;
```

Seemingly fixed it for me...

I am not sure what to make of it. Of course I can push the "fix" (and you can certainly apply it to libigl) but I imagine it'll bite us back someday.

**Comment by ocornut** [comment]
As an experiment I did some search & replace in dear imgui codebase:

`(ImVec2 ` -> `(const ImVec2 `
`, ImVec2 ` -> `, const ImVec2 `

In attempt to detect ImVec2 passed as functions arguments and modified in the function.

I found 21 assignments in 7 unique functions:
`ImGui::ColorButton()`, `ImGui::PlotEx()`, `ImFont::RenderChar()`, `ImFont::RenderText()`, `ImGui::RenderCheckMark()`, `ImVec2 CalcWindowSizeAfterConstraint()`, `ImGui::CalcItemSize()`. 

Offending one `CalcWindowSizeAfterConstraint()` is the only static function, not exposed outside of its compilation unit, which I _guess_ leaves more room for compiler to try to do optimizations across the function call boundary.

**Based on this I am going to push the fix as a cargo-cult leap of faith (with link back to this place).**

Feel free to make the change in libigl's version of dear imgui (1.71) to update to 1.81+ in a few minutes.

**Comment by mmalex** [comment]
thanks omar! I think that leaves a few workarounds in the short term (remove flag ImGuiWindowFlags_AlwaysAutoResize , or remove call to SetNextWindowSizeConstraints, or de-optimize CalcWindowSizeAfterConstraint, or pull new imgui :) so many choices for alec! :)

**Comment by jdumas** [comment]
Oh wow thanks @mmalex and @ocornut for investigating! This bug seems pretty gnarly... I will update our version of ImGui later this week-end. What's puzzling to me is that this bug seems to have been introduced fairly recently (maybe last time we updated our ImGui version).

**Comment by mmalex** [comment]
I think it might be linked to a recent visual studio update, perhaps? going by one of the issue titles. no idea tho.
