### ISSUE TITLE
Connect inner and outer walls of a hollow mesh after trim_with_solid

### ISSUE THREAD

**Issue by Megidd** [libigl/libigl#1671]
#### Background

I tried [`trim_with_solid`](https://github.com/libigl/libigl/blob/508cb9940f4d1e8e54137d5afe2fd2eb9c4dc672/include/igl/copyleft/cgal/trim_with_solid.h#L18) method to drill a hole into a 3D model:

```
igl::copyleft::cgal::trim_with_solid(VA, FA, VB, FB, V, F, D, J);
```

But for hollowed 3D models with inner and outer walls, the hole is *not* closed:

[![Inner and outer walls][1]][1]

### Question

I couldn't figure out how to use the `trim_with_solid` output to connect inner and outer walls. Is there such a tool? Is there any standard approach which might help? Thanks =)

  [1]: https://i.stack.imgur.com/2h2Fp.png

#### OS

My OS is Windows 10

**Comment by alecjacobson** [comment]
`trim_with_solid` won't do this. You probably want to do a `mesh_boolean` subtraction. For that, both models need to be piecewise constant winding number http://www.cs.columbia.edu/cg/mesh-arrangements/#definitions .

    igl::copyleft::cgal::mesh_boolean(VA, FA, VB, FB, 'minus', V, F, D, J);

**Comment by Megidd** [comment]
@alecjacobson Thanks! Is there any libigl tool which would help me make the input meshes PWN (piecewise constant winding number)? I try to make sure I'm going to use all available options 😄

**Comment by alecjacobson** [comment]
It really depends on the type of problems you have. Here's a twitter thread where I and few others discuss some algorithms out there:

https://twitter.com/cba/status/1328832748706885633?s=20

**Comment by Megidd** [comment]
This procedure worked fine:

* Fixing the mesh manually by `MeshFix.exe`
* Calling IGL CGAL on fixed mesh:

```c++
igl::copyleft::cgal::mesh_boolean(VA, FA, VB, FB, igl::MESH_BOOLEAN_TYPE_MINUS, V, F);
```

![image](https://user-images.githubusercontent.com/17475482/103077244-af400300-45e4-11eb-870b-bdf9b17fb8a7.png)

![image](https://user-images.githubusercontent.com/17475482/103077255-b5ce7a80-45e4-11eb-98f3-50e0cecaee33.png)

![image](https://user-images.githubusercontent.com/17475482/103077288-c2eb6980-45e4-11eb-9bb3-ed6e7a16daa1.png)
