### ISSUE TITLE
Empty image in  607_ScreenCapture 

### ISSUE THREAD

**Issue by cheshmi** [libigl/libigl#1677]
The 607_ScreenCapture example generates an empty png on Linux. The issue does not happen in Mac. Am I missing a setting somewhere? 

- [ ] Windows
- [ ] macOS
- [X] Linux

**Comment by BruegelN** [comment]
Which distribution & DE are you running?
On my Ubuntu machines pressing **1** results in the following out.png (everything as expected) :
![out](https://user-images.githubusercontent.com/9728182/102232413-622aa580-3eef-11eb-9fce-6cd13cc00627.png)

**Comment by cheshmi** [comment]
I am using Ubuntu 16.04 and GNome. So, maybe it is not about Ubuntu. I am investigating it.

**Comment by cheshmi** [comment]
It seems it works well on Ubuntu 18.
In my Machine, the following assertion fails:
assert(glCheckFramebufferStatus(GL_FRAMEBUFFER) == GL_FRAMEBUFFER_COMPLETE); line 285 of ViewerCore.cpp.

**Comment by alecjacobson** [comment]
Are you running on a machine with an actual monitor hooked up? Or trying to run headless on a server?

**Comment by cheshmi** [comment]
The machine had a monitor. I don't have the machine anymore so I close the issue.
Thanks.
