### ISSUE TITLE
Time consumption by cgal::mesh_boolean

### ISSUE THREAD

**Issue by Megidd** [libigl/libigl#1685]
### Background

I use the following statement to do a boolean operation 

```c++
igl::copyleft::cgal::mesh_boolean(VA, FA, VB, FB, igl::MESH_BOOLEAN_TYPE_MINUS, V, F);
```

Before hand, I fix the input mesh with [MeshFix](https://github.com/MarcoAttene/MeshFix-V2.1) binary I built. 

### Problem: time consumption

The problem is that it takes too much time to finish the job. For example an input mesh of `1.8 MB` in size would take around `20 min` or more. Another example, an input mesh of `43 MB` in size would *not* finish even after `2 hours and 30 min`.

### Question

Is this kind of time consumption normal? Or am I missing something?

### Sample

This is a sample for reference. The `A` mesh is around `10 MB`, and the `B` mesh is a cylinder of around `3 KB` in size. On my machine, after `30 min`, process is *not* finished yet. The meshes STL binaries are shared here:

https://drive.google.com/drive/folders/1Vnxg9Hr-S1_XczgOMoPggAtPcYFlSahq?usp=sharing

![image](https://user-images.githubusercontent.com/17475482/103088034-c68bea00-45fe-11eb-84db-6f7bef1a60cc.png)

Thanks! I appreciate any help =)

**Comment by alecjacobson** [comment]
On my machine (macbook pro), this took 4.69 seconds.

Here're two guesses:

1. Are you compiling in debug mode? Try release mode.

2. Are you loading in these models as .stl files? Use .obj/.ply or another file type that stores triangle _meshes_ rather than triangle _soups_. The issue with .stl is that each triangle is just a list of 3d positions and there is no explicit triangle adjacency information. For Booleans this means that neighboring triangles must be identified as geometrically *intersecting* at shared edges and vertices. This is very costly way of determining that the mesh is well connected.

If you must load them as .stl, you can pre-process them before calling `mesh_boolean` with `remove_duplicate_vertices`.

**Comment by Megidd** [comment]
@alecjacobson You are right. In *release* mode, it takes just a few seconds to finish the boolean `minus` operation:

![image](https://user-images.githubusercontent.com/17475482/103147958-99ab1480-476f-11eb-923c-5e7e3fdcc11b.png)

**Comment by cljbb** [comment]
@Megidd , I encountered the same problem even when I compile my VS 2022 project in the release mode.

I program is cross-platform, Win, Mac, and Linux. The Mac and Linux version has mesh_boolean function runs very fast but the Windows version is running very slowly. For example two 1MB mesh to input to mesh_boolean can take about 1 hour to run (in release mode).

Do you have similar experience in your program in the release mode?

**Comment by Megidd** [comment]
@cljbb Release mode is expected to be fast and debug mode slow.

**Comment by cljbb** [comment]
@Megidd , thank you for your reply. My problem remains even under release mode. Very strange. Did you compile your project by including the header-only files of libigl?

My project includes libigl with headers only, except that it requires libgmp-10.lib (statically linked).

The libgmp-10.lib is downloaded during libigl set up in gmp-src/lib folder. 

Is your project, did you encounter similar situation?

Thank you.

**Comment by Megidd** [comment]
@cljbb I checked the source code to remember. Looks like I was using header-only IGL as commented on my Qt `*.pro` file:

> Header-only libraries don't have binaries to LINK to

```

#################################################################################
# Eigen and libigl
#################################################################################

# Needed for alternative supporting approach
# Header-only libraries don't have binaries to LINK to

INCLUDEPATH += deps/eigen-3.3.9
### Header-only: just download and place in proper location:
INCLUDEPATH += deps/libigl-2.3.0/include
```

**Comment by cljbb** [comment]
@Megidd, thank you for your reply.

That is a little bit different from my situation. I included header only libigl files just to be able to use the mesh_boolean function; however, during compilation I got some errors, saying several "__gmp ... " functions are missing implementation.

I looked in the libigl folder and found that there is a gmp-src\libgmp-10.lib downloaded during the libigl setup process; so I included libgmp-10.lib in my Visual Studio 2022 project; then the compilation was successful.

But my program in Win is significantly slower than the same program compiled in Mac and Linux. It is so slow as if it was in debug mode but it is actually in the release mode. If I turn it to the debug mode, it is even slower.

I really don't know what happened. Hopefully @alecjacobson may come up with some ideas.

By the way, I have two Windows PC, Win 10 and Win 11. I set up libigl in both PCs afresh. Some problem occurs in both PC.

Secondly, the code of mesh_boolean used parallel processing (multi-thread of C++), it can cause crash on some PCs. Not on mine but on the users' of my program. This problem is not specific to libigl but is observed in many programs using multi-thread of C++. So this is a secondary issue.

**Comment by Megidd** [comment]
> That is a little bit different from my situation. I included header only libigl files just to be able to use the mesh_boolean function; however, during compilation I got some errors, saying several "__gmp ... " functions are missing implementation.
> 
> I looked in the libigl folder and found that there is a gmp-src\libgmp-10.lib downloaded during the libigl setup process; so I included libgmp-10.lib in my Visual Studio 2022 project; then the compilation was successful.

@cljbb That's very strange. As far as I know, the header-only means no other dependency, that's it. So, the `gmp` dependency doesn't make sense to me.

**Comment by cljbb** [comment]
@Megidd , libigl doc says header-only if we only use libigl native API but if we use API related to external packages, such as cgal, it may not be header-only. Cgal depends on gmp; so gmp needs to be used.

Your project might have used gmp on its own; therefore, you might not need to explicitly link gmp just for using the mesh_boolean function.

This is all my guessing. I don't know for sure, unfortunately. @alecjacobson seems to be out of reach either.

**Comment by Megidd** [comment]
> Your project might have used gmp on its own; therefore, you might not need to explicitly link gmp just for using the mesh_boolean function.

@cljbb You're right. My Qt project's `*.pro` file has some comments about how to install CGAL along with `gmp` on Windows, Linux, and macOS. Maybe those comments would be helpful for you:

```pro

#################################################################################
# CGAL on Windows
# CGAL is required by IGL for <igl/copyleft/cgal/trim_with_solid.h>
#################################################################################

### How to install
#
# cd %userprofile%\repos\vcpkg\
# vcpkg.exe install cgal --triplet x64-windows
### if errors are thrown, try these two commands:
# .\vcpkg update
# git pull
### Now, re-run:
# vcpkg.exe install cgal --triplet x64-windows
### If this error is received: "Please install yasm-tool:x86-windows first" have to run:
# vcpkg.exe install yasm-tool:x86-windows
# vcpkg.exe install cgal --triplet x64-windows

### Use gmp rather than mpir
### MPIR is a fork of GMP
### They cannot be installed together and cgal depends on gmp
#
### Remember to copy "vcpkg/installed/x64-windows/bin/gmp.dll" next to executable
win32: LIBS += -L$$PWD/../../vcpkg/installed/x64-windows/lib/ -lgmp

### Remember to copy "vcpkg\installed\x64-windows\bin\mpfr.dll" next to executable
win32: LIBS += -L$$PWD/../../vcpkg/installed/x64-windows/lib/ -lmpfr

INCLUDEPATH += $$PWD/../../vcpkg/installed/x64-windows/include
DEPENDPATH += $$PWD/../../vcpkg/installed/x64-windows/include

#################################################################################
# CGAL on Linux
#################################################################################

# CGAL depends on Boost library,
# however CGAL-5.2.2 is NOT throwing any Boost dependency error,
# so all required Boost libraries might already be satisfied

# CGAl depends upon GMP and MPFR libraries
# provided under various names by Linux distro package managers

### openSUSE Leap 15.3:
# sudo zypper in mpfr-devel

unix:!macx: LIBS += -L$$PWD/../../../../../usr/lib64/ -lgmp

INCLUDEPATH += $$PWD/../../../../../usr/lib64
DEPENDPATH += $$PWD/../../../../../usr/lib64

unix:!macx: PRE_TARGETDEPS += $$PWD/../../../../../usr/lib64/libgmp.a

unix:!macx: LIBS += -L$$PWD/../../../../../usr/lib64/ -lmpfr

# CGAL-5.2.2 is downloaded and extracted inside
# ~/repos/qt3d-editor/editorlib/deps
#
# https://doc.cgal.org/latest/Manual/usage.html#secusingwebsite

unix:!macx: INCLUDEPATH += deps/CGAL-5.2.2/include/

#################################################################################
# CGAL on macOS
#################################################################################

# On macOS, it is recommended to use Homebrew:
# brew install cgal
#
# https://doc.cgal.org/latest/Manual/usage.html

macx: LIBS += -L$$PWD/../../../../../usr/local/Cellar/gmp/6.2.1/lib/ -lgmp

INCLUDEPATH += $$PWD/../../../../../usr/local/Cellar/gmp/6.2.1/include
DEPENDPATH += $$PWD/../../../../../usr/local/Cellar/gmp/6.2.1/include

macx: PRE_TARGETDEPS += $$PWD/../../../../../usr/local/Cellar/gmp/6.2.1/lib/libgmp.a

macx: LIBS += -L$$PWD/../../../../../usr/local/Cellar/mpfr/4.1.0/lib/ -lmpfr

INCLUDEPATH += $$PWD/../../../../../usr/local/Cellar/mpfr/4.1.0/include
DEPENDPATH += $$PWD/../../../../../usr/local/Cellar/mpfr/4.1.0/include

macx: PRE_TARGETDEPS += $$PWD/../../../../../usr/local/Cellar/mpfr/4.1.0/lib/libmpfr.a
```
