### ISSUE TITLE
Compile CSG Boolean Example

### ISSUE THREAD

**Issue by petrasvestartas** [libigl/libigl#1688]
Hi,

I would like to ask how can I compile 610_CSGTree example using CMake.
igl_copy_cgal_dll is not found.

What should I do to properly compile this example?

#### Check all that apply (change to `[x]`)
- [x ] Windows
- [ ] macOS
- [ ] Linux

![image](https://user-images.githubusercontent.com/18013985/103411317-a2388c00-4b6f-11eb-84a3-ecad393bf178.png)

**Comment by jdumas** [comment]
You need to use either `tutorial/` or the root folder as the entry point to your CMake. Using the tutorial 610 folder directly is not gonna work.

**Comment by petrasvestartas** [comment]
I tried to compile using tutorial as root but CGAL is missing. I tried to reference it as I do typically in CGAL, it is still not found.

![q](https://user-images.githubusercontent.com/18013985/103439696-77b60400-4c3f-11eb-99af-72de6a9d00f4.png)

**Comment by jdumas** [comment]
You need to enable the `LIBIGL_WITH_CGAL` CMake option.

**Comment by petrasvestartas** [comment]
Do I need to set GMP and other option at CGAL part to true?
If keep it unticked visual studio still cannot find CGAL.
If tick those two options, CMake would give me this error:
![qqqq](https://user-images.githubusercontent.com/18013985/103444732-bcf02b00-4c6b-11eb-9966-87de8096be36.png)

**Comment by jdumas** [comment]
Don't tick any other option beside `LIBIGL_WITH_CGAL`. If any problem persists delete your build folder and try again.

**Comment by petrasvestartas** [comment]
It seems to run. The problem was that I addend main.cpp of CSG to /tutorial folder. After removing 101_IO project build is successful.

Now I would like to learn how can I reference C++ libraries to empty Visual Studio console app without CMake.
Typically I reference header files from C/C++ and library folders from Linker/Input

I opened both of these tabs and how many references are needed to make project work.

Normally I write full path where libraries are stored.
But in libigl you use some shortcut.

For instance what does two dots mean in Linker?
..\glad\Release\glad.lib
..\glfw\src\Release\glfw3.lib

And in header files multiple /../../../?
C:\libs\libigl\external\cgal\Installation\lib\cmake\CGAL\..\..\..\..\Distance_2\include

Also do I need all these reference for CSG example?

![Success](https://user-images.githubusercontent.com/18013985/103445431-4c99d780-4c74-11eb-9326-fdd6e676a32c.png)
![a1](https://user-images.githubusercontent.com/18013985/103445432-4dcb0480-4c74-11eb-80df-4b274f7c65e6.png)
![a2](https://user-images.githubusercontent.com/18013985/103445433-4dcb0480-4c74-11eb-9057-22be3eb3d01d.png)

**Comment by jdumas** [comment]
CMake can generate a Visual Studio project for you, so I don't really understand what you are trying to achieve?

**Comment by petrasvestartas** [comment]
I would like to compile LibIgl cag method to Dll with additional PInvoke to call this method in c#. I managed to do this with CGAL.

Is there a way to compile .csg method as dll using CMake?

**Comment by jdumas** [comment]
Libigl is a header-only library, so there is no .dll to compile, unless you enable the CMake option `LIBIGL_USE_STATIC_LIBRARY`. But this option will produce a static library (.lib). Building libigl as a shared library is not supported for now.

**Comment by petrasvestartas** [comment]
For dynamic lib is this possible or not at all:

1. I create Visual Studio .dll project.
2. Use methods from 610 csg example
3. Copy paste from C/C++ header and in Linker reference libraries.

I have seen people compiled libigl into dynamic lib and therefore asking if there is any tutorial? Even it is not supported by design.

**Comment by jdumas** [comment]
I would suggest you to use CMake to create your own shared lib using libigl in header-only mode (`LIBIGL_USE_STATIC_LIBRARY=OFF`), then write your own wrapper function to be compiled into your dll. You can use [libigl-example-project](https://github.com/libigl/libigl-example-project) as a template to create your own cmake project using libigl, then simply replace `add_executable()` by `add_library()` (and removed the `main()` function), build with the CMake option `BUILD_SHARED_LIBS=ON` and you should be good to go. Don't try to create the visual studio project directly it's much easier to start from CMake.

**Comment by petrasvestartas** [comment]
Thank you the answer.

Can you elaborate where can I find this:
`then simply replace add_executable() by add_library()`

**Comment by jdumas** [comment]
Yes I am referring to the CMakeLists.txt.

Look, it seems that you are trying to do something pretty complex (you mention C# bindings), without basic knowledge of CMake. I can try to provide basic support, but at some point you're better off learning to use CMake by yourself, it's a valuable skill to learn anyway. Here are some good resources to learn CMake:
- [Introduction to Modern CMake](https://cliutils.gitlab.io/modern-cmake/), a good booklet, fairly succinct
- [How to CMake Good](https://www.youtube.com/playlist?list=PLK6MXr8gasrGmIiSuVQXpfFuE1uPT615s), playlist of video tutorials, if that's your thing

**Comment by petrasvestartas** [comment]
Hi,

Today I watched youtube tutorials for CMake, it was a lot to digest, but I watched all of them.

Could you tell me if I followed the .DLL compilation correctly?

1 Step: I changed CMakeList in tutorial folder like this:
![Step1](https://user-images.githubusercontent.com/18013985/103465562-3a37a080-4d3d-11eb-9151-e29a45b300d8.png)

2 Step: I added .hpp and .cpp file just with 1 empty method linking CGAL and IGL
I also modified CMakeLists of 610CSG by adding a library.

![Step2](https://user-images.githubusercontent.com/18013985/103465581-74a13d80-4d3d-11eb-9f87-3a2c6419c9bf.png)

The compilation is success.
I get CGAL .dll copied to debug folder and .lib file.

**Question:
I get 611_CSGTreeDLL.lib, but how can I get .dll file?**

**Comment by jdumas** [comment]
Yes, adding the `SHARED` keyword will produce a .dll. Alternatively, do not add any keyword and use the CMake option `BUILD_SHARED_LIBS=ON` to build libraries as .dll. Otherwise looks like you are on the right track!

**Comment by petrasvestartas** [comment]
Thank you for the answer. It seems connection between C# and C++ works. Now I am learning about CSG method.
Could you please answer following questions:

1. What are these data-structures stands for?
```
          CSGTree M;
          Matrix<MatrixXi::Index, Dynamic, 1> J;
```

2. Also why these is addition of rows to J (blue color) ?
3.  And how can I get all vertices and all faces from the CSG Mesh boolean result M or J?

**Comment by jdumas** [comment]
The CSG tree is described in the [tutorial entry](https://libigl.github.io/tutorial/#csg-tree). The array J is an array of "birth facets", indicating which input mesh facet an output facet comes from. Facets between [0, #FA[ correspond to the first mesh A, while facets between [#FA, #FA+#FB[ correspond to the second mesh B. `CSGTree::V()` and `CSGTRee::F()` will contain the vertices/facets of the CSG result mesh.

**Comment by petrasvestartas** [comment]
Thank you it makes more clear.
I also managed to run boolean operation and retrieve good result in C# between two closed valid meshes.

Is there any possiblity to compute boolean operation between multiple meshes?

I use code below to compute boolean between 2 meshes:

	const igl::copyleft::cgal::CSGTree t{ {VA_R, FA_R}, {VB_R, FB_R}, type };//"union"
	MatrixXd VertexOut = t.cast_V<MatrixXd> ();
	MatrixXi IndicesOut = t.F ();


But in a case when I have multiple meshes like this? How can I proceed?
In the examples I always see a fixed number of inputs.
	std::vector<MatrixXd> V;
	std::vector<MatrixXi> F;

**Comment by jdumas** [comment]
Please look at the tutorial entry, it shows an example with >2 meshes.

**Comment by petrasvestartas** [comment]
I went through tutorial I really need help to understand how can I change this line of code:
`igl::copyleft::cgal::CSGTree<MatrixXi> CSGTree =  {{{VA,FA},{VB,FB},"i"},{{{VC,FC},{VD,FD},"u"},{VE,FE},"u"},"m"};`

to situations when number of meshes varies 2, 3, 5, n meshes.
This part would definetely change: {{{VA,FA},{VB,FB},"i"},{{{VC,FC},{VD,FD},"u"},{VE,FE},"u"},"m"};
Is it possible somehow to automate this step when number of user input meshes is unknown?

**Comment by petrasvestartas** [comment]
Ok, I am trying to get it, it is a matrix...

**Comment by petrasvestartas** [comment]
I am honestly confused.

How can I write a CSGTree for a situation like this?

I have one mesh:
        MatrixXd VA;
	MatrixXi FA;
and  a list of meshes:
	std::vector<MatrixXd> V;
	std::vector<MatrixXi> F;


I would like to perform boolean difference from VA FA by subtracting all V and F meshes.

**Comment by jdumas** [comment]
The CSGTree has a constructor:
```cpp
CSGTree(const CSGTree & A,
        const CSGTree & B,
        const MeshBooleanType & type)
```
which you can use to build the result of a CSG operation involving an arbitrary number of meshes, you just need to build the tree yourself.

Alternatively you may want to look into the `igl::combine()` function to merge your N meshes into a single one prior to computing the CSG union/difference, that might be more efficient.

**Comment by petrasvestartas** [comment]
Hi,

Thank you for the reference I will try to use it.

I am stuck at another step, it seems I am missing some basic C++ and Eigner library knowledge.
I would like to create a vector of vertices and faces.

If I declare vertices and faces list and the append vectors of matrices nothing get added once I push_back.
After for loop V[0], F[0] is completely empty.

```
std::vector<MatrixXd> V; V.resize(n_mesh);
std::vector<MatrixXi> F; F.resize (n_mesh);
for ( size_t i = 0; i < n_mesh; i++ ) {
        ...create and fill VA_R and FA_R matrices
	V.push_back (VA_R);
	F.push_back (FA_R);
}
```

If I create a dynamic array of matrices application crashes:
	MatrixXd* V = new MatrixXd[n_mesh];
	MatrixXi* F = new MatrixXi[n_mesh];
        ...fill this array and perform csg
	delete V;
	delete F;

The only way I could make an array work is by allocating array on stack like this it works but it is not what I want since n_mesh variable may change:

	MatrixXd* V = new MatrixXd[2];
	MatrixXi* F = new MatrixXi[2];

**Comment by alecjacobson** [comment]
If you use vector.resize(n) then you should just use vector[i] = ... rather
than push_back.

push_back appends to the end of the list. So you're probably ending up with
a vector of length 2n.

>

**Comment by petrasvestartas** [comment]
Dear @alecjacobson ,

Thank you for the answer it compiles and runs successfully.
![bunnies](https://user-images.githubusercontent.com/18013985/103557382-66752d80-4eb3-11eb-9c4e-62465bfab0fb.jpg)


I have an issue with performance boolean difference between these two bunnies takes 21 sec, while CGAL takes 150 ms.
I compile my DLL in Release mode.

What I am doing wrong so that it takes so much time?

I attach the full code:


```
PINVOKE void LIBIGL_MeshBoolean_CreateArrayNoColors (


	double* coord_mesh, int* n_coord_meshArray,//Flat array of coordinates / 0 256 512 flat array of vertices array / number of meshes
	int* faces_mesh, int* n_faces_meshArray,
	size_t n_mesh,

	size_t Difference_Union_Intersection,

	double*& coord_out, int& n_coord_out,
	int*& faces_out, int& n_faces_out

) {




	using namespace Eigen;
	using namespace igl::copyleft::cgal;
	using namespace std;
	using namespace igl;

	////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	//Create Mesh
	////////////////////////////////////////////////////////////////////////////////////////////////////////////////

   std::vector<MatrixXd> V; V.resize(n_mesh);
	std::vector<MatrixXi> F; F.resize (n_mesh);
	//Eigen::MatrixXd* V = new MatrixXd[n_mesh];
	//MatrixXi* F = new MatrixXi[n_mesh];

	////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	//Create Mesh
	////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	for ( size_t i = 0; i < n_mesh; i++ ) {

		int nv = n_coord_meshArray[i + 1] - n_coord_meshArray[i];
		int nf = n_faces_meshArray[i + 1] - n_faces_meshArray[i];

		MatrixXd VA_R = MatrixXd (nv, 3);
		MatrixXi FA_R = MatrixXi (nf, 3);


		int couter = 0;
		for ( int j = n_coord_meshArray[i]; j < n_coord_meshArray[i + 1]; j++ ) {
			VA_R (couter, 0) = coord_mesh[3 * j + 0];
			VA_R (couter, 1) = coord_mesh[3 * j + 1];
			VA_R (couter, 2) = coord_mesh[3 * j + 2];
			couter++;
		}
	

		couter = 0;
		for ( int j = n_faces_meshArray[i]; j < n_faces_meshArray[i + 1]; j++ ) {
			FA_R (couter, 0) = faces_mesh[3 * j + 0];
			FA_R (couter, 1) = faces_mesh[3 * j + 1];
			FA_R (couter, 2) = faces_mesh[3 * j + 2];
			couter++;
		}


		V[i] = VA_R;
		F[i] = FA_R;

	}


	auto type = igl::MeshBooleanType::MESH_BOOLEAN_TYPE_MINUS;
	if ( Difference_Union_Intersection == 1 )
		type = igl::MeshBooleanType::MESH_BOOLEAN_TYPE_UNION;
	if ( Difference_Union_Intersection == 2 )
		type = igl::MeshBooleanType::MESH_BOOLEAN_TYPE_INTERSECT;
	if ( Difference_Union_Intersection == 3 )
		type = igl::MeshBooleanType::MESH_BOOLEAN_TYPE_RESOLVE;
	if ( Difference_Union_Intersection == 4 )
		type = igl::MeshBooleanType::MESH_BOOLEAN_TYPE_XOR;



	igl::copyleft::cgal::CSGTree t{ {V[0], F[0]}, {V[1], F[1]}, type };
	for ( size_t i = 1; i < n_mesh; i++ ) {
		t = igl::copyleft::cgal::CSGTree{ t,{V[i], F[i]}, type };
	}


	MatrixXd VertexOut = t.cast_V<MatrixXd> ();
	MatrixXi IndicesOut = t.F ();


   ////////////////////////////////////////////////////////////////
   // Return vertex and face array
   ////////////////////////////////////////////////////////////////

	coord_out = new double[VertexOut.rows () * 3];

	for ( int i = 0; i < VertexOut.rows (); i++ ) {
		coord_out[i * 3 + 0] = VertexOut (i, 0);
		coord_out[i * 3 + 1] = VertexOut (i, 1);
		coord_out[i * 3 + 2] = VertexOut (i, 2);
	}
	n_coord_out = VertexOut.rows ();

	faces_out = new int[IndicesOut.rows () * 3];

	for ( int i = 0; i < IndicesOut.rows (); i++ ) {
		faces_out[i * 3 + 0] = IndicesOut (i, 0);
		faces_out[i * 3 + 1] = IndicesOut (i, 1);
		faces_out[i * 3 + 2] = IndicesOut (i, 2);
	}

	n_faces_out = IndicesOut.rows ();


	//Clean memory
	//delete[] V;
	//delete[] F;


}


```

**Comment by alecjacobson** [comment]
that certainly sounds too slow. Can you attach the bunny meshes so I can
try when I create time?

>

**Comment by petrasvestartas** [comment]
Hi,

I attached both bunnies here. 
[Bunnies.zip](https://github.com/libigl/libigl/files/5768826/Bunnies.zip)

I face the same problem also with libigl example meshes.

**Comment by petrasvestartas** [comment]
Is there any reason CGAL and LIBIGL mesh booleans are so different in performance?

**Comment by alecjacobson** [comment]
Probably! I haven't tried they're newest mesh Booleans. I vaguely recall
reading that they're limited to polyhedral input.

>

**Comment by petrasvestartas** [comment]
I would like to thank you @jdumas and @alecjacobson  for a great support. I think I learnt a lot and I think the issue is closed.
