### ISSUE TITLE
file_dialog_open and file_dialog_save does not compile

### ISSUE THREAD

**Issue by bekorn** [libigl/libigl#1689]
#### Describe your question

I'm using Visual Studio 2017 and c++17. The files `file_dialog_open.cpp` and `file_dialog_save.cpp` does not compile when I use the OpenGL viewer. (`igl/opengl/glfw/Viewer.h`) 

The errors are same for both files and look like this:
![image](https://user-images.githubusercontent.com/5175163/103456816-c7adcd00-4d0a-11eb-96b2-c96ed9160454.png)

I managed to solve the issue by explicitly casting both values into `wchar_t*`. 
![image](https://user-images.githubusercontent.com/5175163/103456897-91bd1880-4d0b-11eb-8c97-3024c8bac80f.png)

However, I have no idea what I'm doing, so not sure if this is a proper fix or not.

#### Check all that apply (change to `[x]`)
- [X] Windows
- [ ] macOS
- [ ] Linux

**Comment by jdumas** [comment]
Hmm looks like a better fix would be to add a `L` prefix to the string: `L"*.*\0"`
