### ISSUE TITLE
OpenMP Support on Windows

### ISSUE THREAD

**Issue by bradrothenberg** [libigl/libigl#169]
Hello,

I know you mention in the readMe that Eigen + Visual Studio + OpenMP could lead to problems, however, I am able to run Eigen code using Visual Studio + OpenMP outside of the libiGL samples. 

When trying to run the libiGL samples, if OpenMP is turned on, all of the sudden the compiler freaks out & can't recognize the majority of the Eigen types in LibiGL code.

I'm compiling with v140 on MSVC2015 ctp1 -- I don't think I was having this problem before the ctp1.

Has anyone else run into this problem?

Thanks!

Bradley

**Comment by alecjacobson** [comment]
Are you using our cmake build system to generate the visual studio project? I wonder if it's a cmake problem...

**Comment by alecjacobson** [comment]
We're turning away from openmp in favor of std C++11 threads. Unfortunately mac's clang never joined the openmp party.
