### ISSUE TITLE
Is there any requirement to use igl::copyleft::cgal::mesh_boolean?

### ISSUE THREAD

**Issue by aroadktw** [libigl/libigl#1691]
Sometimes mesh_boolean returns zero vertices and indices.

And I found that inverting indices returns the right answer in some cases.

But it does not work every time.

What tasks should be done before using mesh_boolean?

**Comment by alecjacobson** [comment]
Maybe your meshes are inside out? 

mesh_boolean assumes the inputs are PWN http://www.cs.columbia.edu/cg/mesh-arrangements/#definitions which includes being oriented so that normals computed using right hand rule point outward

**Comment by aroadktw** [comment]
Thanks for replying.

And you were right. After I oriented indices, it gives right answer. Thanks!
