### ISSUE TITLE
Libigl incompatible with recent imgui

### ISSUE THREAD

**Issue by Synxis** [libigl/libigl#1692]
Libigl does not compile with newer versions of imgui:

    ../third-parties/libigl/libigl/include/igl/opengl/glfw/imgui/ImGuiHelpers.h:61:91: error: unknown type name 'ImGuiTextEditCallback'; did you mean 'ImGuiInputTextCallback'?
    inline bool InputText(const char* label, std::string &str, ImGuiInputTextFlags flags = 0, ImGuiTextEditCallback callback = NULL, void* user_data = NULL)
                                                                                              ^~~~~~~~~~~~~~~~~~~~~
                                                                                              ImGuiInputTextCallback
    ../third-parties/imgui/imgui/../imgui/imgui.h:199:15: note: 'ImGuiInputTextCallback' declared here
    typedef int (*ImGuiInputTextCallback)(ImGuiInputTextCallbackData* data);    // Callback function for ImGui::InputText()

Indeed, `ImGuiTextEditCallback` was renamed to `ImGuiInputTextCallback`...

#### Applies to:
- [x] Windows
- [x] macOS
- [x] Linux

**Comment by jdumas** [comment]
Are you testing with v1.79, or with the master branch of imgui?

**Comment by Synxis** [comment]
I'm testing with the `docking` branch of imgui. As you can see [in the changelog of imgui](https://github.com/ocornut/imgui/blob/master/docs/CHANGELOG.txt), `ImGuiTextEditCallback` was deprecated in august 2018 and removed somewhere around last week (there is an error in their changelog, see also the log for version 1.63).

**Comment by jdumas** [comment]
Sounds good. Feel free to submit a PR with a fix, otherwise I can look into it this week-end.

**Comment by Synxis** [comment]
Thanks ! I've opened #1694
