### ISSUE TITLE
Confusion: boolean operation with CSG tree use Libigl's method or CGAL's method

### ISSUE THREAD

**Issue by Aniwax** [libigl/libigl#1698]
#### Describe your question
I have a general confusion about the package, when it comes to the boolean operations using a CSG tree, it's written in the documentation to call it the function using: `igl::copyleft::cgal::mesh_boolean`.

Does this mean these boolean operations conducted between each node of the CSG tree is using [CGAL's method](https://doc.cgal.org/latest/Nef_3/group__PkgNef3Ref.html)? Or is it still Libigl's winding number based method described in [this paper](http://www.cs.columbia.edu/cg/mesh-arrangements/mesh-arrangements-for-solid-geometry-siggraph-2016-zhou-et-al.pdf)? 
...

#### Check all that apply (change to `[x]`)
- [x] Windows
- [x] macOS
- [x] Linux

**Comment by jdumas** [comment]
The boolean operation in libigl is different from CGAL's implementation, but it uses other parts of CGAL, which is why it is in the copyleft::cgal package.

**Comment by Aniwax** [comment]
Does this mean when I use CSG tree, it's only using CGAL's method?

**Comment by jdumas** [comment]
No

**Comment by Aniwax** [comment]
@jdumas  Can you elaborate a bit more? How to specify which method to use when constructing CSG tree?

**Comment by jdumas** [comment]
If you want to use CGAL's boolean method, call CGAL directly. If you want to use libigl's boolean method, call libigl (code will use *other* CGAL features).
