### ISSUE TITLE
boundary_loop issue

### ISSUE THREAD

**Issue by cristiprefac** [libigl/libigl#170]
Hi,

It looks like the boundary_loop function only works with Eigen::Matrix of int type. 
I would like to use it with unsigned int, but it throws the following compilation error:

"boundary_loop.cpp:33: error: no matching function for call to 'triangle_triangle_adjacency'
  triangle_triangle_adjacency(Vdummy,F,TT,TTi);"

**Comment by alecjacobson** [comment]
This is due to poor templating in `triangle_triangle_adjacency`. A bug from the point of view of how `boundary_loop` is calling it.

**Comment by alecjacobson** [comment]
Using unsigned int with libigl for matrices is likely to root out a lot of issues like this. We should have compilation tests to find these, rather than relying on catching them one by one.
