### ISSUE TITLE
How to collect border vertices of a mesh(in winding order & convex only)

### ISSUE THREAD

**Issue by linuxaged** [libigl/libigl#1702]
Hi guys, i'm new here.
Blender has feature called: `Select -> Select All by Trait -> Non Manifold`, i want to implement the same thing with libigl.
is `extract_non_manifold_edge_curves` the right tool to pick? any example about how to use it?

![non-manifold](https://user-images.githubusercontent.com/1172901/105577797-b199a680-5db6-11eb-91bd-1602a0a45923.png)

**Comment by alecjacobson** [comment]
There are two ways a triangle mesh can be non-manifold. Vertices and edges.
Sometimes a non-manifold edge is incident on a non-manifold vertex (and
vice versa), but not always. So you could use is_vertex_manifold in
combination with is_edge_manifold to find those.

**Comment by linuxaged** [comment]
why there's no non-manifold vertex/edge on my [mesh](https://bonneeds.oss-cn-hangzhou.aliyuncs.com/stl/test.stl)? both `is_vertex_manifold` and `is_edge_manifold` return true; does `is_edge_manifold` allow boundary edges?
```
    Eigen::MatrixXd V;
    Eigen::MatrixXi F;
    igl::read_triangle_mesh("test.stl", V, F);
    Eigen::MatrixXi B;
    bool result = igl::is_vertex_manifold(F, B);
    result = igl::is_edge_manifold(F);
```

**Comment by jdumas** [comment]
Yes, a non-manifold edge is an edge incident to >2 facets, so boundary edges are manifold. If you want to determine a list of boundary edges, look at igl::boundary_facets() or igl::boundary_loop()

**Comment by linuxaged** [comment]
@jdumas thanks for your reply! `igl::boundary_loop()` returns `0,1,2` and `igl::boundary_facets()` returns the whole mesh's faces; did i miss something?

**Comment by jdumas** [comment]
boundary_loop returns a list of vertices along the boundary loop(s) of the mesh. boundary_facets returns a #E x 2 matrix of all the boundary edge indices.

**Comment by linuxaged** [comment]
> boundary_loop returns a list of vertices along the boundary loop(s) of the mesh. boundary_facets returns a #E x 2 matrix of all the boundary edge indices.

does this depend on vertex normals?

**Comment by jdumas** [comment]
No

**Comment by alecjacobson** [comment]
`igl::boundary_facets` may be returning all faces because your mesh is stored as a .stl file (list of unconnected triangles with shared vertices). When reading from an .stl, use `igl::remove_duplicate_vertices` to merge the triangles into a mesh.
