### ISSUE TITLE
knn implementation in libigl seems slow, or am I reading documentation incorrectly?

### ISSUE THREAD

**Issue by gheylam** [libigl/libigl#1705]
Dear all, I'm new here so I'm unsure about where to ask this but felt it could help the documentation and tutorial. 

I'm playing with the knn function and from observation it seems to be running much slower compared to other implementations such as in scikit. I'm here to show what I've been running and hopefully get verification on whether i'm using it correctly. 

So to describe the problem context, I have 2 sets of points, **query** and **target**. I want to find the nearest neighbours to each point in the **query** set that references points in **target**. 

From reading the header file doc, I believe I should be using this constructor: 

_// Inputs:
  //   P  #P by 3 list of point locations for which which we want the neighbors of
  //   V  #V by 3 list of point locations for which may be neighbors 
  //   k  number of neighbors to find
  //   point_indices  a vector of vectors, where the ith entry is a vector of
  //                  the indices into P that are the ith octree cell's points
  //   CH     #OctreeCells by 8, where the ith row is the indices of
  //          the ith octree cell's children
  //   CN     #OctreeCells by 3, where the ith row is a 3d row vector
  //          representing the position of the ith cell's center
  //   W      #OctreeCells, a vector where the ith entry is the width
  //          of the ith octree cell
  // Outputs:
  //   I  #P by k list of k-nearest-neighbor indices into V_

In my code I have explicitly got: 
igl::octree(rndPointsOnPlane, O_PI, O_CH, O_CN, O_W);
igl::knn(queryPtsSubset, rndPointsOnPlane, 10, O_PI, O_CH, O_CN, O_W, I);

Where O_PI, O_CH, O_CN, O_W are properties of the Octree constructed. 
rndPointsOnPlane is a set of 10000 3D points 
queryPtsSubset are a set of 1000 3D points (queryPtsSubset are points that do not exist in the rndPointsOnPlane set)

When I run this knn query for 1000 query points, the runtime elapsed is approximately 1.5seconds. 
Without having much prior experience to this, is this time expected or is it slow (implying i'm doing something wrong)?  
When I make a query for 10000 points  I see a linear increase in time at around 14seconds. 

I understand that its hard to gauge performance based on time since different machines have different specs, but it seems slow compared to scikit that only takes less than 2 seconds to complete 60 iterations of 1000 query points. 

Perhaps helpful would be specify some specs of my computer:
CPU: i7-6600U CPU @ 2.6Ghz
RAM: 16gb
GPU: No GPU  

My question is then:
1. Is this sluggish behaviour normal?
2. Is the way i'm using the knn call correct?

To be clear, the results I am getting from knn() is exactly what I am after, every queryPtsSubset point has a set of points from rndPointsOnPlane that are neighbours, I am just wondering if there are some problems relating to how I am constructing the octree or whether I should actually be using the alternative knn() definition instead. 
...

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] macOS
- [x] Linux

Appendix: Code I had use to describe the problem statement above:
   //Constructing points on the plane
  Eigen::MatrixXd rndPointsOnPlane(10000, 3);
  int rowId = 0;
  for(int x = 0; x < 100; x++){
      for(int y = 0; y < 100; y++){
          rndPointsOnPlane.row(rowId) = Eigen::RowVector3d(x, y, 0);
          rowId++;
      }
  }

  //Constructing query points 
  Eigen::MatrixXd queryPtsSubSet = rndPointsOnPlane + Eigen::MatrixXd::Ones(10000, 3);
  Eigen::MatrixXd queryPts = queryPtsSubSet.block(0, 0, 1000, 3);

  //Build octree
  std::vector<std::vector<int>> O_PI;
  Eigen::MatrixXi O_CH;
  Eigen::MatrixXd O_CN;
  Eigen::VectorXd O_W;
  igl::octree(rndPointsOnPlane, O_PI, O_CH, O_CN, O_W);

  Eigen::MatrixXi I;
  int numNN = 10;
  auto start = std::chrono::high_resolution_clock::now();
  igl::knn(queryPts, rndPointsOnPlane, numNN, O_PI, O_CH, O_CN, O_W, I); // 1.51513s for 1000 queries
  auto end = std::chrono::high_resolution_clock::now();
  std::chrono::duration<double> elapsed = end - start;
  std::cout << elapsed.count() << std::endl;

**Comment by gheylam** [comment]
After some further investigation, it seems the main different between the scikit implementation of kNN is the use of KDtree instead of an Octree. Perhaps this is the difference in processing cost? Would appreciate some direction or insight in this. And perhaps the documentation could justify why libigl uses octrees instead of kdtrees?

**Comment by alecjacobson** [comment]
I changed your code slightly to get it to compile:

```

#include <Eigen/Core>
#include <Eigen/Sparse>
#include <igl/octree.h>
#include <igl/knn.h>
#include <vector>
#include <igl/get_seconds.h>
#include <iostream>

int main(int argc, char * argv[])
{//Constructing points on the plane
Eigen::MatrixXd rndPointsOnPlane(10000, 3);
int rowId = 0;
for(int x = 0; x < 100; x++){
for(int y = 0; y < 100; y++){
rndPointsOnPlane.row(rowId) = Eigen::RowVector3d(x, y, 0);
rowId++;
}
}

//Constructing query points
Eigen::MatrixXd queryPtsSubSet = rndPointsOnPlane + Eigen::MatrixXd::Ones(10000, 3);
Eigen::MatrixXd queryPts = queryPtsSubSet.block(0, 0, 1000, 3);

//Build octree
std::vector<std::vector<int>> O_PI;
Eigen::MatrixXi O_CH;
Eigen::MatrixXd O_CN;
Eigen::VectorXd O_W;
igl::octree(rndPointsOnPlane, O_PI, O_CH, O_CN, O_W);

Eigen::MatrixXi I;
int numNN = 10;
double tic = igl::get_seconds();
igl::knn(queryPts, rndPointsOnPlane, numNN, O_PI, O_CH, O_CN, O_W, I); // 1.51513s for 1000 queries
printf("%0.4f secs\n",igl::get_seconds()-tic);
}
```

For me on a macbook pro **_compiled in release mode_** this prints:

```
0.0100 secs
```

**Comment by gheylam** [comment]
> ```
> 0.0100 secs
> ```

Ah! I didn't think about a difference in release mode vs debug mode. It makes alot of sense. After compiling in release mode, I was able to get similar results as yours. This have solved my problem, thank you so much! I'll close this thread with this now.
