### ISSUE TITLE
EmbreeIntersector member function missing `IGL_INLINE`

### ISSUE THREAD

**Issue by xarthurx** [libigl/libigl#1708]
#### Describe your question

I'm using `embree::unproject_onto_mesh` where I declare the `embree::EmbreeIntersector` a class member.

When compiling, I got this error:

![image](https://user-images.githubusercontent.com/1921878/105908397-730a2300-6026-11eb-8177-b312859c89bf.png)

After checking the source code, it seems the two functions that cause the above issue does not have the `IGL_INLINE` keyword in the `cpp` file:
https://github.com/libigl/libigl/blob/4d026eeef1d98eac3e91ab8a4447effe85dec188/include/igl/embree/EmbreeIntersector.cpp#L130
https://github.com/libigl/libigl/blob/4d026eeef1d98eac3e91ab8a4447effe85dec188/include/igl/embree/EmbreeIntersector.cpp#L122

All the other functions have the keyword and do not cause the compilation issue, such as:
https://github.com/libigl/libigl/blob/4d026eeef1d98eac3e91ab8a4447effe85dec188/include/igl/embree/EmbreeIntersector.cpp#L52

Based on what I can understand from:
https://stackoverflow.com/questions/9274753/friend-operator-overloading-causes-already-defined-in-linker-errors

Does it seem to be a `bug`?

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by xarthurx** [comment]
Manually change it and compilation passed.
I can submit a `PR` if needed.

**Comment by jdumas** [comment]
Sure, feel free to submit a PR.

**Comment by xarthurx** [comment]
submitted.
