### ISSUE TITLE
How to show multi viewport with Libigl?

### ISSUE THREAD

**Issue by wguo68** [libigl/libigl#171]
Dr. Jacobson:
     I like your libigl. However I have a question: I want the viewer with left and right viewports and show different meshes in different viewports at the same time. So how to  show multi viewports with Libigl?  Sould I define a new class similar to the Viewer and plugins?

**Comment by alecjacobson** [comment]
It might be a little tricky to implement this with a mere plugin. The viewer is really just a simple toy for use to display meshes etc. and not necessarily a good skeleton to build a complicated app upon.
