### ISSUE TITLE
Implementing Extrusion in Libigl

### ISSUE THREAD

**Issue by Aniwax** [libigl/libigl#1710]
#### Describe your question
Dear Team, 

I am currently using Libigl for a 3D mesh processing.  I want to have the extrude functionality to extrude a small box over the surface of another big box. Is there any successful example in implementing extrusion that you can suggest? (3D object extruding another 3D object).

Another work around I can think of is to use the extrude.h file from CGAL to do my calculations. However, in extrude.h from CGAL, there are  also lots of dependencies not included in the libigl-wrapped cgal folder. For example, some header files are included from `boost`.  

If I want to use the extrude.h from CGAL, how should I handle the dependencies coming from `boost`? Is there a particular libigl core that I need to link them?
...

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [x] macOS
- [ ] Linux

**Comment by alecjacobson** [comment]
There's no existing function in libigl for extrusion. In my matlab library, I have an implementation that would be straightforward to port to libigl: https://github.com/alecjacobson/gptoolbox/blob/master/mesh/extrude.m . If you end up doing it, I'd be happy to merge a PR.

Meanwhile, could you post a separate issue detailing the trouble you're running into linking to CGAL dependencies. This is probably an issue with our cmake, but we'd need some minimal example and errors to go off of.
