### ISSUE TITLE
Is the ARAP deformation algorithm non-deterministic?

### ISSUE THREAD

**Issue by gert86** [libigl/libigl#1711]
Hello!
I encountered that using the ARAP algorithm multiple times with the same input data yields (slightly) different results. So I am wondering if there is any randomness in the ARAP deformation algorithm and if so, is it in the arap_precomputation() part or in the arap_solve() part? I tried to debug this on my own, but it is hard to find out without the ability to copy or compare ARAPData objects.
Thanks for your answer!
BR, Gert

**Comment by Coelancanth** [comment]
Deformation is an optimization problem. Which means there is no analytical solution.

**Comment by gert86** [comment]
Just because it is an iterative optimization algorithm does not automatically mean it is non-deterministic. There needs to be some step like a "randomized initialization" that causes different results despite using the exact same input data. My question is where exactly is this randomness introduced?

**Comment by alecjacobson** [comment]
There's no intentional random initialization in the libigl ARAP implementation. On the same system for the same input you should get the same output. If you have a minimal example that shows otherwise perhaps we can locate this to an initialization bug.
