### ISSUE TITLE
Can't open source"igl stb_image.h"

### ISSUE THREAD

**Issue by zhiyingf** [libigl/libigl#1712]
#### Describe your question
#include <igl/png/readPNG.h>
but:
![image](https://user-images.githubusercontent.com/38620101/106405925-ac9dbc80-6472-11eb-8489-d72722fc2197.png)

#### Check all that apply (change to `[x]`)
- [x ] Windows
- [ ] macOS
- [ ] Linux

**Comment by jdumas** [comment]
You need to link against `igl::png` in your cmake file.

**Comment by zhiyingf** [comment]
it is add:
option(LIBIGL_WITH_PNG               "Use PNG"                      ON),in CMakeLists.txt?
but useless.

**Comment by jdumas** [comment]
No you need to link against the appropriate CMake target as well. Cf. this line in the [libigl-example-project](https://github.com/libigl/libigl-example-project):
```cmake
target_link_libraries(${PROJECT_NAME} igl::core igl::opengl_glfw)
```

Just add `igl::png` to the list.

**Comment by zhiyingf** [comment]
I have done this before this problem occurs again：
target_link_libraries(main igl::core igl::opengl_glfw igl::opengl igl::opengl_glfw_imgui)
... ...

**Comment by zhiyingf** [comment]
Thanks, I understant it. However, there is a problem with cmake:
![image](https://user-images.githubusercontent.com/38620101/106413650-964d2c00-6485-11eb-8420-aac4b00ccb39.png)
Is this because of the libigl version?(I am trying to recompile a new libigl, but some files cannot be downloaded and the compilation fails)

**Comment by jdumas** [comment]
Delete your `CMakeCache.txt` in your build folder and try again (enabling the option `LIBIGL_WITH_PNG`).
