### ISSUE TITLE
ImGui Menu not working after Visual Studio Update 

### ISSUE THREAD

**Issue by bthomasz** [libigl/libigl#1717]
Not having updated my visual studio 2019 installation for the past 4  months or so, I yesterday installed the latest version (16.8.5) and realized that the ImGui main menu (created through callback_draw_viewer_window() ) is not working anymore. I did a clean checkout and recompile of libigl and tried it on example 106. I only see the topmost menu 'bar' with the Viewer label and a weird triangle above it. It's not expandable and clickable anymore:
![image](https://user-images.githubusercontent.com/7659118/107612330-508f2100-6c46-11eb-8c3c-1a2becb82be3.png)

This problem only happens in release mode, debug works fine.
Any idea as to what could be causing this problem?

Thanks a lot!
Bernhard

#### Check all that apply (change to `[x]`)
- [x ] Windows
- [ ] macOS
- [ ] Linux

**Comment by jdumas** [comment]
Hi @bthomasz. It's actually a known issue (see #1669). I haven't had time to investigate recently, but I'll try to get on it. Thanks for the reminder!

**Comment by bthomasz** [comment]
Alright, thanks!

**Comment by jdumas** [comment]
Fixed by #1723 (updating ImGui).
