### ISSUE TITLE
Hide "igl::opengl::glfw::Viewer usage:" print on command line

### ISSUE THREAD

**Issue by mesabg** [libigl/libigl#1718]
#### Describe your question
Hi guys, I'm trying to hide the print of the libigl Viewer which shows the usage of the interface, the reason is that I'm printing a lot of importtan info on the command line interface and I want it to be as clean as possible. Is there any way to do this ? 

...

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by BruegelN** [comment]
Hi @mesabg,

sure a defining `IGL_VIEWER_VIEWER_QUIET` should do the trick, see: https://github.com/libigl/libigl/blob/aafb6870c757d2f95211cd351dcbbcc89cf5c22f/include/igl/opengl/glfw/Viewer.cpp#L353-L371

**Comment by mesabg** [comment]
Thanks @BruegelN ! It worked !
