### ISSUE TITLE
3D mesh morphing

### ISSUE THREAD

**Issue by 564654509** [libigl/libigl#1719]
Hi, I'm a fresh man in geometry processing and now learn the tutorials step by step. I don't know how to implement the morphing effect between two different meshes with libigl.  Can you give me some tips ? Thanks very much.

**Comment by alecjacobson** [comment]
Welcome to Geometry Processing. libigl does not have an implementation of a mesh morphing technique. Depending on the method you want to implement there would certainly be useful subroutines in libigl.

**Comment by jdumas** [comment]
If you want an implementation of optimal transport for mesh morphing, I can also suggest to take at [geogram](http://alice.loria.fr/software/geogram/doc/html/index.html):
![image](https://user-images.githubusercontent.com/578702/107882846-7152b300-6ea0-11eb-8ef6-884f5ae55596.png)

**Comment by r03ert0** [comment]
I was just trying https://pythonot.github.io/ the other day (Python Optimal Transport), and it was super easy to hack their example on colour adaptation to morph meshes: just use 3d coordinates instead of red, green and blue! https://pythonot.github.io/auto_examples/domain-adaptation/plot_otda_color_images.html#sphx-glr-auto-examples-domain-adaptation-plot-otda-color-images-py
With some work on the cost matrix, the results could be 👌

**Comment by 564654509** [comment]
> If you want an implementation of optimal transport for mesh morphing, I can also suggest to take at [geogram](http://alice.loria.fr/software/geogram/doc/html/index.html):
> ![image](https://user-images.githubusercontent.com/578702/107882846-7152b300-6ea0-11eb-8ef6-884f5ae55596.png)

![image](https://user-images.githubusercontent.com/7654837/108508080-3b755a80-72f6-11eb-8a3a-ee0c0fa5bbe0.png)
![image](https://user-images.githubusercontent.com/7654837/108508298-9018d580-72f6-11eb-8bb9-72307b651d5e.png)
![image](https://user-images.githubusercontent.com/7654837/108508355-a32ba580-72f6-11eb-9073-f1077bfd4952.png)

Thanks a lot. I have downloaded geogram and tested it. But the morphing effect between a horse and a cat seems not good, you can see the result in top picture. 

In last few days, I have read some papers about mesh morphing. The typical method  firstly parameterizes the different surfaces to a canonical domain such as a plane, sphere or some suitable (genus compatible) domain, then remeshes them. Usually you need to manually provide some feature points. For example, If you want the morphing effect between a horse and a cat, you should mark some points of legs of them.

**Comment by sulemanqamar** [comment]
> > If you want an implementation of optimal transport for mesh morphing, I can also suggest to take at [geogram](http://alice.loria.fr/software/geogram/doc/html/index.html):
> > ![image](https://user-images.githubusercontent.com/578702/107882846-7152b300-6ea0-11eb-8ef6-884f5ae55596.png)
> 
> ![image](https://user-images.githubusercontent.com/7654837/108508080-3b755a80-72f6-11eb-8a3a-ee0c0fa5bbe0.png) ![image](https://user-images.githubusercontent.com/7654837/108508298-9018d580-72f6-11eb-8bb9-72307b651d5e.png) ![image](https://user-images.githubusercontent.com/7654837/108508355-a32ba580-72f6-11eb-9073-f1077bfd4952.png)
> 
> Thanks a lot. I have downloaded geogram and tested it. But the morphing effect between a horse and a cat seems not good, you can see the result in top picture.
> 
> In last few days, I have read some papers about mesh morphing. The typical method firstly parameterizes the different surfaces to a canonical domain such as a plane, sphere or some suitable (genus compatible) domain, then remeshes them. Usually you need to manually provide some feature points. For example, If you want the morphing effect between a horse and a cat, you should mark some points of legs of them.
> 
> But the details of above method is much and complex, I'm trying my best to look for some libraries to save the coding time.

Hey I am also working on a similar problem. Did you manage to find a way to solve the problem, kindly share so others can also benefit from it.
