### ISSUE TITLE
Why the libigl not use the halfedge data structure for a mesh?

### ISSUE THREAD

**Issue by wguo68** [libigl/libigl#172]
Libigl using two array or matrixs to represent a mesh. Why you didn't choose the half-egde structure such as surface mesh? I think because your data structure is very simple and easy to work with Matlab.The efficiency is not good as half-edge data structure,I think.

**Comment by alecjacobson** [comment]
Vertex-face lists easily represent triangle soups, non-manifold meshes and surface meshes. They're more general than a half-edge data structure. They're also sometimes _faster_: by storing all vertices in a  contiguous chunk of memory data access is fast. A naive half-edge data structure might rely on pointers to the heap and memory look up becomes a bottleneck.
Check out the [tutorial](libigl.github.io/libigl/tutorial/tutorial.html) for more information.

**Comment by wguo68** [comment]
I see,thank you very much.
