### ISSUE TITLE
Is Linux (Release, OFF) action testing debug mode or release mode?

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#1720]
![image](https://user-images.githubusercontent.com/2241689/107966393-c6aec300-6f79-11eb-83f6-0f5e7aae1041.png)

The log output appears to use `-DCMAKE_BUILD_TYPE=Release`, but I'm not sure I'm reading this correctly and I don't know where to go to check this. Is it under "Actions"?

**Comment by alecjacobson** [comment]
ah, maybe the OFF is in reference to LIBIGL_USE_STATIC_LIBRARY?

**Comment by jdumas** [comment]
Yes, OFF refers to LIBIGL_USE_STATIC_LIBRARY. The github action for PRs only test Release configuration, as Debug is too heavy to fit in the ccache size limit (Debug is tested in the Nightly build).

**Comment by jdumas** [comment]
I can probably update the github action to make it more explicit though...

**Comment by alecjacobson** [comment]
Thanks. I was just starting to edit the  .github/workflows/continuous.yml
to add "static=" but I'm a bit scared to push this to master and I'm not
sure how these behave in a branch. Do you mind doing it, if you're
confident?

**Comment by jdumas** [comment]
Sure, I'll take a look. I'll probably open a separate PR, I'm wary of pushing anything to master directly.

**Comment by alecjacobson** [comment]
thanks. How do changes to the workflows work via PRs? Is the workflow always just running post-merge of everything?

**Comment by jdumas** [comment]
It depends on what is set for the trigger:
https://stackoverflow.com/questions/57683943/github-actions-how-to-build-a-pull-request-as-if-it-were-merged

So currently yes it will run on the merge commit between the PR and the master branch.

**Comment by jdumas** [comment]
PR is in. The only caveat is we have to update branch protection rules to update the required status check before merging a PR (since it is based on the job name). I'll do that once #1721's jobs have compiled.
