### ISSUE TITLE
NVCC Compiler for CUDA not working as expected

### ISSUE THREAD

**Issue by mobereng** [libigl/libigl#1722]
#### Describe your question
Hi, I'm currently using some CUDA functionalities along my LibIGL project, I spend a few days stuck on compilations issues thinking that it was related to my compiler, but then I try the same compilation but without libigl included on the cmake file, and it worked. I'm guessing some c++ important options used by nvcc are removed once LibIGL library is added, but I'm not sure what's happening, or how to solve it.

Here you can see the error reported, which as I said, this does not happen when I compile without LibIGL

![image](https://user-images.githubusercontent.com/69315094/107999914-19f73480-6fbf-11eb-8a42-190d5ff53110.png)

CmakeList is the following

```cmake
cmake_minimum_required(VERSION 3.19.2)
project(CudaTest LANGUAGES CXX)

set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${CMAKE_CURRENT_SOURCE_DIR}/cmake)

# LIBIGL PACKAGE
option(LIBIGL_WITH_OPENGL              "Use OpenGL"         ON)
option(LIBIGL_WITH_OPENGL_GLFW         "Use GLFW"           ON)
option(LIBIGL_WITH_OPENGL_GLFW_IMGUI   "Use ImGui"          ON)
find_package(LIBIGL REQUIRED QUIET)

# BOOST PACKAGE
find_package(Boost 1.75.0 REQUIRED COMPONENTS program_options filesystem serialization unit_test_framework)

# CUDA PACKAGE
find_package(CUDA)
add_compile_definitions(CUDA_CAPABLE=${CUDA_FOUND})
if (CUDA_FOUND)
  enable_language(CUDA)
endif()

# OPENMP PACKAGE
find_package(OpenMP)
if (OPENMP_FOUND)
  set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
  set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
  set (CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${OpenMP_EXE_LINKER_FLAGS}")
endif()

# Add your project files
file(GLOB_RECURSE SRCFILES src/*.cpp src/*.hpp)
if (CUDA_FOUND)
  file(GLOB_RECURSE CU_SRCFILES src/*.cu)
  add_executable(${PROJECT_NAME} ${CU_SRCFILES} ${SRCFILES})
else()
  add_executable(${PROJECT_NAME} ${SRCFILES})
endif()

# Include
target_include_directories(${PROJECT_NAME} PRIVATE ${Boost_INCLUDE_DIRS} tools/include/)
if (CUDA_FOUND)
  target_include_directories(${PROJECT_NAME} PRIVATE ${CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES})
endif()

# Linker
target_link_libraries(${PROJECT_NAME} igl::core igl::opengl igl::opengl_glfw igl::opengl_glfw_imgui ${Boost_LIBRARIES} ${Boost_PROGRAM_OPTIONS_LIBRARY} ${Boost_SERIALIZATION_LIBRARY} Boost::program_options Boost::filesystem Boost::serialization Boost::unit_test_framework)
if (CUDA_FOUND)
  target_link_libraries(${PROJECT_NAME} ${CUDA_LIBRARIES} ${CUDA_cusparse_LIBRARY} ${CUDA_cusolver_LIBRARY})
endif()
```
...

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by jdumas** [comment]
FindCUDA is deprecated since CMake 3.10. I would suggest that you try to update your CMake script to use the approach described in the [documentation](https://cmake.org/cmake/help/latest/module/FindCUDA.html), and use imported targets provided by the [FindCUDAToolkit](https://cmake.org/cmake/help/latest/module/FindCUDAToolkit.html#module:FindCUDAToolkit) module to compile your project. (Same with OpenMP, you should use imported targets such as `OpenMP::OpenMP_CXX`).

**Comment by mobereng** [comment]
Perfect @jdumas thanks, let me validate and come back here later on

**Comment by mobereng** [comment]
I upgraded to FindCUDAToolkit and also installed Thrust saparately, and the issue seems to be the same one

![image](https://user-images.githubusercontent.com/69315094/108004475-58472080-6fcc-11eb-8bcc-845ef22d839e.png)

And as the previous case, I also compile this without LibIGL dependencies with no errors

CMakeList file:

```cmake
cmake_minimum_required(VERSION 3.19.2)
project(CudaTest LANGUAGES CXX)

set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${CMAKE_CURRENT_SOURCE_DIR}/cmake)

# LIBIGL PACKAGE
option(LIBIGL_WITH_OPENGL              "Use OpenGL"         ON)
option(LIBIGL_WITH_OPENGL_GLFW         "Use GLFW"           ON)
option(LIBIGL_WITH_OPENGL_GLFW_IMGUI   "Use ImGui"          ON)
find_package(LIBIGL REQUIRED QUIET)

# BOOST PACKAGE
find_package(Boost 1.75.0 REQUIRED COMPONENTS program_options filesystem serialization unit_test_framework)

# CUDA PACKAGE
find_package(CUDAToolkit)
add_compile_definitions(CUDA_CAPABLE=${CUDAToolkit_FOUND})
if (CUDAToolkit_FOUND)
  enable_language(CUDA)
  find_package(Thrust REQUIRED CONFIG)
  thrust_create_target(Thrust)
endif()

# OPENMP PACKAGE
find_package(OpenMP)

# Add your project files
file(GLOB_RECURSE SRCFILES src/*.cpp src/*.hpp)
if (CUDAToolkit_FOUND)
  file(GLOB_RECURSE CU_SRCFILES src/*.cu)
  add_executable(${PROJECT_NAME} ${CU_SRCFILES} ${SRCFILES})
else()
  add_executable(${PROJECT_NAME} ${SRCFILES})
endif()

# Include
target_include_directories(${PROJECT_NAME} PRIVATE ${Boost_INCLUDE_DIRS} tools/include/)
if (CUDAToolkit_FOUND)
  target_include_directories(${PROJECT_NAME} PRIVATE ${CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES})
endif()

# Linker
target_link_libraries(${PROJECT_NAME} igl::core igl::opengl igl::opengl_glfw igl::opengl_glfw_imgui ${Boost_LIBRARIES} ${Boost_PROGRAM_OPTIONS_LIBRARY} ${Boost_SERIALIZATION_LIBRARY} Boost::program_options Boost::filesystem Boost::serialization Boost::unit_test_framework)

# Linker CUDA
if (CUDAToolkit_FOUND)
  target_link_libraries(${PROJECT_NAME} CUDA::cudart CUDA::cusparse CUDA::cusolver Thrust)
endif()

# Linker OpenMP
if (OpenMP_FOUND)
  target_link_libraries(${PROJECT_NAME} OpenMP::OpenMP_CXX)
endif()
```

**Comment by jdumas** [comment]
You shouldn't need those lines:
```cmake
# Include
target_include_directories(${PROJECT_NAME} PRIVATE ${Boost_INCLUDE_DIRS} tools/include/)
if (CUDAToolkit_FOUND)
  target_include_directories(${PROJECT_NAME} PRIVATE ${CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES})
endif()
```

Could you try without it? (To use boost please also use the imported targets provided by CMake).

**Comment by mobereng** [comment]
Yes for sure, but this way then ?

```cmake
target_include_directories(${PROJECT_NAME} PRIVATE ${Boost_INCLUDE_DIRS} ${CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES} tools/include/)
```

Or completely removing the includes for boost and cuda toolkit ?

```cmake
target_include_directories(${PROJECT_NAME} PRIVATE tools/include/)
```

I need to leave `tools/include/` cause I have some header only files there

And about boost cmake targets, I already linked them here

```cmake
target_link_libraries(${PROJECT_NAME} igl::core igl::opengl igl::opengl_glfw igl::opengl_glfw_imgui ${Boost_LIBRARIES} ${Boost_PROGRAM_OPTIONS_LIBRARY} ${Boost_SERIALIZATION_LIBRARY} Boost::program_options Boost::filesystem Boost::serialization Boost::unit_test_framework)
```

`Boost::program_options` `Boost::filesystem` and so on

**Comment by jdumas** [comment]
Yes, just keep `target_include_directories(${PROJECT_NAME} PRIVATE tools/include/)` with headers from your project, and remove the other target_include_directories (the imported targets will pull those include).

For the linked targets `${Boost_LIBRARIES} ${Boost_PROGRAM_OPTIONS_LIBRARY} ${Boost_SERIALIZATION_LIBRARY}` are somewhat redundant with `Boost::program_options Boost::filesystem Boost::serialization Boost::unit_test_framework`, but that shouldn't hurt compilation.

**Comment by mobereng** [comment]
Perfect, I already comple it that way, look at the output

![image](https://user-images.githubusercontent.com/69315094/108005422-12d82280-6fcf-11eb-9f32-e235e47b7ce3.png)

And yes, I know, Is a little bit redundant the Boost part, but for sure it is not causing any problems

**Comment by jdumas** [comment]
Ok, if removing the `CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES` didn't help, I guess I would need a minimal example project to be able to investigate.

[This thread](https://forums.developer.nvidia.com/t/compile-error-nvcc-fatal-a-single-input-file-is-required/44762) suggests that the `/FS` flag might be problematic, so see if you can find who is setting this flag for your project.

**Comment by mobereng** [comment]
For sure @jdumas let me prepare it in a repo and share it with you

And that's right, it has to be an extra flag that some part of libigl is using and is not passing with nvcc

**Comment by jdumas** [comment]
I did a quick check on the libigl repo and we're not passing the `/FS` flag to MSVC.

**Comment by mobereng** [comment]
Look at this success compilation, without adding LibIGL to the cmake and to the project

![image](https://user-images.githubusercontent.com/69315094/108007842-4b7afa80-6fd5-11eb-80b6-fdf1d13b5028.png)

So, I'm not sure what one is the flag causing the issue, but everything leads to something added that ended up in the compilation error

I'm about to push to the repos and share the 2 of them, they are just sample test cases in order to compile

**Comment by mobereng** [comment]
Ready @jdumas 

This is the one I want to compile [Cuda Test](https://github.com/mobereng/cuda_test) the one with LibIGL
And this is the one that compiles with no errors but without LibIGL [Cuda Test NoLibIGL](https://github.com/mobereng/cuda_test_nolibigl)

Also each repo has the instructions to compile, my current cuda environment is:

nvcc: 11.2

**Comment by jdumas** [comment]
Sorry @mobereng but could you make a very _minimal_ version of this without boost/without OpenMP? I.e. just depends on libigl + cuda? I really don't want to compile boost myself.

**Comment by mobereng** [comment]
Yes for sure, let me modifye those ones

**Comment by mobereng** [comment]
Ready, both of them updated, expected output when runs is:

```shell
Hello World from CPU
Hello World from GPU
```

[Cuda Test](https://github.com/mobereng/cuda_test)
[Cuda Test No LibIGL](https://github.com/mobereng/cuda_test_nolibigl)

**Comment by jdumas** [comment]
Thanks. I'm able to reproduce the issue. I will try to find some time to investigate how to solve this (I never had to deal with Cuda and CMake before).

**Comment by mobereng** [comment]
Amazing ! thanks for the help @jdumas

**Comment by mobereng** [comment]
Hey @jdumas hope you are fine ! could you check the issue ?

**Comment by jdumas** [comment]
@mobereng Sorry about the delay, and thanks for the reminder. After some investigation it looks like the culprit is the `/bigobj` flag added by libigl on MSVC. I have created a PR to fix the compilation issue with Cuda/NVCC, please let me know if it works for you.

**Comment by mobereng** [comment]
Hey @jdumas thanks for the help, I already did the test and also saw that `/bigobj` flag was removed, also for some reason even without the flag, the same sample [https://github.com/mobereng/cuda_test](Cuda Test) still failing on my environment, also shows the same message

`A single input file is required for a non-link phase when an outputfile is specified`

![image](https://user-images.githubusercontent.com/69315094/111059388-8acd2780-846b-11eb-840d-c7fa349c3135.png)

I downloaded the whole libigl repository again and saw your change on `main` branch

**Comment by mobereng** [comment]
Reading a bit your change on `libigl.cmake` I tried to comment the whole line

`target_compile_options(igl_common INTERFACE /MP $<$<COMPILE_LANGUAGE:CXX>:/bigobj>)`

and it seems to be working now, so I guess the problem are both `/MP` and `/bigobj` flags

**Comment by jdumas** [comment]
Ah, it may be I manually removed /MP for my tests, and forgot to try it again with /MP enabled. I'll try again and let you know.

**Comment by jdumas** [comment]
Ok so as it turns out, I had modified your example project to enable the following option:
```
set_property(TARGET ${PROJECT_NAME} PROPERTY CUDA_SEPARABLE_COMPILATION ON)
```

And with this option enabled, the `/MP` flag was not preventing compilation to go through. I'll add the same `COMPILE_LANGUAGE:CXX` check though, doesn't hurt.

**Comment by mobereng** [comment]
Thanks for the help and suggestions @jdumas ! everything is working as expected
