### ISSUE TITLE
Free up memory during github actions CI?

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#1725]
[This kind of failure](https://github.com/libigl/libigl/runs/1914177128) seems to happen fairly frequently:

   ..\tutorial\609_Boolean\main.cpp(97): fatal error C1060: compiler is out of heap space

Does this mean the compiling this file took too much memory? Or could it be related to disk quota (because of virtual memory of something). We only test _building_ the tutorial. Would adding a cmake widget to immediately delete these executables free up needed space?

This might also be related to another issue: overzealous header includes. Some quick tests show that we have built up _a lot_ of unnecessary includes over time. Maybe that also fixes/assuages this.

**Comment by jdumas** [comment]
It's related to memory usage. It means we need to compile with only 1 threads instead of 2 ... But in average compilation will then take 2x the time.

**Comment by jdumas** [comment]
This is the line you want to change for this:
https://github.com/libigl/libigl/blob/22620eb925ff896d01f564235208663672204053/.github/workflows/continuous.yml#L145

**Comment by alecjacobson** [comment]
oh. Do I understand correctly that most of the time the two threads share
memory successfully but occasionally they both want too much memory at the
same time and it crashes?

If so, do you think the includes make a difference here?

>

**Comment by jdumas** [comment]
I think the memory usage is more related to how many templated functions are explicitly instantiated at the same time. Including unnecessary headers will slow down parsing, but ultimately it shouldn't hog the memory too much. I don't know if there is a tool such as [ClangBuildAnalyzer](https://github.com/aras-p/ClangBuildAnalyzer) but for profiling memory usage. [Templite](https://github.com/mikael-s-persson/templight) looks promising, but I haven't tried it.

**Comment by AndreyMlashkin** [comment]
Have you solved this problem? If yes, how?
It would be interesting, how much RAM do I need to compile the lib.

**Comment by jdumas** [comment]
For now I think we're just limiting the number of threads used to compile libigl. I don't think we've had a lot of failure due to memory usage as of late.

**Comment by alecjacobson** [comment]
Oy, the windows build has been such a pest. Here're the things I did that seem to have mostly solved the heap space issue:

 - split up min_quad_with_fixed template instantiations into multiple cpp files (these caused heap-space crash on static builds
 - split up big tutorials into multiple cpp files (these cause sporadic heap-space crashes on header only)
 - split up the header only build into tutorial and test
 - further split up the windows header only tutorial build into each chapter
