### ISSUE TITLE
Wrong bbw values for 404 example

### ISSUE THREAD

**Issue by KasiaSprawka** [libigl/libigl#1726]
Hi,

I started using libigl for mesh deformation applications and I encountered some problem. I am trying to calculate the bbw for the arm example in tutorial 404, however all my weights are all equal to 0. It looks like my boundary conditions bc and b are empty as well. Could you help me to figure out where my mistake is? 
Here is my code:

using namespace Eigen;
using namespace std;

igl::readOBJ(TUTORIAL_SHARED_PATH "/arm.obj",V,F);

// Tetrahedralize the interior
igl::copyleft::tetgen::tetrahedralize(V,F,"pq1.414Y", VV,TT,FF);

igl::readTGF(TUTORIAL_SHARED_PATH "/arm.tgf",C,BE);

// retrieve parents for forward kinematics
igl::directed_edge_parents(BE,P);

// List of boundary indices (aka fixed value indices into VV)
 VectorXi b;
// List of boundary conditions of each weight function
MatrixXd bc;
igl::boundary_conditions(VV,TT,C,VectorXi(),BE,MatrixXi(),b,bc);

  // compute BBW weights matrix
  igl::BBWData bbw_data;
  bbw_data.active_set_params.max_iter = 8;
  bbw_data.verbosity = 2;
  if(!igl::bbw(VV,TT,b,bc,bbw_data,W))
  {
    return EXIT_FAILURE;
  }

Thank you in advance

**Comment by bmahlbrand** [comment]
I'm also curious in general about the failure cases for igl::boundary_conditions (i.e. other geometry not available from the tutorial samples). Thumbing through https://homes.cs.washington.edu/~jovan/papers/jacobson-2011-bbw.pdf didn't yield any real answers, does anyone have a better suggestion on reading material?

**Comment by alecjacobson** [comment]
https://github.com/libigl/libigl/blob/7342dbe1f8bcc22cd09bbad249713e19aad28159/include/igl/boundary_conditions.h#L16-L19

The trouble with the code above is that `igl::copyleft::tetgen::tetrahedralize` isn't made aware of where the bones `C,BE` will be, so no internal vertices are placed along the bones. Then `igl::boundary_conditions` isn't able to identify them to build the constraints for `igl::bbw`.

Here's an example modification of the code which works:

```
#include <igl/copyleft/tetgen/mesh_with_skeleton.h>
#include <igl/directed_edge_parents.h>
#include <igl/bbw.h>
#include <igl/boundary_conditions.h>
#include <igl/readOBJ.h>
#include <igl/readTGF.h>
#include <igl/opengl/glfw/Viewer.h>

int main(int argc, char * argv[])
{
  using namespace Eigen;
  using namespace std;
  Eigen::MatrixXd V,VV,W,C;
  Eigen::MatrixXi F,TT,FF,BE;
  Eigen::VectorXi P;
  
  igl::readOBJ("arm.obj",V,F);
  igl::readTGF("arm.tgf",C,BE);
 
  // Tetrahedralize the interior
  igl::copyleft::tetgen::mesh_with_skeleton(V,F,C,{},BE,{},10,"pq1.414Y", VV,TT,FF);
  // tetgen returns faces in CW rather than CCW order
  FF = FF.rowwise().reverse().eval();
  
  // List of boundary indices (aka fixed value indices into VV)
  VectorXi b;
  // List of boundary conditions of each weight function
  MatrixXd bc;
  igl::boundary_conditions(VV,TT,C,VectorXi(),BE,MatrixXi(),b,bc);
  
  // compute BBW weights matrix
  igl::BBWData bbw_data;
  bbw_data.active_set_params.max_iter = 8;
  bbw_data.verbosity = 2;
  if(!igl::bbw(VV,TT,b,bc,bbw_data,W))
  {
    return EXIT_FAILURE;
  }
  igl::opengl::glfw::Viewer vr;
  vr.data().set_mesh(VV,FF);
  vr.data().set_data(W.col(1));
  vr.launch();
}
```

<img width="1392" alt="Screen Shot 2021-05-29 at 12 39 32 PM" src="https://user-images.githubusercontent.com/2241689/120077950-f42c0200-c07a-11eb-89e4-6f7d46259760.png">
