### ISSUE TITLE
Can I get grid filled with tetrahedra to do marching_tet in Python?

### ISSUE THREAD

**Issue by hibit-at** [libigl/libigl#1727]
#### Describe your question

Excuse me.
(I searched "tetrahedra grid" but I couldn't the answer so I posted)

My goal is to get a mesh from implicit function.
(The final goal is morphing between 2 models using SDF)

At first, I tried to do marching cube but it is no implemented in python bindings.
So I tried to do marching tet.
But it seems to need tetrahedral points as inputs.
If I want to reconstruct a shape from a implicit function, it should be wide range of grid filled with tetrahedron.

I test that 1 cube (6 tetrahedron) worked successfully on `marching tet` as below.
![image](https://user-images.githubusercontent.com/43929933/108671023-3a754080-7523-11eb-92d5-7ee478d43427.png)

How could I get the grid like (-10,-10,-10),(-10,-10,-9),...,(10,10,9),(10,10,10) in tetrahedral format?

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by alecjacobson** [comment]
`igl/tetrahedralized_grid.h`
