### ISSUE TITLE
As-rigid-as-possible vs deformation transfer, which is better for registering two face model?

### ISSUE THREAD

**Issue by wguo68** [libigl/libigl#173]
Suppose I have two 3d face model with different resolution,scale,orientation, position. I want to register one 3d face model to the other,I can manually select some corresponding points on two models. I want to use some deformation methods such as As-rigid-as-possible  and deformation transfer. But I don't know which deformation technique is better?  
Anyone can give some suggestion?

**Comment by alecjacobson** [comment]
Are you not sure what to use to deform model A or are you not sure how to
transfer it to model B? We have an implementation of ARAP. I'd suggest
trying it or the other methods available first and then returning with
specific problems or artifacts they might cause. Otherwise I'd take a look
at Mario Botsch's more recent transfer papers.

**Comment by wguo68** [comment]
ASAP seems not work well as deformation transfer. Here is the result using ASAP,however the deformation transfer works well. 
![reg](https://cloud.githubusercontent.com/assets/4994038/11897708/d8e2c61a-a5cc-11e5-98f9-61eb3c90edf7.jpg)

**Comment by alecjacobson** [comment]
Certainly looks wrong or like a bad result at least. I'm not sure what's going here or how to help. Do you have a specific question related to libigl?

**Comment by wguo68** [comment]
I use the ASAP method to deform A with 107 handle points with corresponding points from model B. I think ASAP can't  do this kind of tasks because the method try to maintain the length of local edges and the rotation may not good if some handle points are far away.
