### ISSUE TITLE
106_ViewerMenu example does not work in latest Visual Studio 2019

### ISSUE THREAD

**Issue by Fedr** [libigl/libigl#1730]
#### Describe your question

The menu in 106_ViewerMenu example does not work, if the code is compiled in Release configuration in Visual Studio 2019 version 16.8.0 or above:
![image](https://user-images.githubusercontent.com/3136125/109055862-c092b200-76f0-11eb-849a-2d0987efa382.png)

The problem is in wrong return value optimization of imgui function CalcWindowAutoFitSize. I think the root cause in Microsoft compiler, but please at least double check and confirm.

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by jdumas** [comment]
Please update your version of libigl, this was fixed recently.
