### ISSUE TITLE
missing OPENGL_glx_LIBRARY

### ISSUE THREAD

**Issue by YBurakD** [libigl/libigl#1731]
#### Describe your question
I am using Ubuntu 18.04.05 LTS and when I run the cmake command I get the following output:

> -- Creating target: igl::core (igl)
> -- Creating target: igl::comiso (igl_comiso)
> -- Detecting default ISA...
> -- Detected default ISA: SSE2
> -- Creating target: igl::embree (igl_embree)
> -- Creating target: igl::opengl (igl_opengl)
> CMake Error at /usr/local/lib/python3.6/dist-packages/cmake/data/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
>   Could NOT find OpenGL (missing: OPENGL_glx_LIBRARY)
> Call Stack (most recent call first):
>   /usr/local/lib/python3.6/dist-packages/cmake/data/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
>   /usr/local/lib/python3.6/dist-packages/cmake/data/share/cmake-3.18/Modules/FindOpenGL.cmake:433 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
>   cmake/libigl.cmake:353 (find_package)
>   CMakeLists.txt:59 (include)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/ubuntu/libigl/build/CMakeFiles/CMakeOutput.log".
> See also "/home/ubuntu/libigl/build/CMakeFiles/CMakeError.log".

CMakeError.log looks like this:

> Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following
> output:
> Change Dir: /home/ubuntu/libigl/build/CMakeFiles/CMakeTmp
> 
> Run Build Command(s):/usr/bin/make cmTC_70558/fast && /usr/bin/make  -f CMakeFil
> es/cmTC_70558.dir/build.make CMakeFiles/cmTC_70558.dir/build
> make[1]: Entering directory '/home/ubuntu/libigl/build/CMakeFiles/CMakeTmp'
> Building C object CMakeFiles/cmTC_70558.dir/src.c.o
> /usr/bin/cc   -fPIC -DCMAKE_HAVE_LIBC_PTHREAD -o CMakeFiles/cmTC_70558.dir/src.c
> .o -c /home/ubuntu/libigl/build/CMakeFiles/CMakeTmp/src.c
> Linking C executable cmTC_70558
> /usr/local/lib/python3.6/dist-packages/cmake/data/bin/cmake -E cmake_link_script
>  CMakeFiles/cmTC_70558.dir/link.txt --verbose=1
> /usr/bin/cc  -fPIC -DCMAKE_HAVE_LIBC_PTHREAD CMakeFiles/cmTC_70558.dir/src.c.o -
> o cmTC_70558
> CMakeFiles/cmTC_70558.dir/src.c.o: In function `main':
> src.c:(.text+0x3e): undefined reference to `pthread_create'
> src.c:(.text+0x4a): undefined reference to `pthread_detach'
> src.c:(.text+0x56): undefined reference to `pthread_cancel'
> src.c:(.text+0x67): undefined reference to `pthread_join'
> src.c:(.text+0x7b): undefined reference to `pthread_atfork'
> collect2: error: ld returned 1 exit status
> CMakeFiles/cmTC_70558.dir/build.make:105: recipe for target 'cmTC_70558' failed
> make[1]: *** [cmTC_70558] Error 1
> make[1]: Leaving directory '/home/ubuntu/libigl/build/CMakeFiles/CMakeTmp'
> Makefile:140: recipe for target 'cmTC_70558/fast' failed
> make: *** [cmTC_70558/fast] Error 2
> 
> 
> Source file was:
> #include <pthread.h>
> 
> void* test_func(void* data)
> {
>   return data;
> }
> 
> int main(void)
> {
>   pthread_t thread;
>   pthread_create(&thread, NULL, test_func, NULL);
>   pthread_detach(thread);
>   pthread_cancel(thread);
>   pthread_join(thread, NULL);
>   pthread_atfork(NULL, NULL, NULL);
>   pthread_exit(NULL);
> 
>   return 0;
> }
> 
> Determining if the function pthread_create exists in the pthreads failed with th
> e following output:
> Change Dir: /home/ubuntu/libigl/build/CMakeFiles/CMakeTmp
> 
> Run Build Command(s):/usr/bin/make cmTC_77612/fast && /usr/bin/make  -f CMakeFil
> es/cmTC_77612.dir/build.make CMakeFiles/cmTC_77612.dir/build
> make[1]: Entering directory '/home/ubuntu/libigl/build/CMakeFiles/CMakeTmp'
> Building C object CMakeFiles/cmTC_77612.dir/CheckFunctionExists.c.o
> /usr/bin/cc   -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create -o CMakeFiles/cmTC_77
> 612.dir/CheckFunctionExists.c.o -c /usr/local/lib/python3.6/dist-packages/cmake/
> data/share/cmake-3.18/Modules/CheckFunctionExists.c
> Linking C executable cmTC_77612
> /usr/local/lib/python3.6/dist-packages/cmake/data/bin/cmake -E cmake_link_script
>  CMakeFiles/cmTC_77612.dir/link.txt --verbose=1
> /usr/bin/cc  -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create CMakeFiles/cmTC_77612.
> dir/CheckFunctionExists.c.o -o cmTC_77612  -lpthreads
> /usr/bin/ld: cannot find -lpthreads
> collect2: error: ld returned 1 exit status
> CMakeFiles/cmTC_77612.dir/build.make:105: recipe for target 'cmTC_77612' failed
> make[1]: *** [cmTC_77612] Error 1
> make[1]: Leaving directory '/home/ubuntu/libigl/build/CMakeFiles/CMakeTmp'
> Makefile:140: recipe for target 'cmTC_77612/fast' failed
> make: *** [cmTC_77612/fast] Error 2
> 
> 
> 
> Determining if the function sgemm_ exists failed with the following output:
> Change Dir: /home/ubuntu/libigl/build/CMakeFiles/CMakeTmp
> 
> Run Build Command(s):/usr/bin/make cmTC_7f7db/fast && /usr/bin/make  -f CMakeFil
> es/cmTC_7f7db.dir/build.make CMakeFiles/cmTC_7f7db.dir/build
> make[1]: Entering directory '/home/ubuntu/libigl/build/CMakeFiles/CMakeTmp'
> Building C object CMakeFiles/cmTC_7f7db.dir/CheckFunctionExists.c.o
> /usr/bin/cc   -fPIC -DCHECK_FUNCTION_EXISTS=sgemm_ -o CMakeFiles/cmTC_7f7db.dir/
> CheckFunctionExists.c.o -c /usr/local/lib/python3.6/dist-packages/cmake/data/sha
> re/cmake-3.18/Modules/CheckFunctionExists.c
> Linking C executable cmTC_7f7db
> /usr/local/lib/python3.6/dist-packages/cmake/data/bin/cmake -E cmake_link_script
>  CMakeFiles/cmTC_7f7db.dir/link.txt --verbose=1
> /usr/bin/cc  -fPIC -DCHECK_FUNCTION_EXISTS=sgemm_ -rdynamic CMakeFiles/cmTC_7f7d
> b.dir/CheckFunctionExists.c.o -o cmTC_7f7db
> CMakeFiles/cmTC_7f7db.dir/CheckFunctionExists.c.o: In function `main':
> CheckFunctionExists.c:(.text+0x10): undefined reference to `sgemm_'
> collect2: error: ld returned 1 exit status
> CMakeFiles/cmTC_7f7db.dir/build.make:105: recipe for target 'cmTC_7f7db' failed
> make[1]: *** [cmTC_7f7db] Error 1
> make[1]: Leaving directory '/home/ubuntu/libigl/build/CMakeFiles/CMakeTmp'
> Makefile:140: recipe for target 'cmTC_7f7db/fast' failed
> make: *** [cmTC_7f7db/fast] Error 2
> 

I have installed all of the packages listed here in the tutorial:
![image](https://user-images.githubusercontent.com/32135008/109273827-c3da8a80-7823-11eb-81da-6970c34f9ae4.png)

I also have glx.h under /usr/include/GL/
I have no clue why I get this error.
...

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] macOS
- [x ] Linux

**Comment by jdumas** [comment]
Hmm I assume you have tried to delete the build folder and run cmake from scratch after you installed all the packages listed in the tutorial?

**Comment by YBurakD** [comment]
Yes, I did tried that, also tried to re-clone and build from that. Here is the commands I ran:

![image](https://user-images.githubusercontent.com/32135008/109277951-05216900-7829-11eb-9642-f748c0f68da3.png)

**Comment by jdumas** [comment]
Hmm can you try to replace this block of code:
https://github.com/libigl/libigl/blob/7a3af9c85121fe3c8881e1bff08550cd04b63e98/cmake/libigl.cmake#L353-L359

With this:
```cmake
find_package(OpenGL REQUIRED OPTIONAL_COMPONENTS OpenGL)
if(TARGET OpenGL::OpenGL)
    target_link_libraries(igl_opengl ${IGL_SCOPE} OpenGL::OpenGL)
else()
    target_link_libraries(igl_opengl ${IGL_SCOPE} OpenGL::GL)
endif()
```

**Comment by YBurakD** [comment]
I am using cmake version 3.18.4 and replacing the code in libigl.make solved the issue for me. Thank you for your time and effort.

**Comment by STRUGGLE1999** [comment]
When I run a demo,it broke a mistake below:
Can anybody help me please?thk


Traceback (most recent call last):
  File "demo.py", line 68, in <module>
    visualize(renderer, original_img, params, vertices, cam, joints)
  File "../visualise/vis_util.py", line 178, in visualize
    img_overlay = renderer(vert_shifted, img=img, bg_color=np.array((255.0, 255.0, 255.0, 1)))
  File "../visualise/trimesh_renderer.py", line 39, in __call__
    image_bytes = scene.save_image(resolution=(w, h), background=bg_color, visible=True)
  File "/home/XiaoLF/anaconda3/envs/hmr/lib/python3.6/site-packages/trimesh/scene/scene.py", line 867, in save_image
    from ..viewer.windowed import render_scene
  File "/home/XiaoLF/anaconda3/envs/hmr/lib/python3.6/site-packages/trimesh/viewer/windowed.py", line 25, in <module>
    import pyglet.gl as gl  # NOQA
  File "/home/XiaoLF/anaconda3/envs/hmr/lib/python3.6/site-packages/pyglet/gl/__init__.py", line 95, in <module>
    from pyglet.gl.gl import *
  File "/home/XiaoLF/anaconda3/envs/hmr/lib/python3.6/site-packages/pyglet/gl/gl.py", line 45, in <module>
    from pyglet.gl.lib import link_GL as _link_function
  File "/home/XiaoLF/anaconda3/envs/hmr/lib/python3.6/site-packages/pyglet/gl/lib.py", line 149, in <module>
    from pyglet.gl.lib_glx import link_GL, link_GLU, link_GLX
  File "/home/XiaoLF/anaconda3/envs/hmr/lib/python3.6/site-packages/pyglet/gl/lib_glx.py", line 46, in <module>
    glu_lib = pyglet.lib.load_library('GLU')
  File "/home/XiaoLF/anaconda3/envs/hmr/lib/python3.6/site-packages/pyglet/lib.py", line 168, in load_library
    raise ImportError('Library "%s" not found.' % names[0])
ImportError: Library "GLU" not found.
(hmr) [XiaoLF@h3c visualise]$ cd /home/XiaoLF/anaconda3/envs/hmr/lib/python3.6/site-packages/freeglut-3.2.2/build
(hmr) [XiaoLF@h3c build]$ cmake ..
CMake Error at /home/XiaoLF/anaconda3/envs/hmr/lib/python3.6/site-packages/cmake-3.17.0/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_glx_LIBRARY
  OPENGL_INCLUDE_DIR)
Call Stack (most recent call first):
  /home/XiaoLF/anaconda3/envs/hmr/lib/python3.6/site-packages/cmake-3.17.0/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  /home/XiaoLF/anaconda3/envs/hmr/lib/python3.6/site-packages/cmake-3.17.0/share/cmake-3.17/Modules/FindOpenGL.cmake:427 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:266 (FIND_PACKAGE)
