### ISSUE TITLE
Second order derivatives

### ISSUE THREAD

**Issue by acatwithacomputer** [libigl/libigl#1732]
Hello,

I have an equation that includes a term A : grad(grad(f)), where f is a scalar function and A is a rank two tensor. May I ask if libigl can compute the second order derivatives for this?

Thanks,
Brittany

...

Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] macOS
- [X] Linux

**Comment by jdumas** [comment]
For that you might want to look into autodiff libraries such as [this one](https://autodiff.github.io/).

**Comment by acatwithacomputer** [comment]
We're using numerical data. The impression I'm getting, and it may be wrong, is that autodiff needs a function expressed analytically, right? 

The equations have to do with the evolution of the curvatures of the interface between phases. I don't know if this is informative or not. Any recommendations, if you happen to have any off hand and are willing to share, would be awesome.

**Comment by jdumas** [comment]
Hmm maybe you are confusing symbolic differentiation and automatic differentiation? The former works on a symbolic (mathematical) formula of your function, computing analytical derivatives. The latter works by augmenting your scalar type to support elementary operations (like matrix multiply, trigonometry functions, etc.). It then builds a graph of those elementary operations and propagates derivative evaluation either backward/forward to compute the gradient/hessian of your function. Typically you would use a templated function and pass your autodiff scalar type and boom magically you get a gradient/hessian.

**Comment by acatwithacomputer** [comment]
I think what I'm trying to say is that I don't have a templated function for f because it's simulation data (and hence read as constant functions by the autodiff packages), but I might have an idea of something to try. I'll go think about it some more.

Thanks for taking the time, I really do appreciate it, and hope you have a good rest of your day!

**Comment by jdumas** [comment]
Ah ok, makes sense. You might want to look into finite difference schemes then, to approximate your gradient/hessian.
