### ISSUE TITLE
getenv error in "default_num_threads.cpp"

### ISSUE THREAD

**Issue by xarthurx** [libigl/libigl#1743]
#### Describe your issue

When compiling  a project with libigl in  Visual Studio 2019 (info below)
![image](https://user-images.githubusercontent.com/1921878/109839511-773de780-7c47-11eb-9cb0-a73ef67bc126.png)

I got this error:

```
Error C4996 'getenv': This function or variable may be unsafe. Consider using _dupenv_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. igl_cppPort C:\Libraries\libigl\include\igl\default_num_threads.cpp	33	
```

Some reference:
https://stackoverflow.com/questions/48568707/getenv-function-may-be-unsafe-really
https://stackoverflow.com/questions/15916695/can-anyone-give-me-example-code-of-dupenv-s

#### Checklist

- [x] I have read the [bug report](https://libigl.github.io/bug-report/)
- [ ] CMake issue: I have tried with a fresh clone/empty build directory

#### Platform

- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by jdumas** [comment]
Did you change anything to your project in visual studio? Libigl compiles with VS 2019 on Github Actions and doesn't show the error.

**Comment by xarthurx** [comment]
@jdumas  Nope. Just update Visual Studio and got this error.
I can suppress it based on the warning info, though.
Just think this might be some legacy issue and you may want to update the code.

**Comment by xarthurx** [comment]
Perhaps the VS 2019 on github is not the latest version?

**Comment by jdumas** [comment]
Sure. I opened a PR with a fix, will merge once CI is happy.
