### ISSUE TITLE
There seems a bug in read mesh file

### ISSUE THREAD

**Issue by wguo68** [libigl/libigl#175]
For example, if I read an .off file,it will say :"Error: bad line in..."
I modified the code as:

-----------------------------------------------
for(int i = 0;i<number_of_vertices;)
  {
    fgets(line, 1000, off_file);
    if (line[0] == '\n') continue;  //added a line here
   double x,y,z,nx,ny,nz;
----------------------------

**Comment by alecjacobson** [comment]
This fix seems buggy: the variable `i` will continue to increment despite
not reading in a vertex position.

I don't think the off spec allows for blank lines or comments in the middle
of the data chunks.

**Comment by wguo68** [comment]
is it ok?
      if (line[0] == '\n'){ i--; continue;}

**Comment by alecjacobson** [comment]
That would solve the bug, but I still don't think .off files are/should be
allowed to have stray blank lines. I've never run into such files before...
