### ISSUE TITLE
Using static library breaks compilion : no reference towards some functions

### ISSUE THREAD

**Issue by lthiet** [libigl/libigl#1754]
#### Describe your issue

My current goal is to try compiling the static library of libigl because compilation time are too long. However, after adding the CMake rule suggested here : https://libigl.github.io/static-library/ my program does not compile anymore.

Here is the CMake log: 

```
[main] Building folder: assignment2 
[build] Starting build
[proc] Executing command: /usr/bin/cmake --build /home/lam/ETHZ/smgp/gp21-lthiet/assignment2/build --config Debug --target all -- -j 18
[build] [1/2  50% :: 3.176] Building CXX object CMakeFiles/assignment2.dir/src/main.cpp.o
[build] [2/2 100% :: 6.359] Linking CXX executable assignment2
[build] FAILED: assignment2 
[build] : && /bin/g++-10  -fPIC -g  -rdynamic CMakeFiles/assignment2.dir/src/main.cpp.o  -o assignment2  libigl.a  libigl_opengl_glfw.a  libigl_opengl_glfw_imgui.a  libigl_opengl_glfw.a  libigl_opengl.a  libigl.a  -lGL  imgui/libimgui.a  glfw/src/libglfw3.a  -lrt  -lm  -lX11  -lpthread  glad/libglad.a  -ldl && :
[build] /usr/bin/ld: CMakeFiles/assignment2.dir/src/main.cpp.o: in function `callback_key_down(igl::opengl::glfw::Viewer&, unsigned char, int)':
[build] /home/lam/ETHZ/smgp/gp21-lthiet/assignment2/build/../src/main.cpp:228: undefined reference to `void igl::octree<Eigen::Matrix<double, -1, -1, 0, -1, -1>, int, Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, 1, 0, -1, 1> >(Eigen::MatrixBase<Eigen::Matrix<double, -1, -1, 0, -1, -1> > const&, std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >&, Eigen::PlainObjectBase<Eigen::Matrix<int, -1, -1, 0, -1, -1> >&, Eigen::PlainObjectBase<Eigen::Matrix<double, -1, -1, 0, -1, -1> >&, Eigen::PlainObjectBase<Eigen::Matrix<double, -1, 1, 0, -1, 1> >&)'
[build] collect2: error: ld returned 1 exit status
[build] ninja: build stopped: subcommand failed.
[build] Build finished with exit code 1
```

Even though I already included it in my source file

```cpp
#include <igl/octree.h>
```

What is the source of this error? Is there something I missed or is this a bug with CMake/gcc/libigl?

#### Checklist

- [x] I have read the [bug report](https://libigl.github.io/bug-report/) page
- [x] CMake issue: I have tried with a fresh clone/empty build directory

This is for a course work at Uni so I do not have the latest version of libigl. But with it I get another compilation error anyway.

#### Platform

- [ ] Windows
- [ ] macOS
- [x] Linux

**Comment by jdumas** [comment]
The "static lib" version of libigl works by explicitly instantiating a limited number of templated functions, and hides implementations from the C++ headers. As a result, if you are using a function with a type that hasn't been explicitly instantiated (look at the bottom of `igl/octree.cpp`), then you will get such an error.

There is no "easy" way around it: either add your missing template instantiation to libigl and submit a PR, or use libigl in header-only mode.

**Comment by lthiet** [comment]
Thank you for your answer.

Is the submit a PR necessary? I should just be able to modify it locally right?

I assume it it is not something where I just fill in the types or something (sorry I'm no C++ expert..). Could you go into a bit more detail about what is needed to be done when you say "add your missing template instantiation to libigl"?

**Comment by jdumas** [comment]
So basically you need to take this line:
```
[build] /home/lam/ETHZ/smgp/gp21-lthiet/assignment2/build/../src/main.cpp:228: undefined reference to `void igl::octree<Eigen::Matrix<double, -1, -1, 0, -1, -1>, int, Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, 1, 0, -1, 1> >(Eigen::MatrixBase<Eigen::Matrix<double, -1, -1, 0, -1, -1> > const&, std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >&, Eigen::PlainObjectBase<Eigen::Matrix<int, -1, -1, 0, -1, -1> >&, Eigen::PlainObjectBase<Eigen::Matrix<double, -1, -1, 0, -1, -1> >&, Eigen::PlainObjectBase<Eigen::Matrix<double, -1, 1, 0, -1, 1> >&)'
```

Take the part between "\`" (`void igl::octree<...0, -1, 1> >&)`), add `template` + `;` around it, and put it there:
https://github.com/libigl/libigl/blob/bf079eb962e0d3b9b05fa40517656bc8c2a2ba13/include/igl/octree.cpp#L172

Then repeat the process with any new compilation error you encounter.

Sure, you don't have to submit a PR if you are happy with locally modifying libigl. But this means updating libigl to new versions will be more painful.

**Comment by lthiet** [comment]
That worked! Thank you.
