### ISSUE TITLE
'predicates.h' file not found with <angled> include

### ISSUE THREAD

**Issue by z-hasher** [libigl/libigl#1757]
#### Describe your issue

When compiling a test code with clang-8 through bazel, calling `igl::predicates::exactinit`, clang-8 complained as the following:
```
In file included from third_party/official_igl_test.cc:4:
In file included from external/com_github_official_igl/include/igl/predicates/predicates.h:97:
external/com_github_official_igl/include/igl/predicates/predicates.cpp:9:10: error: 'predicates.h' file not found with <angled> include; use "quotes" instead
#include <predicates.h>
```
So when reading `igl/predicates/predicates.cpp`, I see
```
#include <igl/predicates/predicates.h>
#include <predicates.h>
```
Is there any reason keeping the second include? I can submit a quick fix if by either removing it or replacing brackets with quotes. How does this sound?

Thanks
Victor

#### Checklist

- [x] I have read the [bug report](https://libigl.github.io/bug-report/) page
- [x] CMake issue: I have tried with a fresh clone/empty build directory

#### Platform

- [ ] Windows
- [ ] macOS
- [x] Linux

**Comment by jdumas** [comment]
Yes the second include is for https://github.com/libigl/libigl-predicates
I would suggest that you stick with CMake first. Anything not directly under `include/igl` has extra dependencies that you need to compile with.

**Comment by z-hasher** [comment]
Oh I see. I guess then I will just do a personal patch since we don't use CMake in our system directly. Thanks @jdumas
