### ISSUE TITLE
Compile Fail

### ISSUE THREAD

**Issue by BEMfreshman** [libigl/libigl#176]
Hi,
I want to compile the libigl as static library on my archlinux with gcc 5.3 and Eigen 2.7.3 but enconter some  problems as following:

>/home/yangwenlu/libigl/include/igl/ambient_occlusion.cpp:37:3: error: for statement expected before ‘const’
   const MatrixXf D = random_dir_stratified(num_samples).cast<float>();

Someone can help me?

**Comment by alecjacobson** [comment]
Hmmm. It could be that the `#pragma omp parallel for` line is throwing off
your compiler. Though that's surprising. You could try deleting that line...
