### ISSUE TITLE
sort function call in line 145 of doublearea.cpp

### ISSUE THREAD

**Issue by TerranRush** [libigl/libigl#178]
The doublearea() is used in many computation, e.g. the laplacian matrix construction.
However, I don't quite understand why the sort() is necessary here, as it would cause computation overhead.
The Heron's formula does not need a sorting and the following code seems rather irrelevant to the element order in a row.

**Comment by alecjacobson** [comment]
in most cases it will be irrelevant. But in nearly degenerate cases this is
more robust to floating point errors ( see the paper by shewchuck). The
sort is also very little constant overhead.
