### ISSUE TITLE
multiplication out of "unsigned int" range in function "point_in_poly"

### ISSUE THREAD

**Issue by xarthurx** [libigl/libigl#1783]
#### Describe the bug
OK, I have to say this bug costs me a lot of time to dig and find...

When deciding if a point is inside a given closed polygon, the function uses an approach as stated in:
http://www.visibone.com/inpoly/

However, there is a step that makes the internal value going out of the bound if its type, and thus make the function not working as expected.

This line and the line below:
https://github.com/libigl/libigl/blob/e2877039121023dd870d1172d4b209aae160f9a4/include/igl/point_in_poly.cpp#L43

Here, the function converts `unsigned int` to `long` first and conduct the multiplication. However, on my machine:
```
max limit of unsigned int: 4294967295
max limit of long:         2147483647
```

This makes the test go out of range if the given point is large (it doesn't have to be too large even, `400000` is already enough to make it buggy).

The original function is designed for images (the number is usually not too big), but when applying to general geometry, it is quite limited.

I'm not sure about the range of different types in C as the original code, but here, it seems the bug will affect a lot.
Perhaps the "sum of angle" approach should be used to re-write the function?

#### Platform
- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by alecjacobson** [comment]
Sum of angle is what winding number does. I always use that and had
forgotten we have this in poly function.

**Comment by xarthurx** [comment]
I've checked the WindingNumberTree` Class, may I ask how can I use it for 2D polyline boundary?
Does it seem that was designed for closed meshes?

**Comment by alecjacobson** [comment]
call igl::winding_number directly. The tree you're referring to is just for
3D. In 2D, the computation is not accelerated (i.e., it's O( #F #P) )

>

**Comment by xarthurx** [comment]
@alecjacobson 
Does the `igl::winding_number` only accept `V` in `double` format?\

Considering the example below:

```
  MatrixXi testV(4, 2);
  testV << 0, 0, 2, 0, 2, 2, 0, 2;
  MatrixXi testF(4, 2);
  testF << 0, 1, 1, 2, 2, 3, 3, 0;
  Vector2i pt(1, 1);

  auto wn = igl::winding_number(testV, testF, pt);
  cout << "winding number: " << wn << endl;
```
gives `0`, but 

```
  MatrixXd testV(4, 2);
  testV << 0, 0, 2, 0, 2, 2, 0, 2;
  MatrixXi testF(4, 2);
  testF << 0, 1, 1, 2, 2, 3, 3, 0;
  Vector2d pt(1, 1);

  auto wn = igl::winding_number(testV, testF, pt);
  cout << "winding number: " << wn << endl;
```
gives `1`.

**Comment by alecjacobson** [comment]
It should work fine for floating point numbers (for V). In general, libigl
functions are going to misbehave if the vertex positions are integers. You
can use .cast<double>() for example.

>

**Comment by xarthurx** [comment]
> In general, libigl functions are going to misbehave if the vertex positions are integers.

OK, this is good to know.
Thank you.

**Comment by xarthurx** [comment]
The `winding_number` works with no problems, and actually get better precision.
Should the `point_in_poly` be removed? I can submit a PR. Otherwise, this issue can be closed.
