### ISSUE TITLE
slice() problem in debug mode

### ISSUE THREAD

**Issue by TerranRush** [libigl/libigl#179]
windows platform, debug mode in visual studio 2015 community
1. using Y = slice(X,R,dim) gets totally wrong values...
2. in contrast, using slice(X,R,dim,Y) gets correct result.

**Comment by alecjacobson** [comment]
Could you post a small example?

**Comment by TerranRush** [comment]
I think the problem is due to some alignment issue of Eigen for MSVC.
I use "libigl\external\nanogui\ext\eigen" before, so it does not work.
After I change to the latest Eigen, everything is fine now.

**Comment by alecjacobson** [comment]
Good to hear. But are you saying that when you use `nanogui\ext\eigen`
there are memory issues?

Perhaps cross list this on https://github.com/wjakob/nanogui/issues to
alert that team

**Comment by danielepanozzo** [comment]
I updated Eigen in `nanogui\ext\eigen`.

Terranrush, could you please confirm that the issue is gone with a fresh libigl clone on your environment?

**Comment by TerranRush** [comment]
Hi Daniele, yes it works.

**Comment by danielepanozzo** [comment]
Great, thanks for checking!
