### ISSUE TITLE
Cannot open source file "triangle.h" when using the triangle lib

### ISSUE THREAD

**Issue by xarthurx** [libigl/libigl#1791]
#### Describe the bug
1. Turn on the "LIBIGL_WITH_TRIANGLE" lib in cmake.
2.
```cpp
#include <igl/triangle/triangulate.h>

// call igl::triangle::triangluate func
```
3. Compile
4. VS Studio gives error:
![image](https://user-images.githubusercontent.com/1921878/115954430-541a1080-a4f1-11eb-8bb8-1341daf39483.png)
And the error points to:
![image](https://user-images.githubusercontent.com/1921878/115954444-609e6900-a4f1-11eb-9011-caa2b58df3a0.png)
(the `triangulate.cpp` file)

#### Platform

- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by jdumas** [comment]
You need to link against `igl::triangle` in your CMake project.

**Comment by xarthurx** [comment]
My bad... thanks.
