### ISSUE TITLE
Can't convert CGAL::Polyhedron_3 to mesh

### ISSUE THREAD

**Issue by szobov** [libigl/libigl#1795]
#### Describe the bug

Hi there,
Thanks a lot for such a wonderful project.
I'm trying to use it together with CGAL, but when I tried to convert Polyhedron to the mesh I got:
```
typedef CGAL::Exact_predicates_exact_constructions_kernel Kernel;
typedef CGAL::Polyhedron_3<Kernel> Polyhedron;

int main(int argc, char * argv[])
{
            Polyhedron P;
            Eigen::MatrixXi convex_part_faces;
            Eigen::MatrixXd convex_part_vertices;
            igl::copyleft::cgal::polyhedron_to_mesh(P, convex_part_vertices, convex_part_faces);
}
```

```
In file included from /.../libigl/include/igl/copyleft/cgal/polyhedron_to_mesh.h:40,
                 from /.../libigl-example-project/src/test/src/igl.cpp:19:
/.../libigl/include/igl/copyleft/cgal/polyhedron_to_mesh.cpp: In instantiation of ‘void igl::copyleft::cgal::polyhedron_to_mesh(const Polyhedron&, Eigen::PlainObjectBase<DerivedD>&, Eigen::PlainObjectBase<DerivedVC>&) [with Polyhedron = CGAL::Polyhedron_3<CGAL::Epeck>; DerivedV = Eigen::Matrix<double, -1, -1>; DerivedF = Eigen::Matrix<int, -1, -1>]’:
/.../libigl-example-project/src/test/src/igl.cpp:256:95:   required from here
/.../libigl/include/igl/copyleft/cgal/polyhedron_to_mesh.cpp:32:14: error: cannot convert ‘CGAL::cpp11::result_of<CGAL::Lazy_construction_nt<CGAL::Epeck, CGAL::CartesianKernelFunctors::Compute_x_3<CGAL::Simple_cartesian<CGAL::Interval_nt<false> > >, CGAL::CartesianKernelFunctors::Compute_x_3<CGAL::Simple_cartesian<CGAL::Gmpq> > >(CGAL::Point_3<CGAL::Epeck>)>::type’ {aka ‘CGAL::Lazy_exact_nt<CGAL::Gmpq>’} to ‘Eigen::DenseCoeffsBase<Eigen::Matrix<double, -1, -1>, 1>::Scalar’ {aka ‘double’} in assignment
   32 |       V(v,0) = p->point().x();
/.../libigl/include/igl/copyleft/cgal/polyhedron_to_mesh.cpp:33:14: error: cannot convert ‘CGAL::cpp11::result_of<CGAL::Lazy_construction_nt<CGAL::Epeck, CGAL::CartesianKernelFunctors::Compute_y_3<CGAL::Simple_cartesian<CGAL::Interval_nt<false> > >, CGAL::CartesianKernelFunctors::Compute_y_3<CGAL::Simple_cartesian<CGAL::Gmpq> > >(CGAL::Point_3<CGAL::Epeck>)>::type’ {aka ‘CGAL::Lazy_exact_nt<CGAL::Gmpq>’} to ‘Eigen::DenseCoeffsBase<Eigen::Matrix<double, -1, -1>, 1>::Scalar’ {aka ‘double’} in assignment
   33 |       V(v,1) = p->point().y();
/.../libigl/include/igl/copyleft/cgal/polyhedron_to_mesh.cpp:34:14: error: cannot convert ‘CGAL::cpp11::result_of<CGAL::Lazy_construction_nt<CGAL::Epeck, CGAL::CartesianKernelFunctors::Compute_z_3<CGAL::Simple_cartesian<CGAL::Interval_nt<false> > >, CGAL::CartesianKernelFunctors::Compute_z_3<CGAL::Simple_cartesian<CGAL::Gmpq> > >(CGAL::Point_3<CGAL::Epeck>)>::type’ {aka ‘CGAL::Lazy_exact_nt<CGAL::Gmpq>’} to ‘Eigen::DenseCoeffsBase<Eigen::Matrix<double, -1, -1>, 1>::Scalar’ {aka ‘double’} in assignment
   34 |       V(v,2) = p->point().z();
 2make[2]: *** [src/test/CMakeFiles/decompose_exe.dir/build.make:63: src/test/CMakeFiles/decompose_exe.dir/src/igl.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1060: src/test/CMakeFiles/decompose_exe.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```
I suppose I did something wrong, but I found no clue in docs how to fix it.

Thanks in advance.
Cheers
#### Platform

- [ ] Windows
- [ ] macOS
- [ X] Linux

**Comment by alecjacobson** [comment]
Thanks for submitting this. I confirm the issue.

It also appears to point out that CGAL requires C++14 whereas we're claiming we only need C++11, so perhaps we need to document this or bump or requirement. I'll try to debug the issue with ->point...

**Comment by szobov** [comment]
> Thanks for submitting this. I confirm the issue.
> 
> It also appears to point out that CGAL requires C++14 whereas we're claiming we only need C++11, so perhaps we need to document this or bump or requirement. I'll try to debug the issue with ->point...

Thanks a lot @alecjacobson 
If you need any help please reach me out

**Comment by jdumas** [comment]
libigl uses CGAL 4.12, which is still C++11. CGAL bumped the C++ requirement to C++14 for version 5, which we are not supporting at the moment. I am working on a branch of libigl that pulls CGAL directly via CMake, so there won't be any mismatch between system version, but this is not ready yet.

**Comment by alecjacobson** [comment]
I guess merging the PR closes the issue automatically. Hopefully this works for you too. Re:C++14, I agree let's wait until everything is ready.

**Comment by jdumas** [comment]
Yep. We might want to update libigl's minimum requirement to C++14 or even C++17 once we tag version 3.0.0. Eigen 3.4 is coming up soon and is adding proper alignment support when compiled with C++17, which imho has been a source of issue for newcomers unfamiliar with Eigen's alignment particulars.

**Comment by szobov** [comment]
> I guess merging the PR closes the issue automatically. Hopefully this works for you too. Re:C++14, I agree let's wait until everything is ready.

Yes, thanks a lot for such a quick fix. You're marvelous folks!
I've testest it locally by cherry-picking your changes and it compiles. (Didn't check in runtime because have another issue)

I understand that it's not the right place to ask another question, but during this fix, I noticed this [comment and assertation](https://github.com/libigl/libigl/pull/1796/files#diff-1e805c63746a50a9738bf007fdab80b5964c0cf6392629baf24d423bb8d02c06R49-R50) which is a bit confusing, because facets in CGAl's polyhedron could have more than 3 vertices.

> // Facets in polyhedral surfaces are at least triangles.
      assert(CGAL::circulator_size(he) == 3 && "Facets should be triangles");
      
 Just to be sure, should it be so?

**Comment by alecjacobson** [comment]
That certainly looks suspicious. I would need to look at the code to see if
it can really deal with non-triangle inputs.
-Alec

>

**Comment by szobov** [comment]
> That certainly looks suspicious. I would need to look at the code to see if it can really deal with non-triangle inputs. -Alec
> […](#)

Hi Alec,

I met this behavior after trying to apply `polyhedron_to_mesh` on the result, produced by CGAL's functions.
When I checked the number of vertices around facets it was from 4 to 8 which is not acceptable by `polygon_to_mesh` since this assertation.
But! They have a special function `CGAL::Polygon_mesh_processing::triangulate_faces`, which is just dividing the mesh surface to contain only triangles.

I had an idea to make a PR with a detailed description of the assertation's message, to point on this function in CGAL. But of course, it would be better to just deal with it inside a `polygon_to_mesh` function.

Anyway, thanks a lot for your time.
Cheers
