### ISSUE TITLE
Including CGAL in CMakeLists.txt

### ISSUE THREAD

**Issue by drathin4** [libigl/libigl#1799]
I'm trying to include cgal for working with mesh booleans. But when I use the following script, I cannot generate the visual studio solution. 

cmake_minimum_required(VERSION 3.1)
project(example)

set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${CMAKE_CURRENT_SOURCE_DIR}/cmake)

# libigl
option(LIBIGL_WITH_OPENGL            "Use OpenGL"         ON)
option(LIBIGL_WITH_OPENGL_GLFW       "Use GLFW"           ON)

find_package(LIBIGL REQUIRED QUIET)

# Add your project files
file(GLOB SRCFILES *.cpp)
add_executable(${PROJECT_NAME} ${SRCFILES})
target_link_libraries(${PROJECT_NAME} igl::core igl::opengl igl::opengl_glfw igl::cgal)
igl_copy_cgal_dll(${PROJECT_NAME})

It issues the following error:

CMake Error at CMakeLists.txt:14 (add_executable):
  Target "example" links to target "igl::cgal" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?

Even including 
option(LIBIGL_WITH_CGAL              "Use CGAL"           ON)
doesn't help to solve the problem. How should I resolve it ?

**Comment by jdumas** [comment]
You need to enable LIBIGL_WITH_CGAL

**Comment by drathin4** [comment]
I did use 
option(LIBIGL_WITH_CGAL "Use CGAL" ON)
as I mentioned on the penultimate line of my issue. 

Still I'm getting the same error. The error is suggesting something related to find_package().

**Comment by jdumas** [comment]
Right, my bad. You need to have the right version of CGAL installed on your computer somehow. You can use this conda environment for this purpose:
https://github.com/libigl/libigl/blob/main/cmake/libigl-cgal.yml

**Comment by drathin4** [comment]
My basic setup of LibIGL (including CGAL) has happened correctly. I had included the line 

cmake -DLIBIGL_WITH_CGAL=ON ../

while creating the Visual Studio projects and solution. Additionally, I had downloaded Boost library ( version 1_76_0) from 

https://www.boost.org/users/download/ 

After that the compilation happened correctly. So everything is fine till that step. Hence I think that I do have the correct version of CGAL since CMake itself has downloaded/installed CGAL. 

Now I'm trying to code on top of LibIGL, hence I'm creating my own project. I used the example project of LibIGL as a template and started building from that. Am I missing something in the CMakeLists.txt file ?

**Comment by jdumas** [comment]
I don't understand the question. Are you having trouble setting up CGAL+Libigl in your own project? If so, what kind of error message do you get? For CGAL, the only thing you need on Windows is make sure to copy the gmp/mpfr dlls to the folder containing your executable. For the tutorials, this is handled by the cmake function call `igl_copy_cgal_dll(my_exe)`.

**Comment by drathin4** [comment]
Yes, correct. I'm having trouble setting up CGAL + LibIGL in my own project. 

I had already included the line 

igl_copy_cgal_dll(${PROJECT_NAME})

in CMakeLists.txt. And the required files (libgmp-10.dll, libmpfr-4.dll) are already copied in Release folder containing the *.exe files: ...\MeshBoolean\libigl\build\bin\Release\
(MeshBoolean is the project folder)

However it is complaining:

CMake Error at CMakeLists.txt:14 (add_executable):
Target "example" links to target "igl::cgal" but the target was not found.
Perhaps a find_package() call is missing for an IMPORTED target, or an
ALIAS target is missing?

**Comment by jdumas** [comment]
Have you cleared you CMakeCache.txt and confirmed that the option `LIBIGL_WITH_CGAL` is set to `ON` in your `CMakeCache.txt`?

**Comment by drathin4** [comment]
Thanks, that worked. I changed to LIBIGL_WITH_CGAL:BOOL=ON from LIBIGL_WITH_CGAL:BOOL=OFF in the CMakeCache.txt file that you mentioned. Do we manually delete the CMakeCache.txt file to regenerate it after cmake .. command ?

**Comment by jdumas** [comment]
CMake options such as `LIBIGL_WITH_CGAL` are cached into the file `<build>/CMakeCache.txt`, so in practice even if you change the option in your CMakeLists.txt in your project, this will not update the cached value stored in the build folder. You need to use `cmake-gui` or `ccmake` to toggle cached CMake options (or edit `CMakeCache.txt` directly), and _then_ have CMake re-run its "configure" step to update the project definition. Deleting the whole `CMakeCache.txt` is kinda the nuclear option and will wipe out all cached values, thus capturing the new values set in your `CMakeLists.txt` when you re-run CMake.

**Comment by lichengqi0805** [comment]
`-- Forcing include of libigl module: cgal
CMake Error at build/_deps/libigl-src/cmake/igl/igl_include.cmake:32 (include):
  include could not find load file:

    build/_deps/libigl-src/cmake/igl/modules//cgal.cmake
Call Stack (most recent call first):
  build/_deps/libigl-src/cmake/igl/igl_include.cmake:54 (_igl_include_full)
  CMakeLists.txt:16 (igl_include)`
