### ISSUE TITLE
Change variable name to "target" when tracing the path for dijkstra?

### ISSUE THREAD

**Issue by waterrhett** [libigl/libigl#180]
This is not a "bug", but I think it can be confusing as for what to pass in as the first parameter in [dijkstra_get_shortest_path_to] (https://github.com/libigl/libigl/blob/master/include/igl/dijkstra.h#L49).
Should the first input argument be named "target", to avoid confusion?

**Comment by alecjacobson** [comment]
The [dijkstra.h](../tree/master/include/igl/dijkstra.h) and [dijkstra.cpp](../tree/master/include/igl/dijkstra.cpp) are highly non-libigl-standard implementations. They should probably be re-written according to [libigl style](../tree/master/style-guidelines.md).
