### ISSUE TITLE
compile error in the building for  the nanogui project

### ISSUE THREAD

**Issue by wguo68** [libigl/libigl#181]
libigl\external\nanogui\ext\nanovg\src\stb_image.h(715): error C2099: initializer is not a constant

in this line of the code:
  static float stbi__h2l_gamma_i=1.0f/2.2f, stbi__h2l_scale_i=1.0f;

I  have to change the line of code to 
 static float stbi__h2l_gamma_i=0.45454545f, stbi__h2l_scale_i=1.0f;

**Comment by alecjacobson** [comment]
This belongs as an issue to nanogui not libigl.
