### ISSUE TITLE
Two warnings  for two project when Cmake to vs2015

### ISSUE THREAD

**Issue by wguo68** [libigl/libigl#182]
The two warning are similar, for example ,the first is 

"CMake Warning (dev) at 610_CSGTree/CMakeLists.txt:9 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.
 "

**Comment by alecjacobson** [comment]
This is how we're detecting the compiler, according to http://stackoverflow.com/a/10055571/148668
