### ISSUE TITLE
Warning: readOBJ() ignored non-comment line `  o <object-name>`

### ISSUE THREAD

**Issue by Shreeyak** [libigl/libigl#1823]
#### Describe the bug
When reading an .obj file that was composed of multiple objects, python binding raises warnings:
```
Warning: readOBJ() ignored non-comment line 88926:
  o tree-bath-bomb.001
Warning: readOBJ() ignored non-comment line 177805:
  o glass-round-potion
```
The lines starting with `o ` within the .obj file cause this warning. The .obj file was exported from Blender.

#### Platform

- [ ] Windows
- [ ] macOS
- [x ] Linux

**Comment by Shreeyak** [comment]
[scene_mesh.zip](https://github.com/libigl/libigl/files/6616329/scene_mesh.zip)
Sample mesh attached.

**Comment by jdumas** [comment]
Those lines correspond to name/group information, which libigl ignores. Doesn't look like a bug to me.
