### ISSUE TITLE
libigl compilation with win10 error

### ISSUE THREAD

**Issue by futureflsl** [libigl/libigl#1825]
environment:
windows10 x64
vs2019
cmake==3.17.2
libigl==2.3.0

when I cmake libigl,error occurd!

用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.25.28614 版

  src.cxx

  版权所有(C) Microsoft Corporation。保留所有权利。

  cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D WIN32 /D _WINDOWS /D COMPILER_HAS_DEPRECATED_ATTR /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_1a562.dir\Debug\\" /Fd"cmTC_1a562.dir\Debug\vc142.pdb" /Gd /TP /errorReport:queue E:\libigl\build\CMakeFiles\CMakeTmp\src.cxx

E:\libigl\build\CMakeFiles\CMakeTmp\src.cxx(1,16): error C2065: “__deprecated__”: 未声明的标识符 [E:\libigl\build\CMakeFiles\CMakeTmp\cmTC_1a562.vcxproj]

E:\libigl\build\CMakeFiles\CMakeTmp\src.cxx(1,31): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int [E:\libigl\build\CMakeFiles\CMakeTmp\cmTC_1a562.vcxproj]

E:\libigl\build\CMakeFiles\CMakeTmp\src.cxx(1,37): error C2448: “__attribute__”: 函数样式初始值设定项类似函数定义 [E:\libigl\build\CMakeFiles\CMakeTmp\cmTC_1a562.vcxproj]

Source file was:
__attribute__((__deprecated__)) int somefunc() { return 0; }
    int main() { return somefunc();}

**Comment by alecjacobson** [comment]
I can't tell what igl function/file this is referring to. If it was deprecated.h that's been removed. Reopen if this is still an issue.
