### ISSUE TITLE
fatal error C1021: invalid preprocessor command 'warning' when compile using VS2015

### ISSUE THREAD

**Issue by wguo68** [libigl/libigl#183]
there are many many these errors when compile

**Comment by alecjacobson** [comment]
These warnings had to do with improper use of `Eigen::PlainObjectBase`. I've fixed most of them, but those that remain are in highly non-libigl-standard files:

[include/igl/angle_bound_frame_fields.cpp](../tree/master/include/igl/angle_bound_frame_fields.cpp/)
[include/igl/comb_cross_field.cpp](../tree/master/include/igl/comb_cross_field.cpp/)
[include/igl/comb_line_field.cpp](../tree/master/include/igl/comb_line_field.cpp/)
[include/igl/cross_field_missmatch.cpp](../tree/master/include/igl/cross_field_missmatch.cpp/)
[include/igl/cut_mesh.cpp](../tree/master/include/igl/cut_mesh.cpp/)
[include/igl/cut_mesh_from_singularities.cpp](../tree/master/include/igl/cut_mesh_from_singularities.cpp/)
[include/igl/line_field_missmatch.cpp](../tree/master/include/igl/line_field_missmatch.cpp/)
[include/igl/n_polyvector.cpp](../tree/master/include/igl/n_polyvector.cpp/)
[include/igl/n_polyvector_general.cpp](../tree/master/include/igl/n_polyvector_general.cpp/)
[include/igl/polyvector_field_matchings.cpp](../tree/master/include/igl/polyvector_field_matchings.cpp/)

These functions should probably be re-written according to [libigl style](../tree/master/style-guidelines.md) or possibly moved out of libigl into their own repositories and included as extras.

**Comment by danielepanozzo** [comment]
I cleaned them all, please reopen if the problem is still there.
