### ISSUE TITLE
plot function is not working

### ISSUE THREAD

**Issue by FaezAlkadi** [libigl/libigl#1830]
Hello,
Thank you so much for this great package.
I am trying to use this package with python (pycharm) and I installed igl on anaconda as shown [here ](https://libigl.github.io/libigl-python-bindings/)
Then I wanted to plot my stl file as follow:

```
from meshplot import plot, subplot, interact
from igl import read_triangle_mesh

[v, f] = read_triangle_mesh("0001-STL files/1x2x3 mm.stl")
print(v, f)
plot(v, f)
```

However, I unfortunately ended up with the following error when I used `plot(v, f)` command:

```
File "C:\Users\Faez\anaconda3\lib\site-packages\meshplot\plot.py", line 93, in plot
    display(view._renderer)
NameError: name 'display' is not defined
```
**Note: I am working on windows 10**
Hope you can help with this. 
Thank you so much

**Comment by sebastienchappuis** [comment]
Hey, I think it is because you are not using meshplot via a Jupyter notebook, as reported here https://github.com/skoch9/meshplot/issues/11

**Comment by alecjacobson** [comment]
This appears to be a meshplot issues, not a libigl or libigl-python-bindings issue. Closing and would encourage to transfer to  https://github.com/skoch9/meshplot/issues
