### ISSUE TITLE
Failing to build v2.3.0 on Linux

### ISSUE THREAD

**Issue by Jeff-Hadley** [libigl/libigl#1836]
#### Describe your issue
Building libIGL v2.3.0 on Debian GNU/Linux 8.11  using cmake 3.16.0 is failing on "Building CXX object CMakeFiles/igl.dir/include/igl/diag.cpp.o" and "Building CXX object CMakeFiles/igl.dir/include/igl/dual_contouring.cpp.o" returning the following error logs: 

> /users/jeffhadley/Builds/libigl/include/igl/diag.cpp: In instantiation of \u2018void igl::diag(const Eigen::MatrixBase<U>&, Eigen::SparseMatrix<Scalar>&) [with T = double; DerivedV = Eigen::Matrix<double, -1, 1>]\u2019:
> /users/jeffhadley/Builds/libigl/include/igl/diag.cpp:106:177:   required from here
> /users/jeffhadley/Builds/libigl/include/igl/diag.cpp:92:73: warning: \u2018Eigen::DynamicSparseMatrix<_Scalar, _Flags, _StorageIndex>::DynamicSparseMatrix(Eigen::Index, Eigen::Index) [with _Scalar = double; int _Options = 1; _StorageIndex = int; Eigen::Index = long int]\u2019 is deprecated (declared at /users/jeffhadley/Builds/libigl/external/eigen/unsupported/Eigen/src/SparseExtra/DynamicSparseMatrix.h:238) [-Wdeprecated-declarations]
>    Eigen::DynamicSparseMatrix<T, Eigen::RowMajor> dyn_X(V.size(),V.size());
>                                                                          ^
> /users/jeffhadley/Builds/libigl/include/igl/diag.cpp: In instantiation of \u2018void igl::diag(const Eigen::SparseVector<T>&, Eigen::SparseMatrix<Scalar>&) [with T = double]\u2019:
> /users/jeffhadley/Builds/libigl/include/igl/diag.cpp:107:113:   required from here
> /users/jeffhadley/Builds/libigl/include/igl/diag.cpp:75:73: warning: \u2018Eigen::DynamicSparseMatrix<_Scalar, _Flags, _StorageIndex>::DynamicSparseMatrix(Eigen::Index, Eigen::Index) [with _Scalar = double; int _Options = 1; _StorageIndex = int; Eigen::Index = long int]\u2019 is deprecated (declared at /users/jeffhadley/Builds/libigl/external/eigen/unsupported/Eigen/src/SparseExtra/DynamicSparseMatrix.h:238) [-Wdeprecated-declarations]
>    Eigen::DynamicSparseMatrix<T, Eigen::RowMajor> dyn_X(V.size(),V.size());

and

> /users/jeffhadley/Builds/libigl/include/igl/dual_contouring.cpp: In instantiation of \u2018typename decltype (((igl::DualContouring<Scalar>*)0)->igl::DualContouring<Scalar>::V)::Index igl::DualContouring<Scalar>::sub2dual(const RowVector3i&) [with Scalar = double; typename decltype (((igl::DualContouring<Scalar>*)0)->igl::DualContouring<Scalar>::V)::Index = long int; Eigen::RowVector3i = Eigen::Matrix<int, 1, 3>]\u2019:
> /users/jeffhadley/Builds/libigl/include/igl/dual_contouring.cpp:245:62:   required from \u2018bool igl::DualContouring<Scalar>::single_edge(const int&, const int&, const int&, const int&, const RowVector3S&, const Scalar&, const RowVector3S&, const Scalar&) [with Scalar = double; igl::DualContouring<Scalar>::RowVector3S = Eigen::Matrix<double, 1, 3>]\u2019
> /users/jeffhadley/Builds/libigl/include/igl/dual_contouring.cpp:399:48:   required from \u2018igl::DualContouring<Scalar>::dense(const Eigen::MatrixBase<OtherDerived>&, const Eigen::MatrixBase<OtherDerived>&, int, int, int)::<lambda(int)> [with DerivedGf = Eigen::Matrix<double, -1, 1>; DerivedGV = Eigen::Matrix<double, -1, 3, 1, -1, 3>; Scalar = double]\u2019
> /users/jeffhadley/Builds/libigl/include/igl/dual_contouring.cpp:389:33:   required from \u2018struct igl::DualContouring<Scalar>::dense(const Eigen::MatrixBase<OtherDerived>&, const Eigen::MatrixBase<OtherDerived>&, int, int, int) [with DerivedGf = Eigen::Matrix<double, -1, 1>; DerivedGV = Eigen::Matrix<double, -1, 3, 1, -1, 3>; Scalar = double]::<lambda(int)>\u2019
> /users/jeffhadley/Builds/libigl/include/igl/dual_contouring.cpp:403:15:   required from \u2018void igl::DualContouring<Scalar>::dense(const Eigen::MatrixBase<OtherDerived>&, const Eigen::MatrixBase<OtherDerived>&, int, int, int) [with DerivedGf = Eigen::Matrix<double, -1, 1>; DerivedGV = Eigen::Matrix<double, -1, 3, 1, -1, 3>; Scalar = double]\u2019
> /users/jeffhadley/Builds/libigl/include/igl/dual_contouring.cpp:524:3:   required from \u2018void igl::dual_contouring(const std::function<typename DerivedV::Scalar(const Eigen::Matrix<typename DerivedV::Scalar, 1, 3>&)>&, const std::function<Eigen::Matrix<typename DerivedV::Scalar, 1, 3>(const Eigen::Matrix<typename DerivedV::Scalar, 1, 3>&)>&, const Eigen::MatrixBase<Derived>&, const Eigen::MatrixBase<U>&, int, int, int, bool, bool, bool, Eigen::PlainObjectBase<DerivedV>&, Eigen::PlainObjectBase<DerivedQ>&) [with DerivedGf = Eigen::Matrix<double, -1, 1>; DerivedGV = Eigen::Matrix<double, -1, 3, 1, -1, 3>; DerivedV = Eigen::Matrix<double, -1, -1>; DerivedQ = Eigen::Matrix<int, -1, -1>; typename DerivedV::Scalar = double]\u2019
> /users/jeffhadley/Builds/libigl/include/igl/dual_contouring.cpp:560:846:   required from here
> /users/jeffhadley/Builds/libigl/include/igl/dual_contouring.cpp:116:50: error: converting to \u2018igl::DualContouring<double>::KeyTriplet {aka std::tuple<int, int, int>}\u2019 from initializer list would use explicit constructor \u2018constexpr std::tuple< <template-parameter-1-1> >::tuple(const _Elements& ...) [with _Elements = {int, int, int}]\u2019
>          const KeyTriplet key = {kc(0),kc(1),kc(2)};
>                                                   ^
> CMakeFiles/igl.dir/build.make:1401: recipe for target 'CMakeFiles/igl.dir/include/igl/dual_contouring.cpp.o' failed
> make[2]: *** [CMakeFiles/igl.dir/include/igl/dual_contouring.cpp.o] Error 1
> CMakeFiles/Makefile2:2067: recipe for target 'CMakeFiles/igl.dir/all' failed
> make[1]: *** [CMakeFiles/igl.dir/all] Error 2
> Makefile:162: recipe for target 'all' failed
> make: *** [all] Error 2

I have a fresh clone of the git repo and v2.3.0 checked out. I've recreated the issue multiple times in both fresh and previously ran build folders. I'm fairly new to building software, and am not sure what my next steps should be or what I should be investigating to try to resolve this error. Any help or direction would be very appreciated! 

#### Checklist

- [ x] I have read the [bug report](https://libigl.github.io/bug-report/) page
- [x ] CMake issue: I have tried with a fresh clone/empty build directory

#### Platform

- [ ] Windows
- [ ] macOS
- [ x] Linux

**Comment by jdumas** [comment]
> Debian GNU/Linux 8.1

Do you mean you have Debian 8? That's pretty old. What version of gcc are you compiling with?

**Comment by Jeff-Hadley** [comment]
Yes, Debian 8.11 (jessie). Currently using gcc-6.3.0 as that's what we currently use for all our other build purposes (Paraview, SimModeler, Qt, etc, but can soft add up to 8.2.0, 9.2.0, and 10.2.0 if need be.

**Comment by jdumas** [comment]
Our nightly builds of libigl are tested with gcc 8, 9 and 10. Could you try with those and see if it works for you?

**Comment by Jeff-Hadley** [comment]
I'll give that a try and report back. Thank you, @jdumas.

**Comment by Jeff-Hadley** [comment]
@jdumas, we tried with gcc-8.2.0, 9.2.0 and 10.2.0, all failed at the same diag.cpp.o and dual_contouring.cpp.o steps.

**Comment by alecjacobson** [comment]
Closed due to inactivity. Please reopen if this is still a problem.
