### ISSUE TITLE
bug during boolean operation

### ISSUE THREAD

**Issue by Davi84** [libigl/libigl#1839]
#### Describe the bug
there is a bug in the intersection implementation. if one object contains the other the output is none (it should be the smaller one).
here is the files to test the bugs:

[scp.zip](https://github.com/libigl/libigl/files/6725193/scp.zip)

here is a test code:
`
import pymesh
import numpy as np

mesh_A = pymesh.load_mesh("a.obj")

mesh_B = pymesh.load_mesh("b.obj")

#output_mesh = pymesh.boolean(mesh_A, mesh_B, operation="intersection", engine="igl")
output_mesh = pymesh.boolean(mesh_A, mesh_B, operation="intersection", engine="cgal")

pymesh.save_mesh("/home/nuorks/data/obj/c.obj", output_mesh);
`

the issue is not in the python implementation (i experienced it using the library itself) but it's easier to isolate the error in this way: if you change the "engine" to "cgal" the operator works properly, so it's not an issue of the input files.

thanks and regards

#### Platform

- [ ] Windows
- [ ] macOS
- [x] Linux

**Comment by sloriot** [comment]
Note that b.obj is not outward oriented, meaning that it represents the whole 3D space minus the tetrahedron. a.obj being inside the tetrahedron but being outward oriented, the intersection is indeed empty. I did not look at how the CGAL' s Nef code is used but most probably input are re-oriented to be outward oriented. When using CGAL Polygon_mesh_processing corefinement based Boolean, you also have an empty intersection.
