### ISSUE TITLE
Multi-thread for ViewerCore::draw_buffer() 

### ISSUE THREAD

**Issue by pham-cong-nguyen** [libigl/libigl#1840]
I try to draw some data instances in data_list via ViewerCore::draw_buffer() functions. To reduce process time, I process multi-thread for function ViewerCore::draw_buffer() with each data instance. But I get "Aborted (core dumped)". So can I multi-thread for draw buffer?

**Comment by jdumas** [comment]
You should only call OpenGL draw functions from the main thread.

**Comment by pham-cong-nguyen** [comment]
I process multiple threads to get each layer (RGBA) of multiple meshes faster. So that, can OpenGL draw do that?

**Comment by jdumas** [comment]
You should have the main threads gather your results and send them to the GPU via OpenGL. You can still spawn calculation on multiple threads, as long as you keep it on the CPU (i.e. no OpenGL).
