### ISSUE TITLE
tetgen's "REAL" definition conflicts with openCV's "REAL"

### ISSUE THREAD

**Issue by xarthurx** [libigl/libigl#1843]
#### Describe the bug
I'm using both libigl and openCV for my project.
When activating the tetgen lib, compiler report errors due to the conflicts described in the title.

**opencv\core.hpp**
![image](https://user-images.githubusercontent.com/1921878/124583808-c8f3ba00-de53-11eb-80fa-25dfbd450be5.png)

**libigl's tetgren wrapper**
![image](https://user-images.githubusercontent.com/1921878/124583851-d610a900-de53-11eb-957c-32c8daf116f5.png)

Actually, the `REAL` defined by tetgen is just `double`.
Is it possible to add some naming space or similar things to constrain it?

In general, how should one resolve conflicts when using different libraries?

Thanks.

#### Platform

- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by jdumas** [comment]
Well this suck. Both TetGen and OpenCV are bad libraries for doing that. One thing I would suggest is to include OpenCV and TetGen in separate compilation units, and write "wrappers" with an explicit interface that does requires a `REAL` type.

**Comment by xarthurx** [comment]
> Well this sucks. Both TetGen and OpenCV are bad libraries for doing that. One thing I would suggest is to include OpenCV and TetGen in separate compilation units, and write "wrappers" with an explicit interface that does requires a `REAL` type.

Since `libigl` is already a wrapper for `tetgen`, it should do this, no?

**Comment by jdumas** [comment]
Nope, because libigl can be used as a header-only library with templated types, there is no way to avoid header pollution. Plus, someone could compile libigl with a float version of TetGen and decide to use the libigl wrapper with it, so there's no way to assume `REAL` is `double` or `float` in advance...

**Comment by xarthurx** [comment]
OK, I understand.
Thank you for the explanation. I'm closing the issue.
