### ISSUE TITLE
display options in additional ViewerData class do not work

### ISSUE THREAD

**Issue by xarthurx** [libigl/libigl#1846]
#### Describe the bug

I have multiple `ViewerData` class existed in one `ViewerCore` that exist in one `Viewer` class.

These multiple `ViewerData` class handles different meshes or isolated lines.

I tried to turn on/off the options that exist in each `ViewerData` class, to control the visibility of those elements, but that does not seem to work. (to be specific: `show_lines`, `show_faces`)

I currently need to clear/reset those data to make the visualization work as expected.

I'm not sure if this is by design or a bug.

#### Platform

- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by jdumas** [comment]
Can you post a minimal example of what you're trying to do?

**Comment by xarthurx** [comment]
Since you've replied to this questions:
https://github.com/libigl/libigl/discussions/1845#discussioncomment-970975

I think I misunderstand the option of `show_lines`...

The suggestion you mentioned in the answer would be great.
