### ISSUE TITLE
Namespace conflicts

### ISSUE THREAD

**Issue by csverma610** [libigl/libigl#185]
Hello,
With boost range iterators included in the project, there are many compilation errors such as. Is there
any quick fix ?

/usr/include/boost/range/iterator.hpp:63:63:   required from ‘struct boost::range_iterator<int* const>’
/usr/include/boost/range/algorithm/nth_element.hpp:61:33:   required by substitution of ‘template<class RandomAccessRange, class BinaryPredicate> const RandomAccessRange& boost::range::nth_element(const RandomAccessRange&, typename boost::range_iterator<const T>::type, BinaryPredicate) [with RandomAccessRange = int*; BinaryPredicate = int*]’
../../../../Software/LibIGL/include/igl/AABB.h:411:60:   required from here
/usr/include/boost/mpl/eval_if.hpp:60:31: error: no type named ‘type’ in ‘boost::mpl::eval_if_c<true, boost::range_const_iterator<int*>, boost::range_mutable_iterator<int* const> >::f_ {aka struct boost::range_const_iterator<int*>}’
     typedef typename f_::type type;

**Comment by alecjacobson** [comment]
I can't tell what's going on here. Are you including igl/AABB.h after
declaring `using namespace boost` in the global scope?
