### ISSUE TITLE
SCAF: ScafData::mesh_measure uninitialized

### ISSUE THREAD

**Issue by RotateMe** [libigl/libigl#1852]
#### Describe the bug
The value `mesh_measure ` in `ScafData` is not initialized, and the only assignment in `scaf.cpp` is `s.mesh_measure += M.sum() / 2;`, which is undefined if the user doesn't initialize `mesh_measure`. 
I noticed this when `scaf_solve` gave me different results in `Debug` and `Release` builds.
In the SCAF tutorial (https://github.com/libigl/libigl/blob/main/tutorial/710_SCAF/main.cpp) `mesh_measure` is not initialized as well.

#### Platform

- [X] Windows
- [X] macOS
- [X] Linux

Thanks for providing this amazing library!

**Comment by jiangzhongshi** [comment]
Thanks! Fixed through #1941
