### ISSUE TITLE
random_points_on_mesh generates not random points

### ISSUE THREAD

**Issue by n-taka** [libigl/libigl#1861]
#### Describe the bug
random_points_on_mesh generates not random points (see the image below).In the image below, I try to sample dense points by using `random_points_on_mesh(V.rows() * 5, V, F, B, FI, X)`.

I inspected this bug on myside, and found that `histc` generates incorrect `FI`. When I use `histc(R,C,N,FI)` within `random_points_on_mesh(V.rows() * 5, V, F, B, FI, X)`, N contains so many `0`.

![image](https://user-images.githubusercontent.com/20333082/126913140-05a14576-4b9b-4bf0-a7ae-d5f3916c51ca.png)

#### Platform
I didn't check macOS and Linux. Perhaps this problem would happen on these platforms.

- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by xarthurx** [comment]
Check this issue: https://github.com/libigl/libigl/issues/808
The output `B` is not very intuitive.
