### ISSUE TITLE
igl/copyleft/cgal/mesh_boolean.h: No such file or directory

### ISSUE THREAD

**Issue by Meganium97** [libigl/libigl#1862]
#### Describe the bug

After compiling from source, and attempting to compile a slicer (superslicer, to be exact), it complains about `igl/copyleft/cgal/mesh_boolean.h: No such file or directory` and when I check, it indeed is not there.
#### Platform

- [ ] Windows
- [ ] macOS
- [ x] Linux

**Comment by alecjacobson** [comment]
Probably an include path problem. This file does indeed exist
https://github.com/libigl/libigl/blob/main/include/igl/copyleft/cgal/mesh_boolean.h

**Comment by Meganium97** [comment]
Do you have any suggestions on what I should do then?

**Comment by jdumas** [comment]
Looks like you should ask the authors of superslicer, as it doesn't seem to be a libigl issue.

**Comment by Meganium97** [comment]
That's the problem; it is. I looked in system files after installing libigl, but did not see the file. igl/copyleft exists, but further from there, copyleft doesn't exist and by extension mesh_boolean.h.

**Comment by Meganium97** [comment]
Alright so I know you guys are going to hate me for this, but just using the version of mesh_boolean.h (and a few other files) provided by the download, I was able to get it working.

**Comment by dbaarda** [comment]
In case anyone else stumbles onto this and is still struggling with it like I was for v2.6.0; I think the cmake setup doesn't install the copyleft headers, even if you have set `LIBIGL_COPYLEFT_CORE`, and (for `mesh_boolean.h`) `LIBIGL_COPYLEFT_CGAL` to `ON`. Setting those adds the build targets, and they get built, but they don't seem to get installed, even with `LIBIGL_INSTALL` set to `ON`.

Digging through all the cmake stuff the only thing that seems to add the install targets is `igl_install()`, and that's only called in one place in `cmake/igl/modules/core.cmake` with `igl_install(igl_core ${INC_FILES} ${SRC_FILES})` where those INC and SRC files only include the core files. The other modules like `cmake/igl/modules/copyleft/core.cmake`  and `cmake/igl/modules/copyleft/cgal.cmake` never call `igl_install()` so never add the install rules to copy all the headers or even compiled libs into the install location.

This means the CMake setup seems to be broken for standalone builds/installs for anything other than core. This includes download/compile/install of it using `ExternalProject_Add()` in your project's CMake setup. In this use-case it also doesn't search for any dependencies with `find_package()` except for `Matlab` (for `igl_restricted::matlab`), `MOSEK` (for `igl_restricted::mosek`), and `BLAS` (for `igl_copyleft::comiso`), and it will always download/compile/install all the others as sub-projects. This means you can't make it use dependencies pre-installed using `ExternalProject_Add()`. You can however trick it into using them by putting this into `LibiglOptions.cmake`, which tickles the mechanism used for finding dependencies as other existing pre-added sub-projects when compiling libigen as a sub-project;

```cmake
# Explicitly select language CXX so that find_package() invoked before
# project() works reliably. In particular, find_package(Threads), which is
# invoked by find_package(CGAL), requires the language to be selected.
enable_language(CXX)

# Find packages already installed by Orcaslicer.
find_package(Boost REQUIRED)
find_package(Eigen3 REQUIRED)
find_package(CGAL REQUIRED)
```

This can make it compile OK as a standalone build using other pre-installed dependencies, but it still doesn't make it install any of the igl modules beyond `igl_core`. At this point I gave up, and just copied the whole include directory into the project I wanted to use igl for to use it as headers-only.

The libigl CMake stuff probably works OK for sub-projects added with `add_subdirectory()`. Note if doing this and you don't `add_subdirectory()` the required dependencies before it, then it will download/add_subdirectory them as sub-projects of itself, which could result in duplicate copy/compile/installs of them unless you just don't add them yourself.
