### ISSUE TITLE
Installation through vcpkg won't build

### ISSUE THREAD

**Issue by svew** [libigl/libigl#1864]
#### Describe your issue

Unsure if this method of installation is supported or not, but I tried installing libigl through vcpkg, but it doesn't seem to be building.

I created a branch new VS project, copied the first piece of code from the tutorial, and got a bunch of conversion errors

```
Build started...
1>------ Build started: Project: Piranesi, Configuration: Debug x64 ------
1>Piranesi.cpp
1>C:\Dev\vcpkg\installed\x64-windows\include\igl\opengl\bind_vertex_attrib_array.cpp(21,35): warning C4244: 'argument': conversion from 'Eigen::Index' to 'GLint', possible loss of data
1>C:\Dev\vcpkg\installed\x64-windows\include\igl\opengl\MeshGL.cpp(150,33): warning C4244: 'argument': conversion from 'Eigen::Index' to 'GLsizei', possible loss of data
1>C:\Dev\vcpkg\installed\x64-windows\include\igl\opengl\MeshGL.cpp(158,44): warning C4244: 'argument': conversion from 'Eigen::Index' to 'GLsizei', possible loss of data
1>C:\Dev\vcpkg\installed\x64-windows\include\igl\opengl\MeshGL.cpp(163,46): warning C4244: 'argument': conversion from 'Eigen::Index' to 'GLsizei', possible loss of data
1>C:\Dev\vcpkg\installed\x64-windows\include\igl\colormap.cpp(1618,40): error C2589: '(': illegal token on right side of '::'
1>C:\Dev\vcpkg\installed\x64-windows\include\igl\colormap.h(47,19): message : This diagnostic occurred in the compiler generated function 'void igl::colormap(const double [][3],const T,T &,T &,T &)'
1>C:\Dev\vcpkg\installed\x64-windows\include\igl\colormap.cpp(1618,40): error C2760: syntax error: unexpected token '(', expected ')'
1>C:\Dev\vcpkg\installed\x64-windows\include\igl\colormap.h(47,19): message : This diagnostic occurred in the compiler generated function 'void igl::colormap(const double [][3],const T,T &,T &,T &)'
1>C:\Dev\vcpkg\installed\x64-windows\include\igl\material_colors.h(16,77): warning C4305: 'initializing': truncation from 'double' to 'const float'
1>C:\Dev\vcpkg\installed\x64-windows\include\igl\material_colors.h(17,77): warning C4305: 'initializing': truncation from 'double' to 'const float'
1>C:\Dev\vcpkg\installed\x64-windows\include\igl\material_colors.h(18,77): warning C4305: 'initializing': truncation from 'double' to 'const float'
1>C:\Dev\vcpkg\installed\x64-windows\include\igl\material_colors.h(23,78): warning C4305: 'initializing': truncation from 'double' to 'const float'

....
```

And yes, I did put my build settings to x64. Is there a reason for this? Or should I just go use CMake?

#### Checklist

- [ X ] I have read the [bug report](https://libigl.github.io/bug-report/) page
- [ ] CMake issue: I have tried with a fresh clone/empty build directory

#### Platform

- [ X ] Windows
- [ ] macOS
- [ ] Linux

**Comment by jdumas** [comment]
I am unfamiliar with the vcpkg for libigl, but it looks like you need to configure your project with NOMINMAX on Visual Studio. Maybe this is an issue that should be reported to the vcpkg maintainers?

**Comment by svew** [comment]
It wasn't a NOMINMAX issue. I'll report it to them, but In the mean time give up and just use CMake ;)
Thanks

**Comment by jdumas** [comment]
What was it then?

**Comment by svew** [comment]
I was never able to get the hundreds of warnings to go away, but searching for the errors found a couple results:

```
1>C:\Dev\vcpkg\installed\x64-windows\include\igl\writeOBJ.cpp(33,21): error C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
```
It also complained about `sscanf` and `fscanf`. I added `#define _CRT_SECURE_NO_WARNINGS` before my libigl includes, and none of the warnings went away, but the errors did, and it was able to compile.

So it turns out not to be a vcpkg issue (I believe), but I'm still going to bug them about adding an option to include CGAL in the configuration (I reeeeally want to use boolean operations)
