### ISSUE TITLE
typo in igl::diag.cpp

### ISSUE THREAD

**Issue by ervaulu** [libigl/libigl#187]
Hi,

I guess there is a small typo in igl::diag.cpp. Line 98 is unnecessary. When looping over non-zero elements, index is increased twice, so only even numbered indices are visited.

Thanks for your work, it is a very useful library.

**Comment by alecjacobson** [comment]
Thanks. Fixed.

(BTW `igl::diag` is deprecated and will soon disappear, see comments in `igl/diag.h`)
