### ISSUE TITLE
not all `per_vertex_normal` overload works for `float` type vertex

### ISSUE THREAD

**Issue by xarthurx** [libigl/libigl#1872]
#### Describe the bug

```
MatrixXf V;
MatrixXi F;
MatrixXf N;

igl::per_vertex_normal(V, F, N);
```
will get error of "mixed different types".

Checking the source code at: 
https://github.com/libigl/libigl/blob/dda197248e855c13bfac3d6e26b80be75e030ea1/include/igl/per_vertex_normals.cpp#L138

Only `double` type template is provided for this overload.

I see that the header file wrotes these templates are auto-generated, perhaps we need to re-run it?

#### Platform

- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by alecjacobson** [comment]
This can happen if you're using libigl in "static-library mode". If the template instantiation isn't already in the library then it won't be found. You can fix this with:

1. Making  a file in your project to compile the missing templates. E.g., `my_templates.cpp` 

```cpp
#ifdef IGL_STATIC_LIBRARY
#undef IGL_STATIC_LIBRARY
#endif
#include <igl/per_vertex_normals.h>
template void igl::per_vertex_normals<Eigen::Matrix<float, -1, -1, 0, -1, -1>, Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<float, -1, -1, 0, -1, -1> >(Eigen::MatrixBase<Eigen::Matrix<float, -1, -1, 0, -1, -1> > const&, Eigen::MatrixBase<Eigen::Matrix<int, -1, -1, 0, -1, -1> > const&, Eigen::PlainObjectBase<Eigen::Matrix<float, -1, -1, 0, -1, -1> >&); 
```

2. Just use libigl in header only mode for your project.

3. Submit a PR containing your missing template to the development branch of libigl
