### ISSUE TITLE
cotmatrix_entries:Bug 

### ISSUE THREAD

**Issue by DemingQiao** [libigl/libigl#1873]
#### Describe the `bug`

`        C(i,0) = (l2(i,1) + l2(i,2) - l2(i,0))/dblA(i)/4.0;`
As we know cos(theta) = (a^ 2 + b^2 - c^2) / (2 * a * b);
so cot(theta) = cos(theta) / sin(theta) = (a^2 + b^2 - c^2) / (2 * a * b * sin(theta) = (a^2 + b^2 - c^2) / (2 * dblA)
I think it should be 2 not 4
#### Platform

- [ ] Windows
- [x] macOS
- [ ] Linux

**Comment by alecjacobson** [comment]
If anything we can update the header to be more accurate. This function is too deeply integrated to change.
