### ISSUE TITLE
Segmentation Fault Running ARAP on my own mesh

### ISSUE THREAD

**Issue by yhu9** [libigl/libigl#1874]
#### Describe your issue
Hello I installed libigl with python bindings using conda and ran the ARAP tutorial just fine. However, I now run into a segmentation fault when I run it on my own 3D mesh.

#### Platform

- [ ] Windows
- [ ] macOS
- [ x] Linux

```
myface = Face3DMM()
s,tex,exp,res,uv = myface.make_3dmm()
v = s.astype(np.float64)
f = myface.tri.astype(np.int64)
b = myface.keypoints.T.astype(np.int64)
print(v.dtype,v.shape)
print(f.dtype,f.shape)
print(b.dtype,b.shape)
# Precomputation
arap = igl.ARAP(v, f, 3, b)
```

float64 (38365, 3)
int64 (76073, 3)
int64 (68, 1)
Segmentation fault (core dumped)

**Comment by kampelmuehler** [comment]
This is in my experience cause if you have any version of `numpy>1.26.4` in your environment.
