### ISSUE TITLE
Compile error in test

### ISSUE THREAD

**Issue by maidamai0** [libigl/libigl#1875]
#### Test compile error

Compile error in file `tests\include\igl\lscm.cpp`:
`V_uv` undeclared identifier

```
assert(V_uv.rows() == nV);
assert(V_uv.cols() == 2);
```

#### Checklist

- [x] I have read the [bug report](https://libigl.github.io/bug-report/) page
- [x] CMake issue: I have tried with a fresh clone/empty build directory

#### Platform

- [x] Windows
- [x] macOS
- [x] Linux

**Comment by Tinuviela** [comment]
I have exactly the same issue. How do I solve it?

**Comment by maidamai0** [comment]
@Tinuviela A workaround is just comment these two lines
