### ISSUE TITLE
loop subdiv crashes

### ISSUE THREAD

**Issue by lilingtongji** [libigl/libigl#1878]
Hi,
file location: ../libigl/include/igl/loop.cpp, line 68
![image](https://user-images.githubusercontent.com/5976399/130385996-5291d6a3-4e47-4690-982d-cf33d6cd231c.png)
as shown in the screenshot above, I tried to print the FF and FFi elements at location i and j, I find that FFi will also contain the anchor number -1 and cause "_NI(FF(i,j), FFi(i,j)) = counter;_" crashes, so I guess do I need to change "if (FF(i,j) != -1)" to "if (FF(i,j) != -1 **&& FFi(i,j) != -1)**"?

**Comment by alecjacobson** [comment]
Maybe @odedstein  remembers

**Comment by odedstein** [comment]
I'm not sure, sorry.

What exactly is the issue that is happening? What are the values of `FF(i,j)` and `FFi(i,j)` for the example that does not work? What is a simple input mesh that causes the crash to happen?

**Comment by alecjacobson** [comment]
I don't think it should ever be the case that `FF(i,j) ≠ -1` but `FFi(i,j) == -1`. Feel free to reopen with more information or a breaking example.
