### ISSUE TITLE
Overlays with multiple meshes

### ISSUE THREAD

**Issue by MotivaCG** [libigl/libigl#1885]
I think that this actually is a bug (most probably) but maybe it could be a design decision.

When you have multiple meshes and they have overlays like points or edges, the meshes with higher index (the index you get when you append a new mesh to the viewport) have higher drawing priority than the other meshes' overlays, even if the overlays have set show_overlay_depth = false, so they are not visible when a mesh with that higher index is over a mesh with a lower one.

Thank you in advance.

**Comment by alecjacobson** [comment]
Ah, yeah. I think that's probably a bug. I'm not going to fix it but would happily merge a pr if someone else did.
