### ISSUE TITLE
std::__1 preventing compilation with gcc

### ISSUE THREAD

**Issue by romp13** [libigl/libigl#189]
There have been some std::__1 left in the explicit template instantiations in 3 files:
include/igl/copyleft/cgal/remesh_intersections.cpp
include/igl/piecewise_constant_winding_number.cpp
include/igl/list_to_matrix.cpp

They need to be removed. Thanks!

**Comment by alecjacobson** [comment]
Thanks, found and fixed. We have a nightly script that catches these, but occasionally they'll be some that get committed until the next day.
