### ISSUE TITLE
Embree compilation fail

### ISSUE THREAD

**Issue by avaxman** [libigl/libigl#1893]
#### Describe your issue
I am trying to compile Directional, which uses the newest version of libigl. However I now get:

** BUILD FAILED **

The following build commands failed:
	PhaseScriptExecution CMake\ Rules embree-download.build/Debug/embree-download.build/Script-103310B0D69542DCBB61A766.sh
(1 failure)
CMake Error at /Users/amirvaxman/Directional/external/libigl/cmake/DownloadProject.cmake:179 (message):
  Build step for embree failed: 65
Call Stack (most recent call first):
  /Users/amirvaxman/Directional/external/libigl/cmake/LibiglDownloadExternal.cmake:25 (download_project)
  /Users/amirvaxman/Directional/external/libigl/cmake/LibiglDownloadExternal.cmake:37 (igl_download_project_aux)
  /Users/amirvaxman/Directional/external/libigl/cmake/LibiglDownloadExternal.cmake:78 (igl_download_project)
  /Users/amirvaxman/Directional/external/libigl/cmake/libigl.cmake:302 (igl_download_embree)
  /Users/amirvaxman/Directional/cmake/FindLIBIGL.cmake:29 (include)
  CMakeLists.txt:32 (find_package)

-- Configuring incomplete, errors occurred!
See also "/Users/amirvaxman/Directional/tutorial/build/CMakeFiles/CMakeOutput.log".

It worked before (say, two weeks ago). I have updated since libigl as follows:

-Subproject commit a2a1479a88373b3324bce8f753212389f1ebc343
+Subproject commit dda197248e855c13bfac3d6e26b80be75e030ea1

#### Checklist

- [X ] I have read the [bug report](https://libigl.github.io/bug-report/) page
- [ X] CMake issue: I have tried with a fresh clone/empty build directory

#### Platform

- [ ] Windows
- [X ] macOS
- [ ] Linux

**Comment by jdumas** [comment]
We have 3 recent PR that affected the embree module:
https://github.com/libigl/libigl/pulls?q=is%3Apr+project%3Alibigl%2Flibigl%2F3+is%3Aclosed

Can you check which one introduced the issue for you?

Also, what version of cmake/clang do you use? Afaik compilation works fine on github for macOS.

**Comment by avaxman** [comment]
Well a fresh download of DIrectional (including libigl) when deleting everything before, solved the issue. I guess there is some leftover when trying to compile over a version before the new PRs?

**Comment by jdumas** [comment]
Yep, that's not uncommon with CMake whenever we update a third-party library I guess...
