### ISSUE TITLE
attempting to reference a deleted function

### ISSUE THREAD

**Issue by changyunjeff** [libigl/libigl#1896]
#### Does someone knows how to solve it?

1>D:\projects\bundlefusion\mlibExternal\include\Eigen\src\Core\SolveTriangular.h(189,11): error C2280: 'Eigen::Block<Eigen::Block<Eigen::Map<Derived,0,Eigen::Stride<0,0>>,-1,-1,false>,-1,-1,false> &Eigen::Block<Eigen::Block<Eigen::Map<Derived,0,Eigen::Stride<0,0>>,-1,-1,false>,-1,-1,false>::operator =(const Eigen::Block<Eigen::Block<Eigen::Map<Derived,0,Eigen::Stride<0,0>>,-1,-1,false>,-1,-1,false> &)': attempting to reference a deleted function
1>D:\projects\bundlefusion\mlibExternal\include\Eigen\src\Core\SolveTriangular.h(189,11): error C2280: 'Eigen::Block<Eigen::Block<Eigen::Map<Derived,0,Eigen::Stride<0,0>>,-1,-1,false>,-1,-1,false> &Eigen::Block<Eigen::Block<Eigen::Map<Derived,0,Eigen::Stride<0,0>>,-1,-1,false>,-1,-1,false>::operator =(const Eigen::Block<Eigen::Block<Eigen::Map<Derived,0,Eigen::Stride<0,0>>,-1,-1,false>,-1,-1,false> &)': attempting to reference a deleted function
1>D:\projects\bundlefusion\mlibExternal\include\Eigen\src\Core\SolveTriangular.h(189,11): error C2280: 'Eigen::Block<Eigen::Block<Eigen::Map<Derived,0,Eigen::Stride<0,0>>,-1,-1,false>,-1,-1,false> &Eigen::Block<Eigen::Block<Eigen::Map<Derived,0,Eigen::Stride<0,0>>,-1,-1,false>,-1,-1,false>::operator =(const Eigen::Block<Eigen::Block<Eigen::Map<Derived,0,Eigen::Stride<0,0>>,-1,-1,false>,-1,-1,false> &)': attempting to reference a deleted function
1>D:\projects\bundlefusion\mlibExternal\include\Eigen\src\Core\SolveTriangular.h(189,11): error C2280: 'Eigen::Block<Eigen::Block<Eigen::Map<Derived,0,Eigen::Stride<0,0>>,-1,-1,false>,-1,-1,false> &Eigen::Block<Eigen::Block<Eigen::Map<Derived,0,Eigen::Stride<0,0>>,-1,-1,false>,-1,-1,false>::operator =(const Eigen::Block<Eigen::Block<Eigen::Map<Derived,0,Eigen::Stride<0,0>>,-1,-1,false>,-1,-1,false> &)': attempting to reference a deleted function
1>D:\projects\bundlefusion\mlibExternal\include\Eigen\src\Core\SolveTriangular.h(189,11): error C2280: 'Eigen::Block<Eigen::Block<Eigen::Map<Derived,0,Eigen::Stride<0,0>>,-1,-1,false>,-1,-1,false> &Eigen::Block<Eigen::Block<Eigen::Map<Derived,0,Eigen::Stride<0,0>>,-1,-1,false>,-1,-1,false>::operator =(const Eigen::Block<Eigen::Block<Eigen::Map<Derived,0,Eigen::Stride<0,0>>,-1,-1,false>,-1,-1,false> &)': attempting to reference a deleted function
1>D:\projects\bundlefusion\mlibExternal\include\Eigen\src\Core\SolveTriangular.h(189,11): error C2280: 'Eigen::Block<Eigen::Block<Eigen::Map<Derived,0,Eigen::Stride<0,0>>,-1,-1,false>,-1,-1,false> &Eigen::Block<Eigen::Block<Eigen::Map<Derived,0,Eigen::Stride<0,0>>,-1,-1,false>,-1,-1,false>::operator =(const Eigen::Block<Eigen::Block<Eigen::Map<Derived,0,Eigen::Stride<0,0>>,-1,-1,false>,-1,-1,false> &)': attempting to reference a deleted function
1>D:\projects\bundlefusion\mlibExternal\include\Eigen\src\Core\SolveTriangular.h(189,11): error C2280: 'Eigen::Block<Eigen::Block<Eigen::Map<Derived,0,Eigen::Stride<0,0>>,-1,-1,false>,-1,-1,false> &Eigen::Block<Eigen::Block<Eigen::Map<Derived,0,Eigen::Stride<0,0>>,-1,-1,false>,-1,-1,false>::operator =(const Eigen::Block<Eigen::Block<Eigen::Map<Derived,0,Eigen::Stride<0,0>>,-1,-1,false>,-1,-1,false> &)': attempting to reference a deleted function
1>D:\projects\bundlefusion\mlibExternal\include\Eigen\src\Core\SolveTriangular.h(189,11): error C2280: 'Eigen::Block<Eigen::Block<Eigen::Map<Derived,0,Eigen::Stride<0,0>>,-1,-1,false>,-1,-1,false> &Eigen::Block<Eigen::Block<Eigen::Map<Derived,0,Eigen::Stride<0,0>>,-1,-1,false>,-1,-1,false>::operator =(const Eigen::Block<Eigen::Block<Eigen::Map<Derived,0,Eigen::Stride<0,0>>,-1,-1,false>,-1,-1,false> &)': attempting to reference a deleted function

**Comment by alecjacobson** [comment]
I don't see anything related to libigl in this message. Feel free to reopen with more information.
