### ISSUE TITLE
Problems integrating libIGL project in a licensed software

### ISSUE THREAD

**Issue by drathin4** [libigl/libigl#1898]
#### Describe your issue

I'm trying to integrate my libIGL project in a licensed software called uDesign and I'm facing CGAL dependency issues. 

One of the issue is that I'm unable to set the variable `CGAL_HEADER_ONLY`. Hence there are compilation issues at line 150 of `libigl\external\cgal\Installation\include\CGAL\config.h` where it tries to fetch `#    include <CGAL/compiler_config.h>`. 
I tried doing `set(CGAL_HEADER_ONLY TRUE)` in the CMakeLists.txt of uDesign software file, but it doesn't help. Also, when I had created a local libIGL project earlier before integrating into uDesign, I found that `CGAL_HEADER_ONLY=1`. That local libIGL project was building correctly and had no CGAL dependency issues. I tried replicating the project's CMakeLists.txt in uDesign's CMakeLists.txt, but somehow it doesn't work.

Error	C1083	Cannot open include file: 'CGAL/compiler_config.h': No such file or directory (compiling source file C:\Rathin\uDesign\MainApp\Src\Module\UIDBTrayGenerate.cpp)	ULab	C:\Rathin\uDesign\libigl\external\cgal\Installation\include\CGAL\config.h	150
C:\Rathin\uDesign\libigl\external\cgal\Installation\include\CGAL/config.h(150,12): fatal error C1083: Cannot open include file: 'CGAL/compiler_config.h': No such file or directory (compiling source file C:\Rathin\uDesign\MainApp\Src\Module\UIDBTrayGenerate.cpp)

Another issue being that I have to include all the subfolders of CGAL in `INCLUDE_DIRECTORIES` line of uDesign's CMakeLists.txt. It looks like this: 

INCLUDE_DIRECTORIES(
	../../libigl/include
	../../libigl/external/eigen
	../../libigl/external/cgal
	../../libigl/external/cgal/AABB_tree/include
	../../libigl/external/cgal/Advancing_front_surface_reconstruction/include
	../../libigl/external/cgal/Algebraic_foundations/include
	../../libigl/external/cgal/Algebraic_kernel_d/include
	../../libigl/external/cgal/Algebraic_kernel_for_circles/include
	../../libigl/external/cgal/Algebraic_kernel_for_spheres/include
	../../libigl/external/cgal/Alpha_shapes_2/include
        ../../libigl/external/cgal/Alpha_shapes_3/include
        .......
        .......
        .......
)

Using just `../../libigl/external/cgal` is resulting in compilation errors. Can you suggest, how to avert this problem ?

Kindly advise how to resolve these issues. Thanks.

#### Checklist

- [x] I have read the [bug report](https://libigl.github.io/bug-report/) page
- [x] CMake issue: I have tried with a fresh clone/empty build directory

#### Platform

- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by alecjacobson** [comment]
Huh. I never tried this CGAL flag. I'm probably not going to try to get this working. It sounds like perhaps a better question for the CGAL folks. If someone wants to submit a PR with it working then happy to merg.
