### ISSUE TITLE
Example 609 not working for cork library

### ISSUE THREAD

**Issue by soodsumil** [libigl/libigl#1899]
#### Describe your issue
Hi
I am using example 609 to perform boolean mesh operations. However I see that the CGAL library is taking a long time to compute the solution. The given example doesn't work as the data used is big and the it takes huge run time for the code to complete. I am not sure if this is expected or it's my system. 
The tutorial says that using cork library is faster and thus I was trying to use it in place of CGAL. I get the following error message:
"""
1>------ Build started: Project: 609_Boolean, Configuration: Debug x64 ------
1>main.cpp
1>C:\libigl\include\igl/copyleft/cork/mesh_boolean.h(13,10): fatal error C1083: Cannot open include file: 'cork.h': No such file or directory
1>Done building project "609_Boolean.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 7 up-to-date, 0 skipped ==========
"""
I am not able to find this cork.h file that's needed. 

The code that I am using is:
"""
`#include <igl/readOFF.h>
#include <igl/writeOFF.h>
//#undef IGL_STATIC_LIBRARY
#include <igl/copyleft/cork/mesh_boolean.h>
#include <igl/opengl/glfw/Viewer.h>

#include <Eigen/Core>
#include <iostream>
#include <chrono>
#include "tutorial_shared_path.h"
using namespace std::chrono;

Eigen::MatrixXd VA,VB,VC;
Eigen::VectorXi J,I;
Eigen::MatrixXi FA,FB,FC;

int main(int argc, char *argv[])
{
  using namespace Eigen;
  using namespace std;
  igl::readOFF(TUTORIAL_SHARED_PATH "/cube1.off",VA,FA);
  igl::readOFF(TUTORIAL_SHARED_PATH "/cylinder1.off",VB,FB);

  auto start = high_resolution_clock::now();
  igl::copyleft::cork::mesh_boolean(VA, FA, VB, FB, "Union", VC, FC);

  auto stop = high_resolution_clock::now();
  auto duration = duration_cast<microseconds>(stop - start);
  std::cout << duration.count() << std::endl;
  igl::writeOFF("union.off", VC, FC);

}
`
The other issue is that the data type "Eigen::MatrixXd " is not accepted for cork. Can you tell me which data type it takes and is there any working example for using cork library here?

#### Checklist

- [x] I have read the [bug report](https://libigl.github.io/bug-report/) page
- [x] CMake issue: I have tried with a fresh clone/empty build directory

#### Platform

- [x] Windows
- [x] macOS
- [x] Linux

**Comment by alecjacobson** [comment]
We're no longer maintaining the cork wrapper. It's here if you still want to try it https://github.com/libigl/libigl-cork

**Comment by mcavazotti** [comment]
Please, update documentation. It mentions cork
