### ISSUE TITLE
Wireframe, Edges, and Isolated Points

### ISSUE THREAD

**Issue by avaxman** [libigl/libigl#19]
Since the linewidth and pointsize parameters become deprecated in new version of OpenGL, their drawing should be replaced, perhaps with small (and configurable) cylinders for edges\segments and spheres for points, with an interface for the user to control sizes.

**Comment by alecjacobson** [comment]
Is glPointSize really deprecated ? 

The [docs](https://www.opengl.org/sdk/docs/man4/html/glPointSize.xhtml) make it seem like it's still a feature in OpenGL 4.5 but to be honest I never know how to tell if an OpenGL feature is deprecated. I just assume if I remember how to spell it then it must be deprecated.

**Comment by avaxman** [comment]
It works really differently on my macbook if connected to a screen or not.

**Comment by alecjacobson** [comment]
weird.... Perhaps its a retina issue? OpenGl be crazy.
