### ISSUE TITLE
flip_avoiding_line_search uses pass by value

### ISSUE THREAD

**Issue by mattoverby** [libigl/libigl#1903]
#### Describe the bug
[flip_avoiding_linesearch](https://github.com/libigl/libigl/blob/579dc0e2a7a441827fb4a33e8cc6fee53725dfb0/include/igl/flip_avoiding_line_search.h) passes the F matrix by value rather than by reference. I assume this is an oopsie.

#### Platform
- [x] Windows
- [x] macOS
- [x] Linux

**Comment by alecjacobson** [comment]
Fixed in https://github.com/libigl/libigl/pull/1968
