### ISSUE TITLE
A typo in README.md

### ISSUE THREAD

**Issue by wucm1994** [libigl/libigl#192]
Hi! There exists a typo In the term 'Projects/Universities using libigl' of README.md.

The Hong Kong University of Science and Technology is not a USA university. **Basically, it is located in Hong Kong, China.**

For more detail, please visit [Wikipedia](https://en.wikipedia.org/wiki/Hong_Kong_University_of_Science_and_Technology)

**Comment by alecjacobson** [comment]
Thanks, fixed.
