### ISSUE TITLE
perhaps invalid vertex normals

### ISSUE THREAD

**Issue by JianqiangDing** [libigl/libigl#1923]
https://github.com/libigl/libigl/blob/fa94bb27e8e0f64340ebb778d609c82c238df980/include/igl/per_vertex_normals.cpp#L104

Hi, I am afraid this may introduce invalid resulting vertex normals, once the norm of some vector is 0, it should be better to provide some default vertex normal like per_face_normal API does.

I think some of you may check this part on your convinent

**Comment by alecjacobson** [comment]
Just to be clear, if one of the rows is zero, this will only affect that row (not the others).

I'm no longer convinced that these normal computation methods should try to handle the degenerate cases, rather they should be handled by the caller. Rationale being that 1) they slow down computation for the common (non-degenerate) case and 2) it's not clear what it means to "catch" these degeneracies. If it's the ==0 case, than nans are easy to catch post-factor. If it's near degeneracy, then there also needs to be a provided tolerance and this starts to sound like a different more elaborate function.

closing for now.
