### ISSUE TITLE
igl_stb_image.h missing

### ISSUE THREAD

**Issue by BBBBBbruce** [libigl/libigl#1937]
Hello, I am trying to save the rendered results to PNG, but the header igl_stb_image.h has gone missing. I saw there is an ongoing update to put PNG module somewhere else. But the library I downloaded from the main branch is still in <igl/png/> where I cannot use it anymore. I wonder could you upload the igl_stb_image.h and the cpp file temporarily, so we could still use the PNG module for now? 

Thanks for the help

**Comment by BBBBBbruce** [comment]
I saw #1712 that I need to build the project with cmake. Since I am using the libigl as an external library, would it be more convenient to have it directly? I guess the concern is that that would require stb. Hmmm, I think putting in the tutorial would come in handy.

**Comment by jdumas** [comment]
As said in the issue, you need to:
1. Enable the CMake option `LIBIGL_WITH_PNG`
2. Delete your CMakeCache.txt and re-configure the project
3. Add the CMake target `igl::png` to your list of dependencies `target_link_libraries(foo PUBLIC igl::png)`

**Comment by BBBBBbruce** [comment]
What I did is 

1. use the default CMake build
1. copy "igl_stb_image_export.h" to the stb folder 
2. copy the stb folder to my own project
3. add stb to C++ additional include diectories.
4. add "igl_stb_image.cpp" to my project

It is a stupid method. but it works for my Visual Studio project.
