### ISSUE TITLE
Changing Black and White Texture Resolution

### ISSUE THREAD

**Issue by stigersh** [libigl/libigl#194]
Hi,
Thanks for your great library, first of all.
I've noticed there's a hard coded black and white texture pattern (R,G,B matrices) which is recreated in the same resolution each time viewer.data.set_mesh is called (size=128). 
Can you please add an option to change the resolution, or in any case, create the defult resolution just once in some "init" function?

**Comment by alecjacobson** [comment]
Happy to take a PR on this, but not going to fix it anytime soon.
