### ISSUE TITLE
Bump Eigen to 3.4

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#1974]
We're currently using Eigen 3.3.7 (Dec 2018). Eigen's newest tagged release 3.4.0 from Aug 2021 has a bunch of nice features. License-wise it's also quite nice that the SimplicialCholesky solvers [have changed from LGPL to MPL2 ](https://gitlab.com/libeigen/eigen/-/commit/1dc1677d525b1df3cc32b3df5cd816e150b07185).

I believe another great feature is slicing as discussed in https://github.com/libigl/libigl/issues/1485. Maybe we should enumerate some great features (reasons to do this besides obviously staying up to date) and any identified problems (we have been burned in the past by Eigen releases containing bugs, but admittedly that was in the distant past and Eigen seems much more stable).

**Comment by jdumas** [comment]
The main benefits to me are as follows:
- Support for __alignas__ for static alignment in C++17, so we don't need to fiddle with EIGEN_MAKE_ALIGNED_OPERATOR_NEW anymore.
- Support for STL iterators in Eigen types.
- Initializer list constructors for matrices/vectors
- Slice/indexed views (`Eigen::seq`)
- Template aliases (`MatrixX<double>`)
