### ISSUE TITLE
viewer: colored edges are lost in wireframe mode

### ISSUE THREAD

**Issue by stigersh** [libigl/libigl#198]
Hi Alec,
Is there a way to show the wireframe of the mesh and color some of the edges, so that the colored edges won't be overridden with the wireframe color? This is what happens when I color edges using viewer.data.add_edges(...)  with the wireframe mode.

Thanks,
Anna

**Comment by alecjacobson** [comment]
There are two hacks for now:

add _all_ edges of the mesh using `viewer.`data.set_edges()` and give them each a color (e.g. default black, selected red). 

set `viewer.core.show_overlay_depth` to false (this will draw all overlay edges on top of the mesh (regardless of depth ordering)

**Comment by stigersh** [comment]
Thanks
