### ISSUE TITLE
Camera Centering

### ISSUE THREAD

**Issue by ryanlukejohns** [libigl/libigl#1984]
#### Describe the bug
Calls to `ViewerCore::align_camera_center` don't alter the camera position after viewer launch.
For example, if you pan/zoom with the mouse in tutorial _106_ViewerMenu_ , and then click "Center object" in the viewing options menu, nothing happens.

Is this the expected behavior?

#### Platform

- [ ] Windows
- [ ] macOS
- [x] Linux

**Comment by alecjacobson** [comment]
This is probably not expected behavior. I'm probably not personally going to work on fixing but if someone else did, I'd be happy to merge a PR.
