### ISSUE TITLE
igl.heat_geodesic produces Error: Numerical issue. Error: invalid solver type

### ISSUE THREAD

**Issue by tlk13** [libigl/libigl#1999]
#### Describe the bug
Hello all, 

I am trying to use igl.point_mesh_squared_distance to calculate distances of my mesh points to polylines that I created beforehand. My code works for certain polylines but for others it inexplicably does not work. 

`_, closest_faces, closest_points = igl.point_mesh_squared_distance(polylines[i], pts, faces)`

This is how I use the function. 

My arguments are: 

`polylines[i]` = Mx3 numpy array, with each point saved in a numpy array of length 3 and encoded as 3 float values 
`pts` = Nx3 numpy array, with each point of the mesh saved in a numpy array of length 3 and encoded as 3 float values 
`faces` = Ex3 numpy array with each edge encoded as 3 integers referring to the points that make up one triangle 

For some polylines, I get good results, such as below: 

<img width="694" alt="Screen Shot 2022-03-09 at 15 25 36" src="https://user-images.githubusercontent.com/36789465/157461139-1844ed3e-1b01-491a-ab40-340a9b1e0107.png">

For others however, there Numerical issue and invalid solver type is raised. The results are as follows: 
<img width="694" alt="Screen Shot 2022-03-09 at 15 25 46" src="https://user-images.githubusercontent.com/36789465/157461252-8f92b2e7-0937-47ec-a329-44d0459faa8f.png">

There is no real difference between the two polylines. They both lie on the surface of the mesh. 

When I apply a transformation on the points as in the above image, such as this: 

`points_simple[:,0] *= 1.4`, occasionally, no error is raised. However, I still do not get the result I want, as the resulting array for the distances is simply filled with NaNs. 

What am I doing wrong, or is the code simply not working?

#### Platform

- [ ] Windows
- [x] macOS
- [ ] Linux

**Comment by alecjacobson** [comment]
could you include the data to reproduce this?

**Comment by tlk13** [comment]
Hi, sorry for not including beforehand. 

Attached a code snippet to illustrate the problem. I accidentally discovered, that it was regarding `igl.heat_geodesic` and not `igl.point_mesh_squared_distance`. 

The problem however is the same: it inexplicably does not accept certain polylines while it accepts others. 

I have uploaded the code snippet and the files here: [Github Link](https://github.com/tlk13/libigl_bug_geodesic)




This is the code: 

```
import igl
import openmesh as om
import numpy as np


mesh = om.read_trimesh("50009_standing_tall.obj")
polyline_pts = np.load("polylines_points.npy", allow_pickle=True)
works = polyline_pts[4]
does_not_work = polyline_pts[9]

_, closest_faces, closest_points = igl.point_mesh_squared_distance(works, mesh.points(), mesh.fv_indices())
added_vhs = []
for j in range(closest_faces.shape[0]):
    vh = mesh.add_vertex(closest_points[j])
    mesh.split(om.FaceHandle(closest_faces[j]), vh)
    added_vhs.append(vh.idx())
added_vhs = np.array(added_vhs, dtype=np.int32)
dists = np.empty((len(mesh.points()), 1))
dists[:, 0] = igl.heat_geodesic(mesh.points(), mesh.fv_indices(), 0.01, added_vhs)
print("it worked")

mesh = om.read_trimesh("50009_standing_tall.obj")
_, closest_faces, closest_points = igl.point_mesh_squared_distance(does_not_work, mesh.points(), mesh.fv_indices())
added_vhs = []
for j in range(closest_faces.shape[0]):
    vh = mesh.add_vertex(closest_points[j])
    mesh.split(om.FaceHandle(closest_faces[j]), vh)
    added_vhs.append(vh.idx())
added_vhs = np.array(added_vhs, dtype=np.int32)
dists = np.empty((len(mesh.points()), 1))
dists[:, 0] = igl.heat_geodesic(mesh.points(), mesh.fv_indices(), 0.01, added_vhs)
print("did not work")
```

**Comment by alecjacobson** [comment]
I'm not sure what 

```python
mesh.split(om.FaceHandle(closest_faces[j]), vh)
```

is doing but it seems to be creating numerically degenerate faces (area ≈ 1e-17).  

The C++ version has a [parameter for using intrinsic delaunay](https://libigl.github.io/dox/structigl_1_1HeatGeodesicsData.html#af2a3bd5c7574b3122c510cb73d9e4bb1) which would _maybe_ be able to deal with these awful triangles, but your best bet would be to do better remeshing to provide a cleaner input mesh.

**Comment by alecjacobson** [comment]
(closing because this is old and likely stale, but feel free to reopen if needed)
