### ISSUE TITLE
Unable to read and write ply files

### ISSUE THREAD

**Issue by MaSiEb** [libigl/libigl#200]
Hi,
every time I want to read or write a ply file (using the functions in igl/readPLY.h and igl/writePLY.h) I get a  "double free or corruption" error.
I believe this is due to fclosing the file twice, once at the end of the ply_close function in ply.h (called from within readPLY/writePLY at the end) and immediately after this in readPLY/writePLY.
Could you include this in your next commit?

**Comment by alecjacobson** [comment]
Thanks for reporting. This is fixed in 
eb0446791b1ba2c0beea66d9f736de982204f5b8

**Comment by meshdgp** [comment]
It is cool



alanzhaohui@seas.harvard.edu
 
From: Alec Jacobson
Date: 2016-01-15 07:58
To: libigl/libigl
Subject: Re: [libigl] Unable to read and write ply files (#200)
Thanks for reporting. This is fixed in 
eb04467
