### ISSUE TITLE
compilation error with example 102

### ISSUE THREAD

**Issue by haltari** [libigl/libigl#2005]
#### Describe your issue
I was trying to compile example 102 to learn about libigl functions. While compiling, I received this 

> error: 'TUTORIAL_SHARED_PATH' was not declared in this scope. 
`igl::readOFF(TUTORIAL_SHARED_PATH "/cube.off", V, F);`

Then, I recieved the following message:

> make[2]: *** [CMakeFiles/tutorial.dir/build.make:76: CMakeFtles/tutorial.dir/main.Cpp.o] Error 1

> make[1]: ***[CMakeFiles/Makefile2:158: CMakeFiles/tutorial.dir/all] Error 2

> make:*** [Makefile: 136: all] Error 2 

and when I run I get this output: 

> IOError: /cube.off could not be opened.

> Vertices:

> Faces:

> tutortal:/home/BU/haltari1/tutorial/build/_deps/libigl-src/include/igl/writeoBJ

> • cpp: 108: bool igl: :writeoBJ(std::string, const Eigen: : MatrixBase«Derived>&, const Eigen::MatrixBase<U>&) [with Derivedv

> =Eigen:: Matrixedouble,-1,-1>; Derive dF = Eigen: :Matrixeint, -1, -1>; std: :string = std::_ cxx11:: basic stringschar>]

> Assertion V.cols() == 3 && "V should have 3 columns"'failed.

> Aborted (core dumped) 

I used the same CMakeLists.txt as in the blank example because I did not find the CMakeLists file in the example folder. 

#### Checklist

- [x] I have read the [bug report](https://libigl.github.io/bug-report/) page
- [x] CMake issue: I have tried with a fresh clone/empty build directory

#### Platform

- [ ] Windows
- [ ] macOS
- [x] Linux

**Comment by jdumas** [comment]
Please compile using the CMakeLists.txt at the root of the repository.

**Comment by alecjacobson** [comment]
If you're on linux the typical thing to do is:

```bash
git clone https://github.com/libigl/libigl/
cd libigl
mkdir build
cd build
# run cmake using CMakeLists.txt located in libigl/
cmake ../
# compile after cmake is done
make 102_DrawMesh
```
