### ISSUE TITLE
Corrupt output in certain large data sets

### ISSUE THREAD

**Issue by GeoTericMickW** [libigl/libigl#2008]
#### Describe the bug
When running igl::qslim() on a regular gridded mesh of approximately 2.5million faces (created from a heightmap) that has quite a lot of flat (all z values equal), the output appears to be corrupt with some faces appearing to stretch off to infinity.  Processing time also increases dramatically when flat faces are present.

In the attached files are the following:
expected.png - the surface visualised with no simplification at all
result.png - the surface after qslim processing with an output target of 2.3 million faces
IGL_Sample.zip - contains the source data in binary format and a CPP main file that will produce the output shown in result.png (written to files, no visualiser)
![expected](https://user-images.githubusercontent.com/51436144/159890441-0c820efe-2a57-4718-98a2-4f69bc7e3102.png)
[IGL_Sample.zip](https://github.com/libigl/libigl/files/8340377/IGL_Sample.zip)
![result](https://user-images.githubusercontent.com/51436144/159890452-cd50a295-9576-4faa-8329-086d167bf7f1.png)

Looking at the output data, it appears that it is only the X values that are problematic.  They are expected to be in the range of 0-1809, but at a quick glance they vary between +- 126000

I hope this is sufficient for you to see the problems that we see.

#### Platform
- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by alecjacobson** [comment]
What's this .bin file format? Would it be possible to upload at .ply or use binary .dmat files that libigl can read?

**Comment by alecjacobson** [comment]
Ah, good to know. I suppose that makes sense because Qslim will conduct many linear system solves and those are probably more accurate with normalized inputs.

**Comment by GeoTericMickW** [comment]
I don't know if you'll want to look into making qslim handle input like this or just close this issue and leave it around for the benefit of other users.  I'm fine with either, I'm happy to move on with the changes we've made to our app.

Thanks for your time.
