### ISSUE TITLE
cut_mesh - deriving seams relation

### ISSUE THREAD

**Issue by stigersh** [libigl/libigl#201]
Hi,
As I understood the input to cut_mesh are which edges should be in the cut. Can you please say if it's possible to derive from the cut mesh result the seams relation, meaning which edges belong to the same seam and to which side of the seam in the cut mesh they belong?

Thanks

**Comment by danielepanozzo** [comment]
Hi,

the faces of the original and cut mesh correspond: the face in the first row of F correspond to the face in the first row of Fcut. Also the edges are in correspondence.You can extract the relationship that you need by using the edge connectivity on the original mesh, and then jumping to the faces of Fcut using the previous relationship.

**Comment by stigersh** [comment]
Thanks.
