### ISSUE TITLE
[CMakeFiles/gmp.dir/build.make:98: _deps/gmp/src/gmp-stamp/gmp-patch] Error 128

### ISSUE THREAD

**Issue by jbs0645** [libigl/libigl#2014]
#### Describe the bug

I **build all the examples in the tutorial** in ubuntu 21.10 follow these:
```
git clone https://github.com/libigl/libigl.git
cd libigl/
mkdir build
cd build
cmake ../
make
```
But when I conduct the  `make` command, I encounted the error like this:

```

[  0%] Built target predicates
[ 43%] Built target igl_core
[ 44%] Built target igl_predicates
[ 45%] Built target test_igl_predicates
[ 47%] Built target Boost_system
[ 47%] Built target igl_copyleft_core
[ 47%] Performing patch step for 'gmp'
error: can't open patch 'build/_deps/gmp/src/gmp/CONFIGURE_HANDLED_BY_BUILD': No such file or directory
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11061    0 11061    0     0   6419      0 --:--:--  0:00:01 --:--:--  6415
curl: (23) Failed writing body (0 != 11061)
make[2]: *** [CMakeFiles/gmp.dir/build.make:98: _deps/gmp/src/gmp-stamp/gmp-patch] Error 128
make[1]: *** [CMakeFiles/Makefile2:1920: CMakeFiles/gmp.dir/all] Error 2
make: *** [Makefile:163: all] Error 2_
```

#### Platform

- [ ] Windows
- [ ] macOS
- [x] Linux

**Comment by jbs0645** [comment]
I guess it come from the **gmp** package, do I need to preinstall it before the `cmake ../`?

**Comment by alecjacobson** [comment]
no, this is supposed to be downloading and installing gmp when you do `cmake ..`

**Comment by jbs0645** [comment]
I check the folds `**build/_deps/gmp/src/gmp/**` just now, the `**CONFIGURE_HANDLED_BY_BUILD**` file **_does not exist_**

**Comment by alecjacobson** [comment]
I don't know that it should exist... it seems like something got mangled.

**Comment by alecjacobson** [comment]
What version of cmake do you have?

Could you try redoing everything from scratch? Does it still occur?

**Comment by jbs0645** [comment]
I'll try again. Thank you for the kind help. @alecjacobson

**Comment by jbs0645** [comment]
my **`cmake`** version is 3.16.3

**Comment by alecjacobson** [comment]
I'm not sure if it would be the issue, but you could try upgrading your
cmake.

**Comment by jbs0645** [comment]
It's **work**!  Thank you! @alecjacobson

**Comment by jdumas** [comment]
@alecjacobson it looks like this line:
https://github.com/libigl/libigl/blob/c98c375270eedbecdf5a15c352ea0a8fc3ffce40/cmake/recipes/external/gmp.cmake#L30
refers to a CMake option that was introduced in CMake 3.20:
https://cmake.org/cmake/help/latest/module/ExternalProject.html

Should we bump our required version?

**Comment by alecjacobson** [comment]
Is there a way to add this only if cmake is new enough? It's not always easy for users to upgrade cmake and this is not a crucial feature.

**Comment by jdumas** [comment]
Yes you can do something like
```cmake
if(${CMAKE_VERSION} VERSION_LESS 3.20)
    # CMake < 3.20, do not use any extra option
    set(extra_options) 
else()
    # CMake >= 3.20
    set(extra_options CONFIGURE_HANDLED_BY_BUILD)
endif()

ExternalProject_Add(gmp
    ...
    ${extra_options}
)
```
