### ISSUE TITLE
principle_curvature "Could not compute curvature" on STL file

### ISSUE THREAD

**Issue by jochemspek** [libigl/libigl#202]
hi,

When I try to perform 'principal_curvature' on the bunny file, that was converted 
from the .off file format to .stl using meshlab, I consistently get

Could not compute curvature of radius 0.0233055
Segmentation fault: 11

it works fine when using it on the original bunny.off file.
I can't find anything (obviously) wrong with the stl though.

Could anyone shed some light on this ? I'm bound using stl files..

thanks,

Jonathan

**Comment by alecjacobson** [comment]
Probably the stl file is being read in as a collection of unconnected
triangles. Try calling `igl::remove_duplicate_vertices` first

**Comment by jochemspek** [comment]
That was it indeed ! Thank you very much !
