### ISSUE TITLE
EXAMPLE 106 menu doesn't work as expected

### ISSUE THREAD

**Issue by sould628** [libigl/libigl#2020]
#### Describe the bug

Menu is drawn fine. When mouse is clicked on the menu, does nothing and any mouse click wouldn't  respond.
If view is rotated with mouse clicks, menu is dead zone. (even dragging scroll isn't working)

also igl/opengl/glfw/imgui/imGuiPlugin.cpp
require in line 16
#include <imgui_fonts_droid_sans.h>

but "imgui_fonts_droid_sans.h" is missing from master branch

#### Platform

- [x ] Windows
- [ ] macOS
- [ ] Linux

**Comment by asdMild** [comment]
try use imgui-1.86 , higher version change something

**Comment by cjz37** [comment]
I have used the latest version of ImGui's master branch, but I still have this problem.
