### ISSUE TITLE
Getting a very large number of hits on ray_mesh_intersect

### ISSUE THREAD

**Issue by ehedlin** [libigl/libigl#2025]
#### Describe the bug
When I run the ray_mesh_intersect algorithm on the attached mesh with the given ray and origin I get 3048 hits, however, when I run the mesh on my (much slower) algorithm I get only 1 intersect. Am I running the function incorrectly or maybe interpreting the returned hits incorrectly?

example inputs:
[function_inputs.zip](https://github.com/libigl/libigl/files/8499168/function_inputs.zip)

#### Platform

- [ ] Windows
- [ ] macOS
- [x] Linux

**Comment by alecjacobson** [comment]
could you please include the program that you're running to reproduce your error?

**Comment by ehedlin** [comment]
```
import igl
import numpy as np

ray_origins = np.load("ray_origins.npy")
ray_directions = np.load("ray_directions.npy")
mesh_verts = np.load("mesh_verts.npy")
mesh_faces = np.load("mesh_faces.npy")
hits = igl.ray_mesh_intersect(ray_origins, ray_directions, mesh_verts, mesh_faces)
print(len(hits))
```

This prints 3048. Is that not the number of hits?

**Comment by GDCCP** [comment]
I load a ply with read_triangle_mesh and these are x,y,z min/max for my vertices:
array([-0.74707031, -0.74707037, -1.19707072]), array([0.56193352, 0.11686674, 0.17213203])

So when I do
igl.ray_mesh_intersect(np.asarray([0,10,25],dtype=np.float32),np.asarray([0,0,1],dtype=np.float32),*mesh)

I have over 10k hits. The first one is:
(287365, -1, -0.0, 1.0, 1.0842021724855044e-19)
and the last one is:
(130355, -1, 1.0, -0.0, 3.6893488147419103e+19)

(0,10,25)+ t*(0,0,1) doesn't seem to be the right position for both listed. I am actually expecting empty results(no hits). Am I missing some assumption on how ray_mesh_intersect should be used?

I am doing this with python, so need more efforts to have a c++ debug build. Just log this for now.

**Comment by alecjacobson** [comment]
Are you compiling the most recent version? Or using the one on conda?

**Comment by GDCCP** [comment]
> Are you compiling the most recent version? Or using the one on conda?

conda on ubuntu.

**Comment by ehedlin** [comment]
> > Are you compiling the most recent version? Or using the one on conda?
> 
> conda on ubuntu.

Same here. And when visualizing the points it shows that they are not in a line.

**Comment by alecjacobson** [comment]
I think this was fixed. Please retry with the `pip install libigl` version and reopen if necessary.
