### ISSUE TITLE
How to disable CGAL?

### ISSUE THREAD

**Issue by wguo68** [libigl/libigl#203]
I want to disable CGAL because there are  compile errors :

10>e:\dev\libigl\include\igl\cgal\CGAL_includes.hpp(17): fatal error C1083: Cannot open include file: 'CGAL/intersections.h': No such file or directory (compiling source file E:\dev\libigl\include\igl\cgal\mesh_to_cgal_triangle_list.cpp)

**Comment by alecjacobson** [comment]
You can't use the igl::copyleft::cgal code without cgal... Also seems like
you're using a very old libigl
