### ISSUE TITLE
GLVerion not available on windows 

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#2032]
https://github.com/libigl/libigl/blob/2869f9862926ef6e6acc5e2fa0b51f8fd165e22f/include/igl/opengl/glfw/Viewer.cpp#L187

I have a fragile windows set up for testing. Would be nice to have someone confirm this is an issue (in debug mode).

**Comment by jdumas** [comment]
What is the issue here?

**Comment by hjforsythe-rlp** [comment]
Recurring issue: "GLVersion undeclared identifier" is still unresolved for windows

**Comment by lukkio88** [comment]
Having the same issue myself now... was this solved?

**Comment by alecjacobson** [comment]
@lukkio88 you could try replacing that offending line with @monkeygame 's 
```
glGetIntegerv(GL_MAJOR_VERSION, &major); glGetIntegerv(GL_MINOR_VERSION, &minor); printf("OpenGL Version %d.%d loaded\n", major, minor);
```
maybe that fixes it. I believe this is some issue with GLAD on Windows that doesn't seem to happen elsewhere.
