### ISSUE TITLE
Python binding `read_obj` func returns "file not found" error while "read_triangle_mesh" works well

### ISSUE THREAD

**Issue by sebderhy** [libigl/libigl#2034]
#### Describe the bug
I'm using the python bindings.
When I run `igl.read_triangle_mesh(path_to_my_obj)`, I successfully read the V and F matrices.
However, when I run `igl.read_obj(path_to_my_obj)`, I get the following error:
`ValueError: File 'my/path/to/obj_file.obj' not found.`

#### Platform

- [ ] Windows
- [ ] macOS
- [x ] Linux

**Comment by alecjacobson** [comment]
huh. I cannot reproduce this. Is it still happening?
