### ISSUE TITLE
Error in building igl library, related to gmp library package

### ISSUE THREAD

**Issue by Aref-Hemati** [libigl/libigl#2048]
#### Describe your issue

I faced an error in building Igl library. After a successful cmake, when I call make (in build folder).

```
[ 69%] Performing patch step for 'gmp'
/bin/sh: 1: curl: not found
error: unrecognized input
make[2]: *** [CMakeFiles/gmp.dir/build.make:121: _deps/gmp/src/gmp-stamp/gmp-patch] Error 128
make[1]: *** [CMakeFiles/Makefile2:1843: CMakeFiles/gmp.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
aref@aref-GE60-2OC-2OD-2OE:~/Downloads/Sample3/libigl/build$ 
```

#### More Details:
(for the first run "make", it downloaded the required packages and got an error :)
![Screenshot from 2022-05-28 13-40-15](https://user-images.githubusercontent.com/32439156/170820653-6e1b39fa-f2cd-46b6-a434-158b68ff1473.png)
[first-run-make.txt](https://github.com/libigl/libigl/files/8790926/first-run-make.txt)

(after the first "make" and get an error, when I  "make" for the second time)
![Screenshot from 2022-05-28 13-52-21](https://user-images.githubusercontent.com/32439156/170820683-71b1e1e3-8839-4b4d-8f17-c3b146b795e0.png)
[second-run-make.txt](https://github.com/libigl/libigl/files/8790927/second-run-make.txt)

#### Note
I use ubuntu x86_64 and I've also installed these three packages:
```
$ sudo apt update
$ sudo apt install libmpfr-dev
$ sudo apt-get install libgmp3-dev
$ sudo apt-get install libboost-all-dev
```
#### Checklist

- [ ] I have read the [bug report](https://libigl.github.io/bug-report/) page
- [ x] CMake issue: I have tried with a fresh clone/empty build directory

#### Platform

- [ ] Windows
- [ ] macOS
- [ x ] Linux

**Comment by alecjacobson** [comment]
Could you try sudo apt-get install curl ? It's surprising to me that it
can't find curl.

**Comment by Aref-Hemati** [comment]
Thank you, dear Alec, the problem was the missing Curl library, and the build process was completed successfully after installation.
