### ISSUE TITLE
Using CGAL and mesh_boolean compilation error

### ISSUE THREAD

**Issue by derekkkzhang** [libigl/libigl#2054]
Hi,

I am trying to use Libigl with CGAL for a mesh boolean operation. Then I realize whenever I include the boolean header file <igl/copyleft/cgal/mesh_boolean.h>, regardless of the implementation of the functions, the program gives me warning as is shown in the screenshots.

My project is based on the libigl-exmaple-project with CGAL enabled by adding "option(LIBIGL_COPYLEFT_CGAL "Build target igl_copyleft::cgal" ON)" in the CMakeLists.txt. I am also not sure if this is the right way of building the example project with CGAL.

I really appreciate if there could be any help with the error messages. Thanks in advance~

![image](https://user-images.githubusercontent.com/56820401/176371010-c3d3faab-2c55-4468-890d-3df508aefe75.png)

![image](https://user-images.githubusercontent.com/56820401/176371102-04c0f471-30af-4615-9ee7-2dae5ceb4ecd.png)

#### Checklist

- [x] I have read the [bug report](https://libigl.github.io/bug-report/) page
- [x] CMake issue: I have tried with a fresh clone/empty build directory

#### Platform

- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by alecjacobson** [comment]
are you able to build the main libigl project with cgal ? I have a feeling this is not installing the gmp/mpfr dependencies correctly.

**Comment by derekkkzhang** [comment]
@alecjacobson Hi Alec,
Thank you for the reply. I also get error messages about mpfr.h when building the main project.

I can see the gmp-src and mpfr-src folders under libigl/build/_deps. All I did was to build the main project via CMake from the root folder (CGAL headers cgal-src/include/CGAL already built by default). Could you give a bit more hints about how to build the gmp/mpfr correctly? 

![image](https://user-images.githubusercontent.com/56820401/176502878-fabad09c-9b77-4ba3-90ee-88d87867ce84.png)

**Comment by alecjacobson** [comment]
I do know that is possible to build on Windows. (Our continuous integration build is successful https://github.com/libigl/libigl/blob/3370a3e9caab4708e02f00a5ae34f6aaba27a428/.github/workflows/continuous.yml#L137 )

Are you using a modern VS? Is it possible for you to retrace the steps in https://github.com/libigl/libigl/blob/3370a3e9caab4708e02f00a5ae34f6aaba27a428/.github/workflows/continuous.yml locally and see if you can build that way?

**Comment by derekkkzhang** [comment]
@alecjacobson Hi Alec,

My build is successful on Windows + VS2019 + Libigl main project now. I got the issue solved by downloading MPFR library from the official website and edit VS2019 project C++ dependencies to the new mpfr.h file. 

I know libigl download those dependent libraries automatically, but my build errors all come from mpfr.h as shown in the picture above, so I have to download a new one. This issue might be specific to my computer only.

Thanks for your help!
