### ISSUE TITLE
Fixed: mex example doesn't compile

### ISSUE THREAD

**Issue by orlitany** [libigl/libigl#206]
the mex example: compileMEX.m doesn't compile. I changed the readOBJ_mex.cpp file as following (notice the *matlab* addition after igl).

// Return the matrices to matlab
  switch(nlhs)
  {
    case 2:
      igl::matlab::prepare_lhs_index(F,plhs+1);
    case 1:
      igl::matlab::prepare_lhs_double(V,plhs);
    default: break;
  }

**Comment by alecjacobson** [comment]
Thanks, fixed.
