### ISSUE TITLE
exception throwed when user defined properties are not same type.

### ISSUE THREAD

**Issue by fabyday** [libigl/libigl#2064]
#### Describe the bug
Hi, I found some bug in readPLY

in most of ply files, working well. but in some kind of files. it may not be worked as I expected.

I think this may be intended features but, I feel it need to report.

I used dataset http://grail.cs.washington.edu/projects/stfaces/data/.

it has user defined property( unfortunately it is not ASCII) looks like below.
```
.
.
. 
//user defined vertex property.
property float  confidence 
property int diffuse_red 
property int diffuse_green
property int diffuse_blue
.
.
.
```

But they are not same types. so exception throwed  __in tinyply 587 line__.
(In my opinion, this may be valid.)

I tested this code
```
#include <igl/read_triangle_mesh.h>
int main(){
Eigen::MatrixXd V; Eigen::MatrixXi F;
igl::read_triangle_mesh("YOUR_PATH/data.ply", V,F)
}
```

#### Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

**Comment by alecjacobson** [comment]
I guess this is a tinyply issue. If it gets fixed upstream we could try to merge. I'm not personally going to fix this, happy to merge a pr if others do.
