### ISSUE TITLE
problem about building igl_copyleft_cgal.lib 

### ISSUE THREAD

**Issue by echo-hi** [libigl/libigl#2075]
#### Describe your issue
I want to run the tutorial 609 ,but I failed to build igl_copyleft_cgal.lib after running the cmake of libigl.
here is the error to buld the igl_copyleft_cgal.lib:
![image](https://user-images.githubusercontent.com/55911430/187186196-bb745fa5-77ff-4cf1-b7da-324be5949b1f.png)

it could build the lib after i comment the code :
auto* pet = new typename Lazy_exact_nt_rep<ET>::Indirect(cste); this->keep_at(pet); this->set_ptr(pet);
but the lib would occur error when i test the tutorial 609

#### Checklist

- [x] I have read the [bug report](https://libigl.github.io/bug-report/) page
- [x] CMake issue: I have tried with a fresh clone/empty build directory

#### Platform

- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by alecjacobson** [comment]
Could you please provide a minimal example of a program that causes this issue?

**Comment by echo-hi** [comment]
i have solved this in linux , thank you
