### ISSUE TITLE
libigl failed to build with "error C2143: syntax error: missing ')' before 'const'" with MSVC on Windows arm64ec

### ISSUE THREAD

**Issue by YangYang129** [libigl/libigl#2077]
libigl failed to build with "error C2143: syntax error: missing ')' before 'const'" with MSVC on Windows arm64ec. It can reproduce on latest version on master branch. Could you please help look at this issue?
**Versions and configuration**
OS: Windows Server 2022 Datacenter
VS: Visual Studio 2019(16.11.18)
**Repro steps:**
1. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=arm64
2. git clone https://github.com/libigl/libigl F:\libigl
3. cd F:\libigl
4. mkdir build_arm64ec &cd build_arm64ec
5. cmake -G "Visual Studio 16 2019" -A ARM64EC -DCMAKE_SYSTEM_VERSION=10.0.22618.0 -DCMAKE_BUILD_TYPE=Release -DLIBIGL_BUILD_TESTS=OFF -DLIBIGL_PNG=OFF -DLIBIGL_BUILD_TUTORIALS=OFF  ..
6. msbuild /m /p:Platform=ARM64EC /p:Configuration=Release /p:BuildInParallel=true libigl.sln /t:Rebuild >msbuild.log

**Error info:**
Line  815:     39>F:\libigl\include\igl\FastWindingNumberForSoups.h(1116,22): error C2143: syntax error: missing ')' before 'const' (compiling source file F:\libigl\include\igl\fast_winding_number.cpp) [F:\libigl\build_arm64ec\igl_core.vcxproj]
	Line  821:     39>F:\libigl\include\igl\FastWindingNumberForSoups.h(1116,22): error C2660: '__S128': function does not take 0 arguments (compiling source file F:\libigl\include\igl\fast_winding_number.cpp) [F:\libigl\build_arm64ec\igl_core.vcxproj]
	Line  839:     39>F:\libigl\include\igl\FastWindingNumberForSoups.h(1116,22): error C2059: syntax error: 'const' (compiling source file F:\libigl\include\igl\fast_winding_number.cpp) [F:\libigl\build_arm64ec\igl_core.vcxproj]
	Line  842:     39>F:\libigl\include\igl\FastWindingNumberForSoups.h(1116,22): error C2059: syntax error: ')' (compiling source file F:\libigl\include\igl\fast_winding_number.cpp) [F:\libigl\build_arm64ec\igl_core.vcxproj]
	Line  846:     39>F:\libigl\include\igl\FastWindingNumberForSoups.h(1116,53): error C2143: syntax error: missing ';' before '{' (compiling source file F:\libigl\include\igl\fast_winding_number.cpp) [F:\libigl\build_arm64ec\igl_core.vcxproj]
	Line  850:     39>F:\libigl\include\igl\FastWindingNumberForSoups.h(1116,53): error C2447: '{': missing function header (old-style formal list?) (compiling source file F:\libigl\include\igl\fast_winding_number.cpp) [F:\libigl\build_arm64ec\igl_core.vcxproj]
	Line  859:     39>F:\libigl\include\igl\FastWindingNumberForSoups.h(1125,22): error C2143: syntax error: missing ')' before 'const' (compiling source file F:\libigl\include\igl\fast_winding_number.cpp) [F:\libigl\build_arm64ec\igl_core.vcxproj]
	Line  870:     39>F:\libigl\include\igl\FastWindingNumberForSoups.h(1125,22): error C2660: '__S128': function does not take 0 arguments (compiling source file F:\libigl\include\igl\fast_winding_number.cpp) [F:\libigl\build_arm64ec\igl_core.vcxproj]
	Line  884:     39>F:\libigl\include\igl\FastWindingNumberForSoups.h(1125,22): error C2059: syntax error: 'const' (compiling source file F:\libigl\include\igl\fast_winding_number.cpp) [F:\libigl\build_arm64ec\igl_core.vcxproj]
	Line  889:     39>F:\libigl\include\igl\FastWindingNumberForSoups.h(1125,22): error C2059: syntax error: ')' (compiling source file F:\libigl\include\igl\fast_winding_number.cpp) [F:\libigl\build_arm64ec\igl_core.vcxproj]
	Line  890:     39>F:\libigl\include\igl\FastWindingNumberForSoups.h(1125,53): error C2143: syntax error: missing ';' before '{' (compiling source file F:\libigl\include\igl\fast_winding_number.cpp) [F:\libigl\build_arm64ec\igl_core.vcxproj]
	Line  894:     39>F:\libigl\include\igl\FastWindingNumberForSoups.h(1125,53): error C2447: '{': missing function header (old-style formal list?) (compiling source file F:\libigl\include\igl\fast_winding_number.cpp) [F:\libigl\build_arm64ec\igl_core.vcxproj]

**Error log:**
[libigl_msbuild.log](https://github.com/libigl/libigl/files/9488962/libigl_msbuild.log)

**Comment by alecjacobson** [comment]
I don't have access to the same setup to try this so I can't really help out. Perhaps this is related to intrinsics that fast winding number uses. I think we made this optional now so perhaps it's all good now. Feel free to reopen with more info if it's still not working.
