### ISSUE TITLE
GMP Error in CMake.

### ISSUE THREAD

**Issue by avaxman** [libigl/libigl#2078]
I am getting: during cmake:

"
-- Third-party: creating target 'gmp::gmp'
CMake Error at build/_deps/libigl-src/cmake/find/FindGMP.cmake:17 (find_path):
  Could not find GMP_INCLUDES using the following files: gmp.h
Call Stack (most recent call first):
  build/_deps/libigl-src/cmake/recipes/external/gmp.cmake:11 (find_package)
  build/_deps/libigl-src/cmake/recipes/external/cgal.cmake:36 (include)
  build/_deps/libigl-src/cmake/recipes/external/cgal.cmake:58 (cgal_import_target)
  build/_deps/libigl-src/cmake/igl/modules/copyleft/cgal.cmake:17 (include)
  build/_deps/libigl-src/cmake/igl/igl_include.cmake:32 (include)
  build/_deps/libigl-src/cmake/igl/igl_include.cmake:40 (_igl_include_full)
  build/_deps/libigl-src/cmake/libigl.cmake:26 (igl_include_optional)
  build/_deps/libigl-src/CMakeLists.txt:142 (include)
"

I saw that this was changed quite recently? Maybe something broke. This is through commandline cmake or macOS Monterey which is a MacBook air M1 2020.

#### Checklist

- [ ] I have read the [bug report](https://libigl.github.io/bug-report/) page
- [ ] CMake issue: I have tried with a fresh clone/empty build directory

#### Platform

- [ ] Windows
- [X ] macOS
- [ ] Linux

**Comment by avaxman** [comment]
ok nvm. Apparently the new(ish) macs don't install GMP or MPFR by default.

**Comment by jdumas** [comment]
Which version of libigl are you using? In the latest branch, there is no `find_package(gmp)` on `gmp.cmake:11`. The code will download and compile GMP on its own:
https://github.com/libigl/libigl/blob/3ea7f9480967fcf6bf02ce9b993c0ea6d2fc45f6/cmake/recipes/external/gmp.cmake#L11

**Comment by avaxman** [comment]
hmmm I have GIT_TAG v2.4.0. I closed the issue since I just installed GMP on my computer and it worked. But I should have updated the version?
