### ISSUE TITLE
OpenMP critical mac m1

### ISSUE THREAD

**Issue by danilaabramov** [libigl/libigl#2087]
#include <cstdio>
#include <omp.h>
#define nMAX 820000
#define tNUM 8
int main() {
    omp_set_num_threads(tNUM);
    int i, j, Q = 15;
    float sum;
    float *a = static_cast<float *>(malloc(nMAX * sizeof(float)));
    for (i = 0; i < nMAX; ++i) a[i] = 1;
    double start, end, total = 0;
    for (int k = 0; k < 12; ++k) {
        sum = 0;
        start = omp_get_wtime();
#pragma omp parallel for private(i, j) shared(a, sum, Q) default(none)
        for (i = 0; i < nMAX; ++i) {
            for (j = 0; j < Q; j++) {
#pragma omp critical
                sum = sum + a[i];
            }
        }
        sum /= (float) Q;
        end = omp_get_wtime();
        total += end - start;
    }
    printf("\n Critical Q: %d", Q);
    printf("\n Sum = %10.2f", sum);
    printf("\n Time = %f \n", total / 12);
    free(a);
    return 0;
}

#### Describe the bug

The more threads, the longer the running time, does not parallel, please help
#### Platform

- [x] macOS

**Comment by alecjacobson** [comment]
This does not appear to be related to libigl
