### ISSUE TITLE
715_MeshImplicitFunction sample  is outdated

### ISSUE THREAD

**Issue by FrankEscobar** [libigl/libigl#2088]
#### Describe the bug
I'm not sure if this should be consider a bug, but it is not a request or something like that too, since it works but it is not correct either.

715_MeshImplicitFunction sample has in its code:

` printf("  %5f secs dual contouring\n",t_Gf+tictoc());
      // Could use igl::marching_cubes once
      // https://github.com/libigl/libigl/pull/1687 is merged
      tictoc();
      igl::copyleft::marching_cubes(Gf,GV,GI,mcV, mcF);
      printf("  %5f secs marching cubes\n",t_Gf+tictoc());`

Since that branch has been merged probably that code should be updated to use igl::marching_cubes

**Comment by alecjacobson** [comment]
Oh right. Yeah, we should merge that in and then close this issue with a fix. (Happy to merge a PR if you do it).
