### ISSUE TITLE
Crash on signed_distance function

### ISSUE THREAD

**Issue by FrankEscobar** [libigl/libigl#2089]
#### Describe the bug

signed_distance triggers a crash that can be reproduced on 705_MarchingCubes sample with this mesh https://we.tl/t-lDMQHyxOjV

the mesh contains vertices but no faces (point cloud) and voxel_grid seems to be generated properly or at least it doesn't trigger any exception.

#### Platform

- [x] Windows
- [ ] macOS
- [ ] Linux

Thank you for your time

**Comment by alecjacobson** [comment]
705_MarchingCubes is set up for surface meshes. For a point cloud you could compute (unsigned) distance and use a marching cubes to extract the level-set of distance == σ > 0. Take a look at AABB.h to see how to call it for a point cloud, but you'll need to change main.cpp a bit, too.

**Comment by alecjacobson** [comment]
( I guess we could add an assertion to signed_distance to check for 0 faces; I'd merge a PR but probably won't get around to it myself)

**Comment by alecjacobson** [comment]
I probably assumed incorrectly what your input and output is. Could you try to state it again?

**Comment by FrankEscobar** [comment]
Sure, in brief I'm trying to mimic the function of Unreal 5.1 for meshing point clouds.

Instead of using any technique like Poisson Reconstruction they use a rough one that looses high frequencies on the geometry (like wringles and so) but it doesn't create bulbs on holes like doors and so.

In their code they split that in 3 steps:

- It creates an octree partition.
- Transforms that to voxel grid.
- Marching cubes algorithm over that voxel grid.

I think that probably they are taking advance of consider the point normal instead of the position only.


Thank you.

**Comment by alecjacobson** [comment]
I'm not totally sure the best way to go. Another route would be to use unsigned distance to the points + fast winding number for the signing. 

I'm going to close this as an issue for book-keeping. Feel free to open a discussion under an appropriate title to continue.
