### ISSUE TITLE
I can't success compile libigl tutorials in VS2015

### ISSUE THREAD

**Issue by wguo68** [libigl/libigl#209]
I want to static link all depended libraries so that I don't need to ship with the application DLL files.
But I failed to do all the time.  Is my setting right in CMAKE?

![embree](https://cloud.githubusercontent.com/assets/4994038/12480177/6c0cbd6a-c07b-11e5-9603-2d3502178444.jpg)

**Comment by alecjacobson** [comment]
You want to build embree statically? I have no idea how to do that. Try asking the embree folks
