### ISSUE TITLE
Compilation fails on Linux for 102_Drawmesh_bin

### ISSUE THREAD

**Issue by Namdhari** [libigl/libigl#210]
Environment:
-----------------
Linux Ubuntu 14.04 LTS

libigl commit history :
4c50610 matlab namespace
eb04467 double free on ply read/write
f6ae496 better doc
0edbd05 std __1
7da9a55 omp error

Error Log:
-------------
$ make all

======== log starts ==========
[ 14%] Building CXX object 102_DrawMesh/CMakeFiles/102_DrawMesh_bin.dir/main.cpp.o
cd /home/sukhraj/Projects/Acads/MSProject/libigl/tutorial/tut-build/102_DrawMesh && /usr/bin/c++   -DIGL_NO_OPENGL -DIGL_OPENGL_4 -DTUTORIAL_SHARED_PATH=\"/home/sukhraj/Projects/Acads/MSProject/libigl/tutorial/shared\" -std=c++11 -DTETLIBRARY -DTRILIBRARY -DANSI_DECLARATORS -DANSI_DECLARATORS -std=c++11 -fopenmp -march=native -std=c++11 -Wno-deprecated-register -I/home/sukhraj/Projects/Acads/MSProject/libigl/external/nanogui/ext/glew/include -I/usr/include/eigen3 -I/home/sukhraj/Projects/Acads/MSProject/libigl/external/nanogui/ext/glfw/include -I/usr/local/include -I/opt/local/include -I/home/sukhraj/Projects/Acads/MSProject/libigl/tutorial -I/home/sukhraj/Projects/Acads/MSProject/libigl/tutorial/../include    -o CMakeFiles/102_DrawMesh_bin.dir/main.cpp.o -c /home/sukhraj/Projects/Acads/MSProject/libigl/tutorial/102_DrawMesh/main.cpp
In file included from /home/sukhraj/Projects/Acads/MSProject/libigl/tutorial/../include/igl/viewer/Viewer.cpp:38:0,
                 from /home/sukhraj/Projects/Acads/MSProject/libigl/tutorial/../include/igl/viewer/Viewer.h:164,
                 from /home/sukhraj/Projects/Acads/MSProject/libigl/tutorial/102_DrawMesh/main.cpp:2:
/home/sukhraj/Projects/Acads/MSProject/libigl/external/nanogui/ext/glfw/include/GLFW/glfw3.h:131:28: fatal error: GL/glcorearb.h: No such file or directory
   #include <GL/glcorearb.h>
                            ^
compilation terminated.

============== log ends =============

**Comment by alecjacobson** [comment]
Seems like a glfw bug? Can you compile their examples?

**Comment by danielepanozzo** [comment]
This should be fixed now:
https://travis-ci.org/libigl/libigl

Please open it again if the problem is still there for you.
