### ISSUE TITLE
Cmake fails with gcc 4.8.5 due to cxxx_decltype_auto

### ISSUE THREAD

**Issue by sim-saurabh** [libigl/libigl#2108]
#### Describe your issue
Current master fails during cmake generation step with following error:

CMake Error in CMakeLists.txt:
  The compiler feature "cxx_decltype_auto" is not known to CXX compiler

  "GNU"

  version 4.8.5.

#### Checklist

- [x] I have read the [bug report](https://libigl.github.io/bug-report/) page
- [x] CMake issue: I have tried with a fresh clone/empty build directory

#### Platform

- [ ] Windows
- [ ] macOS
- [x] Linux

**Comment by BruegelN** [comment]
Could you please try to update to a newer version of GCC, as 4.8.5 is already quite old (June 23, 2015) and does not support all required features.
See also https://libigl.github.io/faq/ under "What’s the deal with CGAL and GCC 4.8?" . There is another known issue with GCC 4.8 and CGAL.

**Comment by alecjacobson** [comment]
I won't be making any fixes to support gcc 4.8.5. If someone submits a pr, happy to review and merge.
