### ISSUE TITLE
How to CMake libigl to generate VC projects in MTD not MDd?

### ISSUE THREAD

**Issue by wguo68** [libigl/libigl#211]
I want to create VC projects in MTD not MDd so that my program can run on other computers without copying so much DLLs. How to do this?
I can't set the USE_STATIC_RUNTIME. Even I set it .it is reset to OFf after I configure in GUI_Cmake.

If I set  Mtd for MAKE_CXX_FLAGS .then when I compile 607 examples.will be errors such as:

obj : error LNK2019: unresolved external symbol __imp_rtcNewScene referenced in function "public: void __cdecl igl::embree::EmbreeIntersector::init(class std::vector<class Eigen::Matrix<float,-1,3,0,-1,3> const *,class std::allocator<class Eigen::Matrix<float,-1,3,0,-1,3> const *> > const &,class std::vector<class Eigen::Matrix<int,-1,3,0,-1,3> const *,class std::allocator<class Eigen::Matrix<int,-1,3,0,-1,3> const *> > const &,class std::vector<int,class std::allocator<int> > const &,bool)" (?init@EmbreeIntersector@embree@igl@@QEAAXAEBV?$vector@PEBV?$Matrix@M$0?0$02$0A@$0?0$02@Eigen@@V?$allocator@PEBV?$Matrix@M$0?0$02$0A@$0?0$02@Eigen@@@std@@@std@@AEBV?$vector@PEBV?$Matrix@H$0?0$02$0A@$0?0$02@Eigen@@V?$allocator@PEBV?$Matrix@H$0?0$02$0A@$0?0$02@Eigen@@@std@@@5@AEBV?$vector@HV?$allocator@H@std@@@5@_N@Z)
....

**Comment by alecjacobson** [comment]
Libigl is a header only library that does not use dynamic linking. Some of the dependences use dynamic libraries/shared libraries, but we do not provide solutions for compiling them statically.

**Comment by wguo68** [comment]
I found if embree does ont depend on CGAL these error will gone.
So I try to comile CGAL in MTd, but the CGAL depend on Boost which  I don't know how to make it in MTd because Boost does not support CMake.
