### ISSUE TITLE
remesh_self_intersections() not removing all self-intersections.

### ISSUE THREAD

**Issue by Jarelk** [libigl/libigl#2120]
#### Describe the bug
I am trying to run Tetgen on a mesh with self-intersections. After calling `remove_self_intersections()` Tetgen reports that there are still intersections left. I found one person with a similar problem (https://github.com/libigl/libigl/issues/760), but got no further.

#### Platform
- [x] Windows

Here is the mesh in question:
[m1129.zip](https://github.com/libigl/libigl/files/10034679/m1129.zip)

This is the function that I use to remove self intersctions:

```cpp
void INFOMR::Remesh::__removeSelfIntersections(MatrixXd& V, MatrixXi& F)
{
	MatrixXd SV, VV, V_final;
	MatrixXi SF, FF, IF, G, flip;
	VectorXi H, IM, UIM, J;
	igl::copyleft::cgal::remesh_self_intersections(V, F, 
		igl::copyleft::cgal::RemeshSelfIntersectionsParam(false, false, true),
		VV, FF, IF, H, IM);
	for_each(FF.data(), FF.data() + FF.size(), [&IM](int& a) {a = IM(a); });
	igl::remove_unreferenced(VV, FF, SV, SF, UIM);
	igl::copyleft::cgal::outer_hull(SV, SF, V_final, G, J, flip);
	V = V_final;
	F = G;
}
```

Then I run Tetgen on it like so:

```cpp
MatrixXd TV;
MatrixXi TT;
MatrixXi TF;
bool succes = igl::copyleft::tetgen::cdt(V2, F2, { true, 1.01, "pq1.414Y" }, TV, TT, TF);
```
And I get the following error messages from Tetgen:

```console
Warning:  Two line segments are nearly overlapping.
  1st: [2244,2249].
  2nd: [2244,2248].
  Reducing collinear tolerance from 179.9 to 179.962 degree.
Warning:  Two line segments are nearly overlapping.
  1st: [1587,1581].
  2nd: [1587,1586].
  Reducing collinear tolerance from 179.962 to 179.99 degree.
Warning:  Two line segments are nearly overlapping.
  1st: [1307,1287].
  2nd: [1307,1288].
  Reducing collinear tolerance from 179.99 to 179.994 degree.
Warning:  Two line segments are nearly overlapping.
  1st: [3322,3316].
  2nd: [3322,3321].
  Reducing collinear tolerance from 179.994 to 179.997 degree.
Warning:  Two line segments are nearly overlapping.
  1st: [3822,3826].
  2nd: [3822,3825].
  Reducing collinear tolerance from 179.997 to 179.997 degree.
Warning:  Two line segments are nearly overlapping.
  1st: [31,22].
  2nd: [31,27].
  Reducing collinear tolerance from 179.997 to 179.999 degree.
Warning:  Two line segments are nearly overlapping.
  1st: [1808,1793].
  2nd: [1808,1797].
  Reducing collinear tolerance from 179.999 to 179.999 degree.
Warning:  Two line segments are nearly overlapping.
  1st: [2668,2673].
  2nd: [2668,2670].
  Reducing collinear tolerance from 179.999 to 179.999 degree.
Warning:  Two line segments are nearly overlapping.
  1st: [1409,1186].
  2nd: [1409,1264].
  Cannot reduce the current collinear tolerance (=179.999 degree).
Warning:  Two line segments are nearly overlapping.
  1st: [1550,1562].
  2nd: [1550,1555].
  Reducing collinear tolerance from 179.999 to 180 degree.
  Skipped 1 segments due to intersections.
Warning:  Two facets are overlapping at triangle (3321,3322,3325).
  1st facet tag(3574).
  2nd facet tag(4615).
Warning:  Two facets are overlapping at triangle (529,531,533).
  1st facet tag(5066).
  2nd facet tag(4026).
Boundary recovery seconds:  0.081

!!! 4 input triangles are skipped due to self-intersections.
Writing tetgen-tmpfile_skipped.node.
Writing tetgen-tmpfile_skipped.face
Writing nodes.
Writing elements.
Writing faces.
Writing edges.
^igl::copyleft::tetgen::tetrahedralize: TETGEN CRASHED... KABOOOM!!!
```

**Comment by alecjacobson** [comment]
I'll try to take a look at your data. In the meantime, there are two main reasons this can happen.

1. (most likely) Tetgen's self-intersection detection is imperfect. Sometimes very close triangles in its floating point inputs are declared to be self-intersecting when they're not. Tetgen has a tolerance (`-T` I believe) to control this sensitivity. FWIW, in my experience lowering it often results in tetgen errors later though.
2. (less likely) remove_self_intersections works with exact numbers but if you need to convert it to double (e.g., to call tetgen) then the output is "rounded" to double precision. This can introduce self-intersections. You can check this by calling igl::self_intersect on the direct output with parameters to detectonly . If this returns true, then there are some heuristics to do this rounding I can describe if needed.

**Comment by Jarelk** [comment]
Thank you for your reply! I suspect 1. is spot on. I think the error log is showing how the line segments are nearly overlapping, and Tetgen seems to reduce their tolerance each time it finds such a near-overlap. Following that, either there's overlaps happening due to cast from exact number to double, or its tolerance gets so low it starts throwing errors at very near overlaps.

Is there anything I can do about this? Either by somehow resolving self-intersections while not allowing long, narrow triangles, or resampling points?

**Comment by alecjacobson** [comment]
If you're ok with your tetmesh having a fully remeshed surface, I'd recommend trying TetWild as an alternative to Tetgen.

In situtations where I prefer to use tetgen (like when I need the surface close as possible to the input) then I tend to try to use MeshFix to resolve issues on each connected component followed by a "self-union" using libigl's boolean code before calling tetgen. This didn't work so great on your model (sometimes meshfix deletes too much and did in this case).

**Comment by Jarelk** [comment]
fTetWild looks pretty good! I might check it out, but this was for a university assignment and we're practically done, so I also might not, haha. Thank you anyway!

A final question: is it not possible to run `remesh_self_intersections()` with a matrix of `CGAL::Epeck`, and pass that? Does Tetgen accept that as param?

**Comment by alecjacobson** [comment]
no, unfortunately, tetgen is implemented only for floating point inputs.

**Comment by Jarelk** [comment]
Thank you for your time! I will close the issue now.
