### ISSUE TITLE
Exception thrown at 0x00007FFC5FF0CD29 in 609_Boolean.exe: Microsoft C++ exception: CGAL::Uncertain_conversion_exception at memory location 0x0000007CD84FF160.

### ISSUE THREAD

**Issue by AndreAhmed** [libigl/libigl#2122]
#### Describe the bug
I have just used the example boolean, from the repo, and I get the above exception
#### Platform

- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by sloriot** [comment]
Note that this exception is raised each time you need to resort to exact computation. It is caught and handled by CGAL. You can close the issue IMO.
