### ISSUE TITLE
Avoid using namespace std and use std::vector instead

### ISSUE THREAD

**Issue by Nosenzor** [libigl/libigl#2132]
#### Describe your issue

In some files (eg faces_first.cpp; triangle_triangle_adjacency.cpp; unique_edge_map.cpp...) the usage of std::vector are not prefixed by "std::" leads to a compile error for ambiguous naming (vector is too common in geometry)
The problem appears when you only include a very small subset of libIGL (for now i'm including only "igl/triangle_triangle_adjacency.h")
Also i've noted "#include <vector>" is missing in some files.

using namespace std is a bad practice ...
I suggest to also remove all usage of "using namespace Eigen"

**I can do the change and do a PR if you like ...**

#### Checklist

- [ X] I have read the [bug report](https://libigl.github.io/bug-report/) page
- [ X] CMake issue: I have tried with a fresh clone/empty build directory

#### Platform

- [X ] Windows
- [ X] macOS
- [ X] Linux

**Comment by BruegelN** [comment]
Related to https://github.com/libigl/libigl/issues/1282, especially https://github.com/libigl/libigl/issues/1282#issuecomment-527158060
____

> vector is too common in geometry

Yes, thus it's a good idea to capsule your `vector` class into your own namespace and not pollute global namespace with it.

**Comment by Nosenzor** [comment]
Problem is that IGL is "pseudo header-only" (When you include the header it will include the cpp), so it breaks the common rules of not using "using namespace" in headers and pollute the namespace for every caller.
In library mode that's not a big issue (although not recommended).
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rs-using
IMO adding "std::" in front of vector declaration is not too cumbersome.
Do you see any issue adding "std::" ?

**Comment by alecjacobson** [comment]
There shouldn't be any `using namespace` calls in libigl outside of function scopes, so I don't see how this would pollute the namespace.

**Comment by jdumas** [comment]
I've had issues in the past with _other_ headers introducing their own `vector` class, leading to compilation when using libigl in header-only mode. Basically the problem was the other third-party header is included _before_ a libigl header (sometimes for a reason outside of my control), and then the libigl-included .cpp header complains about some ambiguous unqualified `vector` types (one coming from the `std::` namespace, one coming from said third-party).

Unfortunately I don't have a concrete MWE at the moment. One could argue that it's the polluting third-party lib's fault as well, so it would be better to have a concrete failure case with a problematic third-party library that we could examine...

**Comment by Nosenzor** [comment]
I was using trimesh2, https://github.com/Forceflow/trimesh2 that defines it's own vector class. I agree It's bit old we can blame any third party library... but I still think that adding std:: is much safer and the cost to do it is pretty small.
I've seen many using Eigen too, so the same kind of problem can appear too.

**Comment by alecjacobson** [comment]
Could you post a minimal example using Trimesh2? That fork appears to put things in the `Trimesh` namespace.  I also couldn't find the `vector` class there.

My guess is that this is really an issue for Trimesh2, and since that forks being actively developed it might be better to move the issue there.

**Comment by alecjacobson** [comment]
btw, @Nosenzor your original issue mentioned missing includes but didn't say where. Could you please elaborate?

**Comment by BruegelN** [comment]
> I was using trimesh2, https://github.com/Forceflow/trimesh2 that defines it's own vector class. I agree It's bit old we can blame any third party library... but I still think that adding std:: is much safer and the cost to do it is pretty small.
I've seen many using Eigen too, so the same kind of problem can appear too.

Having a brief look at the sources and searching for `using namespace std` (https://github.com/Forceflow/trimesh2/search?p=2&q=using+namespace+std) one will find quite a lot of usage in `libsrc/*.cc` and `utilsrc/*.cc` within global namespace.
@Nosenzor Could you please post a Minimal Working Example (with trimesh2+libigl) to reproduce your error?
____
@jdumas & @alecjacobson Yesterday I've took the effort to drop `using namespace std;` within libigl: https://github.com/BruegelN/libigl/commit/a5f6f4060709d0595f4c109b3a54dfda22fb6235. This is mainly global search+replace. The [branch remove-using-namespace-std](https://github.com/BruegelN/libigl/tree/remove-using-namespace-std) compiles and passes all tests however I'm afraid that the diff is to big to properly review......

**Comment by Nosenzor** [comment]
> > I was using trimesh2, https://github.com/Forceflow/trimesh2 that defines it's own vector class. I agree It's bit old we can blame any third party library... but I still think that adding std:: is much safer and the cost to do it is pretty small.
> > I've seen many using Eigen too, so the same kind of problem can appear too.
> @Nosenzor Could you please post a Minimal Working Example (with trimesh2+libigl) to reproduce your error?>
I will do my best to post it here although not really easy to extract just a simple case as it would need to setup a project with cmake and create a specific program (Trimesh is not header only). Not sure it worths the work.

**Comment by alecjacobson** [comment]
I don't want to take a hard stance either way. If we can make someone's life easier now by removing a few `using namespace std;` then that's great and we might as well do it. On the other hand, `using namespace std;` (or probably more often in our case `using namespace Eigen;`) can make code a lot easier to write and read. Things like `using Eigen::Matrix;` solve some but not all of those ergonometric issues. Bottom line, I'm not convinced that "`using namespace X;` is categorically bad practice". (I _do_ agree that "`using namespace X;` in a global/file scope is bad practice").

btw, for mixing with libraries that don't use namespaces, is it enough of a solution to include libigl headers _before_ that library's headers?

**Comment by jdumas** [comment]
`using namespace foo`, even scoped to a function, is only truly harmless when used inside a .cpp file that we can be sure never interferes with anything else imho. The fact that this keeps coming up is proof of that, even if it's often the fault of _another_ bad library that don't properly namespaces things.

If libigl didn't have this header-only mode, I'd say go to town with the `using namespace Eigen` to write shorter code, but as it stands the preferred approach for new code should be the more robust one of using lengthier names. Maybe another solution would be to alias Eigen's matrix types in the libigl namespace (or at the function level). This should be fairly harmless and allow writing shorter code as well.

> btw, for mixing with libraries that don't use namespaces, is it enough of a solution to include libigl headers before that library's headers?

Relying on header inclusion order is very brittle and should not be relying upon imho, so that's not a great solution to me.

> @jdumas & @alecjacobson Yesterday I've took the effort to drop using namespace std; within libigl: https://github.com/BruegelN/libigl/commit/a5f6f4060709d0595f4c109b3a54dfda22fb6235. This is mainly global search+replace. The [branch remove-using-namespace-std](https://github.com/BruegelN/libigl/tree/remove-using-namespace-std) compiles and passes all tests however I'm afraid that the diff is to big to properly review......

Thanks! I took a cursory glance and I don't see any problem with these changes.

**Comment by alecjacobson** [comment]
I don't think I understand the distinction between a function/local scope in a .h or a .cpp. Could you explain?

**Comment by jdumas** [comment]
If it's in a .cpp, then if it compiles it compiles, you're guaranteed of it. If it's used in a .h, then depending on what the user includes before the libigl header, things might blow up (due to the other lib pollution).

**Comment by alecjacobson** [comment]
Sorry, I still don't get it. What can blow up if `using namespace ...` is in a local scope in a header? Can you think of an example?

**Comment by jdumas** [comment]
Sure, imagine something like this:

#### dirty_lib.h
```c++
// unprotected vector type
template<typename T>
class vector {};
```

#### libigl_function.h
```c++
#include <vector>

namespace igl {
void foo() {
    using namespace std;
    vector<int> x;
}
}
```

#### main.cpp
```c++
#include <dirty_lib.h>
#include <libigl_header.h>

int main(void) {
  return 0;
}
```


So sure you could swap out `<dirty_lib.h>` and `<libigl_header.h>`, but that's a fairly brittle solution in general.

**Comment by alecjacobson** [comment]
Oh. I see. this is the same situation as above. I thought you meant something could go wrong without a "dirty" lib polluting the global namespace.

**Comment by jdumas** [comment]
Well, I think `using namespace std`, even at function scope, can also mess with ADL and other subtle C++ things (e.g. [this snippet](https://quuxplusone.github.io/blog/2020/12/21/using-directive/#consider-the-following-bad-code) or [this one](https://stackoverflow.com/questions/65365681/why-does-cs-using-namespace-work-the-way-it-does)). So even though it does work, I can't say this is a very safe thing to use, even at function scope (and probably not a good habit to teach to students).

**Comment by Nosenzor** [comment]
> btw, @Nosenzor your original issue mentioned missing includes but didn't say where. Could you please elaborate?
I've checked again on the files I've changed but the #include <vector> were in the header, so please consider I spoke too quickly.
