### ISSUE TITLE
Compilation broken: `curl: (60) SSL certificate problem: certificate has expired`

### ISSUE THREAD

**Issue by sgsellan** [libigl/libigl#2133]
#### Describe your issue
At some point in the past 48 hours, libigl stopped compiling on my own MacOS 13.1 laptop as well as our project's MacOS and linux [CI machines](https://github.com/sgsellan/gpytoolbox/actions). 

To reproduce, I clone libigl and build with cmake
```bash
git clone --recursive https://github.com/libigl/libigl.git
cd libigl
mkdir build
cd build
cmake -DLIBIGL_GLFW=OFF -DLIBIGL_IMGUI=OFF ..
make
```

The error returned is

```
[ 81%] Performing patch step for 'gmp'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
error: No valid patches in input (allow with "--allow-empty")
make[2]: *** [_deps/gmp/src/gmp-stamp/gmp-patch] Error 128
make[1]: *** [CMakeFiles/gmp.dir/all] Error 2
make: *** [all] Error 2
```

I attach the full [CMakeCache.txt](https://github.com/libigl/libigl/files/10324029/CMakeCache.txt) and [log](https://github.com/libigl/libigl/files/10324034/Terminal.Saved.Output.txt).

#### Checklist

- [x] I have read the [bug report](https://libigl.github.io/bug-report/) page

- [x] CMake issue: I have tried with a fresh clone/empty build directory

#### Platform

- [ ] Windows
- [x] macOS
- [x] Linux

**Comment by sgsellan** [comment]
Ah, I see. Managed to ages `gmplib.org` on a different browser and they seem aware of the issue:

> YES, THE CERTIFICATE IS EXPIRED. Sorry about that. We're working on the renewal process. Unfortunately, our SSL provider changes the renewal interface each year, and it is always a challenge to figure out what to do. Now the only actions are REGENERATE (actiually not, as the cert is expired), REVOKE (well, not desirable) and INTERMEDIATE CERTIFICATE (which is not an action but a thing, oh well.

So I guess we wait?

**Comment by jdumas** [comment]
Well I guess one could use a mirror of GMP on Github (e.g. [this one](https://github.com/alisw/GMP)?), or create our own mirror, to avoid such inconvenience every year...

**Comment by sgsellan** [comment]
Adding `-k` in the curl command can also be a temporary hot fix, but probably less principled. Whichever you all end up doing sounds fine by me!

**Comment by aradhyamathur** [comment]
gives connection refused `curl: (7) Failed to connect to gmplib.org port 443: Connection refused` when used with -k
