### ISSUE TITLE
How to build libigl as dynamic library?

### ISSUE THREAD

**Issue by Pupillen** [libigl/libigl#2136]
Hello, I have a question about linking libigl to a shared dynamic library (.so).
Actually, I want to link libigl to a ros system by using catkin_make and could not properly compile it.
The error is "relocation R_X86_64_PC32 against..... can not be used when making a shared object; recompile with -fPIC". I have add sth like set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall --std=c++14 -O3 -fPIC" )
set( CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wall -O3 -fPIC" ) in the CMakeList.txt but seems still having the same problem?
Could anyone kindly provide me a CMakeLists.txt showing how to build libigl with a dynamic library? Thanks a lot!

**Comment by alecjacobson** [comment]
I'm not sure how to do this currently (last time I tried was probably 10 years ago). Do you just need the core library? Or some of the optional modules?

**Comment by jdumas** [comment]
The CMake target property to configure to enable `-fPIC` is called [POSITION_INDEPENDENT_CODE](https://cmake.org/cmake/help/latest/prop_tgt/POSITION_INDEPENDENT_CODE.html). You can try to set the default value via [CMAKE_POSITITON_INDEPENDENT_CODE](https://cmake.org/cmake/help/latest/variable/CMAKE_POSITION_INDEPENDENT_CODE.html) in the hope it compiles the required dependencies with the `-fPIC` flag.

For the shared libraries it should be enough to enabled the option [BUILD_SHARED_LIBS](https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html).

**Comment by Pupillen** [comment]
> The CMake target property to configure to enable `-fPIC` is called [POSITION_INDEPENDENT_CODE](https://cmake.org/cmake/help/latest/prop_tgt/POSITION_INDEPENDENT_CODE.html). You can try to set the default value via [CMAKE_POSITITON_INDEPENDENT_CODE](https://cmake.org/cmake/help/latest/variable/CMAKE_POSITION_INDEPENDENT_CODE.html) in the hope it compiles the required dependencies with the `-fPIC` flag.
> 
> For the shared libraries it should be enough to enabled the option [BUILD_SHARED_LIBS](https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html).

Thanks a lot, I've solved my issue!
