### ISSUE TITLE
compile error in the building for 607 example.

### ISSUE THREAD

**Issue by wguo68** [libigl/libigl#214]
![607](https://cloud.githubusercontent.com/assets/4994038/12534489/390494a2-c296-11e5-9776-2e307d0fcb6f.jpg)

If I modified the configuration type of "embree"  from static library to dynamic library. Then the error will gone. I don'kt know the reason for this compile error.

**Comment by alecjacobson** [comment]
If you changed how embree is compiling then you might need to change the associated cmake commands so that the tutorial examples find the static library. However, you're "off piste" at this point...
