### ISSUE TITLE
202_GaussianCurvature ; 'GLVersion' : undeclared identifier

### ISSUE THREAD

**Issue by imfm31** [libigl/libigl#2147]
#### Describe your issue

I've followed the instructions at the beginning of the tutorial page and I wanted to check the 202_GaussianCurvature tutorial to see if it worked. 
Unfortunately, when Visual Studio (2022) tries to build the solution, it gives me the following error 'GLVersion' : undeclared identifier, which is used in line 187 of Viewer.cpp
 
I'm unsure if this is because I already had OpenGL installed on my computer? (I've found it in C:\Windows\System32 as opengl32.dll)

#### Checklist

- [ ] I have read the [bug report](https://libigl.github.io/bug-report/) page
- [x] CMake issue: I have tried with a fresh clone/empty build directory

#### Platform

- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by manuelruivodeoliveira** [comment]
I had the same error when compiling tutorial 102_DrawMesh in Visual Studio 2022 on Windows 10 with a debug configuration. I think it only happens with a debug configuration as that line in Viewer.cpp is inside a `#if defined(DEBUG) || defined(_DEBUG)` block, so you could just use a different build configuration. Or if you want to use a debug configuration I think it's fine to comment out that line (188) as it is just a `printf()` call. Both worked for me.
