### ISSUE TITLE
Example 102 Compilation error

### ISSUE THREAD

**Issue by yuhaozhou2000** [libigl/libigl#2158]
#### Describe your issue

When I compile example 102, the compiler displays that LNK1104 cannot open “..\lib\Debug\igl_glfw.lib”	305_QuadraticProgramming

#### Platform

- [ ] Windows10
- [ ] visualstudio 2019

**Comment by gdwei** [comment]
See [issues 2098](https://github.com/libigl/libigl/issues/2098), it solves this problem.
