### ISSUE TITLE
linker command failed with exit code 1 

### ISSUE THREAD

**Issue by xander-Ito-Low** [libigl/libigl#2159]
#### Describe your issue

As instructed in the tutorial I follow these instructions to compile the examples:
cd libigl/
mkdir build
cd build
cmake ../
make

It results in the following error log:

/usr/local/Cellar/cmake/3.25.2/bin/cmake -E cmake_link_script CMakeFiles/test_igl_core.dir/link.txt --verbose=1
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names CMakeFiles/test_igl_core.dir/tests/main.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/MshLoader.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/MshSaver.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/accumarray.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/avg_edge_length.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/barycentric_interpolation.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/bbw.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/bezier.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/blkdiag.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/blue_noise.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/boundary_facets.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/boundary_loop.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/cat.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/circulation.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/cotmatrix.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/cotmatrix_entries.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/cotmatrix_intrinsic.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/cr_vector_curvature_correction.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/cr_vector_laplacian.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/cumprod.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/cumsum.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/curved_hessian_energy.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/cut_mesh.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/cut_to_disk.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/decimate.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/delaunay_triangulation.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/diag.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/dijkstra.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/direct_delta_mush.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/dirname.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/doublearea.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/edge_exists_near.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/edge_flaps.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/edge_lengths.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/exact_geodesic.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/facet_components.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/fast_winding_number.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/fit_cubic_bezier.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/grad.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/grad_intrinsic.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/grid.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/guess_extension.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/heat_geodesics.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/intrinsic_delaunay_cotmatrix.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/intrinsic_delaunay_triangulation.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/is_delaunay.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/is_edge_manifold.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/is_intrinsic_delaunay.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/is_irregular_vertex.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/is_symmetric.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/ismember.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/iterative_closest_point.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/knn.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/linprog.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/list_to_matrix.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/lscm.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/min_quad_with_fixed.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/moments.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/orient_halfedges.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/path_to_edges.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/path_to_executable.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/pathinfo.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/per_face_normals.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/polygon_corners.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/principal_curvature.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/qslim.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/quadprog.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/randperm.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/readDMAT.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/readMESH.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/readMSH.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/readOBJ.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/readOFF.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/readPLY.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/remesh_along_isoline.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/repmat.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/rigid_alignment.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/seam_edges.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/segment_segment_intersect.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/setdiff.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/signed_distance.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/slice.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/slice_into.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/slice_sorted.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/sort.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/sparse_voxel_grid.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/split_nonmanifold.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/squared_edge_lengths.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/tet_tet_adjacency.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/triangle_triangle_adjacency.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/triangulated_grid.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/unique.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/unique_simplices.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/upsample.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/writeMSH.cpp.o CMakeFiles/test_igl_core.dir/tests/include/igl/writePLY.cpp.o -o tests/test_igl_core  lib/libigl.a 
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/accumarray.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/main.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/MshLoader.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/blkdiag.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/MshSaver.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/blue_noise.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/boundary_facets.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/bezier.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/boundary_loop.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/cat.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/cotmatrix_entries.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64ld: warning: 
ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/cotmatrix.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/circulation.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/avg_edge_length.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/cr_vector_curvature_correction.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: 
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/bbw.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/cotmatrix_intrinsic.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/cumprod.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/barycentric_interpolation.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/cut_mesh.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/curved_hessian_energy.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/decimate.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64ld: warning: 
ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/cumsum.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64

ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/cr_vector_laplacian.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/direct_delta_mush.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/diag.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/dirname.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64ld: warning: 
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/delaunay_triangulation.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/cut_to_disk.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64

ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/edge_flaps.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/edge_exists_near.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: 
ld: warning: ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/edge_lengths.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/fast_winding_number.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/facet_components.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/fit_cubic_bezier.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/grad_intrinsic.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/dijkstra.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64ld: warning: 
ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/guess_extension.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/grad.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64ld: warning: 
ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/exact_geodesic.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/grid.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/heat_geodesics.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/is_delaunay.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/is_edge_manifold.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/intrinsic_delaunay_cotmatrix.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/is_irregular_vertex.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/ismember.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/is_symmetric.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/iterative_closest_point.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/knn.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/list_to_matrix.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/min_quad_with_fixed.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/doublearea.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/moments.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/orient_halfedges.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/intrinsic_delaunay_triangulation.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/path_to_executable.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/pathinfo.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/per_face_normals.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/lscm.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/polygon_corners.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/linprog.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/quadprog.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/randperm.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/readDMAT.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/path_to_edges.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/qslim.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/is_intrinsic_delaunay.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/readMESH.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/principal_curvature.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/repmat.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/remesh_along_isoline.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/rigid_alignment.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ld: warning: ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/seam_edges.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/segment_segment_intersect.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64

ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/readPLY.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/setdiff.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/signed_distance.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/readMSH.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64

ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/readOBJ.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64

ld: warning: ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/slice.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/slice_sorted.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/sort.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/tet_tet_adjacency.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64ld: warning: 
ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/sparse_voxel_grid.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64

ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/readOFF.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/slice_into.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/triangulated_grid.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/squared_edge_lengths.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/triangle_triangle_adjacency.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/unique_simplices.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/unique.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/writeMSH.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/upsample.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64ld: warning: ld: warning: ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/writePLY.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64

ignoring file CMakeFiles/test_igl_core.dir/tests/include/igl/split_nonmanifold.cpp.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file lib/libigl.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [tests/test_igl_core] Error 1
make[1]: *** [CMakeFiles/test_igl_core.dir/all] Error 2
make: *** [all] Error 2

#### Checklist

- [x] I have read the [bug report](https://libigl.github.io/bug-report/) page
- [x] CMake issue: I have tried with a fresh clone/empty build directory

#### Platform

- [ ] Windows
- [x] macOS
- [ ] Linux

Any advice on how to resolve this would be helpful. Thank you

**Comment by alecjacobson** [comment]
Are you on a M1 Mac or Intel Mac?

I haven't experienced this on either. I wonder if there's a mismatched configuration with your cmake.

**Comment by xander-Ito-Low** [comment]
Apple M1 Pro Thanks.

How can I check if my cmake has a configuration mismatch?

**Comment by xander-Ito-Low** [comment]
I used homebrew to install cmake, will try to locate the file and will post it thanks

**Comment by xander-Ito-Low** [comment]
Turns out it was brew being outdated from when I had my previous mac. I deleted and reinstalled and the build command worked Thanks.

When the make command is complete, how can I run the code for the tutorials? Thanks.

**Comment by xander-Ito-Low** [comment]
I have found the bin files will close this now.
