### ISSUE TITLE
Exact Geodesic example failing with STL

### ISSUE THREAD

**Issue by kappa95** [libigl/libigl#2160]
#### Describe the bug
Reproduced the example 206. It works as the doc for armadillo. But it fails with stl files during runtime. It crashes as the program starts with following error: 
```bash
following error: Computing geodesic distance to vertex 0...
Assertion failed: std::find(map.begin(), map.end(), false) == map.end(), file C:\Users\admin\Documenti\Esperimenti\Test2\out\build\x64-Debug\_deps\libigl-src\include\igl\exact_geodesic.cpp, line 1066
```
Mesh has been loaded as following:
```c++
Eigen::MatrixXd V;
Eigen::MatrixXi F;
igl::opengl::glfw::Viewer viewer;
// Load a mesh
std::string file_name = "C:/Users/admin/Documenti/Esperimenti/Test2/ducky_cleaned.obj";
igl::read_triangle_mesh(file_name, V, F);
```

Converting the same stl in obj works.

#### Platform

- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by alecjacobson** [comment]
> **.STL** files do not store meshes. They store a stream of disconnected triangles. libigl loads this literally into `V`, `F`. To connect triangles to mesh, it is correct to call `igl::remove_duplicate_vertices` upon load if a merged mesh is desired.

```cpp
Eigen::MatrixXd V;
Eigen::MatrixXi F;
igl::opengl::glfw::Viewer viewer;
// Load a mesh
std::string file_name = "C:/Users/admin/Documenti/Esperimenti/Test2/ducky_cleaned.obj";
igl::read_triangle_mesh(file_name, V, F);
{
  Eigen::VectorXi _I,_J;
  igl::remove_duplicate_vertices(Eigen::MatrixXd(V),Eigen::MatrixXi(F),0,V,_I,_J,F);
}
```

**Comment by kappa95** [comment]
> > **.STL** files do not store meshes. They store a stream of disconnected triangles. libigl loads this literally into `V`, `F`. To connect triangles to mesh, it is correct to call `igl::remove_duplicate_vertices` upon load if a merged mesh is desired.
> 
> ```c++
> Eigen::MatrixXd V;
> Eigen::MatrixXi F;
> igl::opengl::glfw::Viewer viewer;
> // Load a mesh
> std::string file_name = "C:/Users/admin/Documenti/Esperimenti/Test2/ducky_cleaned.obj";
> igl::read_triangle_mesh(file_name, V, F);
> {
>   Eigen::VectorXi _I,_J;
>   igl::remove_duplicate_vertices(Eigen::MatrixXd(V),Eigen::MatrixXi(F),0,V,_I,_J,F);
> }
> ```

Thank you, I didn't know that STL are considered as disconnected triangles. I have noticed that also meshes (stl and obj both) suffers when mesh intersections occurred and must be cleaned before computing the geodesic distance.
