### ISSUE TITLE
wrong 202_gaussianCurvature results ?

### ISSUE THREAD

**Issue by jochemspek** [libigl/libigl#217]
Hi there,

I'm running the gaussian curvature tutorial on an object I made, and the results
seem wrong to me, but I may be interpreting them in the wrong way. 
I understand that blue gives negative curvature and red shows positive,
but why would the inside of the cup (the lower part) show positive curvature
when it is bending inward ? Could anyone explain ?

thanks,

Jonathan

<img width="636" alt="screen shot 2016-01-26 at 11 16 01" src="https://cloud.githubusercontent.com/assets/377154/12578099/fe9492b0-c41e-11e5-94dc-ffb3989613f7.png">

**Comment by alecjacobson** [comment]
I'm not sure which part you're talking about. The red part inside the cup (circled in white)?

![image](https://cloud.githubusercontent.com/assets/2241689/12581679/2df2f5b0-c406-11e5-9c50-2a20031f294d.png)

Gaussian curvature k is k1 times k2, where k1 and k2 are the maximal and minimal principal curvatures. If k1<0 and k2<0 then k = k1*k2 > 0.

I would _**not**_ interpret k>0 as "bending outward" and k<0 as "bending inward". Rather I prefer the intuition (as in the tutorial):

k>0 ---> locally spherical (from k alone we cannot determine convex k1,k2 >0 or concave k2,k1<0 )
k=0 ---> locally cylindrical (from k alone we cannot determine if flat k1=k2 =0)
k<0 ---> locally saddle-shaped ("bending" in two opposite directions, if you want)

https://en.wikipedia.org/wiki/Principal_curvature#Classification_of_points_on_a_surface

**Comment by jochemspek** [comment]
Oh, thanks, that is clarifying indeed !
