### ISSUE TITLE
Different values of Gaussian curvature for a triangular mesh.

### ISSUE THREAD

**Issue by KanikaRajain** [libigl/libigl#2176]
#### bug
PrincipalDir2, PrincipalDir1, K2, K1 = igl.principal_curvature(mesh.vertices,mesh.faces)
gaussian_curv = igl.gaussian_curvature(mesh.vertices,mesh.faces)

and gaussian_curv ≠ K1*K2 

Please see the attached a screenshot of output:

![Screenshot 2023-02-24 at 11 35 35](https://user-images.githubusercontent.com/71551869/221157663-e99c872e-982b-445a-9eba-b6df8a5af984.png)

![Screenshot 2023-02-24 at 11 31 14](https://user-images.githubusercontent.com/71551869/221156974-daa0fd07-493e-41e6-9998-268233817898.png)

-Python 3.9.16, macOS 13.2.1

**Comment by alecjacobson** [comment]
This is expected (we could do a better job clarifying in the documentation). These two functions use a very difference way of computing curvatures on triangle meshes. `igl:: principal_curvature` uses local fitting, where as `igl::gaussian_curvature` uses discrete sum of triangle angles. 

Different applications/uses require different qualities of a curvature approximation. There are a few other popular curvature methods not implemented in igl, too.

If you're interested you might look at these resources:

https://github.com/alecjacobson/geometry-processing-curvature
"Chapter 5. Curvature of Discrete Surfaces" http://www.cs.cmu.edu/~kmcrane/Projects/DDG/paper.pdf
