### ISSUE TITLE
How to modify the material color of model or the color of lighting ?

### ISSUE THREAD

**Issue by shdong** [libigl/libigl#218]
The default color is yellow color,but I didn't find where the color is set to yellow. It should be white or gray according to the vertex or fragment shaders. How to define material color or lighting color in libigl? I can't find place to modify these color.

**Comment by alecjacobson** [comment]
Please have a look at the [tutorial](http://libigl.github.io/libigl/tutorial/tutorial.html), especially [103](http://libigl.github.io/libigl/tutorial/tutorial.html#scalarfieldvisualization)
