### ISSUE TITLE
MAC sse compilation error

### ISSUE THREAD

**Issue by weiyu666** [libigl/libigl#2183]
#### Describe your issue

MAC sse compilation error. I added libigl library to our own project, including the head file. But when using arap, SIMD compilation reported an error. I don't know whether to add the configuration in cmake or where.
![image](https://user-images.githubusercontent.com/22174508/225231653-0cb72ff3-e6d5-4c38-acf6-66eed7b592a2.png)

this is error log:
![image](https://user-images.githubusercontent.com/22174508/225232404-f4831376-89e6-4753-8e37-1da5741a4b73.png)

![image](https://user-images.githubusercontent.com/22174508/225232461-c6aa1766-4c80-4e2c-880c-c6ad5e976fba.png)

#### Checklist

- [1 ] I have read the [bug report](https://libigl.github.io/bug-report/) page
- [ ] CMake issue: I have tried with a fresh clone/empty build directory

#### Platform

- [ ] Windows
- [1 ] macOS Intel
- [ ] macOS Arm (e.g., M1, M2)
- [ ] Linux

**Comment by alecjacobson** [comment]
Could you give a minimal example with the compilation setup and your Mac os version ?

Did the arap tutorial build and run?

**Comment by weiyu666** [comment]
The problem has been resolved, and I have looked at Case 405 in the tutorial. This causes the problem igl:: arap_ Solve and igl:: arap_ The type of precomputation parameter is wrong! "I should be Eigen:: MatrixXi instead of Eigen:: MatrixXD, and I need # pragma clang diagnostic ignored" - Uninitialized "to ignore uninitialized issues in # include<igl/arap. h>.".
OS Version:
<img width="239" alt="企业微信截图_46ce222f-0687-4579-b326-40aa0484895a" src="https://user-images.githubusercontent.com/22174508/225564794-db902d6c-8957-4657-a743-3365e13dd6bc.png">

Compiler Version：
![image](https://user-images.githubusercontent.com/22174508/225564415-94ff1955-ff76-4a89-8cad-4c01e3bace74.png)

For the construction and operation of the arap tutorial, libigl-example-project will run slowly. I don't know whether SIMD acceleration is not enabled or what. Please see here.
https://github.com/libigl/libigl-example-project/issues/35

**Comment by alecjacobson** [comment]
For the speed issue, my guess is that you're compiling in Debug mode or running on a large model. Please open a new issue if it persists in release mode for a moderate example like the tutorial.
