### ISSUE TITLE
v2.4.0 top-level CMake installation is broken

### ISSUE THREAD

**Issue by FabienPean** [libigl/libigl#2186]
Observed when trying out the new port via vcpkg, see https://github.com/microsoft/vcpkg/issues/30621. Relevant details repeated below:

**CMake config files are broken**

1. Naming inconsistent 
![image](https://user-images.githubusercontent.com/9134757/229367148-69e46315-c00a-40e3-82ac-78334607af5d.png)
2. Main config file not including target file, i.e., missing `include(${CMAKE_CURRENT_LIST_DIR}/LibiglConfigTargets.cmake)`.
   * It means the include folder of igl cannot be found on a simple test case, because it cannot find the target igl::igl_core

**Modules are not installed**

Upstream repository does not install the targets containing the options, only the core target, see https://github.com/search?q=repo%3Alibigl%2Flibigl%20igl_install&type=code. Moreover, installing does not include copyleft targets https://github.com/libigl/libigl/blob/a05865e2650f22057fcdc0b77c40d2458922f5d8/CMakeLists.txt#L150

- [x] Windows
- [x] macOS
- [x] Linux

**Comment by jdumas** [comment]
Libigl has never supported installation of modules other than the core target. Support for installed target is typically user-contributed.

**Comment by FabienPean** [comment]
Indeed, this is a vcpkg issue, options have been made available without checking them. Although, in version 2.3.0, the copyleft folder was installed besides core files https://github.com/libigl/libigl/blob/v2.3.0/cmake/libigl.cmake#L554

For the other point, a PR has been opened with some way to solve it.
