### ISSUE TITLE
igl::decimate fails against simple setup

### ISSUE THREAD

**Issue by Zeta48** [libigl/libigl#2191]
I am trying to add mesh decimation to my engine using LibIgl.
Unfortunaletly the **igl::decimate** method is returning false even on trival cases .

A 2 triangle example that fails:
`

		// 6 vertices.
		const int inNbVertices = 6;
		Eigen::MatrixXd V(inNbVertices, 3);
		{
			V(0, 0) = -120.0f; V(0, 1) = 0.0f; V(0, 2) = -107.0f;
			V(1, 0) = -120.0f; V(1, 1) = 0.0f; V(1, 2) = 107.0f;
			V(2, 0) = 120.0f; V(2, 1) = 0.0f; V(2, 2) = -107.0f;
			V(3, 0) = 120.0f; V(3, 1) = 0.0f; V(3, 2) = 107.0f;
			V(4, 0) = 120.0f; V(4, 1) = 0.0f; V(4, 2) = -107.0f;
			V(5, 0) = -120.0f; V(5, 1) = 0.0f; V(5, 2) = 107.0f;
		}

		// 2 faces
		const int inNbFaces = 2;
		Eigen::MatrixXi F(inNbFaces, 3);
		{
			F(0, 0) = 0; F(0, 1) = 1; F(0, 2) = 2;
			F(1, 0) = 3; F(1, 1) = 4; F(1, 2) = 5;
		}

		// Perform decimation.
		const nbInt32 target_num_faces = 1;//50%
		Eigen::MatrixXd U;
		Eigen::MatrixXi G;
		Eigen::VectorXi J;
		const bool success = igl::decimate(V, F, target_num_faces, U, G, J);// declared in <igl/decimate.h>
		assert(success);
`

Am I doing something wrong? Thank you

**Comment by alecjacobson** [comment]
This example is a mesh with two **_disconnected_** triangles. Since igl::decimate preserves the topology of the input, there's nothing to decimate. This is correct behavior.

**Comment by Zeta48** [comment]
@alecjacobson Thanks for helping.
I tested against [the Sponza Atrium](https://casual-effects.com/g3d/data10/common/model/crytek_sponza/sponza.zip).   
50% of the meshes pass decimation while the remaining don't.
