### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by echo-hi** [libigl/libigl#2196]
i use the cmakeList as follow
```
cmake_minimum_required(VERSION 3.16)
project(example)
list(PREPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/cmake)
include(libigl)
igl_include(glfw)
igl_include(tetgen)
file(GLOB SRC_FILES *.cpp)
add_executable(${PROJECT_NAME} ${SRC_FILES})
target_link_libraries(${PROJECT_NAME} PUBLIC igl::glfw  igl_copyleft::tetgen)
```
then use 
`cmake -DFETCHCONTENT_SOURCE_DIR_LIBIGL=/home/chenpeng/Documents/libigl/libigl ..`
 to build project, I get error message 
```
CMake Error at /home/chenpeng/Documents/libigl/libigl/cmake/igl/igl_include.cmake:32 (include):
  include could not find requested file:

    /home/chenpeng/Documents/libigl/libigl/cmake/igl/modules//tetgen.cmake
Call Stack (most recent call first):
  /home/chenpeng/Documents/libigl/libigl/cmake/igl/igl_include.cmake:54 (_igl_include_full)
  CMakeLists.txt:11 (igl_include)
```

how to fix it ?

**Comment by alecjacobson** [comment]
The syntax for `igl_include` is not very discoverable. The line

    igl_include(tetgen)

should be 

    igl_include(copyleft tetgen)

I think I'll "fix" this issue by adding some examples in the comments of the main CMakeLists.txt

**Comment by alecjacobson** [comment]
@jdumas , `LibiglOptions.cmake.sample` doesn't seem to use `igl_include`. Is it out of date or is it serving a different purpose?

Meanwhile do you have any suggestions on how to make this more discoverable/well documented?

**Comment by jdumas** [comment]
`LibiglOptions.cmake.sample` is for compiling libigl itself. It shouldn't use `igl_include()`. We do have an example of using `igl_include()` in the [example project](https://github.com/libigl/libigl-example-project/blob/9a3c3492fae96b0dc724557fb1b0ec7f3ea21dd1/CMakeLists.txt#L10). I can try to improve usability by throwing a better error message when the module is not found (e.g. missing `copyleft` keyword, etc.). But this will have to wait after May 23rd :D

**Comment by alecjacobson** [comment]
Ah thanks. That makes sense. Better error message helps. Also thinking
about best place to document this igl_include

**Comment by jdumas** [comment]
I'd say [the website](https://libigl.github.io/example-project/) is a good place to start. Maybe add comments to the example project cmake as well (with a commented out example of including a copyleft/restricted modules).
