### ISSUE TITLE
Has anyone built libigl's tutorials in Visual Studio with CMake?

### ISSUE THREAD

**Issue by ArashPix** [libigl/libigl#220]
I tried to use libigl by adding the the required libs to my C++ project and managed to debug the project without any issue. 
BUT, later I tried to run the tutorials in VS 2013. So I used CMake to generate the visual studio solutions of the tutorials in tutorial folder and ran into some issues like "could not find embree" . In below, I have attached an screen shot of the errors in CMake . It would be great if you could help me to solve this issue! 
![image](https://cloud.githubusercontent.com/assets/15247357/12698552/b88ae0f6-c79f-11e5-946c-5b3590ac6c19.png)

**Comment by danielepanozzo** [comment]
We have a working visual studio build of the tutorials done with appveyor: https://ci.appveyor.com/project/danielepanozzo/libigl-6hjk1

It works on a vanilla installation of VS 2015, please take a look there to find out why it is not working for you.
