### ISSUE TITLE
c89-gcc called with non ANSI/ISO C option -std=c99

### ISSUE THREAD

**Issue by Hassan-math** [libigl/libigl#2201]
#### Describe your issue
I was trying to build and use libigl example project. I am able to build it successfully via cmake in the terminal. However, when I want to use VSCode and CMake tool, I get the following errors:

[build] c89-gcc called with non ANSI/ISO C option -std=c99
[build] c89-gcc called with non ANSI/ISO C option -std=c99
[build] gmake[2]: *** [_deps/glfw-build/src/CMakeFiles/glfw.dir/build.make:76: _deps/glfw-build/src/CMakeFiles/glfw.dir/context.c.o] Error 1

I get many of these error during the building process. I reckon there is an incompatibility between gcc version and glfw lib in in the project.
FYI:
gcc version: gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
cmake version 3.22.1

I am using gcc and cmake tools extension in the VSCode. CMake is in debug mode.
#### Checklist

- [X] I have read the [bug report](https://libigl.github.io/bug-report/) page
- [X] CMake issue: I have tried with a fresh clone/empty build directory

#### Platform

- [ ] Windows
- [ ] macOS Intel
- [ ] macOS Arm (e.g., M1, M2)
- [X] Linux

**Comment by Hassan-math** [comment]
Just a quick update. I changed the compiler to clang. It works well. But I would like to know what was the problem with gcc if there is any idea

**Comment by alecjacobson** [comment]
Is -std=c99 incompatible with -std=c++11 ? We require C++11

**Comment by Hassan-math** [comment]
I removed gcc and installed it again. Now it works!
