### ISSUE TITLE
关于igl::harmonic函数加速问题

### ISSUE THREAD

**Issue by Yph0258691** [libigl/libigl#2203]
1:如果网格数量很多，此函数执行，非常慢，麻烦，问下，如何优化

**Comment by alecjacobson** [comment]
2D or 3D?

**Comment by Yph0258691** [comment]
3D

**Comment by Yph0258691** [comment]
麻烦，帮我优化下，谢谢

**Comment by alecjacobson** [comment]
First. Please be sure that you're running in release mode with compiler optimization. Eigen is very slow in debug mode.

Meanwhile, if you're running on a 3D tetrahedral mesh but you only care about the solution on the surface, then you could try using a graded tet mesh (bigger tets in the middle).

If you'd like, you could post some data and a minimal code snippet to try.

**Comment by Yph0258691** [comment]
Eigen is very slow in Release mode.

**Comment by Yph0258691** [comment]
mesh 的网格是总面片大小为10191

**Comment by Yph0258691** [comment]
![image](https://github.com/libigl/libigl/assets/20094370/5270c89c-f397-437d-9a30-2e526242e722)

**Comment by Yph0258691** [comment]
耗时时间为700多毫秒

**Comment by Yph0258691** [comment]
可以优化吗?

**Comment by waterrhett** [comment]
> 可以优化吗?

Instead of spamming everyone subscribed to issues, you could start by providing some data along with your minimal code snippet.

Besides, as it goes without saying, asking more concrete questions instead of "can you optimize it" gives you a much better chance of receiving constructive responses:
https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

**Comment by Yph0258691** [comment]
希望优化下。

**Comment by bobboli** [comment]
首先，正如上面提到的，如果你发现了性能问题，请提供一个最简单的、可运行的代码段，以此来让开发人员追踪性能问题；否则，你都没办法定义什么是快，什么是慢。
其次，这是一个开源项目，没有任何人有必要对你的“希望优化下”这种命令式口气的提问进行回应。你又不付给他们工资，开源项目的开发者都是自愿的，没有义务为你负责。

Firstly, as mentioned above, if you encounter performance issues, please provide a minimal, runnable code snippet to allow developers to track the performance problem. Otherwise, you won't be able to define what is fast and what is slow.
Secondly, this is an open-source project, and no one is obliged to respond to your command-like request like "please optimize it". You are not paying them a salary, and developers of open-source projects are volunteers who have no obligation to be accountable to you.

**Comment by Yph0258691** [comment]
楼上的，请问，那句话是命令的形式？

**Comment by Yph0258691** [comment]
问问题，变成命令的形式，我看，你中文，没学到家，@bobboli

**Comment by Yph0258691** [comment]
> 首先，正如上面提到的，如果你发现了性能问题，请提供一个最简单的、可运行的代码段，以此来让开发人员追踪性能问题；否则，你都没办法定义什么是快，什么是慢。 其次，这是一个开源项目，没有任何人有必要对你的“希望优化下”这种命令式口气的提问进行回应。你又不付给他们工资，开源项目的开发者都是自愿的，没有义务为你负责。
> 
> Firstly, as mentioned above, if you encounter performance issues, please provide a minimal, runnable code snippet to allow developers to track the performance problem. Otherwise, you won't be able to define what is fast and what is slow. Secondly, this is an open-source project, and no one is obliged to respond to your command-like request like "please optimize it". You are not paying them a salary, and developers of open-source projects are volunteers who have no obligation to be accountable to you.

希望优化，也是命令的形式？

**Comment by Yph0258691** [comment]
> 首先，正如上面提到的，如果你发现了性能问题，请提供一个最简单的、可运行的代码段，以此来让开发人员追踪性能问题；否则，你都没办法定义什么是快，什么是慢。 其次，这是一个开源项目，没有任何人有必要对你的“希望优化下”这种命令式口气的提问进行回应。你又不付给他们工资，开源项目的开发者都是自愿的，没有义务为你负责。
> 
> Firstly, as mentioned above, if you encounter performance issues, please provide a minimal, runnable code snippet to allow developers to track the performance problem. Otherwise, you won't be able to define what is fast and what is slow. Secondly, this is an open-source project, and no one is obliged to respond to your command-like request like "please optimize it". You are not paying them a salary, and developers of open-source projects are volunteers who have no obligation to be accountable to you.

你爱看不看，没必要在这说来说去

**Comment by waterrhett** [comment]
Could we just close this issue please? OP clearly has no intention of providing any useful data along with minimal code snippet for diagnosing/improving the performance. Apparently he is more interested in starting meaningless arguments.

**Comment by Yph0258691** [comment]
> 首先，正如上面提到的，如果你发现了性能问题，请提供一个最简单的、可运行的代码段，以此来让开发人员追踪性能问题；否则，你都没办法定义什么是快，什么是慢。 其次，这是一个开源项目，没有任何人有必要对你的“希望优化下”这种命令式口气的提问进行回应。你又不付给他们工资，开源项目的开发者都是自愿的，没有义务为你负责。
> 
> Firstly, as mentioned above, if you encounter performance issues, please provide a minimal, runnable code snippet to allow developers to track the performance problem. Otherwise, you won't be able to define what is fast and what is slow. Secondly, this is an open-source project, and no one is obliged to respond to your command-like request like "please optimize it". You are not paying them a salary, and developers of open-source projects are volunteers who have no obligation to be accountable to you.

要就用实力证明，要就沉默

**Comment by Yph0258691** [comment]
> 首先，正如上面提到的，如果你发现了性能问题，请提供一个最简单的、可运行的代码段，以此来让开发人员追踪性能问题；否则，你都没办法定义什么是快，什么是慢。 其次，这是一个开源项目，没有任何人有必要对你的“希望优化下”这种命令式口气的提问进行回应。你又不付给他们工资，开源项目的开发者都是自愿的，没有义务为你负责。
> 
> Firstly, as mentioned above, if you encounter performance issues, please provide a minimal, runnable code snippet to allow developers to track the performance problem. Otherwise, you won't be able to define what is fast and what is slow. Secondly, this is an open-source project, and no one is obliged to respond to your command-like request like "please optimize it". You are not paying them a salary, and developers of open-source projects are volunteers who have no obligation to be accountable to you.

要不就用实力证明，要不就沉默
