### ISSUE TITLE
unexpected results from principal_curvature

### ISSUE THREAD

**Issue by jochemspek** [libigl/libigl#221]
Hi there,

I'm trying to understand the results of principal_curvature. The results show negative curvature
(k1 being negative, k2 positive) where I expect both directions to be positive. Does anyone see
if and if so, why I'm misreading the results ? Attached are screenshots both from my own project using 
red color where any of the two directions has negative curvature (k1 or k2) and the same mesh shown
using the libigl viewer with it's ::jet coloring.

Thanks again,

Jonathan

![screen shot 2016-02-03 at 10 23 13](https://cloud.githubusercontent.com/assets/377154/12778292/53db897e-ca62-11e5-8679-c909822cc5ab.png)
<img width="746" alt="screen shot 2016-02-03 at 10 22 56" src="https://cloud.githubusercontent.com/assets/377154/12778294/53f30b62-ca62-11e5-8185-28c4dedf8c93.png">

**Comment by alecjacobson** [comment]
I'm guessing this is a meshing problem. Does it persist if you use a denser, less anisotropic mesh?

**Comment by jochemspek** [comment]
it gets better with higher resolution, yes. for me, that is very problematic. why would the given example go wrong in the first place ?

**Comment by alecjacobson** [comment]
extremely skinny triangles.

**Comment by jochemspek** [comment]
ah, i see.. it's a precision thing then ?

**Comment by alecjacobson** [comment]
Don't know for sure without looking into the specific example, but those
triangles are suspicious
