### ISSUE TITLE
Output isolines of Heat Geodesic not working as expected

### ISSUE THREAD

**Issue by danperazzo** [libigl/libigl#2230]
#### Describe the bug
I was working with the following a [mesh](https://github.com/libigl/libigl/files/12242921/test_mesh_quad.txt), which is a triangulation of a square. Using Polyscope for visualization, especially their integration libigl as a [template](https://github.com/nmwsharp/libigl-polyscope-project-template), I have noticed that the method to solve the heat geodesic seems to be giving this result:

![image](https://github.com/libigl/libigl/assets/39570908/d5c83bd1-562c-4a4b-ae69-ebe8ddc0ee67)
The thing that is strange is that it seems that the distance is also radiating from the top-left vertex as well. The snippet I used to compute the heat is just this:

`igl::readOBJ(filename, meshV, meshF);`
`Eigen::MatrixXd meshV;`
`Eigen::MatrixXi meshF;`
`int iVertexSource = 0;`
`igl::HeatGeodesicsData<double> data;`
`igl::heat_geodesics_precompute(meshV,meshF,1.,data);`
`Eigen::VectorXd dist;`
`igl::heat_geodesics_solve(data, (Eigen::VectorXi(1,1)<<iVertexSource).finished(), dist);`

I have also anexed the `main.cpp` file I have been using for these tests. [Its here](https://github.com/libigl/libigl/files/12243186/main.txt).

I have also compared with [potpourri3d](https://github.com/nmwsharp/potpourri3d/tree/master), just to get a comparison, and in there the results for the isolines seem to be as expected, as seen bellow:

![image](https://github.com/libigl/libigl/assets/39570908/7c0b0b7f-2701-4b29-a2a6-343aa59d4ccf)

Thanks for the attention!
#### Platform

- [ ] Windows
- [ ] macOS
- [X]  Linux

**Comment by alecjacobson** [comment]
```
igl::heat_geodesics_precompute(meshV,meshF,1.,data);
```

this is using `t=1` for the time parameter this is way too big. The heat geodesics _papers_ provide different recommendations, but potpourri3d and libigl both use average-edge-length² by default. 

_note: potpourri's `t_coeff` parameter gets multiplied _against_  average-edge-length². So using `t_coeff=1` in potpourri would correspond to using `t=average-edge-length²` in libigl._

For reference here's the result in the 806_HeatGeodesic tutorial 
<img width="592" alt="Screen Shot 2023-08-20 at 12 32 35 PM" src="https://github.com/libigl/libigl/assets/2241689/8948adf7-7717-4f9b-9805-bd69c51d74a5">


Please reopen if this isn't resolved.
