### ISSUE TITLE
Fatal error compiling project with VC++

### ISSUE THREAD

**Issue by wucm1994** [libigl/libigl#224]
When I compiled my project based on libigl with VC++ 2015, a fatal error C1001 occurred and stopped compiling at the linking stage. I fixed the problem by changing optimization option from /O2 to /Ox, hopefully this would be helpful to someone who uses libigl with VC++ like me.

**Comment by danielepanozzo** [comment]
Thank you for the report. I cannot reproduce this on my win 10 + vanilla VS 2015 community edition. Which version of VS are you using?

**Comment by e4lam** [comment]
FYI, I've made some build fixes on Windows in pull request #249

**Comment by alecjacobson** [comment]
Unless we can narrow in on a small libigl example, I'm chalking this up to "windows esotericism"
