### ISSUE TITLE
The "Main Page" of the libigl Documentation is an empty page

### ISSUE THREAD

**Issue by asmwarrior** [libigl/libigl#2248]
Hi, when I open the main document page:  [libigl: Main Page](https://libigl.github.io/dox/index.html)

It just shows empty. 

see the image show here:
![image](https://github.com/libigl/libigl/assets/561818/5fab58ef-0a70-4e84-9422-43370eb6a68c)

I think in your Doxygen style comment, you need to add some descriptions about the main page, there is a [Doxygen Manual: Special Commands](https://www.doxygen.nl/manual/commands.html#cmdmainpage) which can do this.

Thanks.

**Comment by alecjacobson** [comment]
It's here https://github.com/libigl/libigl/blob/main/docs/index.md just haven't pushed onto the GitHub.io site yet

**Comment by alecjacobson** [comment]
it's live now.

**Comment by asmwarrior** [comment]
Thanks. I see the updates.
