### ISSUE TITLE
Question - How do you pick the Handle_Seams in cut_mesh_by_singularities?

### ISSUE THREAD

**Issue by stigersh** [libigl/libigl#225]
I've tried to understand how do you choose the edges Handle_Seams in cut_mesh_by singularities, but got confused. It would be nice if you could help me understand..
I fail to see where the algorithm chooses edges which are not "Rotation Seams".
The cut method initialize Handle_Seams to ones, and is comprised of 3 parts: 
    1. Running flood fill and zeroing the edges which are not "Rotation Seams" + not zeroing some "other edges" - but which and why? When a non rotation seam edge will not be zeroed? If one of its adjacent triangles was visited, it was supposed to be zeroed then..
Another thing is, why do you need both (!(IsRotSeam(f,s))) && (!(IsRotSeam(g,j))- aren't they the same for the same edge?
    2. Retract part - zeroing some more of the "other edges" in Handle_Seams, I didn't understand again which ones (and why them?)..  
    3. Going over the edges which are Rotation Seams and making sure they are true in Handle_Seams - why wouldn't they be at this point, they are never zeroed

Thanks,
Anna

**Comment by olkido** [comment]
Hi Anna,
This function performs the cutting essentially as described in the Mixed Integer Quadrangulation paper, Section 5, "Cutting the Mesh". 
1. The function FloodFill() creates a dual spanning tree - it is leaving "un-zeroed" the rotation edges, as well as a set of non-rotation edges such that the graph of "non-zeroed" edges forms a tree (note the && (!F_visited(g))  clause). With regards to your question regarding  (!(IsRotSeam(f,s))) && (!(IsRotSeam(g,j)), yes you are right these two should be the same, but it's there just for safety.
2. The Retract() function is cleaning up this tree, as described in the paper, "by iteratively removing all open paths". I think the easiest way to see this is by running the code on various examples (e.g. a sphere, a cylinder, and maybe a torus), and disabling the retract() temporarily to see what happens. You will notice that the floodfill generates too many cut edges that are not topologically needed, and retract removes them, while keeping the minimal set of edges that should be cut.
3. Again you might be right that this is redundant, it might just be safety code.
Hope this helps!
best,
--
olga

**Comment by stigersh** [comment]
Thanks, it helped a lot! One thing, the cut is not necessarily a tree, for instance for the torus. Anyway, I got the method and the reference to the mixed integer paper helped too. 
Best, 
Anna
