### ISSUE TITLE
AABB::squared_distance asserts

### ISSUE THREAD

**Issue by RogersDoug** [libigl/libigl#226]
I am hitting the assert in AABB::squared_distance frequently and getting incorrect results.

```

template <typename DerivedV, int DIM>
inline typename igl::AABB<DerivedV, DIM>::Scalar
igl::AABB<DerivedV, DIM>::squared_distance(
    const Eigen::PlainObjectBase<DerivedV> & V,
    const Eigen::MatrixXi & Ele,
    const RowVectorDIMS & p,
    Scalar min_sqr_d,
    int & i,
    RowVectorDIMS & c) const
{
    using namespace Eigen;
    using namespace std;
    Scalar sqr_d = min_sqr_d;
    //assert(DIM == 3 && "Code has only been tested for DIM == 3");
    assert((Ele.cols() == 3 || Ele.cols() == 2 || Ele.cols() == 1)
        && "Code has only been tested for simplex sizes 3,2,1");

    assert(m_primitive==-1 || (m_left == NULL && m_right == NULL)); <------------ THIS ASSERT


```

Here is the calling code:

```
    MatrixXf VM;
    MatrixXi FM;
    igl::AABB<MatrixXf, 3> tree;

    bool V_rect = igl::list_to_matrix(V, VM);
    bool F_rect = igl::list_to_matrix(F, FM);


    // Precompute signed distance AABB tree
    tree.init(VM, FM);

    RowVector3f q3(p.x, p.y, p.z);
    RowVector3f c3;

    float dist2 = tree.squared_distance(VM, FM, q3, i, c3);

```

Note if you change:
`if (is_leaf() )`
to
`if (is_leaf() && m_left == NULL && m_right == NULL)`
you get the correct results for the closest point.

This [(https://dl.dropboxusercontent.com/u/85781814/asserts.obj)] is an obj dump of a mesh and point that cause the assert.  The query point and the correct closest point form a degenerate triangle to represent a line. The points are in the group 'line' and are in the last triangle.

**Comment by alecjacobson** [comment]
Thanks, I'll look into this ASAP. Might be the result of some recent
changes...

**Comment by RogersDoug** [comment]
I'm am getting a different assert for meshes that have a single face, also.

In DenseCoeffsBase.h, line 114:
 ```
     eigen_assert(row >= 0 && row < rows()
          && col >= 0 && col < cols());
```
When calling ClosestPtPointTriangle in point_simplex_squared_distance.cpp, line 98.  
Called from leaf_squared_distance

**Comment by alecjacobson** [comment]
I can't reproduce these problems. Could you post a small but full .cpp main function which causes these asserts to fire? With this `asserts.obj` mesh, which query point is causing asserts or computing incorrect values? If I just probe with random points, things seem ok...

**Comment by RogersDoug** [comment]
Sure.  I get something soon.

**Comment by RogersDoug** [comment]
I cannot repro in a standalone either.  However, I am using the same tree for different mesh inquiries.  I changed the code to use a new tree for each new mesh to be queried and the assert did not occur.  So it looks like the init code is not completely resetting the tree,

**Comment by alecjacobson** [comment]
ah, interesting. I'll see if there's a problem there.

**Comment by alecjacobson** [comment]
right, one must call `deinit` before trying to re-initialize the same
instance. Or you can just create a new instance as you're now doing.

**Comment by RogersDoug** [comment]
I can add that code, but shouldn't deinit be called by init?

**Comment by alecjacobson** [comment]
I can't see why not.
