### ISSUE TITLE
Multiple definition while cannot find where the definitions are

### ISSUE THREAD

**Issue by 010722** [libigl/libigl#2263]
#### Describe the bug

/root/anaconda3/envs/contess/bin/ld: ../_external/predicates-build/libpredicates.a(predicates.c.o):(.bss+0x28): multiple definition of `iccerrboundA'; ../_external/triangle-build/libtriangle.a(triangle.c.o):(.bss+0x30): first defined here

#### Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

**Comment by alecjacobson** [comment]
What if you try just using target link libraries ig_restricted::triangle?

**Comment by 010722** [comment]
Solved. Thanks https://molcasforum.univie.ac.at/viewtopic.php?id=714

**Comment by alecjacobson** [comment]
Cool. Could you explain what the solution was?
