### ISSUE TITLE
Reading .vert and .tri?

### ISSUE THREAD

**Issue by lukkio88** [libigl/libigl#2265]
Hello,

I just downloaded the TOSCA dataset and there are meshes represented using two files, one for triangles and for vertices.

Before I reinvent the wheel is there a libigl method to read such files?
From my exploration of the repo it does not look like it.

**Comment by alecjacobson** [comment]
I don't remember what that dataset looks like and it seems no longer hosted(?).  I'd need more information to know if we have IO routines for it.

**Comment by lukkio88** [comment]
This is the dataset: https://tosca.cs.technion.ac.il/book/resources_data.html

If you download the ascii format that's what I am talking about.

**Comment by alecjacobson** [comment]
Thanks. No, libigl doesn't have this directly. Looks like space separated matrix dump into ascii. Similar to .dmat
