### ISSUE TITLE
igl::signed_distance

### ISSUE THREAD

**Issue by JianlayWang** [libigl/libigl#2273]
#### Describe your issue

When I use the signed_distance function, the function reports an error "In template: static assertion expression is not an integral constant expression", but there is no problem with the running results. Is there a good solution to this problem? Or is there something wrong with my code?
![image](https://github.com/libigl/libigl/assets/138512306/2457e92c-3a26-46f6-8bec-9fc824d8bed4)
![image](https://github.com/libigl/libigl/assets/138512306/c6eb70b8-c650-4b93-afba-543a01d7fcf8)

The IDE is Clion. The strange thing is that on Visual Studio 2022, the code does not report an error.
![image](https://github.com/libigl/libigl/assets/138512306/2bed77ba-cdc4-41b1-b396-4627c609dc2b)

#### Checklist

- [x] I have read the [bug report](https://libigl.github.io/bug-report/) page
- [ ] CMake issue: I have tried with a fresh clone/empty build directory

#### Platform

- [x] Windows
- [ ] macOS Intel
- [ ] macOS Arm (e.g., M1, M2)
- [ ] Linux

**Comment by alecjacobson** [comment]
Is the error stopping compilation or just a warning?

Looks like the error is actually coming from FastWindingNumberForSoups.h. Could you please try to pinpoint more precisely the line of code where the assertion is occurring?

I didn't write that file so it's a little harder to debug. When you use Clion is `_MSC_VER` defined?

**Comment by JianlayWang** [comment]
This code shows errors, but it does not affect compilation and operation, and the result is correct.

**Comment by alecjacobson** [comment]
huh. well, I guess then without much more information or misbehaviour it's ok to ignore.

**Comment by JianlayWang** [comment]
Thank you very much for your reply. I will look into the problem in more detail and contact you again.
