### ISSUE TITLE
I test the example of  408_DirectDeltaMush, have a probleam?

### ISSUE THREAD

**Issue by tvshow5727** [libigl/libigl#2278]
#### Describe your issue

I  compile the whole code successfully; 
when  I test the 408_DirectDeltaMush/main.cpp , I would like to know the content of this file [elephant-anim.dmat ];  this file contains the rotation and translation of each bone，How are these rotation and translation data calculated？？
I am a student and I want to learn this knowledge .
I am looking forward to your replay; thank you very much;

**Comment by alecjacobson** [comment]
Mixamo
