### ISSUE TITLE
Wrong line ending on freshly cloned repository on linux

### ISSUE THREAD

**Issue by evan-barentin** [libigl/libigl#2287]
Hello

#### Describe the bug

When cloning a fresh copy of libigl from github on the `main` branch, the line ending of some file in the `tutorial` folder and a few others are not correctly set.

As a consequence, the repository is not clean and switching branches is quite difficult.

This behavior was confirmed on archlinux, ubuntu 22.04 and debian 10. The test used was this command line: 
```sh
git clone https://github.com/libigl/libigl.git /tmp/libigl && git -C /tmp/libigl status
```

#### Platform

- [ ] Windows
- [ ] macOS
- [x] Linux

Thanks for your work on this library and have a nice day !

**Comment by alecjacobson** [comment]
Not sure what to about this as I never experienced this problem on Linux.
Feel free to pr something

**Comment by alecjacobson** [comment]
Is this related to that . gitattributes change?

**Comment by evan-barentin** [comment]
> Is this related to that . gitattributes change?

I think it is, everything worked fine last week.

To avoid any unexpected behavior with my & other setups, I cloned the repository in a fresh debian docker with the following commands and the line ending problem is still there :

```sh
docker run --rm -ti debian:11
apt update && apt install -y git
git clone https://github.com/libigl/libigl.git /tmp/libigl && git -C /tmp/libigl status
```

Did you perhaps set some option related to line ending in your main configuration file ?

**Comment by evan-barentin** [comment]
After reading https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings I commit all line ending changes in this PR

https://github.com/libigl/libigl/pull/2288

**Comment by evan-barentin** [comment]
https://github.com/libigl/libigl/pull/2288 was merged, this issue is no longer relevant :)
