### ISSUE TITLE
Compiler error when using AABB<MatrixXd,2>::find(...) 

### ISSUE THREAD

**Issue by trnglt** [libigl/libigl#2291]
#### Describe your issue

Compiler error when using AABB<MatrixXd,2>::find(...)

I'm trying to use AABB::find to identify which triangles on a surface contain q.
Within AABB::find() I see the following code:

    switch(DIM)
    {
      case 3:
        {
          // Barycentric coordinates
          typedef Eigen::Matrix<Scalar,1,3> RowVector3S;
          const RowVector3S V1 = V.row(Ele(m_primitive,0));
...

DIM is 2, but the compiler still tries to compile this case, generating an error from Eigen concerning the casting of my V.row with 2 values to a 3-vector (AABB.cpp line 238)

I have a workaround for my case - happy to share - but it's insufficiently elegant to contribute to libigl!

I hope this is of some help. Thanks for the great library!

Bill
#### Checklist

- [x] I have read the [bug report](https://libigl.github.io/bug-report/) page
- [ ] CMake issue: I have tried with a fresh clone/empty build directory

#### Platform

- [ ] Windows
- [ ] macOS Intel
- [x] macOS Arm (e.g., M1, M2)
- [ ] Linux

**Comment by alecjacobson** [comment]
Do you have a small example that I can try to debug?

**Comment by trnglt** [comment]
The following compiles and runs as-is. Uncomment line 43 near the end, and my compiler produces an error.

#include <igl/AABB.h>

Eigen::MatrixXd V(6,2),V3(7,3);
Eigen::MatrixXi F(4,3),F3(4,4);

int main(int argc, char *argv[])
{

  // A 2D mesh
  V << 0,0,
    1,0,
    0,1,
    2,1,
    2,2,
    1,2;

  V3 << 0,0,1,
      1,0,1,
    0,1,1,
    2,1,1,
    2,2,1,
    1,2,1,
    0,0,0;

  F3 << 0,1,2,6,
    1,3,2,6,
    3,4,5,6,
    3,5,1,6;

  std::cout << "Set up tree"<<std::endl;
  igl::AABB<Eigen::MatrixXd,3> tree3;
  tree3.init(V3,F3);
  Eigen::RowVector3d q3;
  q3 << 0.5,0.5,1.0;
  std::cout << "Call find"<<std::endl;
  std::vector<int> r = tree3.find(V3,F3,q3);
  std::cout << "Print results"<<std::endl;

  igl::AABB<Eigen::MatrixXd,2> tree;
  tree.init(V,F);
  Eigen::RowVector2d q;
  q << 0.5,0.5;
  // std::vector<int> r = tree.find(V,F,q);


  std::cout << "r = ";
  for (std::vector<int>::iterator riter = r.begin(); riter != r.end(); riter++) {
    std::cout << *riter << " ";
  }

  
  std::cout<<std::endl;
  std::cout << "Done"<<std::endl;
}

**Comment by alecjacobson** [comment]
Confirmed. Here's a bit smaller version with the eaten <> restored

```cpp
#include <igl/AABB.h>

int main(int argc, char *argv[])
{
  // A 2D mesh
  Eigen::MatrixXd V(6,2);
  V << 
  0,0,
  1,0,
  0,1,
  2,1,
  2,2,
  1,2;
  Eigen::MatrixXi F(4,3);
  F<< 
  2,0,1,
  2,1,5,
  5,3,4,
  5,1,3;
  
  igl::AABB<Eigen::MatrixXd,2> tree;
  tree.init(V,F);
  Eigen::RowVector2d q(0.5,0.5);
  std::vector<int> r = tree.find(V,F,q);
}
```

This is a bug.

**Comment by alecjacobson** [comment]
I think this can be fixed with a similar widget as I used in signed_distance recently. I'll take a stab at it.

**Comment by trnglt** [comment]
Awesome! Are a lot of people not up to C++-17 yet? Really appreciate all the great work you're doing!
