### ISSUE TITLE
libigl version in CMakeLists.txt

### ISSUE THREAD

**Issue by BruegelN** [libigl/libigl#2298]
#### Describe the bug
The version string within the root CMakeLists.txt still says it's 2.4.0.

This is the case for
* current main:
https://github.com/libigl/libigl/blob/7991ee81d81bd8a58df261f2b6cc782a77d57ec2/CMakeLists.txt#L40

* release tag v2.5.0:
https://github.com/libigl/libigl/blob/v2.5.0/CMakeLists.txt#L40

With each release I would expected the version to match that release version e.g. for the latest release:
```
project(libigl VERSION 2.5.0)
```

#### Platform

- [x] Windows
- [x] macOS
- [x] Linux

**Comment by alecjacobson** [comment]
Oh, thanks. I didn't even realize this was here.

**Comment by BruegelN** [comment]
It's not a major flaw (for me) but just something to add to the "release checklist" for all upcoming releases 🙂
