### ISSUE TITLE
Python Bindings: Data Deserialization Segfault

### ISSUE THREAD

**Issue by s-koch** [libigl/libigl#231]
The tcpviewer.py segfaults with Python3.4 on Ubuntu 15.10. I could track the problem back to the deserialization of the viewer data and created the following minimal working example that reproduces the segfault on my machine (crashes on the last line):

```
import sys, os
sys.path.insert(0, os.getcwd() + "/../")
import igl

V = igl.eigen.MatrixXd()
F = igl.eigen.MatrixXi()
igl.readOFF("../../tutorial/shared/2triangles.off", V, F)

viewer = igl.viewer.Viewer()
viewer.data.set_mesh(V, F)
s = viewer.data.serialize()
viewer.data.deserialize(s)
```

Is this maybe OS dependent?

**Comment by alecjacobson** [comment]
Is this still relevant/an issue?

**Comment by s-koch** [comment]
I am checking it and will come back to you soon...
