### ISSUE TITLE
LNK1104	could not open file“..\lib\Debug\igl.lib”

### ISSUE THREAD

**Issue by wanxnyi** [libigl/libigl#2317]
#### Describe your issue

win11,VS2022
My Compilation Process：
+ git clone the libigl from github
+ mkdir "build" directory
+ use cmake to configure and generate a sln.(I'm confused. The name of the SLN I generated here is “getInfo.sln”, why not "libigl.sln"?)
+ remake the ALL_BUILD
My errors:
+ 31 successed,89failed.
+ LNK1104: could not open file “..\lib\Debug\igl.lib”

When I opened this directory, I found that there was no file called "igl. lib" here, only a file called "igl. pdb", and other files in the same directory appeared in pairs in both “lib” and “pdb” formats.

I don't know why this is? Why can't I compile successfully? The file “igl. lib” is not in the directory?

No one knows the solution, thank you very much

#### Checklist

- [ ] I have read the [bug report](https://libigl.github.io/bug-report/) page
- [ ] CMake issue: I have tried with a fresh clone/empty build directory

#### Platform

- [x] Windows
- [ ] macOS Intel
- [ ] macOS Arm (e.g., M1, M2)
- [ ] Linux

**Comment by Forest1Ice** [comment]
I have exactly the same problem. Do you know how to fix it now? Thank you very much.

**Comment by Dididididi-Wu** [comment]
> #### Describe your issue
> win11,VS2022 My Compilation Process：
> 
> * git clone the libigl from github
> * mkdir "build" directory
> * use cmake to configure and generate a sln.(I'm confused. The name of the SLN I generated here is “getInfo.sln”, why not "libigl.sln"?)
> * remake the ALL_BUILD
>   My errors:
> * 31 successed,89failed.
> * LNK1104: could not open file “..\lib\Debug\igl.lib”
> 
> When I opened this directory, I found that there was no file called "igl. lib" here, only a file called "igl. pdb", and other files in the same directory appeared in pairs in both “lib” and “pdb” formats.
> 
> I don't know why this is? Why can't I compile successfully? The file “igl. lib” is not in the directory?
> 
> No one knows the solution, thank you very much
> 
> #### Checklist
> * [ ]  I have read the [bug report](https://libigl.github.io/bug-report/) page
> * [ ]  CMake issue: I have tried with a fresh clone/empty build directory
> 
> #### Platform
> * [x]  Windows
> * [ ]  macOS Intel
> * [ ]  macOS Arm (e.g., M1, M2)
> * [ ]  Linux

You can take a look at those errors at the bottom in VS, it looks like there are emoji emoticons in the code, just comment out those printf statements.
