### ISSUE TITLE
How can I create a Checkbox in libigl?

### ISSUE THREAD

**Issue by wucm1994** [libigl/libigl#233]
Hi! I want to add a Checkbox to my viewer in libigl. However, I can only add **variable**, **button**, **variable**, **widget** and **window** by viewer.ngui default member functions. After referring to example2 in Nanogui,  I add the following code but failed.

```
CheckBox *cb = new CheckBox(viewer.ngui->window(), "Flag 1",
    [](bool state) { cout << "Check box 1 state: " << state << endl; }
);
cb->setChecked(true);
```

Can anyone help me on solving this problem and add a customized Checkbox? Thanks in advance.

**Comment by alecjacobson** [comment]
Try posting this to the nanogui issues page
