### ISSUE TITLE
Change in API in tetrahedralize

### ISSUE THREAD

**Issue by dyollb** [libigl/libigl#2337]
#### Describe your issue

In this [commit](https://github.com/dyollb/libigl/commit/1b07ebcf9e18c33ba342fd5c945dedbda055df78) the API of tetrahedralize was changed probably to reduce maintenance.

The `std::vector` allowed to mesh polygons with different numbers of vertices (quads, triangles, ...) and segments.
This is how I previously created meshes with embedded skeleton bones/joints for running animations with BBW/LBS/DDM.

I would be happy to add something that works. Here are some ideas
- re-add std::vector api
- use a convention, e.g. process vertices of polygon until a `-1` is found (for quads, triangles and segments F would have shape Nx4)
- add extra argument(s), e.g. `Eigen::MatrixXi S` for segments

#### Checklist

- [x] I have read the [bug report](https://libigl.github.io/bug-report/) page
- [x] CMake issue: I have tried with a fresh clone/empty build directory

#### Platform

- [x] Windows
- [x] macOS Intel
- [x] macOS Arm (e.g., M1, M2)
- [x] Linux

**Comment by alecjacobson** [comment]
you're right. it did support polygons before. The `-1` convention is reasonable and would result in the smallest change. Is there any reason not to support segments in the same way? (i.e., a row in `F` with a `-1` in the 3rd column?

**Comment by dyollb** [comment]
Great. No, segments are just polygons with two vertices.
