### ISSUE TITLE
Control stopping criteria for mesh decimation

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#234]
From personal email...

> First of all, thank you so much for developing  the libigl project  I was looking for a lightweight library to treat meshes and IGL seems to be pretty awesome. 
> 
> I have a question regarding mesh decimation. Starting from tutorual 703, I tried testing both the decimate() and collapse_edge() functions, as mentioned in your webpage. I don't have openGL installed, so I erased viewer-related code. Please find my code attached. 
> 
> My question:
> - No matter how I change the max_m value, the decimate function always erases only 3 vetices and 6 factes. This si true for any meshes I tested it on from the share folder. Am I missing something?
> 
> Any clue?

**Comment by alecjacobson** [comment]
The demo in `703_Decimation` is written to continuously decimate the model until nothing's left. If you're looking for better control for stopping the decimation, have a look at `include/igl/decimate.h` this provides two interfaces: one using the default stopping criteria based on the maximum number of remaining faces, and the other is fully programmable (pass a function handle which determines when to quit, e.g., based on some distance you might compute etc).

**Comment by niccolooo** [comment]
Thank you Alec, 

Now I understand. However,

` igl::decimate(OV, OF, max_m, V, F);`

does not seem to return false when F.rows() is smaller than max_m . source code:

```
#include <igl/circulation.h>
#include <igl/collapse_edge.h>
#include <igl/decimate.h>
#include <igl/edge_flaps.h>
#include <igl/read_triangle_mesh.h>
#include <igl/writeOBJ.h>
#include <Eigen/Core>
#include <iostream>
#include <set>
#include "tutorial_shared_path.h"

int main(int argc, char * argv[])
{
  using namespace std;
  using namespace Eigen;
  using namespace igl;

  string filename(TUTORIAL_SHARED_PATH "/xcylinder.obj");

  cout << "  'working on'  = " <<  filename << endl;

  if(argc>=2)
  {
    filename = argv[1];
  }
  MatrixXd V,OV;
  MatrixXi F,OF;
  read_triangle_mesh(filename,OV,OF);

  // save a copy of the original mesh
  igl::writeOBJ("original.obj", OV, OF);
	
  cout << "  'decimation started ...";

  int max_m = (int) round(OF.rows() / 2);

  bool keep_decimating = true;
  while (keep_decimating){
	  keep_decimating = igl::decimate(OV, OF, max_m, V, F);
	  OV = V;
	  OF = F;	
	  cout << "  mesh containts " << V.rows() << " vertices and " << F.rows() << " faces" << endl;
	  //keep_decimating = (F.rows() > max_m);
  }

  igl::writeOBJ("decimated.obj", V, F);

  cout << "  final decimated mesh containts " << V.rows() << " vertices and " << F.rows() << " faces" << endl;
  //cout << "  ----- vertices ----- \n " << V << endl;
  //cout << "  ----- faces ----- \n " << F << endl;


  system("PAUSE");

  return 1;

}
```

OUTPUT:
```
  'working on'  = ../shared/xcylinder.obj

  'decimation started ...  mesh containts 41 vertices and 78 faces
  mesh containts 40 vertices and 76 faces
  mesh containts 39 vertices and 74 faces
  mesh containts 38 vertices and 72 faces
  mesh containts 37 vertices and 70 faces
  mesh containts 36 vertices and 68 faces
  mesh containts 35 vertices and 66 faces
  mesh containts 34 vertices and 64 faces
  mesh containts 33 vertices and 62 faces
  mesh containts 32 vertices and 60 faces
  mesh containts 31 vertices and 58 faces
  mesh containts 30 vertices and 56 faces
  mesh containts 29 vertices and 54 faces
  mesh containts 28 vertices and 52 faces
  mesh containts 27 vertices and 50 faces
  mesh containts 26 vertices and 48 faces
  mesh containts 25 vertices and 46 faces
  mesh containts 24 vertices and 44 faces
  mesh containts 23 vertices and 42 faces
  mesh containts 22 vertices and 40 faces
  mesh containts 21 vertices and 38 faces
  mesh containts 20 vertices and 36 faces
  mesh containts 19 vertices and 34 faces
  mesh containts 18 vertices and 32 faces
  mesh containts 17 vertices and 30 faces
  mesh containts 16 vertices and 28 faces
  mesh containts 15 vertices and 26 faces
  mesh containts 14 vertices and 24 faces
  mesh containts 13 vertices and 22 faces
  mesh containts 12 vertices and 20 faces
  mesh containts 11 vertices and 18 faces
  mesh containts 10 vertices and 16 faces
  mesh containts 9 vertices and 14 faces
  mesh containts 8 vertices and 12 faces
  mesh containts 7 vertices and 10 faces
  mesh containts 6 vertices and 8 faces
  mesh containts 5 vertices and 6 faces
  mesh containts 4 vertices and 4 faces
  mesh containts 4 vertices and 4 faces
  final decimated mesh containts 4 vertices and 4 faces
Press any key to continue . . .
```

**Comment by alecjacobson** [comment]
This seems like a bug. Seems like `igl::decimate` always removes two edges
(it does the first edge collapse before questioning the stopping criteria).

**Comment by niccolooo** [comment]
I see. I'll have a closer look at the igl::collapse_edge function. I tried using igl::decimate to halve the faces of armadillo. 

 'working on'  = ../shared/armadillo.obj
time to read: ../shared/armadillo.obj: 2.815s
time to halve the faces: 2234.8s

Given the run time required, perhaps using the high-level interface of igl::decimation is not a good idea.

**Comment by alecjacobson** [comment]
I'm worried something is wrong with your compiler setup/machine. On my 2011
macbook air using clang, I can read the armadillo in 0.5s and remove 1/2
the faces in 0.96s.

**Comment by niccolooo** [comment]
Indeed, I have to check this. Thank you for the benchmarks. 

Are you using decimate() or collapse_edge() ?

**Comment by alecjacobson** [comment]
I'm just using igl::decimate directly

**Comment by niccolooo** [comment]
The computational overhead can be avoided launching the executable from outside Visual Studio. (As mentioned in [another issue](https://github.com/libigl/libigl/issues/235) . Quite impressive though how heavy VS can be
