### ISSUE TITLE
Cannot run tutorial examples that use CGAL (Windows 11)

### ISSUE THREAD

**Issue by ioannaMitropoulou** [libigl/libigl#2350]
#### Describe your issue
I have downloaded the libigl repository (most recent commit: fe65ecb), and I followed the CMake steps to create a Visual Studio solution with all the tutorial examples, and everything worked normally. When I run most of the examples, they work as expected, but I cannot run any of the examples that contain CGAL. In particular, when I run **609_Boolean** or **610_CSGTree**, they compile normally, but when they run (both in Debug and Release mode), I get the following error; 
<img width="335" alt="image" src="https://github.com/libigl/libigl/assets/17250275/fdf6967b-efc1-4f14-ab9b-8a972f7a5988">

It seems to me that there is a problem with the CGAL installation. Could you help me to resolve this? 
Thank you!!

In the output window I see the following 

```
'610_CSGTree.exe' (Win32): Loaded 'C:\dev\libigl\build\bin\Debug\610_CSGTree.exe'. Symbols loaded.
'610_CSGTree.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. 
'610_CSGTree.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. 
'610_CSGTree.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. 
'610_CSGTree.exe' (Win32): Loaded 'C:\Windows\System32\user32.dll'. 
'610_CSGTree.exe' (Win32): Loaded 'C:\Windows\System32\win32u.dll'. 
'610_CSGTree.exe' (Win32): Loaded 'C:\Windows\System32\gdi32.dll'. 
'610_CSGTree.exe' (Win32): Loaded 'C:\Windows\System32\gdi32full.dll'. 
'610_CSGTree.exe' (Win32): Loaded 'C:\Windows\System32\msvcp_win.dll'. 
'610_CSGTree.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. 
'610_CSGTree.exe' (Win32): Loaded 'C:\Windows\System32\shell32.dll'. 
'610_CSGTree.exe' (Win32): Loaded 'C:\Windows\System32\comdlg32.dll'. 
'610_CSGTree.exe' (Win32): Loaded 'C:\Windows\System32\combase.dll'. 
'610_CSGTree.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. 
'610_CSGTree.exe' (Win32): Loaded 'C:\Windows\System32\SHCore.dll'. 
'610_CSGTree.exe' (Win32): Loaded 'C:\Windows\System32\shlwapi.dll'. 
'610_CSGTree.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. 
'610_CSGTree.exe' (Win32): Loaded 'C:\Windows\System32\libmpfr-4.dll'. 
'610_CSGTree.exe' (Win32): Unloaded 'C:\Windows\System32\libmpfr-4.dll'
'610_CSGTree.exe' (Win32): Loaded 'C:\Windows\System32\libmpfr-4.dll'. 
'610_CSGTree.exe' (Win32): Unloaded 'C:\Windows\System32\libmpfr-4.dll'
The thread 0x74cc has exited with code 3221225595 (0xc000007b).
The thread 0x6398 has exited with code 3221225595 (0xc000007b).
The program '[17104] 610_CSGTree.exe' has exited with code 3221225595 (0xc000007b).
```

#### Checklist

- [X] I have read the [bug report](https://libigl.github.io/bug-report/) page
- [X] CMake issue: I have tried with a fresh clone/empty build directory

#### Platform

- [X] Windows
- [ ] macOS Intel
- [ ] macOS Arm (e.g., M1, M2)
- [ ] Linux

**Comment by alecjacobson** [comment]
It's hard for me to debug on Windows but you might try the most recent commit on main. I don't think it will change your problem but it's at least compiling and running the cgal related tests on github actions on windows https://github.com/libigl/libigl/actions/runs/7967097114/job/21749359719

**Comment by ioannaMitropoulou** [comment]
Thank you for the quick update! With the updates actually, my problem is fixed! I can now run both examples 609 and 610.
