### ISSUE TITLE
Explicit fallthroughs?

### ISSUE THREAD

**Issue by r-barnes** [libigl/libigl#2353]
#### Describe the bug
Looking at [this line of code](https://github.com/libigl/libigl/blob/main/include/igl/signed_distance.cpp#L64) it's unclear to me whether the fallthrough is intentional or not.

Since C++17 the `[[fallthrough]]` attribute can be used to make fallthroughs explicit.

Is it possible to use it here (and elsewhere) if appropriate?

#### Platform

- [X] Windows
- [X] macOS
- [X] Linux

**Comment by alecjacobson** [comment]
I'm pretty sure this case is a bug.

We're currently stuck on C++11 but I'm feeling the itch for C++17 or later. Maybe for a future date.
