### ISSUE TITLE
GMP cannot build

### ISSUE THREAD

**Issue by avaxman** [libigl/libigl#2378]
#### Checklist

- [ ] I have read the [bug report](https://libigl.github.io/bug-report/) page
- [X] CMake issue: I have tried with a fresh clone/empty build directory

#### Platform

- [ ] Windows
- [ ] macOS Intel
- [X] macOS Arm (e.g., M1, M2)
- [ ] Linux

When building a project that uses CGAL, I get:

"checking for suitable m4... configure: error: No usable m4 in $PATH or /usr/5bin (see config.log for reasons)."

which pertains to the building of GMP. It then prompts to install XCode command line which is already installed. I think there is a problem that they don't identity m4, but that breaks the libigl+ cgal compilation... is there a workaround?

**Comment by jdumas** [comment]
Maybe you need to install [m4](https://formulae.brew.sh/formula/m4) via homebrew?

**Comment by avaxman** [comment]
It had already installed it. Update: having actually installed *xcode* rather than just the command line, it seems to be compiling...

**Comment by avaxman** [comment]
(however it's not great that one has to install xcode. Perhaps it would be possible to give preinstalled GMP?)
