### ISSUE TITLE
Template-based 3D Model Fitting using libigl

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#240]
From personal email:

> I am currently trying to create a statistical shape model of a human head from scan data and need to align a template mesh topology to each scan, I found the white paper here:
> [Template-Based 3D Model Fitting Using Dual-Domain Relaxation]
> http://graphics.csie.ncku.edu.tw/TF/
> 
> It appears to be exactly what I need, I was wondering if you could possible point me in the right direction to how you might go about implementing this with libigl?
> 
> I haven't had change to go through the examples but there appears to be a lot of functionality for mesh deformations. If you could point me to the class index or some documentation or give me some insight to your thoughts about this problem I would greatly appreciate it.

**Comment by alecjacobson** [comment]
The [tutorial](libigl.github.io/libigl/tutorial/tutorial.html) is the best documentation currently available.

To implement Template-Based 3D Model Fitting Using Dual-Domain Relaxation, it looks like you'll need:

- uniform vertex Laplacian (see `igl::adjacency_matrix`)
- uniform facet-based (dual) Laplacian (see `igl::orientable_patches`, for a manifold input, output `A` will be a facet-facet adjacency matrix)
- quadratic energy minimization with fixed values (see `igl::min_quad_with_fixed`)
- ray-casting or closest point querying  (see `igl::ray_mesh_intersect` or `igl::embree::ray_mesh_intersect` or `igl::point_mesh_squared_distance`)

I'm confident you can implement this using a lot of functions already implemented in libigl

**Comment by djbailey** [comment]
Thanks, this is a great help. I shall let you know how I get on

**Comment by PatrickCSLin** [comment]
Hi, djbailey,
Did you try to implement Template-Based 3D Model Fitting Using Dual-Domain Relaxation with libigl?
Thanks!
