### ISSUE TITLE
Missing function template instantiation in extract_non_manifold_edge_curves.cpp

### ISSUE THREAD

**Issue by rachael-wang** [libigl/libigl#2420]
#### Describe your issue
We miss an instantiation for the template function in `extract_non_manifold_edge_curves.cpp`. The compile succeeded after adding the instantiation.

```
void igl::extract_non_manifold_edge_curves<Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<int, -1, 1, 0, -1, 1>, int>(Eigen::MatrixBase<Eigen::Matrix<int, -1, -1, 0, -1, -1>> const&, Eigen::MatrixBase<Eigen::Matrix<int, -1, 1, 0, -1, 1>> const&, std::__1::vector<std::__1::vector<int, std::__1::allocator<int>>, std::__1::allocator<std::__1::vector<int, std::__1::allocator<int>>>> const&, std::__1::vector<std::__1::vector<unsigned long, std::__1::allocator<unsigned long>>, std::__1::allocator<std::__1::vector<unsigned long, std::__1::allocator<unsigned long>>>>&), referenced from:
      _main in main.cpp.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

#### Checklist

- [x] I have read the [bug report](https://libigl.github.io/bug-report/) page
- [x] CMake issue: I have tried with a fresh clone/empty build directory

#### Platform

- [ ] Windows
- [ ] macOS Intel
- [x] macOS Arm (e.g., M1, M2)
- [ ] Linux

**Comment by alecjacobson** [comment]
Happy to merge a PR with this. If so, please remove the __1::
