### ISSUE TITLE
Aligned compiler error on vs2013 win10

### ISSUE THREAD

**Issue by iwillburnyou** [libigl/libigl#244]
Error	160	error C2719: 'a': formal parameter with __declspec(align('16')) won't be aligned	D:\git\libigl\include\igl\point_simplex_squared_distance.cpp	46

I met trouble when I try to run tutorials 106_ViewerMenu while I run tutorial 101 102 103 etc successfully. I also clone nanogui and run the example in it successfully. Notice Eigen have Aligned problem itself http://eigen.tuxfamily.org/dox/group__TopicUnalignedArrayAssert.html. Is there something miss in the sourcecode? I am confused who raise the problem.

**Comment by danielepanozzo** [comment]
Could you try with VS 2015 and see if you can reproduce the issue?

**Comment by iwillburnyou** [comment]
I met some strange problem when I install vs 2015 on win10. The aligned problem seems can be solved by define some macros. Anyway thx a lot for reply. Unfortunately, I have trouble in tutorials 106_ViewerMenu using nanogui. The code I clone disabled nanogui by default? And I check  class iglviewer, it also does not define IGL_VIEWER_WITH_NANOGUI. Is nanogui no longer supported in master branch?

**Comment by iwillburnyou** [comment]
Thanks again! I am a fresh men in geometric modeling. I enable LIBIGL_WITH_NANOGUI in cmakelist.txt. Than the tutorials work well. I dont know why the master branch disable nanogui?

**Comment by danielepanozzo** [comment]
Nanogui is disabled since it is problematic with some old compilers and it is not strictly necessary to run the tutorials. Glad that things worked out!
