### ISSUE TITLE
dangling reference in max_faces_stopping_condition

### ISSUE THREAD

**Issue by dixxi** [libigl/libigl#245]
In the file include/igl/max_faces_stopping_condition.cpp, line 23, the parameter max_m is captured by a lambda as reference. However, max_m is a parameter to the function inside which the lambda is defined and from which the lambda is returned. The reference to the captured parameter max_m therefore exceeds the lifetime of the original max_m and reads garbage when the lambda is evaluted. Capturing max_m by value (removing the &) solves the problem.

**Comment by alecjacobson** [comment]
Thanks, fixed.
