### ISSUE TITLE
Bad GLFW directive in Viewer.cpp

### ISSUE THREAD

**Issue by evouga** [libigl/libigl#247]
In Viewer.cpp there are the following lines:
# ifndef _WIN32

  #define GLFW_INCLUDE_GLCOREARB
# endif

The issue is that it is not safe to #define this symbol on all non-Windows machines. Rather, it should be defined on systems that are running newer versions of OpenGL that have a glcorearb.h instead of a gl.h (ideally somehow Cmake would sort this out); this is not the case e.g. on my university Ubuntu machine.

**Comment by danielepanozzo** [comment]
Mmm which version of ubuntu are you using? I was convinced that glcorearb.h was included by default with opengl 3.3 (which is the minimal requirement for the shaders that we have).

**Comment by evouga** [comment]
Is there a way to check which OpenGL version is installed?

If I comment out that line, the libigl example project compiles and runs OK (it shows the yellow cube)

**Comment by danielepanozzo** [comment]
Oh I know what this is, you are using an old ubuntu LTS with a bad opengl package. It is probably the same one that travis is using. We have a fix for this in the autobuild makefile, take a look here:
https://github.com/libigl/libigl/blob/master/.travis.yml

It is enough to wget one header and it should work fine.

**Comment by alecjacobson** [comment]
Daniele, do you think it's possible to catch this upon compilation/cmake ?
Then we could spit out a nice warning/error message pointing people to this
wget solution (at least for now).

**Comment by danielepanozzo** [comment]
Yeah that is a good idea, it is easy to check if that file exists and spit a warning with the instructions to fix it. I did not do it before since this is a bug in that specific ubuntu version (and it is fixed in the more recent versions) and I am reluctant to add a workaround in libigl to a fixed bug. However, it seems that this old ubuntu LTS is quite widely used so it might be worth doing it.

**Comment by evouga** [comment]
Hey guys,

Pinging about this issue again as it's worth fixing -- three different students have so far been hit by this when trying to install libigl (old LTS versions of Ubuntu are extremely common at universities, unfortunately).

**Comment by danielepanozzo** [comment]
Could you ask one of your students to send a PR with the fix? It is very painful to do this on travis since it takes ~30 minutes for every try and I do not have access to an old ubuntu machine where this still happen.

**Comment by evouga** [comment]
I will suggest they do this, though they may not understand enough about how CMake works to get it to work. The fix I tell them is to run the command you suggested,

wget -P external/nanogui/ext/glfw/include/GL http://www.opengl.org/registry/api/GL/glcorearb.h

**Comment by danielepanozzo** [comment]
Yes that's correct, they need to check if GL/glcorearb.h is available in the search path, and if not wget it (and do this only for linux, where wget is available by default).
