### ISSUE TITLE
multiple meshes in the viewer

### ISSUE THREAD

**Issue by evouga** [libigl/libigl#248]
Not a bug report, but a feature request:
- a way of showing multiple meshes at once in the viewer
- alternatively/in addition: a function which concatenates (computes the disjoint union of) two meshes. This may already exist but I couldn't find it. Of course I can compute a true union using the new boolean code but this is overkill

**Comment by danielepanozzo** [comment]
This is already done in the devel version of https://github.com/schuellc but we did not manage to merge it yet in the main. I will ping him and see when this can be done. Please subscribe to this thread for updates!

**Comment by alecjacobson** [comment]
Daniele, do you mean that schuellc has a modified version of the viewer to handle multiple meshes?

In the meantime, concatenating meshes is very simple in pure Eigen. We could write an igl function for this but it would simply contain:


```cpp
// Concatenate (VA,FA) and (VB,FB) into (V,F)
Eigen::MatrixXd V(VA.rows()+VB.rows(),VA.cols());
V<<VA,VB;
Eigen::MatrixXi F(FA.rows()+FB.rows(),FA.cols());
F<<FA,(FB.array()+VA.rows());
```

Here's a complete tutorial-style mini example:

```cpp
#include <igl/read_triangle_mesh.h>
#include <igl/viewer/Viewer.h>

int main(int argc, char * argv[])
{
  Eigen::MatrixXd VA,VB;
  Eigen::MatrixXi FA,FB;
  igl::read_triangle_mesh(argv[1],VA,FA);
  igl::read_triangle_mesh(argv[2],VB,FB);

  // Concatenate (VA,FA) and (VB,FB) into (V,F)
  Eigen::MatrixXd V(VA.rows()+VB.rows(),VA.cols());
  V<<VA,VB;
  Eigen::MatrixXi F(FA.rows()+FB.rows(),FA.cols());
  F<<FA,(FB.array()+VA.rows());

  // blue color for faces of first mesh, orange for second
  Eigen::MatrixXd C(F.rows(),3);
  C<<
    Eigen::RowVector3d(0.2,0.3,0.8).replicate(FA.rows(),1),
    Eigen::RowVector3d(1.0,0.7,0.2).replicate(FB.rows(),1);

  igl::viewer::Viewer viewer;
  viewer.data.set_mesh(V,F);
  viewer.data.set_colors(C);
  viewer.data.set_face_based(true);
  viewer.launch();
}
```

![image](https://cloud.githubusercontent.com/assets/2241689/14854360/501f9608-0c44-11e6-8895-1f9b9e910d94.png)

**Comment by evouga** [comment]
Thanks, didn't know you could add to all matrix entries like that!

**Comment by danielepanozzo** [comment]
This approach is perfect for static geometry, but it is annoying if you have small objects in the scene moving since you have to reconcatenate and reupload the entire vertex buffer (+ normals, colors, etc.) at every frame. Christian has a small (and fully backward compatible) way of extending the viewers that allows to have multiple ViewerData in a same viewer, doing the proper caching and avoiding unnecessary copies and opengl calls. He used it for his last project and we should add it since it is a pretty common scenario and the speedup you gain with it is huge.

**Comment by P-Kinsella** [comment]
Do you happen to have a link to the example that Christian made? I am looking to do the same and have multiple meshes in a viewer that can be moved independently

**Comment by Javier12** [comment]
I think this would be a great feature, is there an option to re-open?

**Comment by alecjacobson** [comment]
This is "in the works". There will be an update supporting this soon.

**Comment by alecjacobson** [comment]
For cross reference, this conversation mostly moved to the comments section of this dead PR: https://github.com/libigl/libigl/pull/470
