### ISSUE TITLE
Odd issue in tutorials (windows VS 2013)

### ISSUE THREAD

**Issue by computerScienceGuy** [libigl/libigl#25]
Hi, I'm new using libigl. I downloaded the source 4 days ago and the Eigen library version 3.2.2. In order to understand the libigl's mesh deformation algorithms, I created with CMake a VS 2013 x64 tutorial solution. But when I run the tutorial 402_PolyharmonicDeformation_bin the figure in the window doesn’t look like the image in the tutorial page, the gold region doesn’t appear. When I tried others tutorials, the simplest works. But for example in the 205_Laplacian_bin, when I press the space the cow disappears.
I tried this in two different PCs and I got the same problem. I think that it’s something that I’m doing wrong. Maybe there is something wrong with the calculations, I got these console output for the 205_Laplacian_bin tutorial:
|K-L|: 1.#QNAN
Press [space] to smooth.
Press [r] to reset.
Status: Using GLEW 1.10.0
ERROR(AntTweakBar) >> Bad value
ERROR(AntTweakBar) >> Unable to set param 'libIGL-Viewer size'  : Bad value

Maybe there is something wrong with Eigen, I searched and found this:
http://stackoverflow.com/questions/26013205/eigen-what-is-the-computational-limitation-for-log-windows-vs-linux. The post says: I have a strange problem with my Eigen code. It works well on Linux (64 bit) and Mac OSX (64 bit), but it fails on Windows (32 bit) with an 1.#INF value.

**Comment by alecjacobson** [comment]
Which version of Eigen are you using? Perhaps it's a file IO issue. Are you sure the mesh is being read in properly?

**Comment by computerScienceGuy** [comment]
I'm using Eigen 3.2.2.

In the 205_Laplacian_bin tutorial the cow appears the first time, but when I press [space] it dissapears. I checked the variables and it's something wrong with the initial values calculations. What version of Eigen I should try?

**Comment by twerdster** [comment]
The problem here is that OpenMP doesnt seem to work in some cases in
Windows with older Visual Studio i.e. 2010/2012 (and maybe linux for older
OpenMP versions?)
I turned off the /openmp flag in the CMake and it runs.

**Comment by alecjacobson** [comment]
thanks Aaron..

computerScienceGuy, can you confirm that it was an openmp+eigen issue for you, too?

**Comment by computerScienceGuy** [comment]
yes, it was that, indeed. Thanks a lot alecjacobson and twerdster!!!
