### ISSUE TITLE
Segmentation functions

### ISSUE THREAD

**Issue by niccolooo** [libigl/libigl#252]
First of all, amazing amazing job with LIBIGL.

This is not a bug report but rather a question. 

Does IGL support segmentation functions ? To my knowledge it doesn't, but I may be mistaken. P

Does the software on inside-outside segmentation [1] will be included in the next releases of the library?

Thanks

Niccolò

[1] https://igl.ethz.ch/projects/winding-number/robust-inside-outside-segmentation-using-generalized-winding-numbers-siggraph-2013-jacobson-et-al.pdf

**Comment by alecjacobson** [comment]
Yes, there is an implementation of the winding number segmentation:
http://libigl.github.io/libigl/tutorial/tutorial.html#generalizedwindingnumber
