### ISSUE TITLE
Neighbor information and oriented faces

### ISSUE THREAD

**Issue by krips89** [libigl/libigl#254]
It seems that libigl does not support Half-edge type data structure. But, is there some conversation or built in routine to simulate them?
That is, is there any ways of getting neighborhood information (neighboring vertices or faces) or face orientation (given its neighbor face) in O(1) time?
Just for this functionality I don't want to switch to a different library.

**Comment by danielepanozzo** [comment]
HalfEdgeIterator.h does exactly what you want. We unfortunately do not have a tutorial with an example but it should be straightforward to use.

**Comment by alecjacobson** [comment]
Daniele is indeed pointing you to the right place. You might also look at
`igl::triangle_triangle_adjacency` for a more compact libigl-style
representation that also extends beyond oriented two-manifolds. One thing
to keep in mind is that libigl is build around the idea that many geometry
processing routines are easier to write and faster _without_ resorting to a
half-edge data structure. Sometimes O(1) performance can be achieved
directly without half-edges and sometimes _amortized_ O(1) performance is
acceptable (for example if doing local operations everywhere, then it can
pay to precompute an adjacency matrix).

**Comment by krips89** [comment]
Hello, thank you for the quick responses. 
I browsed through the code already and found triangle_triangle_adjacency and HalfEdgeIterator. triangle_triangle_adjacency solved my purpose. Also, there are some stuffs like bfs_orient, facet_components which is some sort of applications built around neighbor access.  

One thing is that, it is quite difficult to get what is offered by the library (without them on tutorial). Maybe doxygen types API documentation will help, so that things show up in the search engines when people look for something? Browsing through every header files is quite tedious.

Thanks a lot anyways!
