### ISSUE TITLE
point to mesh distance

### ISSUE THREAD

**Issue by dansand** [libigl/libigl#257]
Hi, 

I need to compute nearest distances from arbitrary points to surface meshes. It looks like this is implemented in libigl, but not yet in the Python bindings. I would really appreciate if this functionality could this be included in (Python wrappers) in the future. Thanks.

**Comment by alecjacobson** [comment]
Ho ho! Nice, first specific request for python bindings. Daniele is
currently working on these and I think there's some effort under way to
automate them. If he doesn't get back to you on this, ping again. I think
it should be straight forward to wrap up the vanilla version of this
function with the python bindings.

**Comment by dansand** [comment]
Thanks, I'll wait to hear from Daniele. I have been using the implementation in PyMesh, but I'm having problems consistently installing that package across multiple environments. I think the libigl - python route looks much more strait forward.

**Comment by danielepanozzo** [comment]
Glad that you find the bindings useful! @s-koch is working on the automation and documentation in these weeks. I can probably find the time to wrap this function and the relative tutorial in a week or so, but maybe @s-koch can do it before.

**Comment by s-koch** [comment]
I'm working on it, should be done latest next week.

**Comment by danielepanozzo** [comment]
@s-koch wrote the wrappers for that function and also converted the entire tutorial 704 to python. Thank you @s-koch for the contribution!

@dansand : I am closing this issue, please reopen it if it does not work for you.

**Comment by alecjacobson** [comment]
Great! Thanks guys. I'm very happy with the progress you've been making
with the python bindings. So useful!
