### ISSUE TITLE
Crash at biharmonic_coordinates

### ISSUE THREAD

**Issue by krips89** [libigl/libigl#260]
I am getting segmentation fault on calling biharmonic_coordinates() function. My code looks like this: 

`igl::biharmonic_coordinates(Vtri, Ftri, S, Vtr_bc);`

Where Vtri, Ftri are vertices and triangulated faces from a simple obj file. S is `a std::vector<std::vector<int> >` with each list element in S containing a single index of Ftri denoting 'marker' points for generalized barycentric coordinates. Calling above I get a segmentation fault at 

slice.cpp:74: `Y = Eigen::SparseMatrix<TY>(dyn_Y);`
called by  igl::min_quad_with_fixed_precompute<double, Eigen::Matrix<int, -1, 1, 0, -1, 1> > min_quad_with_fixed.cpp:96 `slice(A,data.unknown,data.unknown,Auu);`

It also appears that in line slice.cpp:53: `X.nonZeros()/(X.rows()*X.cols())) * (ym*yn)` in `dyn_Y.reserve((X.nonZeros()/(X.rows()*X.cols())) * (ym*yn));` is zero. So it is calling dynY.reserve(0). Not sure if it is a problem just point out the observation. 

Is it also related to #112 ?
Thanks.

**Comment by krips89** [comment]
I also get a warning for slice instantiation at a similar location while compiling biharmonic_coordinates:

`Eigen::DynamicSparseMatrix<_Scalar, _Flags, _Index>::DynamicSparseMatrix(Eigen::DynamicSparseMatrix<_Scalar, _Flags, _Index>::Index, Eigen::DynamicSparseMatrix<_Scalar, _Flags, _Index>::Index) [with _Scalar = double; int _Options = 1; _Index = int; Eigen::DynamicSparseMatrix<_Scalar, _Flags, _Index>::Index = int]’ is deprecated (declared at /usr/include/eigen3/unsupported/Eigen/src/SparseExtra/DynamicSparseMatrix.h:233) [-Wdeprecated-declarations]
   Eigen::DynamicSparseMatrix<TY, Eigen::RowMajor> dyn_Y(ym,yn);`

**Comment by alecjacobson** [comment]
Could you please post your inputs `Vtri`, `Ftri` and `S`? The mesh `(Vtri,Ftri)` should either be a triangle mesh in 2D or a tetrahedral mesh in 3D. The elements of `S` should index into `Vtri` (not `Ftri`).

Not sure why `min_quad_with_fixed` is crashing without probing with your input data. In the meantime you could also try running in debug mode to see if any meaningful asserts fire.

**Comment by krips89** [comment]
That was my doubt. Vtri, Ftri can't be a triangle mesh in 3D? Like the vertices and faces obtained by a simple obj file (3 dimensional  vertices, 3 dimensional faces)? That is what my input is.
How to obtain generalized barycentric coordinates for a 3D triangulated mesh?

I was using the S index of the face instead of vertex. When I now use it properly using vertex indices at S, I run into `Error: Numerical issue`.

**Comment by alecjacobson** [comment]
Biharmonic coordinates [Wang et al. 2015]---like most generalized
barycentric coordinates (GBCs)---are defined for a subregion of the
Euclidean space. So if you object (e.g., a surface mesh) lives in 3D then
biharmonic coordinates will need to be defined for a volume (e.g.,
tetrahedral mesh) containing the object. The unique advantage of biharmonic
coordinates over previous GBCs is that we do require a coarse containing
cage to define this volume. The volume can simply be bound by an input
surface. So, in short, you can _just_ tetrahedralize the interior of your
input triangle mesh.

If you have a clean (closed, watertight, etc.) surface mesh then have a
look at `igl::copyleft::tetgen::tetrahedralize` to compute a tet mesh from
a surface triangle mesh.

Once you have computed biharmonic coordinates over the tet-mesh you can
extract just the coordinates at your original surface mesh vertices and
throw away the tet-mesh.

**Comment by alecjacobson** [comment]
Also, biharmonic_coordinates needs #dimensions + 1 handles as constraints in `S`
