### ISSUE TITLE
How do I know which button and modifier for mouse event such as mouse_move?

### ISSUE THREAD

**Issue by wguo68** [libigl/libigl#261]
bool mouse_move(igl::viewer::Viewer& viewer, int button, int modifier)

what values for button and modifiers?

BTW, for key event ,how do I know I pressed a special key such as "Ctrl"?

Thanks

**Comment by alecjacobson** [comment]
these are the same as GLFW see their docs

**Comment by wguo68** [comment]
Thanks.
For key event. when I pressed 's' ,there is no response. When I pressed '1',it is Okay.
What's the problem?

**Comment by s-koch** [comment]
You probably have to compare to the capital letter: key == 'S'
