### ISSUE TITLE
can not build 102_DrawMesh_bin with vs2015

### ISSUE THREAD

**Issue by sdnusqy** [libigl/libigl#268]
iglviewer.lib(TextRenderer.obj) : error LNK2019: 无法解析的外部符号 _nvgCreateGL3，该符号在函数 "public: virtual int __thiscall igl::viewer::TextRenderer::Init(void)" (?Init@TextRenderer@viewer@igl@@UAEHXZ) 中被引用
1>iglviewer.lib(TextRenderer.obj) : error LNK2019: 无法解析的外部符号 _nvgDeleteGL3，该符号在函数 "public: virtual int __thiscall igl::viewer::TextRenderer::Shut(void)" (?Shut@TextRenderer@viewer@igl@@UAEHXZ) 中被引用

**Comment by danielepanozzo** [comment]
I am currently traveling, I cannot fix the windows build until the beginning of next week. If you manage to fix it, please send a pull request!

**Comment by sdnusqy** [comment]
Thanks! I have solve the problem. But,I can not start up the exe.   The windows build:  http://pan.baidu.com/s/1eSg7Afg    Please download it.

**Comment by sdnusqy** [comment]
Thanks! I have solve the problem. But,I can not start up the exe. The windows build:http://pan.baidu.com/s/1eSg7Afg Please download it.



sdnusqy



From: Daniele Panozzo
Date: 2016-05-25 18:11
To: libigl/libigl
CC: sdnusqy; Author
Subject: Re: [libigl/libigl] can not build 102_DrawMesh_bin with vs2015 (#268)
I am currently traveling, I cannot fix the windows build until the beginning of next week. If you manage to fix it, please send a pull request!

**Comment by danielepanozzo** [comment]
The build is now working again on VS2015:
https://ci.appveyor.com/project/danielepanozzo/libigl-6hjk1

 I will close the issue, please reopen it if you still have problems.
