### ISSUE TITLE
error C2665: 'igl::decimate' : none of the 2 overloads could convert all the argument types

### ISSUE THREAD

**Issue by niccolooo** [libigl/libigl#271]
Hi,
I am trying  to use the igl::decimate() function to simplify a mesh. 

However, I get the following compilation error: 
`error C2665: 'igl::decimate' : none of the 2 overloads could convert all the argument types`	

I assume this is a quite dummy const type of problem, but I can't get figure it out.

Moreover, I see that the decimate function has been refactored and there isn't a 5-argument function anymore (btw, I suggest to update the [tutorial section](http://libigl.github.io/libigl/tutorial/tutorial.html#meshdecimation)) 

Below is my code. 

```
`#include "stdafx.h"
#include <iostream>
#include <igl/circulation.h>
#include <igl/collapse_edge.h>
#include "igl/decimate.h"
#include <igl/edge_flaps.h>
#include <igl/read_triangle_mesh.h>
#include <igl/writeOBJ.h>
#include <Eigen/Core>
#include <set>
```

```
int main(int argc, char * argv[])
{
	using namespace std;
	using namespace Eigen;
	using namespace igl;

```
	std::clock_t start;
	double duration;
	start = std::clock();

	string filename("_PATH_TO_OBJ_FILE_");

	cout << "  'working on'  = " << filename << endl;

	if (argc >= 2)
	{
		filename = argv[1];
	}
	Eigen::MatrixXd V;
	Eigen::MatrixXi F;

	igl::readOBJ(filename, V, F);

	size_t max_f = 1000;

	Eigen::MatrixXd U;
	Eigen::MatrixXi G, J;

	igl::decimate(V, F, max_f, U, G, J);

	duration = (std::clock() - start) / (double)CLOCKS_PER_SEC;
	std::cout << "time to read: " << filename << ": " << duration << "s" << endl;

	cin.get();
}
`

**Comment by alecjacobson** [comment]
Good point about the tutorial. I think your J should be Eigen::VectorXi

**Comment by niccolooo** [comment]
Oh man. Thanks! Problem solved.
