### ISSUE TITLE
Problem decimating stl file

### ISSUE THREAD

**Issue by niccolooo** [libigl/libigl#273]
Hi, 
I experience a problem an issue trying to decimate an stl file. The read_triangle_mesh() function works fine, but igl::decimate throws the following exception : 
`
Assertion failed: index >= 0 && index < size(), file c\:_PATH_TO_EIGEN_\src\core\densecoeffsbase.h`

If I call the same function opening an obj file it works just fine. Meshes example.stl and example.obj are available at [this link](https://drive.google.com/folderview?id=0B0UaFJtQ8NA5Z1kxUnNibFRiZWs&usp=sharing).

Any help appreciated

```
#include "stdafx.h"
#include <iostream>
#include <igl/circulation.h>
#include <igl/collapse_edge.h>
#include "igl/decimate.h"
#include <igl/edge_flaps.h>
#include <igl/read_triangle_mesh.h>
#include <igl/writeOBJ.h>
#include <Eigen/Core>
#include <set>

#include "FileSystemParser.cpp"
//#include "tutorial_shared_path.h"

using namespace std;


int main(int argc, char * argv[])
{
    using namespace std;
    using namespace Eigen;
    using namespace igl;

    std::clock_t start;
    double duration;
    start = std::clock();
    string origin_path = ".";

    string output_path = origin_path + "\\simplified\\";

    fs_parser fsp;
    fsp.createDir(output_path);
    string filename = "example.stl"; // this gives an error
    // string filename = "example.obj"; // this works fine


    cout << "  'working on'  = " << filename << endl;

    if (argc >= 2)
    {
        filename = argv[1];
    }
    Eigen::MatrixXd OV, V;
    Eigen::MatrixXi OF, F;

    igl::read_triangle_mesh(filename, OV, OF);

    Eigen::MatrixXd U;
    Eigen::MatrixXi G;
    Eigen::VectorXi J;

    // save a copy of the original mesh
    igl::writeOBJ( output_path + "original.obj", OV, OF);
    cout << "  mesh containts " << OV.rows() << " vertices and " << OF.rows() << " faces" << endl;

    cout << "  'decimation started ..." << endl; 

    // to halve the number of facets
    int max_m = (int)round(OF.rows() * 0.8);
    cout << "  'F.rows() =" << OF.rows() << endl;
    cout << "  'max_m =" << max_m << endl;

    bool keep_decimating = true;
    int count = 0;
    while (count < 4){
        count += 1;
        keep_decimating = igl::decimate(OV, OF, max_m, V, F, J);
        cout << "  mesh containts " << V.rows() << " vertices and " << F.rows() << " faces" << endl;

        OV = V;
        OF = F;

    }



    duration = (std::clock() - start) / (double)CLOCKS_PER_SEC;
    std::cout << "time to process: " << filename << ": " << duration << "s" << endl;

    igl::writeOBJ(output_path + "\\out.obj", OV, OF);

    cin.get();
}
```

**Comment by alecjacobson** [comment]
There are couple things at least:

1. .stl files contain a stream of triangles rather than a list of vertices
and a list of faces. So when you use import an .stl file it will likely
contain many duplicate vertices and combinatorially disconnected faces. To
recover the original mesh use `igl::remove_duplicate_vertices`.
2. The .stl file contains a zero area face, attached in along a
non-manifold (it seems the .obj does not have this problem)
  a. Zero area faces should probably be removed before calling
igl::decimate (depending on your cost function)
  b. non-manifold edges are strictly not allowed by igl::decimate

**Comment by niccolooo** [comment]
Thanks  a lot for the reply Alec. For this specific case, removing duplicate vertices did the trick. Does libigl have functions to remove zero-area faces? 

On a side note, I didn't find an explicit example for igl::remove_duplicate_vertices, but I worked it out digging in WindingNumberTree.h . Perhaps you'd like to add my short example to the templates? Below is my code.

```
// Test_remove_duplicate.cpp : Defines the entry point for the console application.
//

#include "stdafx.h"
#include <iostream>
#include <igl/circulation.h>
#include <igl/collapse_edge.h>
#include "igl/decimate.h"
#include <igl/edge_flaps.h>
#include <igl/read_triangle_mesh.h>
#include <igl/remove_duplicate_vertices.h>
#include <igl/writeOBJ.h>
#include <Eigen/Core>
#include <set>

using namespace std;


int main(int argc, char * argv[])
{
	using namespace std;
	using namespace Eigen;
	using namespace igl;

	std::clock_t start;
	double duration;
	start = std::clock();

	string origin_path = ".";

	string filename = "../meshes/example1.stl";
	cout << "  'working on'  = " << filename << endl;

	string output_path = origin_path + "\\simplified\\";


	if (argc >= 2)
	{
		filename = argv[1];
	}


	// Read stl matrix
	Eigen::MatrixXd OV;
	Eigen::MatrixXi OF;
	igl::read_triangle_mesh(filename, OV, OF);
	cout << " original  mesh containts " << OV.rows() << " vertices and " << OF.rows() << " faces" << endl;

        // Remove duplicated vertices
	Eigen::MatrixXd V;
	Eigen::MatrixXi F, SVI, SVJ;
	igl::remove_duplicate_vertices(OV, OF, 0.0, V, SVI, SVJ, F);
	cout << " after removing duplicates, mesh containts " << V.rows() << " vertices and " << F.rows() << " faces" << endl;

	duration = (std::clock() - start) / (double)CLOCKS_PER_SEC;
	std::cout << "time to process: " << filename << ": " << duration << "s" << endl;

	cin.get();
}
```

**Comment by alecjacobson** [comment]
We should totally make a "simple mesh clean up" tutorial that calls things
like remove unreferenced vertices, remove duplicate vertices and removes
zero area faces. Your code could be a good starting point.

**Comment by niccolooo** [comment]
It would definitely help rookies like me. Feel free to use it.

**Comment by airycanon** [comment]
Hi,I am new here,does libigl have functions to deal with non-manifold edges,or I need to do it manually?

**Comment by alecjacobson** [comment]
@airycanon  Do you mean for decimation? The current implementation will not work with non-manifold edges. 
Otherwise, we have functions for identifying non-manifold edges. Other functions in libigl are not well separated in terms of those that work only with manifold meshes or triangle soups. Most work with triangle soups, but the more complicated algorithms might fail or give surprising results.
