### ISSUE TITLE
C# Wrapper:  <thread> is not supported 

### ISSUE THREAD

**Issue by niccolooo** [libigl/libigl#276]
Hi,
I would like to call libigl functions in a C# application. After [some reading](http://hintdesk.com/c-how-to-create-a-clr-wrapper-of-c-for-using-in-c/), I decided to:
1. write a C++ class to expose desired libigl (called MeshSimp)
2. create a CLR wrapper for said class (called MeshSimpWrapper)
3. include the CLR wrapper in my C# application

As a test, I did 1,2,3 for a dummy class with only native objects and it worked fine. Then, I compile MeshSimp and it compiles fine. When I build MeshSimpWrapper, I get the following error:

`Error  1   error C1189: #error :  <thread> is not supported when compiling with /clr or /clr:pure. C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\thread   8   1   MeshSimpWrapper
` 

Is there any C# wrapper available for Libigl?

Is the 'thread' dependancy unavoidable?

**Comment by alecjacobson** [comment]
Eeek. A C# wrapper is not a huge priority at the moment. Perhaps the thread
issues could be resolved on a case by case basis. But at this point I'm not
willing to sacrifice anything for C# compatibility.

**Comment by danielepanozzo** [comment]
Maybe the problem could be circumvented by using the python wrappers and calling the python functions from C#?
