### ISSUE TITLE
g++ Version Confusion

### ISSUE THREAD

**Issue by twodee** [libigl/libigl#277]
In README.md, it says that g++ 4.7 should be used because g++ 4.8 has issues with CGAL. But when I use 4.7, I get an error saying `std::set` doesn't support `emplace`. This method wasn't added until 4.8: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=44436.

**Comment by alecjacobson** [comment]
@qnzhou which version of gcc were you using on linux? I think our warning about CGAL+gcc is out of date...

**Comment by qnzhou** [comment]
I have used 4.9 on linux and mac.  See [this old thread](http://cgal-discuss.949826.n4.nabble.com/Bugs-in-AABBTree-td4660077.html) on g++4.8 and CGAL for details.  Maybe the problem no longer exists.

**Comment by twodee** [comment]
I just installed g++ 4.9 and everything compiled. Though the original documentation issue still stands, I am grateful to have an executable finally!

I did encounter an issue that I did not have with older g++ versions. Apparently with g++ 4.9, one must actively link the pthread library when using the C++11 thread API: http://ubuntuforums.org/showthread.php?t=2273365.

g++ 4.8 may work now too, but I was running running out of RAM to compile on a 512 MB Digital Ocean droplet. I assumed my issue was the one hinted at in the README, but it may just have been that the compiler ran out of memory. My eventual successful compile with 4.9 required over 1.0 GB of swap space. The only code in libigl I'm referencing currently is the mesh_boolean stuff. There must be some crazy stuff going on in that code.

**Comment by qnzhou** [comment]
If you are only interested in using mesh_boolean part, you don't need to compile the entire libigl because libigl can be used as a header-only library.  [Here](https://github.com/qnzhou/BooleanDemo) is a tiny example of just using mesh_boolean part from libigl.

**Comment by twodee** [comment]
That is how I'm using it. When I say compile, I'm referring to my code which includes the mesh_boolean.h header.
