### ISSUE TITLE
New errors with C++11 

### ISSUE THREAD

**Issue by csverma610** [libigl/libigl#283]
Hello,

Some new errors came up even with Eigen3.2.8 (compiled with  C++11 ) on Ubuntu 16.10. It seems
that new C++11 have some issues with some non-standard features in Eigen library. With these
errors, there are many great functions in libigl which are not useable right now. 

Is there any quick fix for these problems ?

Thanks.
csv

In file included from /usr/include/eigen3/Eigen/Core:366:0,
                 from /home/csverma/Software/Mesh/LibIGL/include/igl/avg_edge_length.h:12,
                 from ../include/ConjugateField.hpp:6,
                 from ConjugateField.cpp:1:
/home/csverma/Software/Mesh/LibIGL/include/igl/ConjugateFFSolverData.h: In instantiation of ‘igl::ConjugateFFSolverData<DerivedV, DerivedF>::ConjugateFFSolverData(const Eigen::PlainObjectBase<Derived>&, const Eigen::PlainObjectBase<DerivedF>&) [with DerivedV = Eigen::Matrix<double, -1, -1>; DerivedF = Eigen::Matrix<int, -1, -1>]’:
ConjugateField.cpp:35:81:   required from here
/usr/include/eigen3/Eigen/src/Core/PlainObjectBase.h:457:25: error: ‘Eigen::PlainObjectBase<Derived>::PlainObjectBase() [with Derived = Eigen::Matrix<double, -1, -1>]’ is protected
     EIGEN_STRONG_INLINE PlainObjectBase() : m_storage()
                         ^
In file included from /home/csverma/Software/Mesh/LibIGL/include/igl/conjugate_frame_fields.h:12:0,
                 from ../include/ConjugateField.hpp:8,
                 from ConjugateField.cpp:1:
/home/csverma/Software/Mesh/LibIGL/include/igl/ConjugateFFSolverData.h:87:15: error: within this context
 numF(_F.rows())
               ^

**Comment by symek** [comment]
Just to add to the topic, the same errors I've encountered in arap parameterization and eigen decomposition examples. I would love to know a workaround too.

Thanks for libigl btw!
skk.

**Comment by alecjacobson** [comment]
These should be fixed, now.
