### ISSUE TITLE
decimate large meshes

### ISSUE THREAD

**Issue by vibe007** [libigl/libigl#293]
For me, the igl::decimate() function works great on meshes of moderate size - say 100K triangles. But when testing the function on a large mesh (~7 mil triangles), I get the error: "Killed: 9". I'm using a Mac Pro with 16 GB memory - maybe the error relates to the size of data structures created to perform the decimation. 

I wonder if anyone has had success with this function on large models? I'm using this model on the Stanford scanning repository: http://graphics.stanford.edu/data/3Dscanrep/xyzrgb/xyzrgb_dragon.ply.gz

**Comment by alecjacobson** [comment]
I tried this model, but I don't get any errors. How exactly are you calling `igl::decimate` ? 

For the record, `igl::decimate` takes 165 seconds on my machine and [qslim](http://www.cs.cmu.edu/~./garland/quadrics/qslim.html) takes 179 seconds.

**Comment by vibe007** [comment]
Here’s my code - it works on fertility.off, armadillo.obj, and bunny.off. 

It took more than a few minutes on truck.obj, which is only 4K polygons, and I eventually killed it. It similarly took way more than 3 minutes on xyzrgb_dragon and resulted in a “Killed 9” error. 

I might also mention that these same two cases failed in the same way on the tutorial code, 703_Decimation. 

```
#include <igl/circulation.h>
#include <igl/decimate.h>
#include <igl/collapse_edge.h>
#include <igl/edge_flaps.h>
#include <igl/read_triangle_mesh.h>
#include <igl/viewer/Viewer.h>
#include <Eigen/Core>
#include <iostream>
#include <set>
#include <string>
#include <vector>
#include <assert.h>
#include "tutorial_shared_path.h"
#include <boost/filesystem.hpp>
#include <stdlib.h>
#include <igl/writeOBJ.h> 

void DecimateMesh(std::string inputPath, std::string modelName, std::vector<double> LODs, std::string outputFolder) {
  using namespace std;
  using namespace Eigen;
  using namespace igl;

  //read in the input mesh
  MatrixXd V;
  MatrixXi F;
  VectorXi J;
  read_triangle_mesh(inputPath + modelName,V,F);


  for (int i=0; i < LODs.size(); ++i) {
    if(LODs[i] > 100 || LODs[i] <= 0) {
    printf ("incorrect bounds on LODs: %.1f \n", LODs[i]);
    exit (EXIT_FAILURE);
    }
  }
  
  //sort descending the LOD array
  std::sort(LODs.begin(), LODs.end(), std::greater<double>());

  //translate LOD percentages to faces
  std::vector<double> LOD_faces(LODs);
  for (int i=0; i<LODs.size(); ++i) {
    LOD_faces[i] = std::ceil(.01*LOD_faces[i]*F.rows());
    std::cout << LOD_faces[i] << std::endl;
  }


  std::string savePath = outputFolder + modelName.substr(0,modelName.length()-4);
  system(string("mkdir " + savePath).c_str());


  //for each element in LOD:
  for (int i=0; i < LOD_faces.size(); ++i) {

  //1: decimate to that level
  std::cout << "prior size: " << F.rows() << " target: " << int(std::ceil(LOD_faces[i])) << std::endl;
  igl::decimate(V,F,int(std::ceil(LOD_faces[i])),V,F,J);
  std::cout << "target: " << int(std::ceil(LOD_faces[i])) << ", decimated to these faces: " << F.rows() << std::endl;
  //2: save that mesh
  igl::writeOBJ(savePath + "/" + modelName.substr(0,modelName.length()-4) + "_" + std::to_string(int(std::ceil(LOD_faces[i]))) + "_" + std::to_string(int(std::ceil(LODs[i]))).c_str() + ".obj",V,F);
  //3: use the decimated mesh as the starting point for the next decimation
  }
}

int main(int argc, char * argv[])
{
std::string modelName ("xyzrgb_dragon.ply");
  std::string inputPath ("/Users/Home/Documents/MATLAB/packages/libigl/tutorial/shared/");
  std::vector<double> LODs {10, 5, 1}; //What percent of original mesh we want
  std::string outputFolder ("/Users/Home/Documents/MATLAB/packages/libigl/tutorial/shared/LOD/");
  DecimateMesh(inputPath, modelName, LODs, outputFolder);

}

```

**Comment by vibe007** [comment]
I re-cloned libigl and simplified my code to help debug. This code decimates 'bunny.off', 'fertility.off', and 'armadillo.obj' but halts midway through the simplification on larger models like 'xyzrgb_dragon.ply' and 'buddha.obj'. It also halts on 'truck.obj' without reaching the target faces. 

It might be tough for you to debug because these same models are simplifying fine for you, but let me know if you have any suggestions to fix this. 

```

#include <igl/circulation.h>
#include <igl/decimate.h>
#include <igl/collapse_edge.h>
#include <igl/edge_flaps.h>
#include <igl/read_triangle_mesh.h>
#include <Eigen/Core>
#include <iostream>
#include <set>
#include <string>
#include <vector>
#include <stdlib.h>

void DecimateMesh(std::string inputPath, std::string modelName, int target, std::string outputFolder) {
    using namespace std;
    using namespace Eigen;
    using namespace igl;  
    MatrixXd V;
    MatrixXi F;
    VectorXi J;
    read_triangle_mesh(inputPath + modelName,V,F);
    cout << "starting faces: " << F.rows() << endl;
    igl::decimate(V,F,target,V,F,J);
    cout << "decimated to: " << F.rows() << endl;
}

int main(int argc, char * argv[])
{
    
    std::string modelName ("xyzrgb_dragon.ply");
    std::string inputPath ("/Users/Home/Documents/MATLAB/packages/libigl/tutorial/shared/");
    int target = 1000;
    std::string outputFolder ("/Users/Home/Documents/MATLAB/packages/libigl/tutorial/shared/LOD/");
    DecimateMesh(inputPath, modelName, target, outputFolder);
    
}
```

I'm calling `g++ -std=c++11 -I/usr/local/include/eigen3 -I./include/ main.cpp -o hello` to compile and `./hello` to execute.

**Comment by alecjacobson** [comment]
As I recall, truck.obj is non-manifold. For this type of mesh,
igl::decimate simply will not work correctly. When you say the program
"halts", is it crashing or returning from the decimate function?

**Comment by vibe007** [comment]
The code does not crash, it just simplifies some of the faces and then stops (i'm printing the face count each time an edge is collapsed). It reaches a certain face count (still far from the target) and then stops decimating. After many minutes, I get a "Killed 9" error which exits the program. 

Thanks for your help with this :)

**Comment by alecjacobson** [comment]
(bottom line: decimate will not work on non-edge-manifold meshes).

**Comment by alecjacobson** [comment]
You can use is_edge_manifold to find which edges are non manifold and to
which face they belong. Then I suppose you could delete those faces, run
decimate and fill holes.

Decimating a non-manifold mesh is tricky and probably a bit ill posed, but
there are some papers about it. I think Songrun Liu's implementation of
"Seamless" (based on libigl decimate) handles non-manifold edges.
