### ISSUE TITLE
What's the proper way to shut the viewer from another thread ?

### ISSUE THREAD

**Issue by metorm** [libigl/libigl#295]
I put the `viewer::launch()` in a separated thread. The main thread keeps calculating some thing and use  `viewer.data.setmesh()` to update the view.

The program generally works well. However, I didn't find any "official" way to shut it from the main thread. What shall I do if I don't want to close the viewer window manually?

**Comment by alecjacobson** [comment]
AFAIK there's no libigl wrapper for closing the window. But you can tell glfw to close the window directly via `glfwSetWindowShouldClose` and this will break out of the `launch()` loop.

BTW, I would recommend using a buffer to change the mesh and only change the mesh in the viewer via the exposed callbacks or in the main thread to avoid race conditions. This way you can manage mutexes on the buffer if you need to without modifying the viewer code. See this small example:

```cpp
#include <igl/get_seconds.h>
#include <igl/read_triangle_mesh.h>
#include <igl/viewer/Viewer.h>
#include <Eigen/Core>
#include <thread>
#include <future>

int main(int argc, char *argv[])
{
  // Load in mesh and initialize viewer
  Eigen::MatrixXd V,U;
  Eigen::MatrixXi F;
  igl::read_triangle_mesh(argv[1],V,F);
  U = V;
  igl::viewer::Viewer viewer;
  viewer.data.set_mesh(V,F);
  // Computation thread: change the vertices of the mesh but don't touch
  // vertices in the viewer
  auto handle = std::async(std::launch::async,
    [&V,&U,&viewer]()
    {
      // repeat some phony computation for 5 seconds
      double t_start = igl::get_seconds();
      while(igl::get_seconds() - t_start < 5)
      {
        U.col(0) = V.col(0)*cos(igl::get_seconds());
      }
      // Tell glfw (viewer) to close window: this will cause launch() to
      // return.
      glfwSetWindowShouldClose(viewer.window, GL_TRUE);
    }
  );
  // Just before drawing change the vertices of the mesh. Could easily add a
  // flag to only call set_vertices if there's an actually change
  viewer.callback_pre_draw = 
    [&U](igl::viewer::Viewer & v)->bool{ v.data.set_vertices(U);return false;};
  // Set Viewer to tight draw loop
  viewer.core.is_animating = true;
  // Launch viewer in this thread
  viewer.launch();
}
```

**Comment by metorm** [comment]
@alecjacobson Thank you so much. My program is working well with `glfwSetWindowShouldClose` function.

However, I didn't take your idea about using `callback_pre_draw` , because my main thread some times clears everything in `U` and `V` and resize them, which means, to update the mesh using `callback_pre_draw`, I have to allocate two more `Matrix` as buffer. My mesh updates roughly every 10 seconds. Do you think it is OK ?

By the way, why is the lambda expression for `callback_pre_draw` in your code returning `false` ? What if it returns `true`?

**Comment by alecjacobson** [comment]
It's probably OK not to use a buffer. But the viewer is not designed to be
thread safe. So if you call set_mesh while something else is
reading/writing the mesh stored in the viewer you might get strange results.

callback_pre_draw should return whether the callback is "stealing" the
draw. So returning false means "nope I'm not stealing the draw so please do
go ahead and draw the next frame". Return false would mean "Yes, I'm
stealing the draw, so skip the next frame". The booleans are a little
backwards but this is to match mouse/keyboard callbacks which behave the
same way.

**Comment by metorm** [comment]
Got it. Thanks ~
