### ISSUE TITLE
Compiling Nanogui with Viewer - Mac 

### ISSUE THREAD

**Issue by P-Kinsella** [libigl/libigl#296]
I am trying to compile nanogui with viewer so I can add some custom buttons similar to example 106, but I can't seem to get it to work.

The tutorials are all working in xcode using the header file. I have tried using Cmake and compiling the static libraries but I can't get it working in xcode, if you have an example of the process you used for the tutorial it would really help

**Comment by danielepanozzo** [comment]
What errors do you get? The tutorials should compile in Xcode with the following procedure:

cd libigl/tutorials
mkdir build
cd build
cmake -G Xcode ../

Open the generated project in Xcode and compile. If you need a basic template to start your own project you can clone:

https://github.com/libigl/libigl-example-project

**Comment by P-Kinsella** [comment]
Thanks for the reply. I can get all the tutorials to compile but when I try to compile 106 I get the error, "ngui is not a module of viewer"

It says that I need to compile Viewer with Nanogui but I'm not sure how to go about this,

**Comment by danielepanozzo** [comment]
There is a flag in the cmake file, it should work with
cmake -DLIBIGL_WITH_NANOGUI=ON ../

Are you trying to compile the c++ tutorials or to launch the python ones?

**Comment by samansepehri** [comment]
I used the following command to build the tutorial "106_VieweMenu" on mac:

cmake -DLIBIGL_WITH_NANOGUI=ON ../

but still "LIBIGL_VIEWER_WITH_NANOGUI" is not defined. I also tried:

cmake LIBIGL_WITH_NANOGUI=ON -G xcode ../
and
cmake LIBIGL_WITH_NANOGUI=ON  ../

again no success. I got all the dependencis using:

git submodule update --init --recursive

So how and where I can define the "LIBIGL_VIEWER_WITH_NANOGUI" in the libigl source code somehow?

**Comment by ShangxuanWu** [comment]
Same question here as @stefanmessmer

**Comment by ShangxuanWu** [comment]
I fixed it by manually setting the toggle to ON in CMakeList.txt:

![image](https://user-images.githubusercontent.com/12669087/33974233-52c992e6-e055-11e7-8995-08f64fe5ab7c.png)
