### ISSUE TITLE
Problem about MIQ

### ISSUE THREAD

**Issue by lxwzju** [libigl/libigl#30]
When used miq function, meshes with boundaries will prevent jagged boundary if I don't add round_vertices and hard_features; After I added round_vertices and hard_features, the result is not correct. The output:
[1;32mNot using externally supplied vertex valences.[0m
[43mCollapsing inconsistent edge. Length of he0 = 0, length of he1 = 1.4525e-85
If this happens prior to truncation it's ok. If it happens afterwards, this is a bug.[0m
[43mCollapsing inconsistent edge. Length of he0 = 0, length of he1 = 1.4935e-85
If this happens prior to truncation it's ok. If it happens afterwards, this is a bug.[0m
[43mCollapsing inconsistent edge. Length of he0 = 0, length of he1 = 1.41951e-85
If this happens prior to truncation it's ok. If it happens afterwards, this is a bug.[0m
[43mCollapsing inconsistent edge. Length of he0 = 0, length of he1 = 1.4935e-85
If this happens prior to truncation it's ok. If it happens afterwards, this is a bug.[0m

However I don't  the problem, could you tell me when used MIQ, what should I be care of meshes with boundaries? Thank you very much.

**Comment by copyme** [comment]
Is this issue still relevant?
