### ISSUE TITLE
Problem Unresolved External Symbol

### ISSUE THREAD

**Issue by Aidoru** [libigl/libigl#304]
Hello, I have some problems to build some tutorials, I have CGAL installed, I can build other tutorials, but, for example, it is really important for me tutorial 610_CSGTree, where I receive that error (On Visual Studio 2015) :

`Severity   Code    Description Project File    Line    Source  Suppression State
Error   LNK2019 unresolved external symbol "bool __cdecl igl::copyleft::cgal::mesh_boolean<class Eigen::Matrix<class CGAL::Lazy_exact_nt<class CGAL::Gmpq>,-1,3,0,-1,3>,class Eigen::Matrix<int,-1,-1,0,-1,-1>,class Eigen::Matrix<class CGAL::Lazy_exact_nt<class CGAL::Gmpq>,-1,3,0,-1,3>,class Eigen::Matrix<int,-1,-1,0,-1,-1>,class Eigen::Matrix<class CGAL::Lazy_exact_nt<class CGAL::Gmpq>,-1,3,0,-1,3>,class Eigen::Matrix<int,-1,-1,0,-1,-1>,class Eigen::Matrix<__int64,-1,1,0,-1,1> >(class Eigen::PlainObjectBase<class Eigen::Matrix<class CGAL::Lazy_exact_nt<class CGAL::Gmpq>,-1,3,0,-1,3> > const &,class Eigen::PlainObjectBase<class Eigen::Matrix<int,-1,-1,0,-1,-1> > const &,class Eigen::PlainObjectBase<class Eigen::Matrix<class CGAL::Lazy_exact_nt<class CGAL::Gmpq>,-1,3,0,-1,3> > const &,class Eigen::PlainObjectBase<class Eigen::Matrix<int,-1,-1,0,-1,-1> > const &,enum igl::MeshBooleanType const &,class Eigen::PlainObjectBase<class Eigen::Matrix<class CGAL::Lazy_exact_nt<class CGAL::Gmpq>,-1,3,0,-1,3> > &,class Eigen::PlainObjectBase<class Eigen::Matrix<int,-1,-1,0,-1,-1> > &,class Eigen::PlainObjectBase<class Eigen::Matrix<__int64,-1,1,0,-1,1> > &)" (??$mesh_boolean@V?$Matrix@V?$Lazy_exact_nt@VGmpq@CGAL@@@CGAL@@$0?0$02$0A@$0?0$02@Eigen@@V?$Matrix@H$0?0$0?0$0A@$0?0$0?0@2@V12@V32@V12@V32@V?$Matrix@_J$0?0$00$0A@$0?0$00@2@@cgal@copyleft@igl@@YA_NAEBV?$PlainObjectBase@V?$Matrix@V?$Lazy_exact_nt@VGmpq@CGAL@@@CGAL@@$0?0$02$0A@$0?0$02@Eigen@@@Eigen@@AEBV?$PlainObjectBase@V?$Matrix@H$0?0$0?0$0A@$0?0$0?0@Eigen@@@4@01AEBW4MeshBooleanType@2@AEAV34@AEAV54@AEAV?$PlainObjectBase@V?$Matrix@_J$0?0$00$0A@$0?0$00@Eigen@@@4@@Z) referenced in function "public: __cdecl igl::copyleft::cgal::CSGTree::CSGTree(class igl::copyleft::cgal::CSGTree const &,class igl::copyleft::cgal::CSGTree const &,enum igl::MeshBooleanType const &)" (??0CSGTree@cgal@copyleft@igl@@QEAA@AEBV0123@0AEBW4MeshBooleanType@3@@Z)  610_CSGTree_bin G:\Realcut\LIBS\libigl\build-Tutorials\610_CSGTree\main.obj 1   Build   
`

Could you please help me?
Thank you

**Comment by alecjacobson** [comment]
This could be problem of CGAL being compiled with different compiler settings from libigl. Is this still an issue?
