### ISSUE TITLE
How to use  CholmodSolver or  taucsSolver ?

### ISSUE THREAD

**Issue by wguo68** [libigl/libigl#306]
I have installed CGAL and suitesparse in my computer.
I build the tutorial but didn't find  CholmodSolver although there are solvers such as MIsolver. I look at the the "CMakeLists.txt" in the folder "CoMiSo", It seems  CholmodSolver is not included in the CoMiSo? Can I use  CholmodSolver in my code?

If I want to solve AX=b ,but A is a large sparse matrix and not square.  
Do I have to convert it to A^t*A = A^t*b? If so ,how to do large sparse matrix multiplication and multiplication of a matrix and vector? Should I use GMM ?

Is there any example of "quadratic energy" where I needn't to do  A^t*A and A^t*b and directly to solve it?
Thanks

**Comment by danielepanozzo** [comment]
Hi, there are no wrappers for cholmod in libigl and it is not used anywhere. For  solving sparse linear system we use Eigen: https://eigen.tuxfamily.org/dox-devel/group__TopicSparseSystems.html
