### ISSUE TITLE
Question about 203_CurvatureDirections

### ISSUE THREAD

**Issue by thomas39104** [libigl/libigl#310]
Hi everybody, 

First i want to thanks for make this nice project public. i have a question about the principal curvature example. When looking at fandisk.off example i noticed some strange behaviour, for hyperbolic planes the k1 and k2 are exchanged which shouldn’t be. 
Green = Kmin = k1
Red = Kmax = k2 

![libigl viewer_127](https://cloud.githubusercontent.com/assets/20520997/16922503/0acb6510-4d16-11e6-86ad-ce674b4b9f8d.png)
i marked the hyperbolic parts where i think kmin kmax are exchanged for some reason.

![libigl viewer_128](https://cloud.githubusercontent.com/assets/20520997/16922487/fe54a2a6-4d15-11e6-804c-f6a30683d98e.png)

Any help or advise would be nice. I tried to change the vectors back for areas where (k1*k2)<0 but the result has been a bit unsatisfying. Only half of the points has been changed.

**Comment by thomas39104** [comment]
ok i noticed there is a strong influence on the problem by sharp edges. Is it possible to just push parts of a surface which are continous to the function? This parts would not be waterproofed or closed.

**Comment by alecjacobson** [comment]
Well, I suppose you could cut your mesh along edges that have small dihedral angles. Then you'd get funny values along those boundaries rather than along the creases. Not sure if that's what you want.

**Comment by copyme** [comment]
@thomas39104 Is your question answered? If so, can this issue be closed?
