### ISSUE TITLE
slice and colon in MATLAB cheat sheet

### ISSUE THREAD

**Issue by krey** [libigl/libigl#312]
From the MATLAB to[ Eigen+igl cheat sheet](https://libigl.github.io/libigl/matlab-to-eigen.html):

MATLAB: `B = A(I,:)`

igl: `B = igl::slice(A,I,igl::colon(0,A.cols()-1))`

I was unable to get this to work. First of all, I get the error:
`error: no matching function for call to 'colon(int, Eigen::Index)'`
which I was able to fix by using `igl::colon<uint, uint>(0, A.cols()-1)` instead.

Slice then works, but only with the following syntax:

`mat B; igl::slice(A,I,igl::colon<uint, uint>(0,A.cols()-1), B);`

and not with the equality one.

(I'm using GCC 6.1.1 on Archlinux. libigl ~ a week old from GitHub)

**Comment by alecjacobson** [comment]
Thanks for reporting this. To convert:

    B = A(I,:);

into Eigen+libigl, use:

    igl::slice(A,I,1,B)

I've updated the documentation.
