### ISSUE TITLE
writeOFF

### ISSUE THREAD

**Issue by odedstein** [libigl/libigl#315]
The writeOFF function only accepts vertices in R3.

Line 21 of writeOFF.cpp is the following:
assert(V.cols() == 3 && "V should have 3 columns");

Is there a reason for that? I would like to use this function to export scalar fields and vector fields on my mesh. For that reason it would be useful if vertices could be in R4 or R6.

**Comment by alecjacobson** [comment]
There's no real reason other than `.off` is a moderately standard format
and the standard (I believe) mandates 3D vertex positions:
https://en.wikipedia.org/w/index.php?title=OFF_%28file_format%29&type=revision&diff=721824256&oldid=566712475

If you take a look inside the implementation you'll see that it's _very_
easy to write these kind of formats using Eigen's IOFormat thing.

However, if you want to stick to semi-standard things with libigl you
could: 1) use .off for the mesh and .dmat for the scalar field(s), 2) use
.xml to store everything or 3) use MATLAB's .mat format to store everything
(easy to communicate with MATLAB, useless if you don't have MATLAB
installed).

**Comment by odedstein** [comment]
Thank you for your answer. I think for my purpose using .mat is the correct choice.
