### ISSUE TITLE
608_LIM example with 3D triangle mesh

### ISSUE THREAD

**Issue by josecalvario** [libigl/libigl#319]
Hello,

I'm trying to adapt the tutorial 608_LIM to my triangle mesh, a simple cube with 2 triangles on each face.
The example works well with a 2D mesh, but I'm having some problems with my 3D cube. I'm getting asserts on Eigen code.
Before I post my code, I'd like to know if what I'm doing is possible? Is the LIM code supporting 3D triangle mesh deformations? If so, can I post my example code for you to examine?

Thanks in advance,
José Calvário

**Comment by danielepanozzo** [comment]
No it does not support it. LIM is designed to prevent flipped elements which makes sense for triangles in 2D and tetrahedra in 3D. If you want to deform triangles in 3D (where flipping cannot occur), you can use ARAP, BBW or FAST --- there are examples for all of them in the libigl tutorial.

**Comment by josecalvario** [comment]
Thank you, I will use that on my 3D meshes.
