### ISSUE TITLE
can't use igl::lim on 2D mesh

### ISSUE THREAD

**Issue by josecalvario** [libigl/libigl#324]
[mesh.zip](https://github.com/libigl/libigl/files/422475/mesh.zip)

Hello,

I'm trying to use the igl::lim method to deform a 2D mesh, but it fails always on the first iteration when calling computeNMFunction for the first time. 
On line 293 of LIMSolver2D.cpp: 
double det = D.determinant();
det (relative to the first triangle) is negative which causes the algorithm interruption with state = INFEASIBLE

My mesh (attached on mesh.zip) appears to be OK. Could you please help me and see if there is anything wrong with my mesh, or is this a limitation of the algorithm?

I'm using this mesh on the 608_LIM tutorial. The changes on main.cpp are the following:
`igl::readOFF(TUTORIAL_SHARED_PATH "/mesh.off", V0, F);

  C.resize(2 \* 2, V0.rows() \* 2);
  C.insert(0, 2 \* 368) = 1;
  C.insert(1, 2 \* 368 + 1) = 1;
  C.insert(2, 2 \* 369) = 1;
  C.insert(3, 2 \* 369 + 1) = 1;

  b.resize(2 \* 2);
  b(0) = V0(368, 0);
  b(1) = V0(368, 1);
  b(2) = V0(369, 0) + 1;
  b(3) = V0(369, 1) + 1;`

Thanks in advance,
José Calvário

**Comment by alecjacobson** [comment]
I don't see anything obviously wrong with the mesh. Perhaps the entire mesh
is inverted? Try flipping the left-right order of the face list.

**Comment by josecalvario** [comment]
Thank you.
You were right. I flipped all the triangles and the problem was solved.
Should I assume that the LIM algorithm is sensitive to the triangles orientation?

**Comment by alecjacobson** [comment]
Yes. AFAIK LIM is assuming ccw orientation means positive area. It's trying
to maintain the positive area of all triangle and needs to have an all
positive area initial guess.
