### ISSUE TITLE
Tutorial Cannot run using Win10 + VS2015 in 32bit

### ISSUE THREAD

**Issue by chenweikai** [libigl/libigl#329]
Hi,

I'm trying to compile libigl tutorials. If I build in 64bit, everything is super fine. Unfortunately, I have to stay in 32 bit because of compatibility with one of my licensed library. 

Now the problem is that I cannot run the tutorials successfully in 32bit. igl.lib and iglviewer.lib cannot be complied successfully in the beginning. But after I added "EIGEN_DONT_ALIGN" to the preprocessor, both libs can be compiled (note that there was no compile errors in 64bit even "EIGEN_DONT_ALIGN" was not specified).  Now the weird thing is that many of the tutorial examples can be complied successfully, but all of them will crash during running. For example, "102 DrawMesh_bin" will crash when the program is executing "viewer.data.set_mesh(V,F);".  The error message is:

The block at 0x009F2008 was not allocated by _aligned routines, use free()

I'm using Win10 + VS2015 Community Edition. Could you provide any solution to fix it? Thank you very much!

**Comment by chenweikai** [comment]
PS: the mesh can be loaded successfully using igl::readOFF(). V and F are not NULL value.

**Comment by alecjacobson** [comment]
Can you post a specific case where it crashes and a full back trace? Are
you sure Eigen will work for 32 bit?

**Comment by chenweikai** [comment]
I think Eigen works for 32 bit. I have tested the same sample code of 102_DrawMesh_bin in a separate project without using nanogui and only include header files. The sample code works well. But in the tutorial project, it cannot run.

I traced the code and it crashed in executing the line "_mm_free(ptr)" of aligned_free() function inside "Eigen\src\Core\util\Memory.h"

inline void aligned_free(void *ptr)
{
  #if !EIGEN_ALIGN
    std::free(ptr);
  #elif EIGEN_MALLOC_ALREADY_ALIGNED
    std::free(ptr);
  #elif EIGEN_HAS_POSIX_MEMALIGN
    std::free(ptr);
  #elif EIGEN_HAS_MM_MALLOC
    _mm_free(ptr); // crashed here
  #elif defined(_MSC_VER) && (!defined(_WIN32_WCE))
    _aligned_free(ptr);
  #else
    handmade_aligned_free(ptr);
  #endif
}

The call stack is showed as below.
>	102_DrawMesh_bin.exe!Eigen::internal::aligned_free(void * ptr) Line 247	C++
 	102_DrawMesh_bin.exe!Eigen::internal::conditional_aligned_free<1>(void * ptr) Line 317	C++
 	102_DrawMesh_bin.exe!Eigen::internal::conditional_aligned_delete_auto<double,1>(double * ptr, unsigned int size) Line 445	C++
 	102_DrawMesh_bin.exe!Eigen::DenseStorage<double,-1,-1,1,0>::~DenseStorage<double,-1,-1,1,0>() Line 403	C++
 	[External Code]	
 	102_DrawMesh_bin.exe!igl::doublearea<Eigen::Matrix<double,-1,-1,0,-1,-1>,Eigen::Matrix<int,-1,-1,0,-1,-1>,Eigen::Matrix<double,-1,1,0,-1,1> >(const Eigen::PlainObjectBase<Eigen::Matrix<double,-1,-1,0,-1,-1> > & V, const Eigen::PlainObjectBase<Eigen::Matrix<int,-1,-1,0,-1,-1> > & F, Eigen::PlainObjectBase<Eigen::Matrix<double,-1,1,0,-1,1> > & dblA) Line 58	C++
 	102_DrawMesh_bin.exe!igl::per_vertex_normals<Eigen::Matrix<double,-1,-1,0,-1,-1>,Eigen::Matrix<int,-1,-1,0,-1,-1>,Eigen::Matrix<double,-1,-1,0,-1,-1>,Eigen::Matrix<double,-1,-1,0,-1,-1> >(const Eigen::PlainObjectBase<Eigen::Matrix<double,-1,-1,0,-1,-1> > & V, const Eigen::PlainObjectBase<Eigen::Matrix<int,-1,-1,0,-1,-1> > & F, igl::PerVertexNormalsWeightingType weighting, const Eigen::PlainObjectBase<Eigen::Matrix<double,-1,-1,0,-1,-1> > & FN, Eigen::PlainObjectBase<Eigen::Matrix<double,-1,-1,0,-1,-1> > & N) Line 62	C++
 	102_DrawMesh_bin.exe!igl::per_vertex_normals<Eigen::Matrix<double,-1,-1,0,-1,-1>,Eigen::Matrix<int,-1,-1,0,-1,-1> >(const Eigen::PlainObjectBase<Eigen::Matrix<double,-1,-1,0,-1,-1> > & V, const Eigen::PlainObjectBase<Eigen::Matrix<int,-1,-1,0,-1,-1> > & F, const Eigen::PlainObjectBase<Eigen::Matrix<double,-1,-1,0,-1,-1> > & FN, Eigen::PlainObjectBase<Eigen::Matrix<double,-1,-1,0,-1,-1> > & N) Line 111	C++
 	102_DrawMesh_bin.exe!igl::viewer::ViewerData::compute_normals() Line 373	C++
 	102_DrawMesh_bin.exe!igl::viewer::ViewerData::set_mesh(const Eigen::Matrix<double,-1,-1,0,-1,-1> & _V, const Eigen::Matrix<int,-1,-1,0,-1,-1> & _F) Line 109	C++
 	102_DrawMesh_bin.exe!main(int argc, char * * argv) Line 16	C++

Hope the trace info would be helpful. Thanks a lot!

**Comment by alecjacobson** [comment]
Without access to a windows 32 bit machine and because we only support 64 bit, we going to need a much simpler example to narrow in on the problem here. Perhaps you can try to strip down 102_DrawMesh to the smallest program where this still euro still occurs.

**Comment by copyme** [comment]
@chenweikai is the issue resolved? Should it be closed now?

**Comment by chenweikai** [comment]
The issue still remains. But you can close it now as I have switched to a 64-bit OS. Thanks. 

> @chenweikai is the issue resolved? Should it be closed now?

**Comment by jdumas** [comment]
It is specified on the website that we support only 64bit on Windows, so I'll close this.
