### ISSUE TITLE
Reading ASCII STL into float fails

### ISSUE THREAD

**Issue by bjj** [libigl/libigl#33]
readSTL is templated for different scalar types, but it uses fscanf instead of C++ IO and hardcodes %lg which requires pointers to doubles.

Can be solved many ways, like switching to C++ IO, or reading into temporary doubles and assigning back to TypeV, TypeN, etc.  Could also assume either float or double and switch format strings based on size.

If you read an ASCII STL into floats with the current code it's corrupting memory (writing a double into float storage) and returning the wrong values (all zeros in the one case I tried, but it was a unit cube).

**Comment by alecjacobson** [comment]
You're absolutely right. I pushed a change that reads into temporary doubles (VERSION 1.1.2). C++ IO would be a better solution, but requires a little more effort.
