### ISSUE TITLE
Cannot build igl using Windows + Visual Studio

### ISSUE THREAD

**Issue by NMO13** [libigl/libigl#330]
Hi,

basically, this is an extremely great project!
However, I have some problems getting it to run. I'm using Windows 10 64 bit and Visual Studio 2015 32 bit.
I built the Visual Studio project using cmake as described in the tutorial. When I open the libigl solution and click on rebuild I get the following errors:

Severity    Code    Description Project File    Line    Suppression State
Error   C2719   'p': formal parameter with requested alignment of 16 won't be aligned   igl C:\Users\Martin\Desktop\libigl\include\igl\point_simplex_squared_distance.cpp   43  
Error   C2719   'other': formal parameter with requested alignment of 16 won't be aligned (compiling source file C:\Users\Martin\Desktop\libigl\include\igl\signed_distance.cpp)    igl c:\users\martin\desktop\libigl\include\igl\AABB.h   73  
Error   C2719   'other': formal parameter with requested alignment of 16 won't be aligned (compiling source file C:\Users\Martin\Desktop\libigl\include\igl\point_mesh_squared_distance.cpp)    igl c:\users\martin\desktop\libigl\include\igl\AABB.h   73  
Error   C2719   'other': formal parameter with requested alignment of 16 won't be aligned (compiling source file C:\Users\Martin\Desktop\libigl\include\igl\in_element.cpp) igl c:\users\martin\desktop\libigl\include\igl\AABB.h   73  
Error   C2719   'other': formal parameter with requested alignment of 16 won't be aligned (compiling source file C:\Users\Martin\Desktop\libigl\include\igl\AABB.cpp)   igl c:\users\martin\desktop\libigl\include\igl\AABB.h   73  
Error   C2719   'c': formal parameter with requested alignment of 16 won't be aligned   igl C:\Users\Martin\Desktop\libigl\include\igl\point_simplex_squared_distance.cpp   43  
Error   C2719   'b': formal parameter with requested alignment of 16 won't be aligned   igl C:\Users\Martin\Desktop\libigl\include\igl\point_simplex_squared_distance.cpp   43  
Error   C2719   'a': formal parameter with requested alignment of 16 won't be aligned   igl C:\Users\Martin\Desktop\libigl\include\igl\point_simplex_squared_distance.cpp   43

**Comment by danielepanozzo** [comment]
Could you try to switch to 64 bit? The 32bit build is not supported.

**Comment by NMO13** [comment]
64  bit compiling worked! But now I have another problem regarding the tool swept volume example. I have added a screenshot.
![untitled](https://cloud.githubusercontent.com/assets/3988444/18101390/d9d1889a-6eee-11e6-9f65-95fc7dd0b248.png)

**Comment by fusentasticus** [comment]
I see same crash of 707 (header mode, VS2015, 64 bit, with separate CGAL+BOOST, and built-in nanogui Eigen):

`Computing swept volume...Assertion failed: diff<=1e-10 && "distance should match norm of difference", file c:....\libigl\include\igl\AABB.cpp, line 771
`

Stack trace:
```
ucrtbased.dll!00007ff96ee71a05()	Unknown
 	ucrtbased.dll!00007ff96ee71ba3()	Unknown
 	ucrtbased.dll!00007ff96ee92b7d()	Unknown
 	ucrtbased.dll!00007ff96ee98765()	Unknown
 	ucrtbased.dll!00007ff96ee98287()	Unknown
 	ucrtbased.dll!00007ff96ee96318()	Unknown
 	ucrtbased.dll!00007ff96ee98cef()	Unknown
>	707_SweptVolume_bin.exe!igl::AABB<Eigen::Matrix<double,-1,-1,0,-1,-1>,3>::set_min(const Eigen::Matrix<double,1,3,1,1,3> & p, const double sqr_d_candidate, const int i_candidate, const Eigen::Matrix<double,1,3,1,1,3> & c_candidate, double & sqr_d, int & i, Eigen::Matrix<double,1,3,1,1,3> & c) Line 771	C++
 	707_SweptVolume_bin.exe!igl::AABB<Eigen::Matrix<double,-1,-1,0,-1,-1>,3>::squared_distance::__l7::<lambda>() Line 395	C++
 	707_SweptVolume_bin.exe!igl::AABB<Eigen::Matrix<double,-1,-1,0,-1,-1>,3>::squared_distance(const Eigen::PlainObjectBase<Eigen::Matrix<double,-1,-1,0,-1,-1> > & V, const Eigen::Matrix<int,-1,-1,0,-1,-1> & Ele, const Eigen::Matrix<double,1,3,1,1,3> & p, const double min_sqr_d, int & i, Eigen::Matrix<double,1,3,1,1,3> & c) Line 424	C++
 	707_SweptVolume_bin.exe!igl::swept_volume_signed_distance(const Eigen::Matrix<double,-1,-1,0,-1,-1> & V, const Eigen::Matrix<int,-1,-1,0,-1,-1> & F, const std::function<Eigen::Transform<double,3,2,0> __cdecl(double)> & transform, const unsigned __int64 & steps, const Eigen::Matrix<double,-1,-1,0,-1,-1> & GV, const Eigen::Matrix<int,1,3,1,1,3> & res, const double h, const double isolevel, const Eigen::Matrix<double,-1,1,0,-1,1> & S0, Eigen::Matrix<double,-1,1,0,-1,1> & S) Line 69	C++
 	707_SweptVolume_bin.exe!igl::swept_volume_signed_distance(const Eigen::Matrix<double,-1,-1,0,-1,-1> & V, const Eigen::Matrix<int,-1,-1,0,-1,-1> & F, const std::function<Eigen::Transform<double,3,2,0> __cdecl(double)> & transform, const unsigned __int64 & steps, const Eigen::Matrix<double,-1,-1,0,-1,-1> & GV, const Eigen::Matrix<int,1,3,1,1,3> & res, const double h, const double isolevel, Eigen::Matrix<double,-1,1,0,-1,1> & S) Line 113	C++
 	707_SweptVolume_bin.exe!igl::copyleft::swept_volume(const Eigen::Matrix<double,-1,-1,0,-1,-1> & V, const Eigen::Matrix<int,-1,-1,0,-1,-1> & F, const std::function<Eigen::Transform<double,3,2,0> __cdecl(double)> & transform, const unsigned __int64 steps, const unsigned __int64 grid_res, const unsigned __int64 isolevel_grid, Eigen::Matrix<double,-1,-1,0,-1,-1> & SV, Eigen::Matrix<int,-1,-1,0,-1,-1> & SF) Line 47	C++
 	707_SweptVolume_bin.exe!main(int argc, char * * argv) Line 41	C++
 	[External Code]
```

**Comment by alecjacobson** [comment]
Could you post a minimal program + input that causes this error?

**Comment by copyme** [comment]
I suggest to close the issue - it is old, does not reflect the current code and it cannot be reproduced.
