### ISSUE TITLE
Import error pyigl in Ubuntu 16.04 with Python 2.7

### ISSUE THREAD

**Issue by glrnyhc** [libigl/libigl#333]
Hello. 

I have compiled the Python bindings successfully in Python 3.5, and now I am able to do `import pyigl` without any problems. However, I decided to change to Python 2.7. I configured the Python path in CMake, and I have compiled the bindings properly (although with many warnings, maybe). However, I am not able to import pyigl. I get the following error:

`ImportError: ./pyigl.so: undefined symbol: _ZN6COMISO15EigenLDLTSolverD1Ev`

Any help to solve the problem would be appreciated, thanks.

**Comment by s-koch** [comment]
Hi,
unfortunately I cannot reproduce your problem on a fresh Ubuntu 16.04. installation. How did you configure the Pythonpath in CMake? One thing you could try is enabling the CMake flag `CHECK_UNDEFINED` to find out what exactly is missing.

**Comment by glrnyhc** [comment]
Thanks for your response. I used CMake-GUI to set the Python path, but I think the problem is other. When it is building, the compiler shows many messages saying "plugin needed to handle lto object", so maybe it has something to do with other thing. Eventually, I decided to change to Python 3.5 again, where I can compile the Python bindings with no problems.

**Comment by s-koch** [comment]
Yes, there is a problem with LinkTimeOptimization which somehow does not work with Python 2 but 3. If you still need Python2.7 support you could also switch this of by removing the `-flto` flag in line 34 of the CMakeLists.txt.

**Comment by glrnyhc** [comment]
Thank you so much, we will try in the near future. By now we are using Python 3.5 bindings successfully.

**Comment by glrnyhc** [comment]
Removing the `-flto` flag, the bindings worked properly with Python 2.7. Thank you for your help, it has been very helpful.
