### ISSUE TITLE
libigl with VS2015

### ISSUE THREAD

**Issue by sonalipatil** [libigl/libigl#336]
I was trying to build tutorial 610 (CSG tree) , but it's complaining about CGAL, I linked it with the version I have built with VS 2015, (as cgal folder was missing in /external. I am getting following link error

Error   LNK2019 unresolved external symbol "bool __cdecl igl::copyleft::cgal::mesh_boolean<class Eigen::Matrix<class CGAL::Lazy_exact_nt<class CGAL::Gmpq>,-1,3,0,-1,3>,class Eigen::Matrix<int,-1,-1,0,-1,-1>,class Eigen::Matrix<class CGAL::Lazy_exact_nt<class CGAL::Gmpq>,-1,3,0,-1,3>,class Eigen::Matrix<int,-1,-1,0,-1,-1>,class Eigen::Matrix<class CGAL::Lazy_exact_nt<class CGAL::Gmpq>,-1,3,0,-1,3>,class Eigen::Matrix<int,-1,-1,0,-1,-1>,class Eigen::Matrix<__int64,-1,1,0,-1,1> >(class Eigen::PlainObjectBase<class Eigen::Matrix<class CGAL::Lazy_exact_nt<class CGAL::Gmpq>,-1,3,0,-1,3> > const &,class Eigen::PlainObjectBase<class Eigen::Matrix<int,-1,-1,0,-1,-1> > const &,class Eigen::PlainObjectBase<class Eigen::Matrix<class CGAL::Lazy_exact_nt<class CGAL::Gmpq>,-1,3,0,-1,3> > const &,class Eigen::PlainObjectBase<class Eigen::Matrix<int,-1,-1,0,-1,-1> > const &,enum igl::MeshBooleanType const &,class Eigen::PlainObjectBase<class Eigen::Matrix<class CGAL::Lazy_exact_nt<class CGAL::Gmpq>,-1,3,0,-1,3> > &,class Eigen::PlainObjectBase<class Eigen::Matrix<int,-1,-1,0,-1,-1> > &,class Eigen::PlainObjectBase<class Eigen::Matrix<__int64,-1,1,0,-1,1> > &)" (??$mesh_boolean@V?$Matrix@V?$Lazy_exact_nt@VGmpq@CGAL@@@CGAL@@$0?0$02$0A@$0?0$02@Eigen@@V?$Matrix@H$0?0$0?0$0A@$0?0$0?0@2@V12@V32@V12@V32@V?$Matrix@_J$0?0$00$0A@$0?0$00@2@@cgal@copyleft@igl@@YA_NAEBV?$PlainObjectBase@V?$Matrix@V?$Lazy_exact_nt@VGmpq@CGAL@@@CGAL@@$0?0$02$0A@$0?0$02@Eigen@@@Eigen@@AEBV?$PlainObjectBase@V?$Matrix@H$0?0$0?0$0A@$0?0$0?0@Eigen@@@4@01AEBW4MeshBooleanType@2@AEAV34@AEAV54@AEAV?$PlainObjectBase@V?$Matrix@_J$0?0$00$0A@$0?0$00@Eigen@@@4@@Z) referenced in function "public: __cdecl igl::copyleft::cgal::CSGTree::CSGTree(class igl::copyleft::cgal::CSGTree const &,class igl::copyleft::cgal::CSGTree const &,enum igl::MeshBooleanType const &)" (??0CSGTree@cgal@copyleft@igl@@QEAA@AEBV0123@0AEBW4MeshBooleanType@3@@Z)  610_CSGTree_bin

**Comment by fusentasticus** [comment]
Use cmake-gui, then untick LIBIGL_USE_STATIC_LIBRARY, and re-generate build system. Accept reload of all build files in VS (if it's open already). Then, just build!

With static (non-header mode) and CGAL/BOOST,  seven examples fail:
```
609_Boolean_bin.exe : fatal error LNK1120: 10 unresolved externals
405_AsRigidAsPossible_bin.exe : fatal error LNK1120: 10 unresolved externals
610_CSGTree_bin.exe : fatal error LNK1120: 1 unresolved externals
303_LaplaceEquation_bin.exe : fatal error LNK1120: 10 unresolved externals
401_BiharmonicDeformation_bin.exe : fatal error LNK1120: 10 unresolved externals
402_PolyharmonicDeformation_bin.exe : fatal error LNK1120: 10 unresolved externals
407_BiharmonicCoordinates_bin.exe : fatal error LNK1120: 10 unresolved externals

```
In header mode, the fatal errors are:
```

libigl\external\comiso\ext\gmm-4.2\include\gmm\gmm_std.h(64): fatal error C1189: #error:  Add the option /D_SCL_SECURE_NO_DEPRECATE to the compilation command
libigl\external\comiso\ext\gmm-4.2\include\gmm\gmm_std.h(64): fatal error C1189: #error:  Add the option /D_SCL_SECURE_NO_DEPRECATE to the compilation command
libigl\external\comiso\ext\gmm-4.2\include\gmm\gmm_std.h(64): fatal error C1189: #error:  Add the option /D_SCL_SECURE_NO_DEPRECATE to the compilation command
libigl\external\comiso\ext\gmm-4.2\include\gmm\gmm_std.h(64): fatal error C1189: #error:  Add the option /D_SCL_SECURE_NO_DEPRECATE to the compilation command

```

**Comment by alecjacobson** [comment]
Is this still happening? Could you try a _clean_ build with `LIBIGL_USE_STATIC_LIBRARY=OFF` ?

**Comment by liangbright** [comment]
It is still happening.
VS2015+CGAL4.7+untick LIBIGL_USE_STATIC_LIBRARY in cmake-gui
same errors:
\libigl\external\comiso\ext\gmm-4.2\include\gmm\gmm_std.h(64): fatal error C1189: #error:  Add the option /D_SCL_SECURE_NO_DEPRECATE to the compilation command
\libigl\external\comiso\ext\gmm-4.2\include\gmm\gmm_std.h(64): fatal error C1189: #error:  Add the option /D_SCL_SECURE_NO_DEPRECATE to the compilation command
\libigl\external\comiso\ext\gmm-4.2\include\gmm\gmm_std.h(64): fatal error C1189: #error:  Add the option /D_SCL_SECURE_NO_DEPRECATE to the compilation command
\libigl\external\comiso\ext\gmm-4.2\include\gmm\gmm_std.h(64): fatal error C1189: #error:  Add the option /D_SCL_SECURE_NO_DEPRECATE to the compilation command

BTW: 
please modify line-124 in read_triangle_mesh.cpp to v.resize((std::min)(v.size(),(size_t)3));
otherwise, it will lead to compilation error error C2589: '(': illegal token on right side of '::'

**Comment by copyme** [comment]
@liangbright Did you solve the issue? Should it be closed now?

**Comment by jdumas** [comment]
The CGAL setup has changed quite a bit since 2016, and we now build it on AppVeyor too, so I'll close this for now.
