### ISSUE TITLE
Numerical Issue with biharmonic_coordinates

### ISSUE THREAD

**Issue by apapaxiong** [libigl/libigl#337]
Hi Alec,
I always get a result of "Numerical Issue" from biharmonic_coordinates function. I used Eigen 3.2.8. I also tried 3.2.7. It has the same problem. Why? 

Here is my code:
       readMESH("octopus-low.mesh", low.V, low.T, low.F);
    int k = 2;
    vector<vector<int> > S;
    S.resize(1);
    S[0].resize(1);
    S[0][0] = 1;
    igl::biharmonic_coordinates(low.V, low.T, S, k, W);

**Comment by alecjacobson** [comment]
Does example 407 work for you?
https://libigl.github.io/libigl/tutorial/tutorial.html#biharmoniccoordinates

**Comment by apapaxiong** [comment]
It also didn't work. Which version of Eigen do you recommend to use?
The problem happens in this function: min_quad_with_fixed_precompute

`if(data.Auu_pd && neq == 0)
    {
#ifdef MIN_QUAD_WITH_FIXED_CPP_DEBUG
    cout<<"    llt"<<endl;
#endif
      data.llt.compute(Auu);
      switch(data.llt.info())
      {
        case Eigen::Success:
          break;
        case Eigen::NumericalIssue:
          cerr<<"Error: Numerical issue."<<endl;
          return false;
        default:
          cerr<<"Error: Other."<<endl;
          return false;
      }
      data.solver_type = min_quad_with_fixed_data<T>::LLT;
    }else`

**Comment by apapaxiong** [comment]
I also used the EIGEN_DONT_ALIGN. Does it cause the problem?

**Comment by alecjacobson** [comment]
`EIGEN_DONT_ALIGN` shouldn't cause a problem. We're using Eigen 3.2.

**Comment by alecjacobson** [comment]
Rereading your original code, I think you're only fixing a single handle. For `biharmonic_coordinates` (distance from bounded biharmonic weights) you must fix #dimensions + 1 handles.

**Comment by copyme** [comment]
@apapaxiong Should not this issue be closed now?
