### ISSUE TITLE
lscm numerical issue

### ISSUE THREAD

**Issue by ckalas** [libigl/libigl#343]
I'm getting a numerical issue warning during lscm() and was trying to figure out why. After tracing it to min_quad_with_compute() I couldn't find anything more.

It was working for another mesh using the default values you put in the tutorial, but with a new mesh it doesnt. Do the boundaries need changing? The only difference I can tell between the working and the not working is the vertex values are a bit larger in general in the latter.

Is there any way I could troubleshoot this further?

**Comment by alecjacobson** [comment]
Post your mesh here if you can.

You could look for: degenerate faces, unreferenced vertices and be sure
that you have adequate constraints (fix at least two points I believe).

**Comment by ckalas** [comment]
If this link works, https://drive.google.com/open?id=0B_26Copcv2TfSFRZNy1Ia20zT2s. For the optimization I do exactly like the tutorial:

	// LSCM parametrization
	// Fix two points on the boundary
	VectorXi bnd,b(2,1);
	igl::boundary_loop(model.F,bnd);
	b(0) = bnd(0);
	b(1) = bnd(round(bnd.size()/2));
	MatrixXd bc(2,2);
	bc<<0,0,1,0;

	igl::lscm(model.V.leftCols(3),model.F,b,bc,model.V_uv);

**Comment by alecjacobson** [comment]
The linked model has 4 "unreferenced vertices". These will cause numerical issues in `igl::lscm`. You can remove them with `igl::remove_unreferenced`

**Comment by MunichMogician** [comment]
I also met this problem, could you please tell me how to use the igl::remove_unreferenced in the code specifically, like which parameter means what, or kindly show any code written when solve it? great thanks @ckalas @alecjacobson

**Comment by jdumas** [comment]
Can't you read the doc in the header file?
