### ISSUE TITLE
Individual Projects

### ISSUE THREAD

**Issue by avaxman** [libigl/libigl#348]
Is there a way to derive the individual tutorials into (say, XCode) projects? I am struggling with using 505_MIQ functionality on my own code. GMM complains about std::complex<double> not adapting to C. The tutorials themselves compile out of the box, so I am wondering what's the magic preprocessor/configuration ingredient I'm missing.

**Comment by alecjacobson** [comment]
I believe cmake can output an Xcode project.

    cmake -G Xcode ..

Another useful thing, when you're using `make` to build the tutorial, you
can issue

    make VERBOSE=1

This will show you all of the calls to gcc/clang etc. with all of the flags
being used. In the worst case, you could hunt in those for the difference
with your Xcode project.

**Comment by alecjacobson** [comment]
You may also want to check out:

https://github.com/libigl/libigl-example-project

**Comment by Aniwax** [comment]
When I try to build an Xcode project from a tutorial folder, it creates the following warning:
`CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_C_COMPILER could be found.



CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_CXX_COMPILER could be found.

`
What should I do here?
