### ISSUE TITLE
Error in compilation LIBIGL

### ISSUE THREAD

**Issue by kybio** [libigl/libigl#35]
error LNK1120: 17 unresolved externals	
error LNK2001: unresolved external symbol "public: virtual bool __thiscall CTwGraphOpenGLCore::IsDrawing(void)" (?IsDrawing@CTwGraphOpenGLCore@@UAE_NXZ)	
error LNK2001: unresolved external symbol "public: virtual void * __thiscall CTwGraphOpenGLCore::NewTextObj(void)" 
error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::BuildText(void *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const *,unsigned int *,unsigned int *,int,struct CTexFont const *,int,int)" 
error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::ChangeViewport(int,int,int,int,int,int)" 
error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::DeleteTextObj(void *)" 
error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::DrawLine(int,int,int,int,unsigned int,unsigned int,bool)" 
error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::DrawRect(int,int,int,int,unsigned int,unsigned int,unsigned int,unsigned int)" 
error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::DrawTriangles(int,int *,unsigned int *,enum ITwGraph::Cull)" 
error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::Restore(void)" 
error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::RestoreViewport(void)" 
error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::SetScissor(int,int,int,int)" 
error LNK2001: unresolved external symbol "struct CTexFont * g_DefaultNormalFont" 
error LNK2019: unresolved external symbol "public: virtual int __thiscall CTwGraphOpenGLCore::Init(void)" (?Init@CTwGraphOpenGLCore@@UAEHXZ) referenced in function "public: virtual int __thiscall igl::TextRenderer::Init(void)" 
error LNK2019: unresolved external symbol "public: virtual int __thiscall CTwGraphOpenGLCore::Shut(void)" (?Shut@CTwGraphOpenGLCore@@UAEHXZ) referenced in function "public: virtual int __thiscall igl::TextRenderer::Shut(void)" 
error LNK2019: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::BeginDraw(int,int)" (?BeginDraw@CTwGraphOpenGLCore@@UAEXHH@Z) referenced in function "public: void __thiscall igl::TextRenderer::BeginDraw(class Eigen::Matrix<float,4,4,0,4,4> const &,class Eigen::Matrix<float,4,4,0,4,4> const &,class Eigen::Matrix<float,4,1,0,4,1> const &,float)" 
error LNK2019: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::DrawText(void *,int,int,unsigned int,unsigned int)" (?DrawText@CTwGraphOpenGLCore@@UAEXPAXHHII@Z) referenced in function "public: void __thiscall igl::TextRenderer::DrawText(class Eigen::Matrix<double,3,1,0,3,1>,class Eigen::Matrix<double,3,1,0,3,1>,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" 
error LNK2019: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::EndDraw(void)" (?EndDraw@CTwGraphOpenGLCore@@UAEXXZ) referenced in function "public: virtual void __thiscall igl::TextRenderer::EndDraw(void)"

**Comment by danielepanozzo** [comment]
Please use the anttweakbar version embedded in libigl/external. We use a patched versions that exposes a few extra methods of CTwGraphOpenGLCore. Up to now, I only saw this problem while using visual studio. Could you please confirm that you are using visual studio? Which version?

**Comment by kybio** [comment]
I will try...i use visual studio 2013..Thanks!!!

**Comment by kybio** [comment]
The same problem persist, maybe I have copy all sources to directory???

**Comment by kybio** [comment]
I put the folders "include" and "lib" files, do I need to configure something else ???

**Comment by kybio** [comment]
well, I find this, could maybe help someone:

Phil writer
On windows, if you are using Visual Studio 2008 (but should be nearly the same on later versions), modify the AntTweakBar project properties as follow:

    "General/Config type" = static library
    in "C-C++/Preprocessor/Def" replace TW_EXPORTS by TW_STATIC
    "Lib gen/General/Output filename" = $(OutDir)/AntTweakBarStatic.lib (to avoid confusion with the dynamic lib)

In your project properties, in "C-C++/Preprocessor/Def", define TW_STATIC

Then rebuild AntTweakBar and your project, and it should be ok.

**Comment by alecjacobson** [comment]
kybio, did defining TW_STATIC solve your problems?

**Comment by kybio** [comment]
No..unfortunately does not resolve my  problem..

**Comment by RogersDoug** [comment]
Are you using it as a .dll?
Try defining these:
_USRDLL
TW_EXPORTS

**Comment by kybio** [comment]
Eu compilei o AnttWeakBar.lib e coloquei no "Preprocess" do Visual Studio o TW_STATIC, coloquei no "include" o "AntTweakBar.dll" e o "AntTweakBar.h". E no "lib" do Visual Studio coloquei o "AntTweakBar.lib" (com mais de 8 mb).  Coloquei no projeto tutorial "102_DrawMesh" no linker input "additional dependencies" e no "system" tentei tanto console como "Windows"...33 errors

1>------ Build started: Project: ConsoleApplication1, Configuration: Debug Win32 ------
1>AntTweakBar.lib(TwMgr.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in main.obj
1>AntTweakBar.lib(TwOpenGLCore.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in main.obj
1>AntTweakBar.lib(TwFonts.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in main.obj
1>AntTweakBar.lib(TwPrecomp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in main.obj
1>AntTweakBar.lib(TwColors.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in main.obj
1>AntTweakBar.lib(TwBar.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in main.obj
1>AntTweakBar.lib(TwOpenGL.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in main.obj
1>AntTweakBar.lib(TwDirect3D9.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in main.obj
1>AntTweakBar.lib(TwDirect3D10.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in main.obj
1>AntTweakBar.lib(TwDirect3D11.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in main.obj
1>AntTweakBar.lib(LoadOGLCore.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in main.obj
1>AntTweakBar.lib(LoadOGL.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in main.obj
1>msvcprtd.lib(MSVCP120D.dll) : error LNK2005: "public: __thiscall std::_Container_base12::_Container_base12(void)" (??0_Container_base12@std@@QAE@XZ) already defined in AntTweakBar.lib(TwMgr.obj)
1>msvcprtd.lib(MSVCP120D.dll) : error LNK2005: "public: __thiscall std::_Container_base12::~_Container_base12(void)" (??1_Container_base12@std@@QAE@XZ) already defined in AntTweakBar.lib(TwMgr.obj)
1>msvcprtd.lib(MSVCP120D.dll) : error LNK2005: "public: struct std::_Iterator_base12 * * __thiscall std::_Container_base12::_Getpfirst(void)const " (?_Getpfirst@_Container_base12@std@@QBEPAPAU_Iterator_base12@2@XZ) already defined in AntTweakBar.lib(TwMgr.obj)
1>msvcprtd.lib(MSVCP120D.dll) : error LNK2005: "public: void __thiscall std::_Container_base12::_Orphan_all(void)" (?_Orphan_all@_Container_base12@std@@QAEXXZ) already defined in AntTweakBar.lib(TwMgr.obj)
1>msvcprtd.lib(MSVCP120D.dll) : error LNK2005: "public: void __thiscall std::_Container_base12::_Swap_all(struct std::_Container_base12 &)" (?_Swap_all@_Container_base12@std@@QAEXAAU12@@Z) already defined in AntTweakBar.lib(TwMgr.obj)
1>msvcprtd.lib(MSVCP120D.dll) : error LNK2005: "public: __thiscall std::locale::id::id(unsigned int)" (??0id@locale@std@@QAE@I@Z) already defined in AntTweakBar.lib(TwMgr.obj)
1>msvcprtd.lib(MSVCP120D.dll) : error LNK2005: "public: bool __thiscall std::ios_base::good(void)const " (?good@ios_base@std@@QBE_NXZ) already defined in AntTweakBar.lib(TwMgr.obj)
1>msvcprtd.lib(MSVCP120D.dll) : error LNK2005: "public: int __thiscall std::ios_base::flags(void)const " (?flags@ios_base@std@@QBEHXZ) already defined in AntTweakBar.lib(TwMgr.obj)
1>msvcprtd.lib(MSVCP120D.dll) : error LNK2005: "public: __int64 __thiscall std::ios_base::width(void)const " (?width@ios_base@std@@QBE_JXZ) already defined in AntTweakBar.lib(TwMgr.obj)
1>msvcprtd.lib(MSVCP120D.dll) : error LNK2005: "public: __int64 __thiscall std::ios_base::width(__int64)" (?width@ios_base@std@@QAE_J_J@Z) already defined in AntTweakBar.lib(TwMgr.obj)
1>msvcprtd.lib(MSVCP120D.dll) : error LNK2005: "public: int __thiscall std::basic_streambuf<char,struct std::char_traits<char> >::sputc(char)" (?sputc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QAEHD@Z) already defined in AntTweakBar.lib(TwMgr.obj)
1>msvcprtd.lib(MSVCP120D.dll) : error LNK2005: "public: __int64 __thiscall std::basic_streambuf<char,struct std::char_traits<char> >::sputn(char const *,__int64)" (?sputn@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QAE_JPBD_J@Z) already defined in AntTweakBar.lib(TwMgr.obj)
1>msvcprtd.lib(MSVCP120D.dll) : error LNK2005: "public: void __thiscall std::basic_ios<char,struct std::char_traits<char> >::setstate(int,bool)" (?setstate@?$basic_ios@DU?$char_traits@D@std@@@std@@QAEXH_N@Z) already defined in AntTweakBar.lib(TwMgr.obj)
1>msvcprtd.lib(MSVCP120D.dll) : error LNK2005: "public: class std::basic_ostream<char,struct std::char_traits<char> > * __thiscall std::basic_ios<char,struct std::char_traits<char> >::tie(void)const " (?tie@?$basic_ios@DU?$char_traits@D@std@@@std@@QBEPAV?$basic_ostream@DU?$char_traits@D@std@@@2@XZ) already defined in AntTweakBar.lib(TwMgr.obj)
1>msvcprtd.lib(MSVCP120D.dll) : error LNK2005: "public: class std::basic_streambuf<char,struct std::char_traits<char> > * __thiscall std::basic_ios<char,struct std::char_traits<char> >::rdbuf(void)const " (?rdbuf@?$basic_ios@DU?$char_traits@D@std@@@std@@QBEPAV?$basic_streambuf@DU?$char_traits@D@std@@@2@XZ) already defined in AntTweakBar.lib(TwMgr.obj)
1>msvcprtd.lib(MSVCP120D.dll) : error LNK2005: "public: char __thiscall std::basic_ios<char,struct std::char_traits<char> >::fill(void)const " (?fill@?$basic_ios@DU?$char_traits@D@std@@@std@@QBEDXZ) already defined in AntTweakBar.lib(TwMgr.obj)
1>msvcprtd.lib(MSVCP120D.dll) : error LNK2005: "public: char __thiscall std::basic_ios<char,struct std::char_traits<char> >::widen(char)const " (?widen@?$basic_ios@DU?$char_traits@D@std@@@std@@QBEDD@Z) already defined in AntTweakBar.lib(TwMgr.obj)
1>msvcprtd.lib(MSVCP120D.dll) : error LNK2005: "public: void __thiscall std::basic_ostream<char,struct std::char_traits<char> >::_Osfx(void)" (?_Osfx@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEXXZ) already defined in AntTweakBar.lib(TwMgr.obj)
1>msvcprtd.lib(MSVCP120D.dll) : error LNK2005: "public: class std::basic_ostream<char,struct std::char_traits<char> > & __thiscall std::basic_ostream<char,struct std::char_traits<char> >::operator<<(int)" (??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@H@Z) already defined in AntTweakBar.lib(TwMgr.obj)
1>msvcprtd.lib(MSVCP120D.dll) : error LNK2005: "public: class std::basic_ostream<char,struct std::char_traits<char> > & __thiscall std::basic_ostream<char,struct std::char_traits<char> >::flush(void)" (?flush@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV12@XZ) already defined in AntTweakBar.lib(TwMgr.obj)
1>LINK : fatal error LNK1104: cannot open file 'AntTweakBarStatic.lib'
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by kybio** [comment]
Excuse...
I compiled the AnttWeakBar.lib and put in "Preprocess" Visual Studio the TW_STATIC, put in "include" the "AntTweakBar.dll" and the "AntTweakBar.h". And in the "lib" Visual Studio put the "AntTweakBar.lib" (over 8 mb). I put in the tutorial project "102_DrawMesh" in the linker input "additional dependencies" and "system" tried both console as "Windows" ... 33 errors

**Comment by kybio** [comment]
RogersDoug I liked your project..thanks

**Comment by RogersDoug** [comment]
Here is the project file and the filter file
https://dl.dropboxusercontent.com/u/85781814/AntTweakBar.vcxproj

https://dl.dropboxusercontent.com/u/85781814/AntTweakBar.vcxproj.user

**Comment by kybio** [comment]
my visual studio is Ultimate 2013, thank you for the project code..I will try again...

**Comment by chenhonghua** [comment]
@RogersDoug Hi,RogersDoug. 
I am confused with same problem. I can't open the link you provided above . Could you send your project to my email(1063678829@qq.com)?

**Comment by danielepanozzo** [comment]
We now have a continuous build for VS 2015. If you still have compilation issues, please take a look there and check what the differences are. Since our time is limited, we are only supporting the build on VS2015.
https://ci.appveyor.com/project/danielepanozzo/libigl-6hjk1
