### ISSUE TITLE
Python binding linkage error

### ISSUE THREAD

**Issue by MichaelRabinovich** [libigl/libigl#350]
Hey all,

I've followed the instructions at: https://github.com/libigl/libigl/tree/master/python
and compiled it, but when I import pyigl I get the following error:

Symbol not found: ___doc_igl_copyleft_comiso_miq
  Referenced from: /Users/USER/libigl/python/tutorial/../pyigl.so
  Expected in: flat namespace
 in /Users/USER/libigl/python/tutorial/../pyigl.so

Is it broken or is there anything I've might have missed?

Thanks a lot,
Michael

**Comment by danielepanozzo** [comment]
Same for me. @s-koch : do you know why this is happening? Could you please add a few lines in the python readme to explain how to use the python script to regenerate the docstrings?

**Comment by s-koch** [comment]
I fixed the docstrings (problem with escape sequence) and added some documentation with #351.

**Comment by danielepanozzo** [comment]
Great, thanks!

Michael could you please close this issue if the patch fixes the problem for you?

**Comment by MichaelRabinovich** [comment]
Thanks! Now it works
