### ISSUE TITLE
Holes in Tet meshes

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#353]
From personal email:

> I would like to know how I can add hole and region information in the input for TetGen? I have seen the signature for function igl::tetrahedralize function but cannot find provisions for the same.

**Comment by alecjacobson** [comment]
We should first agree on what we mean by "holes". Tetgen's documentation uses "holes" in a funny way: http://wias-berlin.de/software/tetgen/fformats.poly.html
It's api let's you specify points in regions that will be classified as "outside" the volume. This allows you specify "internal cavities" (what they're calling "volume holes"). For example if you wanted to represent the shell of the earth you could provide the surface of a sphere, the surface of a smaller sphere and a point at the origin. Then tetgen would return a tet-mesh for just the space between the two sphere surfaces.
Now, the libigl wrappers `igl::tetrahedralize` currently do not expose this feature of tetgen. You could add another overload to `igl::tetrahedralize` to expose it (and then post a git Pull Request).

**Comment by luca-penasa** [comment]
I am interested in the same feature. has it been implemented somehow?
In particular I am using Polyhedral_mesh_domain_3 as input to 
CGAL::make_mesh_3(...)
to generate a 3d tet mesh. Is there any way to perform boolean operators on multiple polyhedral mesh domains to obtain a composite domain to be used to produce "holed" 3d meshes?

the example of the Earth shell is exactly what I would need to do (generating an empty shell of given thickness). Any chance to do this with libigl?

**Comment by pranavkantgaur** [comment]
@alecjacobson 
Hi,

I am working on implementing this feature. Would it be ok if I create a separate structure/class for storing attribute information associated with each tetrahedron returned by TetGen after its tetrahedralize(). **tetgenio_to_tetmesh()** function will then return a vector of tetrahedrons(current practice) + a vector of this structure, such that say, let s be such a vector then s[i] points to the structure containing attribute information for ith(indexed over the order in the returned vector of tetrahedrons) tetrahedron?

Similarly, tetmesh_to_tetgenio() function will also pass an additional vector of structure containing hole and region information.

**Comment by alecjacobson** [comment]
@pranavkantgaur That sounds like a nice feature. This has a better chance of getting merged in if your code embraces the "struct of arrays" rather than "array of structs" paradigm.

So I would try to achieve this by passing in (multiple) arrays that contain various bits of information rather than one array of structs with all sorts of members.

**Comment by pranavkantgaur** [comment]
@alecjacobson I have opened a pull request for the same.
