### ISSUE TITLE
try to test 102_DrawMesh, failed

### ISSUE THREAD

**Issue by mxgbs** [libigl/libigl#355]
OS:Win10
Compiler: VisualStudio 2012
have added the glfw3.2.1win32 and glew-2.0.0.-win32 to the include path. However, I failed to build the project.  Do you have any idea how to solve the following error. I also tried other test case and some other error occurred. 

Following errors occur:

1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewer.cpp(314): error C2065: 'R' : undeclared identifier
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewer.cpp(314): error C2143: syntax error : missing ')' before 'string'
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewer.cpp(323): error C2059: syntax error : ')'
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewer.cpp(323): error C2001: newline in constant
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewer.cpp(329): error C2059: syntax error : ')'

Besides, lots of warnings:

c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\material_colors.h(16): warning C4305: 'initializing' : truncation from 'double' to 'const float'
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\material_colors.h(17): warning C4305: 'initializing' : truncation from 'double' to 'const float'
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\material_colors.h(18): warning C4305: 'initializing' : truncation from 'double' to 'const float'
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\material_colors.h(23): warning C4305: 'initializing' : truncation from 'double' to 'const float'
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\material_colors.h(24): warning C4305: 'initializing' : truncation from 'double' to 'const float'
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\material_colors.h(25): warning C4305: 'initializing' : truncation from 'double' to 'const float'
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\material_colors.h(26): warning C4305: 'initializing' : truncation from 'double' to 'const float'
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\material_colors.h(39): warning C4305: 'initializing' : truncation from 'double' to 'const float'
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\material_colors.h(40): warning C4305: 'initializing' : truncation from 'double' to 'const float'
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\material_colors.h(43): warning C4305: 'initializing' : truncation from 'double' to 'const float'
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\material_colors.h(44): warning C4305: 'initializing' : truncation from 'double' to 'const float'
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\material_colors.h(45): warning C4305: 'initializing' : truncation from 'double' to 'const float'
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\material_colors.h(47): warning C4305: 'argument' : truncation from 'double' to 'const float'
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\material_colors.h(48): warning C4305: 'argument' : truncation from 'double' to 'const float'
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\material_colors.h(49): warning C4305: 'argument' : truncation from 'double' to 'const float'
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\material_colors.h(50): warning C4305: 'argument' : truncation from 'double' to 'const float'
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\material_colors.h(51): warning C4305: 'argument' : truncation from 'double' to 'const float'
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\material_colors.h(52): warning C4305: 'argument' : truncation from 'double' to 'const float'
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\material_colors.h(54): warning C4305: 'argument' : truncation from 'double' to 'const float'
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\material_colors.h(55): warning C4305: 'argument' : truncation from 'double' to 'const float'
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\parula.h(57): warning C4305: 'argument' : truncation from 'double' to 'const float'
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewerdata.cpp(178): warning C4018: '<' : signed/unsigned mismatch
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewerdata.cpp(185): warning C4018: '<' : signed/unsigned mismatch
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewerdata.cpp(269): warning C4018: '<' : signed/unsigned mismatch
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewerdata.cpp(270): warning C4018: '<' : signed/unsigned mismatch
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewerdata.cpp(318): warning C4018: '<' : signed/unsigned mismatch
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewerdata.cpp(319): warning C4018: '<' : signed/unsigned mismatch
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewerdata.cpp(383): warning C4018: '<' : signed/unsigned mismatch
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewerdata.cpp(394): warning C4018: '<' : signed/unsigned mismatch
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\opengl_state.cpp(111): warning C4018: '<' : signed/unsigned mismatch
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\opengl_state.cpp(119): warning C4018: '<' : signed/unsigned mismatch
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\opengl_state.cpp(127): warning C4018: '<' : signed/unsigned mismatch
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\opengl_state.cpp(135): warning C4018: '<' : signed/unsigned mismatch
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\opengl_state.cpp(143): warning C4018: '<' : signed/unsigned mismatch
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\opengl_state.cpp(154): warning C4018: '<' : signed/unsigned mismatch
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\opengl_state.cpp(161): warning C4018: '<' : signed/unsigned mismatch
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\opengl_state.cpp(172): warning C4018: '<' : signed/unsigned mismatch
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\opengl_state.cpp(180): warning C4018: '<' : signed/unsigned mismatch
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\opengl_state.cpp(188): warning C4018: '<' : signed/unsigned mismatch
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\opengl_state.cpp(196): warning C4018: '<' : signed/unsigned mismatch
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\opengl_state.cpp(204): warning C4018: '<' : signed/unsigned mismatch
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\opengl_state.cpp(218): warning C4018: '<' : signed/unsigned mismatch
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\opengl_state.cpp(225): warning C4018: '<' : signed/unsigned mismatch
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\opengl_state.cpp(236): warning C4018: '<' : signed/unsigned mismatch
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\opengl_state.cpp(249): warning C4018: '<' : signed/unsigned mismatch
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\opengl_state.cpp(265): warning C4018: '<' : signed/unsigned mismatch
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\opengl_state.cpp(279): warning C4800: 'uint32_t' : forcing value to bool 'true' or 'false' (performance warning)
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\opengl_state.cpp(280): warning C4800: 'uint32_t' : forcing value to bool 'true' or 'false' (performance warning)
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\opengl_state.cpp(281): warning C4800: 'uint32_t' : forcing value to bool 'true' or 'false' (performance warning)
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\opengl_state.cpp(282): warning C4800: 'uint32_t' : forcing value to bool 'true' or 'false' (performance warning)
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\opengl_state.cpp(283): warning C4800: 'uint32_t' : forcing value to bool 'true' or 'false' (performance warning)
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\opengl_state.cpp(306): warning C4800: 'uint32_t' : forcing value to bool 'true' or 'false' (performance warning)
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\opengl_state.cpp(322): warning C4800: 'uint32_t' : forcing value to bool 'true' or 'false' (performance warning)
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewercore.cpp(102): warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewercore.cpp(129): warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewercore.cpp(142): warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewercore.cpp(176): warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewercore.cpp(208): warning C4244: 'argument' : conversion from 'float' to 'GLsizei', possible loss of data
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewercore.cpp(208): warning C4244: 'argument' : conversion from 'float' to 'GLint', possible loss of data
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewercore.cpp(226): warning C4244: 'initializing' : conversion from 'double' to 'float', possible loss of data
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewercore.cpp(231): warning C4244: 'initializing' : conversion from 'double' to 'float', possible loss of data
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewercore.cpp(232): warning C4244: 'initializing' : conversion from 'double' to 'float', possible loss of data
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewercore.cpp(423): warning C4244: 'argument' : conversion from 'int' to 'const float', possible loss of data
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewercore.cpp(441): warning C4018: '<' : signed/unsigned mismatch
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewercore.cpp(443): warning C4018: '<' : signed/unsigned mismatch
1>c:\users\dengya\documents\tools\glfw-3.2.1.bin.win32\glfw-3.2.1.bin.win32\include\glfw\glfw3.h(789): warning C4099: 'GLFWwindow' : type name first seen using 'class' now seen using 'struct'
1>          c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewer.h(39) : see declaration of 'GLFWwindow'
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\file_dialog_open.cpp(44): warning C4101: 'szFile' : unreferenced local variable
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\file_dialog_save.cpp(43): warning C4101: 'szFile' : unreferenced local variable
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\eps.h(16): warning C4305: 'initializing' : truncation from 'double' to 'const float'
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\eps.h(17): warning C4305: 'initializing' : truncation from 'double' to 'const float'
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewer.cpp(152): warning C4244: 'initializing' : conversion from 'double' to 'int', possible loss of data
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewer.cpp(153): warning C4244: 'initializing' : conversion from 'double' to 'int', possible loss of data
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewer.cpp(169): warning C4244: 'argument' : conversion from 'double' to 'int', possible loss of data
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewer.cpp(183): warning C4244: 'argument' : conversion from 'double' to 'float', possible loss of data
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewer.cpp(314): error C2001: newline in constant
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewer.cpp(314): error C2065: 'R' : undeclared identifier
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewer.cpp(314): error C2143: syntax error : missing ')' before 'string'
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewer.cpp(323): error C2059: syntax error : ')'
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewer.cpp(323): error C2001: newline in constant
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewer.cpp(329): error C2059: syntax error : ')'
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewer.cpp(608): warning C4244: 'argument' : conversion from 'double' to 'const float', possible loss of data
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewer.cpp(699): warning C4244: 'argument' : conversion from 'float' to 'const int', possible loss of data
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewer.cpp(710): warning C4244: 'argument' : conversion from 'int' to 'const float', possible loss of data
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewer.cpp(711): warning C4244: 'argument' : conversion from 'int' to 'const float', possible loss of data
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewer.cpp(749): warning C4244: 'initializing' : conversion from 'double' to 'float', possible loss of data
1>c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\viewer\viewer.cpp(836): warning C4244: 'argument' : conversion from 'int' to 'const float', possible loss of data

**Comment by danielepanozzo** [comment]
We only support VS 2015 in 64 bit mode. Could you try to see if you get the same errors with VS 2015? Are you using CMAKE to create the project?

**Comment by mxgbs** [comment]
I tried cmake, but it doesn't work. I don't have access to VS 2015. Is
there any specific library you built via VS2015?

Sincerely,

Yan

**Comment by danielepanozzo** [comment]
It must be a problem on your side. libigl builds on VS2015, using a project generated with cmake. You can find the build log here and try to see what are the differences with your setup:
https://ci.appveyor.com/project/danielepanozzo/libigl-6hjk1
