### ISSUE TITLE
201_Normals, build successfully, however, running error

### ISSUE THREAD

**Issue by mxgbs** [libigl/libigl#356]
I used cmake to build the .sln and use the VS2015 to debug.
I included the glew32s.h, glfw3.h, GL/glut.h, and GL/freeglut.h in the main.cpp. The project successfully built, however, when running, following error occurs. Actually, I tried other examples in the tutorials, same error comes. Could you please help me with this? Thanks

Error Message:
IOError: C:/Users/dengya/Documents/tools/libigl-master/libigl-master/shared/fandisk.off could not be opened...
Assertion failed: F.cols() == 3, file c:\users\dengya\documents\tools\libigl-master\libigl-master\include\igl\doublearea.cpp, line 26

**Comment by alecjacobson** [comment]
I would guess that it's not finding the mesh files on your machine
correctly. Could you check that the paths are correct?

**Comment by mxgbs** [comment]
Thanks. How stupid I am. I forgot the /tutorial in the path. Thanks very
much!

Sincerely,

Yan
