### ISSUE TITLE
running tutorial 406, abort caused by assert

### ISSUE THREAD

**Issue by mxgbs** [libigl/libigl#357]
Hi,

I tried to test tutorial 406. However, abort occurred
main.cpp, line 189   igl::arap_dof_recomputation(VectorXi(),Aeq,arap_dof_data); 

inside arap_dof_recomputation, abort() happened at  line 588:
 verbose("condense_CSM maxErr = %.15f (this should be close to zero)\n", maxErr1);
 assert(fabs(maxErr1) < 1e-5);

I used VS2015 64bits(windows 10) to compile. Do you know what caused the aforementioned error? Thanks.

Sinc

**Comment by mxgbs** [comment]
I checked the value of maxErr1, which is inf.

**Comment by alecjacobson** [comment]
Is this (still) happening for the default inputs for 406? Or are you trying to use this on a different mesh?

**Comment by ruoqingsun** [comment]
I think I get the same error.

**Platform**: Windows + Visual Studio 2015
**Error**: Initializing Fast Automatic Skinning Transformations...
Assertion failed: fabs(maxErr1) < 1e-5, file e:\documents\github\libigl\include\igl\arap_dof.cpp, line 588

**Comment by mxgbs** [comment]
The default one.the abort() happened at 588 row in the file arap_dof.cpp.

Sincerely,

Yan

**Comment by jbs0645** [comment]
I faced the same error  when running  the **406_FastAutomaticSkinningTransformations_bin.exe**
**Platform**: Windows + Visual Studio 2017

**Comment by jdumas** [comment]
Have you tried this on the `dev` branch of libigl?

**Comment by jbs0645** [comment]
I can not understand  **_the dev branch of libigl_** mean?

**Comment by jdumas** [comment]
https://github.com/libigl/libigl/tree/dev

**Comment by jbs0645** [comment]
Thank you for the immediate and patience response, but I still meet the similar error : 
_`Assertion failed: fabs(maxErr1) < 1e-5, file D:\0wf\libigl-dev\libigl\include\igl\arap_dof.cpp, line 588`_
I think there is something wrong with the **armadillo.obj** or the **arap_dof.cpp**

**Comment by alecjacobson** [comment]
I can't reproduce this.
