### ISSUE TITLE
question about 404_dualskinning

### ISSUE THREAD

**Issue by mxgbs** [libigl/libigl#360]
Hi,

I tested the 404 and it worked great. I'm wondering how u generate the weights(arm-weights.dmat) regarding to the 4 joints? Can you give me some hint? Thanks.

Sincerely,

Yan

**Comment by alecjacobson** [comment]
They are computed using bounded biharmonic weights.

**Comment by mxgbs** [comment]
Thanks.

Sincerely,

Yan
