### ISSUE TITLE
issue regarding to compute weights of 404 via 403

### ISSUE THREAD

**Issue by mxgbs** [libigl/libigl#361]
Hi,

I'm trying to calculate the weights via bounded biharmonic weights. In the skinning example 404, we have the arm's triangulation data (V,F). In order to use biharmonic, we need to calculate the Tetrahedra. However, if the I used the function igl::tetrahedralize(V,F,"pq1.414", TV,TT,TF), the resulting TV, TF should be different with input (V,F). Am I right? How can I calculate the T without changing V, F? Do you have any idea?

**Comment by alecjacobson** [comment]
tetrahedralize will make sure that the vertices in V are the first vertices
of TV that way any computation you do for TV can be truncated and used for V

**Comment by mxgbs** [comment]
Thanks very much! That really helps.

Sincerely,

Yan

**Comment by KasiaSprawka** [comment]
Did you manage to use bbw in 404? Could you share the code? I have some issue giving me all weights equal to 0...
