### ISSUE TITLE
709_VectorFieldVisualizer Link error

### ISSUE THREAD

**Issue by VVingerfly** [libigl/libigl#362]
Hi, Recently, I try to build  Example 709_VectorFieldVisualizer, but there are link errors with CoMISo. I serached on the Internet and found that templated C++ classes can not be splitted  into .hpp/.cpp files. So I moved the implementation of CoMISo in .cc files  into .hh files. And the link errors about CoMISo disappeared. But new link errors seem related with gmm came out.  I searched on the Internet, but found nothing useful.
The error is

![20161015165003](https://cloud.githubusercontent.com/assets/16233971/19408760/77be8766-92f7-11e6-8382-1ccbeabbec5d.png)

It says Unresolved external symbol _daxpy, referenced in function  void _cdecl gmm::add(......)

How can I solve this problem???

Looking forwarding to your reply. Thanks a lot.

Wei

**Comment by danielepanozzo** [comment]
This is very strange, here is the build log for linux/mac:
https://travis-ci.org/libigl/libigl

And here is the one for windows:
https://ci.appveyor.com/project/danielepanozzo/libigl-6hjk1

Could you check what the differences are? It should work out of the box. If you are building on windows note that only VS2015 and a 64bit build will work.

**Comment by VVingerfly** [comment]
Thanks for your reply.
I don't mean building libigl. I just want to compile and run this example on VS2015 32bit. But the above errors occur. I have included ligigl, CoMISo, gmm. Should I compile CoMISo or gmm first? Or how can I solve this problem?

kind regard,
Wei

**Comment by danielepanozzo** [comment]
VS2015 in 32 bit mode is problematic for many parts of libigl, I think it is related to Eigen but I am not sure. I suggest to try to build the entire libigl with VS2015 64 bit. If it works, you can then use make VERBOSE=1 to see what are the flags that you are missing in your build. As you can see here:
https://ci.appveyor.com/project/danielepanozzo/libigl-6hjk1
our build system successfully builds and link Comiso, gmm and everything else that is needed for tutorial 709.

**Comment by VVingerfly** [comment]
Thanks, I will try and check where the problem is.

kind regard,
Wei

**Comment by r03ert0** [comment]
Hello!
The 709_VectorFieldVisualizer example in the tutorial is no more present...

**Comment by danielepanozzo** [comment]
Hi, 
yes we moved most of the vector field code in libigl to libdirectional, you can find the old tutorials (and a lot more) here: https://avaxman.github.io/libdirectional/tutorial/tutorial.html
