### ISSUE TITLE
Add Alec's example project to the top of the libigl tutorial page

### ISSUE THREAD

**Issue by evouga** [libigl/libigl#366]
Alec's example empty project is extremely useful for students starting out with libigl (otherwise if they try to create a new program by modifying the tutorial examples on their own, there is a 100% chance they get the library paths, or some other CMake detail, incorrect). It would be nice to advertise it prominently in the tutorial.

**Comment by danielepanozzo** [comment]
Thank you for the great suggestion, I added it to the readme and to the tutorial. I did not realize that it was not even mentioned in the tutorial!
