### ISSUE TITLE
function for removing duplicate faces 

### ISSUE THREAD

**Issue by pranavkantgaur** [libigl/libigl#367]
Hi,

Tetgen terminates with an error for the cases when there are duplicate faces in the input polygon meshes. Is there a function for removing duplicate faces like we have a function for removing self-intersections? I have also manually checked the input and there are no such duplicate faces as reported by TetGen. It seems that it internally creates these sub-faces. I have also contacted TetGen author but did not get any response.

Following are simple code(adapted from libigl tutorials) and dataset which reproduce this issue:
[code](https://gist.github.com/pranavkantgaur/bbece4e79f90ed5d370adc9ae3716da7#file-selfintersectfixbeforetetgen-cpp)
[data](https://github.com/libigl/libigl/files/535803/duplicateFaceTest.ply.zip)

**Comment by alecjacobson** [comment]
You could use `igl::unique_simplices`
