### ISSUE TITLE
Support to read/write OFF files with color per vertex

### ISSUE THREAD

**Issue by jmespadero** [libigl/libigl#369]
I have seen that libIGL does not support read/writing .off files with color per vertex. 

The COFF (color-per-vertex OFF) is not very used today, but it is in the ["official" OFF file format ](http://www.geomview.org/docs/html/OFF.html), and is supported by some programs as meshlab. You can see an example file [here](http://www.geomview.org/docs/obj/vertcube.off). Typical usage of this format is to store a mesh colorized by curvature or any other quality measure.

I can add support to read/write .off files with colors (in a similar way as current API for .obj file format) , but not sure if there is enough interest for it. Do you think it will be useful? Which file format would you use to save the output of examples [104](https://libigl.github.io/libigl/tutorial/tutorial.html#scalarfieldvisualization) or [202](https://libigl.github.io/libigl/tutorial/images/bumpy-gaussian-curvature.jpg)? Maybe .ply?

**Comment by jmespadero** [comment]
Ooops, I have seen that libIGL does not support .ply with color per vertex.

**Comment by alecjacobson** [comment]
Supporting COFF is fine so long as the behavior for plain ASCII OFF files
stays the same.
Personally I write extra data into .dmat files because I found that COFF is
less supported by other programs.
