### ISSUE TITLE
question about skinning blending (404 example)

### ISSUE THREAD

**Issue by mxgbs** [libigl/libigl#370]
Hi,

I'm new to the animation manipulation thing. My understanding of skinning is to blend the connecting vertices' associated rigid matrix. (since the warping vertex is close to the nearest vertices, so we approximate the rotation origin is the warping vertex itself. ) 

after setting up bend matrix,
  const Quaterniond bend(AngleAxisd(-igl::PI_0.5, Vector3d(0, 0, 1)));
u apply a rest pose matrix. 
 poses[1][2] = rest_pose[2]_bend*rest_pose[2].conjugate();

My understanding of the rest pose matrix (based on the code) is to calculate the rotation between each bone and the vector [1,0,0].  Why should we do this instead of just using poses[1][2]=bend,

Could you please help me with this? Thanks.

Sincerely,

Yan

**Comment by alecjacobson** [comment]
I don't quite understand the question. You might start by brushing up on the technical details of linear blend skinning and dual quaternion skinning. For example, take a look at the "Direct Methods" section of the SIGGRAPH course notes: http://skinning.org
