### ISSUE TITLE
error when running example 604 triangle in MSVC 2013

### ISSUE THREAD

**Issue by saedrna** [libigl/libigl#372]
Hi,

It seems that the vertexloop is not alloc as the following, in triangle.c of `transfernodes`

```
 initializevertexpool(m, b);

  /* Read the vertices. */
  coordindex = 0;
  attribindex = 0;
  for (i = 0; i < m->invertices; i++) {
    vertexloop = (vertex) poolalloc(&m->vertices);
    /* Read the vertex coordinates. */
    x = vertexloop[0] = pointlist[coordindex++];
    y = vertexloop[1] = pointlist[coordindex++];
...
```

Any thoughts on how to use the `triangulate` function? 

PS: I have tried msvc 12.0 x86 and it's OK. But msvc x64 will have this alloc problem. Also it works on linux (mint x64) with gcc and clang,

Thanks,

Han

**Comment by alecjacobson** [comment]
I don't quite understand the problem. Is `triangulate` crashing? For which
input?

**Comment by saedrna** [comment]
The problem lies in the c library of triangle.c. 

I also don't know how this is happening, because use the same compile processor definition msvc 32 bit will work well and linux gcc will also work well.

On the other hand, it also seems to be not the probelm of msvc x64, because I have solved the problem by using the wrapper provided by [https://github.com/wo80/Triangle](https://github.com/wo80/Triangle).

**Comment by alecjacobson** [comment]
VS 2013 is not supported. (reopen if this also happens for modern VS)
