### ISSUE TITLE
703_Decimation runs out of memory

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#377]
From personal email

> While decimating a test .obj such as Crytek Sponza, libigl runs out of memory (@ ~30 gb) 
> 
> Any plans to optimize the memory usage?

**Comment by alecjacobson** [comment]
In order to debug this, could you share your problematic .obj file?

igl::decimate will not work correctly if the input mesh is not edge-manifold (check with `igl::is_edge_manifold`). It _should_ now be working for meshes with boundary.

**Comment by FredrickV** [comment]
is_edge_manifold() returns true

Mesh source "Crytek Sponza" can be downloaded here : http://graphics.cs.williams.edu/data/meshes.xml

Modified from tutorial (I LOD via key)
```
void LODMore(igl::viewer::Viewer &viewer)
{
   // Assume this is the way you check this
	if (is_edge_manifold(V)) 
		printf("is_edge_manifold() == true\n");
	else 
		printf("is_edge_manifold() == true\n");
	

	bool something_collapsed = false;
	// collapse edge
	const int max_iter = std::ceil(0.01*Q.size());
	for (int j = 0; j < max_iter; j++)
	{
		if (!collapse_edge(shortest_edge_and_midpoint, V, F, E, EMAP, EF, EI, Q, Qit, C))
		{
			break;
		}
		something_collapsed = true;
	}

	if (something_collapsed)
	{
		viewer.data.clear();
		viewer.data.set_mesh(V, F);
		viewer.data.set_face_based(true);
	}
}

```

**Comment by alecjacobson** [comment]
hmmm. When I check `igl::is_edge_manifold` on the `sponza.obj` mesh I get false. Also my matlab check claims there are 62 non-manifold edges. So I'm rather convinced that this mesh is not edge-manifold.

refactoring `igl::decimate` to work on non-manifold meshes is theoretically not a problem, but practically speaking would be a lot of small changes (i.e., not going to happen soon).

In the meantime, it might be simpler to cut the mesh along non-manifold edges. And then simplify as if all of the non-manifold edges were boundaries. The downside is that this might result in gaps/cracks appearing.

**Comment by FredrickV** [comment]
Just to confirm, I got the same results as you did. (I edited my post a few times)

In the short term i will use this "is_edge_manifold" function to pre-validate the mesh before processing. Use manual tools such as Blender where needed for decimation. I think libigl covers more than 50% of the meshes i need to eventually process so i am committed to do the post-process as mentioned in #378
