### ISSUE TITLE
What is `bc` in the `bbw` function?

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#38]
Alec: migrated from personal email.

> > > ...
> > > Anyway, I'm working on a project that requires some 3D shape deformation and so naturally I came across your BBW code as part of libigl (awesome thing, by the way). I am now integrating it into my own code, but I am not sure about the input parameter 'bc', or rather, what it should contain. At first I thought it should contain, at each row, the translation of the handle point specified in 'b' at that same row. But upon closer examination of the paper and the code I am now doubting this assumption, so I thought I would consult you.

> > BBW works by first computing weights `W` in our code. There’s scalar weight function for each “handle” so `W` is #V by #handles. Then your deformation is computed via “linear blend skinning” (in my demos this is simply a matrix multiplication `U = M * T` where `M` is the “lbs matrix” constructed from `W` (weights) and `V` (vertices) and `T` is a stack of the affine transformations at each handle.
> > 
> > But the usual thing is to compute the deformation of each vertex in the vertex shader: u_j = ∑ w_ij T_i * v_j, where u_j is the deformed position of the jth vertex, w_ij is the weight of handle i at vertex j, T_i is the affine transformation applied to handle i and v_j is the rest (original) position of the jth vertex.
> >
> > OK, now, what are `b` and `bc` in the input to my `bbw` function? Well, b contains a list of indices to all vertices that lie in or on a handle. If your handles are just selected vertices of the mesh then `b` will just be those vertices, if your handles are selected regions or bones (line segments) then `b` should contain a list of indices of vertices sampling those regions/bones (the `bbw` function expects that your mesh already contains vertices at/on your handles and that you have identified them via b and bc: i.e. `bbw` does not remesh). So b identifies vertices which will receive fixed values, either 1 or 0 depending on which weight function, which column of `W`. Then bc determines to which handle each entry in b _belongs, to which handle each belongs. That means bc is a #b by #handles matrix, typically bc(i,j) == 1 if b(i) lies in/or handle j and bc(i,j) == 0 otherwise.
> > 
> > You can use my `boundary_conditions` function to determine `b` and `bc` from common handle types.
> >
> > Eventually, I plan to overload `bbw` to merge its inputs with `boundary_conditions` to skip this step. But for now, the typical routine is:
> > 
> > `boundary_conditions(V,Ele,C,P,BE,CE,b,bc);`
> > `bbw(V,Ele,b,bc,data,W);`

> Ahh now I understand! I really did confuse the weight computation with the subsequent deformation. So from what you say I also understand that if my handles are just selected vertices, then 'bc' will be a diagonal matrix of size #b x #b (with 1's on the diagonal), is that correct?
> In my setting I only have cages (that may be partial) as handles. I plan on computing the convex hull of the cage + underlying mesh and have that be the input to Tetgen, along with the additional requirement to include the rest of the vertices (which have not been fortunate enough to be a part of the convex hull) in the tetrahedralization. Does that make sense as the input to BBW?
> 
> Thanks for the super speedy response! :)

**Comment by alecjacobson** [comment]
Yes, if you just have #b point handles then `b` should be the indices of those point handles into `V` and `bc` should be a #b by #b Identity matrix.

Now, if your points are really vertices of a cage (not just floating, isolated control points), then you really ought to use `boundary_conditions` to compute `b` and `bc` for you, since cage vertices should also interpolate linear functions on the cage faces. That is, `b` will now contain not just the indices of the vertices directly under the cage vertices, but also any vertices lying on the faces and edges of the cage. And correspondingly `bc` will contain values for each of those vertices so that only the weights for cage vertices incident on those cage faces and edges have non-zero values.

You might consider taking the _union_ of your partial cage and the input mesh, instead of just the convex hull. This will lead to better (i.e. more "shape-aware") weights if your shape is far from convex. Luckily we have mesh-mesh boolean operations (see `include/igl/boolean/mesh_boolean.h`). Admittedly, this starts to put a lot of faith in Tetgen succeeding. I'll be curious to here of your success or any further issues.

**Comment by noadag** [comment]
I am now facing two issues:

1) When attempting to run on a mesh with ~6000 vertices and ~22000 tetrahedra, and a discretized cylinder with a 100 vertices as the cage, I am getting a numerical issue error in min_quad_with_fixed.cpp (I am not using Mosek for now).
2) Having faced the issue above, I tried simplifying by using just the discretized cylinder as my mesh. Tetgen outputs ~400 vertices and ~1200 tetrahedra for that. The input to BBW is that, along with the original cylinder vertices and edges as the cage. In the output weights matrix I am getting the identity matrix as the submatrix detailing the weights for the original cylinder vertices, which is expected. However, the rest of the matrix is filled with NaN and zero values.

Note that I am using boundary_conditions to compute 'b' and 'bc', and that I am calling Tetgen and BBW from within Matlab.

Any idea what I'm missing?

Thanks!

**Comment by alecjacobson** [comment]
If you're using matlab, you might consider using my [gptoolbox](https://github.com/alecjacobson/gptoolbox) directly. It has much of the same functionality as libigl but is majority pure matlab.

1) What errors exactly are you getting from min_quad_with_fixed? Is it printing errors or is the result garbage?

2) I have the feeling that the cage setup you're using is not quite what's expected. If you have a cage + input mesh, then the tet mesh you pass to `boundary_conditions` should be a _conforming_ mesh inside the union of the cage and the shape. That means there should be tet-mesh vertices exactly at cage vertices and there should be tet-mesh faces (triangles) lying exactly along cage faces. And finally tet-mesh edges lying along cage edges.

Can you share your input?

**Comment by noadag** [comment]
1) After the execution of: ```data.llt.compute(Auu)``` , I am getting that: ```data.llt.info() = Eigen::NumericalIssue```

2) That is what I think I have, at least in the simpler example of the cylinder. I start with the cylinder vertices and I specify a full triangle mesh with those vertices. I then call Tetgen on that mesh. Since my cage is made up of the original cylinder vertices, then the tetrahedralization contains the vertices of the cage, and I think that the tet-mesh faces and edges should also be valid.
As for the more complicated example that I described, I think it is probably not valid, since I had to go with the convex hull method that I mentioned before (due to lack of CGAL - working on it though). Because the cage in this example is not an encompassing cage, but rather is partially enclosed within the mesh, then the convex hull that joins the mesh and the cage together necessarily leaves out parts of the cage. I specifically ask Tetgen to include the missing vertices in the tetrahedralization, but from what you just said it seems like that is not enough, since even if the vertices appear in the tet-mesh, the faces and edges of the cage do not necessarily appear. In short, from all of that I understand that I have no choice but to compute the union of the mesh and cage. One question about that though - is the output of the union a Tetgen-friendly output, in that it contains no face intersections?

I am more than happy to share my input, here is the simple cylinder example:
https://www.dropbox.com/sh/ig2gtnqssctpdz9/AADDrxE_LM84vZu6gjdz_pSZa?dl=0
The folder contains the mesh in the ```.off``` file, and in the ```.mat``` file you can find the struct containing the mesh (it also has an edges field, which I pass as input to ```boundary_conditions```). There are also the Tetgen output files in ```barout.*```
I think that should cover it, but let me know if I forgot anything.

Thanks! :)

**Comment by alecjacobson** [comment]
Ah, I think I see the issue. The output we need from TetGen is the
_tetrahedral_ mesh. TetGen will also output the edges and faces of the tet
mesh but we need the tet indices. We're usually storing this in a #tets by
4 matrix T of indices. Then boundary_conditions and bbw should be called
with this tet mesh rather than the surface facets. That is, something like:

    boundary_condtitions(V,T,C,P,BE,CE,b,bc)
    bbw(V,T,b,bc,...)

rather than passing F (the list of facets).


Regarding the union, yes, if computed correctly this will be _valid_ input
to TetGen: there should be no self-intersections after union, assuming your
inputs to the union are self-intersection free. _However_, TetGen might
still choke on small triangles and close features and these are likely to
arise during boolean operations. We can discuss getting around this
limitation of TetGen further if you run into it.

**Comment by noadag** [comment]
The tet mesh (which is what appears in the file ```barout.ele```) is indeed what I'm passing to ```boundary_conditions``` and ```bbw```...
I will try using the matlab version and report back.

**Comment by alecjacobson** [comment]
If that's the case, can you send your #T by 4 tet indices matrix so I can
try to debug? Ideally, send exactly your inputs to boundary_conditions and
bbw. In the previous .mat I only saw a #F by 3 facets matrix.

**Comment by noadag** [comment]
Sure thing, I added to the dropbox folder a file called ```cyl_data.mat```, containing the input.
I call my mex file ```deform_bbw.cpp``` (also in the folder if needed) from matlab with:
```w = deform_bbw(tverts, ttets, pmesh.vertices, 1:size(pmesh.vertices,1), pmesh.edges);```
Where, if we look at the notation inside ```boundary_conditions.h```, then:
```V -> tverts```
```Ele -> ttets```
```C -> pmesh.vertices```
```P -> 1:size(pmesh.vertices,1)```
```BE -> empty (since I don't have bones)```
```CE -> pmesh.edges```

```deform_bbw.cpp``` calls ```boundary_conditions``` and then ```bbw```.

**Comment by alecjacobson** [comment]
Indeed there was a bug in `igl::boundary_conditions` for cage edges. I've
pushed in a fix (Version 1.1.3). Also, a base-case bug  in
`igl::min_quad_with_fixed`---I'm not sure you were running into---has been
fixed

Only cage _edges_ are implemented. In 3D, ideally you'd also constrain the
value at any vertices lying on cage _faces_. You mesh seems to be coarse
enough that this won't make a difference. And in any case it won't prohibit
computing weights, just the weights won't be linear inside the cage
triangles. This is simply a matter of finding tet mesh vertices lying on
cage faces and constraining the weights of cage vertices there to the
vertices' barycentric coordinates. This is a long-standing TODO for me. Not
sure when I'll get to it.

**Comment by noadag** [comment]
Yay! My weights matrix looks good now, thanks! :)

Ok, I'll take that into account. I think my setting is simple enough (deformation-wise) so as not to be influenced too much by the lack of these constraints .
