### ISSUE TITLE
Nanogui exception running example 106

### ISSUE THREAD

**Issue by faniry6** [libigl/libigl#381]
Hi all,

I built recently the current version of libigl on Win 8/VSC 2015. Everything build fine but when I run example 102, I got some access violation as described in the screenshot. I suspect that it is  a nangui/vg problem but when I build the nanogui separatly, all  examples run nicely. Any help will be welcome.

![libigl_issue](https://cloud.githubusercontent.com/assets/13021697/19761681/3e824c14-9c37-11e6-9e01-4eabb09a6c81.jpg)

Thanks in advance

**Comment by xiuluo211314** [comment]
I hava the same error ! Is there some method to deal with it ?  please ,i need help!

**Comment by alecjacobson** [comment]
This appears to be an issue with nanogui. I would recommend reposting this issue on nanogui's github page.
