### ISSUE TITLE
cotmatrix_entries return half of expected values

### ISSUE THREAD

**Issue by jmespadero** [libigl/libigl#382]
Hi,

I have observed that `igl::cotmatrix_entries()` does not return the value of the cotangent if the angles, but the "half of the cotangent".
As a result, the Laplacian computed with `igl::cotmatrix_entries()` contains values that are "half of the sum of cotangents". This matrix usually works in the same way that "sum of cotangents", but its values does not match the expected in the literature (Botch et al, "Polygon Mesh Processing") nor even your own formulas and pseudocode in [http://libigl.github.io/libigl/tutorial/tutorial.html#laplacian](http://libigl.github.io/libigl/tutorial/tutorial.html#laplacian). 

As a simple example, the `tutorial/shared/2Triangles.off` file contains two triangles (right  and equilateral), whose angles can be seen in this figure:
![2triangles info](https://cloud.githubusercontent.com/assets/6451497/19765495/fbced56a-9c48-11e6-9bfb-c56c1ef71c0c.png)

The output of ``igl::cotmatrix()` is:

```
-0.707107  0.707107         0         0
 0.707107  -1.63801  0.642229  0.288675
        0  0.642229 -0.930904  0.288675
        0  0.288675  0.288675  -0.57735
```

If a student try to understand or reimplement the "laplacian as the sum of cotangents" formula, will expect to find values of "cot(60)+cot(54.7)"  (which is 1.2844)  somewhere in the matrix. Also, in the position (0,1) of the matrix he would expect "cot(35.264)" (which is 1.414) instead 0.7071

As said, your Laplacian usually works fine, due it is a perfect scale of "sum of cotangents", but it is no good that IGL code does not match the formulas in the IGL tutorial or the literature. Is there a reason to use "sum of half of cotangents"?

Also, do you plan to deal with obtuse angles (which will throw negative values of cotangent)?

**Comment by alecjacobson** [comment]
Yes. This is known (should be better documented). It's one of the reasons
why this function isn't called igl::cotagent.
As for obtuse angles, "handling" them is perhaps subjective. Throwing out
negative off diagonals will produce incorrect results for some applications
and Dorsnt have a good mathematical footing

**Comment by jmespadero** [comment]
Ok. 
For the obtuse angles I mean to use a Laplacian not based in cotangents. As, for example, the based in values tan(alpha / 2) / edgeLen.

I have implemented it with IGL as exercise. Not sure if you are interested in.

For example, this is the result for tutorial 501_HarmonicParam:
![0 cot_a](https://cloud.githubusercontent.com/assets/6451497/19774685/42172b42-9c6e-11e6-865c-fbeae2daeef5.png)
![0 cot_b](https://cloud.githubusercontent.com/assets/6451497/19774698/445a175c-9c6e-11e6-85cb-24ff581c807c.png)


And this is the result for Laplacian based on tan(alpha / 2) / edgeLen:
![1 tan_div_edge_a](https://cloud.githubusercontent.com/assets/6451497/19774776/826795c4-9c6e-11e6-86c5-24cf07202710.png)
![1 tan_div_edge_b](https://cloud.githubusercontent.com/assets/6451497/19774777/8287da8c-9c6e-11e6-8d01-7ffb71d7e6b6.png)

For quasi-regular meshes, the cotangent gives a better result. But sometimes we have to deal with irregular meshes. The main idea to transmit to students is that Laplacian based in cotangent is not the unique solution to discrete laplacian (but usually is the best).

**Comment by alecjacobson** [comment]
Agreed.

We currently don't have a  "mean value" coordinates discrete Laplacian.
Though I have one in gptoolbox:
https://github.com/alecjacobson/gptoolbox/blob/master/mesh/mean_value_laplacian.m

**Comment by jmespadero** [comment]
Man, I will borrow that genial piece of ascii-art to coment my code :-). 

If you are interested in the "mean value laplacian", just post a name for the method. The interface for calling is the same that for 'cotmatrix(V, F, L)'

**Comment by avaxman** [comment]
I just ran into this question bc I was wondering myself: the tutorial states full cots but half-cots are the correct thing to give back as the weak part of the Laplacian (so that the mass matrix is Voronoi areas rather than double areas, and also compatible to conventional 1-form Hodge stars). So I guess half-cots are the ones returns by igl::cotmatrix? then the tutorial is wrong.

**Comment by avaxman** [comment]
But... why are you using the negative Laplacian? here:

https://github.com/libigl/libigl/blob/master/tutorial/205_Laplacian/main.cpp

Line 43: 
```
 K = -G.transpose() * T * G;
```
would give a negative-definite Laplacian.

**Comment by avaxman** [comment]
If it is half cots that’s the correct thing to do anyhow. However the negative definite thing puzzles me.

**Comment by avaxman** [comment]
I mean everybody always refer to the Laplacian in the PSD form (altough the continuous one is NSD). That means that the matrix has to be:

$$L = d_0^T * W * d_0$$, 

where W is the positive half-cot weights. Alternatively, $G^TMG$ will give you the same. Fleshing it out you get negative values in the matrix where $i \neq j$ and positive sums on the diagonal. Some papers are inconsistent about it...
