### ISSUE TITLE
question about how to determine the points inside the hole in triangulate

### ISSUE THREAD

**Issue by saedrna** [libigl/libigl#385]
Hi,

I have a 2D polygon with holes, and the polygon is represented by a set of rings: one exterior rings and each other ring represent a hole.

I would like to triangulate the polygon and setting the maximum area of the triangle, like the Tutorial example 604 did, by using the igl/triangle/triangulate method.

However, that function need a point inside each hole as input (argument ```H``` as below), which I find it hard to decide, because the inner rings may be concave.

So my question is, how can I determine a point inside the hole using the ring representation?

Below, is the triangulate function for reference,

```
    // Triangulate the interior of a polygon using the triangle library.
    //
    // Inputs:
    //   V #V by 2 list of 2D vertex positions
    //   E #E by 2 list of vertex ids forming unoriented edges of the boundary of the polygon
    //   H #H by 2 coordinates of points contained inside holes of the polygon
    //   flags  string of options pass to triangle (see triangle documentation)
    // Outputs:
    //   V2  #V2 by 2  coordinates of the vertives of the generated triangulation
    //   F2  #F2 by 3  list of indices forming the faces of the generated triangulation
    //
    // TODO: expose the option to prevent Steiner points on the boundary
    //
    IGL_INLINE void triangulate(
      const Eigen::MatrixXd& V,
      const Eigen::MatrixXi& E,
      const Eigen::MatrixXd& H,
      const std::string flags,
      Eigen::MatrixXd& V2,
      Eigen::MatrixXi& F2);
```

Thanks,

Han

**Comment by alecjacobson** [comment]
You could also just use the winding number to throw away faces after the
fact.

**Comment by saedrna** [comment]
@alecjacobson , after a quick check of what winding number is, is this what you are meant for?

1, triangulate without any holes
2. remove faces, whose vertex has winding number equals to -1, with respect to each inner ring?

**Comment by alecjacobson** [comment]
If you have your rings oriented consistently (alternating CW and CCW), then
you can compute the winding with respect to all of the rings at once and
then remove faces with winding number zero.

**Comment by saedrna** [comment]
I have tried this function and it works, except for that I need to check the points on the rings after triangulate. Because occasionally, these points will also have winding number of zero.

**Comment by alecjacobson** [comment]
I would check the barycenter of each triangle rather than the vertices.

**Comment by saedrna** [comment]
Thanks for the advice!
