### ISSUE TITLE
make failed for cgal

### ISSUE THREAD

**Issue by hurrymomo** [libigl/libigl#386]
I am using MacOS Serria
I just installed cgal(v4.10)
Here is what I did

cd  tutorial/build/
cmake -DCGAL_DIR=~/r/cgal/build/  ..
make

While making, the following error occurs

Scanning dependencies of target 101_FileIO_bin
[ 86%] Building CXX object 101_FileIO/CMakeFiles/101_FileIO_bin.dir/main.cpp.o
[ 86%] Linking CXX executable ../101_FileIO_bin
[ 86%] Built target 101_FileIO_bin
Scanning dependencies of target 102_DrawMesh_bin
[ 86%] Building CXX object 102_DrawMesh/CMakeFiles/102_DrawMesh_bin.dir/main.cpp.o
[ 86%] Linking CXX executable ../102_DrawMesh_bin
Undefined symbols for architecture x86_64:
  "void igl::remove_unreferenced<Eigen::Matrix<CGAL::Lazy_exact_nt<CGAL::Gmpq>, -1, -1, 0, -1, -1>, Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<CGAL::Lazy_exact_nt<CGAL::Gmpq>, -1, -1, 0, -1, -1>, Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<int, -1, 1, 0, -1, 1> >(Eigen::PlainObjectBase<Eigen::Matrix<CGAL::Lazy_exact_nt<CGAL::Gmpq>, -1, -1, 0, -1, -1> > const&, Eigen::PlainObjectBase<Eigen::Matrix<int, -1, -1, 0, -1, -1> > const&, Eigen::PlainObjectBase<Eigen::Matrix<CGAL::Lazy_exact_nt<CGAL::Gmpq>, -1, -1, 0, -1, -1> >&, Eigen::PlainObjectBase<Eigen::Matrix<int, -1, -1, 0, -1, -1> >&, Eigen::PlainObjectBase<Eigen::Matrix<int, -1, 1, 0, -1, 1> >&)", referenced from:
      void igl::copyleft::cgal::outer_hull<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<int, -1, 1, 0, -1, 1>, Eigen::Matrix<int, -1, 1, 0, -1, 1> >(Eigen::PlainObjectBase<Eigen::Matrix<double, -1, -1, 0, -1, -1> > const&, Eigen::PlainObjectBase<Eigen::Matrix<int, -1, -1, 0, -1, -1> > const&, Eigen::PlainObjectBase<Eigen::Matrix<double, -1, -1, 0, -1, -1> >&, Eigen::PlainObjectBase<Eigen::Matrix<int, -1, -1, 0, -1, -1> >&, Eigen::PlainObjectBase<Eigen::Matrix<int, -1, 1, 0, -1, 1> >&, Eigen::PlainObjectBase<Eigen::Matrix<int, -1, 1, 0, -1, 1> >&) in libiglcgal.a(outer_hull.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [102_DrawMesh_bin] Error 1
make[1]: *** [102_DrawMesh/CMakeFiles/102_DrawMesh_bin.dir/all] Error 2
make: *** [all] Error 2

Please help me 
Thanks

**Comment by alecjacobson** [comment]
I would start with LIBIGL_USE_STATIC_LIBRARY=Off  this should have been the
default build option for cmake in the tutorial.

**Comment by hurrymomo** [comment]
I put cgal into libigl/external, and delete everything in the tutorial/build
and recompile everything using

cmake  -DLIBIGL_USE_STATIC_LIBRARY=OFF -DCGAL_DIR=~/r/libigl/external/cgal/  ..
make

then it compiles successfully
