### ISSUE TITLE
glfw weird error

### ISSUE THREAD

**Issue by avaxman** [libigl/libigl#388]
I get this errror when using the viewer (with Nanogui) lately:

"
2016-11-02 14:24:23.030420 example_bin[44061:1017274] [General] ERROR: Setting <GLFWContentView: 0x100b2a240> as the first responder for window <GLFWWindow: 0x1009066d0>, but it is in a different window ((null))! This would eventually crash when the view is freed. The first responder will be set to nil.
(
	0   AppKit                              0x00007fff742dc9a4 -[NSWindow _validateFirstResponder:] + 566
	1   AppKit                              0x00007fff73acd9eb -[NSWindow _setFirstResponder:] + 31
	2   AppKit                              0x00007fff73b7566a -[NSWindow _realMakeFirstResponder:] + 406
	3   AppKit                              0x00007fff73b75480 -[NSWindow makeFirstResponder:] + 123
	4   example_bin                         0x000000010021ac3e createWindow + 1230
	5   example_bin                         0x000000010021a53f _glfwPlatformCreateWindow + 63
	6   example_bin                         0x0000000100212e0a glfwCreateWindow + 874
	7   example_bin                         0x000000010008844f _ZN3igl6viewer6Viewer11launch_initEbb + 271
	8   example_bin                         0x0000000100008d1a _ZN3igl6viewer6Viewer6launchEbb + 58
	9   example_bin                         0x0000000100006d19 main + 521
	10  libdyld.dylib                       0x00007fff8aefe255 start + 1
)
"

**Comment by avaxman** [comment]
I should say that it doesn't seem to affect functionality, but it looks like there is some corruption going on.

**Comment by alecjacobson** [comment]
There's not much happening in the `igl::viewer` before `glfwCreateWindow` is called. I'm guessing this is an issue with glfw or nanogui. I would recommend reposting this issue there.
