### ISSUE TITLE
Remove unnecessary checks for API handles

### ISSUE THREAD

**Issue by elfring** [libigl/libigl#390]
[Extra checks are not needed for zero API handles](https://www.opengl.org/sdk/docs/man/html/glDeleteProgram.xhtml "Description from the OpenGL Reference") in a function like [`igl::viewer::OpenGL_shader::free()`](https://github.com/libigl/libigl/blob/5da97504fbc9c44e1a7396fff0373d16f69fa149/include/igl/viewer/OpenGL_shader.cpp#L119 "Update candidate").

**Comment by danielepanozzo** [comment]
Could you please prepare a PR with the fix? We would be happy to accept it.
