### ISSUE TITLE
Monkey test for compilation/include order

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#391]
Here's a small bash  script that will construct a no-op c++ file that includes **_all_** libigl headers in a random order:

    echo "`ls -1 $LIBIGL/include/igl/*.h | sed -e "s/.*igl\/\(.*\)/#include <igl\/\1>/" | perl -MList::Util=shuffle -wne 'print shuffle <>;'`
    int main(){ }" | clang++ -xc++ - -I$LIBIGL/include -I/usr/local/include/eigen3 -std=c++11

Because of the random order (this is a [monkey test](https://en.wikipedia.org/wiki/Monkey_testing) ), it may take multiple executions to root out missing namespaces/includes.

I tested this on my Mac + clang and found 6 or 7 compilation errors (fixed in 6cfb5a48fdc8b93fb7deda81030e17c00b3ba068).

Try it out on your *nix machines. I'm curious if it finds any more errors on Linux + gcc.

**Comment by jmespadero** [comment]
This is my version of the script for Linux+gcc:
```bash
#!/bin/bash
while true
do
    #Create a name for this test based on current date and time
    testName=`date +%Y%m%d%H%M%S`
    echo Create file $testName.cpp
    echo "`ls -1 ../include/igl/*.h | sed -e "s/.*igl\/\(.*\)/#include <igl\/\1>/" | perl -MList::Util=shuffle -wne 'print shuffle <>;'`
    int smain(){ }" > $testName.cpp
    echo Compile file $testName.cpp
    g++ -S $testName.cpp -I../include -IEigen -std=c++11 -fpermissive -Wno-deprecated-declarations 
    #Check if compile was ok (ignoring warnings)
    ls $testName.s || (echo TEST $testName FAILED && break )
    #Clean files for this test
    echo Test OK. Clean $testName and repeat new test
    rm  $testName.* 
done
    echo Check files *.cpp
```

I get this warning **on every** execution:
```
Compile file 20161110130455.cpp
In file included from 20161110130455.cpp:39:0:
../include/igl/serialize.h:191:25: warning: inline function ‘virtual void igl::Serializable::InitSerialization()’ used but never defined [enabled by default]
     inline virtual void InitSerialization() = 0;
                         ^
```

And sometimes, I get also this warning:
```
In file included from Eigen/Eigen/StdVector:23:0,
                 from ../include/igl/column_to_quats.h:13,
                 from 20161110130350.cpp:73:
Eigen/Eigen/src/StlSupport/StdVector.h:69:9: warning: partial specialization of ‘std::vector<T, Eigen::aligned_allocator<U> >’ after instantiation of ‘std::vector<Eigen::Transform<double, 3, 2>, Eigen::aligned_allocator<Eigen::Transform<double, 3, 2> > >’ [-fpermissive]
   class vector<T,EIGEN_ALIGNED_ALLOCATOR<T> >
         ^
```

I will post here the .cpp file if a compilation ends with an error.

**Comment by alecjacobson** [comment]
Thanks. The first warning seems to be an issue with GCC and pure virtual
(inline) functions. I made a note in the comments. But my feeling is that
this is harmless. The second warning seems to be an issue with Eigen (would
make sense to raise this to Eigen).

**Comment by jmespadero** [comment]
After 130 random compilations

- Still, there is no errors... 
- All compilation show the ```InitSerialization() = 0``` warning.
- 23 compilations show the ```vector<T,EIGEN_ALIGNED_ALLOCATOR<T> >``` warning
    - Sometimes included from ../include/igl/quats_to_column.h:13
    - Sometimes included from ../include/igl/column_to_quats.h:13
    - Sometimes included from ../include/igl/directed_edge_orientations.h:14

Seems there is no hope to find new errors, but I will keep the script running overnight.

**Comment by jmespadero** [comment]
A question...

Is really necessary the ```inline``` keyword in the line 191 of include/igl/serialize.h ? 
```c++
inline virtual void InitSerialization() = 0;
```

Removing the  ```inline``` keyword will eliminate the warning
```
../include/igl/serialize.h:191:25: warning: inline function ‘virtual void igl::Serializable::InitSerialization()’ used but never defined [enabled by default]
     inline virtual void InitSerialization() = 0;
                         ^
```
I'm not sure that ```inline``` makes sense in a pure virtual method. If the method has no body, what do you pretend to inline? 

PD: I have removed the inline and all tutorial compile fine.

**Comment by alecjacobson** [comment]
I think you're right.

**Comment by jmespadero** [comment]
Sent PR #396

**Comment by jmespadero** [comment]
Hi,
I have found a new error in igl/Timer.h:
```
In file included from 20161110193438.cpp:1:0:
../include/igl/Timer.h: In member function ‘void igl::Timer::start()’:
../include/igl/Timer.h:95:33: error: ‘NULL’ was not declared in this scope
       gettimeofday(&startCount, NULL);
                                 ^
../include/igl/Timer.h: In member function ‘void igl::Timer::stop()’:
../include/igl/Timer.h:110:31: error: ‘NULL’ was not declared in this scope
       gettimeofday(&endCount, NULL);
                               ^
../include/igl/Timer.h: In member function ‘double igl::Timer::getElapsedTimeInMicroSec()’:
../include/igl/Timer.h:150:33: error: ‘NULL’ was not declared in this scope
         gettimeofday(&endCount, NULL);
                                 ^
```

It is produced if ```igl/Timer.h``` is included as first file. I have attached one .cpp file that produced the error.

**Comment by jmespadero** [comment]
I have update the PR #396 to solve also this error.

**Comment by alecjacobson** [comment]
adding more evidence that this is a good test to run every now and again. Found 6 new include/namespace errors.

**Comment by alecjacobson** [comment]
Amazingly, this still works at finding bugs. Here's what I used most recently:

```bash
LIBIGL=/Users/alecjacobson/Repos/libigl/ echo -e "`ls -1 $LIBIGL/include/igl/*.h | sed -e "s/.*igl\/\(.*\)/#include <igl\/\1>/" | perl -MList::Util=shuffle -wne 'print shuffle <>;'`\\n  int main(){ }" | clang++ -xc++ - -I$LIBIGL/include -I $LIBIGL/build/_deps/eigen-src/ -std=c++11
```

**Comment by alecjacobson** [comment]
I moved this to https://github.com/libigl/libigl-scripts/blob/master/monkey_build.sh
