### ISSUE TITLE
questions about example 505_MIQ

### ISSUE THREAD

**Issue by VVingerfly** [libigl/libigl#393]
Hi, I am reading example 505_MIQ, but there are some variables that I can't understand, including MMatch, singularityIndex, Seams. I have read the paper and the code related to them, but it is hard for me to get them across. What's their meanings and Where I can find related materials?
Actually, I  want to find the uv  iso-lines of the parameterization. So I need first calculate the uv iso-lines on 2d parameterization domain. Then map them back to 3d surface. But since the original mesh is cut, I don't know how to get the relationship between the 2d cut mesh and 3d original mesh triangles.
Could  you @danielepanozzo  give me some suggestions?
Thank you very much!!!
with regards,
Wei

**Comment by danielepanozzo** [comment]
Hi,

we unfortunately do not have good documentations for these functions yet. It is a direct reimplementation of the MIQ paper:
* "MMatch" stores the matching per edge, i.e. the rotation that you need to transport the nrosy across the edge
* "singularityIndex" is a vector that stores the index of the singularities (which are always on vertices)
* "Seams" encodes the cut edges that needs to be duplicated before flattening the mesh in the Poisson parametrization step

To calcolate the "UV isolines" I suggest to save the mesh (with parametrization stored as UV coordinates) in an obj and then use libqex (https://github.com/hcebke/libQEx) to extract the quad mesh.

Cheers,
Daniele

**Comment by VVingerfly** [comment]
Thank you for your warm reply and suggestion.

One more question, what is the relationship between the mesh before and after cutting? 
How can I correspond a vertex in cut mesh to original mesh (one or more vertex in cut mesh can map to one vertex in the original mesh due to the cut process) ? Is there any variables that store this information??

Look forward to your reply.

with best regards,
Wei

**Comment by VVingerfly** [comment]
I have looked at libQEx, the UV coordinates required for input are saved for each vertex for all triangles, i.e. 3#F UV coordinates totally. I can't find the relationship between FUV and F, so I can't write the file for libQEx.

with best regards,
Wei

**Comment by danielepanozzo** [comment]
FUV and F should have exactly the same number of rows and the rows are in 1-1 correspondence (i.e. the 3D triangle in the first row of F corresponds to the uv triangle in the first row of FUV).

**Comment by VVingerfly** [comment]
Thank you very much for your kind reply!! These explanations really help me a lot. Thank you!

with best regards,
Wei
