### ISSUE TITLE
ubantu eigen3.3.0 build error

### ISSUE THREAD

**Issue by xianyongzhang** [libigl/libigl#397]
hi, I'm trying to use  the module of mesh_boolean.  However, I suffered from the error in the picture with  eigen3.3,0.  What's wrong?  

![image](https://cloud.githubusercontent.com/assets/5358665/20247436/3480d4d2-aa07-11e6-8c18-4e66d9791bf4.png)

**Comment by xianyongzhang** [comment]
here is the command which I used.
![image](https://cloud.githubusercontent.com/assets/5358665/20247473/21ecdc70-aa08-11e6-9342-90d2f345b967.png)

**Comment by alecjacobson** [comment]
This is fixed in e6ffb84

Currently, libigl has only been tested with Eigen 3.2. I'm guessing there
will be other issues with Eigen 3.3...
