### ISSUE TITLE
Possible duplicate code: n_polyvector.cpp and angle_bound_frame_fields.cpp

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#398]
@olkido  @danielepanozzo 

The large files `include/igl/n_polyvector.cpp` and  `include/igl/angle_bound_frame_fields.cpp` contain significant amounts of identical code. Are these functions computing the same thing at a high level?

If so, should we just keep one of them?

If not, is there a clean way to factor out the duplicated code?

**Comment by avaxman** [comment]
I am in the process of writing a full set of operators and processing for vector-set fields which will eventually include polyvectors and cross-fields, but it will take time.

**Comment by alecjacobson** [comment]
Cool. In the meantime, we should sort out these two functions. Are they
duplicates or just reusing copy-pasted code chunks?

**Comment by avaxman** [comment]
AFAIK reusing copy-paste code chunks, but not entirely similar... PolyVector is more general, but combing and matching are similar. I don't think we can currently categorically get rid of one of them.  And at any rate, I wouldn't do it without Olga D. who wrote this stuff.

**Comment by avaxman** [comment]
and there is also a lot of code common with the CoMISo related code.

**Comment by alecjacobson** [comment]
Thanks for clarifying Amir. Does this mean that n_polyvector is strictly
more general than/superior to angle_bound_frame_fields? That might lead to
an easy solution: remove angle_bound_frame_fields.

Another way of asking that is, is there a scenario when someone would want
to use angle_bound_frame_fields rather than n_polyvector (except for making
a comparison)?

Since neither are being used internally besides their respective tutorials.
I might propose that we move angle_bound_frame_fields to a "gist" and keep
n_polyvector. Unless, of course, someone volunteers to pull out the reused
bits between the two (this is my preferred option, but I won't have the
time to be the one to do it).

**Comment by avaxman** [comment]
Come to think of it, where is "angle_bound_frame_fields.h" used? I thought it was part of the conjugate/integrable frame fields which for some reason is distinct from n_polyvector, but I am not sure.

**Comment by alecjacobson** [comment]
You're right. `angle_bound_frame_fields` does not even have a corresponding
tutorial. Perhaps this just got swallowed by `n_polyvector` or it is an
unfinished attempt to pull out some reusable subroutine from `n_polyvector`.

This reenforces the plan to remove `angle_bound_frame_fields` and focus on
refactoring  `n_polyvector` into libigl-style code for the longer term
future.

**Comment by alecjacobson** [comment]
I guess these were removed / fixed.
