### ISSUE TITLE
iterating over adjacent edges

### ISSUE THREAD

**Issue by avaxman** [libigl/libigl#399]
Is there any way to iterate over all edges adjacent to a vertex in some order? corresponding with the edge indices you get in edge_topology().

**Comment by alecjacobson** [comment]
`edge_topology` is an obsolete, inferior duplicate of `edge_flaps`. It will
be removed in the future.

With `edge_flaps` (similar output as `edge_topology`) you can use
`igl::circulation` to travel around a vertex. circulation returns indices
to faces but from this you can easily determine the "spoke" edges or
"one-ring" vertices. See, for example, its use in `collapse_edge`

Currently this is only valid for manifold meshes, but probably what you
want to do won't make sense for non-manifold meshes anyway.

**Comment by avaxman** [comment]
The explanation is vague ("touched by circulation?"). Is the list sorted?

**Comment by alecjacobson** [comment]
yes, circulations are cyclically sorted.

**Comment by avaxman** [comment]
I should note that I put a DCEL structure in libhedra:
https://github.com/avaxman/libhedra ("dcel.h")
it returns matrices (the libigl way) and comfortable to work with in manners of circulation etc.

**Comment by alecjacobson** [comment]
neat!
