### ISSUE TITLE
Windows + gcc won't compile hello.cpp

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#40]
From personal email:

> I'm trying to use your libigl library. When I try to compile the hello.cpp example from the tutorial (using gcc in Windows Vista), I'm getting a long list of errors mostly along the lines of
> 
> "ISO C++ forbids declaration of ... with no type"
>
> If I comment out the parts of the program using igl but keep the parts using Eigen, it works fine. Also, I get the same error messages merely trying to include the <igl/cotmatrix.h> but commenting out the code that uses it.
> 
> If you've got no quick/easy answer for me, then please don't worry about it. I'm just hoping maybe you've encountered my problem and there's an easy troubleshoot. If not, no worries. Thanks for making libigl available!

**Comment by alecjacobson** [comment]
Could you paste a larger portion of the debug output (or all of it). Especially some indication of _where_ (which file, which line) the error is coming from.

**Comment by danielepanozzo** [comment]
we never tried to compile libigl on windows with gcc, not sure what the problem could be.

We tested our library on:
- windows using visual studio
- linux with gcc
- macosx with clang

The easiest fix for you is probably to switch to visual studio (or to use gcc on linux).

**Comment by cap257zero** [comment]
Thanks Alec and Daniele! Alec, below is the debug output:

Microsoft Windows [Version 6.0.6001]
Copyright (c) 2006 Microsoft Corporation.  All rights reserved.

C:\Users\Chris>cd Desktop/programming/tryEigen

C:\Users\Chris\Desktop\programming\tryEigen>g++ -I C:\eigen-eigen -I C:\igl-igl
hello.cpp -o hello
In file included from C:\igl-igl/igl/doublearea.h:93:0,
                 from C:\igl-igl/igl/cotmatrix_entries.cpp:9,
                 from C:\igl-igl/igl/cotmatrix_entries.h:34,
                 from C:\igl-igl/igl/cotmatrix.cpp:13,
                 from C:\igl-igl/igl/cotmatrix.h:56,
                 from hello.cpp:1:
C:\igl-igl/igl/doublearea.cpp: In function 'void igl::doublearea(const Eigen::Pl
ainObjectBase<DerivedV>&, const Eigen::PlainObjectBase<DerivedF>&, Eigen::PlainO
bjectBase<DerivedC>&)':
C:\igl-igl/igl/doublearea.cpp:33:16: error: ISO C++ forbids declaration of 'proj
_doublearea' with no type [-fpermissive]
C:\igl-igl/igl/doublearea.cpp: In lambda function:
C:\igl-igl/igl/doublearea.cpp:36:10: error: 'rx' does not name a type
C:\igl-igl/igl/doublearea.cpp:37:10: error: 'sx' does not name a type
C:\igl-igl/igl/doublearea.cpp:38:10: error: 'ry' does not name a type
C:\igl-igl/igl/doublearea.cpp:39:10: error: 'sy' does not name a type
C:\igl-igl/igl/doublearea.cpp:40:12: error: 'rx' was not declared in this scope
C:\igl-igl/igl/doublearea.cpp:40:15: error: 'sy' was not declared in this scope
C:\igl-igl/igl/doublearea.cpp:40:20: error: 'ry' was not declared in this scope
C:\igl-igl/igl/doublearea.cpp:40:23: error: 'sx' was not declared in this scope
C:\igl-igl/igl/doublearea.cpp: In function 'void igl::doublearea(const Eigen::Pl
ainObjectBase<DerivedV>&, const Eigen::PlainObjectBase<DerivedF>&, Eigen::PlainO
bjectBase<DerivedC>&)':
C:\igl-igl/igl/doublearea.cpp:41:3: warning: lambda expressions only available w
ith -std=c++11 or -std=gnu++11 [enabled by default]
C:\igl-igl/igl/doublearea.cpp:52:53: error: 'proj_doublearea' cannot be used as
a function
C:\igl-igl/igl/doublearea.cpp:64:40: error: 'proj_doublearea' cannot be used as
a function
C:\igl-igl/igl/doublearea.cpp: In function 'void doublearea(const Eigen::PlainOb
jectBase<DerivedA>&, const Eigen::PlainObjectBase<DerivedB>&, const Eigen::Plain
ObjectBase<DerivedC>&, Eigen::PlainObjectBase<DerivedD>&)':
C:\igl-igl/igl/doublearea.cpp:92:16: error: ISO C++ forbids declaration of 'R' w
ith no type [-fpermissive]
C:\igl-igl/igl/doublearea.cpp:93:16: error: ISO C++ forbids declaration of 'S' w
ith no type [-fpermissive]
C:\igl-igl/igl/doublearea.cpp:94:9: error: request for member 'col' in 'R', whic
h is of non-class type 'const int'
C:\igl-igl/igl/doublearea.cpp:94:26: error: request for member 'col' in 'S', whi
ch is of non-class type 'const int'
C:\igl-igl/igl/doublearea.cpp:94:45: error: request for member 'col' in 'R', whi
ch is of non-class type 'const int'
C:\igl-igl/igl/doublearea.cpp:94:62: error: request for member 'col' in 'S', whi
ch is of non-class type 'const int'
C:\igl-igl/igl/doublearea.cpp: In function 'typename DerivedA::Scalar igl::doubl
earea_single(const Eigen::PlainObjectBase<DerivedV>&, const Eigen::PlainObjectBa
se<DerivedF>&, const Eigen::PlainObjectBase<DerivedC>&)':
C:\igl-igl/igl/doublearea.cpp:106:8: error: 'r' does not name a type
C:\igl-igl/igl/doublearea.cpp:107:8: error: 's' does not name a type
C:\igl-igl/igl/doublearea.cpp:108:13: error: there are no arguments to 'r' that
depend on a template parameter, so a declaration of 'r' must be available [-fper
missive]
C:\igl-igl/igl/doublearea.cpp:108:13: note: (if you use '-fpermissive', G++ will
 accept your code, but allowing the use of an undeclared name is deprecated)
C:\igl-igl/igl/doublearea.cpp:108:18: error: there are no arguments to 's' that
depend on a template parameter, so a declaration of 's' must be available [-fper
missive]
C:\igl-igl/igl/doublearea.cpp:108:25: error: there are no arguments to 'r' that
depend on a template parameter, so a declaration of 'r' must be available [-fper
missive]
C:\igl-igl/igl/doublearea.cpp:108:30: error: there are no arguments to 's' that
depend on a template parameter, so a declaration of 's' must be available [-fper
missive]
In file included from C:\igl-igl/igl/volume.h:69:0,
                 from C:\igl-igl/igl/cotmatrix_entries.cpp:12,
                 from C:\igl-igl/igl/cotmatrix_entries.h:34,
                 from C:\igl-igl/igl/cotmatrix.cpp:13,
                 from C:\igl-igl/igl/cotmatrix.h:56,
                 from hello.cpp:1:
C:\igl-igl/igl/volume.cpp: In function 'void igl::volume(const Eigen::PlainObjec
tBase<DerivedA>&, const Eigen::PlainObjectBase<DerivedB>&, const Eigen::PlainObj
ectBase<DerivedC>&, const Eigen::PlainObjectBase<DerivedD>&, Eigen::PlainObjectB
ase<Derivedvol>&)':
C:\igl-igl/igl/volume.cpp:46:16: error: ISO C++ forbids declaration of 'AmD' wit
h no type [-fpermissive]
C:\igl-igl/igl/volume.cpp:47:16: error: ISO C++ forbids declaration of 'BmD' wit
h no type [-fpermissive]
C:\igl-igl/igl/volume.cpp:48:16: error: ISO C++ forbids declaration of 'CmD' wit
h no type [-fpermissive]
C:\igl-igl/igl/volume.cpp:50:13: error: request for member 'eval' in 'BmD', whic
h is of non-class type 'const int'
C:\igl-igl/igl/volume.cpp:50:24: error: request for member 'eval' in 'CmD', whic
h is of non-class type 'const int'
C:\igl-igl/igl/volume.cpp:51:16: error: ISO C++ forbids declaration of 'AmDdx' w
ith no type [-fpermissive]
C:\igl-igl/igl/volume.cpp:51:29: error: request for member 'array' in 'AmD', whi
ch is of non-class type 'const int'

C:\Users\Chris\Desktop\programming\tryEigen>

**Comment by alecjacobson** [comment]
Seems like you have a version of gcc that doesn't support (enough of)
c++11. Specifically the `auto` keyword. Which version of gcc are you using
and can you upgrade to a more modern one?

**Comment by cap257zero** [comment]
Yes, that was the problem. I had been using gcc version 4.7.0. I got Cygwin and used g++ 4.9.2 and it worked properly. Thanks for the help.

**Comment by alecjacobson** [comment]
Interesting. I would have thought gcc 4.7 would work... Thanks for the info and I'm glad it's working for you now.
