### ISSUE TITLE
This version may crash under Windows + VS2015 combination

### ISSUE THREAD

**Issue by wucm1994** [libigl/libigl#400]
This version may crash under Windows + VS2015 combination, I have older version (git 3 months ago) and everything works fine.

The problem may be caused by viewer functions because the program could initialize and print information at console without any troubles.

**Comment by alecjacobson** [comment]
Which tutorial is crashing for you?

**Comment by wucm1994** [comment]
All tutorials crashed when I pre-defined IGL_VIEWER_WITH_NANOGUI.

Without this definitions, the program runs well.

**Comment by danielepanozzo** [comment]
It should be fixed in f2ed64cb3844d5292c5796eb8a76a07bbc5638c7.

Could you please confirm?

**Comment by wucm1994** [comment]
Yes, I confirmed this problem is fixed now. I will close this issue, thank you very much!
