### ISSUE TITLE
ARAP tutorial typo

### ISSUE THREAD

**Issue by ubc-nvining** [libigl/libigl#405]
A small pecadillo:

igl::ARAPData data;
arap_data.energy = igl::ARAP_ENERGY_TYPE_SPOKES;
//arap_data.energy = igl::ARAP_ENERGY_TYPE_SPOKES_AND_RIMS;
//arap_data.energy = igl::ARAP_ENERGY_TYPE_ELEMENTS; //triangles or tets
igl::arap_precomputation(V,F,dim,b,data);

note that the code that sets the energy is arap_data.energy = whatever but the igl::ARAPData variable is actually just data.

**Comment by alecjacobson** [comment]
Fixed 2d23ea9
