### ISSUE TITLE
306_EigenDecomposition python example not taking any keyboard input

### ISSUE THREAD

**Issue by woahitsjc** [libigl/libigl#406]
When I load the example, I can view the model and use my mouse to rotate and drag it. However when I start typing a random key, it displays a runtime error: "unable to cast python object to c++ type" and it points to line "viewer.launch()". 

![306_runtime_error](https://cloud.githubusercontent.com/assets/16124957/20625195/a04d509a-b309-11e6-8a5c-198e667bd7df.png)

**Comment by copyme** [comment]
@woahitsjc do you still have this problem with the current version? Should this issue be still open?
