### ISSUE TITLE
Error when running tutorial 604 triangle in MSVC 2015 x64

### ISSUE THREAD

**Issue by Zcynical** [libigl/libigl#407]
Just like the former issue: [https://github.com/libigl/libigl/issues/372](https://github.com/libigl/libigl/issues/372), the tutorial 604_Triangle crashed in triangle.c under MSVC2015 update3 x64. But it works well in win32 mode. 
The reason is that the "unsigned long" in triangle.c  may not be large enough to store and operate on a pointer in some machine. 
And the solution was provided by: [https://github.com/okigan/triangle](https://github.com/okigan/triangle).
Just replace all the "unsigned long" as "unsigned long long" in triangle.c by defining a macro to avoid pointer truncation on 64-bit systems.
I hope this problem can be fixed in the trunk of the libigl.

**Comment by danielepanozzo** [comment]
Could you prepare a PR here with the change? 
https://github.com/libigl/triangle

**Comment by Zcynical** [comment]
Sure. Hope the code in PR would be fine with other OS / compiler.

**Comment by danielepanozzo** [comment]
This should be fixed in master, could you please confirm and close the issue?

**Comment by shmily1023** [comment]
Just replace all the "unsigned long" as "unsigned long long" in triangle.c by defining a macro to avoid pointer truncation on 64-bit systems.
