### ISSUE TITLE
Example 102_DrawMesh in Cygwin on Vista, error and (possible) fix

### ISSUE THREAD

**Issue by cap257zero** [libigl/libigl#41]
In the process of trying to compile this example (no success yet), I got two similar errors that I was able to eliminate with a small change to each of the files "file_dialog_open.cpp" and "file_dialog_save.cpp".

Should I describe the errors and the changes here or should I do the Fork and Pull Request thing? (Sorry I'm still new to GitHub).

**Comment by alecjacobson** [comment]
Fork and pull request is best and useful to learn how to do if you're
willing.

**Comment by cap257zero** [comment]
Sounds good, I'll give it a shot.
