### ISSUE TITLE
Problem on showing a bunny.off for Example 102 and showing the menu on the left-hand of the glwf window

### ISSUE THREAD

**Issue by etrigger** [libigl/libigl#410]
Hi,

I like the library, libigl. I have some problem with running the demo code  ([Example 102](https://libigl.github.io/libigl/tutorial/102_DrawMesh/main.cpp)).

I can only show the purple window with nothing being displayed (see Figure 1). I think I am expected to see some result as shown in Figure 2.

I use the Microsoft VS 2013 64 bit compiler on Windows 10 Enterprise with 64 bit.

The following libraries are all 64 bit
OpenGL32.Lib
glew32s.lib
glfw3.lib

Do you have any idea where I am wrong? Thanks

![image](https://cloud.githubusercontent.com/assets/3329503/20888563/cdf68d2e-baff-11e6-9524-0ed7a98fc3fd.png)
Figure 1
![image](https://cloud.githubusercontent.com/assets/3329503/20888726/6360e6c0-bb00-11e6-8e03-dcd0de7536b7.png)

Figure 2

**Comment by alecjacobson** [comment]
My guess is that the program cannot find the bunny file. You could confirm this by running in debug more or printing the size of V after the call to `igl::read_triangle_mesh`

**Comment by etrigger** [comment]
Hi,

The path is correct. I also try the absolute path and you can see the number of vertices and faces from the console output.

![image](https://cloud.githubusercontent.com/assets/3329503/20891673/c3cf11b6-bb0b-11e6-91c5-f3da8b16df1f.png)

**Comment by etrigger** [comment]
Thanks for the hint.

I have tried the VS 2015 community. I found that the pre-compiled library (both glew32s.lib and glfw3.lib offered by the official website) are build with 64-bit release mode, but I use the debug mode. That's the reason why I cannot display anything.

BTW, should I see the menu option on the left-hand side of the glwf window like the one shown in the figure below? I have tried many sample codes and they all have no menu option shown on the left-hand.
![image](https://cloud.githubusercontent.com/assets/3329503/20921156/28084994-bba3-11e6-8f65-dc2c0be566d1.png) Window with menu option on the left-hand

![image](https://cloud.githubusercontent.com/assets/3329503/20921209/65e9c0bc-bba3-11e6-967f-f93211941c9a.png)

The window I created does not have a menu option on the left-hand

**Comment by etrigger** [comment]
Hi,
I realized that I should compile the nanogui library and enable the IGL_VIEWER_WITH_NANOGUI option for viewer.h. Unfortunately, I don't know where to enable this option.  I am freshmen in the geometry processing.  Can you give me some hint?

**Comment by etrigger** [comment]
Finally, I figured out the right way for configuring the vs 2015 that enables the menu option.

Property Pages=>C/C++=> Command Line => Additional Options=> /D "IGL_VIEWER_WITH_NANOGUI" 
This turns on the option for the menu.

![image](https://cloud.githubusercontent.com/assets/3329503/20927392/aa72e42a-bbc1-11e6-8d92-5d64eef8fb29.png)

**Comment by alecjacobson** [comment]
Otherwise you can do this via CMAKE.

**Comment by alecjacobson** [comment]
I'm hoping the blank screen bug is fixed by efcd9dddd51d5c841ec08ff2c3ec005cb5d0cf8c

Please confirm

**Comment by etrigger** [comment]
It works for me.

**Comment by copyme** [comment]
The issue can be closed now, I think.
