### ISSUE TITLE
Tutorial 609 fail to reach the final result. The compile environment is: VS2015+X64+CGAL4.9

### ISSUE THREAD

**Issue by luogyong** [libigl/libigl#411]
The source code I used is exactly the tutorial 609.
When It runs,  it seems to fall in an un-limiting cycle status. I steped to " igl::copyleft::cgal::remesh_self_intersections(VV, FF, params, Vr, Fr, IF, CJ, I); ", and never step out again.

The C++ options are:
/Yu"stdafx.h" /GS /W3 /Zc:wchar_t /I"E:\Programminggithub\libigl\include" /I"E:\Programming\sourcecode\eigen-eigen-26667be4f70b" /I"E:\Programming\github\libigl\tutorial" /I"e:\Programming\github\libigl\include\igl\glew-2.0.0\include" /I"e:\Programming\github\libigl\include\igl\glfw-3.2.1.bin.WIN64\include" /I"E:\Programming\github\nanogui\include" /I"E:\Programming\github\nanogui\ext\nanovg" /I"E:\Programming\github\libigl\external\triangle" /I"E:\Programming\github\libigl\external\tetgen" /I"E:\Programming\github\nanogui\ext\nanovg\src" /I"E:\Programming\github\libigl\include\igl\viewer" /I"D:\dev\CGAL-4.9\build\include" /I"E:\Programming\github\boost_1_61_0" /I"D:\dev\CGAL-4.9\auxiliary\gmp\include" /I"D:\dev\CGAL-4.9\build\src" /ZI /Gm /Od /sdl /Fd"x64\Debug\vc140.pdb" /Zc:inline /fp:precise /D "_DEBUG" /D "_CONSOLE" /D "_CRT_SECURE_NO_WARNINGS" /D "_USE_MATH_DEFINES" /D "-D_CRT_NONSTDC_NO_DEPRECATE" /D "_CRT_NONSTDC_NO_DEPRECATE" /D "_SCL_SECURE_NO_WARNINGS" /errorReport:prompt /WX- /Zc:forScope /RTC1 /arch:SSE2 /Gd /MDd /openmp /Fa"x64\Debug" /EHsc /nologo /Fo"x64\Debug" /Fp"x64\Debug\trylibigl.pch"

the linker options are:
/OUT:"E:\Programming\trylibigl\trylibigl\x64\Debug\trylibigl.exe" /MANIFEST /NXCOMPAT /PDB:"E:\Programming\trylibigl\trylibigl\x64\Debug\trylibigl.pdb" /DYNAMICBASE "opengl32.lib" "glu32.lib" "glfw3.lib" "glfw3dll.lib" "glew32s.lib" "nanogui.lib" "triangle.lib" "tetgen.lib" "CGAL_Core-vc140-mt-4.9.lib" "CGAL_Core-vc140-mt-gd-4.9.lib" "CGAL-vc140-mt-4.9.lib" "CGAL-vc140-mt-gd-4.9.lib" "libgmp-10.lib" "libmpfr-4.lib" "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "comdlg32.lib" "advapi32.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "odbc32.lib" "odbccp32.lib" /MACHINE:X64 /INCREMENTAL /PGD:"E:\Programming\trylibigl\trylibigl\x64\Debug\trylibigl.pgd" /SUBSYSTEM:CONSOLE /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /ManifestFile:"x64\Debug\trylibigl.exe.intermediate.manifest" /ERRORREPORT:PROMPT /NOLOGO /LIBPATH:"e:\Programming\github\libigl\include\igl\glew-2.0.0\lib\Release\x64" /LIBPATH:"e:\Programming\github\libigl\include\igl\glfw-3.2.1.bin.WIN64\lib-vc2015" /LIBPATH:"E:\Programming\github\triangle\build\Release" /LIBPATH:"E:\Programming\github\tetgen\build\Release" /LIBPATH:"E:\Programming\github\nanogui\build\Release" /LIBPATH:"D:\dev\CGAL-4.9\build\lib" /LIBPATH:"d:\dev\CGAL-4.9\auxiliary\gmp\lib" /LIBPATH:"D:\dev\CGAL-4.9\build\bin" /TLBID:1

Any suggestion? Thank you.

**Comment by luogyong** [comment]
I found it can reach the right answer when it was complied under Release mode with the last version and the head-only version of CGAL 4.9.
Under the debug mode, it will still run into a unlimited cycle status.

**Comment by alecjacobson** [comment]
Are you sure it's not just taking a long time?

**Comment by alecjacobson** [comment]
I'm running with the assumption that it was just very slow under debug mode...
