### ISSUE TITLE
Unable to compile examples

### ISSUE THREAD

**Issue by Catrexis** [libigl/libigl#412]
Hey =)
i'am using linux and want to build the libigl examples... So i followed the tutorial instructions:

`git clone --recursive https://github.com/libigl/libigl.git`

```
cd tutorial
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ../
make
```

when I execute the "make" command, I get the first error in qslim_optimal_collapse_edge_callbacks.cpp
"isinf(...)" is not defined. I solved it by changing it to "std::isinf(...)"

now i typed "make" again and it compiles longer as in the first try but stops at the 2nd example:

```
[ 86%] Linking CXX executable ../102_DrawMesh_bin
../libigl/libiglcgal.a(outer_hull.cpp.o): In function `void igl::remove_unreferenced<Eigen::Matrix<CGAL::Lazy_exact_nt<CGAL::Gmpq>, -1, -1, 0, -1, -1>, Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<CGAL::Lazy_exact_nt<CGAL::Gmpq>, -1, -1, 0, -1, -1>, Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<int, -1, 1, 0, -1, 1> >(Eigen::PlainObjectBase<Eigen::Matrix<CGAL::Lazy_exact_nt<CGAL::Gmpq>, -1, -1, 0, -1, -1> > const&, Eigen::PlainObjectBase<Eigen::Matrix<int, -1, -1, 0, -1, -1> > const&, Eigen::PlainObjectBase<Eigen::Matrix<CGAL::Lazy_exact_nt<CGAL::Gmpq>, -1, -1, 0, -1, -1> >&, Eigen::PlainObjectBase<Eigen::Matrix<int, -1, -1, 0, -1, -1> >&, Eigen::PlainObjectBase<Eigen::Matrix<int, -1, 1, 0, -1, 1> >&)':
outer_hull.cpp:(.text._ZN3igl19remove_unreferencedIN5Eigen6MatrixIN4CGAL13Lazy_exact_ntINS3_4GmpqEEELin1ELin1ELi0ELin1ELin1EEENS2_IiLin1ELin1ELi0ELin1ELin1EEES7_S8_NS2_IiLin1ELi1ELi0ELin1ELi1EEEEEvRKNS1_15PlainObjectBaseIT_EERKNSA_IT0_EERNSA_IT1_EERNSA_IT2_EERNSA_IT3_EE[_ZN3igl19remove_unreferencedIN5Eigen6MatrixIN4CGAL13Lazy_exact_ntINS3_4GmpqEEELin1ELin1ELi0ELin1ELin1EEENS2_IiLin1ELin1ELi0ELin1ELin1EEES7_S8_NS2_IiLin1ELi1ELi0ELin1ELi1EEEEEvRKNS1_15PlainObjectBaseIT_EERKNSA_IT0_EERNSA_IT1_EERNSA_IT2_EERNSA_IT3_EE]+0x231): undefined reference to `void igl::slice<Eigen::PlainObjectBase<Eigen::Matrix<CGAL::Lazy_exact_nt<CGAL::Gmpq>, -1, -1, 0, -1, -1> >, Eigen::Matrix<int, -1, 1, 0, -1, 1>, Eigen::PlainObjectBase<Eigen::Matrix<CGAL::Lazy_exact_nt<CGAL::Gmpq>, -1, -1, 0, -1, -1> > >(Eigen::PlainObjectBase<Eigen::Matrix<CGAL::Lazy_exact_nt<CGAL::Gmpq>, -1, -1, 0, -1, -1> > const&, Eigen::PlainObjectBase<Eigen::Matrix<int, -1, 1, 0, -1, 1> > const&, int, Eigen::PlainObjectBase<Eigen::Matrix<CGAL::Lazy_exact_nt<CGAL::Gmpq>, -1, -1, 0, -1, -1> >&)'
collect2: error: ld returned 1 exit status
102_DrawMesh/CMakeFiles/102_DrawMesh_bin.dir/build.make:128: recipe for target '102_DrawMesh_bin' failed
make[2]: *** [102_DrawMesh_bin] Error 1
CMakeFiles/Makefile2:1646: recipe for target '102_DrawMesh/CMakeFiles/102_DrawMesh_bin.dir/all' failed
make[1]: *** [102_DrawMesh/CMakeFiles/102_DrawMesh_bin.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

and I don't now how to solve it. Do I have to put the EIGEN library somewhere in the libigl file, or do I have to specify it's location in any makefile? Can anyone help me? 

Thanks in advance
Cat

**Comment by alecjacobson** [comment]
Thanks for pointing out the missing std:: I've fixed that for an upcoming
commit.

What version of which compiler are you using?

It seems your linker is complaining about missing symbols even if they're
not used.

Meanwhile, for the other problem do you get the same problem if you issue:

cd tutorial/build
rm -f CMakeCache.txt
cmake -DCMAKE_BUILD_TYPE=Release -DLIBIGL_STATIC_LIBRARY=OFF ../
make

**Comment by Catrexis** [comment]
I think I use "gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609" 
but in the build output is written "Using /usr/bin/c++ compiler." But I think that's also the gcc compiler.
For 
`c++ --version`
I get the same version as for gcc:
`c++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609`

You mean
`cmake -DCMAKE_BUILD_TYPE=Release -DLIBIGL_**USE_**STATIC_LIBRARY=OFF ../`

When I compile in this way, it works until example 403_BoundedBiharmonicWeights, there he exits with following error in StdVector.h:

```
In file included from /homes/mkomaritzan/research/libigl/shared/cmake/../../external/nanogui/ext/eigen/Eigen/StdVector:23:0,
                 from /homes/mkomaritzan/research/libigl/tutorial/403_BoundedBiharmonicWeights/main.cpp:28:
/homes/mkomaritzan/research/libigl/shared/cmake/../../external/nanogui/ext/eigen/Eigen/src/StlSupport/StdVector.h:69:9: error: partial specialization of ‘class std::vector<T, Eigen::aligned_allocator<U> >’ after instantiation of ‘class std::vector<Eigen::Transform<double, 3, 2>, Eigen::aligned_allocator<Eigen::Transform<double, 3, 2> > >’ [-fpermissive]
   class vector<T,EIGEN_ALIGNED_ALLOCATOR<T> >
         ^
/homes/mkomaritzan/research/libigl/shared/cmake/../../external/nanogui/ext/eigen/Eigen/src/StlSupport/StdVector.h:69:9: error: partial specialization of ‘class std::vector<T, Eigen::aligned_allocator<U> >’ after instantiation of ‘class std::vector<Eigen::Quaternion<double>, Eigen::aligned_allocator<Eigen::Quaternion<double> > >’ [-fpermissive]
403_BoundedBiharmonicWeights/CMakeFiles/403_BoundedBiharmonicWeights_bin.dir/build.make:62: recipe for target '403_BoundedBiharmonicWeights/CMakeFiles/403_BoundedBiharmonicWeights_bin.dir/main.cpp.o' failed
make[2]: *** [403_BoundedBiharmonicWeights/CMakeFiles/403_BoundedBiharmonicWeights_bin.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:2162: recipe for target '403_BoundedBiharmonicWeights/CMakeFiles/403_BoundedBiharmonicWeights_bin.dir/all' failed
make[1]: *** [403_BoundedBiharmonicWeights/CMakeFiles/403_BoundedBiharmonicWeights_bin.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

Do you know a fix for that error?

Thanks in advance

**Comment by alecjacobson** [comment]
Thanks. This seems like an Eigen issue with this compiler.

Try compiling a very simple program like:

```cpp
#include <Eigen/Geometry>
#include <Eigen/StdVector>
#include <vector>
int main(int argc, char * argv[])
{
  std::vector<Eigen::Quaterniond,Eigen::aligned_allocator<Eigen::Quaterniond> >  Q;
}
```

If this fails with a similar error then I would report the issue on [Eigen's forum](https://forum.kde.org/viewforum.php?f=74), be sure to give them the Eigen version and compiler version.

**Comment by Catrexis** [comment]
This test program compiles properly. I tried to include all headers from example 403 in the simple test program and found that the error is induced by the order of included headers. It dissappears if:

```
#include <igl/deform_skeleton.h>
#include <igl/forward_kinematics.h>
#include <igl/column_to_quats.h>
```
are included after the Eigen libraries. Now I can also compile the FAST example. Thank you very much!
Is there a list of input commands for the examples?

**Comment by alecjacobson** [comment]
Ack. This is an _issue with Eigen_ (the include order shouldn't matter like that) but at least we can work around it. I've added extra includes includes that will hopeful fix this in  dd8183fe7056c2b1aee1dbd4aa246e3c908a3cad . It's hard for me to test without your setup though, since the problem is not happening on my setup or on the linux build test.

**Comment by Catrexis** [comment]
Which version of the gcc compiler are you using in your linux build test? 
I can test the new version, when you push your new commits.

Thanks so far =)

**Comment by alecjacobson** [comment]
gcc4.8.1
