### ISSUE TITLE
Lots of warnings in Visual Studio 2015 

### ISSUE THREAD

**Issue by Shazib** [libigl/libigl#413]
My project gives me lots of warnings about loss of data during conversions in visual studio, within the ligigl files.

![image](https://cloud.githubusercontent.com/assets/4405777/20964770/cd8cd91c-bc6a-11e6-8bd6-3b51bb25ff2e.png)

I also had to define certain things to even get it to compile.

#define BOOST_NO_CXX11_VARIADIC_TEMPLATES
#define _CRT_NONSTDC_NO_WARNINGS
#define _SCL_SECURE_NO_WARNINGS

Is there a more comprehensive guide to getting set up in VS2015?

Thanks!

**Comment by alecjacobson** [comment]
Most of these are innocuous. I would just ignore them or turn off warnings
for type conversions.

We use CMAKE to setup the windows build. I'm not sure why you had to define
those things, perhaps cmake knows to do that. You should just have to
enable c++11 support.
