### ISSUE TITLE
Unable to compile libigl with Eigen3.3.1

### ISSUE THREAD

**Issue by csv610** [libigl/libigl#415]
Hello,

How can I get rid of the following message which come while compiling libigl with Eigen3.3.1 ?

angle_bound_frame_fields.cpp:157:26: error: no match for ‘operator*’ (operand types are ‘double’ and ‘const ConstantReturnType {aka const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<int>, Eigen::Matrix<int, -1, 1> >}’)
   indFullToInterior = -1.*Eigen::VectorXi::Ones(numE,1);
                          ^

csv

**Comment by alecjacobson** [comment]
Eigen 3.3 is not yet supported. We expect there will be several compilation
errors like this. The plan is to support it in early 2017 but we'll see.

**Comment by sergio-freelance** [comment]
Hello, 
are there any updates about the support for Eigen 3.3?

Thank you

**Comment by alecjacobson** [comment]
I've managed to get everything compiling with Eigen 3.3.1 but I'm scared off by the performance bugs and problems with backwards compatibility in the current releases of Eigen. For now I plan to wait until Eigen is more stable.

**Comment by ataber** [comment]
Since libigl hosts an [eigen mirror](https://github.com/libigl/eigen) that's now at 3.3.3, can we assume that Eigen 3.3.3 at least is working now?
