### ISSUE TITLE
Sample code for mesh deformation using mouse interaction

### ISSUE THREAD

**Issue by etrigger** [libigl/libigl#417]
I am wondering if we could offer some sample code to interact with the mouse for the mesh deformation example such as the '405_AsRigidAsPossible'. I found the vertices in the selection are loaded from some '*.dmat' file, it will be much easier for the freshman like me to start using the igl library and build an interactive system.

I found some header file such as 'MouseController.h' may contain some useful function but I am not sure. Maybe later we could add it to the tutorial.

**Comment by alecjacobson** [comment]
There're a few examples like this in a separate project: https://github.com/libigl/libigl-examples see `skeleton-poser/`. However, keep in mind that unlike the tutorial, these examples are not build-tested on all systems and more like to be out of date/unsupported.

**Comment by etrigger** [comment]
Thanks. That's exactly what I am looking for.

Just a reminder for those who may try the example.cpp in https://github.com/libigl/libigl-examples see skeleton-poser/, I compile it on VS 2015 and I got the white window without showing anything else. I add _glFlush_() just before _glutSwapBuffers_() for _display_ function and it works for me. 

![image](https://cloud.githubusercontent.com/assets/3329503/21144515/463ddc46-c14b-11e6-80c4-150f7fa40026.png)


I also ignore the case of char(3) for _key_(unsigned char key, int mouse_x, int mouse_y).

BTW, do we have some inverse kinematic code for the mesh deformation?

**Comment by alecjacobson** [comment]
I pushed a change for the glFlush(), thanks for that.

Regarding IK, we do not have a standard IK implementation in libigl.
Instead we have an implementation of "Fast Automatic Skinning
Transformations" `igl::arap_dof`. This acts like IK via the deformation of
the surface. This might be more than you're asking for and has a bit of an
uncomfortable (though powerful) interface.
