### ISSUE TITLE
Will Imesh be part of libIGL ?

### ISSUE THREAD

**Issue by csv610** [libigl/libigl#419]
Hello,

I find Imesh to be one one of the greatest software coming from the same group,
I am wondering if it will be part of libIGL ? 

csv

**Comment by alecjacobson** [comment]
What is IMesh?

iWires?

**Comment by csv610** [comment]
InstantMeshes

**Comment by alecjacobson** [comment]
Probably you already found it. But the code for InstantMeshes is already a separate project on github:
https://github.com/wjakob/instant-meshes/

Not sure if those authors have any plans to reduce it to a libigl-style function call and submit a pull request, but as far as I know there isn't.

**Comment by danielepanozzo** [comment]
The Instant Meshes code has many additional dependencies that we do not have in libigl, that's why it lives in a separate repository. I am not aware of any plan to integrate it in libigl.
