### ISSUE TITLE
tutorial example 102 visualization issue?

### ISSUE THREAD

**Issue by ada-hs** [libigl/libigl#421]
I try to use libigl do geometric processing work, I learn the examples 102. The result should visualize a mesh in an interface. Some errors occurred about glew library,but I did not fix it yet. I need help.
Here is my include library configuration:
![image](https://cloud.githubusercontent.com/assets/11327318/21176073/2aee0116-c220-11e6-89b6-403959a282a4.png)

Is there anybody meet this problem and fix it? Thanks for help.
sorry for my huge error list.

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol __imp_glBindTexture referenced in function "public: void __cdecl igl::viewer::OpenGL_state::bind_mesh(void)" (?bind_mesh@OpenGL_state@viewer@igl@@QEAAXXZ)	geo_process2	c:\Users\cutefairy\documents\visual studio 2015\Projects\geo_process2\geo_process2\main.obj	1	
Error	LNK2019	unresolved external symbol __imp_glClear referenced in function "public: void __cdecl igl::viewer::ViewerCore::clear_framebuffers(void)" (?clear_framebuffers@ViewerCore@viewer@igl@@QEAAXXZ)	geo_process2	c:\Users\cutefairy\documents\visual studio 2015\Projects\geo_process2\geo_process2\main.obj	1	
Error	LNK2019	unresolved external symbol __imp_glClearColor referenced in function "public: void __cdecl igl::viewer::ViewerCore::clear_framebuffers(void)" (?clear_framebuffers@ViewerCore@viewer@igl@@QEAAXXZ)	geo_process2	c:\Users\cutefairy\documents\visual studio 2015\Projects\geo_process2\geo_process2\main.obj	1	
Error	LNK2019	unresolved external symbol __imp_glDeleteTextures referenced in function "public: void __cdecl igl::viewer::OpenGL_state::free_buffers(void)" (?free_buffers@OpenGL_state@viewer@igl@@QEAAXXZ)	geo_process2	c:\Users\cutefairy\documents\visual studio 2015\Projects\geo_process2\geo_process2\main.obj	1	
Error	LNK2019	unresolved external symbol __imp_glDisable referenced in function "public: void __cdecl igl::viewer::ViewerCore::draw(class igl::viewer::ViewerData &,class igl::viewer::OpenGL_state &,bool)" (?draw@ViewerCore@viewer@igl@@QEAAXAEAVViewerData@23@AEAVOpenGL_state@23@_N@Z)	geo_process2	c:\Users\cutefairy\documents\visual studio 2015\Projects\geo_process2\geo_process2\main.obj	1	
Error	LNK2019	unresolved external symbol __imp_glDrawElements referenced in function "public: void __cdecl igl::viewer::OpenGL_state::draw_mesh(bool)" (?draw_mesh@OpenGL_state@viewer@igl@@QEAAX_N@Z)	geo_process2	c:\Users\cutefairy\documents\visual studio 2015\Projects\geo_process2\geo_process2\main.obj	1	
Error	LNK2019	unresolved external symbol __imp_glEnable referenced in function "public: void __cdecl igl::viewer::ViewerCore::draw(class igl::viewer::ViewerData &,class igl::viewer::OpenGL_state &,bool)" (?draw@ViewerCore@viewer@igl@@QEAAXAEAVViewerData@23@AEAVOpenGL_state@23@_N@Z)	geo_process2	c:\Users\cutefairy\documents\visual studio 2015\Projects\geo_process2\geo_process2\main.obj	1	
Error	LNK2019	unresolved external symbol __imp_glGenTextures referenced in function "public: void __cdecl igl::viewer::OpenGL_state::init_buffers(void)" (?init_buffers@OpenGL_state@viewer@igl@@QEAAXXZ)	geo_process2	c:\Users\cutefairy\documents\visual studio 2015\Projects\geo_process2\geo_process2\main.obj	1	
Error	LNK2019	unresolved external symbol __imp_glGetError referenced in function "public: int __cdecl igl::viewer::Viewer::launch_init(bool,bool)" (?launch_init@Viewer@viewer@igl@@QEAAH_N0@Z)	geo_process2	c:\Users\cutefairy\documents\visual studio 2015\Projects\geo_process2\geo_process2\main.obj	1	
Error	LNK2019	unresolved external symbol __imp_glGetString referenced in function "public: int __cdecl igl::viewer::Viewer::launch_init(bool,bool)" (?launch_init@Viewer@viewer@igl@@QEAAH_N0@Z)	geo_process2	c:\Users\cutefairy\documents\visual studio 2015\Projects\geo_process2\geo_process2\main.obj	1	
Error	LNK2019	unresolved external symbol __imp_glLineWidth referenced in function "public: void __cdecl igl::viewer::ViewerCore::draw(class igl::viewer::ViewerData &,class igl::viewer::OpenGL_state &,bool)" (?draw@ViewerCore@viewer@igl@@QEAAXAEAVViewerData@23@AEAVOpenGL_state@23@_N@Z)	geo_process2	c:\Users\cutefairy\documents\visual studio 2015\Projects\geo_process2\geo_process2\main.obj	1	
Error	LNK2019	unresolved external symbol __imp_glPixelStorei referenced in function "public: void __cdecl igl::viewer::OpenGL_state::bind_mesh(void)" (?bind_mesh@OpenGL_state@viewer@igl@@QEAAXXZ)	geo_process2	c:\Users\cutefairy\documents\visual studio 2015\Projects\geo_process2\geo_process2\main.obj	1	
Error	LNK2019	unresolved external symbol __imp_glPointSize referenced in function "public: void __cdecl igl::viewer::ViewerCore::draw(class igl::viewer::ViewerData &,class igl::viewer::OpenGL_state &,bool)" (?draw@ViewerCore@viewer@igl@@QEAAXAEAVViewerData@23@AEAVOpenGL_state@23@_N@Z)	geo_process2	c:\Users\cutefairy\documents\visual studio 2015\Projects\geo_process2\geo_process2\main.obj	1	
Error	LNK2019	unresolved external symbol __imp_glPolygonMode referenced in function "public: void __cdecl igl::viewer::OpenGL_state::draw_mesh(bool)" (?draw_mesh@OpenGL_state@viewer@igl@@QEAAX_N@Z)	geo_process2	c:\Users\cutefairy\documents\visual studio 2015\Projects\geo_process2\geo_process2\main.obj	1	
Error	LNK2019	unresolved external symbol __imp_glPolygonOffset referenced in function "public: void __cdecl igl::viewer::OpenGL_state::draw_mesh(bool)" (?draw_mesh@OpenGL_state@viewer@igl@@QEAAX_N@Z)	geo_process2	c:\Users\cutefairy\documents\visual studio 2015\Projects\geo_process2\geo_process2\main.obj	1	
Error	LNK2019	unresolved external symbol __imp_glTexImage2D referenced in function "public: void __cdecl igl::viewer::OpenGL_state::bind_mesh(void)" (?bind_mesh@OpenGL_state@viewer@igl@@QEAAXXZ)	geo_process2	c:\Users\cutefairy\documents\visual studio 2015\Projects\geo_process2\geo_process2\main.obj	1	
Error	LNK2019	unresolved external symbol __imp_glTexParameteri referenced in function "public: void __cdecl igl::viewer::OpenGL_state::bind_mesh(void)" (?bind_mesh@OpenGL_state@viewer@igl@@QEAAXXZ)	geo_process2	c:\Users\cutefairy\documents\visual studio 2015\Projects\geo_process2\geo_process2\main.obj	1	
Error	LNK2019	unresolved external symbol __imp_glViewport referenced in function "public: void __cdecl igl::viewer::ViewerCore::draw(class igl::viewer::ViewerData &,class igl::viewer::OpenGL_state &,bool)" (?draw@ViewerCore@viewer@igl@@QEAAXAEAVViewerData@23@AEAVOpenGL_state@23@_N@Z)	geo_process2	c:\Users\cutefairy\documents\visual studio 2015\Projects\geo_process2\geo_process2\main.obj	1	
Error	LNK2019	unresolved external symbol glewInit referenced in function "public: int __cdecl igl::viewer::Viewer::launch_init(bool,bool)" (?launch_init@Viewer@viewer@igl@@QEAAH_N0@Z)	geo_process2	c:\Users\cutefairy\documents\visual studio 2015\Projects\geo_process2\geo_process2\main.obj	1	
Error	LNK2019	unresolved external symbol glewGetErrorString referenced in function "public: int __cdecl igl::viewer::Viewer::launch_init(bool,bool)" (?launch_init@Viewer@viewer@igl@@QEAAH_N0@Z)	geo_process2	c:\Users\cutefairy\documents\visual studio 2015\Projects\geo_process2\geo_process2\main.obj	1	
Error	LNK2019	unresolved external symbol glewGetString referenced in function "public: int __cdecl igl::viewer::Viewer::launch_init(bool,bool)" (?launch_init@Viewer@viewer@igl@@QEAAH_N0@Z)	geo_process2	c:\Users\cutefairy\documents\visual studio 2015\Projects\geo_process2\geo_process2\main.obj	1	
Error	LNK2019	unresolved external symbol glfwInit referenced in function "public: int __cdecl igl::viewer::Viewer::launch_init(bool,bool)" (?launch_init@Viewer@viewer@igl@@QEAAH_N0@Z)	geo_process2	c:\Users\cutefairy\documents\visual studio 2015\Projects\geo_process2\geo_process2\main.obj	1	
Error	LNK2019	unresolved external symbol glfwTerminate referenced in function "public: int __cdecl igl::viewer::Viewer::launch_init(bool,bool)" (?launch_init@Viewer@viewer@igl@@QEAAH_N0@Z)	geo_process2	c:\Users\cutefairy\documents\visual studio 2015\Projects\geo_process2\geo_process2\main.obj	1	
Error	LNK2019	unresolved external symbol glfwSetErrorCallback referenced in function "public: int __cdecl igl::viewer::Viewer::launch_init(bool,bool)" (?launch_init@Viewer@viewer@igl@@QEAAH_N0@Z)	geo_process2	c:\Users\cutefairy\documents\visual studio 2015\Projects\geo_process2\geo_process2\main.obj	1	
Error	LNK2019	unresolved external symbol glfwGetPrimaryMonitor referenced in function "public: int __cdecl igl::viewer::Viewer::launch_init(bool,bool)" (?launch_init@Viewer@viewer@igl@@QEAAH_N0@Z)	geo_process2	c:\Users\cutefairy\documents\visual studio 2015\Projects\geo_process2\geo_process2\main.obj	1	
Error	LNK2019	unresolved external symbol glfwGetVideoMode referenced in function "public: int __cdecl igl::viewer::Viewer::launch_init(bool,bool)" (?launch_init@Viewer@viewer@igl@@QEAAH_N0@Z)	geo_process2	c:\Users\cutefairy\documents\visual studio 2015\Projects\geo_process2\geo_process2\main.obj	1	
Error	LNK2019	unresolved external symbol glfwWindowHint referenced in function "public: int __cdecl igl::viewer::Viewer::launch_init(bool,bool)" (?launch_init@Viewer@viewer@igl@@QEAAH_N0@Z)	geo_process2	c:\Users\cutefairy\documents\visual studio 2015\Projects\geo_process2\geo_process2\main.obj	1	
Error	LNK2019	unresolved external symbol glfwCreateWindow referenced in function "public: int __cdecl igl::viewer::Viewer::launch_init(bool,bool)" (?launch_init@Viewer@viewer@igl@@QEAAH_N0@Z)	geo_process2	c:\Users\cutefairy\documents\visual studio 2015\Projects\geo_process2\geo_process2\main.obj	1	
Error	LNK2019	unresolved external symbol glfwDestroyWindow referenced in function "public: void __cdecl igl::viewer::Viewer::launch_shut(void)" (?launch_shut@Viewer@viewer@igl@@QEAAXXZ)	geo_process2	c:\Users\cutefairy\documents\visual studio 2015\Projects\geo_process2\geo_process2\main.obj	1	
Error	LNK2019	unresolved external symbol glfwWindowShouldClose referenced in function "public: bool __cdecl igl::viewer::Viewer::launch_rendering(bool)" (?launch_rendering@Viewer@viewer@igl@@QEAA_N_N@Z)	geo_process2	c:\Users\cutefairy\documents\visual studio 2015\Projects\geo_process2\geo_process2\main.obj	1	
Error	LNK2019	unresolved external symbol glfwSetWindowShouldClose referenced in function "void __cdecl glfw_key_callback(class GLFWwindow *,int,int,int,int)" (?glfw_key_callback@@YAXPEAVGLFWwindow@@HHHH@Z)	geo_process2	c:\Users\cutefairy\documents\visual studio 2015\Projects\geo_process2\geo_process2\main.obj	1	
Error	LNK2019	unresolved external symbol glfwGetWindowSize referenced in function "public: int __cdecl igl::viewer::Viewer::launch_init(bool,bool)" (?launch_init@Viewer@viewer@igl@@QEAAH_N0@Z)	geo_process2	c:\Users\cutefairy\documents\visual studio 2015\Projects\geo_process2\geo_process2\main.obj	1	
Error	LNK2019	unresolved external symbol glfwGetFramebufferSize referenced in function "public: int __cdecl igl::viewer::Viewer::launch_init(bool,bool)" (?launch_init@Viewer@viewer@igl@@QEAAH_N0@Z)	geo_process2	c:\Users\cutefairy\documents\visual studio 2015\Projects\geo_process2\geo_process2\main.obj	1

**Comment by danielepanozzo** [comment]
It seems that you are trying to build the example with a project file that you create by hand. Could you try to:

1. Clone the libigl repository with the --recurvise option
2. Use CMAKE to create the project (as detailed in the tutorial compilation instruction https://libigl.github.io/libigl/tutorial/tutorial.html#chapter1:introductiontolibigl)?

If you get it to work with the cmake project file you can then compare our build system with yours to figure out where the differences are.

**Comment by ada-hs** [comment]
I use cmake to build the project, but when I compile it in the VS 2015(64-bit), the error"can't open include file : igl/readOFF.h occurred.....even I add the path of include library in property manager.

**Comment by danielepanozzo** [comment]
Can you post the error log? It is very strange since we have an automatic build (cmake + VS 2015 64bit) that works on the latest version: https://ci.appveyor.com/project/danielepanozzo/libigl-6hjk1

Also, you should use the cmake inside the tutorial folder, not the one inside the 102 example.

**Comment by ada-hs** [comment]
Well,I do as you suggest like this:
![image](https://cloud.githubusercontent.com/assets/11327318/21228100/7adbb52c-c317-11e6-9ecf-7ed3208645ce.png)
sorry for the long log.


The C compiler identification is MSVC 19.0.24210.0
The CXX compiler identification is MSVC 19.0.24210.0
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Could NOT find Matlab (missing:  Matlab_INCLUDE_DIRS Matlab_MEX_LIBRARY Matlab_MEX_EXTENSION Matlab_ROOT_DIR) 
Visual Leak Detector (VLD) is not found.
Build type: Release
USING CXXFLAGS = '/DWIN32 /D_WINDOWS /W3 /GR /EHsc /MD /O2 /Ob2 /DNDEBUG'
USING EXEFLAGS = '/machine:x64 /INCREMENTAL:NO'
Targetting Visual Studio 14 2015 Win64
Target build enviroment supports auto-linking
Using VC14 compiler.
Generator uses intermediate configuration directory: $(Configuration)
Requested component: MPFR
Requested component: GMP
Found CGAL: C:/CGAL_4.9/BUILD
CMake Error at C:/liggl/libigl-master/libigl-master/shared/cmake/CMakeLists.txt:201 (add_subdirectory):
  The source directory

    C:/liggl/libigl-master/libigl-master/external/CoMISo

  does not contain a CMakeLists.txt file.


CMake Error at C:/liggl/libigl-master/libigl-master/shared/cmake/CMakeLists.txt:255 (add_subdirectory):
  The source directory

    C:/liggl/libigl-master/libigl-master/external/embree

  does not contain a CMakeLists.txt file.


CMake Error at C:/liggl/libigl-master/libigl-master/shared/cmake/CMakeLists.txt:348 (add_subdirectory):
  The source directory

    C:/liggl/libigl-master/libigl-master/external/tetgen

  does not contain a CMakeLists.txt file.


CMake Error at C:/liggl/libigl-master/libigl-master/shared/cmake/CMakeLists.txt:362 (add_subdirectory):
  The source directory

    C:/liggl/libigl-master/libigl-master/external/triangle

  does not contain a CMakeLists.txt file.


Found OpenGL: opengl32  
CMake Error at C:/liggl/libigl-master/libigl-master/shared/cmake/CMakeLists.txt:401 (add_subdirectory):
  add_subdirectory given source
  "C:/liggl/libigl-master/libigl-master/shared/cmake/../../external/nanogui/ext/glfw"
  which is not an existing directory.


CMake Error at C:/liggl/libigl-master/libigl-master/shared/cmake/CMakeLists.txt:410 (add_subdirectory):
  add_subdirectory given source
  "C:/liggl/libigl-master/libigl-master/shared/cmake/../../external/nanogui/ext/glew"
  which is not an existing directory.


-- libigl includes:
	 C:/liggl/libigl-master/libigl-master/shared/cmake/../../external/nanogui/ext/eigen
	 C:/liggl/libigl-master/libigl-master/shared/cmake/../../include
	 C:/boost_1_62_0/boost_1_62_0
	 C:/CGAL_4.9/BUILD/include
	 C:/CGAL_4.9/include
	 C:/liggl/libigl-master/libigl-master/shared/cmake/../../external/CoMISo/ext/gmm-4.2/include
	 C:/liggl/libigl-master/libigl-master/shared/cmake/../../external/CoMISo/../
	 C:/liggl/libigl-master/libigl-master/shared/cmake/../../external/embree/include
	 C:/liggl/libigl-master/libigl-master/shared/cmake/../../external/lim
	 C:/liggl/libigl-master/libigl-master/shared/cmake/../../external/stb_image
	 C:/liggl/libigl-master/libigl-master/shared/cmake/../../external/tetgen
	 C:/liggl/libigl-master/libigl-master/shared/cmake/../../external/triangle
	 C:/liggl/libigl-master/libigl-master/shared/cmake/../../external/nanogui/ext/glfw/include
	 C:/liggl/libigl-master/libigl-master/shared/cmake/../../external/nanogui/ext/glew/include
	 C:/liggl/libigl-master/libigl-master/shared/cmake/../../external/tinyxml2
-- libigl libraries:
	 iglxml
	 iglviewer
	 igltriangle
	 igltetgen
	 iglpng
	 iglopengl2
	 iglopengl
	 igllim
	 iglembree
	 iglcomiso
	 iglcgal
	 igl
-- libigl extra libraries:
	 CoMISo
	 C:/liggl/libigl-master/libigl-master/shared/cmake/../../external/CoMISo/ext/OpenBLAS-v0.2.14-Win64-int64/lib/libopenblas.dll.a.lib
	 embree
	 lim
	 stb_image
	 tetgen
	 triangle
	 glfw
	 opengl32
	 glew
	 tinyxml2
-- libigl definitions:
	 -DIGL_STATIC_LIBRARY
	 -DINCLUDE_TEMPLATES
	 -DENABLE_STATIC_LIB
	 -DIGL_NO_MOSEK
Configuring incomplete, errors occurred!
See also "C:/liggl/Build_demo2/CMakeFiles/CMakeOutput.log".

**Comment by danielepanozzo** [comment]
1. You should clone the repository with the "--recursive" option. It looks like you directly downloaded the zip archive instead of using "git clone --recursive".
2. I suggest to use C:/liggl/libigl-master/libigl-master/tutorial/build as the build directory if the source is in C:/liggl/libigl-master/libigl-master/tutorial
