### ISSUE TITLE
Example 407 - "DenseBase::resize() does not actually allow to resize." failed. Aborted (core dumped)

### ISSUE THREAD

**Issue by vusak** [libigl/libigl#425]
I'm seeing an issue with Example 407

I've copied the example source to a location outside of the libigl installation and also copied the octopus meshes local to the exectuable, and modified the example to use the lines:

```
if(!readMESH("octopus-low.mesh",low.V,low.T,low.F))
  {
    cout<<"failed to load mesh"<<endl;
  }
  if(!readMESH("octopus-high.mesh",high.V,high.T,high.F))
  {
    cout<<"failed to load mesh"<<endl;
  }
```

I'm building with the line:

`g++ main.cpp -std=c++11 -I../libigl/include -I/usr/local/include/eigen3 -lGL -lGLEW -lglfw -o meshdeformtest`

I see a warning (may be relevant?):

```
In file included from ../libigl/include/igl/slice.h:84:0,
                 from ../libigl/include/igl/min_quad_with_fixed.cpp:10,
                 from ../libigl/include/igl/min_quad_with_fixed.h:175,
                 from ../libigl/include/igl/arap.h:11,
                 from main.cpp:1:
../libigl/include/igl/slice.cpp: In instantiation of ‘void igl::slice(const Eigen::SparseMatrix<Scalar>&, const Eigen::Matrix<int, -1, 1>&, const Eigen::Matrix<int, -1, 1>&, Eigen::SparseMatrix<TY>&) [with TX = double; TY = double]’:
../libigl/include/igl/min_quad_with_fixed.cpp:107:40:   required from ‘bool igl::min_quad_with_fixed_precompute(const Eigen::SparseMatrix<Scalar>&, const Eigen::PlainObjectBase<Derivedknown>&, const Eigen::SparseMatrix<Scalar>&, bool, igl::min_quad_with_fixed_data<T>&) [with T = double; Derivedknown = Eigen::Matrix<int, -1, 1>]’
../libigl/include/igl/min_quad_with_fixed.cpp:582:57:   required from ‘bool igl::min_quad_with_fixed(const Eigen::SparseMatrix<Scalar>&, const Eigen::PlainObjectBase<DerivedY>&, const Eigen::PlainObjectBase<Derivedknown>&, const Eigen::PlainObjectBase<DerivedBeq>&, const Eigen::SparseMatrix<Scalar>&, const Eigen::PlainObjectBase<DerivedZ>&, bool, Eigen::PlainObjectBase<Derivedsol>&) [with T = double; Derivedknown = Eigen::Matrix<int, -1, 1>; DerivedB = Eigen::Matrix<double, -1, 1>; DerivedY = Eigen::Matrix<double, -1, -1>; DerivedBeq = Eigen::Matrix<double, -1, 1>; DerivedZ = Eigen::Matrix<double, -1, -1>]’
../libigl/include/igl/biharmonic_coordinates.cpp:145:83:   required from ‘bool igl::biharmonic_coordinates(const Eigen::PlainObjectBase<OtherDerived>&, const Eigen::PlainObjectBase<Derivedknown>&, const std::vector<std::vector<SType> >&, int, Eigen::PlainObjectBase<DerivedBeq>&) [with DerivedV = Eigen::Matrix<double, -1, -1>; DerivedT = Eigen::Matrix<int, -1, -1>; SType = int; DerivedW = Eigen::Matrix<double, -1, -1>]’
main.cpp:67:52:   required from here
../libigl/include/igl/slice.cpp:54:62: warning: ‘Eigen::DynamicSparseMatrix<_Scalar, _Flags, _Index>::DynamicSparseMatrix(Eigen::DynamicSparseMatrix<_Scalar, _Flags, _Index>::Index, Eigen::DynamicSparseMatrix<_Scalar, _Flags, _Index>::Index) [with _Scalar = double; int _Options = 1; _Index = int; Eigen::DynamicSparseMatrix<_Scalar, _Flags, _Index>::Index = int]’ is deprecated (declared at /usr/local/include/eigen3/unsupported/Eigen/src/SparseExtra/DynamicSparseMatrix.h:233) [-Wdeprecated-declarations]
   Eigen::DynamicSparseMatrix<TY, Eigen::RowMajor> dyn_Y(ym,yn);
                                                              ^
```

When I run the executable, i get the output:

```
Finding closest points...
meshdeformtest: /usr/local/include/eigen3/Eigen/src/Core/DenseBase.h:228: void Eigen::DenseBase<Derived>::resize(Eigen::DenseBase<Derived>::Index, Eigen::DenseBase<Derived>::Index) [with Derived = Eigen::Matrix<double, 1, -1>; Eigen::DenseBase<Derived>::Index = long int]: Assertion `nbRows == this->rows() && nbCols == this->cols() && "DenseBase::resize() does not actually allow to resize."' failed.
Aborted (core dumped)
```

With some debug logging, this appears to be happening within AABB.cpp as result of a call to 

`igl::point_mesh_squared_distance(low.V,high.V,J,sqrD,b,_2);`

**Comment by alecjacobson** [comment]
What version of Eigen are you using?

**Comment by vusak** [comment]
I'm using the HEAD of 3.2 which points to https://bitbucket.org/eigen/eigen/commits/3c54486ba8221cfbbbfe3258a4dfd2db449dd555?at=3.2

I had a look around for a specified eigen version dependency or correlated libigl version/tag/branch but couldn't see anything. I did find a reference to not using 3.3 until 2017.

If there is a specific commit from libigl that works with a specific commit from eigen, i can switch to that.

**Comment by alecjacobson** [comment]
Use the eigen buried in the external directory.

**Comment by vusak** [comment]
Ah ok, yeah i see it living under nanogui.

Looks like its pegged to 3.2.9.

I tried setting the eigen checkout to 3.2.9, rebuilt and got the same problem.

I tried checking out https://github.com/libigl/eigen and then rebuilt with that version and still got the same problem.

Just to clarify im trying to avoid depending on all those externals, as i only need the math for my project, and would prefer to be able to just consume the relevant libigl headers and eigen headers. Im using the example to validate the math i need can be built/run.

**Comment by alecjacobson** [comment]
anything directly in the include/igl/ directory only depends on stl and
eigen.

**Comment by vusak** [comment]
thats great news :)

looks like ive got it working, i was overcomplicating the libigl + eigen dependency relation - checking out libigl @ c7507c0d03fe40cb24a272f894375140ab82b891 and eigen @ c34a9130bc585b288703bd9716d7efae194974e2 has allowed me to progress.

thanks!
