### ISSUE TITLE
error in tutorial 503_ARAPParam & 502_LSCMParam

### ISSUE THREAD

**Issue by bradrothenberg** [libigl/libigl#43]
Hello, 

I was just going through the tutoriols you provided, & when trying to run these two: 
503_ARAPParam
&
502_LSCMParam

Th program crashes because of a vector out of range.

I am compiling with VS2013, windows 7.

**Comment by danielepanozzo** [comment]
Thanks for the bug report, it should be fixed now. Could you please confirm that 502 and 503 are now running properly on your machine?

**Comment by bradrothenberg** [comment]
sure, I'll let you know asap

**Comment by bradrothenberg** [comment]
I receive this error now when trying to run run cmake: 

CMake Warning (dev) at cmake/FindMATLAB.cmake:190 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  CMakeLists.txt:11 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at cmake/FindEMBREE.cmake:47 (message):
  could NOT find EMBREE
Call Stack (most recent call first):
  CMakeLists.txt:14 (find_package)

**Comment by danielepanozzo** [comment]
It should be fixed now. It was a bug in the cmake file that was enforcing embree as a requirement for all the tutorials instead of only the ones that need it.

**Comment by bradrothenberg** [comment]
Thanks!




*BRADLEY ROTHENBERG*

Bradley Rothenberg | co-founder |  381-383 Broadway, #203 NY, NY 10013

t. 917.710.1396   e. *brad@bradleyrothenberg.com
<brad@bradleyrothenberg.com>*  w. *bradleyrothenberg.com
<http://bradleyrothenberg.com>*



*twitter*   <https://twitter.com/brad_rothenberg>l  *instagram
<http://instagram.com/bradleyrothenberg>  *l  *facebook*
<https://www.facebook.com/bradley.rothenberg>
