### ISSUE TITLE
Forces, vertex displacement, and arap

### ISSUE THREAD

**Issue by simonncollins** [libigl/libigl#430]
i am trying to displace specific vertices and then have arap treat that displacement as a constraint while it solves the resulting deformation across the mesh. I want to have up to 2 such displacement constraints active at any one time, and those constraints might be changing between every solve.

I dont know how to actually do this, so im taking the approach of generating a force at a point that would be sufficient to displace those specific vertices to where i need as a form of constraint on those vertices - and then solving with arap.

I have setup arap with:

```
arap_data.with_dynamics = true;
arap_data.max_iter = 100;
arap_data.energy = igl::ARAP_ENERGY_TYPE_DEFAULT;
arap_data.h = 0.01;
arap_data.ym = 0.0001;
arap_precomputation(low.V, low.F, 3, Eigen::VectorXi(), arap_data);
```

I have an origin and a direction/magnitude for the force i want to apply:

```
Eigen::MatrixXd origin_matrix; // 1 row, 3 cols (single point)
double force[3] = { 0, 1, 0 };
```

I can build a forces matrix by having a point that corresponds with each vertex (i got the impression i need to do this from the examples - probably my confusion), futher I construct a mass matrix for applying the forces later:

```
Eigen::MatrixXd arap_forces = Eigen::MatrixXd::Zero(low.V.rows(), low.V.cols());
Eigen::SparseMatrix<double> arap_masses;
igl::massmatrix(low.V, low.F, igl::MASSMATRIX_TYPE_DEFAULT, arap_masses);

```

Looking at the examples, I got the impression I need to find the closest vertex in low and apply the force there (this doesnt sound right to me, but i dont really understand how the arap implementation works), so I attempt to find the closest point to the aforementioned point force:

```
Eigen::VectorXd squared_distances;
Eigen::VectorXi indices_by_distance;
Eigen::MatrixXd points_by_distance;
igl::point_mesh_squared_distance(origin_matrix, low.U, low.F, squared_distances, indices_by_distance, points_by_distance);
```

From indices_by_distance I can apply the force at the corresponding point in the force matrix (i dont think im doing this correctly):

```
int row = indices_by_distance(0);
arap_forces(row, 0) += force[0];
arap_forces(row, 1) += force[1];
arap_forces(row, 2) += force[2];
```

Next I can update the aggregate forces for arap:

`arap_data.f_ext = arap_masses * arap_forces;`

Then i can update arap with:

`arap_solve(Eigen::MatrixXd(0, 3), arap_data, low.U);`

And finally i reset all forces/velocities of arap, because i am currently just testing with the instantaneous effect of those displacements, and the forces will be reapplied before the next solve if the constraints are meant to still be active.

```
arap_forces.setZero();
arap_data.vel.setZero();
arap_data.f_ext = arap_masses * arap_forces;
```

Ok so I'm pretty sure ive misunderstood how to accomplish my goal, i do see deformations occurring, however they are happening at the wrong locations and with the wrong force directions, which i suspect is because i am not finding the actual closest vertex - or worse, because the overall approach is just flawed.

**Comment by alecjacobson** [comment]
This should be better documented or removed. For now, I'm not going to personally work on fixing.
