### ISSUE TITLE
MeshBoolean CGAL Problem

### ISSUE THREAD

**Issue by yjm12321** [libigl/libigl#432]
Hi , I use the #include <igl/copyleft/cgal/mesh_boolean.h> file to do the boolean operation, I add boost header file and cgal head file, the boost version is 1.56.0 and cgal version is 4.4, the eigen version is 2.8.5. However when I compile it, error occurs with 'dummy_precision' : is not a member of 'Eigen::NumTraits<CGAL::Lazy_exact_nt<CGAL::Gmpq>>', I think it's because the version of boost, cgal and eigen is not matching. 

Do you have any idea? Thanks.

**Comment by alecjacobson** [comment]
We've only tested "standard" combinations of these libraries. It might help
to whittle down the example until you have the smallest program that still
causes this error (might not actually involve libigl at that point).
