### ISSUE TITLE
Can libigl read tetgen IO files(*.poly, *.node,*.ele,*face,...) and then mesh, plot and render them according to Boundary makers or regional attributes? 

### ISSUE THREAD

**Issue by luogyong** [libigl/libigl#433]
Can libigl read tetgen IO files(*.poly, *.node,*.ele,*face,...) and then mesh,  plot and render them according to boundary makers or regional attributes? 
Thanks.

**Comment by alecjacobson** [comment]
short answer: no.

Long answer: you could code this using a lot of features in libigl like plotting meshes with per-vertex/per-face colors and with some of our file IOs. These are very simple file formats so coding readers yourself should not be hard. We're always happy to receive pull requests.
