### ISSUE TITLE
Unable to compile tutorials (VS15), "module machine type 'x64' conflicts with target machine type 'X86'"

### ISSUE THREAD

**Issue by Linchy** [libigl/libigl#435]
Steps I took:

```
cd tutorial
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ../
```

I then opened in Visual Studio 2015 (I'm on Windows 10), and switched all configurations from Win32 to x64. On building I'm then presented with these errors:

![image](https://cloud.githubusercontent.com/assets/1840551/21592463/8bbfe02e-d105-11e6-9d24-e4f940a32abc.png)

**Comment by danielepanozzo** [comment]
Can you try to select x64 as the preferred compiler directly in cmake? I don't think you can switch from 32 to 64 directly in VS. If you use the cmake GUI, it will ask you to select the compiler before you generate the project.

**Comment by Linchy** [comment]
Sorry for the late reply; yes that fixed the problem thank you.
