### ISSUE TITLE
Transposed output for `igl::lscm`

### ISSUE THREAD

**Issue by jiangzhongshi** [libigl/libigl#437]
From the function `igl::lscm` for _least squared conformal mapping_ in file pair `lscm.h` and `lscm.cpp`, the output u-v coordinate is transposed.

Minimum demo case: 

In tutorial **Example 502**. by adding the following after calling igl::lscm
`std::cout<<V_uv.row(b(0))<<std::endl<<V_uv.row(b(1))<<std::endl;`

The output would be 

> 0 0
> 0 1

rather than what was assigned to `bc<<0,0,1,0;`

**Comment by alecjacobson** [comment]
I feel like we've changed this code back and forth with respect to the sign. Rather than changing it again. I'd like to set up an unequivocal unit test . You're welcome to post a proposal as a pull request there: https://github.com/libigl/libigl-unit-tests
