### ISSUE TITLE
Bug in min_quad_with_fixed.cpp

### ISSUE THREAD

**Issue by jiangzhongshi** [libigl/libigl#438]
At line 97-104 of the file `include/igl/min_quad_with_fixed.cpp`, the edge case of `unknown` or `lagrange` being empty is fixed as follows.

`if(data.unknown.size() > 0)
  {
    data.unknown_lagrange << data.unknown;
  }
  if(data.lagrange.size() > 0)
  {
    data.unknown_lagrange << data.lagrange;
  }`

However, such fix would result in `data.unknown_lagrange` = `data.lagrange` if neither of them is empty, which is not the expected behavior. In fact, something as below will fix this.
`
if(data.unknown.size() == 0)
   {
      data.unknown_lagrange << data.lagrange;
   }
   else if(data.lagrange.size() == 0)
   {
     data.unknown_lagrange << data.unknown;
   }
   else
   {
     data.unknown_lagrange << data.unknown, data.lagrange;
   }
`

**Comment by alecjacobson** [comment]
I don't follow this. Could you post a minimal example where this fails?

**Comment by jiangzhongshi** [comment]
I was trying to say. `<<` is assign rather than append. 

Whenever `data.unknown.size() > 0` and `data.langrange.size() > 0 ` are both satisfied, i.e. equality constraint is not empty, and unknown number is not zero,
the second assignment fail at runtime.

I can write a concrete example later.

**Comment by alecjacobson** [comment]
Oh, I see. That's indeed an Eigen Gotcha. It'd probably be better to just
avoid `<<` altogether.

**Comment by jiangzhongshi** [comment]
This makes a working example.

        using namespace Eigen;
        MatrixXd A(2, 2), Aeq(2, 2);
        VectorXi b;
        A << 1, 0, 0, 1;
        Aeq = A;
        SparseMatrix<double> sA = A.sparseView(), sAeq = Aeq.sparseView();
 
        igl::min_quad_with_fixed_data<double> data;
        igl::min_quad_with_fixed_precompute(sA, b, sAeq, true, data);

And it will complain `Assertion failed: ((m_row+m_currentBlockRows) == m_xpr.rows() && m_col == m_xpr.cols() && "Too few coefficients passed to comma initializer (operator<<)"), function ~CommaInitializer`

In this case, maybe a fix with block operation `segment()` looks better.
