### ISSUE TITLE
error R6010

### ISSUE THREAD

**Issue by bradrothenberg** [libigl/libigl#44]
I'm getting an abort() called on the tutorials now since the latest github commits...

I'm using VS2013, win 7, compiling x64. it crashes in debug & release.

**Comment by bradrothenberg** [comment]
assert(simplex_size == 3 || simplex_size == 4);

is being called in line 33 of cotmatrix.cpp

**Comment by alecjacobson** [comment]
My guess is that it's not reading in the input mesh correctly. Can you
easily check the input routine? Or at least the size of the arguments to
cotmatrix?

On Sat, Mar 7, 2015 at 2:12 AM, Bradley Rothenberg <notifications@github.com

**Comment by bradrothenberg** [comment]
Will do, I'll let you know

**Comment by bradrothenberg** [comment]
figured out the issue -- the shared folder was not linking correctly -- fixed that & the tutoriols run well.

thanks!
