### ISSUE TITLE
igl::vector_area_matrix() does not compile with Eigen 3.3.1

### ISSUE THREAD

**Issue by youngtaekoh** [libigl/libigl#441]
It seems like that Eigen 3.3.1 has a bug on SparseMatrix computation. So, following code does not compile:
```c++
Eigen::SparseMatrix<double> M1(3, 3), M2(3,3), M3;
M3 = (M1 + M2) / 2;
```
It causes problem compiling igl::vector_area_matrix(). So workaround is simply replace
```c++
A = (aux + auxT)/2;
```
with
```c++
A = (aux + auxT) * 0.5;
```
in vector_area_matrix.cpp:50 in commit 9c5f6eaf5eeb0c7b1859c839eaab34a336fef4ad

**Comment by yasushi-saito** [comment]
I'm having the same problem. Can we get this fixed? I can create a pull request.

**Comment by alecjacobson** [comment]
To date we don't recommend using libigl with Eigen 3.3.1. Because of this bug and other backwards compatibility problems, we're waiting for fixes.
