### ISSUE TITLE
Possible to get the igl::lscm output UV coordinates in world space?

### ISSUE THREAD

**Issue by Linchy** [libigl/libigl#444]
After running `igl::lscm`, I get an output of UV values that seem to range from [-1,1]. Therefore it is not possible to tell from this how much space the UV should take up on the whole UV map (which contains other unwraps) without user involvement.

Is it possible to get the result back in coordinates that haven't been resized into the [-1,1] range yet? I could then take the min and max coords to create a rectangle, which could then be used to allocate an appropriate space on the final UV map.

**Comment by alecjacobson** [comment]
`igl::lscm` doesn't force the output to be in the [-1,1] range. The scale depends on the constraints you pass in via `bc`.

Or I'm misunderstanding the issue.

**Comment by Linchy** [comment]
Sorry for the late reply @alecjacobson, but could you show me how to not have it apply any scale at all? For example if I passed in a square, the unwrapped result would be a square of the same size, and the tex coords would reflect that.

I'd look at documentation or something but can't find any on LSCM and the `bc` value.

**Comment by Linchy** [comment]
@alecjacobson what I currently have:

```
extern "C"
{	
	__declspec(dllexport) void CalculateUVCoordinates(float* vertices, int vertCount, int* indices, int faceCount, float* out_UVs)
	{
		//try
		{
			// convert vertices
			Eigen::MatrixXd V;
			V.resize(vertCount, 3);
			for (int i = 0; i < vertCount; i++)
			{
				int j = i * 3;
				V(i, 0) = vertices[j];
				V(i, 1) = vertices[j + 1];
				V(i, 2) = vertices[j + 2];
			}

			// convert faces
			Eigen::MatrixXi F;
			F.resize(faceCount, 3);
			for (int i = 0; i < faceCount; i++)
			{
				int j = i * 3;
				F(i, 0) = indices[j];
				F(i, 1) = indices[j + 1];
				F(i, 2) = indices[j + 2];
			}

			// Fix two points on the boundary
			VectorXi bnd;
			igl::boundary_loop(F, bnd);
			if (bnd.size() <= 1)
				return;

			VectorXi b(2, 1);
			b(0) = bnd(0);
			b(1) = bnd(round(bnd.size() / 2));

			MatrixXd bc(2, 2);
			bc << 0, 0, 1, 0;

			// LSCM parametrization
			Eigen::MatrixXd V_uv;
			igl::lscm(V, F, b, bc, V_uv);

			if (V_uv.rows() != vertCount)
				return;
			
			// convert the UV matrix back to an array
			//out_UVs = new float[vertCount * 2];
			for (int i = 0; i < vertCount; i++)
			{
				int j = i * 2;
				out_UVs[j + 0] = V_uv(i, 0);
				out_UVs[j + 1] = V_uv(i, 1);
			}
		}
		//catch (exception& e)
		{
			//*out_err = e.what();
		}
	}
}
```

**Comment by alecjacobson** [comment]
Probably to just rescale after the fact.
