### ISSUE TITLE
Viewer shows empty screen randomly

### ISSUE THREAD

**Issue by Javier12** [libigl/libigl#445]
Hi,

I've seen that the viewer shows up 50% of the time empty when loading the exact same mesh.
However by commenting the line 964 on Viewer.cpp:

`core.align_camera_center(data.V,data.F);`

The screen shows up just fine always.

**Comment by alecjacobson** [comment]
I think this was fixed in efcd9dddd51d5c841ec08ff2c3ec005cb5d0cf8c

Could you confirm?

**Comment by Javier12** [comment]
Yes, it's fixed.
