### ISSUE TITLE
NRosyField

### ISSUE THREAD

**Issue by csv610** [libigl/libigl#447]
Hello,

After debugging the code, I realized segmentation issues are related to CoMISO, gmn and Eigen.
If things are working for you on Ubuntu, please let me know which versions ( and any specific things)
that  I should take care to make LibIGL work.

csv

2949	malloc.c: No such file or directory.
(gdb) where
#0  __GI___libc_free (mem=0xea0) at malloc.c:2949
#1  0x000000000042f054 in Eigen::SparseMatrix<double, 0, int>::~SparseMatrix() ()
#2  0x0000000000451623 in Eigen::SparseMatrix<double, 0, int>& Eigen::SparseMatrix<double, 0, int>::operator=<Eigen::SparseMatrix<double, 1, int> >(Eigen::SparseMatrixBase<Eigen::SparseMatrix<double, 1, int> > const&) ()
#3  0x00007ffff726e79e in void Eigen::internal::set_from_triplets<__gnu_cxx::__normal_iterator<Eigen::Triplet<double, int>*, std::vector<Eigen::Triplet<double, int>, std::allocator<Eigen::Triplet<double, int> > > >, Eigen::SparseMatrix<double, 0, int>, Eigen::internal::scalar_sum_op<double> >(__gnu_cxx::__normal_iterator<Eigen::Triplet<double, int>*, std::vector<Eigen::Triplet<double, int>, std::allocator<Eigen::Triplet<double, int> > > > const&, __gnu_cxx::__normal_iterator<Eigen::Triplet<double, int>*, std::vector<Eigen::Triplet<double, int>, std::allocator<Eigen::Triplet<double, int> > > > const&, Eigen::SparseMatrix<double, 0, int>&, Eigen::internal::scalar_sum_op<double>) () from /home/csverma/Disk/Software/MathLibs/CoMISo/lib/libCoMISo.so
#4  0x00007ffff726ef66 in void COMISO_EIGEN::gmm_to_eigen<gmm::csc_matrix<double, 0>, Eigen::SparseMatrix<double, 0, int> >(gmm::csc_matrix<double, 0> const&, Eigen::SparseMatrix<double, 0, int>&) ()
   from /home/csverma/Disk/Software/MathLibs/CoMISo/lib/libCoMISo.so
#5  0x00007ffff7271e87 in bool COMISO::EigenLDLTSolver::calc_system_gmm<gmm::csc_matrix<double, 0> >(gmm::csc_matrix<double, 0> const&) () from /home/csverma/Disk/Software/MathLibs/CoMISo/lib/libCoMISo.so
#6  0x00007ffff7264d0e in COMISO::MISolver::solve_multiple_rounding(gmm::csc_matrix<double, 0>&, std::vector<double, std::allocator<double> >&, std::vector<double, std::allocator<double> >&, std::vector<int, std::allocator<int> >&) () from /home/csverma/Disk/Software/MathLibs/CoMISo/lib/libCoMISo.so
#7  0x00007ffff7289610 in void COMISO::ConstrainedSolver::solve<gmm::row_matrix<gmm::wsvector<double> >, gmm::col_matrix<gmm::wsvector<double> >, std::vector<double, std::allocator<double> >, std::vector<int, std::allocator<int> > >(gmm::row_matrix<gmm::wsvector<double> >&, gmm::col_matrix<gmm::wsvector<double> >&, std::vector<double, std::allocator<double> >&, std::vector<double, std::allocator<double> >&, std::vector<int, std::allocator<int> >&, double, bool, bool) () from /home/csverma/Disk/Software/MathLibs/CoMISo/lib/libCoMISo.so
#8  0x000000000041bead in igl::copyleft::comiso::NRosyField::solveRoundings() ()
#9  0x000000000041c1e4 in igl::copyleft::comiso::NRosyField::solve(int) ()
#10 0x000000000041f890 in igl::copyleft::comiso::nrosy(Eigen::Matrix<double, -1, -1, 0, -1, -1> const&, Eigen::Matrix<int, -1, -1, 0, -1, -1> const&, Eigen::Matrix<int, -1, 1, 0, -1, 1> const&, Eigen::Matrix<double, -1, -1, 0, -1, -1> const&, Eigen::Matrix<int, -1, 1, 0, -1, 1> const&, Eigen::Matrix<double, -1, 1, 0, -1, 1> const&, Eigen::Matrix<double, -1, -1, 0, -1, -1> const&, int, double, Eigen::Matrix<double, -1, -1, 0, -1, -1>&, Eigen::Matrix<double, -1, 1, 0, -1, 1>&) ()
#11 0x000000000040cb29 in key_down(igl::viewer::Viewer&, unsigned char, int) ()

**Comment by alecjacobson** [comment]
from this, I can't tell if this is an Eigen issue, a Comiso issue or a libigl issue. Perhaps we can verify whether the input passed to Comiso is valid. In which case, we can declare this a Comiso issue.

I would stay away from Eigen 3.3.* for now. And be sure that you're not mixing different Eigen versions during compilation.
