### ISSUE TITLE
python binding tutorial problem, on Eigen matrix.

### ISSUE THREAD

**Issue by jdily** [libigl/libigl#449]
Hi
I am trying to run the tutorial 502 and 503 from compiled python binding.
But encouter error as followed:
```
File "503_ARAPParam.py", line 46, in <module> 
igl.boundary_loop(F, bnd)
MemoryError: std::bad_alloc
```
I ran the same tutorial on C++ side, and it works pretty ok.

thank you.

**Comment by jdily** [comment]
I found out that on my machine, not only the function 
`
boundary_loop
`
will lead to this problem,  another function, e.g. 
` boundary_facets` also has the same problem.

And I did some experiment, and I think the common things they did, is they need to write results back to one of the function argument : `Eigen::MatrixXi& xx`..

I am wondering if it is relevant to the Eigen version on my machine?

**Comment by s-koch** [comment]
Hi,
can you check if it is working for you with the newest version of the repository?

**Comment by jdily** [comment]
Hi, I think your latest fix solve my problem, it didn't happen again! 
thx so much! :)
