### ISSUE TITLE
Viewer trackball behavior

### ISSUE THREAD

**Issue by avaxman** [libigl/libigl#452]
Has anything changed with the trackball in any recent editions? it's very hard to achieve certain viewing angles, and sometimes not really possible.

**Comment by alecjacobson** [comment]
There are two mouse interfaces available. You can switch between standard arc ball and maya-style using the [,] keys

see the command line output when you launch the viewer.

**Comment by avaxman** [comment]
right, I read "[,]" as "the "," key". I had to go into the viewer code to figure that mistake out... perhaps spell out "] and [".
