### ISSUE TITLE
Triangle markers wrong usage

### ISSUE THREAD

**Issue by russelmann** [libigl/libigl#453]
In triangulate.cpp line 97:
  string full_flags = flags + "pz" + (EM.size() || VM.size() ? "B" : "");
should be:
  string full_flags = flags + "pz" + (EM.size() || VM.size() ? "" : "B");
since the "B" flag suppresses marker output.

**Comment by alecjacobson** [comment]
Fixed in 93204099c32b7273f98964262ab36493ece1f8ac
