### ISSUE TITLE
Tutorial Compilation Issue: Menu doesn't show

### ISSUE THREAD

**Issue by ruoqingsun** [libigl/libigl#455]
I am currently compiling the tutorials on Windows + Visual Studio 2015.

CMake is applied to configuration and generation. When I set LIBIGL_WITH_NANOGUI to be true, an error would show up. Otherwise, I can compile and run the tutorials smoothly without any menu showing up.

![image](https://cloud.githubusercontent.com/assets/4344440/22404822/edfe640c-e638-11e6-8618-052a67410150.png)
![image](https://cloud.githubusercontent.com/assets/4344440/22404824/071bfd46-e639-11e6-9e7d-3ba372dc55a8.png)

Any suggestion is welcome. Thanks

**Comment by danielepanozzo** [comment]
Could you please report what is exactly the error that cmake produces? I cannot reproduce it on my machine.

**Comment by ruoqingsun** [comment]
CMAKE_C_COMPILER: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
CMAKE_CXX_COMPILER: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
Could NOT find Matlab (missing:  Matlab_MEX_EXTENSION) (found version "8.6")
Using Win32 for window creation
Using Win32 for window creation
CMake Error at E:/Documents/GitHub/libigl/external/nanogui/ext/glfw/src/CMakeLists.txt:56 (add_library):
  add_library cannot create target "glfw_objects" because another target with
  the same name already exists.  The existing target is created in source
  directory "E:/Documents/GitHub/libigl/external/nanogui/ext/glfw/src".  See
  documentation for policy CMP0002 for more details.


CMake Error at E:/Documents/GitHub/libigl/external/nanogui/ext/glfw/src/CMakeLists.txt:60 (add_library):
  add_library cannot create target "glfw" because another target with the
  same name already exists.  The existing target is a static library created
  in source directory
  "E:/Documents/GitHub/libigl/external/nanogui/ext/glfw/src".  See
  documentation for policy CMP0002 for more details.


-- libigl includes:
	 E:/Documents/GitHub/libigl/shared/cmake/../../external/nanogui/ext/eigen
	 E:/Documents/GitHub/libigl/shared/cmake/../../include
	 E:/Documents/GitHub/libigl/shared/cmake/../../external/CoMISo/ext/gmm-4.2/include
	 E:/Documents/GitHub/libigl/shared/cmake/../../external/CoMISo/../
	 E:/Documents/GitHub/libigl/shared/cmake/../../external/embree/include
	 E:/Documents/GitHub/libigl/shared/cmake/../../external/lim
	 E:/Documents/GitHub/libigl/shared/cmake/../../external/nanogui/ext/glew/include
	 E:/Documents/GitHub/libigl/shared/cmake/../../external/nanogui/ext/glfw/include
	 E:/Documents/GitHub/libigl/shared/cmake/../../external/nanogui/ext/glew/include
	 E:/Documents/GitHub/libigl/shared/cmake/../../external/nanogui/include
	 E:/Documents/GitHub/libigl/shared/cmake/../../external/nanogui/ext/nanovg/src
	 E:/Documents/GitHub/libigl/shared/cmake/../../external/nanogui/ext/glfw/include
	 E:/Documents/GitHub/libigl/shared/cmake/../../external/nanogui/ext/glew/include
	 E:/Documents/GitHub/libigl/shared/cmake/../../external/stb_image
	 E:/Documents/GitHub/libigl/shared/cmake/../../external/tetgen
	 E:/Documents/GitHub/libigl/shared/cmake/../../external/triangle
	 E:/Documents/GitHub/libigl/shared/cmake/../../external/tinyxml2
-- libigl libraries:
	 igl_xml
	 igl_triangle
	 igl_tetgen
	 igl_png
	 igl_viewer
	 igl_opengl_glfw
	 igl_opengl2
	 igl_opengl
	 igl_lim
	 igl_embree
	 igl_comiso
	 igl
-- libigl extra libraries:
	 CoMISo
	 E:/Documents/GitHub/libigl/shared/cmake/../../external/CoMISo/ext/OpenBLAS-v0.2.14-Win64-int64/lib/libopenblas.dll.a.lib
	 embree
	 lim
	 opengl32
	 glew
	 glfw
	 nanogui
	 opengl32
	 stb_image
	 tetgen
	 triangle
	 tinyxml2
-- libigl definitions:
	 -DIGL_STATIC_LIBRARY
	 -DINCLUDE_TEMPLATES
	 -DENABLE_STATIC_LIB
	 -DIGL_NO_MOSEK
	 -DIGL_VIEWER_WITH_NANOGUI
Configuring incomplete, errors occurred!
See also "E:/Documents/GitHub/libigl/tutorial/build_vs2015_x64/CMakeFiles/CMakeOutput.log".
See also "E:/Documents/GitHub/libigl/tutorial/build_vs2015_x64/CMakeFiles/CMakeError.log".

**Comment by jiangzhongshi** [comment]
I have encountered the same issue after the lastest pull. When set `LIBIGL_WITH_NANOGUI` to be false, cmake produce correct results.

When `LIBIGL_WITH_NANOGUI` = true. Same error arises.
`add_library cannot create target "glfw_objects" because another target with
  the same name already exists.  The existing target is created in source
  directory`
and
` add_library cannot create target "glfw" because another target with the
  same name already exists.  The existing target is a static library created
  in source directory` 


I think it may has something to do with the recent nanogui update. But I cannot really track it down.

**Comment by alecjacobson** [comment]
From https://github.com/libigl/libigl-example-project/issues/6#issuecomment-276081643:

> I wrote: Nanogui's cmake is confusing the libigl cmake and glfw is being added twice.
> 
> I have not fixed this and might suggest moving all the nanogui stuff to a
truly separate dependency (separate folder from igl/viewer) before sorting
this out.

**Comment by danielepanozzo** [comment]
I already fixed this problem a few months ago. I will take a look again, probably some other changes in the build system broke it. The current solution is the inclusion of glfw linking list only if the nanogui stuff is disabled. 

A better long term solution would be to move the nanogui code as a plugin for the viewer, but this might (will) break existing code that uses it and I prefer to postpone it to a later time together with these additional major viewer changes:
1. Removal of unnecessary triple buffering of the visualized data
2. Proper handling of thick lines and points (the current solution behaves differently on different cards/OS)
3. Ensure that render and render_buffer method produce pixel identical results (which is unfortunately really difficult between different platforms and opengl drivers)

**Comment by danielepanozzo** [comment]
@jpanetta just submitted a fix. @jiangzhongshi Could you please confirm that it solves it on your end?

**Comment by jiangzhongshi** [comment]
@danielepanozzo Yes it's fixed and working well. Thanks.
