### ISSUE TITLE
Precision Issues with Mesh Boolean

### ISSUE THREAD

**Issue by twodee** [libigl/libigl#457]
I've been using the mesh boolean operations and have run into a precision issue with subtraction. This code recreates the problem in as contained an example as I can muster. It generates a big rectangular prism and subtracts away a smaller rectangular prism to create a rectangular dish:

````
#define IGL_NO_CORK
#include <igl/copyleft/cgal/mesh_boolean.h>

int main(int argc, char **argv) {
  Eigen::MatrixXd big_positions(10, 3);
  big_positions <<
    -6.010407, 0, 6.010407,
    -6.010407, 2, 6.010407,
    -6.010407, 0, -6.010406,
    -6.010407, 2, -6.010406,
    0, 0, 0,
    0, 2, 0,
    6.010406, 0, -6.010407,
    6.010407, 0, 6.010407,
    6.010406, 2, -6.010407,
    6.010407, 2, 6.010407;

  Eigen::MatrixXd small_positions(10, 3);
  small_positions <<
    -4.949748, 1, -4.949747,
    -4.949747, 1, 4.949747,
    -4.949748, 3.5, -4.949747,
    -4.949747, 3.5, 4.949747,
    0, 1, 0,
    0, 3.5, 0,
    4.949747, 1, -4.949747,
    4.949747, 1, 4.949747,
    4.949747, 3.5, -4.949747,
    4.949747, 3.5, 4.949747;

  Eigen::MatrixXi big_faces(16, 3);
  big_faces <<
    7, 6, 8,
    7, 8, 9,
    6, 2, 3,
    6, 3, 8,
    2, 0, 1,
    2, 1, 3,
    0, 7, 9,
    0, 9, 1,
    4, 6, 7,
    4, 2, 6,
    4, 0, 2,
    4, 7, 0,
    5, 9, 8,
    5, 8, 3,
    5, 3, 1,
    5, 1, 9;

  Eigen::MatrixXi small_faces(16, 3);
  small_faces <<
    7, 6, 8,
    7, 8, 9,
    6, 0, 2,
    6, 2, 8,
    0, 1, 3,
    0, 3, 2,
    1, 7, 9,
    1, 9, 3,
    4, 6, 7,
    4, 0, 6,
    4, 1, 0,
    4, 7, 1,
    5, 9, 8,
    5, 8, 2,
    5, 2, 3,
    5, 3, 9;

  Eigen::MatrixXd difference_positions;
  Eigen::MatrixXi difference_faces;
  Eigen::VectorXi J;

  igl::copyleft::cgal::mesh_boolean(big_positions, big_faces, small_positions, small_faces, igl::MESH_BOOLEAN_TYPE_MINUS, difference_positions, difference_faces, J);
  igl::writeOBJ("diff.obj", difference_positions, difference_faces);
  
  return 0;
}
````

If I shave a digit of precision off the vertex positions (easily done with `%s/\(\d\{5}\)\@<=\d//gc` in Vim!), the resulting model has 22 vertices and is nicely watertight. However, if I leave the last digit in, I get a model with 24 vertices. The extra two are nearly coincident with two of the original 22. These extra two result in NaNs when I compute normals.

Is any there any facility in libigl to account for the precision of boolean operations?

**Comment by alecjacobson** [comment]
Basically, the output of mesh_boolean are coordinates in the space of rational numbers rather than simply floating point numbers. These rational numbers can represent triangles that are potentially much smaller than the floating point grid. Thus when they're naively _cast to float_ (think "rounded" or "snapped" to float) the triangles may become degenerate and normal computation will freak out.

@qnzhou has a fairly robust heuristic for doing the "casting to float" in a more intelligent way. We have been meaning to integrate this into libigl.
