### ISSUE TITLE
VS 2012 viewer build (Windows 8.1)

### ISSUE THREAD

**Issue by cap257zero** [libigl/libigl#46]
First off, running cmake on individual tutorial examples works for me on my machine, for examples including a viewer (yay!). This issue relates to trying to use the libigl viewer functionality in a separate project.

Build is successful when I include the header igl/viewer/Viewer.h but upon declaring a viewer

igl::Viewer viewer;

I receive a long list of "unresolved external" errors (copied at the bottom of this post). Some relevant Project Properties are

* Additional Include Directories:
  * external/AntTweakBar/include
  * external/AntTweakBar/src
  * external/glfw/include
  * external/glfw/src
  * external/glew/include
  * external/glew/src
  * libigl/include
  * eigen-eigen-10219c95fe65
* Additional Library Directories:
  * external/AntTweakBar/lib
  * external/glfw/lib/x64
* Additional Dependencies:
  * AntTweakBar64.lib
  * glfw3.lib

Pretty clearly, the bottom group of errors is related to glew, and indeed the tutorial examples that cmake built successfully on my machine (including working viewer) added glew.c to the project source code. There seem to be precompiled binaries for AntTweakBar and glfw but not for glew -- so I guess the project must build glew somehow? I'm not sure how to do that.

Thanks a bunch. Here are the errors:

1>main.obj : error LNK2019: unresolved external symbol __imp__glDepthMask@4 referenced in function "public: virtual void __thiscall igl::TextRenderer::EndDraw(void)" (?EndDraw@TextRenderer@igl@@UAEXXZ)
1>main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual int __thiscall CTwGraphOpenGLCore::Init(void)" (__imp_?Init@CTwGraphOpenGLCore@@UAEHXZ) referenced in function "public: virtual int __thiscall igl::TextRenderer::Init(void)" (?Init@TextRenderer@igl@@UAEHXZ)
1>main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual int __thiscall CTwGraphOpenGLCore::Shut(void)" (__imp_?Shut@CTwGraphOpenGLCore@@UAEHXZ) referenced in function "public: virtual int __thiscall igl::TextRenderer::Shut(void)" (?Shut@TextRenderer@igl@@UAEHXZ)
1>main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual void __thiscall CTwGraphOpenGLCore::EndDraw(void)" (__imp_?EndDraw@CTwGraphOpenGLCore@@UAEXXZ) referenced in function "public: virtual void __thiscall igl::TextRenderer::EndDraw(void)" (?EndDraw@TextRenderer@igl@@UAEXXZ)
1>main.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::BeginDraw(int,int)" (?BeginDraw@CTwGraphOpenGLCore@@UAEXHH@Z)
1>main.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::BuildText(void *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const *,unsigned int *,unsigned int *,int,struct CTexFont const *,int,int)" (?BuildText@CTwGraphOpenGLCore@@UAEXPAXPBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PAI2HPBUCTexFont@@HH@Z)
1>main.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::ChangeViewport(int,int,int,int,int,int)" (?ChangeViewport@CTwGraphOpenGLCore@@UAEXHHHHHH@Z)
1>main.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::DeleteTextObj(void *)" (?DeleteTextObj@CTwGraphOpenGLCore@@UAEXPAX@Z)
1>main.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::DrawLine(int,int,int,int,unsigned int,unsigned int,bool)" (?DrawLine@CTwGraphOpenGLCore@@UAEXHHHHII_N@Z)
1>main.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::DrawLine(int,int,int,int,unsigned int,bool)" (?DrawLine@CTwGraphOpenGLCore@@UAEXHHHHI_N@Z)
1>main.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::DrawRect(int,int,int,int,unsigned int)" (?DrawRect@CTwGraphOpenGLCore@@UAEXHHHHI@Z)
1>main.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::DrawRect(int,int,int,int,unsigned int,unsigned int,unsigned int,unsigned int)" (?DrawRect@CTwGraphOpenGLCore@@UAEXHHHHIIII@Z)
1>main.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::DrawText(void *,int,int,unsigned int,unsigned int)" (?DrawText@CTwGraphOpenGLCore@@UAEXPAXHHII@Z)
1>main.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::DrawTriangles(int,int *,unsigned int *,enum ITwGraph::Cull)" (?DrawTriangles@CTwGraphOpenGLCore@@UAEXHPAHPAIW4Cull@ITwGraph@@@Z)
1>main.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::EndDraw(void)" (?EndDraw@CTwGraphOpenGLCore@@UAEXXZ)
1>main.obj : error LNK2001: unresolved external symbol "public: virtual int __thiscall CTwGraphOpenGLCore::Init(void)" (?Init@CTwGraphOpenGLCore@@UAEHXZ)
1>main.obj : error LNK2001: unresolved external symbol "public: virtual bool __thiscall CTwGraphOpenGLCore::IsDrawing(void)" (?IsDrawing@CTwGraphOpenGLCore@@UAE_NXZ)
1>main.obj : error LNK2001: unresolved external symbol "public: virtual void * __thiscall CTwGraphOpenGLCore::NewTextObj(void)" (?NewTextObj@CTwGraphOpenGLCore@@UAEPAXXZ)
1>main.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::Restore(void)" (?Restore@CTwGraphOpenGLCore@@UAEXXZ)
1>main.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::RestoreViewport(void)" (?RestoreViewport@CTwGraphOpenGLCore@@UAEXXZ)
1>main.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::SetScissor(int,int,int,int)" (?SetScissor@CTwGraphOpenGLCore@@UAEXHHHH@Z)
1>main.obj : error LNK2001: unresolved external symbol "public: virtual int __thiscall CTwGraphOpenGLCore::Shut(void)" (?Shut@CTwGraphOpenGLCore@@UAEHXZ)
1>main.obj : error LNK2001: unresolved external symbol ___glewAttachShader
1>main.obj : error LNK2001: unresolved external symbol ___glewBindAttribLocation
1>main.obj : error LNK2001: unresolved external symbol ___glewCompileShader
1>main.obj : error LNK2001: unresolved external symbol ___glewCreateProgram
1>main.obj : error LNK2001: unresolved external symbol ___glewCreateShader
1>main.obj : error LNK2001: unresolved external symbol ___glewDeleteProgram
1>main.obj : error LNK2001: unresolved external symbol ___glewDeleteShader
1>main.obj : error LNK2001: unresolved external symbol ___glewGetProgramInfoLog
1>main.obj : error LNK2001: unresolved external symbol ___glewGetProgramiv
1>main.obj : error LNK2001: unresolved external symbol ___glewGetShaderInfoLog
1>main.obj : error LNK2001: unresolved external symbol ___glewGetShaderiv
1>main.obj : error LNK2001: unresolved external symbol ___glewGetUniformLocation
1>main.obj : error LNK2001: unresolved external symbol ___glewLinkProgram
1>main.obj : error LNK2001: unresolved external symbol ___glewShaderSource
1>main.obj : error LNK2001: unresolved external symbol ___glewBindFragDataLocation
1>main.obj : error LNK2001: unresolved external symbol ___glewProgramParameteri
1>C:\Users\Cap\Documents\Visual Studio 2012\Projects\libiglTemplate4\Debug\libiglTemplate4.exe : fatal error LNK1120: 38 unresolved externals

**Comment by RogersDoug** [comment]
I built glew from source: http://glew.sourceforge.net/

I link with glew32sd.lib and have no issues.

**Comment by cap257zero** [comment]
Thanks! I'll see what I can do with that and report back.

**Comment by cap257zero** [comment]
Ok I've got things working. If anyone's interested, I'm going to describe what worked for me in a comment on Issue #31 which I think is related.
