### ISSUE TITLE
Quadratic programming with box constraints can't work well for dense matrix Q?

### ISSUE THREAD

**Issue by wguo68** [libigl/libigl#460]
I want to do a PCA based fitting to find the coeffs of PCA model. The problem is:
    Ax-h=0 
with box constraints:  lx<=x<=ux. 
In my problem lx = -3 and ux = 3 for all coeff because I normalized all the PCA basis.
My code is : 
        Eigen::VectorXi b;
	Eigen::Matrix<T, Eigen::Dynamic, 1> B = -A.transpose()*h, bc, lx, ux, Beq, Bieq, coeffs;// Z;
	Eigen::SparseMatrix<T> Q = (A.transpose()*A).sparseView(), Aeq, Aieq;

	// Lower and upper bound
	lx = Eigen::Matrix<T, Eigen::Dynamic, 1>::Constant(n_shape_coefs,1, -3);
	ux = Eigen::Matrix<T, Eigen::Dynamic, 1>::Constant(n_shape_coefs,1, 3);

	igl::active_set_params as;
	as.max_iter = 8;
	igl::active_set(Q, B, b, bc, Aeq, Beq, Aieq, Bieq, lx, ux, as, coeffs);

In fact Q is a dense matrix and the number of unknown variables  is 40. The resulted coeffs are too bad (not in the between lx ans ux). What's the problem?
![pca](https://cloud.githubusercontent.com/assets/4994038/22723067/5bfe86c0-edf6-11e6-82c9-a19ec18ca875.jpg)

If I used the regularized linear least square,the result is good. The lsqlin of Matlab also works well.
Why box constrained linear least square of libigl failed here? Is it because the matrix Q is not sparse?

**Comment by alecjacobson** [comment]
The `igl::active_set` method was definitely intended for large sparse matrices. I don't see a reason why it should fail, though.

In the meantime, you could use `igl::copyleft::quadprog` that works pretty well for dense QP problems.
