### ISSUE TITLE
A tiny error in 710_SLIM_bin 

### ISSUE THREAD

**Issue by lorrain0407** [libigl/libigl#463]
Hi, 
There is a syntax error in read_triangle_mesh.cpp at line 124.
error C2059: syntax err:“::”

**Comment by wucm1994** [comment]
Hi,
It should be some problems with your compiler, it works fine with my project, compiling by MSVC 2015 Update 3.

**Comment by alecjacobson** [comment]
The line in question is:

          v.resize(std::min(v.size(),(size_t)3));

looks valid to me.
