### ISSUE TITLE
Issue with global parametrization (igl::miq)

### ISSUE THREAD

**Issue by RogersDoug** [libigl/libigl#47]
Another issues has come up with parameterization.

Here are screenshots:
https://dl.dropboxusercontent.com/u/85781814/Planck.jpg
https://dl.dropboxusercontent.com/u/85781814/Planck2.jpg

the code
https://dl.dropboxusercontent.com/u/85781814/flow.cpp

the model is fairly dense and has nothing unusual in that area:
https://dl.dropboxusercontent.com/u/85781814/max_planck.zip

The artifacts are on the back of the neck.  The rest of the model looks correct.

**Comment by danielepanozzo** [comment]
Mmm you are doing only one iteration (iter = 1): this is probably not be sufficient to get rid of the foldovers that are happening in the regions where you see the artefacts. Could you try to set iter = 10 or iter = 50? I think this will fix your problem. (Note that in the original tutorial the algorithm was doing 5 iterations, and you commented out that line in your code :) )

**Comment by RogersDoug** [comment]
Setting the iteration helped, but even at 100, there is still distortion

https://dl.dropboxusercontent.com/u/85781814/planck3.jpg

https://dl.dropboxusercontent.com/u/85781814/planck4.jpg

**Comment by danielepanozzo** [comment]
This is unfortunately the expected behaviour, the MIQ parametrization tends to concentrate the distortion around singularities.
