### ISSUE TITLE
Nanogui required to show labels

### ISSUE THREAD

**Issue by Javier12** [libigl/libigl#471]
I'm not sure if this is a bug, or a documentation issue.
Compiling the example 105 will not show the string labels unless LIBIGL_WITH_NANOGUI is defined.

**Comment by alecjacobson** [comment]
I think only nanovg should be required for this. The viewer dependencies are a bit of a mess right now. The intention is to separate nanovg- and nanogui- dependent code and move the viewer to the correct dependency location `igl/opengl/glfw/`. Hopefully this issue can be more clearly addressed after that change.

**Comment by aPToul** [comment]
Dear @Javier12 I was wondering how you corrected this issue. Indeed I am not seeing the labels for tutorial 105 and I think this is my problem.

**Comment by jdumas** [comment]
Hi,

In the latest version of libigl NanoGui has been dropped in favor of ImGui. Labels are now only visible if you enable the ImGui viewer plugin (see discussion in #719 for how to do it, we are in the process of updating the website accordingly). Note that the viewer menu/labels is now only available for tutorial 106.
