### ISSUE TITLE
Linking Error

### ISSUE THREAD

**Issue by christow** [libigl/libigl#48]
While compiling libigl tutorial on Ubuntu 14.04 two libraries were missing. Namely, -lXcursor -lXinerama.

Fixed by adding them to libigl/tutorial/CMakeLists.shared

set(CMAKE_CXX_LINK_EXECUTABLE "${CMAKE_CXX_LINK_EXECUTABLE} -lGL -lGLU -lrt -lX11 -lXxf86vm -lXrandr -lpthread -lXi -lXcursor -lXinerama")

**Comment by alecjacobson** [comment]
Could you wrap this in an if statement checking for Linux and then post a pull request?

**Comment by christow** [comment]
In fact it is wrapped in if statement:
I just added tese two -lXcursor -lXinerama right at the end.

if(UNIX AND NOT APPLE)
  set(CMAKE_CXX_LINK_EXECUTABLE "${CMAKE_CXX_LINK_EXECUTABLE} -lGL -lGLU -lrt -lX11 -lXxf86vm -lXrandr -lpthread -lXi -lXcursor -lXinerama")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mavx")
endif(UNIX AND NOT APPLE)
