### ISSUE TITLE
Sementation fault in readOFF.h

### ISSUE THREAD

**Issue by 2006pmach** [libigl/libigl#480]
When I am trying to read an OFF file that has a comment followed by a blank line I get a segmentation fault.

i.e [cube_1.off](https://github.com/libigl/libigl/files/810521/cube_1.txt) produces the segmentation fault but not [cube_2.off](https://github.com/libigl/libigl/files/810523/cube_2.txt)
example taken from [Off file format](https://en.wikipedia.org/wiki/OFF_%28file_format%29)

A fix would be nice. Thanks.

(Files attached as txt as github does not allow .off)

**Comment by alecjacobson** [comment]
New lines seem pretty harmless. If somebody posts a PR, I'd merge.
