### ISSUE TITLE
How to get texture ordinates? 

### ISSUE THREAD

**Issue by ada-hs** [libigl/libigl#481]
I use some pramaterization methods to get the UV information, then apply an image to texture mapping, what I want are the texture coordinates,  I found this issue (https://github.com/libigl/libigl/issues/377) mentioned that the  the texture coordinates vertices are a to-do item. So did the newest version of libigl implement this?

Thanks for any help

**Comment by alecjacobson** [comment]
The referenced issue is about decimation. Is your question also about decimation?

Or are you asking about mesh parameterization ? There are multiple tutorial sections about this in Chapter 5.
