### ISSUE TITLE
Add discrete exterior calculus operators

### ISSUE THREAD

**Issue by milkpku** [libigl/libigl#482]
Hi, dear authors of libigl,

I am recently studying Keenan Crane's course *Digital Geometry Processing With Discrete exterior calculus*, and find there is no implementation of discrete exterior calculus in libigl. I have implement it myself, and am wondering if it is ok to contribute to libigl?

I think discrete exterior calculus operators are useful for libigl, since they can ease exterior calculus related computations such as vector field design.

**Comment by alecjacobson** [comment]
Sure, this could be something interesting to have. Most of the resulting
operators for DEC coincide with operators built using linear FEM, so we
should be careful about duplicates.
-A
