### ISSUE TITLE
principal curvature crash 

### ISSUE THREAD

**Issue by wguo68** [libigl/libigl#490]
![cur](https://cloud.githubusercontent.com/assets/4994038/23944303/539974cc-09ad-11e7-8776-39fbd4c83fd1.jpg)
It says: Could not compute curvature of radius ...
It seems it can't find enough vertices. How to do with this problem?  Is there any tool to repair my mesh. I used MeshLab ,but still can't make it work.

**Comment by danielepanozzo** [comment]
Are you sure that that the problem is not on the mesh? Maybe 2065 is an isolated vertex? Meshlab should be fine for cleaning it up, make sure that you delete all isolated vertices and all the connected components except the larger one.

**Comment by wguo68** [comment]
I can't find this function to remove isolated vertices  in Meshlab. I wrote simple code to do this and it is now okay. Thank you.
