### ISSUE TITLE
How to find boundary vertices quickly?

### ISSUE THREAD

**Issue by wguo68** [libigl/libigl#491]
My method is to visit the triangles and put adj vertices to each vertex.Then sort is and check if each adj vertex occur twice. 
Thanks

**Comment by alecjacobson** [comment]
see:

- `igl::boundary_facets`
- `igl::on_boundary`
- `igl::boundary_loop`

Most of the time I need boundary facets. If I need the set of vertices I use `igl::boundary_facets` + `igl::unique`. If I need the boundary vertices _in order_ (rare), I use `igl::boundary_loop`.
