### ISSUE TITLE
Bug in igl::deserialization called from python

### ISSUE THREAD

**Issue by jiangzhongshi** [libigl/libigl#496]
## First Appearance of the Bug
As I was trying to use the python binder and the TCPViewer, I found the following bug. It should be able to be reproduced by just calling the python tutorial `102_DrawMesh_TCPViewer.py`.

In server part of tcp_viewer, `BAD_ACCESS` is reported when the mesh is received and during deserialization. I tried to use debug tool to identify it as follows.

At [line 734 of `igl::serialize.h`](https://github.com/libigl/libigl/blob/master/include/igl/serialize.h#L734)
```
   731 	    inline typename std::enable_if<std::is_fundamental<T>::value>::type deserialize(T& obj,std::vector<char>::const_iterator& iter)
   732 	    {
   733 	      uint8_t* ptr = reinterpret_cast<uint8_t*>(&obj);
-> 734 	      std::copy(iter,iter+sizeof(T),ptr);
   735 	      iter += sizeof(T);
   736 	    }
   737
```
## Minimal Reproducible Case
Further debugging shows that the socket communication is not causing the problem. The problem is within the `deserialize` python binder.
I have been trying to track it down and it's able to be reproduced as follows.

```
import pyigl as igl

V = igl.eigen.MatrixXd()
F = igl.eigen.MatrixXi()
igl.readOFF("../tutorial/shared/beetle.off", V, F)

viewer = igl.viewer.Viewer()
viewer.data.set_mesh(V,F)

ser = viewer.data.serialize()
viewer.data.deserialize(ser)
```

This would output something like
```
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-6-274ee1106449> in <module>()
     17 
     18 ser = viewer.data.serialize()
---> 19 viewer.data.deserialize(ser)
     20 
     21 viewer

MemoryError: std::bad_alloc
```

Further, it can be located to [`serialize.h:759`](https://github.com/libigl/libigl/blob/master/include/igl/serialize.h#L759).
```
   756 	      size_t size;
   757 	      serialization::deserialize(size,iter);
   758
-> 759 	      std::string str(size,'\0');
   760 	      for(size_t i=0; i<size; ++i)
   761 	      {
   762 	        serialization::deserialize(str.at(i),iter);
```
where `size` is as large as `4594516044848037888`, causing the string construction failure.

**Comment by jiangzhongshi** [comment]
The exception of `std::bad_alloc` seems to be thrown pretty often in python binder. Also in Tutorial 303 (issue #497 ) and Tutorial 506.

@s-koch Could you help us with it? Thanks!

**Comment by jiangzhongshi** [comment]
@s-koch Could you help check the problem? Thanks.

**Comment by s-koch** [comment]
Hi Zhongshi,
I already stumbled upon the deserialization problem as well (see #231) and did not look further then you into it. I can take another look into it tomorrow and we can try to fix it together. As for the tutorials 303 and 506 it is strange that you get these errors. What os do you use and how do you compile libigl?

**Comment by jiangzhongshi** [comment]
Hi Sebastian,

Well, it seems to be a long standing issue...
I am using MacOS Sierra and 
my compiler and python is as follows: 
```
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.4.0
Python 3.5.2 :: Anaconda 4.2.0 (x86_64)
```

Though in my case, it's not a segfault, only a `std::bad_alloc` exception.

Seems something wrong happened to passing the object `iter`.

**Comment by s-koch** [comment]
Ok, so I first looked into the problem with tutorial 303 and could reproduce the exception. I have an idea how to fix it and will commit a fix soon. You mentioned tutorial 506, but this doesn't exist. In which tutorial do you get a similar exception?

**Comment by jiangzhongshi** [comment]
That's great to know.

So another one was [505_MIQ: 256](https://github.com/libigl/libigl/blob/master/python/tutorial/505_MIQ.py#L256).

**Comment by s-koch** [comment]
So these are all different problems: 

- 303: The generated bindings for the function unique are defect as there is something wrong with the overloading.  As a temporary workaround, you can comment out (in py_igl/py_unique.cpp) the versions of the function that use std::vector, I hope that works for you as well. @danielepanozzo do we need these std::vector-parametrized functions or should everything be passed as Eigen types?

- 505: In the current master branch I get a segfault, could you check if it works for you with the version of f9c0891?

I will continue with 102_TCP tomorrow and create a pull request with fixes for the other problems as well.

**Comment by jiangzhongshi** [comment]
Hi, this is amazing, I wonder how you were able to find out the defect of overloading.
- 303: commenting out those `std::vector` binder also works on my side. 
- 505 works fine with `f9c0891`

I ran through the tutorials in `f9c0891`, and only significant bugs are for the 102 and 303.

**Comment by danielepanozzo** [comment]
I think we can drop the wrappers for the std::vectors, they are convenient in C++, but I don't think they are useful in the wrappers.

**Comment by s-koch** [comment]
@danielepanozzo: Ok, let`s drop them then. I will create a pull request with all the combined fixes.

@jiangzhongshi: I narrowed down the problem with tutorial 102 and am checking back with the guys from pybind11 on how to solve it (the problem arises from binding a std::vector<char>, which is represented in python as a list of strings). The bug with 303 I found out by creating a minimal (non-) working example which showed this problem with the overloading. I will do the same for 505 in the coming days...

**Comment by s-koch** [comment]
So I fixed the problems with 102 and 303 with pull request #504, can you check if this works for you as well @jiangzhongshi? There was a bug in pybind11 which has recently been fixed, so in the end not much had to be changed in our code. 505 and 709 have been damaged by recent commits of C++ code, I might check them tomorrow.

**Comment by jiangzhongshi** [comment]
Great, it works like a charm.

Only thing is that in the first commit of the PR, you may have accidentally reverted the version of Embree, so that it didn't pass the build test for the main tutorials. 

It works fine if the Embree version coordinates with the current master.

**Comment by stigersh** [comment]
Hey, I'm trying to serialize from Xcode and deserialize from python.
I fail to find the interface to deserialize from python. Can you please refer to some example? 
Best,
Anna
