### ISSUE TITLE
writeOFF only saves triangles

### ISSUE THREAD

**Issue by amonszpart** [libigl/libigl#499]
There is a hard-coded "3" in writeOFF, whilst readOFF returns a 4-column matrix for a quad mesh: 
https://github.com/libigl/libigl/blob/master/include/igl/writeOFF.cpp#L32
How about swapping `"3 "` for: `std::to_string(F.cols()) + " "`?

Test:
```
Eigen::MatrixXd V, F;
igl::readOFF(TUTORIAL_SHARED_PATH "/cube.off", V, F);
igl::writeOFF("cube_out.off", V, F);
```
Output:
```
OFF
8 6 0
1 0 1
0 1 1
-1 0 1
0 -1 1
1 0 -1
0 1 -1
-1 0 -1
0 -1 -1
3 0 1 2 3
3 7 4 0 3
3 4 5 1 0
3 5 6 2 1
3 3 2 6 7
3 6 5 4 7
```
Note the 3-s at the beginning of the last 6 lines.

Input:
```
OFF
8 6 12
 1.0   0.0   1.0
 0.0   1.0   1.0
-1.0   0.0   1.0
 0.0  -1.0   1.0
 1.0   0.0  -1.0
 0.0   1.0  -1.0
-1.0   0.0  -1.0
 0.0  -1.0  -1.0
 4  0 1 2 3
 4  7 4 0 3
 4  4 5 1 0
 4  5 6 2 1
 4  3 2 6 7
 4  6 5 4 7
```
Thanks

**Comment by danielepanozzo** [comment]
Sounds good, could you send a PR with the change?
