### ISSUE TITLE
Undefined symbols: CTwGraphOpenGLCore

### ISSUE THREAD

**Issue by candycat1992** [libigl/libigl#50]
Mac + Qt creator,  used the anttweakbar version embedded in libigl/external. But I got errors:

Undefined symbols for architecture x86_64:
  "CTwGraphOpenGLCore::BuildText(void*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const*, unsigned int*, unsigned int*, int, CTexFont const*, int, int)", referenced from:
      vtable for igl::TextRenderer in main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by danielepanozzo** [comment]
Could you please try to compile the examples in the tutorial using the provided cmake file and see if you get the same error?

**Comment by candycat1992** [comment]
@danielepanozzo Thanks for you refly! I finally fixed it myself. I use the anttweakbar version from http://anttweakbar.sourceforge.net/doc/ and replace the version embedded in libigl/external. It works!
