### ISSUE TITLE
qslim segfaults with DEM like mesh

### ISSUE THREAD

**Issue by Luk0r** [libigl/libigl#506]
I created a mesh (160k faces) from a 2.5D height field (dem, digital elevation model) and tried to use igl::qslim( ... ) on it.
It starts and is calculating for some time but after a while it gives me a segfault.
The igl::decimate() function runs our of memory (malloc error) after while (8GB machine).

The bunny model works.

I would need the simplification for the rendering.
Any ideas?

**Comment by alecjacobson** [comment]
If you can upload your mesh then it will be easier to diagnose. I'm guessing your mesh has non-manifold edges.

**Comment by Luk0r** [comment]
Thanks, something is wrong with my mesh. I exported it and imported it into meshlab. This import gave me some warnings and fixed the mesh. After exporting and loading it with libigl, qslim worked.

Can be closed.
