### ISSUE TITLE
Libigl mesh booleans

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#51]
From personal email:

> I am interested in trying out your Libigl for 3D mesh Boolean. I have tried Cork which does not work (crashes on its supplied sample files in Shewchuk's 2D Triangle code which is unstable according to my previous test despite the original developer's claim). 
> 
> I have two questions :
> 1) Does Libigl use the same 2D Triangle code (my search in the Libigl source code indicates NO, but a confirmation would be reassuring) ? 
> 2) Libigl's Boolean depends on some GPL-licensed header files from CGAL. Is it possible to remove this dependency?
> 3) Do you have a ready to run command line program so that I can run a test with a few of my sample data sets?
> 
> Many thanks in advance,

1) No, it uses CGAL for triangulation.
2) No, the dependency on CGAL would require severely rewriting a core function. It is possible to do, but I will not do it.
3) No, but it would be very easy to alter the [boolean tutorial example](http://libigl.github.io/libigl/tutorial/tutorial.html#609) to do that. Basically drop the viewer and change the hardcoded paths to command line arguments and write out the result to an obj.

Sorry for all of the nos. I will say, if you're unhappy with Shewchuk's triangle in terms of robustness, you might just be hard to please. I rarely encounter implementations that even come close to his robustness. I can also attest that cork is not robust (although pretty good as free/open-source libraries go).

We're still developing the boolean library in libigl. There are some known issues, but we (think we) know the solutions.

**Comment by dnjiang** [comment]
Thanks for the answers. 

I tried to use  Shewchuk's triangle code several times over the last couple of years, it occasionally crashes on my data sets. However, there is a .NET port (by someone else) of his code (https://triangle.codeplex.com/) with which  I have much better luck and I am using it daily.

There is also a supposedly robust and fast mesh Boolean implementation.from here:
http://www.graphics.rwth-aachen.de/webbsp/
I am keen on checking it out, but it is offered as a web service, i.e., no source code, nor binary executable to try.

**Comment by cesss** [comment]
The GPL license of the boolean implementation (GPL inherited from CGAL) is what makes it impossible for me to use it (I could use it now because in this moment I don't have any incompatibility with the GPL, but I never put GPL dependencies in my code, so that it's always possible to release it under MIT license -or similar- if necessary).

It's quite sad, as the algorithm shines, but I see no way of using it.

**Comment by pierre-leon** [comment]
Hi @alecjacobson, sorry to wake this old issue but I could't find the answer elsewhere.

1. If we're looking to get a commercial license from CGAL to be able to implement Libigl's boolean, what module(s) of CGAL are required?
2. The same question - just for Tetwild?
Many thanks

**Comment by alecjacobson** [comment]
I believe it's the ration numbers, triangle-triangle intersection, 2D
constrained Delaunay and AABB tree. I'm not sure how these show up on
CGAL's menu.
(FWIW I think CGAL already has customers who pay them to use libigl
booleans, so they might just tell you from past experience).

I think tetwild is just using the rational number type. but if you ask on
that github issue then it would ping Yixin to answer.
-Alec

>

**Comment by jdumas** [comment]
If you get an answer from the CGAL folks, please let us know, I'd be happy to update the FAQ on the website.

**Comment by hearables-pkinsella** [comment]
I just checked with CGAL, would you be able to confirm if the following modules are correct:

- 2D Triangulation
- dD Spatial Searching
- Intersecting Sequences of dD Iso-oriented Boxes
- 3D Fast Intersection and Distance Computation (AABB Tree)

Total cost is $36,000 euro.

**Comment by alecjacobson** [comment]
That seems right for igl::mesh_boolean IIRC, but can't confirm in any official sense (CGAL probably can?). Not sure what we'd use from "dD Spatial Searching" that's not in "3D fast ...", but that's a question for CGAL.

FWIW, The AABB tree should be easy to replace (could even just use the libigl one; since it's axis-aligned I believe there's no opportunity for floating-point non-sense to cause issues). 

The 2D triangulation is a bit more annoying to replace since we need a _constrained_ Delaunay triangulation (i.e., not just vertices as input but edges). I think @qnzhou started this but we still don't have a non-CGAL CDT in libigl. There are others out there (e.g., https://www.geometrictools.com/) but for the Booleans we need it to be exact and work with rational types.

**Comment by JLYang123** [comment]
> I just checked with CGAL, would you be able to confirm if the following modules are correct:
> 
> * 2D Triangulation
> * dD Spatial Searching
> * Intersecting Sequences of dD Iso-oriented Boxes
> * 3D Fast Intersection and Distance Computation (AABB Tree)
> 
> Total cost is $36,000 euro.

per year?
