### ISSUE TITLE
UV mapping as a simple projection of the XY plane

### ISSUE THREAD

**Issue by FelipeSempertegui** [libigl/libigl#510]
Hello everyone,

I have a specific problem that might be easy solvable for the ones used to C++. I need to perform a simple UV mapping of a membrane (figures are attached to this message). I, however, need the UV map to be a simple projection of the XY plane. This means that the uv coordinates won`t be deformed in regions where the triangles are parallel to the XY plane, while the regions with a certain slope will show the highest distortion.

Moreover, I understood that the only operation is the exchange of z coordinates of the vertice's matrix V to zero. 
In matlab syntax: V_uv=[ V(:,1:2) zeros( size(V,1) ) ]
Am I right? If this is the case, which would be the easiest way to implement it in Libigl?
![membrane](https://cloud.githubusercontent.com/assets/26798374/24663996/c333a4a4-1959-11e7-887b-2450b5d9bfc6.png)

**Comment by alecjacobson** [comment]
Among many ways:

V_uv = V;
V_uv.col(2).setConstant(0);

**Comment by MatillaMartin** [comment]
Checkout harmonic parametrization too, it will give you better results than planar mapping
