### ISSUE TITLE
Issue with the unique function

### ISSUE THREAD

**Issue by orpheus92** [libigl/libigl#511]
It seems there is a problem when I was trying to use the unique function in the include/igl.
Has anyone tried that before?

**Comment by alecjacobson** [comment]
We use this function all over the place. What's the problem?

**Comment by orpheus92** [comment]
Originally I was using this function to for two vectors in Eigen Library, just similar to the way I would use cmake to link other libaries. Then it says undefined reference. Then I write a simple test script with the CMakeLists to see if that works. It gives me the same problem. 
The following is my test script.
#include <iostream>
#include <igl/viewer/Viewer.h>
#include <igl/viewer/Viewer.h>
#include <igl/unique.h>
int main(int argc, char *argv[])
{
  using namespace Eigen;
  using namespace std;
  	Eigen::VectorXd old(8);
  	old<<-1,-1, 1,-1, 1,1, -1, 1;
  	Eigen::VectorXd cur;
  	igl::unique(old,cur);
  	
  	std::cout<<cur<<std::endl;
}

The following is the CMakeLists
cmake_minimum_required(VERSION 2.8.12)
project(uniquetest)

add_executable(${PROJECT_NAME}_bin
  main.cpp)
target_include_directories(${PROJECT_NAME}_bin PRIVATE ${LIBIGL_INCLUDE_DIRS})
target_compile_definitions(${PROJECT_NAME}_bin PRIVATE ${LIBIGL_DEFINITIONS})
target_link_libraries(${PROJECT_NAME}_bin ${LIBIGL_LIBRARIES} ${LIBIGL_VIEWER_EXTRA_LIBRARIES} ${LIBIGL_EXTRA_LIBRARIES})

I was not quite sure which was the library corresponding to igl. Thus I use both LIBIGL_LIBRARIES and LIBIGL_EXTRA_LIBRARIES for the CMakeLists.

**Comment by alecjacobson** [comment]
Try -DLIBIGL_USE_STATIC_LIBRARY=OFF in your cmake command.

**Comment by orpheus92** [comment]
Thanks a lot! 
That solves my problem.
I was working on this for several days....
