### ISSUE TITLE
Tutorial 505_MIQ broken

### ISSUE THREAD

**Issue by jiangzhongshi** [libigl/libigl#513]
There seems to be a run-time memory bug in tutorial 505_miq.
Information is as follows,

```
505_MIQ_bin(20305,0x7fff97ca43c0) malloc: *** mach_vm_map(size=535131099590066176) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
libc++abi.dylib: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
Abort trap: 6
```

**Comment by jiangzhongshi** [comment]
It works well as of commit 4f6c95. I haven't examine further.

**Comment by copyme** [comment]
This issue seems to be old and anyway the tutorial 505 works and compiles well here. I suggest to close the issue.

**Comment by jdumas** [comment]
If it works on your OS doesn't mean it works with everyone else. @jiangzhongshi is the issue still relevant to you?

**Comment by copyme** [comment]
@jdumas je suis d'accord avec toi. But first we do not have enough information to reproduce it. Second it is quite old so anyway is not referring to the current code. @jiangzhongshi can you feel us up with more accurate and current feedback, please?

**Comment by jiangzhongshi** [comment]
The steps to reproduce was only compiling and run. However, as I just tried, the issue is no longer relevant.

**Comment by copyme** [comment]
thanks @jiangzhongshi for the feedback! One open issue less ;-)
