### ISSUE TITLE
Projecting mesh onto a plane

### ISSUE THREAD

**Issue by rileyjf1** [libigl/libigl#514]
I'm interested in finding the convex hull of a mesh that I have projected onto a plane, think of finding the shadow from the sun. I was just hoping someone could provide some input how I might be able to do this with libigl?

I thought about flattening the mesh but projecting all the vertices on to the plane, but then I have a terrible mess of intersecting edges and vertices stacked right on top of each other, etc (is it possible to clean up this mesh and just extract the flat convex hull?)

I also thought about just creating a grid on the plane and casting rays from the grid to see if they intersect this mesh, but I have not figured out how to test the intersection of the rays with the mesh.

Any help would be greatly appreciated!

**Comment by alecjacobson** [comment]
If I understand correctly then I would do this by projecting only the vertices to the plan and using `igl::triangle::triangulate` to get a mesh of the convex hull of those points (if you really want only the boundary curve then there are more efficient ways, but not in libigl)

**Comment by rileyjf1** [comment]
Thanks, alec, I thought about doing this but the problem is my mesh may have gaps (like a torus) that I don't believe would be caught using this method

**Comment by alecjacobson** [comment]
Then perhaps you don't want the convex hull since the convex hull will not have a hole. What do you want as output for the torus case?

**Comment by alecjacobson** [comment]
The "outer hull"?

**Comment by alecjacobson** [comment]
Meanwhile, I think `igl::copyleft::cgal::projected_cdt` is very close to what you want.

**Comment by rileyjf1** [comment]
You're right I was using that term incorrectly, I am not interested in the convex hull. 

The function you listed does look promising, but I'm not sure I understand it exactly. In the header file it looks like it takes a list of cgal objects, what kind of cgal objects are these and how do I construct them from an igl triangle mesh?

also for the inputs it says:
// Inputs:
      //   objects  list of objects. This should lie on the given plane (P),
      //     otherwise they are added to the cdt _after_ their non-trivial
      //     projection

the objects exist in the plane already? or do they exist in 3d and will be projected onto the plane?

additionally, I suppose I'll have to use cgal directly to define the plane P?

sorry for the litany of questions, your help is greatly appreciated

**Comment by alecjacobson** [comment]
`projected_cdt` was written as a helper function for `remesh_intersections`. In that use case, the "objects" already live in the plane. However, according to [cgal](http://doc.cgal.org/latest/Kernel_23/classCGAL_1_1Plane__3.html#a73b656f5111f2845a5ba2e845a82d747) the `to_2d` function that's used by `insert_into_cdt`<`projected_cdt` will conduct the projection onto the plane. So it should be OK if the objects do not already live in the plane.

The objects can be points, lines, triangles or polygons. In your case, you'll just have triangles (CGAL shouldn't complain about duplicate vertices). So you could use `mesh_to_cgal_triangle_list` to get a list of `triangles` and then 

```
for(const auto & triangle : triangles)
{
  objects.push_back(CGAL::make_object(triangle));
}
```

The `CGAL::Plane_3` is quite easy to [construct](http://doc.cgal.org/latest/Kernel_23/classCGAL_1_1Plane__3.html) from the: plane equation, three points on the plane, or a point+normal vector.

If you end up writing a friendlier API for your specific case, I'd be happy to merge a PR.
