### ISSUE TITLE
Gaussian Curvature on Boundary Vertices

### ISSUE THREAD

**Issue by avaxman** [libigl/libigl#516]
Currently, Gaussian_curvature always compute "2*pi-angle_sum". This is not the usual way to discretize (geodesic) curvature on boundary vertices, which is "pi-angle_sum" (also in this way the total sum obeys the Euler characteristic).

**Comment by alecjacobson** [comment]
Agreed. This should be fixed.

**Comment by liangbright** [comment]
Boundary may not be straight.  Let's delete a triangle face consisting of points: P1 P2 P3 from a triangle mesh. The triangle face was near the boundary. P1 and P3 are on the boundary. P2 was not on boundary before the deletion, and it is now on boundary after the deletion. The Gaussian curvature on P2 should be the same before and after deletion. "pi-angle_sum" can not guarantee this.

**Comment by avaxman** [comment]
No, it's not. There is no "Gaussian curvature" on boundary vertices per se. The is the geodesic curvature. It is needed to be defined this way to satisfy the Gauss-Bonnet = index theorem = whatever, by counting the total angle sums\defects.

**Comment by alecjacobson** [comment]
I'm no longer convinced this should change ( and it didn't in the meantime). Is there a reference for π-∑θ for boundary vertices?
if we're calling that geodesic curvature then it seems a bit weird to return it in a function called gaussian_curvature. Maybe this function just needs better documentation.

**Comment by avaxman** [comment]
There isn't any "Gaussian curvature" at boundary vertices. Index theorem is
defined with the geodesic curvature on boundary vert ices. Lazy reference
here:
https://twitter.com/keenanisalive/status/1514325321939566594?t=EGA0mPs4O8Ov6F2bL8ZvZw&s=19

**Comment by alecjacobson** [comment]
I should have read the whole thread before replying. I'm content changing the doc to be clear what the output is. I think any other change would have to involve changing the name of this function or adding a different function for geodesic curvature along the boundary curve.
