### ISSUE TITLE
Tutorial build on fresh ubuntu broken

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#517]
Trying to build on a fresh ubuntu installation the default cmake set up is choking on the lack of ispc from embree.

How is travis currently handling this? It'd be nice if our cmake automatically turned off this support based on whether it's installed.

```
-- CMAKE_C_COMPILER: /usr/bin/cc
-- CMAKE_CXX_COMPILER: /usr/bin/c++
-- Build type: Release
-- USING CXXFLAGS = ' -O3 -DNDEBUG'
-- USING EXEFLAGS = ' '
-- Targetting Unix Makefiles
-- Using /usr/bin/c++ compiler.
-- Requested component: Core
-- Requested component: MPFR
-- Requested component: GMP
-- Found CGAL: /usr/lib/x86_64-linux-gnu/cmake/CGAL
-- A library with BLAS API found.
CMake Error at /usr/local/igl/libigl/external/embree/common/cmake/ispc.cmake:54 (MESSAGE):
  Intel SPMD Compiler (ISPC) not found.  Disable EMBREE_ISPC_SUPPORT or
  install ISPC.
Call Stack (most recent call first):
  /usr/local/igl/libigl/external/embree/CMakeLists.txt:280 (INCLUDE)


-- Configuring incomplete, errors occurred!
See also "/usr/local/igl/libigl/tutorial/build/CMakeFiles/CMakeOutput.log".
See also "/usr/local/igl/libigl/tutorial/build/CMakeFiles/CMakeError.log".

```

**Comment by alecjacobson** [comment]
I see. Travis is currently ignoring the embree dependency on linux. I managed to get the embree dependency compiling using:

    sudo apt install libtbb-dev
    sudo apt install freeglut3-dev

And then

    cmake -DEMBREE_ISPC_SUPPORT=OFF ../

Is there a clean way to put this into the cmake?

**Comment by danielepanozzo** [comment]
This is already in our shared cmake file, line 246 of shared/cmake/CMakeLists.txt
```
set(EMBREE_ISPC_SUPPORT OFF CACHE BOOL " " FORCE)
```
It is very strange that it is not working out of the box. Could you check if this line is in your cmake? I cannot reproduce it on my linux VM.

Embree also does not require tbb and glut. This line is disabling tbb (247)
```
set(EMBREE_TASKING_SYSTEM "INTERNAL" CACHE BOOL " " FORCE)
```
and this one is removing the glut dependency (I think it is used only in the examples) (248):
```
 set(EMBREE_TUTORIALS OFF CACHE BOOL " " FORCE)
```

**Comment by alecjacobson** [comment]
Ahah, I think I had pulled in the new embree but not these [recent changes](https://github.com/libigl/libigl/commit/d6adabe15ed777b53d6321e2c4e71b018ebfbcae) to our CMakeLists.txt.
