### ISSUE TITLE
Libigl with windows 7 and Visual Studio 2015

### ISSUE THREAD

**Issue by cisnex123** [libigl/libigl#518]
I am trying to compile libigl with visual studio 2015 under windows 7 (64 bit), following the tutorial's instruction (64 bits), everything is going ok, but when I trying to execute the *.exe files (102_DrawMesh_bin examples), there is a common error, "WGL: Failed to create OpenGL contextAssertion failed: window != NULL, file C:\Users\Esmeide\libigl\external\nanogui\ext\glfw\src\window.c, line 411".

The same is happening with the "blank project example", I compile sucessfully but when execute the "example_bin", the same error occurs "WGL: Failed to create OpenGL contextAssertion failed: window != NULL, file C:\Users\Esmeide\libigl\external\nanogui\ext\glfw\src\window.c, line 411".

Can somebody help me to see what is happening ?
Thak you.

![imagen](https://cloud.githubusercontent.com/assets/3765720/25048640/0fe2f52e-2103-11e7-95c0-fa23b0bdef7d.png)

**Comment by danielepanozzo** [comment]
It is failing to open the opengl context --- this is likely due to having outdated opengl drivers or a very old graphic card that does not support opengl 3.

**Comment by cisnex123** [comment]
Thank you for your help daniele
