### ISSUE TITLE
How to close or quit the viewer?

### ISSUE THREAD

**Issue by wguo68** [libigl/libigl#519]
I want to close or quit the viewer ,then do some job and then restart another viewer. How to close or quit current viewer? 
Thanks.

**Comment by Javier12** [comment]
It may be a little late:

`glfwSetWindowShouldClose(viewer.window, 1);`

Where `viewer` is your `igl::viewer::Viewer`

**Comment by Javier12** [comment]
@alecjacobson I'm not sure if I should request the issue to be closed.
