### ISSUE TITLE
example makefiles ignore global Makefile.conf configuration variables

### ISSUE THREAD

**Issue by louen** [libigl/libigl#52]
It appears that most of the makefiles in the example folder only take into account some of the variables defined in Makefile.conf, thus leading to compilation errors when building the examples.

For instance, my makefile.conf states 
` EIGEN3_INC=-I$(DEFAULT_PREFIX)/libs/eigen324/` 

but the examples makefiles proceed to ignore this folder and force the Eigen include directory to
`eigen=$(DEFAULT_PREFIX)/include/eigen3` which obviously doesn't  exist on my configuration.

I suggest that these makefiles use the global Makefile.conf variables wherever possible.

**Comment by alecjacobson** [comment]
I've unified the `examples/*/Makefile`s to pull in definitions from `../build/Makefile.conf`

**Comment by louen** [comment]
It's true, although some of them still ignore the makefile.conf variables, e.g. for eigen directories. See my pull request (#53) which attemps to fix this problem :)
