### ISSUE TITLE
mesh_boolean crashes sometimes

### ISSUE THREAD

**Issue by moneimne** [libigl/libigl#522]
Hello,

I have been working on a fracturing plugin for Houdini using `igl/copyleft/cgal/mesh_boolean.cpp`, but the application crashes with a segfault sometimes. The issue is that on the same input, the application will only crash sometimes and work other times. Whenever there is a segfault, the same stack trace is produced that leads somewhere into the depths of Eigen. Do you have any advice for how to approach this?

> Crash report from moneimne; Houdini FX Version 15.5.717 [windows-x86_64-cl19]
Uptime 63 seconds
Sun Apr 30 16:00:44 2017
Caught signal 11

> Traceback from 10288 ThreadId=0x00004110
CURRENT THREAD 16656
packetmath.h(360) [Eigen::internal::pstore<int,__m128i>]
genericpacketmath.h(475) [Eigen::internal::pstoret<int,__m128i,16>]
assignmentfunctors.h(28) [Eigen::internal::assign_op<int,int>::assignPacket<16,__m128i>]
assignevaluator.h(659) [Eigen::internal::generic_dense_assignment_kernel<Eigen::internal::evaluator<Eigen::Matrix<int,-1,1,0,-1,1> >,Eigen::internal::evaluator<Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<int>,Eigen::Matrix<int,-1,1,0,-1,1> > >,Eigen::internal::assig]
assignevaluator.h(416) [Eigen::internal::dense_assignment_loop<Eigen::internal::generic_dense_assignment_kernel<Eigen::internal::evaluator<Eigen::Matrix<int,-1,-1,0,-1,-1> >,Eigen::internal::evaluator<Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<int>,Eigen::Matrix<in]
assignevaluator.h(741) [Eigen::internal::call_dense_assignment_loop<Eigen::Matrix<int,-1,-1,0,-1,-1>,Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<int>,Eigen::Matrix<int,-1,-1,0,-1,-1> >,Eigen::internal::assign_op<int,int> >]
assignevaluator.h(880) [Eigen::internal::Assignment<Eigen::Matrix<int,-1,-1,0,-1,-1>,Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<int>,Eigen::Matrix<int,-1,-1,0,-1,-1> >,Eigen::internal::assign_op<int,int>,Eigen::internal::Dense2Dense,void>::run]
assignevaluator.h(837) [Eigen::internal::call_assignment_no_alias<Eigen::Matrix<int,-1,-1,0,-1,-1>,Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<int>,Eigen::Matrix<int,-1,-1,0,-1,-1> >,Eigen::internal::assign_op<int,int> >]
assignevaluator.h(805) [Eigen::internal::call_assignment<Eigen::Matrix<int,-1,-1,0,-1,-1>,Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<int>,Eigen::Matrix<int,-1,-1,0,-1,-1> >,Eigen::internal::assign_op<int,int> >]
assignevaluator.h(783) [Eigen::internal::call_assignment<Eigen::Matrix<int,-1,-1,0,-1,-1>,Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<int>,Eigen::Matrix<int,-1,-1,0,-1,-1> > >]
plainobjectbase.h(711) [Eigen::PlainObjectBase<Eigen::Matrix<int,-1,-1,0,-1,-1> >::_set<Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<int>,Eigen::Matrix<int,-1,-1,0,-1,-1> > >]
matrix.h(226) [Eigen::Matrix<int,-1,-1,0,-1,-1>::operator=<Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<int>,Eigen::Matrix<int,-1,-1,0,-1,-1> > >]
cwisenullaryop.h(328) [Eigen::DenseBase<Eigen::Matrix<int,-1,-1,0,-1,-1> >::setConstant]
propagate_winding_numbers.cpp(248) [igl::copyleft::cgal::propagate_winding_numbers<Eigen::Matrix<CGAL::Lazy_exact_nt<CGAL::Gmpq>,-1,-1,0,-1,-1>,Eigen::Matrix<int,-1,-1,0,-1,-1>,Eigen::Matrix<int,-1,-1,0,-1,-1>,unsigned __int64,Eigen::Matrix<int,-1,1,0,-1,1>,Eigen::Matrix<int,-1,-1,0,-1,-1>,E]
mesh_boolean.cpp(282) [igl::copyleft::cgal::mesh_boolean<Eigen::Matrix<double,-1,3,0,-1,3>,Eigen::Matrix<int,-1,-1,0,-1,-1>,Eigen::Matrix<unsigned __int64,2,1,0,2,1>,Eigen::Matrix<double,-1,-1,0,-1,-1>,Eigen::Matrix<int,-1,-1,0,-1,-1>,Eigen::Matrix<__int64,-1,1,0,-1,1> >]
mesh_boolean.cpp(118) [igl::copyleft::cgal::mesh_boolean<Eigen::Matrix<double,-1,-1,0,-1,-1>,Eigen::Matrix<int,-1,-1,0,-1,-1>,Eigen::Matrix<double,-1,-1,0,-1,-1>,Eigen::Matrix<int,-1,-1,0,-1,-1>,Eigen::Matrix<double,-1,-1,0,-1,-1>,Eigen::Matrix<int,-1,-1,0,-1,-1>,Eigen::Matrix<_]
mesh_boolean.cpp(55) [igl::copyleft::cgal::mesh_boolean<Eigen::Matrix<double,-1,-1,0,-1,-1>,Eigen::Matrix<int,-1,-1,0,-1,-1>,Eigen::Matrix<double,-1,-1,0,-1,-1>,Eigen::Matrix<int,-1,-1,0,-1,-1>,Eigen::Matrix<double,-1,-1,0,-1,-1>,Eigen::Matrix<int,-1,-1,0,-1,-1>,Eigen::Matrix<_]
mesh_boolean.cpp(425) [igl::copyleft::cgal::mesh_boolean<Eigen::Matrix<double,-1,-1,0,-1,-1>,Eigen::Matrix<int,-1,-1,0,-1,-1>,Eigen::Matrix<double,-1,-1,0,-1,-1>,Eigen::Matrix<int,-1,-1,0,-1,-1>,Eigen::Matrix<double,-1,-1,0,-1,-1>,Eigen::Matrix<int,-1,-1,0,-1,-1> >]
booleanops.cpp(35) [BooleanOps::testBoolean]
breakingpointplugin.c(196) [HDK_Sample::SOP_BreakingPoint::cookMySop]
+0x6a543964 [SOP_Node::cookMe]
+0x6ffb586e [OP_Node::cook]
+0x6a53a079 [SOP_Node::getCookedGeoHandle]
+0x6ec19de9 [OBJ_Node::getDisplayGeometryHandle]
+0x70d12bfa [JEDI_View::opuiUpdateNodeInfo]
+0x6c6648e2 [OH_OpHandler::opuiUpdateData]
+0x70ac8a6d [OP3D_View::doUpdate]
+0x70d11860 [JEDI_View::opuiUpdateData]
+0x6c664ab5 [OH_OpHandler::trigger]
+0x7131507f [UI_Queue::processNextEvent]
+0x71313b56 [UI_Queue::drain]
+0x71313c48 [UI_Queue::eventLoop]
+0x715a9a80 [AP_Interface::loadWindowGeoPref]
+0x715aa105 [myWinMain]
+0x73c9169e
+0x7a948364 [BaseThreadInitThunk]
+0x7c5f70d1 [RtlUserThreadStart]

**Comment by alecjacobson** [comment]
best guess this is an out of bounds error. The best way to debug would be to catch some input where this happens and post it for us to debug. If you can get it to happen in debug mode then Eigen might fire a meaningful assertion.

**Comment by moneimne** [comment]
What do you mean by an out of bounds error? Are there some forms of input I should be avoiding? Here is an example of a case in which the function crashes.

>VA: 
-0.5 -0.5 -0.5
 0.5 -0.5 -0.5
 0.5 -0.5  0.5
-0.5 -0.5  0.5
-0.5  0.5 -0.5
 0.5  0.5 -0.5
 0.5  0.5  0.5
-0.5  0.5  0.5
>FA: 
1 4 5
1 0 4
2 5 6
2 1 5
3 6 7
3 2 6
0 7 4
0 3 7
2 0 1
2 3 0
5 7 6
5 4 7
>VB:  
         1         -1   0.725658
         1         -1   0.929351
         1 -0.0699225       -0.5
         1          1       -0.5
         1   0.123664        1.5
  0.459069          1        1.5
 -0.699994          1   0.546395
         1          1        1.5
 -0.776867          1  -0.337976
 -0.593725          1       -0.5
 0.0300697  -0.204453   0.535369
  0.880702         -1     0.8312
>FB: 
 1 10 11
 1  6 10
 1  5  6
 1  4  5
 1 11  0
 1  7  4
 1  3  7
 1  2  3
 1  0  2
 2  8  9
 2 10  8
 2 11 10
 2  0 11
 2  9  3
 3  5  7
 3  6  5
 3  8  6
 3  9  8
 4  7  5
 6  8 10

However, sometimes (about 1 in 10 times) the app doesn't crash and returns the following results.

>VC: 
  -0.441886         0.5   0.0245724
  -0.408513         0.5    0.408513
   -0.40056         0.5         0.5
 -0.0604219  -0.0604219         0.5
-0.00260988   -0.155675         0.5
  0.0535048         0.5   -0.413694
  0.0632033   -0.199857         0.5
    0.15106         0.5        -0.5
        0.5   -0.493094         0.5
        0.5   -0.471364    0.471364
        0.5   -0.139273   0.0337337
        0.5    0.231147   -0.454407
        0.5    0.265745        -0.5
        0.5         0.5        -0.5
        0.5         0.5         0.5
>FC: 
 1  0  3
 1  5  0
 3  0  4
 5  4  0
 2  1  3
14  1  2
13  5  1
13  1 14
 3 14  2
 3  4  6
 3  6 14
11  4  5
11  6  4
11  5  7
13  7  5
 9  8  6
 6  8 14
10  9  6
10  6 11
12 11  7
12  7 13
 8  9 14
 9 10 13
 9 13 14
10 11 13
11 12 13

**Comment by alecjacobson** [comment]
thanks. That will help.

Does it ever crash in debug mode?

**Comment by moneimne** [comment]
Sadly we aren't able to run the plugin in debug mode. Also, I realized I didn't mention that we are using intersection as the boolean type.

**Comment by moneimne** [comment]
I ran the same test in a second implementation and it runs just fine. It seems that there might be a memory issue with using the function in Houdini. Thanks for the help!
