### ISSUE TITLE
Generating a cage for one 3d surface model

### ISSUE THREAD

**Issue by etrigger** [libigl/libigl#523]
I am wondering if we have some routine that computes a coarse cage encloses one 3d surface model (e.g. ). Or some suggested source code for this problem.
Thanks.

**Comment by alecjacobson** [comment]
Outside libigl, you might try ["Nested Cages"](http://www.cs.columbia.edu/cg/nested-cages/)

Within libigl, we have `igl::copyleft::progressive_hulls` which will collapse edges on input triangle mesh while keeping the simplified mesh outside the original.

We also have `igl::copyleft::offset_surface` which computes an isocontour of the signed distance function using marching cubes.

**Comment by etrigger** [comment]
Thanks for your information.

**Comment by etrigger** [comment]
Sorry, I can't find the 

> offset_surface

 under copyleft folder.  Is it defined in some other header?

**Comment by alecjacobson** [comment]
Ah. It's in my dev branch: https://github.com/libigl/libigl/tree/alecjacobson/include/igl/copyleft

I'll merge that into the master branch once the tests pass. For now you could try it there.

**Comment by etrigger** [comment]
Thanks.
