### ISSUE TITLE
Efficiency issue about  AABB test in mesh Boolean operation

### ISSUE THREAD

**Issue by metorm** [libigl/libigl#526]
Hi

I am working on a CSG problem, and I am a little confused about so-called AABB test.

It seems AABB test uses the bounding box to eliminate unnecessary intersection tests. Now I have a tube-like mesh and I want to cut off a part of it along the x-axis. As libigl doesn't provide half-space structure (or maybe I didn't find it ?), I have to use a large enough box to replace it, like the following figure:

![image](https://cloud.githubusercontent.com/assets/12082680/25777776/c1aa385c-331a-11e7-9d77-3d9495d8f6b4.png)

However, I am not sure whether should I use a large cube or a large prism. A cube contains more triangles, but 5 among the 6 faces of the cube can be easily eliminated from intersection test. A prism (shown in figure) contains fewer faces, but it seems only 1 among it's 5 faces can be easily eliminated from intersection test. As I don't know much about AABB algorithm, I am not sure which route shall I use.

**Comment by alecjacobson** [comment]
right. half-spaces need to be turned into appropriately large meshes. It won't really matter if it's a rect or tri prism.
