### ISSUE TITLE
Curvature extraction in different scales

### ISSUE THREAD

**Issue by FelipeSempertegui** [libigl/libigl#528]
Hello, 

I am currently using the algorithm to extract the principal curvatures of a geometry and it is working fine. Thanks for making it public.

According to the paper "Efficient multi-scale curvature and crease estimation", it is possible to the scale the amount of triangules that will be taken into account to estimate the curvature of a certain point (you call it the scale parameter r in the paper). Where could I alter this setting in your program so I could check its influence?

Regards, 
Felipe

**Comment by alecjacobson** [comment]
I guess that would be the radius parameter.
