### ISSUE TITLE
"Segmentation fault" while running the FrameField tutorial

### ISSUE THREAD

**Issue by FelipeSempertegui** [libigl/libigl#529]
Hello,

I wish to run the example 506 (FrameField) but I get a "Segmentation fault" when I run its binary file (the output from running the code can be seen at the end of this message). I have also made the changes suggested on the post https://github.com/libigl/libigl/issues/129, which might help me to make it run properly. 

As it was suggested in that post, I installed the compiler GCC 4.7 and I tried to run the example 506 with both the original source code (include/igl/copyeft/frame_field.cpp) and a new one by modifying the line 227 of "frame_field.cpp"(from "b[num] = i;" to "b(num, 0) = i;"). However, the output shown in the terminal from both the original source code and the modified one were the same.

Would you have an idea of where the error might be located?

Regards,
Felipe

--------------------------------

pc@pc ~/libigl/tutorial/build $ ./506_FrameField_bin
solve
Initital dimension: 26832 x 26832, number of constraints: 0 use reordering: 1
Eliminated dimension: 26832 x 26832
#nonzeros: 115664
# integer    variables: 9120
# continuous variables: 17712
	solve_multiple_rounding *** Statistics of MiSo Solver ***
		 Number of CG    iterations  = 0
		 Number of LOCAL iterations  = 504
		 Number of FULL  iterations  = 2
		 Number of ROUNDING          = 9120
		 time searching next integer = 0.02127s

Timings: 
		Gauss Elimination  0.000723 s
		System Elimination 0.003366 s
		Mi-Solver          0.202245 s
		Resubstitution     0.000109 s
		Total              0.206443

Precomputing ARAP terms
Precomputing SMOOTH terms
Preconditioning done.
solve
 Initital dimension: 26832 x 26832, number of constraints: 0 use reordering: 1
Eliminated dimension: 26832 x 26832
#nonzeros: 115664
# integer    variables: 9120
# continuous variables: 17712
	solve_multiple_rounding *** Statistics of MiSo Solver ***
		 Number of CG    iterations  = 0
		 Number of LOCAL iterations  = 714
		 Number of FULL  iterations  = 2
		 Number of ROUNDING          = 9120
		 time searching next integer = 0.029251s

Timings: 
		Gauss Elimination  0.000517 s
		System Elimination 0.003212 s
		Mi-Solver          0.278516 s
		Resubstitution     0.000105 s
		Total              0.28235

Segmentation fault

---------------------------------

**Comment by gaoalexander** [comment]
I also encounter this segmentation fault when running Tutorial 506.

```
solve
 Initital dimension: 26832 x 26832, number of constraints: 0 use reordering: 1
Eliminated dimension: 26832 x 26832
#nonzeros: 115664
# integer    variables: 9120
# continuous variables: 17712
	solve_multiple_rounding *** Statistics of MiSo Solver ***
		 Number of CG    iterations  = 0
		 Number of LOCAL iterations  = 500
		 Number of FULL  iterations  = 2
		 Number of ROUNDING          = 9120
		 time searching next integer = 0.008155s

Timings: 
		Gauss Elimination  0.000211 s
		System Elimination 0.000689 s
		Mi-Solver          0.079375 s
		Resubstitution     3.3e-05 s
		Total              0.080308

Precomputing ARAP terms
Precomputing SMOOTH terms
Preconditioning done.
solve
 Initital dimension: 26832 x 26832, number of constraints: 0 use reordering: 1
Eliminated dimension: 26832 x 26832
#nonzeros: 115664
# integer    variables: 9120
# continuous variables: 17712
	solve_multiple_rounding *** Statistics of MiSo Solver ***
		 Number of CG    iterations  = 0
		 Number of LOCAL iterations  = 711
		 Number of FULL  iterations  = 2
		 Number of ROUNDING          = 9120
		 time searching next integer = 0.010103s

Timings: 
		Gauss Elimination  0.000193 s
		System Elimination 0.000863 s
		Mi-Solver          0.119133 s
		Resubstitution     3.3e-05 s
		Total              0.120222


 INITIALIZED SPARSE MATRIX OF 42452d x 42452d 

 INITIALIZED SPARSE MATRIX OF 2716d x 42652d 

 INITIALIZED VECTOR OF 42452d x 1 

 INITIALIZED VECTOR OF 2716d x 1 
# integer    variables: 108
# continuous variables: 39828
zsh: segmentation fault  ./506_FrameField
```

Is this likely caused by an issue with one of the dependencies (Eigen, CoMiSo)?
