### ISSUE TITLE
add_lines makes wireframe or any other lines looks jittered on Mac (GL_LINE_SMOOTH flag)

### ISSUE THREAD

**Issue by MichaelRabinovich** [libigl/libigl#532]
Hey all,

I guess it's only a problem on Mac OS. Basically if you load a mesh, then draw the wireframe, and then draw some random lines with set_lines/add_lines, then the wireframe looks really bad (better to untick the 'fill' button to see it). I've fixed it locally by uncommenting the line:

glEnable(GL_LINE_SMOOTH)

in ViewerCore.draw() next to the   if (data.lines.rows() > 0) line, which is called once after you add lines, and turns on this opengl flag that apparently does that.

Also, changing line width doesn't work on MacOS (with the flag or without it), but I heard you guys already know that.

best,
Michael

**Comment by alecjacobson** [comment]
drawing lines with opengl doesn't seem well supported on macs 😢
