### ISSUE TITLE
swept volume debug build

### ISSUE THREAD

**Issue by rileyjf1** [libigl/libigl#533]
I've found an issue when trying to run a debug build using igl/copyleft/swept_volume. There is some debug code in AABB.cpp at line 764 with an assert that fails when querying distance using swept_volume. It fails in the tutorial 707_SweptVolume when built using the debug option. I can't tell if the failed assert means there is also an error in the release build that simply isn't caught or if this is entirely limited to the debug code

**Comment by jfdupuis** [comment]
I ran into the same issue.

include/igl/AABB.cpp:768: void igl::AABB<DerivedV, DIM>::set_min(const RowVectorDIMS&, igl::AABB<DerivedV, DIM>::Scalar, int, const RowVectorDIMS&, igl::AABB<DerivedV, DIM>::Scalar&, int&, igl::AABB<DerivedV, DIM>::RowVectorDIMS&) const [with DerivedV = Eigen::Matrix<double, -1, -1>; int DIM = 3; igl::AABB<DerivedV, DIM>::RowVectorDIMS = Eigen::Matrix<double, 1, 3>; typename DerivedV::Scalar = double; igl::AABB<DerivedV, DIM>::Scalar = double]: Assertion `diff<=1e-10 && "distance should match norm of difference"' failed.

Removing the #ifndef NDEBUG and rebuilding in release mode works. The assertion therefore only fails in debug mode.

When removing the asserting and running in debug, swept volume is fully computed. A quick visual inspection didn't seems to reveal noticeable inaccuracy.

**Comment by alecjacobson** [comment]
Could you post a minimal example that trips this assert? Maybe it's
overzealous or the epsilon that it's using isn't playing nice with the
scale of your inputs.
-A

**Comment by jfdupuis** [comment]
Building the tutorial as is will trigger it.

 cmake -DCMAKE_BUILD_TYPE=Debug ../tutorial/
 ./707_SweptVolume_bin

**Comment by jfdupuis** [comment]
The problem is occurring for me with clang 3.6.0 and gcc 4.8.4

**Comment by alecjacobson** [comment]
I can't reproduce this in debug mode on mac. Please reopen if still an issue.
