### ISSUE TITLE
constraining decimation

### ISSUE THREAD

**Issue by maorptz** [libigl/libigl#538]
Hi, i need an advice about constraining decimation, i want to be able select some of the mesh to be fixed.
i know that all i need to do is to set infinite cost on some edges, i'm wondering if there is an easy way to do it without hacking the current code too much. thanks...

**Comment by alecjacobson** [comment]
Look at the overloaded functions in https://github.com/libigl/libigl/blob/master/include/igl/decimate.h that expose `cost_and_placement` and `stopping_condition`. The `cost_and_placement` parameter is a function handle that should return the _cost_ of collapsing an edge and the _placement_ of the vertex resulting from the collapse. You can look inside the default overload in https://github.com/libigl/libigl/blob/master/include/igl/decimate.cpp for a trivial definition of these functions.
