### ISSUE TITLE
Merge two meshes

### ISSUE THREAD

**Issue by candycat1992** [libigl/libigl#54]
Hi, I'd like to merge two 3D meshes into one. I used remesh_self_intersections(V, F, params, SV, SF, IF, J, IM) to compute self intersections successfully, but I don't know how to discard triangles from one surface inside the other. How to do it with igl? 
Thanks for your help!

**Comment by alecjacobson** [comment]
It sounds like you're trying to compute a union. Are your two meshes closed, watertight manifolds? Then you could call `igl/boolean/mesh_boolean` with the union option. If not, then there's still hope with something else.

**Comment by candycat1992** [comment]
@alecjacobson It works! Appreciate your work!

**Comment by coreqode** [comment]
Hi, @alecjacobson @candycat1992 

What to do if meshes are not watertight?

**Comment by alecjacobson** [comment]
It depends. You might try using winding numbers as described in the appendix of https://www.dgp.toronto.edu/projects/fast-winding-numbers/
