### ISSUE TITLE
render high quality image

### ISSUE THREAD

**Issue by etrigger** [libigl/libigl#540]
I follow the tutorial to render the scene but the image quality is poor.
https://libigl.github.io/libigl/tutorial/tutorial.html#screencapture
![02_05_000001](https://user-images.githubusercontent.com/3329503/26931585-43bdccbe-4c61-11e7-8b77-7c09826b5d7d.png)

(1) Is it possible to improve the rendered image quality?
(2) Can I obtain the video while rendering like the build in function "VideoWriter " in OpenCV? or any suggested library for recording video.
Thanks.

**Comment by alecjacobson** [comment]
1) you could make the image larger then downsample. 
2) no. In the past I've written out pngs and then used ffmpeg to make them into a video. I've heard that mp4 libraries are easier now but never tried it.
