### ISSUE TITLE
typos in the tutorial

### ISSUE THREAD

**Issue by etrigger** [libigl/libigl#541]
[https://libigl.github.io/libigl/tutorial/tutorial.html#signeddistances](url)

> igl::AABB tree;
tree.init(V,F);
tree.squared_distance(V,F,P,sqrD,I,C);
... // P changes, but (V,F) does not
tree.squared_distance(V,F,P,sqrD,I,C);

If I understand it correctly, the parameters should be like the ones below:

igl::AABB tree;
tree.init(V,F);
tree.squared_distance(**P, V,F**,sqrD,I,C);
... // P changes, but (V,F) does not
tree.squared_distance(**P, V, F**, sqrD,I,C);

**Comment by alecjacobson** [comment]
I don't think so. Check `igl/AABB.h`:

      // Compute the squared distance from all query points in P to the
      // _closest_ points on the primitives stored in the AABB hierarchy for
      // the mesh (V,Ele).
      //
      // Inputs:
      //   V  #V by dim list of vertex positions
      //   Ele  #Ele by dim list of simplex indices
      //   P  #P by dim list of query points
      // Outputs:
      //   sqrD  #P list of squared distances
      //   I  #P list of indices into Ele of closest primitives
      //   C  #P by dim list of closest points
      template <
        typename DerivedP,
        typename DerivedsqrD,
        typename DerivedI,
        typename DerivedC>
      IGL_INLINE void squared_distance(
        const Eigen::MatrixBase<DerivedV> & V,
        const Eigen::MatrixXi & Ele,
        const Eigen::MatrixBase<DerivedP> & P,
        Eigen::PlainObjectBase<DerivedsqrD> & sqrD,
        Eigen::PlainObjectBase<DerivedI> & I,
        Eigen::PlainObjectBase<DerivedC> & C) const;

**Comment by etrigger** [comment]
Then, maybe the order of "P, V, F" in the code above them should be inversed as "V, F, P". Please correct me if I am wrong.
https://libigl.github.io/libigl/tutorial/tutorial.html#closestpoints
> VectorXd sqrD;
VectorXi I;
MatrixXd C;
igl::point_mesh_squared_distance(P,V,F,sqrD,I,C);

**Comment by etrigger** [comment]
Sorry, I was wrong!

**Comment by alecjacobson** [comment]
I can see where the confusion comes from. V,F come first in the AABB
because they "belong" to the AABB tree. In `point_mesh_squared_distance` P
comes first to match the name.
-A

**Comment by etrigger** [comment]
You are right. Because I did not look into the two function and I thought both of the first two parameters refer to mesh vertices.
