### ISSUE TITLE
MKL + Eigen As-rigid-as-possible parametrization crash

### ISSUE THREAD

**Issue by ShuangLiu1992** [libigl/libigl#542]
The example code for As-rigid-as-possible parametrization crashes with Eigen and EIGEN_USE_MKL_ALL enabled, it produces the following error message:

Eigen Version: 3.3
MKL: 2017
LIBIGL: clone from current master
GCC: 5

eigen-eigen-67e894c6cd8f/Eigen/src/Core/Assign_MKL.h:132: static void Eigen::internal::Assignment<DstXprType, Eigen::CwiseUnaryOp<Eigen::internal::scalar_sqrt_op<double>, SrcXprNested>, Eigen::internal::assign_op<double, double>, Eigen::internal::Dense2Dense, typename Eigen::internal::enable_if<Eigen::internal::vml_assign_traits<Dst, Src>::EnableVml>::type>::run(DstXprType&, const SrcXprType&, const Eigen::internal::assign_op<double, double>&) [with DstXprType = Eigen::Matrix<double, -1, 3>; SrcXprNested = const Eigen::ArrayWrapper<Eigen::Matrix<double, -1, 3> >; Eigen::internal::Assignment<DstXprType, Eigen::CwiseUnaryOp<Eigen::internal::scalar_sqrt_op<double>, SrcXprNested>, Eigen::internal::assign_op<double, double>, Eigen::internal::Dense2Dense, typename Eigen::internal::enable_if<Eigen::internal::vml_assign_traits<Dst, Src>::EnableVml>::type>::SrcXprType = Eigen::CwiseUnaryOp<Eigen::internal::scalar_sqrt_op<double>, const Eigen::ArrayWrapper<Eigen::Matrix<double, -1, 3> > >]: Assertion `dst.rows() == src.rows() && dst.cols() == src.cols()' failed.

**Comment by ShuangLiu1992** [comment]
in cotmatrix_entries.cpp, line 43:
      Matrix<typename DerivedC::Scalar,Dynamic,3> l;
      l = l2.array().sqrt();

**Comment by ShuangLiu1992** [comment]
seems to be resolved by changing the line to
l = l2.array().sqrt().matrix();
but there are way too many similar assignment in the code base.

**Comment by alecjacobson** [comment]
ewww. So this only happens when invoking MKL somehow?

**Comment by ShuangLiu1992** [comment]
yep, with EIGEN_USE_MKL_VML to be specific. Ewww indeed. Apparently Eigen assumes this is inplace and doesn't allocate memory...

**Comment by alecjacobson** [comment]
I see. So for the foreseeable future libigl will simply "not support"
`EIGEN_USE_MKL_VML`. We can of course fix these on a case by case basis and
improve our style guidelines, but this really seems like an Eigen
flaw/issue.
