### ISSUE TITLE
efficiently detect if a line segment penetrates a mesh

### ISSUE THREAD

**Issue by Astar2** [libigl/libigl#544]
For a given mesh, I need to connect any two vertices of the mesh which forms a line segment. I then want to check if this line segment penetrates the internal area inside the mesh.

As shown in the picture below, the line segment _AD_ crosses the mesh. Similarly, the line segment _AC_ is completed inside the shape which is also considered as penetration. Only the line segment _AB_ is not penetrating the shape.
![intersection](https://user-images.githubusercontent.com/28564067/27122967-a3afa1bc-50ec-11e7-94b7-3b0752467365.jpg)

I tried the _ray_mesh_intersect_ function, e.g. for line segment _AD_, I check if the first intersected point is D. If the first intersected point is not D, then it must intersect with the shape. Otherwise, this line segment could either completed outside (like the line segment _AB_) or inside (like _AC_)  the shape.

But it is slow, for a mesh with 10K vertices, it may take 10 mins to test all the combinations.
Any suggestion on this problem?

**Comment by alecjacobson** [comment]
`igl::ray_mesh_intersect` will simply loop over all triangles and test for
intersection. In your O(n^2) tests this means you'll be doing O(n^3)
computation. Yikes!

Instead you should construct an axis-aligned bounding box hierarchy using
`igl::AABB` and then call `igl::AABB::intersect_ray`. This will bring down
the computation to something like O(n^2 log n).

Even better you should use `igl::embree::EmbreeIntersector`. This requires
installing embree, but will be significantly faster than our AABB tree. It
might even have better asymptotic behavior, though if you do your O(n^2)
tests independently you'll always be bound by that.

-A

**Comment by etrigger** [comment]
Thanks, I tried the Embree which is much faster.

However, the hits seem not to behave consistently.
(1) The first hit could be either be the start (see picture A)or the end point (see picture B) of the line segment. The green triangle face is the first hit face.
![raytracing4](https://user-images.githubusercontent.com/3329503/27229492-1eec945a-52ac-11e7-9534-9bd7d62764e2.jpg)
[Figure A]

![raytracing3](https://user-images.githubusercontent.com/3329503/27220792-ad441ca8-5286-11e7-93f1-47ad1e3eecb4.jpg)
[Figure B]
(2)Sometimes, even the ray does intersect with the mesh (ei.intersectRay returns true), the size of hits is zero. Or the ei.intersectRay returns false but the size of hits is not zero.

For the asian_man_test_000000.obj, set the starting and ending point as 5468 and 915 can reproduce this zero hit. (The vertex index stars from 0)
[man_test_000000.zip](https://github.com/libigl/libigl/files/1080947/man_test_000000.zip)

**Comment by alecjacobson** [comment]
I'd just check the hits and reject these. In rendering you'd traditionally use a fudge factor to avoid hitting your own face 🤦
