### ISSUE TITLE
mesh-components and spline functionalities

### ISSUE THREAD

**Issue by Raikshton** [libigl/libigl#546]
First of all thank you for the great work with libigl.
I heavily use the python-bindings and they help me a lot. 

I can not find some functionalities, but there seems to exist a c++ counterpart:

* finding unbound components of a mesh
  igl\include\components.h
* fit a spline through 3d-points
  \external\nanogui\ext\eigen\unsupported\Eigen\src\Splines\SplineFitting.h

Are they coming soon in the next release? Or can someone point me in the right direction how to add them to the pyhton bindings?

For the following functionalities I was not able to find a solution in c++ or python using libigl. But I think they possibly exist:

* get the 3d-point on a spline for the given time t 
* calculating the length of the spline
* projecting spline/polyline to a mesh
* cutting/trimming a mesh with a polyline/spline
* fitting a spline by tolerance
  This means fitting a spline through points, but with respect to a tolerance ignoring points out of this tolerance
  I was not able to find that in eigen, but may be I overlooked it

I know that the last 5 functionalities are a little bit much for one question, but they somehow fit into the spline-theme. Please let me know if I should better open a new issue for them.
Has Someone an idea of how one or better all of the last 5 functionalities could be done?

Best,

Raik

**Comment by jiangzhongshi** [comment]
For your first question, the python bindings in `libigl` are created with [`pybind11`](https://github.com/pybind/pybind11).  
You can have a look at its documentation and the `libigl` implementation under `https://github.com/libigl/libigl/tree/master/python/py_igl`.

It's easy to create your own and I think it would be helpful to open pull requests.

As for the second, I don't think `libigl` have features for spline. Maybe you need to find other libraries for this.

**Comment by alecjacobson** [comment]
We do have fitting a cubic bezier spline to a set of points: [fit_cubic_bezier](https://libigl.github.io/dox/namespaceigl.html#a7e61e6506e142c21944010806e350df3). We don't have those other functions and they're probably not coming soon.

I'm not sure what you mean by "unbounded components". Please reopen with more details if you still need help with that.
