### ISSUE TITLE
Not able to compile "Hello World" program...on Ubuntu 16.04LTS

### ISSUE THREAD

**Issue by ManikaBindal** [libigl/libigl#547]
I included the **Eigen** library in **/usr/include/** and tried executing sample Eigen program, worked fine.
then I tried working with **"Hello World"** program given on **http://libigl.github.io/libigl/** after doing
**git clone --recursive https://github.com/libigl/libigl.git**  
Saved  hello world program in **t1.cpp** file in home directory
then  tried running the following command:
**g++ -std=c++11 -I /usr/include/ -I ./libigl/include t1.cpp -o t1exec**

It's not compiling and giving the following error: 

/tmp/ccsLLsPg.o: In function `_ZNSt6threadC1IRKZN3igl12parallel_forIiZNS1_12parallel_forIiZNS1_20squared_edge_lengthsIN5Eigen6MatrixIdLin1ELin1ELi0ELin1ELin1EEENS6_IiLin1ELin1ELi0ELin1ELin1EEENS6_IdLin1ELi3ELi0ELin1ELi3EEEEEvRKNS5_10MatrixBaseIT_EERKNSA_IT0_EERNS5_15PlainObjectBaseIT1_EEEUliE_EEbSB_RKSF_mEUlmE_ZNS3_IiSN_EEbSB_SP_mEUlimE0_SQ_EEbSB_SP_RKSK_RKT2_mEUliimE_JRiS10_RmEEEOSB_DpOT0_':
t1.cpp:(.text._ZNSt6threadC2IRKZN3igl12parallel_forIiZNS1_12parallel_forIiZNS1_20squared_edge_lengthsIN5Eigen6MatrixIdLin1ELin1ELi0ELin1ELin1EEENS6_IiLin1ELin1ELi0ELin1ELin1EEENS6_IdLin1ELi3ELi0ELin1ELi3EEEEEvRKNS5_10MatrixBaseIT_EERKNSA_IT0_EERNS5_15PlainObjectBaseIT1_EEEUliE_EEbSB_RKSF_mEUlmE_ZNS3_IiSN_EEbSB_SP_mEUlimE0_SQ_EEbSB_SP_RKSK_RKT2_mEUliimE_JRiS10_RmEEEOSB_DpOT0_[_ZNSt6threadC5IRKZN3igl12parallel_forIiZNS1_12parallel_forIiZNS1_20squared_edge_lengthsIN5Eigen6MatrixIdLin1ELin1ELi0ELin1ELin1EEENS6_IiLin1ELin1ELi0ELin1ELin1EEENS6_IdLin1ELi3ELi0ELin1ELi3EEEEEvRKNS5_10MatrixBaseIT_EERKNSA_IT0_EERNS5_15PlainObjectBaseIT1_EEEUliE_EEbSB_RKSF_mEUlmE_ZNS3_IiSN_EEbSB_SP_mEUlimE0_SQ_EEbSB_SP_RKSK_RKT2_mEUliimE_JRiS10_RmEEEOSB_DpOT0_]+0xc6): undefined reference to `pthread_create'
/tmp/ccsLLsPg.o: In function `_ZNSt6threadC1IRKZN3igl12parallel_forIiZNS1_12parallel_forIiZNS1_20squared_edge_lengthsIN5Eigen6MatrixIdLin1ELin1ELi0ELin1ELin1EEENS6_IiLin1ELin1ELi0ELin1ELin1EEENS6_IdLin1ELi3ELi0ELin1ELi3EEEEEvRKNS5_10MatrixBaseIT_EERKNSA_IT0_EERNS5_15PlainObjectBaseIT1_EEEUliE_EEbSB_RKSF_mEUlmE_ZNS3_IiSN_EEbSB_SP_mEUlimE0_SQ_EEbSB_SP_RKSK_RKT2_mEUliimE_JRiRKiRmEEEOSB_DpOT0_':
t1.cpp:(.text._ZNSt6threadC2IRKZN3igl12parallel_forIiZNS1_12parallel_forIiZNS1_20squared_edge_lengthsIN5Eigen6MatrixIdLin1ELin1ELi0ELin1ELin1EEENS6_IiLin1ELin1ELi0ELin1ELin1EEENS6_IdLin1ELi3ELi0ELin1ELi3EEEEEvRKNS5_10MatrixBaseIT_EERKNSA_IT0_EERNS5_15PlainObjectBaseIT1_EEEUliE_EEbSB_RKSF_mEUlmE_ZNS3_IiSN_EEbSB_SP_mEUlimE0_SQ_EEbSB_SP_RKSK_RKT2_mEUliimE_JRiRKiRmEEEOSB_DpOT0_[_ZNSt6threadC5IRKZN3igl12parallel_forIiZNS1_12parallel_forIiZNS1_20squared_edge_lengthsIN5Eigen6MatrixIdLin1ELin1ELi0ELin1ELin1EEENS6_IiLin1ELin1ELi0ELin1ELin1EEENS6_IdLin1ELi3ELi0ELin1ELi3EEEEEvRKNS5_10MatrixBaseIT_EERKNSA_IT0_EERNS5_15PlainObjectBaseIT1_EEEUliE_EEbSB_RKSF_mEUlmE_ZNS3_IiSN_EEbSB_SP_mEUlimE0_SQ_EEbSB_SP_RKSK_RKT2_mEUliimE_JRiRKiRmEEEOSB_DpOT0_]+0xc6): undefined reference to `pthread_create'
/tmp/ccsLLsPg.o: In function `_ZNSt6threadC1IRKZN3igl12parallel_forIiZNS1_12parallel_forIiZNS1_20squared_edge_lengthsIN5Eigen6MatrixIdLin1ELin1ELi0ELin1ELin1EEENS6_IiLin1ELin1ELi0ELin1ELin1EEENS6_IdLin1ELi3ELi0ELin1ELi3EEEEEvRKNS5_10MatrixBaseIT_EERKNSA_IT0_EERNS5_15PlainObjectBaseIT1_EEEUliE0_EEbSB_RKSF_mEUlmE_ZNS3_IiSN_EEbSB_SP_mEUlimE0_SQ_EEbSB_SP_RKSK_RKT2_mEUliimE_JRiS10_RmEEEOSB_DpOT0_':
t1.cpp:(.text._ZNSt6threadC2IRKZN3igl12parallel_forIiZNS1_12parallel_forIiZNS1_20squared_edge_lengthsIN5Eigen6MatrixIdLin1ELin1ELi0ELin1ELin1EEENS6_IiLin1ELin1ELi0ELin1ELin1EEENS6_IdLin1ELi3ELi0ELin1ELi3EEEEEvRKNS5_10MatrixBaseIT_EERKNSA_IT0_EERNS5_15PlainObjectBaseIT1_EEEUliE0_EEbSB_RKSF_mEUlmE_ZNS3_IiSN_EEbSB_SP_mEUlimE0_SQ_EEbSB_SP_RKSK_RKT2_mEUliimE_JRiS10_RmEEEOSB_DpOT0_[_ZNSt6threadC5IRKZN3igl12parallel_forIiZNS1_12parallel_forIiZNS1_20squared_edge_lengthsIN5Eigen6MatrixIdLin1ELin1ELi0ELin1ELin1EEENS6_IiLin1ELin1ELi0ELin1ELin1EEENS6_IdLin1ELi3ELi0ELin1ELi3EEEEEvRKNS5_10MatrixBaseIT_EERKNSA_IT0_EERNS5_15PlainObjectBaseIT1_EEEUliE0_EEbSB_RKSF_mEUlmE_ZNS3_IiSN_EEbSB_SP_mEUlimE0_SQ_EEbSB_SP_RKSK_RKT2_mEUliimE_JRiS10_RmEEEOSB_DpOT0_]+0xc6): undefined reference to `pthread_create'
/tmp/ccsLLsPg.o: In function `_ZNSt6threadC1IRKZN3igl12parallel_forIiZNS1_12parallel_forIiZNS1_20squared_edge_lengthsIN5Eigen6MatrixIdLin1ELin1ELi0ELin1ELin1EEENS6_IiLin1ELin1ELi0ELin1ELin1EEENS6_IdLin1ELi3ELi0ELin1ELi3EEEEEvRKNS5_10MatrixBaseIT_EERKNSA_IT0_EERNS5_15PlainObjectBaseIT1_EEEUliE0_EEbSB_RKSF_mEUlmE_ZNS3_IiSN_EEbSB_SP_mEUlimE0_SQ_EEbSB_SP_RKSK_RKT2_mEUliimE_JRiRKiRmEEEOSB_DpOT0_':
t1.cpp:(.text._ZNSt6threadC2IRKZN3igl12parallel_forIiZNS1_12parallel_forIiZNS1_20squared_edge_lengthsIN5Eigen6MatrixIdLin1ELin1ELi0ELin1ELin1EEENS6_IiLin1ELin1ELi0ELin1ELin1EEENS6_IdLin1ELi3ELi0ELin1ELi3EEEEEvRKNS5_10MatrixBaseIT_EERKNSA_IT0_EERNS5_15PlainObjectBaseIT1_EEEUliE0_EEbSB_RKSF_mEUlmE_ZNS3_IiSN_EEbSB_SP_mEUlimE0_SQ_EEbSB_SP_RKSK_RKT2_mEUliimE_JRiRKiRmEEEOSB_DpOT0_[_ZNSt6threadC5IRKZN3igl12parallel_forIiZNS1_12parallel_forIiZNS1_20squared_edge_lengthsIN5Eigen6MatrixIdLin1ELin1ELi0ELin1ELin1EEENS6_IiLin1ELin1ELi0ELin1ELin1EEENS6_IdLin1ELi3ELi0ELin1ELi3EEEEEvRKNS5_10MatrixBaseIT_EERKNSA_IT0_EERNS5_15PlainObjectBaseIT1_EEEUliE0_EEbSB_RKSF_mEUlmE_ZNS3_IiSN_EEbSB_SP_mEUlimE0_SQ_EEbSB_SP_RKSK_RKT2_mEUliimE_JRiRKiRmEEEOSB_DpOT0_]+0xc6): undefined reference to `pthread_create'
/tmp/ccsLLsPg.o: In function `_ZNSt6threadC1IRKZN3igl12parallel_forIlZNS1_12parallel_forIlZNS1_10doubleareaIN5Eigen6MatrixIdLin1ELi3ELi0ELin1ELi3EEENS6_IdLin1ELi1ELi0ELin1ELi1EEEEEvRKNS5_10MatrixBaseIT_EENSA_6ScalarERNS5_15PlainObjectBaseIT0_EEEUliE_EEbSA_RKSG_mEUlmE_ZNS3_IlSJ_EEbSA_SL_mEUllmE0_SM_EEbSA_SL_RKT1_RKT2_mEUlllmE_JRlSX_RmEEEOSA_DpOT0_':
t1.cpp:(.text._ZNSt6threadC2IRKZN3igl12parallel_forIlZNS1_12parallel_forIlZNS1_10doubleareaIN5Eigen6MatrixIdLin1ELi3ELi0ELin1ELi3EEENS6_IdLin1ELi1ELi0ELin1ELi1EEEEEvRKNS5_10MatrixBaseIT_EENSA_6ScalarERNS5_15PlainObjectBaseIT0_EEEUliE_EEbSA_RKSG_mEUlmE_ZNS3_IlSJ_EEbSA_SL_mEUllmE0_SM_EEbSA_SL_RKT1_RKT2_mEUlllmE_JRlSX_RmEEEOSA_DpOT0_[_ZNSt6threadC5IRKZN3igl12parallel_forIlZNS1_12parallel_forIlZNS1_10doubleareaIN5Eigen6MatrixIdLin1ELi3ELi0ELin1ELi3EEENS6_IdLin1ELi1ELi0ELin1ELi1EEEEEvRKNS5_10MatrixBaseIT_EENSA_6ScalarERNS5_15PlainObjectBaseIT0_EEEUliE_EEbSA_RKSG_mEUlmE_ZNS3_IlSJ_EEbSA_SL_mEUllmE0_SM_EEbSA_SL_RKT1_RKT2_mEUlllmE_JRlSX_RmEEEOSA_DpOT0_]+0xd5): undefined reference to `pthread_create'
/tmp/ccsLLsPg.o:t1.cpp:(.text._ZNSt6threadC2IRKZN3igl12parallel_forIlZNS1_12parallel_forIlZNS1_10doubleareaIN5Eigen6MatrixIdLin1ELi3ELi0ELin1ELi3EEENS6_IdLin1ELi1ELi0ELin1ELi1EEEEEvRKNS5_10MatrixBaseIT_EENSA_6ScalarERNS5_15PlainObjectBaseIT0_EEEUliE_EEbSA_RKSG_mEUlmE_ZNS3_IlSJ_EEbSA_SL_mEUllmE0_SM_EEbSA_SL_RKT1_RKT2_mEUlllmE_JRlRKlRmEEEOSA_DpOT0_[_ZNSt6threadC5IRKZN3igl12parallel_forIlZNS1_12parallel_forIlZNS1_10doubleareaIN5Eigen6MatrixIdLin1ELi3ELi0ELin1ELi3EEENS6_IdLin1ELi1ELi0ELin1ELi1EEEEEvRKNS5_10MatrixBaseIT_EENSA_6ScalarERNS5_15PlainObjectBaseIT0_EEEUliE_EEbSA_RKSG_mEUlmE_ZNS3_IlSJ_EEbSA_SL_mEUllmE0_SM_EEbSA_SL_RKT1_RKT2_mEUlllmE_JRlRKlRmEEEOSA_DpOT0_]+0xd5): more undefined references to `pthread_create' follow
collect2: error: ld returned 1 exit status

**Comment by jdumas** [comment]
You need to link with `pthread` on linux/macos (`-lpthread`).

**Comment by skulumani** [comment]
So simply. Thank you!
