### ISSUE TITLE
Compilation Error for Eg, 102....while Eg. 101 working fine...

### ISSUE THREAD

**Issue by ManikaBindal** [libigl/libigl#548]
Please suggest what to do?

I have installed GLFW/glfw3.h in /usr/include/

However, example 102 is not compiling. 
I tried like copy pasting the code in t1.cpp file
then

Input:
 $ g++ -std=c++11 -I /usr/include/ -I ./libigl/include -pthread  t1.cpp -o t1exec

Output: [error]

In file included from ./libigl/include/igl/viewer/Viewer.h:164:0,
                 from t1.cpp:2:
./libigl/include/igl/viewer/Viewer.cpp: In member function ‘int igl::viewer::Viewer::launch_init(bool, bool)’:
./libigl/include/igl/viewer/Viewer.cpp:948:59: error: ‘glfwSetCharModsCallback’ was not declared in this scope
     glfwSetCharModsCallback(window,glfw_char_mods_callback);
                                                           ^
./libigl/include/igl/viewer/Viewer.cpp:949:50: error: ‘glfwSetDropCallback’ was not declared in this scope
     glfwSetDropCallback(window,glfw_drop_callback);

**Comment by danielepanozzo** [comment]
I suggest to follow the instructions in the tutorial: http://libigl.github.io/libigl/tutorial/tutorial.html#chapter1:introductiontolibigl

It is important that:
1. you use the --recursive option to clone it
2. you use cmake to create the makefile

**Comment by ManikaBindal** [comment]
Thanks for replying...Using cmake it is working...My question is why I am unable to compile it when using it in a header only mode..???

**Comment by danielepanozzo** [comment]
Only the core of igl works in header-only mode. If you use functions in any of the subfolders (such as "viewer"), you have to link against the corresponding dependencies. For the case of the viewer, it glfw, opengl, and glew.
