### ISSUE TITLE
Animation / Redraw callback without moving the mouse

### ISSUE THREAD

**Issue by TsubameDono** [libigl/libigl#550]
Hi,

Firstly, thank you for this magnificent library ! Really, it's cool !

I have built a plugin which makes an animation by interpolating points between two meshes as a two state machine.
And it's working well, until I stop moving my mouse to force the redraw callback.
Is it possible to force the redraw by sending signals or to set a framerate for libigl windows ?

Thanks you in advance for your answers.

**Comment by etrigger** [comment]
Hi,

I have a similar problem.
I load a sequence of obj files into a vector of a matrix and I update the corresponding matrix in the prepre_draw. I have to keep moving the mouse such that prepre_draw can be called.

I hope there is some way to force calling the prepre_draw function.

**Comment by alecjacobson** [comment]
viewer.core.is_animating = true;

**Comment by TsubameDono** [comment]
Thanks you ! And it is embarrassing how simple the answer is.
