### ISSUE TITLE
Usage of flat coordinates in lscm.cpp

### ISSUE THREAD

**Issue by jmespadero** [libigl/libigl#552]
Hi,

I am trying to simplify the code in `igl::lscm(V,F,b,bc,V_uv)` method.

From my understanding, you are computing V_uv using "flat coordinates" technique,
so if you have 1k vertex, you will compute the 1k UV coordinates as a 2k double
vector.

To work in this way, you need to compute:
* `vector_area_matrix(F,A)`, which is not really the [vector area Matrix](https://en.wikipedia.org/wiki/Vector_area) , but a doubled-size matrix. ready to be multiplied by a "flatten version" of UV.
* `repdiag(L,2,L_flat)`, which is an "extended Laplacian" built as the Kronecker product of cotMatrix L. 
* A "flatten version" of b, which is a vector of 2 * numVertex elements.
* etc..

So you compute W_flat solution and then "unflat" it into V_uv

And the question is...

It is not possible to create a matrix `SparseMatrix<double> Q = -L + 2.*A;` of size numVertex x numVertex, and solve directly the V_uv (a matrix numVertex x 2)? 

Wouldn't it generate a smaller (and probably even faster) code? 
Or maybe I am missing something...

Regards

**Comment by alecjacobson** [comment]
Have a look at the original papers (Desbrun's or Levy's). The _insight_ of these papers was that the linear dependence between the u and v coordinates is essential to creating an as-conformal-as-possible map. So, no, it is not possible to solve for each coordinate function independently.

**Comment by jmespadero** [comment]
Thanks.
