### ISSUE TITLE
how to design a rosy field? 

### ISSUE THREAD

**Issue by Ahbee** [libigl/libigl#56]
In other apps I have seen the the user is asked to specify singularities , and the then the rosy field is generated.  But in libigl It seems like you have specify to faces and direction vectors to design a field.

Unfortunately I dont understand what that direction vector means or what coordinate space the vector it is in. Can anyone please help me thanks :smile:.  Is it possible to specify singularities?

**Comment by danielepanozzo** [comment]
It is not possible to specify singularities right now. To specify the directions, the vectors should be in global coordinates, you can take a look here for a basic example that fixes only one face: http://libigl.github.io/libigl/tutorial/tutorial.html#505

**Comment by Ahbee** [comment]
Thanks I was confused because the vector is 3d but the surface is 2d. But the projection makes sense.
