### ISSUE TITLE
CSGTree constructor problems

### ISSUE THREAD

**Issue by digitalwannabe** [libigl/libigl#560]
From a plugin I'm doing for a c# app I'm calling a c++ dll implementing CSGTree operations. In c++ I'm retrieving (meshes and) a string from C# (eg.: "0 0 1 union union 0 1 intersect minus"), then I use a vector<CSGTree> stack to deconstruct the expression.

`vector<CSGTree> CSG_Stack;`

If the string element is an operand, I construct a CSGTree like so:

```
MatrixXd VertexOperand = //set to values of operand mesh
MatrixXi IndexOperand = //set to values of operand mesh

const CSGTree operand = { VertexOperand, IndexOperand };
CSG_Stack.push_back(operand);
```
which works fine; but in case the string element is an operator, eg "union", I'm setting CSGTrees from stack and try to construct a new one like so:

```
const CSGTree rightOperand = CSG_Stack.back();
CSG_Stack.pop_back();
const CSGTree leftOperand = CSG_Stack.back();
CSG_Stack.pop_back();
//opElement is a string containing one of "union", "intersect", etc.
const CSGTree fullOp = { leftOperand, rightOperand, opElement };	//this line fails	
CSG_Stack.push_back(fullOp);
```
but this fails, giving me a memory access error in the c# app. Am I missing something, shouldn't this work? Unfortunately I don't have many options at hand to debug this in the c# app I'm using.

Sorry if there's an obvious c++ specific mistake I'm making which is unrelated to CSGTree- if so, please just let me know and I'll bring this over to stackoverflow etc.

Thank you!

for reference here's the full c++ code 
[src.zip](https://github.com/libigl/libigl/files/1119453/src.zip)

**Comment by alecjacobson** [comment]
did you find an answer to this?

**Comment by digitalwannabe** [comment]
hi, thanks for coming back to me!
The code I posted here is just fine, that's why I simply closed this. It turned out the array I was giving to my c++ dll from c# was corrupt already due to some parsing error elsewhere...sorry for stealing your time on this....
Here's the release:
https://vvvv.org/contribution/boolean-geometry

For reference, here's a link to the full source code of my c# (vvvv) plugin as well as the c++ side (libigl implementation; in folder src):
https://github.com/digitalwannabe/vvvv-sdk/tree/develop/vvvv45/addonpack/src/nodes/plugins/3d/3dConstructiveSolidGeometryTree
