### ISSUE TITLE
libigl uses freopen reading files

### ISSUE THREAD

**Issue by ankorus** [libigl/libigl#562]
Reading STL (or OBJ), or other files libigl uses freopen extensively in a manner:
freopen(NULL, “rb”, stream)
While working fine on OSX and Linux such calls return NULL on Windows failing reading ops!

**Comment by danielepanozzo** [comment]
Is there a tutorial example where this problem can be reproduced?

**Comment by ankorus** [comment]
typedef Eigen::Matrix<float, Eigen::Dynamic, 3, Eigen::RowMajor> EVertices;
typedef Eigen::Matrix<int, Eigen::Dynamic, 3, Eigen::RowMajor> EFaceIndices;

void loadModelFile(const std::string& fileName)
{
    EVertices meshVertices;
    EFaceIndices meshIndices;
    EVertices meshNormals;

    igl::readSTL(fileName, meshVertices, meshIndices, meshNormals);
}
Sure, the code snippet above compiled with Visual Studio 2015 and run on MS Windows 10 results in empty mesh. freopen(NULL, “rb”, stream) on Windows returning NULL seems to be a known issue (just try googling it)...

**Comment by danielepanozzo** [comment]
I see, thanks for the snippet. Do you know what the fix should be? It would be great if you could prepare a PR with the patch.
