### ISSUE TITLE
CMake improvements

### ISSUE THREAD

**Issue by jdumas** [libigl/libigl#563]
Hi there,

I believe libigl's CMake scripts could be modernized a bit, to facilitate integration into other new project, projects with large codebase, etc. The problem with the current `shared/cmake/CMakeLists.txt` is that it is a bit too monolithic: all the definitions are pulled under `LIBIGL_DEFINITIONS`, etc. By having transitive per-target properties, we can greatly simplify the way those options are handled on a *per target basis*.

I had a go at the [libigl-example-project](https://github.com/jdumas/libigl-example-project) to illustrate my proposition. Now using `libigl` becomes as simple as this (the whole [`CMakeLists.txt`](https://github.com/jdumas/libigl-example-project/blob/master/CMakeLists.txt) has been drastically reduced):

```cmake
target_link_libraries(${PROJECT_NAME}_bin igl::core igl::viewer)
```

Some of the features in the new [`libigl.cmake`](https://github.com/jdumas/libigl-example-project/blob/master/cmake/libigl.cmake) script I made:

- Starting from version 3.3, Eigen provides a `Eigen3Config.cmake` file. Idk if you want to use this or not, but at least I think the user should be able to use their own version of Eigen (when including libigl in a larger codebase, you may have different package that need different versions of Eigen, and it can get messy).
- Starting from CMake 3.8, we can impose C++11 standard as a transitive per-target property with `target_compile_features(my_target cxx_std_11)`
- Since CMake 3.8, `find_package(OpenGL)` also provides an imported target `OpenGL::GL`.
- Most directories are included as `SYSTEM` directories. This is a trick to disable all warnings coming from those (on UNIX at least, I don't know about Windows). This should not be taken as an incentive to take bad habits, but I this the user couldn't care less about warnings which are *not* coming from their code.
- The rest is pretty much no surprise, but I still define alias targets in the form `igl::module` because I think it looks nice :-)
- With this approach, I would suggest passing all the default options to `ON` (possibly with a `set_target_properties(my_target PROPERTIES EXCLUDE_FROM_ALL TRUE)` to prevent `make` from compiling modules which are not used in a project). The advantage is that you could get rid of [the corresponding options](https://github.com/jdumas/libigl-example-project/blob/81587647d58b08a290bb867f35aed350b67163c7/CMakeLists.txt#L8) in the root `CMakeLists.txt`.

Now, I've only done this change for the main lib + the viewer module, but I believe we could extend this to all the libigl modules, if you think this is worth it. One could put it in a file called `shared/cmake/libigl.cmake` to preserve compatibility with older projects, with a warning message.

**Comment by jdumas** [comment]
Starting from version 3.9, CMake will also provide imported targets for [OpenMP](https://cmake.org/cmake/help/v3.9/module/FindOpenMP.html). The modern way to compile with OpenMP accross platform now becomes:

```cmake
find_package(OpenMP QUIET)
if(OpenMP_CXX_FOUND)
	target_link_library(mylib PUBLIC OpenMP::OpenMP_CXX)
endif()
```

No more messing around with `CMAKE_CXX_FLAGS` and `CMAKE_C_FLAGS`!

**Comment by danielepanozzo** [comment]
Hi Jeremie, thanks for starting this! I will take a look at it this week and give feedback. At a first look, it seems the way to go, but I want to be sure that there will not be some hidden problems on other platforms. Did you already test it on win, mac, and linux?

**Comment by jdumas** [comment]
Not yet, but I can easily test on Windows. The main "problem" with this approach is that some features require CMake 3.8, but Ubuntu and Debian are stuck with CMake 3.7 for now (CMake 3.8 will be in the next Ubuntu release in October, but it may take more time to arrive in Debian). And CMake 3.9 in still in RC so it's not even in Archlinux repositories yet.

Also, last week I discovered that CGAL now provides imported targets. I don't know why they didn't update their doc, but using CGAL in a projet now becomes as simple as:

```cmake
# CGAL library
find_package(CGAL REQUIRED COMPONENTS Core)
target_link_libraries(my_lib CGAL::CGAL)
```


Anyway, my suggestion would be to keep the old cmake file alongside the new one, to make sure that the transition goes smoothly for everyone.

**Comment by danielepanozzo** [comment]
Mmm I am reluctant to put CMake 3.8 (or even worse 3.9) as a requirement, and I am also reluctant to have two set of cmake files (difficult to maintain and to keep synced up). @alecjacobson: what do you think?

Maybe we could keep this as a separate branch for now? Or simply wait for a few more months until the new cmake will be the default on most distributions.

**Comment by jdumas** [comment]
We can use the older (but more verbose) alternative and keep the minimum required CMake version to 3.7.

The most interesting feature of CMake 3.8 is I think the meta compile feature `cxx_std_11`, which properly impose C++11 standard in a transitive manner (compared to the target property [`CXX_STANDARD`](https://cmake.org/cmake/help/v3.1/prop_tgt/CXX_STANDARD.html) introduced in CMake 3.1 which is *not* transitive). There are of course workarounds before CMake 3.8, such as the one proposed by this [SO answer](https://stackoverflow.com/questions/29687331/how-to-define-transitive-cxx-standard-c11-in-cmake), which I think would be the most robust alternative prior to CMake 3.8.

For the other features I mentioned that require CMake 3.8 (OpenGL imported target) and 3.9 (OpenMP imported targets), I think it may be enough to copy the `FindPackage.cmake` from the [latest CMake version](https://github.com/Kitware/CMake/tree/master/Modules) into libigl's repository.

The rest of the modifications I proposed should work fine with CMake 3.7 (or even with CMake 3.1).

**Comment by alecjacobson** [comment]
Besides being more modern, could you list the benefits of making this
change?

**Comment by jdumas** [comment]
I can think of several advantages:

1. The primary benefit is a much easier setup for projects that use libigl. Just link against the module you need and bam, you're all setup. This also means it gets much easier to handle dependencies. You don't need to link against `${LIBIGL_EXTRA_LIBRARIES}` that you don't need.
2. The second important aspect is that it doesn't clutter your global compilation flags. The current file does a decent job in that area (I only see a few global `set(CMAKE_CXX_FLAGS ...)`, and the `include(${CGAL_USE_FILE})` which are polluting the global  compilation settings). This allows different modules to pull different compilation flags (such as defines and compile options), e.g. you can compile different modules with different compilation flags (or even compile the same file with different flags depending on which target it belongs to). You also have a more fine-grain control over what properties are PRIVATE or PUBLIC (public ones will get transitively exported, while private ones stay confined to your library's compilation units --- but it is not so relevant for header-only libraries such as libigl). 
3. Another minor point in using imported targets over cmake variables, is that if a parent cmake has already defined said target, the imported target won't be overridden (i.e. you will use the one defined by the parent cmake script). This would ensure that your whole program uses the same version of a lib (e.g. eigen), but ultimately it is the user's responsibility to ensure they are not messing around too much. You may see that as an advantage or an inconvenient.
4. Finally, since it simplifies the cmake script, I think it makes maintenance easier.

To me the first two are the real selling points of this new target-based paradigm.

**Comment by alecjacobson** [comment]
Can you help me understand #1 a bit more? What's the "before" and "after"
look like for somebody integrating libigl into their cmake project?

**Comment by jdumas** [comment]
Compared to the CMake script of the [`libigl-example-project`](https://github.com/libigl/libigl-example-project/blob/master/CMakeLists.txt) I forked from, and [the one](https://github.com/jdumas/libigl-example-project/blob/master/CMakeLists.txt) I came up with, you:
- Don't have to specify compilation flags specifics to libigl (such as C++11, `/bigobj`, etc.), as those would be pulled as part of each target properties.
- Don't need to specify most of the `option(LIBIGL_WITH_WHATEVER  "Use whatever" OFF)` to enable a certain module: if you don't want to compile a specific module, then don't link against it!
- Those [2](https://github.com/libigl/libigl-example-project/blob/master/CMakeLists.txt#L69) [lines](https://github.com/libigl/libigl-example-project/blob/master/CMakeLists.txt#L70) `include_directories` and `add_definitions` become unnecessary, as those are pulled again from their respective targets (when you do link the target with [`target_link_libraries()`](https://github.com/jdumas/libigl-example-project/blob/master/CMakeLists.txt#L16)). You also don't have to think about linking against any extra library `LIBIGL_EXTRA_LIBRARIES` (e.g. if you are using `nanogui` with the viewer).

**Comment by alecjacobson** [comment]
Thanks. So, I'm convinced of the value of this change. What about the
downsides? Is the only issue that it requires a fairly modern cmake? Do we
have a sense of how (un)reasonable that requirement is?

**Comment by jdumas** [comment]
I think most of it requires only CMake 3.1 (for `target_compile_features`), or 3.0 (for INTERFACE targets, i.e targets without source files to compile, but that can carry various properties --- useful for header-only libraries). The points I mentioned above that require CMake newer that 3.7 can easily be circumvented.

In Debian/Ubuntu the latest version of CMake is 3.7, so I guess it's a fairly reasonable requirement. On Windows people can easily get the latest version of CMake, and on brew/macports seems that cmake is already at 3.8. It seems that CMake 3.1 was introduced around 2 years ago, so it depends how old you want your support to stretch.

**Comment by jdumas** [comment]
So I've started to integrate this stuff my fork of `libigl`, on the [cmake](https://github.com/jdumas/libigl/tree/cmake) branch. It's still work in progress and I need to make sure it compiles on Travis (which has recently updated their Ubuntu image to [Trusty](https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming?utm_source=web&utm_medium=banner&&utm_campaign=trusty-default) btw), but it shouldn't be too hard. Let me know if I should do an open PR now, or only once I'm done (which may take some time).

**Comment by danielepanozzo** [comment]
Please open the PR once it is finished. Thanks a lot!

**Comment by decrispell** [comment]
My 2 cents: If you're interested in supporting Ubuntu distributions, I suggest that you don't require a cmake that is newer than the version included in the latest LTS release (currently Ubuntu 16.04).  That means CMake version 3.5.1.

**Comment by jdumas** [comment]
CMake-wise it's gonna be working with CMake 3.2, possibly even 3.1, so I wouldn't be too worried about that.

**Comment by jdumas** [comment]
Hi,

This is still a work in progress on my fork, but I wanted to discuss another possible change.

Basically, the idea is to get rid of most of the CMake options that selectively compile different libigl modules, since we will now have a more fine-grained control over what is pulled when we link to a libigl module.

Take the example of Mosek: instead of having an CMake option `LIBIGL_WITH_MOSEK`  to compile the mosek module, CMake script will create a target`igl::mosek` for the module only if the library is found (i.e. if we get `${MOSEK_FOUND}` after calling `find_package(MOSEK)`). The check to see if the module is available would be done as follows (see [example 403](https://github.com/jdumas/libigl/blob/f73a8f22127dc4781fbca6d6f95592458c107fd1/tutorial/403_BoundedBiharmonicWeights/CMakeLists.txt#L6) in the tutorials):

```cmake 
if(TARGET igl::mosek)
  target_link_libraries(${PROJECT_NAME}_bin igl::mosek)
endif()
```

Instead of (what is currently done):

```cmake
if(LIBIGL_WITH_MOSEK)
  target_link_libraries(${PROJECT_NAME}_bin ${LIBIGL_MOSEK_EXTRA_LIBRARIES})
endif()
```

This mean that the current CMake script for the `igl::mosek` module would be changed from [this](https://github.com/jdumas/libigl/blob/f73a8f22127dc4781fbca6d6f95592458c107fd1/shared/cmake/libigl.cmake#L287):

```cmake
if(LIBIGL_WITH_MOSEK)
  find_package(MOSEK REQUIRED)
  compile_igl_module("mosek" "")
  target_link_libraries(igl_mosek ${IGL_SCOPE} ${MOSEK_LIBRARIES})
  target_include_directories(igl_mosek ${IGL_SCOPE} ${MOSEK_INCLUDE_DIRS})
  target_compile_definitions(igl_mosek ${IGL_SCOPE} -DLIBIGL_WITH_MOSEK)
endif()
```

To something like this:

```cmake
find_package(MOSEK)
if(MOSEK_FOUND)
  compile_igl_module("mosek" "")
  target_link_libraries(igl_mosek ${IGL_SCOPE} ${MOSEK_LIBRARIES})
  target_include_directories(igl_mosek ${IGL_SCOPE} ${MOSEK_INCLUDE_DIRS})
  target_compile_definitions(igl_mosek ${IGL_SCOPE} -DLIBIGL_WITH_MOSEK)
endif()
```

If that's ok, I think we could get rid of most of the options for the different modules that depend on a third-party library (anttweakbar, cgal, comiso, cork, embree, lim, matlab, mosek, nanogui, png, tetgen, triangle, xml).

**Comment by alecjacobson** [comment]
In general I like this. Probably there should still be an override flag.

One super annoying issue comes up with CGAL since calling its find_package
has bizarre side-effects.

**Comment by jdumas** [comment]
You mean an override to *not* create the module?

Regarding CGAL, I think only the `${CGAL_USE_FILE}` has super annoying effects. However, I recently found out that since CGAL 4.9, CGAL's `find_package` also offers imported target, meaning that you can use it without the `${CGAL_USE_FILE}`:

```cmake
if(LIBIGL_WITH_CGAL)
  # CGAL Core is needed for
  # `Exact_predicates_exact_constructions_kernel_with_sqrt`
  compile_igl_module("cgal" "copyleft/")
  find_package(CGAL REQUIRED COMPONENTS Core)
  find_package(Boost 1.48 REQUIRED thread system)
  target_link_libraries(igl_cgal ${IGL_SCOPE} CGAL::CGAL ${Boost_LIBRARIES})
endif()
```

Of course if there are still side-effects we will keep the `LIBIGL_WITH_CGAL` option, but I believe we can get around that.

**Comment by alecjacobson** [comment]
Yes, I think having on-off switches are useful. Some modules like Embree
take a while to compile and projects that don't use them shouldn't compile
them. Or will cmake be smart enough not to compile them if they're not
linked by the target?

It's great if we can get around the CGAL-cmake mess.

**Comment by jdumas** [comment]
One thing we can do is add the igl modules with the option [`EXCLUDE_FROM_ALL`](https://cmake.org/cmake/help/v3.0/command/add_library.html). That way they won't be compiled when you type `make` or `make all` by default, unless you compile another target that depends on it (otherwise you'll need to type `make igl_embree` explicitly). I don't know if `EXCLUDE_FROM_ALL` has any effect in Visual Studio however.

**Comment by danielepanozzo** [comment]
I think we should keep a way to manually disable some modules (and by disable I mean exclude from cmake entirely). Especially on windows (I know, windows is always the problematic one), it happens that cmake find some parts of CGAL but then fails to properly link. In these cases, having an option to disable manually the inclusion of CGAL is convenient.

**Comment by jdumas** [comment]
If the `igl::cgal` module is not built (because it is unused), then it won't have to be linked as well. We'd just need to check that the option `EXCLUDE_FROM_ALL` works as expected on Windows.
But I guess what can be problematic is for one to rely on the presence of the `igl::cgal` target to compile part of their code, but then find out it doesn't compile properly? (But then maybe it should be the end-user responsibility to enable/disable the cgal portion of *their* code?)

For the sake of simplificity, it doesn't hurt to keep the option anyway. However I vote to make them all `ON` by default, eventually using `EXCLUDE_FROM_ALL` to not bloat up the build time for unused targets.

**Comment by jdumas** [comment]
Ok so today I was taking a look at the `igl::png` module, and I would like to discuss the case of `stb_image` a little bit. As you may know, `stb_image` relies `STB_IMAGE_IMPLEMENTATION` to provide implementations of its different functions. However, those function should be defined in only one translation unit, otherwise you'll get in trouble.

The problem is that `nanovg` (by way of `nanogui`) already implements `stb_image` functions in its file `nanovg.c`. This obviously conflicts with the `igl::png` module if both are present at the same time. The [current solution](https://github.com/libigl/libigl/blob/1e01eb2b3d3a359891a82d4c721983dcc21a8449/shared/cmake/CMakeLists.txt#L425) works fine when you have a monolithic build, but is not very satisfying if you want to create independent targets that can be compiled on their own. To put it differently, I want to be able to use functions from the `igl::png` module without pulling all `nanogui` as a dependency (to implement `stb_image` functions), and I want to be able to use both `igl::png` functions and `nanogui` in my viewer in the same project.

Hopefully, I think there is a pretty good solution thanks to the [`-fvisibility=hidden`](https://gcc.gnu.org/wiki/Visibility) option (on Windows you don't need the option as it's arleady hidden by default). Basically, the idea is to compile a small [shared library](https://github.com/jdumas/libigl/blob/83dfc28ebc317fe1014a19ba96b2eedf34025ec3/external/stb_image/CMakeLists.txt) that hides its internal symbols, and to export only the relevant functions in the [`igl` namespace](https://github.com/jdumas/libigl/blob/83dfc28ebc317fe1014a19ba96b2eedf34025ec3/external/stb_image/igl_stb_image.h):

```cpp
#ifndef IGL_STB_IMAGE_H
#define IGL_STB_IMAGE_H

#include <igl_stb_image_export.h>

namespace igl {
  IGL_STB_IMAGE_EXPORT unsigned char * stbi_load(char const *filename, int *x, int *y, int *comp, int req_comp);
  IGL_STB_IMAGE_EXPORT void stbi_image_free(void *retval_from_stbi_load);
  IGL_STB_IMAGE_EXPORT int stbi_write_png(char const *filename, int w, int h, int comp, const void *data, int stride_in_bytes);
} // namespace igl

#endif
```

- **Pros**: No more clash with `nanogui`'s implementation of `stb_image`, we can use both in the same code. Also no risk of clashing with a user's implementation of `stb_image`!
- **Cons**: Depends on CMake (still 3.1) to take care of the logistics of compiling the small shared library with hidden symbols and exported functions. But then again, I don't think it was possible to use `igl/png` without CMake before anyway.

**Comment by danielepanozzo** [comment]
Sounds like a great solution to me, the Cons is minor, we are depending on cmake already for igl/png.

**Comment by jdumas** [comment]
Hi everyone,

I have finished updating the CMake script for all the libigl modules, and it seems that things are working fine (at least as fine as before). I have updated all the tutorials and the Python bindings to use the new build system. I can do the PR request now if you want to review the changes.

The result is available in the `cmake` branch of my [libigl mirror](https://github.com/jdumas/libigl/tree/cmake), and you can see an example of how to use it in the `cmake` branch of my [libigl-example-project mirror](https://github.com/jdumas/libigl-example-project/tree/cmake).

I summarize below the summary of my changes (tl;dr the only kinks left are issues already present with the current build on Mac and Windows, and an issue with Python and the new Travis Ubuntu image `trusty`).


### About the submodules
- I had to update the CoMISo submodule to make small changes to its `CMakeLists.txt`. I have thus changed the submodule url to my personal mirror, but feel free to change it back once you update the libigl mirror.
- The cork module works, but there is a the letter case issue in its `CMakeLists.txt` (it points to a `cmake/` subfolder, whereas the repo contains one name `CMake/`). Also, it probably shouldn't set the `-std=c++11` flag directly as it does right now (would probably not fly on Windows). If you want to update it, here is a [gist](https://gist.github.com/anonymous/7304b30360fb33bd0e88c083f2eec428) with a correct CMake script (I didn't bother to create another mirror).

### About the libigl modules
- I haven't tested the Matlab module, but changes were minimal so I don't expect any trouble.
- It doesn't look like AntTweakBar was working on Windows before (it was not enabled in the current build).

### About the CMake files
- I did only one small change to `cmake/shared/CMakeLists.txt`, due to the stb encapsulation for the igl_png module as discussed above, so that the update doesn't break any existing project.
- Why use a custom `FindMATLAB.cmake` when there is one provided by CMake itself? Does it not work?
- With `cork` included as a submodule of libigl, I don't know if you want to keep the `FindCORK.cmake` file. It should be safe to remove it.

### About the CI build
- Travis is switching its linux vm from `precise` to `trusty`. See details [here](https://blog.travis-ci.com/2017-08-31-trusty-as-default-status).
- On the new `trusty` image, there is an issue with the Python bindings, which fails on import with the following error:
  ```
  ImportError: /home/travis/build/jdumas/libigl/python/tutorial/../pyigl.so: undefined symbol: PyInstanceMethod_Type
  ```
  See [this build](https://travis-ci.org/jdumas/libigl/builds/273133872) that shows the problem on the main libigl tip. Note that Travis has finished to switch all repository to default to using `dist: trusty` as of September 1, so it is likely that you will have the same issue next time you commit something in libigl.
- On the old `precise` image, Nanogui was not compiling properly (there is some weird error about OpenGL). The problem already exists on the libigl main branch, but you don't see it because Nanogui is not enabled in the CI build.
- The Python module was not tested on Mac nor Windows in the previous CI build, so I haven't tried it either.
- The Embree module compiles on Mac/Windows only when Nanogui is disabled. Because the Nanogui cmake script seems to have some underisable side-effects, it is disabled by default in the new CMake build.
- It seems that AntTweakBar does not currently compile on Windows either, so it is also disabled by default.
- I have summarized the above discussion in the following table:

| Module      | Precise | Trusty | Mac | Windows |
|-------------|---------|--------|-----|---------|
| Embree      | Yes     | Yes    | Yes*| Yes*    |
| Nanogui     | No      | Yes    | Yes | Yes     |
| AntTweakBar | Yes     | Yes    | Yes | No      |
| Python      | Yes     | No     | ?   | ?       |

*: Compiles when Nanogui is disabled.

In the end, the *errors* that remain are issues/incompatibilities which are already present with the current CMake build of libigl, so I don't really know how to fix them.

**Comment by jdumas** [comment]
@alecjacobson @danielepanozzo Did you have any time to look into this? Shall I make the PR so that you can more easily review the changes I made?

**Comment by jdumas** [comment]
Ok so FYI following @alecjacobson's suggestion I've also updated the [libigl-unit-tests](https://github.com/jdumas/libigl-unit-tests/tree/cmake) repository to use the new build system as well. I've had to update the googletest framework, ditch a bunch of stuff in the build script that I think had become superfluous, and update a couple of minor things in libigl proper, but now the unit tests are also [passing on Travis with the new build](https://travis-ci.org/jdumas/libigl-unit-tests/builds/284492727) =)

**Comment by alecjacobson** [comment]
Thanks! Could you create a PR for that?

What's left on this issue? @danielepanozzo should we merge these?

**Comment by jdumas** [comment]
Closing as this is now merged =)

**Comment by alecjacobson** [comment]
Yay!
