### ISSUE TITLE
remesh_self_intersections(): Associating attributes with the faces 

### ISSUE THREAD

**Issue by pranavkantgaur** [libigl/libigl#566]
Hi,

I am using igl::copyleft::cgal::remesh_self_intersections(). I would like to know if we have any provision to associate attributes(for example, boundary tag information) with each input face and to be able to preserve it across the function call?

**Comment by alecjacobson** [comment]
Take a look at the `J` and `IM` outputs. These reveal the originating input triangles of each output triangle. So if you have data stored on the input triangles you can transfer that onto the outputs.

**Comment by pranavkantgaur** [comment]
Thanks for your quick response. `J` does solve my problem. However, I am not sure what `IM` is supposed to represent?
The in-line comment(`remesh_self_intersections.h`) states: 

> IM  #VV list of indices into VV of unique vertices.

Like `J`, does it map each vertex in `VV` to a vertex(unique?) in the input `V`?
