### ISSUE TITLE
valid inputs for LSCMParam and ARAPParam...?

### ISSUE THREAD

**Issue by digitalwannabe** [libigl/libigl#569]
I've recently implemented CSGTree/mesh_boolean and would now like to compute texture coordinates- also eg for surface meshes generated from point sets with tetgen.

I got LSCM(502) and ARAP(503) up and running with the camelhead example, but it fails almost any other model I feed to it: I've tried very simple geometry like a box (2 triangles per side), a sphere, a torus and different outputs coming from csgTree, like the intersection of 2 spheres, but no luck. 
The only other model which worked so far was a cylinder.
So I wonder if there's special requirements for meshes with the LSCM/ARAP algorithms? 
Or, to put this differently, what's the best technique to compute texture coordinates for *any* model coming out of csgTree or TetGen?

thank you!

**Comment by alecjacobson** [comment]
Both of these methods assume that you have already "cut" your mesh so that it is topologically equivalent to a disk (or more generally to a finite subregion of the plane like an annulus, or two disks).
