### ISSUE TITLE
The result of mesh boolean is not "neat"

### ISSUE THREAD

**Issue by candycat1992** [libigl/libigl#57]
Hi,
recently I used the mesh boolean operations to combine some .obj files. But I found that the resulted mesh of "union" had some unexpected triangles. 
In my case, the resulted mesh had a weird triangle which just connected with a single neighbor triangle.
The below image shows the conjunction of two meshes: 
![2015-04-14 14 48 53](https://cloud.githubusercontent.com/assets/5907064/7131851/47883918-e2b6-11e4-97e4-7b6a1aeed873.png)
And the weird triangle (marked using red color):
![2015-04-14 14 49 37](https://cloud.githubusercontent.com/assets/5907064/7131911/c8eb3ef6-e2b6-11e4-9f60-87f50a83fcc8.png)
![2015-04-14 14 49 44](https://cloud.githubusercontent.com/assets/5907064/7131912/c8f0dba4-e2b6-11e4-9407-92c8245bd6c7.png)
Just one edge of the triangle is connected with others, and the remians are floating.

I wonder if this is a bug or something?

**Comment by alecjacobson** [comment]
Can you include your inputs? Then I'll try to debug.

**Comment by candycat1992** [comment]
@alecjacobson 
Thanks for your attention.

Here are the two meshed:
[A.obj](https://drive.google.com/file/d/0BwWDClXCK5C1ckh2c1BNSFpWQzQ/view?usp=sharing)
[B.obj](https://drive.google.com/file/d/0BwWDClXCK5C1b01vMExwTEdLUHc/view?usp=sharing)

I use MESH_BOOLEAN_TYPE_UNION to combine them.

And use the code below to test the integrity:
```c++
struct MeshVertex
{
    MeshVertex() : edge(-1) {}

    int edge; //an edge such that edge->prev->vertex is this
};

struct MeshEdge
{
    MeshEdge() : vertex(-1), prev(-1), twin(-1) {}

    int vertex; //the vertex the edge points to--the start vertex is prev->vertex
    int prev; //ccw, next is prev->prev
    int twin;
};

void ComputeTopology(const Eigen::MatrixXd &V, const Eigen::MatrixXi &F,
                     vector<MeshVertex> &vertices, vector<MeshEdge> &edges) {
    vertices.clear();
    vertices.resize(V.rows());
    edges.clear();
    edges.resize(F.rows()*3);

    int i, j;
    for(i = 0; i < (int)edges.size(); ++i) {
        edges[i].vertex = F.row((int)floor(i / 3))[i % 3];
        edges[i].prev = (i - i % 3) + (i + 2) % 3;
    }

    vector<map<int, int> > halfEdgeMap(vertices.size());
    for(i = 0; i < (int)edges.size(); ++i) {
        int v1 = edges[i].vertex;
        int v2 = edges[edges[i].prev].vertex;
        vertices[v1].edge = edges[edges[i].prev].prev; //assign the vertex' edge

        if(halfEdgeMap[v1].count(v2)) {
            cout << "Error: duplicate edge detected: " << v1 << " to " << v2 << " Related faces:" << halfEdgeMap[v1][v2] << " " << i << endl;
            continue;
        }
        halfEdgeMap[v1][v2] = i;
        if(halfEdgeMap[v2].count(v1)) {
            int twin = halfEdgeMap[v2][v1];
            edges[twin].twin = i;
            edges[i].twin = twin;
        }
    }
}

#define CHECK(pred) { if(!(pred)) { cout << "Mesh integrity error: " #pred << " in line " << __LINE__ << endl; } }
bool IntegrityCheck(Eigen::MatrixXd &V, Eigen::MatrixXi &F, vector<MeshVertex> &vertices, vector<MeshEdge> &edges) {
    int i, j;
    int vs = vertices.size();
    int es = edges.size();

    if(vs == 0) { //if there are no vertices, shouldn't be any edges either
        CHECK(es == 0);
        return true;
    }

    CHECK(es > 0); //otherwise, there should be edges

    //check index range validity
    for(i = 0; i < vs; ++i) {
        CHECK(vertices[i].edge >= 0);
        CHECK(vertices[i].edge < es);
    }

    vector<int> singleEdges;
    for(i = 0; i < es; ++i) {
        CHECK(edges[i].vertex >= 0 && edges[i].vertex < vs);
        CHECK(edges[i].prev >= 0 && edges[i].prev < es);
        CHECK(edges[i].twin >= 0 && edges[i].twin < es);
        if (!(edges[i].twin >= 0 && edges[i].twin < es)) {
            singleEdges.push_back(i);
        }
    }

    vector<int> invalidEdges;
    //check basic edge and vertex relationships
    for(i = 0; i < es; ++i) {
        CHECK(edges[i].prev != i); //no loops
        CHECK(edges[edges[edges[i].prev].prev].prev == i); //we have only triangles
        CHECK(edges[i].twin != i); //no self twins
        CHECK(edges[edges[i].twin].twin == i); //twins are valid
        if (!(edges[edges[i].twin].twin == i)) {
            invalidEdges.push_back(i);
        }
        CHECK(edges[edges[i].twin].vertex == edges[edges[i].prev].vertex); //twin's vertex and prev's vertex should be the same
        if (!(edges[edges[i].twin].vertex == edges[edges[i].prev].vertex)) {
            invalidEdges.push_back(i);
        }
    }

    for(i = 0; i < vs; ++i) {
        CHECK(edges[edges[vertices[i].edge].prev].vertex == i); //make sure the edge pointer is correct
    }

    vector<pair<int,int> > invalidVertex;
    //check that the edges around a vertex form a cycle -- by counting
    vector<int> edgeCount(vs, 0); //how many edges adjacent to each vertex
    for(i = 0; i < es; ++i)
        edgeCount[edges[i].vertex] += 1;

    for(i = 0; i < vs; ++i) {
        int startEdge = vertices[i].edge;
        int curEdge = startEdge;
        int count = 0;
        do {
            curEdge = edges[edges[curEdge].prev].twin; //walk around
            ++count;
        } while(curEdge != startEdge && count <= edgeCount[i]);
        CHECK(count == edgeCount[i] && "Non-manifold vertex found");
        if (!(count == edgeCount[i]) && edgeCount[i]) {
            invalidVertex.push_back(pair<int, int>(i, edgeCount[i]));
        }
    }

    return true;
}
```

I got this output:
Error: duplicate edge detected: 4345 to 4346 Related faces:29287 29303
Mesh integrity error: edges[i].twin >= 0 && edges[i].twin < es in line 100
Mesh integrity error: edges[i].twin >= 0 && edges[i].twin < es in line 100
Mesh integrity error: edges[i].twin >= 0 && edges[i].twin < es in line 100
Mesh integrity error: edges[edges[i].twin].twin == i in line 112
Mesh integrity error: edges[edges[i].twin].vertex == edges[edges[i].prev].vertex in line 116
Mesh integrity error: edges[edges[i].twin].twin == i in line 112
Mesh integrity error: edges[edges[i].twin].vertex == edges[edges[i].prev].vertex in line 116
Mesh integrity error: edges[edges[i].twin].twin == i in line 112
Mesh integrity error: edges[edges[i].twin].vertex == edges[edges[i].prev].vertex in line 116
Mesh integrity error: count == edgeCount[i] && "Non-manifold vertex found" in line 140
Mesh integrity error: count == edgeCount[i] && "Non-manifold vertex found" in line 140
Mesh integrity error: count == edgeCount[i] && "Non-manifold vertex found" in line 140

**Comment by alecjacobson** [comment]
Thanks for sending the meshes. You're indeed running into a "known issue".
I'm currently working on this and will hope to have a fix soon. Keep
checking in!

**Comment by alecjacobson** [comment]
I’ve just pushed a potential fix. It works in your case. I’ll be debugging
these cases further, but if you git pull it might already fix things for
you (version >=1.1.5).
​

**Comment by candycat1992** [comment]
@alecjacobson 
Yeah, it works for now. It's kind of you! Thanks again.
