### ISSUE TITLE
Segmentation fault at OpenMP multithreaded 'readPLY' (readOBJ OK)

### ISSUE THREAD

**Issue by skanti** [libigl/libigl#573]
Hi,

when

```
#pragma omp parallel for
for (int i = 0; i < n; i++) {
     ...
     int success = igl::readPLY(filename, mesh1.V, mesh1.F);
     ...
}      
```       
then it spits out a `segmentation fault`. 

Some info:
- works fine multithreaded with `readOBJ`
- works fine serial
- `readPLY` is used in my case for binary `.ply`
                                                                                      
---

Smells like a bug. Can you provide a fix for this?  Thanks.

**Comment by alecjacobson** [comment]
Our ply reader is based on the original code which I believe is not
threadsafe due to global variables.
