### ISSUE TITLE
problem with principal curvatures

### ISSUE THREAD

**Issue by chbader** [libigl/libigl#58]
Hi,

first off, thanks for making this libary public.
I am having a problem with igl::principal_curvature using the code provided in example 203 and the attached model http://goo.gl/ZGTruh. I am getting an output of very small and all the same numbers (4.8367*10^26). 
I am working with visual studio 2012. 

Any idea what I am doing wrong?

Thanks

**Comment by alecjacobson** [comment]
Google seems to have canceled your short URL. Can you try to send the full link to the mesh?

**Comment by chbader** [comment]
Yes:
www.deskriptiv.de/OTHER/christoph/test.zip

**Comment by alecjacobson** [comment]
I'm worried something is wrong with your installation. When I run example 203 on this model I get sane values:

    H.maxCoeff() ---> 6.45997
    H.minCoeff() ---> -1.00281

Can you please verify that the mesh has been read in correctly? Is it rendering correctly? Did you change this example at all besides the input filename?
