### ISSUE TITLE
tutorial  mathematical formula 'transcoding error in browser?'

### ISSUE THREAD

**Issue by dingtiandu** [libigl/libigl#581]
I have tried chrome,ie,safari, the mathematical formula in  the libigl tutorial page  seems like having transcoding error.For example,in chapter2 Laplacian,the formula looks like this:\(\Delta f = \frac{\partial^2 f}{\partial x^2} + \frac{\partial^2 f}{\partial y^2} + \frac{\partial^2 f}{\partial z^2}.\)       and    \(L_{ij} = \begin{cases}j \in N(i) &\cot \alpha_{ij} + \cot \beta_{ij},\\ j \notin N(i) & 0,\\ i = j & -\sum\limits_{k\neq i} L_{ik}, \end{cases}\)......Is this  mathematical formula 'transcoding error in browser?'???Hope for replying.

**Comment by alecjacobson** [comment]
The math is converted at run time from LaTeX into symbols via javascript. You'll need javascript enabled and a working internet connection to view them.
