### ISSUE TITLE
Separate repository for python bindings

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#585]
I'd like to propose that we move the python bindings to a separate repository. This has a couple immediate advantages:

1. The python bindings can be frozen to a particular (stable) commit of the master branch of the libigl repo (via submodules),
2. Errors/omissions in the python bindings will not trigger automatic build errors on the main libigl branch, and
3. Build testing the main branch will be faster (currently the entire static library is built again to test the python bindings).

One possible disadvantage is that people will be less likely to find and use it. I wonder if it would be enough to place a prominent link near the top of the main repo's readme.

**Comment by danielepanozzo** [comment]
I vote for keeping them inside the main repo.

If we do this, it will be more likely that commits that break them will be pushed in the main library. It will be annoying to "bump up" the version of libigl used in the bindings, and they will thus lag behind. As a compromise, we could switch them to use a dynamic build to speed up the build time (I think it is already like this for the windows build).

Overall, I don't think the upside of this change will compensate the major disadvantages:
1. Not having them up to date "by default" with the main branch
2. Reducing their visibility by moving them in a different repo

**Comment by alecjacobson** [comment]
Is there a more systematic way to fix build issues in the python bindings? For example, there is [currently a python-related build error](https://travis-ci.org/libigl/libigl/jobs/264858961), but the error is not intelligible to me:

```
$ python 101_FileIO.py
Traceback (most recent call last):
  File "101_FileIO.py", line 5, in <module>
    import pyigl as igl
ImportError: /home/travis/build/libigl/libigl/python/tutorial/../pyigl.so: undefined symbol: _ZN3igl12signed_angleIN5Eigen5BlockIKNS1_6MatrixIfLin1ELi3ELi0ELin1ELi3EEELi1ELi3ELb0EEES6_NS3_IfLi1ELi2ELi1ELi1ELi2EEEEENT_6ScalarERKNS1_10MatrixBaseIS8_EERKNSA_IT0_EERKNSA_IT1_EE
```

> Clearly there's a missing symbol, probably just needs an explicit template instantiation, but unlike the c++ compile error I have no idea what template to add.

It's frustrating that these python errors are holding back commits to the main C++ library. I would rather that these are handled when the python bindings are "bumped up". So it seems natural for the python bindings to exist in a separate repo and have python users in charge of maintaining them. Otherwise all contributors to libigl (which is after all a C++ library) must also have to understand the python setup to fix python build errors.

How do other libraries handle this? Is there a good example to follow?

**Comment by danielepanozzo** [comment]
To debug these issues, you need to enable the option "-DCHECK_UNDEFINED=ON". I will add this option to the default travis builds. I am debugging this error on my fork, I will push a fix soon. It is likely a missing explicit template instantiation.

**Comment by jdumas** [comment]
I don't know how most libraries are doing, but I think until `libigl` gets a proper `pip` package that is easy to install (see discussion in #553), moving the Python bindings into a separate repository is probably the best way to ensure that nobody ever uses them.

> It's frustrating that these python errors are holding back commits to the main C++ library. I would rather that these are handled when the python bindings are "bumped up".

On the other hand, if you do that, it's gonna be a mess to track down what are the changes that broke the python bindings (*"oh, let me go through the last 50+ commits since I last updated the libigl submodule and figure out which commit broke the python build"*).
