### ISSUE TITLE
Build fail on Travis

### ISSUE THREAD

**Issue by jdumas** [libigl/libigl#588]
It seems that the current version of libigl fails to build on Travis with gcc, due a [weird error with Pybind11](https://travis-ci.org/libigl/libigl/jobs/265037839+0). Does anyone have an idea where this is coming from? Could it be a side-effect of Travis updating its Ubuntu image to [Trusty](https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming?utm_source=web&utm_medium=banner&&utm_campaign=trusty-default)?

**Comment by danielepanozzo** [comment]
Fixed it in the last commit.
