### ISSUE TITLE
Python support.

### ISSUE THREAD

**Issue by chrisidefix** [libigl/libigl#59]
It's not christmas, yet and easter just pasted, but I wish to see support for a Python interface to run libigl not only through C. It might actually not be too difficult to realize and could mostly be generate automatically. I might try to get something setup, if you guys agree that [Cython](http://cython.org) is the way to go here?

**Comment by alecjacobson** [comment]
Indeed, we'd like to do this and have a plan. But so far no one to execute
it.

**Comment by alecjacobson** [comment]
Python support is underway and will be rolled out shortly. You can track (and contribute to?) the early progress in the `igl/python` directory that now exists.
