### ISSUE TITLE
readPLY.h inline fuction error 

### ISSUE THREAD

**Issue by Adamwgoh** [libigl/libigl#593]
Hi there,

I'm using readPLY's readPLY function, and throws this error during compile time. Here is an example Cpp i created for it and the error given. Let me know if this suffice or more info is needed. Thanks !

```

#include <igl/readPLY.h>
#include <igl/viewer/Viewer.h>

int main (int argc, char* argv[])
{
  Eigen::MatrixXd V;
  Eigen::MtarixXd F;

  igl::viewer::Viewer viewer;
  igl::readPLY("Data/case1.ply", V, F);
  viewer.data.set_mesh(V, F);
  viewer.launch();

  return 0;
  
}
```

Error code : 

`/home/adamg/share/externalLib/libigl//include/igl/ply.h: At global scope:
/home/adamg/share/externalLib/libigl//include/igl/ply.h:232:13: warning: inline function ‘void ply_get_element(PlyFile*, void*)’ used but never defined [enabled by default]
 inline void ply_get_element(PlyFile *, void *);
             ^
make: *** [main.o] Error 1
`

**Comment by danielepanozzo** [comment]
Could you try to compile this snippet using the cmake file in https://github.com/libigl/libigl-example-project ? It is likely that you have some wrong compiler flags in your makefile.
