### ISSUE TITLE
error: calling protected constructor [hessian.cpp, hessian_energy.cpp]]

### ISSUE THREAD

**Issue by Luk0r** [libigl/libigl#595]
/git/libigl/include/igl/hessian.cpp:37: error: ‘Eigen::PlainObjectBase<Derived>::PlainObjectBase(const Eigen::DenseBase<OtherDerived>&) [with OtherDerived = Eigen::Matrix<double, -1, -1>; Derived = Eigen::Matrix<double, -1, -1>]’ is protected within this context
     igl::grad(Eigen::PlainObjectBase<DerivedV>(V),
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

same for line 37
and line 39 in hessian_energy.cpp

**Comment by xinyazhang** [comment]
Also found at AABB.cpp:404
``include/igl/AABB.cpp:404:45: error: ‘Eigen::PlainObjectBase<Derived>::PlainObjectBase(const Eigen::PlainObjectBase<Derived>&) [with Derived = Eigen::Matrix<float, 1, 3>]’ is protected within this context
       Eigen::PlainObjectBase<RowVectorDIMS> c_right = c;``

**Comment by Luk0r** [comment]
AABB.cpp can be fixed by changing line 404 to:
`RowVectorDIMS c_right = c; // compare line 395`

For the hessian stuff I just dropped the template instantiation at the end of the corresponding cpp files.

**Comment by danielepanozzo** [comment]
Could you please file a PR with the change? It is the easiest way for us to review and integrate it in the main branch. Thanks!

**Comment by alecjacobson** [comment]
I think we went through and fixed all of these.
