### ISSUE TITLE
PLY files not being read properly

### ISSUE THREAD

**Issue by Morpheus3000** [libigl/libigl#598]
Hello,

UPDATE:

I tried with a new ply file and the viewer loaded up. Weird that other programs could load it properly. But now there is a new problem. The viewer gives this output:

![image](https://user-images.githubusercontent.com/16116047/30216818-88225820-94b4-11e7-8d8f-e86c3e65e5bf.png)

While it should look like this:

![image](https://user-images.githubusercontent.com/16116047/30216857-a6262c20-94b4-11e7-9a25-3dcbed5589fa.png)

It only happens with Ply files. I tried converting it to Obj files, and that loads up correctly. But I will be getting ply files, so it would be good if I could get the Ply reader working and not having to convert to Obj. The code is the same as before.

I am trying to read a ply file that I have and display it in the viewer. I have the following code:

```
#include <igl\readPLY.h>
#include <igl\viewer\Viewer.h>

#include <iostream>

void readFilePLY()
{
	Eigen::MatrixXd V;
	Eigen::MatrixXi F;
	igl::viewer::Viewer viewer;
	igl::readPLY("E:\\testModels\\rnd_head.ply", V, F);
	viewer.data.set_mesh(V, F);
	viewer.launch();
}

int main()
{
	readFilePLY();
    return 0;
}
```

But when I run the program, I get the following:

![image](https://user-images.githubusercontent.com/16116047/30215231-988f7b16-94af-11e7-80db-80f2b2a999b4.png)

The ply file works when I load it up with Meshlab and matlab, so the ply file is correct.

Can you please tell me where I am going wrong?

Thanks!

**Comment by jmespadero** [comment]
Could you paste the header of the .ply?
Just open the .ply file with an editor and copy the first lines until the `end header`
```ply
format binary_little_endian 1.0
comment generated by tinyply
element vertex 18844
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
element face 36752
property list uchar uint vertex_indices
end_header
```

**Comment by rozentill** [comment]
Hi, I also met the error you met at first. I wonder how do you fix that. 

> PLY ERROR: fread() failed -- aborting.

**Comment by jmespadero** [comment]
Could you share the Ply file or at least the header of the file?

**Comment by rozentill** [comment]
Hi, headers of the two files I tested are : 

`ply
format binary_little_endian 1.0
comment Running Screened Poisson Reconstruction (Version 9.011)
comment 	--in pointcloud_sym_b2_refine/19901_fake_fake.npts
comment 	--depth 8
comment 	--out pointcloud_sym_b2_refine/output_8/19901_fake_fake.ply
comment # Read input into tree:       0.1 (s),      12.3 (MB) /      12.3 (MB) /      13.1 (MB)
comment #   Got kernel density:       0.0 (s),      15.4 (MB) /      15.4 (MB) /      15.4 (MB)
comment #     Got normal field:       0.1 (s),      19.6 (MB) /      19.6 (MB) /      19.6 (MB)
comment #       Finalized tree:       0.1 (s),      24.1 (MB) /      24.1 (MB) /      25.4 (MB)
comment #  Set FEM constraints:       0.3 (s),      27.6 (MB) /      27.6 (MB) /      27.6 (MB)
comment #Set point constraints:       0.1 (s),      24.3 (MB) /      27.6 (MB) /      27.6 (MB)
comment # Linear system solved:       0.7 (s),      51.5 (MB) /      51.5 (MB) /      51.5 (MB)
comment #        Got triangles:       0.3 (s),      32.3 (MB) /      51.5 (MB) /      51.5 (MB)
element vertex 40986
property float x
property float y
property float z
element face 81968
property list uchar int vertex_indices
end_header`

and 

`ply
format binary_little_endian 1.0
comment VCGLIB generated
element vertex 362271
property float x
property float y
property float z
property float nx
property float ny
property float nz
element face 0
property list uchar int vertex_indices
end_header`

**Comment by maria-korosteleva** [comment]
I also experience the problem in reading the ply file

PLY ERROR: fread() failed -- aborting.

The file header is:
ply
format binary_little_endian 1.0
comment VCGLIB generated
element vertex 12475
property float x
property float y
property float z
element face 24950
property list uchar int vertex_indices
end_header

**Comment by jmespadero** [comment]
@maria-korosteleva 
That header is quite standard, libIgL should not have any problem reading that .ply file unless the binary part is corrupt. Have you tried to open the file with other editor (for example meshlab)?
Could you share the complete .ply file?

**Comment by maria-korosteleva** [comment]
Yes, I can successfully open the file with MeshLab, I also was able to load it with plyfile (https://github.com/dranjan/python-plyfile)
File is from INRIA dataset (http://dressedhuman.gforge.inria.fr/#dr)

[0000.zip](https://github.com/libigl/libigl/files/2222026/0000.zip)

**Comment by jmespadero** [comment]
I can confirm that tinyply is also able to load the file too. This really seems a bug in LibIGL loader

**Comment by jmespadero** [comment]
Sorry for previous comment, but I can confirm that LibIGL **can** read the 0000.ply file with no problem.
![screenshot at 2018-07-24 12-33-55](https://user-images.githubusercontent.com/6451497/43133388-de926d32-8f3e-11e8-99ea-1537cac7f523.jpg)

I just used the readPLY 
```cpp
int main(int argc, char *argv[])
{
  Eigen::MatrixXd V, C, UV;
  Eigen::MatrixXi F;
  igl::readPLY("0000.ply", V, F, C, UV);
  
  // Plot the mesh
  igl::viewer::Viewer viewer;
  viewer.data.set_mesh(V, F);
  viewer.launch();
}
```

**Comment by maria-korosteleva** [comment]
I think I forgot to mention that I used python binding of the libigl

**Comment by jmespadero** [comment]
That should be indifferent, because Python is just calling the C++ method.

**Comment by 1um** [comment]
I faced a similar issue with a PLY file because those lines are commented:
https://github.com/libigl/libigl/blob/e699d257fe860d4fd82709835e72438bd0cd1533/include/igl/ply.h#L1900
This lead to storing not default properties (e.g. r,g,b) in the same memory as default ones.
Just uncommenting those lines worked well for me.

**Comment by jmespadero** [comment]
If you think that line is a bug, you should create a new issue, post your .ply file there and recall the user alecjacobson (and probably me). This issue has been reused too many times with too many .ply files.

**Comment by csyhping** [comment]
Hi, 
I have exactly the same problem. I use the 0000.ply and the readPLY() failed, it shows  `PLY ERROR: fread() failed -- aborting.`, can anyone give me some help? Thank you.

**Comment by granzuglia** [comment]
I noticed that the "PLY ERROR: fread() failed -- aborting" error happens just on a Windows 10 computer with the ply file saved in a binary format from MeshLab. If the ply file is in an ascii format (again saved with MeshLab), libigl is able to import correctly the ply file. I have no issue at all, both with the ascii and the binary format, if the importing application is compiled on a linux machine. 
[ducks.zip](https://github.com/libigl/libigl/files/3294844/ducks.zip)

**Comment by jmespadero** [comment]
Now this is a good bug report! I will try to reproduce this problem, but I am not sure to be able to install VisualStudio. I'm sendind an explicit addressing to @jdumas and @robertguetzkow as the last contributors to the include/igl/ply.h file.

**Comment by robertguetzkow** [comment]
@granzuglia @jmespadero I contributed little fixes for the very obvious memory leaks the code had.  The code of the ply.h has severe quality issues. I currently don't have time to check and debug, but I'd bet this error happens on Windows due to different line endings or encoding.

**Comment by jdumas** [comment]
As discussed before (e.g. #919), the ply read/write should be replaced with a more mature library, such as tinyply.

**Comment by jmespadero** [comment]
Well, fortunately I have experience with tinyply. So I will try to re-implement the methods at file /include/igl/readPLY.cpp to use tinyply 2.2 library instead the methods at ply.h. Give me a week.

**Comment by jdumas** [comment]
Thanks! I think for ease of use we should copy the tinyply files into `include/igl` directly, and wrap that up with proper namespace, and make sure it can also be used with libigl's header only mode (i.e. remove the `using namespace std;` from tinyply's implementation, and inline all methods with `IGL_INLINE`).

**Comment by jmespadero** [comment]
Hi @jdumas , 

I have started to write the reader using tinyply, but I have found a big problem: libIGL is using C file descriptors as argument in several methods. For example...

```
  IGL_INLINE bool igl::readPLY(FILE *ply_file, ....

  IGL_INLINE bool igl::read_triangle_mesh(const std::string & ext,  FILE * fp, ...
```

Those headers need to be changed because Tinyply only admits std::ifstreams as input, and there 
is no way to convert from "FILE *" to "std::ifstream". This mean that the libIGL API need to be changed, and the new version is not going to compile some programs written for previous versions.

So, previously to implement the new reader, I need to ask if such API changes will be accepted.

**Comment by jdumas** [comment]
I think it's fine to drop the `FILE *` interface, as long as we document it in the changelog. Using a `std::istream` is the way to go (allows to read from string and files with the same interface, also compatible with Windows paths that contains unicode characters, etc.).

But before we move on maybe @alecjacobson or @danielepanozzo can also comment on why we provide an interface to read from a `FILE *` in the first place, and whether we want to keep that or not?

**Comment by danielepanozzo** [comment]
Not sure why we support the ``FILE *`` interface, I think it is indeed better to replace it with ``std::ifstream``.

**Comment by alecjacobson** [comment]
I _think_ the FILE * pointer is so that I could handle streaming ply data
from stdin. I'm guessing std::ifstream can also handle that so that should
be fine.

**Comment by jdumas** [comment]
Ok so then we can go ahead, as there is no real reason to use `FILE *` anymore.

I just want to point out the distinction between `std::istream` (input stream) and `std::ifstream` (input _file_ stream). `std::cin` is of type `std::istream`, while `std::ifstream` is a derived class of `std::istream`. 

Tinyply uses a **`std::istream`** to read data, so it can read both from a file (`std::ifstream`), stdin (via `std::cin`), and from a string (by creating a `std::istringstream(str)`).

**Comment by jmespadero** [comment]
Ok, I'll go ahead with the change from FILE * to std::istream

Also, will add source for a read test.
