### ISSUE TITLE
AntTweakBar: OpenGL Core Profile functions cannot be loaded.

### ISSUE THREAD

**Issue by chrisidefix** [libigl/libigl#60]
Let me first say that I would like to use the "original" AntTweakBar version, which I installed through homebrew. If you think this is not a good idea, please share your thoughts.

I am compiling some of the tutorials and received this error from AntTweakBar:

    AntTweakBar: OpenGL Core Profile functions cannot be loaded.
    ERROR(AntTweakBar) >> Cannot load OpenGL library dynamically

It is apparently due to the OpenGL library not being found and can be fixed manually by adding the path to your OpenGL library to your linker path. In my case under Mac OS X this can be accomplished like this:

    export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/System/Library/Frameworks/OpenGL.framework/Versions/Current/

However, it may be a good idea to include the OpenGL lib path into the `link_directories` in your `CMakeLists.shared` file.

Credit for this blog-post to point me into the right direction: [http://www.pixelnerve.com/v/2015/01/22/anttweakbar-with-core-gl-osx](http://www.pixelnerve.com/v/2015/01/22/anttweakbar-with-core-gl-osx/)

**Comment by chrisidefix** [comment]
[UPDATE]
I just saw that you already reference `${OPENGL_LIBRARIES}` in your `SHARED_LIBRARIES` variable, which you then write into the `target_link_libraries`. If I do `otool -L` on the compiled executable I can also see the OpenGL library with full path. I guess the issue is solely with `AntTweakBar` wanting to load OpenGL dynamically at run-time and can not be fixed through CMake.

It is weird, though, since I also ran `otool -L` on my `AntTweakBar` library and it correctly references OpenGL. This is strange.

    otool -L 102_DrawMesh_bin:
    /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
    /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 21.0.0)
    /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
    /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo (compatibility version 1.2.0, current version 1.8.0)
    /System/Library/Frameworks/AGL.framework/Versions/A/AGL (compatibility version 1.0.0, current version 1.0.0)
    /usr/local/lib/libAntTweakBar.dylib (compatibility version 0.0.0, current version 0.0.0)
    /usr/local/lib/libglfw3.3.dylib (compatibility version 3.0.0, current version 3.1.0)
    /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)

    otool -L /usr/local/lib/libAntTweakBar.dylib:
    /usr/local/lib/libAntTweakBar.dylib (compatibility version 0.0.0, current version 0.0.0)
    /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
    /System/Library/Frameworks/GLUT.framework/Versions/A/GLUT (compatibility version 1.0.0, current version 1.0.0)
    /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 1265.0.0)
    /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
    /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 855.11.0)
    /usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
    /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1056.0.0)

**Comment by chrisidefix** [comment]
I just came across another issue in relation to AntTweakBar. `libigl` includes a non-public header from AntTweakBar `#include <TwOpenGLCore.h>` inside `TextRenderer.h`. When trying to link with libigl through CMake from an external project, this file may not be found. I fixed this by adding the AntTweakBar source directory into the `include_directories` of `FindLIBIGL.cmake`.

**Comment by alecjacobson** [comment]
As of roughly f03c6f13b941c682c3fb0c81c06c57ff3b3d52e6 the tutorial uses nanogui instead of AntTweakBar and the TextRenderer.h is obsolete.
