### ISSUE TITLE
Compile fail with CGAL

### ISSUE THREAD

**Issue by BEMfreshman** [libigl/libigl#600]
Hi,
I want to build libigl on archlinux 64 bits but some compile error happen when installing.
The compiler report that there is a error happening in /usr/include/CGAL/Triangulation_2.h:3012:30
with the message about this problem:

Error:"to_double" was not declared in this scope,and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]

How can I solve this problem?

Thanks in advance.

**Comment by alecjacobson** [comment]
This should be fixed by now.
