### ISSUE TITLE
Screen capture without showing GUI

### ISSUE THREAD

**Issue by Morpheus3000** [libigl/libigl#601]
Hi,

I was looking at the examples and seems that the only way to capture screenshots is to have the capturing routine as a callback. But I was wondering if it was possible to use libigl to render the mesh in memory and save a capture based on a specific view rotation, lighting etc. without the need to start up the launcher. I ask this because while libigl is a wonderful library that allows me to do almost everything that I can imagine myself needing to, I need to process a large number of models and would ideally run it on a headless server. I could use MATLAB to do the bit, but I would want a purely C++ software without MATLAB as a dependency. Would this be possible?

Thanks!

P.S.: I didn't know where to reach out, so used this instead.

**Comment by jiangzhongshi** [comment]
Just a comment for your reference. 

Basically, you would like to capture the `openGL` content created by `igl::viewer`. 
So in order for it to be "in memory", you need to render `openGL` in background, which can be done through off-screen rendering by [Mesa3D](https://www.mesa3d.org/osmesa.html). An example that I can find is [MeshQuickLookPlugin](https://github.com/alecjacobson/MeshQuickLookPlugin/blob/master/src/render_to_buffer.cpp#L474)

I tried this, but ended up using Blender for rendering in the end.
