### ISSUE TITLE
Matlab connection code failing to compile

### ISSUE THREAD

**Issue by Morpheus3000** [libigl/libigl#602]
I am trying to run a simple command using Matlab. I followed the tutorial and tried compiling it. But the compilation fails with the following errors:

![image](https://user-images.githubusercontent.com/16116047/30242816-cce60f30-959d-11e7-8f47-ab237560e96e.png)

I tried running the tutorial code from lesson 602, but it still gives the same error.

My code is as follows:
```
	Engine* engine;

	igl::matlab::mlinit(&engine);
	igl::matlab::mleval(&engine, "pth = pwd");
	igl::matlab::mlclose(&engine);

```

**Comment by alecjacobson** [comment]
Hopefully the new cmake changes have fixed this. If not, please reopen.
