### ISSUE TITLE
Python module import error under Linux 

### ISSUE THREAD

**Issue by jiangzhongshi** [libigl/libigl#603]
I am trying to use pyigl under Linux but encountered the following error.
```
>>> import pyigl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /opt/conda/envs/pytorch-py27/lib/python2.7/site-packages/pyigl.so: undefined symbol: _ZN6COMISO15EigenLDLTSolverD1Ev
```

These are the command I used to compile 
```
cd /opt
git clone --recursive https://github.com/jiangzhongshi/libigl.git
cd /opt/libigl/python
sed -i '26s/R/2.7 R/' CMakeLists.txt
mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DLIBIGL_WITH_VIEWER=OFF -                     DLIBIGL_WITH_OPENGL=OFF -DLIBIGL_WITH_OPENGL_GLFW=OFF ../ \
  73 && make -j2
```

I am building this with `gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)` and `python 2.7.13`

**Comment by danielepanozzo** [comment]
This error typically happens when you are building the lib using a different version of python than the one you are using to load it. Can you check the cmake log to make sure that it is not the case?

**Comment by jiangzhongshi** [comment]
Yeah, I already tried to manually set the PYTHON_LIBRARY and PYTHON_INCLUDE_DIR to be compatible.
When I dropped the `Release` in the command line, it works. Also, the compiler keeps complaining about `linking plugin` so I wonder if that may be the case of `-flto`

**Comment by jiangzhongshi** [comment]
When I tried to delete `-flto` from `CMakelists.txt`, import works with the same building procudure. I can look into more detail later.

**Comment by danielepanozzo** [comment]
Very strange, that flag should only affect performances and not change the behavior. This could be a compiler bug, or maybe some strange interaction with pybind.

**Comment by skoch9** [comment]
As far as I know, LTO support is not enabled in the default version of GCC in Ubuntu and you should get messages like `xxx.o: plugin needed to handle lto object` when building. If you find out another way rather than removing the `-flto` flag or using a custom GCC I would be happy to know as well.
