### ISSUE TITLE
Colocal vertices

### ISSUE THREAD

**Issue by JSandusky** [libigl/libigl#605]
Are there any built in utility functions for dealing with vertex colocality? Specifically mapping to and from a mesh without any positional redundancy and back to the source (which is redundant)?

Using igl::cotmatrix and igl::massmatrix I noticed that the weights are incorrect for indexed meshes with colocal vertices (along UV seams) when diffusing a function (Eigen LLT) over the mesh using those weights.

**Comment by alecjacobson** [comment]
`igl::remove_duplicate_vertices` is probably what you want.

This is will snap exactly duplicate (`epsilon = 0`) vertices.  And `SVI` and `SVJ` will keep track of the mapping.

**Comment by JSandusky** [comment]
Yeap, that's exactly what I was looking for and faster than the cludge I had whipped up. Thanks!
