### ISSUE TITLE
problem about creating/converting DMAT and TGF file formats

### ISSUE THREAD

**Issue by gezawa** [libigl/libigl#606]
please i need some guidance on how to create a DMAT and TGF files from my model which are in obj. and off. formats.

**Comment by jiangzhongshi** [comment]
You can refer to [file-formats](https://github.com/libigl/libigl/tree/master/file-formats) and use [writeTGF](https://github.com/libigl/libigl/blob/master/include/igl/writeTGF.h)/[readTGF](https://github.com/libigl/libigl/blob/master/include/igl/writeTGF.h) and [readDMAT](https://github.com/libigl/libigl/blob/master/include/igl/readDMAT.h)/[writeDMAT](https://github.com/libigl/libigl/blob/master/include/igl/writeDMAT.h)

**Comment by gezawa** [comment]
Thank you very much. your link and this http://blog.csdn.net/seamanj/article/details/51704355 help me solve the problem.
