### ISSUE TITLE
How to build libigl with NANOGUI?

### ISSUE THREAD

**Issue by mingzengliu** [libigl/libigl#607]
![image](https://user-images.githubusercontent.com/6506406/30521055-67b7949a-9beb-11e7-9d42-99fb15adcd2b.png)

**Comment by alecjacobson** [comment]
Can you repost this as actually text rather than an image of text?

**Comment by mingzengliu** [comment]
Thank you for replying.  Could you tell me know how to build the example in a **Xcode IDE**-based.  I am not familiar with editing cmakelist file.

**Comment by danielepanozzo** [comment]
Hi, you can use cmake to generate an xcode project using the "-G xcode" option.

**Comment by jdumas** [comment]
Closing as NanoGui has been replaced by ImGui.
