### ISSUE TITLE
Refactoring external dependencies as separate repositories.

### ISSUE THREAD

**Issue by chrisidefix** [libigl/libigl#61]
I would like to advocate the use of separate github repositories for your external dependencies (AntTweakBar, glew, glfw, triangle, etc). It might make things more complicated from the look of it, but this way it would be possible to back port your fixes to the original repositories (if they are still being maintained). I would highly recommend using `git submodules` to pull these dependencies back into your library - this way your current folder structure could very much stay intact - you would "just" have to create these external repositories and then setup the submodules.

For example, you will find a few AntTweakBar repositories on github already and right now it is very difficult to merge other fixes into your code.

PS: I assume you don't have the time for it, but maybe it could go onto the todo list :)

**Comment by alecjacobson** [comment]
This is and has been on the todo list. I've already started moving some of the less critical external libraries out this past week.

**Comment by alecjacobson** [comment]
This has more or less taken place. I think the only outstanding dependencies are AntTweakBar (barely used), lim (not sure why it can't be a separate repo), and stb_image (similar, not sure it can't/isn't a submodule).

CGAL _could_ be a submodule but it's huge and has a messy cmake configuration so it wouldn't play nicely with our cmake anyway.
