### ISSUE TITLE
Not checking division by zero when computing the cotangent matrix

### ISSUE THREAD

**Issue by IasonManolas** [libigl/libigl#610]
In the cotmatrix_entries.cpp in lines 53-55 dblA(i) could be zero and there isn't something handling it.

**Comment by jmespadero** [comment]
dblA(i) will be zero if the triangle area is zero, which mean you have degenerate triangles in you mesh (most probably triangles with two or more duplicate vertex). 
Doing such division-by-zero check will only introduce a performance penalty that will slow every case where no degenerate data is present.

So, if you (as user) think that your data could contain degenerate triangles, it is better that you check the sanity of your own data, and do not intend to process it. It is better to do it just right after dat ais generated of loaded from a file.

```
//Load input file in V,F
igl::readOFF(inputFilename, V, F);

//Check data sanity
Eigen::VectorXd dblArea;
doublearea(V, F, dblArea);
if (dblArea.minCoeff() < igl::DOUBLE_EPS )
  throw "Input data contains degenerate triangles";

...
```
