### ISSUE TITLE
License issues

### ISSUE THREAD

**Issue by schwa423** [libigl/libigl#615]
First of all, the LICENSE file is inaccurate, or at least incomplete (and it's difficult to immediately assess its accuracy/completeness).  For example, only one GPLed file is listed.  However, there is a significant amount of code that is under neither the MPL nor the GPL.  Examples:

- AntTweakBar appears to be under the zlib license
- CoMISo uses GPLv3
- Cork uses LGPLv3
- Embree uses Apache 2.0
- Lim's license is not specified
  - perhaps intended as MPL2, since it is also written at ETH Zurich?
- NanoGUI appears to use a derivative of BSD 3-clause
- STB is public domain
- TetGen uses AGPLv3
- TinyXML uses zlib
- Triangle is under a bespoke (?) not-exactly-copyleft license 

My understanding is that some of these libraries are needed only for specific features of libigl.  I also see under "Installation" that "Libigl is a header-only library", but since many of the .hpp files include .cpp files, it's difficult to tell when I might accidentally transitively include a file that is under an unacceptable license.

It's good that you have an include/copyleft directory; since copyleft licenses are forbidden-by-default by my organization, I simply won't include any of those files.  However, I think that there are other problems:

The Triangle library is not exactly copyleft, but it isn't something that most commercial entities would be able to use without running the license past their lawyer (since most organizations will use a "whitelisting" approach to the licenses that they are willing to accept).  For this reason, I suggest moving the code that uses triangle into include/copyleft/triangle.  Either that, or mention it explicitly in the LICENSE file.

Also, is include/opengl2 OK to use, as long as we don't include include/opengl2/tga.hpp?  If so, then this should be made explicit.  Perhaps tga.hpp/cpp should be moved into include/copyleft/opengl2.

It would be very useful for the LICENSE file to have an explicit statement about which files are OK to include, for use-cases where copyleft is unacceptable.  Here is some proposed wording for the license file (I'm not vouching for its accuracy, but if accurate it would meet my needs):

=== Begin suggested LICENSE file ========================

Libigl is primarily licensed under MPL2
  - http://www.mozilla.org/MPL/2.0/
  - http://www.mozilla.org/MPL/2.0/FAQ.html

All of the files in include/igl (but not necessarily in sub-directories) are subject only to the terms of the MPL2; they do not include any code that is covered by other licenses.

Many of the sub-directories in include/igl allow Libigl to integrate with the libraries in external/.  These files are also subject to the MPL2, and also the terms of the corresponding libraries.  The licenses used by these libraries fall under three categories:
- common "free, non-copyleft licenses" (such as zlib, BSD, MIT, and public domain)
- common "copyleft" licences (such as GPL, LGPL, and AGPL)
- other

The Libigl code that interfaces with "copyleft" libraries is in include/igl/copyleft.  Only include these headers if you are accept the licensing terms of the corresponding external library.  For example, using include/igl/copyleft/tetgen requires that you accept the terms of the AGPLv3.

The following directories interface with libraries that use "uncommon" licenses; examine the terms of the corresponding license before using files in these directories:
- include/igl/triangle

One additional exception is include/igl/opengl2/tga.hpp (and tga.cpp), which is subject to the terms of the GNU GPLv2.  No other files include these files, so it is safe to use all other files in include/igl/opengl2, even if you do not accept the terms of the GPLv2.
// TODO: consider moving these two files to include/igl/copyleft/opengl2

=== END suggested LICENSE file ========================

**Comment by alecjacobson** [comment]
Thanks, these are important things to fix. I think the LICENSE file grew stale and wasn't updated after some restructuring. 

Regarding triangle, it should go into `copyleft/` since it's not copyleft. It requires purchasing a license, similar to mosek and Matlab. I like what you've written for it in the suggested LICENSE file. I will probably push an updated `LICENSE` soon.

Regarding `tga.h` and those that include it, These should simply be moved to  `copyleft/opengl2/`. If they're under GPL then they have no business outside of `copyleft` (will change imminently).

**Comment by schwa423** [comment]
Thanks for addressing this, Alec!

**Comment by bchretien** [comment]
On a related note, I noticed that LGPL code from Eigen might be silently included, cf. [Eigen's website](http://eigen.tuxfamily.org/index.php?title=Main_Page#License):

> Note that currently, a few features rely on third-party code licensed under the LGPL: SimplicialCholesky, AMD ordering, and constrained_cg. Such features can be explicitly disabled by compiling with the EIGEN_MPL2_ONLY preprocessor symbol defined. Furthermore, Eigen provides interface classes for various third-party libraries (usually recognizable by the <Eigen/*Support> header name). Of course you have to mind the license of the so-included library when using them.

Defining `EIGEN_MPL2_ONLY` can help detect such cases. After doing this, I noticed that generic includes such as `<Eigen/Sparse>` include LGPL code (e.g. `<Eigen/SparseCholesky>`).
