### ISSUE TITLE
"Camera" in viewer is constant

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#617]
There seems to be some stale "camera" member fields in the ViewerCore:

`ViewerCore::camera_eye`,`ViewerCore::camera_center`,`ViewerCore::camera_up`

These never change. Instead the view of the mesh is altered via `ViewerCore::model` by manipulating `ViewerCore::camera_zoom`, `ViewerCore::trackball_angle`.

As we switch to a multi-mesh viewer, we should strip out this "model"-based transformation. We shouldn't be maintaining a separate transformation per-model (the viewer is not a modelling tool).

It would also be nice to have a easy way to grab the camera position relative to the mesh (without having to jump through `ViewerCore::model`, `ViewerCore::view`, etc).

**Comment by avaxman** [comment]
I noticed this as I struggled to retrieve the camera parameters (for instance, to export rendering file for POVRay). It would be nice to get a function that returns them.

**Comment by alecjacobson** [comment]
We're working on a refactor of the viewer right now and this is one of the
issues that will be resolved.

**Comment by trnglt** [comment]
I'm trying to follow where things are now. What's the recommended way to retrieve and set the camera view programmatically now? Thanks!
