### ISSUE TITLE
frame_field and curvature 

### ISSUE THREAD

**Issue by dougepps** [libigl/libigl#618]
Trying to modify the 506_FrameField demo to use curvatures instead of the hard-coded constraints.
With the demo mesh all seems well.

But with different meshes I either get a core-dump or .. no quad-mesh made.

Are there any requirements for the mesh for this technique ? ( water-tight ? ).

Or does passing the fields from  igl::principal_curvature() to comiso::frame_field() mess something up ?

I've thought maybe I should sort the curvatures and only use the top longest ? 
(no idea how to do that with Eigen, but seems like it should be possible ).

Any help would be great. IGL is like a magical beacon of hope in the wilderness for pulling together different geo-processing things . Thank you !

-doug

**Comment by danielepanozzo** [comment]
Hi,

the mesh has to be of good quality (i.e. no slivers), it should be a single connected component, and it should be manifold. If you get garbage (or a crash) out of the optimization it is likely to be a problem with the input mesh.
