### ISSUE TITLE
Example Project Cmake Error

### ISSUE THREAD

**Issue by majsad** [libigl/libigl#621]
Hi to all,

I am trying to build the example project, I have libigl installed and I have built the tutorials and they work. But when I am configuring the example project with cmake I get this error:

The C compiler identification is MSVC 19.0.24210.0
The CXX compiler identification is MSVC 19.0.24210.0
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
CMake Error at cmake/FindLIBIGL.cmake:36 (include):
include could not find load file:
libigl
Call Stack (most recent call first):
CMakeLists.txt:26 (find_package)
Configuring incomplete, errors occurred!
See also "E:/Software/LibIgl/Githubbed/libigl-example-project-master/build/CMakeFiles/CMakeOutput.log".

Do you have any idea why this happens?

Thank you so much.

**Comment by danielepanozzo** [comment]
I just tested it with the latest version of both libigl and libigl-example-project and it works for me (VS 2015 Community edition, Win 10). You could you try a fresh clone (using the —recursive option), not sure why this is happening. Maybe you have some wrong permissions and the cmake is not able to access the libigl folder?

**Comment by majsad** [comment]
@danielepanozzo 
Dear Daniel,

I am using GitHub Desktop on my windows 7, what is the equivalent option to recursive on LINUX?

Thanks.

**Comment by ManikaBindal** [comment]
I am also getting the same error ....R u @majsad able to rectify it ?

**Comment by carloselcastro** [comment]
I am also having the same error. 

CMake Error at cmake/FindLIBIGL.cmake:36 (include):
  include could not find load file:

    libigl
Call Stack (most recent call first):
  CMakeLists.txt:26 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/Carlos/libigl-example-project/build/CMakeFiles/CMakeOutput.log

**Comment by carloselcastro** [comment]
Hi,
I was having the same error, and it was happening because an Mac Security actualization 2017-003 (https://support.apple.com/en-us/HT207922).

The example was working normally until I did the update mentioned above. When formatting the mac and not updating the security system (which has insisted that I install it), the example returned to normal operation.

The question is: Is there another way to fix the problem?

Thanks for all help,
Carlos Castro

**Comment by Leo-Souto** [comment]
@carloselcastro This error happened to me when i tried to compile the mex files of gptoolbox (which are based on libigl)
It seems to be a problem in FindLIBIGL.cmake
`sudo cmake .. -DMatlab_ROOT_DIR=<your_matlab_root> -DLIBIGL_INCLUDE_DIR=<your_libigl_dir>/include/`
corrected it, you should be able to adapt to your problem.
Tested on:
Debian 9
Matlab R2017a
