### ISSUE TITLE
pyigl.signed_distance ridiculously slow on a high-performance cluster

### ISSUE THREAD

**Issue by mibieri** [libigl/libigl#623]
I use 

` pyigl.signed_distance(eigen_query, eigen_points, eigen_idx, pyigl.SignedDistanceType.SIGNED_DISTANCE_TYPE_PSEUDONORMAL, eigen_signed_distances, eigen_idx_to_query, eigen_closest, eigen_normals)`

to compute some signed distances. The number of points/faces is in the order of 10-50. 

I observe that calling this function takes about 100x longer on our high-performance cluster than on my laptop. It's not the import, it's really the function that takes so long. If I call the function 10x in a row, it will actually take 10x the time.

The cluster is a Cray system, where computing tasks are done on a scratch file system. The pyigl.so file is on that scratch file system. Normally, the system wants to link statically, but I think, that's not possible for a Python binding. However, other Python bindings work fine and fast.

Where could be the problem? What could I try?

**Comment by danielepanozzo** [comment]
It is peculiar that it only happens on the Cray system and not on your laptop, this might be hard to debug. My rceommendation would be to directly call the function from C++ if you care about performances — the python bindings will in any case introduce some unnecessary overhead. One thing to try if you have to stick to python, is to try to switch from python 2 to 3 (or viceversa), it might be a bug that goes away with a newer version of Python.

**Comment by lijiaman** [comment]
Met the same issue. pyigl.signed_distance is 5 times faster on my local maptop (Mac) than a ubuntu machine...
