### ISSUE TITLE
compile example 604 in VS 2015

### ISSUE THREAD

**Issue by Dacastror** [libigl/libigl#624]
Hello everyone,
I'm trying to compile the tutorial example 604 in visual studio 2015, but it did not work, try putting the files from https://github.com/libigl/triangle
in the triangle folder (igl / triangle) and add the path to the project's additional directories, but it did not work.
Also try with this code https://github.com/wo80/Triangle
this compiles correctly, but I can not get it to work inside igl. I have been able to compile other examples of libigl correctly.
I know very little about these things with what I may be making mistakes, can anyone tell me the steps to follow to compile the 604 example? thanks for your help.

(I use google translator, sorry for the translation errors)

**Comment by danielepanozzo** [comment]
I just pushed a fix for the runtime crash on VS 2015 64 bit. It should work now.

In case you ahve problems compiling, make sure that you are cloning the repository with the —recursive option and that you are using the cmake file in the tutorial folder (not the one inside the 604 folder).

**Comment by Dacastror** [comment]
Hi, I'm getting an error like this:

```
Error LNK2019 unresolved external symbol triangulate referenced in function "void __cdecl igl::triangle::triangulate<class Eigen::Matrix<double,-1,-1,0,-1,-1>,class Eigen::...
```
I am using the files of: https://github.com/libigl/triangle
and I add the folder to the project. I do not know how to use cmake in Visual Studio, I just select "build solution", am I doing something wrong?

**Comment by danielepanozzo** [comment]
You need to clone the repository using --recursive (it will pull the triangle sources automatically for you) and then use cmake to generate a solution for ALL tutorials (use the cmake file in /tutorials/), not only for the one that you need. Cmake will create a solution for you, then double click on it and build it.

**Comment by Dacastror** [comment]
Hello, I understood the cmake software, I installed it and created the Visual Studio project with it. I successfully compile example 604,
Now I want to use `triangulate()` in my personal project, but I can not achieve it, I write
`#include <igl / triangle / triangulate.h>`
And I add the path where `triangle.h` is located, but it does not work, the error appears

`Error LNK2019 unresolved external symbol triangulate referenced in function "void __cdecl igl::triangle::triangulate<class Eigen::Matrix<double,-1,-1,0,-1,-1>,class Eigen::...`

What should I do to be able to use `triangulate ()` in my project?

**Comment by danielepanozzo** [comment]
I recommend to start from https://github.com/libigl/libigl-example-project and use cmake to generate the visual studio project.

**Comment by Dacastror** [comment]
Hello,I finally have some free time. 
Ok, I have already downloaded the libigl-example-project and it compiles correctly, now I want to add the function to triangulate a polygon, which are the steps to follow? I tried with
  `#include <igl / triangle / triangulate.h>`
And with
`igl :: triangle :: triangulate (V, E, H, "a0.005q", V2, F2);`
but I get the same error that always appears:
`Error LNK2019 unresolved external symbol triangulate referenced in function "void __cdecl igl::triangle::triangulate<class Eigen::Matrix<double,-1,-1,0,-1,-1>,class Eigen::...`

what is the correct way to add the triangulate function?

(I use google translator, sorry for the translation errors)

**Comment by Dacastror** [comment]
ok, I already solved it,
in `Project/Properties/Linker/Input/Aditional Dependencies`
it is necessary to add the files triangle.lib, igl_triangle.lib and triange.obj
In `Project/Properties/Linker/General/Aditional Library Directories`
you must add the routes to these files (are the folder where the tutorials were built (with cmake))
you should also add the routes to the .h in `Project/Properties/C++/General/Aditional include directories`

thank you very much for your advice Daniele, without them I would not have found the solution.
