### ISSUE TITLE
IOError: stl file can not be reopened as binary

### ISSUE THREAD

**Issue by majsad** [libigl/libigl#625]
Hi to All

I am using tutorial 609 Boolean which works fine using its own .off files, but when I try to do the same thing on my own STL files, igl can not read it and gives the error below, although I can open my STLs with other programs, I have saved my STLs as both  binary and ascii (STLs are attached):

[STL_ASCII.zip](https://github.com/libigl/libigl/files/1417852/STL_ASCII.zip)
[STL_Binary.zip](https://github.com/libigl/libigl/files/1417853/STL_Binary.zip)

IOError: stl file can not be reopened as binary (1) ...

Here is the edited code of the tutorial:

#include <igl/readOFF.h>
#include <igl/readPLY.h>
#include <igl/writePLY.h>
#include <igl/readSTL.h>
#include <igl/writeSTL.h>
//#define IGL_NO_CORK
//#undef IGL_STATIC_LIBRARY
#include <igl/copyleft/cgal/mesh_boolean.h>
#include <igl/viewer/Viewer.h>

#include <Eigen/Core>
#include <iostream>

#include "tutorial_shared_path.h"

Eigen::MatrixXd VA,VB,VC,NA,NB;
Eigen::VectorXi J,I;
Eigen::MatrixXi FA,FB,FC;
igl::MeshBooleanType boolean_type(
  igl::MESH_BOOLEAN_TYPE_UNION);

const char * MESH_BOOLEAN_TYPE_NAMES[] =
{
  "Union",
  "Intersect",
  "Minus",
  "XOR",
  "Resolve",
};

void update(igl::viewer::Viewer &viewer)
{
  igl::copyleft::cgal::mesh_boolean(VA,FA,VB,FB,boolean_type,VC,FC,J);
  Eigen::MatrixXd C(FC.rows(),3);
  for(size_t f = 0;f<C.rows();f++)
  {
    if(J(f)<FA.rows())
    {
      C.row(f) = Eigen::RowVector3d(1,0,0);
    }else
    {
      C.row(f) = Eigen::RowVector3d(0,1,0);
    }
  }
  igl::writePLY("E:/Arash/Ph.D/libtestres1.ply", VC, FC);
  igl::writeSTL("E:/Arash/Ph.D/libtestres1.stl", VC, FC, false);
  std::cout << "file is written" << std::endl;
  viewer.data.clear();
  viewer.data.set_mesh(VA,FA);
  viewer.data.set_colors(C);
  std::cout<<"A "<<MESH_BOOLEAN_TYPE_NAMES[boolean_type]<<" B."<<std::endl;

}

bool key_down(igl::viewer::Viewer &viewer, unsigned char key, int mods)
{
  switch(key)
  {
    default:
      return false;
    case '.':
      boolean_type =
        static_cast<igl::MeshBooleanType>(
          (boolean_type+1)% igl::NUM_MESH_BOOLEAN_TYPES);
      break;
    case ',':
      boolean_type =
        static_cast<igl::MeshBooleanType>(
          (boolean_type+igl::NUM_MESH_BOOLEAN_TYPES-1)%
          igl::NUM_MESH_BOOLEAN_TYPES);
      break;
    case '[':
      viewer.core.camera_dnear -= 0.1;
      return true;
    case ']':
      viewer.core.camera_dnear += 0.1;
      return true;
  }
  update(viewer);
  return true;
}

int main(int argc, char *argv[])
{
  using namespace Eigen;
  using namespace std;
  //igl::readOFF(TUTORIAL_SHARED_PATH "/cheburashka.off", VA, FA);
  //igl::readOFF(TUTORIAL_SHARED_PATH "/decimated-knight.off", VB, FB);
  igl::readSTL("E:/Arash/Ph.D/alltricleansubdivideds.stl",VA,FA,NA);
  igl::readSTL("E:/Arash/Ph.D/cylinder1tripolycleans.stl",VB,FB,NB);
  //igl::readPLY("E:/Arash/Ph.D/alltricleansubdivided",VA,FA);
  //igl::readPLY("E:/Arash/Ph.D/cylinder1tripolyclean",VB,FB);
  // Plot the mesh with pseudocolors
  igl::viewer::Viewer viewer;

  // Initialize
  update(viewer);

  viewer.core.show_lines = true;
  viewer.callback_key_down = &key_down;
  viewer.core.camera_dnear = 3.9;
  cout<<
    "Press '.' to switch to next boolean operation type."<<endl<<
    "Press ',' to switch to previous boolean operation type."<<endl<<
    "Press ']' to push near cutting plane away from camera."<<endl<<
    "Press '[' to pull near cutting plane closer to camera."<<endl<<
    "Hint: investigate _inside_ the model to see orientation changes."<<endl;
  viewer.launch();
}

Any idea what the problem is?

Thanks.

**Comment by alecjacobson** [comment]
I can't reproduce this problem: when I compile and run your example it
loads in the meshes fine (although these meshes are not suitable inputs to
mesh_boolean but that's not related to IO).

What system are you on? Do any binary STL files load OK for you?
-Alec

**Comment by majsad** [comment]
@alecjacobson 
Dear Alec,

Thank you so much, I will reinstall everything and check again. What is the problem with the mesh types? Is there not enough vertices?

**Comment by alecjacobson** [comment]
mesh_boolean expects a "piecewise constant winding number" mesh. See the definitions on the paper's project page:
http://www.cs.columbia.edu/cg/mesh-arrangements/

**Comment by majsad** [comment]
@alecjacobson 

Dear Alec, 

I tried to understand the paper, it is a little bit too much information for me at the moment. I am creating my meshes using VTK STL Writer, Does generally stl files work with libigl boolean? Or is vtk exporting stl in a not proper stl format? 

What if I use other stl files generated with other software? If I create the mesh in .ply format will it help? Generally is there a file format which guarantees working with libigl boolean?

Thanks,

**Comment by alecjacobson** [comment]
It's not an issue with the file format, rather the mesh itself. If there are gaping holes or even slits in the model then this boolean code will not work. Depending on what your meshes look like you may have some other options though.

**Comment by alecjacobson** [comment]
@majsad are you also on Windows?

I wonder if this is a big vs. little endian problem... I hope not...

**Comment by majsad** [comment]
@alecjacobson Yes I am using Win 7, MSVC2015, CGAL 4.8.2, Boost 1.62.0
How does it matter?

**Comment by alecjacobson** [comment]
So what was the solution?

**Comment by majsad** [comment]
@alecjacobson  I just remade the meshes. problem was witht the meshes themselves.
