### ISSUE TITLE
compile tutorials with Xcode

### ISSUE THREAD

**Issue by Lagrant** [libigl/libigl#626]
Hello to everyone
I'm trying to compile libigl tutorials with Xcode,  after it generates  .xcodeproj files, I try to run one example with Xcode, but errors generates that 
clang: error: no such file or directory: '/Users/XXX/libigl/tutorial/build/nanogui/ext_build/glfw/src/Debug/libglfw3.a'
clang: error: no such file or directory: 
'/Users/XXX/libigl/tutorial/build/nanogui/Debug/libnanogui.a'
can anyone give some help?

**Comment by jdumas** [comment]
Seems related to #383 and  #673. I believe this should be fixed with the latest build (NanoGui has been replaced by ImGui and glfw is linked directly without object targets).
