### ISSUE TITLE
libigl tutorial build MSVC2015 Win 7

### ISSUE THREAD

**Issue by majsad** [libigl/libigl#629]
Hi to All,

Trying to build tutorials with Cmake 3.8.0 GUI and MSVC2015 on Win 7 64, and CGAL 4.8. 
I have tried with both option(LIBIGL_USE_STATIC_LIBRARY "Use LibIGL as static library" ON) and option(LIBIGL_USE_STATIC_LIBRARY "Use LibIGL as static library" OFF) in CMakeLists.txt inside tutorial folder.  I Can not build the project successfully.

Cmake config results and MSVC2015 Build results are attached.

[CMAKE.docx](https://github.com/libigl/libigl/files/1427493/CMAKE.docx)
[MSVC2015debug.docx](https://github.com/libigl/libigl/files/1427494/MSVC2015debug.docx)
[MSVC2015Release.docx](https://github.com/libigl/libigl/files/1427495/MSVC2015Release.docx)

Any Help with the source of error? Is it my systems or Libigl?

Thanks.

**Comment by danielepanozzo** [comment]
There are some issues with your CGAL installation, it is not able to find boost

**Comment by majsad** [comment]
Dear Daniel,

I reinstalled CGAL and it can find boost for its own examples. The demos and examples work. but why when building libigl tutorials CGAL has problem finding boost? Any idea?

Thanks.

**Comment by jdumas** [comment]
We had some trouble yesterday with @gaoxifeng trying to make CGAL work again with libigl in the new build system. While it works fine on Linux/Mac, the new target-based CMake build for CGAL seems to be lacking on Windows, for mysterious reasons (and the CI build on AppVeyor doesn't compile CGAL). I will investigate to see how it can be fixed.

@majsad try adding a `${Boost_INCLUDE_DIRS}` [here](https://github.com/libigl/libigl/blob/dbfa2b70f599de37d8d58681a6c068a752752659/shared/cmake/libigl.cmake#L139) to see if it helps. I suspect you may run into further issues down the line.

**Comment by alecjacobson** [comment]
So wait, does this mean that the cmake refactor broke the build on Windows?

**Comment by jdumas** [comment]
Daniele told me he tested it on Windows at the time, so maybe it's just that @majsad didn't install Boost/CGAL properly. It's easy to mess up this sort of stuff on Windows.

**Comment by danielepanozzo** [comment]
@gaoxifeng could you confirm if the CGAL tutorial works on your side? This could also be a problem related to the recent cgal update, I only tested it with an older version.

**Comment by gaoxifeng** [comment]
The compilation of Example 609 Boolean failed at my side.

**Comment by majsad** [comment]
My Cmake configuration of CGAL with Boost is this:

[CGAL.docx](https://github.com/libigl/libigl/files/1440486/CGAL.docx)

It is build successfully in MSVC2015 release mode.

**Comment by majsad** [comment]
@jdumas 
This is what I get with adding ${Boost_INCLUDE_DIRS} to cmake file, (it complains about gmp.h?!)

[1.docx](https://github.com/libigl/libigl/files/1440532/1.docx)
[CMAKE.docx](https://github.com/libigl/libigl/files/1440533/CMAKE.docx)

**Comment by jdumas** [comment]
@majsad we pushed a fix. Please try to update libigl and let us know how it goes.

**Comment by majsad** [comment]
@jdumas  Thanks, although it builds all the tutorials, 609 fails to run and says: "The application was unable to start correctly (0xc000007b). Click to close the application."

**Comment by jdumas** [comment]
Are you sure you are compiling in 64-bit and that you system is a 64-bit Windows? 32-bit is not supported.

**Comment by majsad** [comment]
Yes I am all 64-bits, I have been using the tutorials before with the same system, after an update it stopped working.

**Comment by jdumas** [comment]
And the other tutorials work, it's only the one with CGAL thase poses a problem? Could it be a missing dll that is not copied properly? (like gmp or mpfr). I tried to run this tutorial on my Windows machine after the fix and it was working.

**Comment by majsad** [comment]
No, among the others I tested 602,607,609,610 and 709 also doe snot work:
607: the program can't start because igl_stb_image.dll is missing fom your computer.
709: libopenblas.dll is missing
and similar errors, where should these dlls have been generated?

**Comment by jdumas** [comment]
Ok well the missing dlls are easy to fix, you need to copy them from wherever they are generated to the folder where your .exe is compiled (this could be copied by cmake itself but one needs to create the rule for it). Search your build/ folder for `igl_stb_image.dll`. For 709 looks like `libopenblas.dll` comes from `external/CoMISo`. However, if 609 doesn't work for a reason other than a missing dll this is something one would need to investigate.

**Comment by majsad** [comment]
thanks, right now I just need the boolean (609), which as you said is giving an error not related to dlls. Is there a way I can clone the previous versions of Libigl?

**Comment by jdumas** [comment]
I mean, you could always do `git checkout` of and older version of libigl, but honestly it would be better to try and fix the issue you have. I just tried again on my Windows with Visual Studio 2017 with the latest mirror of libigl and it works great:

![boolean](https://user-images.githubusercontent.com/578702/32447774-fd4e3bba-c2da-11e7-835a-bac71c6a555f.png)

**Comment by majsad** [comment]
I will try so, but do you have any suggestion where to look for? Or where to start from?
Thanks.

**Comment by jdumas** [comment]
Well, what version MSVC, CMake and CGAL are you using? Can you run the other tutorials if you copy the dlls into the same folder as the .exe? Can you try to clean up you CGAL installation (update & reinstall), etc. You can also try with the latest version of MSVC (recompiling both boost and CGAL with it) ...

**Comment by majsad** [comment]
@jdumas can I ask what version of CGAL is supprted by libigl to be used with MSVC2015?

**Comment by jdumas** [comment]
I don't know about MSVC2015, but the example you see above is using the latest version to date (4.11). It should work with 4.9 onward.

**Comment by majsad** [comment]
Thanks everyone for the great and fast support. I could run it with CGAL 4.10 and it works fine, the problem was using CGAL 4.8 I guess.
