### ISSUE TITLE
Update EmbreeIntersector.h with new embree 2.1.7.0 API

### ISSUE THREAD

**Issue by etrigger** [libigl/libigl#636]
It seems like functions such as 'rtcInit' are deprecated and I cannot pass the compiling with VS2015.
Right now, I just add '#pragma warning(disable : 4996)' to the beginning of 'EmbreeIntersector.h' and I can still run the code.
Hopefully, we could update to new API soon.

Thanks.

**Comment by danielepanozzo** [comment]
I am not getting this error, and the build passes on appveyor. If this happen with a newer version of embree, could you please send a PR that both updates the embree version and contains the fix that you propose?

Thanks

**Comment by jdumas** [comment]
New version of embree has been merged in the `dev` branch with #947
