### ISSUE TITLE
ModuleNotFoundError no module named pyigl

### ISSUE THREAD

**Issue by FLaenen2** [libigl/libigl#638]
Hello,
I have successfully compiled libigl/python with the generator Visual Studio 14 2015 win64. 
No error during the compilation phase, the generation succeeded for all targets. 
Since, when I try to run a tutorial (the 101 for example), I get the error 
ModuleNotFoundError: No module named 'pyigl'
I checked that the python version with which I run the example and the one used during configuration phase was the same.

**Comment by FLaenen2** [comment]
Sorry, i used the generator visual studio 15 2017 win64

**Comment by skoch9** [comment]
Hi,
currently there is no installation procedure of the bindings, so you have to manually add the created python bindings (the files pyigl and nanogui) to your PYTHONPATH so that python can find the module. See [here, 3.3](https://docs.python.org/3/using/windows.html) for more information.
