### ISSUE TITLE
Build error: cannot convert from 'const char [1]' to 'LPCWSTR' in Visual Studio 2015?

### ISSUE THREAD

**Issue by penguin1214** [libigl/libigl#639]
Hi, I'm trying to use `libigl` to do marching cube. When compiling, error popped up

`
\libigl\include\igl\file_dialog_save.cpp(54): error C2440: '=': cannot convert from 'const char [1]' to 'LPCWSTR'
`
corresponding code is 
`
  ofn.lpstrFile = new char[100];
`
It might be error with my config since no one seems to run into similar issue before, but I can't manage to solve it.

**Comment by evouga** [comment]
Open up the Property Pages for the project, and in the "General" tab, make sure that "Character Set" is set to "Use Multi-Byte Character Set" (and in particular, *not* Unicode).

**Comment by penguin1214** [comment]
@evouga  Thanks. Problem solved!

**Comment by T1Cr4azy** [comment]
@evouga Good!
