### ISSUE TITLE
VS 2013v4 compilation errors when doing tutorials (libigl as per 4/19/2015)

### ISSUE THREAD

**Issue by fusentasticus** [libigl/libigl#64]
Hi again, so I'm trying my luck on Windows (my virtual Linux machine doesn't allow OpenGL 3 graphics)  -- again, just trying to get tutorial to build! Can you help me with one big (?) issue? I'm also reporting various minor things below that are probably without significance.

MAJOR ISSUE: Error ...  "term does not evaluate to a function taking 1 arguments..." and two more:

Here Visual Studio barfs, look here:
https://gist.github.com/fusentasticus/7a896030ce5abf105b53

MINOR ISSUE: glfw binaries are not included. My solution: add
    ${PROJECT_SOURCE_DIR}/../external/glfw/src/Release
    ${PROJECT_SOURCE_DIR}/../../external/glfw/src/Release
to tutorial/cmake/FindGLFW.cmake in appropriate place, and cmake configure in glfw, and build.

MINOR ISSUE: Example 101 compiles with a million warnings: configuring with
 
  cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=" /D GLEW_STATIC" ..

solves that problem for Example 101. But this then results in a macro redefinition in OpenGL_shader.h when building Example 102.  Apropos GLEW: it should perhaps be made clear somewhere that GLEW binaries are not needed. Perhaps I just missed it.

MORE MINOR ISSUES WITH VS2013:

- Warning: ignoring unknown option '-std=c++11'
- Warning: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc

/Nils

**Comment by ahmedafifijp** [comment]
Hi
I am facing the same problem,
I hope someone can help in solving this problem or describes how to correctly run the viewer in Visual studio 2013

**Comment by alecjacobson** [comment]
Are you sure you have enabled C++11?

**Comment by ahmedafifijp** [comment]
Hello,
As I know the partially supported features of C++11 in visual studio 2013 are enabled by default. Is there anything special I have to do?

**Comment by alecjacobson** [comment]
Please do a `git pull`. I found a bug in the callback initializations in
Veiwer.cpp that could be causing these problems.

**Comment by ahmedafifijp** [comment]
Thank you very much Alec,
Now, it is OK.
