### ISSUE TITLE
Visualization of tetrahedron 

### ISSUE THREAD

**Issue by Ziheng-Liang** [libigl/libigl#641]
Does `viewer.data.set_colors(C);` not work with tetrahedron? I've tried different C that has size 1/V.rows()/F.rows() * 3. Only size of 1 * 3 will render with color.

**Comment by danielepanozzo** [comment]
The viewer only supports triangles. If you want to render a tetrahedron you will first have to create one triangle for each of its faces, and then provide one color for each face.
