### ISSUE TITLE
AABB.cpp does not compile

### ISSUE THREAD

**Issue by evouga** [libigl/libigl#642]
Line 404

     Eigen::PlainObjectBase<RowVectorDIMS> c_right = c;

does not compile for me (MSVC 2014, Eigen 3.3.4) because Eigen::PlainObjectBase's copy constructor is protected.

I don't understand the context of this code well enough to know if the fix is as simple as

     Eigen::PlainObjectBase<RowVectorDIMS> &c_right = c;

**Comment by alecjacobson** [comment]
Thanks for pointing this out. The correct line should (and will shortly) read:

    RowVectorDIMS c_right = c;

(FWIW, your correction will compile but likely induce bugs since `c_right` will be written into and in turn into `c`).
