### ISSUE TITLE
signed_distance has wrong sign

### ISSUE THREAD

**Issue by evouga** [libigl/libigl#644]
I *think* I'm using the function correctly, but I'm getting unexpected results. Here's a minimum broken example (the mesh is in a .txt file, because GitHub does not let me upload .obj).

````
#include <Eigen/Core>
#include <limits>
#include <iostream>
#include <igl/signed_distance.h>
#include <igl/readOBJ.h>
#include <igl/writeOBJ.h>

int main()
{
	Eigen::MatrixXd V;
	Eigen::MatrixXi F;
	igl::readOBJ("scaled.txt", V, F);

	Eigen::MatrixXd P(1,3);
	P << 16.0, 16.0, 16.0;

	Eigen::VectorXi I;
	Eigen::MatrixXd C;
	Eigen::MatrixXd N;
	Eigen::VectorXd gridvals;
	igl::signed_distance(P, V, F, igl::SIGNED_DISTANCE_TYPE_WINDING_NUMBER, -std::numeric_limits<double>::infinity(), std::numeric_limits<double>::infinity(), gridvals, I, C, N);
	std::cout << gridvals[0] << std::endl;
}
````

I get a positive number as output (1.77181) despite the point being clearly inside the object.

[scaled.txt](https://github.com/libigl/libigl/files/1484166/scaled.txt)

**Comment by alecjacobson** [comment]
Is your mesh “inside out”?

Ie is it consistently wrong?

**Comment by evouga** [comment]
Ah, no, but it does contain duplicate copies of some of the faces, with opposite orientation. That must be confusing the winding number check.
