### ISSUE TITLE
Strange Eigen issue in window.cpp (Viewer segfaults in Release mode)

### ISSUE THREAD

**Issue by evouga** [libigl/libigl#645]
Window::preferredSize has this innocuous-looking line:

````
return result.cwiseMax(Vector2i(
        bounds[2]-bounds[0] + 20, bounds[3]-bounds[1]
    ));
````

For whatever reason (bug in Eigen? bug in MSVC's optimizer? Some arcane issue with Eigen's expression templates and vectorization?) this returns garbage when compiled in Release mode on MSVC 2015 using Eigen 3.3.4, which then segfaults the Viewer.

Replacing the above with
````
Vector2i ret(std::max( int(bounds[2] - bounds[0]) + 20, result[0]),
        std::max( int(bounds[3] - bounds[1]), result[1]));   
return ret;
````
fixes the problem (for whatever reason).

**Comment by jdumas** [comment]
Is this bug still relevant? I don't see any file `window.cpp` in libigl, nor any mention to the code snippet you mentioned.
