### ISSUE TITLE
Viewer crashes in Debug mode in VS2017, due to strange Eigen error

### ISSUE THREAD

**Issue by milkpku** [libigl/libigl#647]
Hi, dear authors, 

There is a problem of `igl::viewer::Viewer` troubling me for a long time, and recently I figured out the possible location of the error. Can you help to fix this?

I compile program with `igl::viewer::Viewer` in VS2015/17, linking it with Release/Debug mode static lib of **nanogui**. The program have no problem under Release mode, but will crash under Debug mode. I looked into the program and found that it is `Viewer.cpp line 256` who cause the error.

By looking further, I found it is `colorwheel.cpp line 300` of **nanogui** cause the error, but I can go no further at this line. I have copied the code out and tested, but found it works well. I guess a possible cause of this error may come from the strange definition of macros in `colorwheel.h line 111`.

The following code is the test code I use to show viewer crash, wish this can help:

```c++
#include <GL/glew.h>
#include <GLFW/glfw3.h>

#pragma comment(lib, "opengl32")
#pragma comment(lib, "glew32")
#pragma comment(lib, "glfw3")

#ifndef _DEBUG
#pragma comment(lib, "nanogui")
#else
#pragma comment(lib, "nanoguid")
#endif

#define IGL_VIEWER_WITH_NANOGUI
#include <igl/viewer/Viewer.h>

int main(int argc, char* argv[])
{
  igl::viewer::Viewer viewer;
  viewer.launch();
}

```

**Comment by alecjacobson** [comment]
Since this seems to be an error in nanogui, could you please re-post the issue on that project's page?

https://github.com/wjakob/nanogui
