### ISSUE TITLE
Interaction facility for deformation examples 

### ISSUE THREAD

**Issue by sumukhbansal** [libigl/libigl#648]
Are there tutorials/examples available fordiscussing user interaction for interactive deformation problem?
The deformation for the examples in IGL tutorial is being  provided from the dmat files.
Is there any support for such interaction facility?

**Comment by alecjacobson** [comment]
Take a look at this assignment from my geometry processing course:

https://github.com/alecjacobson/geometry-processing-deformation/

It uses mouse interactions for ARAP deformation.
