### ISSUE TITLE
matrix index error in function setFieldFromGeneralCoefficients (n_polyvector.cpp)

### ISSUE THREAD

**Issue by szlyc** [libigl/libigl#649]
Hi,
   I'm using n_polyvector function and it reports an error of 
Assertion failed: index >= 0 && index < size(), file d:\library\eigen-3.3.1\eigen\src\core\densecoeffsbase.h, line 408

From the stack I saw it stopped at the line 294 of n_polyvector.cpp, so I had a look into the function setFieldFromGeneralCoefficients. I'm wondering if it is caused by the following for loop:

 for (int k=0; k<2*n; ++k)
    {
      if (done[k])
        continue;
      u[ind] = roots[k];
      done[k] = 1;

      int mini = -1;
      double mind = 1e10;
      for (int l =k+1; l<2*n; ++l)
      {
        double dist = abs(roots[l]+u[ind]);
        if (dist<mind)
        {
          mind = dist;
          mini = l;
        }
      }
      done[mini] = 1;
      ind ++;
    }
The initial value of 'mini' is -1, it only triggers mini = l when dist<mind. Is there any chance that dist >= mind is always true?

**Comment by danielepanozzo** [comment]
This function will be removed soon: https://github.com/libigl/libigl/pull/630

I suggest that you use the reimplementation in libdirectional, it has more features: https://github.com/avaxman/libdirectional

@avaxman: can I merge the PR https://github.com/libigl/libigl/pull/630?
