### ISSUE TITLE
"no member named 'normalize' in" in igl::per_vertex_normals

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#65]
> From personal email

Dear Jacobson,
    
   Hi!
   
  Everything went smoothly till the step “make” after “cmake -DCMAKE_BUILD_TYPE=Release ../
", according your instructions.
Here comes the errors as follows. I have no idea where i’m wrong. BTW, all the operations were performed on the MAC laptop with Yosmite 10.10.2. And, example 101 were correctly compiled and linked into the executive file. I would be very appreciate your reply. Thank you for taking your time.

```bash
———————
/Users/user/libigl/include/igl/per_vertex_normals.cpp:88:15: error: no member named 'normalize' in
      'Eigen::VectorwiseOp<Eigen::Matrix<double, -1, -1, 0, -1, -1>, 1>'
  N.rowwise().normalize();
  ~~~~~~~~~~~ ^
/Users/user/libigl/include/igl/per_vertex_normals.cpp:99:5: note: in instantiation of function
      template specialization 'igl::per_vertex_normals<Eigen::Matrix<double, -1, -1, 0, -1, -1>,
      Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>,
      Eigen::Matrix<double, -1, -1, 0, -1, -1> >' requested here
    per_vertex_normals(V,F,PER_VERTEX_NORMALS_WEIGHTING_TYPE_DEFAULT,FN,N);
    ^
/Users/user/libigl/include/igl/viewer/ViewerData.cpp:360:8: note: in instantiation of function
      template specialization 'igl::per_vertex_normals<Eigen::Matrix<double, -1, -1, 0, -1, -1>,
      Eigen::Matrix<int, -1, -1, 0, -1, -1> >' requested here
  igl::per_vertex_normals(V, F, F_normals, V_normals);
       ^
1 error generated.
make[2]: *** [102_DrawMesh/CMakeFiles/102_DrawMesh_bin.dir/main.cpp.o] Error 1
make[1]: *** [102_DrawMesh/CMakeFiles/102_DrawMesh_bin.dir/all] Error 2
make: *** [all] Error 2
——————————————————————
```

**Comment by alecjacobson** [comment]
Seems like you're using an older version of Eigen. Which version do you have? (This might help: http://www.alecjacobson.com/weblog/?p=3415)

**Comment by fusentasticus** [comment]
I guessed Eigen 3.2 (3.2.4) and compiled 102! See https://github.com/fusentasticus/libigl/commit/ec5f54de30a605647316fdab7236ac35c9e3a890
Another little version headache: for Linux, one of the dependencies (can't remember which one) from Intel asked to build with 4.8. But you write on libigl homepage that CGAL may not work with 4.8.  How to wrangle that one?

**Comment by alecjacobson** [comment]
Hard to say without more details. Do you mean that some other code from Intel requires CGAL version 4.8?

**Comment by Jiangjunfeng** [comment]
I use Eigen 3.1.

**Comment by Jiangjunfeng** [comment]
The Problem is sovled. Example 102 can be compiled and linked correctly. Thank you so much, Jacobson. The key is updating the version of eigen 3.1 to latest 3.2.4.
