### ISSUE TITLE
CGAL and GCC 4.8

### ISSUE THREAD

**Issue by MaelRL** [libigl/libigl#650]
Hello,

The front page of libigl states 

> The include/igl/copyleft/cgal/*.h headers depend on CGAL. It has come to our attention that CGAL does not work properly with GCC 4.8.

I cannot find anything related to that in your open or closed issues, could you please detail us what are the issues so that we can look into fixing them?

Thank you.

**Comment by alecjacobson** [comment]
I believe this combination was leading to issues with triangle-triangle intersection tests.

@qnzhou , do you remember?

**Comment by qnzhou** [comment]
@MaelRL See this thread: http://cgal-discuss.949826.n4.nabble.com/Bugs-in-AABBTree-td4660077.html

It is an old issue, and maybe CGAL has already fixed it.

**Comment by lrineau** [comment]
Hi libIGL, your message in the section [GCC and the Optional CGAL Dependency](https://libigl.github.io/#gcc-and-the-optional-cgal-dependency) is incorrect. The bug in in [in gcc 4.8.2 only, and fixed in gcc 4.8.3](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=58800).

**Comment by jdumas** [comment]
@alecjacobson is it ok to remove the message from the front page and keep an entry in the FAQ then? If 4.8.3 is the latest version of the 4.8 branch, people shouldn't have the issue anymore.

**Comment by lrineau** [comment]
There is even a gcc 4.8.4 : https://gcc.gnu.org/gcc-4.8/.
