### ISSUE TITLE
Variables named "I"  break build with EIGEN_USE_LAPACKE due to including <complex.h>

### ISSUE THREAD

**Issue by jpeoples** [libigl/libigl#651]
`Eigen/Dense` includes `complex.h` through the lapacke header (`Eigen/src/misc/lapacke.h`) when building with EIGEN_USE_LAPACKE defined.

The header `<complex.h>` defines `I` as the imaginary unit constant, which causes a bunch of cryptic parsing errors with variables or parameters named `I`. I encountered this with the `igl::decimate` function, and am not sure if it occurs elsewhere in libigl.

It can be worked around without disabling `EIGEN_USE_LAPACKE` by including Eigen yourself, then undef'ing I before including the header with the variable named `I`:
```
#include <Eigen/Dense>
#undef I
#include <igl/decimate.h>
```

**Comment by jdumas** [comment]
I think it's very similar to #679. There are three solutions to this problem:

1. Do nothing, and have the user implement the workaround you mentioned if they want to use Eigen with Lapack.
2. Undefine `I` and other stupid macros defined by third-party libraries. To achieve this one would need to replace all mentions of `#include <Eigen/Dense>` by something like `#include <igl/EigenDense.h>` that protects the rest of the code and `#undef` whatever symbols.
3. Avoid using problematic variables like `I` in libigl.

Solution 3. is obviously not acceptable, a third-party library should not pollute the current namespace and impose any particular practice on local variable names. I also don't think it's worth the trouble to go for 2. unless there is a serious reason for it. If a user needs lapack + igl they can protect all their include the way you describe already. So in the end I vote for 1.

**Comment by danielepanozzo** [comment]
I also vote for 1.

**Comment by jpeoples** [comment]
That sounds completely reasonable to me. It's unfortunate `complex.h` defines `I` as a macro!  It might be worth documenting though, since I know it took me a while to track down the source of the problem. In GCC at least, it prints so many lines of errors that it flooded the terminal's 1000 line buffer, and I had to redirect the output to a log file before I could even scroll back enough to track down the error to somewhere outside `libigl`.

**Comment by jdumas** [comment]
Yep we should have a FAQ or something =)
