### ISSUE TITLE
Is there a method to extrude a surface to a solid mesh in Libigl?

### ISSUE THREAD

**Issue by majsad** [libigl/libigl#653]
Dear All,

Is it possible to create a mesh from scratch using for example 10 points as vertices of a surface and then extrude the surface to have a closed 3D mesh in Libigl? (is there an extrude command?)

**Comment by alecjacobson** [comment]
I'm not sure what exactly you're imagining. Do the 10 points determine a flat 2D polygon? Or are they arbitrary points in 3D?

**Comment by majsad** [comment]
Case 1:  lets say that I have a set of points which make a 2 dimentional (flat) polygon and I want to extrude it to have a 3D mesh. Is it posible? Is it also possible to make that 2D polygon with libigl (without manually defining faces)?

Case 2: The set of points which make the surface are in the 3D space, so the surface is a 3D surface (or polygon) can this be extruded?

Thanks.

**Comment by alecjacobson** [comment]
We don't have tools for this directly.

I'd recommend:

1. projecting the points onto a common 2D plane,
2. using igl::triangle::triangulate to construct the 2D polygon, and
3. generating a strip of triangles around the boundary for the extrusion.

You could have a look at extrude.m in gptoolbox for a MATLAB implementation
of step 3.

**Comment by majsad** [comment]
Thanks.
