### ISSUE TITLE
How to use libigl in an existing MSVC project?

### ISSUE THREAD

**Issue by majsad** [libigl/libigl#655]
Dear All,

I chenged the Cmake file of the example project to include cgal and then configured and built it with Cmake GUI and MSVC and could do cgal::Boolean with no proble.

My problem is that I want to use this with an existing project which does not use CMake. So I want to add the library (libigl) any dependencies manually to my project. How on earth is this possible?

Thanks.

**Comment by danielepanozzo** [comment]
I suggest that you use libigl in header-only mode, and then add whatever dependency you need (in your case it seems only CGAL) manually to your VS project. I am closing this issue since this is a generic c++ question which is not related to libigl, and we only support the build using cmake.

**Comment by majsad** [comment]
OK, thanks.
