### ISSUE TITLE
igl/mosek/mosek_linprog.cpp

### ISSUE THREAD

**Issue by KIKI007** [libigl/libigl#658]
Hi All,

I found a bug in the mosek_linprog.cpp file.

It implements like:

if(isfinite(lxj) && isfinite(uxj))
    {
      if(lxj == uxj)
      {
        **k = MSK_BK_RA;** //Here is k = MSK_BK_FX;
      }else{
        **k = MSK_BK_FX;** //Here is k = k = MSK_BK_RA;
      }
    }else if(isfinite(lxj))
    {
      k = MSK_BK_LO;
    }else if(isfinite(uxj))
    {
      k = MSK_BK_UP;
    }
    return k;
  };

**Comment by jdumas** [comment]
@danielepanozzo looks legit to me, according to [this](https://docs.mosek.com/7.0/capi/Bound_keys.html), the two should be flipped no?

**Comment by danielepanozzo** [comment]
Yes, I think they should be flipped. This code is used by functions written by @alecjacobson , let's wait for his approval before proceeding with the fix.
