### ISSUE TITLE
LSCM Parametrization

### ISSUE THREAD

**Issue by BorisMansencal** [libigl/libigl#66]
Hello,

 I am trying to compute the parametrization of the following mesh:
https://bfs.u-bordeaux.fr/telecharge.php?id=40014  (~75MB)

I have tried with code from tutorial 502_LSCMParam.
I get the following errors:
Error: Numerical issue.
Error: invalid solver type

It seems to come from min_quad_with_fixed.cpp
If I compile with -DMIN_QUAD_WITH_FIXED_CPP_DEBUG, I get the following messages:
    pre
    Aeq_li=true
    factorize
    llt
Error: Numerical issue.
Error: invalid solver type

(I get the same errors with 503_ARAPParam)

Do you have any recommandation to avoid this issue ?

I am on linux (Fedora 19, gcc 4.8.3).

thank you,

Boris.

**Comment by alecjacobson** [comment]
I've updated `igl::lscm` to return a boolean indicating success. The most common reason for failure is bad input. For example your mesh has 69373 un-referenced vertices and 90 non-trivial connected components. With our implementation of LSCM (and ARAP):

 1. un-referenced vertices should be removed _ante hoc_, for example with (`igl::remove_unreferenced`), and
 2. at least two vertices of each component should be fixed. In the tutorial example there's only one component. You could use `igl::connected_components` to find the largest connected component (and discard the rest) or you should fix more vertices.

Hope this helps (I'll also update the comments to better explain this.)
