### ISSUE TITLE
How do I set in higher order constraints as boundary conditions for the bilaplacian

### ISSUE THREAD

**Issue by MuhammadFarzi** [libigl/libigl#661]
I was using libigl for the discrete bi-laplacian and need to set higher order constraints as boundary conditions https://math.stackexchange.com/questions/818563/biharmonic-equation-boundary-conditions

How can I do this ? I would be grateful if you could point me to relevant articles.

Thanks!

**Comment by alecjacobson** [comment]
This is not directly supported in libigl, but would be a straightforward extension.

The relevant article to look at is "Mixed Finite Elements for Variational Surface Modeling" [Jacobson et al. 2010]. For example, to set Neumann boundary conditions one would need the `N` matrix described there.

Setting Laplacian values directly is much simpler. And finally setting normal derivatives of Laplacians should be possible by applying the N matrix on the auxiliary variables that are constrained to equal the Laplacian.
