### ISSUE TITLE
Unable to create eigen MatrixXi from python list or numpy matrix in pyigl

### ISSUE THREAD

**Issue by pilcru** [libigl/libigl#662]
I have been having issues with using the python bindings to instantiate matrices of integers (pyigl.eigen.MatrixXi) from python lists or numpy matrices. For example, trying to run tutorial 405_AsRigidAsPossible.py gives:

```
python 405_AsRigidAsPossible.py 
Traceback (most recent call last):
  File "405_AsRigidAsPossible.py", line 80, in <module>
    b = igl.eigen.MatrixXi([[t[0] for t in [(i, S[i]) for i in range(0, V.rows())] if t[1] >= 0]]).transpose()
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. pyigl.eigen.MatrixXi()
    2. pyigl.eigen.MatrixXi(arg0: int, arg1: int)
    3. pyigl.eigen.MatrixXi(arg0: int)
    4. pyigl.eigen.MatrixXi(arg0: buffer)
    5. pyigl.eigen.MatrixXi(arg0: std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >)
    6. pyigl.eigen.MatrixXi(arg0: std::vector<int, std::allocator<int> >)

Invoked with: [[8, 17, 23, 26, 29, 40, 55, 56, 57, 61, 73, 79, 82, 90, 102, 104, 105, 108, 111, 112, 116, 124, 126, 128, 130, 148, 155, 174, 175, 176, 177, 179, 180, 181, 190, 192, 197, 198, 199, 209, 218, 224, 245, 247, 260, 262, 264, 272, 276, 277, 303, 319, 334, 339, 342, 354, 355, 369, 372, 374, 390, 391, 394, 407, 417, 421, 435, 467, 473, 474, 475, 478, 500]]
```

Instantiating with a numpy array of int also fails, with the message `Incompatible buffer format!`. I can still create an empty MatrixXi of a given size, and then assign to its elements.

I've reproduced this on Windows (compiling with Visual Studio 2015 update 3, against python 3.5.4 and 2.7.12) and Linux (gcc 5.4.1, python 3.5.4), staying as close as I could to the [CMakeLists](../tree/master/python/CMakeLists.txt). This is all on a fresh checkout of master.

I thought I was not compiling properly (first time using libigl) but it does not seem to be the issue. Is this maybe more of a pybind11+eigen issue that I should file there, or is the issue coming directly from the bindings defined in [py_vector.cpp](../tree/master/python/modules/py_vector.cpp)? Am I just doing something wrong?

**Comment by jiangzhongshi** [comment]
You should be able to use `dtype=np.int32` to initialize the `numpy` array, which will be compatible with buffer format. 

That being said, there does seem to be something wrong here on accepting list as input.

**Comment by pilcru** [comment]
Hi, thanks for looking at this.

Actually, the only `dtype` that has worked for me on windows is the "compatible C int", `intc`, or `i` for short. `int32` is the default (so it is already using that when converting from a list), and it gets taken to a "compatible Python int" through the C interface, `int_` or `l`. I'm using [this page](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.scalars.html#arrays-scalars-built-in) of the numpy docs for reference.

`i` and `l` have the same length on most (all?) platforms, so they should be compatible, but [this line](https://github.com/libigl/libigl/blob/a630c8e27330c75767e40e821173878049b36458/python/modules/py_vector.cpp#L35) tests for format name rather than format size, so it fails.

It looks like pybind11 now recommends using their own [eigen bindings](http://pybind11.readthedocs.io/en/stable/advanced/cast/eigen.html) rather than [this](http://pybind11.readthedocs.io/en/stable/advanced/pycpp/numpy.html) which is what libigl's `py_vector.cpp` seems to be based on. Maybe that's something to check out? Or you've already found that it doesn't match your requirements? From the pybind11 doc:

> For a much easier approach of binding Eigen types (although with some limitations), refer to the section on Eigen.

**Comment by jdumas** [comment]
Yes updating the eigen python bindings for libigl is on the TODO list. PR welcome :p

**Comment by jiangzhongshi** [comment]
It may work to open another issue for this. But using the pybind11+eigen binding is quite straightforward to do, simply delete the current `py_vector.*` and add corresponding includes.

The one thing that held me back, was use `Eigen::Ref<Matrix>`(pybind style) as an argument to a function taking `Matrix&` as a parameter, as to bind `void foo(Eigen::MatrixXd& A)`

**Comment by arch-chen** [comment]
hi,
now,i have  the same quesiton, i want to konw ,how to slove  it ,finally ?
thanks

**Comment by arch-chen** [comment]
oh,
I can‘t wait to try  the new version. In short, thanks for your reply

**Comment by changhongjian** [comment]
I add the code in **py_vector.cpp**,  then the bug fixed.
```c++
// .def("__init__", [](Type &m, py::buffer b) {
//            py::buffer_info info = b.request();

if (info.format != py::format_descriptor<Scalar>::format()) {
    if (info.format == "l" && py::format_descriptor<Scalar>::format()=="i") {
    }else throw std::runtime_error("Incompatible buffer format!");
}

// if (info.ndim == 1) {
        // new (&m) Type(info.shape[0], 1);
        // memcpy(m.data(), info.ptr, sizeof(Scalar) * m.size());
```

**Comment by teseoch** [comment]
ARAP is part of the new python bindings which are compatible with numpy.
This shouldnt be an issue anymore
