### ISSUE TITLE
Could you provide instructions for creating pyigl functions?

### ISSUE THREAD

**Issue by HTDerekLiu** [libigl/libigl#663]
Hi All,

I would like to use some libigl functions, such as offset_surface, which do not yet exist in pyigl. Could you provide step-by-step instructions for creating wrapper functions? I am happy to create pull requests after making changes. Thanks!

**Comment by zero-impact** [comment]
Check out my recent pull request which does exactly this for writeDMAT
https://github.com/libigl/libigl/pull/665/commits/37e79290dc8b6525e3304cc98eb9e14271ed0d0d
