### ISSUE TITLE
igl::copyleft::cgal::remesh_self_intersections crashes when input is already exact

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#664]
I've discussed a bit already with @qnzhou , but the current parallel implementation of `igl::copyleft::cgal::remesh_self_intersections` is buggy. The following code (wish it were more minimal ) compiles using commit c2b500b3ac2c3eb2141cf33c549d5ac66e623261 and will sporadically crash due to bad access:

```
#include <Eigen/Core>
#include <igl/readDMAT.h>
#include <igl/slice_tets.h>
#include <igl/combine.h>
#include <igl/copyleft/cgal/assign.h>
#include <igl/copyleft/cgal/remesh_self_intersections.h>
#include <iostream>
int main(int argc, char * argv[])
{
  Eigen::MatrixXd V,Ud;
  Eigen::MatrixXi T,F;
  igl::readDMAT("V.dmat",V);
  igl::readDMAT("U.dmat",Ud);
  igl::readDMAT("T.dmat",T);T.array() -= 1;
  Ud.rowwise() -= Ud.colwise().minCoeff();
  Ud.array() *= 6.0/Ud.maxCoeff();
  Ud.array() += 0.5;

  for(int iter = 0;iter<100;iter++)
  {
    std::cout<<iter<<std::endl;
    typedef Eigen::Matrix<CGAL::Epeck::FT,Eigen::Dynamic,3> MatrixX3E;
    typedef Eigen::Matrix<CGAL::Epeck::FT,Eigen::Dynamic,1> VectorXE;
    MatrixX3E Ue;
    std::vector<MatrixX3E> Vlist;
    std::vector<Eigen::MatrixXi> Flist;
    igl::copyleft::cgal::assign(Ud,Ue);
    for(int c = 0;c<3;c++)
    {
      CGAL::Epeck::FT iso = ceil(Ud.col(c).minCoeff());
      while(true)
      {
        VectorXE X;
        igl::copyleft::cgal::assign(Ud.col(c),X);
        for(int j = 0;j<X.size();j++)
        {
          X(j) = X(j)-iso;
        }
        if(X.minCoeff() < 0 && X.maxCoeff() > 0)
        {
          MatrixX3E Vc;
          Eigen::MatrixXi Fc;
          Eigen::VectorXi _;
          igl::slice_tets(V,T,X,Vc,Fc,_);
          Vlist.push_back(Vc);
          Flist.push_back(Fc);
        }
        iso=iso+1;
        if(iso >= floor(Ud.col(c).maxCoeff()))
        {
          break;
        }
      }
    }
    MatrixX3E VV;
    Eigen::MatrixXi FF;
    {
      Eigen::VectorXi _1,_2;
      igl::combine(Vlist,Flist,VV,FF,_1,_2);
    }
    igl::copyleft::cgal::RemeshSelfIntersectionsParam params;
    params.stitch_all = true;
    MatrixX3E SV;
    Eigen::MatrixXi SF;
    {
      Eigen::MatrixXi IF;
      Eigen::VectorXi I,SJ;
      igl::copyleft::cgal::remesh_self_intersections(VV,FF,params,SV,SF,IF,SJ,I);
    }
  }
}
```

This code is extracting the _exact_ level-set surfaces from scalar field define inside of a floating point tet-mesh. Then it resolves all intersections between many level sets.

It runs many iterations of the same thing hoping to illicit a crash (e.g., last time I ran it, it didn't crash until the 5th iterations).

My current hypothesis is that this is crashing due to the fact that **reading**  `CGAL::Lazy_exact_nt` variable type is _not thread-safe_. Typically the input mesh to `igl::copyleft::cgal::remesh_self_intersections` has vertex positions at floating point positions. But in my case the input is already "Exact" and specifically the vertex positions on the level set share common data in their rational expressions (i.e., the original scalar field and tet mesh).

Our current implementation uses mutex-locks around each vertex and triangle but this is not enough if two vertices actually share common sub-expressions.

> I'm using Apple LLVM version 9.0.0 (clang-900.0.39.2), CGAL 4.11 and I'm on MacBook Pro with a 3.5 GHz Intel Core i7

[data.zip](https://github.com/libigl/libigl/files/1576473/data.zip)

**Comment by dyollb** [comment]
I am getting this error too. My test case is a bent pipe (attached).

[pipe.zip](https://github.com/libigl/libigl/files/6630192/pipe.zip)

My system:
- VS 2019
- IGL 2.3.0
- CGAL 4.9

**Comment by dyollb** [comment]
> I am getting this error too. My test case is a bent pipe ([pipe.zip](https://github.com/libigl/libigl/files/6630192/pipe.zip)).
> 
> My system:
> 
> * VS 2019
> * IGL 2.3.0
> * CGAL 4.9
> * boost 1.74
> 
> The crash occurs in mesh_to_cgal_triangle_list. I don't see how this could be related to thread-safety, since this function is just copying the triangles in a simple for loop.

EDIT: sorry, but this was just a bug on my side. I was declaring vertices and faces as Eigen::Matrix3Xd

**Comment by dyollb** [comment]
btw. I found a copy of your code in Easy3D, without any mention/acknowledgement of libigl:
https://github.com/LiangliangNan/Easy3D/blob/main/easy3d/algo_ext/self_intersection.cpp

**Comment by alecjacobson** [comment]
This seems to have fixed by time. Here's the updated test code which appears to work fine:

```cpp
#include <Eigen/Core>
#include <igl/readDMAT.h>
#include <igl/marching_tets.h>
#include <igl/combine.h>
#include <igl/copyleft/cgal/assign.h>
#include <igl/copyleft/cgal/remesh_self_intersections.h>
#include <iostream>
int main(int argc, char * argv[])
{
  Eigen::MatrixXd V,Ud;
  Eigen::MatrixXi T,F;
  igl::readDMAT("V.dmat",V);
  igl::readDMAT("U.dmat",Ud);
  igl::readDMAT("T.dmat",T);T.array() -= 1;
  Ud.rowwise() -= Ud.colwise().minCoeff();
  Ud.array() *= 6.0/Ud.maxCoeff();
  Ud.array() += 0.5;

  for(int iter = 0;iter<100;iter++)
  {
    std::cout<<iter<<std::endl;
    typedef Eigen::Matrix<CGAL::Epeck::FT,Eigen::Dynamic,3> MatrixX3E;
    typedef Eigen::Matrix<CGAL::Epeck::FT,Eigen::Dynamic,1> VectorXE;
    MatrixX3E Ue;
    std::vector<MatrixX3E> Vlist;
    std::vector<Eigen::MatrixXi> Flist;
    igl::copyleft::cgal::assign(Ud,Ue);
    for(int c = 0;c<3;c++)
    {
      CGAL::Epeck::FT iso = ceil(Ud.col(c).minCoeff());
      while(true)
      {
        VectorXE X;
        igl::copyleft::cgal::assign(Ud.col(c),X);
        if(X.minCoeff() < 0 && X.maxCoeff() > 0)
        {
          MatrixX3E Vc;
          Eigen::MatrixXi Fc;
          igl::marching_tets(V,T,X,iso,Vc,Fc);
          Vlist.push_back(Vc);
          Flist.push_back(Fc);
        }
        iso=iso+1;
        if(iso >= floor(Ud.col(c).maxCoeff()))
        {
          break;
        }
      }
    }
    MatrixX3E VV;
    Eigen::MatrixXi FF;
    {
      Eigen::VectorXi _1,_2;
      igl::combine(Vlist,Flist,VV,FF,_1,_2);
    }
    igl::copyleft::cgal::RemeshSelfIntersectionsParam params;
    params.stitch_all = true;
    MatrixX3E SV;
    Eigen::MatrixXi SF;
    {
      Eigen::MatrixXi IF;
      Eigen::VectorXi I,SJ;
      igl::copyleft::cgal::remesh_self_intersections(VV,FF,params,SV,SF,IF,SJ,I);
    }
  }
}
```
