### ISSUE TITLE
libigl boolean union fail

### ISSUE THREAD

**Issue by majsad** [libigl/libigl#670]
Dear All, 

I have two simple triangular small meshes. 
igl::copyleft::cgal::mesh_boolean(VA, FA, VB, FB, igl::MESH_BOOLEAN_TYPE_UNION, VC, FC);
fails to out put the right object, it only outputs one of the meshes.

Here are input meshes:
[input.zip](https://github.com/libigl/libigl/files/1588826/input.zip)

And this is the output:
[output.zip](https://github.com/libigl/libigl/files/1588827/output.zip)

What is going wrong here?

**Comment by alecjacobson** [comment]
The input mesh `alltricleansubdividedsASCII_OpenMesh.off` has
inconsistently oriented faces. In this case, you can probably fix it with
`igl::bfs_orient`

Although our mesh boolean input preconditions are less strict than other
boolean libraries, we still have restrictions. The input meshes must be
"PWN":

http://www.cs.columbia.edu/cg/mesh-arrangements/#definitions

**Comment by majsad** [comment]
thanks a lot. How can I check my meshes for future cases? How did you find out the problem?

I am making that mesh using an extrude command from a polydata in VTK. Are you aware of possible errors in their extrude command?

**Comment by alecjacobson** [comment]
The method `igl::copyleft::cgal::piecewise_constant_winding_number` can be used to validate input meshes.

I don't know anything about VTK, but it looks like the extruded part of the input is inverted with respect to the original faces.

**Comment by majsad** [comment]
Thanks.

I used `igl::copyleft::cgal::piecewise_constant_winding_number` to check.

I tried with `igl::bfs_orient(FA, FA2, BoolVecI);` but when I check the mesh with old VA and new FA2 the output of PWN test is still false.

Should I use `igl::embree::reorient_facets_raycast` since my mesh is a closed one?

When I try that I need to add `C:\libigl\external\embree\include` to my projects additional include directories. but then I get a bunch of these errors when compiling:

error LNK2019: unresolved external symbol __imp_rtcInit referenced in function "public: void __cdecl igl::embree::EmbreeIntersector::init(class std::vector<class Eigen::Matrix<float,-1,3,0,-1,3> const *,class std::allocator<class Eigen::Matrix<float,-1,3,0,-1,3> const *> > const &,class std::vector<class Eigen::Matrix<int,-1,3,0,-1,3> const *,class std::allocator<class Eigen::Matrix<int,-1,3,0,-1,3> const *> > const &,class std::vector<int,class std::allocator<int> > const &,bool)" (?init@EmbreeIntersector@embree@igl@@QEAAXAEBV?$vector@PEBV?$Matrix@M$0?0$02$0A@$0?0$02@Eigen@@V?$allocator@PEBV?$Matrix@M$0?0$02$0A@$0?0$02@Eigen@@@std@@@std@@AEBV?$vector@PEBV?$Matrix@H$0?0$02$0A@$0?0$02@Eigen@@V?$allocator@PEBV?$Matrix@H$0?0$02$0A@$0?0$02@Eigen@@@std@@@5@AEBV?$vector@HV?$allocator@H@std@@@5@_N@Z)

Any idea?

**Comment by alecjacobson** [comment]
I'd start with igl::bfs_orient . If the problems are simple then this
should work (it might invert your entire model though)

**Comment by majsad** [comment]
Dear @alecjacobson 

I did try with `igl::bfs_orient` and it did not work. When I check the mesh, the output of PWN test is still false.

I have also provided the meshes, they have a cery small number of faces (less than 20 I think) can you give it a try and see why it does not work?

What is the problem with `igl::embree::reorient_facets_raycast` ? 

Thanks for your time.

**Comment by alecjacobson** [comment]
It seems your mesh is fully _un_-connected. You'll need to first merge duplicate vertex positions before calling `bfs_orient`

```
#include <Eigen/Core>
#include <igl/viewer/Viewer.h>
#include <igl/read_triangle_mesh.h>
#include <igl/bfs_orient.h>
#include <igl/remove_duplicate_vertices.h>
int main(int argc, char * argv[])
{
  Eigen::MatrixXd V;
  Eigen::MatrixXi F;
  igl::read_triangle_mesh(argv[1],V,F);
  {
    Eigen::VectorXi _1,_2;
    igl::remove_duplicate_vertices(
     Eigen::MatrixXd(V),
     Eigen::MatrixXi(F),
     1e-16,
     V,
     _1,_2,
     F);
  }
  {
    Eigen::VectorXi _;
    igl::bfs_orient(Eigen::MatrixXi(F),F,_);
  }

  igl::viewer::Viewer v;
  v.data.set_mesh(V,F);
  v.launch();
}
```

Nothing is wrong with `reorient_facets_raycast` it's just not needed in such a simple case.

**Comment by majsad** [comment]
Thanks alot @alecjacobson 

I was already using a command in VTK to remove duplicate vertices, but apparently I could not set it right.

With libigl it works now. How can you find out that there are duplicate vertices? How can I check that for any mesh?

**Comment by alecjacobson** [comment]
To find exact duplicates I would use igl::unique_rows

to remove them, then I'd use

igl::remove_duplicate_vertices

**Comment by majsad** [comment]
Thanks
