### ISSUE TITLE
piecewise_constant_winding_number compilation error.

### ISSUE THREAD

**Issue by majsad** [libigl/libigl#674]
Very strangly sometimes when I try to compile my code which includes `#include <igl/copyleft/cgal/piecewise_constant_winding_number.h>` the compiler says:

`Error	C2780	'bool igl::copyleft::cgal::piecewise_constant_winding_number(const Eigen::PlainObjectBase<Derived> &,const Eigen::PlainObjectBase<DerivedF> &)': expects 2 arguments - 3 provided	QtGuiApplication2	c:\libigl\include\igl\copyleft\cgal\propagate_winding_numbers.cpp	121	
`

And actually in that code there are 3 input arguments for piecewise_constant_winding_number as here:

  bool valid = true;
  if (!piecewise_constant_winding_number(F, uE, uE2E)) 
  {
    assert(false && "Input mesh is not orientable");
    std::cerr << "Input mesh is not orientable!" << std::endl;
    valid = false;
  }

Is this an error in libigl?

**Comment by alecjacobson** [comment]
You shouldn't be getting this error. Line 121 in
include/igl/copyleft/cgal/propagate_winding_number.cpp is call the version
of piecewise_constant_winding_number with 3 arguments defined in
include/igl/piecewise_constant_winding_number.h since this file is included
by the line 14 #include "../../piecewise_constant_winding_number.h"

What is your compilation setup ?

Did you change any of the files in libigl?

**Comment by majsad** [comment]
I did not manually edit any igl codes.

What exactly do you mean by compilation setup?
I am on windows 7, MSVC2015, release, x64 and I have these headers:

```
#include <igl/readOFF.h>
#include <igl/writeOFF.h>
#include <igl/copyleft/cgal/mesh_boolean.h>
#include <igl/copyleft/cgal/piecewise_constant_winding_number.h>
#include <Eigen/Core>
//#include <igl/embree/reorient_facets_raycast.h>
#include <igl/bfs_orient.h>
#include <igl/remove_duplicate_vertices.h>
```

Then I call it this way:

```
bool outputvalue;
outputvalue = igl::copyleft::cgal::piecewise_constant_winding_number(VA, FA);
```

**Comment by alecjacobson** [comment]
Do you still get the error if you change:

if (!piecewise_constant_winding_number(F, uE, uE2E))

to

if (!igl::piecewise_constant_winding_number(F, uE, uE2E))

**Comment by majsad** [comment]
Dear @alecjacobson 

Thanks, when I apply the change you mentioned, it does not give any error.

But is it a safe method? I am not sure why and from where that code is being called! And very starangly it only happen some times, not every time I compile.

**Comment by alecjacobson** [comment]
I'm really not sure either. I thought that being in the igl::copyleft::cgal
namespace meant that you're also in the igl:: namespace. Maybe that's not
true on visual studio? Or maybe it's just running into a bug in the
compiler (rare... probably not).
-Alec

**Comment by alecjacobson** [comment]
I've also pushed this change to my branch 1e62abf0 which will eventually go into master.
