### ISSUE TITLE
Problem related to /libigl/include/igl/xml/serialize_xml.cpp

### ISSUE THREAD

**Issue by tingyizhou** [libigl/libigl#676]
Hi, I'm installing a package which contains part of libigl. However, when it run /libigl/include/igl/xml/serialize_xml.cpp, a lot of errors occurred. For example, in line 46,
 _tinyxml2::XMLError error = doc->LoadFile(filename.c_str());_  
an error ocurred:
 _‘XMLError’ is not a member of ‘tinyxml2’_.
 And I can't find any reference related to tinyxml2::XMLError, according to document **http://leethomason.github.io/tinyxml2/functions.html.**  , I can only find some example like
 _XMLError tinyxml2::XMLDocument_
Other problems are just like _‘class tinyxml2::XMLDocument’ has no member named ‘Clear’_ ,claiming the nonexistence of members.

**Comment by jdumas** [comment]
Looks like you forgot to link against `igl::xml` in your CMake build. Be sure to enable `LIBIGL_WITH_XML` and link against the target `igl::xml`.
