### ISSUE TITLE
tetrahedralize an open mesh

### ISSUE THREAD

**Issue by etrigger** [libigl/libigl#684]
I have a mesh that is not closed and I want to tetrahedralize it.
![image](https://user-images.githubusercontent.com/3329503/35830248-d8a5b30a-0ac5-11e8-8273-e69ff6ba8031.png)
[bodypart.obj.zip](https://github.com/libigl/libigl/files/1696887/bodypart.obj.zip)

//// Tetrahedralized interior
Eigen::MatrixXd TV;
Eigen::MatrixXi TT;
Eigen::MatrixXi TF;
igl::readOBJ("../shared/bodypart.obj", V, F);
igl::copyleft::tetgen::tetrahedralize(V, F, "pq1.414Y", TV, TT, TF);

I got some error and no tetrahedron is generated. Any suggestion to fix it?

Delaunizing vertices...
Delaunay seconds:  0.002
Creating surface mesh ...
Surface mesh seconds:  0
Recovering boundaries...
Boundary recovery seconds:  0
Removing exterior tetrahedra ...
Exterior tets removal seconds:  0.001
Recovering Delaunayness...
Delaunay recovery seconds:  0
Refining mesh...
Refinement seconds:  0
Optimizing mesh...
Optimization seconds:  0
Jettisoning redundant points.

Writing nodes.
Writing edges.

Output seconds:  0
Total running seconds:  0.004

Statistics:

  Input points: 268
  Input facets: 483
  Input segments: 751
  Input holes: 0
  Input regions: 0

  Mesh points: 0
  Mesh tetrahedra: 0
  Mesh faces: 0
  Mesh faces on facets: 0
  Mesh edges on segments: 0

^igl::copyleft::tetgen::tetrahedralize: Tetgen failed to create tets
igl::viewer::Viewer usage:
  [drag]  Rotate scene
  A,a     Toggle animation (tight draw loop)
  F,f     Toggle face based
  I,i     Toggle invert normals
  L,l     Toggle wireframe
  O,o     Toggle orthographic/perspective projection
  T,t     Toggle filled faces
  Z       Snap to canonical view
  [,]     Toggle between rotation control types (trackball, two-axis
          valuator with fixed up, 2D mode with no rotation)
  ;       Toggle vertex labels
  :       Toggle face labels

**Comment by danielepanozzo** [comment]
igl::tetrahedralize is a wrapper around tetgen. You cannot tetrahedralize an open surface since the interior is not well defined. Tetgen will only succeed on closed, manifold meshes without self-intersections.

You need to clean the mesh first, making it closed, and then it should work.

**Comment by alecjacobson** [comment]
You can call

igl::copyleft::tetgen::cdt to give you a tetrahedralization of the entire
convex hull

and then use igl::winding_number to extract the tets on the interior

If your mesh has self-intersections, then you should mesh these in advance
of calling `cdt`, using `igl::copyleft::cgal::remesh_self_intersections
