### ISSUE TITLE
How are external libraries, cork and tinyXML2, added to example project?

### ISSUE THREAD

**Issue by ryuuguu** [libigl/libigl#685]
Specifically I would like to use cork and tinyXML2 with Eigen matrices.
I can get the example project setup to run with my own code but not when calling external libraries tinyXML2 or Cork.

I can get tinyXML2 to run if I put my project under tutorial and copy the 601_Serialization MakeLists.txt but not outside the libigl tree as the example project suggests. 

Things I have tried.

Changing XML to ON
option(LIBIGL_WITH_XML              "Use XML"            ON)
and adding igl::xml to the target_link_libraries as in
target_link_libraries(${PROJECT_NAME}_bin igl::core igl::viewer igl::xml )

CMake Error at CMakeLists.txt:30 (add_executable):
  Target "example_bin" links to target "igl::xml" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
  
I could not find any references to XML in the CMakeLists.txt in the project with find_package.

I have been 
unable to use serialize_xml with any Eigen::Matrix even in Tutorial 
for example adding the line 

 igl::xml::serialize_xml(stateIn.V,"VectorXML",xmlFile,false,true);
 causes make errors
Undefined symbols for architecture x86_64:
  "void igl::xml::serialize_xml<Eigen::Matrix<double, -1, -1, 0, -1, -1> >(Eigen::Matrix<double, -1, -1, 0, -1, -1> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, bool)", referenced from:
      _main in main.cpp.o
  "void igl::xml::deserialize_xml<Eigen::Matrix<double, -1, -1, 0, -1, -1> >(Eigen::Matrix<double, -1, -1, 0, -1, -1>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      _main in main.cpp.o
ld: symbol(s) not found for architecture x86_64

	
Also I do not understand how to get the cork library to run even in tutorial.			
I tried adding to 
tutorial/CMakeLists.txt 
and changed OFF to ON
option(LIBIGL_WITH_CORK             "Use CORK"           ON)
Cmake works but final make still failed

	
609_Boolean/CMakeLists.txt	
tried adding 	igl::copyleft::cork or igl::cork to	
target_link_libraries(${PROJECT_NAME}_bin igl::core igl::cgal igl::viewer  tutorials)
but Cmake did not like this

change main.cpp to			
igl::copyleft::cork::mesh_boolean(VA,FA,VB,FB,boolean_type,VC,FC,J);
but this would not make

**Comment by jdumas** [comment]
Did you properly clone the submodules? Did you clean your `CMakeCache.txt` after changing the option and before trying to recompile your project?

**Comment by ryuuguu** [comment]
Thanks for the advice.
I have 
Recloned libgil and example project
git clone --recursive https://github.com/libigl/libigl.git
built libigl tutorials
changed Example CMakeList.txt
turned on CGAL, cork and XML
target_link_libraries(${PROJECT_NAME}_bin igl::core igl::viewer igl::xml igl::cgal igl::cork)

igl::xml::serialize_xml() works fine with  std::vector<float> (thanks)
it did not work with Eigen::MatrixXd  or the State class in 601_Serialization, but that may be my misunderstanding that it could serialize igl::Serializable derived classes.

CGAL worked in the Example. I changed the include and method name to cork from CGAL
#include <igl/copyleft/cork/mesh_boolean.h>
igl::copyleft::cork::mesh_boolean(
removed the 8th parameter as the compiler said only 7 were allowed and I assumed cork did not return J list of birth parent indices

this did not compile.
Error
Undefined symbols for architecture x86_64:
  "computeUnion(CorkTriMesh, CorkTriMesh, CorkTriMesh*)", referenced from:
  void igl::copyleft::cork::mesh_boolean<Eigen::Matrix<double, -1, -1, 0, -1, -1>,, ...

I am using eigen 3.3 with the latest brew install
any suggestions?

**Comment by jdumas** [comment]
I have no idea about serializing Eigen matrices. (I would suggest to use [json](https://github.com/nlohmann/json) to serialize stuff, XML is a horrible format).

Regarding the second error, are you sure you are compiling libigl in header-only mode? It could be a  missing template instantiation. Otherwise, please post a MWE so we can reproduce your problem.

**Comment by alecjacobson** [comment]
Perhaps Daniele can comment about the XML serialization. I always use .dmat
(readDMAT and writeDMAT) for serializing dense matrices.

**Comment by danielepanozzo** [comment]
The XML stuff has not been maintained in a long time, since serialization.h is superior (self-contained, way faster and more compact). The only downside is that it is not editable with a text editor. I have in my todo list to remove this feature (and drop tynyxml2). If you think it is useful, we could convert it to use json (I agree with Jeremie that it is the way to go now that is finally well supported in c++). What do you think?

@ryuuguu I suggest to use the binary serialization format in serialization.h
