### ISSUE TITLE
readSTL issues (coredumps, wrong ascii/binary detection/behaviour)

### ISSUE THREAD

**Issue by 0x6373** [libigl/libigl#686]
While trying to use the Viewer with STL files i found several issues:
* freopen() caused coredumps (i'm on OpenBSD), so i replaced it with fseek() where appropriate
* when reading an ascii STL file it was positioning to the start of file (with freopen) instead of positioning behind "solid " so that the solid name could be read.

I have a diff (see below) for this which allows me to successfully load both ascii and binary STL files.

Since there are some issues regarding freopen (#562, #625) i think replacing it with fseek is a good idea since it should work on all platforms.
Also, at least on OpenBSD the "b" flag for opening/reopening files as binary is obsolete, ignored and only available for ANSI X3.159-1989 ("ANSI C89") compatability.

Could someone test this on Linux/Mac/Win?

```
diff --git a/include/igl/readSTL.cpp b/include/igl/readSTL.cpp
index e0eebfd0..43593db8 100644
--- a/include/igl/readSTL.cpp
+++ b/include/igl/readSTL.cpp
@@ -71,18 +71,13 @@ IGL_INLINE bool igl::readSTL(
   std::vector<std::vector<TypeN> > & N)
 {
   using namespace std;
-  stl_file = freopen(NULL,"rb",stl_file);
-  if(NULL==stl_file)
-  {
-    fprintf(stderr,"IOError: stl file could not be reopened as binary (1) ...\n");
-    return false;
-  }
+  
+  fseek(stl_file,0,SEEK_SET);
 
   V.clear();
   F.clear();
   N.clear();
 
-
   // Specifically 80 character header
   char header[80];
   char solid[80];
@@ -120,16 +115,9 @@ IGL_INLINE bool igl::readSTL(
 
   if(is_ascii)
   {
-    // Rewind to end of header
-    //stl_file = fopen(filename.c_str(),"r");
-    stl_file = freopen(NULL,"r",stl_file);
-    if(NULL==stl_file)
-    {
-      fprintf(stderr,"IOError: stl file could not be reopened as ascii ...\n");
-      return false;
-    }
-    // Read 80 header
-    // Eat file name
+    // Rewind to after "solid" statement
+    fseek(stl_file,6,SEEK_SET);
+
 #ifndef IGL_LINE_MAX
 #  define IGL_LINE_MAX 2048
 #endif
@@ -213,7 +201,7 @@ IGL_INLINE bool igl::readSTL(
   }else
   {
     // Binary
-    stl_file = freopen(NULL,"rb",stl_file);
+    fseek(stl_file,0,SEEK_SET);
     // Read 80 header
     char header[80];
     if(fread(header,sizeof(char),80,stl_file)!=80)

```

**Comment by alecjacobson** [comment]
I think you have an old version. The current version of igl::readSTL no longer uses freopen.

**Comment by alecjacobson** [comment]
https://github.com/libigl/libigl/blob/master/include/igl/readSTL.cpp#L217

**Comment by 0x6373** [comment]
You're right, this has been fixed.
But i think the name-reading is still wrong.
So if the file start with "solid somename" it would currently read "solid somename" into variable name instead of only "somename".

This diff would fix that:
```
diff --git a/include/igl/readSTL.cpp b/include/igl/readSTL.cpp
index fcdeddcd..31a3fb49 100644
--- a/include/igl/readSTL.cpp
+++ b/include/igl/readSTL.cpp
@@ -123,7 +123,7 @@ IGL_INLINE bool igl::readSTL(
     // Rewind to end of header
     //stl_file = fopen(filename.c_str(),"r");
     //stl_file = freopen(NULL,"r",stl_file);
-    fseek(stl_file, 0, SEEK_SET);
+    fseek(stl_file, 6, SEEK_SET);
     if(NULL==stl_file)
     {
       fprintf(stderr,"IOError: stl file could not be reopened as ascii ...\n");
```

**Comment by alecjacobson** [comment]
Ok, thanks. Right now we're just ignoring the name
