### ISSUE TITLE
boolean operator and color

### ISSUE THREAD

**Issue by alireza59** [libigl/libigl#687]
Does libgl boolean operator retain the polygon color?
Thank you.

**Comment by alecjacobson** [comment]
igl::copyleft::cgal::mesh_boolean has an output argument `J`:

```
J  #FC list of indices into [FA;FA.rows()+FB] revealing "birth" facet
```

This way you can retrieve color or any other per-face information from the input shapes. The `609_Boolean/main.cpp` is in fact using this to color the outputs red and green.

**Comment by alireza59** [comment]
Thank you for your quick answer.
