### ISSUE TITLE
Error!! incompatible constructor arguments. 

### ISSUE THREAD

**Issue by sharathjapa** [libigl/libigl#688]
For Tutorial Examples 304,305,401,402,405,504,505,507,604,605,607,708,709
Running pyigl on Ubuntu

Here is the error for one of the examples.

  File "/libigl/python/tutorial/304_LinearEqualityConstraints.py", line 27, in <module>
    b = igl.eigen.MatrixXi([[4331], [5957]])
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. pyigl.eigen.MatrixXi()
    2. pyigl.eigen.MatrixXi(arg0: int, arg1: int)
    3. pyigl.eigen.MatrixXi(arg0: int)
    4. pyigl.eigen.MatrixXi(arg0: buffer)
    5. pyigl.eigen.MatrixXi(arg0: std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >)
    6. pyigl.eigen.MatrixXi(arg0: std::vector<int, std::allocator<int> >)

Invoked with: [[4331], [5957]]

**Comment by jiangzhongshi** [comment]
I can confirm this on my side. It seems that somewhere [[4331], [5957]] is understood as `std::vector<double>`, since ` igl.eigen.MatrixXd([[4331], [5957]])` works without a problem.

` igl.eigen.MatrixXi(np.array([[4331], [5957]], dtype=np.int32))` will work as expected.

**Comment by sharathjapa** [comment]
libigl deals with eigen arrays but we are creating a numpy array. I guess this would yell as well!

**Comment by sharathjapa** [comment]
Yes! This did resolve the issue. Thank you

**Comment by teseoch** [comment]
Obsolete, we now use numpy
