### ISSUE TITLE
Loading polygonal quad-based meshes.

### ISSUE THREAD

**Issue by chrisidefix** [libigl/libigl#69]
`libigl` appears to only load triangle meshes properly. As the `README.md` suggests, most algorithms are:
> tailored to operate on a generic triangle mesh

However, I found the function `readOBJPoly` and the following comment in `readOBJ.cpp`:
> // THIS IS ANNOYING, I WANT TO READ QUADS, Why not?

Is reading quad-meshes supported in any format inside `libigl`. I could imagine, if most algorithms would fail on quad-meshes, they could also be triangulated quite easily.

I was just wondering if I am missing something or if loading quad-meshes is not supported?

**Comment by alecjacobson** [comment]
That comment is referring to the commented-out code beneath it. `readOBJpoly` will indeed read a pure-quad mesh.

If you have a mixture of quads and triangles then you can't store the indices in a matrix without deciding on some convention for the "missing indices" of the triangle rows. For that I suggest that you use the `std::vector` version and build your own matrices if you need them.

**Comment by chrisidefix** [comment]
Thanks Alec - I did that, but I guess my question should have been: Does the renderer also support quad meshes? I see a very distorted mesh when loading a quad obj files such as this simple one (see screenshots below from meshlab and libigl):

	v -10.0 -10.0 -10.0
	v -10.0 10.0 -10.0
	v 10.0 10.0 -10.0
	v 10.0 -10.0 -10.0

	v -10.0 -10.0 10.0
	v -10.0 10.0 10.0
	v 10.0 10.0 10.0
	v 10.0 -10.0 10.0

	f 1 2 3 4
	f 5 6 2 1
	f 7 8 4 3
	f 8 7 6 5

Am I doing something wrong when parsing the face indices?
    
    [...]
    Eigen::MatrixXi F;
    std::vector<std::vector<int> > qF;
    igl::readOBJPoly(input_file.c_str(), V, qF, CN, FN, TC, FTC);
    igl::list_to_matrix(qF,F);
    igl::Viewer viewer;
    viewer.data.set_mesh(V, F);
    [...]


![obj_test](https://cloud.githubusercontent.com/assets/382555/7370528/f9dd7b3c-edba-11e4-8971-98ac46b493a6.jpg)

**Comment by alecjacobson** [comment]
No, the Viewer does not support quad/poly meshes. Unless specifically
mentioned in the comments/headers, you can safely assume that libigl will
only function correctly on triangle meshes.

**Comment by chrisidefix** [comment]
Ok, thanks. I am still a bit confused. It looks like the viewer has some very basic draw routine `IGL_INLINE void igl::OpenGL_state::draw_mesh(bool solid)`, which indeed assumes everything it receives is a triangle and uses `glDrawElements(GL_TRIANGLES, 3*F_vbo.cols(), GL_UNSIGNED_INT, 0);` for drawing.

However, I also found drawing functions inside the files `draw_mesh.h/.cpp`, which appear very capable for rendering quad meshes and which are used inside the examples section frequently.

Unless, I am missing something important, ideally the viewer should be calling this - what appears to be a - more advanced `draw_mesh` function?

I assume for historical reasons the viewer is trying to be independent from other libigl code. But I am still left wondering, if is something worth changing in favour of a more advanced viewer?

**Comment by alecjacobson** [comment]
The Viewer is not really meant to be a project base or even a fully
functional mesh viewer. We just need a basic viewer to demo the functions
in the core library and to make the tutorial more visual.

For various reasons, the viewer is written using modern OpenGL (buffer
objects, no immediate mode, etc.).

`igl::draw_mesh` indeed handles quads. I've pushed an update to its header
comments. But `draw_mesh` uses old-style opengl.

**Comment by chrisidefix** [comment]
Looks like `draw_mesh.h/.cpp` is using `GL_QUADS` for rendering quad meshes, which apparently has been deprecated a while ago and actually been removed from OpenGL 4.

However, for the moment should I theoretically be able to use something like this?

`glDrawElements(GL_QUADS, 4*F_vbo.cols(), GL_UNSIGNED_INT, 0);`?

I made the required changes to add support for quad-rendering, but something doesn't quite work, yet.

**Comment by danielepanozzo** [comment]
Yes, quad/polygonal rendering is not directly supported anymore by OpenGL 4. The best way I found to visualize them (with flat shading) is the following (for which most of the pieces are in libigl, but there isn't a nice wrapper yet):

1. Triangulate the polygonal mesh (polygon_mesh_to_tringle_mesh.h)
2. For every polygon, fit a plane and and get the normal from the plane (fit_plane.h)
3. Render the triangles, and assign to each one the normal of the corresponding polygon, and use per-face rendering
4. (optional) Add as a line overlay the set of all edges of the original polygonal mesh

It is in my todo list to add a wrapper for this in the viewer, but it will take a while before I get to it.

If you need to do smooth shading on a polygonal mesh you are on your own and you have to write a custom shader for that.

**Comment by chrisidefix** [comment]
Great, that generally works for me. It would be [b]nice to have[/b] build in support for mixed triangle/quad element models (I use them frequently), but I guess that is not going to be happen.

@alecjacobson: I did notice the `writeOBJ.cpp` code also happily writes out (pure) quad models - not sure if this is something you want to add to the documentation. There also is no `writeOBJPoly` which I might add and push, if this is something of interest for you, too.
