### ISSUE TITLE
Undefined reference to nanogui functions

### ISSUE THREAD

**Issue by IasonManolas** [libigl/libigl#691]
When I am building the [example-project](https://github.com/libigl/libigl-example-project)
 and turn nanogui on I get linker errors related to the nanogui functions a part of which is shown below. I also noticed that static versions of libglew and nanogui are generated after compilation although static version of libigl is off. The project runs smoothly on other machines so I am pretty sure that I messed up somewhere along the way. Any suggestions what might be wrong?
 
CMakeFiles/example_bin.dir/main.cpp.o: In function `nanogui::FormHelper::addWindow(Eigen::Matrix<int, 2, 1, 0, 2, 1> const&, std::__cxx11::basic_strin
g<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/iason/Documents/libigl-example-project/main.cpp:(.text._ZN7nanogui10FormHelper9addWindowERKN5Eigen6MatrixIiLi2ELi1ELi0ELi2ELi1EEERKNSt7__cxx1112
basic_stringIcSt11char_traitsIcESaIcEEE[_ZN7nanogui10FormHelper9addWindowERKN5Eigen6MatrixIiLi2ELi1ELi0ELi2ELi1EEERKNSt7__cxx1112basic_stringIcSt11cha
r_traitsIcESaIcEEE]+0x35): undefined reference to `nanogui::Window::Window(nanogui::Widget*, std::__cxx11::basic_string<char, std::char_traits<char>, 
std::allocator<char> > const&)'
/home/iason/Documents/libigl-example-project/main.cpp:(.text._ZN7nanogui10FormHelper9addWindowERKN5Eigen6MatrixIiLi2ELi1ELi0ELi2ELi1EEERKNSt7__cxx1112
basic_stringIcSt11char_traitsIcESaIcEEE[_ZN7nanogui10FormHelper9addWindowERKN5Eigen6MatrixIiLi2ELi1ELi0ELi2ELi1EEERKNSt7__cxx1112basic_stringIcSt11cha
r_traitsIcESaIcEEE]+0xc2): undefined reference to `nanogui::AdvancedGridLayout::AdvancedGridLayout(std::vector<int, std::allocator<int> > const&, std:
:vector<int, std::allocator<int> > const&, int)'
CMakeFiles/example_bin.dir/main.cpp.o: In function `nanogui::FormHelper::addGroup(std::__cxx11::basic_string<char, std::char_traits<char>, std::alloca
tor<char> > const&)':
/home/iason/Documents/libigl-example-project/main.cpp:(.text._ZN7nanogui10FormHelper8addGroupERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_
ZN7nanogui10FormHelper8addGroupERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x3a): undefined reference to `nanogui::Label::Label(nanogui::
Widget*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<cha
r>, std::allocator<char> > const&, int)'
CMakeFiles/example_bin.dir/main.cpp.o: In function `nanogui::FormHelper::addButton(std::__cxx11::basic_string<char, std::char_traits<char>, std::alloc
ator<char> > const&, std::function<void ()> const&)':
/home/iason/Documents/libigl-example-project/main.cpp:(.text._ZN7nanogui10FormHelper9addButtonERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEER
KSt8functionIFvvEE[_ZN7nanogui10FormHelper9addButtonERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt8functionIFvvEE]+0x38): undefined refer
ence to `nanogui::Button::Button(nanogui::Widget*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
CMakeFiles/example_bin.dir/main.cpp.o: In function `nanogui::detail::FormWidget<bool, std::integral_constant<bool, true> >* nanogui::FormHelper::addVa
riable<bool>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (bool const&)> const&, std::fu
nction<bool ()> const&, bool)':
/home/iason/Documents/libigl-example-project/main.cpp:(.text._ZN7nanogui10FormHelper11addVariableIbEEPNS_6detail10FormWidgetIT_St17integral_constantIb
Lb1EEEERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt8functionIFvRKS4_EERKSH_IFS4_vEEb[_ZN7nanogui10FormHelper11addVariableIbEEPNS_6detail
10FormWidgetIT_St17integral_constantIbLb1EEEERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt8functionIFvRKS4_EERKSH_IFS4_vEEb]+0x4b): undef
ined reference to `nanogui::Label::Label(nanogui::Widget*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std
::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'

**Comment by jdumas** [comment]
Did you clean your CMakeCache? Are you trying in header-only mode? Did you properly initialize the submodule (recursively)?

**Comment by IasonManolas** [comment]
Thanks for your quick reply, I did the first. I cloned libigl using -recursive. Is that what you mean with properly? How do I try in header only mode?

**Comment by jdumas** [comment]
Header-only corresponds to the CMake option `LIBIGL_USE_STATIC_LIBRARY=ON`. Make sure the correct folder is used by the example project for libigl (add a `message(${LIBIGL_INCLUDE_DIR})` [here](https://github.com/libigl/libigl-example-project/blob/master/cmake/FindLIBIGL.cmake#L34)), then delete your `build/` folder and try to recompile the whole thing (with `LIBIGL_WITH_NANOGUI=ON`).

**Comment by IasonManolas** [comment]
I tried those things but I still get linker errors related to nanogui..

**Comment by jdumas** [comment]
What system/compiler are you using? When I just tried to download and compile the libigl-example-project with NanoGUI it worked on my machine. Sorry I don't have a crystal ball =). You said yourself that it is working on other machines, what is the difference between those?

**Comment by jdumas** [comment]
Closing as NanoGui has been replaced by ImGui.
