### ISSUE TITLE
Don't mix camera motion and model matrix in the viewer

### ISSUE THREAD

**Issue by jdumas** [libigl/libigl#692]
Hi there,

I've been playing around a bit with the multi-mesh viewer and the 3D manipulation gizmo from [ImGuizmo](https://github.com/CedricGuillemet/ImGuizmo). It's very much WIP for now, but I think it already looks pretty good:

![out](https://user-images.githubusercontent.com/578702/36080522-69eabc78-0f5f-11e8-8f85-d0ce81e66c25.gif)

While setting this up, I've been bugged by the fact that the libigl viewer, when rotating the camera, is *updating the model matrix* to reflect the change of the scene viewpoint. This is wrong and it makes it difficult for me to implement this slicing properly on scenes with different sizes.

I know that the viewer is not a modeling tool, but I think this inconsistency could be fixed pretty easily, and it just makes everything very confusing. So basically, the correct approach to implement should be:

- Use the `model` matrix to rescale/translate the scene to the unit bbox (no rotation).
- When zooming/panning/rotating the camera, apply those transformations to the `view` matrix.
- Also remove the `view * light_position_world` in the shader, as the light position should be given directly in camera space.

Those are all pretty small changes, but I just can't figure how to zoom properly with the perspective camera in the current viewer.

Anyway, this would enable me to use the gizmo shown above on scenes with different mesh sizes, so I think it'd be great to have (the current code is in the [slicing](https://github.com/jdumas/libigl-example-project/tree/slicing) branch on my fork of the `libigl-example-project`).

**Comment by alecjacobson** [comment]
This seems to be a duplicate in many ways with https://github.com/libigl/libigl/issues/617 .

We should have a meaningful camera matrix, but no per model matrices. We've exposed the shaders so any more complex application built on top of the viewer can add this feature individual. But the basic viewer needs to be, well, basic.

**Comment by jdumas** [comment]
I suggest to keep the model matrix to set the scale/translation of the whole scene though. We don't need to have one model matrix per model i agree, but it's be nice to be able to assume the camera is always visualizing and rotating around a scene that fits in a unit box centered around its centroid. And rescaling each mesh manually to fit into the unit box would be quite cumbersome.

**Comment by alecjacobson** [comment]
I see no reason to assume the camera is looking at a unit box...

**Comment by jdumas** [comment]
I just gave you an example with the rotation gizmo in my first post. To set the size of the widget to be scene-agnostic, I need to center it and rescale so that it covers the whole scene. It would be easier to do if I could assume the camera is looking at a unit box, otherwise I would need to extract the scaling/translation part from the `view` matrix (I guess these are `model_zoom` and `model_translation` in the `ViewerCore`). I mean I guess this is possible to do, it's just that right now I found the code to be confusing on this level. At the very least you should remove the `model` matrix and only keep the `view` matrix in the `ViewerCore` class.

**Comment by alecjacobson** [comment]
Yes. I think just the view is needed (see original issue)

**Comment by jdumas** [comment]
Sure. I'll try to sort shit out things out manually to set the scale then.
