### ISSUE TITLE
Cannot open include file: 'gmpxx.h': No such file or directory - Static Library Build (Win 10)

### ISSUE THREAD

**Issue by oracle3001** [libigl/libigl#693]
When attempting to build LibIGL as a static library, a get a significant number of errors relating to the igl_cgal project, complaining about not being able to find gmpxx.h in my CGAL installation directory.

I believe the issue is that LibIGL is making the presumption that gmpxx.h is included with all CGAL builds. However, for the windows installer gmpxx.h isn't included.

[http://cgal-discuss.949826.n4.nabble.com/Can-t-locate-gmpxx-h-included-in-CGAL-gmpxx-h-td4655254.html](url)

I have previously (in the past 3 months) built the CGAL component of LibIGL successfully with the same installation of CGAL, so I am presuming some much recent update to LibIGL has caused the lack of gmpxx.h to become an issue.

**Comment by jdumas** [comment]
Looks like [this commit](https://github.com/libigl/libigl/commit/1950ee9c09b3213ba78cc8d6f052937b1989ebd3) introduced the `#include <gmpxx.h>`. Can you try to comment those parts and see if it solves your issue?

**Comment by oracle3001** [comment]
This just leads to lots of compiler errors related to mpq_class being undeclared.

**Comment by jdumas** [comment]
Did you also comment the 3 functions `assign_scalar` that use `mpq_class`? Apart from those 3, I don't see any mention of `mpq_class` anywhere, so it should compile (it does on my machine).

**Comment by oracle3001** [comment]
It is successfully building for me now, albeit with 

warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library

Thank you for your help.

**Comment by jdumas** [comment]
Well, that's because there are no explicit template instantiations in the cpp file, so this warning is normal at this point.

**Comment by oqilipo** [comment]
I still have to comment out the #ifndef WIN32 statements in assign_scalar.cpp and assign_scalar.h to complile selfintersect.cpp from gptoolbox on a windows machine:
```
arch = '64'; % Computer architecture
msvc = '14'; % Version of Visual Studio

boost_version='1_67';
path_to_boost=['C:\dev\boost_' boost_version '_0'];

cgal_version='4.12';
path_to_cgal=['C:\dev\CGAL-' cgal_version];

eigen_version='5a0156e40feb';
path_to_eigen=['C:\dev\eigen-eigen-' eigen_version];

path_to_libigl='C:\dev\libigl';

path_to_gmp=['C:\dev\CGAL-' cgal_version '\auxiliary\gmp'];

%%

MEXOPTS={'-v','-largeArrayDims','-DMEX'};

BOOST_INC=['-I' path_to_boost];
BOOST_LIB={['-L' path_to_boost '\lib' arch '-msvc-' msvc '.0'], ...
    ['-lboost_thread-vc' msvc '0-mt-x' arch '-' boost_version '.lib'], ...
    ['-lboost_system-vc' msvc '0-mt-x' arch '-' boost_version '.lib']};

CGAL_INC={['-I' path_to_cgal '\build\include'], ...
    ['-I' path_to_cgal '\include\']};
CGAL_LIB={['-L' path_to_cgal '\build\lib'],...
    ['-lCGAL-vc' msvc '0-mt-' cgal_version '.lib'],...
    ['-lCGAL_Core-vc' msvc '0-mt-' cgal_version '.lib']};

CGAL_FLAGS='CXXFLAGS=\$CXXFLAGS -frounding-math';

EIGEN_INC= ['-I' path_to_eigen];

GMP_INC=['-I' path_to_gmp '\include'];
GMP_LIB={['-L' path_to_gmp '\lib'], '-llibgmp-10.lib', '-llibmpfr-4.lib'};

LIBIGL_INC=['-I' path_to_libigl '\include'];
LIBIGL_FLAGS='-DIGL_SKIP';
LIBIGL_LIB={'-DIGL_SKIP'};
LIBIGL_LIBMATLAB='-DIGL_SKIP';
LIBIGL_LIBCGAL='-DIGL_SKIP';
LIBIGL_LIBCORK='-DIGL_NO_CORK';
LIBIGL_BASE={LIBIGL_INC, LIBIGL_FLAGS,LIBIGL_LIB{:}, LIBIGL_LIBMATLAB};

mex( ...
  MEXOPTS{:}, ...
  LIBIGL_BASE{:},EIGEN_INC, ...
  BOOST_INC, BOOST_LIB{:}, ...
  CGAL_INC{:},CGAL_LIB{:},CGAL_FLAGS, LIBIGL_LIBCGAL, ...
  GMP_INC, GMP_LIB{:},...
  'external\gptoolbox\mex\selfintersect.cpp');
```

Otherwise I get the error:
```
Error using mex
selfintersect.cpp
C:\dev\CGAL-4.12\include\CGAL/gmpxx.h(45): fatal error C1083: Cannot open include file: 'gmpxx.h': No such file or directory
```
Although the file exists "gmpxx.h" in the directory
```
C:\dev\CGAL-4.12\include\CGAL\
```
?

**Comment by rin-23** [comment]
I had the same issue on Ubuntu even after compiling GMP from source. Running apt install libgmp-dev seemed to solve that error for me.
