### ISSUE TITLE
how to use libigl to calculate the volume of a mesh

### ISSUE THREAD

**Issue by jiangwei221** [libigl/libigl#694]
HI, 
I'm new to computational geometry, and it maybe a silly question.
I realized that there is a "volume.cpp" contains the igl::volume function.
But I cannot figure out how to use it.

```IGL_INLINE void igl::volume(
  const Eigen::MatrixBase<DerivedV>& V,
  const Eigen::MatrixBase<DerivedT>& T,
  Eigen::PlainObjectBase<Derivedvol>& vol)
{
  using namespace Eigen;
  const int m = T.rows();
  vol.resize(m,1);
  for(int t = 0;t<m;t++)
  {
    typedef Eigen::Matrix<typename DerivedV::Scalar,1,3> RowVector3S;
    const RowVector3S & a = V.row(T(t,0));
    const RowVector3S & b = V.row(T(t,1));
    const RowVector3S & c = V.row(T(t,2));
    const RowVector3S & d = V.row(T(t,3));
    vol(t) = -(a-d).dot((b-d).cross(c-d))/6.;
  }
}
```
[https://github.com/libigl/libigl/blob/master/include/igl/volume.cpp](url)

What is the x-by-4 T matrix? If the T matrix is the index list, why it has 4 columns?
Are a, b, c, d the 4 vertices of a tetrahedron?
Is this algorithm inspired by "EFFICIENT FEATURE EXTRACTION FOR 2D/3D OBJECTS
IN MESH REPRESENTATION" paper?

Thank you!

**Comment by jdumas** [comment]
Hi,

It's written in the documentation in [the header file](https://github.com/libigl/libigl/blob/master/include/igl/volume.h):
```
  // VOLUME Compute volume for all tets of a given tet mesh
  // (V,T)
  //
  // vol = volume(V,T)
  //
  // Inputs:
  //   V  #V by dim list of vertex positions
  //   T  #V by 4 list of tet indices
  // Outputs:
  //   vol  #T list of dihedral angles (in radians)
  //
```

I don't know what else you need to know. If you want the total volume of the mesh, you need to do `vol.array().abs().sum()`.

**Comment by jiangwei221** [comment]
Hi,

Thanks for the quick reply!

I see, it calculates the volume of every tetrahedron of a tet mesh.

I was confused because I tried to apply it to a triangle mesh.

**Comment by jdumas** [comment]
I don't think so, but it should be pretty easy to hack it up, by building a tet-mesh with a virtual point at the origin, and summing up the signed volumes:

```
Eigen::MatrixXd V2(V.rows() + 1, V.cols());
V2.topRows(V.rows()) = V;
V2.bottomRows(1).setZero();
Eigen::MatrixXi T(F.rows(), 4);
T.leftCols(3) = F;
T.rightCols(1).setConstant(V.rows());
Eigen::VectorXd vol;
igl::volume(V2, T, vol);
return std::abs(vol.sum());
```
