### ISSUE TITLE
compiling static library in windows

### ISSUE THREAD

**Issue by irenji** [libigl/libigl#702]
Dear All.

I,m trying compile static library in windows , cmake in optional folder make this error :
```
CMake Error at CMakeLists.txt:52 (add_subdirectory):
  The source directory

    E:/libigl-master/shared/cmake

  does not contain a CMakeLists.txt file.
```

is there windows user can compile it to static library ?

Thank you

**Comment by jdumas** [comment]
This was the old way of using libigl in a CMake project. Please check out the new approach in the [libigl-example-project](https://github.com/libigl/libigl-example-project).

**Comment by oracle3001** [comment]
The example project still has a CMakeLists.txt file.

**Comment by jdumas** [comment]
I'm sorry but I fail to see the difficulty here. The libigl-example-project I pointed out has a `CMakeLists.txt`, and if you clone and download libigl as instructed in this repository, you will be able to compile it.

**Comment by oracle3001** [comment]
Sorry, my apologizes, I though the example project was simply showing how to build a very simple viewer example using libigl, and nothing to do with creating static libraries. 

Where as I now see that it also create the static libraries (as required / set).

**Comment by jdumas** [comment]
We do not provide a way to build and install libigl in the system, but encourage users to build it as part of their project. Maybe this will evolve over time, but right now that's how it is. You can also use the core functions as header-only files without any specific configuration beside Eigen.

**Comment by irenji** [comment]
@jdumas Yes it,s easy and very simple. But building libigl as a part of project make the compile time very long.

**Comment by jdumas** [comment]
Yes that's a current limitation ... But unless you spin a new project everyday you can build libigl once as a static library and then use it without the extra compilation time =)

**Comment by alecjacobson** [comment]
@jdumas this is a failure of the new cmake setup and we should fix it. It seems that the `optional/CMakeLists.txt` for building all static libraries has been forgotten. It should not be required for a project to use CMake in order to use libigl.

**Comment by jdumas** [comment]
I'm sorry but can you elaborate? Was the point of the `optional/CMakeLists.txt` to compile a single `libigl.a` that people can use however later on? It has been forgotten during the CMake refactoring I agree, but I think it could use some work on its own: why does the README mentions a `libiglsvd3x3` or `bbw` and `boolean` packages, when I see no such folder in `include/igl`? And why OpenGL 4? I thought the viewer needs only OpenGL 3.3. And why was this file into an `optional/` folder? If this is the official way to build libigl as a static library that people can install on their system, it should be in the root of the project. If we keep it in a subfolder and do not build it on Travis, this is not gonna be maintained (which is exactly what happened here).

I'd be happy to help bring this up to speed, but some things need to be clarified first. Compiling a `libigl.a` for the core library (that depends only on Eigen) should be easy enough. But what do we do for other modules that depend on external libraries? Having a `libigl-embree.a` is not enough: you need to make sure that your own project uses the same version of embree, with the same compile definitions (`-DFOO`). For example cork is built with `-DNO_TIMER -DREDUCED -DCDT_ONLY -DTRILIBRARY -DANSI_DECLARATORS`.

Then there is the matter of the single .h/.cpp pair: I see the point for the core library (everything directly under `include/igl`), but I think again that the different modules are more complicated to deal with properly. I think there should be a separate pair `iglcgal.h`/`iglcgal.cpp` for each module that depend on an external library.

I mean this can be done, but one would need to be careful about what is going on, if we want to have something that works for all the different modules. We can continue this discussion up in #711 if you want.
