### ISSUE TITLE
Error building tutorial on Windows 10

### ISSUE THREAD

**Issue by majia67** [libigl/libigl#704]
When I try to build the latest tutorial on my Win10 laptop, I [got this error message](https://gist.github.com/majia67/3c4c7a099aadb4435f52bebe81cda8e5). It looks like an issue with the external module called Eigen.

Below is my testing environment (all are the latest version):

OS: Windows 10
IDE: Visual Studio 2017

**Comment by danielepanozzo** [comment]
This is strange, the autobuild works:
https://ci.appveyor.com/project/danielepanozzo/libigl-6hjk1/branch/master

Can you try a fresh clone? Your git client might have only pulled the new version and not updated the submodules.

**Comment by majia67** [comment]
Same error. I am not sure if this is related to the version of c++ compilers. For your reference, [see my CMake configuration log](https://gist.github.com/majia67/8659833f33f38104c999f76f0259723d). I noticed in Appveyor, the VC version is 2014.

**Comment by jdumas** [comment]
Did you select the x64 version of the MSVC compiler?

**Comment by majia67** [comment]
Thank you @jdumas! After switching to x64 version of the MSVC compiler, the tutorial can build without any problems. Thanks, @danielepanozzo for your prompt reply!
