### ISSUE TITLE
boolean operation with color

### ISSUE THREAD

**Issue by irenji** [libigl/libigl#707]
I,m using Boolean operation of libigl and want to save the color of my points , i found that an extra output argument named J used to return the faces that new mesh belong to . but in my input ,vertexes has color. how can i use J to color my points.

Thank you.

**Comment by jdumas** [comment]
Well it's not well defined for the output vertices which input vertex it comes from (there could be new inserted vertices, etc.). However, if you know, for an output face, which input face it comes from, then you can project each corner on the original triangle and interpolate the colors of the input mesh vertices. You can then average the colors from incident facets at a given output vertex.

**Comment by irenji** [comment]
Thanks , for your help . Another question is : when i minuses two  mesh is there any parameter for tuning the result . for example when i minus mesh there will be some part that not accurately aligned but they are so close and must be removed but they are remain in result

**Comment by jdumas** [comment]
Well if your meshes are not aligned then you should align them properly before doing the boolean operation.

**Comment by alireza59** [comment]
Hi, after alignment still there is microscopic level of displacement between two meshes, that causes lot of noise and outliers.
is there any threshold or parameter in boolean subtraction to adjust the sensitivity and get rid of outliers? Thank you.

**Comment by jdumas** [comment]
Looking at the boolean code you can enable a `#define SMALL_CELL_REMOVAL` [here](https://github.com/libigl/libigl/blob/f50084cacb0f3ec76ef270d0a1bc3e9931ac2719/include/igl/copyleft/cgal/mesh_boolean.cpp#L303). Maybe @qnzhou can comment on what this does?

**Comment by qnzhou** [comment]
I don't think `SMALL_CELL_REMOVAL` would help here.  It only removes small cells that are completely embedded within other cells.  It can be used for filtering out small bubbles in a liquid mesh, for example.

To remove microscopic misalignments, maybe quantizing the input meshes would help.  E.g. round vertices to `k` decimal digits then run `mesh_boolean`.  You can adjust `k` to get the desired results.
