### ISSUE TITLE
Better igl::decimate() Documentation

### ISSUE THREAD

**Issue by KermMartian** [libigl/libigl#712]
It appears that the [documentation for igl::decimate()](http://libigl.github.io/libigl/tutorial/tutorial.html#meshdecimation) is incomplete and/or incorrect. On the incorrect side, the current documentation mentions `igl::decimate(V,F,1000,U,G);`, while it appears that the simplest interface currently available from reading libigl/decimate.h is `decimate(V, F, max_m, U, G, J, I)`, i.e., the version that computes birth facets. On the incomplete side, I'm at a particular loss to understand the arguments to cost-and-placement and stopping condition callbacks, and what their arguments mean. For example, I'm interested in a pair of callbacks that use an approximation of the second derivative of the surface at each of the current edge's endpoint for the cost, and some bound on the most costly edge's second derivative as a stopping condition (ie, stop when no more shallow concavities or convexities can be simplified). I suspect I can muddle through decimate.cpp to figure it out, but it looks like this is an area particularly ripe for additional documentation.

Specific to my application, I'd also love to see more about using the methods in `connect_boundary_to_infinity.h` to allow me to simplify a non-manifold mesh patch (I suppose I can also just return an infinite cost for boundary edges?), but I understand if that's too specific to me.

**Comment by jiangzhongshi** [comment]
**Tutorial** The arguments do seem wrong, you should be able to use it with empty `Eigen::VectorXi J` initialized.

**lambda arguments** I had the same problem as well, I looked through the implementation of `qslim.cpp`. Hope it helps.

**connect to inf** I don't understand the question, as far as I know, `connect_boundary_to_infinity.h` is simply creating an artificially closed mesh,  what method do you intend to use for simplification?

**Comment by jiangzhongshi** [comment]
This looks great. Maybe you can open a PR or we can do it later.
