### ISSUE TITLE
Tutorial could explain better how to compile for Windows and VS 2015

### ISSUE THREAD

**Issue by ArturoJafet** [libigl/libigl#713]
The past couple days I have been trying to compile libigl to start working with it but I found the tutorial was missing some explanations that could help those who work with Windows 10 and Visual Studio 2015

Line to compile the tutorials should be:
`cmake -DCMAKE_BUILD_TYPE=Release ../ -DCMAKE_GENERATOR_PLATFORM=x64`

When you open any of the Visual Studio solutions you need to change the startup project for the one you want to run.
Right Click on the project of the tutorial -> select Set as Startup Project

Hope this helps other users and thank you

**Comment by jdumas** [comment]
On Windows people normally use CMake GUI to generate the CMake project. A Window user that knows how to use a terminal usually ends up on Linux/macOS pretty quick.

Joke aside, the [tutorial](http://libigl.github.io/libigl/tutorial/tutorial.html#libigldesignprinciples) already states explicitly:
> Note for windows users: libigl only supports the Microsoft Visual Studio 2015 compiler in 64bit mode. It will not work with a 32bit build and it will not work with older versions of visual studio.

And setting up the startup project to run the tutorial you want is pretty much basic Visual Studio behavior. You can still run it from the command line though. But feel free to create a PR if you feel this is missing from the documentation.

**Comment by ArturoJafet** [comment]
Thanks for the quick response, I would so much prefer working on Linux/macOS but I work with VR which is still pretty much on Windows, and it never occurred me to use CMake GUI.

I won't create a PR since if anyone has the question they can see the answer here.

**Comment by jdumas** [comment]
As a side-note, I think you can also configure the default compiler for CMake to be the 64bit version of visual studio, so that you do not need to specify the platform on the command-line if this is how you want to generate your project. Also note that on Windows, it is useless to specify `-DCMAKE_BUILD_TYPE`, as this is an option you will have to select within the Visual Studio project anyway.
