### ISSUE TITLE
Making pyigl.eigen.* pickle-able

### ISSUE THREAD

**Issue by qianyizh** [libigl/libigl#715]
When use ``pickle`` to dump a class with ``pyigl.eigen.*`` as member variables, an error returns:
```
import pickle
with open('file.pic', 'wb') as f:
    pickle.dump(temp, f)     # temp has a member variable of pyigl.eigen.MatrixXd

TypeError: can't pickle pyigl.eigen.MatrixXd objects
```

Making these objects pickle-able seems to be doable with pybind11.
http://pybind11.readthedocs.io/en/stable/advanced/classes.html#pickling-support

**Comment by teseoch** [comment]
obsolete we now use numpy wich can be pickled
