### ISSUE TITLE
Improving libigl's documentation.

### ISSUE THREAD

**Issue by jdumas** [libigl/libigl#717]
Hi,

I'd like to open a thread to discuss possible improvements to libigl's documentation. Right now I have the feeling that there are a bunch of .md files spread out here and there in the repository (style-guideline, before-submitting-pull-request, python/README, optional/README, etc.). I feel that what's missing is really a left panel with table of content + text search to navigate all this more easily.

There are a couple of static website generators that are great for write documentation, and they could be used to generate such a panel automatically. On the top of my head the ones I can think of are:

- [Gitbook](https://toolchain.gitbook.com/) (written in javascript).
- [mkdocs](http://www.mkdocs.org) (written in python).
- Hugo with a [documentation theme](https://themes.gohugo.io/tags/documentation/) (written in Go).

All 3 are open-source, static website generators. mkdocs and hugo are probably easier to install on the system, being written in python/Go. And while I use Hugo for my homepage, it seems that text search works better on gitbook/mkdocs. Mkdocs also has a bunch of [themes](https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes) and can be customized with CSS.

If you're ok with it, I can try to set up a proper website with mkdocs, and maybe also reorganize the existing files a little bit (maybe move them into a `doc/` subfolder).

**Comment by alecjacobson** [comment]
Creating a better website is a nice idea.

(we will not use automatically generated documentation though. This has been discussed a number of times.)

**Comment by jdumas** [comment]
> (we will not use automatically generated documentation though. This has been discussed a number of times.)

What's wrong with that? Are you talking about hosting, or generating the website? A tool such as mkdocs is basically a sophisticated script that translate markdown into html. Not very different from multimarkdown that is currently used to generate the html. We can still use github pages to host the generated html (if this is what you were worried about).

**Comment by alecjacobson** [comment]
We're not changing the way that the header files are documented.

**Comment by jdumas** [comment]
Oh ok. I wasn't talking about that, just the doc/website around libigl.

It would be nice to be able to generate a doxygen documentation out of the headers though, but that's require changing the formatting of all the header files and it's a lot of work, so I wasn't even suggesting that.

**Comment by alecjacobson** [comment]
ok, great. Glad we're on the same page.

**Comment by jdumas** [comment]
I've started a quick attempt at putting a website together. The result is available at [this address](http://www.jdumas.org/libigl/) for now. This is all very much work in progress, and images are broken, but it ought to give an overall idea. See e.g. [this page](http://www.jdumas.org/libigl/tutorial/chapter-4/) from the tutorial.

Changes are committed on my fork in the [docs branch](https://github.com/jdumas/libigl/tree/docs), and resulting website is built and deployed via github pages on the [gh-pages](https://github.com/jdumas/libigl/tree/gh-pages) branch.

I've split the `tutorial.md` file into one file per chapter, so that it becomes easier to extend. I am still trying to figure out how to organize everything properly though.

One thing that I like with this setup however, is that html files are not mixed with the .md (the html files are built and committed on the `gh-pages` directly). This helps reducing the clutter a bit.

**Comment by danielepanozzo** [comment]
This looks nice! I looked at the branch and it seems that the only added overhead over what we have now is the addition of the file https://github.com/jdumas/libigl/blob/docs/mkdocs.yml (and splitting the tutorial in multiple files, which is a good idea too since it is growing quickly).
If this is the case then I am in favor of adding it, it is really nice and simple to maintain.

**Comment by alecjacobson** [comment]
Some of the tutorial is not parsing correctly: the labels are showing up in the headers (see image)
<img width="452" alt="screen shot 2018-03-18 at 8 30 33 pm" src="https://user-images.githubusercontent.com/2241689/37573174-4929f178-2aeb-11e8-968b-df9e24b2e284.png">

**Comment by jdumas** [comment]
Yes I know, it's a work in progress. I just wanted your overall opinion before I spend the time to clean up the markdown files. The flavor of markdown are a bit different, e.g. labels and citations need to be fixed. Citations as footnotes need to be changed from `[#foo]` to `[^foo]`, and explicit labels for sections are not needed anymore, as anchor links are automatically generated (`### Foo Bar` generates an anchor link that can be referenced as `[link][#foo-bar]`, this helps reduce the clutter in the markdown).

**Comment by alecjacobson** [comment]
My high-level opinion is that this is low priority. And things like changing the markdown flavor for the tutorial sounds like a headache. 

I would much rather see the unit tests taken seriously.

(BTW, Anchors are also generated automatically in the multimarkdown version, but we get the option to chose what they are. This makes it much easier to change the order without changing numbers all over the place.)

**Comment by jdumas** [comment]
It's not like this is a big change. If you want a website that can be easily organized into different pages, then we need to use a different tool to build it from the markdown. And it's much easier to fix what little deviation there is in the mardown (probably a couple of hours), than building the website using multimarkdown (which is great, but for single pages).

Improving the unit tests would also be nice, but that's not the topic here. I'd rather help consolidate the CMake build and the documentation first.

> (BTW, Anchors are also generated automatically in the multimarkdown version, but we get the option to chose what they are. This makes it much easier to change the order without changing numbers all over the place.)

The automatic anchors don't have numbers in them. I don't see how this prevents you from reordering the sections as you wish.

**Comment by alecjacobson** [comment]
Maybe I'm misunderstanding the anchors. But if I write:

     ### Chapter 5: Parameterization

won't the anchor be [chapter5:parameterization] ? So if you have a bunch of links elsewhere in the tutorial you'll have to change all the 5's to 4's if you decide to reorder the chapters.

**Comment by jdumas** [comment]
Well yes, but the current [tutorial file](https://raw.githubusercontent.com/libigl/libigl/master/tutorial/tutorial.md) is already using `[chapter5:parameterization]` as anchor names ... So this wouldn't change anything to the current situation. I don't think renaming chapters happen so often that you need to worry about that. Plus, if we split each chapter into files, the links will need to be changed anyway, since it won't be an anchor anymore.

**Comment by alecjacobson** [comment]
It would also happen for all subchapters. 

Not clear that splitting is a good idea. This especially seems like a drawback.

**Comment by danielepanozzo** [comment]
Do we really have to split the tutorial.md? Couldn't we keep it as a single file and still use mkdocs? 
The python readme.md should also be incorporated in this (and updated, it has not been changed in a while).

**Comment by jdumas** [comment]
I suppose we could, but what are the advantages?

**Comment by danielepanozzo** [comment]
Just minimizing the amount of refactoring needed.

**Comment by jdumas** [comment]
I've updated the [website](http://www.jdumas.org/libigl/) a bit.
- Added the matlab-libigl cheatsheet that was missing
- Added some extra pages: libigl-example-project, unit-tests, file formats, etc.
- Fixed section titles in the tutorial
- Fixed caption text and math
- Added footnote references as before
- Removed default favicon (but if we have a fancy one I can add it)

It's almost ready to be merged. I just need to figure out how to deal with links to the code, since the `.md` are now in a separate `docs/` folder (and we want the url to point to `https://github.com/libigl/libigl/tree/master/tutorial/<...>`).

Another annoying thing is a limitation of mkdocs that does not allow pages from outside the `docs/` folder to be used for the website. That means right now the main `README.md` is duplicated. We could try to find a way around this, or use a shorter README for either github or the website.

**Comment by danielepanozzo** [comment]
Nice! Two comments:
- it is currently not showing the python readme
- the static compilation page is out of date, shall we hide it until someone sends a PR to support it with the new build system?

**Comment by jdumas** [comment]
Sure. I've added the python readme. I'll keep the page about the static library for now, but we can simply comment it when we merge if you want.

**Comment by jdumas** [comment]
I've updated the release history on the website to briefly mention the latest major changes we made to libigl (CMake stuff, viewer, imgui, etc.). Let me know if I should create the PR to merge this into the main branch. We only need to decide what to do for the main README I think.

The instructions to build the website on my branch is the following:
1. Install mkdocs and the material theme `pip install -U --user mkdocs mkdocs-material`
2. Preview the website locally `python -m mkdocs serve` (in the root folder of the libigl project)
3. Build the website to generate the html locally: `python -m mkdocs build` (optional)
4. Deploy the website directly to github: `python -m mkdocs gh-deploy` (will overwrite the `gh-pages` branch of the remote repository)

Be careful to not have any `<>` character in your email in your `.gitconfig`, otherwise the `gh-deploy` script will fail.

**Comment by danielepanozzo** [comment]
Looks good to me, I vote for merging this asap.

**Comment by jdumas** [comment]
I've created the PR. There are a lot of file changes because images for the tutorial have been moved into the `docs/` folder, and a bunch of other files have also been renamed/moves to be in the `docs/` folder.

**Comment by alecjacobson** [comment]
I mostly really like it. Great work!

I won't have time for a thorough review until after this week (many conference deadlines).

One thing that gave me hesitation was having the tutorial split into chapters. The old tutorial was one giant page. The bad thing about that was that it was slow to load all of the math, but the good thing was that it was really easy to search (CMD+F on the whole page). Our first few chapters are coherent but it gets to be a little messy near the end. Is it easy to have the nice sidebar that you added but still have the entire single-page tutorial?

**Comment by danielepanozzo** [comment]
There is now a builtin search box at the top, that has the same function of CMD-F, but works on all pages and not only in the tutorial. I think the division in chapters is a good idea to keep things more organized.

The current hosting at github.io is broken (not sure why pages are not being updated), an it still contains the old nanogui tutorial, which is very confusing. I have in my todo list to fix it but I will not get to it till the end of the week too, and it will be pointless anyway if we switch documentation.

I think we should merge now and eventually change it later on if there are issues.

**Comment by alecjacobson** [comment]
a search box just isn't the same thing. I'm not sure the organization is
actually better this way (see discussion above).

what's broken about the current page? Seems to work for me.

I'm not in a hurry to do this. It's a nice change but not critical.

**Comment by jdumas** [comment]
The current markdown for the tutorial page is not building with multimarkdown, so the html version doesn't match the current .md file (the html still mentions nanogui, whereas the .md has been updated to mention imgui).

I find the search box to work quite well tbh. What is it that you don't llike about the search box vs the Ctrl+F situation? It seems like a good compromise to keep math loading fast and provide a way to search the website/tutorial.

If I put the tutorials on a single page, the table of content on the right will become very long (even if I keeps the chapters on the left, the ToC on the right will be built on the content of the whole page).

**Comment by danielepanozzo** [comment]
The current documentation is still broken. @alecjacobson Can we merge this PR? Otherwise I will try to fix the old documentation but I see no reason for supporting the old one given that this is in my opinion strictly better.

**Comment by alecjacobson** [comment]
Why was the original documentation broken in the first place? I'm guessing because we plowed ahead with some major changes without checking it thoroughly. I'm reluctant to do that again here.

A good compromise would be to dial down the structural and organizational changes in this PR so that the transition is smoother. Rather than changing a bunch of things and hoping we go back and clean it up later.

**Comment by jdumas** [comment]
Looking at the commit log, I believe the original documentation got broken when the ShapeUp tutorial was merged. The PR (#637) was open since November 2017. I don't know exactly the syntax error that led to that, since I never tried to compile the original documentation myself.

Anyway, there's gonna be a lot of file changes with this next PR, since I has to move a lot of files (mostly the images from the `tutorial` folder). This is because `mkdocs` by design doesn't supports files outside the `docs/` folder. I can tune it down by not splitting the tutorial for the first merge, but I find it a bit artificial. Anything less than that will leave a broken/partial doc website, so I am not sure that it is desirable. You can already see the new website in effect on my domain (www.jdumas.org/libigl), and test it locally. I have also crawled it with [LinkChecker](https://wummel.github.io/linkchecker/) and there is no dead-link left.

If you want more time to double-check it that's fine, but I don't think it makes sense to break down the PR into smaller chunks at least for this one.

**Comment by alecjacobson** [comment]
Thanks, Jeremie. I meant break down the changes to the docs, not necessarily the PR itself.

The changes I'm immediately OK with are: 
 - moving images and md/html files to `docs/`
 - combining the Home, Tutorial, Compilation, Contributing, etc. into a unified site (this is _great_)
 - fixing the broken tutorial

If we're hurrying to switch to this site, I'd like to postpone:
 - separating the tutorial into many files and many pages
 - (sub issue) distributing the references among the many tutorial mds

So if it's easy to revert the tutorial to a single page document, I'd be more at ease with this change. Then we can discuss best ways to deal with sidebars for chapters, consistent references and organization after.

**Comment by jdumas** [comment]
It's trivial to merge the tutorial again in a single file. There will be the downside we discussed (slow loading maths and either gigantic side-bar or non-informative side-bar), but we can easily work it out in a separate PR.

I'm still attending Eurographics tomorrow but I can create the PR with the single tutorial page by Sunday.

**Comment by alecjacobson** [comment]
That'd be great. Thanks for your hard work on this. It will be very satisfying to announce the new site and I'll feel at ease discussion these other issues without a broken documentation looming over us.

**Comment by jdumas** [comment]
@alecjacobson idk if you got the notification, but the PR is ready to be merged (waiting for your approval).

**Comment by jdumas** [comment]
Can you try with `python3`? Are you also running it from the root folder of the project? I've put the instructions to build the doc on [this webpage](https://www.jdumas.org/libigl/building-the-website/) (but I can probably name the source file `docs/README.md` so it can be visible both on github and the website).

**Comment by zhfsu** [comment]
Where is the documentation of libigl? As a user, I think there should be a link somewhere on the left side of https://libigl.github.io/ which contains all the on-line documentation, but there isn't. Or, there should be a sub dir named docs in the root dir of libigl which contains all the off-line documentation, but there isn't. I searched google using key words, e.g., libigl Viewer::append_mesh documentation, but I was returned nothing useful for this method. For now, I can only use libigl functions by guesswork based on its source code. So, Where is the documentation of libigl, if there is any at all? Note that tutorial is NOT doc.
