### ISSUE TITLE
Windows issue: access violation

### ISSUE THREAD

**Issue by TheFalk** [libigl/libigl#718]
Hello, so on 64-arch I'm getting an access violation issue on line 267 in wgl_context.c:
       SwapBuffers(window->context.wgl.dc);

Exception thrown at 0x00007FFA1DF483F9 (ig9icd64.dll) in example_bin.exe: 0xC0000005: Access violation reading location 0x000000000000001C.

This was happening in my research project so I cloned and ran the example project. The following is output from the example project's cmake. The targets(igl::core, etc) are being created but the includes, sources, and libraries aren't propagating up to the topmost cmakelists. Could this be the issue? How do I resolve this?

1> Command line: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe  -G "Ninja" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\michael\CMakeBuilds\145ae8e7-591a-173b-b4da-53f6c2d7d1bd\install\x64-Debug"  -DCMAKE_CXX_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.12.25827/bin/HostX64/x64/cl.exe"  -DCMAKE_C_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.12.25827/bin/HostX64/x64/cl.exe"  -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" "C:\Users\michael\Source\Repos\libigl-example-project"
1> Working directory: C:\Users\michael\CMakeBuilds\145ae8e7-591a-173b-b4da-53f6c2d7d1bd\build\x64-Debug
1> -- Found CGAL: C:/dev/CGAL-4.11.1/build
1> -- Boost version: 1.65.1
1> -- Found the following Boost libraries:
1> --   thread
1> --   system
1> --   chrono
1> --   date_time
1> --   atomic
1> -- Could NOT find MOSEK (missing: MOSEK_LIBRARIES MOSEK_INCLUDE_DIR) 
1> -- Creating target: igl::core
1> -- Creating target: igl::opengl
1> -- Creating target: igl::opengl_glfw
1> -- Could NOT find Vulkan (missing: VULKAN_LIBRARY VULKAN_INCLUDE_DIR) 
1> -- Using Win32 for window creation
1> libigl include: C:/Users/michael/Source/Repos/libigl/include
1> libigl includes: 
1> libigl libraries: 
1> libigl extra sources: 
1> libigl extra libraries: 
1> libigl definitions: 
1> -- Configuring done
1> -- Generating done
1> -- Build files have been written to: C:/Users/michael/CMakeBuilds/145ae8e7-591a-173b-b4da-53f6c2d7d1bd/build/x64-Debug
1> Starting CMake target info extraction ...
1> CMake server connection made.
1> Extracted includes paths.
1> Extracted CMake variables.
1> Extracted source files and headers.
1> Extracted global settings.
1> Extracted code model.
1> Collating data ...
1> Target info extraction done.

**Comment by jdumas** [comment]
Can you run the tutorials?

> The targets(igl::core, etc) are being created but the includes, sources, and libraries aren't propagating up to the topmost cmakelists. Could this be the issue? How do I resolve this?

I don't understand what you mean here.

**Comment by TheFalk** [comment]
No, I got the same error on tutorial 102_DrawMesh. 

I was trying to point out the output from the CMakeLists.txt lines:

message("libigl include: ${LIBIGL_INCLUDE_DIR}")
message("libigl includes: ${LIBIGL_INCLUDE_DIRS}")
message("libigl libraries: ${LIBIGL_LIBRARIES}")
message("libigl extra sources: ${LIBIGL_EXTRA_SOURCES}")
message("libigl extra libraries: ${LIBIGL_EXTRA_LIBRARIES}")
message("libigl definitions: ${LIBIGL_DEFINITIONS}")

being:
1> libigl include: C:/Users/michael/Source/Repos/libigl/include
1> libigl includes:
1> libigl libraries:
1> libigl extra sources:
1> libigl extra libraries:
1> libigl definitions:

**Comment by jdumas** [comment]
Yes those variables are not used anymore, since we updated the CMake build system. I don't know why you are getting an error, last time I checked on my Windows machine it worked fine, but I can try again at the end of the week ...

**Comment by danielepanozzo** [comment]
Maybe you have an old version of some of the subrepos? Could you try a fresh clone with the "--recursive" option?

**Comment by TheFalk** [comment]
It is a fresh clone. After weeks of pulling my hair out I discovered that I needed to completely uninstall and reinstall my intel display driver. It works though, thanks!
