### ISSUE TITLE
igl::matlab_format() dumps no output for sparse matrices

### ISSUE THREAD

**Issue by waterrhett** [libigl/libigl#72]
I tried the following code (similar to those from the tutorial):

    Eigen::MatrixXd V, F;
    igl::readOFF("../../Libraries/libigl/tutorial/shared/2triangles.off", V, F);
    Eigen::SparseMatrix<double> L;
    igl::cotmatrix(V,F,L);
    std::cout<<igl::matlab_format(V,"V")<<std::endl;
    std::cout<<igl::matlab_format((F.array()+1).eval(),"F")<<std::endl;
    std::cout<<igl::matlab_format(L,"L")<<std::endl;

The first two dense matrices are formatted fine:
V = [
  0 0 0
  1 0 0
  1 1 1
  2 1 0
];
F = [
  1 2 3
  2 4 3
];

but L gets no output.

**Comment by waterrhett** [comment]
This was tested with Eigen 3.2.4

**Comment by alecjacobson** [comment]
This is strange. I just tried and the correct output is:

```matlab
LIJV = [
                      1                     1   -0.7071067811865476
                      2                     1    0.7071067811865475
                      3                     1 1.570092458683775e-16
                      1                     2    0.7071067811865475
                      2                     2    -1.638010440969447
                      3                     2    0.6422285251880865
                      4                     2    0.2886751345948129
                      1                     3 1.570092458683775e-16
                      2                     3    0.6422285251880865
                      3                     3   -0.9309036597828995
                      4                     3    0.2886751345948129
                      2                     4    0.2886751345948129
                      3                     4    0.2886751345948129
                      4                     4   -0.5773502691896258
];
L = sparse(LIJV(:,1),LIJV(:,2),LIJV(:,3));
```

Can you run your code in a debugger to be sure that it's not crashing before L is output?
