### ISSUE TITLE
 maximum triangle edge size for decimation 

### ISSUE THREAD

**Issue by alireza59** [libigl/libigl#722]
Hello 
Is it possible to set a maximum triangles edge size for decimation to avoid blurred color? Because our color is stored per vertex.
Thank you

**Comment by alecjacobson** [comment]
You can customize the cost function to reject collapse that create large
triangle edges (set their cost to infinity).

If you wanted to get fancy, you could also play with the placement function
to ensure that the bound is not exceeded. My guess is that this is overkill.

**Comment by alireza59** [comment]
Thank you for the quick answer, I will it.
