### ISSUE TITLE
Checking out the old version of libigl?

### ISSUE THREAD

**Issue by evouga** [libigl/libigl#724]
Hey y'all, I could use some help figuring out the correct incantation for checking out the old version of libigl. I tried

```
git clone --recursive https://github.com/libigl/libigl.git libiglold
git checkout --recurse-submodules 9a805a9764880a1c51d6ccbb5240dc6d0f8399bb

```

which gives me error

> warning: unable to rmdir 'tools/clang': Directory not empty
> warning: unable to rmdir 'external/pybind11': Directory not empty
> fatal: Not a git repository: ../../.git/modules/external/nanogui
> fatal: could not reset submodule index

I need the old version in order to compile and grade my class assignments.

**Comment by jdumas** [comment]
Hi,

Try the following in an empty folder:

```
git clone https://github.com/libigl/libigl.git
git checkout 9a805a9764880a1c51d6ccbb5240dc6d0f8399bb
git submodule upgrade --init --recursive
```

If you are in an existing repository, things can get funny with the submodules when you are switching between versions. If a problem occurs you can usually get away with `rm -rf external`, followed by a `git checkout 9a805a97` and `git submodule upgrade --init --recursive`.

**Comment by evouga** [comment]
I needed

`git submodule update --init --recursive`

rather than "upgrade", but then it worked for me. Thanks.

**Comment by jdumas** [comment]
Yeah my bad. I fixed my comment.
