### ISSUE TITLE
python/tutorial/708_Picking.py is not updated

### ISSUE THREAD

**Issue by Adamwgoh** [libigl/libigl#726]
Hi all, On python/tutorials/708_picking.py, a git clone shows that the latest master branch's 708_Picking.py is not updated to use glfw.viewer. 

Namely, line 58-61:
`viewer = igl.viewer.Viewer()`
`viewer.data.set_mesh(V, F)`
`viewer.data.set_colors(C)`

Initialization of `fid` Eigen.MatrixXi in mouse_down:
`fid = Eigen.MatrixXi([-1])`

and so forth.

**Comment by danielepanozzo** [comment]
This should be fixed, please reopen it if it is not the case!
