### ISSUE TITLE
VS 2012 recent Viewer problems

### ISSUE THREAD

**Issue by cap257zero** [libigl/libigl#73]
Encountering errors like this

Error	84	error C2064: term does not evaluate to a function taking 3 arguments	c:\program files (x86)\microsoft visual studio 11.0\vc\include\xrefwrap	431	1	libigl

when compiling a project. No errors if I do not include Viewer.h

Also, this is using code that worked (using the viewer) with a version of libigl from around March 20, 2014. (Want to update to use the collapse_edge function...)

I have defined _VARIADIC_MAX=10 and this helped with some other (I think related) errors.

My googling let me into stuff about constructing std::function from NULL leading to this sort of error in VS, and maybe constructing from nullptr_t would work... am totally lost though.

Thanks

**Comment by alecjacobson** [comment]
Can you give more details about which function and on which line this error
is showing up?

**Comment by cap257zero** [comment]
Okay, had a chance to make a minimal example:

#include iostream
#include Eigen/Core
#include igl/readOFF.h
#include igl/viewer/Viewer.h

using namespace std;
using namespace Eigen;

int main()
{
	cout << "Hello, bunny!" << endl;

	MatrixXd V;
	MatrixXi F;
	igl::readOFF("bunny.off", V, F);
	cout << V.rows() << " vertices read and " << F.rows() << " faces read." << endl;

	return 0;
}

Works as expected if I remove the igl/viewer/Viewer.h include. With the include, I get these three errors:

Error	81	error C2064: term does not evaluate to a function taking 1 arguments	c:\program files (x86)\microsoft visual studio 11.0\vc\include\xrefwrap	431	1	libigl-test

Error	82	error C2064: term does not evaluate to a function taking 3 arguments	c:\program files (x86)\microsoft visual studio 11.0\vc\include\xrefwrap	431	1	libigl-test

Error	83	error C2064: term does not evaluate to a function taking 2 arguments	c:\program files (x86)\microsoft visual studio 11.0\vc\include\xrefwrap	431	1	libigl-test

If it's relevant I've defined _VARIADIC_MAX=10. This is Visual Studio 2012 on Windows 8.1.

Finally, problem was not present using the viewer from a libigl clone from mid March.

**Comment by alecjacobson** [comment]
Hmmm. Not really sure what's going on. The error doesn't seem to be from
our code. Are you sure that you have enabled C++11 support?

**Comment by cap257zero** [comment]
Yes, I think that is the issue, C++11 support in Visual Studio 2012. Not sure if I want to install the compiler patch, but I think you pinpointed the problem and it's not the libigl code. Thanks!
