### ISSUE TITLE
AntTweakBar Compile Error with VS2017

### ISSUE THREAD

**Issue by adam-hartshorne** [libigl/libigl#731]
I receive the following compilation errors when attempting to build AntTweakBar as part of libigl using VS2017.

2>d:\data\documents\github\libigl\external\anttweakbar\src\tweventglfw.c(194): error C2491: 'TwEventMouseButtonGLFWcdecl': definition of dllimport function not allowed
2>d:\data\documents\github\libigl\external\anttweakbar\src\tweventglfw.c(198): error C2491: 'TwEventKeyGLFWcdecl': definition of dllimport function not allowed
2>d:\data\documents\github\libigl\external\anttweakbar\src\tweventglfw.c(202): error C2491: 'TwEventCharGLFWcdecl': definition of dllimport function not allowed
2>d:\data\documents\github\libigl\external\anttweakbar\src\tweventglfw.c(206): error C2491: 'TwEventMousePosGLFWcdecl': definition of dllimport function not allowed
2>d:\data\documents\github\libigl\external\anttweakbar\src\tweventglfw.c(210): error C2491: 'TwEventMouseWheelGLFWcdecl': definition of dllimport function not allowed

**Comment by danielepanozzo** [comment]
AntTweakbar is deprecated, we are not supporting it anymore. @alecjacobson shall we delete the folder in external to prevent confusion?

**Comment by jdumas** [comment]
We could at least remove it from the CMake, but keep the files in `include/igl/anttweakbar`. Not sure what to do with the submodule though, I'd vote for removing it.
