### ISSUE TITLE
Do not try to configure CGAL if LIBIGL_WITH_CGAL is OFF

### ISSUE THREAD

**Issue by evouga** [libigl/libigl#732]
If the CGAL_DIR variable is set, libigl will try to configure CGAL, even if LIBIGL_WITH_CGAL is set to OFF. This causes CMake to fail to build the libigl application if CGAL is present on the system, but misconfigured.

**Comment by evouga** [comment]
Some of my students are trying to build a project that doesn't use CGAL at all (has LIBIGL_WITH_CGAL set to OFF) but are getting errors like

> CMake Error at /usr/lib/x86_64-linux-gnu/cmake/CGAL/CGALExports.cmake:83 (message):
>   The imported target "CGAL::CGAL_Qt5" references the file
> 
>      "/usr/lib/x86_64-linux-gnu/libCGAL_Qt5.so.11.0.1"
> 
>   but this file does not exist.  Possible reasons include:
> 
>   * The file was deleted, renamed, or moved to another location.
> 
>   * An install or uninstall procedure did not complete successfully.
> 
>   * The installation package was faulty and contained
> 
>      "/usr/lib/x86_64-linux-gnu/cmake/CGAL/CGALExports.cmake"
> 
>   but not all the files it references

**Comment by jdumas** [comment]
Hmm I see. Not my fault this time. I'm impressed that CGAL manage to ship broken packages.
We should proably remove [this line](https://github.com/libigl/libigl/blob/9de4b378ecf7a77e8ffeee1c95ceb3ff3e0428bd/shared/cmake/libigl.cmake#L6) then. Honestly I'm not fond of all this `find_package()` business at the top of the CMake file anyway, it is doing unnecessary work to populate the default options.

**Comment by ManikaBindal** [comment]
@evouga  how to solve this error. I started getting this error as soon as I installed CGAL in my system

**Comment by evouga** [comment]
You need to clear the CGAL_DIR variable when you run cmake. For example:

`cmake -DCGAL_DIR= ..`

**Comment by ManikaBindal** [comment]
Thanks...it is a good solution...Though mine worked after I uninstalled CGAL completely...

**Comment by the13fools** [comment]
Thank you!  Ran into the same issue, solution by @evouga worked, but was very confusing for a moment :(

**Comment by alecjacobson** [comment]
Hopefully this is all fixed with cmake changes. libigl works now with CGAL installed via cmake.
