### ISSUE TITLE
Call to `CGAL::do_intersect` ambiguous in `igl::copyleft::cgal::mesh_boolean`

### ISSUE THREAD

**Issue by elfprince13** [libigl/libigl#734]
I currently get two compiler errors from using `igl::copyleft::cgal::mesh_boolean`, that point to ambiguities invoking `CGAL::do_intersect`:

> In file included from /path/elided/deps/CGAL/Kernel_23/include/CGAL/Exact_predicates_inexact_constructions_kernel.h:28:
> In file included from /path/elided/deps/CGAL/Cartesian_kernel/include/CGAL/Simple_cartesian.h:28:
> In file included from /path/elided/deps/CGAL/Cartesian_kernel/include/CGAL/Cartesian/Cartesian_base.h:70:
> In file included from /path/elided/deps/CGAL/Cartesian_kernel/include/CGAL/Cartesian/function_objects.h:28:
> In file included from /path/elided/deps/CGAL/Kernel_23/include/CGAL/Kernel/function_objects.h:37:
> In file included from /path/elided/deps/CGAL/Intersections_3/include/CGAL/intersection_3.h:29:
> In file included from /path/elided/deps/CGAL/Intersections_3/include/CGAL/intersection_3_1.h:31:
> /path/elided/deps/CGAL/Intersections_3/include/CGAL/Intersections_3/intersection_3_1_impl.h:554:10: error: call to 'do_intersect' is ambiguous
>   bool b=do_intersect(s1.supporting_line(),s2.supporting_line(),k);
>          ^~~~~~~~~~~~
> 
> In file included from /path/elided/deps/CGAL/Kernel_23/include/CGAL/Exact_predicates_inexact_constructions_kernel.h:28:
> In file included from /path/elided/deps/CGAL/Cartesian_kernel/include/CGAL/Simple_cartesian.h:28:
> In file included from /path/elided/deps/CGAL/Cartesian_kernel/include/CGAL/Cartesian/Cartesian_base.h:70:
> In file included from /path/elided/deps/CGAL/Cartesian_kernel/include/CGAL/Cartesian/function_objects.h:28:
> /path/elided/deps/CGAL/Kernel_23/include/CGAL/Kernel/function_objects.h:2946:24: note: in instantiation of function template specialization 'CGAL::internal::do_intersect<CGAL::Simple_cartesian<CGAL::Interval_nt<false> > >' requested here
>     { return internal::do_intersect(t1, t2, K()); }
>                        ^
> 
> In file included from /path/elided/deps/CGAL/Kernel_23/include/CGAL/Exact_predicates_inexact_constructions_kernel.h:29:
> In file included from /path/elided/deps/CGAL/Filtered_kernel/include/CGAL/Filtered_kernel.h:26:
> /path/elided/deps/CGAL/Filtered_kernel/include/CGAL/Filtered_predicate.h:167:15: note: in instantiation of function template specialization 'CGAL::CommonKernelFunctors::Do_intersect_3<CGAL::Simple_cartesian<CGAL::Interval_nt<false> > >::operator()<CGAL::Segment_3<CGAL::Simple_cartesian<CGAL::Interval_nt<false> > >, CGAL::Segment_3<CGAL::Simple_cartesian<CGAL::Interval_nt<false> > > >' requested here
>           Ares res = ap(c2a(args)...);
>                      ^
> 
> In file included from /path/elided/deps/CGAL/Kernel_23/include/CGAL/Exact_predicates_inexact_constructions_kernel.h:28:
> In file included from /path/elided/deps/CGAL/Cartesian_kernel/include/CGAL/Simple_cartesian.h:28:
> In file included from /path/elided/deps/CGAL/Cartesian_kernel/include/CGAL/Cartesian/Cartesian_base.h:70:
> In file included from /path/elided/deps/CGAL/Cartesian_kernel/include/CGAL/Cartesian/function_objects.h:28:
> In file included from /path/elided/deps/CGAL/Kernel_23/include/CGAL/Kernel/function_objects.h:37:
> In file included from /path/elided/deps/CGAL/Intersections_3/include/CGAL/intersection_3.h:29:
> In file included from /path/elided/deps/CGAL/Intersections_3/include/CGAL/intersection_3_1.h:31:
> /path/elided/deps/CGAL/Intersections_3/include/CGAL/Intersections_3/intersection_3_1_impl.h:78:1: note: in instantiation of function template specialization 'CGAL::Filtered_predicate<CGAL::CommonKernelFunctors::Do_intersect_3<CGAL::Simple_cartesian<CGAL::Gmpq> >, CGAL::CommonKernelFunctors::Do_intersect_3<CGAL::Simple_cartesian<CGAL::Interval_nt<false> > >, CGAL::Cartesian_converter<CGAL::Type_equality_wrapper<CGAL::Cartesian_base_no_ref_count<double, CGAL::Epick>, CGAL::Epick>, CGAL::Simple_cartesian<CGAL::Gmpq>, CGAL::NT_converter<double, CGAL::Gmpq> >, CGAL::Cartesian_converter<CGAL::Type_equality_wrapper<CGAL::Cartesian_base_no_ref_count<double, CGAL::Epick>, CGAL::Epick>, CGAL::Simple_cartesian<CGAL::Interval_nt<false> >, CGAL::NT_converter<double, CGAL::Interval_nt<false> > >, true>::operator()<CGAL::Segment_3<CGAL::Epick>, CGAL::Segment_3<CGAL::Epick> >' requested here
> CGAL_DO_INTERSECT_FUNCTION_SELF(Segment_3, 3)
> ^
> 
> In file included from /path/elided/deps/CGAL/Kernel_23/include/CGAL/Exact_predicates_inexact_constructions_kernel.h:28:
> In file included from /path/elided/deps/CGAL/Cartesian_kernel/include/CGAL/Simple_cartesian.h:28:
> In file included from /path/elided/deps/CGAL/Cartesian_kernel/include/CGAL/Cartesian/Cartesian_base.h:70:
> In file included from /path/elided/deps/CGAL/Cartesian_kernel/include/CGAL/Cartesian/function_objects.h:28:
> In file included from /path/elided/deps/CGAL/Kernel_23/include/CGAL/Kernel/function_objects.h:36:
> In file included from /path/elided/deps/CGAL/Intersections_2/include/CGAL/intersection_2.h:30:
> In file included from /path/elided/deps/CGAL/Intersections_2/include/CGAL/intersection_2_1.h:30:
> In file included from /path/elided/deps/CGAL/Intersections_2/include/CGAL/Line_2_Line_2_intersection.h:34:
> In file included from /path/elided/deps/CGAL/Intersections_2/include/CGAL/Intersection_traits_2.h:24:
> /path/elided/deps/CGAL/Intersections_2/include/CGAL/Intersection_traits.h:108:25: note: expanded from macro 'CGAL_DO_INTERSECT_FUNCTION_SELF'
>     return BOOST_PP_CAT(K().do_intersect_, BOOST_PP_CAT(DIM, _object()(a, b))); \
>                         ^
> 
> In file included from /path/elided/deps/libigl/include/igl/copyleft/cgal/mesh_boolean.h:213:
> In file included from /path/elided/deps/libigl/include/igl/copyleft/cgal/mesh_boolean.cpp:16:
> In file included from /path/elided/deps/libigl/include/igl/copyleft/cgal/remesh_self_intersections.h:78:
> In file included from /path/elided/deps/libigl/include/igl/copyleft/cgal/remesh_self_intersections.cpp:9:
> /path/elided/deps/libigl/include/igl/copyleft/cgal/SelfIntersectMesh.h:679:22: note: in instantiation of function template specialization 'CGAL::do_intersect<CGAL::Epick>' requested here
>     bool ret = CGAL::do_intersect(sa,sb);
>                      ^
> /path/elided/deps/libigl/include/igl/copyleft/cgal/SelfIntersectMesh.h:894:11: note: in instantiation of member function 'igl::copyleft::cgal::SelfIntersectMesh<CGAL::Epick, Eigen::Matrix<double, -1, 3, 0, -1, 3>, Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<CGAL::Lazy_exact_nt<CGAL::Gmpq>, -1, -1, 0, -1, -1>, Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<long, -1, 1, 0, -1, 1>, Eigen::Matrix<int, -1, 1, 0, -1, 1> >::double_shared_vertex' requested here
>           double_shared_vertex(A,B,fa,fb,shared);
>           ^
> /path/elided/deps/libigl/include/igl/copyleft/cgal/SelfIntersectMesh.h:361:5: note: (skipping 2 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)
>     process_intersecting_boxes();
>     ^
> 
> In file included from /path/elided/deps/libigl/include/igl/copyleft/cgal/mesh_boolean.h:213:
> /path/elided/deps/libigl/include/igl/copyleft/cgal/mesh_boolean.cpp:220:26: note: in instantiation of function template specialization 'igl::copyleft::cgal::remesh_self_intersections<Eigen::Matrix<double, -1, 3, 0, -1, 3>, Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<CGAL::Lazy_exact_nt<CGAL::Gmpq>, -1, -1, 0, -1, -1>, Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<long, -1, 1, 0, -1, 1>, Eigen::Matrix<int, -1, 1, 0, -1, 1> >' requested here
>     igl::copyleft::cgal::remesh_self_intersections(
>                          ^
> /path/elided/deps/libigl/include/igl/copyleft/cgal/mesh_boolean.cpp:122:10: note: in instantiation of function template specialization 'igl::copyleft::cgal::mesh_boolean<Eigen::Matrix<double, -1, 3, 0, -1, 3>, Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<unsigned long, 2, 1, 0, 2, 1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<long, -1, 1, 0, -1, 1> >' requested here
>   return mesh_boolean(VV,FF,sizes,wind_num_op,keep,VC,FC,J);
>          ^
> /path/elided/deps/libigl/include/igl/copyleft/cgal/mesh_boolean.cpp:55:10: note: in instantiation of function template specialization 'igl::copyleft::cgal::mesh_boolean<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<long, -1, 1, 0, -1, 1> >' requested here
>   return mesh_boolean(VA,FA,VB,FB,wind_num_op,keep,VC,FC,J);
>          ^
> /path/elided/deps/libigl/include/igl/copyleft/cgal/mesh_boolean.cpp:429:31: note: in instantiation of function template specialization 'igl::copyleft::cgal::mesh_boolean<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<long, -1, 1, 0, -1, 1> >' requested here
>   return igl::copyleft::cgal::mesh_boolean(VA,FA,VB,FB,type,VC,FC,J);
>                              ^
> 
> In file included from /path/elided/deps/CGAL/Kernel_23/include/CGAL/Exact_predicates_inexact_constructions_kernel.h:28:
> In file included from /path/elided/deps/CGAL/Cartesian_kernel/include/CGAL/Simple_cartesian.h:28:
> In file included from /path/elided/deps/CGAL/Cartesian_kernel/include/CGAL/Cartesian/Cartesian_base.h:70:
> In file included from /path/elided/deps/CGAL/Cartesian_kernel/include/CGAL/Cartesian/function_objects.h:28:
> In file included from /path/elided/deps/CGAL/Kernel_23/include/CGAL/Kernel/function_objects.h:37:
> In file included from /path/elided/deps/CGAL/Intersections_3/include/CGAL/intersection_3.h:29:
> In file included from /path/elided/deps/CGAL/Intersections_3/include/CGAL/intersection_3_1.h:31:
> /path/elided/deps/CGAL/Intersections_3/include/CGAL/Intersections_3/intersection_3_1_impl.h:435:1: note: candidate function [with K = CGAL::Simple_cartesian<CGAL::Interval_nt<false> >]
> do_intersect(const typename K::Line_3 &l1,
> ^
> 
> 
> /path/elided/deps/CGAL/Boolean_set_operations_2/include/CGAL/Boolean_set_operations_2.h:1009:13: note: candidate function [with InputIterator = CGAL::Line_3<CGAL::Simple_cartesian<CGAL::Interval_nt<false> > >, Traits = const CGAL::Simple_cartesian<CGAL::Interval_nt<false> >]
> inline bool do_intersect(InputIterator begin, InputIterator end, Traits& tr,

and: 

> In file included from /path/elided/deps/CGAL/Kernel_23/include/CGAL/Exact_predicates_inexact_constructions_kernel.h:28:
> In file included from /path/elided/deps/CGAL/Cartesian_kernel/include/CGAL/Simple_cartesian.h:28:
> In file included from /path/elided/deps/CGAL/Cartesian_kernel/include/CGAL/Cartesian/Cartesian_base.h:70:
> In file included from /path/elided/deps/CGAL/Cartesian_kernel/include/CGAL/Cartesian/function_objects.h:28:
> In file included from /path/elided/deps/CGAL/Kernel_23/include/CGAL/Kernel/function_objects.h:37:
> In file included from /path/elided/deps/CGAL/Intersections_3/include/CGAL/intersection_3.h:29:
> In file included from /path/elided/deps/CGAL/Intersections_3/include/CGAL/intersection_3_1.h:31:
> /path/elided/deps/CGAL/Intersections_3/include/CGAL/Intersections_3/intersection_3_1_impl.h:554:10: error: call to 'do_intersect' is ambiguous
>   bool b=do_intersect(s1.supporting_line(),s2.supporting_line(),k);
>          ^~~~~~~~~~~~
> 
> In file included from /path/elided/deps/CGAL/Kernel_23/include/CGAL/Exact_predicates_inexact_constructions_kernel.h:28:
> In file included from /path/elided/deps/CGAL/Cartesian_kernel/include/CGAL/Simple_cartesian.h:28:
> In file included from /path/elided/deps/CGAL/Cartesian_kernel/include/CGAL/Cartesian/Cartesian_base.h:70:
> In file included from /path/elided/deps/CGAL/Cartesian_kernel/include/CGAL/Cartesian/function_objects.h:28:
> /path/elided/deps/CGAL/Kernel_23/include/CGAL/Kernel/function_objects.h:2946:24: note: in instantiation of function template specialization 'CGAL::internal::do_intersect<CGAL::Simple_cartesian<CGAL::Gmpq> >' requested here
>     { return internal::do_intersect(t1, t2, K()); }
>                        ^
> 
> In file included from /path/elided/deps/CGAL/Kernel_23/include/CGAL/Exact_predicates_inexact_constructions_kernel.h:29:
> In file included from /path/elided/deps/CGAL/Filtered_kernel/include/CGAL/Filtered_kernel.h:26:
> /path/elided/deps/CGAL/Filtered_kernel/include/CGAL/Filtered_predicate.h:175:12: note: in instantiation of function template specialization 'CGAL::CommonKernelFunctors::Do_intersect_3<CGAL::Simple_cartesian<CGAL::Gmpq> >::operator()<CGAL::Segment_3<CGAL::Simple_cartesian<CGAL::Gmpq> >, CGAL::Segment_3<CGAL::Simple_cartesian<CGAL::Gmpq> > >' requested here
>     return ep(c2e(args)...);
>            ^
> 
> In file included from /path/elided/deps/CGAL/Kernel_23/include/CGAL/Exact_predicates_inexact_constructions_kernel.h:28:
> In file included from /path/elided/deps/CGAL/Cartesian_kernel/include/CGAL/Simple_cartesian.h:28:
> In file included from /path/elided/deps/CGAL/Cartesian_kernel/include/CGAL/Cartesian/Cartesian_base.h:70:
> In file included from /path/elided/deps/CGAL/Cartesian_kernel/include/CGAL/Cartesian/function_objects.h:28:
> In file included from /path/elided/deps/CGAL/Kernel_23/include/CGAL/Kernel/function_objects.h:37:
> In file included from /path/elided/deps/CGAL/Intersections_3/include/CGAL/intersection_3.h:29:
> In file included from /path/elided/deps/CGAL/Intersections_3/include/CGAL/intersection_3_1.h:31:
> /path/elided/deps/CGAL/Intersections_3/include/CGAL/Intersections_3/intersection_3_1_impl.h:78:1: note: in instantiation of function template specialization 'CGAL::Filtered_predicate<CGAL::CommonKernelFunctors::Do_intersect_3<CGAL::Simple_cartesian<CGAL::Gmpq> >, CGAL::CommonKernelFunctors::Do_intersect_3<CGAL::Simple_cartesian<CGAL::Interval_nt<false> > >, CGAL::Cartesian_converter<CGAL::Type_equality_wrapper<CGAL::Cartesian_base_no_ref_count<double, CGAL::Epick>, CGAL::Epick>, CGAL::Simple_cartesian<CGAL::Gmpq>, CGAL::NT_converter<double, CGAL::Gmpq> >, CGAL::Cartesian_converter<CGAL::Type_equality_wrapper<CGAL::Cartesian_base_no_ref_count<double, CGAL::Epick>, CGAL::Epick>, CGAL::Simple_cartesian<CGAL::Interval_nt<false> >, CGAL::NT_converter<double, CGAL::Interval_nt<false> > >, true>::operator()<CGAL::Segment_3<CGAL::Epick>, CGAL::Segment_3<CGAL::Epick> >' requested here
> CGAL_DO_INTERSECT_FUNCTION_SELF(Segment_3, 3)
> ^
> 
> In file included from /path/elided/deps/CGAL/Kernel_23/include/CGAL/Exact_predicates_inexact_constructions_kernel.h:28:
> In file included from /path/elided/deps/CGAL/Cartesian_kernel/include/CGAL/Simple_cartesian.h:28:
> In file included from /path/elided/deps/CGAL/Cartesian_kernel/include/CGAL/Cartesian/Cartesian_base.h:70:
> In file included from /path/elided/deps/CGAL/Cartesian_kernel/include/CGAL/Cartesian/function_objects.h:28:
> In file included from /path/elided/deps/CGAL/Kernel_23/include/CGAL/Kernel/function_objects.h:36:
> In file included from /path/elided/deps/CGAL/Intersections_2/include/CGAL/intersection_2.h:30:
> In file included from /path/elided/deps/CGAL/Intersections_2/include/CGAL/intersection_2_1.h:30:
> In file included from /path/elided/deps/CGAL/Intersections_2/include/CGAL/Line_2_Line_2_intersection.h:34:
> In file included from /path/elided/deps/CGAL/Intersections_2/include/CGAL/Intersection_traits_2.h:24:
> /path/elided/deps/CGAL/Intersections_2/include/CGAL/Intersection_traits.h:108:25: note: expanded from macro 'CGAL_DO_INTERSECT_FUNCTION_SELF'
>     return BOOST_PP_CAT(K().do_intersect_, BOOST_PP_CAT(DIM, _object()(a, b))); \
>                         ^
> 
> In file included from /path/elided/deps/libigl/include/igl/copyleft/cgal/mesh_boolean.h:213:
> In file included from /path/elided/deps/libigl/include/igl/copyleft/cgal/mesh_boolean.cpp:16:
> In file included from /path/elided/deps/libigl/include/igl/copyleft/cgal/remesh_self_intersections.h:78:
> In file included from /path/elided/deps/libigl/include/igl/copyleft/cgal/remesh_self_intersections.cpp:9:
> /path/elided/deps/libigl/include/igl/copyleft/cgal/SelfIntersectMesh.h:679:22: note: in instantiation of function template specialization 'CGAL::do_intersect<CGAL::Epick>' requested here
>     bool ret = CGAL::do_intersect(sa,sb);
>                      ^
> /path/elided/deps/libigl/include/igl/copyleft/cgal/SelfIntersectMesh.h:894:11: note: in instantiation of member function 'igl::copyleft::cgal::SelfIntersectMesh<CGAL::Epick, Eigen::Matrix<double, -1, 3, 0, -1, 3>, Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<CGAL::Lazy_exact_nt<CGAL::Gmpq>, -1, -1, 0, -1, -1>, Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<long, -1, 1, 0, -1, 1>, Eigen::Matrix<int, -1, 1, 0, -1, 1> >::double_shared_vertex' requested here
>           double_shared_vertex(A,B,fa,fb,shared);
>           ^
> /path/elided/deps/libigl/include/igl/copyleft/cgal/SelfIntersectMesh.h:361:5: note: (skipping 2 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)
>     process_intersecting_boxes();
>     ^
> 
> In file included from /path/elided/deps/libigl/include/igl/copyleft/cgal/mesh_boolean.h:213:
> /path/elided/deps/libigl/include/igl/copyleft/cgal/mesh_boolean.cpp:220:26: note: in instantiation of function template specialization 'igl::copyleft::cgal::remesh_self_intersections<Eigen::Matrix<double, -1, 3, 0, -1, 3>, Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<CGAL::Lazy_exact_nt<CGAL::Gmpq>, -1, -1, 0, -1, -1>, Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<long, -1, 1, 0, -1, 1>, Eigen::Matrix<int, -1, 1, 0, -1, 1> >' requested here
>     igl::copyleft::cgal::remesh_self_intersections(
>                          ^
> /path/elided/deps/libigl/include/igl/copyleft/cgal/mesh_boolean.cpp:122:10: note: in instantiation of function template specialization 'igl::copyleft::cgal::mesh_boolean<Eigen::Matrix<double, -1, 3, 0, -1, 3>, Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<unsigned long, 2, 1, 0, 2, 1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<long, -1, 1, 0, -1, 1> >' requested here
>   return mesh_boolean(VV,FF,sizes,wind_num_op,keep,VC,FC,J);
>          ^
> /path/elided/deps/libigl/include/igl/copyleft/cgal/mesh_boolean.cpp:55:10: note: in instantiation of function template specialization 'igl::copyleft::cgal::mesh_boolean<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<long, -1, 1, 0, -1, 1> >' requested here
>   return mesh_boolean(VA,FA,VB,FB,wind_num_op,keep,VC,FC,J);
>          ^
> /path/elided/deps/libigl/include/igl/copyleft/cgal/mesh_boolean.cpp:429:31: note: in instantiation of function template specialization 'igl::copyleft::cgal::mesh_boolean<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<long, -1, 1, 0, -1, 1> >' requested here
>   return igl::copyleft::cgal::mesh_boolean(VA,FA,VB,FB,type,VC,FC,J);
>                              ^
> 
> In file included from /path/elided/deps/CGAL/Kernel_23/include/CGAL/Exact_predicates_inexact_constructions_kernel.h:28:
> In file included from /path/elided/deps/CGAL/Cartesian_kernel/include/CGAL/Simple_cartesian.h:28:
> In file included from /path/elided/deps/CGAL/Cartesian_kernel/include/CGAL/Cartesian/Cartesian_base.h:70:
> In file included from /path/elided/deps/CGAL/Cartesian_kernel/include/CGAL/Cartesian/function_objects.h:28:
> In file included from /path/elided/deps/CGAL/Kernel_23/include/CGAL/Kernel/function_objects.h:37:
> In file included from /path/elided/deps/CGAL/Intersections_3/include/CGAL/intersection_3.h:29:
> In file included from /path/elided/deps/CGAL/Intersections_3/include/CGAL/intersection_3_1.h:31:
> /path/elided/deps/CGAL/Intersections_3/include/CGAL/Intersections_3/intersection_3_1_impl.h:435:1: note: candidate function [with K = CGAL::Simple_cartesian<CGAL::Gmpq>]
> do_intersect(const typename K::Line_3 &l1,
> ^
> 
> 
> /path/elided/deps/CGAL/Boolean_set_operations_2/include/CGAL/Boolean_set_operations_2.h:1009:13: note: candidate function [with InputIterator = CGAL::Line_3<CGAL::Simple_cartesian<CGAL::Gmpq> >, Traits = const CGAL::Simple_cartesian<CGAL::Gmpq>]
> inline bool do_intersect(InputIterator begin, InputIterator end, Traits& tr,

Reasonably sure the problem is with IGL and not with our code, since `mesh_boolean` itself isn't templated.

**Comment by jdumas** [comment]
Hi,

- Which platform/compiler/version of CGAL are you using?
- Can you compile the CGAL boolean tutorial in the libigl repository?

**Comment by alecjacobson** [comment]
@qnzhou might have some insight, too.

It might also be useful to know on what system you're compiling and with which compiler.

**Comment by elfprince13** [comment]
Currently have libigl checked out at dbfa2b7, and CGAL/cgal@3742089.

Compiler is:

> [thomas@Mithlond] builddir $ /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ --version
> Apple LLVM version 8.0.0 (clang-800.0.42.1)
> Target: x86_64-apple-darwin15.6.0
> Thread model: posix
> InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
on OS X 10.11.6

I'm testing the boolean tutorial now, and will reply with the results shortly.

**Comment by elfprince13** [comment]
`609_Boolean_bin` compiles (but fails to link with some errors that look like it couldn't find the system objective C runtime used for the graphical part of the app, which don't seem relevant to the errors above).

**Comment by jdumas** [comment]
Could you try to compile the tutorial a latest clone of libigl and see if it solves your problem?

**Comment by qnzhou** [comment]
Hmmm, the error message from CGAL is cryptic...  But I am wondering why `CGAL::Epick` kernel is used for `SelfIntersectMesh` in the first place.

**Comment by alecjacobson** [comment]
It's used when Param.detect_only = true.

These could be cleaned up with `if constexpr` in C++17 or pre-C++17-style partial template specialization structs. not going to do it for this old issue that is hopefully resolved by time though.
