### ISSUE TITLE
Eigen not compiling on MSVC2017 in Debug Mode

### ISSUE THREAD

**Issue by danhambleton** [libigl/libigl#736]
I just pulled the latest libigl and eigen (from your mirror) and included both in a DLL project (VS2017). In Release Mode, everything compiles fine (and runs fine). But in Debug mode, I got these kinds of errors:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2059	syntax error: 'constant'	Geomlib	c:\development\uidev\source\geomlib\eigen\eigen\src\Core\PlainObjectBase.h	143	
```
and
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2091	function returns function	Geomlib	c:\development\uidev\source\geomlib\eigen\eigen\src\Core\PlainObjectBase.h	143	

```

There are more, but those are good start. Any thoughts on this? I have tried setting ```-DEIGEN_DONT_ALIGN``` (or some such macro). However, I then get an error in Memory.h, which does not seem like progress.

I know that this is not directly related to libigl, but any help is appreciated!

**Comment by danhambleton** [comment]
Any ideas? Would be great to get this compiling in Debug mode again.

**Comment by jdumas** [comment]
- Are you compiling in 64bits?
- Can you compile the tutorials? The example-project?

**Comment by danhambleton** [comment]
Hmm ok interesting. So, I just grabbed all the libigl submodules (including eigen) and built the tutorials with no issues (on Debug mode). So there most be something in my project that is messing things up...

**Comment by danhambleton** [comment]
FWIW, I had to include Eigen/Core before some of my other header files. Not sure why.
