### ISSUE TITLE
ViewerData needs EIGEN_MAKE_ALIGNED_OPERATOR_NEW

### ISSUE THREAD

**Issue by evouga** [libigl/libigl#743]
I am getting crashes because
`Eigen::Vector4f line_color;`
in ViewerData is not correctly aligned.

**Comment by danielepanozzo** [comment]
Which OS? If it is windows, can you confirm that you are compiling in 64-bit mode?

**Comment by evouga** [comment]
Windows 32-bit. 

Is this unsupported? I didn't see anything about 32-bit in the tutorial.

**Comment by jdumas** [comment]
Yes there is this note in the tutorial:

> Note for windows users: libigl only supports the Microsoft Visual Studio 2015 compiler in 64bit mode. It will not work with a 32bit build and it will not work with older versions of visual studio.

That being said, it probably wouldn't hurt to add this macro. We could also add an error message in the CMake (this is easy to detect), and ask the user to compile in 64bit mode.

**Comment by evouga** [comment]
Hmm I don't see that text either at https://github.com/libigl/libigl/blob/master/README.md or at http://libigl.github.io/libigl/.

In any case it's easy enough for me to switch to 64-bit mode, but some error in CMake would certainly be useful.

**Comment by jdumas** [comment]
The note is hidden in the tutorial webpage (but we should make it more visible):
https://libigl.github.io/libigl/tutorial/tutorial.html

**Comment by alecjacobson** [comment]
I guess this was fixed by #1029
