### ISSUE TITLE
Mesh comparison

### ISSUE THREAD

**Issue by alireza59** [libigl/libigl#745]
Is there any mesh comparison assessment method in libigl?

**Comment by jdumas** [comment]
You mean like [Hausdorff distance](https://github.com/libigl/libigl/blob/master/include/igl/hausdorff.h)?

**Comment by alireza59** [comment]
Thank you for the answer. What I need is something for comparing a decimated mesh with the original mesh.  to get the mean and RMS of the distance between 2 meshes. also I wanna use the same algorithm for mesh alignment test to be sure they are aligned good enough.

**Comment by alecjacobson** [comment]
See `point_mesh_squared_distance` you can build all sorts of distance measures with that.
