### ISSUE TITLE
Viewer rendering loop

### ISSUE THREAD

**Issue by KristianZarn** [libigl/libigl#746]
I wrote a simple program that displays a webcam video in seperate window. The new window is created with `menu.callback_draw_custom_window` as in `Example 106`. 

It looks like this:
![screenshot](https://user-images.githubusercontent.com/6253845/38646811-cc37b8a0-3de9-11e8-9fb0-6b2cdb5075c4.png)

The problem was that the webcam video was not refreshing if I was not moving the mouse inside of the `Viewer` window (or if there were no other events). 

In an attempt to solve the problem I commented out the command `glfwWaitEvents();` inside the viewer's rendering loop (see the snippet below). This seems to solve my problem and constatnly refreshes the webcam video.

Since I don't know much about `glfw` I am wondering if this is a bad idea, and if it can potentially break other things. I would also prefer a more elegant solution without changing the Viewer's source code if such solution exists.

This is a code snippet from my `Viewer.cpp`:
```
IGL_INLINE bool Viewer::launch_rendering(bool loop)
  {
    // glfwMakeContextCurrent(window);
    // Rendering loop
    const int num_extra_frames = 5;
    int frame_counter = 0;
    while (!glfwWindowShouldClose(window))
    {
      double tic = get_seconds();
      draw();
      glfwSwapBuffers(window);
      if(core.is_animating || frame_counter++ < num_extra_frames)
      {
        glfwPollEvents();
        // In microseconds
        double duration = 1000000.*(get_seconds()-tic);
        const double min_duration = 1000000./core.animation_max_fps;
        if(duration<min_duration)
        {
          std::this_thread::sleep_for(std::chrono::microseconds((int)(min_duration-duration)));
        }
      }
      else
      {
        // glfwWaitEvents();
        frame_counter = 0;
      }
      if (!loop)
        return !glfwWindowShouldClose(window);
    }
    return EXIT_SUCCESS;
  }
```

**Comment by jdumas** [comment]
You need to set `viewer.core.is_animating = true;`. If you don't, then the viewer redraw its content only when there is a mouse/keyboard event.

**Comment by KristianZarn** [comment]
Thank you for quick reply. It works!
