### ISSUE TITLE
Error Win10+Visual Studio 2015

### ISSUE THREAD

**Issue by hadibeiki** [libigl/libigl#749]
Hi..
i instal libigl with Cmake but at the All_Build this error show:

- Severity	Code	Description	Project	File	Line
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	360
Error	C2065	'GLFW_OSMESA_CONTEXT_API': undeclared identifier	glfw	G:\DirectField\libigl\external\glfw\src\context.c	62
Error	C2198	'memset': too few arguments for call	glfw	G:\DirectField\libigl\external\glfw\src\init.c	97
Error	C2079	'_glfw' uses undefined struct '_GLFWlibrary'	glfw	G:\DirectField\libigl\external\glfw\src\init.c	44
Error	C2371	'_glfw': redefinition; different basic types	glfw	G:\DirectField\libigl\external\glfw\src\init.c	44
Error	C2198	'_glfwPlatformGetTls': too few arguments for call	glfw	G:\DirectField\libigl\external\glfw\src\context.c	362
Error	C2198	'_glfwPlatformGetTls': too few arguments for call	glfw	G:\DirectField\libigl\external\glfw\src\context.c	615
Error	C1003	error count exceeds 100; stopping compilation	glfw	G:\DirectField\libigl\external\glfw\src\context.c	638
Error	C2037	left of 'callbacks' specifies undefined struct/union '_GLFWlibrary'	glfw	G:\DirectField\libigl\external\glfw\src\init.c	97
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	53
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	359
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	365
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	366
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	367
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	368
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	369
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	376
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	401
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	407
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	408
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	409
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	411
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	426
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	427
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	428
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	437
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	442
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	449
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	456
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	462
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	463
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	464
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	473
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	476
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	479
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	482
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	485
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	492
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	496
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	500
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	501
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	504
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	507
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	509
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	516
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	527
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	531
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	533
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	545
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	549
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	551
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	558
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	561
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	563
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	570
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	572
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	619
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	628
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	629
Error	C2037	left of 'context' specifies undefined struct/union '_GLFWwindow'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	633
Error	C2037	left of 'contextSlot' specifies undefined struct/union '_GLFWlibrary'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	362
Error	C2037	left of 'contextSlot' specifies undefined struct/union '_GLFWlibrary'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	615
Error	C2037	left of 'initialized' specifies undefined struct/union '_GLFWlibrary'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	617
Error	C2037	left of 'initialized' specifies undefined struct/union '_GLFWlibrary'	glfw	G:\DirectField\libigl\external\glfw\src\context.c	638
Error	C2037	left of 'windowListHead' specifies undefined struct/union '_GLFWlibrary'	glfw	G:\DirectField\libigl\external\glfw\src\init.c	99
Error	C2059	syntax error: ')'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	42
Error	C2059	syntax error: ')'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	43
Error	C2059	syntax error: ')'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	44
Error	C2059	syntax error: ')'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	45
Error	C2059	syntax error: ')'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	46
Error	C2059	syntax error: ')'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	47
Error	C2059	syntax error: ')'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	48
Error	C2059	syntax error: ')'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	42
Error	C2059	syntax error: ')'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	43
Error	C2059	syntax error: ')'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	44
Error	C2059	syntax error: ')'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	45
Error	C2059	syntax error: ')'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	46
Error	C2059	syntax error: ')'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	47
Error	C2059	syntax error: ')'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	48
Error	C2059	syntax error: ';'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	79
Error	C2059	syntax error: ';'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	80
Error	C2059	syntax error: ';'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	81
Error	C2059	syntax error: ';'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	82
Error	C2059	syntax error: ';'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	83
Error	C2059	syntax error: ';'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	84
Error	C2059	syntax error: ';'	glfw	g:\directfield\libigl\external\glfw\src\internal.h	405
Error	C2059	syntax error: ';'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	79
Error	C2059	syntax error: ';'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	80
Error	C2059	syntax error: ';'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	81
Error	C2059	syntax error: ';'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	82
Error	C2059	syntax error: ';'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	83
Error	C2059	syntax error: ';'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	84
Error	C2059	syntax error: ';'	glfw	g:\directfield\libigl\external\glfw\src\internal.h	405
Error	C2059	syntax error: '}'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	86
Error	C2059	syntax error: '}'	glfw	g:\directfield\libigl\external\glfw\src\internal.h	414
Error	C2059	syntax error: '}'	glfw	g:\directfield\libigl\external\glfw\src\internal.h	418
Error	C2059	syntax error: '}'	glfw	g:\directfield\libigl\external\glfw\src\internal.h	581
Error	C2059	syntax error: '}'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	86
Error	C2059	syntax error: '}'	glfw	g:\directfield\libigl\external\glfw\src\internal.h	414
Error	C2059	syntax error: '}'	glfw	g:\directfield\libigl\external\glfw\src\internal.h	418
Error	C2059	syntax error: '}'	glfw	g:\directfield\libigl\external\glfw\src\internal.h	581
Error	C2061	syntax error: identifier 'CreateContextAttribs'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	79
Error	C2061	syntax error: identifier 'CreateContextAttribs'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	79
Error	C2061	syntax error: identifier 'DestroyContext'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	80
Error	C2061	syntax error: identifier 'DestroyContext'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	80
Error	C2061	syntax error: identifier 'GetColorBuffer'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	82
Error	C2061	syntax error: identifier 'GetColorBuffer'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	82
Error	C2061	syntax error: identifier 'GetDepthBuffer'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	83
Error	C2061	syntax error: identifier 'GetDepthBuffer'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	83
Error	C2061	syntax error: identifier 'GetProcAddress'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	84
Error	C2061	syntax error: identifier 'GetProcAddress'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	84
Error	C2061	syntax error: identifier 'GLFWwindowmaximizefun'	glfw	g:\directfield\libigl\external\glfw\src\internal.h	403
Error	C2061	syntax error: identifier 'GLFWwindowmaximizefun'	glfw	g:\directfield\libigl\external\glfw\src\internal.h	403
Error	C2061	syntax error: identifier 'MakeCurrent'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	81
Error	C2061	syntax error: identifier 'MakeCurrent'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	81
Error	C2061	syntax error: identifier 'PFN_OSMesaCreateContextExt'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	78
Error	C2061	syntax error: identifier 'PFN_OSMesaCreateContextExt'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	78
Error	C2061	syntax error: identifier 'scale'	glfw	g:\directfield\libigl\external\glfw\src\internal.h	405
Error	C2061	syntax error: identifier 'scale'	glfw	g:\directfield\libigl\external\glfw\src\internal.h	405
Error	C2061	syntax error: identifier '_GLFWlibraryOSMesa'	glfw	g:\directfield\libigl\external\glfw\src\internal.h	580
Error	C2061	syntax error: identifier '_GLFWlibraryOSMesa'	glfw	g:\directfield\libigl\external\glfw\src\internal.h	580
Error	C2143	syntax error: missing ')' before '*'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	42
Error	C2143	syntax error: missing ')' before '*'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	43
Error	C2143	syntax error: missing ')' before '*'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	44
Error	C2143	syntax error: missing ')' before '*'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	45
Error	C2143	syntax error: missing ')' before '*'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	46
Error	C2143	syntax error: missing ')' before '*'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	47
Error	C2143	syntax error: missing ')' before '*'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	48
Error	C2143	syntax error: missing ')' before '*'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	42
Error	C2143	syntax error: missing ')' before '*'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	43
Error	C2143	syntax error: missing ')' before '*'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	44
Error	C2143	syntax error: missing ')' before '*'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	45
Error	C2143	syntax error: missing ')' before '*'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	46
Error	C2143	syntax error: missing ')' before '*'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	47
Error	C2143	syntax error: missing ')' before '*'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	48
Error	C2143	syntax error: missing '{' before '*'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	42
Error	C2143	syntax error: missing '{' before '*'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	43
Error	C2143	syntax error: missing '{' before '*'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	44
Error	C2143	syntax error: missing '{' before '*'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	45
Error	C2143	syntax error: missing '{' before '*'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	46
Error	C2143	syntax error: missing '{' before '*'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	47
Error	C2143	syntax error: missing '{' before '*'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	48
Error	C2143	syntax error: missing '{' before '*'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	42
Error	C2143	syntax error: missing '{' before '*'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	43
Error	C2143	syntax error: missing '{' before '*'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	44
Error	C2143	syntax error: missing '{' before '*'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	45
Error	C2143	syntax error: missing '{' before '*'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	46
Error	C2143	syntax error: missing '{' before '*'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	47
Error	C2143	syntax error: missing '{' before '*'	glfw	g:\directfield\libigl\external\glfw\src\osmesa_context.h	48
Error	C1903	unable to recover from previous error(s); stopping compilation	glfw	G:\DirectField\libigl\external\glfw\src\init.c	99

i think all about GLFW....
Help me please..

**Comment by jdumas** [comment]
Did you check everything that was mentioned on [this page](https://github.com/libigl/libigl/blob/master/CONTRIBUTING.md)

**Comment by hadibeiki** [comment]
yes...
when i turn off LIBIGL_USE_STATIC_LIBRARY cmake on gneration make error :
![untitled02](https://user-images.githubusercontent.com/4311329/38768875-5d071ba6-400f-11e8-91bf-a0a970f50795.png)

CMAKE_C_COMPILER: D:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
CMAKE_CXX_COMPILER: D:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
Could NOT find Matlab (missing:  Matlab_INCLUDE_DIRS Matlab_MEX_LIBRARY Matlab_MEX_EXTENSION Matlab_ROOT_DIR) 
Could NOT find MOSEK (missing:  MOSEK_LIBRARIES MOSEK_INCLUDE_DIR) 
CGAL not found.  Set the CGAL_DIR cmake variable or environment variable to the directory containing CGALConfig.cmake. This is either the binary directory where CGAL was configured or PREFIX/lib/CGAL for an installation.
Could NOT find Boost
Could NOT find Matlab (missing:  Matlab_INCLUDE_DIRS Matlab_MEX_LIBRARY Matlab_MEX_EXTENSION Matlab_ROOT_DIR MEX_COMPILER MX_LIBRARY ENG_LIBRARY) 
Could NOT find MOSEK (missing:  MOSEK_LIBRARIES MOSEK_INCLUDE_DIR) 
CMake Error: Target igl_core has dependency information when it shouldn't.
Your cache is probably stale. Please remove the entry
  igl_core_LIB_DEPENDS
from the cache.
Creating target: igl::core
CMake Error: Target igl_comiso has dependency information when it shouldn't.
Your cache is probably stale. Please remove the entry
  igl_comiso_LIB_DEPENDS
from the cache.
Creating target: igl::comiso
Could NOT find Git (missing:  GIT_EXECUTABLE) 
Detecting default ISA:
Detecting default ISA: SSE2
CMake Error: Target igl_embree has dependency information when it shouldn't.
Your cache is probably stale. Please remove the entry
  igl_embree_LIB_DEPENDS
from the cache.
Creating target: igl::embree
CMake Error: Target igl_lim has dependency information when it shouldn't.
Your cache is probably stale. Please remove the entry
  igl_lim_LIB_DEPENDS
from the cache.
Creating target: igl::lim
CMake Error: Target igl_opengl has dependency information when it shouldn't.
Your cache is probably stale. Please remove the entry
  igl_opengl_LIB_DEPENDS
from the cache.
Creating target: igl::opengl
CMake Error: Target igl_opengl_glfw has dependency information when it shouldn't.
Your cache is probably stale. Please remove the entry
  igl_opengl_glfw_LIB_DEPENDS
from the cache.
Creating target: igl::opengl_glfw
Could NOT find Vulkan (missing:  VULKAN_LIBRARY VULKAN_INCLUDE_DIR) 
Using Win32 for window creation
CMake Error: Target igl_png has dependency information when it shouldn't.
Your cache is probably stale. Please remove the entry
  igl_png_LIB_DEPENDS
from the cache.
Creating target: igl::png
CMake Error: Target igl_tetgen has dependency information when it shouldn't.
Your cache is probably stale. Please remove the entry
  igl_tetgen_LIB_DEPENDS
from the cache.
Creating target: igl::tetgen
CMake Error: Target igl_triangle has dependency information when it shouldn't.
Your cache is probably stale. Please remove the entry
  igl_triangle_LIB_DEPENDS
from the cache.
Creating target: igl::triangle
CMake Error: Target igl_xml has dependency information when it shouldn't.
Your cache is probably stale. Please remove the entry
  igl_xml_LIB_DEPENDS
from the cache.
Creating target: igl::xml
Configuring incomplete, errors occurred!
See also "G:/DirectField/iglbuild/CMakeFiles/CMakeOutput.log".
See also "G:/DirectField/iglbuild/CMakeFiles/CMakeError.log".


but when i using blank tutorial the previous error show again.
![untitled01](https://user-images.githubusercontent.com/4311329/38768856-13a44a42-400f-11e8-8443-706259772673.png)

**Comment by jdumas** [comment]
Ok well, you need to delete your `CMakeCache.txt` and try again (be sure to uncheck the `LIBIGL_USE_STATIC_LIBRARY` *before* the configure/generate step).

**Comment by hadibeiki** [comment]
not working 
same error...

**Comment by hadibeiki** [comment]
i trry to install on another PC but i have same errors on GLFW...

![untitled](https://user-images.githubusercontent.com/4311329/38775288-c69e0b54-4093-11e8-9ef5-830b8f6b0794.png)

**Comment by jdumas** [comment]
Does this happen on the tutorials? Or the libigl-example-project? On your screenshot it doesn't look like you are building the tutorial. I won't be able to try on a Windows machine until next week, and I don't have a magic crystal ball to guess how to reproduce your error ...

**Comment by hadibeiki** [comment]
thank you very much for help me...im sorry for my comment it just for help ...and you are amazing...
for both of them i have same errors ....
i try to download LIBIGL again and see what happen.
thank you very much for answering me .

**Comment by jdumas** [comment]
Ok. The Windows build is only tested with the static mode on AppVeyor, because it is usually the one that poses problems. I will try later on a Windows machine and see if I can reproduce.

**Comment by hadibeiki** [comment]
i am so sorry 
i downloaded libigl once more and update Cmake to v3.10.3 and the build is success

![untitled05](https://user-images.githubusercontent.com/4311329/38780941-3519bc5e-40f3-11e8-858a-eaafba8eee78.png)

but another problem is when i debuging any of tutorial this error show:
![untitled06](https://user-images.githubusercontent.com/4311329/38780966-96f77042-40f3-11e8-88ed-c1ec95c754cd.png)

**Comment by jdumas** [comment]
This error is probably not libigl's fault. But wait so it means the compilation fails with an earlier version of CMake? This should work with CMake 3.1 or 3.2 already.

**Comment by hadibeiki** [comment]
> This error is probably not libigl's fault. But wait so it means the compilation fails with an earlier version of CMake? This should work with CMake 3.1 or 3.2 already.3.

i dont think so...
i think my first download of libigl is missing a file maybe...but i tried install first with Cmake 3.8
anyway i try to solve this small error and thank you for answer my question..

**Comment by jdumas** [comment]
Is it working now?

**Comment by hadibeiki** [comment]
yes...
and thank you very much
