### ISSUE TITLE
How to pick vertices

### ISSUE THREAD

**Issue by wujilingfeng** [libigl/libigl#750]
Thanks for your work!
Example 708 only show how to pick face.Could you offer detailed code?
When I create a class of EmbreeIntersector,it showed error.
Thank you very much!

**Comment by danielepanozzo** [comment]
The bc variable:
https://github.com/libigl/libigl/blob/3123b967c1e2cd8e9233937396c5736f2274b5e0/tutorial/708_Picking/main.cpp#L23

contains the barycentric coordinates of the picked point. The entry with the highest value corresponds to the closest vertex in the triangle.
