### ISSUE TITLE
glad results in undefined symbols on Mac OS for simple example

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#751]
If I replace the [libigl example project](https://github.com/libigl/libigl-example-project)'s main.cpp with this minimal example

```
#include <igl/opengl/create_shader_program.h>

int main()
{
  GLuint Fg_prog_id = igl::opengl::create_shader_program("","",{});
}
```

I get the following undefined symbol errors on Mac OS X:

```
[ 95%] Linking CXX executable example_bin
/usr/local/Cellar/cmake/3.10.2/bin/cmake -E cmake_link_script CMakeFiles/example_bin.dir/link.txt --verbose=1
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/example_bin.dir/main.cpp.o  -o example_bin -framework OpenGL glad/libglad.a glfw/src/libglfw3.a -framework Cocoa -framework IOKit -framework CoreFoundation -framework CoreVideo 
Undefined symbols for architecture x86_64:
  "_glad_glAttachShader", referenced from:
      igl::opengl::create_shader_program(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned int, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, unsigned int> > > const&, unsigned int&) in main.cpp.o
  "_glad_glBindAttribLocation", referenced from:
      igl::opengl::create_shader_program(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned int, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, unsigned int> > > const&, unsigned int&) in main.cpp.o
  "_glad_glCompileShader", referenced from:
      igl::opengl::load_shader(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned int) in main.cpp.o
  "_glad_glCreateProgram", referenced from:
      igl::opengl::create_shader_program(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned int, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, unsigned int> > > const&, unsigned int&) in main.cpp.o
  "_glad_glCreateShader", referenced from:
      igl::opengl::load_shader(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned int) in main.cpp.o
  "_glad_glDeleteShader", referenced from:
      igl::opengl::create_shader_program(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned int, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, unsigned int> > > const&, unsigned int&) in main.cpp.o
  "_glad_glDetachShader", referenced from:
      igl::opengl::create_shader_program(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned int, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, unsigned int> > > const&, unsigned int&) in main.cpp.o
  "_glad_glGetProgramInfoLog", referenced from:
      igl::opengl::create_shader_program(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned int, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, unsigned int> > > const&, unsigned int&) in main.cpp.o
  "_glad_glGetProgramiv", referenced from:
      igl::opengl::create_shader_program(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned int, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, unsigned int> > > const&, unsigned int&) in main.cpp.o
  "_glad_glGetShaderInfoLog", referenced from:
      igl::opengl::load_shader(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned int) in main.cpp.o
  "_glad_glGetShaderiv", referenced from:
      igl::opengl::load_shader(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned int) in main.cpp.o
  "_glad_glLinkProgram", referenced from:
      igl::opengl::create_shader_program(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned int, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, unsigned int> > > const&, unsigned int&) in main.cpp.o
  "_glad_glShaderSource", referenced from:
      igl::opengl::load_shader(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned int) in main.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [example_bin] Error 1
make[1]: *** [CMakeFiles/example_bin.dir/all] Error 2
make: *** [all] Error 2
```

This is strange because `libglad.a` contains these symbols  (revealed via `nm`) and the vanilla example `main.cpp` calls the Viewer which in turn calls MeshGL which calls `create_shader_program`, and links just fine. I haven't tested yet if this is happening on other build environments. I'm using 

```
Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
on Mac OS 10.13 and used  `cmake ../ -DLIBIGL_USE_STATIC_LIBRARY=Off -DCMAKE_BUILD_TYPE=Release` to create the build.

**Comment by alecjacobson** [comment]
I believe this is related to glad or how it's linked. If I replace glad with a straight OpenGL include in `include/igl/opengl/gl.h` with

```
//#include <glad/glad.h>
#include <OpenGL/gl3.h>
```
Then the example above links fine.

**Comment by jdumas** [comment]
This is strange. I just tried that on my archlinux and it works fine with both gcc and clang. This is the output of my `make VERBOSE=1` for the linker part:

```
[100%] Linking CXX executable example_bin
/usr/bin/cmake -E cmake_link_script CMakeFiles/example_bin.dir/link.txt --verbose=1
/usr/bin/clang++  -O3 -DNDEBUG  -rdynamic CMakeFiles/example_bin.dir/main.cpp.o  -o example_bin -lGL glad/libglad.a glfw/src/libglfw3.a -lrt -lm -ldl -lX11 -lpthread
```

Can you try manually with flags like `-ldl` or `-rdynamic`?
I really don't understand why the viewer would work, but not the example project, maybe some other lib is adding those flags privately to the viewer target.

**Comment by alecjacobson** [comment]
Hmm. The `-ldl` and `-rdynamic` flags didn't change anything.

It's weird. If I issue, e.g., 

    nm glad/libglad.a | grep _glad_glShaderSource

Then I see

    0000000000000008 C _glad_glShaderSource

but clang is not finding it when linking...

This kind of error reminds me a bit of linker order issues I'd have on linux, but I thought clang didn't suffer from that (and any order I try seems to fail...).

@danielepanozzo Can you confirm this issue on Mac+Clang ?

**Comment by jdumas** [comment]
Can you try to compile glad with `-DGLAD_GLAPI_EXPORT` and/or `-DGLAD_GLAPI_EXPORT_BUILD`? It should be useful only for shared versions of the library, so maybe something's afoot there.

**Comment by alecjacobson** [comment]
That didn't change anything, but this might help. I tried building everything manually (without cmake and without building glad as a library) and it worked:

```
LIBIGL=/usr/local/libigl/ clang++ -std=c++11 main.cpp -I$LIBIGL/include/ -I$LIBIGL/external/glad/include/ -c -o main.o
LIBIGL=/usr/local/libigl/ clang $LIBIGL/external/glad/src/glad.c -I $LIBIGL/external/glad/include/ -c -o glad.o
clang++ -o main main.o glad.o -framework OpenGL
```

If I mimic the cmake `ar` command to make glad static library, then it fails:

```
LIBIGL=/usr/local/libigl/ clang++ -std=c++11 main.cpp -I$LIBIGL/include/ -I$LIBIGL/external/glad/include/ -c -o main.o
LIBIGL=/usr/local/libigl/ clang $LIBIGL/external/glad/src/glad.c -I $LIBIGL/external/glad/include/ -c -o glad.o
ar qc libglad.a glad.o
clang++ -o main main.o libglad.a -framework OpenGL
```

(Same undefined symbol error as above).

`nm` outputs for glad.o and libglad.a are the same... (except for the `libglad.a(glad.o):` header). 

I'm not sure why clang would treat linking to these differently.

**Comment by jdumas** [comment]
Hmm this is really weird, I have no idea why this happens. This is starting to smell like Apple not being kosher with it's implementation of `ar`, as I seem to find pointers to [similar issues](https://stackoverflow.com/questions/30948807/static-library-link-issue-with-mac-os-x-symbols-not-found-for-architecture-x8) on SO.

I'll see if we can debug that on a macOS machine with others from our group at NYU (I'm pretty much the only one on Linux there).

**Comment by jdumas** [comment]
It worries me that we have to change this. I'm not exactly what it does to mess with the `CMAKE_${lang}_CREATE_STATIC_LIBRARY` variables. We can add it as a temporary workaround, but it seems a bit brittle and I'd like to understand why this fails in the first place (and also why it works with the viewer).

**Comment by jdumas** [comment]
Ok so I've done a bit of reading and found [this link](http://kwwidgets.org/Bug/view.php?id=10342) to be quite useful in understanding the problem.

Basically what happens is that symbols such as `glad_glCreateShader` are declared as `extern` in the .h (I assume these will be populated at runtime when we call `gladLoadGLLoader((GLADloadproc) glfwGetProcAddress)` in the viewer). Such uninitialized symbols in C are put in the COMMON section of the `libglad.a` archive file. It seems that on macOS, the default dehavior of `ar` is to not index those symbols (unless you run `ranlib -c libglad.a`). This is just speculation, you can probably check if the index of the archive with `nm -s libglad.a` contains the `glad_glCreateShader` symbol.

There are two workarounds suggested in the thread above:

1. Use `set(CMAKE_C_ARCHIVE_FINISH "<CMAKE_RANLIB> -c <TARGET>")` in the CMake script, to pass the `-c` option to `ranlib` and force it to include common symbols in the index of the `libglad.a` archive.

2. Compile the `glad` target with the `-fno-common` option. This basically tells the compiler to put the list of unitialized symbols directly into the data section of the `glad.o` object file. The "downside" is that you can no longer have duplicated symbols, they will clash (which I think in this case is totally ok). If this solution works, that would be the cleanest/more robust solution from the CMake point of view (i.e. no messing around with variables, just adding a target property).

**Comment by alecjacobson** [comment]
This is still an issue. Would it be easier to somehow disable glad entirely on macos ? It doesn't appear to be necessary.

**Comment by jdumas** [comment]
FWIW this seems to be related to https://github.com/libigl/libigl-example-project/issues/33 (which I explained in more details [later in the thread](https://github.com/libigl/libigl-example-project/issues/33#issuecomment-1008171774)). Not sure I would recommend disabling glad entirely on macOS.

**Comment by alecjacobson** [comment]
Yes, that seems to be hitting the same issue and related to the flags discussed above. So what's the solution? Changing the libtool flags in cmake for glad?
I'm not convinced we need glad on mac os though? What's the value it adds there?

**Comment by alecjacobson** [comment]
It sounded like earlier, Jermie you preferred the `-fno-common` option. Would that also solve https://github.com/libigl/libigl-example-project/issues/33 ?

**Comment by alecjacobson** [comment]
That makes sense. On the other hand, glad itself seems broken/causing issues. So it seems like it's a question of whether we have a different code path in cmake or in the C++. If it's only in cmake, it makes it less clear how to use the code outside of cmake.

**Comment by alecjacobson** [comment]
I'm observing the issue in static library mode with cmake.

**Comment by jdumas** [comment]
Hmm then it's likely a different issue from https://github.com/libigl/libigl-example-project/issues/33. Is the MWE example in your first post still a valid way to reproduce the problem? Now that I have a MacBook I can probably take a closer look on my machine.

We could also try another loader, e.g. in Lagrange we use [gl3w](https://github.com/adobe/lagrange-gl3w). It may have the same issues as glad though, if that's an OpenGL limitation.

**Comment by alecjacobson** [comment]
yeah, the example above still hits this issue (just checked in static library mode, too).

**Comment by alecjacobson** [comment]
Thanks. What's the role of glad on Macs?

**Comment by jdumas** [comment]
Well, this ensures we're using the same version of OpenGL on all platforms, loaded with the same cross-platform code. We're using OpenGL 3.3 for now in the viewer, but you could technically use 4.1 even on macOS. Why are you asking now specifically? :)
