### ISSUE TITLE
compile error on tutorial/609_Boolean

### ISSUE THREAD

**Issue by 461353349** [libigl/libigl#755]
Can someone help me? Thanks.

\libigl\include\igl\copyleft\cgal\SelfIntersectMesh.h:831: error: C2780: “void igl::unique(const Eigen::DenseBase<Derived> &,Eigen::PlainObjectBase<DerivedF> &)”: 应输入 2 个参数，却提供了 4 个

**Comment by jdumas** [comment]
Jeez, can't you be more specific?

- What OS are you using?
- Are you compiling in 64bit?
- Can you compile the tutorial and example project?
- Are you compiling in static mode?

We don't have a magic crystal ball, and certainly cannot read error messages in Chinese (not all of us at least).

**Comment by 461353349** [comment]
It is my fault. I should use CGAL 4.7.
