### ISSUE TITLE
How to extend MeshGL with a customized shader?

### ISSUE THREAD

**Issue by TerranRush** [libigl/libigl#756]
It seems I have to directly modify MeshGL.h and MeshGL.cpp to add a customized shader, e.g. a depth map. So my question is: If I don't wanna modify the library sources, is there any convenient way to achieve this extension?

Inheritance seems also not possible, because MeshGL is composed in ViewerData as an object, not a pointer or reference.

**Comment by jdumas** [comment]
This was discussed in #657, but the example needs to be adapted for the new viewer, and possibly put in a tutorial. The new MeshGL structure now compiles its shaders in a lazy fashion, so the thread above doesn't apply directly. @alecjacobson do you have any suggestions?

**Comment by alecjacobson** [comment]
@TerranRush It is not necessary to edit the source of MeshGL. You'll just need to compile the shader after initializing the viewer (see the aforementioned #657).

**Comment by TerranRush** [comment]
Thank you guys for the prompt reply, that's clear.
