### ISSUE TITLE
Runtime error in tutorial Example 607

### ISSUE THREAD

**Issue by majia67** [libigl/libigl#758]
I use the latest version of libigl and have updated its submodules. The build is successful, but an error is raised when the example starts to execute:

> The code execution cannot proceed because igl_stb_image.dll was not found. Reinstalling the program may fix this problem.

I guess there is a bug in the CMakeLists.txt file associated with stb_image. Could someone take a look at this as I need to use PNG handling?

Testing environment:
OS: Windows 10 x64, 1709
IDE: Visual Studio Community 2017, 15.6.7
Build: x64 Release

**Comment by jdumas** [comment]
Can you try removing the `SHARED` from [this line](https://github.com/libigl/libigl/blob/a16f338ca2b0781a34bdd5dcc8ef7447ffa093b6/external/stb_image/CMakeLists.txt#L4) and see if it helps?

**Comment by majia67** [comment]
Thanks, @jdumas ! Removing the `SHARED` works for me!

**Comment by majia67** [comment]
@jdumas Do you think I should submit a pull request to fix this bug?
