### ISSUE TITLE
SignedDistanceType

### ISSUE THREAD

**Issue by irenji** [libigl/libigl#759]
Hi.

I try to calculate distance of a point cloud to mesh. my input mesh was **non-watertight and non-manifold with self-intersect**.

I test two Type for computing signed distance : 
1.SIGNED_DISTANCE_TYPE_PSEUDONORMAL.
2.SIGNED_DISTANCE_TYPE_WINDING_NUMBER

the result was same without any error, also PSEUDONORMAL was very fast. So now I use PSEUDONORMAL for non-watertight mesh.

In igl tutorial I see : 
The pseudo-normal test (see also igl::pseudonormal_test) assumes the input mesh is a watertight (closed, non-self-intersecting, manifold) mesh.
But it work for me very fast and without error .

**Comment by alecjacobson** [comment]
Since _signed_ distance won't really make sense on your example you can just use `point_mesh_squared_distance`
