### ISSUE TITLE
Where is the latest stable release

### ISSUE THREAD

**Issue by huxingyi** [libigl/libigl#762]
Very cool and clean project, I am interested in using it in my 3D modeling software to do the uv-unwrapping, however, I couldn't find any release or version tag. Is clone the master branch the only way?

**Comment by jdumas** [comment]
Right now yes. I've been nagging @danielepanozzo to add version tags in the github to mark breaking changes in the API (e.g. the new viewer/ui), but it hasn't happened yet. We are usually pretty careful before merging new code into the main branch, so it should be pretty safe to stick to the main branch. But of course we don't have unit tests for everything, so mistakes can be made.

**Comment by huxingyi** [comment]
Thanks for your clear answer, I will follow the master branch.
