### ISSUE TITLE
[non-BUG] The type of `side` in `offset_surface()`

### ISSUE THREAD

**Issue by riaqn** [libigl/libigl#763]
This is just a question not a bug, but I can't find anywhere else to post it.

So the signature of `offset_surface()` is 
```
template <
      typename DerivedV,
      typename DerivedF,
      typename isolevelType,
      typename DerivedSV,
      typename DerivedSF,
      typename DerivedGV,
      typename Derivedside,
typename DerivedS>
void offset_surface(
      const Eigen::MatrixBase<DerivedV> & V,
      const Eigen::MatrixBase<DerivedF> & F,
      const isolevelType isolevel,
      const typename Derivedside::Scalar s,
      const SignedDistanceType & signed_distance_type,
      Eigen::PlainObjectBase<DerivedSV> & SV,
      Eigen::PlainObjectBase<DerivedSF> & SF,
      Eigen::PlainObjectBase<DerivedGV> & GV,
      Eigen::PlainObjectBase<Derivedside> & side,
      Eigen::PlainObjectBase<DerivedS> & S);
}
```
Can someone tell me what the type of `side` should be? And in general, how to infer the type that depends on the template parameter?

**Comment by alecjacobson** [comment]
Double.

In general if it sounds like it should be an array of real
numbers/fractional values then use double; if it sounds like it should be
an array of indices use int

**Comment by riaqn** [comment]
Hi @alecjacobson Thanks for the reply. I tried both `int` and `double` but neither works. 

Maybe I ask why it should be `int` when it sounds like `VectorXi`?

**Comment by alecjacobson** [comment]
oh sorry. Yeah I meant double or int in the template argument of the Eigen
matrices: Eigen::Matrix<double, ...> or  Eigen::Matrix<int, ...>

**Comment by riaqn** [comment]
Thanks for the reply. But I'm not familiar with C++ nor Eigen. Can you tell me the type I should use here for `side`?

**Comment by alecjacobson** [comment]
Eigen::VectorXi

**Comment by riaqn** [comment]
I actually tried that, and here is the error:
```
In file included from /usr/include/eigen3/Eigen/Core:347:0,
                 from /home/riaqn/codes/libigl/include/igl/AABB.h:13,
                 from /home/riaqn/codes/libigl/include/igl/signed_distance.h:12,
                 from /home/riaqn/codes/libigl/include/igl/copyleft/offset_surface.h:4,
                 from /home/riaqn/codes/cxx/offset.cxx:1:
/usr/include/eigen3/Eigen/src/Core/DenseCoeffsBase.h: In instantiation of ‘Eigen::DenseCoeffsBase<Derived, 0>::CoeffReturnType Eigen::DenseCoeffsBase<Derived, 0>::operator[](Eigen::Index) const [with Derived = Eigen::Matrix<double, -1, -1>; Eigen::DenseCoeffsBase<Derived, 0>::CoeffReturnType = const double&; Eigen::Index = long int]’:
/home/riaqn/codes/libigl/include/igl/copyleft/marching_cubes.cpp:129:19:   required from ‘MarchingCubes<Derivedvalues, Derivedpoints, Derivedvertices, DerivedF>::MarchingCubes(const Eigen::PlainObjectBase<Derived>&, const Eigen::PlainObjectBase<DeriveddblA>&, unsigned int, unsigned int, unsigned int, Eigen::PlainObjectBase<DerivedBC>&, Eigen::PlainObjectBase<DerivedD>&) [with Derivedvalues = Eigen::Matrix<double, -1, -1>; Derivedpoints = Eigen::Matrix<double, -1, -1>; Derivedvertices = Eigen::Matrix<double, -1, -1>; DerivedF = Eigen::Matrix<int, -1, -1>]’
/home/riaqn/codes/libigl/include/igl/copyleft/marching_cubes.cpp:237:74:   required from ‘void igl::copyleft::marching_cubes(const Eigen::PlainObjectBase<Derived>&, const Eigen::PlainObjectBase<DeriveddblA>&, unsigned int, unsigned int, unsigned int, Eigen::PlainObjectBase<DerivedBC>&, Eigen::PlainObjectBase<DerivedD>&) [with Derivedvalues = Eigen::Matrix<double, -1, -1>; Derivedpoints = Eigen::Matrix<double, -1, -1>; Derivedvertices = Eigen::Matrix<double, -1, -1>; DerivedF = Eigen::Matrix<int, -1, -1>]’
/home/riaqn/codes/libigl/include/igl/copyleft/offset_surface.cpp:55:32:   required from ‘void igl::copyleft::offset_surface(const Eigen::MatrixBase<Derived>&, const Eigen::MatrixBase<U>&, isolevelType, typename Derivedside::Scalar, const igl::SignedDistanceType&, Eigen::PlainObjectBase<DerivedD>&, Eigen::PlainObjectBase<DerivedsqrD>&, Eigen::PlainObjectBase<DerivedL>&, Eigen::PlainObjectBase<Derivedb>&, Eigen::PlainObjectBase<DerivedS>&) [with DerivedV = Eigen::Matrix<double, -1, -1>; DerivedF = Eigen::Matrix<int, -1, -1>; isolevelType = double; DerivedSV = Eigen::Matrix<double, -1, -1>; DerivedSF = Eigen::Matrix<int, -1, -1>; DerivedGV = Eigen::Matrix<double, -1, -1>; Derivedside = Eigen::Matrix<int, -1, 1>; DerivedS = Eigen::Matrix<double, -1, -1>; typename Derivedside::Scalar = int]’
/home/riaqn/codes/cxx/offset.cxx:17:138:   required from here
/usr/include/eigen3/Eigen/src/Core/DenseCoeffsBase.h:160:7: error: static assertion failed: THE_BRACKET_OPERATOR_IS_ONLY_FOR_VECTORS__USE_THE_PARENTHESIS_OPERATOR_INSTEAD
       EIGEN_STATIC_ASSERT(Derived::IsVectorAtCompileTime,
       ^
```

**Comment by alecjacobson** [comment]
Can you paste the full code snippet around where you're calling
offset_surface?

-Alec

**Comment by riaqn** [comment]
sure. 
```
#include <igl/copyleft/offset_surface.h>
#include <igl/signed_distance.h>

#include <igl/readOFF.h>
#include <igl/writeOFF.h>


int main(int argc, char *argv[]) {
  Eigen::MatrixXd V;
  Eigen::MatrixXi F;
  igl::readOFF(argv[1], V, F);


  Eigen::MatrixXd SV, GV, S;
  Eigen::MatrixXi SF;
  Eigen::VectorXi side;
  igl::copyleft::offset_surface(V, F, std::stod(std::string(argv[3]), NULL), 1024, igl::SIGNED_DISTANCE_TYPE_DEFAULT, SV, SF, GV, side, S);
  igl::writeOFF(argv[2], SV, SF);
}

```

**Comment by alecjacobson** [comment]
Ah. Probably values[...] in marching_cubes.cpp should be replaced with
values( ...)

But in the meantime I think you can fix this by making your S of type
VectorXd instead of MatrixXd

**Comment by riaqn** [comment]
Thanks! it works now, although it triggers SIGSEGV when `offset()`.

**Comment by alecjacobson** [comment]
To debug this we'll likely need your exact input data and arguments.

**Comment by mabl** [comment]
Hi @alecjacobson ,

I have tried the same code as @riaqn, and get:

```
example_bin.exe cube.off cube_offset.off 0.1
Assertion failed: index >= 0 && index < size(), file c:\users\user\development\libigl\external\eigen\eigen\src\core\densecoeffsbase.h, line 394
```

Probably the same issue as riaqn saw? cube.off is from the tutorial test data. But the same happens on other meshes, too.

**Comment by aseverino** [comment]
> Hi @alecjacobson ,
> 
> I have tried the same code as @riaqn, and get:
> 
> ```
> example_bin.exe cube.off cube_offset.off 0.1
> Assertion failed: index >= 0 && index < size(), file c:\users\user\development\libigl\external\eigen\eigen\src\core\densecoeffsbase.h, line 394
> ```
> Probably the same issue as riaqn saw? cube.off is from the tutorial test data. But the same happens on other meshes, too.

Hello all,

I'm facing exactly the same problem.

**Comment by BruegelN** [comment]
@riaqn, @mabl & @aseverino maybe it's already to late BUT:
It seems like `Eigen::VectorXi side;` causes this issue.
For me `Eigen::Vector3i side;` worked.
And as [the comment above offset_surface()](https://github.com/libigl/libigl/blob/master/include/igl/copyleft/offset_surface.h#L25) states **side** holds the number grid cells in every direction (i.e. 100x200x300 voxels) so `Eigen::Vector3i` is quite reasonable.
The error message is a sanity check which fails for dynamic/ not pre-initialised types ( i.e. `Eigen::VectorXi`).
I've tested it with current master & dev branch and the default build config (`mkdir build && cd build && cmake ../ && make` ) and it worked.


Note: The static build still does not seem to work out due to missing template initialization. I might have a look into that in the future, for now just use default header-only mode.

**Comment by mabl** [comment]
Hi @BruegelN ,

thank you for looking into this. Unfortunately, it still does not work for me even after changing to `Vector3i` and preinitializing it. If you have it, could you post an example which works for you?

**Comment by BruegelN** [comment]
Hi @mabl,

glad that it worked for you!
Yeah using 1024 cells on my smaller computer with only 12GiB of memory I get the following error:
`terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc` (only runs on my workstation more RAM). 
Somewhere in the neighbourhood of 200-500 grid cells along longest side (`const typename Derivedside::Scalar s`) was the best trade off between resolution, runtime and memory for me.

**Comment by riaqn** [comment]
I'm not longer using libigl so if everyone is happy I'm closing the issue. Feel free to re-open it if you need.

**Comment by JLYang123** [comment]
try Eigen::RowVector3i
