### ISSUE TITLE
Delaunay Triangulation

### ISSUE THREAD

**Issue by arvigj** [libigl/libigl#766]
Is there an example of Delaunay triangulation working? I was not able to get a list of faces here, whereas Scipy Delaunay triangulation does generate one. The following is the list of vertices and faces generated by scipy for reference.
V << 339, 205,
325, 208,
327, 209,
241, 255,
275, 320,
350, 345,
197, 479,
208, 490,
309, 325,
392, 363,
407, 411,
377, 414,
474, 428,
425, 431,
148, 527,
163, 551,
152, 553,
206, 557,
263, 562,
225, 662,
226, 260,
401, 302,
294, 332,
272, 455,
211, 692,
220, 259,
346, 343,
277, 335,
285, 335,
407, 346,
452, 399,
240, 264,
241, 332,
256, 371,
251, 430,
313, 372,
302, 316,
176, 636;

F << 24, 19, 12,
            19, 18, 12,
            15, 16, 14,
            19, 17, 18,
            34, 33, 35,
            30, 21, 12,
            9, 30, 10,
            18, 13, 12,
            13, 30, 12,
            30, 13, 10,
            37, 17, 19,
            17, 37, 15,
            15, 37, 16,
            37, 19, 24,
            23, 34, 35,
            1, 3, 25,
            33, 28, 35,
            28, 22, 35,
            22, 28, 4,
            3, 20, 25,
            20, 32, 25,
            32, 31, 4,
            31, 20, 3,
            20, 31, 32,
            11, 9, 10,
            11, 23, 35,
            13, 11, 10,
            11, 13, 18,
            23, 11, 18,
            30, 29, 21,
            9, 29, 30,
            23, 7, 34,
            17, 7, 18,
            7, 23, 18,
            7, 15, 14,
            7, 17, 15,
            21, 2, 0,
            2, 1, 0,
            27, 32, 4,
            28, 27, 4,
            32, 27, 33,
            27, 28, 33,
            5, 29, 9,
            11, 5, 9,
            5, 26, 21,
            29, 5, 21,
            5, 11, 35,
            26, 5, 35,
            7, 6, 34,
            34, 6, 33,
            6, 32, 33,
            6, 7, 14,
            25, 6, 14,
            32, 6, 25,
            36, 2, 21,
            36, 22, 4,
            31, 36, 4,
            36, 31, 3,
            1, 36, 3,
            2, 36, 1,
            26, 8, 21,
            8, 36, 21,
            36, 8, 22,
            22, 8, 35,
            8, 26, 35;

**Comment by alecjacobson** [comment]
Can you post a code snippet of what you tried and describe the output? (e.g., Is the output face list empty?)

**Comment by arvigj** [comment]
Eigen::MatrixXd V_S; //V_S has been populated as above
    Eigen::MatrixXi F;

    typedef Eigen::MatrixXd::Scalar Scalar;
    auto orient2D = [] (const Scalar pa[2], const Scalar pb[2], const Scalar pc[2]) {
        std::cout << pa[0] << "\t" << pa[1] << std::endl;
        std::cout << pb[0] << "\t" << pb[1] << std::endl;
        std::cout << pc[0] << "\t" << pc[1] << std::endl;
        std::cout << std::endl;
        Eigen::Vector3d a,b;
        a << pa[0] - pb[0], pa[1] - pb[1], 0;
        b << pc[0] - pb[0], pc[1] - pb[1], 0;
        double c = a.cross(b)(2);
        if (c> 0) {
            return 1;
        } else if (c< 0) {
            return -1;
        } else {
            return 0;
        }
    };


    auto incircle = [] (const Scalar pa[2], const Scalar pb[2], const Scalar pc[2], const Scalar pd[2]) {
        Eigen::Matrix4d mat;
        mat.col(0) << std::sqrt(pd[0]*pd[0]+pd[1]*pd[1]), std::sqrt(pa[0]*pa[0]+pa[1]*pa[1]),std::sqrt(pb[0]*pb[0]+pb[1]*pb[1]),std::sqrt(pc[0]*pc[0]+pc[1]*pc[1]);
        mat.col(1) << pd[0], pa[0], pb[0], pc[0];
        mat.col(2) << pd[1], pa[1], pb[1], pc[1];
        mat.col(3) << 1,1,1,1;
        double d = mat.determinant();
        if (d > 0) {
            return -1;
        } else if (d < 0) {
            return 1;
        } else {
            return 0;
        }
    };

    igl::delaunay_triangulation(V_S, orient2D, incircle, F);

The above code throws the following error
`igl::delaunay_triangulation(const Eigen::PlainObjectBase<DerivedV>&, Orient2D, InCircle, Eigen::PlainObjectBase<DerivedF>&)::<lambda(std::size_t)> [with DerivedV = Eigen::Matrix<double, -1, -1>; Orient2D = transformations(cv::Mat, cv::Mat, cv::Mat, Eigen::MatrixXd)::<lambda(const Scalar*, const Scalar*, const Scalar*)>; InCircle = transformations(cv::Mat, cv::Mat, cv::Mat, Eigen::MatrixXd)::<lambda(const Scalar*, const Scalar*, const Scalar*, const Scalar*)>; DerivedF = Eigen::Matrix<int, -1, -1>; std::size_t = long unsigned int]: Assertion `f1 != f2' failed.`

**Comment by alecjacobson** [comment]
I won't have a chance to look at this in depth for a bit. But my first guess is that your orient2D and incircle implementations are not robust to non-general position inputs and susceptible to floating point errors. you could grab Shewchuck's robust predicates or If you're OK with using CGAL then you could try `igl::copyleft::cgal::delaunay_triangulation`.

**Comment by robertliebo** [comment]
i came here looking for am working example of Delaunay triangulation (preferably purely CGAL-free) as well. i see that pull request #1163 integrated shewchuck's predicates via #include <igl/predicates/predicates.h> and via external #include <predicates.h> (which is libigl/external/predicates/predicates.h).

it's just not clear to me how to call igl::delaunay_triangulation() using those.

`igl::delaunay_triangulation(V, igl::predicates::orient2d, igl::predicates::incircle, F);` gives me compiler error ...`libigl/igl/delaunay_triangulation.cpp:23:22: Candidate template ignored: couldn't infer template argument 'Orient2D'`

**Comment by mgaillard** [comment]
Hello,

Today I faced the same problem as you. It seems that the types in igl::predicates::orient2d and igl::predicates::incircle are not directly compatible with igl::delaunay_triangulation. I just wrote a wrapper and it is working for my use case. If anybody finds a better way to do it, I am open to suggestions.

`
int orient2dPredicates(const double* pa, const double* pb, const double* pc)
{
    const Eigen::Vector2d a(pa[0], pa[1]);
    const Eigen::Vector2d b(pb[0], pb[1]);
    const Eigen::Vector2d c(pc[0], pc[1]);

    const auto result = igl::predicates::orient2d<Eigen::Vector2d>(a, b, c);

    if (result == igl::predicates::Orientation::POSITIVE) {
        return 1;
    } else if (result == igl::predicates::Orientation::NEGATIVE) {
        return -1;
    } else {
        return 0;
    }
}

int inCirclePredicates(const double* pa, const double* pb, const double* pc, const double* pd)
{
    const Eigen::Vector2d a(pa[0], pa[1]);
    const Eigen::Vector2d b(pb[0], pb[1]);
    const Eigen::Vector2d c(pc[0], pc[1]);
    const Eigen::Vector2d d(pd[0], pd[1]);

    const auto result = igl::predicates::incircle(a, b, c, d);

    if (result == igl::predicates::Orientation::INSIDE) {
        return 1;
    } else if (result == igl::predicates::Orientation::OUTSIDE) {
        return -1;
    } else {
        return 0;
    }
};

// How I call the delaunay triangulation function
Eigen::MatrixXd vertices(numberOfVertices, 2);
Eigen::MatrixXi faces;
igl::delaunay_triangulation(vertices, orient2dPredicates, inCirclePredicates, faces);
`

Best regards,

**Comment by robertliebo** [comment]
i ended up in a mix between your (@mgaillard) [approach](https://github.com/libigl/libigl/issues/766#issuecomment-587972372) and @arvigj 's [approach](https://github.com/libigl/libigl/issues/766#issuecomment-386817323) :

```
const auto &orient2d_predicates = [](const float * pa, const float * pb, const float * pc) {
    return igl::predicates::orient2d(Eigen::Vector2f {pa[0], pa[1]}, Eigen::Vector2f {pb[0], pb[1]}, Eigen::Vector2f {pc[0], pc[1]});
};
const auto &incircle_predicates = [](const float * pa, const float * pb, const float * pc, const float * pd) {
    return igl::predicates::incircle(Eigen::Vector2f {pa[0], pa[1]}, Eigen::Vector2f {pb[0], pb[1]}, Eigen::Vector2f {pc[0], pc[1]}, Eigen::Vector2f {pd[0], pd[1]});
};
igl::delaunay_triangulation(V, orient2d_predicates, incircle_predicates, F);
```

but with that i had to modify `libigl/igl/is_delaunay.cpp` and `libigl/igl/lexicographic_triangulation.cpp` to cast `orientation` from `igl::predicates::Orientation` to `short`.
still all those conversions are insane, this can only be a workaround, not a solution.

**Comment by alecjacobson** [comment]
[`igl::predicates::delaunay_triangulation`](https://libigl.github.io/dox/namespaceigl_1_1predicates.html#a7edd289c72535b2014622b5fc55c397e) works fine on the original example above.
