### ISSUE TITLE
Is there any example of mesh segmentation?

### ISSUE THREAD

**Issue by FrankEscobar** [libigl/libigl#770]
I've been playing with it a little and seems to be really nice but I miss any implemented segmentation algorightms, there are lots of them like Random Cuts, Shape Diameter Function (the one used in CGAL), Hierarchical Mesh Segmentation and so.

Is there any example of anyone of them using IGL? thank you in advance!

**Comment by alecjacobson** [comment]
We have a basic implementation of Shape Diameter Function (without the segmentation part though). Many of the segmentation algorithms can be implemented by building a sparse matrix and then feeding it into graph-cut/randomized cuts/consensus segmentation. We don't have these in libigl but there's some code floating around. I'll try to have my grad student Derek who looked at this add a pointer.

**Comment by HTDerekLiu** [comment]
Besides what Alec has mentioned, I also like this segmentation algorithm "Robust Region Detection via
Consensus Segmentation of Deformable Shapes" and you can find the implementation here: https://vision.in.tum.de/members/rodola/code

**Comment by FrankEscobar** [comment]
Thank you both but @HTDerekLiu I think that we are speaking about different kind of segmentation Shape Diameter, Random Walks, Fitting primitives and so are related to segment a mesh into subparts nothing to do with object recognition.

**Comment by HTDerekLiu** [comment]
@FrankEscobar Yes, the method can segment a mesh into subparts. 
It uses shape signatures to represent each vertex, runs clustering algorithms multiple times with different initializations on a mesh, then those clustering results will vote for final segments. You can see the teaser image: http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.454.4342&rep=rep1&type=pdf. Hope this is related to your problem :)

**Comment by FrankEscobar** [comment]
Thank you @HTDerekLiu  I'll try (without so many hope) to implement this one http://efpisoft.sourceforge.net/

**Comment by Bennyyy27** [comment]
Hi all,
I am currently really interested in the topic of segmentation and thus I am coming to the same question as mentioned in the issue. 
Is there in the meantime any implementation of these shape segmentation algorithms in libigl?

**Comment by Juyi9640** [comment]
Hi all,
recently im also trying to find some methods about mesh segmentation, and find two algorithms from CGAL that really helpful: CGAL 5.2 - Shape Detection and CGAL 5.2 - Triangulated Surface Mesh Approximation.

**Comment by jeannotes** [comment]
@FrankEscobar  did you try that? any rsults? o

**Comment by r03ert0** [comment]
this is not as fancy as the CGAL algorithm, but it worked quite nicely for me. I just used sklearn's spectral clustering on the adjacency matrix of the mesh. Code:

```python
import igl
import meshplot as mp
from sklearn.cluster import spectral_clustering
sv, sf = igl.read_triangle_mesh("mymesh.ply")
A = igl.adjacency_matrix(sf)
labels = spectral_clustering(A)
mp.plot(sv, sf, labels)
```

**Comment by jeannotes** [comment]
@r03ert0  may I ask that waht is your mesh, if this is a keyboard, will this method be ok?

**Comment by r03ert0** [comment]
@jeannotes : my meshes are brains of ferrets... the simple spectral clustering nicely segments the two brain hemispheres, the olfactory bulbs, and the rest.
