### ISSUE TITLE
Is there an available way or function to quickly get the 2-ring neighbors of a boundary loop?

### ISSUE THREAD

**Issue by chaofeng2007** [libigl/libigl#774]
Hello,

I had adopted the `igl::boundary_loop(inputF, inputLoop)` to get the boundary vertices, where inputF is the triangle index, inputLoop is the boundary vertices index.

My question is:
I want to quickly obtain the 1-ring or 2-ring neighbors of the computed boundary vertices.  Is there an available function in libigl can deal with this issue?

Thanks in advance.

**Comment by jmespadero** [comment]
There is a clever way to do that....

1. Call igl::boundary_loop(inputF, inputLoop) and convert inputLoop from a list of indexes to a isBoundary sparse vector of 

2. Compute the numVertex xnumVertex sparse matrix with the vertex adjacency matrix of your mesh.

3. Compute n-ring boundaries by as:

n_ring_boundary = adjacencyMatrix^n * isBoundary

**Comment by chaofeng2007** [comment]
@jmespadero 

Thank you for your reply.

I am sorry I still have a little doubt about your solution, since I am not very familiar with `libigl`. 

1. Call `igl::boundary_loop(inputF, inputLoop)`, then get the boundary indexes`inputLoop`. How to convert the `inputLoop` from a list of indexes to a isBoundary sparse vector? Can you post the specific command here?

2. Concerning the vertex adjacency of the input mesh, I call the following commands:
```c++
vector<std::vector<int>> VF, VFi;
VectorXd Vdummy(originalF.maxCoeff() + 1, 1);
igl::vertex_triangle_adjacency(Vdummy, originalF, VF, VFi);
// VF saves the adjacency triangles of each vertex in inputV.
```
So, how to compute the `numVertex * numVertex` sparse matrix?  Can you post the specific command here?

Thank you very much.

**Comment by jmespadero** [comment]
It is awkward to me, but I am contrary to paste that code here.

My reason is that libIGL is being used in many universities as material for class exercises. I feel that pasting such code will invalidate a very nice exercise. 

So, instead... I will try to explain again the solution. 

1. isBoundary is an `Eigen::SparseVector<int>` that contains 1 in the positions that are in the boundary. So, you have to iterate the inputLoop vector and, for each index found there, you insert one element in that position with `isBoundary.coeffRef(index)=1;`

2. adjacencyMatrix is an  `Eigen::SparseMatrix<int>` that contains 1 in the position (i,j) if vertex i is neighbor of vertex j. You can build that matrix iterating the triangles and inserting 6 "ones" in your matrix for each triangle. See [Filling a sparse matrix](https://eigen.tuxfamily.org/dox/group__TutorialSparse.html#title3) for an example of doing this efficiently.

After that... You can use the adjacencyMatrix object to ask for the neighbours of a vertex list, just multiplying the matrix with a vector that contains ones in the positions of those vertex. And we just built the isBoundary vector that way...

**Comment by jdumas** [comment]
Well you can also use directly the function [`igl::adjacency_matrix()`](https://github.com/libigl/libigl/blob/master/include/igl/adjacency_matrix.h). If you are not comfortable with matrices, another option is to use the vertex-adjacency graph with the [`igl::adjacency_list()`](https://github.com/libigl/libigl/blob/master/include/igl/adjacency_list.h) function.

**Comment by chaofeng2007** [comment]
@jmespadero @jdumas 

Thank you very much.
