### ISSUE TITLE
have igl::decimate return map from old to new vertices (feature request)

### ISSUE THREAD

**Issue by evouga** [libigl/libigl#775]
Right now igl::decimate returns a mapping from decimated vertex id to original vertex id. This is not as useful as the opposite mapping---from old vertex id to decimated vertex id---since the decimation process is many-to-one, and it can be useful (when writing projection operators e.g.) to know *all* of the vertices that were merged together during edge collapse into a coarse mesh vertex.

**Comment by alecjacobson** [comment]
This would be a nice feature to expose at some point. Right now you could do it without changing the libigl code by _capturing_ an array that tracks this after each successful collapse in a customized `stopping_condition` function (which you could copy, e.g., from `decimate` or `qslim`).
