### ISSUE TITLE
In ViewerData, per-face-corner normals incorrectly take precedence over per-vertex attributes

### ISSUE THREAD

**Issue by nussetorten** [libigl/libigl#777]
Consider a mesh on which we've computed per-vertex (`N_per_vertex`) and per-corner normals (`N_per_corner`).

```
// viewer is instance of igl::opengl::glfw::Viewer
viewer.data().set_normals(N_per_corner); // populates ViewerData::F_normals, 3*#F normals
viewer.data().set_normals(N_per_vertex); // populates ViewerData::V_normals, #V normals
```

In `ViewerData::updateGL()`, `per_corner_normals` evaluates to `true` and `MeshGL::V_normals_vbo` is populated with per-face-corner data, not the more-recently-specified per-vertex data.

**Comment by nussetorten** [comment]
Is it the author's intent that we be able to toggle between the per-face and per-vertex attributes in the viewer? Or is the viewer simply meant to upscale the vertex count when face/corner data is supplied?

**Comment by danielepanozzo** [comment]
The viewer is designed to be used with only one type of property at a time. The typical workflow is to clear a mesh, send a new geometry, and its set of attributes (either on faces,vertices,corners). It would be nice to add options to switch between all of them consistently, but I am not sure of how useful this will be, it seems a pretty rare scenario.

**Comment by jdumas** [comment]
That being said, there is one issue with the current design: for a mesh with the same number of faces as the number of vertices, it becomes ambiguous to determine which is which based on the size alone ... This happened to me a few times, and I don't know if we want to do anything about it (what I did is add a dummy vertex to be able to set one and not the other ...).

**Comment by alecjacobson** [comment]
This should only happen for very small or poorly triangulated meshes where
per vertex won’t make much since. So perhaps we just need to make sure the
default is per face in this case

**Comment by nussetorten** [comment]
I agree with @danielepanozzo, the use case described is rare.  I think the correct behavior should be "last specified, first displayed" for each attribute.

As for the ambiguous case, we could at least generate a warning when #F == #V...

**Comment by jdumas** [comment]
It is possible in 2D.

**Comment by avaxman** [comment]
You need to have O(F) boundary loops... 

(BTW #V~=#F is the standard in quad meshes)

**Comment by jdumas** [comment]
Yes I know, but it already happened to me before =).
A pretty rare occurrence for sure, but it *can* happen.
