### ISSUE TITLE
compound obj "separation"

### ISSUE THREAD

**Issue by giordi91** [libigl/libigl#78]
Hi there, I am using the lib to load an obj, if I load an obj containing two meshes (in this case two cubes), if I have generic meshes like I plan to do there is no way for me to know where one mesh ends and the other begins. The reason why I need that is mostly for applying different textures.
Is there a way to achieve this result? basically getting multiple buffers out of the function.

M.

**Comment by alecjacobson** [comment]
Not sure what you mean by “multiple buffers”. But you can use
igl/facet_components.h or igl/boost/connected_components.h to identify
connected components of your meshes.
​

**Comment by giordi91** [comment]
Sorry I said buffer because I use the loaded array as buffers for opengl.
Basically what I need is being able to distinguish between different meshes inside the obj,
Being able to know that I can slice the array and handle differently the two arrays.
Example if I have two meshes for a total of 200 vertices, I need a way to know that for example from 0 to 123 vertices is the first mesh from 124 to n-1 is the second mesh.

I am gonna have a look at the facet_components.h
