### ISSUE TITLE
Question on Enum naming convention

### ISSUE THREAD

**Issue by jiangzhongshi** [libigl/libigl#781]
In the style guidelines, here is the convention for enum
```
namespace igl
{
  enum SolverStatus
  {
    // Good
    SOLVER_STATUS_CONVERGED = 0,
    // OK
    SOLVER_STATUS_MAX_ITER = 1,
    // Bad
    SOLVER_STATUS_ERROR = 2,
    NUM_SOLVER_STATUSES = 3,
  };
};
```
And an example is here https://github.com/libigl/libigl/blob/master/include/igl/ARAPEnergyType.h

However, this makes it difficult to identify which header file to include, difficult to read, and more importantly, not safe. What would be the advantage of the former compared to the modern enum
```
namespace igl
{
  enum class SolverStatus
  {
    // Good
    CONVERGED,
    // OK
    MAX_ITER,
    // Bad
    ERROR
  };
};
```

**Comment by jdumas** [comment]
The advantage of non-class enums is that they are easier to cast back and from integer types.This is useful for enum that corresponds to bitmasks where you want to do bitwise operations (`OPTION_A | OPTION_B`, etc.). The conversion to integer types is also useful to make drop-down menus with ImGui or NanoGui, showing which option is selected, etc.

Other than that I'd say enum class are superior (more safe, explicit, etc.), if only more verbose.

**Comment by alecjacobson** [comment]
Seems in C++11 you can even get those bitmask benefits too by specifying the storage.

```cpp
enum class Options  : unsigned char
```

Anyway, happy to merge a PR if somebody wants to change all of these (and change the python bindings to match. For now, i'm not going to do it.
