### ISSUE TITLE
Tutorial 406 abort at arap_dof_recomputation

### ISSUE THREAD

**Issue by josecalvario** [libigl/libigl#784]
Dear libigl support,

I'm currently trying to use the ARAP deformation algorithm on a 3D mesh. I'm using the existing 406 tutorial as a starting point. I'm using the arap_dof method because it looks like it's the fastest and more robust than the others.
However, I'm facing a problem when I try to run the code with my mesh/weight values.
The function arap_dof_recomputation aborts at line 596 with a very big maxErr2 value.
I suspect that the reason for this abort is related to the big number of handles that I'm using on my deformation. To have the necessary control over the deformation I need to use around 300 handles on a 50K triangle mesh. If I reduce the number if handles to a few 4 or 5, the code works without abort... but I can't control the mesh as I need to.

Is there any limitation that you know about the number of handles on the ARAP_dof algorithm?
If you want I can provide my mesh and weights files for you to inspect.

Many thanks on advance,
José Calvário

**Comment by alecjacobson** [comment]
I would have to dig a little into this case to root down the problem, but I'm guessing this is an issue with the matrix inverse. So that the runtime deformation is fast, we pre-invert (rather than, say, pre-factor) the O(#handles) by O(#handles) system matrix. I'm guessing for small #handles this is numerical OK, but things are going badly for 300 handles.

**Comment by josecalvario** [comment]
Hi Alec,
Thank you for the quick response. 

You are correct about the numerical stability when #handles is too big. After reducing considerably the number of handles the maxErr2 decreased significantly. However, I'm now facing another problem: after reducing the number of handles, the resulting deformation is not as smooth as I would like. I suspect that the weights that I'm computing during the ARAP setup are responsible for the bad smoothness of the deformation. My weights are simply the inverse of the square distance of each vertex to the handles. My question is:

Do you think that I should try to compute the weights with another algorithm? Maybe the "bbw" that's implemented on libigl? If so, could you give me a sample of how to compute them for a triangle mesh? I've look into the 403 tutorial, but it's for a tetrahedral mesh with defined control bones... in my case I have a triangle mesh with defined control vertices. The control vertices are
a subset of defined control connected edges.

Attached are two pictures of the original mesh and the deformed mesh. 
On original.png, the red and blue triangles are the handle vertices neighbouring triangles.
The red handles will be moved during the deformation.
On deformed.png you can see the deformation result. The mesh "in-between" the control vertices did not deform smoothly.

Thanks,
José Calvário

<img width="702" alt="deformed" src="https://user-images.githubusercontent.com/20952634/40369780-b3e073c0-5dd6-11e8-80ad-1d8fa0b206b5.png">
<img width="699" alt="original" src="https://user-images.githubusercontent.com/20952634/40369781-b3feaaca-5dd6-11e8-9c09-a1707c9e52b9.png">

**Comment by josecalvario** [comment]
The domain is a parametric surface.
I'm currently using the inverse of the squared distance to compute the weights.
My next step will be to replace the current weights by the bounded biharmonic weights. After looking at the bbw code I understand that I have to compute the weights on the mesh boundary and the bbw function will do the rest of the mesh for me...  is this right?

**Comment by alecjacobson** [comment]
BBW should already look better than this.

Not quit right. The "boundary conditions" are just the values at the points, so `b` would be a list of vertex indices of the point handles and `bc` would be an identity matrix. (Have a look at the bbw tutorial code).

**Comment by josecalvario** [comment]
Thank u for your help Alec,
The result looks better after using BBW, but I think I'm not using it the best way possible. I probably need to re-arrange my handles in order to get the desired effect.
My current problem is on how to select the minimum amount of handles to achieve a smooth deformation, without increasing drastically the complexity and time of the setup step of the ARAP algorithm.
