### ISSUE TITLE
How to decompose a mesh in components?

### ISSUE THREAD

**Issue by FrankEscobar** [libigl/libigl#786]
I've seen that you can retrieve the number of components by using

> 	Eigen::MatrixXi C, Ci;
> 	igl::components(A, C, Ci);

But there is any way to retrieve the separated components or the face/vertex indices that are used by each component?

Thank you in advance

**Comment by FrankEscobar** [comment]
I've notice that I can get the component id from C but it refers to edges, how can I relate it to faces?

**Comment by jiangzhongshi** [comment]
This question is probably outdated, but you can use https://github.com/libigl/libigl/blob/dev/include/igl/facet_components.h
