### ISSUE TITLE
Issue in projecting mesh on to the image plane.

### ISSUE THREAD

**Issue by bhushaan** [libigl/libigl#787]
I have a mesh which I read from ply file and build AABB tree using it. 

`
       
        Eigen::MatrixXd V;
        Eigen::MatrixXi F;

        if(!igl::readPLY(mesh_file, V, F)){
            std::cerr<< "Error occurred in reading the ply file\n";
            exit(1);
        }

        std::cout << "Total number of vertices are " << V.rows() << "\n";
        std::cout << "Total number of Faces are " << F.rows() << "\n";
        std::cout << "Building the AABB tree\n";
        igl::AABB<Eigen::MatrixXd, 3> tree;
        tree.init(V,F);
` 
I want to project it onto the image plane. I have camera extrinsics and intrinsics so for each pixel of the image, I generate a ray using camera coordinates and pixel coordinates in the world coordinate system. I try to find the first intersection of the ray.

`

            const Eigen::Vector3d source(cam_center_wcs[0], cam_center_wcs[1], cam_center_wcs[2]);
            const Eigen::Vector3d dir_vec(dir_vector[0], dir_vector[1], dir_vector[2]);

            igl::Hit hit; // intersection result

            bool did_intersect = MatTreeMain.intersect_ray(V, F, source, dir_vec, hit);

            if( ! did_intersect ) {
                non_intersection_counter++;
            } else {
              //calculate the depth map using distance hit.t
            }

`

I know that camera center is definitely inside the mesh and every ray that is generated has to intersect with the mesh but for some reason, for image with `1000 x 1000` resolution almost 75% of rays do not intersect with the mesh. 
I have following questions: 

1.  Am I doing something wrong or is it expected behavior ?  
2.  Does AABB tree skips certain faces while checking for ray intersections depending on orientation? 
3.  I understand how AABB trees are built how does ray intersections are calculated efficiently using AABB trees?

Thank you.

**Comment by alecjacobson** [comment]
1. looks OK
2. no
3. By checking if the ray hits the root axis aligned bounding box. If it does, recursing in each child until either deciding it misses all of them or hitting a leaf (and checking the primitive inside).
