### ISSUE TITLE
procrustes doesn't compile with non-double matrices

### ISSUE THREAD

**Issue by patrikhuber** [libigl/libigl#789]
Hi!

I think `igl::procrustes` in theory allows to pass arbitrary matrix types, it's defined as follows:

```
template <
  typename DerivedX,
  typename DerivedY,
  typename Scalar,
  typename DerivedR,
  typename DerivedT>
IGL_INLINE void igl::procrustes(
    const Eigen::PlainObjectBase<DerivedX>& X,
    const Eigen::PlainObjectBase<DerivedY>& Y,
    bool includeScaling,
    bool includeReflections,
    Scalar& scale,
    Eigen::PlainObjectBase<DerivedR>& R,
    Eigen::PlainObjectBase<DerivedT>& t)
```

However, if you pass anything other than a `MatrixXd`, it doesn't compile at all, there's compiler errors like for example:

> libigl\include\igl\procrustes.cpp(61): error C2676: binary '-': 'const Eigen::VectorXd' does not define this operator or a conversion to a type acceptable to the predefined operator

I think this is because internally `igl::procrustes` uses `MatrixXd` in multiple places and Eigen does probably not define subtraction and other operators for mixed types like `MatrixXf` and `MatrixXd` (just a guess from the errors - I haven't checked).

Also, I am not an Eigen expert, but I'm not sure if `Eigen::PlainObjectBase<Derived>` is the right thing to use. This page of the Eigen documentation (https://eigen.tuxfamily.org/dox/TopicFunctionTakingEigenTypes.html) doesn't even mention it in fact. It may be that `MatrixBase` should be used there instead.

**Comment by alecjacobson** [comment]
seems to be fine now.
