### ISSUE TITLE
LIM documentation / behavior mismatch when lim() can't satisfy tolerance

### ISSUE THREAD

**Issue by jimmyland** [libigl/libigl#79]
The docs for lim() say it returns 1 on "Successful optimization with fulfilled tolerance", but actually it returns 1 on reaching a local minimum regardless of whether it has satisfied the positional energy tolerance.

See the code in LIMSolverInterface.h: 
"if(data->solver->CurrentStepSize < 1e-15 || (data->solver->CurrentPositionalEnergy <= tolerance && (findLocalMinima == false || data->solver->CurrentStepSize < 1e-15)))
      result = 1; // termination criteria fulfilled"

As long as a local minima is reached (indicated by a small step size), the || condition doesn't check the CurrentPositionalEnergy against tolerance at all ...

**Comment by jimmyland** [comment]
(It'd be easy to fix this either by changing the documentation or changing the return code in this case; I'd submit a pull request but not sure which way you'd want to go.  Also: sorry if there was some other repo I should have submitted this to, since it's an external dep & not really your bug!)

**Comment by alecjacobson** [comment]
I attached Christian Schueller. He might be able to help.

**Comment by alecjacobson** [comment]
For now I fixed the doc in our wrapper `igl::lim::lim.h` to reflect this issue. Otherwise, I hope Christian might be able to help you with the possible issue _inside_ the lim dependency.

**Comment by schuellc** [comment]
Thank you for bringing this up. That is indeed not what it is supposed to do. I will push a fix to distinguish these cases. In general there is no guarantee that the solver will find a feasible minimum.
