### ISSUE TITLE
Callback collision?

### ISSUE THREAD

**Issue by Keudeugi** [libigl/libigl#790]
I'm wondering if this can be figured out to a glitch, but it seems like 2 callbacks between ImGui & Viewer occurs kinda collision, interrupting ImGui's menu lambda function call.

- Below is code snippet & result, where two callbacks are activated.
![image](https://user-images.githubusercontent.com/9735077/40588101-56391df8-6213-11e8-84b3-180378c60b87.png)
![image](https://user-images.githubusercontent.com/9735077/40588104-6006b098-6213-11e8-87aa-62cd01fbef86.png)
You can see the GUI didn't activated.

- ImGui is properly working when there's no Viewer callback:
![image](https://user-images.githubusercontent.com/9735077/40588107-6f83b656-6213-11e8-9bd5-7376cf4074a1.png)
![image](https://user-images.githubusercontent.com/9735077/40588117-8e8e0894-6213-11e8-9b41-93d7b3d1eced.png)

- However there's no additional function call in my Viewer callback function, makes me feel strange. Commenting function calls are intended.
![image](https://user-images.githubusercontent.com/9735077/40588130-aefed130-6213-11e8-8eb8-515037d163f0.png)

Any suggestions? If you found something I missed, please let me know. Thanks in advance.
-PilJoong

**Comment by jdumas** [comment]
Hi there,

You need to return `false` in your `post_draw()` function callback. If you return `true`, it informs the viewer that you want the flow to be interrupted. If such is the case, then the `post_draw()` callback of the imgui plugin (which is called after the custom callback specified via a lambda function) will not be called, and hence the imgui menu will not appear.

**Comment by Keudeugi** [comment]
Oh I didn't know that true interrupts the flow :| Thanks for let me know!
