### ISSUE TITLE
 why i use the igl::per_vertex _normals build nan(ind),is the mesh problem

### ISSUE THREAD

**Issue by wtrience** [libigl/libigl#791]
![image](https://user-images.githubusercontent.com/4581522/40607746-f560c722-629b-11e8-9d7f-84173cfe0f12.png)

**Comment by jdumas** [comment]
English please?

**Comment by alecjacobson** [comment]
Yes, the mesh is likely the problem. I'd guess there's a face with zero area.

**Comment by wtrience** [comment]
thank you sir.
