### ISSUE TITLE
Any ideas for using igl::unproject_ray?

### ISSUE THREAD

**Issue by Keudeugi** [libigl/libigl#798]
Hello,

I'm trying to generate a ray from camera position with the direction of camera eye. For that I found related function named **igl::unproject_ray()**, however it keep gives me error like __no instances of function template "igl::unproject_ray" matches the argument list.__

![image](https://user-images.githubusercontent.com/9735077/40897190-a1776630-67f4-11e8-8769-871470d36fdd.png)

Since source and direction required from the function should be formed in 3D vector, I also tried Eigen::Vector3f for both parameters however it doesn't work too.

Any suggestions for making it work? Is the function appropriate for my purpose? Thanks in advance.

**Comment by bickybilly** [comment]
Also having trouble with this.

**Comment by fwilliams** [comment]
Are you using a static build or header only version of libIGL?

If you're compiling libIGL as a static library, then it looks like there's only one instantiation of that functions for `float` scalars and specifically sized matrices. Could you post the full compiler error as well as the relevant code?

**Comment by alecjacobson** [comment]
Please reopen with a minimal reproducible example if this is still an issue.
