### ISSUE TITLE
CGAL's Poisson Surface Reconstruction in libigl (question)

### ISSUE THREAD

**Issue by TheodoreT** [libigl/libigl#800]
Hi to all, I would like to ask whether in libigl there is a corresponding functionality to CGAL's poison surfrace reconstruction ([https://doc.cgal.org/latest/Poisson_surface_reconstruction_3/index.html](https://doc.cgal.org/latest/Poisson_surface_reconstruction_3/index.html)). I was checking the functions within the libigl/include/igl/copyleft/cgal folder but I couldn't find something related except the "delaunay_triangulation" but I think this is not doing exactly the same think, please correct me if I am wrong.

Of course the alternative would be to link and use CGAL straight forward since I have compiled it within the libigl/external folder but the issue is that since I am passing the points on the fly (not reading them from a file) through a mex script it is quite tricky to cast them to the types that CGAL is waiting according to the examples from the above link. If someone has any experience though, I would appreciate any feedback.

With libigl on the other hand was quite easy with Eigen to insert and use the point cloud, thus I am asking whether I can do the same think with it or not. Thanks.

**Comment by evouga** [comment]
A CGAL expert may be able to help you figure out how to wrap CGAL's functionality; but I also recommend looking at http://www.cs.jhu.edu/~misha/Code/PoissonRecon/Version9.011/ which is lighter-weight than CGAL and has worked for me in past projects.

**Comment by TheodoreT** [comment]
FYI (might be useful for others as well), answer was given [here](https://github.com/CGAL/cgal/issues/3161) and more specific [here](https://gist.github.com/afabri/4ac12bdc89fead1f009fe878c3b2e0f0)
