### ISSUE TITLE
Read multiple objects from an obj file

### ISSUE THREAD

**Issue by Salingo** [libigl/libigl#803]
I have a question about reading multiple objects in Wavefront .obj files, the obj files may contain many object groups such as:
```
#
# object example_1
#
v 0.0 0.0 0.0
v 1.0 0.0 0.0
v 1.0 0.0 1.0
v 0.0 0.0 1.0
# 4 vertices

g example_1
f 1 4 3 
f 3 2 1 
# 2 faces

#
# object example_2
#
v 2.0 2.0 2.0
v 3.0 2.0 2.0
v 1.0 1.0 3.0
v 2.0 2.0 2.0
# 4 vertices

g example_2
f 1 4 3 
f 3 2 1 
# 2 faces
```
The igl::readOBJ function only returns one single object, so the group information is lost. Is there an easy way to read this kind of obj file as grouped objects?

**Comment by jdumas** [comment]
Well I suppose you can use `igl::facet_components()` and `igl::remove_unreferenced()` to extract each connected component (supposing you have one per object), and then remove vertices that do not belong to each object.

**Comment by alecjacobson** [comment]
(@jdumas, groups are different from connected components)

@Salingo , no. libigl .obj io does not support groups.

**Comment by jdumas** [comment]
Oh ok. I didn't know you could store a scene in a single .obj file.

**Comment by alecjacobson** [comment]
there's a lot of crazy stuff you can do in a .obj ... For example, we also don't support negative indices.

**Comment by Salingo** [comment]
@alecjacobson @jdumas Many thanks! I modified the readOBJ file and now group objects can be loaded.

**Comment by QhelDIV** [comment]
> @alecjacobson @jdumas Many thanks! I modified the readOBJ file and now group objects can be loaded.

I wonder how to edit it. Could you please share your code?

**Comment by Salingo** [comment]
Sure, just change '.txt' to '.h'.
:D
[read_groupOBJ.txt](https://github.com/libigl/libigl/files/6215126/read_groupOBJ.txt)

**Comment by Salingo** [comment]
> > @alecjacobson @jdumas Many thanks! I modified the readOBJ file and now group objects can be loaded.
> 
> I wonder how to edit it. Could you please share your code?

Sure, just change '.txt' to '.h'.
:D
[read_groupOBJ.txt](https://github.com/libigl/libigl/files/6215129/read_groupOBJ.txt)

**Comment by QhelDIV** [comment]
> > > @alecjacobson @jdumas Many thanks! I modified the readOBJ file and now group objects can be loaded.
> > 
> > 
> > I wonder how to edit it. Could you please share your code?
> 
> Sure, just change '.txt' to '.h'.
> :D
> [read_groupOBJ.txt](https://github.com/libigl/libigl/files/6215129/read_groupOBJ.txt)

Great! Thanks a lot.
