### ISSUE TITLE
requirement missing from tutorials 

### ISSUE THREAD

**Issue by xkunglu** [libigl/libigl#805]
Note for linux users ought to include:

`sudo apt-get install libcgal-qt5-11`

without that tutorials cmake will break on Ubuntu 16.04.3

> CMake Error at /usr/lib/x86_64-linux-gnu/cmake/CGAL/CGALExports.cmake:83 (message):
>   The imported target "CGAL::CGAL_Qt5" references the file
> 
>      "/usr/lib/x86_64-linux-gnu/libCGAL_Qt5.so.11.0.1"
> 
>   but this file does not exist.

regards

**Comment by jdumas** [comment]
This is probably not relevant anymore, now that CGAL is bundled with libigl.
