### ISSUE TITLE
Measuring deformation for mesh parametrization

### ISSUE THREAD

**Issue by RaduCorcodel** [libigl/libigl#806]
Hi everyone, I was wondering if you could help me with a bit of code:
What would be a nice and easy way to color code the deformation of the UV map when doing mesh parametrization (Tutorials 502, 503 for example). 
I need something that encodes say white for when there is no deformation of a particular triangle, red when it's stretched and blue compressed...
Any suggestion is welcome. 
Sorry if it's a simple thing for some, but I just got started working with the library.
Thank you.

**Comment by evouga** [comment]
So you can think of the parameterization as a map r: R^2 -> R^2 from the barycentric coordinates of the triangle to the plane. Given a vector (alpha, beta) in barycentric coordinates, the corresponding vector in R^3 is

[ p1 - p0   p2 - p0] [alpha beta]^T

where pi is the ith vertex of the triangle; and in the plane, the push-forward by r is

alpha (uv1 - uv0) + beta (uv2 - uv0)

where uvi is the (u,v) coordinate assigned to the ith vertex. The difference in squared length of the two two vectors (the triangle Green strain) is

e(alpha, beta) = [alpha, beta] M [alpha, beta]^T / 2

where M is the 2x2 matrix

M = [ p1 - p0   p2 - p0]^T[ p1 - p0   p2 - p0] - [ uv1 - uv0   uv2 - uv0]^T[ uv1 - uv0   uv2 - uv0].

The eigenvalues lambda1, lambda2 of M tell you the principal strains of the triangle. If both are positive, the parameterization compresses the triangle; if negative, it stretches the triangle, and if one is positive and the other is negative, the triangle is stretched in one direction but compressed in the other. You'll have to decide if you care more about measuring the total distortion of the parameterization (in which case something like tr(M^2) = lambda1^2 + lambda2^2 might make sense), or the anisotropy max(lambda1, lambda2) - min(lambda1, lambda2), or something else...

Once you've computed a number per triangle, you can use igl::colormap to turn them into colors, and
viewer.data().set_colors() to set the colors of the mesh faces (don't forget to also call viewer.data().set_face_based(true);)
