### ISSUE TITLE
Point sampling on mesh

### ISSUE THREAD

**Issue by Salingo** [libigl/libigl#808]
I want to convert the mesh to point cloud, so I need to do point sampling. I found there are two methods in libigl: **random_points_on_mesh** and **uniformly_sample_two_manifold**. Unfortunately, I met problems in both methods.
1. In **random_point_on_mesh**, the sampled pointcloud is always a triangle plane shape whatever the input mesh is. For example, This is one of the meshes I want to sample:
![snipaste_2018-06-13_16-36-04](https://user-images.githubusercontent.com/15212673/41341125-88fbea66-6f2b-11e8-94be-1b1a15c88d41.png)
Here is the result I got, visualizing with Cloudcompare:
![snipaste_2018-06-13_16-36-36](https://user-images.githubusercontent.com/15212673/41341213-c0721a2e-6f2b-11e8-88f0-49fff624ebc3.png)
I changed the input mesh but the result still the same. 
Here is my code:
```
int main(int argc, char *argv[])
{
  Eigen::MatrixXd V;
  Eigen::MatrixXi F;
  readOBJ("../../Data/object/Balance_1.obj", V, F);
  /* ... */
  menu.callback_draw_custom_window = [&]()
  {
    /* ... */
    if (ImGui::Button("Sample points", ImVec2(-1,0)))
    {
      Eigen::MatrixXd samples, FI;
      igl::random_points_on_mesh(5000, V, F, samples, FI);
      std::ofstream outFile;
      outFile.open("../outFile.pts", std::ios::trunc);
      for(auto i = 0; i<samples.rows(); i++)
      {
        outFile << samples.row(i).col(0) << " " << samples.row(i).col(1) << " " << samples.row(i).col(2) << "\n"; 
      }
      outFile.close();
    }
    ImGui::End();
  };
  viewer.data().set_mesh(V, F);
  viewer.launch();
}
```
2. In **uniformly_sample_two_manifold**, when I use this function instead of random sample above, the program got stuck in this function and had no response. Also, I don't understand the meaning of parameter "push" clearly, is there an example to show how to use this function?

Many many thanks!

**Comment by alecjacobson** [comment]
Have a look at the documentation in `include/igl/random_points_on_mesh.h` the first output is not given in "world" coordinates, but rather they're barycentric coordinates w.r.t. the sampled face in `FI`.

There are two ways you could change your code:

```
  Eigen::VectorXi FI;
  Eigen::MatrixXd B;
  igl::random_points_on_mesh(5000, V, F, B, FI);
  Eigen::MatrixXd samples(V.rows(),3);
  for(int i = 0;i<B.rows();i++)
  {
    samples.row(i) = 
      B(i,0)*V.row(F(FI(i),0))+
      B(i,1)*V.row(F(FI(i),1))+
      B(i,2)*V.row(F(FI(i),2));
  }
```

Or 

```
  Eigen::VectorXi FI;
  Eigen::SparseMatrix<double> B;
  igl::random_points_on_mesh(5000, V, F, B, FI);
  Eigen::MatrixXd samples = B*V;
```

(`uniformly_sample_two_manifold` is poorly named and probably not related to what you want to do)

**Comment by Salingo** [comment]
@alecjacobson I didn't understand the document correctly, now I can get the right output : )
Very appreciate for your detailed answer!

**Comment by ChimMeya** [comment]
Actually here is the right way to do sampling:
```
        igl::random_points_on_mesh(100000, V, F, B, FI);
	Eigen::MatrixXd samples(B.rows(), 3);
	for (int i = 0; i < samples.rows(); i++){
		samples.row(i) =
			B(i, 0)*V.row(F(FI(i), 0)) +
			B(i, 1)*V.row(F(FI(i), 1)) +
			B(i, 2)*V.row(F(FI(i), 2));
	}
```
PS: There is a bug in `random_points_on_mesh(n, , V, F, B, FI)`, it returns sometimes negative indices, so make sure that the indices int `FI(i)` are positive before accessing `F()`.

@Salingo & @alecjacobson

**Comment by alecjacobson** [comment]
There shouldn't ever be negative entries in `FI`. Please submit a minimal example if it's reproducible.
