### ISSUE TITLE
readMESH should not fail if `Triangles 0` line is missing

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#811]
See https://github.com/Yixin-Hu/TetWild/pull/8

The .mesh file format's documentation is not great, but it seems reasonable that omitting `Triangles 0` should be still parse.

**Comment by evouga** [comment]
I've hit this issue as well; here is a concrete failure case: https://www.dropbox.com/s/lwgerbr8l68bpdx/square_torus_400.mesh?dl=0

Thanks for the workaround hint (adding "Triangles 0" to the .mesh file contents).

**Comment by alecjacobson** [comment]
seems to be fixed.
