### ISSUE TITLE
Errors while trying to use igl::harmonic

### ISSUE THREAD

**Issue by Hugo-Pereira** [libigl/libigl#817]
Hi everyone

Trying to implement a geometry deformer that will behave like a lattice, I came across this incredible library.
 
I have a face mesh on “rest” pose, and a deformed face mesh (both with the same topology). I want to then apply the same deformation to other meshes (e.g. teeth, eyes, etc), so that these meshes will fit properly with the deformed head mesh.
 
Using igl::harmonic, I am getting the following errors:

- With laplacian power (k) of 1:
```Error: Numerical issue. Error: invalid solver type```
 - With laplacian power of 2, 3 or 4:
```libigl/include/igl/invert_diag.cpp:18: void igl::invert_diag(const Eigen::SparseMatrix<Scalar>&, Eigen::SparseMatrix<Scalar>&) [with T = double]: Assertion `dX.nonZeros() == dX.size()' failed.```

I lack the mathematical background to properly understand the tutorials, so I might be doing something obviously wrong. Just in case, I am attaching the serialization of the matrices I am using for the igl::harmonic parameters. I get the same issue with both Laplacian power of 1 and 2.
The values are mapped as igl::harmonic(“V”, “F”, “b”, “bc” …)
 
“V” and “F” contain the merged vertices and faces of the head and tongue meshes (they come from an obj).
“b” is a list of head mesh vertice indices in “V”
“bc” is face_vertices_deformed - face_vertices_rest
 
Maybe igl::harmonic isn’t meant for this use case?
 
This is a screenshot of the head mesh with the tongue mesh merged.
![image](https://user-images.githubusercontent.com/10086956/41708225-e2cdaefa-7537-11e8-9817-7787136b5c67.png)
[harmonic.zip](https://github.com/libigl/libigl/files/2122785/harmonic.zip)

Thanks for your time,
Hugo

**Comment by vutiqibyl** [comment]
Hello,

I noticed that igl::harmonic outputs "Numerical issue" with non-watertight meshes. Yours looks "open" at some places, so it might be due to this.

**Comment by Hugo-Pereira** [comment]
Oh, didn't realize  it was supposed to be water tight.
Is there a way I can do this automatically using libigl?

Thanks for your help!

**Comment by vutiqibyl** [comment]
As far as I know, there is no libigl function to automatically close meshes. In my case, I used meshlab to do it.

**Comment by Hugo-Pereira** [comment]
I made the mesh watertight (I think), but I still have the same issue.
I do have overlapping faces though...

![image](https://user-images.githubusercontent.com/10086956/41780810-b07a494e-762d-11e8-92bf-d1a0bf8c4068.png)

I'll try another solution (maybe biharmonic coordinates). Since that doesn't require a "cage", I am hoping it will work with non-manifold meshes?

**Comment by Hugo-Pereira** [comment]
From what I can see, igl::biharmonic_coordinates requires a tetrahedral mesh. Is there any way I can deform non-manifold triangular meshes?
