### ISSUE TITLE
Update the Embree lib pull to (at least) version 2.17.4

### ISSUE THREAD

**Issue by emanuelegissi** [libigl/libigl#822]
The current **Embree** version pulled by Libigl repository is **2.17.0**
This version fails to compile with gcc version 8.1.1, that is available by default in updated Linux distributions, as shown in:
https://github.com/embree/embree/issues/193#issuecomment-399888219

Embree 3.2.0 and Embree 2.17.4 both have this issue fixed.
So I suggest updating the version pulled by this repository at least to **2.17.4**

Thank you

**Comment by jdumas** [comment]
Embree 3.0 introduces breaking changes to the API so updating would be more complicated. But updating to 2.17.4 should be easy.

**Comment by emanuelegissi** [comment]
Thanks! 2.17.4 is good.

**Comment by ikoruk** [comment]
For embree 3.0, you might want to see this commit: https://github.com/rayform/libigl/commit/3979b8591d557eb4cea99921356d4bd1bb9dcc5c

**Comment by jdumas** [comment]
Would be nice if they could do a PR :p

**Comment by ikoruk** [comment]
Sure, here you go 😄  https://github.com/libigl/libigl/pull/834
