### ISSUE TITLE
Trying to deform a non-manifold triangle mesh with control points lying on the mesh surface

### ISSUE THREAD

**Issue by Hugo-Pereira** [libigl/libigl#823]
Hi guys,

I have a **non-manifold triangle mesh** that I need to deform. This deformation is based on points lying on the surface of the mesh (handles), that I then move around (when moved, they are no longer constrained to the surface of the mesh).
I have a solution for this using Thin Plates Spline, but it only works well for about 200 or so handles (performance issues). I was thinking I could use boundary_conditions + bbw to do this deformation.
Pre-computation times aren't much of an issue, I can cache the weights (so long as the target position of the handles don't influence the pre-computation :) ). I might need up to 15k handles.

When using boundary_conditions(
    const Eigen::MatrixXd & V,
    const Eigen::MatrixXi & Ele,
    const Eigen::MatrixXd & C,
    const Eigen::VectorXi & P,
    const Eigen::MatrixXi & BE,
    const Eigen::MatrixXi & CE,
    Eigen::VectorXi & b,
    Eigen::MatrixXd & bc);

I understand each argument is as follows:
V: the vertices of the mesh
Ele: the faces of the mesh
C: original position of the handles (unrelated to the vertices of the mesh)
P: indices of the handles... so [0, N-1] where N is the number of handles?
BE: empty matrix (I want to do "point deformation", is this correct?)
CE: empty matrix

Am I doing something wrong? I was hoping I could then use b and bc to compute weights (with bbw), and then use those weights to deform the matrix according to the new positions of the handle points (with the help of a linear blend skinning matrix).

However, boundary_conditions returns false, and both b and bc are empty.
Can someone shine a light on this problem? :)

Thanks,
Hugo

**Comment by alecjacobson** [comment]
Your understanding appears to be correct. Can you re-compile with `-DVERBOSE` ? It should spit out a debug message before returning false.

Meanwhile, for so many point handles, `boundary_conditions` will probably be slow. Are your input handles vertices of the original mesh or could they be in the middle of a triangle?

**Comment by Hugo-Pereira** [comment]
With `-DVERBOSE` get this:
`boundary_conditions: Error: boundary conditions are empty.`

The handles can be in the middle of a triangle. 
I also tried deforming a model with `harmonic` too. What I did was I created new points and faces so that each deformation point would have its own vertice. After the deformation, I retrieve the original set of vertices and faces. It seems to be alright, the issue is that I will then have to transfer the deformation to submeshes (teeth, eyeballs, etc), and so I am trying a deformation method that doesn't require the points to be on the surface/on a vertex (and doesn't require watertight and manifold meshes, and doesn't require a cage).

Thanks for your help

**Comment by alecjacobson** [comment]
bounded biharmonic weights doesn't necessarily require a manifold mesh, but
they won't leap across different components.

Are you trying to rig a character mesh that's a "solid" or are you working
with a more surface like shape?

(Might help to upload a model/image if you can)

**Comment by Hugo-Pereira** [comment]
The mesh I am trying to deform at the moment has a dingle component. 

However, I’d later like to transfer the deformation to other meshes. Is there a way to do this?
Can’t I use the points from a mesh as handles and deform the vertices of a different mesh? Do the handles need to be on the mesh face?

I’ll upload the mesh tomorrow when I get on my computer.
The mesh is just like this one but without the tongue

https://user-images.githubusercontent.com/10086956/41708225-e2cdaefa-7537-11e8-9817-7787136b5c67.png

Thanks

**Comment by Hugo-Pereira** [comment]
Here is the model's obj.
In the zip, you can also find a "boundary_conditions" file where you can retrieve the input arguments for boundary_conditions ("V", "Ele", "C", "P", "BE", "CE").
[boundary_conditions.zip](https://github.com/libigl/libigl/files/2148785/boundary_conditions.zip)

**Comment by Hugo-Pereira** [comment]
Still stuck with this. Can anyone help?

**Comment by Adamwgoh** [comment]
I have found out my issue. It is the handle 3d coords. For my case, I made sure that all handles are a vertex point on the generated tetrahedral mesh, and it works.

**Comment by alecjacobson** [comment]
What file format is the file `boundary_conditions` ?
