### ISSUE TITLE
Question on Calculating Gradient

### ISSUE THREAD

**Issue by QWFKS3FDS** [libigl/libigl#824]
Hi,

Firstly, thanks for such a great tool and such great documentation. It's helped tremendously for the work that I'm doing. 

That said, would you be able to explain a bit more how you calculate the scalar function values used in the gradient? How exactly are the values in the DMAT file generated? Does libigl include a way of creating the DMAT file from the mesh?

**Comment by nawuxicaa** [comment]
Hi jdumas,

mabe you have found the answer how to creating the DMAT file from the mesh with libigl?

Best regards,
Doudou

**Comment by mathieulin** [comment]
Hi jdumas,

mabe you have found the answer how to creating the DMAT file from the mesh with libigl?

Best regards,
Mathieu

**Comment by alecjacobson** [comment]
writeDMAT will write a dense matrix to a file.

**Comment by mathieulin** [comment]
> 
Thanks a lot.
If I want to deform an obj. file, how can i get the value of the dense matrix in the .dmat file ? For example, the "elephant-anim.dmat" in the tutorial

**Comment by mathieulin** [comment]
这是来自QQ邮箱的假期自动回复邮件。收到
