### ISSUE TITLE
dsq deformation using handle points coordinates 

### ISSUE THREAD

**Issue by ofirDubi** [libigl/libigl#828]
I currently have a .tgf skeleton and a 2d triangular mesh (that looks like a human body). I would like to use [404_DualQuaternionSkinning ](https://github.com/libigl/libigl/blob/master/python/tutorial/404_DualQuaternionSkinning.py)to perform dqs deformation. In the example you provide rotation and bending factors, which are used to calculate a bone's final pose. Instead, I would like to only provide the final location of one of the handle points. Is this possible?

**Comment by alecjacobson** [comment]
Are you asking about [inverse kinematics](https://en.wikipedia.org/wiki/Inverse_kinematics) ? We do not have a traditional implementation of IK, but we do have an implementation of "Fast Automatic Skinning Transformations", which is a type of "mesh-IK".
