### ISSUE TITLE
deforming texture from PNG

### ISSUE THREAD

**Issue by ofirDubi** [libigl/libigl#829]
Hi,
I currently have a 2D triangular mesh that I created from a PNG image (with texture).
I am using dqs deformation, and while I managed to rotate and band the mesh, I am not sure how to add and preform deformation on the texture.

**Comment by alecjacobson** [comment]
There's two main ways to deform an image.

1. create a mesh of the region you'd like to deform. Move the mesh but use the original positions as [texture mapping](https://en.wikipedia.org/wiki/Texture_mapping) [UV](https://en.wikipedia.org/wiki/UV_mapping) coordinates.

2. Think of each pixel at location [x,y] as starting with a vector [0,0] telling it to look for its color at [x+0,y+0]. Then you apply a warp by designing a non-trivial vector/displacement field. I.e. [0,0] becomes [2.5,3.7] so then when you go to draw the pixel at [x,y] you use the color at [x+2.5,y+3.7]

It sounds like you probably want option #1. You could use the libigl viewer to do the texture mapping or have a look at the map_texture function (probably doesn't do exactly what you want, but close).

**Comment by ofirDubi** [comment]
Hi Alec, Thanks for your response,
I've spent some time trying to get the map_texture function to work. I am developing with python, so I had to add it to the python bindings first. After i bound the function, I had to update the glad version provided with libigl to the [newest version](https://github.com/Dav1dde/glad), so I could use openGL4 features. 
Everything was looking good, but when i called map_texture, my program crashed with the following error code: 
```Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)```

I traced the error to line 126 in map_texture.cpp:
```c
glVertexAttribLPointer(0, U.cols(), GL_DOUBLE, U.cols() * sizeof(GLdouble), (GLvoid*)0);
```
After doing some digging i found out that this might be a graphics driver issue.

Can you please specify the graphics card that you used to test this function?

P.S
I am running Ubuntu 16.04 on VMware, which emulates a VGA compatible graphics card.
I also tried using the openGL library from [mesa](https://01.org/linuxgraphics/downloads/2018q1-intel-graphics-stack-recipe), but the program failed with the same error.

**Comment by jdumas** [comment]
Can you try to run it on Linux directly, e.g. on a live USB, to see if it's not a limitation of the graphics driver from the VM?

**Comment by ofirDubi** [comment]
I've run the program on a fresh ubuntu 18.04 install on my main PC (that has a Nvidia 960 GTX GPU). I did the modifications as in my original attempt, and I got the same error. I've also installed Nvidia graphics card driver and CUDA.

I would appreciate it if some one that has successfully run this method can post his openGL version.
you can check it using this command:

`glxinfo | grep "OpenGL version"`
The output on my machine is:
`OpenGL version string: 4.6.0 NVIDIA 396.45`

It occurred to me that I perform deformation on  2D objects (all Z components are 0), can that be an issue?

The .obj and .png files i use:
[objects.zip](https://github.com/libigl/libigl/files/2225712/objects.zip)
I take V from `atlas.obj` and U from `deformed_atlas.obj`, I call `igl::stbi_load` to get the image data.

**Comment by jdumas** [comment]
Can you post a MWE with your code as well?

**Comment by ofirDubi** [comment]
I made a minimal cpp program based on the 102_DrawMesh (i used it's cmake file). 

```C

#include <igl/readOBJ.h>
#include <igl/opengl/glfw/map_texture.cpp>
#include "tutorial_shared_path.h"
#include "../../external/stb_image/igl_stb_image.cpp"

Eigen::MatrixXd U;
Eigen::MatrixXd V;
Eigen::MatrixXi F;

int main(int argc, char *argv[])
{
  // Load V,U and F from OBJ. F is the same in both files.
  igl::readOBJ(TUTORIAL_SHARED_PATH "/atlas.obj", V, F);
  igl::readOBJ(TUTORIAL_SHARED_PATH "/deformed_atlas.obj", U, F);


  int width, height, bpp, nc =3;
  std::vector<unsigned char> out_rgb;
  //Read image with stbi_load
  unsigned char * in_rgb  = igl::stbi_load(TUTORIAL_SHARED_PATH "/streched_atlas.png", &width, &height, &bpp, nc );

 // in_rgb is now three bytes per pixel, width*height size. Or NULL if load failed.
  if(in_rgb == NULL){
	  printf("image reading failed!\n");
	  return 1;
  }

  //Calling map texture
  printf("Calling map_texture\n");
  igl::opengl::glfw::map_texture(V,F,U,in_rgb,width,height,nc,out_rgb);
  printf("Finished map_texture\n");
  //Write output image with stbi_write
  igl::stbi_write_png(TUTORIAL_SHARED_PATH "/deformed_atlas.png", width, height, bpp, out_rgb.data(), 0);

  igl::stbi_image_free(in_rgb);

}
```
output is:
```
Calling map_texture
Segmentation fault (core dumped)
```

**Comment by ofirDubi** [comment]
Hi @alecjacobson @jdumas, 
Can you take a look at my code and tell me if I did something wrong?

**Comment by alecjacobson** [comment]
`map_texture` was a mess. The version in #2277 assumes that the input meshes are in the UV domain (unit square [0,1]²). Meanwhile, in your example the meshes weren't well aligned with the texture AFAICT. After aligning them 

**input**
![streched_atlas-0](https://github.com/libigl/libigl/assets/2241689/d171e006-93d9-4409-af23-08644606fb65)
**deformed**
![deformed_atlas](https://github.com/libigl/libigl/assets/2241689/064c8263-9ecf-41b0-9144-8026a8fbf72d)
