### ISSUE TITLE
Simplify mesh without decimation

### ISSUE THREAD

**Issue by FrankEscobar** [libigl/libigl#831]
I was thinking about the idea of making a mesh simplification without decimation just by using two conditions:

- Weld vertices if their distance is lower than X

- Join faces if their normal is identical or the difference is lower than X.

Is there something like that already done?

Thank you in advance

**Comment by jdumas** [comment]
For the first one there is already a function `remove_duplicate_vertices()` that does it. For the second one I am not sure what that would achieve...

**Comment by FrankEscobar** [comment]
remove_duplicate_vertices works with vertices sharing position but not sharing triangle?

**Comment by jdumas** [comment]
True. You'd probably need to implement it yourself then, shouldn't be too complicated.

**Comment by jmespadero** [comment]
Joining faces based in their normal usually is not a good idea. First, you have to check that the faces are neighbors. Then, you will produce planar patches that can get a complicated boundary, even with holes inside.

**Comment by alecjacobson** [comment]
simplify_polyhedron joins faces that are coplanar. you could modify it to collapse edges, too.
