### ISSUE TITLE
Tutorial 106 compile fail

### ISSUE THREAD

**Issue by BacheryChan** [libigl/libigl#836]
I try to compile and run the tutorials and find 106_ViewerMenu doesn't appear in the build folder after:

```
cd tutorial
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ../
```

And if I add the following sentence to the CMakeLists.txt in the tutorial folder 

`option(LIBIGL_WITH_OPENGL_GLFW_IMGUI "Use ImGui"    ON)
`

an error occurs while cmake:
```
CMake Error at 106_ViewerMenu/CMakeLists.txt:4 (add_executable):
  Target "106_ViewerMenu_bin" links to target "igl::opengl_glfw_imgui" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
```

The same problem happens when I use the example-project when using ImGui.

**Comment by BacheryChan** [comment]
Cool, it works, thanks.

Another problem is when I replace the code in the example-project with

```
Eigen::MatrixXd V;
Eigen::MatrixXi F;

int main(int argc, char *argv[])
{
  // Load a mesh in OFF format
  igl::readOFF("cube.off", V, F);

  // Print the vertices and faces matrices
  std::cout << "Vertices: " << std::endl << V << std::endl;
  std::cout << "Faces:    " << std::endl << F << std::endl;

  // Save the mesh in OBJ format
  igl::writeOBJ("cube.obj",V,F);
}

```

there is an IOError occurs:

`IOError: cube.off could not be opened...`

**Comment by jdumas** [comment]
Well you need to have a file `cube.off` in your current working directory to be able to open it ...
