### ISSUE TITLE
menu is not visible at Example 102

### ISSUE THREAD

**Issue by MingiYeom** [libigl/libigl#837]
- I used CMake-gui.exe to configure and generate tutorials.  But, when I execute tutorial 102(Example 102), the menu window is not visible at Windows10 + VS2015 Win64.

![image](https://user-images.githubusercontent.com/37587281/42800712-e2e6212e-89d7-11e8-8017-20e8dfec070d.png)
**Value Settings at CMake**
　
　　
![image](https://user-images.githubusercontent.com/37587281/42800246-03a66e66-89d6-11e8-9615-a58c5af3f307.png)
**Example 102**
　
　　
![image](https://user-images.githubusercontent.com/37587281/42800317-422eb724-89d6-11e8-8493-cd94155958be.png)
**My Case**
　
　　
Can somebody help me, plz?

**Comment by jdumas** [comment]
Yes the menu have been removed from all tutorials except 106. Look at tutorial 106 if you want to enable a menu on other tutorials.

**Comment by MingiYeom** [comment]
Thank you!! :D
