### ISSUE TITLE
Create an additional face

### ISSUE THREAD

**Issue by skotti** [libigl/libigl#843]
Hello!
I have an initial set faces. I added several new points to my point set and want to construct new faces. However, being unsure what is the correct order of faces, I always get incorrect result.
For example, if I introduce an additional point in the center of a triangle, I want to have three additional faces. It would be nice, if there was a possibility to construct faces from edges or so, but now I spent couple of hours to figure out in what order should the points follow in the newly introduced faces. It is not documented well.

was: 1, 2, 3. I added 4th vertex in the middle. Should the faces which I want to add in my face set now look like: 1, 4, 3 + 1, 2, 4 + 4, 2, 3? This is my suggestion based on the first chapter of tutorial. However, this order produces incorrect results.

**Comment by jmespadero** [comment]
The trick is to choose the order in vertex to keep the orientation

If you want to replace the face [a, b, c] with 3 new faces by adding a vertex x, you can create 3 copies of your face and replace one vertex in each by the new vertex

1.  Your initial face -> [a, b, c] 
2.  Create 3 duplicates -> [a, b, c]  +  [a, b, c]  +  [a, b, c] 
3.  Change one coordinate in each face-> [x, b, c]  +  [a, x, c]  +  [a, b, x] 

In your example, face [1, 2, 3] should be replaced by [4, 2, 3] + [1, 4, 3] + [1, 2, 4]

Note that you reused vertex 1 and 2 on every face in your solution.
