### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by csverma610** [libigl/libigl#845]
Hello,

What could be the source of the following compilation errors? Can someone help?

/Software/Mesh/LibIGL/include/igl/vertex_triangle_adjacency.cpp:70:6: error: ‘Eigen::PlainObjectBase<Derived>& Eigen::PlainObjectBase<Derived>::operator=(Eigen::PlainObjectBase<Derived>&&) [with Derived = Eigen::Matrix<int, -1, 1>]’ is protected within this context
   VF = Eigen::VectorXi(3*F.rows());
   ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

/Software/MathLibs/Eigen/V3.3.4/include/eigen3/Eigen/src/Core/PlainObjectBase.h:509:22: note: declared protected here
     PlainObjectBase& operator=(PlainObjectBase&& other) EIGEN_NOEXCEPT
                      ^~~~~~~~
<builtin>: recipe for target 'main.o' failed

**Comment by jdumas** [comment]
You should use Eigen 3.2, the version that is provided in the submodule, for now. There is a pending PR #840 for compatibility with Eigen 3.3, but it is not merged yet.
