### ISSUE TITLE
701_Statistics Routine 

### ISSUE THREAD

**Issue by csverma610** [libigl/libigl#847]
Hello,

It seems the call to the function always fails. 
  // Count the number of irregular vertices, the border is ignored
  vector<bool> irregular = igl::is_irregular_vertex(V,F);
  
The message is:

stat: /LibIGL/external/eigen/Eigen/src/Core/DenseCoeffsBase.h:394: Eigen::DenseCoeffsBase<Derived, 1>::Scalar& Eigen::DenseCoeffsBase<Derived, 1>::operator()(Eigen::DenseCoeffsBase<Derived, 1>::Index) [with Derived = Eigen::Matrix<int, -1, 1>; Eigen::DenseCoeffsBase<Derived, 1>::Scalar = int; Eigen::DenseCoeffsBase<Derived, 1>::Index = long int]: Assertion `index >= 0 && index < size()' failed.
Aborted (core dumped)

**Comment by jdumas** [comment]
Tutorial 701 works for me. What are your modifications / which mesh are you trying it on?

**Comment by csverma610** [comment]
For me no example ( in the shared file ) works. I always get the message:

stat:
/home/csverma/Disk/Software/Mesh/LibIGL/external/eigen/Eigen/src/Core/DenseCoeffsBase.h:394:
Eigen::DenseCoeffsBase<Derived, 1>::Scalar& Eigen::DenseCoeffsBase<Derived,
1>::operator()(Eigen::DenseCoeffsBase<Derived, 1>::Index) [with Derived =
Eigen::Matrix<int, -1, 1>; Eigen::DenseCoeffsBase<Derived, 1>::Scalar =
int; Eigen::DenseCoeffsBase<Derived, 1>::Index = long int]: Assertion
`index >= 0 && index < size()' failed.
Aborted (core dumped)

**Comment by jdumas** [comment]
Can you provide a bit more context maybe? Which OS are you using? Are you using the version of Eigen bundled in the submodules? Are you compiling the tutorial in debug/release/header-only? Etc.

**Comment by csverma610** [comment]
Hello,

I am using Linux 18.04. Initially, I tried the latest Eigen, but it did not
work. So, I am using the Eigen provided in the external folder. Most of the
tutorial examples are working except those related
to CoMISo and the irregular in the Statistics.

csv
