### ISSUE TITLE
Probably wrong documentation on readSTL

### ISSUE THREAD

**Issue by ithron** [libigl/libigl#848]
In readSTL.h lines 28 to 31:

```
// Outputs:
  //   V  double matrix of vertex positions  #V*3 by 3
  //   F  index matrix of triangle indices #F by 3
  //   N  double matrix of vertex positions  #F by 3
```

I would expect that `N` is a matrix of normal vectors instead if vertex positions, again?

**Comment by jdumas** [comment]
Yeah looks like it. Not sure why you need read normals when reading a STL file though.
