### ISSUE TITLE
Integrate Matlab in a libigl application

### ISSUE THREAD

**Issue by chenhonghua** [libigl/libigl#85]
hi,
Libigl can connect to an existing instance of Matlab (or launching a new one on Linux/MacOSX).
I want to  integrate Matlab in a libigl application(Example 602) on Windows. 
But is that also work on Windows?

**Comment by alecjacobson** [comment]
Yes, this will also work on windows. I _believe_ on Windows, the C++ application will use an existing Matlab instance if it exists and if not launch a new one. Whereas on Linus/Mac OS X a new instance is always launched.

**Comment by chenhonghua** [comment]
Yes, that's really really cool.

**Comment by ucesnro** [comment]
Hi, 
I have problems launching example 602 on my Windows 10 machine. I changed all paths and obvious differences; however, the tutorial file does not seem to run. 
the error is within defining the engine:
// Matlab instance
Engine* engine;
>> Cant resolve type "Engine"

Is there anything else I have to include or change in the Cmake file to use that example 602?

Cheers!
