### ISSUE TITLE
Slice a triangle mesh with a plane

### ISSUE THREAD

**Issue by RaduCorcodel** [libigl/libigl#851]
Does anyone know if libigl has an implementation for slicing a triangulation with a plane?
CGAL has a similar function but I'd prefer not to go back and forth to use CGAL's implementation:
https://doc.cgal.org/latest/Polygon_mesh_processing/index.html#PMPSlicer

Thanks in advance. Any suggestion is welcomed.

Radu,

**Comment by jdumas** [comment]
Maybe you could try to get away with [`igl::isolines()`](isolines.h), by evaluating the plane equation at each vertices?

**Comment by alecjacobson** [comment]
I have limited internet access but I believe there’s a function called half
space intersect.

**Comment by RaduCorcodel** [comment]
Thank you both. 
@jdumas that is a great idea. I'm actually computing a function on the mesh and I can tweak it to use isolines. Thank you for.

@alecjacobson I found the intersect_with_half_space.h 
will try to see how to use it. I'm a little fuzzy on what the third output (J  #FC list of indices into [F;F.rows()+[1;2]] revealing "birth" facet) does.

**Comment by AlessandroFasse** [comment]
Thats very interesting and also what I am looking for! Could work it out with the isolines? How can I produce back a Mesh from the isolines?

**Comment by jdumas** [comment]
What do you want to produce? A triangle mesh of the sliced area? That's not strictly necessary for slicing a mesh (e.g. for 3D printing). But if you want that you can try to use `igl::triangle::triangulate()` with input edges.

One thing that `igl::isolines()` doesn't do is 1) join the lines into a closed polygons/open polylines, and 2) determine which part is inside/outside.

If the input mesh is clean and closed it's easy to do that (I can contribute if the function is missing from libigl). If the input is dirty though, it's probably best to use something like [this](http://www.dgp.toronto.edu/projects/fast-winding-numbers/) (see #810 ?).

**Comment by AlessandroFasse** [comment]
The central idea is to measure the circumference of the intersection of a mesh with plane, i.e. the length along the boundary edges. However, I also would like to export the slice as a whole mesh because maybe I need to also do a analysis of the shape of the slice. 

The idea of triangulating sounds very good! Maybe I could compute the intersections of edges with the plane and triangulate the resulting set of vertices. This would also remove of assumption of the mesh being closed. ( In case the mesh isn't closed I only will have very tiny holes compared to the total size and therefore these holes, which will not give edge in the intersection will be filled). I will try this approach and if there are some problems I will come back to you later. 

Many thanks in advanve for your time!

**Comment by AlessandroFasse** [comment]
Hey there! I am sorry for disturbing again. I tried to uses triangulate but however I can not use it due to the following. When I call 
```
#include <igl/triangle/triangulate.h>
```
in any file and try to compline then I get the following error
```
alessandro@ThinkStation:~/PycharmProjects/onefid_core_v2/PyOnefid/testing$ g++ -std=c++11 -I ~/libigl/include/ -I ~/libigl/external/eigen/ -pthread main.cpp
In file included from /home/alessandro/libigl/include/igl/triangle/triangulate.h:84:0,
                 from main.cpp:9:
/home/alessandro/libigl/include/igl/triangle/triangulate.cpp:27:10: fatal error: triangle.h: No such file or directory
 #include <triangle.h>
          ^~~~~~~~~~~~
compilation terminated.
```

I looked into the code and found the error
```
extern "C"
{
#include <triangle.h> (this is row 27:10)
}
```
 I am pretty sure that he is not capable of finding the ```triangle.h``` file in the folder ```/external/triangle/```. How can I resolve this?

Also regarding trianguate: It is possible the leave the set of edges and holes empty?

**Comment by AlessandroFasse** [comment]
Today I tried out several approaches but I am not capabale of solving the problem. 
But I have the following idea: 
Is there a method in order to remove a part of the mesh that belongs to one side of the plane and return this is a new set of vertices and faces? I.e. assume you define two 3d-vectors ```point``` and ```normal``` that span the plane. Then, let ```p``` be any point on the initial mesh (which can also be on an edge or on a face). Then, I want that the only mesh ONLY consists points with the property that
```
(p-point).dot(normal) < 0
```
Do you know how this can be done? 

If somehow I could produce this I could simply use ```igl::boundary_loop``` to get the boundary that was createded by "intersection". Furthermore, I would have a nice orienatation of that boundary. I know that if the mesh has holes that cross the plain these would contribute at this boundary. But I know that these effects are negligible.

**Comment by jdumas** [comment]
Well, you can always use the boolean in libigl, but that's way overkill and probably too expensive. Do you want something that works on clean meshes, or does it need to be robust to dirty input as well?

**Comment by AlessandroFasse** [comment]
What exactly do you mean by "dirty"?
As far as I understood, boolean works only for closed meshes, right?

**Comment by jdumas** [comment]
Well do you want your algorithm to handle input meshes with imperfections, e.g. tiny gaps and holes, self-intersections, etc.

**Comment by AlessandroFasse** [comment]
I tried to complie the following code
```
#include <iostream>
#include <Eigen/Dense>
#include <igl/copyleft/cgal/intersect_with_half_space.h>

using Eigen::MatrixXi;
using Eigen::MatrixXd;
using Eigen::VectorXd;
using Eigen::VectorXi;
using Eigen::Vector3d;

void half_space_slice(MatrixXd &vertices, MatrixXi &faces, Vector3d &point, Vector3d &direction){
        MatrixXd J;
        igl::copyleft::cgal::intersect_with_half_space(vertices, faces, point, direction, vertices, faces, J);
    }


int main(){
    MatrixXd vertices(8,3);
    vertices <<
    1,1,1,
    -1,1,1,
    -1,-1,1,
    1,-1,1,
    1,1,-1,
    -1,1,-1,
    -1,-1,-1,
    1,-1,-1;
    MatrixXi faces(11,3);
    faces <<
    4,0,1,
    4,1,5,
    5,1,2,
    5,2,6,
    6,2,3,
    6,3,7,
    7,3,0,
    7,0,4,
    3,0,1,
    3,1,2,
    5,6,7;
    Vector3d point(0,0,0);
    Vector3d direction(1,0,0);
    half_space_slice(vertices, faces, point, direction);
    std::cout << vertices << std::endl;
}
```
via
```
g++ -std=c++11 -I ~/libigl/include/ -I ~/libigl/external/eigen/ -lgmp -lmpfr -frounding-math -pthread main.cpp
```
However, I get a horrible long error code. Here are some of the first lines:
```
/tmp/ccQCHSmp.o: In function `__gmp_unary_minus::eval(__mpq_struct*, __mpq_struct const*)':
main.cpp:(.text._ZN17__gmp_unary_minus4evalEP12__mpq_structPKS0_[_ZN17__gmp_unary_minus4evalEP12__mpq_structPKS0_]+0x1f): undefined reference to `__gmpq_neg'
/tmp/ccQCHSmp.o: In function `__gmp_binary_plus::eval(__mpq_struct*, __mpq_struct const*, __mpq_struct const*)':
main.cpp:(.text._ZN17__gmp_binary_plus4evalEP12__mpq_structPKS0_S3_[_ZN17__gmp_binary_plus4evalEP12__mpq_structPKS0_S3_]+0x27): undefined reference to `__gmpq_add'
/tmp/ccQCHSmp.o: In function `__gmp_binary_minus::eval(__mpq_struct*, __mpq_struct const*, __mpq_struct const*)':
main.cpp:(.text._ZN18__gmp_binary_minus4evalEP12__mpq_structPKS0_S3_[_ZN18__gmp_binary_minus4evalEP12__mpq_structPKS0_S3_]+0x27): undefined reference to `__gmpq_sub'
/tmp/ccQCHSmp.o: In function `__gmp_binary_minus::eval(__mpq_struct*, __mpq_struct const*, double)':
main.cpp:(.text._ZN18__gmp_binary_minus4evalEP12__mpq_structPKS0_d[_ZN18__gmp_binary_minus4evalEP12__mpq_structPKS0_d]+0x87): undefined reference to `__gmpq_set_d'
main.cpp:(.text._ZN18__gmp_binary_minus4evalEP12__mpq_structPKS0_d[_ZN18__gmp_binary_minus4evalEP12__mpq_structPKS0_d]+0xa7): undefined reference to `__gmpq_sub'
/tmp/ccQCHSmp.o: In function `__gmp_binary_minus::eval(__mpq_struct*, double, __mpq_struct const*)':
main.cpp:(.text._ZN18__gmp_binary_minus4evalEP12__mpq_structdPKS0_[_ZN18__gmp_binary_minus4evalEP12__mpq_structdPKS0_]+0x87): undefined reference to `__gmpq_set_d'
main.cpp:(.text._ZN18__gmp_binary_minus4evalEP12__mpq_structdPKS0_[_ZN18__gmp_binary_minus4evalEP12__mpq_structdPKS0_]+0xa7): undefined reference to `__gmpq_sub'
/tmp/ccQCHSmp.o: In function `__gmp_binary_multiplies::eval(__mpq_struct*, __mpq_struct const*, __mpq_struct const*)':
main.cpp:(.text._ZN23__gmp_binary_multiplies4evalEP12__mpq_structPKS0_S3_[_ZN23__gmp_binary_multiplies4evalEP12__mpq_structPKS0_S3_]+0x27): undefined reference to `__gmpq_mul'
/tmp/ccQCHSmp.o: In function `__gmp_binary_divides::eval(__mpq_struct*, __mpq_struct const*, __mpq_struct const*)':
main.cpp:(.text._ZN20__gmp_binary_divides4evalEP12__mpq_structPKS0_S3_[_ZN20__gmp_binary_divides4evalEP12__mpq_structPKS0_S3_]+0x27): undefined reference to `__gmpq_div'
/tmp/ccQCHSmp.o: In function `__gmp_cmp_function::eval(__mpq_struct const*, __mpq_struct const*)':
main.cpp:(.text._ZN18__gmp_cmp_function4evalEPK12__mpq_structS2_[_ZN18__gmp_cmp_function4evalEPK12__mpq_structS2_]+0x1f): undefined reference to `__gmpq_cmp'
/tmp/ccQCHSmp.o: In function `__gmp_binary_equal::eval(__mpq_struct const*, __mpq_struct const*)':
main.cpp:(.text._ZN18__gmp_binary_equal4evalEPK12__mpq_structS2_[_ZN18__gmp_binary_equal4evalEPK12__mpq_structS2_]+0x1f): undefined reference to `__gmpq_equal'
/tmp/ccQCHSmp.o: In function `__gmp_binary_equal::eval(__mpq_struct const*, long)':
main.cpp:(.text._ZN18__gmp_binary_equal4evalEPK12__mpq_structl[_ZN18__gmp_binary_equal4evalEPK12__mpq_structl]+0x24): undefined reference to `__gmpq_cmp_si'
/tmp/ccQCHSmp.o: In function `__gmp_binary_less::eval(__mpq_struct const*, __mpq_struct const*)':
main.cpp:(.text._ZN17__gmp_binary_less4evalEPK12__mpq_structS2_[_ZN17__gmp_binary_less4evalEPK12__mpq_structS2_]+0x1f): undefined reference to `__gmpq_cmp'
/tmp/ccQCHSmp.o: In function `__gmp_binary_less::eval(__mpq_struct const*, long)':
main.cpp:(.text._ZN17__gmp_binary_less4evalEPK12__mpq_structl[_ZN17__gmp_binary_less4evalEPK12__mpq_structl]+0x24): undefined reference to `__gmpq_cmp_si'
/tmp/ccQCHSmp.o: In function `__gmp_binary_less::eval(long, __mpq_struct const*)':
main.cpp:(.text._ZN17__gmp_binary_less4evalElPK12__mpq_struct[_ZN17__gmp_binary_less4evalElPK12__mpq_struct]+0x24): undefined reference to `__gmpq_cmp_si'
/tmp/ccQCHSmp.o: In function `__gmp_binary_less::eval(__mpq_struct const*, double)':
main.cpp:(.text._ZN17__gmp_binary_less4evalEPK12__mpq_structd[_ZN17__gmp_binary_less4evalEPK12__mpq_structd]+0x80): undefined reference to `__gmpq_set_d'
main.cpp:(.text._ZN17__gmp_binary_less4evalEPK12__mpq_structd[_ZN17__gmp_binary_less4evalEPK12__mpq_structd]+0x99): undefined reference to `__gmpq_cmp'
/tmp/ccQCHSmp.o: In function `__gmp_binary_less::eval(double, __mpq_struct const*)':
main.cpp:(.text._ZN17__gmp_binary_less4evalEdPK12__mpq_struct[_ZN17__gmp_binary_less4evalEdPK12__mpq_struct]+0x80): undefined reference to `__gmpq_set_d'
main.cpp:(.text._ZN17__gmp_binary_less4evalEdPK12__mpq_struct[_ZN17__gmp_binary_less4evalEdPK12__mpq_struct]+0x99): undefined reference to `__gmpq_cmp'
/tmp/ccQCHSmp.o: In function `__gmp_abs_function::eval(__mpq_struct*, __mpq_struct const*)':
main.cpp:(.text._ZN18__gmp_abs_function4evalEP12__mpq_structPKS0_[_ZN18__gmp_abs_function4evalEP12__mpq_structPKS0_]+0x1f): undefined reference to `__gmpq_abs'
/tmp/ccQCHSmp.o: In function `__gmp_expr<__mpz_struct [1], __mpz_struct [1]>::assign_si(long)':
main.cpp:(.text._ZN10__gmp_exprIA1_12__mpz_structS1_E9assign_siEl[_ZN10__gmp_exprIA1_12__mpz_structS1_E9assign_siEl]+0x1f): undefined reference to `__gmpz_set_si'
/tmp/ccQCHSmp.o: In function `__gmp_expr<__mpq_struct [1], __mpq_struct [1]>::assign_si(long)':
main.cpp:(.text._ZN10__gmp_exprIA1_12__mpq_structS1_E9assign_siEl[_ZN10__gmp_exprIA1_12__mpq_structS1_E9assign_siEl]+0x24): undefined reference to `__gmpq_set_si'
/tmp/ccQCHSmp.o: In function `__gmp_expr<__mpq_struct [1], __mpq_struct [1]>::assign_d(double)':
main.cpp:(.text._ZN10__gmp_exprIA1_12__mpq_structS1_E8assign_dEd[_ZN10__gmp_exprIA1_12__mpq_structS1_E8assign_dEd]+0x26): undefined reference to `__gmpq_set_d'
/tmp/ccQCHSmp.o: In function `__gmp_expr<__mpq_struct [1], __mpq_struct [1]>::init_si(long)':
main.cpp:(.text._ZN10__gmp_exprIA1_12__mpq_structS1_E7init_siEl[_ZN10__gmp_exprIA1_12__mpq_structS1_E7init_siEl]+0x18): undefined reference to `__gmpq_init'
/tmp/ccQCHSmp.o: In function `__gmp_expr<__mpq_struct [1], __mpq_struct [1]>::init_d(double)':
main.cpp:(.text._ZN10__gmp_exprIA1_12__mpq_structS1_E6init_dEd[_ZN10__gmp_exprIA1_12__mpq_structS1_E6init_dEd]+0x19): undefined reference to `__gmpq_init'
/tmp/ccQCHSmp.o: In function `__gmp_expr<__mpq_struct [1], __mpq_struct [1]>::__gmp_expr()':
main.cpp:(.text._ZN10__gmp_exprIA1_12__mpq_structS1_EC2Ev[_ZN10__gmp_exprIA1_12__mpq_structS1_EC5Ev]+0x14): undefined reference to `__gmpq_init'
/tmp/ccQCHSmp.o: In function `__gmp_expr<__mpq_struct [1], __mpq_struct [1]>::__gmp_expr(__gmp_expr<__mpq_struct [1], __mpq_struct [1]> const&)':
main.cpp:(.text._ZN10__gmp_exprIA1_12__mpq_structS1_EC2ERKS2_[_ZN10__gmp_exprIA1_12__mpq_structS1_EC5ERKS2_]+0x1f): undefined reference to `__gmpz_init_set'
main.cpp:(.text._ZN10__gmp_exprIA1_12__mpq_structS1_EC2ERKS2_[_ZN10__gmp_exprIA1_12__mpq_structS1_EC5ERKS2_]+0x3a): undefined reference to `__gmpz_init_set'
/tmp/ccQCHSmp.o: In function `__gmp_expr<__mpq_struct [1], __mpq_struct [1]>::__gmp_expr(__gmp_expr<__mpq_struct [1], __mpq_struct [1]>&&)':
main.cpp:(.text._ZN10__gmp_exprIA1_12__mpq_structS1_EC2EOS2_[_ZN10__gmp_exprIA1_12__mpq_structS1_EC5EOS2_]+0x3e): undefined reference to `__gmpq_init'
/tmp/ccQCHSmp.o: In function `__gmp_expr<__mpq_struct [1], __mpq_struct [1]>::~__gmp_expr()':
main.cpp:(.text._ZN10__gmp_exprIA1_12__mpq_structS1_ED2Ev[_ZN10__gmp_exprIA1_12__mpq_structS1_ED5Ev]+0x14): undefined reference to `__gmpq_clear'
/tmp/ccQCHSmp.o: In function `__gmp_expr<__mpq_struct [1], __mpq_struct [1]>::operator=(__gmp_expr<__mpq_struct [1], __mpq_struct [1]> const&)':
main.cpp:(.text._ZN10__gmp_exprIA1_12__mpq_structS1_EaSERKS2_[_ZN10__gmp_exprIA1_12__mpq_structS1_EaSERKS2_]+0x1f): undefined reference to `__gmpq_set'
/tmp/ccQCHSmp.o: In function `CGAL::Real_embeddable_traits<__gmp_expr<__mpq_struct [1], __mpq_struct [1]> >::To_interval::operator()(__gmp_expr<__mpq_struct [1], __mpq_struct [1]> const&) const':
main.cpp:(.text._ZNK4CGAL22Real_embeddable_traitsI10__gmp_exprIA1_12__mpq_structS3_EE11To_intervalclERKS4_[_ZNK4CGAL22Real_embeddable_traitsI10__gmp_exprIA1_12__mpq_structS3_EE11To_intervalclERKS4_]+0x2c): undefined reference to `mpfr_init2'
main.cpp:(.text._ZNK4CGAL22Real_embeddable_traitsI10__gmp_exprIA1_12__mpq_structS3_EE11To_intervalclERKS4_[_ZNK4CGAL22Real_embeddable_traitsI10__gmp_exprIA1_12__mpq_structS3_EE11To_intervalclERKS4_]+0x4f): undefined reference to `mpfr_set_q'
main.cpp:(.text._ZNK4CGAL22Real_embeddable_traitsI10__gmp_exprIA1_12__mpq_structS3_EE11To_intervalclERKS4_[_ZNK4CGAL22Real_embeddable_traitsI10__gmp_exprIA1_12__mpq_structS3_EE11To_intervalclERKS4_]+0x60): undefined reference to `mpfr_get_d'
main.cpp:(.text._ZNK4CGAL22Real_embeddable_traitsI10__gmp_exprIA1_12__mpq_structS3_EE11To_intervalclERKS4_[_ZNK4CGAL22Real_embeddable_traitsI10__gmp_exprIA1_12__mpq_structS3_EE11To_intervalclERKS4_]+0x8c): undefined reference to `mpfr_set_q'
main.cpp:(.text._ZNK4CGAL22Real_embeddable_traitsI10__gmp_exprIA1_12__mpq_structS3_EE11To_intervalclERKS4_[_ZNK4CGAL22Real_embeddable_traitsI10__gmp_exprIA1_12__mpq_structS3_EE11To_intervalclERKS4_]+0x9d): undefined reference to `mpfr_get_d'
main.cpp:(.text._ZNK4CGAL22Real_embeddable_traitsI10__gmp_exprIA1_12__mpq_structS3_EE11To_intervalclERKS4_[_ZNK4CGAL22Real_embeddable_traitsI10__gmp_exprIA1_12__mpq_structS3_EE11To_intervalclERKS4_]+0xb2): undefined reference to `mpfr_clear'
/tmp/ccQCHSmp.o: In function `CGAL::Handle::Handle(CGAL::Handle const&)':
main.cpp:(.text._ZN4CGAL6HandleC2ERKS0_[_ZN4CGAL6HandleC5ERKS0_]+0x46): undefined reference to `CGAL::precondition_fail(char const*, char const*, int, char const*)'
/tmp/ccQCHSmp.o: In function `CGAL::Handle::operator=(CGAL::Handle const&)':
main.cpp:(.text._ZN4CGAL6HandleaSERKS0_[_ZN4CGAL6HandleaSERKS0_]+0x46): undefined reference to `CGAL::precondition_fail(char const*, char const*, int, char const*)'
/tmp/ccQCHSmp.o: In function `CGAL::Mpzf::Mpzf(CGAL::Mpzf const&)':
main.cpp:(.text._ZN4CGAL4MpzfC2ERKS0_[_ZN4CGAL4MpzfC5ERKS0_]+0x8d): undefined reference to `__gmpn_copyi'
/tmp/ccQCHSmp.o: In function `CGAL::Mpzf::Mpzf(double)':
main.cpp:(.text._ZN4CGAL4MpzfC2Ed[_ZN4CGAL4MpzfC5Ed]+0x73): undefined reference to `CGAL::assertion_fail(char const*, char const*, int, char const*)'
/tmp/ccQCHSmp.o: In function `CGAL::operator==(CGAL::Mpzf const&, CGAL::Mpzf const&)':
main.cpp:(.text._ZN4CGALeqERKNS_4MpzfES2_[_ZN4CGALeqERKNS_4MpzfES2_]+0x84): undefined reference to `__gmpn_cmp'
/tmp/ccQCHSmp.o: In function `CGAL::Mpzf::aors(CGAL::Mpzf const&, CGAL::Mpzf const&, int)':
main.cpp:(.text._ZN4CGAL4Mpzf4aorsERKS0_S2_i[_ZN4CGAL4Mpzf4aorsERKS0_S2_i]+0xef): undefined reference to `__gmpn_copyi'
main.cpp:(.text._ZN4CGAL4Mpzf4aorsERKS0_S2_i[_ZN4CGAL4Mpzf4aorsERKS0_S2_i]+0x193): undefined reference to `__gmpn_copyi'
main.cpp:(.text._ZN4CGAL4Mpzf4aorsERKS0_S2_i[_ZN4CGAL4Mpzf4aorsERKS0_S2_i]+0x35f): undefined reference to `__gmpn_copyi'
main.cpp:(.text._ZN4CGAL4Mpzf4aorsERKS0_S2_i[_ZN4CGAL4Mpzf4aorsERKS0_S2_i]+0x3b0): undefined reference to `__gmpn_copyi'
main.cpp:(.text._ZN4CGAL4Mpzf4aorsERKS0_S2_i[_ZN4CGAL4Mpzf4aorsERKS0_S2_i]+0x40e): undefined reference to `__gmpn_copyi'
/tmp/ccQCHSmp.o:main.cpp:(.text._ZN4CGAL4Mpzf4aorsERKS0_S2_i[_ZN4CGAL4Mpzf4aorsERKS0_S2_i]+0x48a): more undefined references to `__gmpn_copyi' follow
/tmp/ccQCHSmp.o: In function `CGAL::Mpzf::aors(CGAL::Mpzf const&, CGAL::Mpzf const&, int)':
main.cpp:(.text._ZN4CGAL4Mpzf4aorsERKS0_S2_i[_ZN4CGAL4Mpzf4aorsERKS0_S2_i]+0x5ad): undefined reference to `__gmpn_add'
main.cpp:(.text._ZN4CGAL4Mpzf4aorsERKS0_S2_i[_ZN4CGAL4Mpzf4aorsERKS0_S2_i]+0x63b): undefined reference to `__gmpn_add'
main.cpp:(.text._ZN4CGAL4Mpzf4aorsERKS0_S2_i[_ZN4CGAL4Mpzf4aorsERKS0_S2_i]+0x95a): undefined reference to `__gmpn_copyi'
main.cpp:(.text._ZN4CGAL4Mpzf4aorsERKS0_S2_i[_ZN4CGAL4Mpzf4aorsERKS0_S2_i]+0x9d6): undefined reference to `__gmpn_neg'
main.cpp:(.text._ZN4CGAL4Mpzf4aorsERKS0_S2_i[_ZN4CGAL4Mpzf4aorsERKS0_S2_i]+0xa29): undefined reference to `__gmpn_sub_1'
main.cpp:(.text._ZN4CGAL4Mpzf4aorsERKS0_S2_i[_ZN4CGAL4Mpzf4aorsERKS0_S2_i]+0xad6): undefined reference to `__gmpn_neg'
main.cpp:(.text._ZN4CGAL4Mpzf4aorsERKS0_S2_i[_ZN4CGAL4Mpzf4aorsERKS0_S2_i]+0xb42): undefined reference to `__gmpn_sub'
main.cpp:(.text._ZN4CGAL4Mpzf4aorsERKS0_S2_i[_ZN4CGAL4Mpzf4aorsERKS0_S2_i]+0xb6d): undefined reference to `__gmpn_sub_1'
main.cpp:(.text._ZN4CGAL4Mpzf4aorsERKS0_S2_i[_ZN4CGAL4Mpzf4aorsERKS0_S2_i]+0xba6): undefined reference to `CGAL::assertion_fail(char const*, char const*, int, char const*)'
/tmp/ccQCHSmp.o: In function `CGAL::operator*(CGAL::Mpzf const&, CGAL::Mpzf const&)':
main.cpp:(.text._ZN4CGALmlERKNS_4MpzfES2_[_ZN4CGALmlERKNS_4MpzfES2_]+0x106): undefined reference to `__gmpn_mul'
main.cpp:(.text._ZN4CGALmlERKNS_4MpzfES2_[_ZN4CGALmlERKNS_4MpzfES2_]+0x159): undefined reference to `__gmpn_mul'
/tmp/ccQCHSmp.o: In function `CGAL::Triangulation_cw_ccw_2::ccw(int)':
main.cpp:(.text._ZN4CGAL22Triangulation_cw_ccw_23ccwEi[_ZN4CGAL22Triangulation_cw_ccw_23ccwEi]+0x4c): undefined reference to `CGAL::precondition_fail(char const*, char const*, int, char const*)'
/tmp/ccQCHSmp.o: In function `CGAL::Triangulation_cw_ccw_2::cw(int)':
main.cpp:(.text._ZN4CGAL22Triangulation_cw_ccw_22cwEi[_ZN4CGAL22Triangulation_cw_ccw_22cwEi]+0x4c): undefined reference to `CGAL::precondition_fail(char const*, char const*, int, char const*)'
/tmp/ccQCHSmp.o: In function `CGAL::get_default_random()':
main.cpp:(.text._ZN4CGAL18get_default_randomEv[_ZN4CGAL18get_default_randomEv]+0x2d): undefined reference to `CGAL::Random::Random()'
```

I am pretty sure this is a simple compilation error but I tried to include gmp via ```-lgmp``` or what do I wrong? 

Many thanks for your advice! Without your help I would have been lost already.

**Comment by jdumas** [comment]
Well first, 1) are you compiling with the CMake, 2) are you linking properly against the `igl::cgal` target (check the boolean tutorial for an example), and 3) can you try with libigl in header-only mode (if it's a template issue).

**Comment by AlessandroFasse** [comment]
Again many thanks for your help! I found now a solution using triangle_triangle_adjacency.h where I start with one intersection of an edge with the plane and then moving around on the mesh to computer further intersections. Of course these are then oriented and it onlt works for closed meshes. But I am satisfied with this! Thanks!

**Comment by RaduCorcodel** [comment]
@AlessandroFasse could you please paste the code that you used? It would be a great contribution to the thread.
Thanks in advanced.

**Comment by KaizhengLiu** [comment]
I have read the code about boolean operation in libigl, and from this I learn a lot. So I am very grateful @alecjacobson . In the meanwhile,  I make a little improvement that we can split solid meshes with open surfaces, illustrated by the following pictures. maybe this can help you @RaduCorcodel . 
![QQ图片20190313074501](https://user-images.githubusercontent.com/37786181/54263157-22f95300-45ab-11e9-9094-6630116b0b02.png)
![QQ图片20190313074546](https://user-images.githubusercontent.com/37786181/54263168-27be0700-45ab-11e9-947e-4703a0dd58e6.png)

**Comment by chitalu** [comment]
Given that this is still an open issue, there is a solution that solves all problems mentioned here. Its a library I wrote called MCUT. You can access here on Github: https://github.com/cutdigital/mcut 

maybe it could be made part of libigl if there is a demand.

**Comment by alecjacobson** [comment]
Looks great. Could you spell out the differences with igl::copyleft::cgal::mesh_boolean and igl::copyleft::cgal::trim_with_solid? Would be awesome to add any new functionality to libigl!

**Comment by chitalu** [comment]
There is general resemblance with "igl::mesh_boolean" and " igl::trim_with_solid" but MCUT is not restricted to solids. Moreover, MCUT is built as a 'cutting' tool, catering to open and closed meshes by working with halfedge connectivity. This is different from PWN [Zhou et al. 2016] which--though great for solids--will only permit working with solids as in igl::trim_with_solid. 

MCUT supports partial (non-through) cuts, and open-surface to open-surface cutting.

An input-mesh for MCUT is a manifold N-gon mesh that is a single connected component. Triangulated inputs are merely a special case. Meshes are however expected to be clean: the intersected/cutting faces of a given input-mesh must not be involved in a self-intersection (but non-intersecting faces can be).

**Partial cut**

![image](https://user-images.githubusercontent.com/7461679/119961683-3cc1bd80-bf9e-11eb-9181-11c1ed89e676.png)
![image](https://user-images.githubusercontent.com/7461679/119961723-464b2580-bf9e-11eb-835c-20a296817cc8.png)

**Trim with surface (instead of just "trim_with_solid")**

![image](https://user-images.githubusercontent.com/7461679/119962006-87433a00-bf9e-11eb-852a-d9585965f0f1.png)

**Open-surface to open-surface cutting**

![image](https://user-images.githubusercontent.com/7461679/119962241-bf4a7d00-bf9e-11eb-97f7-479613c1ee08.png)

**Boolean op with intermediate results**

Inputs:
![sphere](https://user-images.githubusercontent.com/7461679/119962893-692a0980-bf9f-11eb-8846-b6631306ae91.png)
![torus](https://user-images.githubusercontent.com/7461679/119962944-73e49e80-bf9f-11eb-8ca0-f34995e74e23.png)

Outputs:
![intersection](https://user-images.githubusercontent.com/7461679/119962995-8068f700-bf9f-11eb-8870-89374d9296d1.png)
![patches](https://user-images.githubusercontent.com/7461679/119962998-819a2400-bf9f-11eb-8fe0-28a6fc7d147b.png)
![sphere-not-torus](https://user-images.githubusercontent.com/7461679/119963003-8232ba80-bf9f-11eb-891f-3dbd5b05814d.png)
![sphere-unsealed](https://user-images.githubusercontent.com/7461679/119963005-82cb5100-bf9f-11eb-95fd-966b3b83f455.png)
![torus-not-sphere](https://user-images.githubusercontent.com/7461679/119963006-8363e780-bf9f-11eb-936b-79f335040b2d.png)
![union](https://user-images.githubusercontent.com/7461679/119963007-8363e780-bf9f-11eb-9fac-099d3d12ced8.png)

Perhaps it could be added in due course.

**Comment by jdumas** [comment]
This looks really cool. The MCUT website mentions a publication discussing the technique, but I cannot find it anywhere. Is it still unpublished?

**Comment by alecjacobson** [comment]
Very nice, @chitalu !

**Comment by chitalu** [comment]
> This looks really cool. The MCUT website mentions a publication discussing the technique, but I cannot find it anywhere. Is it still unpublished?

Thanks. Happy to contribute in due course.

The MCUT website needs some updates. The referenced paper has already been published (EG2020).
Here is the URL: https://onlinelibrary.wiley.com/doi/abs/10.1111/cgf.13953
PDF: http://www.ipab.inf.ed.ac.uk/cgvu/xfem.pdf

There has been a good amount of updates to the core algorithm since the publication date (turned into a project of its own).

**Comment by jdumas** [comment]
Thanks for the reference!
