### ISSUE TITLE
Embree 3 

### ISSUE THREAD

**Issue by csverma610** [libigl/libigl#852]
Hello, 
It seems "libigl" still uses embree2. Is there a way to use the latest embree3.* ?

**Comment by jdumas** [comment]
Yes there is a pending pull-request to update libigl to use Embree 3. See #834. Unfortunately there were still some bugs preventing its use in libigl, so it looks like you'll need to wait for Embree 3.3 so they get fix.

**Comment by jdumas** [comment]
Embree 3 is in the dev branch since #947
