### ISSUE TITLE
CoMISO library link.

### ISSUE THREAD

**Issue by csverma610** [libigl/libigl#853]
Hello,
I compiled CoMISo library. I also installed gmm++ software and using OpenBlas library 
However, I get the following message which is difficult to understand.

g++ -o events main.o -L/home/Disk/Software/Graphics/GLFW/GLAD/lib -lglad -L/home/Disk/Software/Graphics/GLFW/V3.2.1/lib -lglfw -lpthread -lGL  /home/Disk/Software/Mesh/LibIGL/external/CoMISo/libCoMISo.a -L/home/Disk/Software/MathLibs/OpenBLAS/V2.20/lib -lopenblas
main.o: In function `igl::copyleft::comiso::NRosyField::solveRoundings()':
main.cpp:(.text._ZN3igl8copyleft6comiso10NRosyField14solveRoundingsEv[_ZN3igl8copyleft6comiso10NRosyField14solveRoundingsEv]+0x4ab): undefined reference to `void COMISO::ConstrainedSolver::solve<gmm::row_matrix<gmm::wsvector<double> >, gmm::col_matrix<gmm::wsvector<double> >, std::vector<double, std::allocator<double> >, std::vector<int, std::allocator<int> > >(gmm::row_matrix<gmm::wsvector<double> >&, gmm::col_matrix<gmm::wsvector<double> >&, std::vector<double, std::allocator<double> >&, std::vector<double, std::allocator<double> >&, std::vector<int, std::allocator<int> >&, double, bool, bool)'
main.o: In function `igl::copyleft::comiso::PoissonSolver<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<int, -1, -1, 0, -1, -1> >::MixedIntegerSolve(double, bool, int)':
main.cpp:(.text._ZN3igl8copyleft6comiso13PoissonSolverIN5Eigen6MatrixIdLin1ELin1ELi0ELin1ELin1EEENS4_IiLin1ELin1ELi0ELin1ELin1EEEE17MixedIntegerSolveEdbi[_ZN3igl8copyleft6comiso13PoissonSolverIN5Eigen6MatrixIdLin1ELin1ELi0ELin1ELin1EEENS4_IiLin1ELin1ELi0ELin1ELin1EEEE17MixedIntegerSolveEdbi]+0xd8f): undefined reference to `void COMISO::ConstrainedSolver::solve<gmm::row_matrix<gmm::wsvector<double> >, gmm::col_matrix<gmm::wsvector<double> >, std::vector<double, std::allocator<double> >, std::vector<int, std::allocator<int> > >(gmm::row_matrix<gmm::wsvector<double> >&, gmm::col_matrix<gmm::wsvector<double> >&, std::vector<double, std::allocator<double> >&, std::vector<double, std::allocator<double> >&, std::vector<int, std::allocator<int> >&, double, bool, bool)'
collect2: error: ld returned 1 exit status
Makefile:16: recipe for target 'events' failed
make: *** [events] Error 1

**Comment by jdumas** [comment]
Maybe a bit more context would help. Are you building the tutorials, the libigl-example-project, something else? What's your setup? Are you building in header-only mode, or using the static library? Are you linking your executable against `igl::comiso` in the CMake? From the look of it, I'd say one of the last two may be responsible for your error.

**Comment by csverma610** [comment]
Hello Jeremie,

Everything works. Thanks for your feedback.

Now I use CMake and not my own makefiles to build tutorials.
