### ISSUE TITLE
Set texture for a .obj file whose number of uv is less than the number of vertexes

### ISSUE THREAD

**Issue by Bachery** [libigl/libigl#860]
I tried to set the texture for .obj files. Their uv are all less than the number of vertexes, while the function `viewer.data().set_uv()` requires them to be equal. How can I set textures for those .obj files?

Here is my code:
```
  Eigen::MatrixXd V, TC, N, FTC, FN;
  Eigen::MatrixXi F;
  igl::readOBJ("../objects/snowman/snowman.obj", V, TC, N, F, FTC, FN);
  igl::png::readPNG("../objects/snowman/snowman.png", R,G,B,A);

  std::cout << "V  rows: " << V.rows() << std::endl;
  std::cout << "UV rows: " << TC.rows() << std::endl;

  igl::opengl::glfw::Viewer viewer;

  viewer.data().set_mesh(V, F);
  viewer.data().set_normals(FN);
  viewer.data().set_uv(TC);

  viewer.data().show_lines = false;
  viewer.data().show_texture = true;

  viewer.data().set_texture(R,G,B);
  
  viewer.launch();
```

And the output:

```
  V  rows: 43152
  UV rows: 33198

  ERROR (set_UV): Please provide uv per vertex.
```

**Comment by alecjacobson** [comment]
In this case, it must be that your uv's use a different face indexing matrix so you should call the [set_uv(UV_V,UV_F)](https://libigl.github.io/dox/classigl_1_1opengl_1_1ViewerData.html#a2ce2dbe479d1f212ae038b929ff06944) overload
