### ISSUE TITLE
Viewer callback functions as class methods

### ISSUE THREAD

**Issue by RaduCorcodel** [libigl/libigl#865]
This is probably more a C++ question rather than specific for `libigl` but I would like to try this:

Let's say I want to implement a couple methods `foo` in a class that also launches the Viewer and in main.cpp I simply instantiate the Operations class.

```
class Operations{
public:
    Operations();
    ~Operations();
private:
    int foo(double a);
private:
    igl::opengl::glfw::Viewer viewer_;
};
```
Now here's the kicker, I would like to register the mouse and keyboard callbacks as methods of this class. I could do:
```
private:
    static bool key_down(igl::opengl::glfw::Viewer& viewer, unsigned char key, int modifier);
    static bool mouse_down(igl::opengl::glfw::Viewer& viewer, int button, int modifier);
```
And use them in the `Operations` constructor like so:
```
viewer_.callback_key_down = &Operations::key_down;
viewer_.callback_mouse_down = &Operations::mouse_down;
```
but in this case, I will not be able to use the non-static method `foo` from inside the static `key_down` and `mouse_down`. Sample would look like:
```
// This will not compile
bool Operations::mouse_down(igl::opengl::glfw::Viewer& viewer, int button, int modifier)
{
    double x,y;
    if (modifier == 1 && button == 0) //Modifier=1:Shift key
    {
        int ret = foo(1.2);
        //Do something with ret
        return true;
    }
  return false;
}
```
I looked on other forums but I couldn't get a satisfactory answer... I guess the TL;DR question is how to implement the callbacks as regular, non-static methods?

Many thanks, any suggestion is welcomed.

**Comment by jdumas** [comment]
Hi,

If you want to use a class and register methods as callbacks, I would suggest to implement your class as a `ViewerPlugin`. Take a look at `opengl/glfw/ViewerPlugin.h` and for an example of an actual plugin `opengl/glfw/imgui/ImGuiMenu.h`.
