### ISSUE TITLE
Debugging igl::decimate takes way too long on MSVC

### ISSUE THREAD

**Issue by aseverino** [libigl/libigl#866]
I have tried moving the code to another file which will be compiled with optimization -O2, NDEBUG, and no symbols, but still no satisfying results.

Executing decimation on a mesh with 100k faces with 50k as goal takes 1.5 seconds in Release, but takes 25 minutes (really) in Debug. What can I do to improve performance and be able to debug my application with decimation in it?

I read that Eigen runs much better with predefined matrices and vectors, so I tried replacing `MatrixXd` with `MatrixX3d` (and so on), but `igl::decimate` doesn't support fixed sized matrices.

**Comment by jdumas** [comment]
Well, Eigen is notoriously slow in Debug, maybe even more so on Windows. If you *really* need to run the debugger on a large input model, you can try to compile in `RelWithDebInfo` in MSVC. This won't trigger Eigen's assertions, but should allow you to step into the debugger and keep track of the call stack.
