### ISSUE TITLE
Generate a sphere

### ISSUE THREAD

**Issue by AlessandroFasse** [libigl/libigl#867]
Hey everybody, 
does anyone have an idea to generate a sphere with a given center, radius and nr_faces?
First I tought of producing a box, then splitting the edges and the normalizing every vertex to the given radius + in the end shifting the output. However, there is no function for splitting edges, if I guess right. 

But maybe there is a better approach that I overlooked. What are your thoughts? Thanks :)

**Comment by jdumas** [comment]
If you just want to create one mesh you can use meshlab to create a sphere and then export it. If you want to create it programmatically in C++ you can take a look at [this code](https://github.com/avaxman/libdirectional/blob/master/include/directional/point_spheres.h).

**Comment by AlessandroFasse** [comment]
Many thanks! I managed to create a sphere by using polar coordinates. Therefore you can close the issue and if you want I can provide the code snippet.

**Comment by jdumas** [comment]
Please feel free to post a snippet, it may be always useful for other people.
