### ISSUE TITLE
error in compiling hello.cpp

### ISSUE THREAD

**Issue by amiltonwong** [libigl/libigl#869]
Hi, all,

After I download the libigl and writing `hello.cpp`, I got this compile [error](https://gist.githubusercontent.com/amiltonwong/15479d7976cb083a4154aed676d28934/raw/da346bc8f8b98f253603ee08aaa7efa8a0fbf52d/error_log).

Could someone suggest how to fix it? It seems the issue is related to the version of eigen3 or the version of g++.

My system info is as follows: 
ubuntu 14.04
g++: 5.5.0
eigen: 3.3.5

THX!

**Comment by amiltonwong** [comment]
Supplement:
Then, I downgrade g++ version as 4.8.4. The compilation process succeeds.

Does the libigl require a bit older version of g++, such as g++ 4.8?

**Comment by jdumas** [comment]
You should link with `-lpthread`. Beware that gcc has some problems with CGAL. Otherwise it is recommended to use the bundled libraries (Eigen 3.2) to avoid further trouble. Building with CMake also ensures you have all the correct flags set up (such as `-lpthread`).

**Comment by amiltonwong** [comment]
Hi, @jdumas ,
Thanks for your answer. It works, after appending `-lpthread` at the end of compile command.
BTW, you also mentioned a CMakeList.txt for cmake building. Did you mean this [one](https://github.com/libigl/libigl-example-project/blob/master/CMakeLists.txt)? However, I couldn't find any pthread options in it. Could you give an example for general CMakeLists.txt for cmake building?

THX!

**Comment by jdumas** [comment]
Take a look at the [libigl-example-project](https://github.com/libigl/libigl-example-project) for an example of working setup. In CMake, `pthread` is linked against all libigl module via [this line](https://github.com/libigl/libigl/blob/382c3a911a786d122a6ff7a8d7da4570c1966c79/shared/cmake/libigl.cmake#L109), so that is also works on Windows and macOS.
