### ISSUE TITLE
PyIgl: How does libigl::eigs compare with scipy.sparse.linalg.eigs?

### ISSUE THREAD

**Issue by r03ert0** [libigl/libigl#870]
I am trying to use scipy for spectral decomposition of a laplacian, but I don't get the same results. This is the python code using libigl.eigs:

```
import pyigl as igl
V = igl.eigen.MatrixXd()
F = igl.eigen.MatrixXi()
U = igl.eigen.MatrixXd()
D = igl.eigen.MatrixXd()
L = igl.eigen.SparseMatrixd()
M = igl.eigen.SparseMatrixd()
igl.readOFF(TUTORIAL_SHARED_PATH + "beetle.off", V, F)
igl.cotmatrix(V, F, L)
L = -L
igl.massmatrix(V, F, igl.MASSMATRIX_TYPE_DEFAULT, M)
k = 5
if not igl.eigs(L, M, k + 1, igl.EIGS_TYPE_SM, U, D):
    print("Eigs failed.")
print(D)
```

The eigenvalues are:
```
     47.7116
     27.9209
     19.2998
     14.6074
     7.50988
-1.26248e-13
```

Now, this is the code to convert the L and M matrices to scipy sparse matrices and use scipy.sparse.linalg.eigs:

```
from iglhelpers import *
from scipy.sparse.linalg import eigs
from scipy.sparse import csc_matrix
pL=csc_matrix(e2p(L))
pM=csc_matrix(e2p(M))
vals, vecs = eigs(pL,6,pM,tol=1e-10)
print(vals)
```

The eigenvalues are:
`array([-1.72822106e+08+0.j, -1.72822547e+08+0.j, -3.58186645e+07+0.j,-3.56162852e+07+0.j, -2.84866885e+07+0.j, -2.84702535e+07+0.j])`

By the way, these are the same values I obtain using Spectra (see issue #89).

What do I need to do to replicate the behaviour of igl::eigs??

Thanks in advance!

**Comment by alecjacobson** [comment]
`igl::eigs` is a poor man's sparse Eigen decomposition. It should be well behaved for the first non-trivial Eigen pair if there's no multiplicity. Beyond that it's asking a lot of its simple power iterations. A dedicated Eigen solver should be much better (e.g., Arpack or Spectra).

I've witnessed very poor behaviour of `scipy.sparse.linalg.eigs` in past projects. Maybe it works, but I haven't been impressed.

The values you're getting are very large which makes me think that you're getting the 6 _largest_ eigenvalues rather than the 6 _smallest_. Maybe it's an easy fix, but outside the scope of a libigl issue.

**Comment by r03ert0** [comment]
Thank you @alecjacobson! In scipy's doc they say that their `eigs` function is just a wrapper for ARPACK... so it seems I'm getting the same results with ARPACK (through scipy) and Spectra.

Also, if I set to find for the smallest magnitude eigenvalues, the code runs for ages and then gives me values very close to 0...

I looked into the `eigs.cpp` code, and I see that the matrix M is being rescaled (the diagonal values for `beetle.off` are of the order of 1e-5) to max=1 using 

```
  // Rescale B for better numerics
  const Scalar rescale = std::abs(iB.diagonal().maxCoeff());
  const Eigen::SparseMatrix<Btype> B = iB/rescale;
```

I rescaled the M matrix similarly in my python code (`pM=pM/pM.max()`), and now the eigenvalues I get are: `32864.30662135+0.j, 32864.39045123+0.j,  6811.37151536+0.j,
        6772.88653625+0.j,  5417.1036694 +0.j,  5413.97834897+0.j`. Still larger and still repeated... I'll keep digging.

**Comment by r03ert0** [comment]
Thank you @jdumas !
So it's better to use shift-invert of mat = inv(M)*L instead of the generalised eigenvalue problem solver for L and M separate? (there doesn't seem to be a shift solver for SymGEigsSolver)

**Comment by jdumas** [comment]
Ah, right you're trying to solve a generalized eigenvalue problem. I am not sure that the same trick will help you in this case. Probably you're better off asking the Spectra guys directly.

**Comment by jdumas** [comment]
I suggest you should take the issue to the authors of Spectra then.

**Comment by r03ert0** [comment]
I'll do. Thank you for your help!
