### ISSUE TITLE
Adding py_igl/py_hessian_energy.py and tutorial 712

### ISSUE THREAD

**Issue by r03ert0** [libigl/libigl#871]
hello!
There's currently no python wrapper for hessian_energy.h (and others), and no python version of tutorial 712 (and several others at the end of the list).
Can I give it a try and write the wrapper? Or is there a particular difficulty that I need to be aware of?
thanks!
roberto

**Comment by jdumas** [comment]
I don't think there's any limitation. If you want to adapt the python wrappers to cover those tutorials feel free to do so =)

**Comment by teseoch** [comment]
hessian_energy is part of the new bindings https://libigl.github.io/libigl-python-bindings/
