### ISSUE TITLE
boundary_loop.h return loops that are no loops

### ISSUE THREAD

**Issue by alessandrofasse** [libigl/libigl#873]
I have the following problem: 
I have a mesh and I usethe following code snippet
```
std::vector<std::vector<int>> compute_longest_boundary_loop(){
        std::vector<std::vector<int>> loop;
        igl::boundary_loop(faces, loop); 
        return loop;
    }
```
However, when I loop at ever list inside of the first std::vector i do not even get list. Example outputs are 
```
[4, 8, 13, 9, 7]
[223]
``` 
So sometimes he also only detects single points as a boundary loop. What is going wrong? Am I doing something bad here?

In order to further understand what is going on I considered the following example. 

[igl_example.pdf](https://github.com/libigl/libigl/files/2293348/igl_example.pdf)

From this I get the faces 
```
faces = [[0, 2, 1], [0, 3, 2], [4, 2, 5]]
```
and if I call the above method I get
```
loop = [[0, 3, 1, 2, 4, 5]]
```
which makes for me no sense because it is not a loop and also there exists no edge between 3 and 1. 

Any suggestions?

**Comment by jiangzhongshi** [comment]
`igl::boundary_loop` is implemented through triangle_triangle_adjacency, which based on the assumption that the mesh is manifold. 

As in the image you posted, point 2 is a single point connecting two parts of the mesh and is not manifold. In this case, the implementation wouldn't give the correct answer.

See also,
https://en.wikipedia.org/wiki/Manifold
https://knowledge.autodesk.com/support/maya-lt/learn-explore/caas/CloudHelp/cloudhelp/2015/ENU/MayaLT/files/Polygons-overview-Twomanifold-vs--nonmanifold-polygonal-geometry-htm.html

**Comment by AlessandroFasse** [comment]
May thanks for the hint! That explains a lot. 

Is there a way to remove non-manifold edges so that I get a closed loop? 

I tried ```igl::extract_mainfold_patches``` to just get faces that define a manifold patch. However, if I call the boundary_loop on the ne set of vertices I again get no closed loop and one can see some of these non-manifold crossings as in my image.

**Comment by jiangzhongshi** [comment]
It's easy to identify remove non manifold edges/vertices, but you end up with separate meshes and that's what `igl::extract_mainfold_patches` would achieve. 

If you still want to have a single loop that's taking care of non-manifoldness, to return [0 3 2 5 4 2 1] for the given image, (if this is what you want), then it's not implemented.
