### ISSUE TITLE
Cannot use "igl:slice()" or "igl:slice_into()" with mixed sparse and dense matrix as input

### ISSUE THREAD

**Issue by ramirezaa** [libigl/libigl#88]
I am trying to use the `igl::slice()` and `igl::slice_into` method in order to replicate the following `Matlab` operations:

```
1. B = A(I,J)  => igl::slice(A,I,J,B)
2. B(I,J) = A  => igl::slice_into(A,I,J,B)
```

For the first bullet, matrix `A` is an `Eigen::SparseMatrix<float>` populated with triplets. Then, matrix `B` is an `Eigen::MatrixXf`. When I attempt to do `igl::slice(A,I,J,B)`, I get the following error:

```
error: no matching function for call to ‘slice(Eigen::SparseMatrix<float>&, Eigen::VectorXi&, Eigen::VectorXi&, Eigen::MatrixXf&)’
```

And when I attempt to do `igl::slice_into(A,I,J,B)`, I get the following error:

```
error: no matching function for call to ‘slice_into(Eigen::MatrixXf&, Eigen::VectorXi&, Eigen::VectorXi&, Eigen::SparseMatrix<float>&)’
```

Is there a way to work around this? Do I need to supply two matrices of the same type in order to succesfully use `igl::slice` and `igl::slice_into`? Do these functions work for sparse matrices?

Any suggestions would be greatly appreciated.

**Comment by alecjacobson** [comment]
Yes, for now they must be the same type. It's easy then to cast sparse to
dense afterward:

D = (MatrixXf)S;

or dense to sparse

S = D.sparseView();

**Comment by ramirezaa** [comment]
I will try that. Thank you!
