### ISSUE TITLE
Passing motion parameters to swept_volume transform

### ISSUE THREAD

**Issue by RaduCorcodel** [libigl/libigl#882]
I would like to create swept volumes (pure translation) by passing the translation vector as a parameter.
What would be the best way to modify example 707 so that the function handle also accepts say an Eigen::Vector3d?

Thank you in advance

**Comment by Aniwax** [comment]
Is there an update on this issue?

**Comment by alecjacobson** [comment]
Change this part
```cpp
  // Define a rigid motion
  const auto & transform = [](const double t)->Eigen::Affine3d
  {
    Eigen::Affine3d T = Eigen::Affine3d::Identity();
    T.rotate(Eigen::AngleAxisd(t*2.*igl::PI,Eigen::Vector3d(0,1,0)));
    T.translate(Eigen::Vector3d(0,0.125*cos(2.*igl::PI*t),0));
    return T;
  };
```
to _capture_ your vector and then just use translate.

Alternatively you could compute a sweep along a translation _exactly_ using `minkowski_sum`
