### ISSUE TITLE
[python] Error message too long when a large matrix involved.

### ISSUE THREAD

**Issue by jiangzhongshi** [libigl/libigl#883]
When calling `igl.grad(V,F,G)` and if `type(F): igl.eigen.MatrixXd`

Python interpreter would print the following error message:
```
TypeError: grad(): incompatible function arguments. The following argument types are supported:
1.  (V: pyigl.eigen.MatrixXd, F: pyigl.eigen.MatrixXi, G: pyigl.eigen.SparseMatrixd)
Invoked with 
(printing whole V)
(printing whole F)
(printing whole G)
```

When V/F/G is large, the message would long exceed the buffer of my terminal or require a lot of effort to scroll. 

A suggestive solution would be to implement `__repr__` in numpy way.

**Comment by teseoch** [comment]
You can use the new version of the bindings https://libigl.github.io/libigl-python-bindings/ which are compatible with numpy
