### ISSUE TITLE
Calculating smallest eigenvalue/eigenvector of a sparse matrix like in Matlab

### ISSUE THREAD

**Issue by ramirezaa** [libigl/libigl#89]
Matlab has the the `eigs()` function that calculates the eigenvalue/eigenvector pairs, and it has the option to obtain the eigenvalue/eigenvector's that have the smallest magnitude. I am attempting to do something similar with C++  for sparse matrices and I was wondering if this was possible with `libigl`? If `libigl` cannot help, do you have any recommendations as to how to approach this problem with other libraries?

Anything helps. Thanks!!

**Comment by alecjacobson** [comment]
The ideal solution is to use ARPACK, to which Eigen has [(unsupported) bindings])http://eigen.tuxfamily.org/dox-devel/unsupported/group__ArpackSupport__Module.html). The less ideal but possibly OK solution is to [call Matlab's `eigs` function](http://libigl.github.io/libigl/tutorial/tutorial.html#mixingmatlabcode). A third option which really might be ok if you only want the smallest few eigen modes is to _roll your own_ and implement the most basic form of Arnoldi iterations. This is actually not so hard to do if you're not paranoid about getting the most efficient solution.

**Comment by alecjacobson** [comment]
`igl::eigs` (mirroring matlab) exists in 4d64fb8333a4eea1f17b1390ddd17a4ae45015fc and there is a related [tutorial entry](http://libigl.github.io/libigl/tutorial/tutorial.html#eigendecomposition)

I'd still recommend using ARPACK for performance and robustness reasons.

**Comment by r03ert0** [comment]
Hi @alecjacobson,
could you provide an example of how to use ARPACK as a replacement for igl::eigs?
thank you in advance!

**Comment by r03ert0** [comment]
by the way, I tried Spectra, but I can't get the same values as libigl::eigs... This is my code (I'm using the beetle mesh)

```
  igl::readPLY("../data/beetle.ply",V,F,N,UV);
  SparseMatrix<double> L,M;
  igl::cotmatrix(V,F,L);
  L = (-L).eval();
  massmatrix(V,F,MASSMATRIX_TYPE_DEFAULT,M);

  size_t k = 5; // trying to get 5 eigenvectoss

  // USING libigl::eigs
  //------------------
  if(!eigs(L,M,k+1,EIGS_TYPE_SM,U,D)) cout<<"\nfailed: Libigl"<<endl;
  else cout<<"\nsuccess: Libigl"<<endl;

 // display evals
  cout<<"evals: "<<D.rows()<<","<<D.cols()<<endl;
  for(i=0;i<k;i++)
    cout<<D.row(i)<<endl;

  // USING SPECTRA
  //-----------------
  SparseSymMatProd<double> Lop(L);
  SparseCholesky<double> Mop(M);
  SymGEigsSolver<double, LARGEST_MAGN, SparseSymMatProd<double>, SparseCholesky<double>, GEIGS_CHOLESKY> geigs(&Lop, &Mop, k+1, 3*k);
  geigs.init();
  int nconv = geigs.compute();
  Eigen::VectorXd evals;
  Eigen::MatrixXd evecs;
  if(geigs.info() == SUCCESSFUL)
  {
      cout<<"\nsuccess: Spectra"<<endl;
      evals = geigs.eigenvalues();
      evecs = geigs.eigenvectors();

      // display evals
      cout<<"evals: "<<evals.rows()<<","<<evals.cols()<<endl;
      for(i=0;i<k;i++)
          cout<<evals(i)<<endl;
  }
  else
      cout<<"\nfailed: Spectra"<<endl;
```

The list of eigenvalues using libigl::eigs is:
```
47.7116
27.9209
19.2998
14.6074
7.50989
```

And the list of eigenvalues using Spectra is:
```
1.72182e+08
1.72181e+08
3.57004e+07
3.54983e+07
2.84747e+07
2.84712e+07
```
They are much larger, come in pairs, and plotting the eigenvectors on the beetle mesh just shows a single colour (no variation). I tried using `SMALLEST_MAGN` instead of `LARGEST_MAGN`, but the code just never converges.

**Comment by alecjacobson** [comment]
I've never used Spectra, but I heard it was good...

It's been a long while since I've used ARPACK. I don't remember how to use
it. I thought there were (unsupported) Eigen wrappers now...

**Comment by r03ert0** [comment]
thank you for your answer!
I'm trying to use scipy's wrapper to ARPACK now, and realised that the values that I get using Spectra are the same as those I get using Scipy.sparse.linalg.eigs.... so, it seems that I'm not correctly understanding what libigl::eigs does :(

**Comment by unclejimbo** [comment]
@r03ert0 I think you might want to try the shift-and-invert solvers in Spectra to calculate the smallest eigenvalues and eigenvectors. Here's an example to decompose a sparse Laplacian matrix I wrote in my own library, https://github.com/unclejimbo/Euclid/blob/dev/include/Euclid/Analysis/src/HKS.cpp

**Comment by stigersh** [comment]
> 

Hi, 
can anyone post an example using spectra? The link above with HKS is broken, does igl::spectra exist? I cannot find any example with it..
Thanks!
