### ISSUE TITLE
igl::slice_into doesn't accept Eigen::SparseView

### ISSUE THREAD

**Issue by lawsonfulton** [libigl/libigl#890]
I'm trying to slice from a dense matrix into a sparse matrix, which is not supported by `slice_into`.

I've tried calling:
`igl::slice_into(denseMat.sparseView(), I, 1, sparseMat);`

However it fails to compile unless I explicitly convert it to a SparseMatrix:
`igl::slice_into(SparseMatrix<double>(denseMat.sparseView()), I, 1, sparseMat);`

**Comment by jdumas** [comment]
Are you compiling in header-only mode? If not, then it's normal that it fails as the specific function signature you are looking for has probably not been instantiated.

**Comment by alecjacobson** [comment]
@zero-impact can you post the compilation error?

I'm guessing that templating on SparseMatrix<T> is not enough here. Not sure what the base type (if any) should be to accept SparseView

**Comment by jdumas** [comment]
Right, esp. as the type of the first `slice_into` function takes a `const SparseMatrix<T> &` as an argument, so I'm guessing implicit conversion (copy) should be allowed to happen.

**Comment by alecjacobson** [comment]
Ah. I think it should just be `Eigen::SparseMatrixBase<T>`

@jdumas we should consider making this consistent for all SparseMatrix **_input_** (non-resizable) arguments.

reference test code:

```
#include <Eigen/Core>
#include <Eigen/Sparse>
#include <iostream>

template <typename T>
void sizes(const Eigen::SparseMatrixBase<T> & S)
{
  std::cout<<S.rows()<<" "<<S.cols()<<std::endl;
}

int main()
{
  Eigen::SparseMatrix<double> S(10,10);
  Eigen::MatrixXd D(10,10);
  sizes(D.sparseView());
  sizes(S);
}

```

**Comment by alecjacobson** [comment]
I'm not 100% convinced that it will be safe to change all `SparseMatrix` input types to `SparseMatrixBase` in libigl functions. I'm also not sure it's important to support `dense.sparseView()` as inputs to begin with. There are lots of gotchas already when supported un-evaluated Eigen _expressions_ as input. My inclination is to leave this as is unless someone clamours for it.
