### ISSUE TITLE
Help in example 304

### ISSUE THREAD

**Issue by csverma610** [libigl/libigl#894]
Hello,
Can someone explain the example 304:

  // Two fixed points
  VectorXi b(2,1);
  // Left hand, left foot
  b<<4331,5957;
  VectorXd bc(2,1);
  bc<<1,-1;

What are bc values? I was thinking that these are coordinates, but then there should be
four as there are two values of "b".

**Comment by alecjacobson** [comment]
`bc` contains the fixed value constraints. So the solution `Z` will satisfy `Z(b(i)) == bc(i)`.
