### ISSUE TITLE
Question about libIGL capabilities

### ISSUE THREAD

**Issue by manavbhatia** [libigl/libigl#898]
Hi, 

   Are the tutorials here: http://libigl.github.io/libigl/tutorial/ the complete list of capabilities of libigl? I am hoping to find some guidance on tasks that can be accomplished with libigl, and how this compares with Cgal. 

Thanks!
Manav

**Comment by jdumas** [comment]
Hi. Not there are some functions that are not featured in any tutorial yet. Usually I just browse the list of functions on github or search the repo to see if there's something that might do what I want before implementing my own stuff.

**Comment by manavbhatia** [comment]
Thanks!
