### ISSUE TITLE
 topology operations for mesh

### ISSUE THREAD

**Issue by fool1025** [libigl/libigl#9]
It will be perfect to add the function of basic topology operations (such as split, flips, collapse, et. al) for mesh.

**Comment by alecjacobson** [comment]
As of version 1.1.4 there is support for edge-collapses (e.g. for mesh decimation) for closed manifold meshes.

**Comment by alecjacobson** [comment]
there are now also methods for edge-flipping. global remeshing and remeshing during deformation are larger endeavors that I have no immediate plans to integrate them, but the foundations are here.
