### ISSUE TITLE
Question: compute edges in faces

### ISSUE THREAD

**Issue by cap257zero** [libigl/libigl#90]
Is there a function that computes the edges in each face? For example if (V,F) is the mesh, the function would record values in a #F by 3 matrix where row i contains the three indices (coming from E in igl::edges(F,E)) of the edges in that face.

Just curious. I looked and did not find one, but maybe I missed it; igl::edge_flaps seems close. I wrote one myself but I wonder if it's a lot slower than it needs to be. Thank you.

**Comment by alecjacobson** [comment]
`igl::unique_edge_map` is exactly what you want. See the `EMAP` output
(it's a column vector version of your desired #F by 3 matrix of indices.

**Comment by cap257zero** [comment]
Great, thanks a lot!
