### ISSUE TITLE
rendering an animation sequence is very slow

### ISSUE THREAD

**Issue by etrigger** [libigl/libigl#901]
I load an animation sequence from OBJ files and keep all OBJ files in a vector.

I set the following settings:
viewer.core.is_animating = true;
viewer.core.animation_max_fps = 30.;

In the pre_draw function, I set the mesh with one of the OBJ files in the vector. However, it seems to be very slow to render each object file. I checked the "405_AsRigidAsPossible/main.cpp", which runs in a good framerate.

Any idea why my implementation is so slow and how to fix it?

**Comment by jdumas** [comment]
Well how big is your mesh? Also in tutorial 205 only the vertices are updated and sent to the GPU at every frame, so it might help not sending too much data at once.

**Comment by etrigger** [comment]
It's around 18000 vertices and  30000 faces for each obj file.

**Comment by jdumas** [comment]
Depending on your graphics card that shouldn't be so slow. You can post a minimal example so we can try it on our side.

**Comment by timkarlo** [comment]
Hi. I am asked to go on a similar project for VR. Have you managed the performance? How far are you with your project?
