### ISSUE TITLE
Error while building with Visual Studio

### ISSUE THREAD

**Issue by larsbrubaker** [libigl/libigl#904]
Anyone have an idea what to try next. I followed all the instructions on building and got this far.
Seems to be a problem with Eigen library and STL.
Thanks in advance.

Here is the error I am getting. 

Error	C2039	'_Insert_n': is not a member of 'std::vector<Eigen::internal::workaround_msvc_stl_support<T>,Eigen::aligned_allocator_indirection<Eigen::internal::workaround_msvc_stl_support<T>>>'	igl	c:\development\libigl2\libigl\external\eigen\eigen\src\stlsupport\stdvector.h	85

**Comment by jdumas** [comment]
What version of MSVC do you have?

**Comment by larsbrubaker** [comment]
15.8.1 

15.8.5 is available, but I have updated to that with my work computer and it is having the same problem.

Thanks again.

![image](https://user-images.githubusercontent.com/1158332/45922995-89b87200-be8e-11e8-9797-8f3f11e67d6e.png)

**Comment by jdumas** [comment]
Are you compiling in 64 bits?

**Comment by larsbrubaker** [comment]
Well that is at least part of the problem. I was definately in 32 bit. I have change to x64 but it is still not working. Do I need to re-run CMake with some other parameters? I can see that it looks like the program is trying to use lots of 32 bit stuff and that will, of coarse, not work.

![image](https://user-images.githubusercontent.com/1158332/45923467-d3f42000-be9b-11e8-8622-009c1c50031c.png)


![image](https://user-images.githubusercontent.com/1158332/45923465-a14a2780-be9b-11e8-9dc0-487b9e637688.png)

Thanks so much for the help. I have spent way too much time on this.

**Comment by jdumas** [comment]
Well the instructions on the [website](http://libigl.github.io/libigl/tutorial/#downloading-libigl) explicitly say that you should compile in 64 bit on Windows. If that still doesn't work from a clean build I cannot guess what's wrong unless you post the error log out here.

**Comment by larsbrubaker** [comment]
Look at that, it's working!

This was the cmake commands that I ran that finally got me to something running:

``` mkdir build64 & pushd build64
cmake -G "Visual Studio 15 2017 Win64" C:\Development\libigl\tutorial
popd
cmake --build build64 --config Release
```

![image](https://user-images.githubusercontent.com/1158332/45924200-c3997080-beae-11e8-95aa-4eaf1f15bd6b.png)

Thanks again!
