### ISSUE TITLE
bumps from igl::signed_distance

### ISSUE THREAD

**Issue by wtholliday** [libigl/libigl#906]
After running `signed_distance` using `SIGNED_DISTANCE_TYPE_PSEUDONORMAL` (`SIGNED_DISTANCE_TYPE_WINDING_NUMBER` is too slow), I get these bumps on my model:

![bumps](https://user-images.githubusercontent.com/841144/45987196-0a10db80-c025-11e8-83dc-32a7ddd24764.png)

What sort of mesh degeneracy could cause this? (I previously removed zero-area triangles from the mesh to get around https://github.com/libigl/libigl/issues/905)

**Comment by jdumas** [comment]
What are you rendering here? Can you post a minimal example with you mesh so we can take a look?

**Comment by wtholliday** [comment]
@jdumas I'm rendering the generated SDF via ray marching. I've attached the mesh I'm using in https://github.com/libigl/libigl/issues/905.

Looks like this is an issue with my mesh because Preview.app has trouble with the vertex normals in the same locations as where the bumps appear:

![bad normals](https://user-images.githubusercontent.com/841144/45988411-a5a54a80-c02b-11e8-9773-f33de08915cc.png)

**Comment by jdumas** [comment]
I don't know how you did you cleanup, but it looks like some triangle got flipped in the process. you could try to run `igl::bfs_orient()` to retrieve a consistently oriented patch.

**Comment by wtholliday** [comment]
@jdumas I tried `bfs_orient` but the bumps persisted. That's consistent with my own code, which validates correct orientation of triangles. The mesh is likely degenerate around those vertices in some other way.

**Comment by alecjacobson** [comment]
could also be self intersections: the surface could be flipped inside out
there. Winding number will get that right, but pseudonormal will be
confused.
-Alec

**Comment by wtholliday** [comment]
Does `igl::marching_cubes` produce meshes suitable for the pseudonormal test? I'm currently using the table from http://paulbourke.net/geometry/polygonise/ to generate my mesh, which produces the faces with bad normals.

**Comment by wtholliday** [comment]
Using `igl::copyleft::marching_cubes` has the same issue.

**Comment by alecjacobson** [comment]
a good implementation should not produce flipped triangles or
self-intersecting mesh, but most implementations can create arbitrarily
poorly shaped triangles.

>

**Comment by alecjacobson** [comment]
The pseudo-normal technique could be improved but it's a fragile method to begin with.

Use `SIGNED_DISTANCE_TYPE_FAST_WINDING_NUMBER` instead.
