### ISSUE TITLE
IglViewer and ImGui

### ISSUE THREAD

**Issue by Enigma-li** [libigl/libigl#909]
Hi,

There seems bugs in igl viewer menu that:

1) the "face-based" options is not working when click on/off, but the shortcut key works well
2) the "centre object" button does not work when pressing

And is there callback functions for ImGui InputFloat or DragFloat item?

**Comment by jdumas** [comment]
Hi,

The first one is a known bug (#757), and I have a pending PR to fix that (#857). For the second one maybe it's also related to #764?

As for the callbacks, there is no need for them, since ImGui uses the immediate mode paradigm:
```cpp
if (ImGui::InputFloat(...)) {
  // do something when the user modifies the field
}
```

Note that you can also use `ImGui::IsItemActive()` and `ImGui::IsItemHovered()` to check whether the last item you drew with ImGui has been active/hovered or whatever.

**Comment by Enigma-li** [comment]
Thanks for your reply.

You are right of face-based visualization (#757) and the callback functions as you said.

But for the "centre object" button, I thing it is a bug in the code:
`IGL_INLINE void igl::opengl::ViewerCore::align_camera_center(
  const Eigen::MatrixXd& V,
  const Eigen::MatrixXi& F)
{
  if(V.rows() == 0)
    return;

  //get_scale_and_shift_to_fit_mesh(V,F,camera_base_zoom,camera_base_translation);
    get_scale_and_shift_to_fit_mesh(V,F,camera_zoom,camera_translation);
  // Rather than crash on empty mesh...
  if(V.size() > 0)
  {
    object_scale = (V.colwise().maxCoeff() - V.colwise().minCoeff()).norm();
  }
}`

when changing the camera zoom and translation, base_ parameters are not used and if we change it to camera_zoom and camera_translation, it works.

Another question is how about "object_scale" used in drawing?

**Comment by jdumas** [comment]
Hmm I'll have to double-check, but the idea is that `camera_base_zoom` and `camera_base_translation` store the base transformation to fit the viewed model into a unit box, while `camera_zoom` and `camera_translation` correspond to the user-interaction on top of it. They are combined to set the view matrix [here](https://github.com/libigl/libigl/blob/274dc2de4535e7a91aac782d088c0ee14c6d3f1e/include/igl/opengl/ViewerCore.cpp#L134).

**Comment by Enigma-li** [comment]
Yes, I saw the code as you pointed. User interaction links to camera_zoom and camera_translation. But the case now seems that the updated value is not applied to drawing functions if we use camera_base zoom and translation.

Is this update_matrices flag not updated to block the usage of camera_base parameters?

**Comment by jdumas** [comment]
Yes that could be the source of the problem. I don't have a lot of time to investigate right now, but I'll flag this as a bug and hopefully come back to it soon.

**Comment by Enigma-li** [comment]
Thanks and I would change it to camera_zoom and translate to use first.

BTW, what the object_scale parameter used for?

  ```
  if(V.size() > 0)
  {
    object_scale = (V.colwise().maxCoeff() - V.colwise().minCoeff()).norm();
  }
```

**Comment by jdumas** [comment]
I have no idea. Looks like it could be removed (@alecjacobson ?).

**Comment by Enigma-li** [comment]
Get it and thanks.

Hope the bug could be fixed and also the face-based visualization.

**Comment by panchagil** [comment]
was the "center object" bug fixed? I have the same problem.
