### ISSUE TITLE
igl::lscm globally flips orientation

### ISSUE THREAD

**Issue by MichaelRabinovich** [libigl/libigl#91]
Hey,

I think there's a bug in igl::lscm, and it globally flips orientation. By that I don't mean that some triangles are flipped in the lscm, but usually all of them.
I found it after seeing that initializing arap with lscm usually works quite bad*. Especially the first iterations seems bad.
- Initializing arap on lscm uv coords generated from a mesh after flipping it's orientation works well.

**Comment by KlintQinami** [comment]
@MichaelRabinovich Have you looked into a way of editing `igl::lscm` so that it preserves mesh orientation?

I do not mean flipping the mesh artificially to undo it but rather having the solution preserve orientation.

**Comment by KlintQinami** [comment]
To add context to Michael's comment, here is what using LSCM as an initial guess for ARAP looks like on the camelhead mesh:
![camelheadpreinv](https://cloud.githubusercontent.com/assets/13695551/17002243/688548c8-4e98-11e6-8203-c881a9e67ad7.png)

Inverting the mesh beforehand (interchanging F.col(0) and F.col(2)) gives
![afterinverting](https://cloud.githubusercontent.com/assets/13695551/17002306/a809b9f2-4e98-11e6-80a2-d60640f486bf.png)

I'll look into a less hacky way to fix this.

**Comment by KlintQinami** [comment]
Changing


```
 64   for (unsigned i=0;i<V_uv.cols();++i)
 65   {
 66     V_uv.col(i) = W_flat.block(V_uv.rows()*i,0,V_uv.rows(),1);
 67   }
```

to

 ```
64   for (unsigned i=0;i<V_uv.cols();++i)
65   {
66     V_uv.col(V_uv.cols()-i-1) = W_flat.block(V_uv.rows()*i,0,V_uv.rows(),1);
67   }
```

does the trick. Here is a comparison of the nose of the camel under all three:

Running LSCM as a guess for ARAP without any changes:
![camelnoseinit](https://cloud.githubusercontent.com/assets/13695551/17003395/c0a9b0d4-4e9d-11e6-954b-4ba1af3a40d8.png)

Running LSCM with flipped faces as a guess for ARAP:
![camelinvefaces](https://cloud.githubusercontent.com/assets/13695551/17003410/d6a0d958-4e9d-11e6-8d2c-30a3294e554f.png)

Running the updated LSCM as a guess for ARAP:
![camelfixed](https://cloud.githubusercontent.com/assets/13695551/17003420/e30c6c20-4e9d-11e6-8658-846fd41ebb7a.png)
