### ISSUE TITLE
Tutorial.md doesn't mention that Boost is required to build the tutorial projects

### ISSUE THREAD

**Issue by neverhood311** [libigl/libigl#912]
To successfully build the tutorial projects, I had to download Boost (v1.68.0) and put it in `C:\Program Files\boost`. This wasn't mentioned in the tutorial, but I think it would be helpful, especially for C++ noobs like me.

**Comment by jdumas** [comment]
Boost is only required to build the examples using CGAL. It shouldn't be a requirement. Maybe you'll get a warning since by default it will try to build and use CGAL.

**Comment by paulkry** [comment]
It is more than a warning, at least for cmake on windows will fail to generate a solution file if you do not deselect the appropriate tutorial.

**Comment by alecjacobson** [comment]
I believe this is now longer an issue as boost is sucked in by cmake. But if it's persisting then please reopen.
