### ISSUE TITLE
Slice a cube with a plane 

### ISSUE THREAD

**Issue by Ajinkya-Nawarkar** [libigl/libigl#913]
Does anyone know if libigl has an implementation of slicing a cube to compute intersection points? 
I'd like to create a grid sampling 3D space with hexahedral elements and slice it with a simple plane equation to get all the points intersecting on each of the cubes in the grid. 

I'm new to libigl but aware that the library doesn't exactly do this and most of the libigl functions deal with triangle or tetrahedral meshes. Are there a sequence of functions in libigl that I could use to achieve this? 

The ultimate goal would be to get an evolving plane that rotates from 0 to 180 degrees and computes all the intersections on the grid at each degree and giving elements on either side of the plane. 

Thanks in advance!

**Comment by jdumas** [comment]
Hi there,

You could try to start with the function `igl::slice_tets()` that does what you want but for a tet-mesh. Maybe you can then adapt it to your current situation (either modify the function to deal with cubes, or split you hexes into tets and discard intersections along the diagonals).

**Comment by alecjacobson** [comment]
[igl::copyleft::cgal::intersect_with_half_space](https://libigl.github.io/dox/namespaceigl_1_1copyleft_1_1cgal.html#acbf85761952ab999a6d3a69e91017ee1)
