### ISSUE TITLE
Will Fast Winding Number for Soups be included?

### ISSUE THREAD

**Issue by neverhood311** [libigl/libigl#914]
I see that an implementation of Fast Winding Number for Clouds is included in LibIgl, but there's no implementation of Fast Winding Number for Soups. Are there any plans to implement that?

**Comment by jdumas** [comment]
Hi,

Code for triangles is already available in a separate repository:
https://github.com/sideeffects/WindingNumber

I don't know if there are any plan to integrate/provide a wrapper in libigl for this specific implementation.

**Comment by alecjacobson** [comment]
this is integrated into libigl now.
