### ISSUE TITLE
Add vertex to mesh

### ISSUE THREAD

**Issue by Hugo-Pereira** [libigl/libigl#915]
Hi Guys,

I have barycentric coordinates on a mesh that I wish to turn into vertices.
I was wondering if there is a simple way to add a vertex to a mesh, while updating the faces. I can think of an algorithm, but I'm just wondering if such a thing already exists :)

Thanks

**Comment by jdumas** [comment]
`V.conservativeResize(new_num_vertices, 3);` ?

**Comment by Hugo-Pereira** [comment]
Forgot to mention, I have a manifold watertight mesh. I need to add vertices to it, update the faces, and keep it a manifold watertight.

**Comment by jiangzhongshi** [comment]
There isn't an existing function for this.
But it should be simple to do.

First, use `conservativeResize` to add the vertex to the bottom of the matrix
Then, add three rows to the bottom of `F`
suppose your original face was `a,b,c`, and the newly added vertex was `d`
Then add `[a b d; b c d; c a d]`

**Comment by Hugo-Pereira** [comment]
That would leave the old triangle on the faces matrix, but I see what you mean :p

I ended up doing something like that, with the extra of detecting if a vertex is lying on top of an edge, in which case I subdivide the two triangles that contain that edge into two new triangles each. I'll try to explain this with an image. Red X marks the new vertex. (warning, mad paint skills ahead)

![image](https://user-images.githubusercontent.com/10086956/46940160-f7a42380-d05f-11e8-8bc5-50a8aaac2a36.png)

**Comment by jdumas** [comment]
Seems like you got it working, so I'll close this.
