### ISSUE TITLE
readPLY probably leaks memory

### ISSUE THREAD

**Issue by jimmyland** [libigl/libigl#919]
Based on just reading over the code, the functions in ply.h do a lot of mallocs (`myalloc`s) and largely don't appear to have corresponding free calls, so e.g. ply_get_element_description allocates for each description and igl::readPLY doesn't appear to free this memory.

**Comment by teseoch** [comment]
there is also no test/tutorial using it

**Comment by qnzhou** [comment]
I can confirm this issue.  Repeatedly reading a ply file does increase the memory consumption over time on mac.

**Comment by jdumas** [comment]
We should consider removing the current dependency on `ply.h` in favor of a more modern implementation, e.g. I've found https://github.com/ddiakopoulos/tinyply which looks neat.

**Comment by jimmyland** [comment]
tinyply is neat but fwiw note that it does not support loading files with a mix of tris and quads currently (when loading lists of lists, it doesn't seem to tell you how long each sub-list is; it wants to assume they are all the same length), though the developer plans to address this for the next version

**Comment by jdumas** [comment]
Libigl's matrix representation also does not map well to hybrid meshes that are a mix of quads and triangles, so I don't expect this will be an issue (in fact, very few libigl functions support quad meshes at all).

**Comment by jdumas** [comment]
I don't think any of the loader is doing that at the moment. And it's not really the job of the loader to triangulate quad faces on read (after all, there are several ways to triangulate a quad face, e.g. you may decide to add a vertex in each quad barycenter to avoid directional bias, etc.).

**Comment by jimmyland** [comment]
ah, you're right that the other loaders do not triangulate on load, but the OBJ loader does return false rather than allow you to incorrectly load a mixed tri/quad file as if it were just a tri file

**Comment by alecjacobson** [comment]
use the std vector std vector version.

**Comment by jdumas** [comment]
And of course there are tons of ply io libraries out there, e.g. look at [this benchmark](https://github.com/mhalber/ply_io_benchmark). There's all single files without dependencies. I guess tinyply may be easier to use (requires fewer loc), but once it's wrapped up it doesn't matter much.

What I'm more worried about is how to integrate it into libigl. The header-only paradigm of libigl doesn't really help here, as you'd need to compile the .c/.cpp part of the dependency. We cannot really move it to the `external/` folder either, as it'd be super annoying to have the `readPLY` be in a subfolder, and have its own module ... (and `read_triangle_mesh` wouldn't work for ply anymore). The last option is to inline every function in the library implementation, to make it possible to use it as a pure header-only library. This may be easier to do with tinyply than with rply ... But this also mean we're less likely to update the lib itself.
