### ISSUE TITLE
List of tutorial build issues and workarounds on Ubuntu 14.04

### ISSUE THREAD

**Issue by dukecyto** [libigl/libigl#93]
Hi,

I just had a chance to build libigl tutorials on Ubuntu 14.04.
I will note some non-documented things I had to do to build it.

1. Make sure to recursively clone the repository
GLEW and GLFW are not in libigl/extern any more. They need to be recursively cloned from nanogui repository

2. Make symlinks to GLEW and GLFW from libigl/extern pointing to nanogui/ext/glew and nanogui/ext/glfw

3. Additionally install libmagick++-dev, libxinerama-dev and libxcursor-dev using apt-get
There might be some other depending packages not included in compile_dependencies_linux.sh

4. Edit main.cpp in libigl/tutorial/407_BiharmonicCoordinates and libigl/tutorial/306_EigenDecomposition, correct include path from igl/Viewer/viewer.h to igl/viewer/Viewer.h

Sorry if all this was due to problems specific to my environment!

Jun Saito

**Comment by dukecyto** [comment]
Oops, I just checked the latest doc, and it does say to clone recursively.

**Comment by alecjacobson** [comment]
Thanks, Jun.

.1. I've put the recursive clone up front in the doc.
.4. Fixed these capitalizations.

What are libmagick++-dev, libxinerama-dev and libxcursor-dev  needed for? Something in nanogui or glfw perhaps?

@danielepanozzo , @schuellc Do you know what's needed for the symlink problem 2. ?

**Comment by danielepanozzo** [comment]
libmagick++-dev, libxinerama-dev and libxcursor-dev are probably some headers needed by glfw and not installed by default by the basic ubuntu installation. It is really unfortunate that the documentation of GLFW is even more vague than ours:

-----
To compile GLFW for X11, you need to have the X11 and OpenGL header packages installed, as well as the basic development tools like GCC and make. For example, on Ubuntu and other distributions based on Debian GNU/Linux, you need to install the xorg-dev and libglu1-mesa-dev packages. The former pulls in all X.org header packages and the latter pulls in the Mesa OpenGL and GLU packages. GLFW itself doesn't need or use GLU, but some of the examples do. Note that using header files and libraries from Mesa during compilation will not tie your binaries to the Mesa implementation of OpenGL.
-----

The symlink problem should not be there, it is not happening to me on a vanilla ubuntu 15.04.
Jun, could you please try to clone the current version and let us know if the symlinks are still necessary?

Thanks!

**Comment by dukecyto** [comment]
2. symlink

I should have clarified that this is the problem in compile_dependencies_linux.sh.
The script changes the dir to ../external/AntTweakBar/src/ and builds it, and then tries to change dir to ../../glfw which definitely does not exist unless you make a symlink manually to nanogui/ext/glfw.

If you have depending packages already installed with apt and do not need to run this script, this is probably not a issue.

**Comment by alecjacobson** [comment]
Sounds like the issues may have been resolved. Is that the case? Can this be closed? Or are there out-standing issues with `compile_dependencies_linux.sh` ?

**Comment by danielepanozzo** [comment]
This is outdated. The current version of libigl builds on linux with no issues.

https://travis-ci.org/libigl/libigl
