### ISSUE TITLE
Using libigl to solve Biharmonic Distance" [Lipman et al.] 

### ISSUE THREAD

**Issue by chengchengxuxu** [libigl/libigl#945]
"Biharmonic Distance" [Lipman et al.] using the ig::cotmatrix, igl::massmatrix and igl::eigs

how can i do it?
Would you mind giving me a reference?
Thank you!

**Comment by alecjacobson** [comment]
If you can read MATLAB code, have a look at:

https://github.com/alecjacobson/gptoolbox/blob/master/mesh/biharmonic_distance.m

It would almost be a line by line translation using libigl.

One caveat is that biharmonic distance needs k Eigen modes of the Laplacian. Our `igl::eigs` can do this, but it starts to get slow/less robust when k gets larger.

**Comment by chengchengxuxu** [comment]
Got it !
Thank you!
