### ISSUE TITLE
Mesh PWN ordering (again) and volume

### ISSUE THREAD

**Issue by borki23** [libigl/libigl#946]
Hello,

I have two very simple mesh. One is a plane and the other one is a pyramid.
I want to use the `igl::copyleft::cgal::mesh_boolean` function to intersect  both of them with a cube. However, I keep getting the message that both mesh are now PWN. 
Yet, in the release build the function still seems to work fine and puts out the intersected mesh.
The debug build will crash due to the corresponding assert in `propagate_winding_numbers.h` .
I can imagine that the plane has an ["open boundary"](https://github.com/libigl/libigl/issues/599) and that this could cause it to crash, even though the plane itself is a valid mesh (error in the code?).
For the pyramide I cannot see why this is the case. I checked every triangle of the pyramide for it's winding order  regarding the neighbour triangles. If I understand the verification part of the [paper ](http://www.cs.columbia.edu/cg/mesh-arrangements/#definitions) in 3.1 correctly, then every edge must have adjacent triangles with opposite winding orders. This should be the case for the pyramide. Hence, I cannot see what I did wrong and assume that there is an error in the code.

I attached the mesh:
[Mesh.zip](https://github.com/libigl/libigl/files/2482479/Mesh.zip)

I also was wondering if there is a way to calculate the volume of a mesh since it is not mentioned in the tutorials. I saw that you can tetrahedralize the interior of a mesh and then there are some functions in `volume.h` which seem to calculate the volume of  a single tetrahedra.

Thanks in advance.

- [x] Windows
- [ ] Mac OS X
- [ ] Linux

**Comment by alecjacobson** [comment]
It appears your pyramid also has an open boundary (it does not have a pass). Therefore it is also _not_ PWN.

You might be interested in the `igl::copyleft::cgal::trim_with_solid` function. This only requires that the mesh used for "trimming" is solid (e.g., your cube). And the other mesh(es) can be whatever (e.g., your plane or pyramid).

(re:volume, it's easier for us if you could open a separate issue per question.)

**Comment by jdumas** [comment]
To compute the volume without creating a tet mesh, you can also use `igl::centroid` (this is confusing I know). See #880 for more details.

**Comment by jdumas** [comment]
No it's on my todo-list :D 

But we need to make an alias/overload. (Although I find the fact that we have both a `igl::centroid` and `igl::barycenter` function is also confusing.)

**Comment by fwilliams** [comment]
We renamed `slice_tets` to `marching_tets`. Can we just rename `centroid` to `signed_volume` and call it a day?

**Comment by alecjacobson** [comment]
We should _**not**_ rename `igl::centroid` because  `igl::centroid` computes _the_ centroid, and optionally also outputs _the_ signed volume, for an _entire_ closed triangle mesh.

`igl::volume` computes the signed volume of each tetrahedron in a volumetric tet-mesh.

`igl::barycenter` computes the barycenter of each simplex in a triangle/tet mesh.

Adding an `igl::signed_volume` which calls `igl::centroid` could be OK, but it will still create confusion with `igl::volume`. My thoughts earlier were that this confusion out-weighed the possible gain and we should look for terminology that would better disambiguate the function names.

**Comment by jdumas** [comment]
Yeah. Having `igl::centroid` and `igl::barycenter` is already confusing. I would use the plural for functions that operate on simplices (`igl::volumes` and `igl::barycenters`) and singular for functions that operate on the whole thing (`igl::signed_volume` and `igl::barycenter`==`igl::centroid`). But that's not easy to distinguish so maybe we should think a bit more about this (e.g. `igl::each_barycenter` or `igl::all_barycenters`).

**Comment by borki23** [comment]
Thank you guys for the quick response. I didn't want to open another issue regarding the volume since it is related to my question, so I added it here. 

@alecjacobson The problem is that I want to "trim" the cube with an arbitrary mesh. Most of the times this mesh is open, i.e. the surface is not closed. Choosing `igl::copyleft::cgal::mesh_boolean` is the easier method  to do that.
I could also trim my mesh with the cube, then cut off the cube at the intersection border and somehow stitch together the remaining cube with the trimmed mesh. I think the way of doing it is:

- Trim the mesh (using use `igl::copyleft::cgal::trim_with_solid`). 
- "Cut" the cube along the intersection border (using `igl::cut_mesh()` ?)
- Stitching the trimmed mesh and the cut cube together(using  `igl::copyleft::cgal::remesh_intersections` ?)

If there is no easier way to do it, is this approach always yielding correct results? 

btw, I just tried `igl::copyleft::cgal::mesh_boolean`  from the build of the current repository and the pyramid. Somehow it is now working.

**Comment by alecjacobson** [comment]
For simple shapes, being on the "left side" or "inside" is well defined. For example a plane or your pyramid. For more complex open shapes, this is not well defined. So in general these types of inputs won't be guaranteed to work correctly with `igl::copyleft::cgal::mesh_boolean`: the inputs must be PWN.

Since you want to trim a solid with a open mesh, you might consider whether (for your cases) you know how to "close" them correctly. For example, you might extend them beyond the bounding box of your solid shape and then close them up "around" that shape. Then you can do a simple intersection.

**Comment by borki23** [comment]
I already thought about your last point. 
Assuming that I know the corner vertices of my mesh and extend them to lie outside the cube. Is it possible to do the closing with `igl::copyleft::cgal::remesh_intersections()` ?
Does this function give me a valid PWN mesh if the open mesh is PWN (except of the open boundary) and which can then be used in `igl::copyleft::cgal::mesh_boolean` ?

**Comment by alecjacobson** [comment]
I don't think `igl::copyleft::cgal::remesh_intersections` does what you think it does. What you'd need is a procedural way to close up your shape. For example you could extend the corners far enough away and then "extrude" the shape in one direction to create a closed surface.

**Comment by borki23** [comment]
Okay, you said that the trimming mesh should be a solid. As far as I understood this means that it is closed. Nevertheless, it is working in each direction, so ended up using two times the `igl::copyleft::cgal::trim_with_solid` function  and combine the resulting volumes. If this approach will fail during my tests I will use the extruding method you mentioned. Thanks a lot.
