### ISSUE TITLE
Error during migration to v2.0

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#948]
I have a repo 

https://github.com/alecjacobson/geometry-processing-shared

Prior to Oct 15 2018, it was successfully that uses libigl as a submodule.

I followed the instructions https://libigl.github.io/rewritten-history/

I first changed libigl to libigl-legacy to have a commit in my repo with the legacy just in case:

https://github.com/alecjacobson/geometry-processing-shared/commit/7ff47d41515b6e38308ad426617f219f9155a659

Then I followed the instructions https://libigl.github.io/rewritten-history/ to add the modern libigl v2.0. This seemed to go well and I pushed:

https://github.com/alecjacobson/geometry-processing-shared/commit/2fdfdeefaac92b8b6eae17c09a1508bc736bf7fc

But now if I try to clone via:

    git clone --recursive https://github.com/alecjacobson/geometry-processing-shared.git

I get this error

```
Cloning into 'geometry-processing-shared'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 30655 (delta 0), reused 3 (delta 0), pack-reused 30650
Receiving objects: 100% (30655/30655), 32.09 MiB | 18.33 MiB/s, done.
Resolving deltas: 100% (667/667), done.
Checking out files: 100% (30550/30550), done.
Submodule 'libigl' (https://github.com/libigl/libigl.git) registered for path 'libigl'
Cloning into '/Users/ajx/Downloads/geometry-processing-shared/libigl'...
remote: Enumerating objects: 34145, done.        
remote: Total 34145 (delta 0), reused 0 (delta 0), pack-reused 34145        
Receiving objects: 100% (34145/34145), 8.44 MiB | 13.92 MiB/s, done.
Resolving deltas: 100% (21048/21048), done.
error: Server does not allow request for unadvertised object 737149498ad3d25ea1a56dc4234a66d2876764ef
Fetched in submodule path 'libigl', but it did not contain 737149498ad3d25ea1a56dc4234a66d2876764ef. Direct fetching of that commit failed.
```

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [x] Mac OS X
- [ ] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by jdumas** [comment]
Looks like you ran into https://libigl.github.io/rewritten-history/#problem-1

**Comment by jdumas** [comment]
I was able to solve your problem by doing the following:

```
git clone https://github.com/alecjacobson/geometry-processing-shared
cd geometry-processing-shared
git submodule deinit libigl
rm -rf libigl
git submodule add --force git@github.com:libigl/libigl.git
```

I guess what happened is that when you updated the submodule from `libigl-legacy` to `libigl` somehow the ref still pointed to an old commit `7371494`, which is not referenced in the new history.

**Comment by jdumas** [comment]
This is the message from `git status` before committing the changes:
```
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   .gitmodules
	modified:   libigl

Submodule changes to be committed:

* libigl 7371494...ed363da:
  Warn: libigl doesn't contain commit 737149498ad3d25ea1a56dc4234a66d2876764ef
```

The warning is normal, because the old ref (7371494) no longer exist on the libigl submodule, but the new ref (ed363da) does.

**Comment by alecjacobson** [comment]
huh. I don't get that warning.

**Comment by alecjacobson** [comment]
But following these steps did fix my problems.

It's strange because this seems to be what I did before. The only difference is that I ran these steps deeper in a submodule recursion: shared is a submodule of another repo and I tried to run these steps in that submodule and push back to shared. 

(closing for now, unless there's more to say).

**Comment by jdumas** [comment]
Maybe the warning is something from a newer version of git? I'm not sure what happened with your nested repo. Git has its mysterious ways sometimes :s
