### ISSUE TITLE
igl::harmonic issue: "Auu should be symmetric if positive definite"

### ISSUE THREAD

**Issue by jinyx728** [libigl/libigl#958]
I'm trying to use igl::harmonic to deform a heart model. But igl::harmonic failed with assertion: 
```
Assertion failed: (is_symmetric(Auu,1.0) && "Auu should be symmetric if positive definite"), function min_quad_with_fixed_precompute, file /Users/kevinjyx/Downloads/libigl/cmake/../include/igl/min_quad_with_fixed.cpp, line 120.
```

I use the same code as tutorial 401, just changing the model and labeling boundary conditions. 

the model is like:
![9507d01f87d9a8cff1451bdcbc7c3751](https://user-images.githubusercontent.com/22089030/47198530-512d8a80-d39f-11e8-8be0-83948b934ab7.png)

Does anyone have similar problems?

**Comment by alecjacobson** [comment]
It could be that you're getting NaNs in your matrix because the mesh quality is poor. Could you post a minimal reproducible example including data?
