### ISSUE TITLE
Question:how to get the data of the parametric mesh from "Tutorial 505-MIQ"?

### ISSUE THREAD

**Issue by arch-tu** [libigl/libigl#962]
[Describe your issue]
505_MIQ generates the quad-mesh,it is in the viewer(use set_UV),could i get the data of the parametric mesh,ie,Vertices or Faces?
#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [ ] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by alecjacobson** [comment]
I can't tell if 505_MIQ got broken recently or if it's been broken for a while. I'll see if it's an easy fix but I'm losing my patience trying to maintain the comiso/ module and it may just spin out into an unsupported repo llike cork/ did.

**Comment by alecjacobson** [comment]
IIRC the 505_MIQ didn't actually construct a quad mesh, just a parametrization and drew a texture of a quad grid on it.
