### ISSUE TITLE
Terminals in Wire Mesh

### ISSUE THREAD

**Issue by twodee** [libigl/libigl#963]
The new wire mesh feature is great. I've been looking at implementing this for a long time, and then I saw Alec's blog post about it. Thank you!

My understanding of the algorithm is that the regular polygons must be pushed away from the endpoints a bit to ensure a reasonable surface. This offset works well for generating wire meshes of solid models.

For networks that have a lot of terminal endpoints, this offset isn't so agreeable. We end up with lots of pointy spears. See https://twodee.org/forothers/pointed.png.

Would it be possible to eliminate this offset when a vertex is connected to the network by only one edge? So that the endcaps are flat? If there's interest but not time, I'm happy to look into implementing it myself and submitting a pull request.

**Comment by jdumas** [comment]
A quick workaround would be to place spheres at the endpoints, and use libigl's boolean to "resolve" the self-intersections (this is already what the code is doing if you pass the option `solid = true`). I personnaly don't really use this feature so I can't comment on usability.

**Comment by alecjacobson** [comment]
@twodee could you describe what you'd like? Flat tops? round tops?

unioning spheres would work but would be quite messy compared to the wire meshes we currently make. If you want round caps it might be better to come up with a procedurally way so it perfectly matches the existing vertex from the edge-parts.

**Comment by alecjacobson** [comment]
yeah, that would do it. To find the vertices with only a single edge, I'd create an array of length #Vertices, initialize it to zero and then iterate over all of the edges, incrementing the counter of each vertex that is touched.
