### ISSUE TITLE
Bug report in ImGuiTraits.h

### ISSUE THREAD

**Issue by Salingo** [libigl/libigl#964]
Hello,
After I upgraded libigl to 2.0 version, there is an error in ImGuiTraits.h when building the project: 

> E0144: a value of type "const char*" cannot be used to initiate an entity of type "char*"

I fixed this issue by using force convert, the modified file is uploaded. (The file format is .txt cause I can't upload .h file)
[ImGuiTraits.txt](https://github.com/libigl/libigl/files/2498907/ImGuiTraits.txt)

My project is built using Visual Studio 2017 on Windows 10.

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [ ] Linux

**Comment by jdumas** [comment]
Hi. I don't see what line you changed in the file you uploaded? Can you paste the diff in a code block o github? (`git diff include/igl/opengl/glfw/imgui/ImGuiTraits.h`).

**Comment by Salingo** [comment]
> Hi. I don't see what line you changed in the file you uploaded? Can you paste the diff in a code block o github? (`git diff include/igl/opengl/glfw/imgui/ImGuiTraits.h`).

Here is the changes, left is original, right is modified code.
![image](https://user-images.githubusercontent.com/15212673/47267564-1c286000-d578-11e8-8e0b-204c184614ce.png)

**Comment by jdumas** [comment]
Hmm this is weird. Are you getting the error in your own codebase, or compiling the tutorials? The CI build on AppVeyor uses Visual Studio 2017, which is why I'm puzzled by the error.

A better fix to the changes you propose would be to change all the `constexpr` back to `const` and avoid doing the `(char *)` cast. Could you try that and see if it works for you?

**Comment by Salingo** [comment]
I got the error in my own project.
I changed `constexpr` to `const`, and another error appear:
![image](https://user-images.githubusercontent.com/15212673/47269051-2e5fc980-d58b-11e8-8262-36b8adc34477.png)

**Comment by Salingo** [comment]
Hi, it works if I change `static constexpr char * format = "foo"`  to `static constexpr char format [] = "foo" `
I already provided a minimal examle for you to check. You can complie the sln using the latest version of VS2017, then this error may occur.
[MME.zip](https://github.com/libigl/libigl/files/2500126/MME.zip)

**Comment by jdumas** [comment]
Thanks! I'll take a look at the minimal example later on my Windows machine. As for this issue, if using `char format []` works then I'd prefer we go for this fix! Do you mind creating a PR for that?

**Comment by Salingo** [comment]
Sure, I already created a PR, It's my pleasure to make a little contribution : )
