### ISSUE TITLE
igl::eigs does not work with complex matrices

### ISSUE THREAD

**Issue by avaxman** [libigl/libigl#967]
igl::eigs should seemingly work with complex matrices, except that the "scalar" is also used for the error variables, and thus it doesn't compile on lines like (85--93):

```
 if(err<conv)
      {
        break;
      }
      if(ray || err<tol)
      {
        eff_sigma = sigma;
        ray = true;
      }
```

**Comment by avaxman** [comment]
Update: I did that just by opening up into a real matrix of twice the size. It's equivalent, but costly... it might be worthwhile to just write a wrapper around these real igl::eigs for that.

**Comment by fwilliams** [comment]
So this is a sort of related question, but why do we have our own `eigs` function? It's just doing Rayleigh quotient iteration which is fairly limited and the code is not super optimized. Eigen comes with an eigenvalue solver, though admittedly the default backend is not super fast. That said, you can use BLAS/LAPACK or even MKL as a backend for speedup. 

If we really want an `eigs` function, is it worth just wrapping whatever Eigen provides?

**Comment by jdumas** [comment]
The Eigen solver is only for dense matrices afaik?

**Comment by avaxman** [comment]
@jdumas yes. It kinda sucks actually that **Eigen** does not have a sparse eigenvalue module.

**Comment by jdumas** [comment]
There is Spectra which is supposed to be pretty good (it has shift inverse mode for small eigenvalues). @teseoch was not happy that it wasn't always as robust as Matlab's function unless you tweak parameters or something, but I don't have any test case at hand for that.

**Comment by jdumas** [comment]
Related discussion: #870

**Comment by avaxman** [comment]
Right. But bear in mind that we do have an issue of compatibility here with complex numbers - so maybe disclaim in the tutorial at least. I can work out a wrapper later if you want (I am busy with putting out libdirectional 1.5 in the next few days...)

**Comment by fwilliams** [comment]
It might be nice to call it something else, e.g. `igl::power_iterations`. Having a function called `eigs` sounds like a great way for somebody to mistake this for a real eigenvalue solver. The documentation does say you should probably use ARPACK but it would be a frustrating bug.

**Comment by jdumas** [comment]
Yes we can put a warning or something in the tutorial for sure. We can have `igl::eigs` and `igl::spectra::eigs` the same way we have `igl::delaunay_triangulation` and `igl::copyleft::cgal::delaunay_triangulation`.

**Comment by alecjacobson** [comment]
we have igl::spectra::eigs now. I haven't tried it with complex but I guess it should work. Feel free to report bugs if you try it.
