### ISSUE TITLE
Color bleeding in the viewer

### ISSUE THREAD

**Issue by avaxman** [libigl/libigl#983]
Consider the following piece of code (that's libdirectional tutorial 303 which is actually already working), when given in the sequence:

```
if ((viewingMode ==ORIGINAL_FIELD)||(viewingMode ==OPTIMIZED_FIELD))
    viewer.data_list[0].set_colors(Eigen::RowVector3d::Constant(3,1.0));
  else{  //curl viewing - currently averaged to the face
    Eigen::VectorXd currCurl = AE2F*(viewingMode==ORIGINAL_CURL ? curlOrig: curlCF);
    igl::jet(currCurl, 0.0,curlMax, CMesh);
    viewer.data_list[0].set_colors(CMesh);
  }
```

Given the sequence ORIGINAL_FIELD -> OPTIMIZED_FIELD -> ORIGINAL_FIELD again, I get the following three images (there is no clear() called; just this update):

<img width="1553" alt="screen shot 2018-10-25 at 17 09 36" src="https://user-images.githubusercontent.com/8985720/47510943-74fa4000-d879-11e8-96e0-1fb850918257.png">
<img width="1495" alt="screen shot 2018-10-25 at 17 09 43" src="https://user-images.githubusercontent.com/8985720/47510976-804d6b80-d879-11e8-8172-e97b4bdfc744.png">
<img width="1412" alt="screen shot 2018-10-25 at 17 09 52" src="https://user-images.githubusercontent.com/8985720/47510979-82afc580-d879-11e8-997a-5ae18a063c23.png">

The last image is supposed to be as white as the first, but there is some color bleeding from the second.

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [ ] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by avaxman** [comment]
I'm at the starting point of libigl 2.0 (I hope):
<img width="2524" alt="screen shot 2018-10-25 at 17 31 01" src="https://user-images.githubusercontent.com/8985720/47512108-cf949b80-d87b-11e8-8c78-04486961a6dd.png">

**Comment by jdumas** [comment]
Yep. Can you try the tip of the `dev` branch? In 2.0 on macOS we messed a bit with the transparency of the windows trying to fix an OpenGL issue on Mojave with GLFW. #953 pushed a better fix in the `dev` branch.

**Comment by avaxman** [comment]
Haven't tried your suggestion yet, but it does the same problem exactly on windows, which makes it unlikely be an openGL problem then? I think indeed maybe something is up with updating ambient vs. diffuse in the viewer. You can actually reproduce it with Directional (formerly known as libdirectional): Tutorial chapter 303 clearly exhibits this when passing from color plots to uniform mesh colors.

**Comment by jdumas** [comment]
Yeah, it's possible there is some state that isn't properly reset. Maybe the bug is also present on Linux. I'll try it whenever I find some time =)

**Comment by avaxman** [comment]
I found out what the problem was: if you use ``set_colors()`` with a single-row color, it does not devise whether it is face- or vertex-based explicitly, but rather update both. If you then move around between color discretization spaces, it will only override one of them, and therefore you can see them both superposed. I solved it in Directional by ``set_face_based(false)`` but maybe it's worthwhile to disclaim the issue.

**Comment by jdumas** [comment]
Yeah I'm not a huge fan of this automatic guessing of face-based vs vertex-based in general (see #777). This is something we ought to clarify (I'd prefer to have two methods `set_vertex_colors` and `set_face_colors`, which could internally call `set_face_based` as appropriate).
