### ISSUE TITLE
Draw spline curve

### ISSUE THREAD

**Issue by Enigma-li** [libigl/libigl#985]
Hi,

Does iglViewer support spline curve drawing? In OpenGL, we have gluNurbsCurve with knots, stride, control points, degrees as input, how to draw spline curve in current configuration?

#### Check all that apply (change to `[x]`)
- [x] Windows
- [x] Mac OS X
- [x] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by jdumas** [comment]
The libigl viewer only supports line segments, so you need to rasterize your splines somehow.

**Comment by Enigma-li** [comment]
You mean just discretise into for example 100 or 1000 points and draw these line segments?

**Comment by jdumas** [comment]
Yep.

**Comment by Enigma-li** [comment]
Seeing that there are some basic drawing primitives cannot be drawn easily, I have one question that why iglViewer choose modern openGL(3.0) instead of glBegin, glEnd?

**Comment by jdumas** [comment]
Because we live in 2018. And more seriously, using core profile OpenGL 3.0 allows one to use additional debugging/profiling tools (renderdoc, NSight, etc.) which are not available with legacy OpenGL.
