### ISSUE TITLE
website\documentation instructions are on the documentation repository?

### ISSUE THREAD

**Issue by avaxman** [libigl/libigl#986]
The documentation for building the website (https://libigl.github.io/website/) refers to the libigl main folder, but are these scripts not meant for the documentation repository?

**Comment by jdumas** [comment]
Hmm the webpage itself does not refer to any particular repository. But we can update to remove the ambiguity.

**Comment by jdumas** [comment]
I've updated the website accordingly. We still need to refresh the content of all the auxiliary pages of course.
