### ISSUE TITLE
Surface of Contact ?

### ISSUE THREAD

**Issue by Randa-Almadhoun** [libigl/libigl#99]
Is it possible to use libigl to find the surface of contact between two 3D models. 
if I have a 3D mesh for an object, and I simulate the FOV of a sensor similar to kinect at a known position (Quadrahedron with known dimensions, position and orientation) , can I find out which surface on that 3D mesh will be exposed by the FOV ?

**Comment by alecjacobson** [comment]
I'm not sure exactly what you mean by "surface of contact". It sounds like you'd like to compute the sub-surface visible to a given point. We do not have a specific function for this. 

I suppose you could implement this by 1) projecting the mesh onto the viewing plane, 2) remeshing its self-intersections (using `igl::remesh_self_intersections` 3) unprojecting back to original positions and then 4) keeping only facets whose barycenters are visible to the point.

**Comment by Randa-Almadhoun** [comment]
Thanks for your suggestion, 
As you mentioned, I want the visible surface of the model exposed by the FOV given its position and orientation.
