### ISSUE TITLE
Transformation per mesh

### ISSUE THREAD

**Issue by Roipo** [libigl/libigl#991]
I want to be able to transform each mesh independently. I understand this is something that should not be part of the viewer (#692), but what is the suggested way of doing it then?

**Comment by jdumas** [comment]
Yep. You can apply your model_matrix before setting each `ViewerData` (on the CPU), or write a custom shader to apply this transformation on the GPU side. I'd suggest the former unless you are performance bound (since it'll be easier to update future versions of the viewer).

**Comment by Roipo** [comment]
Does the former mean to apply the transformation on the CPU and then update the vbo?

**Comment by jdumas** [comment]
If you call `set_mesh()` then ViewerData will update the VBO itself yes.

**Comment by xarthurx** [comment]
@jdumas  I think I'm encountering the "performance bound"...

I have around 50k lines, and visualize with different diameters (varying along the line). 
So for each line, I created a truncated cone, using 16 vertices and 16 faces. 
Now, I have in total meshes with V ~ 800k.

I'm also trying to interactively change the diameters with a slider, thus updating the openGL with `set_mesh()` constantly when dragging the slider. 

This is where I notice "performance bound".

I know nothing about shader language. Are there any other methods that can improve the performance?
Or the shader approach is the only way to go?

**Comment by nsmela** [comment]
I've got a similar issue where I have a large mesh that's difficult to manipulate. The CPU stutters as we rotate, transform, scale, etc. Gauging from the discussion, I was thinking a temporary matrix to manipulate the mesh via shaders and have it set the vertices when the mouse/key is released (and clear the temp matrix).

could we do this by modifying MeshGL.cpp to add:

`uniform mat4 model;`
and 
`gl_Position = model * proj * vec4 (position_eye, 1.0); //proj * view * vec4(position, 1.0);`

 to the mesh_vertex_shader_string? Also, I have no idea how to pass that matrix to the shader. Would anyone be able to please help with that if that's the best way?

**Comment by alecjacobson** [comment]
I've resisted having a model matrix in the viewer because it'd be too tempting for the viewer to expand its scope (and required maintenance) beyond a simple viewer. Users can add a model matrix via their custom shader (which is admittedly quite annoying).
