### ISSUE TITLE
Who did history rewriting?

### ISSUE THREAD

**Issue by elfprince13** [libigl/libigl#992]
Our repo has this one as a submodule, currently at commit 0dd952856fc485e88977c19918f6a13932bdc9dd. Trying to check this commit out from command line git results in:
> error: Server does not allow request for unadvertised object 0dd952856fc485e88977c19918f6a13932bdc9dd
And:
> fatal: reference is not a tree: 0dd952856fc485e88977c19918f6a13932bdc9dd

Checking out master, and grepping shows a new commit has taken its place: 0685feba995d0c740cfb1422c1a529a87fad8389

It's unclear how this happened, but it suggests somebody did a forced push, which is really bad manners for everyone else interacting with this repo.

**Comment by jdumas** [comment]
Hi. This is clearly mentioned on the first page of the [website](https://libigl.github.io/). Please read the dedicated [web page](https://libigl.github.io/rewritten-history/) as to why and how to deal with it.

**Comment by elfprince13** [comment]
Can you also put a big flashing warning in the `README.md` displayed on the github repo?

**Comment by jdumas** [comment]
That sounds reasonable.

**Comment by elfprince13** [comment]
Thanks!
